iterator: read sampling for keys on file boundary
cockroachdb/pebble pull request #1031
Opened 2020-12-22 18:06 UTC by aadityasondhi

Previously, for Iterator.Last(), Iterator.SeekLT() and Iterator.Prev(),
if a key was the first key or the only key in the file, sampling would
skip it as the iterator would have moved past it.

This change checks for both an invalid iterator and an iterator pointing
to the wrong file. It then seeks to the correct file if necessary based
on the direction of `mergingiter`. The tests have been fixed to reflect
this new behavior.

Fixes https://github.com/cockroachdb/pebble/issues/1029.

2020-12-22 18:06 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1031)
<!-- Reviewable:end -->

2020-12-22 22:37 UTC, aadityasondhi commented
Based on benchmarks, it doesn't seem like the edge case handling is having any impact on performance when compared to not handling it.

```
name                old ops/sec  new ops/sec  delta
ycsb/A/values=1024   92.3k ± 1%   92.3k ± 1%   ~     (p=1.000 n=5+5)
ycsb/B/values=1024    419k ± 5%    419k ± 5%   ~     (p=1.000 n=5+5)
ycsb/C/values=1024   1.42M ± 5%   1.42M ± 5%   ~     (p=1.000 n=5+5)
ycsb/D/values=1024    108k ±17%    108k ±17%   ~     (p=1.000 n=5+5)
ycsb/E/values=1024   71.0k ±16%   71.0k ±16%   ~     (p=1.000 n=5+5)
```

```
name              old ops/sec  new ops/sec  delta
ycsb/A/values=64    789k ± 2%    779k ± 6%    ~     (p=0.413 n=4+5)
ycsb/B/values=64   1.18M ± 2%   1.15M ± 6%    ~     (p=0.556 n=4+5)
ycsb/C/values=64   2.76M ± 4%   2.66M ± 6%    ~     (p=0.310 n=5+5)
ycsb/D/values=64    650k ±14%    661k ± 5%    ~     (p=0.841 n=5+5)
ycsb/E/values=64    230k ± 2%    226k ± 5%    ~     (p=0.421 n=5+5)
```

2020-12-22 23:19 UTC, itsbilal requested changes
Looks good so far! Only two major suggestions are around:
1) Adding a test case for First/Next/SeekGE and Merge
2) Making FileInLevel sublevel-aware.

Also the `i.pos` thing should probably be merged in a separate PR before this lands.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1031#-:-MPBjkWtDsMm_-aGdcbt:bj87apy)* status: all files reviewed, 3 unresolved discussions (waiting on @aadityasondhi)

___
*[iterator.go, line 212 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1031#-MPBj-bL50C8wRq-v-dF:-MPBj-bL50C8wRq-v-dG:bkzyfmc) ([raw file](https://github.com/cockroachdb/pebble/blob/e1beccdb0df63082910521ebfc3edff2c2aa616f/iterator.go#L212)):*
> ```Go
> 				var containsKey bool
> 				if file != nil {
> 					if mi.dir == int(iterPosNext) || mi.dir == int(iterPosCurForward) {
> ```

Oops, this crept in in the previous PR. But this should be `i.dir` not `mi.dir`. `mi.dir` does not follow the enum in this file; that one is just a simpler +1/-1. Feel free to do this fix in a separate PR.
___
*[iterator.go, line 219 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1031#-MPBh9ixEN2TEah9WhMP:-MPBh9ixEN2TEah9WhMQ:bhyl9cy) ([raw file](https://github.com/cockroachdb/pebble/blob/e1beccdb0df63082910521ebfc3edff2c2aa616f/iterator.go#L219)):*
> ```Go
> 				}
> 				if !containsKey && (mi.dir == int(iterPosNext) || mi.dir == int(iterPosPrev)) {
> 					if f := i.readState.current.FileInLevel(l, i.cmp, i.key, i.key); f != nil {
> ```

While this works, this isn't sublevel-aware, while `ForEachLevelIter` is. I think it'd be a good idea to pass in `li.level` as-is, and have FileInLevel take advantage of L0Sublevels to find the file in just that sublevel. This might be quite a bit of work. so I might take over this PR after you leave if you aren't able to finish it off.
___
*[testdata/iterator_read_sampling, line 170 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1031#-MPBiLn_7LdByt0_L13Q:-MPBiLn_7LdByt0_L13R:b3zwdl8) ([raw file](https://github.com/cockroachdb/pebble/blob/e1beccdb0df63082910521ebfc3edff2c2aa616f/testdata/iterator_read_sampling#L170)):*
> ```
> 
> # Edge case: For Iterator.Last(), Iterator.SeekLT() and Iterator.Prev(), if the key is the first key of the file or
> # the only key, the iterator moves past the file. Sampling should be able to handle this and seek to the correct file.
> ```

The same case would also apply for First, SeekGE, and Next, for single-keyed files where the only key is a `Merge`. The underlying iterator would have already moved onto the next user key. Might be worth adding a test case for that as well.


<!-- Sent from Reviewable.io -->

2020-12-23 18:35 UTC, aadityasondhi reviewed
I was able to get to 1. but did not get to 2. I also rebased this to the latest changes including the one with `i.pos` rather than `mi.dir`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1031#-:-MPFsJvm01RNdRLjjhIp:bxskcsn)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @aadityasondhi and @itsbilal)

___
*[iterator.go, line 219 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1031#-MPBh9ixEN2TEah9WhMP:-MPFs6qm9vTIN4pLbWLm:b-ne840i) ([raw file](https://github.com/cockroachdb/pebble/blob/e1beccdb0df63082910521ebfc3edff2c2aa616f/iterator.go#L219)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

While this works, this isn't sublevel-aware, while `ForEachLevelIter` is. I think it'd be a good idea to pass in `li.level` as-is, and have FileInLevel take advantage of L0Sublevels to find the file in just that sublevel. This might be quite a bit of work. so I might take over this PR after you leave if you aren't able to finish it off.
</blockquote></details>

Sorry, I did not end up getting to it. You will have to take this over.
___
*[testdata/iterator_read_sampling, line 170 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1031#-MPBiLn_7LdByt0_L13Q:-MPFsHCD8t9QCFK6SmLQ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e1beccdb0df63082910521ebfc3edff2c2aa616f/testdata/iterator_read_sampling#L170)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The same case would also apply for First, SeekGE, and Next, for single-keyed files where the only key is a `Merge`. The underlying iterator would have already moved onto the next user key. Might be worth adding a test case for that as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-23 19:53 UTC, itsbilal reviewed
Sounds good, thanks for your work on this! I can take over the PR from this point onward.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1031#-:-MPFsm2n4JDaCGsgCRe8:bheji9k)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @aadityasondhi and @itsbilal)



<!-- Sent from Reviewable.io -->

2021-02-01 23:31 UTC, closed without merging