record: prototype vectorized I/O in LogWriter
cockroachdb/pebble pull request #1048
Opened 2021-01-10 01:07 UTC by nvanbenschoten

This commit prototypes the use of vectorized I/O (i.e. writev) calls by
the `LogWriter` when flushing multiple blocks at once. Vectorized writes
coalesce the system calls needed to write a collection of discontinuous
buffers to a single file. They can also provide an atomicity win, though
such atomicity is not needed here.

I was pleasantly surprised to see that this does result in a measurable
improvement to latency and throughput in write-heavy workloads (many
writes + large writes). I observed the following improvement on YCSB F
with 16KB writes and 16 worker threads when run on my Mac.
```
$ pebble bench ycsb <dir> --workload=F --concurrency=16 --values=16384 --duration=1m

name             old ops/s    new ops/s    delta
insert_100_16kb     190 ± 1%     196 ± 0%  +2.77%  (p=0.100 n=3+3)

name             old avg(ms)  new avg(ms)  delta
insert_100_16kb    84.0 ± 1%    81.6 ± 0%  -2.86%  (p=0.100 n=3+3)

name             old p99(ms)  new p99(ms)  delta
insert_100_16kb     140 ± 4%     130 ± 3%  -7.01%  (p=0.200 n=3+3)
```

I'm not necessarily expecting that we'll want to make this change. This
was mainly done out of curiosity but the result was interesting enough
that I figured I'd post it.

2021-01-10 01:08 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1048)
<!-- Reviewable:end -->

2021-01-11 15:29 UTC, petermattis reviewed
I'm mildly surprised that this has an affect on throughput and latency. How often is `WriteV` getting used in this workload? How many buffers are being written at once?

> I observed the following improvement on YCSB F with 16KB writes run on my Mac.

Mac fsync performance is really bad which can distort other disk bottlenecks. Would be worthwhile to test this on Linux to sanity check the improvement isn't Mac specific. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1048#-:-MQm2eOABVs-0y188h4a:b-g1uvs7)* status: 0 of 6 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-11 21:30 UTC, nvanbenschoten commented
> Would be worthwhile to test this on Linux to sanity check the improvement isn't Mac specific.

Surprisingly, things are actually even better on Linux. Here are the results when running on an n1-standard-4 instance with a local SSD. I ran with a range of value sizes, but always with 16 writer threads.
```
name             old ops/s    new ops/s    delta
insert_100_1kb    8.79k ± 4%   9.30k ± 3%   +5.77%  (p=0.016 n=5+5)
insert_100_2kb    8.09k ± 2%   8.77k ± 3%   +8.52%  (p=0.008 n=5+5)
insert_100_4kb    7.36k ± 1%   8.08k ± 3%   +9.71%  (p=0.008 n=5+5)
insert_100_8kb    5.13k ± 1%   5.58k ± 1%   +8.81%  (p=0.008 n=5+5)
insert_100_16kb   3.05k ± 1%   3.39k ± 1%  +11.05%  (p=0.008 n=5+5)
insert_100_32kb   1.68k ± 0%   2.18k ± 1%  +30.03%  (p=0.008 n=5+5)

name             old avg(ms)  new avg(ms)  delta
insert_100_1kb     1.84 ± 3%    1.74 ± 3%     ~     (p=0.079 n=5+5)
insert_100_2kb     1.96 ± 3%    1.84 ± 3%   -6.12%  (p=0.048 n=5+5)
insert_100_4kb     2.20 ± 0%    2.00 ± 0%   -9.09%  (p=0.008 n=5+5)
insert_100_8kb     3.10 ± 0%    2.90 ± 0%   -6.45%  (p=0.029 n=4+4)
insert_100_16kb    5.24 ± 1%    4.70 ± 0%  -10.31%  (p=0.008 n=5+5)
insert_100_32kb    9.50 ± 0%    7.36 ± 1%  -22.53%  (p=0.008 n=5+5)

name             old p99(ms)  new p99(ms)  delta
insert_100_1kb     7.30 ± 0%    7.18 ± 2%     ~     (p=0.167 n=5+5)
insert_100_2kb     7.54 ± 5%    7.38 ± 4%     ~     (p=0.484 n=5+5)
insert_100_4kb     7.90 ± 0%    7.82 ± 4%     ~     (p=0.968 n=4+5)
insert_100_8kb     13.6 ± 0%    14.4 ± 5%     ~     (p=0.079 n=4+5)
insert_100_16kb    22.0 ± 0%    23.1 ± 0%   +5.00%  (p=0.008 n=5+5)
insert_100_32kb    30.8 ± 2%    27.9 ± 2%   -9.53%  (p=0.008 n=5+5)
```

Are there any other write-heavy workloads we care about that I can run this on?

> How many buffers are being written at once?

With 16 threads and 16KB writes, I was seeing an average of 5 writes per call to `flushPending`. Given the 32KB block size, this seems to add up. But I do even see WriteV called for very small value sizes and a low concurrency. I wonder if this is right around block boundaries, where we flush one completed block and the prefix of the next block at the same time. Does that sound possible?

2021-01-11 21:42 UTC, petermattis commented
> Surprisingly, things are actually even better on Linux. Here are the results when running on an n1-standard-4 instance with a local SSD. I ran with a range of value sizes, but always with 16 writer threads.

This is nice. That delta for 16 and 32kb values is quite large.

> Are there any other write-heavy workloads we care about that I can run this on?

ycsb/A. 50% updates of 1kb data. I'd expect to see a small single digit improvement on the throughput.

> But I do even see WriteV called for very small value sizes and a low concurrency. I wonder if this is right around block boundaries, where we flush one completed block and the prefix of the next block at the same time. Does that sound possible?

Yeah, that sounds possible.

2021-01-11 23:05 UTC, nvanbenschoten commented
> ycsb/A. 50% updates of 1kb data. I'd expect to see a small single digit improvement on the throughput.

Here are those results:
```
name               old ops/s    new ops/s    delta
ycsb_a_1kb_16conc   9.88k ± 6%  10.05k ± 5%  +1.79%  (p=0.421 n=5+5)
ycsb_a_1kb_48conc   25.0k ± 3%   26.0k ± 2%  +4.14%  (p=0.008 n=5+5)

name               old avg(ms)  new avg(ms)  delta
ycsb_a_1kb_16conc    1.62 ± 7%    1.60 ± 0%    ~     (p=0.968 n=5+4)
ycsb_a_1kb_48conc    1.90 ± 0%    1.84 ± 3%  -3.16%  (p=0.095 n=4+5)

name               old p99(ms)  new p99(ms)  delta
ycsb_a_1kb_16conc    6.46 ±10%    6.72 ±14%    ~     (p=0.778 n=5+5)
ycsb_a_1kb_48conc    6.98 ± 3%    6.78 ± 5%  -2.87%  (p=0.238 n=5+5)
```

2021-01-12 13:49 UTC, petermattis reviewed
These benchmark results are compelling. Some small comments below. This looks relatively straightforward and safe (though probably worth @sumeerbhola, @itsbilal or @jbowens giving this a look as well).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1048#-:-MQqqWJ2Btvmtf_1EG8W:bci97us)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @nvanbenschoten)

___
*[compaction.go, line 418 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQqpci_5gKCrcCqLdbb:-MQqpci_5gKCrcCqLdbc:b-r011zt) ([raw file](https://github.com/cockroachdb/pebble/blob/bb8eff3c226f2cc7b476cb743f9133dcad9571d4/compaction.go#L418)):*
> ```Go
> // WriteV implements the vfs.VectorWriter interface.
> func (c *compactionFile) WriteV(bufs [][]byte) (n int, err error) {
> 	return vfs.WriteV(c.File, bufs)
> ```

I think you should be incrementing `c.written` and call `incrementCompactionBytes` here as is done in `compactionFile.Write`.
___
*[vfs/disk_health.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQqo9kt12bI-EsMgRIJ:-MQqo9kt12bI-EsMgRIK:blzv4mw) ([raw file](https://github.com/cockroachdb/pebble/blob/bb8eff3c226f2cc7b476cb743f9133dcad9571d4/vfs/disk_health.go#L120)):*
> ```Go
> 
> // FD implements the fd interface.
> func (d *diskHealthCheckingFile) Fd() uintptr {
> ```

Should wait for #1049 to go in first and then revert this part of the change.
___
*[vfs/writev.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQqoNF4Bt_UmzU9CWGC:-MQqoNF4Bt_UmzU9CWGD:byivavg) ([raw file](https://github.com/cockroachdb/pebble/blob/bb8eff3c226f2cc7b476cb743f9133dcad9571d4/vfs/writev.go#L15)):*
> ```Go
> // write collections of discontinuous buffers in a single operation.
> type VectorWriter interface {
> 	io.Writer
> ```

Does this need to include the `io.Writer` interface? [`io.WriterAt`](https://golang.org/pkg/io/#WriterAt), which is related to `io.Writer`, doesn't include the `io.Writer` interface.
___
*[vfs/writev.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQqpA4yAsXgf_lWdW87:-MQqpA4yAsXgf_lWdW88:b-mma2aw) ([raw file](https://github.com/cockroachdb/pebble/blob/bb8eff3c226f2cc7b476cb743f9133dcad9571d4/vfs/writev.go#L29)):*
> ```Go
> }
> 
> // WriteV writes writes each of the byte slices to provided Writer, in
> ```

`s/writes writes/writes/g`
`s/to provided/to the provided/g`
___
*[vfs/writev.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQqpOhJ3xPgpm7HelRB:-MQqpOhJ3xPgpm7HelRC:b-1h9xhp) ([raw file](https://github.com/cockroachdb/pebble/blob/bb8eff3c226f2cc7b476cb743f9133dcad9571d4/vfs/writev.go#L43)):*
> ```Go
> 	for _, buf := range bufs {
> 		var m int
> 		m, err = w.Write(buf)
> ```

Should we check that `m == len(buf)` here. If `m < len(buf)` badness will result.


<!-- Sent from Reviewable.io -->

2021-01-13 04:49 UTC, nvanbenschoten reviewed
Thanks for taking a look. After putting this all together, I agree that it is relatively straightforward.

I think the biggest risk is that we aren't handling certain error codes directly from the raw system call, but I adapted a lot of that code from `src/internal/poll/writev.go` in the stdlib (minus the `EAGAIN` handling because this is blocking I/O), so we have some reason to believe it all works. I'm not sure if you saw, but I also switched to linking in the stdlib's `libc_writev_trampoline` call on Darwin, so we'll be using `libSystem`'s `libc_write` [instead of risking the unstable kernel ABI](https://github.com/golang/go/issues/17490).

Do you think we need to add more testing for this? How much confidence does a green build give you? Would a metamorphic test option to disable/enable writev calls be a good idea, or overkill? Do we do any real filesystem-level (not `internal/errorfs`-level) failure injection testing? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1048#-:-MQtxY0T2vM9i8R1bvwp:bpt21qb)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @petermattis)

___
*[compaction.go, line 418 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQqpci_5gKCrcCqLdbb:-MQtw2fZEULhIgZHqB2h:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/bb8eff3c226f2cc7b476cb743f9133dcad9571d4/compaction.go#L418)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think you should be incrementing `c.written` and call `incrementCompactionBytes` here as is done in `compactionFile.Write`.
</blockquote></details>

Done.
___
*[vfs/disk_health.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQqo9kt12bI-EsMgRIJ:-MQtw8L2Ba8wAuZPwR7C:boljb40) ([raw file](https://github.com/cockroachdb/pebble/blob/bb8eff3c226f2cc7b476cb743f9133dcad9571d4/vfs/disk_health.go#L120)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should wait for #1049 to go in first and then revert this part of the change.
</blockquote></details>

I backed it out now. It wasn't needed anymore.
___
*[vfs/writev.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQqoNF4Bt_UmzU9CWGC:-MQtwPVtAW1WGjHiCIP-:bcmqenq) ([raw file](https://github.com/cockroachdb/pebble/blob/bb8eff3c226f2cc7b476cb743f9133dcad9571d4/vfs/writev.go#L15)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does this need to include the `io.Writer` interface? [`io.WriterAt`](https://golang.org/pkg/io/#WriterAt), which is related to `io.Writer`, doesn't include the `io.Writer` interface.
</blockquote></details>

It needs to include `io.Writer` so that the `WriteV` function can fallback to repeated writes if it ever reaches an `io.Writer` impl that isn't also a `VectorWriter`. FWIW this is all modeled after the "extension interface pattern" presented in https://go.googlesource.com/proposal/+/master/design/draft-iofs.md#extensions-to-fs / https://www.youtube.com/watch?t=931&v=yx7lmuwUNv8&feature=youtu.be.
___
*[vfs/writev.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQqpA4yAsXgf_lWdW87:-MQtxENQ2RnDLhZqfG5r:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/bb8eff3c226f2cc7b476cb743f9133dcad9571d4/vfs/writev.go#L29)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/writes writes/writes/g`
`s/to provided/to the provided/g`
</blockquote></details>

Done.
___
*[vfs/writev.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQqpOhJ3xPgpm7HelRB:-MQtxXEY3u7g_-mdaY1E:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/bb8eff3c226f2cc7b476cb743f9133dcad9571d4/vfs/writev.go#L43)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should we check that `m == len(buf)` here. If `m < len(buf)` badness will result.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-13 19:21 UTC, jbowens approved these changes
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

This looks great.

> Would a metamorphic test option to disable/enable writev calls be a good idea, or overkill? 

I'd say that the metamorphic tests are likely to surface any bugs without the test option.

> Do we do any real filesystem-level (not `internal/errorf`s-level) failure injection testing?

I don't think so. We previously did some testing on RocksDB with the `synctest` roachtest. That test used [charybdefs](https://github.com/scylladb/charybdefs), a FUSE filesystem, to inject random errnos. It's been disabled since Pebble was introduced because the injection of `EAGAIN` would confuse the Go runtime into blocking forever. I have a wip branch to fix up that test, but I never finished it.

> Reviewed 8 of 11 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1048#-:-MQx3lrZ4i4DIFpz-5wP:b-5x1s41)* status: all files reviewed, 6 unresolved discussions (waiting on @nvanbenschoten and @petermattis)

___
*[vfs/writev_windows.go, line 11 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQx12ZHEpyjMteokIdM:-MQx12ZHEpyjMteokIdN:b-qw294t) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/vfs/writev_windows.go#L11)):*
> ```Go
> import "os"
> 
> // Will prevents calls to writevFile from writev.go.
> ```

I think this comment needs rephrasing.

maybe just s/prevents/prevent/?


<!-- Sent from Reviewable.io -->

2021-01-13 22:19 UTC, sumeerbhola requested changes
Nice! Some minor comments only.

> Reviewed 8 of 11 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1048#-:-MQxp74aDVXLa3WNaJ_I:b-4yra6s)* status: all files reviewed, 12 unresolved discussions (waiting on @nvanbenschoten and @petermattis)

___
*[internal/record/log_writer.go, line 315 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQxmq7m8fE0fUJLxXGY:-MQxmq7m8fE0fUJLxXGZ:bb062al) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/internal/record/log_writer.go#L315)):*
> ```Go
> 	r.flusher.closed = make(chan struct{})
> 	r.flusher.pending = make([]*block, 0, cap(r.free.blocks))
> 	r.flusher.bufs = make([][]byte, 0, cap(r.free.blocks)+1)
> ```

Could you add a comment that this +1 since the total number of allocated blocks is `cap(r.free.blocks)` plus the block already in `LogWriter.block`.
___
*[internal/record/log_writer.go, line 476 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQxo5Ea4-sRMqcjjkSR:-MQxo5Ea4-sRMqcjjkSS:b-an0mwi) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/internal/record/log_writer.go#L476)):*
> ```Go
> 		bufs = append(bufs, data)
> 	}
> 	switch len(bufs) {
> ```

Do any of the current `LogWriter` unit tests exercise flushing more than a single buf?
___
*[vfs/writev.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQx_FP81zMSxYNYEyrK:-MQx_FP91bdYOBt74RJP:bo2y78s) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/vfs/writev.go#L21)):*
> ```Go
> 	// len(bufs)*len(bufs[..])) and any error encountered that caused the write
> 	// to stop early. WriteV must return a non-nil error if it returns n <
> 	// len(bufs)*len(bufs[..]).
> ```

Does writev have a limit on the number of bytes or the number of slices it can accept, because of the atomicity requirement? I noticed some mention of `IOV_MAX` when searching.
I am asking since it looks like an error here is unrecoverable since we don't know when `n < len(bufs)*len(bufs[..])` the bytes that were written from each slice, so we don't want to do things that will unnecessarily cause errors.
Hmm, it looks like the "in order" part of the comment implies we can retry, as is done in `writevFile`. Never mind.

I think this interface could use a comment that all retryable errors are dealt with in the implementation of `WriteV`.
___
*[vfs/writev_unix.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQxievi6lqujoXgvUsD:-MQxievjEsdi9zdovR74:bpx2a3w) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/vfs/writev_unix.go#L24)):*
> ```Go
> 		if e != syscall.EINTR {
> 			break
> 		}
> ```

if it is EINTR, is `r` guaranteed to be 0, or could some bytes have already been written? Or maybe it does not matter since the over-write in the next attempt is idempotent. A code comment would be helpful.
___
*[vfs/writev_unix_shared.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQxgCvAAqQtQYcmgSs5:-MQxgCvAAqQtQYcmgSs6:b-brn6pl) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/vfs/writev_unix_shared.go#L61)):*
> ```Go
> 			break
> 		}
> 		if n == 0 {
> ```

I don't understand this `n == 0` case. It looks like this can only happen in the first iteration when `wrote` is 0. What about subsequent iterations where nothing new gets written?
___
*[vfs/writev_unix_shared.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQxhMnDDSJNECbcKKNK:-MQxhMnDDSJNECbcKKNL:b-xc83zc) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/vfs/writev_unix_shared.go#L74)):*
> ```Go
> 		ln0 := len(bufs[0])
> 		if ln0 > n {
> 			bufs[0] = bufs[0][n:]
> ```

how about setting `n = 0` here and checking after the loop that `n == 0`, to ensure that we didn't break out of the loop because `bufs` became empty and `n` was still positive.


<!-- Sent from Reviewable.io -->

2021-01-13 23:57 UTC, nvanbenschoten reviewed
Thanks for the reviews!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1048#-:-MQyAJMIAtumPeJftyiE:b-hlc8bm)* status: all files reviewed, 12 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[internal/record/log_writer.go, line 315 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQxmq7m8fE0fUJLxXGY:-MQxusnf-vJ1j6yGsjAP:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/internal/record/log_writer.go#L315)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Could you add a comment that this +1 since the total number of allocated blocks is `cap(r.free.blocks)` plus the block already in `LogWriter.block`.
</blockquote></details>

Done.
___
*[internal/record/log_writer.go, line 476 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQxo5Ea4-sRMqcjjkSR:-MQxvz0s8-SsY4QGbKiy:bwq2r4n) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/internal/record/log_writer.go#L476)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do any of the current `LogWriter` unit tests exercise flushing more than a single buf?
</blockquote></details>

Yes, it seems to be hit by all of the following tests:
- `TestMinSyncInterval`
- `TestMany`
- `TestRandom`
- `TestBasic`
- `TestBoundary`
- `TestRecycleLog`
- `TestTruncatedLog`
- `TestRecycleLogWithPartialRecord`

Out of these, I think `TestBoundary` and its many subtests are the most exhaustive.
___
*[vfs/writev.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQx_FP81zMSxYNYEyrK:-MQxxH8n0JShR8AeYWsz:btes02e) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/vfs/writev.go#L21)):*
> Does writev have a limit on the number of bytes or the number of slices it can accept, because of the atomicity requirement? I noticed some mention of IOV_MAX when searching.

I'm not sure whether there's a limit on the number of total bytes, but there is a number of total iovecs accepted by the call. This seems to be 1024 across all major systems (`IOV_MAX`, like you mentioned). I updated the function to respect this limit and added a test case that fails without the limit. I feel a little bad about hard-coding this instead of reading from `IOV_MAX`, but this is also what the [Go standard library does](https://github.com/golang/go/blob/ba76567bc2500204432ed8a5cb28848410e74447/src/internal/poll/writev.go#L28-L31), so I think it's ok.

> I think this interface could use a comment that all retryable errors are dealt with in the implementation of WriteV.

Done.
___
*[vfs/writev_unix.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQxievi6lqujoXgvUsD:-MQy5GyQ2VTQnsemUbJ7:brwkw2k) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/vfs/writev_unix.go#L24)):*
> if it is EINTR, is r guaranteed to be 0

I believe this is true, otherwise, the call would have returned with a partial success. This code was copied verbatim from `src/internal/poll/fd_writev_unix.go`. It does look like this is safe, as Go repeats syscalls all over the place when it observes `EINTR`. For instance, see uses of `ignoringEINTR`. I added a comment.
___
*[vfs/writev_unix_shared.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQxgCvAAqQtQYcmgSs5:-MQy8_Rj3_518uUf0v0C:b-k5za45) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/vfs/writev_unix_shared.go#L61)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't understand this `n == 0` case. It looks like this can only happen in the first iteration when `wrote` is 0. What about subsequent iterations where nothing new gets written?
</blockquote></details>

Yes, that's correct. This can only happen in the first iteration, otherwise, we shouldn't return an `ErrUnexpectedEOF`. I probably would not have written the code with exactly this structure, but I tried to keep things as close to `src/internal/poll/writev.go` as possible, because I figured diverging would cause more issues than it would solve.
___
*[vfs/writev_unix_shared.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQxhMnDDSJNECbcKKNK:-MQyA5CJ6O7OHfcyFSDi:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/vfs/writev_unix_shared.go#L74)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about setting `n = 0` here and checking after the loop that `n == 0`, to ensure that we didn't break out of the loop because `bufs` became empty and `n` was still positive.
</blockquote></details>

Done.
___
*[vfs/writev_windows.go, line 11 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQx12ZHEpyjMteokIdM:-MQxucOS02z4DaVtCAif:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/1a7793314fbb68c1ae342f74ddc34c7ab3418b56/vfs/writev_windows.go#L11)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think this comment needs rephrasing.

maybe just s/prevents/prevent/?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-14 02:11 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1048#-:-MQyeOe79BESDBGupwCL:bg7igkv)* status: all files reviewed, 13 unresolved discussions (waiting on @jbowens, @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[internal/record/log_writer.go, line 517 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQyc_yJ1cnqCfuYxGvI:-MQyc_yJ1cnqCfuYxGvJ:b-4l8dok) ([raw file](https://github.com/cockroachdb/pebble/blob/df65554c58b579b8b693f27428e35d2cdcae5f18/internal/record/log_writer.go#L517)):*
> ```Go
> 		b.flushed = 0
> 		w.free.blocks = append(w.free.blocks, b)
> 		w.free.cond.Signal()
> ```

was there a particular reason the Signal call was hoisted into the loop?
Seems correct either way, since there should be only a single goroutine waiting in queue().


<!-- Sent from Reviewable.io -->

2021-01-14 02:38 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1048)* status: all files reviewed, 13 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[internal/record/log_writer.go, line 517 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1048#-MQyc_yJ1cnqCfuYxGvI:-MQyjg_26_-WGIMcZNAg:b-jri4ux) ([raw file](https://github.com/cockroachdb/pebble/blob/df65554c58b579b8b693f27428e35d2cdcae5f18/internal/record/log_writer.go#L517)):*
> there should be only a single goroutine waiting in queue

Because I wasn't sure about ^ and wanted to avoid changing the semantics here from what they were, in case doing so led to rare stalls. Do you think I should change this back? Or is it better to not assume only a single caller to queue at this point?


<!-- Sent from Reviewable.io -->

2021-01-14 05:30 UTC, nvanbenschoten commented
So I have some good news and some bad news. I decided to run one more sanity check on these performance numbers because they seemed too good to be true. The good news is that the speedup I measured is real. The bad news is that it isn't due to the use of `writev`. Instead, my tests were picking up a speedup due to a fix for https://github.com/cockroachdb/pebble/issues/1047, which I needed in an earlier version of this prototype but backed out after [this round of comments](https://github.com/cockroachdb/pebble/pull/1048#pullrequestreview-566283288), since @itsbilal fixed it for real.

So in some ways, we did get this speedup, but from https://github.com/cockroachdb/pebble/pull/1049. The speedup was also nothing new, it was actually just fixing a regression from a few months ago. Did the regression make it into v20.2?

The speedup due to `writev` alone seems mostly negligible, so I don't think the change here is worth the added complexity. Unless anyone feels otherwise, I think I'll close this.

2021-01-14 14:21 UTC, petermattis commented
Huh, I'm really surprised that WAL preallocation is having such an effect. I'm pretty sure the regression is present in v20.2. @itsbilal Can you confirm?

2021-01-14 14:21 UTC, petermattis commented
> The speedup due to writev alone seems mostly negligible, so I don't think the change here is worth the added complexity. Unless anyone feels otherwise, I think I'll close this.

Agreed.

2021-01-15 15:29 UTC, sumeerbhola commented
Why did we not notice this regression earlier? Do we not run with this setting in the Pebble nightly benchmarks? Also, eye-balling the blue-lines at https://cockroachdb.github.io/pebble/?detail=readAmp is very fragile wrt noticing regressions.

Regarding the effect of preallocation, we could `Stat` the file in `NewSyncingFile` and then measure how often we end up writing more to the file than the original size (when the original size > 0). We probably want to separate out the stats for the log and sstable paths.

2021-01-15 15:45 UTC, petermattis commented
> Why did we not notice this regression earlier? Do we not run with this setting in the Pebble nightly benchmarks? Also, eye-balling the blue-lines at https://cockroachdb.github.io/pebble/?detail=readAmp is very fragile wrt noticing regressions.

This is a good question. We always run with preallocation. Agreed that the nightly benchmarks are a bit noisy for noticing small regressions. I also suspect that we're not being diligent enough about the regressions which are visible. For example, there were is a perf dip on Sept 25 on `ycsb/A/values=1024`. What was the cause? Perhaps we looked at the time, but we should have added an annotation to explain that dip (or fixed it).

> Regarding the effect of preallocation, we could Stat the file in NewSyncingFile and then measure how often we end up writing more to the file than the original size (when the original size > 0). 

It still surprises me that preallocation is having an effect for WAL writes in the presence of WAL recycling. We should rarely be increasing the size of a WAL in steady state. I would think the only effect of preallocation is to ensure that the WAL is contiguous on disk.

> We probably want to separate out the stats for the log and sstable paths.

I don't think we preallocate on the sstable path. I believe `syncingFile.preallocateBlocks` is set to 0 for sstables. The reason for this is that over allocation isn't too problematic for WALs, but could result in significant wasted space for sstables.

2021-01-15 16:44 UTC, jbowens commented
Should we add a 100% insert workload to the nightly benchmarks too, since that seems to be the workload with the most pronounced unnoticed regression?

> It still surprises me that preallocation is having an effect for WAL writes in the presence of WAL recycling. We should rarely be increasing the size of a WAL in steady state. I would think the only effect of preallocation is to ensure that the WAL is contiguous on disk.

Maybe we're actually seeing the impact of compaction readahead being fixed?

2021-01-15 16:48 UTC, petermattis commented
> Should we add a 100% insert workload to the nightly benchmarks too, since that seems to be the workload with the most pronounced unnoticed regression?

Yeah, I think that would be worthwhile.

> Maybe we're actually seeing the impact of compaction readahead being fixed?

Oh, I keep forgetting about that. Very possible.

2021-01-16 23:34 UTC, closed without merging