vfs: Add fdFileWrapper to re-implement Fd() method on file wrappers
cockroachdb/pebble pull request #1049
Opened 2021-01-11 17:15 UTC by itsbilal

Pebble relies on the existence of an `Fd() uintptr` method on file
handles for some optimizations (eg. WAL preallocation, Prefetch).
However, two of Pebble's own file wrappers used in production,
namely diskHealthCheckingFile and syncingFile, "hide" this
method even if the underlying os.File had it.

This change adds another type, fdFileWrapper, that embeds an "outer"
vfs.File while also reimplementing an Fd() method that bypasses
that outer vfs.File and passes through to the inner file.

Fixes #1047.

2021-01-11 17:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1049)
<!-- Reviewable:end -->

2021-01-11 17:17 UTC, itsbilal commented
Once this is in Cockroach, we'd also have to use this `WithFd` method in `encryptedFile`.

2021-01-12 14:03 UTC, petermattis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1049#-:-MQqu56F3-ngFuxBQY8O:bnfp4nl)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[vfs/fd.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1049#-MQqt4Yx4Oy1md56cqF0:-MQqt4Yx4Oy1md56cqF1:barw0jo) ([raw file](https://github.com/cockroachdb/pebble/blob/80a661f0b25fb871bd20175ea4f84ea3fea2b7ea/vfs/fd.go#L22)):*
> ```Go
> 	// All methods usually pass through to File above, except for Fd(), which
> 	// bypasses it and gets called directly on the inner file.
> 	inner fileWithFd
> ```

Rather than holding on to `fileWithFD`, I think you could store the file descriptor directly here and return it in `Fd()`: `fd uintptr`. This probably doesn't matter, just pointing out this alternative.
___
*[vfs/fd.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1049#-MQmpzVK7mAUM42MiYKV:-MQmpzVL-zLtBvJ5gM6x:bh83ptz) ([raw file](https://github.com/cockroachdb/pebble/blob/80a661f0b25fb871bd20175ea4f84ea3fea2b7ea/vfs/fd.go#L31)):*
> ```Go
> // WithFd takes an inner (unwrapped) and an outer (wrapped) vfs.File,
> // and returns an fdFileWrapper if the inner file has an Fd() method. Use this
> // method to fix the hiding of the Fd() method and the unintentional
> ```

The last sentence in this comment appears to be incomplete.
___
*[vfs/fd_test.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1049#-MQqs_fTB0Zm0tq_SC1F:-MQqs_fTB0Zm0tq_SC1G:b-zgkg8y) ([raw file](https://github.com/cockroachdb/pebble/blob/80a661f0b25fb871bd20175ea4f84ea3fea2b7ea/vfs/fd_test.go#L23)):*
> ```Go
> 	defer os.RemoveAll(dir)
> 
> 	// Skip test if vfs.Default does not return files with Fd() for some reason.
> ```

The code doesn't seem to be checking for the presence of `Fd()`. Nor does there appear to be a call to `t.Skip`. Am I missing something?


<!-- Sent from Reviewable.io -->

2021-01-12 14:24 UTC, sumeerbhola requested changes
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1049)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[vfs/fd.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1049#-MQqxagrBMpYqjs__eLZ:-MQqxagrBMpYqjs__eL_:b-mtf62j) ([raw file](https://github.com/cockroachdb/pebble/blob/80a661f0b25fb871bd20175ea4f84ea3fea2b7ea/vfs/fd.go#L16)):*
> ```Go
> // fdFileWrapper is a File wrapper that also exposes an Fd() method. Used to
> // wrap file wrappers that could unintentionally hide the Fd() method exposed by
> // the root File.
> ```

I found the "Used to wrap file wrappers" and "root File" a bit confusing. I like the "inner (unwrapped)", "outer (wrapped)" terms you use below. Can you hoist part of that comment here.
`fdFileWrapper` is really wrapping both the inner and outer files in a manner that causes the Fd() method to bypass the outer file and directly use the inner file.
___
*[vfs/fd.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1049#-MQqy7971EchclKGe4eL:-MQqy7971EchclKGe4eM:btyyfri) ([raw file](https://github.com/cockroachdb/pebble/blob/80a661f0b25fb871bd20175ea4f84ea3fea2b7ea/vfs/fd.go#L33)):*
> ```Go
> // method to fix the hiding of the Fd() method and the unintentional
> func WithFd(inner, outer File) File {
> 	if f, ok := inner.(fileWithFd); ok {
> ```

If the outer File implements `fileWithFd`, we shouldn't wrap, yes?
___
*[vfs/syncing_file.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1049#-MQqyvML20Na-WcEdVTb:-MQqyvML20Na-WcEdVTc:bu0n9w5) ([raw file](https://github.com/cockroachdb/pebble/blob/80a661f0b25fb871bd20175ea4f84ea3fea2b7ea/vfs/syncing_file.go#L83)):*
> ```Go
> // NB: syncingFile.Write is unsafe for concurrent use!
> func (f *syncingFile) Write(p []byte) (n int, err error) {
> 	_ = f.preallocate(atomic.LoadInt64(&f.atomic.offset) + int64(n))
> ```

can we remove the `+ int64(n)` in light of https://github.com/cockroachdb/pebble/issues/1047#issuecomment-757972175


<!-- Sent from Reviewable.io -->

2021-01-12 16:13 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1049)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[vfs/fd.go, line 10 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1049#-MQrM78o7Etcx50LcSlz:-MQrM78p14YkwTwIO79-:b-n2m1b4) ([raw file](https://github.com/cockroachdb/pebble/blob/80a661f0b25fb871bd20175ea4f84ea3fea2b7ea/vfs/fd.go#L10)):*
> ```Go
> // File related optimizations (eg. Prefetch(), WAL recycling) rely on the
> // existence of the Fd method to return a raw file descriptor.
> type fileWithFd interface {
> ```

It's potentially a little confusing that the `fileWithFd` interface doesn't embed the file interface. Maybe a different name for this interface? Or follow Peter's suggestion below to store the file descriptor directly?


<!-- Sent from Reviewable.io -->

2021-01-12 16:30 UTC, itsbilal reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1049#-:-MQrQpMd7O0P4caH3992:bz5mair)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[vfs/fd.go, line 10 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1049#-MQrM78o7Etcx50LcSlz:-MQrPLqV-ciTO9QJ7y2I:blazh9b) ([raw file](https://github.com/cockroachdb/pebble/blob/80a661f0b25fb871bd20175ea4f84ea3fea2b7ea/vfs/fd.go#L10)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

It's potentially a little confusing that the `fileWithFd` interface doesn't embed the file interface. Maybe a different name for this interface? Or follow Peter's suggestion below to store the file descriptor directly?
</blockquote></details>

Renamed to fdGetter.
___
*[vfs/fd.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1049#-MQqxagrBMpYqjs__eLZ:-MQrLNXFEsjLvF1QBF6H:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/80a661f0b25fb871bd20175ea4f84ea3fea2b7ea/vfs/fd.go#L16)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I found the "Used to wrap file wrappers" and "root File" a bit confusing. I like the "inner (unwrapped)", "outer (wrapped)" terms you use below. Can you hoist part of that comment here.
`fdFileWrapper` is really wrapping both the inner and outer files in a manner that causes the Fd() method to bypass the outer file and directly use the inner file.
</blockquote></details>

Done.
___
*[vfs/fd.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1049#-MQmpzVK7mAUM42MiYKV:-MQrMnE6-I41CVpEJ2rn:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/80a661f0b25fb871bd20175ea4f84ea3fea2b7ea/vfs/fd.go#L31)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The last sentence in this comment appears to be incomplete.
</blockquote></details>

Done.
___
*[vfs/fd.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1049#-MQqy7971EchclKGe4eL:-MQrMpI8CqPOdX1222Cx:bxtjzd7) ([raw file](https://github.com/cockroachdb/pebble/blob/80a661f0b25fb871bd20175ea4f84ea3fea2b7ea/vfs/fd.go#L33)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If the outer File implements `fileWithFd`, we shouldn't wrap, yes?
</blockquote></details>

We shouldn't, but I couldn't find a single wrapper that implemented it so I'm fine with skipping that case entirely. 
___
*[vfs/fd_test.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1049#-MQqs_fTB0Zm0tq_SC1F:-MQrNikN6s3shapgnHf3:bvasr1l) ([raw file](https://github.com/cockroachdb/pebble/blob/80a661f0b25fb871bd20175ea4f84ea3fea2b7ea/vfs/fd_test.go#L23)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The code doesn't seem to be checking for the presence of `Fd()`. Nor does there appear to be a call to `t.Skip`. Am I missing something?
</blockquote></details>

Oops, yes that's from an earlier approach that was unnecessary. Removed.
___
*[vfs/syncing_file.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1049#-MQqyvML20Na-WcEdVTb:-MQrNmYDC78J1BWSJOpo:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/80a661f0b25fb871bd20175ea4f84ea3fea2b7ea/vfs/syncing_file.go#L83)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can we remove the `+ int64(n)` in light of https://github.com/cockroachdb/pebble/issues/1047#issuecomment-757972175
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-13 02:30 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1049#-:-MQt_Aa41YuHmH45UQVY:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @jbowens and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-01-13 14:51 UTC, merged