iterator: fix build merger in iterator with wrong key
cockroachdb/pebble pull request #1055
Opened 2021-01-20 04:41 UTC by glorv

2021-01-20 04:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1055)
<!-- Reviewable:end -->

2021-01-20 06:27 UTC, kennytm commented on iterator_test.go
> +						return bytes.Compare(old, new) * -1
```suggestion
						return bytes.Compare(new, old)
```

2021-01-20 06:48 UTC, glorv commented on iterator_test.go
> +						return bytes.Compare(old, new) * -1
updated

2021-01-22 03:52 UTC, sumeerbhola requested changes
Thanks for finding this bug!

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1055#-:-MRcCrQqBqHDAXSCyjMq:bcnebv3)* status: all files reviewed, 3 unresolved discussions (waiting on @glorv and @kennytm)

___
*[iterator.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1055#-MRc9Nr53mR5iCX_jpe4:-MRc9Nr6EXf2gxe70HZT:b8p3bvk) ([raw file](https://github.com/cockroachdb/pebble/blob/98eaec1fae6604567695743302202128b1df9954/iterator.go#L144)):*
> ```Go
> 
> 		case InternalKeyKindMerge:
> 			// Save the current key.
> ```

Can you adjust this comment to be something like
// The key passed to the Merge type needs to be stable for the duration of the merge. So we save the current key for use there, and also for subsequent use in mergeNext.
___
*[iterator_test.go, line 810 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1055#-MRcBhjj-Bgz2cfxf7-H:-MRcBhjj-Bgz2cfxf7-I:b-af7o5m) ([raw file](https://github.com/cockroachdb/pebble/blob/98eaec1fae6604567695743302202128b1df9954/iterator_test.go#L810)):*
> ```Go
> }
> 
> func TestMerger(t *testing.T) {
> ```

I'm having trouble understanding what this test is trying to do.
I believe it is trying to change its behavior based on the key provided to the `Merge` function. It may be simpler to just concatenate the key to the state kept in the `ValueMerger` and return a merged output that is the `[]byte` equivalent of the string concatenation of "key=" + <key> + "values=" + <value1> + "," <value2> ... It would make it easier to know what the expected behavior should be.


<!-- Sent from Reviewable.io -->

2021-01-22 06:27 UTC, glorv commented
> _[iterator.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1055#-MRc9Nr53mR5iCX_jpe4:-MRc9Nr6EXf2gxe70HZT:b8p3bvk) ([raw file](https://github.com/cockroachdb/pebble/blob/98eaec1fae6604567695743302202128b1df9954/iterator.go#L144)):_
> 
> > ```go
> > 		case InternalKeyKindMerge:
> > 			// Save the current key.
> > ```
> 
> Can you adjust this comment to be something like
> // The key passed to the Merge type needs to be stable for the duration of the merge. So we save the current key for use there, and also for subsequent use in mergeNext.

Updated. Also add a comment for not set `i.value` here like the `InternalKeyKindSet` branch.

> 
> _[iterator_test.go, line 810 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1055#-MRcBhjj-Bgz2cfxf7-H:-MRcBhjj-Bgz2cfxf7-I:b-af7o5m) ([raw file](https://github.com/cockroachdb/pebble/blob/98eaec1fae6604567695743302202128b1df9954/iterator_test.go#L810)):_
> 
> > ```go
> > }
> > 
> > func TestMerger(t *testing.T) {
> > ```
> 
> I'm having trouble understanding what this test is trying to do.
> I believe it is trying to change its behavior based on the key provided to the `Merge` function. It may be simpler to just concatenate the key to the state kept in the `ValueMerger` and return a merged output that is the `[]byte` equivalent of the string concatenation of "key=" + + "values=" + + "," ... It would make it easier to know what the expected behavior should be.

Simplify the merger to only concat each value together with an extra reset to the value if it is the same as the key in building the merger.  Since merge is executed in both flush and iterator, concat key into the value causes the finally value quite long and redundant.

@sumeerbhola  PTAL again, thank you.

2021-01-25 21:51 UTC, sumeerbhola requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1055)* status: all files reviewed, 7 unresolved discussions (waiting on @glorv, @kennytm, and @sumeerbhola)

___
*[iterator.go, line 144 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1055#-MRvTOOV7r3lDdZ5mVR1:-MRvTOOV7r3lDdZ5mVR2:b-1db6rb) ([raw file](https://github.com/cockroachdb/pebble/blob/a244e3aa04f596de79034fe214c40a190ae5cf83/iterator.go#L144)):*
> ```Go
> 
> 		case InternalKeyKindMerge:
> 			// set iter key to new key before building the merge function to ensure the merge key
> ```

nit: Capitalize the letter s in set.
___
*[iterator_test.go, line 786 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1055#-MRvUDFM1P76s2TnwEE-:-MRvUDFM1P76s2TnwEE0:b-wq10bp) ([raw file](https://github.com/cockroachdb/pebble/blob/a244e3aa04f596de79034fe214c40a190ae5cf83/iterator_test.go#L786)):*
> ```Go
> }
> 
> // concatMerger concat key and each value together as a new value
> ```

I don't see it concatenating the key. How about a comment like
// concatMerger concatenates the values together to construct a new value.

And the behavior below is odd in that `MergeNewer` and `MergeOlder` are doing the same thing, so this merger has a result that changes based on whether it is called from old to new or new to old, which should not be the case. I think this test only fiddles with the initial `concatMerger.value` based on the key, so there is nothing key sensitive in this `ValueMerger` itself. We already have an `AppendValueMerger` in `merger.go` that could be reused here. 
___
*[iterator_test.go, line 810 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1055#-MRvU7E-1To4gyF1HVHX:-MRvU7E-1To4gyF1HVHY:best77p) ([raw file](https://github.com/cockroachdb/pebble/blob/a244e3aa04f596de79034fe214c40a190ae5cf83/iterator_test.go#L810)):*
> ```Go
> 		Merger: &Merger{
> 			Merge: func(key, value []byte) (ValueMerger, error) {
> 				// clear the value if equals to key.
> ```

nit: capitalize c in clear.
___
*[iterator_test.go, line 827 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1055#-MRvVZIG5uRb3Fgdq8Oh:-MRvVZIG5uRb3Fgdq8Oi:b-ndqt1n) ([raw file](https://github.com/cockroachdb/pebble/blob/a244e3aa04f596de79034fe214c40a190ae5cf83/iterator_test.go#L827)):*
> ```Go
> 		err = db.Flush()
> 		require.NoError(t, err)
> 	}
> ```

I'm trying to understand this test case.
We have key-value pairs:
(2, 2), (2, 1) from new to old
(1, 1), (1, 0) from new to old

The merger will encounter (2, 2) and so the value 2 will not be included in the initialization of `concatMerger`. Then (2, 1) and the value 1 will be appended. So the result is (2, 1).
Same happens for key 1, where the value 1 is ignored.
Can you add a code comment explaining something like the above?

What is the output without the fix?


<!-- Sent from Reviewable.io -->

2021-02-23 12:54 UTC, glorv commented
@sumeerbhola Sorry for my late reply, I replaced the unit with a new one to make the test clearer, PTAL again, thanks~

2021-03-02 16:58 UTC, sumeerbhola requested changes
sorry about the delay.

> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1055#-:-MUns4um3Sj2I2u8DbRI:bi6tvhx)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @glorv and @sumeerbhola)

___
*[iterator_test.go, line 860 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1055#-MUnrfwWCLaE4DDFi91M:-MUnrfwWCLaE4DDFi91N:b7yaxos) ([raw file](https://github.com/cockroachdb/pebble/blob/451a49d4062cc00da9b0706e06ffcff47e929c11/iterator_test.go#L860)):*
> ```Go
> 	merge([][]byte{{1}, {1}, {2}, {2}, {1}, {2}})
> 	require.Len(t, duplicatedRecords, 1)
> 	require.Equal(t, duplicatedRecords[0], dupRecord{key: []byte{1}, values: [][]byte{{1}, {2}}})
> ```

I'm still somewhat confused by this test: can you clarify the contents of `duplicatedRecords` before you fixed the code in Iterator?


<!-- Sent from Reviewable.io -->

2026-05-18 19:21 UTC, xxmplus commented
Close to due to age

2026-05-18 19:21 UTC, closed without merging