internal/manifest: calculate L0 in-use key ranges using sublevels
cockroachdb/pebble pull request #1153
Opened 2021-05-19 15:01 UTC by jbowens

Use the existing structure of L0 sublevels when calculating in-use key
ranges for L0. The sublevel intervals are already sorted and can be used
to efficiently construct the in-use key ranges. The max interval index
of overlapping intervals allows us to skip over swaths of the keyspace
that are known to be covered.

In a subsequent PR, I'll adapt the setupInuseKeyRange function to use
the in-use bounds of higher levels to seek among files in the lower
levels.

Informs #718.

2021-05-19 15:01 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1153)
<!-- Reviewable:end -->

2021-05-19 18:26 UTC, itsbilal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> great work! The logic seems correct.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1153#-:-Ma4rw5A97R45NAjHpnq:bw850zy)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-05-19 19:42 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1153)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[internal/manifest/l0_sublevels.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1153#-Ma58C4hBB2HZv7puAuj:-Ma58C4i9t-tdqp6kLOc:b-c8576q) ([raw file](https://github.com/cockroachdb/pebble/blob/b810d78080b6ddd045a91e9dc2ad6566080ab1d6/internal/manifest/l0_sublevels.go#L554)):*
> ```
> curr.End = s.orderedIntervals[i+1].startKey.key
> ```

it's not quite clear why we need to do this, given that we have `curr.End = s.orderedIntervals[i+1].startKey.key` below. Perhaps it is the `maxIdx` code path that delays the setting of End. In that case can we consistently delay setting the End until we get to the first interval that does not belong in `curr`?


<!-- Sent from Reviewable.io -->

2021-05-19 21:08 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1153)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1153#-Ma58C4hBB2HZv7puAuj:-Ma5S-KH3LpLkOCecraL:b-vsvdsc) ([raw file](https://github.com/cockroachdb/pebble/blob/b810d78080b6ddd045a91e9dc2ad6566080ab1d6/internal/manifest/l0_sublevels.go#L554)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> ```
> curr.End = s.orderedIntervals[i+1].startKey.key
> ```

it's not quite clear why we need to do this, given that we have `curr.End = s.orderedIntervals[i+1].startKey.key` below. Perhaps it is the `maxIdx` code path that delays the setting of End. In that case can we consistently delay setting the End until we get to the first interval that does not belong in `curr`?
</blockquote></details>

Good catch, it's not needed.


<!-- Sent from Reviewable.io -->

2021-05-20 14:18 UTC, sumeerbhola requested changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1153)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[internal/manifest/l0_sublevels.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1153#-Ma58C4hBB2HZv7puAuj:-Ma95N_e4akomgJK1zxx:b-cb3535) ([raw file](https://github.com/cockroachdb/pebble/blob/b810d78080b6ddd045a91e9dc2ad6566080ab1d6/internal/manifest/l0_sublevels.go#L554)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Good catch, it's not needed.
</blockquote></details>

When we jump to `maxIdx` by setting `i = maxIdx` don't we need to update `curr.End` too?
Which makes me think that the `curr.End = ...` should move after the if-else block and be `curr.End = s.orderedIntervals[i].startKey.key`.
___
*[internal/manifest/testdata/l0_sublevels, line 19 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1153#-Ma96Pz4B29WBwcN8Zce:-Ma96Pz4B29WBwcN8Zcf:bjdgk3b) ([raw file](https://github.com/cockroachdb/pebble/blob/bad92f58a029fed5e37de7ac4bef79d56adbd149/internal/manifest/testdata/l0_sublevels#L19)):*
> ```
> 
> in-use-key-ranges
> a-z
> ```

can you add some more test cases in this file:
- with in-use-key-ranges parameters that have different key spans, so that the binary search to position at start and end gets better exercises. Including some corner cases where the spans align with ordered intervals.
- call in-use-key-ranges for additional sub-levels setup in this file.

I'm being somewhat paranoid here because a bug in this code will cause deleted data to become visible again.


<!-- Sent from Reviewable.io -->

2021-05-20 16:49 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1153)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1153#-Ma58C4hBB2HZv7puAuj:-Ma9N6IR9KKcBieQfQ_S:b-z6ay15) ([raw file](https://github.com/cockroachdb/pebble/blob/b810d78080b6ddd045a91e9dc2ad6566080ab1d6/internal/manifest/l0_sublevels.go#L554)):*
Thanks for that. Since the `filesMaxIntervalIndex` is inclusive and the interval at that index is guaranteed to have a positive file count, I was relying on that next iteration to set `curr.End`. But if `end <= maxIdx`, that iteration won't happen.

> Which makes me think that the curr.End = ... should move after the if-else block and be curr.End = s.orderedIntervals[i].startKey.key.

I think these cases are a little different. In the jump to `maxIdx` case, the interval at `maxIdx` is inclusive, so we want to set it to `s.orderedIntervals[maxIdx+1].startKey.key`. In the increment case, we don't know yet whether 
 the `s.orderedIntervals[i+1]` interval is in-use, so we want to set it that interval's start key.
___
*[internal/manifest/testdata/l0_sublevels, line 19 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1153#-Ma96Pz4B29WBwcN8Zce:-Ma9ae9UEMRl5sBfMxvl:bjjk4k7) ([raw file](https://github.com/cockroachdb/pebble/blob/bad92f58a029fed5e37de7ac4bef79d56adbd149/internal/manifest/testdata/l0_sublevels#L19)):*
> I'm being somewhat paranoid here because a bug in this code will cause deleted data to become visible again.

ack, I appreciate it, and it was warranted!

I fleshed out these test cases.


<!-- Sent from Reviewable.io -->

2021-05-20 18:25 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1153#-:-MaA0feqB4-F6O5OFozW:b-uwkowd)* status: all files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-05-20 20:56 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1153#-:-MaAZEEO08R3Lsv_VJGw:bz5mair)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-05-20 20:57 UTC, merged