db: improve disk usage accounting metrics
cockroachdb/pebble pull request #1157
Opened 2021-05-27 18:57 UTC by jbowens

Improve metrics surrounding disk space usage, by tracking physical WAL
sizes of both live and obsolete WALs, the OPTIONS file and the MANIFEST
file.

Expose a `(*pebble.Metrics).DiskSpaceUsage` function that handles
summing all the disk usage information from within `Metrics` into a
single value.

See cockroachdb/cockroach#56620.

2021-05-27 18:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1157)
<!-- Reviewable:end -->

2021-05-28 13:23 UTC, sumeerbhola requested changes
looks good. some minor comments.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1157#-:-Man8FBkACqy8miNhASV:b-eloy9p)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens)

___
*[db.go, line 1136 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1157#-Man4e9y2rtE_yo_5bja:-Man4e9y2rtE_yo_5bjb:bh5dpib) ([raw file](https://github.com/cockroachdb/pebble/blob/645b10b22070667ea50ae03b0f628408b62758a7/db.go#L1136)):*
> ```Go
> 	metrics.WAL.PhysicalSize = metrics.WAL.Size
> 	if len(d.mu.log.queue) > 0 && metrics.WAL.PhysicalSize < d.mu.log.queue[len(d.mu.log.queue)-1].fileSize {
> 		metrics.WAL.PhysicalSize = d.mu.log.queue[len(d.mu.log.queue)-1].fileSize
> ```

I'm assuming this is because of WAL reuse. Can you add a comment that `DB.atomic.logSize` is what has been written to the WAL in the latest reuse of the file.

Are the queue.fileSize values all from when the file was created/reused or is it ever updated? A comment there would be helpful too. Ah, I see now that it is updated. It still deserves a comment that it could be larger than what has been written to in the latest incarnation.
___
*[db.go, line 1472 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1157#-Man6sq2DVCdumisC4v9:-Man6sq2DVCdumisC4vA:bjgmtfm) ([raw file](https://github.com/cockroachdb/pebble/blob/645b10b22070667ea50ae03b0f628408b62758a7/db.go#L1472)):*
> ```Go
> 
> 			if err == nil {
> 				var finfo os.FileInfo
> ```

I guess `logRecycler.add` could accept a file size, and then we wouldn't need to stat. Not sure if it is worth it. Worth a code comment as a possible future improvement.

Oh, I now see that it does have the file size. Then why do we need to stat here?
___
*[metrics.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1157#-Man81P73jKaW-VmHi13:-Man81P73jKaW-VmHi14:b-sxqv9v) ([raw file](https://github.com/cockroachdb/pebble/blob/645b10b22070667ea50ae03b0f628408b62758a7/metrics.go#L206)):*
> ```Go
> 	private struct {
> 		optionsFileSize  uint64
> 		manifestFileSize uint64
> ```

is there any reason to keep this private?


<!-- Sent from Reviewable.io -->

2021-05-28 17:59 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1157)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)

___
*[db.go, line 1136 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1157#-Man4e9y2rtE_yo_5bja:-Mao1rcP6q18AcwxcE38:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/645b10b22070667ea50ae03b0f628408b62758a7/db.go#L1136)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm assuming this is because of WAL reuse. Can you add a comment that `DB.atomic.logSize` is what has been written to the WAL in the latest reuse of the file.

Are the queue.fileSize values all from when the file was created/reused or is it ever updated? A comment there would be helpful too. Ah, I see now that it is updated. It still deserves a comment that it could be larger than what has been written to in the latest incarnation.
</blockquote></details>

Done.
___
*[db.go, line 1472 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1157#-Man6sq2DVCdumisC4v9:-Mao3j0xBCLxQ-n53yVy:b-qew5i7) ([raw file](https://github.com/cockroachdb/pebble/blob/645b10b22070667ea50ae03b0f628408b62758a7/db.go#L1472)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I guess `logRecycler.add` could accept a file size, and then we wouldn't need to stat. Not sure if it is worth it. Worth a code comment as a possible future improvement.

Oh, I now see that it does have the file size. Then why do we need to stat here?
</blockquote></details>

The comment on `ReuseForWrite` allows for implementations that delete the old file and create a new file, which I think is what the encryption-at-rest code does. I added a comment here explaining the stat and a `TODO` for removing it. I think we can remove it if we add a new return value to `ReuseForWrite` to indicate whether the file was reused, or if we add support for recycling w/ encryption-at-rest (cockroachdb/cockroach#42460).
___
*[metrics.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1157#-Man81P73jKaW-VmHi13:-Mao39on-n5Ved9p72pC:b9et40r) ([raw file](https://github.com/cockroachdb/pebble/blob/645b10b22070667ea50ae03b0f628408b62758a7/metrics.go#L206)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there any reason to keep this private?
</blockquote></details>

I was thinking that it's probably not useful outside of `(*Metrics).DiskSpaceUsage` and we might not want to commit to maintaining exactly these fields in the public interface, in case non-CockroachDB packages start depending on them. I was also hemming and hawing on where to put them within the `Metrics` struct, and this is a cop-out. :)


<!-- Sent from Reviewable.io -->

2021-05-28 20:14 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1157#-:-MaobHVV0SF1Yfa_sMHO:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[metrics.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1157#-Man81P73jKaW-VmHi13:-MaobA_r3JWvdkJrfiuc:bqy67xj) ([raw file](https://github.com/cockroachdb/pebble/blob/645b10b22070667ea50ae03b0f628408b62758a7/metrics.go#L206)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I was thinking that it's probably not useful outside of `(*Metrics).DiskSpaceUsage` and we might not want to commit to maintaining exactly these fields in the public interface, in case non-CockroachDB packages start depending on them. I was also hemming and hawing on where to put them within the `Metrics` struct, and this is a cop-out. :)
</blockquote></details>

Fair enough


<!-- Sent from Reviewable.io -->

2021-06-01 14:47 UTC, jbowens reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1157#-:-Mb71nle9zEJ_juD_rLq:b-814g8k)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-06-01 14:47 UTC, merged