vfs: add OnDiskFull VFS wrapper
cockroachdb/pebble pull request #1164
Opened 2021-06-09 21:34 UTC by jbowens

Add an OnDiskFull VFS function that wraps a vfs.FS with an
implementation that inspects errors from write operations, looking for
errors indicating that the disk is full.

If the FS observes a full disk, it invokes the provided callback,
blocking all incoming writes from proceeding until the callback returns.
The write that encountered the ENOSPC, plus any concurrent writes that
also encountered an ENOSPC all retry their writes exactly once after the
callback completes.

This is intended to be used to automatically manage a ballast file. A
client may remove the ballast file within the callback. The retried
writes will succeed, consuming from the newly available disk space from
the ballast. The callback may also asynchronously trigger processes to
handle the out-of-disk condition, like preventing or slowing incoming
writes.

2021-06-09 21:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1164)
<!-- Reviewable:end -->

2021-06-10 13:44 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1164)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[vfs/disk_full.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-Mbq6uOyAW7SdsBbwhXt:-Mbq6uOyAW7SdsBbwhXu:b73s383) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L22)):*
> ```Go
> // disk space.
> //
> // All new writes to the filesystem are blocked while the callback executes,
> ```

is this blocking necessary, or we could allow them to also see the ENOSPC and de-duplicate invoking the callback?
is the blocking mainly to prevent the (rare?) WAL writes that extend the WAL from seeing this.
___
*[vfs/disk_full.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-Mbq8oWJ6PVnslev7W2D:-Mbq8oWJ6PVnslev7W2E:b-xjfdap) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L96)):*
> ```Go
> 		//   writes, like WAL or MANIFEST fsyncs, are fatal if they encounter
> 		//   an ENOSPC.
> 		generation uint32
> ```

is there a benchmark, say with memFS, showing the overhead when there is no ENOSPC.


<!-- Sent from Reviewable.io -->

2021-06-10 14:22 UTC, sumeerbhola requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1164)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[vfs/disk_full.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbqDbCLEC9YqWvhph9_:-MbqDbCM3NmF-Cm4IP0M:b1q780e) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L81)):*
> ```Go
> 		//       generation is updated indicating that the generation's
> 		//       callback invocation has completed.
> 		// 3. Retry the write once. The callback for the write's generation
> ```

Maybe add a sentence justifying this "retry once".
Something about how we expect that after the callback has properly handled ENOSPC, we wouldn't see ENOSPC for at least a few minutes. And if the callback has not been able to do anything useful, the ENOSPC condition will persist (the FS may be at the boundary of exhaustion so flip back and forth), in which case retrying more than once is not really useful -- without human intervention this system is going to continue to be in a bad state. 
___
*[vfs/disk_full.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbqGKZ7148fVxI8pqh2:-MbqGKZ7148fVxI8pqh3:b370jm0) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L85)):*
> ```Go
> 		//    The write may proceed with the expectation that the full disk
> 		//    has been handled and may retry the write. Any error, including
> 		//    ENOSPC, during the retry is returned without further handling.
> ```

I think worth noting in the comment here that none of the callers retrying will claim the responsibility of invoking the callback.
___
*[vfs/disk_full.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbqEZ2S88ojazyG2wBI:-MbqEZ2S88ojazyG2wBJ:be8vi0b) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L95)):*
> ```Go
> 		// * Incoming writes block if there's an unhandled ENOSPC. Some
> 		//   writes, like WAL or MANIFEST fsyncs, are fatal if they encounter
> 		//   an ENOSPC.
> ```

never mind my earlier question about blocking.
___
*[vfs/disk_full.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbqFl-57rKPOSYGxpXD:-MbqFl-6CnJUffl2px7R:b-mo9tf1) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L114)):*
> ```Go
> // might return ENOSPC. If an ENOSPC was encountered and the corresponding
> // invocation of the `onDiskFull` callback has not yet returned,
> // waitUntilReady blocks until the callback returns.
> ```

could use a code comment stating the invariant that the returned generation is always even.
___
*[vfs/disk_full.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbqGk1i-Q93-tXZGYb3:-MbqGk1i-Q93-tXZGYb4:b-sd94md) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L170)):*
> ```Go
> 	// callback is currently being run by another goroutine or it's already
> 	// completed. Wait for it complete if it hasn't already.
> 	for currentGeneration == gen+1 {
> ```

I don't see what would prevent currentGeneration from being an even higher value, say `gen+3`, which also represents an ENOSPC callback being run, which may be worth waiting for. Though if there are such frequent callbacks it really doesn't help to wait. But still from a code cleanliness perspective should this be waiting until currrentGeneration is even?


<!-- Sent from Reviewable.io -->

2021-06-10 16:59 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1164)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[vfs/disk_full.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbqDbCLEC9YqWvhph9_:-Mbqj-I70w6dbemC_dYu:b-48vilg) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L81)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Maybe add a sentence justifying this "retry once".
Something about how we expect that after the callback has properly handled ENOSPC, we wouldn't see ENOSPC for at least a few minutes. And if the callback has not been able to do anything useful, the ENOSPC condition will persist (the FS may be at the boundary of exhaustion so flip back and forth), in which case retrying more than once is not really useful -- without human intervention this system is going to continue to be in a bad state. 
</blockquote></details>

Good call, done.
___
*[vfs/disk_full.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbqGKZ7148fVxI8pqh2:-MbqiEu4-ebkSoP4oRFz:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L85)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think worth noting in the comment here that none of the callers retrying will claim the responsibility of invoking the callback.
</blockquote></details>

Done.
___
*[vfs/disk_full.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-Mbq8oWJ6PVnslev7W2D:-Mbq_gkxC-n5SO5Z_S8N:b-lrn0ks) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L96)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there a benchmark, say with memFS, showing the overhead when there is no ENOSPC.
</blockquote></details>

Added a targeted benchmark for a call to `Write` on a memFS and ran it with and without `OnDiskFull` wrapping:

```
name           old time/op    new time/op    delta
OnDiskFull-16     363ns ± 6%     367ns ± 4%  +1.10%  (p=0.013 n=21+18)

name           old alloc/op   new alloc/op   delta
OnDiskFull-16     62.9B ±13%     63.3B ±15%    ~     (p=0.094 n=21+20)

name           old allocs/op  new allocs/op  delta
OnDiskFull-16      0.00           0.00         ~     (all equal)
```
___
*[vfs/disk_full.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbqFl-57rKPOSYGxpXD:-MbqW38F4ijCo-wj046p:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L114)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

could use a code comment stating the invariant that the returned generation is always even.
</blockquote></details>

Done.
___
*[vfs/disk_full.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbqGk1i-Q93-tXZGYb3:-Mbqj4UoB1LNy36AFADq:b-a65fxa) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L170)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't see what would prevent currentGeneration from being an even higher value, say `gen+3`, which also represents an ENOSPC callback being run, which may be worth waiting for. Though if there are such frequent callbacks it really doesn't help to wait. But still from a code cleanliness perspective should this be waiting until currrentGeneration is even?
</blockquote></details>

Yeah, `currentGeneration` may be an even higher value. I was a little wary of continuing to wait here since if we're continuously unlucky, we may block an unbounded number of generations.

Waiting is unlikely to be helpful if we're continuously encountering ENOSPC, but bubbling the error up _might_ help if we can abort a large compaction that may have started before we began being more selective in compaction picking. Thoughts? If that logic makes sense to you too, I can document it here.


<!-- Sent from Reviewable.io -->

2021-06-11 14:27 UTC, sumeerbhola requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1164)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[vfs/disk_full.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-Mbq8oWJ6PVnslev7W2D:-MbvOmW7CG5XD3NRnkaR:b-zcjvte) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L96)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Added a targeted benchmark for a call to `Write` on a memFS and ran it with and without `OnDiskFull` wrapping:

```
name           old time/op    new time/op    delta
OnDiskFull-16     363ns ± 6%     367ns ± 4%  +1.10%  (p=0.013 n=21+18)

name           old alloc/op   new alloc/op   delta
OnDiskFull-16     62.9B ±13%     63.3B ±15%    ~     (p=0.094 n=21+20)

name           old allocs/op  new allocs/op  delta
OnDiskFull-16      0.00           0.00         ~     (all equal)
```
</blockquote></details>

Thanks
___
*[vfs/disk_full.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbqGk1i-Q93-tXZGYb3:-MbvOwfw28zJDoeRVuMt:b-mzv7al) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L170)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, `currentGeneration` may be an even higher value. I was a little wary of continuing to wait here since if we're continuously unlucky, we may block an unbounded number of generations.

Waiting is unlikely to be helpful if we're continuously encountering ENOSPC, but bubbling the error up _might_ help if we can abort a large compaction that may have started before we began being more selective in compaction picking. Thoughts? If that logic makes sense to you too, I can document it here.
</blockquote></details>

This makes sense. Can you add a code comment about it.
___
*[vfs/disk_full_test.go, line 19 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbvRTu08LlOmYfbMoyf:-MbvRTu1EQ9vbDBMDPia:b10ca2m) ([raw file](https://github.com/cockroachdb/pebble/blob/ac3434d70e0d53c12083e6048e48a63255a02ca1/vfs/disk_full_test.go#L19)):*
> ```Go
> 	"github.com/stretchr/testify/require"
> )
> ```

Nice tests!
___
*[vfs/disk_full_test.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbvRJDlB2psQriHj7K1:-MbvRJDlB2psQriHj7K2:b-d93b7a) ([raw file](https://github.com/cockroachdb/pebble/blob/ac3434d70e0d53c12083e6048e48a63255a02ca1/vfs/disk_full_test.go#L56)):*
> ```Go
> 			require.NoError(t, fn(fs))
> 			require.Equal(t, 1, callbackInvocations)
> 			// There inner filesystem should be invoked twice, because of the
> ```

s/There/The/
___
*[vfs/disk_full_test.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbvSD2CB_GCV_rvTw7g:-MbvSD2CB_GCV_rvTw7h:b-kaedxl) ([raw file](https://github.com/cockroachdb/pebble/blob/ac3434d70e0d53c12083e6048e48a63255a02ca1/vfs/disk_full_test.go#L134)):*
> ```Go
> 	wg.Wait()
> 	// Since all operations should start before the first one returns an
> 	// ENOSPC, the callback should only be invoked once.
> ```

I didn't quite follow this comment. The part about "all operations should start before the first one returns" is because of the opDelay, yes?
If the others did not start before the first one returned there would still be only 1 call that received ENOSPC -- should `innerFS.atomic.enospcs` be set to 10 so they all receive  ENOSPC and only one claims the callback? This would mean doing the `maybeENOSPC` call before sleeping for `opDelay` and then returning the error.


<!-- Sent from Reviewable.io -->

2021-06-11 17:36 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1164)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[vfs/disk_full.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbqGk1i-Q93-tXZGYb3:-Mbw4cSd5xCDCrU9URrs:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/956a03ddf132f3d719ba3d21befa3d77f03f7b62/vfs/disk_full.go#L170)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This makes sense. Can you add a code comment about it.
</blockquote></details>

Done.
___
*[vfs/disk_full_test.go, line 19 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbvRTu08LlOmYfbMoyf:-Mbw4qkz9OBIEdmAzq0f:bvtk9y9) ([raw file](https://github.com/cockroachdb/pebble/blob/ac3434d70e0d53c12083e6048e48a63255a02ca1/vfs/disk_full_test.go#L19)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Nice tests!
</blockquote></details>

Thanks :)
___
*[vfs/disk_full_test.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbvRJDlB2psQriHj7K1:-Mbw5cnd4N8HYNV6P5eq:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/ac3434d70e0d53c12083e6048e48a63255a02ca1/vfs/disk_full_test.go#L56)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/There/The/
</blockquote></details>

Done.
___
*[vfs/disk_full_test.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1164#-MbvSD2CB_GCV_rvTw7g:-Mbw7bYFAzCzWJL_adQg:b1pgprh) ([raw file](https://github.com/cockroachdb/pebble/blob/ac3434d70e0d53c12083e6048e48a63255a02ca1/vfs/disk_full_test.go#L134)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't quite follow this comment. The part about "all operations should start before the first one returns" is because of the opDelay, yes?
If the others did not start before the first one returned there would still be only 1 call that received ENOSPC -- should `innerFS.atomic.enospcs` be set to 10 so they all receive  ENOSPC and only one claims the callback? This would mean doing the `maybeENOSPC` call before sleeping for `opDelay` and then returning the error.
</blockquote></details>

Thanks, yeah, I'm not sure what I was trying to do here. Updated with your suggestion.


<!-- Sent from Reviewable.io -->

2021-06-14 14:53 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1164#-:-McA-nbg3TMyiCDe3pop:bg7igkv)* status: all files reviewed, 10 unresolved discussions (waiting on @itsbilal and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-06-14 21:51 UTC, jbowens reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1164#-:-McBVUzlAdKYSiNpQizo:b-814g8k)* status: all files reviewed, 10 unresolved discussions (waiting on @itsbilal and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-06-14 21:51 UTC, merged