sstable: Update Reader to isolate and report corruption
cockroachdb/pebble pull request #1180
Opened 2021-06-30 21:50 UTC by itsbilal

If an sstable reader comes across corruption, whether through
mismatching sizes or checksums or something else, it now
calls a CorruptionReporter method if a CorruptionReportingOpt
was specified upon creation. If this corruption was observed
in a data block, it tries to isolate it more narrowly than
the file's bounds if possible (and if not, it reports the
entire file's bounds as corrupt).

Currently only used in tests, but eventually this will thread
into Cockroach.

2021-06-30 21:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1180)
<!-- Reviewable:end -->

2021-07-09 17:12 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1180)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[sstable/reader.go, line 314 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MeB81Ir8iCBsWPeRUdC:-MeB81Ir8iCBsWPeRUdD:b-a1hjzc) ([raw file](https://github.com/cockroachdb/pebble/blob/e651623e8e6f1011816618cd070beca46ae8d5a7/sstable/reader.go#L314)):*
> ```Go
> }
> 
> func (i *singleLevelIterator) maybeReportDataBlockCorruption() {
> ```

I'm wondering whether we should be doing such changes to iterator state in the iterator that is being used for normal reads (or compactions).
And we'll be doing this repeatedly for a file where we have already narrowed the corruption, which is not necessary.

We don't need to report the actual bounds immediately, I think. We could maintain a bit in the FileMetadata for files that are already known to be corrupt, and have had their corruption bounds reported. And we could maintain a de-duped queue of files for whom corruption has been noticed but corruption bounds not computed. Then a background thread could iterate through the blocks of a file, looking for which block is corrupt. And that iteration for finding corruption could be simpler and not a normal iterator, say like what we do in `Layout.Describe`, since its state can be quite simple given it is just doing coordinated forward iteration across all the index levels and the data blocks. It would maintain (key interval for top-level index, key interval for second-level index (when not corrupt), data block). The top-level index key interval would have the file's lower bound as the start key for the first index entry and for subsequent ones the previous index entry. By maintaining these key intervals, it would immediately be able to compute the scope of the corruption.
And it could find all the places the file was corrupt, and not just what happened to be read by the iterator that first encountered some corruption.

The FileMetadata bit would be used to not include these files in compactions. Eventually a higher layer would add a "masked span" (which would get assigned a seqnum) and a corresponding range deletion which would tell Pebble that it can skip over the masked data during compactions (I think this is mostly consistent with the comment in https://docs.google.com/document/d/1fFlO6ARtolczS6mvOTh4JWPfq5PllKDRn6M3m99V80o/edit?disco=AAAAICphiww)


<!-- Sent from Reviewable.io -->

2021-07-15 15:31 UTC, itsbilal commented
___
*[sstable/reader.go, line 314 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MeB81Ir8iCBsWPeRUdC:-MeekyMA9mA6wa_WnZjN:bzihnw3) ([raw file](https://github.com/cockroachdb/pebble/blob/e651623e8e6f1011816618cd070beca46ae8d5a7/sstable/reader.go#L314)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm wondering whether we should be doing such changes to iterator state in the iterator that is being used for normal reads (or compactions).
And we'll be doing this repeatedly for a file where we have already narrowed the corruption, which is not necessary.

We don't need to report the actual bounds immediately, I think. We could maintain a bit in the FileMetadata for files that are already known to be corrupt, and have had their corruption bounds reported. And we could maintain a de-duped queue of files for whom corruption has been noticed but corruption bounds not computed. Then a background thread could iterate through the blocks of a file, looking for which block is corrupt. And that iteration for finding corruption could be simpler and not a normal iterator, say like what we do in `Layout.Describe`, since its state can be quite simple given it is just doing coordinated forward iteration across all the index levels and the data blocks. It would maintain (key interval for top-level index, key interval for second-level index (when not corrupt), data block). The top-level index key interval would have the file's lower bound as the start key for the first index entry and for subsequent ones the previous index entry. By maintaining these key intervals, it would immediately be able to compute the scope of the corruption.
And it could find all the places the file was corrupt, and not just what happened to be read by the iterator that first encountered some corruption.

The FileMetadata bit would be used to not include these files in compactions. Eventually a higher layer would add a "masked span" (which would get assigned a seqnum) and a corresponding range deletion which would tell Pebble that it can skip over the masked data during compactions (I think this is mostly consistent with the comment in https://docs.google.com/document/d/1fFlO6ARtolczS6mvOTh4JWPfq5PllKDRn6M3m99V80o/edit?disco=AAAAICphiww)
</blockquote></details>

The interaction with the eventual range tombstone is going to be an important piece. My thought process when coding this up was to leave the deduplication / span-of-keys to Cockroach and to keep the pebble side simple, but maybe Pebble is the right place to track "corrupt spans" or "corrupt files" to some extent in general, for the eventual range tombstone compaction / deletion. I'll try putting this into FileMetadata (but not serializing it into the manifest) and see how this goes.


<!-- Sent from Reviewable.io -->

2021-07-15 15:41 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1180)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[sstable/reader.go, line 314 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MeB81Ir8iCBsWPeRUdC:-MeenaxY3FZ1emyOkpPK:b-5uvu7z) ([raw file](https://github.com/cockroachdb/pebble/blob/e651623e8e6f1011816618cd070beca46ae8d5a7/sstable/reader.go#L314)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The interaction with the eventual range tombstone is going to be an important piece. My thought process when coding this up was to leave the deduplication / span-of-keys to Cockroach and to keep the pebble side simple, but maybe Pebble is the right place to track "corrupt spans" or "corrupt files" to some extent in general, for the eventual range tombstone compaction / deletion. I'll try putting this into FileMetadata (but not serializing it into the manifest) and see how this goes.
</blockquote></details>

If we set that aside for a moment, what I would like to see is a `Reader.FindCorruptSpans` method, with a specialized implementation that does not use `singleLevelIterator`, `twoLevelIterator`. My intuition is that it would be clearer to understand (despite more code in total), and more comprehensive, but I could easily be wrong. A quick prototype should help resolve this one way or another.


<!-- Sent from Reviewable.io -->

2021-07-27 15:29 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1180)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

___
*[sstable/reader.go, line 314 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MeB81Ir8iCBsWPeRUdC:-Mfc_HKB-6EHQxXPpfMz:bx80h7) ([raw file](https://github.com/cockroachdb/pebble/blob/e651623e8e6f1011816618cd070beca46ae8d5a7/sstable/reader.go#L314)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If we set that aside for a moment, what I would like to see is a `Reader.FindCorruptSpans` method, with a specialized implementation that does not use `singleLevelIterator`, `twoLevelIterator`. My intuition is that it would be clearer to understand (despite more code in total), and more comprehensive, but I could easily be wrong. A quick prototype should help resolve this one way or another.
</blockquote></details>

I prototyped this up - thanks for that suggestion! It does seem more understandable this way. Things I still need to tackle are tests for manifest.Spans, as well as a way to prevent goroutine leakage, but other than that this is good to review. 


<!-- Sent from Reviewable.io -->

2021-08-03 21:02 UTC, sumeerbhola requested changes
> Reviewed 3 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1180)* status: 3 of 8 files reviewed, 7 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/manifest/spans.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MgCniWk55oPBB7kIQu2:-MgCniWk55oPBB7kIQu3:bvxwfax) ([raw file](https://github.com/cockroachdb/pebble/blob/538aae4811db30fb943ddbc35b2d7f2acf18df1a/internal/manifest/spans.go#L34)):*
> ```Go
> 
> // Add merges the new span into the set of spans. If this span already existed
> // in the span set, added is false, otherwise it's true.
> ```

It's not clear why we need an incremental Add method.
It would be simpler to have two methods: Add and Finish. Add would append to a slice of spans. Finish would sort, and then walk the spans and coalesce.
___
*[sstable/reader.go, line 2083 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MgCo3b44WQQZ2qTFOT3:-MgCo3b44WQQZ2qTFOT4:bf2hp96) ([raw file](https://github.com/cockroachdb/pebble/blob/538aae4811db30fb943ddbc35b2d7f2acf18df1a/sstable/reader.go#L2083)):*
> ```Go
> 		}
> 		r.fileMeta.Mu.Lock()
> 		r.fileMeta.Mu.CorruptSpans.Add(spanToAdd)
> ```

why not assign instead of adding?
___
*[sstable/reader.go, line 2256 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MgCoArU78D9OhF4jgZA:-MgCoArU78D9OhF4jgZB:b-vbwqei) ([raw file](https://github.com/cockroachdb/pebble/blob/538aae4811db30fb943ddbc35b2d7f2acf18df1a/sstable/reader.go#L2256)):*
> ```Go
> 			bh, n := decodeBlockHandle(value)
> 			if n == 0 || n != len(value) {
> 				spans.Add(fullFileSpan)
> ```

we could narrow this based on key and the previous key, yes?
I suppose it was an explicit choice not to, since the block handle is corrupt so maybe the keys are too. Could you add a code comment.
___
*[sstable/reader.go, line 2270 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MgCoQJP5sE5Xbxef-ZL:-MgCoQJP5sE5Xbxef-ZM:b9lxjun) ([raw file](https://github.com/cockroachdb/pebble/blob/538aae4811db30fb943ddbc35b2d7f2acf18df1a/sstable/reader.go#L2270)):*
> ```Go
> 			}
> 
> 			subIndex, err := r.readBlock(indexBH, nil /* transform */, nil /* readaheadState */)
> ```

A corrupt second level index block can be scoped narrowly based on the the keys in topIter.
___
*[sstable/reader.go, line 2281 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MgCoYOj8EdAcQ2nmvFM:-MgCoYOj8EdAcQ2nmvFN:b-duc46) ([raw file](https://github.com/cockroachdb/pebble/blob/538aae4811db30fb943ddbc35b2d7f2acf18df1a/sstable/reader.go#L2281)):*
> ```Go
> 				dataBH, n := decodeBlockHandle(value)
> 				if n == 0 || n != len(value) {
> 					spans.Add(fullFileSpan)
> ```

same comment
___
*[sstable/reader.go, line 2300 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MgCjEjc5eQfs0VDDFu3:-MgCiuKHAVd8IpQOrsIG:bbdvjo1) ([raw file](https://github.com/cockroachdb/pebble/blob/538aae4811db30fb943ddbc35b2d7f2acf18df1a/sstable/reader.go#L2300)):*
> ```Go
> 			foundCorruptBlock = true
> 		} else if err != nil {
> 			return spans, nil
> ```

swallowing an error seems bad


<!-- Sent from Reviewable.io -->

2021-09-13 16:03 UTC, itsbilal reviewed
TFTR! Addressed the comments. I've yet to add a test for the second-level-index-block-corrupt case, but I'll look into that shortly.

> Dismissed @sumeerbhola from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1180#-:-MjUtWpU0fCkzcs-PEAD:bmzmtca)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/manifest/spans.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MgCniWk55oPBB7kIQu2:-MjUi58iEBP4o-YsRwVP:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/538aae4811db30fb943ddbc35b2d7f2acf18df1a/internal/manifest/spans.go#L34)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It's not clear why we need an incremental Add method.
It would be simpler to have two methods: Add and Finish. Add would append to a slice of spans. Finish would sort, and then walk the spans and coalesce.
</blockquote></details>

Done.
___
*[sstable/reader.go, line 2083 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MgCo3b44WQQZ2qTFOT3:-MjUjA-t66iuWy_kTzpi:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/538aae4811db30fb943ddbc35b2d7f2acf18df1a/sstable/reader.go#L2083)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why not assign instead of adding?
</blockquote></details>

Done.
___
*[sstable/reader.go, line 2256 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MgCoArU78D9OhF4jgZA:-Mj0rfrwCEjiL_yOxW_F:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/538aae4811db30fb943ddbc35b2d7f2acf18df1a/sstable/reader.go#L2256)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we could narrow this based on key and the previous key, yes?
I suppose it was an explicit choice not to, since the block handle is corrupt so maybe the keys are too. Could you add a code comment.
</blockquote></details>

Done.
___
*[sstable/reader.go, line 2270 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MgCoQJP5sE5Xbxef-ZL:-MjUs_HZBTY8rI3LTLU1:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/538aae4811db30fb943ddbc35b2d7f2acf18df1a/sstable/reader.go#L2270)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

A corrupt second level index block can be scoped narrowly based on the the keys in topIter.
</blockquote></details>

Done.
___
*[sstable/reader.go, line 2281 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MgCoYOj8EdAcQ2nmvFM:-MjUsZxOAmvob_8GFjej:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/538aae4811db30fb943ddbc35b2d7f2acf18df1a/sstable/reader.go#L2281)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same comment
</blockquote></details>

Done.
___
*[sstable/reader.go, line 2300 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MgCjEjc5eQfs0VDDFu3:-MjUm3jlB99ySU36c2qW:belvumw) ([raw file](https://github.com/cockroachdb/pebble/blob/538aae4811db30fb943ddbc35b2d7f2acf18df1a/sstable/reader.go#L2300)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

swallowing an error seems bad
</blockquote></details>

I don't swallow it anymore, but it's still not logged as a BackgroundError anywhere. Do you think we should do that?


<!-- Sent from Reviewable.io -->

2021-09-21 18:57 UTC, bananabrick reviewed
Nice! Since I'll be working on the remaining Pebble side of this project, I've left a review.

> Reviewed 1 of 8 files at r3, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1180#-:-Mje61eP9X415plYBXDg:bqnfecd)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/manifest/spans.go, line 64 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1180#-Mje7RHq751Xv6zja-0y:-Mje7RHq751Xv6zja-0z:b-vfef20) ([raw file](https://github.com/cockroachdb/pebble/blob/c52dd2ecafdc2978449d66f933b2653709027dc9/internal/manifest/spans.go#L64)):*
> ```Go
> 		}
> 		// Cases 1 and 2. Delete RHS span. Note that we do *not* increment i.
> 		n := copy(s.spans[i:], s.spans[i+1:])
> ```

It probably doesn't matter, but I think we can avoid the copies here on almost every execution of the loop, and maybe simplify the logic.

1. In the case of no overlap, increment i.
2. In the case of partial/complete overlap,
```
spans[i].Start = spans[i - 1].Start
spans[i].End = max(spans[i].End, spans[i - 1].End)

// Mark the previous span as useless by setting it to nil, although, there can be
// some other way to mark it as useless, too.
spans[i - 1].Start = nil
spans[i - 1].End = nil
i++
```

Then, after the for loop, copy the spans where the start,end isn't `nil` to a new spans slice.
```
var newSpans []Span
for i := 0; i < len(s.spans); i++ {
    if s.spans[i].Start != nil && s.spans[i].End != nil {
        newSpans = append(newSpans, s.spans[i])
    }
}
s.spans = newSpans
```

Might also be useful to have a test for any merge logic we use.


<!-- Sent from Reviewable.io -->

2021-09-22 19:02 UTC, bananabrick reviewed
Took a look at the rest of the files. Do we still want to add a `CrashOnCorruption` field from the RFC?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1180#-:-MkDlC1Y3h-UZZK7jlGj:b-sff7mh)* status: 3 of 8 files reviewed, 10 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/manifest/version.go, line 112 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MkD_n2Z4sNDJUFaaxUE:-MkD_n2Z4sNDJUFaaxUF:b7xn22s) ([raw file](https://github.com/cockroachdb/pebble/blob/c52dd2ecafdc2978449d66f933b2653709027dc9/internal/manifest/version.go#L112)):*
> ```Go
> 	// Fields protected by a Mutex.
> 	Mu struct {
> 		sync.Mutex
> ```

Do we need a mutex here? As far as I can tell, this field will only be accessed by a single go routine(the first one to find the corruption).
___
*[sstable/reader.go, line 1715 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MkDoBgX28y9nXFcyZ-k:-MkDoBgX28y9nXFcyZ-l:b-se0emc) ([raw file](https://github.com/cockroachdb/pebble/blob/c52dd2ecafdc2978449d66f933b2653709027dc9/sstable/reader.go#L1715)):*
> ```Go
> // CorruptionReporter is an interface for reporting sstable corruption.
> type CorruptionReporter interface {
> 	// ReportCorruption reports an instance of sstable corruption. The sstable
> ```

Is this comment up to date? Do we still need to "inform any callers to stop issuing more read requests over the user-key range [start, end], as those will return CorruptionErrors again"?

Does this need to be idempotent? It looks like for a given file, we'll only report corruptions once anyway. I suppose the start,end ranges could be the same for two files on different layers.
___
*[sstable/reader.go, line 2240 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MkDpxAC5JvLZ6TgX1XR:-MkDpxAC5JvLZ6TgX1XS:b-pvqtdy) ([raw file](https://github.com/cockroachdb/pebble/blob/c52dd2ecafdc2978449d66f933b2653709027dc9/sstable/reader.go#L2240)):*
> ```Go
> 		return spans, r.err
> 	}
> 	if r.fileMeta == nil {
> ```

Is this supposed to be `r.fileMeta`?
___
*[sstable/reader.go, line 2246 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MkDqXKJ9a99h11xBrQ1:-MkDqXKJ9a99h11xBrQ2:bmdzvts) ([raw file](https://github.com/cockroachdb/pebble/blob/c52dd2ecafdc2978449d66f933b2653709027dc9/sstable/reader.go#L2246)):*
> ```Go
> 	fullFileSpan := manifest.Span{Start: r.fileMeta.Smallest.UserKey, End: r.fileMeta.Largest.UserKey}
> 	indexH, err := r.readIndex()
> 	if err != nil {
> ```

r.readIndex here could already be reporting corruption by calling `r.maybeReportCorruption`. Is there some redundancy here, or am I thinking about it incorrectly?


<!-- Sent from Reviewable.io -->

2021-09-27 21:50 UTC, itsbilal reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1180#-:-MkbueR31Pf7G5Jib1HI:bz5mair)* status: 2 of 8 files reviewed, 10 unresolved discussions (waiting on @bananabrick, @jbowens, and @sumeerbhola)

___
*[internal/manifest/spans.go, line 64 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1180#-Mje7RHq751Xv6zja-0y:-Mkd5ppT0yF-7wXV-kaq:bmm2q4w) ([raw file](https://github.com/cockroachdb/pebble/blob/c52dd2ecafdc2978449d66f933b2653709027dc9/internal/manifest/spans.go#L64)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

It probably doesn't matter, but I think we can avoid the copies here on almost every execution of the loop, and maybe simplify the logic.

1. In the case of no overlap, increment i.
2. In the case of partial/complete overlap,
```
spans[i].Start = spans[i - 1].Start
spans[i].End = max(spans[i].End, spans[i - 1].End)

// Mark the previous span as useless by setting it to nil, although, there can be
// some other way to mark it as useless, too.
spans[i - 1].Start = nil
spans[i - 1].End = nil
i++
```

Then, after the for loop, copy the spans where the start,end isn't `nil` to a new spans slice.
```
var newSpans []Span
for i := 0; i < len(s.spans); i++ {
    if s.spans[i].Start != nil && s.spans[i].End != nil {
        newSpans = append(newSpans, s.spans[i])
    }
}
s.spans = newSpans
```

Might also be useful to have a test for any merge logic we use.
</blockquote></details>

This is a good point! We could possibly use the nil value to denote a tombstone, but I'm slightly wary of that as nil is equivalent to an empty-length slice which might also be a valid user key in some contexts (it isn't for Cockroach but it could be for the temp engine, etc).

If the goal is to avoid a copy, we could just start putting deleted indices in a separate slice, then iterate over this slice once and shift everything left, but that means we need one additional slice worth of space. At that point I'm okay with the current solution unless you feel strongly otherwise; we do similar slice copies to delete elements elsewhere too.
___
*[internal/manifest/version.go, line 112 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MkD_n2Z4sNDJUFaaxUE:-MkbvFtYAAB8mD4tyxmS:b-831izk) ([raw file](https://github.com/cockroachdb/pebble/blob/c52dd2ecafdc2978449d66f933b2653709027dc9/internal/manifest/version.go#L112)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Do we need a mutex here? As far as I can tell, this field will only be accessed by a single go routine(the first one to find the corruption).
</blockquote></details>

It's an anticipatory mutex - the other major user will be the compaction logic that'd special-case deletion of corrupt spans down the line. I'll mention that in the comment.
___
*[sstable/reader.go, line 1715 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MkDoBgX28y9nXFcyZ-k:-MkbwVL98paO_1jVALl4:bypoguh) ([raw file](https://github.com/cockroachdb/pebble/blob/c52dd2ecafdc2978449d66f933b2653709027dc9/sstable/reader.go#L1715)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Is this comment up to date? Do we still need to "inform any callers to stop issuing more read requests over the user-key range [start, end], as those will return CorruptionErrors again"?

Does this need to be idempotent? It looks like for a given file, we'll only report corruptions once anyway. I suppose the start,end ranges could be the same for two files on different layers.
</blockquote></details>

Since we don't persist `CorruptSpans` in the manifest, it's possible that it could be called the next time the node starts. But yes, the lack of level information is the other reason why putting idenpotency in the contract is a good idea IMO.
___
*[sstable/reader.go, line 2240 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MkDpxAC5JvLZ6TgX1XR:-MkbzKXN20NYPLBCzvVh:b-h2vy0r) ([raw file](https://github.com/cockroachdb/pebble/blob/c52dd2ecafdc2978449d66f933b2653709027dc9/sstable/reader.go#L2240)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Is this supposed to be `r.fileMeta`?
</blockquote></details>

Yes? Not sure if I understand the question. But that field is only set in `CorruptionReportingOpt`.
___
*[sstable/reader.go, line 2246 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1180#-MkDqXKJ9a99h11xBrQ1:-MkbzpzN7WoqW9xE-xzn:b-eo3jwb) ([raw file](https://github.com/cockroachdb/pebble/blob/c52dd2ecafdc2978449d66f933b2653709027dc9/sstable/reader.go#L2246)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

r.readIndex here could already be reporting corruption by calling `r.maybeReportCorruption`. Is there some redundancy here, or am I thinking about it incorrectly?
</blockquote></details>

`readIndex` can only call `maybeReportCorruption` which does _not_ call `FindCorruptSpans` - that is only called by `maybeReportDataBlockCorruption`. So that cycle should not happen.


<!-- Sent from Reviewable.io -->

2023-06-05 17:44 UTC, itsbilal commented
Closing as unplanned/abandoned.

2023-06-05 17:44 UTC, closed without merging