compaction: adjust nonzero-seqnum splitting logic
cockroachdb/pebble pull request #1182
Opened 2021-07-02 00:56 UTC by jbowens

This commit contains two changes related to #1181, fixing two ways
excessively large output tables may be created.

The first adjusts the nonZeroSeqNumSplitter to allow splitting if the
compaction is allowing zeroing of sequence numbers and all of the
pending range deletions will be elided. This avoids the problematic case
where a very wide range deletion at a low sequence number sits in the
rangedel fragmenter, preventing splitting sstables. Previously if the
compaction was actively zeroing sequence numbers, we were unable to
split compaction output until the range deletion's end.

The second adjusts the logic around when to zero sequence numbers,
preventing zeroing if there's a range deletion tombstone in the
fragmenter that covers the current key but didn't drop it because of
an open snapshot. This ensures that we can split the compaction output
even if a wide range deletion must be added to the output table.

Fix #1181.

2021-07-02 00:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1182)
<!-- Reviewable:end -->

2021-07-02 15:07 UTC, petermattis reviewed
Nice finds. It is worth having @itsbilal and @sumeerbhola scrutinize this new logic as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182#-:-MdbkXkCBIDtWaA7sV0E:b-6a29xq)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @jbowens)

___
*[compaction.go, line 370 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MdbjFrK5hATEdTk5x3J:-MdbjFrK5hATEdTk5x3K:b-9qoxqa) ([raw file](https://github.com/cockroachdb/pebble/blob/a95f930c849dda2aac99105bcdf14dc587a37ef3/compaction.go#L370)):*
> ```Go
> 	// avoiding the sstable-boundary issue that motivates the non-zero seqnum
> 	// splitting. If the compaction is zeroing sequence numbers, there are no
> 	// keys beneath the tombstone. If all the pending tombstones are also in
> ```

Let's add that the range tombstone will be elided by the `elideRangeTombstone` check in `compactionIter.emitRangeDelChunk`. It took me a moment to understand this and that `n.c.allowedZeroSeqNum` is what guarantees this. Perhaps worth a diagram if your ascii-art skills are up to it.
___
*[compaction_iter.go, line 684 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Mdbh7r95_4lnxbOiSBe:-Mdbh7rA9KLr9kKBoLz9:b-l4dl52) ([raw file](https://github.com/cockroachdb/pebble/blob/a95f930c849dda2aac99105bcdf14dc587a37ef3/compaction_iter.go#L684)):*
> ```Go
> 	// of creating an excessively large sstable outweighs the zero sequence
> 	// number optimization, so we do not zero.
> 	if i.rangeDelFrag.Deleted(i.key, math.MaxUint64) {
> ```

Please add some test cases for this behavior to `testdata/compaction_iter`.
___
*[internal/rangedel/fragmenter.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MdbhKO_5marU-EfT9sF:-MdbhKO_5marU-EfT9sG:bmbcbx3) ([raw file](https://github.com/cockroachdb/pebble/blob/a95f930c849dda2aac99105bcdf14dc587a37ef3/internal/rangedel/fragmenter.go#L94)):*
> ```Go
> // MaxSeqNum returns the highest sequence number of a pending tombstone. If
> // there are no pending tombstones, MaxSeqNum returns zero.
> func (f *Fragmenter) MaxSeqNum() uint64 {
> ```

This is pretty simple logic, but I think it is still worth adding some test cases to `testdata/fragmenter`. 


<!-- Sent from Reviewable.io -->

2021-07-06 16:48 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @petermattis)

___
*[compaction.go, line 370 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MdbjFrK5hATEdTk5x3J:-MdwhxMO0DPzLoh3oC-6:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a95f930c849dda2aac99105bcdf14dc587a37ef3/compaction.go#L370)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Let's add that the range tombstone will be elided by the `elideRangeTombstone` check in `compactionIter.emitRangeDelChunk`. It took me a moment to understand this and that `n.c.allowedZeroSeqNum` is what guarantees this. Perhaps worth a diagram if your ascii-art skills are up to it.
</blockquote></details>

Done.
___
*[compaction_iter.go, line 684 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Mdbh7r95_4lnxbOiSBe:-Mdwb5CbBJB6S-2z0Tq3:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a95f930c849dda2aac99105bcdf14dc587a37ef3/compaction_iter.go#L684)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Please add some test cases for this behavior to `testdata/compaction_iter`.
</blockquote></details>

Done.
___
*[internal/rangedel/fragmenter.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MdbhKO_5marU-EfT9sF:-MdwQeCdCjrSkls17une:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a95f930c849dda2aac99105bcdf14dc587a37ef3/internal/rangedel/fragmenter.go#L94)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is pretty simple logic, but I think it is still worth adding some test cases to `testdata/fragmenter`. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-06 21:54 UTC, itsbilal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 5 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182#-:-MdxoGzj6IzZrPQbv4Vt:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 397 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MdxlT3R20wO-Xg728Kx:-MdxlT3S5YuiLrFeocj9:br8m4ce) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L397)):*
> ```Go
> 	// When m.SET#0 is encountered, the only range deletion in the fragmenter
> 	// is at sequence number #1. There's no snapshot preserving it. That fact
> 	// combined with the lack over overlapping in-use ranges indicates the
> ```

s/lack over/lack of?


<!-- Sent from Reviewable.io -->

2021-07-07 13:44 UTC, sumeerbhola reviewed
> Reviewed 3 of 5 files at r1, 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens and @petermattis)

___
*[compaction.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Me0AAQG-nud8ORfimY5:-Me0AAQG-nud8ORfimY6:b-mzm6ts) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L412)):*
> ```Go
> 	}
> 
> 	if n.splitOnNonZeroSeqNum {
> ```

(I didn't read through the long comment in `pendingRangeDelsEmpty` -- don't wait for me since I may not get to it until later today)

I am wondering if we could sidestep the need for more complicated logic by:
- splitting here if the user key has changed
- improving the `userKeyChange` logic by doing an actual key comparison instead of tolerating false negatives that go with `curSeqNum > prevPointSeqNum`. We already do such comparisons in `userKeyChangeSplitter` (not used here) and presumably that is not costing us much.

In the CockroachDB setting the number of seqnums for a user key should be modest given that different MVCC versions are different user keys. The one exception being the intent which uses the same key (until we have separated intents enabled) but even then the number of seqnums for a user key is unlikely to be more than 100MB.
 
___
*[compaction_iter.go, line 684 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Mdbh7r95_4lnxbOiSBe:-Me07eqW5wIMLij4nYL7:be5of2b) ([raw file](https://github.com/cockroachdb/pebble/blob/a95f930c849dda2aac99105bcdf14dc587a37ef3/compaction_iter.go#L684)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

btw, do we have a benchmark that shows how compaction speed is affected by range tombstones? `Fragmenter.Deleted` does a linear scan and key comparisons and CockroachDB keys are probably not short in many cases. If we don't have one, I think we should create an issue to add one.


<!-- Sent from Reviewable.io -->

2021-07-07 19:34 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Me0AAQG-nud8ORfimY5:-Me1Pwmj8DXyEfKZBhG2:b683uvc) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L412)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

(I didn't read through the long comment in `pendingRangeDelsEmpty` -- don't wait for me since I may not get to it until later today)

I am wondering if we could sidestep the need for more complicated logic by:
- splitting here if the user key has changed
- improving the `userKeyChange` logic by doing an actual key comparison instead of tolerating false negatives that go with `curSeqNum > prevPointSeqNum`. We already do such comparisons in `userKeyChangeSplitter` (not used here) and presumably that is not costing us much.

In the CockroachDB setting the number of seqnums for a user key should be modest given that different MVCC versions are different user keys. The one exception being the intent which uses the same key (until we have separated intents enabled) but even then the number of seqnums for a user key is unlikely to be more than 100MB.
 
</blockquote></details>

Can we actually split on the next user key if it also has a zero seqnum? My understanding is that even if the next key has a different user key _u_, the finished sstable will have its range tombstone truncated to the first user key of the next table _u_, producing a largest key bound of _u.RANGEDEL.x_. The next sstable we produce will have a smallest key bound of _u#0_.

I think that `userKeyChange` variable is confusing and should be renamed/modified, because what we're actually testing is that the `curSeqNum > 0`, which ensures we can modify the next table's smallest sequence number here: https://github.com/cockroachdb/pebble/blob/31f3ea68e61c41e601e53c9501d406f7678e2d5f/compaction.go#L2292
___
*[compaction_iter.go, line 684 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Mdbh7r95_4lnxbOiSBe:-Me16BqAEGh2_BsDJAYJ:b-8r64qt) ([raw file](https://github.com/cockroachdb/pebble/blob/a95f930c849dda2aac99105bcdf14dc587a37ef3/compaction_iter.go#L684)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

btw, do we have a benchmark that shows how compaction speed is affected by range tombstones? `Fragmenter.Deleted` does a linear scan and key comparisons and CockroachDB keys are probably not short in many cases. If we don't have one, I think we should create an issue to add one.
</blockquote></details>

I don't think we have _any_ compaction benchmarks. Filed #1185.


<!-- Sent from Reviewable.io -->

2021-07-07 19:43 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Me0AAQG-nud8ORfimY5:-Me1TyBI1eIf_jfr-Ars:b-8oxlkk) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L412)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Can we actually split on the next user key if it also has a zero seqnum? My understanding is that even if the next key has a different user key _u_, the finished sstable will have its range tombstone truncated to the first user key of the next table _u_, producing a largest key bound of _u.RANGEDEL.x_. The next sstable we produce will have a smallest key bound of _u#0_.

I think that `userKeyChange` variable is confusing and should be renamed/modified, because what we're actually testing is that the `curSeqNum > 0`, which ensures we can modify the next table's smallest sequence number here: https://github.com/cockroachdb/pebble/blob/31f3ea68e61c41e601e53c9501d406f7678e2d5f/compaction.go#L2292
</blockquote></details>

I'm getting all mixed up here — why do we care about the _previous_ key's sequence number at all? Don't we only care about the sequence number of the current key, which determines what the smallest key in the _next_ sstable will be, which determines whether or not we'll be able to adjust the metadata's smallest key's sequence number?


<!-- Sent from Reviewable.io -->

2021-07-07 20:00 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Me0AAQG-nud8ORfimY5:-Me1XtawEiZ-8gwaobMq:bbabh60) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L412)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I'm getting all mixed up here — why do we care about the _previous_ key's sequence number at all? Don't we only care about the sequence number of the current key, which determines what the smallest key in the _next_ sstable will be, which determines whether or not we'll be able to adjust the metadata's smallest key's sequence number?
</blockquote></details>

Ah, right, we can't adjust the _next_ table's smallest key's sequence number if the _previous_ table's largest key's sequence number is 0.


<!-- Sent from Reviewable.io -->

2021-07-07 21:07 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Me0AAQG-nud8ORfimY5:-Me1hqZ_5dFsQHkd_zGP:bldotix) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L412)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Ah, right, we can't adjust the _next_ table's smallest key's sequence number if the _previous_ table's largest key's sequence number is 0.
</blockquote></details>

I'm still getting all mixed up. If the previous key had a zero sequence number, isn't the current key necessarily a new user key? Keys are provided by the compaction iterator in decreasing order and duplicate keys (same user key and sequence number) are not permitted.

Is the nonzero compaction splitting logic even necessary?


<!-- Sent from Reviewable.io -->

2021-07-07 22:54 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens and @petermattis)

___
*[compaction.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Me0AAQG-nud8ORfimY5:-Me1quM-3hiZptkTtAlS:b-o23yrh) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L412)):*
> and duplicate keys (same user key and sequence number) are not permitted.

I agree that compactionIter should never produce duplicate keys. And when it zeroes the seqnum it is at the last snapshot stripe and will do `skipInStripe`, which should ensure this.

I think we are getting confused because this has gotten very complicated and probably over complicated. We should be able to cleanly split when the user key changes -- this is the "mostly simple" case described in https://github.com/cockroachdb/pebble/blob/master/docs/range_deletions.md#the-mostly-simple-world
The comment at https://github.com/cockroachdb/pebble/blob/31f3ea68e61c41e601e53c9501d406f7678e2d5f/compaction.go#L2360-L2375 is not fully correct. I think it depends on what key we use in the call to `Fragmenter.FlushTo`. Also, much of the commentary was written prior to us adding `Fragmenter.TruncateAndFlushTo` -- I think it would be nice (but not necessary) to use the latter when we are switching user keys (and not just for flushes), since it would result in fewer untruncated range tombstones.

I think it is possible that the `limit` that we pass to `FlushTo` is equal to the last key added to the prev sstable, even if that last key had a seqnum of 0. I think this can happen since `limit` is inclusive (grandparentLimitSplitter and l0LimitSplitter), and we could run out of keys. Then we would have the case of x.SET.0 as the last key in an sstable and since we used x in FlushTo, the next sstable would start with a range tombstone [x, ...).RANGEDEL.<num> and we can't adjust than num down to -1. I think if `limit` were exclusive and `compactionOutputSplitter` guaranteed that `shouldSplitBefore` would return `splitNow` for a key <= `limit`, then we could eliminate the `nonZeroSeqNumSplitter`. I suspect such a change would be messy because `limit` is calculated using grandparent file bounds and file bounds are inclusive.
Luckily for us, another `prevPointSeqNum` logic exists in https://github.com/cockroachdb/pebble/blob/31f3ea68e61c41e601e53c9501d406f7678e2d5f/compaction.go#L2488-L2495 and handles the above case by setting `limit=nil`.

So the cases we want to document are:
- limit > last key added to previous sstable: The truncation of the tombstone is clean
- limit == last key added to previous sstable: This can happen because of file size limits or because we ran out of keys. The first subcase is where `key != nil`. The last key added could not have a seqnum of 0. The second subcase is where seqnum != 0 (again no problem), or seqnum == 0 (handled by flushing all the range tombstones in the current sstable).


<!-- Sent from Reviewable.io -->

2021-07-07 23:09 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Me0AAQG-nud8ORfimY5:-Me2D75o0mwmlS-lmsiT:b-37k57l) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L412)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> and duplicate keys (same user key and sequence number) are not permitted.

I agree that compactionIter should never produce duplicate keys. And when it zeroes the seqnum it is at the last snapshot stripe and will do `skipInStripe`, which should ensure this.

I think we are getting confused because this has gotten very complicated and probably over complicated. We should be able to cleanly split when the user key changes -- this is the "mostly simple" case described in https://github.com/cockroachdb/pebble/blob/master/docs/range_deletions.md#the-mostly-simple-world
The comment at https://github.com/cockroachdb/pebble/blob/31f3ea68e61c41e601e53c9501d406f7678e2d5f/compaction.go#L2360-L2375 is not fully correct. I think it depends on what key we use in the call to `Fragmenter.FlushTo`. Also, much of the commentary was written prior to us adding `Fragmenter.TruncateAndFlushTo` -- I think it would be nice (but not necessary) to use the latter when we are switching user keys (and not just for flushes), since it would result in fewer untruncated range tombstones.

I think it is possible that the `limit` that we pass to `FlushTo` is equal to the last key added to the prev sstable, even if that last key had a seqnum of 0. I think this can happen since `limit` is inclusive (grandparentLimitSplitter and l0LimitSplitter), and we could run out of keys. Then we would have the case of x.SET.0 as the last key in an sstable and since we used x in FlushTo, the next sstable would start with a range tombstone [x, ...).RANGEDEL.<num> and we can't adjust than num down to -1. I think if `limit` were exclusive and `compactionOutputSplitter` guaranteed that `shouldSplitBefore` would return `splitNow` for a key <= `limit`, then we could eliminate the `nonZeroSeqNumSplitter`. I suspect such a change would be messy because `limit` is calculated using grandparent file bounds and file bounds are inclusive.
Luckily for us, another `prevPointSeqNum` logic exists in https://github.com/cockroachdb/pebble/blob/31f3ea68e61c41e601e53c9501d406f7678e2d5f/compaction.go#L2488-L2495 and handles the above case by setting `limit=nil`.

So the cases we want to document are:
- limit > last key added to previous sstable: The truncation of the tombstone is clean
- limit == last key added to previous sstable: This can happen because of file size limits or because we ran out of keys. The first subcase is where `key != nil`. The last key added could not have a seqnum of 0. The second subcase is where seqnum != 0 (again no problem), or seqnum == 0 (handled by flushing all the range tombstones in the current sstable).

</blockquote></details>

Even if the limit is inclusive, if the largest key in the sstable has a zero sequence number, how is it possible that there's a range tombstone that spans between the two sstables? We don't zero range tombstone sequence numbers. If the tombstone has a nonzero sequence number, why isn't the largest key in the sstable the range deletion sentinel?


<!-- Sent from Reviewable.io -->

2021-07-07 23:53 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Me0AAQG-nud8ORfimY5:-Me2Kkow5i-6yzwspTrJ:bz6jpwd) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L412)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Even if the limit is inclusive, if the largest key in the sstable has a zero sequence number, how is it possible that there's a range tombstone that spans between the two sstables? We don't zero range tombstone sequence numbers. If the tombstone has a nonzero sequence number, why isn't the largest key in the sstable the range deletion sentinel?
</blockquote></details>

Sorry, I'm still talking myself in circles. I'm going to walk through your comment (thank you, it's very comprehensive) and the code again tomorrow to make sure I'm fully understanding these interactions.


<!-- Sent from Reviewable.io -->

2021-07-08 12:11 UTC, sumeerbhola commented
> Even if the limit is inclusive, if the largest key in the sstable has a zero sequence number, how is it possible that there's a range tombstone that spans between the two sstables? We don't zero range tombstone sequence numbers. If the tombstone has a nonzero sequence number, why isn't the largest key in the sstable the range deletion sentinel?
> Sorry, I'm still talking myself in circles. I'm going to walk through your comment (thank you, it's very comprehensive) and the code again tomorrow to make sure I'm fully understanding these interactions.

This is indeed very subtle/complicated and good that you are looking at it. The short answer to "why isn't the largest key in the sstable the range deletion sentinel" is that it is because of what we do in `finishOutput` in computing the sstable bounds. The longer version:

Say the last point key is c#0 and there was a range deletion tombstone `[b,f)#10`, which didn't delete the last point key because of a snapshot. And the limit is c (because we've run out of point keys). The current sstable ends with c#0 and the next sstable would have `[c,f)#10` (if we didn't have the special logic in https://github.com/cockroachdb/pebble/blob/31f3ea68e61c41e601e53c9501d406f7678e2d5f/compaction.go#L2488-L2495 that sets limit=nil).

The previous sstable would have `[b, f)#10`, because Fragmenter.FlushTo would get called and it does not truncate. In this case we know that there are no more c's because of seqnum 0, but we don't have the ability to produce ImmediateSuccessor(c) which is what we would need if we wanted to call Fragmenter.TruncateAndFlushTo which would result in the previous sstable having `[b, IC(c))#10` and the new sstable `[IC(c), f)#10`, so let's ignore the possibility of doing this.

Then `finishOutput(c)` would get called for the current sstable. This would exercise https://github.com/cockroachdb/pebble/blob/31f3ea68e61c41e601e53c9501d406f7678e2d5f/compaction.go#L2297-L2310 which would adjust `writerMeta.LargestRange` to c#inf, which would eventually result in the current sstable having bound [.., c#0]. Then when we eventually called `finishOutput` for the next sstable we would try to do https://github.com/cockroachdb/pebble/blob/31f3ea68e61c41e601e53c9501d406f7678e2d5f/compaction.go#L2297-L2310 and generate an error.

2021-07-08 16:28 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Me0AAQG-nud8ORfimY5:-Me5mK7p-PBbi6XK8JeS:boug4e2) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L412)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Sorry, I'm still talking myself in circles. I'm going to walk through your comment (thank you, it's very comprehensive) and the code again tomorrow to make sure I'm fully understanding these interactions.
</blockquote></details>

I'd like to come up with a test case that exercises this condition. (none of our current unit tests fall into [this condition](https://github.com/cockroachdb/pebble/blob/31f3ea68e61c41e601e53c9501d406f7678e2d5f/compaction.go#L2261-L2273) when I remove the `nonZeroSeqNumSplitter`)

The `limit` is inclusive, but we call `finishOutput`/`FlushTo` with the first key of the _next_ sstable. The pending tombstones will be truncated to the next table's key, which necessarily must be a different user key because the last key of the previous sstable had a zero sequence number (so there are no more point keys with that user key that sort after it). This means that the previous sstable's largest key is a range deletion sentinel rather than the zero-sequence numbered key.


<!-- Sent from Reviewable.io -->

2021-07-08 16:39 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Me0AAQG-nud8ORfimY5:-Me5zAmH3XeKqVf28nrK:b-f6tw5x) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L412)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I'd like to come up with a test case that exercises this condition. (none of our current unit tests fall into [this condition](https://github.com/cockroachdb/pebble/blob/31f3ea68e61c41e601e53c9501d406f7678e2d5f/compaction.go#L2261-L2273) when I remove the `nonZeroSeqNumSplitter`)

The `limit` is inclusive, but we call `finishOutput`/`FlushTo` with the first key of the _next_ sstable. The pending tombstones will be truncated to the next table's key, which necessarily must be a different user key because the last key of the previous sstable had a zero sequence number (so there are no more point keys with that user key that sort after it). This means that the previous sstable's largest key is a range deletion sentinel rather than the zero-sequence numbered key.
</blockquote></details>

(missed your top-level comment, going to review it now)


<!-- Sent from Reviewable.io -->

2021-07-08 17:02 UTC, jbowens reviewed
Thanks for the writeup @sumeerbhola: I'm still not sure about this point:

> Then finishOutput(c) would get called for the current sstable. 

My reading of the code is that we actually would call `finishOutput(IS(c))` (or `finishOutput(nil)` if there are no more keys) because we pass the first key of the next sstable to `finishOutput`, rather than the `limit` that triggered the output split.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182#-:-Me62yHv3x6CeCvycOJL:bxco5)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-07-08 17:51 UTC, itsbilal reviewed
> The limit is inclusive, but we call finishOutput/FlushTo with the first key of the next sstable. The pending tombstones will be truncated to the next table's key, which necessarily must be a different user key because the last key of the previous sstable had a zero sequence number (so there are no more point keys with that user key that sort after it). This means that the previous sstable's largest key is a range deletion sentinel rather than the zero-sequence numbered key.

This could be correct if we made the change to have the bound of the left sstable at [...-limit#RangeDelSentinel] and the right sstable at [limit#bar-...]. I'd have to think if that'd work well in cases where we end up writing no point keys at `limit` due to elision, but without too much thought I think we might be able to get away with that change in bound computation without changing too much read logic.

That's not what happens currently though. It's true that limit is the first key of the next sstable, but the bounds are set relative to the last key of the previous sstable when the fragmenter isn't empty. So the bounds are `[...-prev(limit)#seqnum]` and `[prev(limit)#seqnum-1...]`, where `prev(limit)` is the key returned by the compactionIter before the limit key. The goal is to keep the gap between the two keys as small as possible, while for correctness it might only be necessary for both bounds to have the same user key (so they can be treated as one atomic compaction unit).

Let me know if this doesn't make sense. It's been a while since I last touched compaction splitting in detail as it's been a while since we actually found a bug in this space, but I'm happy to explain more.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182#-:-Me6A-Nt7LnA8ymcHvZa:b2yqjte)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Me0AAQG-nud8ORfimY5:-Me6B2Cf0MRymnzKCdMT:b-mjkb98) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L412)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

(missed your top-level comment, going to review it now)
</blockquote></details>

A lot of these conditionals came about after metamorphic test run failures back in the day.  I'm surprised that the zero seqnum case isn't tested at all yet on the compaction side, but at least the splitter itself is tested. Would be good to see the compaction loop side tested more too.

(Replying to the top-level comment about the rest of your comment)


<!-- Sent from Reviewable.io -->

2021-07-08 21:47 UTC, jbowens reviewed
Hmm, I'm still confused. My understanding is: There's a `limit` that determines when to split outputs. We trigger a split, when `key` > `limit`, indicating that all keys `<= limit` have already been added to the current output. This causes the splitter to return `splitNow` and _set `limit` to the current key's user key_:
```
			if split := splitter.shouldSplitBefore(key, tw); split != noSplit {
				if split == splitNow {
					limit = key.UserKey
```
and then we break out of the inner loop, to trigger the finishing of the table.

When we call into `finishOutput`, `key` is _not_ a user key contained within the sstable we're finishing, because it's either `nil` or the first key of the _next_ sstable.
```
	// finishOutput is called for an sstable with the first key of the next sstable, and for the
	// last sstable with an empty key.
	finishOutput := func(key []byte) error {
```

In `finishOutput`, we pass this key to `iter.Tombstones`:
```
		// NB: clone the key because the data can be held on to by the call to
		// compactionIter.Tombstones via rangedel.Fragmenter.FlushTo.
		key = append([]byte(nil), key...)
		for _, v := range iter.Tombstones(key, splitL0Outputs) {
```

If `key != nil`, then key _must_ have a different user key than the last key added to the previous sstable with a zero sequence number.

If `key = nil`, then this compaction isn't going to produce another sstable, and the largest bound will be determined by the pending tombstones in the rangedel fragmenter.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182#-:-Me6wvyt1wOcfaeJTxSz:b8hluxt)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-Me0AAQG-nud8ORfimY5:-Me74RAyAicS9a2Dpk1n:b-6nyr3e) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L412)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

A lot of these conditionals came about after metamorphic test run failures back in the day.  I'm surprised that the zero seqnum case isn't tested at all yet on the compaction side, but at least the splitter itself is tested. Would be good to see the compaction loop side tested more too.

(Replying to the top-level comment about the rest of your comment)
</blockquote></details>

Yeah, I'm speculating/hoping that code drift in the two years since the metamorphic failure inadvertently made this case impossible :crossed_fingers: 


<!-- Sent from Reviewable.io -->

2021-07-09 16:22 UTC, sumeerbhola commented
btw, just to make sure I didn't confuse anyone, my last comment was all hypothetical assuming we left limit=c in the absence of the special-case logic. I do believe we don't need the `nonZeroSeqNumSplitter`.

> Hmm, I'm still confused. My understanding is: There's a limit that determines when to split outputs. We trigger a split, when key > limit, indicating that all keys <= limit have already been added to the current output. This causes the splitter to return splitNow and set limit to the current key's user key:

This is not fully accurate, in that due to size based splitting we could have added some seqnums for a user key and not all. We wouldn't have crossed `limit` as originally computed using `onNewOutput`, but we will soon do `limit=key.UserKey` to override that.

I suspect we are in general agreement. We just need to document the cases in the code, when removing the `nonZeroSeqNumSplitter`.

And we should add a TODO with the following code to improve it.
```
		case key == nil && prevPointSeqNum == 0 && !c.rangeDelFrag.Empty():
			// We ran out of keys and the last key added to the sstable has a zero
			// seqnum and there are buffered range tombstones, so we're unable to use
			// the grandparent/flush limit for the sstable boundary. See the example in the
			// in the loop above with range tombstones straddling sstables. Setting
			// limit to nil ensures that we flush the entirety of the rangedel
			// fragmenter when writing the last output.
			limit = nil
```
since this is only a problem if the `limit` is equal to the last point key added (so we could narrow this case). And even in this narrower case we can calculate the next grandparent limit that will be > limit and use that as the limit -- we don't really need to include all the remaining tombstones in the current sstable.

2021-07-12 13:08 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 2427 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MePourT-ZwlRZkf1Z8A:-MePourT-ZwlRZkf1Z8B:b-29skm6) ([raw file](https://github.com/cockroachdb/pebble/blob/b2f05cd248ebc4b57e6da4a802edb4e4588c8afd/compaction.go#L2427)):*
> ```Go
> 		// don't split outputs where the largest key on the left side has a
> 		// seqnum of zero. This limitation exists because we need the two
> 		// tables to be disjoint in key space. Consider the scenario:
> ```

nit: "take care to ensure we don't split" should say "take care to ensure we don't split in some cases (described below)".


The following cases are a bit hard to follow, since we are not actually comparing `limit` and last key in the switch statement. 

We could say something like: At a high-level we have the following cases when the fragmenter is non-empty:
- case 1 limit > last key: <more text>
- case 2 limit == last key:
  - case 2a last key with seqnum == 0: the problem case. <more text> The TODO you added below applies here.
  - case 2b last key with seqnum != 0: <more text> the no problem case because of adjusting the next sstable's smallest boundary
- case 2' limit == last key when splitting L0 outputs: another problem case. The TODO you added also applies here. <more text>

The first case in the switch statement is a superset of 2a, and a subset of 2' (we should probably narrow this not include any of 2')
The second case in the switch is a superset of 2'.

I think what we need is a coordinated rewrite of the comments in the switch statement and here. And I now think this coordinated rewrite would be easier if we just made the high-level cases correspond more precisely to what we do in the switch statement, by actually comparing limit and last key. How about lifting the key saving logic out of `userKeyChangeSplitter` and passing the last point key in as a parameter to `shouldSplitBefore`?


<!-- Sent from Reviewable.io -->

2021-07-12 16:24 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 2427 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MePourT-ZwlRZkf1Z8A:-MeQ5R9C90RXyomzq9je:bxqi1cm) ([raw file](https://github.com/cockroachdb/pebble/blob/b2f05cd248ebc4b57e6da4a802edb4e4588c8afd/compaction.go#L2427)):*
> How about lifting the key saving logic out of `userKeyChangeSplitter` and passing the last point key in as a parameter to `shouldSplitBefore`?

Hmm, `userKeyChangeSplitter` only saves the key if one of the splitters it wraps advises a split. It would be difficult to reconcile that with the splitter interface.

I took a stab at a different refactor, including replacing the larger-scoped `limit` variable. I found it a little confusing, because we were using the same terminology in two contexts: splitters deciding when to initiate a split and the main compaction loop deciding the range deletion flush key. Open to try more refactoring here.


<!-- Sent from Reviewable.io -->

2021-07-12 19:09 UTC, itsbilal reviewed
> Reviewed 3 of 11 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: 3 of 11 files reviewed, 10 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 423 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MeQsACq3G4sXwo7QGZc:-MeQsACq3G4sXwo7QGZd:b-r4etep) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L423)):*
> ```Go
> 		}
> 		n.splitOnNonZeroSeqNum = true
> 		return splitSoon
> ```

You can remove splitSoon as a type now that it's not being used.
___
*[compaction.go, line 2427 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MePourT-ZwlRZkf1Z8A:-MeR3R6r5ktg74uf3yYq:bvq3l3n) ([raw file](https://github.com/cockroachdb/pebble/blob/b2f05cd248ebc4b57e6da4a802edb4e4588c8afd/compaction.go#L2427)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> How about lifting the key saving logic out of `userKeyChangeSplitter` and passing the last point key in as a parameter to `shouldSplitBefore`?

Hmm, `userKeyChangeSplitter` only saves the key if one of the splitters it wraps advises a split. It would be difficult to reconcile that with the splitter interface.

I took a stab at a different refactor, including replacing the larger-scoped `limit` variable. I found it a little confusing, because we were using the same terminology in two contexts: splitters deciding when to initiate a split and the main compaction loop deciding the range deletion flush key. Open to try more refactoring here.

</blockquote></details>

I like the `limit` refactor, the code is definitely more readable now. I too went in circles every time I came back to this part of the code.
___
*[compaction.go, line 2456 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MeR6E9943-AX1nyBuh7:-MeR6E9943-AX1nyBuh8:bc5b30a) ([raw file](https://github.com/cockroachdb/pebble/blob/59f79a528f1cc6d8f59547d5de159077a5ae6195/compaction.go#L2456)):*
> ```Go
> 			// TODO(jackson): This case is only problematic if splitKey equals
> 			// the user key of the last point key added. We don't need to
> 			// flush *all* sstables to the current sstable. We could flush up
> ```

flush all sstables to current sstable -> flush all range tombstones to current sstable
___
*[compaction.go, line 2462 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MeR6O8D1YKdX_cxuPzx:-MeR6O8D1YKdX_cxuPzy:b-w0mak5) ([raw file](https://github.com/cockroachdb/pebble/blob/59f79a528f1cc6d8f59547d5de159077a5ae6195/compaction.go#L2462)):*
> ```Go
> 		case key == nil && prevPointSeqNum != 0:
> 			// The last key added did not have a zero sequence number, so
> 			// we'll always be able to adjust the next table's smallest key.
> ```

Might be worth adding here that, according to the `onNewOutput` contract, the `splitterSuggestion` _has_ to be >= any key already added to the sstable. 
___
*[compaction.go, line 2473 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MeR6Hrp2rri7CcgGg7X:-MeR6Hrp2rri7CcgGg7Y:b-7ropln) ([raw file](https://github.com/cockroachdb/pebble/blob/59f79a528f1cc6d8f59547d5de159077a5ae6195/compaction.go#L2473)):*
> ```Go
> 			// TODO(jackson): This case is only problematic if splitKey equals
> 			// the user key of the last point key added. We don't need to
> 			// flush *all* sstables to the current sstable. We could flush up
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-07-12 20:40 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: 3 of 11 files reviewed, 11 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 2434 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MeRRlCi1B6-eOkqdjM_:-MeRRlCi1B6-eOkqdjMa:b-xbxwsy) ([raw file](https://github.com/cockroachdb/pebble/blob/813f08165f2d61ff814b1ca435d41c9aee1bdc85/compaction.go#L2434)):*
> ```Go
> 			// grandparent's smallest key may be less than the current key.
> 			// Splitting at the current key will cause this output to overlap
> 			// a potentially unbounded number of grandparents.
> ```

This is not something that is a newly introduced problem, yes?
Is this the case where we jump from the last added point being 100, to the next point which is 1000, while the grandparent is recommending splitting at 110 (using numbers as keys in this example), but we end up using splitKey=1000, so a wide range tombstone like [5, 2000) will have [5, 1000) in the first sst, which is undesirable?

I remember making a suggestion related to this when we were originally redoing the splitting logic to split tombstones properly using grandparents regardless of point key density, and I thought we'd implemented it.


<!-- Sent from Reviewable.io -->

2021-07-13 16:53 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182)* status: 3 of 11 files reviewed, 11 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 2456 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MeR6E9943-AX1nyBuh7:-MeVjB0k2xC_zXkY7I74:b-medfbp) ([raw file](https://github.com/cockroachdb/pebble/blob/59f79a528f1cc6d8f59547d5de159077a5ae6195/compaction.go#L2456)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

flush all sstables to current sstable -> flush all range tombstones to current sstable
</blockquote></details>

whoops, thanks!
___
*[compaction.go, line 2462 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MeR6O8D1YKdX_cxuPzx:-MeVj_-vCV5zb31GVrDf:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/59f79a528f1cc6d8f59547d5de159077a5ae6195/compaction.go#L2462)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Might be worth adding here that, according to the `onNewOutput` contract, the `splitterSuggestion` _has_ to be >= any key already added to the sstable. 
</blockquote></details>

Done
___
*[compaction.go, line 2473 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MeR6Hrp2rri7CcgGg7X:-MeVjAlRA__0fW07B3uj:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/59f79a528f1cc6d8f59547d5de159077a5ae6195/compaction.go#L2473)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[compaction.go, line 2434 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MeRRlCi1B6-eOkqdjM_:-MeVkUIt43s1UY0wq-tB:b-ntf9ys) ([raw file](https://github.com/cockroachdb/pebble/blob/813f08165f2d61ff814b1ca435d41c9aee1bdc85/compaction.go#L2434)):*
Yeah, it's an existing problem.

> Is this the case where we jump from the last added point being 100, to the next point which is 1000, while the grandparent is recommending splitting at 110 (using numbers as keys in this example), but we end up using splitKey=1000, so a wide range tombstone like [5, 2000) will have [5, 1000) in the first sst, which is undesirable?

Yes, that's the case case.

> I remember making a suggestion related to this when we were originally redoing the splitting logic to split tombstones properly using grandparents regardless of point key density, and I thought we'd implemented it.

Hmm, I peeked through the history but as far back as I looked, my read of the code was that it's susceptible to this unbounded overlap.


<!-- Sent from Reviewable.io -->

2021-07-13 17:03 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182#-:-MeVogcQ6r0c6UWp8kJ0:bg7igkv)* status: 4 of 11 files reviewed, 11 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-07-13 17:31 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1182#-:-MeVv5o_7MCmcKEqN2Mj:bz5mair)* status: 3 of 11 files reviewed, 10 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 423 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1182#-MeQsACq3G4sXwo7QGZc:-MeVtbVT8mQGL6LIutTY:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e47881460216f8df56e73c91706c67397cc2faa7/compaction.go#L423)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

You can remove splitSoon as a type now that it's not being used.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-13 17:43 UTC, merged