compaction : Skip compaction if the level score is low
cockroachdb/pebble pull request #1197
Opened 2021-07-15 22:58 UTC by bananabrick

Implements 4 here: https://docs.google.com/document/d/1qnhunjPrR1FSgRQ8MgwDay_FGgd8CoRpcsoK0Iybu2o/edit

2021-07-15 22:58 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1197)
<!-- Reviewable:end -->

2021-07-15 22:59 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1197)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @bananabrick)

___
*[compaction.go, line 1172 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1197#-MegOEcpCtNnWK8eTihn:-MegOEcpCtNnWK8eTiho:bht7o0c) ([raw file](https://github.com/cockroachdb/pebble/blob/be055dedb04bfbbf1d99b6a7ccbd1843f409d11b/compaction.go#L1172)):*
> ```Go
> // a low score, then skip the read compaction.
> // TODO(bananbrick) : What should this limit be?
> const readCompactionSkipScore = 0.5
> ```

What's a good limit for this?
___
*[compaction_picker.go, line 1376 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1197#-MegOI-gCj42mYQNHgIk:-MegOI-gCj42mYQNHgIl:bimm0o3) ([raw file](https://github.com/cockroachdb/pebble/blob/be055dedb04bfbbf1d99b6a7ccbd1843f409d11b/compaction_picker.go#L1376)):*
> ```Go
> 
> 	// Don't do the compaction if level score is already low.
> 	if pc.startLevel.level < numLevels &&
> ```

Am I checking the correct score here? I was trying to implement fix number 4 here: https://docs.google.com/document/d/1qnhunjPrR1FSgRQ8MgwDay_FGgd8CoRpcsoK0Iybu2o/edit


<!-- Sent from Reviewable.io -->

2021-07-19 21:08 UTC, itsbilal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> but benchmark this to see if it still has the intended positive effect on ycsb/B,C,D with read compactions enabled vs. disabled (i.e. we aren't too aggressively removing read compactions).

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1197#-:-Mf-aEkb3ZStz4Yi96bh:b-sl7eon)* status: all files reviewed, 6 unresolved discussions (waiting on @bananabrick)

___
*[compaction.go, line 1172 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1197#-MegOEcpCtNnWK8eTihn:-Mf-VXLV6o7LplajgpyC:b-6pwfxi) ([raw file](https://github.com/cockroachdb/pebble/blob/be055dedb04bfbbf1d99b6a7ccbd1843f409d11b/compaction.go#L1172)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

What's a good limit for this?
</blockquote></details>

This would be something you might have to figure out with benchmarks, but 0.5 sounds like a good starting point to me.
___
*[compaction_picker.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1197#-Mf-_ITX7WoPdZ3v7SaP:-Mf-_ITX7WoPdZ3v7SaQ:b-9tzvnk) ([raw file](https://github.com/cockroachdb/pebble/blob/be055dedb04bfbbf1d99b6a7ccbd1843f409d11b/compaction_picker.go#L38)):*
> ```Go
> 	pickManual(env compactionEnv, manual *manualCompaction) (c *pickedCompaction, retryLater bool)
> 	pickElisionOnlyCompaction(env compactionEnv) (pc *pickedCompaction)
> 	pickReadTriggeredCompaction(env compactionEnv, scores [7]candidateLevelInfo) (pc *pickedCompaction)
> ```

Nit: the 7 could be numLevels as that's a const.
___
*[compaction_picker.go, line 1339 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1197#-Mf-_UDt37Z0wEUMFFK_:-Mf-_UDt37Z0wEUMFFKa:b-g9dryh) ([raw file](https://github.com/cockroachdb/pebble/blob/be055dedb04bfbbf1d99b6a7ccbd1843f409d11b/compaction_picker.go#L1339)):*
> ```Go
> 
> func (p *compactionPickerByScore) pickReadTriggeredCompaction(
> 	env compactionEnv, scores [7]candidateLevelInfo,
> ```

Use numLevels
___
*[compaction_picker.go, line 1359 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1197#-Mf-_VIy7x-BTTKqzmsG:-Mf-_VIy7x-BTTKqzmsH:b-g9dryh) ([raw file](https://github.com/cockroachdb/pebble/blob/be055dedb04bfbbf1d99b6a7ccbd1843f409d11b/compaction_picker.go#L1359)):*
> ```Go
> func pickReadTriggeredCompactionHelper(
> 	p *compactionPickerByScore, rc *readCompaction,
> 	env compactionEnv, scores [7]candidateLevelInfo,
> ```

Use numLevels
___
*[compaction_picker.go, line 1375 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1197#-Mf-_lvWDfIFplsRMSR4:-Mf-_lvWDfIFplsRMSR5:b5qgc9m) ([raw file](https://github.com/cockroachdb/pebble/blob/be055dedb04bfbbf1d99b6a7ccbd1843f409d11b/compaction_picker.go#L1375)):*
> ```Go
> 	pc.startLevel.files = overlapSlice
> 
> 	// Don't do the compaction if level score is already low.
> ```

You could mention that this is likely because copmacting in this level
___
*[compaction_picker.go, line 1376 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1197#-MegOI-gCj42mYQNHgIk:-Mf-__l-4s9Uy3hcQnql:b-g2k86) ([raw file](https://github.com/cockroachdb/pebble/blob/be055dedb04bfbbf1d99b6a7ccbd1843f409d11b/compaction_picker.go#L1376)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Am I checking the correct score here? I was trying to implement fix number 4 here: https://docs.google.com/document/d/1qnhunjPrR1FSgRQ8MgwDay_FGgd8CoRpcsoK0Iybu2o/edit
</blockquote></details>

Yes, that's the correct score you're comparing against. 


<!-- Sent from Reviewable.io -->

2021-08-02 12:24 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1197)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[compaction.go, line 1171 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1197#-Mg5mxAd-6cd1zE5hzAT:-Mg5mxAd-6cd1zE5hzAU:bvrt5yv) ([raw file](https://github.com/cockroachdb/pebble/blob/8eb42aa3f112205cd5829e2e90f6a4f5006ab121/compaction.go#L1171)):*
> ```Go
> // If the score of level L * readCompactionSkipFactor, is less than the
> // score of level L + 1, then skip the compaction. This is used to prevent
> // imbalanced compactions between the levels.
> ```

This could use a longer comment about what an "imbalanced compaction" is and why it is bad.

Also, I'm slightly concerned about using the scores here since we do various adjustments to scores based on ratios, and we also use compensated sizes for those scores. And it seems less principled to reuse a measure that was setup for write-triggered compactions.

Since the main purpose here is to prevent read-triggered compactions from Li to Li+1 (where i > 0) when the actual byte size ratios are far higher than the level multiplier (say > 2x the level multiplier), in order to prevent blow up of write amplification, how about we directly make this determination when initializing compactionPickerByScore and mark certain levels in the compaction picker state as disabled for read compactions?


<!-- Sent from Reviewable.io -->

2021-08-02 21:23 UTC, closed without merging