compaction: add key validation for compacted files
cockroachdb/pebble pull request #1226
Opened 2021-08-16 22:47 UTC by nicktrav

Currently, in cases where invalid keys are present in a file that is
being created or deleted as part of a compaction, either due to
corruption or programmer error, pebble will silently propagate the
corruption, which may not be detected until much later. At such time,
the corruption may have propagated to multiple files.

Add a new experimental option, `CompactionKeyValidationFunc` that when
provided will be used to validate both the smallest and largest key in
both new and deleted files in `versionEdit`s constructed as part of a
compaction.

In the case of a key that fails validation, as there is rarely any
effective remediation that can be taken, pebble will log a fatal error
and exit.

The new option is marked as experimental. In the case where no
validation function is provided, no validation is performed on the files
in the new `versionEdit`.

Closes #1202.

2021-08-16 22:47 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1226)
<!-- Reviewable:end -->

2021-08-16 22:49 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1226)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

*[a discussion](https://reviewable.io/reviews/cockroachdb/pebble/1226#-MhG8dvm9s1Rl5Ugq_l5:-MhG8dvn9Y04SPKghkeN:bzere63) (no related file):*
Please don't hold back with the nits! This will help me pick up style, etc.

---


<!-- Sent from Reviewable.io -->

2021-08-17 18:03 UTC, sumeerbhola requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1226)* status: all files reviewed, 4 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[compaction.go, line 2488 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1226#-MhKFIDT8TevA_61b8FJ:-MhKFIDT8TevA_61b8FK:bjlgn8h) ([raw file](https://github.com/cockroachdb/pebble/blob/469a830f0e16ececc2a278ff46a9c80ab8e82372/compaction.go#L2488)):*
> ```Go
> 	// As a sanity check, confirm that the smallest / largest keys for new and
> 	// deleted files in the new versionEdit pass a validation function before
> 	// returning the edit.
> ```

can you hoist this to the top of `runCompaction` as a deferred func -- there are some early returns that return a `versionEdit` and for completeness we should capture them all.
___
*[compaction.go, line 2503 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1226#-MhKFqm0-TYuLqqOJkLm:-MhKFqm0-TYuLqqOJkLn:bimzrce) ([raw file](https://github.com/cockroachdb/pebble/blob/469a830f0e16ececc2a278ff46a9c80ab8e82372/compaction.go#L2503)):*
> ```Go
> 		return nil
> 	}
> ```

how about something like:
```
metaValidationFunc := func(meta *fileMetadata) error {
  ...
}
for _, f := range ve.NewFiles {
  if err := metaValidationFunc(f.Meta); err != nil {
     return err
   }
}
for _, f := range files {
  if err := metaValidationFunc(f); err != nil {
     return err
   }
}
```

Fewer loops and no need to allocate another slice.
___
*[options.go, line 366 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1226#-MhKEQyY6wqDx_Z2nxeZ:-MhKEQyY6wqDx_Z2nxe_:b256wc5) ([raw file](https://github.com/cockroachdb/pebble/blob/469a830f0e16ececc2a278ff46a9c80ab8e82372/options.go#L366)):*
> ```Go
> 		//
> 		// NOTE: callers should take care to not mutate the key being validated.
> 		CompactionKeyValidationFunc func(userKey []byte) error
> ```

Lets rename this `KeyValidationFunc` and say that it can be used for validating any key in an sstable.
The remaining comment can say how it is currently used (which just needs tweaking your current comment a bit)


<!-- Sent from Reviewable.io -->

2021-08-17 19:20 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1226)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @jbowens and @sumeerbhola)

*[a discussion](https://reviewable.io/reviews/cockroachdb/pebble/1226#-MhKYbQm60Hg6Cu9YM0S:-MhKYbQm60Hg6Cu9YM0T:b-vw4f5q) (no related file):*
@sumeerbhola - thanks for the first pass. Made some adjustments.

---
___
*[compaction.go, line 2488 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1226#-MhKFIDT8TevA_61b8FJ:-MhKV0mCD9qxVpvW77vQ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/469a830f0e16ececc2a278ff46a9c80ab8e82372/compaction.go#L2488)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you hoist this to the top of `runCompaction` as a deferred func -- there are some early returns that return a `versionEdit` and for completeness we should capture them all.
</blockquote></details>

Done.
___
*[compaction.go, line 2503 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1226#-MhKFqm0-TYuLqqOJkLm:-MhKVkU1-oEr2zYru94W:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/469a830f0e16ececc2a278ff46a9c80ab8e82372/compaction.go#L2503)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about something like:
```
metaValidationFunc := func(meta *fileMetadata) error {
  ...
}
for _, f := range ve.NewFiles {
  if err := metaValidationFunc(f.Meta); err != nil {
     return err
   }
}
for _, f := range files {
  if err := metaValidationFunc(f); err != nil {
     return err
   }
}
```

Fewer loops and no need to allocate another slice.
</blockquote></details>

Done.
___
*[options.go, line 366 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1226#-MhKEQyY6wqDx_Z2nxeZ:-MhKY2fR9E3qdJpiBZAS:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/469a830f0e16ececc2a278ff46a9c80ab8e82372/options.go#L366)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Lets rename this `KeyValidationFunc` and say that it can be used for validating any key in an sstable.
The remaining comment can say how it is currently used (which just needs tweaking your current comment a bit)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-17 19:48 UTC, sumeerbhola approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1226)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

*[a discussion](https://reviewable.io/reviews/cockroachdb/pebble/1226#-MhKYbQm60Hg6Cu9YM0S:-MhKdshk77YKj9muxyok:bg7igkv) (no related file):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

@sumeerbhola - thanks for the first pass. Made some adjustments.
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

---


<!-- Sent from Reviewable.io -->

2021-08-17 20:18 UTC, merged

2021-08-17 20:19 UTC, nicktrav commented
*[a discussion](https://reviewable.io/reviews/cockroachdb/pebble/1226#-MhKYbQm60Hg6Cu9YM0S:-MhKkyi22BeJ3prCuLEq:b-814g8k) (no related file):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

:lgtm: 
</blockquote></details>

TFTR!

---


<!-- Sent from Reviewable.io -->