tet
cockroachdb/pebble pull request #1235
Opened 2021-08-20 21:19 UTC by bananabrick

2021-08-20 21:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1235)
<!-- Reviewable:end -->

2021-08-20 21:35 UTC, bananabrick commented
Tested by triggering the situation which causes the finalizer to run, and making sure that all the tests pass with the invariants tag on.

2021-08-22 13:08 UTC, sumeerbhola requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1235)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @bananabrick, @itsbilal, @jbowens, and @nicktrav)

___
*[compaction_test.go, line 1538 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1235#-Mhhxmfv4LgzTxnaCvfz:-Mhhxmfv4LgzTxnaCvg-:bkzk8tq) ([raw file](https://github.com/cockroachdb/pebble/blob/e9ceb3384d48e8c7bc6c4faf479e048b08a58527/compaction_test.go#L1538)):*
> ```Go
> 		})
> 
> 	d.Close()
> ```

can you hoist this to where `d` is declared into a defer func. Something like
```
defer func() {
   if d != nil {
      d.Close()
   }
}()
```
Same for the other datadriven tests in this file


<!-- Sent from Reviewable.io -->

2021-08-23 15:23 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1235)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[compaction_test.go, line 1538 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1235#-Mhhxmfv4LgzTxnaCvfz:-MhnayjV-oyWjZnCKdrC:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e9ceb3384d48e8c7bc6c4faf479e048b08a58527/compaction_test.go#L1538)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you hoist this to where `d` is declared into a defer func. Something like
```
defer func() {
   if d != nil {
      d.Close()
   }
}()
```
Same for the other datadriven tests in this file
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-23 16:55 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1235#-:-Mhnw0t6-HMbDC73YNq-:bg7igkv)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-08-23 17:03 UTC, merged

2021-08-23 17:05 UTC, bananabrick commented
TFTR!