metamorphic: transform percentage of SINGLEDEL ops to DELETE ops
cockroachdb/pebble pull request #1249
Opened 2021-09-01 16:17 UTC by nicktrav

Generated SINGLEDEL operations are eligible for transformation into less
restrictive DELETE operations.

Transform a fixed percentage of SINGLEDEL operations at generation time
into DELETEs to further exercise the delete execution paths.

Related to cockroachdb/cockroach#69414.

2021-09-01 16:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1249)
<!-- Reviewable:end -->

2021-09-01 16:23 UTC, nicktrav reviewed
I'd also written a version of this patch that annotated the DELETE operations in the op and history logs that were the result of the conversion from SINGLEDELs at generation time. I figured this was overkill.

If we think it would be useful for debugging purposes (assuming we see a failure eventually due to these "mutated deletes"), I can add back the annotations. It was along the lines of:

```
db.Delete("foo", true /* wasSingleDelete */)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1249#-:-MiX8jw2E-UmM8co4Rd0:bw1qcxs)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[internal/metamorphic/generator.go, line 846 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1249#-MiX9yl48mwfEhMGC_8k:-MiX9yl48mwfEhMGC_8l:bbgb6o4) ([raw file](https://github.com/cockroachdb/pebble/blob/2981677158f90654c6e08082b177a5b4ee35a159/internal/metamorphic/generator.go#L846)):*
> ```Go
> 	// Keys eligible for single deletes can be removed with a regular delete.
> 	// Mutate a percentage of SINGLEDEL ops into DELETEs.
> 	if g.rng.Float64() < 0.25 {
> ```

Open to suggestions on the probability.


<!-- Sent from Reviewable.io -->

2021-09-01 18:34 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1249)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nicktrav)

___
*[internal/metamorphic/generator.go, line 846 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1249#-MiX9yl48mwfEhMGC_8k:-MiXcN1R7wG1bPeZzIpY:b2xy1rw) ([raw file](https://github.com/cockroachdb/pebble/blob/2981677158f90654c6e08082b177a5b4ee35a159/internal/metamorphic/generator.go#L846)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Open to suggestions on the probability.
</blockquote></details>

Probability is fine and we can tweak more later if needed.

But this is happening in the `generator` so all the DBs being compared will do this delete instead of single-delete. What we want is to vary this across the different DBs. See `testOptions.ingestUsingApply` as a way we vary behavior at operation execution time. I think we want to add another test option.


<!-- Sent from Reviewable.io -->

2021-09-02 00:15 UTC, nicktrav reviewed
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1249)* status: all files reviewed, 1 unresolved discussion (waiting on @nicktrav)

___
*[internal/metamorphic/generator.go, line 846 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1249#-MiX9yl48mwfEhMGC_8k:-MiYpSEz1zjDerdg3EuH:bsy0b6x) ([raw file](https://github.com/cockroachdb/pebble/blob/2981677158f90654c6e08082b177a5b4ee35a159/internal/metamorphic/generator.go#L846)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Probability is fine and we can tweak more later if needed.

But this is happening in the `generator` so all the DBs being compared will do this delete instead of single-delete. What we want is to vary this across the different DBs. See `testOptions.ingestUsingApply` as a way we vary behavior at operation execution time. I think we want to add another test option.
</blockquote></details>

Ah, gotcha.

I've pushed a new version that should do this. Worth nothing that now, at generation time, we need to persist an indicator as to whether the SINGLEDEL will be replaced, which means putting an additional field in the signature for `SingleDelete(...)`, as it appears in the op log. I also had to tweak the parser to read this new field. Now, at test runtime, we take into account whether the SINGLEDEL _could_ be replace, along with the configuration for the specific DB (i.e. should this DB replace SINGLEDEL -> DELETE).
___
*[internal/metamorphic/meta_test.go, line 261 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1249#-MiYqEkG1fHURItu5Z43:-MiYqEkG1fHURItu5Z44:bxfej0j) ([raw file](https://github.com/cockroachdb/pebble/blob/da31477c8d36e48d27333b84c840325d6b6bef52/internal/metamorphic/meta_test.go#L261)):*
> ```Go
> 	// Perform runs with random options.
> 	nOpts := len(options)
> 	for i := 0; i < nOpts; i++ {
> ```

I had this in another patch too. Wasn't sure whether the number 20 was intended to match the number of standard tests, or whether we want to keep 20 as a fixed number of random tests.


<!-- Sent from Reviewable.io -->

2021-09-08 17:49 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1249#-:-Mj5Wuqs-UY3VXWenFD3:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @nicktrav)

___
*[internal/metamorphic/meta_test.go, line 261 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1249#-MiYqEkG1fHURItu5Z43:-Mj5Vp12CAV0Vi8Fa4O7:bbdqlqr) ([raw file](https://github.com/cockroachdb/pebble/blob/da31477c8d36e48d27333b84c840325d6b6bef52/internal/metamorphic/meta_test.go#L261)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

I had this in another patch too. Wasn't sure whether the number 20 was intended to match the number of standard tests, or whether we want to keep 20 as a fixed number of random tests.
</blockquote></details>

Your change is fine. But can you add a comment like
// Arbitrary choice to run with as many random options as we have with the standard options. 


<!-- Sent from Reviewable.io -->

2021-09-08 18:37 UTC, nicktrav reviewed
TFTR!

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1249#-:-Mj5giKuBXFdfko9PmRB:b-814g8k)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nicktrav)

___
*[internal/metamorphic/meta_test.go, line 261 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1249#-MiYqEkG1fHURItu5Z43:-Mj5g_y55fvvxUq0hXhq:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e0f0a4abb82b0d60fc8fb4216534991c00f551e5/internal/metamorphic/meta_test.go#L261)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Your change is fine. But can you add a comment like
// Arbitrary choice to run with as many random options as we have with the standard options. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-08 18:52 UTC, merged