[WIP] internal/base: add SETWITHDEL key kind
cockroachdb/pebble pull request #1261
Opened 2021-09-09 20:42 UTC by nicktrav

FIXME(travers): Add commit message.

2021-09-09 20:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1261)
<!-- Reviewable:end -->

2021-09-09 21:06 UTC, sumeerbhola reviewed
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @nicktrav)

___
*[compaction_iter.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjBK9Nr38TZvv03zlHj:-MjBK9Ns50FhmHnpFSVl:bo51hgf) ([raw file](https://github.com/cockroachdb/pebble/blob/9d26f58fa309be298182e5774fc375b143e969ba/compaction_iter.go#L465)):*
> ```Go
> 	// SETWITHDEL. This guards against a SINGLEDEL above us removing the
> 	// original SET and erroneously exposing keys underneath is.
> 	if i.iterKey.Kind() == InternalKeyKindDelete {
> ```

I think we need to loop until we get a `sameStripeNonSkippable` or `newStripe` because we could have DEL => SET => SET'. Say we are at SET' at the start of this method, then step to SET as the next record and emit SET. Which would be incorrect since the `skip=true` will cause the DEL to also be skipped.

Also, we have a slightly bigger code-structuring problem here in that we don't want to stop if we see a rangedelete which causes `sameStripeNonSkippable` to be true, since there may be a DEL underneath that which we need to know about now in order to return SETWITHDEL. Note that the current code will leave `skip=true` and continue skipping after returning the rangedelete. The following comment in the code explains this
```
 `			// Although, note that `skip` may already be true before reaching here
			// due to an earlier key in the stripe. Then it is fine to leave it set
			// to true, as the earlier key must have had a higher sequence number.
 ```

Changing the code structure is going to be quite intrusive since we'll need to save the rangedelete too, iterate until we are done with this user key or stripe, then emit the SET or SETWITHDEL, and then the saved RANGEDEL and then resume.
Given the rarity that we will have a SET coincident with the start key of a RANGEDEL, we could be conservative and set skip=false if we are stopping because of `sameStripeNonSkippable`. This will cause this to be emitted as SET, then RANGEDEL, and then the other keys in the same stripe. So the compaction would possibly keep an extra key-value pair. Hmm, not sure when this extra key-value pair will eventually get deleted. Maybe a better approach is that if we encounter a `sameStripeNonSkippable`, be conservative and emit a SETWITHDEL now because that is always safe.


<!-- Sent from Reviewable.io -->

2021-09-10 00:06 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[compaction_iter.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjBK9Nr38TZvv03zlHj:-MjC-cAR7zoUBdYXoSTs:b-ic7g9u) ([raw file](https://github.com/cockroachdb/pebble/blob/9d26f58fa309be298182e5774fc375b143e969ba/compaction_iter.go#L465)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we need to loop until we get a `sameStripeNonSkippable` or `newStripe` because we could have DEL => SET => SET'. Say we are at SET' at the start of this method, then step to SET as the next record and emit SET. Which would be incorrect since the `skip=true` will cause the DEL to also be skipped.

Also, we have a slightly bigger code-structuring problem here in that we don't want to stop if we see a rangedelete which causes `sameStripeNonSkippable` to be true, since there may be a DEL underneath that which we need to know about now in order to return SETWITHDEL. Note that the current code will leave `skip=true` and continue skipping after returning the rangedelete. The following comment in the code explains this
```
 `			// Although, note that `skip` may already be true before reaching here
			// due to an earlier key in the stripe. Then it is fine to leave it set
			// to true, as the earlier key must have had a higher sequence number.
 ```

Changing the code structure is going to be quite intrusive since we'll need to save the rangedelete too, iterate until we are done with this user key or stripe, then emit the SET or SETWITHDEL, and then the saved RANGEDEL and then resume.
Given the rarity that we will have a SET coincident with the start key of a RANGEDEL, we could be conservative and set skip=false if we are stopping because of `sameStripeNonSkippable`. This will cause this to be emitted as SET, then RANGEDEL, and then the other keys in the same stripe. So the compaction would possibly keep an extra key-value pair. Hmm, not sure when this extra key-value pair will eventually get deleted. Maybe a better approach is that if we encounter a `sameStripeNonSkippable`, be conservative and emit a SETWITHDEL now because that is always safe.

</blockquote></details>

I pushed a new commit that should address the `DEL -> SET -> SET'` case. I also took the conservative approach that you mentioned,  where we emit SETWITHDEL when we encounter a non skippable entry. I dropped in a TODO to optimize this, following a re-think of how to structure the code to make this simpler.
___
*[compaction_iter.go, line 465 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjC045J7HNeEIrST8uK:-MjC045J7HNeEIrST8uL:bt5mbh5) ([raw file](https://github.com/cockroachdb/pebble/blob/cd5ee70f6513d1d59f2322473194431ff253b212/compaction_iter.go#L465)):*
> ```Go
> 			if t == sameStripeNonSkippable {
> 				// This is a key we cannot skip. We can safely emit a SETWITHDEL
> 				// here, though it is suboptimal due to ... FIXME
> ```

FIXME here is to pad out the explanation, paraphrasing your comment below.


<!-- Sent from Reviewable.io -->

2021-09-10 01:46 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[compaction_iter.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjBK9Nr38TZvv03zlHj:-MjCNTYh10qPGr77nj6F:baoem2i) ([raw file](https://github.com/cockroachdb/pebble/blob/9d26f58fa309be298182e5774fc375b143e969ba/compaction_iter.go#L465)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

I pushed a new commit that should address the `DEL -> SET -> SET'` case. I also took the conservative approach that you mentioned,  where we emit SETWITHDEL when we encounter a non skippable entry. I dropped in a TODO to optimize this, following a re-think of how to structure the code to make this simpler.
</blockquote></details>

Logic looks correct to me.


<!-- Sent from Reviewable.io -->

2021-09-11 00:11 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 4 of 12 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[compaction_iter.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjBK9Nr38TZvv03zlHj:-MjH6Hh19zEdWZFIg9e9:b6rw79i) ([raw file](https://github.com/cockroachdb/pebble/blob/9d26f58fa309be298182e5774fc375b143e969ba/compaction_iter.go#L465)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Logic looks correct to me.
</blockquote></details>

There's something subtle causing the metamorphic tests to fail.

In the diff I see records whose values have extra bytes. For example:

```console
===== DIFF =====
_meta/210910-170740.824/{standard-000,standard-001}
@@ -5140,11 +5140,11 @@
 iter46.Prev("") // [false] <nil> #5140
 db.Delete("tgdi") // <nil> #5141
 snap36 = db.NewSnapshot() #5142
 iter43.Next("") // [false] <nil> #5143
 iter43.Prev("szgtdorsgku") // [invalid] <nil> #5144
-iter48.Prev("") // [true,"zmxbgc","nnipdhfl"] <nil> #5145
+iter48.Prev("") // [true,"zmxbgc","\x00nipdhfl"] <nil> #5145
```

I've been able to narrow this down to the interaction with the cache, and how it is freeing memory when we run with `-tags invariants`. When running _without_ invariants, I do not see the issue.

In terms of the new code in this PR, it looks like the issue is somewhere in `setNext()`. Reverting the switch statement to bypass `setNext()`, I also see no issue:

```go
		case InternalKeyKindSet, InternalKeyKindSetWithDelete:
			//i.setNext()
			i.saveKey()
			i.value = i.iterValue
			i.valid = true
			i.skip = true
			i.maybeZeroSeqnum(i.curSnapshotIdx)
			return &i.key, i.value
```

Specifically _where_ in `setNext()` the problem is I'm not too sure, so could use some help in debugging further.

Running the metamorphic tests at SHA `54f499be` (current tip of branch) with seed `1631305910565978000` and `-tags invariants` should produce the test failure I'm seeing.


<!-- Sent from Reviewable.io -->

2021-09-12 21:50 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 4 of 12 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[compaction_iter.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjBK9Nr38TZvv03zlHj:-MjQwpSK9j07lSCoD5qv:bghgeyw) ([raw file](https://github.com/cockroachdb/pebble/blob/9d26f58fa309be298182e5774fc375b143e969ba/compaction_iter.go#L465)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

There's something subtle causing the metamorphic tests to fail.

In the diff I see records whose values have extra bytes. For example:

```console
===== DIFF =====
_meta/210910-170740.824/{standard-000,standard-001}
@@ -5140,11 +5140,11 @@
 iter46.Prev("") // [false] <nil> #5140
 db.Delete("tgdi") // <nil> #5141
 snap36 = db.NewSnapshot() #5142
 iter43.Next("") // [false] <nil> #5143
 iter43.Prev("szgtdorsgku") // [invalid] <nil> #5144
-iter48.Prev("") // [true,"zmxbgc","nnipdhfl"] <nil> #5145
+iter48.Prev("") // [true,"zmxbgc","\x00nipdhfl"] <nil> #5145
```

I've been able to narrow this down to the interaction with the cache, and how it is freeing memory when we run with `-tags invariants`. When running _without_ invariants, I do not see the issue.

In terms of the new code in this PR, it looks like the issue is somewhere in `setNext()`. Reverting the switch statement to bypass `setNext()`, I also see no issue:

```go
		case InternalKeyKindSet, InternalKeyKindSetWithDelete:
			//i.setNext()
			i.saveKey()
			i.value = i.iterValue
			i.valid = true
			i.skip = true
			i.maybeZeroSeqnum(i.curSnapshotIdx)
			return &i.key, i.value
```

Specifically _where_ in `setNext()` the problem is I'm not too sure, so could use some help in debugging further.

Running the metamorphic tests at SHA `54f499be` (current tip of branch) with seed `1631305910565978000` and `-tags invariants` should produce the test failure I'm seeing.
</blockquote></details>

I was able to come up with a small reproducer in a unit test: https://gist.github.com/nicktrav/f6fec5ff35c03f61cfabcf9fb0440d06

```bash
$ go test -tags invariants -run TestManualCompaction -count 1 ./...
--- FAIL: TestManualCompaction (0.00s)
    compaction_test.go:1151:
        testdata/manual_compaction_use_after_free_repro:39: first
        next
        next
        expected:
        a:baz
        z:bar
        .

        found:
        a:baz
        z:
        .
FAIL
```

It looks like there's a use-after-free bug when we iterate past the end-key of the final file in the lowest level in the compaction, when the end-key is a SET (as we are now iterating forward to look for a DELETE). When we iterate past the end-key, the `sstable.singleLevelIterator` frees the memory from the block cache. This is the data for the value that we still have a reference to in `compaction_iter.go:L447`.

Note that we only see this when the cache size is small, which is what I've observed from the metamorphic tests.

I also had to un-comment out some dead code in `cache/value_invariants.go` to zero out the memory when it is freed. Without this the test passes, but I believe this is only due to the fact that this memory is probably still live, and we can point to it.


<!-- Sent from Reviewable.io -->

2021-09-13 14:15 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 4 of 12 files reviewed, 2 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[compaction_iter.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjBK9Nr38TZvv03zlHj:-MjUPN6M0oLLFsbGuI-F:b-33k2t9) ([raw file](https://github.com/cockroachdb/pebble/blob/9d26f58fa309be298182e5774fc375b143e969ba/compaction_iter.go#L465)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

I was able to come up with a small reproducer in a unit test: https://gist.github.com/nicktrav/f6fec5ff35c03f61cfabcf9fb0440d06

```bash
$ go test -tags invariants -run TestManualCompaction -count 1 ./...
--- FAIL: TestManualCompaction (0.00s)
    compaction_test.go:1151:
        testdata/manual_compaction_use_after_free_repro:39: first
        next
        next
        expected:
        a:baz
        z:bar
        .

        found:
        a:baz
        z:
        .
FAIL
```

It looks like there's a use-after-free bug when we iterate past the end-key of the final file in the lowest level in the compaction, when the end-key is a SET (as we are now iterating forward to look for a DELETE). When we iterate past the end-key, the `sstable.singleLevelIterator` frees the memory from the block cache. This is the data for the value that we still have a reference to in `compaction_iter.go:L447`.

Note that we only see this when the cache size is small, which is what I've observed from the metamorphic tests.

I also had to un-comment out some dead code in `cache/value_invariants.go` to zero out the memory when it is freed. Without this the test passes, but I believe this is only due to the fact that this memory is probably still live, and we can point to it.
</blockquote></details>

Nice find!
This looks like a serious bug. We are relying on the stability of the value `[]byte` even after stepping to the next entry, but if the next entry is in a different block we will call `cache.Handle.Release` on the existing block which can free it. I think we got lucky in that `compaction_iter.go` was only using `iterPosNext` (and never using `iterPosPrev`) for single delete and merges:
- single delete, the `iterValue` byte slice is empty, so doesn't matter if we free the underlying memory.
- merge: the `iterValue` is not used since we are using the output of the merge.

I don't think any of the other internal iterators are relying on this behavior. There is the use `iterPosNext/iterPosPrev` in `iterator.go` that needs to be looked at carefully -- based on a quick read I think it is doing the right thing and saving the value in `valueBuf`. I think similar saving logic in a `valueBuf` in `compaction_iter.go` for this `setNext` would fix this problem.


<!-- Sent from Reviewable.io -->

2021-09-13 15:33 UTC, nicktrav reviewed
> Dismissed @sumeerbhola from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 4 of 12 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[compaction_iter.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjBK9Nr38TZvv03zlHj:-MjUlBxWD_NiFU025YCV:b-4rwudy) ([raw file](https://github.com/cockroachdb/pebble/blob/9d26f58fa309be298182e5774fc375b143e969ba/compaction_iter.go#L465)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Nice find!
This looks like a serious bug. We are relying on the stability of the value `[]byte` even after stepping to the next entry, but if the next entry is in a different block we will call `cache.Handle.Release` on the existing block which can free it. I think we got lucky in that `compaction_iter.go` was only using `iterPosNext` (and never using `iterPosPrev`) for single delete and merges:
- single delete, the `iterValue` byte slice is empty, so doesn't matter if we free the underlying memory.
- merge: the `iterValue` is not used since we are using the output of the merge.

I don't think any of the other internal iterators are relying on this behavior. There is the use `iterPosNext/iterPosPrev` in `iterator.go` that needs to be looked at carefully -- based on a quick read I think it is doing the right thing and saving the value in `valueBuf`. I think similar saving logic in a `valueBuf` in `compaction_iter.go` for this `setNext` would fix this problem.


</blockquote></details>

Nice. I took the same approach that is used in `iterator.go`. Interestingly, the introduction of that code was to fix the reverse version of this bug (seeking backwards across the start of a block in a lower level). See #572. We have existing test coverage in this case, as each time we encounter a SET, we seek forward at least once, and there are a number of test cases that have SETs as the final key in an sstable.

Marking this as resolved, as all tests are now passing :thumbsup: 


<!-- Sent from Reviewable.io -->

2021-09-13 15:59 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 4 of 12 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[compaction_iter.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjBK9Nr38TZvv03zlHj:-MjUrlYt-sNxUqkdibmd:b-ygacvj) ([raw file](https://github.com/cockroachdb/pebble/blob/9d26f58fa309be298182e5774fc375b143e969ba/compaction_iter.go#L465)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Nice. I took the same approach that is used in `iterator.go`. Interestingly, the introduction of that code was to fix the reverse version of this bug (seeking backwards across the start of a block in a lower level). See #572. We have existing test coverage in this case, as each time we encounter a SET, we seek forward at least once, and there are a number of test cases that have SETs as the final key in an sstable.

Marking this as resolved, as all tests are now passing :thumbsup: 
</blockquote></details>

If we added another field to `Options.private` and used that to wrap the `InternalIterator` normally used by `compactionIter` in an `invalidatingIter`, would that cause the bug to trigger easily on the existing datadriven tests? If yes, we should do that. We should generally add non-metamorphic tests for bugs found by the metamorphic test since the former are easier to debug if we later regress.


<!-- Sent from Reviewable.io -->

2021-09-13 16:42 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 4 of 12 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[compaction_iter.go, line 465 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjBK9Nr38TZvv03zlHj:-MjV126B3jLWun8UybwD:bx63u29) ([raw file](https://github.com/cockroachdb/pebble/blob/9d26f58fa309be298182e5774fc375b143e969ba/compaction_iter.go#L465)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If we added another field to `Options.private` and used that to wrap the `InternalIterator` normally used by `compactionIter` in an `invalidatingIter`, would that cause the bug to trigger easily on the existing datadriven tests? If yes, we should do that. We should generally add non-metamorphic tests for bugs found by the metamorphic test since the former are easier to debug if we later regress.
</blockquote></details>

Good call. I tested just now on master with an `invalidatingIter` and there are some test failures. I'll dig into these and put up a separate patch, along with test case(s) to verify.


<!-- Sent from Reviewable.io -->

2021-09-13 22:12 UTC, nicktrav reviewed
I have confirmed that this fixes the failing metamorphic test from #1254, with the problematic `SET -> ... -> DEL -> SET -> SINGLEDEL` sequence in the history. I also ran the meta tests for ~1 hour without failure.

#1254 will most likely land _after_ this change lands, but I just wanted to point out that the lack of test failures increases the confidence that we're a) resolving the underlying with SET / SINGLEDEL, and b) not introducing any additional correctness bugs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261#-:-MjWBz4J9k_DCbYSoLYh:bc9t14s)* status: 4 of 12 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-09-14 04:09 UTC, nicktrav reviewed
@sumeerbhola - looks like I spoke too soon. I encountered a metamorphic test that fails, when a SETWITHDEL is emitted twice at the same (zero) sequence number, which [fails the level checker](https://github.com/cockroachdb/pebble/blob/bd92c6f1b074fd1fd76e9703bae6c2853cf1edf7/level_checker.go#L233-L234) with an error along the lines of:

```
out of order keys cpqjje#0,SETWITHDEL >= cpqjje#0,SETWITHDEL in L6: fileNum=000036
```


Here's a minimal reproducer:
```
define
a.SET.3:c
a.RANGEDEL.2:z
a.SET.2:b
a.DEL.1:
----

iter allow-zero-seqnum=true
first
next
next
next
----
a#0,18:c
a#2,15:z
a#0,18:b
.
```

I think this is that "coincident" case we were talking about, that should be rare. However, it's not clear what the expected behavior should be?

There are also some similar existing data-driven tests that have a RANGEDEL and SET at the same sequence number, that output both the RANGEDEL and SET from the compaction iterator ([example](https://github.com/cockroachdb/pebble/blob/bd92c6f1b074fd1fd76e9703bae6c2853cf1edf7/testdata/compaction_iter#L651-L669)).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261#-:-MjWkf2LAX-us00Bi7qz:bio3s6a)* status: 4 of 12 files reviewed, all discussions resolved (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-09-14 17:34 UTC, sumeerbhola reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 5 of 12 files reviewed, 2 unresolved discussions (waiting on @nicktrav)

___
*[compaction_iter.go, line 460 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_LVn0CGVfkc5ODF7L:-Mj_LVn0CGVfkc5ODF7M:bjl1blc) ([raw file](https://github.com/cockroachdb/pebble/blob/c1cda4eae1915c0d49acda1d84cff196ee1ef1ec/compaction_iter.go#L460)):*
> ```Go
> 	// i.iter-owned value buffer.
> 	i.valueBuf = append(i.valueBuf[:0], i.iterValue...)
> 	i.value = i.valueBuf
> ```

I think we should do `i.value = i.iterValue` here, since we may return in the following if-block.
After that if-block we should do this `valueBuf` stuff since then we know we are going to iterate forward.
___
*[compaction_iter.go, line 506 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_MJtC6J3vxlXyeeYY:-Mj_MJtC6J3vxlXyeeYZ:bfgmkmm) ([raw file](https://github.com/cockroachdb/pebble/blob/c1cda4eae1915c0d49acda1d84cff196ee1ef1ec/compaction_iter.go#L506)):*
> ```Go
> 				// returns a sameStripeNonSkippable when it encounters a
> 				// RANGEDEL.
> 				// TODO(travers): optimize to handle the RANGEDEL case.
> ```

we should set `i.skip=true` since we do want points (not rangedel) with the same user key to be skipped after the rangedel is returned.
That should fix the zero seqnum problem.


<!-- Sent from Reviewable.io -->

2021-09-14 18:47 UTC, nicktrav reviewed
> Dismissed @sumeerbhola from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 4 of 12 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[compaction_iter.go, line 460 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_LVn0CGVfkc5ODF7L:-Mj_SgqOEyjyZO5I-qFY:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c1cda4eae1915c0d49acda1d84cff196ee1ef1ec/compaction_iter.go#L460)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we should do `i.value = i.iterValue` here, since we may return in the following if-block.
After that if-block we should do this `valueBuf` stuff since then we know we are going to iterate forward.
</blockquote></details>

Done.
___
*[compaction_iter.go, line 506 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_MJtC6J3vxlXyeeYY:-Mj_bsOpE3xtTIlGJgXh:b-vtd8mk) ([raw file](https://github.com/cockroachdb/pebble/blob/c1cda4eae1915c0d49acda1d84cff196ee1ef1ec/compaction_iter.go#L506)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we should set `i.skip=true` since we do want points (not rangedel) with the same user key to be skipped after the rangedel is returned.
That should fix the zero seqnum problem.
</blockquote></details>

Done. The code reads _slightly_ confusingly, as we're setting skip within a conditional branch intended for non-skippable keys. I added a comment here.

Also added some data-driven tests to exercise this a little more. r5/r6 have these changes.


<!-- Sent from Reviewable.io -->

2021-09-14 19:50 UTC, sumeerbhola reviewed
Looks good -- minor suggestions on code comments.

Reminder that the writing of SETWITHDEL needs to be gated by a new format major version.

> Reviewed 6 of 6 files at r3, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261#-:-Mj_qpy72rqUHI63UXlm:bsaxcmo)* status: all files reviewed, 6 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[compaction_iter.go, line 489 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_nFFJ1TVpGySrq_M3:-Mj_nFFJ1TVpGySrq_M4:bym45kk) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4ab3d1a503891062f6b0dbe412295f923b74a6/compaction_iter.go#L489)):*
> ```Go
> 				// DEL will eventually be elided in a subsequent compaction. The
> 				// cost for ensuring correctness is that this entry is kept
> 				// around for an additional compaction cycle.
> ```

... is that the DEL is kept around for additional compaction cycle(s).
___
*[compaction_iter.go, line 505 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_nZt71FAJmbCVJRXD:-Mj_nZt71FAJmbCVJRXE:bcmvgqw) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4ab3d1a503891062f6b0dbe412295f923b74a6/compaction_iter.go#L505)):*
> ```Go
> 				// returns a sameStripeNonSkippable when it encounters a
> 				// RANGEDEL.
> 				// TODO(travers): optimize to handle the RANGEDEL case.
> ```

nit: can you add a qualification to the TODO that says:
optimize ... case if it turns out to be a performance problem.

I very much doubt we will ever need to do anything here given that the rangedel start key has to coincide with this point key, so this is going to be rare.
___
*[compaction_iter.go, line 512 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_o4jq42ebCkfS6TOx:-Mj_o4jq42ebCkfS6TOy:bfwika5) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4ab3d1a503891062f6b0dbe412295f923b74a6/compaction_iter.go#L512)):*
> ```Go
> 				// if we mark the key to be skipped, subsequent loops will still
> 				// ensure that the keys are retained. However, keys *beyond* the
> 				// this key are indeed truly skippable.
> ```

I think this comment could be simplified
// By setting i.skip=true, we are saying that *after* the non-skippable key is emitted (which is likely a RANGEDEL), the remaining point keys that share the same user key as this saved key should be skipped.
___
*[testdata/compaction_iter, line 1408 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_qQCNE6NPuopLeWW5:-Mj_qQCNE6NPuopLeWW6:b-uwg6h9) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4ab3d1a503891062f6b0dbe412295f923b74a6/testdata/compaction_iter#L1408)):*
> ```
> a#3,18:3
> b#1,1:c
> .
> ```

nice test cases
___
*[testdata/singledel_manual_compaction, line 2 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_qZOB5230y8ICqJtp:-Mj_qZOB5230y8ICqJtq:b-5mooei) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4ab3d1a503891062f6b0dbe412295f923b74a6/testdata/singledel_manual_compaction#L2)):*
> ```
> # This is not actually a manual compaction test, and simply uses manual
> # compaction to demonstrate single delete semantics with used with
> ```

when used with ...


<!-- Sent from Reviewable.io -->

2021-09-14 20:08 UTC, nicktrav reviewed
> Reminder that the writing of SETWITHDEL needs to be gated by a new format major version.

Ah, thanks. I'll add this to my TODO list.

> Dismissed @sumeerbhola from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261#-:-Mj_uFL6Do4jrCK00Rdq:b-eyo6y3)* status: 10 of 12 files reviewed, all discussions resolved (waiting on @sumeerbhola)

___
*[compaction_iter.go, line 489 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_nFFJ1TVpGySrq_M3:-Mj_t3cD3UxVd-wX1oTs:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4ab3d1a503891062f6b0dbe412295f923b74a6/compaction_iter.go#L489)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... is that the DEL is kept around for additional compaction cycle(s).
</blockquote></details>

Done.
___
*[compaction_iter.go, line 505 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_nZt71FAJmbCVJRXD:-Mj_t8nn4JNLnAa3RR90:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4ab3d1a503891062f6b0dbe412295f923b74a6/compaction_iter.go#L505)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: can you add a qualification to the TODO that says:
optimize ... case if it turns out to be a performance problem.

I very much doubt we will ever need to do anything here given that the rangedel start key has to coincide with this point key, so this is going to be rare.

</blockquote></details>

Done.
___
*[compaction_iter.go, line 512 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_o4jq42ebCkfS6TOx:-Mj_tPrp80ykcRUm0KBg:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4ab3d1a503891062f6b0dbe412295f923b74a6/compaction_iter.go#L512)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think this comment could be simplified
// By setting i.skip=true, we are saying that *after* the non-skippable key is emitted (which is likely a RANGEDEL), the remaining point keys that share the same user key as this saved key should be skipped.
</blockquote></details>

Done.
___
*[testdata/compaction_iter, line 1408 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_qQCNE6NPuopLeWW5:-Mj_tSjT-WUW0xDRMsDf:b4c9lyr) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4ab3d1a503891062f6b0dbe412295f923b74a6/testdata/compaction_iter#L1408)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nice test cases
</blockquote></details>

:thumbsup: 
___
*[testdata/singledel_manual_compaction, line 2 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mj_qZOB5230y8ICqJtp:-Mj_u9GA7Av01MHC1QIc:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0a4ab3d1a503891062f6b0dbe412295f923b74a6/testdata/singledel_manual_compaction#L2)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

when used with ...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-14 21:01 UTC, nicktrav commented
Opening this up for wider review.

The one bug remaining item is to add the version gate. That shouldn't affect the review of the remainder of the PR.

There are also some failing tests due to the introduction of the new key kind that I need to dig into (likely to regenerate some test fixtures).

2021-09-14 21:13 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @petermattis and @sumeerbhola)

___
*[internal/base/internal.go, line 53 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mja9-jFAgdn0_sCiwkZ:-Mja9-jFAgdn0_sCiwk_:b-nt94j5) ([raw file](https://github.com/cockroachdb/pebble/blob/a754ba7cf9221bfc3c67882bd0177acf400f22ed/internal/base/internal.go#L53)):*
> ```Go
> 	// searching for any kind of internal key formed by a certain user key and
> 	// seqNum.
> 	InternalKeyKindMax InternalKeyKind = 19
> ```

@sumeerbhola - does this part look ok to you? I bumped the max key kind to `19`. This causes some fixture tests to fail.


<!-- Sent from Reviewable.io -->

2021-09-14 21:34 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @petermattis and @sumeerbhola)

___
*[internal/base/internal_test.go, line 40 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjaDhgEC84qumgcycaD:-MjaDhgEC84qumgcycaE:b-un78wu) ([raw file](https://github.com/cockroachdb/pebble/blob/2fb8de6ebb5568fdf2af12f30a7fbaa0547a7f23/internal/base/internal_test.go#L40)):*
> ```Go
> 		"foo",
> 		"foo\x08\x07\x06\x05\x04\x03\x02",
> 		"foo\x14\x07\x06\x05\x04\x03\x02\x01",
> ```

Bumped this from 18 -> 20, so that it is no longer valid.


<!-- Sent from Reviewable.io -->

2021-09-14 23:03 UTC, nicktrav reviewed
@jbowens - r11 contains the logic to switch on the format major version. Would be great if you could give this part of the PR a look.

@sumeerbhola - I also forked some of the data driven tests like we talked about, to ensure we're testing against new and old versions of the DB. I've reverted the testdata files I modified for this PR to the original state, and instead made copies that contain the modifications that are specific to the new DB format version.

The branching / switching logic clutters things a little. If you have another way you were thinking of, let me know, and I can revisit.

Question: what default version of the DB do we want on the Pebble master / release branches? It looks like by default we'll run in the most compatible mode.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261#-:-MjaWQmY9uZgJzEPHpkU:b-cw4omi)* status: 5 of 24 files reviewed, 1 unresolved discussion (waiting on @petermattis and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-09-15 01:06 UTC, sumeerbhola reviewed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 6 of 24 files reviewed, 1 unresolved discussion (waiting on @nicktrav, @petermattis, and @sumeerbhola)

___
*[internal/base/internal.go, line 53 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mja9-jFAgdn0_sCiwkZ:-Mjayvtw3y5Vyquw3Rjy:b-4qesmv) ([raw file](https://github.com/cockroachdb/pebble/blob/a754ba7cf9221bfc3c67882bd0177acf400f22ed/internal/base/internal.go#L53)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

@sumeerbhola - does this part look ok to you? I bumped the max key kind to `19`. This causes some fixture tests to fail.
</blockquote></details>

I think this needs to be 18, because the comment here says it is equal to the largest used key kind. Which means the other place I suggested using an array needs to use `bool[InternalKeyKindMax+1]`.


<!-- Sent from Reviewable.io -->

2021-09-15 01:30 UTC, sumeerbhola requested changes
Looks good. Only minor comments.

> Reviewed 1 of 1 files at r10, 16 of 17 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261#-:-Mjb3cG91XKGjJBAn5ik:b-53mc1x)* status: 23 of 24 files reviewed, 10 unresolved discussions (waiting on @nicktrav and @petermattis)

___
*[-- commits, line 10 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mjb3B-b9jqpTfjqg9lx):*
key
___
*[-- commits, line 35 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mjb3RJB0YEc5FnfkAuP):*
nit: missing period
(same for bullets below)
___
*[compaction_iter.go, line 517 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjazYuaAxAmmoLSukFz:-MjazYuaAxAmmoLSukG-:b8oq009) ([raw file](https://github.com/cockroachdb/pebble/blob/d8ee6a9f686cb45f065fafbdfc663abd354dcd12/compaction_iter.go#L517)):*
> ```Go
> 
> 	// We can only proceed if the format major version is high enough that it
> 	// support SetWithDelete. If it does not support the format version, we fall
> ```

supports
___
*[compaction_iter.go, line 522 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjazhRg4e_QV7ofJi3V:-MjazhRg4e_QV7ofJi3W:b-fhwgof) ([raw file](https://github.com/cockroachdb/pebble/blob/d8ee6a9f686cb45f065fafbdfc663abd354dcd12/compaction_iter.go#L522)):*
> ```Go
> 		i.skip = true
> 		return
> 	}
> ```

Can you hoist this before the `valueBuf` logic.
___
*[compaction_iter_test.go, line 86 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mjb2_0S7B6UvDO66ZrH:-Mjb2_0S7B6UvDO66ZrI:bit3kkb) ([raw file](https://github.com/cockroachdb/pebble/blob/d8ee6a9f686cb45f065fafbdfc663abd354dcd12/compaction_iter_test.go#L86)):*
> ```Go
> 	fileFunc := func(formatVersion FormatMajorVersion) string {
> 		if formatVersion < FormatSetWithDelete {
> 			return "testdata/compaction_iter"
> ```

Maybe reviewable is confused but looks like these existing testdata files like compaction_iter, manual_compaction, single_del_manual_compaction have been removed.
___
*[compaction_iter_test.go, line 223 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mjb-K230-xTMYc1Eleb:-Mjb-K230-xTMYc1Elec:b6o6qdh) ([raw file](https://github.com/cockroachdb/pebble/blob/d8ee6a9f686cb45f065fafbdfc663abd354dcd12/compaction_iter_test.go#L223)):*
> ```Go
> 	for _, formatVersion := range formatVersions {
> 		t.Run(fmt.Sprintf("version-%s", formatVersion), func(t *testing.T) {
> 			runTest(formatVersion)
> ```

I think we should be passing `t` to `runTest` and not using the `t` that is in the context of that closure.
___
*[compaction_test.go, line 1130 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mjb0Wdk6tfbfNqXpy-I:-Mjb0Wdk6tfbfNqXpy-J:bli9t3) ([raw file](https://github.com/cockroachdb/pebble/blob/88a1b55857575737e0fc2e4c78329b263e461171/compaction_test.go#L1130)):*
> ```Go
> 		}
> 		opts.private.disableAutomaticCompactions = true
> 		opts.testingRandomized()
> ```

how about keeping this randomization of version but changing it to opts.testingRandomized(minVersion, maxVersion) which represents the range [minVersion, maxVersion). Then change the testCases struct to have the min and max versions instead of the specific version. That way we get better coverage.
___
*[compaction_test.go, line 1328 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mjb-mZq6ZUJtLzpAnOJ:-Mjb-mZq6ZUJtLzpAnOK:b-3xhj6i) ([raw file](https://github.com/cockroachdb/pebble/blob/d8ee6a9f686cb45f065fafbdfc663abd354dcd12/compaction_test.go#L1328)):*
> ```Go
> 	for _, tc := range testCases {
> 		t.Run(fmt.Sprintf("version-%s", tc.formatVersion), func(t *testing.T) {
> 			runTest(tc.testData, tc.formatVersion)
> ```

same comment about passing `t` as a parameter.
___
*[format_major_version.go, line 66 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mjb1JWx6ylK2uBVgzjD:-Mjb1JWx6ylK2uBVgzjE:b-v91yts) ([raw file](https://github.com/cockroachdb/pebble/blob/d8ee6a9f686cb45f065fafbdfc663abd354dcd12/format_major_version.go#L66)):*
> ```Go
> 	FormatVersioned
> 	// FormatSetWithDelete is a format major version that introduces a new key
> 	// kind, base.InternalKeyKindSetWithDelete. Previous Pebble version will be
> ```

how about the following phrasing, since by definition they are not aware of this new key kind.
... versions will be unable to open this database.


<!-- Sent from Reviewable.io -->

2021-09-15 03:47 UTC, nicktrav reviewed
> Reviewed 1 of 17 files at r11.
> Dismissed @sumeerbhola from 8 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261)* status: 15 of 25 files reviewed, 1 unresolved discussion (waiting on @nicktrav, @petermattis, and @sumeerbhola)

___
*[-- commits, line 10 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mjb3B-b9jqpTfjqg9lx):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

key
</blockquote></details>

Done.
___
*[compaction_iter.go, line 517 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjazYuaAxAmmoLSukFz:-MjbJw-sCZ0daWO2tocM:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d8ee6a9f686cb45f065fafbdfc663abd354dcd12/compaction_iter.go#L517)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

supports
</blockquote></details>

Done.
___
*[compaction_iter.go, line 522 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-MjazhRg4e_QV7ofJi3V:-MjbKx860lNXjcPoETsV:bsn4v55) ([raw file](https://github.com/cockroachdb/pebble/blob/d8ee6a9f686cb45f065fafbdfc663abd354dcd12/compaction_iter.go#L522)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you hoist this before the `valueBuf` logic.
</blockquote></details>

Done. Merged the check with the other return-early check.
___
*[compaction_iter_test.go, line 86 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mjb2_0S7B6UvDO66ZrH:-MjbL4sM6HX9t4nnG6-a:b-aslap) ([raw file](https://github.com/cockroachdb/pebble/blob/d8ee6a9f686cb45f065fafbdfc663abd354dcd12/compaction_iter_test.go#L86)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Maybe reviewable is confused but looks like these existing testdata files like compaction_iter, manual_compaction, single_del_manual_compaction have been removed.
</blockquote></details>

Good catch. That was a silly on my part. Fixed.
___
*[compaction_iter_test.go, line 223 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mjb-K230-xTMYc1Eleb:-MjbM4L88LdqvDjkVmPL:bt2vr1b) ([raw file](https://github.com/cockroachdb/pebble/blob/d8ee6a9f686cb45f065fafbdfc663abd354dcd12/compaction_iter_test.go#L223)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we should be passing `t` to `runTest` and not using the `t` that is in the context of that closure.
</blockquote></details>

Fixed.
___
*[compaction_test.go, line 1130 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mjb0Wdk6tfbfNqXpy-I:-MjbX6XpB8CfqD3DLC1m:b-h71838) ([raw file](https://github.com/cockroachdb/pebble/blob/88a1b55857575737e0fc2e4c78329b263e461171/compaction_test.go#L1130)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about keeping this randomization of version but changing it to opts.testingRandomized(minVersion, maxVersion) which represents the range [minVersion, maxVersion). Then change the testCases struct to have the min and max versions instead of the specific version. That way we get better coverage.
</blockquote></details>

I updated this to pick a random version in a given range. I opted to do the randomization in the test itself, rather than modifying all existing callers of `testingRandomized` to accept a version. This seemed reasonable, given this is the only test that has the requirement for a range of values.
___
*[compaction_test.go, line 1328 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mjb-mZq6ZUJtLzpAnOJ:-MjbMN_nA3gzd6xo6L-s:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d8ee6a9f686cb45f065fafbdfc663abd354dcd12/compaction_test.go#L1328)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same comment about passing `t` as a parameter.
</blockquote></details>

Done.
___
*[format_major_version.go, line 66 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mjb1JWx6ylK2uBVgzjD:-MjbMaxI4eIyb6iBN_4y:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d8ee6a9f686cb45f065fafbdfc663abd354dcd12/format_major_version.go#L66)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about the following phrasing, since by definition they are not aware of this new key kind.
... versions will be unable to open this database.


</blockquote></details>

Done.
___
*[internal/base/internal.go, line 53 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1261#-Mja9-jFAgdn0_sCiwkZ:-MjbMk681glflu3u8Dmf:b1ku7gi) ([raw file](https://github.com/cockroachdb/pebble/blob/a754ba7cf9221bfc3c67882bd0177acf400f22ed/internal/base/internal.go#L53)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think this needs to be 18, because the comment here says it is equal to the largest used key kind. Which means the other place I suggested using an array needs to use `bool[InternalKeyKindMax+1]`.
</blockquote></details>

Unfortunately doing that breaks things elsewhere. Specifically the `internalKeyKindNames` slice definition below. As the key kind is used as an index into the slice, we can't re-use.

One way to fix this is to just remove "MAX" from the slice - given it's not part of the file format, we shouldn't need to look it up. Making this change doesn't seem to break anything elsewhere. I've pushed this change.

There is still the test failure of `TestFixtureOutput` in `writer_fixture_test.go` that we need to look into. It looks like the existing `InternalKeyKindMax` has somehow leaked into the sstables that are generated as fixtures, so now that the max value has been incremented, it's breaking the generated output in the test.


<!-- Sent from Reviewable.io -->

2021-09-15 16:36 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 17 files at r11, 9 of 9 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1261#-:-MjeJEHi7uS3QgBkt-cQ:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @petermattis and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-09-16 02:08 UTC, merged

2021-09-16 02:10 UTC, nicktrav commented
TFTR!

Also forgot to note that I did another two hour burn of the meta tests and nothing cropped up.