db: improve use-after-free test coverage for compactions
cockroachdb/pebble pull request #1267
Opened 2021-09-13 21:50 UTC by nicktrav

To increase confidence that use-after-free bugs are not present on
compaction codepaths, use the `invalidatingIter` wrapper to mutate the
previous key and value during iteration.

Alter the `invalidatingIter` to avoid zeroing range deletion key / value
pairs, which aligns with the current assumption
`(*compactionIter).Next()`.

Add an in-line comment to point out that storage of a reference to the
previous key / value pairs is safe for range deletion keys during
compaction iteration.

Enable some previously dead code to mutate released byte slices. This
allows for easier detection of use-after-free-type bugs.

2021-09-13 21:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1267)
<!-- Reviewable:end -->

2021-09-13 21:51 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1267)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @sumeerbhola)

___
*[iterator_test.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1267#-MjW826EE1a90fIzq4vG:-MjW826EE1a90fIzq4vH:b-antllk) ([raw file](https://github.com/cockroachdb/pebble/blob/a3ae56a276feb5b9e3b7a9a4c374ec4c7014d303/iterator_test.go#L221)):*
> ```Go
> 	lastKey     *InternalKey
> 	lastValue   []byte
> 	ignoreKinds map[base.InternalKeyKind]struct{}
> ```

I had an original version of this patch that always skipped invalidation of RangeDeletes. This reduces the coupling a little.


<!-- Sent from Reviewable.io -->

2021-09-13 22:02 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1267)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[internal/cache/value_invariants.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1267#-MjWARYH91tlsCGKhQEi:-MjWARYH91tlsCGKhQEj:bk0nbl5) ([raw file](https://github.com/cockroachdb/pebble/blob/a3ae56a276feb5b9e3b7a9a4c374ec4c7014d303/internal/cache/value_invariants.go#L46)):*
> ```Go
> 	// When "invariants" are enabled set the value contents to 0xff in order to
> 	// cache use-after-free bugs.
> 	for i := range v.buf {
> ```

cc: @petermattis - I wasn't sure if there was any particular reason or history as to why this was commented out. Hopefully it's fine to enable.


<!-- Sent from Reviewable.io -->

2021-09-14 00:34 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1267)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[internal/cache/value_invariants.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1267#-MjWARYH91tlsCGKhQEi:-MjWgxOV3_sU0-PWSFKE:by20syc) ([raw file](https://github.com/cockroachdb/pebble/blob/a3ae56a276feb5b9e3b7a9a4c374ec4c7014d303/internal/cache/value_invariants.go#L46)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

cc: @petermattis - I wasn't sure if there was any particular reason or history as to why this was commented out. Hopefully it's fine to enable.
</blockquote></details>

I have a vague recollection that this was slow for some reason. I can't recall if the slowness was when running normal tests or running the metamorphic test. And possibly I'm just completely misremembering. Doesn't seem like it should be slow. I'm fine with re-enabling and watching for any fallout.


<!-- Sent from Reviewable.io -->

2021-09-14 02:20 UTC, sumeerbhola requested changes
code change looks fine

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1267#-:-MjX5i4V7qo_X8qQNTPp:brcico)* status: all files reviewed, 3 unresolved discussions (waiting on @itsbilal and @nicktrav)

___
*[compaction_iter.go, line 270 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1267#-MjWusm79O7v_1U5kiT5:-MjWusm79O7v_1U5kiT6:bafw90y) ([raw file](https://github.com/cockroachdb/pebble/blob/a3ae56a276feb5b9e3b7a9a4c374ec4c7014d303/compaction_iter.go#L270)):*
> ```Go
> 			//
> 			// Note that storing and returning a reference to the key and value
> 			// here is safe. There is no risk that these stored values that are
> ```

I am not sure this is the right comment

- A `blockIter` provides a value stability guarantee for RANGEDELs since there is only 1 rangedel block in an sstable and this blockIter will not release the bytes for this block until it is closed.
This statement can be added to the code comment above the `blockIter` struct that already talks about key stability.

- Translating this per `blockIter` guarantee into a key and value stability guarantee for the lifetime of the iterator tree in which this `blockIter` is a leaf is tricky. `levelIter` opens and closes iterators so there is nothing preventing the `blockIter` from being closed, which would release the memory. However, `compactionIter` construction in `compaction.newInputIter` is wrapping the rangedel `blockIter` in a `noCloseIter` to provide this stability guarantee.
   We already have a comment there. But we could probably use a comment at the top of `compaction_iter.go` saying that because of the construction scheme in `compaction.newInputIter` we can rely on key and value stability of rangedels for the lifetime of the compactionIter (but see next bullet -- we don't actually have a key stability guarantee)

- The use of `saveKey` in `compactionIter` has nothing to do with the key stability guarantee for rangedels, which is for the lifetime of the `compactionIter`, while this `saveKey` will overwrite much earlier. In fact saving the key and returning that saved key destroys the key stability guarantee since now we are not returning the original slice backed by the block's memory. I think this is working because the caller is doing `cloneKey` to restore the stability guarantee that we accidentally destroyed here. It is possible that if we returned `i.iterKey` here that we could remove that clone. Let us not make this change now, but add a TODO to investigate this.

- I think we use `saveKey` primarily as a requirement for anyone trying to transitively call `nextInStripe` (including calls via `skipInStripe`). This `nextInStripe` call could be because we are calling it now, or in a later call to Next because we've set `skip=true` before returning. `nextInStripe` needs the saved key to compare with the latest `iterKey` so that it can know when it has stepped to the next user key. I think we should add a code comment about this invariant required by `nextInStripe`. I think the one exception to this use of `saveKey` is the one here, and as I said earlier I'm not sure it is necessary -- we may be just blindly following the idiom that we return `i.key` (note that we say "This is the case on return from all public methods" where `i.key` is declared). Which is fine -- code simplicity is sometimes better than performance and rangedels are not that common.
___
*[iterator_test.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1267#-MjW826EE1a90fIzq4vG:-MjX5PBsBcVa8bPSOQU1:bv2q201) ([raw file](https://github.com/cockroachdb/pebble/blob/a3ae56a276feb5b9e3b7a9a4c374ec4c7014d303/iterator_test.go#L221)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

I had an original version of this patch that always skipped invalidation of RangeDeletes. This reduces the coupling a little.
</blockquote></details>

mild preference for doing `ignoreKinds [InternalKeyKindMax]bool` instead of a map.


<!-- Sent from Reviewable.io -->

2021-09-14 04:25 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1267)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[iterator_test.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1267#-MjW826EE1a90fIzq4vG:-MjXYCLsBH996I7SWyjZ:b4c9lyr) ([raw file](https://github.com/cockroachdb/pebble/blob/a3ae56a276feb5b9e3b7a9a4c374ec4c7014d303/iterator_test.go#L221)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

mild preference for doing `ignoreKinds [InternalKeyKindMax]bool` instead of a map.
</blockquote></details>

:thumbsup: 
___
*[internal/cache/value_invariants.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1267#-MjWARYH91tlsCGKhQEi:-MjXVug0AX7VAeGgM14C:b-wdalyy) ([raw file](https://github.com/cockroachdb/pebble/blob/a3ae56a276feb5b9e3b7a9a4c374ec4c7014d303/internal/cache/value_invariants.go#L46)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I have a vague recollection that this was slow for some reason. I can't recall if the slowness was when running normal tests or running the metamorphic test. And possibly I'm just completely misremembering. Doesn't seem like it should be slow. I'm fine with re-enabling and watching for any fallout.
</blockquote></details>

Cool, thanks. Will keep for now, and monitor.


<!-- Sent from Reviewable.io -->

2021-09-14 15:25 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1267)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @sumeerbhola)

___
*[compaction_iter.go, line 270 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1267#-MjWusm79O7v_1U5kiT5:-MjZu28x0t_PVgv44TBb:b-ieq5et) ([raw file](https://github.com/cockroachdb/pebble/blob/a3ae56a276feb5b9e3b7a9a4c374ec4c7014d303/compaction_iter.go#L270)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am not sure this is the right comment

- A `blockIter` provides a value stability guarantee for RANGEDELs since there is only 1 rangedel block in an sstable and this blockIter will not release the bytes for this block until it is closed.
This statement can be added to the code comment above the `blockIter` struct that already talks about key stability.

- Translating this per `blockIter` guarantee into a key and value stability guarantee for the lifetime of the iterator tree in which this `blockIter` is a leaf is tricky. `levelIter` opens and closes iterators so there is nothing preventing the `blockIter` from being closed, which would release the memory. However, `compactionIter` construction in `compaction.newInputIter` is wrapping the rangedel `blockIter` in a `noCloseIter` to provide this stability guarantee.
   We already have a comment there. But we could probably use a comment at the top of `compaction_iter.go` saying that because of the construction scheme in `compaction.newInputIter` we can rely on key and value stability of rangedels for the lifetime of the compactionIter (but see next bullet -- we don't actually have a key stability guarantee)

- The use of `saveKey` in `compactionIter` has nothing to do with the key stability guarantee for rangedels, which is for the lifetime of the `compactionIter`, while this `saveKey` will overwrite much earlier. In fact saving the key and returning that saved key destroys the key stability guarantee since now we are not returning the original slice backed by the block's memory. I think this is working because the caller is doing `cloneKey` to restore the stability guarantee that we accidentally destroyed here. It is possible that if we returned `i.iterKey` here that we could remove that clone. Let us not make this change now, but add a TODO to investigate this.

- I think we use `saveKey` primarily as a requirement for anyone trying to transitively call `nextInStripe` (including calls via `skipInStripe`). This `nextInStripe` call could be because we are calling it now, or in a later call to Next because we've set `skip=true` before returning. `nextInStripe` needs the saved key to compare with the latest `iterKey` so that it can know when it has stepped to the next user key. I think we should add a code comment about this invariant required by `nextInStripe`. I think the one exception to this use of `saveKey` is the one here, and as I said earlier I'm not sure it is necessary -- we may be just blindly following the idiom that we return `i.key` (note that we say "This is the case on return from all public methods" where `i.key` is declared). Which is fine -- code simplicity is sometimes better than performance and rangedels are not that common.

</blockquote></details>

Thanks for the clarification. I've added some extra documentation elsewhere, and removed the original comment. This should be good for another look.


<!-- Sent from Reviewable.io -->

2021-09-14 16:54 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1267#-:-Mj_Dk5n4VBqxBKFFgwW:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[compaction_iter.go, line 451 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1267#-Mj_CkGL3jsjPh3w96Ko:-Mj_CkGL3jsjPh3w96Kp:b-4g7mzo) ([raw file](https://github.com/cockroachdb/pebble/blob/21ad9b9f49e711ba88d6f2264c77e906de855dba/compaction_iter.go#L451)):*
> ```Go
> // indicating how its state changed.
> //
> // Calls to nextInStripe are typically preceded by a call to saveKey to retain a
> ```

nit: I think this could be more strongly stated as "Calls to nextInStripe must be preceded by a call ...".
We need that for the `i.cmp(i.key.UserKey, key.UserKey)` calls in this function.
___
*[iterator_test.go, line 227 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1267#-Mj_DFa0BLjlQZygvVdt:-Mj_DFa14nQ45TuZIF5P:babyl8k) ([raw file](https://github.com/cockroachdb/pebble/blob/21ad9b9f49e711ba88d6f2264c77e906de855dba/iterator_test.go#L227)):*
> ```Go
> 	return &invalidatingIter{
> 		iter:        iter,
> 		ignoreKinds: make([]bool, 1<<8 /* 8 bits for key kinds */),
> ```

nit: any reason to use a slice instead of the array sized using `InternalKeyKindMax`? Also, it would be nice if we didn't have `1<<8` here and could use an existing enum for sizing.


<!-- Sent from Reviewable.io -->

2021-09-14 17:12 UTC, nicktrav reviewed
> Dismissed @sumeerbhola from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1267)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @itsbilal and @sumeerbhola)

___
*[compaction_iter.go, line 451 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1267#-Mj_CkGL3jsjPh3w96Ko:-Mj_FtRk81F9X3jQBqqQ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/21ad9b9f49e711ba88d6f2264c77e906de855dba/compaction_iter.go#L451)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: I think this could be more strongly stated as "Calls to nextInStripe must be preceded by a call ...".
We need that for the `i.cmp(i.key.UserKey, key.UserKey)` calls in this function.
</blockquote></details>

Done.
___
*[iterator_test.go, line 227 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1267#-Mj_DFa0BLjlQZygvVdt:-Mj_H2Bh6_qIUnCyDDax:bt3s5l) ([raw file](https://github.com/cockroachdb/pebble/blob/21ad9b9f49e711ba88d6f2264c77e906de855dba/iterator_test.go#L227)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: any reason to use a slice instead of the array sized using `InternalKeyKindMax`? Also, it would be nice if we didn't have `1<<8` here and could use an existing enum for sizing.
</blockquote></details>

Ah, I see what you meant now. That field isn't part of the file format and can change. Updated to use that.


<!-- Sent from Reviewable.io -->

2021-09-14 17:20 UTC, merged

2021-09-14 17:20 UTC, nicktrav commented
TFTR!