sstable: add suffix replacement block transform
cockroachdb/pebble pull request #1314
Opened 2021-10-01 21:13 UTC by jbowens

In CockroachDB, there exist processes that build and ingest sstables.
These sstables have timestamp-suffixed MVCC keys. Today, these keys'
timestamps are dated in the past and rewrite history. This rewriting
violates invariants in parts of the system. We would like to support
ingesting these sstables with recent, invariant-maintaing MVCC
timestamps. However, ingestion is used during bulk operations, and
rewriting large sstables' keys with a recent MVCC timestamp is
infeasibly expensive.

This change introduces a facility for constructing an sstable with a
placeholder suffix. When using this facility, a caller specifies a
SuffixPlaceholder write option. The caller is also required to configure
a Comparer that contains a non-nil Split function. When configured with
a suffix placeholder, the sstable writer requires that all keys that
have a suffix (as determined by Split) that exactly matches the provided
SuffixPlaceholder. An sstable constructed in this fashion is still
incomplete and unable to be read unless explicitly permitted through the
AllowUnreplacedSuffix option.

When a caller would like to complete an sstable constructed with a
suffix placeholder, they may call ReplaceSuffix providing the
original placeholder value and the replacement value. The placeholder
and replacement values are required to be equal lengths. ReplaceSuffix
performs an O(1) write to record the replacement value.

After a suffix replacement the resulting sstable is complete, and
sstable readers may read the sstable. Readers will perform a block
transform to replace suffix placeholders with the replacement value on
the fly as blocks are loaded.

Informs cockroachdb/cockroach#70422.
Adapted from #1233.

2021-10-01 21:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1314)
<!-- Reviewable:end -->

2021-10-01 21:22 UTC, jbowens reviewed
I'd like to flesh out the testing more, probably coping some of the testing from #1233. I figured I'd put it up for an initial review first.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1314#-:-Mkxitp04i3EadsZS6DG:b-cpu9cu)* status: 0 of 12 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-10-15 11:28 UTC, erikgrinaker reviewed
Looks good overall!

@dt did a benchmark (see [internal Slack thread](https://cockroachlabs.slack.com/archives/C021WMUML04/p1629322927025800)) of his prototype that showed negligible overhead (1-3%) when reading synthesized timestamps. I expect similar overhead here, but can we run a few benchmarks to check?

> Do any of a range's keyspaces contain both keys that require MVCC timestamp replacement and keys that must not undergo timestamp replacement but still contain MVCC timestamps? I believe the answer to be no.

I also think that's right. In the common case we have to uphold MVCC invariants, so all writes must be at the current timestamp (thus all keys' timestamps can be replaced). In the exceptional cases where we want to write historical data (e.g. during streaming replication into virgin keyspans), I do not see why we would need timestamp replacement.

I guess the one edge case to be mindful of here is intents, whose interleaved form had MVCC timestamp 0. Although now that we have migrated to separated intents, which use a different timestamp-less key encoding, I don't think it's a problem. I'm also not sure why we would need to write intents in an SSTable that uses timestamp replacement.

In any case, I suppose there's nothing stopping us from relaxing this requirement later, if necessary (?).

> we might as well just make it a valid timestamp. my prototype just used a giant future time like 0f00 << 62 and logical 1 or something like that which I figured would be readily recognized if we ever saw it show up un-replaced.

This seems reasonable.

> Reviewed 3 of 12 files at r1, 6 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1314#-:-Mm2c7tbCedbsCUUwViN:bba61a5)* status: all files reviewed, 4 unresolved discussions (waiting on @dt, @jbowens, and @sumeerbhola)

___
*[sstable/reader.go, line 1988 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1314#-Mm2XP1R6j_pThiV8V0M:-Mm2XP1R6j_pThiV8V0N:b6gxd2k) ([raw file](https://github.com/cockroachdb/pebble/blob/942c2952f6d1b425f0f49a9d635ae055d9c5113b/sstable/reader.go#L1988)):*
> ```Go
> 	// concatenated with the replacement value. Values are required to
> 	// be equal length. The SuffixReplacement property was already
> 	// validated in when the reader was constructed.
> ```

nit: stray "in"


<!-- Sent from Reviewable.io -->

2021-10-19 01:18 UTC, sumeerbhola requested changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1314)* status: all files reviewed, 8 unresolved discussions (waiting on @dt, @jbowens, and @sumeerbhola)

___
*[sstable/options.go, line 203 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1314#-MmL6Tb2A1XhZceAFCvJ:-MmL6Tb31cRYQQzvUscB:bnefa8p) ([raw file](https://github.com/cockroachdb/pebble/blob/747770e11c0fdb5a0ffae39fac52747328f2af4a/sstable/options.go#L203)):*
> ```Go
> 	// value.
> 	//
> 	// When a SuffixPlaceholder is set, all added keys must contain a a
> ```

nit: extra "a"
___
*[sstable/reader.go, line 2000 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1314#-MmL6eHB0BImdVC34pRM:-MmL6eHB0BImdVC34pRN:b-xcx6cf) ([raw file](https://github.com/cockroachdb/pebble/blob/747770e11c0fdb5a0ffae39fac52747328f2af4a/sstable/reader.go#L2000)):*
> ```Go
> 		switch {
> 		case split == len(key.UserKey):
> 			panic(errors.New("pebble: suffix replacement sstable contains key without a suffix"))
> ```

I didn't expect to see a panic here, since this could happen due to corruption. Return error instead?
___
*[sstable/writer.go, line 813 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1314#-MmL74DdCAopfpPORcbJ:-MmL74DdCAopfpPORcbK:b-p6jq9c) ([raw file](https://github.com/cockroachdb/pebble/blob/747770e11c0fdb5a0ffae39fac52747328f2af4a/sstable/writer.go#L813)):*
> ```Go
> 	if len(o.SuffixPlaceholder) > 0 {
> 		w.separator = func(dst, a, b []byte) []byte { return a }
> 		w.successor = func(dst, a []byte) []byte { return a }
> ```

It would be nice to have a unit test that would have failed because the index was lying about the range of keys in a block.


<!-- Sent from Reviewable.io -->

2021-10-19 01:22 UTC, dt commented
>  the caller (e.g. an IMPORT) first has to construct the SSTable with the SuffixReplacement option and appropriate timestamps, but then also call AddSSTable with the placeholder timestamp as an RPC parameter

FWIW, on the cockroach side, I wonder if we can just have well-known "placeholder timestamp", e.g. defined by pkg/storage, which is what a wrapped SSTWriter uses and is what evalAddSSTable always passes to ReplaceSuffix if a single boolean arg, which indicates this is an sst constructed with the standard placeholder which expects its replacement with the batch timestamp, is passed? I dunno, I like the explicit from/to suffix in the pebble API, but I don't know if that means we have to have it mirrored 1:1 in the kv rpc api.

2021-10-19 12:59 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1314)* status: all files reviewed, 9 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)

___
*[sstable/properties.go, line 140 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1314#-MmMiL4o5a-tPhXwhe5_:-MmNZBRrEJVBLzxrZCXE:b-oydoye) ([raw file](https://github.com/cockroachdb/pebble/blob/747770e11c0fdb5a0ffae39fac52747328f2af4a/sstable/properties.go#L140)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

How about allowing the placeholder and replacement to have different lengths? We could set an upper bound at e.g. 256 bytes and use length-prefixed encoding in a fixed-size buffer. This is based on the possibly naïve assumption that the fixed-length restriction is only to be able to update the replacement suffix in place.
</blockquote></details>

I'm not sure I understand what you mean by "we no longer use a unique timestamp encoding"?

I was thinking we're probably not going to feel the extra bytes since we're adding a bunch of keys with _identical_ bytes, so snappy should be pretty effective on them, or were you thinking in the block cache.

If we were trying to save space in the block cache, we'd need to re-allocate the smaller block and then shift everything down during replacement, which could mean moving big values around, vs just editing a few key bytes now. I'm dubious it is worth it to sometimes save 4b per key?  (nit: it is  4, right? just the potentially extra zero logical? we don't need to leave room for a synthetic byte do we?) 

I suppose we could at least remove extra zero logical during compaction, with a custom merge op that runs iff the sst has the replacement prop, so they don't keep taking up space, but I still suspect it isn't worth worrying about?


<!-- Sent from Reviewable.io -->

2021-10-19 13:17 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1314)* status: all files reviewed, 9 unresolved discussions (waiting on @dt, @jbowens, and @sumeerbhola)

___
*[sstable/properties.go, line 140 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1314#-MmMiL4o5a-tPhXwhe5_:-MmNdE0kC_4oPThDClJw:bw8kri4) ([raw file](https://github.com/cockroachdb/pebble/blob/747770e11c0fdb5a0ffae39fac52747328f2af4a/sstable/properties.go#L140)):*
>I'm not sure I understand what you mean by "we no longer use a unique timestamp encoding"?

Previously, any given MVCC timestamp would encode to exactly one binary representation in Pebble. If we have to use fixed-length timestamps with these SST replacements then that is no longer true, as the same MVCC timestamp can have two different representations in Pebble: one variable-length (often 8 bytes) and one fixed-length (13 bytes). This could presumably cause problems with comparisons, where two timestamps that are semantically equal appear different to Pebble. I don't know if this will end up actually mattering, hence the question, but it's the sort of thing it's worth being careful about and I think it would be nice if we could avoid it altogether.

>I was thinking we're probably not going to feel the extra bytes since we're adding a bunch of keys with identical bytes, so snappy should be pretty effective on them, or were you thinking in the block cache.

I think the space thing is a secondary concern, and you're probably right that it won't matter all that much post-compression and such. But if we were to allow variable-length replacements then the space savings would be a nice added benefit.

>(nit: it is 4, right? just the potentially extra zero logical? we don't need to leave room for a synthetic byte do we?)

I'm not sure if the synthetic byte actually matters at this level, but it is part of the binary encoding so presumably there's a reason for that?


<!-- Sent from Reviewable.io -->

2021-10-19 13:24 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1314)* status: all files reviewed, 9 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)

___
*[sstable/properties.go, line 140 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1314#-MmMiL4o5a-tPhXwhe5_:-MmNhU9Z23QYpPBEBR3Q:bgqukjj) ([raw file](https://github.com/cockroachdb/pebble/blob/747770e11c0fdb5a0ffae39fac52747328f2af4a/sstable/properties.go#L140)):*
> Previously, any given MVCC timestamp would encode to exactly one binary representation in Pebble. If we have to use fixed-length timestamps with these SST replacements then that is no longer true, as the same MVCC timestamp can have two different representations in Pebble: one variable-length (often 8 bytes) and one fixed-length (13 bytes). This could presumably cause problems with comparisons, where two timestamps that are semantically equal appear different to Pebble. I don't know if this will end up actually mattering, hence the question, but it's the sort of thing it's worth being careful about and I think it would be nice if we could avoid it altogether.

This is a good catch. It does matter as we do bytes comparison on the suffix in a few places. See https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/pebble.go#L109-L119.


<!-- Sent from Reviewable.io -->

2021-10-19 16:09 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1314)* status: all files reviewed, 9 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)

___
*[sstable/properties.go, line 140 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1314#-MmMiL4o5a-tPhXwhe5_:-MmOIL-H2ZQI-KMM3Nks:b-dxir8n) ([raw file](https://github.com/cockroachdb/pebble/blob/747770e11c0fdb5a0ffae39fac52747328f2af4a/sstable/properties.go#L140)):*
> Is there a compelling reason why we can't allow variable-length replacements (with an upper bound)? I believe that would avoid this entirely.

The encoding of a KV in an sstable block is `<varint><key-bytes><varint><value-bytes>`. So if you change the length of the key you have to rewrite the value and all subsequent KVs in the block. I think Jackson alluded to this above. If we want to change the length of the suffix we'd have to rewrite the block. Perhaps this isn't too bad as we're only doing this when the block is loaded. It just makes the transform more complex.


<!-- Sent from Reviewable.io -->

2021-10-19 18:06 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1314)* status: all files reviewed, 9 unresolved discussions (waiting on @dt, @jbowens, @petermattis, and @sumeerbhola)

___
*[sstable/properties.go, line 140 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1314#-MmMiL4o5a-tPhXwhe5_:-MmOiV-zDWsqAiYOpRl1:bm4hp5i) ([raw file](https://github.com/cockroachdb/pebble/blob/747770e11c0fdb5a0ffae39fac52747328f2af4a/sstable/properties.go#L140)):*
I've been thinking along the same lines, let me chew on it for a bit.

> I think we could just always tick the logical in the client sending those requests

The txn's write timestamp might still get pushed to one without a logical component.


<!-- Sent from Reviewable.io -->

2021-11-24 17:34 UTC, jbowens commented
Closing this out in favor of write-time replacement (eg, #1384).

2021-11-24 17:34 UTC, closed without merging

2022-03-08 00:01 UTC, sumeerbhola commented
@nvanbenschoten see the discussion starting at https://github.com/cockroachdb/pebble/pull/1314#pullrequestreview-782980880

@erikgrinaker @jbowens @dt: Nathan has another case where two different suffix byte slices must compare as equal and he is planning to change the comparison and equality functions in Pebble (this is for local timestamps https://github.com/cockroachdb/cockroach/pull/77342).
We could consider doing the same here -- the risk is the repeated performance cost of a more sophisticated comparison versus a one time more expensive rewrite in AddSSTable.

2022-03-08 09:33 UTC, erikgrinaker commented
> Nathan has another case where two different suffix byte slices must compare as equal and he is planning to change the comparison and equality functions in Pebble

I'd be very careful with this, since it wouldn't surprise me if we just did `bytes.Compare()` or something similar in a bunch of places. I also find it unfortunate that we're leaking additional timestamps down into MVCC keys -- but I'm sure Nathan has given this a lot of thought, and I haven't looked at this closely enough to offer any viable alternatives.

> We could consider doing the same here

We ended up rewriting SSTs at request time, and avoiding it altogether when the request wasn't pushed, which got us to within 5% overhead. That seems like a simpler and more robust solution for our use in any case. But I'll keep this in mind if we should need it sometime (ranged intents with constant-time commits come to mind).

2022-03-08 14:42 UTC, sumeerbhola commented
> I also find it unfortunate that we're leaking additional timestamps down into MVCC keys -- but I'm sure Nathan has given this a lot of thought, and I haven't looked at this closely enough to offer any viable alternatives.

The local timestamps are going into the key because of the following discussion https://github.com/cockroachdb/cockroach/pull/72121#issuecomment-955038874, and it is likely that older version values are going to be in value sections of an sstable for v22.2.

2022-03-08 14:54 UTC, erikgrinaker commented
>The local timestamps are going into the key because of the following discussion https://github.com/cockroachdb/cockroach/pull/72121#issuecomment-955038874, and it is likely that older version values are going to be in value sections of an sstable for v22.2.

I see. I realize that I'm late to the party here, but all else being equal, I have a strong preference for keeping this timestamp in the value unless we have a demonstrated significant performance gain. Keys should be unique identifiers, and this timestamp is not an identifier. I'll reiterate my concerns from the previous discussion above.

2022-03-08 14:57 UTC, nvanbenschoten commented
> I'd be very careful with this, since it wouldn't surprise me if we just did bytes.Compare() or something similar in a bunch of places.

We already provide Pebble a [custom key comparator](https://github.com/cockroachdb/cockroach/blob/d384f953bc238b818f0c8aca41c7234792134837/pkg/storage/pebble.go#L136), so `bytes.Compare()` is not a valid way to determine order of _versioned_ MVCC keys today. The primary change that we'll be making in https://github.com/cockroachdb/cockroach/pull/77342 is to also provide Pebble with a custom key equality function as well, so that `bytes.Equal` will no longer be a valid way to determine equality of _versioned_ MVCC keys.

I'm still in the process of confirming that this will have a negligible impact on performance. From a quick glance around, it appears that Pebble's `Compare` function is used on much hotter paths than its `Equal` function, but I'd like to confirm that.

If this ends up being workable then it will be trivial and cheap to normalize a zero logical component to no logical component in the two comparator functions.