cmd: lower the default L0 sub-level count for write benchmarks
cockroachdb/pebble pull request #1370
Opened 2021-11-11 18:50 UTC by nicktrav

Match the values that Cockroach Admission Control uses as limits for L0
sub-level file and level count.

Split out the defaults to constants, with associated comment explaining
the reasoning for using the particular values.

Related to #1369.

2021-11-11 18:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1370)
<!-- Reviewable:end -->

2021-11-16 01:46 UTC, sumeerbhola requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1370)* status: all files reviewed, 1 unresolved discussion (waiting on @nicktrav)

___
*[cmd/pebble/write_bench.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1370#-MoaOvscBglT2-CKkC3D:-MoaOvscBglT2-CKkC3E:b6lge7k) ([raw file](https://github.com/cockroachdb/pebble/blob/de7ec63b6ac82b36b87a7e9a7c9d21d3895f417a/cmd/pebble/write_bench.go#L23)):*
> ```Go
> // See: https://github.com/cockroachdb/cockroach/blob/8f24d350aef508e14b74546fc5f24f52a51548d9/pkg/util/admission/granter.go#L790-L804
> const (
> 	defaultL0FileLimit     = 1_000
> ```

1_000?

you must be looking at an old version.
it is 20 here https://github.com/cockroachdb/cockroach/blob/master/pkg/util/admission/granter.go#L1229

I should have looked when you mentioned this on slack.
I now remember that I'd started with 10, but changed it to 20 later.


<!-- Sent from Reviewable.io -->

2021-11-16 01:54 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1370)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[cmd/pebble/write_bench.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1370#-MoaOvscBglT2-CKkC3D:-MoaRhYY0Ejzr74Rh0fA:b-gx4rxt) ([raw file](https://github.com/cockroachdb/pebble/blob/de7ec63b6ac82b36b87a7e9a7c9d21d3895f417a/cmd/pebble/write_bench.go#L23)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

1_000?

you must be looking at an old version.
it is 20 here https://github.com/cockroachdb/cockroach/blob/master/pkg/util/admission/granter.go#L1229

I should have looked when you mentioned this on slack.
I now remember that I'd started with 10, but changed it to 20 later.

</blockquote></details>

Oh how weird. Thanks for double checking. I've reverted to 20.


<!-- Sent from Reviewable.io -->

2021-11-16 14:26 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1370#-:-Mod8APU095jkuY80bCE:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-11-16 16:28 UTC, nicktrav commented
TFTR!

2021-11-16 16:28 UTC, merged