batch: add RangeKey{Set,Unset,Delete} methods
cockroachdb/pebble pull request #1386
Opened 2021-11-24 16:56 UTC by jbowens

Add key kinds for range key sets, unsets and deletes. Add corresponding methods
to the Batch, behind an experimental type. With this commit, these keys may be
encoded into a batch but are discarded when committed.

2021-11-24 16:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1386)
<!-- Reviewable:end -->

2021-11-24 21:45 UTC, sumeerbhola requested changes
I didn't finish reading -- flushing some comments.

> Reviewed 7 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1386#-:-MpIu840B3OtNXFuZePh:b-yhgp5j)* status: 7 of 15 files reviewed, 4 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[format_major_version.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpItdMmAF-nuhJjq421:-MpItdMmAF-nuhJjq422:b9d4ynr) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/format_major_version.go#L73)):*
> ```Go
> 	FormatBlockPropertyCollector
> 	// FormatRangeKeys is a format major version that introduces range keys.
> 	FormatRangeKeys
> ```

Since support for range keys will be spread across many PRs, should the format major version be introduced once the code is complete? Meanwhile we can just mark the public interfaces with "DO NOT USE" in case they are partially usable.
___
*[internal/rangekey/rangekey.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIq_5AAUcjj5Ub-91r:-MpIq_5AAUcjj5Ub-91s:b-g55qad) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/rangekey/rangekey.go#L29)):*
> ```Go
> // EncodedSetValueLen precomputes the length of a RangeKeySet's value when
> // encoded.  It may be used to construct a buffer of the appropriate size before
> // encoding.
> ```

Can you add a comment at the top of this file that specifies that RANGEKEYSET [start, end), Set of SuffixValue pairs is encoded as
RANGEKEYSET, start => end, Set of SuffixValue pairs.
___
*[internal/rangekey/rangekey.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIrRbW07WgcBsNbZSc:-MpIrRbW07WgcBsNbZSd:b-qjhm0o) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/rangekey/rangekey.go#L36)):*
> ```Go
> 		// Add len(varint(len(endKey))).
> 		x := uint32(len(endKey))
> 		n++
> ```

is there any reason to believe that we should be inlining instead of defining `func lenVarint(x uint64) int`?
___
*[internal/rangekey/rangekey.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIsv0tBTf-Wj9JJ8GS:-MpIsv0tBTf-Wj9JJ8GT:bh37nec) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/rangekey/rangekey.go#L88)):*
> ```Go
> 
> 		// Encode the value itself.
> 		n += copy(dst[n:], suffixValues[i].Value)
> ```

This encoding looks simpler than what was mentioned in the design doc. Are you leaving that for later, if needed? If yes, that sounds fine.


<!-- Sent from Reviewable.io -->

2021-11-24 22:14 UTC, nicktrav reviewed
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1386)* status: all files reviewed, 13 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[batch.go, line 220 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIluj-AdGwBk2p_1tW:-MpIlIW79ZH6vUvcNDDM:bg3n99s) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/batch.go#L220)):*
> ```Go
> 	countRangeDels uint64
> 
> 	// The count of range sets and unsets in the batch. Updated every time a
> ```

nit: `count of range sets, unsets and deletes ...`?
___
*[batch.go, line 669 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpImnWeCIhBdZQ4dZgB:-MpImnWeCIhBdZQ4dZgC:b-qpuu24) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/batch.go#L669)):*
> ```Go
> }
> 
> // RangeKeySet sets a range key mapping the key range [start, end) at the MVCC
> ```

Just a general comment on references to MVCC. My understanding is that the support we're adding is more general than MVCC timestamps? i.e. a suffix doesn't necessarily have to be an MVCC ts.

Is it worth referring to plain suffixes rather than talking about MVCC?

Same comment applies elsewhere.
___
*[batch.go, line 700 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIqQYI3PK0cw6p25h9:-MpIqQYI3PK0cw6p25hA:b4fgjok) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/batch.go#L700)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> 	b.countRangeKeys++
> 	if b.index != nil {
> 		b.rangeKeys = nil
> 		// Range keys are rare, so we lazily allocate the index for them.
> 		if b.rangeKeyIndex == nil {
> 			b.rangeKeyIndex = batchskl.NewSkiplist(&b.data, b.cmp, b.abbreviatedKey)
> 		}
> 		b.deferredOp.index = b.rangeKeyIndex
> 	}
> ```
</details>


It looks like we repeat this chunk across the three deferred ops. Worth extracting out to a helper?
___
*[batch.go, line 718 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIpwba4O5dNxfBIz0A:-MpIpwbbDdiGq-0jPelX:byonlhp) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/batch.go#L718)):*
> ```
> ... RangeKeyUnset returns.
> ```
___
*[batch_test.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIrXZl0GDig1_gi1Yy:-MpIrXZl0GDig1_gi1Yz:btpmw77) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/batch_test.go#L50)):*
> ```Go
> 
> 	// RangeKeySet and RangeKeyUnset are untested here because they don't expose
> 	// deferred variants. This is a consequence of these keys more complex value
> ```

nit: `keys'` (possessive?). Or just `... consequence of these keys having more complex ...`.
___
*[internal/base/internal_test.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpItam-4PUHtibv3jaZ:-MpItam-4PUHtibv3ja_:b-6k96fp) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/base/internal_test.go#L40)):*
> ```Go
> 		"foo",
> 		"foo\x08\x07\x06\x05\x04\x03\x02",
> 		"foo\x16\x07\x06\x05\x04\x03\x02\x01",
> ```

nit: Thoughts on making this less brittle by making the value `base16(InternalKeyKindMax)`?
___
*[internal/rangekey/rangekey.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIvNbcAN8dYKR49cMA:-MpIvNbcAN8dYKR49cMB:b-niyv3u) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/rangekey/rangekey.go#L77)):*
> ```Go
> 
> 	// Encode the list of (suffix, value-len) tuples.
> 	for i := 0; i < len(suffixValues); i++ {
> ```

nit: if you were to `for _, sv := range suffixValues` here, we avoid indexing into the slice four times. Not sure that's a massive win, but slightly less verbose.
___
*[internal/rangekey/rangekey.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIsv0tBTf-Wj9JJ8GS:-MpIupZBD2dOMyN1H5AZ:b3wg7yf) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/rangekey/rangekey.go#L88)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This encoding looks simpler than what was mentioned in the design doc. Are you leaving that for later, if needed? If yes, that sounds fine.
</blockquote></details>

On this point, is it worth documenting the encoding somewhere in this file? I didn't see it mentioned.
___
*[internal/rangekey/rangekey.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIyJf_-jzXYhjzMOac:-MpIyJf_-jzXYhjzMOad:bx8lhhk) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/rangekey/rangekey.go#L119)):*
> ```Go
> func DecodeSuffixValue(data []byte) (sv SuffixValue, rest []byte, ok bool) {
> 	// Decode the suffix.
> 	sv.Suffix, data, ok = decodeVarstring(data)
> ```

Worth documenting that we're mutating `data`? The caller should be aware of this.
___
*[internal/rangekey/rangekey.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpJ-8J-BCakiteiOK8t:-MpJ-8J-BCakiteiOK8u:bpg8uwu) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/rangekey/rangekey.go#L269)):*
> ```Go
> //
> // For example:
> // - a.RANGEKEYSET.5: c [(@t10, foo), (@t9, bar)]
> ```

nit: This seems at odds with the format definition. Should it be `[(@t10=foo), (@t9=bar)]` instead? Or is the format definition `[(s1, v1), (s2, v2), (s3, v3)]`


<!-- Sent from Reviewable.io -->

2021-11-29 18:32 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1386)* status: all files reviewed, 8 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[batch.go, line 669 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpImnWeCIhBdZQ4dZgB:-MpggqLH7KrhHmXI3xS6:b4uq00r) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/batch.go#L669)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Just a general comment on references to MVCC. My understanding is that the support we're adding is more general than MVCC timestamps? i.e. a suffix doesn't necessarily have to be an MVCC ts.

Is it worth referring to plain suffixes rather than talking about MVCC?

Same comment applies elsewhere.
</blockquote></details>

We actually already document `Split` as splitting a MVCC key into a user key and an encoded timestamp:

```
// Split returns the length of the prefix of the user key that corresponds to
// the key portion of an MVCC encoding scheme to enable the use of prefix bloom
// filters.
```

In some of the back-and-forth on the RFC draft, we came to the conclusion that Pebble will likely increasingly depend on MVCC semantics of suffixes.
___
*[batch.go, line 700 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIqQYI3PK0cw6p25h9:-MpgjFCEBVBqmAlcadBn:b8c1kh6) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/batch.go#L700)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

> ```
> 	b.countRangeKeys++
> 	if b.index != nil {
> 		b.rangeKeys = nil
> 		// Range keys are rare, so we lazily allocate the index for them.
> 		if b.rangeKeyIndex == nil {
> 			b.rangeKeyIndex = batchskl.NewSkiplist(&b.data, b.cmp, b.abbreviatedKey)
> 		}
> 		b.deferredOp.index = b.rangeKeyIndex
> 	}
> ```

It looks like we repeat this chunk across the three deferred ops. Worth extracting out to a helper?
</blockquote></details>

Sure. This was mirroring the manual inlining used throughout the batch implementation, but our range key design requires range keys to be rare.
___
*[batch.go, line 718 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIpwba4O5dNxfBIz0A:-MpglAVICBE9ojIQEfKc:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/batch.go#L718)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

> ```
> ... RangeKeyUnset returns.
> ```

</blockquote></details>

Done.
___
*[format_major_version.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpItdMmAF-nuhJjq421:-MpglwEk9_307NH-ZQNw:b-1eh3wi) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/format_major_version.go#L73)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Since support for range keys will be spread across many PRs, should the format major version be introduced once the code is complete? Meanwhile we can just mark the public interfaces with "DO NOT USE" in case they are partially usable.
</blockquote></details>

Sure, done.
___
*[internal/rangekey/rangekey.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIq_5AAUcjj5Ub-91r:-MpguQJK1lXOqedT9QI-:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/rangekey/rangekey.go#L29)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a comment at the top of this file that specifies that RANGEKEYSET [start, end), Set of SuffixValue pairs is encoded as
RANGEKEYSET, start => end, Set of SuffixValue pairs.
</blockquote></details>

Done.
___
*[internal/rangekey/rangekey.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIrRbW07WgcBsNbZSc:-MpgxHErExnyM8pmIPX-:b-b5o8gm) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/rangekey/rangekey.go#L36)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there any reason to believe that we should be inlining instead of defining `func lenVarint(x uint64) int`?
</blockquote></details>

factored it out: just premature optimization
___
*[internal/rangekey/rangekey.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIsv0tBTf-Wj9JJ8GS:-MpgmFpaDJEawNNWcwB9:b-tj46dg) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/rangekey/rangekey.go#L88)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

On this point, is it worth documenting the encoding somewhere in this file? I didn't see it mentioned.
</blockquote></details>

I implemented the more complicated encoding first and was dissatisfied with the encoding/decoding API that it required. Yeah, I figured if needed, we can switch back to the more complicated scheme.

I'll add a TODO for documenting the encoding so that we can document once we've made that decision.
___
*[internal/rangekey/rangekey.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIyJf_-jzXYhjzMOac:-MpgnFLE8hkbB7FBSFmQ:bsfe4oq) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/rangekey/rangekey.go#L119)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Worth documenting that we're mutating `data`? The caller should be aware of this.
</blockquote></details>

The `data` slice that the caller provides is unmodified, we just save a resliced tail of it to our `data` local variable.
___
*[internal/rangekey/rangekey.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpJ-8J-BCakiteiOK8t:-Mpgr0DA2uIKrxwijvLT:bj9krkv) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/rangekey/rangekey.go#L269)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: This seems at odds with the format definition. Should it be `[(@t10=foo), (@t9=bar)]` instead? Or is the format definition `[(s1, v1), (s2, v2), (s3, v3)]`
</blockquote></details>

Thanks, I changed the format and forgot to update this.


<!-- Sent from Reviewable.io -->

2021-11-29 19:01 UTC, nicktrav approved these changes
Did another pass through. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1386#-:-Mph3Zhm-Bls78YMCEYU:b-5ha45z)* status: all files reviewed, 4 unresolved discussions (waiting on @sumeerbhola)

___
*[batch.go, line 669 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpImnWeCIhBdZQ4dZgB:-Mph1qa0DY-xK-R2Up6c:b-31mjjy) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/batch.go#L669)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

We actually already document `Split` as splitting a MVCC key into a user key and an encoded timestamp:

```
// Split returns the length of the prefix of the user key that corresponds to
// the key portion of an MVCC encoding scheme to enable the use of prefix bloom
// filters.
```

In some of the back-and-forth on the RFC draft, we came to the conclusion that Pebble will likely increasingly depend on MVCC semantics of suffixes.
</blockquote></details>

Gotcha. Makes sense.
___
*[internal/rangekey/rangekey.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1386#-MpIyJf_-jzXYhjzMOac:-Mph1RJb7zSGDsX41M53:bnikynh) ([raw file](https://github.com/cockroachdb/pebble/blob/0463e0829ac747162dc311110b2214960b1fc015/internal/rangekey/rangekey.go#L119)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

The `data` slice that the caller provides is unmodified, we just save a resliced tail of it to our `data` local variable.
</blockquote></details>

Woops, my bad. Misinterpreted.


<!-- Sent from Reviewable.io -->

2021-11-30 00:01 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 15 files at r1, 3 of 8 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1386#-:-Mpi8PHd0k5lbrUGIHhf:bg7igkv)* status: all files reviewed, 6 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[batch.go, line 376 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1386#-Mpi86io22te08rUxpsz:-Mpi86ip5kuUTnwIEL45:b6h8x3h) ([raw file](https://github.com/cockroachdb/pebble/blob/2d67350929fb8c7aee600015edb521b339202390/batch.go#L376)):*
> ```Go
> 				b.countRangeDels++
> 			case InternalKeyKindRangeKeySet, InternalKeyKindRangeKeyUnset, InternalKeyKindRangeKeyDelete:
> 				b.countRangeKeys++
> ```

do we need to set `b.rangeKeys = nil`?
___
*[batch.go, line 678 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1386#-Mpi7P6v1oHafhQc5mTp:-Mpi7P6v1oHafhQc5mTq:b-tiv9uk) ([raw file](https://github.com/cockroachdb/pebble/blob/2d67350929fb8c7aee600015edb521b339202390/batch.go#L678)):*
> ```Go
> // WARNING: This is an experimental feature with limited functionality.
> func (b ExperimentalBatch) RangeKeySet(start, end, suffix, value []byte, _ *WriteOptions) error {
> 	suffixValues := [1]rangekey.SuffixValue{{Suffix: suffix, Value: value}}
> ```

where do we enforce that start, end are prefix keys?


<!-- Sent from Reviewable.io -->

2021-11-30 16:44 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1386#-:-MplirozDBkHzVNqQi_L:bz5mair)* status: 10 of 15 files reviewed, 6 unresolved discussions (waiting on @nicktrav and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-11-30 16:44 UTC, merged