sstable: Revert "Revert "sstable: reduce allocations during index flushing""
cockroachdb/pebble pull request #1389
Opened 2021-11-25 02:41 UTC by dt

This reverts commit 9791c0f4c0526c9397312bb7a4021415b50513f1, and fixes
the memory usage issue in the original commit it reverts, which was caused by
the fact that the `Metadata` outlived the `Writer`, and since a key in that
metadata was backed by a portion of the Writer's allocation pooling slice,
the entire slice remained in-use. Instead, the field for the metadata is
restored to being allocated individually, so that only it needs to be
kept after the writer finishes.

2021-11-25 02:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1389)
<!-- Reviewable:end -->

2021-11-28 19:43 UTC, dt commented on sstable/writer.go
>  		w.meta.SmallestPoint = w.meta.LargestPoint.Clone()
This is the only diff from the reverted commit: originally it replaced this Clone with one from the pooled alloc, but here is left as-is, and the the comment is added to explain why it should stay that way.

2021-11-29 15:02 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @dt, @jbowens, and @nicktrav)

___
*[sstable/writer.go, line 450 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1389#-Mpg5Zs1D9tMIih4FmU-:-Mpg5Zs1D9tMIih4FmU0:bejlpzq) ([raw file](https://github.com/cockroachdb/pebble/blob/fa09a9ab4614e4c26898e18b52081bfa7e827be6/sstable/writer.go#L450)):*
> ```Go
> 		}
> 		sep = prevKey.Successor(w.compare, w.successor, w.keyAlloc[:0])
> 		w.keyAlloc = w.keyAlloc[len(sep.UserKey):]
> ```

- This slicing is making some assumptions. `Separator` and `Successor` (the ones defined in comparer,go) must return keys of length equal to or smaller than the `a` parameter. It it returns a longer one, this could panic. This is a fine assumption to make, but we need to document it in comparer.go.
-  We use `DefaultComparer.{Separator,Successor}` as part of the implementation of `EngineComparer.{Separator,Successor}`. These `DefaultComparer` implementations are quite odd, and have poor code comments explaining their invariants at each step of the code. I'd be wary of making any assumptions without documenting these better. Some examples:
   - https://github.com/cockroachdb/pebble/blob/badc275a96543c449bcf61cee6b94339ccb87a64/internal/base/comparer.go#L150 is handling the case of b < a which should not be allowed. I suspect we didn't want to panic (because this could be because of some sstable corruption), and we don't have an error return in this function. We should add a TODO(storage-team) here.
   - Why is this line https://github.com/cockroachdb/pebble/blob/badc275a96543c449bcf61cee6b94339ccb87a64/internal/base/comparer.go#L155 not `i++`?
   - Both `Separator` and `Successor` are appending to `dst` when all they want to do is return `a` e.g. https://github.com/cockroachdb/pebble/blob/badc275a96543c449bcf61cee6b94339ccb87a64/internal/base/comparer.go#L179 This is wasteful when `InternalKey.{Separator,Successor}` will simply return `k` in this case. I don't know how frequently this happens but we could change to not appending to `dst` and returning a bool saying `a` was returned, and avoid the string comparison.

- `EngineComparer.{Separator,Successor}` similarly do wasteful appending of `append(dst, a...)`. The worst is when the `DefaultComparer` is returning `aKey` which it has appended to `dst`. We then proceed to append `a`, almost doubling the cost.


<!-- Sent from Reviewable.io -->

2021-11-29 23:08 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/writer.go, line 450 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1389#-Mpg5Zs1D9tMIih4FmU-:-MphuBrM4gg-Vmrw_HZ9:bprphjs) ([raw file](https://github.com/cockroachdb/pebble/blob/fa09a9ab4614e4c26898e18b52081bfa7e827be6/sstable/writer.go#L450)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

- This slicing is making some assumptions. `Separator` and `Successor` (the ones defined in comparer,go) must return keys of length equal to or smaller than the `a` parameter. It it returns a longer one, this could panic. This is a fine assumption to make, but we need to document it in comparer.go.
-  We use `DefaultComparer.{Separator,Successor}` as part of the implementation of `EngineComparer.{Separator,Successor}`. These `DefaultComparer` implementations are quite odd, and have poor code comments explaining their invariants at each step of the code. I'd be wary of making any assumptions without documenting these better. Some examples:
   - https://github.com/cockroachdb/pebble/blob/badc275a96543c449bcf61cee6b94339ccb87a64/internal/base/comparer.go#L150 is handling the case of b < a which should not be allowed. I suspect we didn't want to panic (because this could be because of some sstable corruption), and we don't have an error return in this function. We should add a TODO(storage-team) here.
   - Why is this line https://github.com/cockroachdb/pebble/blob/badc275a96543c449bcf61cee6b94339ccb87a64/internal/base/comparer.go#L155 not `i++`?
   - Both `Separator` and `Successor` are appending to `dst` when all they want to do is return `a` e.g. https://github.com/cockroachdb/pebble/blob/badc275a96543c449bcf61cee6b94339ccb87a64/internal/base/comparer.go#L179 This is wasteful when `InternalKey.{Separator,Successor}` will simply return `k` in this case. I don't know how frequently this happens but we could change to not appending to `dst` and returning a bool saying `a` was returned, and avoid the string comparison.

- `EngineComparer.{Separator,Successor}` similarly do wasteful appending of `append(dst, a...)`. The worst is when the `DefaultComparer` is returning `aKey` which it has appended to `dst`. We then proceed to append `a`, almost doubling the cost.


</blockquote></details>

On the panic, I could.slice it to cap(keyAlloc) if len(sep.UserKey) > cap(keyAlloc), but I perhaps if I'm going to explicitly handle the case where the comparer didn't use the passed in buffer, I should instead maybe just check &keyAlloc[0] ==& sep.UserKey[0] and decline to slice at all if it didn't use it?

On the aspects of DefaultComparer's implementation, I think I'd prefer to say those are out of scope for this change, and keep this just on what Writer does against the general Comparer interface as it stands. I toyed with whether that interface would be better if it was changed so that the signatures for these functions included returning the suffix of the alloc which they didn't use, so that a caller could hand them a catch buffer, then replace its catch buffer with their returned remainder, rather than trying to slice off what it thinks the callee used, but I decided I didn't really want to mess with anything outside just the Writer for now. I guess that suggests I should do the &[0] comparison to check what it used.


<!-- Sent from Reviewable.io -->

2021-11-29 23:23 UTC, sumeerbhola reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @dt, @jbowens, and @nicktrav)

___
*[sstable/writer.go, line 450 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1389#-Mpg5Zs1D9tMIih4FmU-:-MphzS3r0ndKsisWikG1:b-vjgoi5) ([raw file](https://github.com/cockroachdb/pebble/blob/fa09a9ab4614e4c26898e18b52081bfa7e827be6/sstable/writer.go#L450)):*
>  if I'm going to explicitly handle the case where the comparer didn't use the passed in buffer, I should instead maybe just check &keyAlloc[0] ==& sep.UserKey[0] and decline to slice at all if it didn't use it?

yep, sounds reasonable.

> On the aspects of DefaultComparer's implementation, I think I'd prefer to say those are out of scope for this change, and keep this just on what Writer does against the general Comparer interface as it stands.

that's fine


<!-- Sent from Reviewable.io -->

2021-11-29 23:41 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/writer.go, line 450 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1389#-Mpg5Zs1D9tMIih4FmU-:-Mpi3PdP9X6B_kbZir-C:b-puwvhk) ([raw file](https://github.com/cockroachdb/pebble/blob/fa09a9ab4614e4c26898e18b52081bfa7e827be6/sstable/writer.go#L450)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

>  if I'm going to explicitly handle the case where the comparer didn't use the passed in buffer, I should instead maybe just check &keyAlloc[0] ==& sep.UserKey[0] and decline to slice at all if it didn't use it?

yep, sounds reasonable.

> On the aspects of DefaultComparer's implementation, I think I'd prefer to say those are out of scope for this change, and keep this just on what Writer does against the general Comparer interface as it stands.

that's fine
</blockquote></details>

Okay, I updated this to check if the returned key is stored in the passed buf, and added a comment to the interface on those to stipulate that if they use any part of the passed dst buf to store the key they return, it must be a prefix so this comparison is possible.


<!-- Sent from Reviewable.io -->

2021-12-02 18:21 UTC, sumeerbhola requested changes
> Reviewed 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @dt, @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/writer.go, line 450 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1389#-Mpg5Zs1D9tMIih4FmU-:-MpwLTyFD66XE3lNTUgS:b-qvsiiy) ([raw file](https://github.com/cockroachdb/pebble/blob/fa09a9ab4614e4c26898e18b52081bfa7e827be6/sstable/writer.go#L450)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Okay, I updated this to check if the returned key is stored in the passed buf, and added a comment to the interface on those to stipulate that if they use any part of the passed dst buf to store the key they return, it must be a prefix so this comparison is possible.
</blockquote></details>

Both `EngineComparer.Separator` and `DefaultComparer.Separator` go to the trouble of handling the case when the `dst` parameter is non-empty. This behavior is very questionable, but without changing that spec, I don't think we can make this requirement. Can you instead use the condition
``` 
if len(w.keyAlloc) > 0 && len(sep.UserKey) > 0 && len(prevKey.UserKey) > 0 && !(&prevKey.UserKey[0] == &sep.UserKey[0])
```


<!-- Sent from Reviewable.io -->

2021-12-03 13:13 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/writer.go, line 450 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1389#-Mpg5Zs1D9tMIih4FmU-:-MpxNr-W0_8WCfIwv6mx:bri240m) ([raw file](https://github.com/cockroachdb/pebble/blob/fa09a9ab4614e4c26898e18b52081bfa7e827be6/sstable/writer.go#L450)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Both `EngineComparer.Separator` and `DefaultComparer.Separator` go to the trouble of handling the case when the `dst` parameter is non-empty. This behavior is very questionable, but without changing that spec, I don't think we can make this requirement. Can you instead use the condition
``` 
if len(w.keyAlloc) > 0 && len(sep.UserKey) > 0 && len(prevKey.UserKey) > 0 && !(&prevKey.UserKey[0] == &sep.UserKey[0])
```
</blockquote></details>

Huh, I'm not immediately following, and you elaborate?

As far as I could tell, including when handling a non-empty dst, the current implementation would still conform to a requirement that says if the returned slice is stored in any part of dst, it must be stored in a prefix of it?


<!-- Sent from Reviewable.io -->

2021-12-03 16:48 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389#-:-Mq0BXua1K3iKdGVyX6k:bg7igkv)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @dt, @jbowens, and @nicktrav)

___
*[sstable/writer.go, line 450 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1389#-Mpg5Zs1D9tMIih4FmU-:-Mq098fb0Uxi6Ghqz7vq:b-nk9tmo) ([raw file](https://github.com/cockroachdb/pebble/blob/fa09a9ab4614e4c26898e18b52081bfa7e827be6/sstable/writer.go#L450)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Huh, I'm not immediately following, and you elaborate?

As far as I could tell, including when handling a non-empty dst, the current implementation would still conform to a requirement that says if the returned slice is stored in any part of dst, it must be stored in a prefix of it?
</blockquote></details>

You are right. Fine to keep this if condition, but could you change the comment in `Separator` and `Successor` where you say "may be stored in dst" to the following:

// The returned key k must be constructed by appending to dst, so we are guaranteed that len(k) > 0 => &dst[0] == &k[0].
//
// TODO(sumeer): This necessity of appending to dst causes unnecessary copying when the code wants to return a. It would have been useful if 
// some callers were passing in a dst such that len(dst)>0, but the only user is InternalKey.Separator, which always passes a len(dst)==0. Change it so that
// len(dst)==0 is a precondition, and that appending to dst is optional, but if appending to dst, the returned key must be such that &dst[0] == &k[0].


<!-- Sent from Reviewable.io -->

2021-12-03 17:47 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/writer.go, line 450 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1389#-Mpg5Zs1D9tMIih4FmU-:-Mq0CPyWCwg7qso0xP3T:b-npb30s) ([raw file](https://github.com/cockroachdb/pebble/blob/fa09a9ab4614e4c26898e18b52081bfa7e827be6/sstable/writer.go#L450)):*
Huh, sorry, I'm still not quite following

>  The returned key k must be constructed by appending to dst, so we are guaranteed that len(k) > 0 => &dst[0] == &k[0].

This seems like a stricter requirement than I have added to the comment currently, is perhaps stricter than we require  -- if they don't want to use any part of dst, that is fine -- and I'm not sure that `append` actually guarantees the following implication e.g. if it needs to realloc and copy dst over, due to insufficient cap, then it returns a new slice.


<!-- Sent from Reviewable.io -->

2021-12-09 05:12 UTC, sumeerbhola approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @dt, @jbowens, and @nicktrav)

___
*[sstable/writer.go, line 450 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1389#-Mpg5Zs1D9tMIih4FmU-:-MqS_Azo8iQIMmWR7aiX:bfsuge8) ([raw file](https://github.com/cockroachdb/pebble/blob/fa09a9ab4614e4c26898e18b52081bfa7e827be6/sstable/writer.go#L450)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Huh, sorry, I'm still not quite following

>  The returned key k must be constructed by appending to dst, so we are guaranteed that len(k) > 0 => &dst[0] == &k[0].

This seems like a stricter requirement than I have added to the comment currently, is perhaps stricter than we require  -- if they don't want to use any part of dst, that is fine -- and I'm not sure that `append` actually guarantees the following implication e.g. if it needs to realloc and copy dst over, due to insufficient cap, then it returns a new slice.
</blockquote></details>

You are right again. My thinking has been very muddled.
The comment where `Separator/Successor` are defined is messing with my head.
The properties are specified for k, but what is returned is k appended to dst (which may be non-empty), as the aquablb example specifies.
So saying 
// The returned key k may be stored in dst, but if it is, it must be stored in a
// prefix of dst i.e. &dst[0] == &k[0].
is not quite correct.
What we are saying is that the return value (rv = concat(dst, k)) may use the dst slice, but if it does it must a prefix of the dst slice, that is &rv[0]=&dst[0].

Does this make sense?


<!-- Sent from Reviewable.io -->

2022-01-12 20:56 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/writer.go, line 450 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1389#-Mpg5Zs1D9tMIih4FmU-:-Mt4-gmZ2VN_3_RoaJH8:b-aockhw) ([raw file](https://github.com/cockroachdb/pebble/blob/fa09a9ab4614e4c26898e18b52081bfa7e827be6/sstable/writer.go#L450)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

You are right again. My thinking has been very muddled.
The comment where `Separator/Successor` are defined is messing with my head.
The properties are specified for k, but what is returned is k appended to dst (which may be non-empty), as the aquablb example specifies.
So saying 
// The returned key k may be stored in dst, but if it is, it must be stored in a
// prefix of dst i.e. &dst[0] == &k[0].
is not quite correct.
What we are saying is that the return value (rv = concat(dst, k)) may use the dst slice, but if it does it must a prefix of the dst slice, that is &rv[0]=&dst[0].

Does this make sense?
</blockquote></details>

I'm still not following -- that's what "The *returned* key k" ... &k[0] == &dst[0]" is saying isn't it? like, there's a big comment above about what this thing is going to return and I don't really want to try to reiterate anything there about concats or whatever. I just want to say that whatever you're returning -- concat or otherwise --, if it is stored in the passed dst, but must be stored at the beginning of dst, which I think is what the existing comment says?


<!-- Sent from Reviewable.io -->

2022-01-21 14:09 UTC, dt commented
Rebased over #1442, looks like there's one new allocation vs before, but still far, far fewer than master:

```
name                                                          old allocs/op  new allocs/op  delta
Writer/block=4.0_K/filter=true/compression=NoCompression-10      10.7k ± 0%      0.1k ± 0%   -98.66%  (p=0.008 n=5+5)
Writer/block=4.0_K/filter=true/compression=Snappy-10             10.7k ± 0%      0.1k ± 0%   -98.60%  (p=0.000 n=5+4)
Writer/block=4.0_K/filter=true/compression=ZSTD-10               95.8k ± 0%     85.2k ± 0%   -11.03%  (p=0.029 n=4+4)
Writer/block=4.0_K/filter=false/compression=NoCompression-10     10.7k ± 0%      0.1k ± 1%   -99.08%  (p=0.008 n=5+5)
Writer/block=4.0_K/filter=false/compression=Snappy-10            10.7k ± 0%      0.1k ± 0%   -99.02%  (p=0.029 n=4+4)
Writer/block=4.0_K/filter=false/compression=ZSTD-10              95.7k ± 0%     85.2k ± 0%      ~     (p=0.079 n=4+5)
Writer/block=32_K/filter=true/compression=NoCompression-10       1.31k ± 0%     0.14k ± 0%   -89.37%  (p=0.000 n=5+4)
Writer/block=32_K/filter=true/compression=Snappy-10              1.31k ± 0%     0.14k ± 0%   -89.03%  (p=0.000 n=5+4)
Writer/block=32_K/filter=true/compression=ZSTD-10                11.7k ± 0%     10.5k ± 0%      ~     (p=0.079 n=4+5)
Writer/block=32_K/filter=false/compression=NoCompression-10      1.26k ± 0%     0.09k ± 0%   -92.56%  (p=0.000 n=5+4)
Writer/block=32_K/filter=false/compression=Snappy-10             1.27k ± 0%     0.10k ± 0%   -92.19%  (p=0.029 n=4+4)
Writer/block=32_K/filter=false/compression=ZSTD-10               11.7k ± 0%     10.5k ± 0%   -10.02%  (p=0.008 n=5+5)
```

2022-01-21 14:12 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/writer.go, line 450 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1389#-Mpg5Zs1D9tMIih4FmU-:-MtwymSS-vyonytrF0b4:bu8t07h) ([raw file](https://github.com/cockroachdb/pebble/blob/fa09a9ab4614e4c26898e18b52081bfa7e827be6/sstable/writer.go#L450)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I'm still not following -- that's what "The *returned* key k" ... &k[0] == &dst[0]" is saying isn't it? like, there's a big comment above about what this thing is going to return and I don't really want to try to reiterate anything there about concats or whatever. I just want to say that whatever you're returning -- concat or otherwise --, if it is stored in the passed dst, but must be stored at the beginning of dst, which I think is what the existing comment says?
</blockquote></details>

@sumeerbhola Did you get a chance to look at this?


<!-- Sent from Reviewable.io -->

2022-01-21 19:12 UTC, sumeerbhola commented
@dt sorry, I must have missed the update. Will look this afternoon. Please feel free to harass me aggressively on slack if I am not responding on github.

2022-01-21 21:10 UTC, sumeerbhola requested changes
my comments are mainly about the original code that was reverted

> Reviewed 1 of 3 files at r5, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389#-:-MtyRpuf2e7pqD0avzoG:b93m7bw)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @dt, @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/base/comparer.go, line 63 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1389#-MtyAXmkCzdVq1hJWFWk:-MtyAXmkCzdVq1hJWFWl:b-ih5tzu) ([raw file](https://github.com/cockroachdb/pebble/blob/10126f1cfc13ffcf290820ebe6ba6487c6007ab9/internal/base/comparer.go#L63)):*
> ```Go
> //
> // The returned key k may be stored in dst, but if it is, it must be stored in a
> // prefix of dst i.e. &dst[0] == &k[0].
> ```

We are using k twice is what I was objecting to
First use: Given keys a, b for which Compare(a, b) < 0, Separator returns a key k such that ...
Second use: The returned key k ...

The returned key (say x) was defined as concat(dst, k), even prior to your change. We just didn't write this comment properly (the first line talks about `return a` but that isn't permissible either).

Rather than nit pick about it, how about you go ahead and merge this with your current change, and I'll subsequently rewrite the whole comment to what I think it should be and try to convince the other storage folks about that rewrite.
___
*[sstable/writer.go, line 150 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1389#-MtyCcWUEX69yiwph9n3:-MtyCcWV6CcOyMRldmcF:ble8cty) ([raw file](https://github.com/cockroachdb/pebble/blob/10126f1cfc13ffcf290820ebe6ba6487c6007ab9/sstable/writer.go#L150)):*
> ```Go
> 	indexPartitions []indexBlockAndBlockProperties
> 
> 	keyAlloc        []byte
> ```

Can you add code comments stating what these are for.

And it would help if the code comment pointed out the lifetime of the data allocated via these blocks. IIUC,
1. the slices allocated via `indexBlockAlloc` are alive until the writer finishes.
2. `keyAlloc` is used for two things (a) `indexBlockAndBlockProperties.sep` which also live until the writer finishes, (b) the `sep` produced in `addIndexEntry`, which only lives until the call to `w.indexBlock.add`.

The 2b case in the latter bullet is probably where the high allocation count originates.
Is my understanding accurate?

It's interesting that this PR is mixing the two lifetimes. It at least deserves a code comment stating the above, even if the code stays the same.
And maybe 2a should use the same buffer as 1a, to reduce the lifetime of `keyAlloc` buffers. Maybe it won't practically matter given that the keyAllocSize is quite large, 256KB, but seems conceptually cleaner.
___
*[sstable/writer.go, line 200 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1389#-MtyEzsD3OsXltdcpVLL:-MtyEzsD3OsXltdcpVLM:b-45u14l) ([raw file](https://github.com/cockroachdb/pebble/blob/10126f1cfc13ffcf290820ebe6ba6487c6007ab9/sstable/writer.go#L200)):*
> ```Go
> type indexBlockAndBlockProperties struct {
> 	nEntries   int
> 	sep        InternalKey
> ```

how about
// sep is the last key added to this index block and will later be used to compute a separator.
___
*[sstable/writer.go, line 202 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1389#-MtyFMjT7sMdnDWG--Yb:-MtyFMjT7sMdnDWG--Yc:bbgswmi) ([raw file](https://github.com/cockroachdb/pebble/blob/10126f1cfc13ffcf290820ebe6ba6487c6007ab9/sstable/writer.go#L202)):*
> ```Go
> 	sep        InternalKey
> 	properties []byte
> 	block      []byte
> ```

// block is the encoded block produced by blockWriter.finish
___
*[sstable/writer.go, line 861 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1389#-MtyOVyc19QxFtFZwNXn:-MtyOVyc19QxFtFZwNXo:b-e4bwdv) ([raw file](https://github.com/cockroachdb/pebble/blob/10126f1cfc13ffcf290820ebe6ba6487c6007ab9/sstable/writer.go#L861)):*
> ```Go
> 	w.keyAlloc, part.sep = cloneKeyWithBuf(base.DecodeInternalKey(w.indexBlock.curKey), w.keyAlloc)
> 	bk := w.indexBlock.finish()
> 	if len(w.indexBlockAlloc) < len(bk) {
> ```

// Allocating enough bytes for approximatelly 16 index blocks.

Btw, did this actually make much difference in performance? I would expect most of the benefits would come from amortizing the individual key allocations.


<!-- Sent from Reviewable.io -->

2022-01-21 22:35 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389)* status: 1 of 8 files reviewed, 7 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/writer.go, line 150 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1389#-MtyCcWUEX69yiwph9n3:-MtyX96x9J9T4H3n101n:by3ww62) ([raw file](https://github.com/cockroachdb/pebble/blob/10126f1cfc13ffcf290820ebe6ba6487c6007ab9/sstable/writer.go#L150)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add code comments stating what these are for.

And it would help if the code comment pointed out the lifetime of the data allocated via these blocks. IIUC,
1. the slices allocated via `indexBlockAlloc` are alive until the writer finishes.
2. `keyAlloc` is used for two things (a) `indexBlockAndBlockProperties.sep` which also live until the writer finishes, (b) the `sep` produced in `addIndexEntry`, which only lives until the call to `w.indexBlock.add`.

The 2b case in the latter bullet is probably where the high allocation count originates.
Is my understanding accurate?

It's interesting that this PR is mixing the two lifetimes. It at least deserves a code comment stating the above, even if the code stays the same.
And maybe 2a should use the same buffer as 1a, to reduce the lifetime of `keyAlloc` buffers. Maybe it won't practically matter given that the keyAllocSize is quite large, 256KB, but seems conceptually cleaner.
</blockquote></details>

Ahhh, you make a very good point that I completely missed: I was so focused on pooling the allocations that `Separator(..., nil)` was doing I missed that the lifetime of its returned slice is local to the function call -- `indexBlock.add` is just going to copy it into its own buf. A single, reused scratch, that we just alloc ourselves and then don't bother with re-slicing based on what Separator/Successor did/didn't use of it works just fine. So that whole thread about their returned slice storage is all moot :facepalm:.

I still think it makes sense to have two separate pooled allocation slices from which we take index blocks and index block separators, just since their refill amounts are different (one is in terms of blocks, the other is fixed or could be in terms of keys), even though they have the same lifetime now (until finished). Commented on all of them.
___
*[sstable/writer.go, line 200 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1389#-MtyEzsD3OsXltdcpVLL:-MtyU7Oe4aSRH9vY1L9t:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/10126f1cfc13ffcf290820ebe6ba6487c6007ab9/sstable/writer.go#L200)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about
// sep is the last key added to this index block and will later be used to compute a separator.
</blockquote></details>

Done.
___
*[sstable/writer.go, line 202 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1389#-MtyFMjT7sMdnDWG--Yb:-MtyVwOA-AdQ--CWq2YW:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/10126f1cfc13ffcf290820ebe6ba6487c6007ab9/sstable/writer.go#L202)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

// block is the encoded block produced by blockWriter.finish
</blockquote></details>

Done.
___
*[sstable/writer.go, line 861 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1389#-MtyOVyc19QxFtFZwNXn:-MtyTqtT7IHYLp-gfQUz:b-ld2ru1) ([raw file](https://github.com/cockroachdb/pebble/blob/10126f1cfc13ffcf290820ebe6ba6487c6007ab9/sstable/writer.go#L861)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

// Allocating enough bytes for approximatelly 16 index blocks.

Btw, did this actually make much difference in performance? I would expect most of the benefits would come from amortizing the individual key allocations.
</blockquote></details>

Done.

My memory is a bit fuzzy but I *think* this was mostly driven by my parallel key rewriter PR, where I have a big buffer of index entries and then flush them all in one tight loop, so anything in that loop that allocated showed up.
___
*[internal/base/comparer.go, line 63 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1389#-MtyAXmkCzdVq1hJWFWk:-MtyfQCN2-NEn5sZuQWc:b-3i31vk) ([raw file](https://github.com/cockroachdb/pebble/blob/10126f1cfc13ffcf290820ebe6ba6487c6007ab9/internal/base/comparer.go#L63)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We are using k twice is what I was objecting to
First use: Given keys a, b for which Compare(a, b) < 0, Separator returns a key k such that ...
Second use: The returned key k ...

The returned key (say x) was defined as concat(dst, k), even prior to your change. We just didn't write this comment properly (the first line talks about `return a` but that isn't permissible either).

Rather than nit pick about it, how about you go ahead and merge this with your current change, and I'll subsequently rewrite the whole comment to what I think it should be and try to convince the other storage folks about that rewrite.
</blockquote></details>

Welp, it turns out I didn't need this at all, as mentioned above (below?) since all we need is a local, reused scratch buf for the Separator/Successor calls.

So this is somewhat academic now and we can just ignore it but if you do come along later to fix up these comments, perhaps explaining what I was struggling with will be useful context: my read was they were the same `k` in both cases, that is a new byte slice which is expected to both 1) be the concat of dst and some new bytes which 2) _as a whole_ satisfies the described ordering conditions? or is that second part incorrect, and it is it only those appended bytes  and not the whole, which is being constrained to order as described? 


<!-- Sent from Reviewable.io -->

2022-01-24 15:36 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r6, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1389#-:-MuBijhHBPVbzoTVwjeA:bg7igkv)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @dt, @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/writer.go, line 861 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1389#-MtyOVyc19QxFtFZwNXn:-MuBhyhv5jKS7tA5akYk:b2nhb2c) ([raw file](https://github.com/cockroachdb/pebble/blob/10126f1cfc13ffcf290820ebe6ba6487c6007ab9/sstable/writer.go#L861)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Done.

My memory is a bit fuzzy but I *think* this was mostly driven by my parallel key rewriter PR, where I have a big buffer of index entries and then flush them all in one tight loop, so anything in that loop that allocated showed up.
</blockquote></details>

Ack
___
*[internal/base/comparer.go, line 63 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1389#-MtyAXmkCzdVq1hJWFWk:-MuBhEGb0B3KS55-ikhE:b-a03v0m) ([raw file](https://github.com/cockroachdb/pebble/blob/10126f1cfc13ffcf290820ebe6ba6487c6007ab9/internal/base/comparer.go#L63)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Welp, it turns out I didn't need this at all, as mentioned above (below?) since all we need is a local, reused scratch buf for the Separator/Successor calls.

So this is somewhat academic now and we can just ignore it but if you do come along later to fix up these comments, perhaps explaining what I was struggling with will be useful context: my read was they were the same `k` in both cases, that is a new byte slice which is expected to both 1) be the concat of dst and some new bytes which 2) _as a whole_ satisfies the described ordering conditions? or is that second part incorrect, and it is it only those appended bytes  and not the whole, which is being constrained to order as described? 
</blockquote></details>

it is not a whole. It is only the appended bytes that need to satisfy the constraint. See the comment
```
// For example, if dst, a and b are the []byte equivalents of the strings
// "aqua", "black" and "blue", then the result may be "aquablb".
```
Don't ask me why these semantics are useful :), since we only ever call it with an empty slice.


<!-- Sent from Reviewable.io -->

2022-01-24 15:38 UTC, dt commented
TFT(many)Rs (and sorry about all the back and forth on a non-point)!

2022-01-24 15:38 UTC, merged