internal/rangekey: add Coalescer, CoalescedSpan, Iter
cockroachdb/pebble pull request #1394
Opened 2021-12-01 01:27 UTC by jbowens

internal/rangekey: add Coalescer, CoalescedSpan

Add a Coalescer type that may 'coalesce' overlapping range key fragments into a
single CoalescedSpan. A CoalescedSpan represents the aggregate of all the
information from the individual range keys coalesced. A CoalesecedSpan is always
internally consistent, meaning that all necessary shadowing of keys is applied.

Coalescer is expected to be used in compactions, coalescing any overlapping
range key fragments from compaction inputs, and emitting CoalescedSpans that may
be used to construct the range keys persisted to outputs. It is also expected to
be used during iteration, for coalescing snapshot-separated overlapping range
keys and for respecting unsets and deletes across levels. Additional interface
changes may be necessary to support all of the above use cases.

internal/rangekeys: add Iter

Add an iterator that wraps a range key keyspan.Iter and performs on-the-fly
coalescing of range keys. This may be used to implement range-key iteration over
the memtable's range keys. It may also be useful elsewhere with extensions.

2021-12-01 01:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1394)
<!-- Reviewable:end -->

2021-12-01 16:42 UTC, jbowens reviewed
Naming is a little tricky here—I originally used 'Merger' and 'MergedSpan', but that sounded too much like it might be the inverse of fragmentation. Range keys are fragmented to form disjoint 'stacks' of perfectly overlapping internal range keys. Each internal key within each stack has its own sequence number and key-kind, which form an ordering to the stack. "Coalescing" squashes the stack into a single, internally-consistent unit.

```
 ↑
 |                                         ___
 |       _______                           ___
 |       _______ ______  _______     _____ ___
 |       _______ _______ _______ ___ _____ ___
 |     a b c d e f g h i j k l m n o p q r s t u v w x y z
seq #
```
turns into
```
         ======= ======= ======= === ===== ===
       a b c d e f g h i j k l m n o p q r s t u v w x y z
```

Curious if y'all have any clearer names for this concept. I'll also include a similar diagram in the comments once we've settled on naming.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1394#-:-MpqorOOBXYwSeh_EiSP:b-rhk5eb)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @nicktrav and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-12-01 18:56 UTC, nicktrav reviewed
I still have the second commit to review, but flushing some comments now.

I think the naming is decent. The only other words I could think of were "flatten" and "squash". But then the structs sound goofy: "Flattener" and "Squasher".

> Reviewed 2 of 3 files at r1, 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1394#-:-Mpr878dC9WALsR7Xqbu:b-5xteup)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/coalescer.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MpqzMjm5GUO_AiJcz28:-MpqzMjm5GUO_AiJcz29:bkbmv9s) ([raw file](https://github.com/cockroachdb/pebble/blob/6eaa233dcd96d88e1879b0403890026b78639b31/internal/rangekey/coalescer.go#L47)):*
> ```Go
> //
> // A Coalescer expects to receive only fragmented range keys, such that if two
> // keys overlap in user key space, they have the same bounds. The caller may
> ```

s/may fragment/should/? Or are you using "may" as a directive?
___
*[internal/rangekey/coalescer.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mpr3CXo1vu6Q3hjfJGI:-Mpr3CXo1vu6Q3hjfJGJ:b-eg1yoh) ([raw file](https://github.com/cockroachdb/pebble/blob/6eaa233dcd96d88e1879b0403890026b78639b31/internal/rangekey/coalescer.go#L231)):*
> ```Go
> 		// TODO(jackson): Gate behind invaraints.Enabled eventually.
> 		if c.items.cmp(s.Start.UserKey, c.start) > 0 {
> 			panic(fmt.Sprintf("pebble: range key key ordering invariant violated: %s < %s",
> ```

Should the error string have the inequality going the other way, i.e. `s.start > c.start`. Same below.
___
*[internal/rangekey/coalescer.go, line 268 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mpr4vnu8sq9jPoEcoTC:-Mpr4vnu8sq9jPoEcoTD:b-p2gnw0) ([raw file](https://github.com/cockroachdb/pebble/blob/6eaa233dcd96d88e1879b0403890026b78639b31/internal/rangekey/coalescer.go#L268)):*
> ```Go
> 				// This suffix is already set or unset at a lower sequence
> 				// number. Replace it.
> 				c.items.items[i] = SuffixItem{
> ```

Is it possible to have "duplicate" aligned fragments in `c.items` (i.e. same start, end and suffix?). Would all of those have to be replaced?

I _think_ the answer is "no", but just wanted to check.
___
*[internal/rangekey/testdata/coalescer, line 253 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MprJgQj3gsVGG8YWStg:-MprJgQj3gsVGG8YWSth:b-2kgdzb) ([raw file](https://github.com/cockroachdb/pebble/blob/86a8d93e528f61ea071606bbc7194acf1d27c1d2/internal/rangekey/testdata/coalescer#L253)):*
> ```
> finish
> ----
> ●   [a, c)#10 (DEL)
> ```

Does it make sense to have a RANGEKEYDEL with a "logical value" (i.e. `@t5=foo`)? I assume that code elsewhere wouldn't look at the logical value when the key kind is RANGEKEYDEL, but it's still a little weird to encounter it.

In the "sequence number is the same" scenario, would it be possible to clear out `SuffixItems` when flushing the fragment if the key kind is RANGEKEYDEL?


<!-- Sent from Reviewable.io -->

2021-12-01 20:21 UTC, nicktrav approved these changes
Nice! The test cases are really nice.

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1394#-:-Mprdrp7EIzAlg8z1SJt:b848bbj)* status: all files reviewed, 8 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/iter.go, line 182 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mpr_UdO5ctGrVgh7Yua:-Mpr_UdO5ctGrVgh7Yub:bxdy3qi) ([raw file](https://github.com/cockroachdb/pebble/blob/6eaa233dcd96d88e1879b0403890026b78639b31/internal/rangekey/iter.go#L182)):*
> ```Go
> 		// the last fragment.
> 		i.dir = -1
> 		_, _ = i.iter.Prev()
> ```

Wondering if there should be some "symmetry" here with the `i.dir == -1 && i.valid` case in `(*Iter).Next()`. Here, we're not checking the return value, but we are in `Next()`.

Can `Next()` be simplified to allow the check to happen outside of the `switch` statement, where we check the validity of the iterator?
___
*[internal/rangekey/testdata/iter, line 11 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mprb4_f-ZnbAbK-x4WW:-Mprb4_f-ZnbAbK-x4WX:b-37vm3q) ([raw file](https://github.com/cockroachdb/pebble/blob/6eaa233dcd96d88e1879b0403890026b78639b31/internal/rangekey/testdata/iter#L11)):*
> ```
> h.RANGEKEYDEL.22  : j
> h.RANGEKEYSET.21  : j [(@t5=peaches),(@t3=starfruit)]
> l.RANGEKEYUNSET.2 : m [@t5,@t9]
> ```

Is it valid to have a suffixes sorted ascending like this? In the iterator output below, it looks like we sort before emitting, so there's no issue, but just wanted to check if this was technically valid?
___
*[internal/rangekey/testdata/iter, line 32 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MpraYAf-4sv_SxQ_DyA:-MpraYAf-4sv_SxQ_DyB:b7mp0o1) ([raw file](https://github.com/cockroachdb/pebble/blob/6eaa233dcd96d88e1879b0403890026b78639b31/internal/rangekey/testdata/iter#L32)):*
> ```
> ├── @t5 : pineapple
> └── @t3 : guava
> ●   [h, j)#22 (DEL)
> ```

I left a comment elsewhere about having RANGEKEYSET and RANGEKEYDEL at the same sequence number, and emitting a value with the latter. This line is more in line with what I'd expect to encounter (i.e. no user value).
___
*[internal/rangekey/testdata/iter, line 164 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mprd1S7BOChExvKXmy-:-Mprd1S7BOChExvKXmy0:b2jd6l0) ([raw file](https://github.com/cockroachdb/pebble/blob/6eaa233dcd96d88e1879b0403890026b78639b31/internal/rangekey/testdata/iter#L164)):*
> ```
> 
> iter
> seek-ge 1
> ```

If we're showing ASCII ordering, it might be night to have `seek-ge 1a`, `9a`, etc. And maybe `c0`, `c1`, etc. that land in the next range?


<!-- Sent from Reviewable.io -->

2021-12-02 19:42 UTC, sumeerbhola requested changes
some preliminary comments. I haven't carefully looked at the code yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1394#-:-MpweYFM89vqizSvBzv2:b-316wv7)* status: all files reviewed, 12 unresolved discussions (waiting on @jbowens)

___
*[internal/rangekey/coalescer.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MpwacxgAC5Feea17bg_:-MpwacxgAC5Feea17bga:b-ueno8p) ([raw file](https://github.com/cockroachdb/pebble/blob/86a8d93e528f61ea071606bbc7194acf1d27c1d2/internal/rangekey/coalescer.go#L41)):*
> ```Go
> // Coalescer imposes range key semantics and coalesces fragments with the same
> // bounds. A Coalescer receives—through its Add method—a stream of internal
> // range keys (sets, unsets and deletes). Among overlapping fragments, fragments
> ```

"Among overlapping fragments": they have to be perfectly aligned, yes?
I think its worth hoisting that "they have the same bounds" earlier and adding an example.
Also, a `CoalescedSpan` can eventually result in multiple internal key-value pairs, yes? That is, we are coalescing the sets and unsets here, and the RANGEKEYDELs so we can eliminate the ones that are no longer needed? In which case it should have more than one coalesced seqnum, one for the set and one for the unsets?

And looks like RANGEKEYDELs influence the coalescing but aren't actually an output since they are not fully represented in a `CoalescedSpan`. Is that correct?
Why should anyone care about `CoalescedSpan.Delete` (I can see why the `Coalescer.delete` exists)?
___
*[internal/rangekey/coalescer.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mpwbs7r6bu4Ero7Q3Z6:-Mpwbs7s9hisRfNHiC_4:b9u6rqy) ([raw file](https://github.com/cockroachdb/pebble/blob/86a8d93e528f61ea071606bbc7194acf1d27c1d2/internal/rangekey/coalescer.go#L55)):*
> ```Go
> //
> // A Coalescer may also coalesce internal range keys in reverse order, through
> // AddReverse. Add and AddReverse calls may be made to the same coalescer, but
> ```

why does the order matter if the rangekeys are perfectly aligned?
___
*[internal/rangekey/coalescer.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mpwc3aa5aQCzKhuydwY:-Mpwc3aa5aQCzKhuydwZ:b-k90twz) ([raw file](https://github.com/cockroachdb/pebble/blob/86a8d93e528f61ea071606bbc7194acf1d27c1d2/internal/rangekey/coalescer.go#L60)):*
> ```Go
> // The memory backing emitted coalesced spans is only guaranteed to be unused
> // until the next Add or AddReverse call. Coalescer does not make copies of any
> // user keys, suffixes or values. The user keys, suffixes and values emitted are
> ```

I'm a bit confused here. If it doesn't copy keys or values why this "memory backing" comment?
___
*[internal/rangekey/coalescer.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mpwe2hQDpL521DslqLW:-Mpwe2hQDpL521DslqLX:b-zdz07f) ([raw file](https://github.com/cockroachdb/pebble/blob/86a8d93e528f61ea071606bbc7194acf1d27c1d2/internal/rangekey/coalescer.go#L254)):*
> ```Go
> 	c.largestSeqNum = s.Start.SeqNum()
> 
> 	switch s.Start.Kind() {
> ```

what is different about this switch statement code from Add?


<!-- Sent from Reviewable.io -->

2021-12-02 21:49 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1394)* status: all files reviewed, 10 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/coalescer.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MpwacxgAC5Feea17bg_:-Mpx1gb8BXHLC0g40TsU:b-fskp13) ([raw file](https://github.com/cockroachdb/pebble/blob/86a8d93e528f61ea071606bbc7194acf1d27c1d2/internal/rangekey/coalescer.go#L41)):*
> Also, a CoalescedSpan can eventually result in multiple internal key-value pairs, yes?

Yeah, that's right.

> In which case it should have more than one coalesced seqnum, one for the set and one for the unsets?

When internal keys are constructed from a `CoalescedSpan`, I was planning to make them all adopt the `LargestSeqNum` as their seqnum. And since we define that keys at the same sequence number don't affect each other (required for ingests), coalescing the resulting internal keys together should yield the same state.

 > And looks like RANGEKEYDELs influence the coalescing but aren't actually an output since they are not fully represented in a CoalescedSpan. Is that correct?

There's no outputting of the internal keys yet, but I was planning on outputing `RANGEKEYDEL`s too, with the `CoalescedSpan`'s start and end keys, and the `LargestSeqNum`. 
___
*[internal/rangekey/coalescer.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mpwbs7r6bu4Ero7Q3Z6:-Mpx3-Xq6UMBpzCSzfIw:bka4bay) ([raw file](https://github.com/cockroachdb/pebble/blob/86a8d93e528f61ea071606bbc7194acf1d27c1d2/internal/rangekey/coalescer.go#L55)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why does the order matter if the rangekeys are perfectly aligned?
</blockquote></details>

the shadowing and elision of keys is determined by their sequence numbers. eg, if calling `Add(RANGEKEYSET([a,c), @10, v2)#10` and then `Add(RANGEKEYSET([a,c), @10, v1)#8`, the first key wins. We don't retain the sequence numbers of every coalesced key, so the ordering is used to determine what shadows what.
___
*[internal/rangekey/coalescer.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mpwc3aa5aQCzKhuydwY:-Mpx3uLRBdhKUJPIU6DU:b-ay2a8y) ([raw file](https://github.com/cockroachdb/pebble/blob/86a8d93e528f61ea071606bbc7194acf1d27c1d2/internal/rangekey/coalescer.go#L60)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm a bit confused here. If it doesn't copy keys or values why this "memory backing" comment?
</blockquote></details>

The `CoalescedSpan.Items` slice is the `Coalescer.items.items` slice. A subsequent call to `Add` will start overwriting the items (although not the keys themselves). I'll call this out explicitly.
___
*[internal/rangekey/coalescer.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mpwe2hQDpL521DslqLW:-Mpx5FsT-7vBg1UCXlJo:bllnns4) ([raw file](https://github.com/cockroachdb/pebble/blob/86a8d93e528f61ea071606bbc7194acf1d27c1d2/internal/rangekey/coalescer.go#L254)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what is different about this switch statement code from Add?
</blockquote></details>

The implementation of shadowing is different, since we're receiving keys from oldest to newest now. For example, the handling of `RangeKeyDelete` in `AddReverse` clears `c.items`, because all previously added keys are shadowed by the range key delete. In `Add`, it only marks `c.delete = true` so that any future additions are dropped without ever appending them to `c.items`.
___
*[internal/rangekey/coalescer.go, line 268 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mpr4vnu8sq9jPoEcoTC:-Mpx54CR4L5l7V97lHfv:bnltliz) ([raw file](https://github.com/cockroachdb/pebble/blob/6eaa233dcd96d88e1879b0403890026b78639b31/internal/rangekey/coalescer.go#L268)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Is it possible to have "duplicate" aligned fragments in `c.items` (i.e. same start, end and suffix?). Would all of those have to be replaced?

I _think_ the answer is "no", but just wanted to check.
</blockquote></details>

Suffixes should be unique within items, so we should only need to replace 1.
___
*[internal/rangekey/testdata/coalescer, line 253 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MprJgQj3gsVGG8YWStg:-Mpx5vwE6c9HncdyNrES:bl6smxw) ([raw file](https://github.com/cockroachdb/pebble/blob/86a8d93e528f61ea071606bbc7194acf1d27c1d2/internal/rangekey/testdata/coalescer#L253)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Does it make sense to have a RANGEKEYDEL with a "logical value" (i.e. `@t5=foo`)? I assume that code elsewhere wouldn't look at the logical value when the key kind is RANGEKEYDEL, but it's still a little weird to encounter it.

In the "sequence number is the same" scenario, would it be possible to clear out `SuffixItems` when flushing the fragment if the key kind is RANGEKEYDEL?
</blockquote></details>

It's a little subtle here, but the DEL doesn't apply to the `@t5=foo`. When two keys are at the same sequence number, they don't affect one another (this is required for ingests, which ingest whole sstables at a single sequence number).


<!-- Sent from Reviewable.io -->

2021-12-02 23:54 UTC, nicktrav reviewed
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1394)* status: all files reviewed, 10 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/coalescer.go, line 61 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MpxYAZqC1uGojyWemhW:-MpxYAZqC1uGojyWemhX:bo3xgqm) ([raw file](https://github.com/cockroachdb/pebble/blob/e5876cb0541b42792b7ba54b0c0f786865634849/internal/rangekey/coalescer.go#L61)):*
> ```Go
> // The memory backing the CoalescedSpan.Items is only guaranteed to be unused
> // until the next Add or AddReverse call. Callers should make a copy of the
> // Items slice is they wish to retain it beyond the next call to Add or
> ```

nit: "if they wish"
___
*[internal/rangekey/testdata/coalescer, line 253 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MprJgQj3gsVGG8YWStg:-MpxYdO85JmSWtkCF_ug:bcbvrtq) ([raw file](https://github.com/cockroachdb/pebble/blob/86a8d93e528f61ea071606bbc7194acf1d27c1d2/internal/rangekey/testdata/coalescer#L253)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

It's a little subtle here, but the DEL doesn't apply to the `@t5=foo`. When two keys are at the same sequence number, they don't affect one another (this is required for ingests, which ingest whole sstables at a single sequence number).
</blockquote></details>

Oh, I must have missed that part. In that case, does it matter that we're eliding the RANGEKEYSET key but preserving its suffix and user-value? Is the value enough to resurrect it if we needed to?


<!-- Sent from Reviewable.io -->

2021-12-03 18:43 UTC, sumeerbhola requested changes
> Reviewed 1 of 5 files at r3, 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1394)* status: all files reviewed, 18 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/coalescer.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MpwacxgAC5Feea17bg_:-Mq0I1PNC54TnQMSoHRv:bm8n9da) ([raw file](https://github.com/cockroachdb/pebble/blob/86a8d93e528f61ea071606bbc7194acf1d27c1d2/internal/rangekey/coalescer.go#L41)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> Also, a CoalescedSpan can eventually result in multiple internal key-value pairs, yes?

Yeah, that's right.

> In which case it should have more than one coalesced seqnum, one for the set and one for the unsets?

When internal keys are constructed from a `CoalescedSpan`, I was planning to make them all adopt the `LargestSeqNum` as their seqnum. And since we define that keys at the same sequence number don't affect each other (required for ingests), coalescing the resulting internal keys together should yield the same state.

 > And looks like RANGEKEYDELs influence the coalescing but aren't actually an output since they are not fully represented in a CoalescedSpan. Is that correct?

There's no outputting of the internal keys yet, but I was planning on outputing `RANGEKEYDEL`s too, with the `CoalescedSpan`'s start and end keys, and the `LargestSeqNum`. 
</blockquote></details>

I am somewhat bothered by the use of the same seqnum when it isn't imposed on us (because of sharing the same InternalKey). I realize it is not incorrect.
 
___
*[internal/rangekey/coalescer.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0Ie930PYg3m5KEHpy:-Mq0Ie930PYg3m5KEHpz:b-xt18eh) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L43)):*
> ```Go
> // range keys (sets, unsets and deletes). Among overlapping fragments (which
> // must have the same bounds), fragments must be supplied in order of their
> // Start internal keys (when user keys are equal, descending by sequence number,
> ```

they have the same start and end key, so isn't "in order of their start internal keys" redundant?
___
*[internal/rangekey/coalescer.go, line 133 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0TLHz9wdo6O2cwIOX:-Mq0TLHz9wdo6O2cwIOY:b-ay8y98) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L133)):*
> ```Go
> 		panic("pebble: cannot change directions during range key coalescence")
> 	}
> ```

similar comments as the ones in AddReverse
___
*[internal/rangekey/coalescer.go, line 212 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0aFrXAEkj6y8atb-J:-Mq0aFrXAEkj6y8atb-K:b-1ub5ne) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L212)):*
> ```Go
> 	case base.InternalKeyKindRangeKeyDelete:
> 		// Record that all subsequent fragments with the same bounds should be
> 		// ignored, because they were deleted by this RangeKeyDelete.
> ```

need code comment as mentioned in AddReverse
___
*[internal/rangekey/coalescer.go, line 236 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0NcH040Urn5NQdeFJ:-Mq0NcH040Urn5NQdeFK:brirk0x) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L236)):*
> ```Go
> 			panic(fmt.Sprintf("pebble: range key key ordering invariant violated: %s > %s",
> 				c.formatKey(s.Start.UserKey), c.formatKey(c.start)))
> 		}
> ```

this should also check that the end keys are such the spans are not overlapping.
___
*[internal/rangekey/coalescer.go, line 249 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0NXSB4T0GK0nHZYcu:-Mq0NXSC99NbnjBvnucs:b-b4g139) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L249)):*
> ```Go
> 	} else {
> 		// TODO(jackson): Gate behind invariants.Enabled eventually.
> 		if base.InternalCompare(c.items.cmp, s.Start, c.prevKey) > 0 {
> ```

the preceding code has flushed if the starts were not equal. Should this be checking that the end keys are aligned too.
___
*[internal/rangekey/coalescer.go, line 261 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0Po6G5EOWtxkfh1qy:-Mq0Po6G5EOWtxkfh1qz:bpajq3s) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L261)):*
> ```Go
> 		n := len(c.items.items)
> 
> 		value := s.Value
> ```

can you add a comment stating the invariant that value represents a set of suffixes, i.e., there are no duplicates.
That helps with understanding why the `get` call only needs to consider the `n` suffixes that existed prior to this loop. 
___
*[internal/rangekey/coalescer.go, line 295 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0U7slAUWfvW9GeE6S:-Mq0U7smDKQDzDrVr-OW:b-ckdumd) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L295)):*
> ```Go
> 			if i := c.get(n, sv.Suffix); i < n {
> 				// This suffix is already set or unset at a lower sequence
> 				// number. Replace it.
> ```

what if the unset was at the same seqnum? I think we need a comment at the top of the file stating the assumption that overlapping RANGEKEYSET, RANGEKEYUNSET will have different seqnum, and justifying this by saying that ingested sstables must have collapsed these before writing.
We should have some defensive code that returns an error if this invariant is violated. Maybe track the seqnum in SuffixItem.
___
*[internal/rangekey/coalescer.go, line 308 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0ZS9H4X_UbJM1aBjk:-Mq0ZS9H4X_UbJM1aBjl:b-gegsjv) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L308)):*
> ```Go
> 		}
> 		sort.Sort(c.items)
> 	case base.InternalKeyKindRangeKeyDelete:
> ```

RANGEKEYDEL could have the same seqnum as a RANGEKEYSET since when we ingest a cockroachdb range snapshot we would lay down a RANGEKEYDEL to clear out the underlying key space. This happens to be correct because RANGEKEYDEL uses 19 which is lower than the 20, 21 used by the other two, so it will be encountered first during reverse iteration. This is definitely worth a code comment.

I just noticed that there is a discussion in the test case for this.


<!-- Sent from Reviewable.io -->

2021-12-03 19:38 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1394)* status: all files reviewed, 16 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/coalescer.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0Ie930PYg3m5KEHpy:-Mq0e43B1J0w-h-1W2lS:b-r0m06z) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L43)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

they have the same start and end key, so isn't "in order of their start internal keys" redundant?
</blockquote></details>

Dropped the 'when user keys are equal'.
___
*[internal/rangekey/coalescer.go, line 133 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0TLHz9wdo6O2cwIOX:-Mq0l_gxD_Hydlhz9S1w:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L133)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

similar comments as the ones in AddReverse
</blockquote></details>

Done.
___
*[internal/rangekey/coalescer.go, line 212 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0aFrXAEkj6y8atb-J:-Mq0mxtK-KtiMu3O6yaX:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L212)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

need code comment as mentioned in AddReverse
</blockquote></details>

Done.
___
*[internal/rangekey/coalescer.go, line 236 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0NcH040Urn5NQdeFJ:-Mq0jwdY0gl7WcvgJ0pm:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L236)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this should also check that the end keys are such the spans are not overlapping.
</blockquote></details>

Done.
___
*[internal/rangekey/coalescer.go, line 249 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0NXSB4T0GK0nHZYcu:-Mq0kU_n3e_iDd9ZwrOI:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L249)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the preceding code has flushed if the starts were not equal. Should this be checking that the end keys are aligned too.
</blockquote></details>

Done.
___
*[internal/rangekey/coalescer.go, line 261 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0Po6G5EOWtxkfh1qy:-Mq0fNeX22XIfErOmxy-:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L261)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a comment stating the invariant that value represents a set of suffixes, i.e., there are no duplicates.
That helps with understanding why the `get` call only needs to consider the `n` suffixes that existed prior to this loop. 
</blockquote></details>

Done.
___
*[internal/rangekey/coalescer.go, line 295 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0U7slAUWfvW9GeE6S:-Mq0f_0E4K1JgYptSRuE:b-3u7sks) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L295)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what if the unset was at the same seqnum? I think we need a comment at the top of the file stating the assumption that overlapping RANGEKEYSET, RANGEKEYUNSET will have different seqnum, and justifying this by saying that ingested sstables must have collapsed these before writing.
We should have some defensive code that returns an error if this invariant is violated. Maybe track the seqnum in SuffixItem.
</blockquote></details>

I'm not sure if you'll find this satisfying, but the sorting of internal keys (descending by seqnum, descending by kind) ensures that within the same sequence number we see `RANGEKEYSET`, `RANGEKEYUNSET` then `RANGEKEYDEL`. This ordering ensures each range key op doesn't affect each other range key op at the same sequence number. I added a comment to this effect. The `base.InternalCompare` invariant checks are a defense against out-of-order Adds (including within a sequence number). Added a comment at the top, plus above each key kind switch.
___
*[internal/rangekey/coalescer.go, line 308 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0ZS9H4X_UbJM1aBjk:-Mq0iHTVATAden6PZAXo:bvs2scm) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L308)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

RANGEKEYDEL could have the same seqnum as a RANGEKEYSET since when we ingest a cockroachdb range snapshot we would lay down a RANGEKEYDEL to clear out the underlying key space. This happens to be correct because RANGEKEYDEL uses 19 which is lower than the 20, 21 used by the other two, so it will be encountered first during reverse iteration. This is definitely worth a code comment.

I just noticed that there is a discussion in the test case for this.
</blockquote></details>

Yeah, this is in general how this code achieves the right semantics within the same sequence number. Added a comment at the top, plus above each key kind switch.
___
*[internal/rangekey/iter.go, line 182 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mpr_UdO5ctGrVgh7Yua:-Mq0nOyc2_yLf0pbm2va:b-i9ze3k) ([raw file](https://github.com/cockroachdb/pebble/blob/6eaa233dcd96d88e1879b0403890026b78639b31/internal/rangekey/iter.go#L182)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Wondering if there should be some "symmetry" here with the `i.dir == -1 && i.valid` case in `(*Iter).Next()`. Here, we're not checking the return value, but we are in `Next()`.

Can `Next()` be simplified to allow the check to happen outside of the `switch` statement, where we check the validity of the iterator?
</blockquote></details>

good catch, yeah that was some refactoring detritus
___
*[internal/rangekey/testdata/iter, line 11 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mprb4_f-ZnbAbK-x4WW:-Mq0m7WIAwOiYi5P11c7:buuan1o) ([raw file](https://github.com/cockroachdb/pebble/blob/6eaa233dcd96d88e1879b0403890026b78639b31/internal/rangekey/testdata/iter#L11)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Is it valid to have a suffixes sorted ascending like this? In the iterator output below, it looks like we sort before emitting, so there's no issue, but just wanted to check if this was technically valid?
</blockquote></details>

Oops, no it's not. fixed!
___
*[internal/rangekey/testdata/iter, line 32 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MpraYAf-4sv_SxQ_DyA:-Mq0mjxvAxVspQ4biaAA:bajints) ([raw file](https://github.com/cockroachdb/pebble/blob/6eaa233dcd96d88e1879b0403890026b78639b31/internal/rangekey/testdata/iter#L32)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

I left a comment elsewhere about having RANGEKEYSET and RANGEKEYDEL at the same sequence number, and emitting a value with the latter. This line is more in line with what I'd expect to encounter (i.e. no user value).
</blockquote></details>

yeah, in this case there's no user value since there were no sets for this keyspan at sequence numbers ≥ 22, but if there were, there would be a user value too.


<!-- Sent from Reviewable.io -->

2021-12-06 16:12 UTC, sumeerbhola requested changes
> Reviewed 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1394)* status: 0 of 6 files reviewed, 19 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/coalescer.go, line 295 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0U7slAUWfvW9GeE6S:-MqFL8W18Sn3fTpwHOBO:boyi6h1) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L295)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I'm not sure if you'll find this satisfying, but the sorting of internal keys (descending by seqnum, descending by kind) ensures that within the same sequence number we see `RANGEKEYSET`, `RANGEKEYUNSET` then `RANGEKEYDEL`. This ordering ensures each range key op doesn't affect each other range key op at the same sequence number. I added a comment to this effect. The `base.InternalCompare` invariant checks are a defense against out-of-order Adds (including within a sequence number). Added a comment at the top, plus above each key kind switch.
</blockquote></details>

This is mostly satisfying, but we are not preserving the RANGEKEYUNSET in the following sequence:
a.RANGEKEYSET.10: c@10
a.RANGEKEYUNSET.10: c@10
The former will replace the latter when executing
```
			if i := c.get(n, sv.Suffix); i < n {
				// This suffix is already set or unset at a lower sequence
				// number. Replace it.
```
This is why I was assuming we were requiring ingested sstables to not have RANGEKEYSET, RANGEKEYUNSET at the same seqnum.  If we don't require this, it suggests we need the ability to track up to two identical suffixes in `suffixItems`, with set and unset. The code comment like "this ensures that none of the range keys sharing a sequence number shadow each other" and "Within a sequence number, none of the internal range keys affect one another" reinforce this impression.

I am assuming we don't bother because the RANGEKEYUNSET is actually useless in this case since anything (set or unset) at a lower sequence number will be shadowed by the set. But this situation is strange and I think a case where we could be stricter in general even for point keys: `compactionIter` gets away with similar behavior for SET and DEL since SET is ordered before DEL. But it also does the same for SINGLEDEL even though it is ordered before SET. Which means it is making an assumption that SINGLEDEL and SET will not have identical seqnums. I can create an issue to do the stricter checking in general, after this PR merges.
___
*[internal/rangekey/iter.go, line 26 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MqFVrhc9ZRCaYwfb952:-MqFVrhc9ZRCaYwfb953:b-ss44dr) ([raw file](https://github.com/cockroachdb/pebble/blob/bc6c92de7a2344f0f078fcd5eedc55915beeda84/internal/rangekey/iter.go#L26)):*
> ```Go
> // are no longer relevant.
> type Iter struct {
> 	iter      *keyspan.Iter
> ```

will `Iter` eventually wrap an interface that produces fragmented spans?
___
*[internal/rangekey/iter.go, line 158 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MqFUNsh0KFimDWcTmE4:-MqFUNsh0KFimDWcTmE5:bobhxsv) ([raw file](https://github.com/cockroachdb/pebble/blob/bc6c92de7a2344f0f078fcd5eedc55915beeda84/internal/rangekey/iter.go#L158)):*
> ```Go
> 		// previous set of fragments. Move forward once to move to the first of
> 		// the next set of fragments.
> 		i.dir = +1
> ```

Is it correct to say that the invariant here is that this iterator must have at least two coalesced spans? Since we couldn't have a non-exhausted reverse iterator if it hadn't already produced a coalesced span. So the statement `_ = i.Next()` could actually check that the return value is non-nil and if nil enter an error state.
___
*[internal/rangekey/iter.go, line 200 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MqFVBK5CYcj7JUBGbEX:-MqFVBK5CYcj7JUBGbEY:bcffrx7) ([raw file](https://github.com/cockroachdb/pebble/blob/bc6c92de7a2344f0f078fcd5eedc55915beeda84/internal/rangekey/iter.go#L200)):*
> ```Go
> 			// returned coalesced span. The caller Prev'd because they want the
> 			// coalesced span before that, so Prev() once [on this iter, not the
> 			// inner iter] to skip over it.
> ```

same comment about error checking


<!-- Sent from Reviewable.io -->

2021-12-06 19:27 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1394)* status: 0 of 6 files reviewed, 19 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/coalescer.go, line 295 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1394#-Mq0U7slAUWfvW9GeE6S:-MqFkjxf0LVy37azq6yB:b-2g0pft) ([raw file](https://github.com/cockroachdb/pebble/blob/e8ae58588e6a806a2756db50e2ec880ef1fcf4cb/internal/rangekey/coalescer.go#L295)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is mostly satisfying, but we are not preserving the RANGEKEYUNSET in the following sequence:
a.RANGEKEYSET.10: c@10
a.RANGEKEYUNSET.10: c@10
The former will replace the latter when executing
```
			if i := c.get(n, sv.Suffix); i < n {
				// This suffix is already set or unset at a lower sequence
				// number. Replace it.
```
This is why I was assuming we were requiring ingested sstables to not have RANGEKEYSET, RANGEKEYUNSET at the same seqnum.  If we don't require this, it suggests we need the ability to track up to two identical suffixes in `suffixItems`, with set and unset. The code comment like "this ensures that none of the range keys sharing a sequence number shadow each other" and "Within a sequence number, none of the internal range keys affect one another" reinforce this impression.

I am assuming we don't bother because the RANGEKEYUNSET is actually useless in this case since anything (set or unset) at a lower sequence number will be shadowed by the set. But this situation is strange and I think a case where we could be stricter in general even for point keys: `compactionIter` gets away with similar behavior for SET and DEL since SET is ordered before DEL. But it also does the same for SINGLEDEL even though it is ordered before SET. Which means it is making an assumption that SINGLEDEL and SET will not have identical seqnums. I can create an issue to do the stricter checking in general, after this PR merges.
</blockquote></details>

I see, that makes sense. I expanded the comments here to explicitly call out this case of setting and unsetting the same suffix at the same sequence number.
___
*[internal/rangekey/iter.go, line 26 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MqFVrhc9ZRCaYwfb952:-MqGA5jB-26Z2SMiAgDF:b-v6348a) ([raw file](https://github.com/cockroachdb/pebble/blob/bc6c92de7a2344f0f078fcd5eedc55915beeda84/internal/rangekey/iter.go#L26)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

will `Iter` eventually wrap an interface that produces fragmented spans?
</blockquote></details>

Yeah, that's my current plan.

I've considered two options so far:

1. We implement a merging range key iter that, like you said, is wrapped by `rangekey.Iter` and fragments `keyspan.Span`s across levels of rangekey iters, producing an iterator over fragmented spans.
2. We implement a merging range key iter that sits above this `rangekey.Iter` and handles fragmenting and coalescing `CoalescedSpans` across levels of `rangekey.Iter`s

The second option duplicates a lot of logic around fragmentation and coalescence, so I've been planning on the first option.
___
*[internal/rangekey/iter.go, line 158 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MqFUNsh0KFimDWcTmE4:-MqG9ewM5T1vjDl0dYQa:b-wszehd) ([raw file](https://github.com/cockroachdb/pebble/blob/bc6c92de7a2344f0f078fcd5eedc55915beeda84/internal/rangekey/iter.go#L158)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is it correct to say that the invariant here is that this iterator must have at least two coalesced spans? Since we couldn't have a non-exhausted reverse iterator if it hadn't already produced a coalesced span. So the statement `_ = i.Next()` could actually check that the return value is non-nil and if nil enter an error state.
</blockquote></details>

Yeah, good point. Since the iterator is valid, there necessarily must be a next fragment. Added this check and a brief diagram + expanded comments.
___
*[internal/rangekey/iter.go, line 200 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MqFVBK5CYcj7JUBGbEX:-MqG9ppv9SRbi4JKyF3m:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/bc6c92de7a2344f0f078fcd5eedc55915beeda84/internal/rangekey/iter.go#L200)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same comment about error checking
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-06 21:33 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 5 files at r7, 2 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1394#-:-MqGeTNd6ihiuXkaqvqs:bg7igkv)* status: 2 of 6 files reviewed, 21 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/iter.go, line 178 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MqGeDXY9Y3EjcTfg8YD:-MqGeDXY9Y3EjcTfg8YE:bcj4pq1) ([raw file](https://github.com/cockroachdb/pebble/blob/67f373ac08791c2eb4f4bdbd8de5e601be09e1f3/internal/rangekey/iter.go#L178)):*
> ```Go
> 		// because they want the coalesced span after that, so Next() once [on
> 		// this iter, not the inner iter] to skip over it.
> 		_ = i.Next()
> ```

can we also check that this returns a non-nil coalesced span.
___
*[internal/rangekey/iter.go, line 225 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1394#-MqGeNYz2DsaJ44FePl4:-MqGeNYz2DsaJ44FePl5:b-duc46) ([raw file](https://github.com/cockroachdb/pebble/blob/67f373ac08791c2eb4f4bdbd8de5e601be09e1f3/internal/rangekey/iter.go#L225)):*
> ```Go
> 		// because they want the coalesced span before that, so Prev() once [on
> 		// this iter, not the inner iter] to skip over it.
> 		_ = i.Prev()
> ```

same comment


<!-- Sent from Reviewable.io -->

2021-12-07 17:15 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1394#-:-MqKtA187DkC7XGCPmk8:bz5mair)* status: 1 of 6 files reviewed, 21 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-12-07 17:18 UTC, merged