internal/rangekey: add InterleavingIter
cockroachdb/pebble pull request #1399
Opened 2021-12-08 00:11 UTC by jbowens

Add an InterleavingIter implementation of the InternalIterator interface that
wraps another InternalIterator and a `*rangekey.Iter`, interleaving the two.
An `InterleavingIter` steps through both a point iterator and a range key
iterator in tandem. At any point, a caller may query its `RangeKey()` method to
retrieve the range key covering the current iterator position, if any.
Additionally, when an interleaving iterator passes over the inclusive start
boundary of a range key, it returns a key with the special InternalKey trailer
`InternalKeyBoundaryRangeKey`. This key (with the RangeKeySet key-kind and an
infinite sequence number) indicates the beginning of a range key.

Eventually, the `*pebble.Iterator` will use an `InterleavingIter` when
configured to surface range keys.

2021-12-08 00:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1399)
<!-- Reviewable:end -->

2021-12-08 19:29 UTC, nicktrav reviewed
Still reading. Flushing some comments.

> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399#-:-MqQWO8O8bUq2R1aw1QU:bzgx1zj)* status: 3 of 5 files reviewed, 12 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/coalescer.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQN6oI2HdGp6dGRwtt:-MqQN6oI2HdGp6dGRwtu:b8i6jsf) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/coalescer.go#L35)):*
> ```Go
> // only contain unsets or deletes. If encountered during user iteration, these
> // range keys may be elided.
> func (s *CoalescedSpan) Sets() bool {
> ```

nit: `HasSets`? When reading the code I parse the return value as "a collection of the RANGEKEYSETs for the span". Not sure if there's a Go idiom for these types of functions.
___
*[internal/rangekey/coalescer.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQT4JVAYjMZVrs3aTm:-MqQT4JVAYjMZVrs3aTn:b1neorc) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/coalescer.go#L35)):*
> ```Go
> // only contain unsets or deletes. If encountered during user iteration, these
> // range keys may be elided.
> func (s *CoalescedSpan) Sets() bool {
> ```

nit: tests?
___
*[internal/rangekey/coalescer.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQT7uj8ioq8MlTd7Oj:-MqQT7uj8ioq8MlTd7Ok:b-mupnpw) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/coalescer.go#L36)):*
> ```Go
> // range keys may be elided.
> func (s *CoalescedSpan) Sets() bool {
> 	for _, i := range s.Items {
> ```

In practice I assume that for-looping over all the items has immaterial cost? Looks like we need to do this on every iteration, so I wonder if it would make sense to set some bit in the span upon construction to avoid the loop.

Probably premature optimization.
___
*[internal/rangekey/interleaving_iter.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQQJUi3Gi1AQMd_7SQ:-MqQQJUi3Gi1AQMd_7SR:b-e2yj70) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter.go#L16)):*
> ```Go
> // asserts. We should eventually gate these behind `invariants.Enabled`.
> 
> // InterleavingIter combines an iterator over point keys with an iterator over
> ```

Maybe this is "assumed" for an iterator, and / or because I haven't read enough iterator code yet: during iteration we elide range key spans that don't contain at least one RANGEKEYSET.

I wasn't sure if there was something special about the case where there are RANGEKEYSETs and RANGEKEYUNSETs "interleaved" in the same `CoalescedSpan`. In that case, my current reading is that we return the span, and it's then up to the caller to iterate through the suffix-values?
___
*[internal/rangekey/interleaving_iter.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQJ_RWAk_854mBfjgr:-MqQJ_RWAk_854mBfjgs:b6fk4rw) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter.go#L41)):*
> ```Go
> 	pointVal []byte
> 	rangeKey *CoalescedSpan
> 	// rangeKeyMarker is holds synthetic RangeKeySet keys returned when the
> ```

nit: `s/is //`
___
*[internal/rangekey/interleaving_iter.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQKKJd9Rf0J1WmqKgh:-MqQKKJd9Rf0J1WmqKgi:b-kvhwts) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter.go#L58)):*
> 	// interleaved when first passing over the start key. The rangeKey field
>	// isn't updated until the iterator moves beyond the end key. This field is

nit: I wasn't sure how to read this at first. Would `... isn't updated again ...` be slightly clearer, to  indicate that the state machine is paused for the range while iterating over point keys within it?
___
*[internal/rangekey/interleaving_iter.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQOuc_9e5rxMI9Io0K:-MqQOuc_9e5rxMI9Io0L:bvi4jen) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter.go#L278)):*
> ```Go
> 		// past the current point key.
> 		if i.rangeKeyInterleaved {
> 			i.nextRangeKey()
> ```

In the case that there are no more eligible range keys left in the iterator, and `i.rangeKey` is `nil`. Then when we call `i.syntheticRangeKeyMarker()`, we deref `i.rangeKey.Start`, which would panic?
___
*[internal/rangekey/interleaving_iter.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQUVqSBG3_bDzkVVMD:-MqQUVqSBG3_bDzkVVME:b-scis7u) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter.go#L349)):*
> ```Go
> 	for {
> 		i.rangeKey = i.rangeKeyIter.Prev()
> 		i.rangeKeyInterleaved = false
> ```

Can this go outside the loop?
___
*[internal/rangekey/interleaving_iter.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQOJQZ7vL5XQp71_wq:-MqQOJQZ7vL5XQp71_wr:b7nma3p) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter.go#L358)):*
> ```Go
> func (i *InterleavingIter) syntheticRangeKeyMarker() (*base.InternalKey, []byte) {
> 	i.rangeKeyMarker.UserKey = i.rangeKey.Start
> 	i.rangeKeyMarker.Trailer = base.InternalKeyBoundaryRangeKey
> ```

This line is effectively static. Would it makes sense to move into`Init()`? I'm sure the performance gained is immaterial, so if it reads clearer here, there's probably no point.
___
*[internal/rangekey/interleaving_iter.go, line 364 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQVqPBDWljnS1_wneL:-MqQVqPBDWljnS1_wneM:blklac8) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter.go#L364)):*
Worth restating the following point from the struct doc? i.e. up to the caller to handle the bounds on the range.

> // Similarly, returned range keys' bounds are not
> // truncated to the bounds set through SetBounds. InterleavingIter will
> // propagate SetBounds calls to its underlying point iterator.
___
*[internal/rangekey/interleaving_iter.go, line 371 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQV7sXBJUXzL5ggIz0:-MqQV7sXBJUXzL5ggIz1:b-yzl2ao) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter.go#L371)):*
> ```Go
> // Error implements (base.InternalIterator).Error.
> func (i *InterleavingIter) Error() error {
> 	return i.pointIter.Error()
> ```

`rangekey.Iter` seems to have an `Error()` function too. Is it possible to have an error on that iterator too that should be returned instead of an error on the point iterator?
___
*[internal/rangekey/interleaving_iter_test.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQTzFjDk9v-BfQ1HCe:-MqQTzFjDk9v-BfQ1HCf:b-6waw92) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter_test.go#L90)):*
> ```Go
> 					formatKey(iter.SeekLT([]byte(strings.TrimSpace(line[i:]))))
> 				default:
> 					return fmt.Sprintf("unrecognized iter command %q", iterCmd)
> ```

Is `SetBounds` relevant to this type of iterator? Worth testing? Same for `SeekPrefixGE`.


<!-- Sent from Reviewable.io -->

2021-12-08 20:36 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/coalescer.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQN6oI2HdGp6dGRwtt:-MqQhhH21kJWarnvFcCx:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/coalescer.go#L35)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: `HasSets`? When reading the code I parse the return value as "a collection of the RANGEKEYSETs for the span". Not sure if there's a Go idiom for these types of functions.
</blockquote></details>

Done.
___
*[internal/rangekey/interleaving_iter.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQOuc_9e5rxMI9Io0K:-MqQkksC3msosyfnn_r1:bd30ifx) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter.go#L278)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

In the case that there are no more eligible range keys left in the iterator, and `i.rangeKey` is `nil`. Then when we call `i.syntheticRangeKeyMarker()`, we deref `i.rangeKey.Start`, which would panic?
</blockquote></details>

good catch
___
*[internal/rangekey/interleaving_iter.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQUVqSBG3_bDzkVVMD:-MqQiiQr1wY8WJeKS57f:b8wkl2v) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter.go#L349)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Can this go outside the loop?
</blockquote></details>

thanks, refactored nextRangeKey but forgot to update prevRangeKey


<!-- Sent from Reviewable.io -->

2021-12-08 20:43 UTC, nicktrav reviewed
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @jbowens and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-12-08 21:27 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/coalescer.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQT7uj8ioq8MlTd7Oj:-MqQp4YzCEMIkLzN5QUi:b-3a0jgp) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/coalescer.go#L36)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

In practice I assume that for-looping over all the items has immaterial cost? Looks like we need to do this on every iteration, so I wonder if it would make sense to set some bit in the span upon construction to avoid the loop.

Probably premature optimization.
</blockquote></details>

Yeah, I'm expecting this loop to not matter — we most range keys in the LSM should be Sets, since Unsets and Dels may be elided from L6, and we expect few per sstable. Let's see if it shows up in any profiles.
___
*[internal/rangekey/interleaving_iter.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQQJUi3Gi1AQMd_7SQ:-MqQpWKK3TTBWWPT-TxU:bbsmsla) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter.go#L16)):*
>  it's then up to the caller to iterate through the suffix-values?

Yeah, that's right. The fact that knowledge of Unsets and Deletes still exists here during iteration is a side effect of the `Coalescer` and `CoalescedSpan`types being shared between compactions and iteration.
___
*[internal/rangekey/interleaving_iter.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQOJQZ7vL5XQp71_wq:-MqQsOVA-k8NL092E0y6:booi5vs) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter.go#L358)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

This line is effectively static. Would it makes sense to move into`Init()`? I'm sure the performance gained is immaterial, so if it reads clearer here, there's probably no point.
</blockquote></details>

Yeah, IMO it does read a little clearer.
___
*[internal/rangekey/interleaving_iter_test.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQTzFjDk9v-BfQ1HCe:-MqQvp5SEoucqdKIWHjk:bgemwqu) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter_test.go#L90)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Is `SetBounds` relevant to this type of iterator? Worth testing? Same for `SeekPrefixGE`.
</blockquote></details>

`SetBounds` doesn't affect the range key iterator, and `SeekPrefixGE` is only implemented as `SeekGE` on the range key iterator. I'm planning on deferring testing those interactions to when this is integrated into the `Iterator`, because there we'll have a `pointIter` that meaningfully implements `SeekPrefixGE` and `SetBounds` and there are interesting interactions to test there. 


<!-- Sent from Reviewable.io -->

2021-12-08 22:38 UTC, nicktrav approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Nice! Test cases are great too.

> Reviewed 3 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399#-:-MqRBXB01U0WY5gRrAGW:b-8ipumh)* status: all files reviewed, 4 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/interleaving_iter.go, line 164 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQvjlN2A7HPQ40_NMk:-MqQvjlN2A7HPQ40_NMl:b4od89a) ([raw file](https://github.com/cockroachdb/pebble/blob/0874c9ab158d653fad7229427943afed6dd77185/internal/rangekey/interleaving_iter.go#L164)):*
> ```Go
> 		// Switching directions.
> 		i.dir = +1
> 		// Exactly one of {pointKey,rangeKey}Interleaved must be true if we were
> ```

Is this eligible for an `INVARIANT: ...` type comment too?
___
*[internal/rangekey/interleaving_iter.go, line 193 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQvAf-1k26vKFsxS3k:-MqQvAf-1k26vKFsxS3l:bkofs0p) ([raw file](https://github.com/cockroachdb/pebble/blob/0874c9ab158d653fad7229427943afed6dd77185/internal/rangekey/interleaving_iter.go#L193)):*
> ```Go
> 		//                            ^
> 		// i.rangeKey.Start is the key we last returned during backward
> 		// iteration. From the perspective of forward-iteration, it's the start
> ```

nit: `s/it's //`
___
*[internal/rangekey/interleaving_iter.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQx-mW9OUdcg8NOOzJ:-MqQx-mW9OUdcg8NOOzK:b-mkx50d) ([raw file](https://github.com/cockroachdb/pebble/blob/0874c9ab158d653fad7229427943afed6dd77185/internal/rangekey/interleaving_iter.go#L255)):*
> ```Go
> 		i.prevRangeKey()
> 	}
> 	return i.mergeBackward()
> ```

Meta comment: I wonder if there's some kind of `defer`-like invariant check we can add to these? Presumably after each type of movement (forward, back, first, last, etc.), either a point key or range key has been interleaved?
___
*[internal/rangekey/interleaving_iter_test.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQTzFjDk9v-BfQ1HCe:-MqR5o0F-oaoKIQA-RaN:b-81nlyc) ([raw file](https://github.com/cockroachdb/pebble/blob/31109b4f6e38ba837ae1fcfec7572015d5f74539/internal/rangekey/interleaving_iter_test.go#L90)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

`SetBounds` doesn't affect the range key iterator, and `SeekPrefixGE` is only implemented as `SeekGE` on the range key iterator. I'm planning on deferring testing those interactions to when this is integrated into the `Iterator`, because there we'll have a `pointIter` that meaningfully implements `SeekPrefixGE` and `SetBounds` and there are interesting interactions to test there. 
</blockquote></details>

SGTM.


<!-- Sent from Reviewable.io -->

2021-12-09 05:00 UTC, sumeerbhola requested changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399)* status: all files reviewed, 12 unresolved discussions (waiting on @jbowens)

___
*[internal/rangekey/interleaving_iter.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSSr8YDtzsPhV-NzWJ:-MqSSr8YDtzsPhV-NzWK:bl7mtny) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L25)):*
> ```Go
> // RangeKeySet key kind. Because these synthetic keys have the infinite sequence
> // number, they're interleaved before any point keys with same user key when
> // iterating forward.
> ```

May be worth adding a motivation for using the infinite sequence number versus the sequence number of the range key. I am assuming because we can utilize this for masking, by layering another iterator on top, where the relative seqnums of the range key and point key are irrelevant.
What about iteration in the reverse direction -- do we still use the start key?
___
*[internal/rangekey/interleaving_iter.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSTtPI5bSgc1cti86C:-MqSTtPI5bSgc1cti86D:b-gegmb8) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L63)):*
> ```Go
> 	// isn't updated again until the iterator moves beyond the end key. This
> 	// field is used to remember that the range key has already been interleaved
> 	// and shouldn't be interleaved again.
> ```

How is this field used in the reverse direction?
___
*[internal/rangekey/interleaving_iter.go, line 111 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSUVAfEFe6NS5x1I0l:-MqSUVAfEFe6NS5x1I0m:b-9yheoj) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L111)):*
> ```Go
> 	// to the levelIter implementation to ensure that SeekPrefixGE on the point
> 	// iterator loads files that do not contain `prefix` but may contain a range
> 	// key covering `prefix`.
> ```

If we retain this structure of two iterators in the more complete implementation won't there be two `mergingIters` each with their own `levelIters` so it wouldn't matter, since these two iters don't need to be synchronized wrt files?
___
*[internal/rangekey/interleaving_iter.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSWxNwCL0xiGIuWzpd:-MqSWxNwCL0xiGIuWzpe:b-dl9aqf) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L168)):*
> ```Go
> 		i.dir = +1
> 		// Exactly one of {pointKey,rangeKey}Interleaved must be true if we were
> 		// previously going in the backward direction.
> ```

Because we interleave the range key at the start key, so from an interleaving perspective it is behaving like a point?
___
*[internal/rangekey/interleaving_iter.go, line 175 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSXajwApzymxNYAFq2:-MqSXajwApzymxNYAFq3:b-aagy42) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L175)):*
> ```Go
> 
> 		// The existing point key is either the last point key we returned, or
> 		// the upcoming point key in the backward direction. Move to the next.
> ```

This took me a minute to visualize to see why doing the same thing for both cases is correct. Could use an example here.
___
*[internal/rangekey/interleaving_iter.go, line 233 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSYZJC1btwvpwOp-DE:-MqSYZJC1btwvpwOp-DF:b37al0d) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L233)):*
> ```Go
> 		// Since we were previously iterating forward, the current range-key
> 		// start key may be less than, equal, or greater than the current
> 		// iterator position. If it's marked as having already been interleaved,
> ```

won't it be marked as interleaved if we just emitted the synthetic marker in the forward direction? In which case Prev should not see this range key again?
An example here would help.
___
*[internal/rangekey/interleaving_iter.go, line 298 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSB5pg3LbfpIm0YBh1:-MqSB5pg3LbfpIm0YBh2:b7d41cg) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L298)):*
> ```Go
> 		// returning a point key, but we need to determine if the point key is
> 		// covered by the current range key.
> 		i.rangeKeyCoversKey = c >= 0
> ```

So `i.rangeKeyCoversKey` will be true when we've fallen here because the previous time we emitted the synthetic marker?
Why does that mean that `rangeKeyCoversKey` is true. Couldn't the range key be [a,b) and the point key be c?
___
*[internal/rangekey/interleaving_iter.go, line 363 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSVP6YAXaplsGVX-gN:-MqSVP6Z42lrJLGJS33n:br4yeul) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L363)):*
> ```Go
> func (i *InterleavingIter) syntheticRangeKeyMarker() (*base.InternalKey, []byte) {
> 	i.rangeKeyMarker.UserKey = i.rangeKey.Start
> 	i.rangeKeyMarker.Trailer = base.InternalKeyBoundaryRangeKey
> ```

Due to this `InternalKeyBoundaryRangeKey`, this `InternalKey` isn't actually "covered by" the range key. Or maybe I am misunderstanding the definition of `rangeKeyCoversKey`. Could you add a definition of "covers".


<!-- Sent from Reviewable.io -->

2021-12-10 15:37 UTC, jbowens reviewed
I made some substantial changes,
* SetBounds is enforced by the interleaving iter now, truncating the range key bounds as necessary.
* The synthetic range key marker may also be truncated. In the case of a SeekGE(k) where k > the overlapping range key start, the marker's key is truncated to k.
* Some invariant checks are pulled out into a `verify` function, similar to the `levelIter`'s `verify` method.
* All iterator returns funnel through `yield{Nil,Point,SyntheticRangeKeyMarker}` to keep some of the state management and invariant checking organized.
* Rather than exposing the `CoalescedSpan` directly, the `InterleavingIter` exposes separate `HasRangeKey()`, `RangeKeyBounds()` and `RangeKeys()` methods. This is motivated by the range key bounds truncation, and not wanting to mutate the `CoalescedSpan` nor copy `CoalescedSpan` state that we don't require.


PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399#-:-MqZwwWp6Pynq8UZEkZA:bpeguea)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[internal/rangekey/interleaving_iter.go, line 164 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQvjlN2A7HPQ40_NMk:-MqUedQQ8GrH0V3VkjlJ:bb7f2mf) ([raw file](https://github.com/cockroachdb/pebble/blob/0874c9ab158d653fad7229427943afed6dd77185/internal/rangekey/interleaving_iter.go#L164)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Is this eligible for an `INVARIANT: ...` type comment too?
</blockquote></details>

done
___
*[internal/rangekey/interleaving_iter.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqQx-mW9OUdcg8NOOzJ:-MqW9j3TChsbfsDnBCBM:bbhx8r8) ([raw file](https://github.com/cockroachdb/pebble/blob/0874c9ab158d653fad7229427943afed6dd77185/internal/rangekey/interleaving_iter.go#L255)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Meta comment: I wonder if there's some kind of `defer`-like invariant check we can add to these? Presumably after each type of movement (forward, back, first, last, etc.), either a point key or range key has been interleaved?
</blockquote></details>

Refactored to funnel return values through a `.verify` method, like how the `levelIter` does.
___
*[internal/rangekey/interleaving_iter.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSSr8YDtzsPhV-NzWJ:-MqV1QWZ37kIKxzNcJrK:ba9c309) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L25)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

May be worth adding a motivation for using the infinite sequence number versus the sequence number of the range key. I am assuming because we can utilize this for masking, by layering another iterator on top, where the relative seqnums of the range key and point key are irrelevant.
What about iteration in the reverse direction -- do we still use the start key?
</blockquote></details>

I expanded this comment to explain the motivation.

Yeah, we still only use the start key in reverse: Since the end boundary is exclusive, it doesn't fit in nicely with the interleaving. It's also not necessary, since if there exists a range key overlapping the span of keyspace being iterated, we'll either hit a point key or the start key. Either way, we're guaranteed to encounter the overlapping range key.
___
*[internal/rangekey/interleaving_iter.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSTtPI5bSgc1cti86C:-MqUnT_y-RJJrEvlSsWF:b-tk6nkg) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L63)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How is this field used in the reverse direction?
</blockquote></details>

Added some commentary
___
*[internal/rangekey/interleaving_iter.go, line 111 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSUVAfEFe6NS5x1I0l:-MqUzAbB6sXzgjAYU09H:bysvduk) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L111)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If we retain this structure of two iterators in the more complete implementation won't there be two `mergingIters` each with their own `levelIters` so it wouldn't matter, since these two iters don't need to be synchronized wrt files?
</blockquote></details>

If we wanted to share the `sstable.Reader`s, I was thinking that we could share the `levelIter`s but integrate the point iter and range key iter into separate heaps managed by the mergingIter. There would be a lot of interlocking pieces to make that work and ensure we reorganize both heaps when a moving from one sstable to the next.

I'm now thinking that probably would end up too complicated. Separate levelIters also sidesteps the `RANGEDEL` `SeekGE` optimization problem that we talked about at the team meeting, allowing the two levelIter to look at different sstables based on their own `RANGEDEL` and `RANGEKEYDEL` states. I'll remove this comment
___
*[internal/rangekey/interleaving_iter.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSWxNwCL0xiGIuWzpd:-MqUfCwnAKeIZ1Ga-dCy:b-ucp2sz) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L168)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Because we interleave the range key at the start key, so from an interleaving perspective it is behaving like a point?
</blockquote></details>

Yeah, exactly. Expanded this explanation in the Prev() check of this same invariant
___
*[internal/rangekey/interleaving_iter.go, line 175 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSXajwApzymxNYAFq2:-MqUlk6_7l-tS8-RF5Wi:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L175)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This took me a minute to visualize to see why doing the same thing for both cases is correct. Could use an example here.
</blockquote></details>

Done.
___
*[internal/rangekey/interleaving_iter.go, line 233 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSYZJC1btwvpwOp-DE:-MqZvodaAyah7vwGOYbV:b-z4b09z) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L233)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

won't it be marked as interleaved if we just emitted the synthetic marker in the forward direction? In which case Prev should not see this range key again?
An example here would help.
</blockquote></details>

Yeah, there was a bug here that was a little tricky to solve. Included an example in the fix.
___
*[internal/rangekey/interleaving_iter.go, line 298 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSB5pg3LbfpIm0YBh1:-MqWmAumAQF-NTmWXtd3:b-tmbvph) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L298)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So `i.rangeKeyCoversKey` will be true when we've fallen here because the previous time we emitted the synthetic marker?
Why does that mean that `rangeKeyCoversKey` is true. Couldn't the range key be [a,b) and the point key be c?
</blockquote></details>

We're relying on `Next` to have already advanced past the range key `[a, b)` because it's already interleaved. 

I refactored these conditionals to make it a little clearer, expanded the commentary and docum [...]

2021-12-13 16:28 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399)* status: 4 of 6 files reviewed, 12 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[internal/rangekey/interleaving_iter.go, line 301 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqajhieAIPwMq3X_DAv:-MqoXoHI8k3JeD2tTCEa:bjjzuo5) ([raw file](https://github.com/cockroachdb/pebble/blob/f7316eb7e887460a67de9375cffd203390f7d18b/internal/rangekey/interleaving_iter.go#L301)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

I'll admit that I found it a little surprising to see this appear here (i.e. it's up to the caller). Was the reason adding this constraint that it simplified the code somehow? Or is strictly a correctness thing?

Put another way, I was surprised that if the iterator state upon entering this function is`range key = [a, b), point key = c`, then it would be in violation of the constraint. Feels like a "merging" operation would be responsible for correcting the state.

edit: ah, perhaps it's this new `yieldPointKey(covered / uncovered)` function.
</blockquote></details>

Lifting it into the caller avoids redundant work for the absolute positioning methods. During a `SeekGE` we're guaranteed to have not interleaved the range key. Only during a `Next` is it possible that we need to move the range key iterator forward.
___
*[internal/rangekey/interleaving_iter.go, line 504 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqamJZS5vtM_yjrMpa9:-MqoZnB_E2vJ-Go3gu_T:brj5wyz) ([raw file](https://github.com/cockroachdb/pebble/blob/f7316eb7e887460a67de9375cffd203390f7d18b/internal/rangekey/interleaving_iter.go#L504)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

For these two if-blocks, it _seems_ like we're truncating. Should that imply that we set `i.rangeKeyTruncated`?
</blockquote></details>

Added some clarification here and renamed the flag to make this clearer: this flag gets set when we truncate the synthetic start-key marker to the SeekGE/SeekPrefixGE search key only.
___
*[internal/rangekey/testdata/interleaving_iter, line 146 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1399#-Mqb8wN8C6FqCUsJCAUJ:-Mqo_paW6gCzuBEOTJku:b51a27p) ([raw file](https://github.com/cockroachdb/pebble/blob/f7316eb7e887460a67de9375cffd203390f7d18b/internal/rangekey/testdata/interleaving_iter#L146)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: So this truncation is due to `SeekGE`, which I follow. However, seeing the `yyy` result in this test case felt a little jarring, as the `seek-ge a`, `seek-ge p` and `seek-ge z` that precede it are simpler in how they "round up" to the closest point or range key.

Can we make this test case more explicit by either adding some more "obviously truncating" operations (i.e. seek-ge in a wide range), or remove the `seek-ge a, p, z` ops, or, drop it entirely, as you also added a test case below (in these latest revs, i.e. `seek-ge b`).

Alternatively - but I think may require a change to the data-driven tests, and might be hard as there's already a `#` for the seqnum - would be to slap a comment at the end of this line explicitly calling out what's happening.
</blockquote></details>

Added a comment up above the command.
___
*[internal/rangekey/testdata/interleaving_iter, line 655 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqbBG87-0VrhzbOsRAj:-Mqobhv9ENQXJphY3bWh:b-pqa4ti) ([raw file](https://github.com/cockroachdb/pebble/blob/f7316eb7e887460a67de9375cffd203390f7d18b/internal/rangekey/testdata/interleaving_iter#L655)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Meta question: I wonder if it may be surprising to future users of the API that we effectively return two synthetic keys during a forward-then-reverse sequence like this where the first op involves truncation on the `seek-ge`. It gives the impression that there are two ranges in play (one with a start key at `c`, and another before it with start key `a`).

Maybe that's totally what the caller already expects. Though I do wonder if the operations that truncate range keys deserve some more explicit commentary around this quirk. We have a comment on the struct about `SeekGE`, but we don't mention in the exported docs what happens when switching directions.

edit: I noticed in the PR comment that it seems like we now have `RangeKeyBounds()` and `RangeKeys()` for this case. Perhaps incorporate this feedback into docs for those functions too?
</blockquote></details>

Made a few documentation updates, including expanding comments on `RangeKeyBounds` and `SeekPrefixGE`/`SeekGE`.


<!-- Sent from Reviewable.io -->

2021-12-13 16:48 UTC, nicktrav reviewed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399)* status: all files reviewed, 9 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/interleaving_iter.go, line 513 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1399#-Mqog-BcAbNlTHLtWOzf:-Mqog-BcAbNlTHLtWOzg:b-gy4oqa) ([raw file](https://github.com/cockroachdb/pebble/blob/9e77a835bca1a421b6f3316220e920c22b659722/internal/rangekey/interleaving_iter.go#L513)):*
> ```Go
> 	// TODO(jackson): The key comparisons below truncate bounds whenever the
> 	// range key iterator is repositioned. We could perform this lazily, and
> 	// only do it first the time the user actually asks for this range key's
> ```

nit: "do it the first time"


<!-- Sent from Reviewable.io -->

2021-12-13 20:25 UTC, sumeerbhola requested changes
> Reviewed 1 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399)* status: all files reviewed (commit messages unreviewed), 22 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/interleaving_iter.go, line 111 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSUVAfEFe6NS5x1I0l:-MqpGuyeE3JZ2HIl_1aP:bj4as4b) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L111)):*
> Separate levelIters also sidesteps the RANGEDEL SeekGE optimization problem that we talked about at the team meeting

Yep, that is what I was hoping to get rid of :thumbsup: 
___
*[internal/rangekey/interleaving_iter.go, line 298 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqSB5pg3LbfpIm0YBh1:-MqpN41zCB_mNN0Mor5E:bka2viu) ([raw file](https://github.com/cockroachdb/pebble/blob/7804030783fe8a3c81cff7cf289e2e3e461466f3/internal/rangekey/interleaving_iter.go#L298)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

We're relying on `Next` to have already advanced past the range key `[a, b)` because it's already interleaved. 

I refactored these conditionals to make it a little clearer, expanded the commentary and documented the invariant we're relying on here.
</blockquote></details>

Ah yes, this makes sense.
___
*[internal/rangekey/interleaving_iter.go, line 40 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpEkUP2qAzVjPj3svO:-MqpEkUP2qAzVjPj3svP:b-99fuc1) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L40)):*
> ```Go
> // at the start key, even if the point key at the same user key is deleted.
> //
> // InterleavingIter may truncate a range key's start bound to a SeekGE or
> ```

may truncate, but not required to truncate?
___
*[internal/rangekey/interleaving_iter.go, line 46 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpEymq2Kv7s4Gb_KNK:-MqpEymq2Kv7s4Gb_KNL:beh3xo8) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L46)):*
> ```Go
> // If bounds have been applied to the iterator through SetBounds,
> // InterleavingIter will truncate the bounds returned through RangeKeyBounds to
> // the set bounds. The bounds returned through RangeKeyBounds are not however
> ```

doesn't this "not however truncated by a SeekGE" contradict the "may truncate a range key's start bound to a SeekGE" mentioned earlier?
Oh, I think the previous comment was meant to refer to the the synthetic start key?
___
*[internal/rangekey/interleaving_iter.go, line 124 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpFl-Q0_DLhv9OiiVG:-MqpFl-Q0_DLhv9OiiVH:b-4l05ac) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L124)):*
> ```Go
> //
> // If there exists a range key with a start key ≤ the first matching point key,
> // SeekPrefixGE will return a synthetic range key marker for the range key. If
> ```

s/SeekPrefixGE/SeekGE
___
*[internal/rangekey/interleaving_iter.go, line 248 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpRHkHBm6k6KDcghTH:-MqpRHkHBm6k6KDcghTI:bkwrvck) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L248)):*
> ```Go
> 			// be less than or equal to the current iterator position. If it's
> 			// less, the current range key is still relevant and we should not
> 			// move the range key iterator.
> ```

"start key must be less than or equal ... It it's less ... If it's equal ..."
is a bit confusing because it suggests a user key comparison. Which I don't think is what the code implies. Since the userkey could be the same as the point key and if pointKeyInterleaved is true, we will emit this range key again (as we should).
Maybe the comment could be rephrased somehow.
___
*[internal/rangekey/interleaving_iter.go, line 261 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpRyWW1F1unZN2eYBb:-MqpRyWW1F1unZN2eYBc:bgu7irp) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L261)):*
> ```Go
> 			// SeekGE or SeekPrefixGE call, then it's still relevant in the
> 			// reverse direction with an untruncated start key.
> 			if i.pointKeyInterleaved || i.rangeKeySeekTruncated {
> ```

We are relying on a property here that `pointKeyInterleaved => the point key was last returned key`. This is because whenever `pointKeyInterleaved` becomes true, a step using next/prev will immediately step the point iter and turn it back to false.
Worth a comment I think.
___
*[internal/rangekey/interleaving_iter.go, line 312 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpM1-u8lUVzc-amAfW:-MqpM1-v-j_3ePxkinbv:bn3npjf) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L312)):*
> ```Go
> 		panic("pebble: invariant violation: range-key span without visible Sets")
> 	}
> 	// INVARIANT: !rangeKeyInterleaved || pointKey < rangeKey.End
> ```

This invariant is only for the case where pointKey is not nil, yes? I have a few more prospective invariants in a comment below.
It may be worth organizing these in one place, and categorizing them based on (a) rangeKey==nil, (b) pointKey==nil, (b) both non-nil, so that it corresponds naturally to the switch statement below.
___
*[internal/rangekey/interleaving_iter.go, line 314 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpJUr5-oSMFWsraVuI:-MqpJUr5-oSMFWsraVuJ:b-rccijc) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L314)):*
> ```
> and the point key ends before it
> ```

and the range key ends before the point key?
___
*[internal/rangekey/interleaving_iter.go, line 319 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpJgFS-20SdGOtLCzY:-MqpJgFS-20SdGOtLCzZ:b32vlw) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L319)):*
>=
___
*[internal/rangekey/interleaving_iter.go, line 320 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpJp9KA6Sit-QD9wSv:-MqpJp9KA6Sit-QD9wSw:b-rvpe9p) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L320)):*
> ```Go
> 		i.cmp(i.pointKey.UserKey, i.rangeKey.End) >= 0 {
> 		panic("pebble: invariant violation: range key interleaved, but point key > range key end")
> 	}
> ```

Are the following invariants too:
- `!rangeKeyInterleaved || !pointKeyIntervleaved`
- `i.pointKey != nil => !i.pointKeyIntervleaved`
___
*[internal/rangekey/interleaving_iter.go, line 325 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpKPlWCNRCth0sxEU0:-MqpKPlWCNRCth0sxEU1:b-fijn2h) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L325)):*
> ```Go
> 	case i.rangeKey == nil:
> 		// If we're out of range keys, just return the point key.
> 		return i.yieldPointKey(false /* covered */)
> ```

This assumes that if we have a point key, we have `!pointKeyInterleaved`, yes?
___
*[internal/rangekey/interleaving_iter.go, line 374 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpNvuT6FovsTsupwto:-MqpNvuUECKK8tLgTLeW:bqqt5jz) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L374)):*
> ```Go
> 		panic("pebble: invariant violation: range-k [...]

2021-12-13 20:26 UTC, sumeerbhola reviewed
looks good. all my comments are about code comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399#-:-MqpTCDP-i8C-JvWajsA:b52jvjx)* status: all files reviewed (commit messages unreviewed), 22 unresolved discussions (waiting on @jbowens and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-12-15 21:48 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399)* status: 5 of 6 files reviewed, 21 unresolved discussions (waiting on @sumeerbhola)

___
*[internal/rangekey/interleaving_iter.go, line 40 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpEkUP2qAzVjPj3svO:-MqrOElK5z9HmLBBjzlW:bfh4dju) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L40)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

may truncate, but not required to truncate?
</blockquote></details>

s/may/will/

Done.
___
*[internal/rangekey/interleaving_iter.go, line 46 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpEymq2Kv7s4Gb_KNK:-MqrPHQs0kFpSYh595dd:b-j1orwb) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L46)):*
> Oh, I think the previous comment was meant to refer to the the synthetic start key?

yeah, fixed this up.
___
*[internal/rangekey/interleaving_iter.go, line 124 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpFl-Q0_DLhv9OiiVG:-MqrQ9Zl-EmVoCBdlsLm:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L124)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/SeekPrefixGE/SeekGE
</blockquote></details>

Done.
___
*[internal/rangekey/interleaving_iter.go, line 248 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpRHkHBm6k6KDcghTH:-MqzvCHj-7rTUGQ6zdWS:b-tvcak) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L248)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

"start key must be less than or equal ... It it's less ... If it's equal ..."
is a bit confusing because it suggests a user key comparison. Which I don't think is what the code implies. Since the userkey could be the same as the point key and if pointKeyInterleaved is true, we will emit this range key again (as we should).
Maybe the comment could be rephrased somehow.
</blockquote></details>

Tried rewording this; how's this?
___
*[internal/rangekey/interleaving_iter.go, line 261 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpRyWW1F1unZN2eYBb:-MqzvxZTCAJPJsu-Okdn:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L261)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We are relying on a property here that `pointKeyInterleaved => the point key was last returned key`. This is because whenever `pointKeyInterleaved` becomes true, a step using next/prev will immediately step the point iter and turn it back to false.
Worth a comment I think.
</blockquote></details>

Done.
___
*[internal/rangekey/interleaving_iter.go, line 312 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpM1-u8lUVzc-amAfW:-Mqzn2Sk63z3s9tPkBNg:bmky5wa) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L312)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This invariant is only for the case where pointKey is not nil, yes? I have a few more prospective invariants in a comment below.
It may be worth organizing these in one place, and categorizing them based on (a) rangeKey==nil, (b) pointKey==nil, (b) both non-nil, so that it corresponds naturally to the switch statement below.
</blockquote></details>

Reworked into a switch mirroring the below switch.
___
*[internal/rangekey/interleaving_iter.go, line 314 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpJUr5-oSMFWsraVuI:-Mqzo2gm00uAswrngKBC:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L314)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> ```
> and the point key ends before it
> ```

and the range key ends before the point key?
</blockquote></details>

Done.
___
*[internal/rangekey/interleaving_iter.go, line 319 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpJgFS-20SdGOtLCzY:-MqrRBbd5fn1kYuA44vF:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L319)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

>=
</blockquote></details>

Done.
___
*[internal/rangekey/interleaving_iter.go, line 320 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpJp9KA6Sit-QD9wSv:-Mqzp6DM9rtiriT_AIzb:blrtdc7) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L320)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are the following invariants too:
- `!rangeKeyInterleaved || !pointKeyIntervleaved`
- `i.pointKey != nil => !i.pointKeyIntervleaved`
</blockquote></details>

I think these can be collapsed into a single `!i.pointKeyIntervleaved` invariant: Either there's a point and it hasn't been interleaved, or there's not a point key and the `nil` hasn't be interleaved yet. (This makes it an invariant violation to `Next` again on an exhausted forward iterator, which seems fine.)
___
*[internal/rangekey/interleaving_iter.go, line 325 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpKPlWCNRCth0sxEU0:-MqzsxNNBVsrApr-UuUq:bs00axz) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L325)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This assumes that if we have a point key, we have `!pointKeyInterleaved`, yes?
</blockquote></details>

Yeah (see the above comment about the `!i.pointKeyIntervleaved` invariant).
___
*[internal/rangekey/interleaving_iter.go, line 388 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpORSoCDEPgf1li2xa:-Mqzt_ly6IT7f4kI3BvQ:b-3y58uy) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L388)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

"after" in the reverse direction, yes?
</blockquote></details>

yeah, reworded.
___
*[internal/rangekey/interleaving_iter.go, line 518 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpI6s00lJsJis7BlI6:-Mqztwex1SeYyHdD-MFh:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L518)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should that be renamed rangeKeyMarkerTruncated?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-16 17:02 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399#-:-Mr3BTRXE8j45IoQsHuE:bg7igkv)* status: all files reviewed, 22 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/interleaving_iter.go, line 248 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1399#-MqpRHkHBm6k6KDcghTH:-Mr39YGJ00UGGTfaTi5B:b-47fafm) ([raw file](https://github.com/cockroachdb/pebble/blob/f7886f7a33ffdfd4089ddce1c7f9ce328ee3377e/internal/rangekey/interleaving_iter.go#L248)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Tried rewording this; how's this?
</blockquote></details>

looks good
___
*[internal/rangekey/interleaving_iter.go, line 345 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1399#-Mr3A_qE9Qa2tP4wYle0:-Mr3A_qE9Qa2tP4wYle1:bg571xy) ([raw file](https://github.com/cockroachdb/pebble/blob/1e5db70dfca3e64569e42c34cb842f9388514f7d/internal/rangekey/interleaving_iter.go#L345)):*
> ```Go
> 	}
> 
> 	// Merge.
> ```

nit: should this say "Interleave" and the method be named "interleaveForward".
We already use merge in a different sense in the Pebble iteration code, so if there is an easy alternative name, it may be worth considering.  


<!-- Sent from Reviewable.io -->

2021-12-16 17:23 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1399#-:-Mr3GF-i5aGAq8BUVx4r:bz5mair)* status: 5 of 6 files reviewed, 22 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/interleaving_iter.go, line 345 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1399#-Mr3A_qE9Qa2tP4wYle0:-Mr3FUfP2mODbqaIpa1P:b-ulcfqc) ([raw file](https://github.com/cockroachdb/pebble/blob/1e5db70dfca3e64569e42c34cb842f9388514f7d/internal/rangekey/interleaving_iter.go#L345)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: should this say "Interleave" and the method be named "interleaveForward".
We already use merge in a different sense in the Pebble iteration code, so if there is an easy alternative name, it may be worth considering.  
</blockquote></details>

Good call


<!-- Sent from Reviewable.io -->

2021-12-16 17:39 UTC, merged