*: Add trySeekUsingNext optimization to SeekGE
cockroachdb/pebble pull request #1412
Opened 2021-12-15 19:28 UTC by itsbilal

This change takes the trySeekUsingNext optimization that
exists in SeekPrefixGE and applies that to SeekGE as well. It
is expected to help out a lot in cockroachdb/cockroach#66410
as the CheckSSTCollisions call in Cockroach repeatedly
calls SeekGE on the engine iterator in bad cases of
ingested sst <> engine overlap.

2021-12-15 19:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1412)
<!-- Reviewable:end -->

2021-12-15 19:47 UTC, itsbilal commented
Running CheckSSTConflicts with and without this optimization against a pre-https://github.com/cockroachdb/cockroach/pull/73514 version of Cockroach gets me:

```
name                                                                      old time/op  new time/op  delta
CheckSSTConflicts/keys=1000/versions=8/sstKeys=1000/overlap=false-24      72.6µs ±11%  69.2µs ± 1%     ~     (p=0.690 n=5+5)
CheckSSTConflicts/keys=1000/versions=8/sstKeys=1000/overlap=true-24       12.2ms ± 1%   1.7ms ± 0%  -86.07%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/versions=8/sstKeys=10000/overlap=false-24     69.8µs ± 2%  70.3µs ± 0%     ~     (p=0.151 n=5+5)
CheckSSTConflicts/keys=1000/versions=8/sstKeys=10000/overlap=true-24      13.3ms ± 3%   2.9ms ± 1%  -78.51%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/versions=64/sstKeys=1000/overlap=false-24     75.8µs ± 3%  67.1µs ± 1%  -11.50%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/versions=64/sstKeys=1000/overlap=true-24      13.0ms ± 1%   2.0ms ± 3%  -84.30%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/versions=64/sstKeys=10000/overlap=false-24    69.8µs ±11%  67.2µs ± 1%     ~     (p=0.690 n=5+5)
CheckSSTConflicts/keys=1000/versions=64/sstKeys=10000/overlap=true-24     14.8ms ± 9%   3.8ms ± 8%  -74.21%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=10000/versions=8/sstKeys=1000/overlap=false-24     66.1µs ± 2%  66.0µs ± 1%     ~     (p=0.841 n=5+5)
CheckSSTConflicts/keys=10000/versions=8/sstKeys=1000/overlap=true-24      14.2ms ± 9%   2.1ms ± 1%  -85.51%  (p=0.016 n=5+4)
CheckSSTConflicts/keys=10000/versions=8/sstKeys=10000/overlap=false-24    72.3µs ±10%  66.6µs ± 1%     ~     (p=0.690 n=5+5)
CheckSSTConflicts/keys=10000/versions=8/sstKeys=10000/overlap=true-24      122ms ± 2%    19ms ± 1%  -84.39%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=10000/versions=64/sstKeys=1000/overlap=false-24    69.0µs ± 9%  64.4µs ± 1%     ~     (p=0.690 n=5+5)
CheckSSTConflicts/keys=10000/versions=64/sstKeys=1000/overlap=true-24     14.0ms ± 1%   3.0ms ±11%  -78.55%  (p=0.016 n=4+5)
CheckSSTConflicts/keys=10000/versions=64/sstKeys=10000/overlap=false-24   69.4µs ± 9%  65.1µs ± 1%     ~     (p=0.690 n=5+5)
CheckSSTConflicts/keys=10000/versions=64/sstKeys=10000/overlap=true-24     140ms ± 5%    33ms ± 3%  -76.56%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=100000/versions=8/sstKeys=1000/overlap=false-24    69.2µs ±10%  64.5µs ± 2%     ~     (p=0.310 n=5+5)
CheckSSTConflicts/keys=100000/versions=8/sstKeys=1000/overlap=true-24     15.3ms ±11%   2.7ms ±12%  -82.09%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=100000/versions=8/sstKeys=10000/overlap=false-24   69.7µs ±12%  64.8µs ± 1%     ~     (p=0.548 n=5+5)
CheckSSTConflicts/keys=100000/versions=8/sstKeys=10000/overlap=true-24     148ms ± 6%    36ms ± 2%  -75.34%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=100000/versions=64/sstKeys=1000/overlap=false-24   67.1µs ±10%  64.5µs ± 5%     ~     (p=1.000 n=5+5)
CheckSSTConflicts/keys=100000/versions=64/sstKeys=1000/overlap=true-24    14.4ms ± 2%   4.9ms ± 8%  -66.26%  (p=0.016 n=4+5)
CheckSSTConflicts/keys=100000/versions=64/sstKeys=10000/overlap=false-24  68.9µs ±21%  64.5µs ± 3%     ~     (p=1.000 n=5+5)
CheckSSTConflicts/keys=100000/versions=64/sstKeys=10000/overlap=true-24    204ms ±14%    61ms ±12%  -70.12%  (p=0.008 n=5+5)
```

2021-12-16 21:24 UTC, sumeerbhola requested changes
I've only partially swapped back in the state for these subtle optimizations. I'll do some more reading to swap in the rest. Sending some comments meanwhile.

> Reviewed 2 of 33 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1412#-:-Mr473DF8U4CDEueqLvG:bmanx5h)* status: 2 of 33 files reviewed, 3 unresolved discussions (waiting on @itsbilal)

___
*[iterator.go, line 674 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mr3yPfg6y20vQ1Skz7r:-Mr3yPfhAZwjNkPJmyVP:b-vt97c6) ([raw file](https://github.com/cockroachdb/pebble/blob/af213b816214bb7cca8c38c6623b66b09b2a10d5/iterator.go#L674)):*
> ```Go
> 					return i.iterValidityState
> 				}
> 			}
> ```

So the invariant (negating the if condition)
i.iterValidityState != IterExhausted &&
i.iterValidityState != IterValid || i.cmp(key, i.key) > 0 || (limit != nil && i.cmp(i.key, limit) >= 0)

which could be simplified to
i.iterValidityState != IterExhausted &&
i.iterValidityState == IterAtLimit || i.cmp(key, i.key) > 0 || (limit != nil && i.cmp(i.key, limit) >= 0)

We may need to be careful with the limit and IterAtLimit cases here. SeekPrefixGE does not have limit support.
If we are at IterAtLimit, we should be at iterPosCurForwardPaused or iterPosCurReversePaused. Does that cause a problem -- if not, could you add a comment with a justification.
We don't know how this limit compares to the previous limit.
And if  (limit != nil && i.cmp(i.key, limit) >= 0) should we be doing anything?

I would be fine if we scope it to exclude all cases where the previous or this seek was using a limit.
___
*[sstable/reader.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mr4539D5TvInbWPnYj8:-Mr4539D5TvInbWPnYj9:b-5d5o7g) ([raw file](https://github.com/cockroachdb/pebble/blob/af213b816214bb7cca8c38c6623b66b09b2a10d5/sstable/reader.go#L346)):*
> ```Go
> 	if i.dataBH == bhp.BlockHandle && i.data.Valid() {
> 		// No-op; we're already at the data block we want to load.
> 		i.initBounds()
> ```

what about the position of the blockIter corresponding to i.data. It is being left at the old position?
___
*[sstable/reader.go, line 1219 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mr46uwfEOZe4SE1JrVf:-Mr46uwfEOZe4SE1JrVg:bvad3d1) ([raw file](https://github.com/cockroachdb/pebble/blob/af213b816214bb7cca8c38c6623b66b09b2a10d5/sstable/reader.go#L1219)):*
> ```Go
> 	if i.topLevelIndex.isDataInvalidated() || !i.topLevelIndex.Valid() || i.boundsCmp <= 0 ||
> 		i.cmp(key, i.topLevelIndex.Key().UserKey) > 0 {
> 		trySeekUsingNext = false
> ```

this will typically not be useful, yes? for the same reason as the comment in twoLevelIterator.SeekPrefixGE.


<!-- Sent from Reviewable.io -->

2021-12-17 16:49 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1412)* status: 1 of 33 files reviewed, 3 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[iterator.go, line 674 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mr3yPfg6y20vQ1Skz7r:-Mr8CvG33cCXllYk9Mu3:b-1s825i) ([raw file](https://github.com/cockroachdb/pebble/blob/af213b816214bb7cca8c38c6623b66b09b2a10d5/iterator.go#L674)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So the invariant (negating the if condition)
i.iterValidityState != IterExhausted &&
i.iterValidityState != IterValid || i.cmp(key, i.key) > 0 || (limit != nil && i.cmp(i.key, limit) >= 0)

which could be simplified to
i.iterValidityState != IterExhausted &&
i.iterValidityState == IterAtLimit || i.cmp(key, i.key) > 0 || (limit != nil && i.cmp(i.key, limit) >= 0)

We may need to be careful with the limit and IterAtLimit cases here. SeekPrefixGE does not have limit support.
If we are at IterAtLimit, we should be at iterPosCurForwardPaused or iterPosCurReversePaused. Does that cause a problem -- if not, could you add a comment with a justification.
We don't know how this limit compares to the previous limit.
And if  (limit != nil && i.cmp(i.key, limit) >= 0) should we be doing anything?

I would be fine if we scope it to exclude all cases where the previous or this seek was using a limit.
</blockquote></details>

I excluded cases where we set a limit, just to keep it safe. Added a comment about it too. Thanks for catching this!
___
*[sstable/reader.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mr4539D5TvInbWPnYj8:-Mr4WEfDBIh7IDqU8CU4:b-m9koh0) ([raw file](https://github.com/cockroachdb/pebble/blob/af213b816214bb7cca8c38c6623b66b09b2a10d5/sstable/reader.go#L346)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what about the position of the blockIter corresponding to i.data. It is being left at the old position?
</blockquote></details>

It's safe to just leave blockIter as-is, because in all cases where we call `loadBlock` and get a `loadBlockOK` in response, the very next thing we do is an absolute positioning call (i.e. seek or first/last) on `i.data`. I should leave a comment about this.
___
*[sstable/reader.go, line 1219 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mr46uwfEOZe4SE1JrVf:-Mr8DhvT2llJcwIJGjsZ:b-g38gql) ([raw file](https://github.com/cockroachdb/pebble/blob/af213b816214bb7cca8c38c6623b66b09b2a10d5/sstable/reader.go#L1219)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this will typically not be useful, yes? for the same reason as the comment in twoLevelIterator.SeekPrefixGE.
</blockquote></details>

Yep, can't rely on bound monotonicity. Copied the comment from there.


<!-- Sent from Reviewable.io -->

2021-12-18 01:25 UTC, sumeerbhola requested changes
> Reviewed 29 of 33 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1412)* status: 31 of 33 files reviewed, 8 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[internal/arenaskl/skl_test.go, line 584 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1412#-MrA1UUt9_nMyWzASuho:-MrA1UUt9_nMyWzASuhp:b8zfbsk) ([raw file](https://github.com/cockroachdb/pebble/blob/1d01451ab268fb0cdc452ef8c2c71fd74657fafe/internal/arenaskl/skl_test.go#L584)):*
> ```Go
> 
> 		// Seeking to a nearby key that can be reached using Next.
> 		require.True(t, it.SeekPrefixGE(makeKey("01020"), makeKey("01020"), true))
> ```

we need some similar cases using SeekGE(... true)
___
*[sstable/reader.go, line 1219 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mr46uwfEOZe4SE1JrVf:-MrA3MieBYdy7cKaKKlh:bgk5kfg) ([raw file](https://github.com/cockroachdb/pebble/blob/af213b816214bb7cca8c38c6623b66b09b2a10d5/sstable/reader.go#L1219)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yep, can't rely on bound monotonicity. Copied the comment from there.
</blockquote></details>

I should have clarified my comment -- it was misleading.
- the fast-path does apply to CockroachDB use cases that use monotonic bounds.
- it's the case where `!i.topLevelIndex.isDataInvalidated() && i.topLevelIndex.Valid() && i.cmp(key, i.topLevelIndex.Key().UserKey) <= 0` is what we would like to optimize when `trySeekUsingNext=true`. We are on the the same lower-level index in that case.
___
*[sstable/reader.go, line 1270 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1412#-MrA6CwXDZYyJEjNdRqv:-MrA6CwY4oJR4bqEIudO:bwtx4av) ([raw file](https://github.com/cockroachdb/pebble/blob/1d01451ab268fb0cdc452ef8c2c71fd74657fafe/sstable/reader.go#L1270)):*
> ```Go
> 
> 	if !dontSeekWithinSingleLevelIter {
> 		if ikey, val := i.singleLevelIterator.SeekGE(key, trySeekUsingNext); ikey != nil {
> ```

This is going to get confusing for a code reader, since trySeekUsingNext can be false here, but the callee can be doing the boundsCmp based fast-path.

I wonder whether it is time to lift the boundsCmp up like the comment in `InternalIterator.SetPrefixGE` suggests, and use the same `trySeekUsingNext` to represent both cases where these sstable iters can optimize.
___
*[sstable/reader.go, line 1329 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1412#-MrA42gRAsGwrvMhqh-Y:-MrA42gRAsGwrvMhqh-Z:b-6xm161) ([raw file](https://github.com/cockroachdb/pebble/blob/1d01451ab268fb0cdc452ef8c2c71fd74657fafe/sstable/reader.go#L1329)):*
> ```Go
> 		trySeekUsingNext = false
> 		var ikey *InternalKey
> 		if ikey, _ = i.topLevelIndex.SeekGE(key, trySeekUsingNext); ikey == nil {
> ```

shouldn't this be false? We are seeking the top level index that may be invalid. For instance, the bloom filter may not have matched in the previous call to SeekPrefixGE.
If this is a bug, it would be good to add a test case that fails.
___
*[testdata/event_listener, line 185 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mr9nZMx3dC-Gq3_5gBv:-Mr9nZMy7Atk7U8dJ4fa:bb601zj) ([raw file](https://github.com/cockroachdb/pebble/blob/1d01451ab268fb0cdc452ef8c2c71fd74657fafe/testdata/event_listener#L185)):*
> ```
> zmemtbl         0     0 B
>    ztbl         0     0 B
>  bcache         8   1.4 K    0.0%  (score == hit-rate)
> ```

is this due to the change to not reload the same block?
___
*[testdata/iterator, line 209 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mr9l1hx0ibor5ufSKFt:-Mr9l1hy5mhFCSdMb-oK:bdn4gun) ([raw file](https://github.com/cockroachdb/pebble/blob/1d01451ab268fb0cdc452ef8c2c71fd74657fafe/testdata/iterator#L209)):*
> ```
> b:c
> .
> stats: (interface (dir, seek, step): (fwd, 3, 0), (rev, 0, 0)), (internal (dir, seek, step): (fwd, 3, 0), (rev, 0, 0))
> ```

so there are 3 seeks in the InternalIterator because this test uses a `fakeIter` and not a real sst?

I think there is an oversight for the `Iterator.SeekPrefixGE` optimization too -- we lack a datadriven test that exercises the end-to-end path. We only test `levelIter` and the sstable code. We shouldn't have a bug because of the metamorphic test and `disableSeekOpt` but it is still worthwhile having a test for both Iterator.{SeekPrefixGE,SeekGE}.

I'd suggest taking a fresh look at the state of testing of the iterators for these next optimizations -- you may spot some additional gaps.


<!-- Sent from Reviewable.io -->

2022-01-06 18:41 UTC, itsbilal reviewed
Thanks for the review!

> Dismissed @sumeerbhola from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1412#-:-MskgZGbBtwPm6uCjtTp:b-9qdoz3)* status: 27 of 36 files reviewed, 7 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[sstable/reader.go, line 1219 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mr46uwfEOZe4SE1JrVf:-Msg7Kmu23TU8EMS9UhC:bcwqkqg) ([raw file](https://github.com/cockroachdb/pebble/blob/af213b816214bb7cca8c38c6623b66b09b2a10d5/sstable/reader.go#L1219)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I should have clarified my comment -- it was misleading.
- the fast-path does apply to CockroachDB use cases that use monotonic bounds.
- it's the case where `!i.topLevelIndex.isDataInvalidated() && i.topLevelIndex.Valid() && i.cmp(key, i.topLevelIndex.Key().UserKey) <= 0` is what we would like to optimize when `trySeekUsingNext=true`. We are on the the same lower-level index in that case.
</blockquote></details>

Done. I hope I was able to implement that fast path case correctly - PTAL!
___
*[sstable/reader.go, line 1270 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1412#-MrA6CwXDZYyJEjNdRqv:-Msg9yBu38CCy8Pa8GDq:b5y9rm7) ([raw file](https://github.com/cockroachdb/pebble/blob/1d01451ab268fb0cdc452ef8c2c71fd74657fafe/sstable/reader.go#L1270)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is going to get confusing for a code reader, since trySeekUsingNext can be false here, but the callee can be doing the boundsCmp based fast-path.

I wonder whether it is time to lift the boundsCmp up like the comment in `InternalIterator.SetPrefixGE` suggests, and use the same `trySeekUsingNext` to represent both cases where these sstable iters can optimize.
</blockquote></details>

That would feel a little odd, as `singleLevelIterator` is still an internal iterator and we'd be passing in `trySeekUsingNext == true` in cases other than the ones where k2 >= k1. I left a comment for now, but if you think it's good to lift up that case, I can do it too.
___
*[sstable/reader.go, line 1329 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1412#-MrA42gRAsGwrvMhqh-Y:-MsfwNar0OH_0XR9zkAj:b-xd7a48) ([raw file](https://github.com/cockroachdb/pebble/blob/1d01451ab268fb0cdc452ef8c2c71fd74657fafe/sstable/reader.go#L1329)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

shouldn't this be false? We are seeking the top level index that may be invalid. For instance, the bloom filter may not have matched in the previous call to SeekPrefixGE.
If this is a bug, it would be good to add a test case that fails.
</blockquote></details>

It is false - see the line that's two lines above where we set `trySeekUsingNext`. I'll make that more explicit by passing in `false` here.
___
*[testdata/event_listener, line 185 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mr9nZMx3dC-Gq3_5gBv:-Msfw_xh-cxBpZwK5gM7:bb77uci) ([raw file](https://github.com/cockroachdb/pebble/blob/1d01451ab268fb0cdc452ef8c2c71fd74657fafe/testdata/event_listener#L185)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this due to the change to not reload the same block?
</blockquote></details>

Yep!
___
*[testdata/iterator, line 209 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mr9l1hx0ibor5ufSKFt:-MsfwnaW7tea7DvNaKWv:brkm9lb) ([raw file](https://github.com/cockroachdb/pebble/blob/1d01451ab268fb0cdc452ef8c2c71fd74657fafe/testdata/iterator#L209)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

so there are 3 seeks in the InternalIterator because this test uses a `fakeIter` and not a real sst?

I think there is an oversight for the `Iterator.SeekPrefixGE` optimization too -- we lack a datadriven test that exercises the end-to-end path. We only test `levelIter` and the sstable code. We shouldn't have a bug because of the metamorphic test and `disableSeekOpt` but it is still worthwhile having a test for both Iterator.{SeekPrefixGE,SeekGE}.

I'd suggest taking a fresh look at the state of testing of the iterators for these next optimizations -- you may spot some additional gaps.
</blockquote></details>

Done. Wasn't able to easily add an end-to-end test that can also confirm what's happening down at the block iterator level, but there's a better test of this optimization than before. Thanks!
___
*[internal/arenaskl/skl_test.go, line 584 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1412#-MrA1UUt9_nMyWzASuho:-Msg-iIT4JkeidNOo277:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/1d01451ab268fb0cdc452ef8c2c71fd74657fafe/internal/arenaskl/skl_test.go#L584)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we need some similar cases using SeekGE(... true)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-11 19:32 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1412#-:-Mt9c42FBCFDBgGbhH2E:bg7igkv)* status: all files reviewed, 11 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[batch.go, line 1472 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mt9TfNN8Y33k6deqvBT:-Mt9TfNN8Y33k6deqvBU:bcp2die) ([raw file](https://github.com/cockroachdb/pebble/blob/b6701804f0e0f459fdae78223633e93fd1a8f791/batch.go#L1472)):*
> ```Go
> // SeekGE implements internalIterator.SeekGE, as documented in the pebble
> // package. Ignore trySeekUsingNext since flushable batches are not user-facing,
> // so optimizing prefix seeks is not important.
> ```

this comment seems stale, since this method is not limited to prefix seeks.

Also, I think the old "not user-facing" comment was not correct -- an `Iterator` where the DB has a `flushableBatch` in its queue of unflushed `flushables` will contain `flushableBatchIters`. How about saying "Ignore trySeekUsingNext since we don't expect this optimization will provide much benefit."
We can revisit this later.
___
*[testdata/iterator_seek_opt, line 2 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mt9ZUdaCn-fkAeisgi8:-Mt9ZUdaCn-fkAeisgi9:b-j6rd9r) ([raw file](https://github.com/cockroachdb/pebble/blob/b6701804f0e0f459fdae78223633e93fd1a8f791/testdata/iterator_seek_opt#L2)):*
> ```
> 
> define auto-compactions=off
> ```

nice test!
___
*[testdata/iterator_seek_opt, line 163 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mt9ZCfh0-ecV0Xy3jbv:-Mt9ZCfh0-ecV0Xy3jbw:b-rqppqn) ([raw file](https://github.com/cockroachdb/pebble/blob/b6701804f0e0f459fdae78223633e93fd1a8f791/testdata/iterator_seek_opt#L163)):*
> ```
> 
> iter
> set-bounds lower=a upper=d
> ```

can you add a couple of cases where the bounds are monotonic and non-overlapping (including seek-lt).
Something like

```
set-bounds lower=a upper=c
seek-ge b
-----

set-bounds lower=c upper=e
seek-ge c
----
```
___
*[iterator_test.go, line 965 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mt9X2e9BdVktLvGtUut:-Mt9X2e9BdVktLvGtUuu:b-kcd13i) ([raw file](https://github.com/cockroachdb/pebble/blob/b6701804f0e0f459fdae78223633e93fd1a8f791/iterator_test.go#L965)):*
> ```Go
> 			d.mu.Lock()
> 			// Disable the "dynamic base level" code for this test.
> 			// d.mu.versions.picker.forceBaseLevel1()
> ```

leftover code?


<!-- Sent from Reviewable.io -->

2022-01-11 19:56 UTC, itsbilal reviewed
TFTR!

> Dismissed @sumeerbhola from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1412#-:-Mt9ersY46BvCHVLa886:b-814g8k)* status: 21 of 36 files reviewed, 10 unresolved discussions (waiting on @sumeerbhola)

___
*[batch.go, line 1472 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mt9TfNN8Y33k6deqvBT:-Mt9fiMmDwG3GVAaPl5m:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b6701804f0e0f459fdae78223633e93fd1a8f791/batch.go#L1472)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this comment seems stale, since this method is not limited to prefix seeks.

Also, I think the old "not user-facing" comment was not correct -- an `Iterator` where the DB has a `flushableBatch` in its queue of unflushed `flushables` will contain `flushableBatchIters`. How about saying "Ignore trySeekUsingNext since we don't expect this optimization will provide much benefit."
We can revisit this later.
</blockquote></details>

Done.
___
*[testdata/iterator_seek_opt, line 163 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mt9ZCfh0-ecV0Xy3jbv:-Mt9gVUa2F7iE3Nm-ncU:b8v72ad) ([raw file](https://github.com/cockroachdb/pebble/blob/b6701804f0e0f459fdae78223633e93fd1a8f791/testdata/iterator_seek_opt#L163)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a couple of cases where the bounds are monotonic and non-overlapping (including seek-lt).
Something like

```
set-bounds lower=a upper=c
seek-ge b
-----

set-bounds lower=c upper=e
seek-ge c
----
```
</blockquote></details>

Added, thanks! Just to clarify, by `seek-lt` you meant `seek-prefix-ge` right? and we won't actually use `trySeekUsingNext = true` here because the `set-bounds` sets the last operation to unknownLastOp. We would still use the optimization down in singleLevelIterator, but we don't have visibility into that here.
___
*[iterator_test.go, line 965 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1412#-Mt9X2e9BdVktLvGtUut:-Mt9foIlCxng-7J47DfQ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b6701804f0e0f459fdae78223633e93fd1a8f791/iterator_test.go#L965)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

leftover code?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-12 16:45 UTC, merged