internal/keyspan: convert Iter to interface, add VisibleIter
cockroachdb/pebble pull request #1414
Opened 2021-12-16 02:01 UTC by jbowens

Convert the Iter type to an interface.

Add a VisibleIter iterator that implements the interface but filters fragments
by sequence number. A VisibleIter takes a sequence number, indicating the
sequence number at which the iterator reads. Any Spans with start keys that are
not visible at that sequence number (because they were committed at a ≥
sequence number) are skipped.

This will be used to filter out range-key fragments that should be ignored.

2021-12-16 02:01 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1414)
<!-- Reviewable:end -->

2021-12-16 21:02 UTC, nicktrav approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1414#-:-Mr4260kBHmbFFsqbfMq:bnfp4nl)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

___
*[internal/keyspan/testdata/visible_iter, line 1 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1414#-Mr41Bdk-XpNLXwgrONB:-Mr41Bdk-XpNLXwgrONC:bcdq9pr) ([raw file](https://github.com/cockroachdb/pebble/blob/97132dd160d3c69406b6ec2a7be336eb92958c7c/internal/keyspan/testdata/visible_iter#L1)):*
> ```
> define
> ```

I think I missed this notation, as it looks like it came over from range-dels, which predates me. We're just using `foo.SET.n:bar` as shorthand for the range `foo-bar` at sequence number `n`?

Not an issue, I was just a little confused at first glance when I saw SETs in here.


<!-- Sent from Reviewable.io -->

2021-12-17 22:49 UTC, sumeerbhola requested changes
> Reviewed 6 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1414)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/keyspan/visible.go, line 13 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1414#-Mr9YBeo12crtRuzkpWu:-Mr9YBepADbvfpZ8I4kf:bi9z6tq) ([raw file](https://github.com/cockroachdb/pebble/blob/97132dd160d3c69406b6ec2a7be336eb92958c7c/internal/keyspan/visible.go#L13)):*
> ```Go
> type VisibleIter struct {
> 	keyspanIter
> 	SeqNum uint64
> ```

Could you clarify why we need this very thin wrapper instead of including its functionality in `keyspanIter` itself?
We have a similar situation with `mergingIter` where when it is used in the compaction case we set the seqnum to `InternalKeySeqNumMax`.

(I am somewhat averse to thin wrappers, since it involves jumping around in the code to reconstruct what is happening. Almost all our InternalIterator implementations are substantial.) 


<!-- Sent from Reviewable.io -->

2021-12-20 16:36 UTC, jbowens commented
Superseded by #1420.

2021-12-20 16:36 UTC, closed without merging