db: add experimental, in-memory range keys implementation
cockroachdb/pebble pull request #1415
Opened 2021-12-16 19:28 UTC by jbowens

This change adds experimental, in-memory support for range keys. If a database
is configured with the `Experimental.RangeKeys` field set, batches containing
range keys may be committed. The range keys are applied to a fixed-size
in-memory arena. The `pebble.Iterator` type is extended to surface these range
keys when an iterator's `IterOptions.KeyTypes` option is set to
`IterKeyTypeRangesOnly` or `IterKeyTypePointsAndRanges`.

With this change, range keys are non-durable. When a database is closed, all
committed range keys are lost.

----

This change is rebased over #1414.

2021-12-16 19:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1415)
<!-- Reviewable:end -->

2021-12-17 02:31 UTC, nicktrav reviewed
Nice! I focused on the test cases first, and all lines up with my understanding there. Left a few minor comments. Will continue the review on the implementation next.

> Reviewed 5 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415#-:-Mr5CSj2Acq6YWiqPxsN:b-3n7u4)* status: 5 of 19 files reviewed, 6 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)

___
*[data_test.go, line 748 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr595Zc12jx7rORYw1b:-Mr595Zc12jx7rORYw1c:b-bl3jl4) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/data_test.go#L748)):*
> ```Go
> 		for _, ts := range timestamps {
> 			n := testkeys.WriteKeyAt(buf, ks, i, ts)
> 			require.NoError(t, b.Set(buf[:n], []byte("v"), nil))
> ```

Is it possible to make this `v` value a little more explicit and / or configurable in the test cases? It wasn't immediately clear where `v` was coming from.
___
*[testdata/rangekeys, line 5 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr4pU-rCsPY3MY4oVQD:-Mr4pU-rCsPY3MY4oVQE:bba1sdw) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/testdata/rangekeys#L5)):*
> ```
> 
> batch
> set a a
> ```

I got confused a little with the examples, as the point keys and values are the same (i.e. `set a a`). Any chance we can make the values fruits or something to help disambiguate? No issue with the beeps and boops :)
___
*[testdata/rangekeys, line 64 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr4uq6YD4F6De7o7Qoi:-Mr4uq6YD4F6De7o7Qoj:b-orc7gt) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/testdata/rangekeys#L64)):*
> ```
> cat: (., [cat-dog) @3=beep)
> d: (d, [cat-dog) @3=beep)
> day: (., [cat-dog) @3=beep)
> ```

Just confirming my understanding. This `day` is due to truncation on the range key "side" of the iterator, right?
___
*[testdata/rangekeys, line 134 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr52bHC2o_9WHmbJf19:-Mr52bHC2o_9WHmbJf1A:bckuupu) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/testdata/rangekeys#L134)):*
> ```
> b [b-c) @5=boop
> 
> # Delete the beginning of the cat-dog range key, truncating it to now begin at
> ```

nit: "Delete up to the beginning of ...". We're dropping the `b-c` range too, yeah? Or perhaps just mention explicitly that `b-c` gets dropped.
___
*[testdata/rangekeys, line 200 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr567bzCquI6bct4Vw5:-Mr567bzCquI6bct4Vw6:b-6zyblv) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/testdata/rangekeys#L200)):*
> ```
> ----
> 
> populate keylen=2 timestamps=(1, 10, 100)
> ```

Perhaps some commentary on this? i.e. create point keys `a-zz` each with timestamps 1, 10 and 100 (i.e. (26 ** 2 + 26) * 3 = 2106), etc.
___
*[testdata/rangekeys, line 211 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr59qSw1NAuF5QbquvH:-Mr59qSw1NAuF5QbquvI:b141wp7) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/testdata/rangekeys#L211)):*
> ```
> wrote 3 keys
> 
> combined-iter
> ```

This test case is nice. Would it be worth adding another case that has the same point keys, but has some overlapping range key set, unsets, and dels? The "gaps" in the range keyspace would give us some good coverage over the fragmentation and coalescing.


<!-- Sent from Reviewable.io -->

2021-12-17 17:35 UTC, nicktrav reviewed
The rest looked good. I will do another full pass once #1414 lands, and any changes get reflected here.

> Reviewed 8 of 8 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415#-:-Mr8RvGL84v7s2H4Q7o9:b-1cutpe)* status: all files reviewed, 10 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)

___
*[iterator.go, line 333 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr8LLTqBIGDLvNcWA1Y:-Mr8LLTqBIGDLvNcWA1Z:bqmzrxy) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/iterator.go#L333)):*
> ```Go
> 	}
> 
> 	for {
> ```

All of the arms in the `switch` have `returns`. Are we actually looping?
___
*[iterator.go, line 1207 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr8Mfz95TKEah9rUS8E:-Mr8Mfz95TKEah9rUS8F:b-7e0u9) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/iterator.go#L1207)):*
> ```Go
> }
> 
> // setRangeKey to sets the current range key to the underlying iterator's
> ```

nit: `s/setRangeKey to/setRangeKey/`
___
*[range_keys.go, line 22 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr8PwWeAnqcmUlo8V0_:-Mr8PwWeAnqcmUlo8V0a:b-i2srl5) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/range_keys.go#L22)):*
> ```Go
> //
> // This is a temporary type that will eventually be removed.
> type RangeKeysArena struct {
> ```

Is this exported in anticipation of the metamorphic tests? Can we get away with not exporting?
___
*[range_keys.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr8R7z9996GAcS_HV3Y:-Mr8R7z9996GAcS_HV3Z:b-iw03tu) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/range_keys.go#L45)):*
> ```Go
> 			break
> 		}
> 		switch kind {
> ```

nit: can this have a `default` arm with a basic comment saying something like "we're only applying range keys, so ignore all other other keys". Just so it's explicit we're handing all cases.


<!-- Sent from Reviewable.io -->

2021-12-17 18:09 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415)* status: 16 of 19 files reviewed, 7 unresolved discussions (waiting on @erikgrinaker, @jbowens, @nicktrav, and @sumeerbhola)

___
*[iterator.go, line 333 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr8LLTqBIGDLvNcWA1Y:-Mr8XA_B8yxc8yHyiuse:b9wdcp2) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/iterator.go#L333)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

All of the arms in the `switch` have `returns`. Are we actually looping?
</blockquote></details>

Good call, I thought we needed to loop for `MERGE` keys, but `mergeNext` takes care of that. Done.
___
*[range_keys.go, line 22 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr8PwWeAnqcmUlo8V0_:-Mr8XWyT17_sz0XO_yLJ:b932rp2) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/range_keys.go#L22)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Is this exported in anticipation of the metamorphic tests? Can we get away with not exporting?
</blockquote></details>

Yeah. Also, it's currently serving as a way to require explicitly enabling range-keys functionality. If `Options.Experimental.RangeKeys` is nil, applying batches containing range keys will error.
___
*[range_keys.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr8R7z9996GAcS_HV3Y:-Mr8Xyb25Opdw6CdXF72:b-szhbky) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/range_keys.go#L45)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: can this have a `default` arm with a basic comment saying something like "we're only applying range keys, so ignore all other other keys". Just so it's explicit we're handing all cases.
</blockquote></details>

sure, done.
___
*[testdata/rangekeys, line 64 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr4uq6YD4F6De7o7Qoi:-Mr8YKl61shUSXKiHBFl:b-rx1hzf) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/testdata/rangekeys#L64)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Just confirming my understanding. This `day` is due to truncation on the range key "side" of the iterator, right?
</blockquote></details>

Yeah, it's due to the 'day' seek-ge argument. 


<!-- Sent from Reviewable.io -->

2021-12-20 09:53 UTC, erikgrinaker commented
Great to see this @jbowens. I'm building a small prototype of MVCC range tombstones on top of this, will review when I have something functional.

2021-12-21 03:51 UTC, sumeerbhola requested changes
I need to make another pass through `iterator.go` -- meanwhile flushing some comments.

> Reviewed 5 of 11 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415#-:-MrQ61mlDCkqLhTfcDdo:bmwsifq)* status: 17 of 19 files reviewed, 14 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @nicktrav)

___
*[db.go, line 943 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrPyaKu6VA7pX3OAnmp:-MrPyaKu6VA7pX3OAnmq:btqfxxf) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/db.go#L943)):*
> ```Go
> 		buf.merging.elideRangeTombstones = true
> 	} else {
> 		buf.merging.init(&dbi.opts, dbi.cmp, dbi.split)
> ```

so this is a mergingIter with no levels, so produces nothing, yes?
___
*[iterator.go, line 174 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrQ-maoDsOUaljXR3CK:-MrQ-maoDsOUaljXR3CL:bb0zn6a) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/iterator.go#L174)):*
> ```Go
> 	keys         []RangeKey
> 	start        []byte
> 	end          []byte
> ```

could you add a comment that [start, end) is the span of the range keys.
___
*[iterator.go, line 1195 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrQ-EypAJoXeGtNKvgT:-MrQ-EypAJoXeGtNKvgU:b-t6obtp) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/iterator.go#L1195)):*
> ```Go
> // RangeKey describes a range key, set through RangeKeySet. The range of the
> // range key is provided by Iterator.RangeBounds.
> type RangeKey struct {
> ```

if this only has the suffix and value, it isn't a full range key. Is there a better name?
___
*[options.go, line 361 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrQ06cd7a-5mWO72cVR:-MrQ06cd7a-5mWO72cVS:b-gneicy) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/options.go#L361)):*
> ```Go
> 		// temporary, to allow the Pebble metamorphic tests to reuse the
> 		// range-key arena across DB restarts.
> 		RangeKeys *RangeKeysArena
> ```

how does this become non-nil using the corresponding field in the DB 
___
*[range_keys.go, line 73 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrQ1i7J2kIrTLkYQdqc:-MrQ1i7J2kIrTLkYQdqd:b7ed5un) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/range_keys.go#L73)):*
> ```Go
> 	// buffer.
> 	d.rangeKeys.once.Do(func() {
> 		d.rangeKeys.arenaBuf = make([]byte, rangeKeyArenaSize)
> ```

nit: do we need the arenaBuf member field given that we are not doing manual memory management?
___
*[range_keys.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrQ2OJX8dJXObo2yrrs:-MrQ2OJX8dJXObo2yrrt:b-xgstnl) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/range_keys.go#L86)):*
> ```Go
> 					err = base.CorruptionErrorf("unable to decode end key for key of kind %s", kind)
> 				}
> 				return endKey, value, err
> ```

so the value here includes the suffix? Would be worth clarifying since there are other places we refer to the value as excluding the suffix.
___
*[range_keys.go, line 98 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrQ54br18CjKM19i6jb:-MrQ54br18CjKM19i6jc:b-u516et) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/range_keys.go#L98)):*
> ```Go
> 	d.maybeInitializeRangeKeys()
> 	frags := d.rangeKeys.fragCache.get()
> 	fragIter := new(keyspan.VisibleIter)
> ```

just curious -- is there a reason this method uses `new` here and below instead of doing the more common `&fooStructType{}`


<!-- Sent from Reviewable.io -->

2021-12-21 17:39 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415)* status: 7 of 19 files reviewed, 14 unresolved discussions (waiting on @erikgrinaker, @jbowens, @nicktrav, and @sumeerbhola)

___
*[db.go, line 943 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrPyaKu6VA7pX3OAnmp:-MrSziE880vwMezbVqFO:bc9sq1n) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/db.go#L943)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

so this is a mergingIter with no levels, so produces nothing, yes?
</blockquote></details>

Yeah, that's right. Added a comment.
___
*[iterator.go, line 174 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrQ-maoDsOUaljXR3CK:-MrT-hdR5zB-GvnJmyh-:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/iterator.go#L174)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

could you add a comment that [start, end) is the span of the range keys.
</blockquote></details>

Done.
___
*[iterator.go, line 1195 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrQ-EypAJoXeGtNKvgT:-MrT2Gp29JIOpXFGMruh:b-4qrwur) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/iterator.go#L1195)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

if this only has the suffix and value, it isn't a full range key. Is there a better name?
</blockquote></details>

updated to `RangeKeyData` for now... still trying to think of something better
___
*[options.go, line 361 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrQ06cd7a-5mWO72cVR:-MrT0_Bv1ut5UcadBBSU:bsdjlvs) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/options.go#L361)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how does this become non-nil using the corresponding field in the DB 
</blockquote></details>

the user needs to populate this themselves:
```
rangeKeys := &pebble.RangeKeysArena{}
opts.Experimental.RangeKeys = rangeKeys
```
At `Open`, it's copied from the `Options` into the `DB` field. The actual arena, skiplist, etc are lazily initialized.
___
*[range_keys.go, line 73 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrQ1i7J2kIrTLkYQdqc:-MrT1Uxd85ItmiNl4qMh:b-hfpv0l) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/range_keys.go#L73)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: do we need the arenaBuf member field given that we are not doing manual memory management?
</blockquote></details>

removed
___
*[range_keys.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrQ2OJX8dJXObo2yrrs:-MrT3PAx4r4MkjA6zYmb:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/range_keys.go#L86)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

so the value here includes the suffix? Would be worth clarifying since there are other places we refer to the value as excluding the suffix.
</blockquote></details>

Done.
___
*[range_keys.go, line 98 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrQ54br18CjKM19i6jb:-MrT1bsxEPHY1SgsnEl_:b-solaus) ([raw file](https://github.com/cockroachdb/pebble/blob/c3ef2c391026a61d5037302d14383fd82af639b9/range_keys.go#L98)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

just curious -- is there a reason this method uses `new` here and below instead of doing the more common `&fooStructType{}`
</blockquote></details>

no reason, I think I found myself doing that when there are no fields to explicitly initialize. The `&fooStructType{}` is a lot more common, so I'll switch this.


<!-- Sent from Reviewable.io -->

2021-12-21 18:45 UTC, nicktrav reviewed
> Reviewed 1 of 1 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415)* status: all files reviewed, 10 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-12-22 13:40 UTC, erikgrinaker commented
Seems like we don't handle `Iterator.rangeKey` in `Iterator.Clone()`. CockroachDB relies on this in intent interleaving iterators, which clone the main iterator from the intent iterator:

https://github.com/cockroachdb/cockroach/blob/c6fee20e9d7275714902a6105859ad050ca4fd7a/pkg/storage/intent_interleaving_iter.go#L236

Since most MVCC accesses go via intent interleaving iterators, we generally always end up with such iterators that are unable to access range keys.

Mind adding in support for this too?

2021-12-22 15:06 UTC, jbowens reviewed
> Seems like we don't handle Iterator.rangeKey in Iterator.Clone()

Ah, forgot about that! Added

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415#-:-MrXfNPs0AqIMdvK8uOY:b-pi1qmp)* status: 17 of 19 files reviewed, 10 unresolved discussions (waiting on @erikgrinaker, @jbowens, @nicktrav, and @sumeerbhola)

___
*[testdata/rangekeys, line 5 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Mr4pU-rCsPY3MY4oVQD:-MrXeh60EpMzIhMmjG_w:b-7eh6pu) ([raw file](https://github.com/cockroachdb/pebble/blob/37f0773f797a085a29b81f167ecffc603996120f/testdata/rangekeys#L5)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

I got confused a little with the examples, as the point keys and values are the same (i.e. `set a a`). Any chance we can make the values fruits or something to help disambiguate? No issue with the beeps and boops :)
</blockquote></details>

mind if I add a comment? Sharing the same key and value is useful just to easily be able to catch if we accidentally omit setting the value buffer, and surface the wrong value.


<!-- Sent from Reviewable.io -->

2021-12-22 15:07 UTC, nicktrav reviewed
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415)* status: all files reviewed, 9 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-12-22 17:52 UTC, erikgrinaker commented
One thing that came up is that MVCC mostly cares about point keys, but want access to range keys at those point keys. So when we do e.g. an `MVCCGet`, we do a `SeekGE(MVCCKey{Key: start})` without a timestamp. However, consider a range key [a-c)@2 across b@1. This seek is then simply going to land on the range key without being at a point key, and we'll need to keep iterating until we get to the point at b@1.

This is totally workable, and we can handle this in `pebbleIterator`. But would it make sense to support this as an iteration mode in Pebble (i.e. iterate over points but expose ranges at points), or should that be up to the caller?

2021-12-22 18:16 UTC, jbowens reviewed
In that scenario, if there are no point keys at the search key, but there's a range key covering the key, do we need to see the range key at all?

The interleaving of range key start boundaries was added for the case where we need to notice that there exists a write at the key at a higher timestamp. If there are cases where that's unnecessary, we could add an `IterOption` field to configure the iterator to omit range key start boundaries?

In the case of `SeekPrefixGE`, where we know the user's intention is to look for a specific prefix, we could seek to the first point key that exists with the prefix (surfacing the range keys at the same iterator position) _or_ the range key start boundary if there is no point key with the prefix.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415#-:-MrYHNpPCmdakNLeYW7s:b3p5b5i)* status: all files reviewed, 8 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-12-22 18:38 UTC, erikgrinaker reviewed
> In that scenario, if there are no point keys at the search key, but there's a range key covering the key, do we need to see the range key at all?

No, not in this specific scenario. There are cases where we do want to see them as separate entities though (e.g. when exporting a history for incremental backups).

>The interleaving of range key start boundaries was added for the case where we need to notice that there exists a write at the key at a higher timestamp. If there are cases where that's unnecessary, we could add an `IterOption` field to configure the iterator to omit range key start boundaries?

Right, are you saying that if we `SeekGE` to b then we would want to see [b-c)@3? Would we not see that anyway when we're at b@2? What about [b-c)@1?

An option to omit range key start boundaries sounds like it might be convenient. But maybe we can wait until I've gotten a little further with the prototype, as we might find other minor stuff that could affect this.

> In the case of `SeekPrefixGE`, where we know the user's intention is to look for a specific prefix, we could seek to the first point key that exists with the prefix (surfacing the range keys at the same iterator position) or the range key start boundary if there is no point key with the prefix.

Yeah, I think that'd make sense.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415#-:-MrYN3UEBuZEc9zUE3lU:bszt2kp)* status: 16 of 19 files reviewed, 8 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-12-22 21:33 UTC, sumeerbhola reviewed
I don't fully understand this -- isn't the normal case the one with uncertainty checking where we need to see the range key even if there isn't a point key? If there are cases where we don't care about the range key we should consider whether omitting the range key belongs in a wrapper implementation in the storage package instead of plumbing this case into Pebble.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415#-:-MrZ2NqGBxXwNbJL0is5:btwt0dz)* status: 16 of 19 files reviewed, 8 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-12-22 22:48 UTC, sumeerbhola requested changes
> Reviewed 9 of 11 files at r5, 2 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415)* status: 18 of 19 files reviewed, 18 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[iterator.go, line 270 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZ8yXuC1iGC0RPE7ay:-MrZ8yXuC1iGC0RPE7az:bmlhuqv) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L270)):*
> ```Go
> 			i.key = i.keyBuf
> 			i.value = nil
> 			// There may also be a live point key at this key.
> ```

We've not seen this live point key yet, yes? So this is for the future?
And we have to save because we may find that the live point key is beyond the end of the range key, so we don't want to lose the range key?
This could use a longer comment.
I guess one could claim that the `InterleavingIter` interface is hurting us since it already knows if there is a point key coincident with this range key's start user key. I am not saying we should optimize this -- it would be extremely premature.
___
*[iterator.go, line 296 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZHSQG1Nzw_MJlKTEM:-MrZHSQHBN9QQI3bajI7:b-xnvorc) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L296)):*
> ```Go
> 			valueMerger, i.err = i.merge(key.UserKey, i.iterValue)
> 			if i.err == nil {
> 				i.saveRangeKey()
> ```

Can you add a code comment here stating why we need to save the range key (because the merge can take us to the next point key which may be beyond the end of the range key).
___
*[iterator.go, line 331 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZAWYlD8RsMFl75Uwh:-MrZAWYlD8RsMFl75Uwi:b-h3uykp) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L331)):*
> ```Go
> 
> 	// Close the closer for the current value if one was open.
> 	if i.closeValueCloser() != nil {
> ```

why do we need to call `closeValueCloser` for an earlier merge value here given that we've already done so at the top of `findNextEntry`. Is there something about the loop in `findNextEntry` that causes this to be needed for range keys but not for the other cases like `InternalKeyKindSet`?
___
*[iterator.go, line 332 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZBVgR6hzDMeQ-Qo0s:-MrZBVgR6hzDMeQ-Qo0t:bivnw6d) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L332)):*
> ```Go
> 	// Close the closer for the current value if one was open.
> 	if i.closeValueCloser() != nil {
> 		i.iterValidityState = IterExhausted
> ```

We seem to be abusing `iterValidityState` to carry back to the caller some information about point keys, where we will override it given that we do have a range key. An explicit return value seems better.
___
*[iterator.go, line 339 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZBu4ODRAVH-GbMTwO:-MrZBu4ODRAVH-GbMTwP:b-hgodqq) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L339)):*
> ```Go
> 	i.stats.ForwardStepCount[InternalIterCall]++
> 	if i.iterKey == nil || !i.equal(i.key, i.iterKey.UserKey) {
> 		i.pos = iterPosNext
> ```

So `pos` is now only a statement about the point position, yes? Can you add a code comment where `pos` is declared.
___
*[iterator.go, line 340 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZBmGa7c5tOc_qZ9Tw:-MrZBmGa7c5tOc_qZ9Tx:b-ygb1cy) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L340)):*
> ```Go
> 	if i.iterKey == nil || !i.equal(i.key, i.iterKey.UserKey) {
> 		i.pos = iterPosNext
> 		i.iterValidityState = IterExhausted
> ```

same comment about `iterValidityState`.
___
*[iterator.go, line 352 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZCpvM5B4jPLw2EmAO:-MrZCpvM5B4jPLw2EmAP:bbwsk3e) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L352)):*
> ```Go
> 		i.iterValidityState = IterExhausted
> 
> 	case InternalKeyKindDelete, InternalKeyKindSingleDelete:
> ```

We've moved the iterator to `iterPosNext` in some sense. But since this is the same user key, I guess we can pretend that the iterator is still at `iterPosCurForward`, so that a call to Next will skip these deleted point keys. I think we need to strengthen the commentary around what `iterPosCurForward` means -- in this case we've partially consumed stuff for that user key (since we've moved past the range key and are now at the delete). There is a similar comment in the `SeekPrefixGE` that says
```
		// - Even if i.pos were at iterPosCurForward, we could have a DELETE,
		//   SET pair for a key, and the iterator would have moved past DELETE
		//   but stayed at iterPosCurForward. A similar situation occurs for a
		//   MERGE, SET pair where the MERGE is consumed and the iterator is
		//   at the SET.
```
Though I couldn't remember how this can happen for the DELETE,SET pair.

In general, it's worth thinking about any invariants we can add in code comments, so that we can continue evolving this code with low risk (e.g. Bilal is adding the `trySeekUsingNext` optimization to `SeekGE`).
___
*[iterator.go, line 361 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZFaAy3MjcYVa-gC2K:-MrZFaAy3MjcYVa-gC2L:b-1mpkly) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L361)):*
> ```Go
> 	case InternalKeyKindMerge:
> 		var valueMerger ValueMerger
> 		valueMerger, i.err = i.merge(key.UserKey, i.iterValue)
> ```

is this code (close to) the same as the `InternalKeyKindMerge` case in `findNextEntry`? If yes, we should abstract it out.
___
*[iterator.go, line 585 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZIJcT1Ou3vdB5gB4u:-MrZIJcT1Ou3vdB5gB4v:bbeznln) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L585)):*
> ```Go
> 			// must've already iterated over it. This is the final entry at this
> 			// user key.
> 			i.rangeKey.rangeKeyOnly = i.iterValidityState != IterValid
> ```

I don't quite understand this. If there is a range key [b,c) and a point key b, we've already exposed (b, [b,c)) to the user, yes?
Then we shouldn't be showing [b,c) again, should we?
But if the point key was bb, then we would want to show [b,c)?

And why would `iterValidityState` be not `IterValid`? Is this the `IterAtLimit` case?

I am not clear on how range keys are interacting with limits -- I think we need a code comment explaining it.
___
*[iterator.go, line 1520 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZ89dB360BHfDoeS1K:-MrZ89dB360BHfDoeS1L:btqkqsk) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L1520)):*
> ```Go
> 		// TODO(jackson): Pool range-key iterator objects.
> 		dbi.rangeKey = &iteratorRangeKeyState{
> 			rangeKeyIter: i.rangeKey.rangeKeyIter,
> ```

I don't see why we can just share the `rangekey.Iter` since the original and cloned iterator will be iterating independently.


<!-- Sent from Reviewable.io -->

2021-12-23 09:42 UTC, erikgrinaker commented
>I don't fully understand this -- isn't the normal case the one with uncertainty checking where we need to see the range key even if there isn't a point key?

Yeah, I think you're right -- we'll likely need to always check this after all.

>If there are cases where we don't care about the range key we should consider whether omitting the range key belongs in a wrapper implementation in the storage package instead of plumbing this case into Pebble.

Sure, we can do that.

2021-12-23 19:51 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415)* status: 18 of 19 files reviewed, 17 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[iterator.go, line 270 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZ8yXuC1iGC0RPE7ay:-MrcHwJ88J8s6S6ZY60A:blgqvh3) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L270)):*
> I guess one could claim that the InterleavingIter interface is hurting us since it already knows if there is a point key coincident with this range key's start user key

It's pretty tricky, because while the `InterleavingIter` knows whether or not there's a point key, it doesn't know whether it's live. I had originally thought we could tell whether or not the point key is live just by examining it, but there was a change not long ago to allow `ValueMerger`s to drop keys. If there's a `MERGE`, we may need to read an arbitrary number of points ahead to determine if the key is live.
___
*[iterator.go, line 296 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZHSQG1Nzw_MJlKTEM:-MrcKVNc0QDTC99H3wM9:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L296)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a code comment here stating why we need to save the range key (because the merge can take us to the next point key which may be beyond the end of the range key).
</blockquote></details>

Done.
___
*[iterator.go, line 331 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZAWYlD8RsMFl75Uwh:-MrcMgwJ8wi_L7h79Z5f:bwqc8hx) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L331)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why do we need to call `closeValueCloser` for an earlier merge value here given that we've already done so at the top of `findNextEntry`. Is there something about the loop in `findNextEntry` that causes this to be needed for range keys but not for the other cases like `InternalKeyKindSet`?
</blockquote></details>

this was superfluous
___
*[iterator.go, line 332 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZBVgR6hzDMeQ-Qo0s:-MrcXZOxBm7RdGLWPYEH:b1012br) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L332)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We seem to be abusing `iterValidityState` to carry back to the caller some information about point keys, where we will override it given that we do have a range key. An explicit return value seems better.
</blockquote></details>

Yeah, I think there's an unfortunate amount of reliance on callees mutating `iterValidityState` to propagate to callers throughout the iterator implementation. Refactoring `mergeNext` allowed me to clean this bit up some.
___
*[iterator.go, line 339 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZBu4ODRAVH-GbMTwO:-MrcZs6S4c8wGqwXxRz4:b-98qsh) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L339)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So `pos` is now only a statement about the point position, yes? Can you add a code comment where `pos` is declared.
</blockquote></details>

I don't follow. I think it's still a statement about the `internalIterator`'s position, neither specifically about the point or the range.
___
*[iterator.go, line 340 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZBmGa7c5tOc_qZ9Tw:-MrcZlavAsnyJIUuI6x3:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L340)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same comment about `iterValidityState`.
</blockquote></details>

Done.
___
*[iterator.go, line 352 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZCpvM5B4jPLw2EmAO:-MrcikeL0IzE75PpTh8R:b-mjulda) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L352)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We've moved the iterator to `iterPosNext` in some sense. But since this is the same user key, I guess we can pretend that the iterator is still at `iterPosCurForward`, so that a call to Next will skip these deleted point keys. I think we need to strengthen the commentary around what `iterPosCurForward` means -- in this case we've partially consumed stuff for that user key (since we've moved past the range key and are now at the delete). There is a similar comment in the `SeekPrefixGE` that says
```
		// - Even if i.pos were at iterPosCurForward, we could have a DELETE,
		//   SET pair for a key, and the iterator would have moved past DELETE
		//   but stayed at iterPosCurForward. A similar situation occurs for a
		//   MERGE, SET pair where the MERGE is consumed and the iterator is
		//   at the SET.
```
Though I couldn't remember how this can happen for the DELETE,SET pair.

In general, it's worth thinking about any invariants we can add in code comments, so that we can continue evolving this code with low risk (e.g. Bilal is adding the `trySeekUsingNext` optimization to `SeekGE`).
</blockquote></details>

In general the ambiguity seems to be that an `Iterator` maps many `internalIterator` positions to a single `Iterator` position. In the case of `MERGE`, the number of `internalIterator` positions represented by a single `Iterator` position is technically unbounded.

I took a stab at adding some additional comments on `iterPos` to disambiguate this. Thoughts?
___
*[iterator.go, line 361 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZFaAy3MjcYVa-gC2K:-MrcXTEF9Ax4sd3kouyi:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L361)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this code (close to) the same as the `InternalKeyKindMerge` case in `findNextEntry`? If yes, we should abstract it out.
</blockquote></details>

Done.
___
*[iterator.go, line 585 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZIJcT1Ou3vdB5gB4u:-MrckjpI8ZUdk17rZcMV:b-r0u6t8) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L585)):*
> I don't quite understand this. If there is a range key [b,c) and a point key b, we've already exposed (b, [b,c)) to the user, yes?

No — we're producing an entry in the reverse direction here, so when we encounter the `b.SET` we don't know whether it's live. Typically, this loop terminates when we find a key with a different user key. For consistency, I've updated this case to Prev() to the previous user key.

> And why would `iterValidityState` be not `IterValid`?

If there's not a valid point key between the old iterator position and the range key set. For example, if the internalIterator contains `a.RANGEKEYSET` and `b.SET.4` and the `Iterator` is currently positioned at `b.SET.4`. The user `Prev`s, calling `findPrevEntry` which immediately sets `iterValidityState` to `IterExhausted`. The first entry encountered is `a.RANGEKEYSET`. We want to surface the range key at `Key() == "a"`, and there's no coincident point key (signaled by `iterValidityState == IterExhausted`).
___
*[iterator.go, line 1520 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZ89dB360BHfDoeS1K:-MrcM0WZ3EfUxRL6JXjo:b6zjgg5) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L1520)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't see why we can just share the `rangekey.Iter` sin [...]

2021-12-23 21:25 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415)* status: 15 of 19 files reviewed, 17 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[iterator.go, line 585 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZIJcT1Ou3vdB5gB4u:-MrdAaDHBpRQ7BCMKsTN:b-igfjed) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L585)):*
> I am not clear on how range keys are interacting with limits -- I think we need a code comment explaining it.

There was some unaccounted for complexity here during reverse limited iteration. I added some logic to account for it, plus some commentary up top discussing the interactions.


<!-- Sent from Reviewable.io -->

2022-01-04 16:32 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 
I haven't looked carefully at the test cases -- I am assuming @nicktrav is covering that well.

> Reviewed 2 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415#-:-Ms_vfiF86aRd4LLI-5q:baa4wr5)* status: 17 of 19 files reviewed, 20 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[iterator.go, line 270 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZ8yXuC1iGC0RPE7ay:-Ms_cL5l0CMuWqqNZb9x:b-a7jufr) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L270)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> I guess one could claim that the InterleavingIter interface is hurting us since it already knows if there is a point key coincident with this range key's start user key

It's pretty tricky, because while the `InterleavingIter` knows whether or not there's a point key, it doesn't know whether it's live. I had originally thought we could tell whether or not the point key is live just by examining it, but there was a change not long ago to allow `ValueMerger`s to drop keys. If there's a `MERGE`, we may need to read an arbitrary number of points ahead to determine if the key is live.
</blockquote></details>

I see. Thanks for the explanation.
___
*[iterator.go, line 332 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZBVgR6hzDMeQ-Qo0s:-Ms_r3ViC5R_uW1WKFWk:b-ohe1l2) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L332)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, I think there's an unfortunate amount of reliance on callees mutating `iterValidityState` to propagate to callers throughout the iterator implementation. Refactoring `mergeNext` allowed me to clean this bit up some.
</blockquote></details>

Looks cleaner with this bool return value.
___
*[iterator.go, line 339 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZBu4ODRAVH-GbMTwO:-Ms_dELJDhRrM1BhYrPI:b2nhysk) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L339)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I don't follow. I think it's still a statement about the `internalIterator`'s position, neither specifically about the point or the range.
</blockquote></details>

ack
___
*[iterator.go, line 352 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZCpvM5B4jPLw2EmAO:-Ms_dPjUEEyupIQDLT8-:bou2whh) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L352)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

In general the ambiguity seems to be that an `Iterator` maps many `internalIterator` positions to a single `Iterator` position. In the case of `MERGE`, the number of `internalIterator` positions represented by a single `Iterator` position is technically unbounded.

I took a stab at adding some additional comments on `iterPos` to disambiguate this. Thoughts?
</blockquote></details>

additional comment about iterPos looks good
___
*[iterator.go, line 361 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZFaAy3MjcYVa-gC2K:-Ms_ovow8WSGGLb2MKz4:b-5rvp9i) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L361)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This looks much better
___
*[iterator.go, line 44 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Ms_bE-f-fG5JFRFYAE3:-Ms_bE-f-fG5JFRFYAE4:b-66vwx) ([raw file](https://github.com/cockroachdb/pebble/blob/a14cecbc224f3d5f6bc5f4b9302179c6e3952362/iterator.go#L44)):*
> ```Go
> // Iterator positioning methods may set iterPos to iterPosCur{Foward,Backward}
> // iff the user key at the current internalIterator position equals the
> // Iterator.Key returned to the user. This guarantees that a call to nextUserKey
> ```

Nice comment. Could you add another sentence tying this back to the example that IterPosCurForward is not making any guarantee about which of the `a` InternalKeys it is at (and it will vary subtly based on the semantics of the various key kinds encountered).
___
*[iterator.go, line 700 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Ms_tT8z16hho2LpGhdv:-Ms_tT8z16hho2LpGhdw:b-1b1baf) ([raw file](https://github.com/cockroachdb/pebble/blob/a14cecbc224f3d5f6bc5f4b9302179c6e3952362/iterator.go#L700)):*
> ```Go
> 			i.valueBuf = append(i.valueBuf[:0], i.iterValue...)
> 			i.value = i.valueBuf
> 			i.saveRangeKey()
> ```

A single range key could overlap with many point keys, and we'll be repeatedly saving it. Consider adding a TODO to optimize this.
We could expose methods to `rangekey.InterleavingIter` to save the current range key and access the saved key, and multiple calls to save the current, when the current hasn't changed, would become noops.  
___
*[internal/rangekey/iter.go, line 50 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Ms_ZMzJ55XXkGZIkiYf:-Ms_ZMzJ55XXkGZIkiYg:bysismk) ([raw file](https://github.com/cockroachdb/pebble/blob/a14cecbc224f3d5f6bc5f4b9302179c6e3952362/internal/rangekey/iter.go#L50)):*
> ```Go
> func (i *Iter) Clone() *Iter {
> 	newIter := &Iter{}
> 	*newIter = *i
> ```

does the mutable state in the `Coalescer` needs to be reset? And does one need to clear `newIter.curr` and the other fields in `newIter` (err, valid, ...)?
And similar question about `keyspan.Iter.index`. I suspect the answer is no for most/all of these (except for an err field) since they represent the current iterator position and it is harmless to preserve it, since the caller has to do some kind of seek before using the new iterator. But it is worth a code comment.


<!-- Sent from Reviewable.io -->

2022-01-04 22:42 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415)* status: 14 of 19 files reviewed, 20 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[iterator.go, line 361 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MrZFaAy3MjcYVa-gC2K:-MsbBafgBn37Kgmg9Okm:b-j1we20) ([raw file](https://github.com/cockroachdb/pebble/blob/413726b320e35a165c51514f083b8c9ffeae9c49/iterator.go#L361)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This looks much better
</blockquote></details>

:raised_hands: 
___
*[iterator.go, line 44 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Ms_bE-f-fG5JFRFYAE3:-MsbB5POCcvlI41ZuGqN:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a14cecbc224f3d5f6bc5f4b9302179c6e3952362/iterator.go#L44)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Nice comment. Could you add another sentence tying this back to the example that IterPosCurForward is not making any guarantee about which of the `a` InternalKeys it is at (and it will vary subtly based on the semantics of the various key kinds encountered).
</blockquote></details>

Done.
___
*[iterator.go, line 700 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Ms_tT8z16hho2LpGhdv:-MsbCqQZAVDVAWo9hcvC:buy9xhf) ([raw file](https://github.com/cockroachdb/pebble/blob/a14cecbc224f3d5f6bc5f4b9302179c6e3952362/iterator.go#L700)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

A single range key could overlap with many point keys, and we'll be repeatedly saving it. Consider adding a TODO to optimize this.
We could expose methods to `rangekey.InterleavingIter` to save the current range key and access the saved key, and multiple calls to save the current, when the current hasn't changed, would become noops.  
</blockquote></details>

Yeah, there's a TODO in saveRangeKey but added another one here.
___
*[internal/rangekey/iter.go, line 50 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1415#-Ms_ZMzJ55XXkGZIkiYf:-MsbEV_26bklAhf-r_wg:b-bsmxu8) ([raw file](https://github.com/cockroachdb/pebble/blob/a14cecbc224f3d5f6bc5f4b9302179c6e3952362/internal/rangekey/iter.go#L50)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

does the mutable state in the `Coalescer` needs to be reset? And does one need to clear `newIter.curr` and the other fields in `newIter` (err, valid, ...)?
And similar question about `keyspan.Iter.index`. I suspect the answer is no for most/all of these (except for an err field) since they represent the current iterator position and it is harmless to preserve it, since the caller has to do some kind of seek before using the new iterator. But it is worth a code comment.
</blockquote></details>

modified this to use `newIter.Init` to clear the mutable state, including the harmless state, anyways.

Also added a TODO to remove this method once range keys state is included in the read state.


<!-- Sent from Reviewable.io -->

2022-01-05 18:33 UTC, nicktrav approved these changes
Nice. Did a pass of the changes since last review, and <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 3 files at r8, 1 of 3 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415#-:-MsfVezn5bOWFxmt4gog:b-n5utvv)* status: all files reviewed, 21 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[testdata/rangekeys, line 292 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MsfUck1AyPZSIINiriV:-MsfUck1AyPZSIINiriW:b-j6ae1t) ([raw file](https://github.com/cockroachdb/pebble/blob/7b19937c9f0fe2f8d0bb7bda64064e1dfd17a6fe/testdata/rangekeys#L292)):*
> ```
> wrote 4 keys
> 
> scan-rangekeys
> ```

nit: Perhaps we can add a comment here that calls out that when shadowing ranges in a batch, the last op wins? That seems to be what's happening here.


<!-- Sent from Reviewable.io -->

2022-01-05 21:19 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415#-:-Msg68y71k6GmFWkDV6G:bz5mair)* status: 18 of 19 files reviewed, 21 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[testdata/rangekeys, line 292 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MsfUck1AyPZSIINiriV:-Msg6AIyE_gnZn6kVIDc:b-48vilg) ([raw file](https://github.com/cockroachdb/pebble/blob/7b19937c9f0fe2f8d0bb7bda64064e1dfd17a6fe/testdata/rangekeys#L292)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: Perhaps we can add a comment here that calls out that when shadowing ranges in a batch, the last write wins? That seems to be what's happening here.
</blockquote></details>

Good call, done.


<!-- Sent from Reviewable.io -->

2022-01-05 21:20 UTC, merged

2022-01-05 21:42 UTC, nicktrav reviewed
> Reviewed 1 of 3 files at r8, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415)* status: all files reviewed, 20 unresolved discussions



<!-- Sent from Reviewable.io -->

2022-01-06 13:41 UTC, sumeerbhola reviewed
> Reviewed 2 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1415)* status: all files reviewed, 21 unresolved discussions

___
*[internal/rangekey/iter.go, line 54 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1415#-MsjbO4f1czQsbWgGO_0:-MsjbO4f1czQsbWgGO_1:bbdyori) ([raw file](https://github.com/cockroachdb/pebble/blob/ae2a14a21d0b191799f80ee0495905ed54d9a03b/internal/rangekey/iter.go#L54)):*
> ```Go
> 	ki := &keyspan.Iter{}
> 	*ki = *i.iter
> 	// Init the new Iter to ensure err is clearer.
> ```

nit: is cleared.


<!-- Sent from Reviewable.io -->