internal/rangekey: implement range-key masking
cockroachdb/pebble pull request #1425
Opened 2021-12-21 22:55 UTC by jbowens

Extend the InterleavingIter to also implement nave range-key masking. When
configured with a range-key masking threshold _t_, and there exists a range key
with suffix _r_ covering a point key with suffix _p_, and

	_t_ < _r_ < _p_

then the point key is elided.

2021-12-21 22:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1425)
<!-- Reviewable:end -->

2021-12-22 20:01 UTC, nicktrav reviewed
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1425)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/coalescer.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1425#-MrY5e0o1VrelxvUGmMg:-MrY5e0pEoz-YoDUYff-:b-qco166) ([raw file](https://github.com/cockroachdb/pebble/blob/b8d02e3c769c81ba7ba5b50ecb6e8f3b474206d4/internal/rangekey/coalescer.go#L34)):*
> // that's also less (as defined by cmp) than the suffixThreshold argument.

Isn't this method returning "the first set suffix _greater_ than then threshold"? 
___
*[internal/rangekey/interleaving_iter.go, line 518 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1425#-MrYBht91N_PMZaRw-fB:-MrYBht91N_PMZaRw-fC:b-rt2gda) ([raw file](https://github.com/cockroachdb/pebble/blob/b8d02e3c769c81ba7ba5b50ecb6e8f3b474206d4/internal/rangekey/interleaving_iter.go#L518)):*
> ```Go
> 			// interleaved next, if it's not masked.
> 			if i.cmp(i.pointKey.UserKey, i.rangeKey.End) < 0 {
> 				// The range key is covered by the point key. It might be masked
> ```

nit: `The range key covers the point key ...`?
___
*[internal/rangekey/interleaving_iter.go, line 534 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1425#-MrYC4vO7ha1M3O8jOvX:-MrYC4vP18SdnmaZlXKH:bxw5oib) ([raw file](https://github.com/cockroachdb/pebble/blob/b8d02e3c769c81ba7ba5b50ecb6e8f3b474206d4/internal/rangekey/interleaving_iter.go#L534)):*
> ```Go
> 
> 				// Point key is unmasked but covered.
> 				return i.yieldPointKey(true)
> ```

nit: add `/* covered */` comments here (and below) too?
___
*[internal/rangekey/testdata/interleaving_iter_masking, line 1 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1425#-MrYiE294llQuH7tcZNc:-MrYiE294llQuH7tcZNd:b78idfj) ([raw file](https://github.com/cockroachdb/pebble/blob/b8d02e3c769c81ba7ba5b50ecb6e8f3b474206d4/internal/rangekey/testdata/interleaving_iter_masking#L1)):*
> ```
> # Test the scenario illustrated in the below visualization.
> ```

Are there additional use cases that would be useful for adding coverage to other iterator methods (seek GE / LT, set bounds, etc.) to ensure they behave as expected with range keys?
___
*[internal/rangekey/testdata/interleaving_iter_masking, line 316 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1425#-MrYhbPc5_ad-5TJ4b3P:-MrYhbPc5_ad-5TJ4b3Q:b-q4976m) ([raw file](https://github.com/cockroachdb/pebble/blob/b8d02e3c769c81ba7ba5b50ecb6e8f3b474206d4/internal/rangekey/testdata/interleaving_iter_masking#L316)):*
> ```
> first
> next
> next
> ```

nit: Worth iterating backwards too and ensuring that the same keys are returned in reverse?


<!-- Sent from Reviewable.io -->

2021-12-22 23:52 UTC, sumeerbhola requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1425)* status: all files reviewed, 7 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1425#-MrZWmLyBNai1WSckRKB):*
can you remind me why this is not t <= r, given that we CockroachDB has a read timestamp that indicates a desire to read all unmasked values <= t?
___
*[internal/rangekey/coalescer.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1425#-MrY5e0o1VrelxvUGmMg:-MrZYDRvBZ3xQjwifShu:b-ogrbev) ([raw file](https://github.com/cockroachdb/pebble/blob/b8d02e3c769c81ba7ba5b50ecb6e8f3b474206d4/internal/rangekey/coalescer.go#L34)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

> // that's also less (as defined by cmp) than the suffixThreshold argument.

Isn't this method returning "the first set suffix _greater_ than then threshold"? 
</blockquote></details>

yep, looks like it.
___
*[internal/rangekey/interleaving_iter.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1425#-MrZYghH6wBsChfTJXgl:-MrZYghH6wBsChfTJXgm:bqv886q) ([raw file](https://github.com/cockroachdb/pebble/blob/b8d02e3c769c81ba7ba5b50ecb6e8f3b474206d4/internal/rangekey/interleaving_iter.go#L87)):*
> ```Go
> // will observe point keys b@2 and l@8. The range keys [h,q)@6 and [f,l)@3 serve
> // as masks, because cmp(@6,@7) > 0 and cmp(@3,@7) > 0. The range key [e,m)@9
> // does not serve as a mask, because cmp(@9,@7) ≤ 0.
> ```

Are the range keys that serve as masks also exposed?


<!-- Sent from Reviewable.io -->

2021-12-23 17:14 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1425)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1425#-MrZWmLyBNai1WSckRKB):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you remind me why this is not t <= r, given that we CockroachDB has a read timestamp that indicates a desire to read all unmasked values <= t?
</blockquote></details>

I think I was just confused.

The t ≤ r condition precludes using AddSSTable with timestamp rewriting on a sstable that MVCCDeleteRanges a keyspace that overlaps with the table's point keys. I don't think this is actually something we require.
___
*[internal/rangekey/coalescer.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1425#-MrY5e0o1VrelxvUGmMg:-MrcCKdd7XqpDl2HtHyF:bt2vr0y) ([raw file](https://github.com/cockroachdb/pebble/blob/b8d02e3c769c81ba7ba5b50ecb6e8f3b474206d4/internal/rangekey/coalescer.go#L34)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

yep, looks like it.
</blockquote></details>

Fixed!
___
*[internal/rangekey/interleaving_iter.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1425#-MrZYghH6wBsChfTJXgl:-MrcA51g-ZyXS2zd5kJt:b-bzprqs) ([raw file](https://github.com/cockroachdb/pebble/blob/b8d02e3c769c81ba7ba5b50ecb6e8f3b474206d4/internal/rangekey/interleaving_iter.go#L87)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are the range keys that serve as masks also exposed?
</blockquote></details>

Yeah they are — updated the comment to state this explicitly


<!-- Sent from Reviewable.io -->

2021-12-24 04:56 UTC, nicktrav reviewed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1425)* status: all files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-01-04 23:08 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1425)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[internal/rangekey/interleaving_iter.go, line 517 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1425#-Msa07X-6NY7AxSeHVFp:-MsbIacd0LhMaZNx9dLl:b-th2zke) ([raw file](https://github.com/cockroachdb/pebble/blob/e4a41e10a730e4003b2e2a5ef4fc11af4e804f64/internal/rangekey/interleaving_iter.go#L517)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Begins at a key equal to or before the current point key?
Since the invariant here is i.rangeKey.Start <= i.pointKey.UserKey

</blockquote></details>

good call, done
___
*[internal/rangekey/testdata/interleaving_iter_masking, line 316 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1425#-MrYhbPc5_ad-5TJ4b3P:-MsbJ1vPEvnMUe70Itm7:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b8d02e3c769c81ba7ba5b50ecb6e8f3b474206d4/internal/rangekey/testdata/interleaving_iter_masking#L316)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: Worth iterating backwards too and ensuring that the same keys are returned in reverse?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-05 19:57 UTC, nicktrav approved these changes
Latest changes <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1425#-:-MsfoFX0CwFnojXswoJV:bbtwnlv)* status: all files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-01-05 21:34 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1425#-:-Msg9a279lxqQAOQQjfS:bz5mair)* status: all files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-01-05 21:34 UTC, merged