internal/manifest: narrow Overlaps to exclude RANGEDEL sentinel keys.
cockroachdb/pebble pull request #1432
Opened 2021-12-28 21:09 UTC by jbowens

When the largest key in a sstable is a range tombstone, the sstable's largest
boundary is set to the range deletion sentinel with the tombstone's exclusive
end boundary and the maximum sequence number. The range deletion sentinel
serves as a marker, indicating that the file's bounds end immediately before
the first key with the sentinel's user key.

In many places such as growing compactions or determining atomic compaction
units, Pebble considers the sentinel as exclusive and avoids unnecessarily
including files that share the same user key but only as a sentinel's exclusive
end bounary.

The `(*manifest.Version).Overlaps` method did not share this logic and only
considered user keys. This method is used during compaction picking when
finding the initial compaction inputs, for determining in-use key ranges,
grandparent files, etc.

This change adapts this method to consider a file with a largest user key equal
to the search range's start user key nonoverlapping if the file's largest key
is a range deletion sentinel.

This change is expected to reduce write amplification in the presence of range
deletions by avoiding unnecessarily pulling in file(s) on the left due to
perceived overlap.

2021-12-28 21:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1432)
<!-- Reviewable:end -->

2021-12-30 21:10 UTC, itsbilal approved these changes
Great catch! It's been a while since we caught an instance of Pebble not special-casing rangedel sentinel keys, but I'm not surprised there's one more.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1432#-:-MsC5x4L7NGm1LEy0rIs:bvdo10d)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

___
*[internal/manifest/version.go, line 517 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1432#-MsC9nxQ-DPOL3FaMAwX:-MsC9nxQ-DPOL3FaMAwY:b-dwxhel) ([raw file](https://github.com/cockroachdb/pebble/blob/5529fe87b65e71ec96136e8ca600b93fc9527583/internal/manifest/version.go#L517)):*
> ```Go
> // The returned files are a subsequence of the input files, i.e., the ordering
> // is not changed.
> func (v *Version) Overlaps(level int, cmp Compare, start, end []byte) LevelSlice {
> ```

You're handling the `f.Largest.UserKey == start && f.Largest.Trailer = RangeDelSentinel` case correctly, but we can do better and also handle the `end == RangeDelSentinel && f.Smallest.UserKey == end` case. But since `end` is a user key, you'd have to add an `exclusiveEnd` bool in the signature and make the relevant signature changes everywhere.

What do you think? I think that'd be a good idea to also fix while we're addressing this, but if you feel otherwise, I'm good with <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> -ing this as-is.


<!-- Sent from Reviewable.io -->

2022-01-04 14:24 UTC, sumeerbhola requested changes
nice!

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1432#-:-Ms_TP735F9cBmmY7FcT:b-7m74ox)* status: all files reviewed, 2 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[internal/manifest/version.go, line 517 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1432#-MsC9nxQ-DPOL3FaMAwX:-Ms_Q_4FEFu5Ukw6AJ1E:bcfl8bc) ([raw file](https://github.com/cockroachdb/pebble/blob/5529fe87b65e71ec96136e8ca600b93fc9527583/internal/manifest/version.go#L517)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

You're handling the `f.Largest.UserKey == start && f.Largest.Trailer = RangeDelSentinel` case correctly, but we can do better and also handle the `end == RangeDelSentinel && f.Smallest.UserKey == end` case. But since `end` is a user key, you'd have to add an `exclusiveEnd` bool in the signature and make the relevant signature changes everywhere.

What do you think? I think that'd be a good idea to also fix while we're addressing this, but if you feel otherwise, I'm good with <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> -ing this as-is.
</blockquote></details>

+1 to handling the end being exclusive case. There seem to be enough callers who have an [InternalKey, InternalKey] and we are losing information by passing in only the `UserKey`.
___
*[testdata/range_del, line 1269 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1432#-Ms_Rr3VC19qbjGjPQI-:-Ms_Rr3VC19qbjGjPQI0:blpkisp) ([raw file](https://github.com/cockroachdb/pebble/blob/5529fe87b65e71ec96136e8ca600b93fc9527583/testdata/range_del#L1269)):*
> ```
> ----
> 1:
>   000008:[a-c]
> ```

can this test be changed to print the InternalKey bounds. It will make it easier to see that the test cases are actually correct.


<!-- Sent from Reviewable.io -->

2022-01-05 00:25 UTC, jbowens reviewed
Added the exclusiveEnd parameter. I also added a `(*InternalKey).IsExclusiveSentinel` helper, because range keys will also have exclusive sentinel key kinds. Some of this logic will need to further change with range keys, for example, `levelIter` and `mergingIter` will only care if the largest key that affects points (eg, point key or range del) is a sentinel. I've deferred that for now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1432#-:-MsbbRZyCM3Vr3-cHEqU:b49bda6)* status: 0 of 23 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[internal/manifest/version.go, line 517 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1432#-MsC9nxQ-DPOL3FaMAwX:-MsbbOwG9dTztx4GzxQk:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/5529fe87b65e71ec96136e8ca600b93fc9527583/internal/manifest/version.go#L517)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

+1 to handling the end being exclusive case. There seem to be enough callers who have an [InternalKey, InternalKey] and we are losing information by passing in only the `UserKey`.
</blockquote></details>

Done.
___
*[testdata/range_del, line 1269 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1432#-Ms_Rr3VC19qbjGjPQI-:-MsahI524Kk9ANVrPlii:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/5529fe87b65e71ec96136e8ca600b93fc9527583/testdata/range_del#L1269)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can this test be changed to print the InternalKey bounds. It will make it easier to see that the test cases are actually correct.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-05 16:27 UTC, itsbilal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 17 files at r2, 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1432#-:-Msf3Lx5460cQjUmKyqV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-01-05 20:05 UTC, nicktrav approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1432)* status: all files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-01-11 18:07 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 17 files at r2, 16 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1432#-:-Mt9Jcdr1RW0qmhfNZx-:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/manifest/version.go, line 275 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1432#-Mt9GrbI5q0GdYCRnmwx:-Mt9GrbI5q0GdYCRnmwy:beou5ne) ([raw file](https://github.com/cockroachdb/pebble/blob/e4fab746b6dfbbd5a6cc41eb4778c5137c47e866/internal/manifest/version.go#L275)):*
> ```Go
> 	if !endIter.iter.valid() {
> 		endIter.Prev()
> 	} else if c := cmp(endIter.Current().Smallest.UserKey, end); c > 0 || c == 0 && exclusiveEnd {
> ```

nit: we don't need to do the comparison if !exclusiveEnd, so may as well avoid it.
___
*[internal/manifest/version_test.go, line 264 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1432#-Mt9IFjD3RZGVKsZfI9w:-Mt9IFjE3QOeGxLu8f1S:beyqnyj) ([raw file](https://github.com/cockroachdb/pebble/blob/e4fab746b6dfbbd5a6cc41eb4778c5137c47e866/internal/manifest/version_test.go#L264)):*
> ```Go
> 		// Level 2: empty.
> 		{2, "a", "z", false, ""},
> 	}
> ```

I'm being paranoid here, but curious if coverprofile shows that we've covered all the code paths.


<!-- Sent from Reviewable.io -->

2022-01-11 19:17 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1432)* status: all files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)

___
*[internal/manifest/version.go, line 275 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1432#-Mt9GrbI5q0GdYCRnmwx:-Mt9YAM4DGeEu26UVyG_:b-syuym3) ([raw file](https://github.com/cockroachdb/pebble/blob/e4fab746b6dfbbd5a6cc41eb4778c5137c47e866/internal/manifest/version.go#L275)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: we don't need to do the comparison if !exclusiveEnd, so may as well avoid it.
</blockquote></details>

I might be misunderstanding, but if `!exclusiveEnd` the above for loop might've Nexted to a file with `Smallest.UserKey` > `end`, and we need the comparison to check for that.
___
*[internal/manifest/version_test.go, line 264 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1432#-Mt9IFjD3RZGVKsZfI9w:-Mt9ZZvX8tZAVQSU_aAp:b-hzmg7x) ([raw file](https://github.com/cockroachdb/pebble/blob/e4fab746b6dfbbd5a6cc41eb4778c5137c47e866/internal/manifest/version_test.go#L264)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm being paranoid here, but curious if coverprofile shows that we've covered all the code paths.
</blockquote></details>

Just checked and it does :+1: 


<!-- Sent from Reviewable.io -->

2022-01-11 19:37 UTC, sumeerbhola approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1432)* status: 16 of 23 files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/manifest/version.go, line 275 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1432#-Mt9GrbI5q0GdYCRnmwx:-Mt9d7VE-mN3FDc5rT64:bfijfv2) ([raw file](https://github.com/cockroachdb/pebble/blob/e4fab746b6dfbbd5a6cc41eb4778c5137c47e866/internal/manifest/version.go#L275)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I might be misunderstanding, but if `!exclusiveEnd` the above for loop might've Nexted to a file with `Smallest.UserKey` > `end`, and we need the comparison to check for that.
</blockquote></details>

I see. Could you add a tiny example in a code comment -- it will make future readers very happy :)
___
*[internal/manifest/version_test.go, line 264 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1432#-Mt9IFjD3RZGVKsZfI9w:-Mt9dGKX6gydhQXe00LL:b-zcjvte) ([raw file](https://github.com/cockroachdb/pebble/blob/e4fab746b6dfbbd5a6cc41eb4778c5137c47e866/internal/manifest/version_test.go#L264)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Just checked and it does :+1: 
</blockquote></details>

Thanks


<!-- Sent from Reviewable.io -->

2022-01-13 02:40 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1432#-:-MtGIm7WDlyEBbUOHJV2:bz5mair)* status: 15 of 23 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/manifest/version.go, line 275 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1432#-Mt9GrbI5q0GdYCRnmwx:-MtGIjkTCU_LE2tZfJLh:b-896fja) ([raw file](https://github.com/cockroachdb/pebble/blob/e4fab746b6dfbbd5a6cc41eb4778c5137c47e866/internal/manifest/version.go#L275)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I see. Could you add a tiny example in a code comment -- it will make future readers very happy :)
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2022-01-13 02:41 UTC, merged