internal/keyspan: add FragmentIterator interface
cockroachdb/pebble pull request #1436
Opened 2022-01-05 17:09 UTC by jbowens

Introduce a keyspan.FragmentIterator interface that is a superset of the
InternalIterator interface, with additional methods relevant for dealing with
fragmented key spans. This removes the assumption from `keyspan.Seek{GE,LE}`
that a key span's internal value is always the end key.

When iteration over range key blocks is integrated, we may introduce a small
type that wraps a `*blockIter` and implements the `FragmentIterator` interface
and decodes end keys from internal values.

2022-01-05 17:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1436)
<!-- Reviewable:end -->

2022-01-05 21:58 UTC, nicktrav approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

The only observation I had was w.r.t. the cosmetics of altering some of the existing methods to return this new, more specific type, the name for which doesn't immediately convey the fact that it is also a `internalIterator`. It felt like there was a code smell here, but I couldn't convince myself that there was an alternative that was better. We're also only updating the API on un-exported methods and types, so this also seems fine.

> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1436#-:-MsgDjIoAuRvIo45Gzqd:b-ps5l6f)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

___
*[internal/keyspan/iter.go, line 11 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1436#-MsftrSl5DPXbUWKRQmU:-MsftrSl5DPXbUWKRQmV:bh80vp1) ([raw file](https://github.com/cockroachdb/pebble/blob/2d3c8422b0d9ece8c1d0aa842ad675e669b37edf/internal/keyspan/iter.go#L11)):*
> ```Go
> // FragmentIterator defines an interator interface over keyspan fragments. The
> // spans surfaced by a FragmentIterator must already be fragmented — that is if
> // two spans overlaps, they must have identical start and end bounds.
> ```

nit: s/overlaps/overlap/


<!-- Sent from Reviewable.io -->

2022-01-06 14:21 UTC, sumeerbhola requested changes
> Reviewed 22 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1436)* status: all files reviewed, 4 unresolved discussions (waiting on @jbowens)

___
*[error_iter.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1436#-MsjfLO0D5qvK9FfvJ5w:-MsjfLO0D5qvK9FfvJ5x:bkoh96o) ([raw file](https://github.com/cockroachdb/pebble/blob/06e42cfa82c0345e710fec737e9e859b44a6bc25/error_iter.go#L50)):*
> ```Go
> }
> 
> func (c *errorIter) Key() *InternalKey {
> ```

were these `Key`, `Value` methods left over from some old version of the `InternalIterator` interface?
___
*[internal/keyspan/iter.go, line 12 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1436#-Msjdb30-yFJlBGE_n9J:-Msjdb30-yFJlBGE_n9K:b-dxlzih) ([raw file](https://github.com/cockroachdb/pebble/blob/2d3c8422b0d9ece8c1d0aa842ad675e669b37edf/internal/keyspan/iter.go#L12)):*
> ```Go
> // spans surfaced by a FragmentIterator must already be fragmented — that is if
> // two spans overlaps, they must have identical start and end bounds.
> // Additionally, the key spans must be sorted by start key.
> ```

I don't understand this "Additionally" statement. Is this talking about an implementation detail or the interface contract?
If spans are of the form [a,b), [a,b), [c,d), [d,e), [d,e), won't the iterator contract (progressing forward in the key space) plus the fact that they don't partially overlap ensure that forward iteration will see them in increasing order of start key. Maybe that is what this comment is trying to say. Worth elaborating.
___
*[internal/keyspan/iter.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1436#-MsjklaJ-dTzEgogQjFh:-MsjklaJ-dTzEgogQjFi:bos2vhi) ([raw file](https://github.com/cockroachdb/pebble/blob/2d3c8422b0d9ece8c1d0aa842ad675e669b37edf/internal/keyspan/iter.go#L22)):*
> ```Go
> 	// Start returns the start key of the fragment at the current iterator
> 	// position.
> 	Start() *base.InternalKey
> ```

is `Start` the same as the `InternalKey` returned by the `InternalIterator` positioning method?
If yes, is there a reason we need it in the interface?
___
*[internal/keyspan/seek.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1436#-Msjisgt-3QFHxraS2Oa:-Msjisgt-3QFHxraS2Ob:b2lu7sh) ([raw file](https://github.com/cockroachdb/pebble/blob/2d3c8422b0d9ece8c1d0aa842ad675e669b37edf/internal/keyspan/seek.go#L28)):*
> ```Go
> 	// search key `e`. In that case SeekLT will land us on the span [a,e)
> 	// and we'll have to move forward.
> 	iterKey, _ := iter.SeekLT(key)
> ```

btw, is there any code now that uses a `FragmentIterator` as an `InternalIterator` without being aware that it is dealing with key spans? If not, I wonder whether we need to make `FragmentIterator` an extension of `InternalIterator` or we can clean it up to be specific to spans. That would remove this odd behavior of ignoring some of the return values.
Additionally, the `InternalIterator` was deliberately structured to reduce calls across the interface boundary, for performance reasons, by returning whatever is needed for each step or seek in the return values. I realize we don't expect many range keys so this is likely not performance sensitive code, but now we need to call End() and Current() when iterating in addition to the positioning method.


<!-- Sent from Reviewable.io -->

2022-01-07 16:19 UTC, jbowens reviewed
Yeah, I think the use of the `InternalIterator` interface for spans is something we should remove, but I'd prefer to defer that clean up for now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1436#-:-MspKJEu7_7LEgXuigX6:blwxtfy)* status: 18 of 23 files reviewed, 4 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[error_iter.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1436#-MsjfLO0D5qvK9FfvJ5w:-Msp5NdK85MV4TC5GD_0:bg11n7m) ([raw file](https://github.com/cockroachdb/pebble/blob/06e42cfa82c0345e710fec737e9e859b44a6bc25/error_iter.go#L50)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

were these `Key`, `Value` methods left over from some old version of the `InternalIterator` interface?
</blockquote></details>

Yeah, that's right. There are still a few other vestigial `Key()`, `Value()`, `Valid()` implementations in the code base, like on the sstable `blockIter`.
___
*[internal/keyspan/iter.go, line 12 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1436#-Msjdb30-yFJlBGE_n9J:-Msp7NOl0jmvnc4sTP6L:b-qbp3kg) ([raw file](https://github.com/cockroachdb/pebble/blob/2d3c8422b0d9ece8c1d0aa842ad675e669b37edf/internal/keyspan/iter.go#L12)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't understand this "Additionally" statement. Is this talking about an implementation detail or the interface contract?
If spans are of the form [a,b), [a,b), [c,d), [d,e), [d,e), won't the iterator contract (progressing forward in the key space) plus the fact that they don't partially overlap ensure that forward iteration will see them in increasing order of start key. Maybe that is what this comment is trying to say. Worth elaborating.

</blockquote></details>

Yeah, that's what it's try to say. Adjusted to explicitly describe the internal key ordering. wdyt?
___
*[internal/keyspan/iter.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1436#-MsjklaJ-dTzEgogQjFh:-MspCZWlCrR9RSWFX8ST:b-u3d3c3) ([raw file](https://github.com/cockroachdb/pebble/blob/2d3c8422b0d9ece8c1d0aa842ad675e669b37edf/internal/keyspan/iter.go#L22)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is `Start` the same as the `InternalKey` returned by the `InternalIterator` positioning method?
If yes, is there a reason we need it in the interface?
</blockquote></details>

Yeah, it is. It was used in the `rangekey.Iter`, but I replaced its use with an `iterKey` field.
___
*[internal/keyspan/seek.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1436#-Msjisgt-3QFHxraS2Oa:-MspBkerEX9SHY3qflsB:b-h7wbku) ([raw file](https://github.com/cockroachdb/pebble/blob/2d3c8422b0d9ece8c1d0aa842ad675e669b37edf/internal/keyspan/seek.go#L28)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

btw, is there any code now that uses a `FragmentIterator` as an `InternalIterator` without being aware that it is dealing with key spans? If not, I wonder whether we need to make `FragmentIterator` an extension of `InternalIterator` or we can clean it up to be specific to spans. That would remove this odd behavior of ignoring some of the return values.
Additionally, the `InternalIterator` was deliberately structured to reduce calls across the interface boundary, for performance reasons, by returning whatever is needed for each step or seek in the return values. I realize we don't expect many range keys so this is likely not performance sensitive code, but now we need to call End() and Current() when iterating in addition to the positioning method.
</blockquote></details>

Yeah, I think we should remove the awkwardness of shoeing key span iteration into the `InternalIterator` . I think it's possible to disentangle the two interfaces, but there are some range deletion uses of the `InternalIterator` that make it a bit of a lift. I added a TODO, if you're comfortable with deferring it for now.


<!-- Sent from Reviewable.io -->

2022-01-10 17:12 UTC, nicktrav reviewed
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1436)* status: all files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-01-10 17:27 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 23 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1436#-:-Mt40u1K0c6zRf1IC22f:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/keyspan/seek.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1436#-Msjisgt-3QFHxraS2Oa:-Mt40ryBBU71Wnw1dASD:bntvaa7) ([raw file](https://github.com/cockroachdb/pebble/blob/2d3c8422b0d9ece8c1d0aa842ad675e669b37edf/internal/keyspan/seek.go#L28)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, I think we should remove the awkwardness of shoeing key span iteration into the `InternalIterator` . I think it's possible to disentangle the two interfaces, but there are some range deletion uses of the `InternalIterator` that make it a bit of a lift. I added a TODO, if you're comfortable with deferring it for now.
</blockquote></details>

TODO is sufficient.
___
*[internal/keyspan/seek.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1436#-Mt407kB8lMN2L_pj0Vf:-Mt407kB8lMN2L_pj0Vg:bywzwuo) ([raw file](https://github.com/cockroachdb/pebble/blob/4247ff02a1ffb0ef549eaad5210428077ee40483/internal/keyspan/seek.go#L30)):*
> ```Go
> 	iterKey, _ := iter.SeekLT(key)
> 
> 	// Invariant: key < iter.Start().UserKey
> ```

there is no Start() any more


<!-- Sent from Reviewable.io -->

2022-01-11 17:35 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1436#-:-Mt9CTpdEoXez0r9LL1J:bz5mair)* status: 16 of 23 files reviewed, 4 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[internal/keyspan/seek.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1436#-Mt407kB8lMN2L_pj0Vf:-Mt9CDN55qucLmYsLY5n:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/4247ff02a1ffb0ef549eaad5210428077ee40483/internal/keyspan/seek.go#L30)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

there is no Start() any more
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-11 17:43 UTC, merged