internal/keyspan: implement SetBounds on Iter
cockroachdb/pebble pull request #1439
Opened 2022-01-05 21:30 UTC by jbowens

The `keyspan.Iter` implementation previously did not implement `SetBounds`,
because Pebble never needs to set bounds on range deletion iterators. When
range keys are fully integrated, propagating bounds to range-key fragment
iterators (specifically range-key levelIters) will be an important optimization
to avoid needing to load range-key blocks beyond the iterator bounds.

SetBounds will continue to be unused on `keyspan.Iter`s that expose range
deletion tombstones.

2022-01-05 21:30 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1439)
<!-- Reviewable:end -->

2022-01-05 21:48 UTC, nicktrav approved these changes
Nice. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1439#-:-MsgChSX8hG9MkfQIVA8:b-i2pyn4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens)



<!-- Sent from Reviewable.io -->

2022-01-06 14:32 UTC, sumeerbhola requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1439)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1439#-MsjmLA221cG80404WiY):*
I don't understand this.
- Why are range deletions different from range keys regarding bounds?
- We use `keyspan.Iter` now for in-memory range deletions like the ones in the memtable or in a batch. Those don't have anything to do with range-key blocks.
- If we don't want to load range-key blocks beyond the iterator bounds for a levelIter wouldn't that be based on the file bounds in the level?


<!-- Sent from Reviewable.io -->

2022-01-07 15:09 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1439)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @sumeerbhola)

___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1439#-MsjmLA221cG80404WiY):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't understand this.
- Why are range deletions different from range keys regarding bounds?
- We use `keyspan.Iter` now for in-memory range deletions like the ones in the memtable or in a batch. Those don't have anything to do with range-key blocks.
- If we don't want to load range-key blocks beyond the iterator bounds for a levelIter wouldn't that be based on the file bounds in the level?
</blockquote></details>

Sorry, this commit description was unclear. I added some additional explanation.

`keyspan.Iter` will also be used for memtable and batch range keys. These `keyspan.Iter`s will form the levels above the `levelIter`s in the merging iterator for range keys. To propagate bounds to the `levelIter`s, the merging iterator will `SetBounds` on its levels' iterators, including both `keyspan.Iter`s and the `levelIter`s.

Range keys are different from range deletions in that considering range deletions outside the iterator bounds can never result in returning keys outside the iterator bounds. Since range keys are interleaved in iteration, we need to ensure we never return range keys completely outside of the iterator bounds. Pushing those bounds checks down into the levels allows avoiding block loads, but requires that the memtable `keyspan.Iter`s also check bounds. [I think it also helps avoid unnecessary comparisons per key within the interleaving iterator during a scan when the memtable contains range keys outside the bounds, at the cost of these two upfront comparisons.]


<!-- Sent from Reviewable.io -->

2022-01-10 18:07 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1439#-:-Mt4A7xK5qN8OYY20wSl:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1439#-MsjmLA221cG80404WiY):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Sorry, this commit description was unclear. I added some additional explanation.

`keyspan.Iter` will also be used for memtable and batch range keys. These `keyspan.Iter`s will form the levels above the `levelIter`s in the merging iterator for range keys. To propagate bounds to the `levelIter`s, the merging iterator will `SetBounds` on its levels' iterators, including both `keyspan.Iter`s and the `levelIter`s.

Range keys are different from range deletions in that considering range deletions outside the iterator bounds can never result in returning keys outside the iterator bounds. Since range keys are interleaved in iteration, we need to ensure we never return range keys completely outside of the iterator bounds. Pushing those bounds checks down into the levels allows avoiding block loads, but requires that the memtable `keyspan.Iter`s also check bounds. [I think it also helps avoid unnecessary comparisons per key within the interleaving iterator during a scan when the memtable contains range keys outside the bounds, at the cost of these two upfront comparisons.]
</blockquote></details>

Thanks for the explanation.


<!-- Sent from Reviewable.io -->

2022-01-10 19:36 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1439#-:-Mt4UTHh-8-oPua4rLlN:bz5mair)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens)



<!-- Sent from Reviewable.io -->

2022-01-10 19:36 UTC, merged