sstable: return err from `(BlockPropertyCollector).FinishTable`
cockroachdb/pebble pull request #1447
Opened 2022-01-10 20:19 UTC by nicktrav

Currently, when finalizing the properties for a table, any error
returned by the `BlockPropertyCollector` is silently ignored.

Return any error returned by the collector.

2022-01-10 20:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1447)
<!-- Reviewable:end -->

2022-01-10 21:15 UTC, bananabrick approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1447)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbowens and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-01-11 15:58 UTC, sumeerbhola requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1447)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens and @nicktrav)

___
*[sstable/writer.go, line 530 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1447#-Mt8pvqKCyQfdaFlRSwK:-Mt8pvqKCyQfdaFlRSwL:b5whi8t) ([raw file](https://github.com/cockroachdb/pebble/blob/13974f633a3e50a026a1f75d33eae32f2972bf50/sstable/writer.go#L530)):*
> ```Go
> 		scratch := w.blockPropsEncoder.getScratchForProp()
> 		if scratch, err = w.blockPropCollectors[i].FinishDataBlock(scratch); err != nil {
> 			return BlockHandleWithProperties{}, err
> ```

thanks for catching this!
We lack testing of the error paths.

Can you add a small non-datadriven test that would fail before this change. 


<!-- Sent from Reviewable.io -->

2022-01-11 18:05 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1447)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

___
*[sstable/writer.go, line 530 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1447#-Mt8pvqKCyQfdaFlRSwK:-Mt9ImaX6ZGGn6XC7uwH:bmdu4m) ([raw file](https://github.com/cockroachdb/pebble/blob/13974f633a3e50a026a1f75d33eae32f2972bf50/sstable/writer.go#L530)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

thanks for catching this!
We lack testing of the error paths.

Can you add a small non-datadriven test that would fail before this change. 
</blockquote></details>

Good call. Added a unit-test for the various error cases that a block-property collector can see. Confirmed it was failing prior to this fix.


<!-- Sent from Reviewable.io -->

2022-01-11 18:11 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1447#-:-Mt9KW0u3xZTgdx4P8Aj:bg7igkv)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/writer_test.go, line 268 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1447#-Mt9KUYm9Nc9OLfH1PlO:-Mt9KUYm9Nc9OLfH1PlP:b-j6rd9r) ([raw file](https://github.com/cockroachdb/pebble/blob/162f350241aac3911392c809cf425cce0c47d704/sstable/writer_test.go#L268)):*
> ```Go
> 	errSiteFinishIndex
> 	errSiteFinishTable
> )
> ```

nice test!


<!-- Sent from Reviewable.io -->

2022-01-11 18:26 UTC, nicktrav commented
TFTR!

2022-01-11 18:26 UTC, merged