internal/rangekey: add merging, fragmenting iterator
cockroachdb/pebble pull request #1451
Opened 2022-01-13 23:48 UTC by jbowens

Add a rangekey.MergingIter type that implements the keyspan.FragmentIterator
interface, merging and fragmenting keyspan.FragmentIterators across many
levels. MergingIter uses a heap to consider the spans between adjacent, unique
user keys across levels.

2022-01-13 23:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1451)
<!-- Reviewable:end -->

2022-01-14 21:33 UTC, nicktrav reviewed
Got through everything except the merging iter part. So far so good.

Flushing some comments.

> Reviewed 7 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451#-:-MtPV9V52KMM5jf3l1wl:b-8nglxh)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/bound_iter.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtPFd174QazfinPFoSZ:-MtPFd174QazfinPFoS_:b-1ugbca) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/bound_iter.go#L90)):*
> ```Go
> 	// indicated by boundKind. All of the underlying iterators fragments with
> 	// the bounds [start, end) are contained within the fragments field.
> 	start     []byte
> ```

nit: meta comment about these structs where we maintain byte slices. Would it be worth some brief commentary around the lifetimes? i.e. are these stable, etc.



_Code quote:_
```Go
	start     []byte
	end       []byte
```
___
*[internal/rangekey/bound_iter.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtPKDzm-v7kLz5yRv27:-MtPKDzm-v7kLz5yRv28:b-81lzbl) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/bound_iter.go#L164)):*
> ```Go
> 		// current iterator position.
> 		//
> 		//    [c, d)   [c, d)   [e, f)   [e, f)   [e, f)   [g, h)   [g, h)
> ```

nit: Are you able to update this to indicate where `i.iter` should end up? From the description it sounds like the first `[g, h)` fragment. i.e. we call `Next()` `len(i.fragments) + 1 == 3 + 1 == 4` times? Maybe like a before / after type thing.

Same for the comment in `prev()`, below.
___
*[internal/rangekey/testdata/fragment_bound_iterator, line 37 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtPNdSn3FwFsPXS3k5X:-MtPNdSn3FwFsPXS3k5Y:blb0lvg) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/testdata/fragment_bound_iterator#L37)):*
> ```
> seek-ge a
> seek-ge b
> seek-ge c
> ```

I'm a little confused by this one given that the fragments for this span are both `[a, c)`. If we're seeking _greater than or equal to_ `c` but `c` is an exclusive endpoint, how is it that we can end up still within the span `[a, c)`? No doubt this is just a gap in my understanding.
___
*[internal/rangekey/testdata/fragment_bound_iterator, line 45 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtPPHnU6yuB4-QgIr99:-MtPPHnV5zFtbIG9quE_:bpza65p) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/testdata/fragment_bound_iterator#L45)):*
> ```
> ----
> fragment-start a [a-c#6, a-c#3]
> fragment-end   c [a-c#3, a-c#6]
> ```

When we're doing this forward iteration and we have this `cmp(end, key) >= 0` case, we do this reverse iteration over the fragments. I didn't quite get the significance of returning the fragments in reverse order. Is that purely a performance thing (i.e. we're iterating from the last fragment, so it's cheaper to collect fragments as we iterate backwards)?

I'm still reading the merging iter code, so maybe this will become clear eventually.


<!-- Sent from Reviewable.io -->

2022-01-14 23:49 UTC, nicktrav reviewed
Very nice! Took a look at the merging iter and it LGTM.

I'd like to take a second pass early next week, after I digest this a little more.

> Reviewed 3 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451#-:-MtPzOAXDZnadW3C1Gx_:b-q1qrjp)* status: all files reviewed, 9 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/merging_iter.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtPh-9l3N_LrPRSq54-:-MtPh-9l3N_LrPRSq540:bh19tkg) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L20)):*
> ```Go
> // by adjusting MergingIter to return sets of overlapping fragments rather than
> // individual fragments. MergingIter already knows the full set of overlapping
> // fragments, so we mind as well.
> ```

nit: s/mind/may/ ?
___
*[internal/rangekey/merging_iter.go, line 452 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtPtwUS29Og_VJ_0UyC:-MtPtwUS29Og_VJ_0UyD:b-v41a26) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L452)):*
> ```Go
> 		// L2:          [c, e)
> 		// If we're positioned at L1's end(c) end boundary, we want to advance
> 		// to accumulate L1's [c, d) fragment as well as L2's [c, e) fragment.
> ```

nit: instead of "accumulate", can we say something like "... advance to the first key `>c`"?. Accumulate made it sound like we add / store something, whereas we're consuming from the heap until the heap key is `>c`.

Same for the equivalent comment in `findPrevFragmentSet()`.



_Code quote:_
```Go
		// If we're positioned at L1's end(c) end boundary, we want to advance
		// to accumulate L1's [c, d) fragment as well as L2's [c, e) fragment.
```
___
*[internal/rangekey/merging_iter.go, line 462 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtPqr9I9f3hJ7khkbGd:-MtPqr9I9f3hJ7khkbGe:b-s8b9kt) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L462)):*
> ```Go
> 
> 		// The current entry at the top of the heap is the first key > m.start.
> 		// It's the end bound for the set of fragments we'll return to the user.
> ```

nit: can we clarify as "It becomes the end bound for the set of fragments we will return to the user."?
___
*[internal/rangekey/merging_iter.go, line 466 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtPwWbG79D9EpIaIQbg:-MtPwWbG79D9EpIaIQbh:b-pkaj24) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L466)):*
> ```Go
> 		m.end = m.heapRoot().key
> 
> 		// Each level within m.levels has a set of fragments that overlap the
> ```

nit: should the comment here read "each level ... _may_ have a set of fragments"?

Thinking of the case:

```
// L1:   [a, c) [c, d)
// L2:                             [k, l)
```

If we're currently at L1's `end(c)`, then wouldn't L2's heap key be `start(k)`? In `synthesizeFragments()` it looks like we'd (correctly) ignore L2, as it's a start key, and therefore non-overlapping.

Same nitpick for the equivalent comment in `findPrevFragmentSet()`
___
*[internal/rangekey/merging_iter.go, line 506 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtPtiJ6CvquO_oLJhU5:-MtPtiJ7-94kzfSMHxwS:b-r6gm5c) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L506)):*
> ```Go
> 
> 		// The current entry at the top of the heap is the first key < m.end.
> 		// It's the start bound for the set of fragments we'll return to the
> ```

nit: "It becomes ... " (per suggestion above).


<!-- Sent from Reviewable.io -->

2022-01-18 16:40 UTC, sumeerbhola requested changes
Nice to see this big step!

Flushing as I read. I'll need to make multiple passes -- this is the first pass over everything other than MergingIter.

> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451#-:-Mti2_Al6n4eM2B66sq0:bn0xefv)* status: all files reviewed, 13 unresolved discussions (waiting on @jbowens)

___
*[internal/rangekey/bound_iter.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mthyh4x0A-GInqnzWN7:-Mthyh4x0A-GInqnzWN8:bg1hh7x) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/bound_iter.go#L31)):*
> ```Go
> type boundKey struct {
> 	kind boundKind
> 	key  []byte
> ```

is `key` equal to fragments[i].Start.UserKey for all i?
___
*[internal/rangekey/bound_iter.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mthyzyb8Ow9vHQbPGe4:-Mthyzyb8Ow9vHQbPGe5:bfw17oe) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/bound_iter.go#L34)):*
> ```Go
> 	// fragments holds a set of fragments with this bound. The ordering of
> 	// fragments is unspecified and depends on internal iteration implementation
> 	// details.
> ```

What invariants do the `fragments` need to satisfy wrt each other?
___
*[internal/rangekey/bound_iter.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mti074e383eokY6OG2S:-Mti074e383eokY6OG2T:b-n4dg1x) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/bound_iter.go#L84)):*
> ```Go
> 	// iter holds the underlying fragment iterator. iterSpan is always set to
> 	// the span at iter's current position.
> 	iter     keyspan.FragmentIterator
> ```

Does the `FragmentIterator` provide any stability of the slices it has returned previously after it steps/seeks? I guess the `blockIter` (because of restarts=1) and `keyspan.Iter` do, but doesn't look like we document this in the interface.
I assume we need that property to avoid making copies here. I'm murky on how that guarantee will work when we step across files in a level since if the callee makes a copy (using a shared buffer) it needs to know when it can throw away that copy.
___
*[internal/rangekey/bound_iter.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mti1c1_E17Y2IW6CYKe:-Mti1c1_E17Y2IW6CYKf:bvn4kb5) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/bound_iter.go#L103)):*
> ```Go
> func (i *fragmentBoundIterator) seekGE(cmp base.Compare, key []byte) boundKey {
> 	// Search for the span with the largest Start < key.
> 	_, _ = i.iter.SeekLT(key)
> ```

this was a surprise. I think we should document what seekGE means for `fragmentBoundIterator` and why we care about the seeing only the end bound.


<!-- Sent from Reviewable.io -->

2022-01-18 19:18 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451)* status: all files reviewed, 22 unresolved discussions (waiting on @jbowens)

___
*[internal/rangekey/merging_iter.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtiSS4h4mjmdXaddE8G:-MtiSS4h4mjmdXaddE8H:bwlxex5) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L129)):*
> ```Go
> 		heap: mergingIterHeap{cmp: cmp},
> 	}
> 	if cap(levels) < len(iters) {
> ```

Is this logic based on an invariant that the cap of levels and items is the same?
___
*[internal/rangekey/merging_iter.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtiSclD1rksaJufi0va:-MtiSclD1rksaJufi0vb:blvmwt5) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L149)):*
> ```Go
> 
> // End returns the end key of the fragment at the current iterator position.
> func (m *MergingIter) End() []byte {
> ```

should we require that this should only be called if `Valid` returns true?
Same question for `Current()`.
___
*[internal/rangekey/merging_iter.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mti4qz3C4343l209T8P:-Mti4qz41vdH4Eb2OuSO:b-q9x7ky) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L191)):*
> ```Go
> 	// TODO(jackson): Evaluate whether there's an implementation of SeekLT
> 	// independent of SeekGE that is more efficient. It's tricky, because the
> 	// fragment we should return might straddle `key` itself.
> ```

is this similar to the issue discussed in https://github.com/cockroachdb/pebble/blob/628db895569d460239b44076f2e819dd79983182/internal/keyspan/seek.go#L81-L93?
___
*[internal/rangekey/merging_iter.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtiTiES94y9sjx0EPa1:-MtiTiES94y9sjx0EPa2:bhbqinz) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L232)):*
> ```Go
> 	// If we're currently at a valid iterator position, we might only need to
> 	// move to the next fragment within our existing set of fragments.
> 	if !m.curr.Empty() {
> ```

if `m.dir` was already `+1` does `m.curr.Empty()` mean that the iterator is already exhausted in the forward direction?
I am trying to understand the cases underlying not being at a "valid iterator position".
___
*[internal/rangekey/merging_iter.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtiWRBF5rRCPxwZE5MQ:-MtiWRBF5rRCPxwZE5MR:b-ice4wr) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L358)):*
> ```Go
> 	// Reversing the heap should not change any of the mergingIterLevel's
> 	// fragments or the current merging iterator [m.start, m.end) bounds. It
> 	// should only update the child iterators' heap keys to:
> ```

I am finding this a bit confusing.
We don't want to actually change the MergingIter position. It is just preparing it for forward iteration, yes?
All mergingIterLevels that are contributing to fragments are at the position they should be. The only mergingIterLevels not contributing to fragments are either exhausted (in the reverse direction) or must have a span that completely precedes curr. Those are exactly the ones that we have need to step forward once.
If we tracked which levels were contributing to curr (say using a bool) we wouldn't even need a key comparison to switch.

I see that what you have here is different in that we are stepping everything forward because the boundKey needs to move from the start to the end. Is that the primary reason why `boundKind` exists?
___
*[internal/rangekey/merging_iter.go, line 445 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mtia4L42ZnXNRZ-O2d5:-Mtia4L42ZnXNRZ-O2d6:btkxm1i) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L445)):*
> ```Go
> 	for m.heap.len() > 0 && m.err == nil {
> 		// Initialize the next span's start bound.
> 		m.start = m.heapRoot().key
> ```

It looks like a step like Next() consumes everything it needs to from the heap to construct its output, so the heap is already at what the next step needs to consume. Is that correct?
___
*[internal/rangekey/merging_iter.go, line 446 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mtiaqr72jn_0aqQU2L9:-Mtiaqr72jn_0aqQU2LA:btpn4mv) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L446)):*
> ```Go
> 		// Initialize the next span's start bound.
> 		m.start = m.heapRoot().key
> ```

can this be `boundKindFragmentEnd`?
If yes, shouldn't we completely ignore this. I think I see a glimmer of why not, but this could use an example with overlapping spans.
___
*[internal/rangekey/merging_iter.go, line 677 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mti5pbSBY4fxr91gVeG:-Mti5pbSBY4fxr91gVeH:b-6685t8) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L677)):*
> ```Go
> // mergingIterHeap is copied from mergingIterHeap defined in the root pebble
> // package for use with point keys.
> ```

I assume we are doing this to avoid the interface overhead imposed by using `container/heap`. Not that using it would have saved much code.
___
*[internal/rangekey/merging_iter.go, line 689 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtiZDyu2vbwQzr7CiSV:-MtiZDyu2vbwQzr7CiSW:bfctqr2) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L689)):*
> ```Go
> 
> func (h *mergingIterHeap) less(i, j int) bool {
> 	ik, jk := h.items[i].key, h.items[j].key
> ```

looks like the comparison only uses the userkey, and not the boundKind.
Worth a code comment explaining why the boundKind does not matter


<!-- Sent from Reviewable.io -->

2022-01-19 19:46 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451)* status: 8 of 10 files reviewed, 16 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[internal/rangekey/bound_iter.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mthyh4x0A-GInqnzWN7:-MtnC7gX1po-_E1aMmO5:b7yo58f) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/bound_iter.go#L31)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is `key` equal to fragments[i].Start.UserKey for all i?
</blockquote></details>

`key` is either
1. equal to fragments[i].Start.UserKey for all i
OR
2. equal to fragments[i].End for all i

Updated the comment to describe this.
___
*[internal/rangekey/bound_iter.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mthyzyb8Ow9vHQbPGe4:-MtnD5rq9nRT64FgoRMJ:blrhn5g) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/bound_iter.go#L34)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

What invariants do the `fragments` need to satisfy wrt each other?
</blockquote></details>

They all need to have identical user key bounds. Updated to describe this.
___
*[internal/rangekey/bound_iter.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mti074e383eokY6OG2S:-MtnDIQh7X7RJYJYgSML:bt3fv4t) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/bound_iter.go#L84)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Does the `FragmentIterator` provide any stability of the slices it has returned previously after it steps/seeks? I guess the `blockIter` (because of restarts=1) and `keyspan.Iter` do, but doesn't look like we document this in the interface.
I assume we need that property to avoid making copies here. I'm murky on how that guarantee will work when we step across files in a level since if the callee makes a copy (using a shared buffer) it needs to know when it can throw away that copy.
</blockquote></details>

Yeah, there's a TODO to document this on the top of merging_iter.go. Currently, we're relying on the total key stability provided by `keyspan.Iter`.

Later, when stepping through files, `fragmentBoundIterator` will only assure stability between `boundKindTableStart` and `boundKindTableEnd` bounds. The merging iterator will be able to step a level's iterator onto an adjacent `boundKindTable{Start,End}` key without invalidating the level's current `heapKey` spans.

Implementing the above within `fragmentBoundIterator` requires coordination with the level iterator. I've been thinking the level iterator will implement an additional, optional interface alongside `FragmentIterator` that allows it to indicate whether or not the current iterator position represents a table start key or a table end key. The final `keyspan.FragmentIterator` interface after we disentangle it from `InternalIterator` will probably need to be adjusted too, to accommodate stepping onto these non-fragment iterator positions.
___
*[internal/rangekey/bound_iter.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtPFd174QazfinPFoSZ:-MtnGD5v1K6KLwFgzZwn:b-kwktpx) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/bound_iter.go#L90)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: meta comment about these structs where we maintain byte slices. Would it be worth some brief commentary around the lifetimes? i.e. are these stable, etc.
</blockquote></details>

Yeah, it's definitely worth it. I'm going to defer it until later, because currently the lifetimes are infinite, which will not be the case once we introduce iterators over the files of a level. (see the above reply to Sumeer's comment)
___
*[internal/rangekey/bound_iter.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mti1c1_E17Y2IW6CYKe:-MtnM2U_6wnSCLNlU-lH:b-q1bj08) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/bound_iter.go#L103)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this was a surprise. I think we should document what seekGE means for `fragmentBoundIterator` and why we care about the seeing only the end bound.
</blockquote></details>

Added a comment here, above `seekGE` and also some additional motivational commentary above `fragmentBoundIterator`. 
___
*[internal/rangekey/bound_iter.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtPKDzm-v7kLz5yRv27:-MtnNA26DqggkvqJk4N6:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/bound_iter.go#L164)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: Are you able to update this to indicate where `i.iter` should end up? From the description it sounds like the first `[g, h)` fragment. i.e. we call `Next()` `len(i.fragments) + 1 == 3 + 1 == 4` times? Maybe like a before / after type thing.

Same for the comment in `prev()`, below.
</blockquote></details>

Done.
___
*[internal/rangekey/merging_iter.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtiSS4h4mjmdXaddE8G:-MtnN_KC4zj85-RmXsY4:b-8bn10t) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L129)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this logic based on an invariant that the cap of levels and items is the same?
</blockquote></details>

Yeah, just for performance, not correctness. Documented.
___
*[internal/rangekey/merging_iter.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtiSclD1rksaJufi0va:-MtnP5gu5f-KgGs4hkD9:b-rfnkoh) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L149)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should we require that this should only be called if `Valid` returns true?
Same question for `Current()`.
</blockquote></details>

Added TODOs. Currently `rangekey.Iter` relies on calling `(keyspan.FragmentIterator).Current()` and checking `(keyspan.Span).IsEmpty()`. During the followup that adds a direct dependency from `rangekey.Iter` on the `MergingIter`, we can adjust that.
___
*[internal/rangekey/merging_iter.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mti4qz3C4343l209T8P:-Mtnc-aw196JfkigjDkE:b-uuahi1) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L191)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this similar to the issue discussed in https://github.com/cockroachdb/pebble/blob/628db895569d460239b44076f2e819dd79983182/internal/keyspan/seek.go#L81-L93?
</blockquote></details>

It's similar but even trickier because of the additional fragmentation that the merging iterator needs to do. I added an example here.
___
*[internal/rangekey/merging_iter.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtiTiES94y9sjx0EPa1:-MtnrNQs4mwlYZaBz3Sx:bqql639) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L232)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

if `m.dir` was already `+1` does `m.curr.Empty()` mean that the iterator is already exhausted in the forward direction?
I am trying to understand the cases underlying not being at a "valid iterator position".
</blockquote [...]

2022-01-19 20:03 UTC, nicktrav reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451)* status: all files reviewed, 13 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-01-19 22:32 UTC, nicktrav approved these changes
Did another pass.

I didn't review the heap code, as you mentioned that was lifted from elsewhere.

 Just nits remain. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451#-:-MtoSjO71lmcS7uQPl9F:bmrkxof)* status: all files reviewed, 16 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/merging_iter.go, line 471 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtoLWB863DiX8OTXqm0:-MtoLWB863DiX8OTXqm1:b-ar6i9i) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L471)):*
> ```Go
> 
> 	for m.heap.len() > 0 && m.err == nil {
> 		// Initialize the next span's start bound. Next leaves the heap in a
> ```

We also call this from `SeekGE` and `First`. I assume the comment also applies here as we invalidate the heap, reposition all iters, then init the heap? Wasn't sure if this was an intentional omission, but might be good to at least mention the expectation that we can arrive here from `SeekGE` and `First`.

Ditto for `findPrevFragmentSet` with `Prev` and `Last`.



_Code quote:_
```Go
Next leaves the heap
```
___
*[internal/rangekey/merging_iter.go, line 476 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtoMLKwEJvy-kGViWE6:-MtoMLKx7H95SCkpqqQm:booqhvb) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L476)):*
> `either`

Is there another case to consider here? Or is `either` unintentional?
___
*[internal/rangekey/merging_iter.go, line 477 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtoMcFJ4FVqSPGXNURl:-MtoMcFJ4FVqSPGXNURm:b-xvmhz1) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L477)):*
> `still be may`

Typo.
___
*[internal/rangekey/merging_iter.go, line 490 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtoNCQZ3EvpaadDTIsq:-MtoNCQZ3EvpaadDTIsr:b9ytk4a) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L490)):*
> ```Go
> 		//                   l-m   #2
> 		//
> 		// When advancing to l-m#2, we must set m.start to 'l', which originated
> ```

nit: s/must/may/? We aren't necessarily on a start key that shares an end key at the same user key?
___
*[internal/rangekey/merging_iter.go, line 491 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtoN1tE5zGNDOVxtVRx:-MtoN1tE5zGNDOVxtVRy:b3d26b1) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L491)):*
> ```Go
> 		//
> 		// When advancing to l-m#2, we must set m.start to 'l', which originated
> 		// from [a,l)#1's end boundary.
> ```

nit: was expecting a short following sentence, e.g. "This is safe as the user keys are the same and we are dropping the bound kind (i.e. start or end)."
___
*[internal/rangekey/merging_iter.go, line 573 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtoQQVFAnNh-wMeWOTx:-MtoQQVFAnNh-wMeWOTy:bivl377) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L573)):*
> ```Go
> 		// It must become the start bound for the set of fragments we will
> 		// return to the user. In the above example, the root of the heap is
> 		// L1's end(d).
> ```

If we're positioned at `start(c)` and moving backwards, wouldn't we want to end up at `start(a)`?
___
*[internal/rangekey/merging_iter.go, line 603 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtoRprR-443RRgToFjF:-MtoRprR-443RRgToFjG:bazsrdm) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L603)):*
> ```Go
> 	}
> 
> 	// synthesizeFragments is called by find{Next,Prev}FragmentSet to populate
> ```

Would be nice if there were a couple of examples here (perhaps in keeping with the examples in `find[Next/Prev]FragmentSet`) to illustrate how adding fragments for levels with end bound kinds in forward iteration mode (and fragments for levels with start bound kinds in reverse iteration mode) works in principle.
___
*[internal/rangekey/merging_iter_test.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mto3CsR6_TeeY-fZIQz:-Mto3CsR6_TeeY-fZIR-:b-5pb7hp) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter_test.go#L121)):*
> ```Go
> //
> // It does this by producing 1-10 levels of well-formed fragments. Generated
> // fragments may overlap other levels arbitrary, but within their level
> ```

nit: s/arbitrary/arbitrarily/


<!-- Sent from Reviewable.io -->

2022-01-20 18:28 UTC, sumeerbhola requested changes
This is mostly looking good

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451#-:-MtsjBwb8ZCrRJNdw6Ob:bov1anl)* status: all files reviewed, 21 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/bound_iter.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mti074e383eokY6OG2S:-MtsL-9xBkdEkEPbOp9Y:bx9uwp6) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/bound_iter.go#L84)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, there's a TODO to document this on the top of merging_iter.go. Currently, we're relying on the total key stability provided by `keyspan.Iter`.

Later, when stepping through files, `fragmentBoundIterator` will only assure stability between `boundKindTableStart` and `boundKindTableEnd` bounds. The merging iterator will be able to step a level's iterator onto an adjacent `boundKindTable{Start,End}` key without invalidating the level's current `heapKey` spans.

Implementing the above within `fragmentBoundIterator` requires coordination with the level iterator. I've been thinking the level iterator will implement an additional, optional interface alongside `FragmentIterator` that allows it to indicate whether or not the current iterator position represents a table start key or a table end key. The final `keyspan.FragmentIterator` interface after we disentangle it from `InternalIterator` will probably need to be adjusted too, to accommodate stepping onto these non-fragment iterator positions.
</blockquote></details>

Ack. Sounds reasonable.
___
*[internal/rangekey/merging_iter.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mti4qz3C4343l209T8P:-MtsPndqADVMy-9i9vh2:b-k73z76) ([raw file](https://github.com/cockroachdb/pebble/blob/89e993050ae07d591029f6e93b82613b6906030a/internal/rangekey/merging_iter.go#L191)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

It's similar but even trickier because of the additional fragmentation that the merging iterator needs to do. I added an example here.
</blockquote></details>

thanks
___
*[internal/rangekey/merging_iter.go, line 198 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtsOyIv2zIrxw-oNKDS:-MtsOyIwA2Dv6gB8WgYq:b-avvq0l) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L198)):*
> ```Go
> 	// Consider the scenario:
> 	//       a----------l      #1
> 	//         b-----------m   #2
> ```

are `#1` and `#2` seqnums? If yes, shouldn't the ordering below be adjusted since `[b,l)#2` should be before `[b,l)#1`.
___
*[internal/rangekey/merging_iter.go, line 250 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtsQK_BEKjHhew-c6Rd:-MtsQK_BEKjHhew-c6Re:b-5cklb3) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L250)):*
> ```Go
> 
> 	// If the iterator is not already exhausted, we might only need to move to
> 	// the next fragment within our existing set of fragments.
> ```

I think it's worth noting in a code comment here that m.dir could be -1 and will stay -1. I realize there is a later comment "We only switch the heap direction in the case..." that says this, but it is easy to overlook that since it doesn't explicitly point out this lag in the change to the `dir` value.

Same for `Prev()`.
___
*[internal/rangekey/merging_iter.go, line 474 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtsS92x4-bwDF3p7G4t:-MtsS92x4-bwDF3p7G4u:b-nn0bvo) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L474)):*
> ```Go
> 		// state such that the root is the smallest bound key equal to the
> 		// returned span's end key, so the heap is already positioned at the
> 		// next span's start key.
> ```

It doesn't have to be the next span's start key if there isn't any remaining overlapping span, yes?
___
*[internal/rangekey/merging_iter.go, line 500 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtsW9QeAMFCc1u52d_s:-MtsW9QeAMFCc1u52d_t:bp91id8) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L500)):*
> ```Go
> 		// If we're positioned at L1's end(c) end boundary, we want to advance
> 		// to the first bound > c.
> 		m.nextEntry()
> ```

Say we had
L1: [a, c) [x, y)
L2: [f, g)
and m.start used the end boundary of c.
m.nextEntry will step L1 to start boundary of [x,y) and the heap top will be the start boundary of [f, g). I don't see why it is correct to use c as m.start.
We should be setting m.start to the end boundary of c only if after doing nextEntry we still have some heap elements positioned on an end boundary. If there are none we don't have any remaining overlap.
What am I missing?
___
*[internal/rangekey/merging_iter.go, line 502 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtsTwH8-phrPktpL27o:-MtsTwH9AqKC2Lz0pSJb:b1fg38t) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L502)):*
> ```Go
> 		m.nextEntry()
> 		for len(m.heap.items) > 0 && m.err == nil && m.cmp(m.heapRoot().key, m.start) == 0 {
> 			m.nextEntry()
> ```

looks like we are skipping these under the assumption that these are all end boundaries with the end userkey equal to m.start. I don't fully understand:
- what it m.start was an end boundary, but one of these is a start boundary?
- what if m.start was a start boundary.

I think I see why this works -- we will continue to see all the fragments for each heap element until when we get to the end boundary, and the first end boundary that exceeds m.start or the first start boundary that exceeds m.start will allow us to figure out where the next output fragment should end. At that point all the relevant heap elements have the fragments we need. Exposing all the fragments on both boundaries is what allows for this "lazy gathering" of fragments after the bounds of the next output fragment are determined.

I think we need a higher level comment with an example somewhere that explains the basic idea on how this fragmentation approach works. Currently one has to piece this together using various code level comments.


<!-- Sent from Reviewable.io -->

2022-01-21 22:18 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451)* status: 8 of 10 files reviewed, 20 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[internal/rangekey/merging_iter.go, line 198 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtsOyIv2zIrxw-oNKDS:-Mty2l4iDkOl7aeBVv4z:b-lel219) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L198)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

are `#1` and `#2` seqnums? If yes, shouldn't the ordering below be adjusted since `[b,l)#2` should be before `[b,l)#1`.
</blockquote></details>

Oops, thanks, fixed.
___
*[internal/rangekey/merging_iter.go, line 250 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtsQK_BEKjHhew-c6Rd:-Mty4Q1X54BiSHUuyn50:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L250)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think it's worth noting in a code comment here that m.dir could be -1 and will stay -1. I realize there is a later comment "We only switch the heap direction in the case..." that says this, but it is easy to overlook that since it doesn't explicitly point out this lag in the change to the `dir` value.

Same for `Prev()`.
</blockquote></details>

Done.
___
*[internal/rangekey/merging_iter.go, line 474 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtsS92x4-bwDF3p7G4t:-Mty5HFi7LYzT2SBI5pD:b7tjg2) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L474)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It doesn't have to be the next span's start key if there isn't any remaining overlapping span, yes?
</blockquote></details>

This is referring to the next _merged_ span. I'll add "merged" here to clarify.
___
*[internal/rangekey/merging_iter.go, line 490 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtoNCQZ3EvpaadDTIsq:-Mty7roY9gSZfC7-V4ny:b-n4irr) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L490)):*
> We aren't necessarily on a start key that shares an end key at the same user key?

I don't follow?
___
*[internal/rangekey/merging_iter.go, line 491 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtoN1tE5zGNDOVxtVRx:-Mty8E1nD6P064uKuOVf:b-n6t5ma) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L491)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: was expecting a short following sentence, e.g. "This is safe as the user keys are the same and we are dropping the bound kind (i.e. start or end)."
</blockquote></details>

hmm, this is trying to establish that it's not just safe to use an end boundary as a start boundary of a merged bound, but mandatory. all the above is serves as the example demonstrating that necessity. should I add something to the beginning of the comment to make that more clear?
___
*[internal/rangekey/merging_iter.go, line 500 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtsW9QeAMFCc1u52d_s:-Mty9cyj7O88yNX5DJPU:b-g5pi62) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L500)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Say we had
L1: [a, c) [x, y)
L2: [f, g)
and m.start used the end boundary of c.
m.nextEntry will step L1 to start boundary of [x,y) and the heap top will be the start boundary of [f, g). I don't see why it is correct to use c as m.start.
We should be setting m.start to the end boundary of c only if after doing nextEntry we still have some heap elements positioned on an end boundary. If there are none we don't have any remaining overlap.
What am I missing?
</blockquote></details>

That's exactly right. Each iteration of the outer loop considers a new, merged span (eg, [c,f), [f,g), [g, x), [x, y)...). After positioning all the levels appropriately, `synthesizeFragments` examines which of the heap elements are positioned on an end boundary, collecting fragments from any that are. If there are none, we advance to the next merged span. This was alluded to above the for loop, but I expanded that comment.

----

This discussion also gets at a potential optimization that I've been considering... Maybe the `rangekey.Iter` should be adapted to support returning spans that have no range keys set. Imagine you have a dense point keyspace a-z and a single range key covering the span `[y, z)`.  If you have an iterator without any bounds and perform a `SeekGE('b')`, the point iterator might land on an sstable with bounds like `b-ba`,  but the rangekey iterator will need to scan all the sstables' `fileMetadata` until it finds the file containing `[y, z)` and opens it.

Alternatively, the rangekey iterator could return a span `[b, y)` with no range keys, reflecting that it seeked and found that no range keys existed all the way up to `y`, all without reading any blocks. If the point iterator is eventually Next'd to `y`, the interleaving iterator can handle Next-ing the range key iterator onto the `[y,z)` range key's sstable and range key.
___
*[internal/rangekey/merging_iter.go, line 502 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtsTwH8-phrPktpL27o:-Mtyhy3nAZcNisovbPBv:b-36is58) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L502)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

looks like we are skipping these under the assumption that these are all end boundaries with the end userkey equal to m.start. I don't fully understand:
- what it m.start was an end boundary, but one of these is a start boundary?
- what if m.start was a start boundary.

I think I see why this works -- we will continue to see all the fragments for each heap element until when we get to the end boundary, and the first end boundary that exceeds m.start or the first start boundary that exceeds m.start will allow us to figure out where the next output fragment should end. At that point all the relevant heap elements have the fragments we need. Exposing all the fragments on both boundaries is what allows for this "lazy gathering" of fragments after the bounds of the next output fragment are determined.

I think we need a higher level comment with an example somewhere that explains the basic idea on how this fragmentation approach works. Currently one has to piece this together using various code level comments.
</blockquote></details>

Added a higher-level comment to the top of `MergingIter`. 


<!-- Sent from Reviewable.io -->

2022-01-21 23:14 UTC, nicktrav reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451)* status: all files reviewed, 21 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/merging_iter.go, line 490 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtoNCQZ3EvpaadDTIsq:-Mtyl3Ch7oyXdrcHYcJz:bkezwiu) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L490)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> We aren't necessarily on a start key that shares an end key at the same user key?

I don't follow?
</blockquote></details>

Disregard.
___
*[internal/rangekey/merging_iter.go, line 491 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtoN1tE5zGNDOVxtVRx:-Mtyn1HD3wLsnp26alP4:bfw462n) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L491)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

hmm, this is trying to establish that it's not just safe to use an end boundary as a start boundary of a merged bound, but mandatory. all the above is serves as the example demonstrating that necessity. should I add something to the beginning of the comment to make that more clear?
</blockquote></details>

Yeah, reading the note, it wasn't clear to me what you're demonstrating. The first sentence is incomplete. It's "either an end boundary of a level's fragment." .. or what? The second thing is missing.
___
*[internal/rangekey/merging_iter.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mtyuc624JepcUChqk5Y:-Mtyuc624JepcUChqk5Z:bhnc3me) ([raw file](https://github.com/cockroachdb/pebble/blob/31d0c46f20a94f23a417a3cec9ad1da0c0a4090f/internal/rangekey/merging_iter.go#L60)):*
> ```Go
> //
> //
> // Algorithm
> ```

These two sections were super useful :thumbsup: 
___
*[internal/rangekey/merging_iter.go, line 71 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtyqNCL2EvSpCNxh5IN:-MtyqNCM5WEB2941NKE7:b-j9a8p6) ([raw file](https://github.com/cockroachdb/pebble/blob/31d0c46f20a94f23a417a3cec9ad1da0c0a4090f/internal/rangekey/merging_iter.go#L71)):*
> ```Go
> //     4. Determine if any of the child iterators' spans overlap the candidate
> //        span.
> //         3a. If any of the child iterator's current bounds are end keys
> ```

nit: 4a/4b
___
*[internal/rangekey/merging_iter.go, line 174 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtyuGs94La9rbAHFU12:-MtyuGsA7Mr9BWa7nsvR:b-c4dzgx) ([raw file](https://github.com/cockroachdb/pebble/blob/31d0c46f20a94f23a417a3cec9ad1da0c0a4090f/internal/rangekey/merging_iter.go#L174)):*
> ```Go
> // fragmentBoundIterator surfaces the set of all fragments with a bound as a
> // part of a bound key. In the above example, i1 and i2 are positioned at end
> // boundaries, so findNextFragmentSet collects [a,c) and [a,p).
> ```

nit: maybe mention the truncation part too. In your example, we have to truncate both fragments to the start / end bound, i.e. we emit `[a, b), [a, b)`.


<!-- Sent from Reviewable.io -->

2022-01-24 15:55 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451)* status: 9 of 10 files reviewed, 19 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[internal/rangekey/merging_iter.go, line 491 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtoN1tE5zGNDOVxtVRx:-MuBmsdy1J365ncqcijn:bg8hwzk) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L491)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Yeah, reading the note, it wasn't clear to me what you're demonstrating. The first sentence is incomplete. It's "either an end boundary of a level's fragment." .. or what? The second thing is missing.
</blockquote></details>

thanks yeah, that makes sense. I fixed up the opening to be more clear.


<!-- Sent from Reviewable.io -->

2022-01-24 16:07 UTC, nicktrav reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451)* status: all files reviewed, 18 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-01-24 19:43 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 
looks great

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451#-:-MuCbI3x-pFeTHKstxz0:by91cne)* status: all files reviewed, 19 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/merging_iter.go, line 500 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtsW9QeAMFCc1u52d_s:-MuCaq0M2B4U333kC9VO:b-ozahjk) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L500)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

That's exactly right. Each iteration of the outer loop considers a new, merged span (eg, [c,f), [f,g), [g, x), [x, y)...). After positioning all the levels appropriately, `synthesizeFragments` examines which of the heap elements are positioned on an end boundary, collecting fragments from any that are. If there are none, we advance to the next merged span. This was alluded to above the for loop, but I expanded that comment.

----

This discussion also gets at a potential optimization that I've been considering... Maybe the `rangekey.Iter` should be adapted to support returning spans that have no range keys set. Imagine you have a dense point keyspace a-z and a single range key covering the span `[y, z)`.  If you have an iterator without any bounds and perform a `SeekGE('b')`, the point iterator might land on an sstable with bounds like `b-ba`,  but the rangekey iterator will need to scan all the sstables' `fileMetadata` until it finds the file containing `[y, z)` and opens it.

Alternatively, the rangekey iterator could return a span `[b, y)` with no range keys, reflecting that it seeked and found that no range keys existed all the way up to `y`, all without reading any blocks. If the point iterator is eventually Next'd to `y`, the interleaving iterator can handle Next-ing the range key iterator onto the `[y,z)` range key's sstable and range key.

</blockquote></details>

Do you want to record this optimization in a TODO code comment somewhere so the rest of us also remember it.
___
*[internal/rangekey/merging_iter.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1451#-Mtyuc624JepcUChqk5Y:-MuCQ6xw0lYLIKZKb7Jf:b32v57) ([raw file](https://github.com/cockroachdb/pebble/blob/31d0c46f20a94f23a417a3cec9ad1da0c0a4090f/internal/rangekey/merging_iter.go#L60)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

These two sections were super useful :thumbsup: 
</blockquote></details>

+1
___
*[internal/rangekey/merging_iter.go, line 174 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MuC_u7XDAoc9l-u7p3P:-MuC_u7XDAoc9l-u7p3Q:b-sgbbjp) ([raw file](https://github.com/cockroachdb/pebble/blob/146dbf55ebcee7265e74fc85bcfd7ff8a1583194/internal/rangekey/merging_iter.go#L174)):*
> ```Go
> // boundary is ≥ m.end. The corresponding start boundary must be ≤ m.start since
> // there were no other user keys between m.start and m.end. So the fragments
> // associated with the iterator's current end boundary have stard and end bounds
> ```

s/stard/start/


<!-- Sent from Reviewable.io -->

2022-01-24 21:36 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1451#-:-MuD07Yy6oJWJaurIVHI:bz5mair)* status: 8 of 10 files reviewed, 19 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[internal/rangekey/merging_iter.go, line 500 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MtsW9QeAMFCc1u52d_s:-MuD-ZNc-zFAnOrrXcwt:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/5377f52c8c9c08bc6178444f6ca5731f73e8d74e/internal/rangekey/merging_iter.go#L500)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do you want to record this optimization in a TODO code comment somewhere so the rest of us also remember it.
</blockquote></details>

Done.
___
*[internal/rangekey/merging_iter.go, line 174 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1451#-MuC_u7XDAoc9l-u7p3P:-MuD-YFCDxoMnXDM7i-N:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/146dbf55ebcee7265e74fc85bcfd7ff8a1583194/internal/rangekey/merging_iter.go#L174)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/stard/start/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-24 21:46 UTC, merged