internal/manifest: incrementally generate L0Sublevels for L0 additions
cockroachdb/pebble pull request #1465
Opened 2022-01-21 17:30 UTC by itsbilal

NewL0Sublevels is an expensive method to call, and it's called every time
there's a change to L0. This commit adds a faster, incremental generation
method for cases when there are only additions to L0 and no deletions from
it. This lets us reuse most of the slices in NewL0Sublevels and merge new
fileIntervals into it instead of starting from scratch.

Fixes #1406.

2022-01-21 17:30 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1465)
<!-- Reviewable:end -->

2022-01-21 17:43 UTC, itsbilal commented
Loading the `MANIFEST_import` manifest in testdata (taken from a large TPCC import)is now 85% faster with this optimization:

```
name                             old time/op  new time/op  delta
ManifestApplyWithL0Sublevels-12   27.1s ± 4%    4.0s ± 9%  -85.05%  (p=0.000 n=10+10)
```

And that reduction is with all the overhead involved in reading the manifest and applying version edits. The actual improvement in `L0Sublevels` generation time is definitely well above 90% if it is able to improve a coarse benchmark that much.

2022-01-24 19:37 UTC, nicktrav reviewed
> Reviewed 2 of 6 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1465)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuCZVmXE-OYnKoJebb0:-MuCZVmXE-OYnKoJebb1:brnnyo8) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L303)):*
> Note that this function can only be called once on a given receiver

Is there some way to check this? i.e. when invariants are enabled, confirm that this method has only been called once on the given receiver.
___
*[internal/manifest/testdata/l0_sublevels, line 1439 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuCY9aX0P5QfsUWCxFR:-MuCY9aX0P5QfsUWCxFS:b-5tseaz) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/testdata/l0_sublevels#L1439)):*
> ```
> L0.1:     b---------e f---------i
> L0.0:  a--------d---------g                            q---r
>        aa bb cc dd ee ff gg hh ii jj kk ll mm nn oo pp qq rr
> ```

Is it possible to add an error case too? So that we can confirm that we're seeing the `errInvalidOptimization`?


<!-- Sent from Reviewable.io -->

2022-01-26 00:35 UTC, bananabrick reviewed
Cool! Some of my questions might be silly since I've never looked at this part of the code before.

1. Do we expect this to cause any changes in our high level ycsb benchmarks, and if so, would it be worthwhile to run those? I'm curious about `ycsb/F` in particular, since it will be doing a lot of flushes.

2. I noticed that the `BenchmarkL0SublevelsInit` runs much faster on this pr vs master, but that's probably because the `BenchmarkL0SublevelsInit` calls `readManifest` on `testdata/MANIFEST_import`.

Didn't quite get through all of it, will take a look later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1465#-:-MuCiPw30ajWqnxdA1bH:boriaa)* status: 3 of 6 files reviewed, 11 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuHcV0j2FjhVX45Hodn:-MuHcV0j2FjhVX45Hodo:b-12f3z2) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L21)):*
> ```Go
> // errInvalidOptimization is for use in AddL0Files when the incremental
> // sublevel generation optimization failed, and NewL0Sublevels must be called.
> var errInvalidOptimization = errors.New("pebble: L0 sublevel generation optimization cannot be used")
> ```

nit: This variable is visible to the rest of the manifest package, is it worthwhile to rename this to have a more specific name? Making the error message more specific could also help.
___
*[internal/manifest/l0_sublevels.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuHe10H6O5iUwa94_98:-MuHe10H6O5iUwa94_99:bj5dk1) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L197)):*
> ```Go
> 	// that sublevel in increasing key order. Levels is constructed from
> 	// levelFiles and is used by callers that require a LevelSlice. The below two
> 	// fields are treated as immutable once created in NewL0Sublevels.
> ```

The `FileMetadata` references through the pointer in the `levelFiles` could be changing, right? So, while the pointer won't change, the underlying data could.

Most other fields in `L0Sublevels` also seem immutable. `cmp`. `formatKey`, `fileBytes`, `levelMetaData`, `flushSplitUserKeys`. The `fileInterval` structs seem to be the only data in this struct which is not immutable.

Not suggesting a change in wording, just wondering.
___
*[internal/manifest/l0_sublevels.go, line 271 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuHgTVb9AOMN9tsTKE6:-MuHgTVb9AOMN9tsTKE7:bfmz1sn) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L271)):*
> ```Go
> 	// to update intervals.
> 	for f := iter.First(); f != nil; f = iter.Next() {
> 		if err := s.addFileToSublevels(f, false /* checkInvariant */); err != nil {
> ```

Cool! The addition of this function call to `NewL0Sublevels` really cleans up this function.
___
*[internal/manifest/l0_sublevels.go, line 297 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuIX-Sd5rKkSh8iknNu:-MuIX-Sd5rKkSh8iknNv:bcmk8gc) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L297)):*
> ```Go
> // These files can "sit on top" of existing sublevels, creating at most one
> // new sublevel for a flush (and possibly multiple for an ingestion), and at
> // most len(files) additions to s.orderedIntervals. No files must have been
> ```

Should this be `... at most 2 * len(files) additions to s.orderedIntervals`? I might be missing some invariant which ensures it's only `atmost len(files)`.
___
*[internal/manifest/l0_sublevels.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuCZVmXE-OYnKoJebb0:-MuHgcps6yvE80pPccvv:bxogp2) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L303)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

> Note that this function can only be called once on a given receiver

Is there some way to check this? i.e. when invariants are enabled, confirm that this method has only been called once on the given receiver.
</blockquote></details>

+1. I don't think go has a way to encode this invariant in the type system, but we could have a runtime panic in this case. What do you think?
___
*[internal/manifest/l0_sublevels.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuHq2c04aQPJV07Jqx5:-MuHq2c04aQPJV07Jqx6:b-yotwr6) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L310)):*
> ```Go
> // so on. If errInvalidOptimization is returned as an error, it likely means
> // the optimization could not be applied (i.e. files added were older than
> // files already in the sublevels, something only seen in tests). Any other
> ```

Is this a issue with the tests, or do those tests actually need to add older files? It would be nice to modify the tests, get rid of this error, and turn it into a panic.
___
*[internal/manifest/l0_sublevels.go, line 315 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuHtezP0Asg7-F-beY5:-MuHtezP0Asg7-F-beY6:b-7r2iwr) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L315)):*
> ```Go
> func (s *L0Sublevels) AddL0Files(files []*FileMetadata, flushSplitMaxBytes int64, levelMetadata *LevelMetadata) (*L0Sublevels, error) {
> 	// Start with a shallow copy of s.
> 	newVal := &L0Sublevels{}
> ```

nit: Does `newVal := *s`, achieve the same result as `newVal := &L0Sublevels` and then `*newVal = *s`? We could return `&newVal` at the end.
___
*[internal/manifest/l0_sublevels.go, line 344 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuIJZbv0NWD6-7ikAdF:-MuIJZbv0NWD6-7ikAdG:bm12rig) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L344)):*
> ```Go
> 	}
> 	fileKeys = sortAndDedup(fileKeys, s.cmp)
> 	keys := make([]fileInterval, 0, 2*levelMetadata.Len())
> ```

nit: Am I correct in assuming that `levelMetadata.len` won't count the new files which are being added? Maybe this should be `2 * (levelMetadata.Len() + len(fileKeys)`?
___
*[internal/manifest/l0_sublevels.go, line 349 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuIDyrH5BsOGz2bS133:-MuIDyrIA0dhD1h2fjKV:bl4lsuy) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L349)):*
> ```Go
> 	// sorted runs, fileKeys and s.orderedIntervals, into `keys` which will form
> 	// newVal.orderedIntervals.
> 	{
> ```

This function is well structured by creating a child scope where required, but I think moving those to separate function calls is a good idea. For example, this merge step is a great candidate for a separate function call which returns the required data. What do you think?

As it is right now, the function is quite long.
___
*[internal/manifest/l0_sublevels.go, line 376 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuIYpwC29i_CBIYktXK:-MuIYpwC29i_CBIYktXL:b4ls37q) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L376)):*
> ```Go
> 				var prevInterval fileInterval
> 				// Insert a new interval for a newly-added file. prevInterval, if
> 				// non-zero, will be "inherited"; we copy its files as those extend
> ```

We should definitely add some reasoning on why the files from the `prevInterval` extend into this interval. I think I understand why this is mostly true, though. Correct me if I'm wrong.

1. If an interval is of the form `[( [...]

2022-01-31 23:50 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1465)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @bananabrick, @itsbilal, @nicktrav, and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 376 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuIYpwC29i_CBIYktXK:-MulXASu0UyXjpXnx6pc:b-jkbadf) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L376)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We need to copy the files over because we could be independently appending those `files` slices further down. It's less likely in a simple example like this one with only two files, but after a bunch of incremental additions like these, it's entirely possible that you append a different file to `prevInterval.files` and `newInterval.files`. If you hadn't done a copy at all, that would lead to corruption.

The performance issue is a real concern, and a lot of work in this method can probably be rethought if we decided to rework `L0Sublevels` in its entirety or figured out a better way to determine sublevels,  but seeing as we will only do this copy `2*len(files)` times at most, and each of those copies could be `len(sublevels)` amount of work, that's still far better than what we had before where we did `2*len(allFiles)*sublevels` amount of copying/additions. And in all realistic scenarios, we expect allFiles >> sublevels and also allFiles >> files. It's common to have thousands of L0 files that only take up a two or at most three digit number of sublevels.
</blockquote></details>

I understand the need for the copy, but I'm trying to reason about why the `newInterval` must ALWAYS have the `prevInterval`s files.

Particularly, for this example:


The only file previously in `L0` has the key range `[a, b]`, which CAN translate to a fileIntervals with startKeys `(a, isLargest: false)`, and `(b, isLargest: false)`. The `intervalKey` with `key = b` can have `isLargest = false` in the case of some range key stuff(We do `isLargest: !f.Largest.IsExclusiveSentinel`).

We add a new file with key range `[c, d]` by calling `L0Sublevels.AddL0Files`. When we run the merging algorithm in the code here, the intervalKey `(c, isLargest: false)` will sort AFTER the intervalKey `(b, isLargest: false)`. So, will run the `cmp > 0` case. Will we still want to copy the files over from the `prevInterval` to the `newInterval`?
___
*[internal/manifest/l0_sublevels.go, line 424 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MulkXJzAiAMCRT8lEAO:-MulkXK-2qAp8y4UV818:b606byp) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L424)):*
> ```Go
> 		}
> 	}
> 	newVal.orderedIntervals = keys
> ```

I think it might be possible to compute the `{min, max}IntervalIndex` for all of the `fileInterval`s during the merge loop. I'm thinking through the details currently.
___
*[internal/manifest/l0_sublevels.go, line 474 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mulcsgv65CaBN2xhlwh:-Mulcsgv65CaBN2xhlwi:b-sey3vw) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L474)):*
> ```Go
> 	// Go through old files and update interval indices.
> 	//
> 	// TODO(bilal): This is the only place in this method where we loop through
> ```

I believe the merge step, pretty much loops through all files in L0 x 2, so this step should be fine asymptotically at least.


<!-- Sent from Reviewable.io -->

2022-01-31 23:50 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1465)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @bananabrick, @itsbilal, @nicktrav, and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 424 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MulkXJzAiAMCRT8lEAO:-MumY2M66XSR845mj7gh:b-ir17po) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L424)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I think it might be possible to compute the `{min, max}IntervalIndex` for all of the `fileInterval`s during the merge loop. I'm thinking through the details currently.
</blockquote></details>

I think you alluded to the same during standup


<!-- Sent from Reviewable.io -->

2022-02-01 02:41 UTC, sumeerbhola requested changes
sorry about the delay

> Reviewed 1 of 2 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1465#-:-Mun9-KrDF7A-0BFw-5a:bi6tvgx)* status: 2 of 6 files reviewed, 10 unresolved discussions (waiting on @bananabrick, @itsbilal, and @nicktrav)

___
*[internal/manifest/l0_sublevels.go, line 340 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun3k8G5tKHHwtm4rFR:-Mun3k8G5tKHHwtm4rFS:b-ne62dx) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L340)):*
> ```Go
> 				// Copy the below attributes from prevInterval.
> 				files:                         append([]*FileMetadata(nil), prevInterval.files...),
> 				estimatedBytes:                prevInterval.estimatedBytes,
> ```

Can you add a code comment that we will fix this `estimatedBytes` later since we are interpolating over a different number of intervals.
___
*[internal/manifest/l0_sublevels.go, line 371 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun0oiC7TMa-xKVqzzT:-Mun0oiC7TMa-xKVqzzU:bkoffen) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L371)):*
> ```Go
> // so on. If errInvalidL0SublevelsOpt is returned as an error, it likely means
> // the optimization could not be applied (i.e. files added were older than
> // files already in the sublevels, which is possible around ingestions and in
> ```

what makes this possible for ingestions? I thought the only odd case with ingestions was that the seqnum of the ingested file could be sandwiched in the seqnum interval of a later flushed file. But in that case the flushed file will land in a later version edit.
___
*[internal/manifest/l0_sublevels.go, line 403 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun2RDZ06EV-JT0aKi-:-Mun2RD_CcNwJWzQRsOn:b-89e1sj) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L403)):*
> ```Go
> 			isLargest: !f.Largest.IsExclusiveSentinel(),
> 		}
> 		if len(fileKeys) == 0 || intervalKeyCompare(s.cmp, fileKeys[len(fileKeys)-1], left) != 0 {
> ```

what is the purpose of this comparison given that these files are in seqnum order and not in key order?
___
*[internal/manifest/l0_sublevels.go, line 446 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun6HC685U-QwV9ngQ9:-Mun6HC685U-QwV9ngQA:by2trrj) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L446)):*
> ```Go
> 	// to reflect that of adjacent old intervals.
> 	{
> 		lastIdx := 0
> ```

should this be initialized to -1.
If the first entry in the oldToNewMap is (0, 3) then the indices 0, 1, 2 are new. And presumably we would want to examine index 0 in the loop below.
If not, this deserves a code comment.
___
*[internal/manifest/l0_sublevels.go, line 463 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun7Toj4_cthOXZ1ZnQ:-Mun7Toj4_cthOXZ1ZnR:brk8the) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L463)):*
> ```Go
> 				// different from that generated by NewL0Sublevels, but this might
> 				// actually be a more accurate estimate, especially when the same
> 				// intervals keep getting repeatedly split.
> ```

I didn't follow this.
Also, given that we are iterating over all files below, it seems preferable to do the interpolation in the same manner as the non-incremental path.
___
*[internal/manifest/version_edit.go, line 605 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun-E9cCMqTVpZ9nJYB:-Mun-E9cCMqTVpZ9nJYC:b8bcfig) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/version_edit.go#L605)):*
> ```Go
> 				// it incrementally.
> 				var err error
> 				// AddL0Sublevels requires addedFiles to be sorted in seqnum order.
> ```

AddL0Files?


<!-- Sent from Reviewable.io -->

2022-02-01 02:44 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1465)* status: 2 of 6 files reviewed, 10 unresolved discussions (waiting on @bananabrick, @itsbilal, and @nicktrav)

___
*[internal/manifest/l0_sublevels.go, line 424 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MulkXJzAiAMCRT8lEAO:-Mun4BUD3BsmNezczlee:b-om90rr) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L424)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I think you alluded to the same during standup
</blockquote></details>

Okay, I thought about a method to generate the `{min,max}IntervalIndex` for every file during the merge step. I'm outlining the tradeoffs of the method here, and not the algorithm itself:

I ran `BenchmarkL0SublevelsInit`, and here's the number of unique keys, number of duplicates detected during the `sortAndDedup` step: `6762 unique keys, 11 duplicates`.

Which means that at least for this Benchmark, and I guess in general too, `len(orderedIntervals) ~ 2 * len(total files in L0)`.

With that in mind, I think it's possible to compute the `{min, max}IntervalIdex` for every single file in the merge step, with a total run time of `2 * len(total files in L0)` for the `mergeIntervals` function.

The current runtime of `mergeIntervals` is ~ `len(orderedIntervals) + len(newFiles)`. Note that `2 * len(total files in L0)`, `len(orderedIntervals) + len(newFiles)` are the same, if the number of duplicate `intervalKey`s is low.

Even if the number of duplicate `intervalKey`s is high during the `sortAndDedup` step, we already do `len(files)` work in the following step. The following step also uses `LevelIterator`s to iterate through the files in a level which is more expensive than just iterating through a slice:

```
	// of the first interval touched by this method.
	for sublevel := range s.Levels {
		s.Levels[sublevel].Each(func(f *FileMetadata) {
			f.minIntervalIndex = oldToNewMap[f.minIntervalIndex]
			// maxIntervalIndex is special. Since it's an inclusive end bound, we
			// actually have to map it to the _next_ old interval's new previous
			// interval. This logic is easier to understand if you see
			// [f.minIntervalIndex, f.maxIntervalIndex] as
			// [f.minIntervalIndex, f.maxIntervalIndex+1).
			f.maxIntervalIndex = oldToNewMap[f.maxIntervalIndex+1] - 1
		})
	}

```

The algorithm would need to instrument each `intervalKey` with some additional data, but it's doable.

The benefit of the algorithm would be that it would get rid of the code where we iterate through all of the files using a `LevelIterator`, which should improve the runtime, and also make the function shorter.

What do you think? The code as it is, already has great perf benefits, so we don't need to do the optimization I'm thinking of, but it will clean up some code, and get rid of your `TODO`:
```
	// TODO(bilal): This is the only place in this method where we loop through
	// all existing files, which could be much more in number than newly added
	// files. See if we can avoid the need for this, either by getting rid of
	// f.minIntervalIndex and f.maxIntervalIndex and calculating them on the
	// fly with a binary search, or by only looping through files to the right
	// of the first interval touched by this method.
```


<!-- Sent from Reviewable.io -->

2022-02-01 22:57 UTC, itsbilal reviewed
> Dismissed @sumeerbhola from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1465)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 376 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuIYpwC29i_CBIYktXK:-Muq11HL3T_mGFOdRIrP:bp0acqo) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L376)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I understand the need for the copy, but I'm trying to reason about why the `newInterval` must ALWAYS have the `prevInterval`s files.

Particularly, for this example:


The only file previously in `L0` has the key range `[a, b]`, which CAN translate to a fileIntervals with startKeys `(a, isLargest: false)`, and `(b, isLargest: false)`. The `intervalKey` with `key = b` can have `isLargest = false` in the case of some range key stuff(We do `isLargest: !f.Largest.IsExclusiveSentinel`).

We add a new file with key range `[c, d]` by calling `L0Sublevels.AddL0Files`. When we run the merging algorithm in the code here, the intervalKey `(c, isLargest: false)` will sort AFTER the intervalKey `(b, isLargest: false)`. So, will run the `cmp > 0` case. Will we still want to copy the files over from the `prevInterval` to the `newInterval`?

</blockquote></details>

The key thing to remember is that `[minIntervalIndex, maxIntervalIndex] are inclusive, so in your example, a file that's [a,b] will get intervalKeys `(a,false), (b, true)` (let's assume the latter isn't a rangedel sentinel, though it doesn't change anything), but critically the file will get "minIntervalIndex = 0, maxIntervalIndex=0" and the `(b, true)` intervalKey will just serve as an empty marker as the end of the previous intervalKey. Which is to say, its files slice will be empty. So a split on the right of (b, true) will copy the empty files slice.

It's confusing since we mix inclusive and exclusive file bounds a lot here, but it holds. 
___
*[internal/manifest/l0_sublevels.go, line 340 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun3k8G5tKHHwtm4rFR:-MurHz4yCtFVS4youtO0:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L340)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a code comment that we will fix this `estimatedBytes` later since we are interpolating over a different number of intervals.
</blockquote></details>

Done.
___
*[internal/manifest/l0_sublevels.go, line 371 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun0oiC7TMa-xKVqzzT:-MurG61818jXP4GeScPy:bxp2mpo) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L371)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what makes this possible for ingestions? I thought the only odd case with ingestions was that the seqnum of the ingested file could be sandwiched in the seqnum interval of a later flushed file. But in that case the flushed file will land in a later version edit.
</blockquote></details>

For some reason I am getting an error here in the metamorphic tests if I replace this with a panic; it seemed like a variant of the sandwiched case but with no keys after the flushed file (producing a flushed sst that is truly below the ingested sst before it).
___
*[internal/manifest/l0_sublevels.go, line 403 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun2RDZ06EV-JT0aKi-:-MurGtsE1Jw1XXMablgt:b5rmqud) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L403)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what is the purpose of this comparison given that these files are in seqnum order and not in key order?
</blockquote></details>

It's from an older version where we were relying on `files` representing a flush and being sorted by key order, but now that we call sortAndDedup and no longer have that constraint it's no longer necessary. Removed.
___
*[internal/manifest/l0_sublevels.go, line 424 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MulkXJzAiAMCRT8lEAO:-MurKrTO0d0cNQh5DdIi:bvlrg3) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L424)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Okay, I thought about a method to generate the `{min,max}IntervalIndex` for every file during the merge step. I'm outlining the tradeoffs of the method here, and not the algorithm itself:

I ran `BenchmarkL0SublevelsInit`, and here's the number of unique keys, number of duplicates detected during the `sortAndDedup` step: `6762 unique keys, 11 duplicates`.

Which means that at least for this Benchmark, and I guess in general too, `len(orderedIntervals) ~ 2 * len(total files in L0)`.

With that in mind, I think it's possible to compute the `{min, max}IntervalIdex` for every single file in the merge step, with a total run time of `2 * len(total files in L0)` for the `mergeIntervals` function.

The current runtime of `mergeIntervals` is ~ `len(orderedIntervals) + len(newFiles)`. Note that `2 * len(total files in L0)`, `len(orderedIntervals) + len(newFiles)` are the same, if the number of duplicate `intervalKey`s is low.

Even if the number of duplicate `intervalKey`s is high during the `sortAndDedup` step, we already do `len(files)` work in the following step. The following step also uses `LevelIterator`s to iterate through the files in a level which is more expensive than just iterating through a slice:

```
	// of the first interval touched by this method.
	for sublevel := range s.Levels {
		s.Levels[sublevel].Each(func(f *FileMetadata) {
			f.minIntervalIndex = oldToNewMap[f.minIntervalIndex]
			// maxIntervalIndex is special. Since it's an inclusive end bound, we
			// actually have to map it to the _next_ old interval's new previous
			// interval. This logic is easier to understand if you see
			// [f.minIntervalIndex, f.maxIntervalIndex] as
			// [f.minIntervalIndex, f.maxIntervalIndex+1).
			f.maxIntervalIndex = oldToNewMap[f.maxIntervalIndex+1] - 1
		})
	}

```

The algorithm would need to instrument each `intervalKey` with some additional data, but it's doable.

The benefit of the algorithm would be that it would get rid of the code where we iterate through all of the files using a `LevelIterator`, which should improve the runtime, and also make the function shorter.

What do you think? The code as it is, already has great perf benefits, so we don't need to do the optimization I'm thinking of, but it will clean up some code, and get rid of your `TODO`:
```
	// TODO(bilal): This is the only place in this method where we loop through
	// all existing files, which could be much more in number than newly added
	// files. See if we can avoid the need for this, either by getting rid of
	// f.minIntervalIndex and f.maxIntervalIndex and calculating them on the
	// fly with a binary search, or by only looping through files to the right
	// of the first interval touched by this method.
```
</blockquote></details>

Thanks for thinking of this and writing up the tradeoffs! If the only win is that we'd get to leave the `LevelIterator` behind then it might not be that worthwhile as we might want to use the LevelIterator and rely less on slices anyway in the long run. Full-level slices are expensive to allocate, but they are faster to iterate. @jbowens actually has a TODO higher up on reducing any cases where we use LevelSlices for the entire level. 

Seeing as this PR is relatively large, I'm al [...]

2022-02-03 03:16 UTC, bananabrick reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

I haven't tried to understand how the `estimatedBytes` change works. I'll defer to @sumeerbhola for that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1465#-:-MuxZpyH8JsVd0qzBFnn:b-xr5apk)* status: 1 of 6 files reviewed, 11 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 376 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuIYpwC29i_CBIYktXK:-MuwP5Bh7P3yjAiIqDGl:b-9xyepz) ([raw file](https://github.com/cockroachdb/pebble/blob/c62ac114c8c66ed21d18a2ba5cdbdcba42b67860/internal/manifest/l0_sublevels.go#L376)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The key thing to remember is that `[minIntervalIndex, maxIntervalIndex] are inclusive, so in your example, a file that's [a,b] will get intervalKeys `(a,false), (b, true)` (let's assume the latter isn't a rangedel sentinel, though it doesn't change anything), but critically the file will get "minIntervalIndex = 0, maxIntervalIndex=0" and the `(b, true)` intervalKey will just serve as an empty marker as the end of the previous intervalKey. Which is to say, its files slice will be empty. So a split on the right of (b, true) will copy the empty files slice.

It's confusing since we mix inclusive and exclusive file bounds a lot here, but it holds. 
</blockquote></details>

True. I was thinking if `isLargest: false`, then we could end up including files in the interval which we shouldn't copy, but that's not the case.

Thanks.
___
*[internal/manifest/l0_sublevels.go, line 424 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MulkXJzAiAMCRT8lEAO:-MuwPsNREQKk8RJDruje:b-xi1za5) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L424)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Thanks for thinking of this and writing up the tradeoffs! If the only win is that we'd get to leave the `LevelIterator` behind then it might not be that worthwhile as we might want to use the LevelIterator and rely less on slices anyway in the long run. Full-level slices are expensive to allocate, but they are faster to iterate. @jbowens actually has a TODO higher up on reducing any cases where we use LevelSlices for the entire level. 

Seeing as this PR is relatively large, I'm also down to merge this (with a variant of the sweep change you've made to set the min/maxIntervalIndex of new files, which I've completed now), but leave this `Each` loop around to map old file indices to new files. I would also want to explore dropping min/max interval indices altogether, or at least remove the contract requirement that they be accurate for the most recent Version, since the only place where we really need them after sublevel creation is in compaction picking, and there we can probably calculate these on the fly with a binary search for any files we're interested in.

Given the average Version will only have compactions picked off of it 1-4 times (assuming 4 is max compaction concurrency, and even then the avg number of compactions picked off of it will likely be less than the max), and each Version creation requires calculating 2*len(L0 files) number of interval indices, we're probably doing a lot of up-front work to reduce a small amount of downstream work.
</blockquote></details>

It's not necessary to add it here. But we're already iterating through slices/maps of len ~ 2 * len(total files) by iterating through 1. `ordered intervals`. 2. `oldToNewMap`.
___
*[internal/manifest/l0_sublevels.go, line 490 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuxXpgh8jOewm-0Gn-_:-MuxXpgh8jOewm-0Gn-a:b-zfurnp) ([raw file](https://github.com/cockroachdb/pebble/blob/08bd58e66292fe2ef796c65fafce177135ee215d/internal/manifest/l0_sublevels.go#L490)):*
> ```Go
> 	newVal.orderedIntervals = keys
> 	// Update indices in s.orderedIntervals for fileIntervals we retained.
> 	for _, newIdx := range oldToNewMap {
> ```

If I'm understanding correctly, the `files{Min,Max}IntervalIndex` we're setting here aren't necessarily accurate. If inaccurate, they'll get fixed by the calls to `addFilesToSublevels`. Is that right? If it is, could we indicate that these values aren't "final"?
___
*[internal/manifest/l0_sublevels.go, line 503 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuxYY2v83UZvEovp8hc:-MuxYY2v83UZvEovp8hd:b-1rcx3d) ([raw file](https://github.com/cockroachdb/pebble/blob/08bd58e66292fe2ef796c65fafce177135ee215d/internal/manifest/l0_sublevels.go#L503)):*
> ```Go
> 			newInterval.filesMaxIntervalIndex = oldToNewMap[newInterval.filesMaxIntervalIndex+1] - 1
> 		} else {
> 			newInterval.filesMaxIntervalIndex = oldToNewMap[newInterval.filesMaxIntervalIndex]
> ```

I believe in this case, `newInterval.filesMaxIntervalIndex` == `len(oldToNewMap) - 1`? Could we do an `else if` with that condition, and then another `else`, with a panic?

if newInterval.filesMaxIntervalIndex < len(oldToNewMap)-1 {
	newInterval.filesMaxIntervalIndex = oldToNewMap[newInterval.filesMaxIntervalIndex+1] - 1
} else if  newInterval.filesMaxIntervalIndex == len(oldToNewMap)-1 {
	newInterval.filesMaxIntervalIndex = oldToNewMap[newInterval.filesMaxIntervalIndex]
} else {
        panic
}

Or even just a code comment stating that it is the "equals" case in the "else".


<!-- Sent from Reviewable.io -->

2022-02-03 19:08 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1465#-:-Mv-z9ZYCi-irYH9dd-R:b-814g8k)* status: 1 of 6 files reviewed, 11 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 424 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MulkXJzAiAMCRT8lEAO:-Mv-xPrvCQe5fKN2zBI6:b-id9n62) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L424)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

It's not necessary to add it here. But we're already iterating through slices/maps of len ~ 2 * len(total files) by iterating through 1. `ordered intervals`. 2. `oldToNewMap`.
</blockquote></details>

You mean the TODO is not necessary? I guess you're right, we'll probably be iterating through some factor of len(total files) regardless. But the hope would be that with flush splitting (which will largely happen on existing interval keys, though it might not be the exact same key but around it), we will hopefully bring num_intervals to a number that's much less than 2*len(files). Maybe we should check this out in practice more; one of your experiments uncovered very few duplicates so you're probably correct.
___
*[internal/manifest/l0_sublevels.go, line 490 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuxXpgh8jOewm-0Gn-_:-Mv-xrcXCerH3RZr9eil:b2kaby5) ([raw file](https://github.com/cockroachdb/pebble/blob/08bd58e66292fe2ef796c65fafce177135ee215d/internal/manifest/l0_sublevels.go#L490)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

If I'm understanding correctly, the `files{Min,Max}IntervalIndex` we're setting here aren't necessarily accurate. If inaccurate, they'll get fixed by the calls to `addFilesToSublevels`. Is that right? If it is, could we indicate that these values aren't "final"?
</blockquote></details>

After this loop, `files{Min, Max}IntervalIndex` should be accurate for all old/retained intervals, and after the next loop it should be accurate  for new intervals in between old intervals. New intervals to the left or right of all old intervals will get adjusted in `addFilesToSublevels`, as well as any old intervals that overlapped with new files, yep. I'll clarify that in the same comment that Sumeer asked for clarification in.
___
*[internal/manifest/l0_sublevels.go, line 503 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MuxYY2v83UZvEovp8hc:-Mv-ycmR7f7Tqmo5fBTl:byjn61q) ([raw file](https://github.com/cockroachdb/pebble/blob/08bd58e66292fe2ef796c65fafce177135ee215d/internal/manifest/l0_sublevels.go#L503)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I believe in this case, `newInterval.filesMaxIntervalIndex` == `len(oldToNewMap) - 1`? Could we do an `else if` with that condition, and then another `else`, with a panic?

if newInterval.filesMaxIntervalIndex < len(oldToNewMap)-1 {
	newInterval.filesMaxIntervalIndex = oldToNewMap[newInterval.filesMaxIntervalIndex+1] - 1
} else if  newInterval.filesMaxIntervalIndex == len(oldToNewMap)-1 {
	newInterval.filesMaxIntervalIndex = oldToNewMap[newInterval.filesMaxIntervalIndex]
} else {
        panic
}

Or even just a code comment stating that it is the "equals" case in the "else".
</blockquote></details>

I'll just add the comment, as the panic already happens; we'll do an index-out-of-bounds read from `oldToNewMap`. 


<!-- Sent from Reviewable.io -->

2022-02-03 19:39 UTC, bananabrick approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1465)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 424 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-MulkXJzAiAMCRT8lEAO:-Mv02MoRDyLbhmyBf1Kr:bo0mzqt) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L424)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

You mean the TODO is not necessary? I guess you're right, we'll probably be iterating through some factor of len(total files) regardless. But the hope would be that with flush splitting (which will largely happen on existing interval keys, though it might not be the exact same key but around it), we will hopefully bring num_intervals to a number that's much less than 2*len(files). Maybe we should check this out in practice more; one of your experiments uncovered very few duplicates so you're probably correct.
</blockquote></details>

No, I meant the optimization I wrote about.


<!-- Sent from Reviewable.io -->

2022-02-03 20:25 UTC, sumeerbhola reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 4 files at r3, 1 of 2 files at r4, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1465#-:-Mv0Ffyz69JXQTSQRMo-:b593w57)* status: 5 of 6 files reviewed, 9 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 371 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun0oiC7TMa-xKVqzzT:-Mv05YAu8OUMLPSIcKUg:b-7q9769) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L371)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

For some reason I am getting an error here in the metamorphic tests if I replace this with a panic; it seemed like a variant of the sandwiched case but with no keys after the flushed file (producing a flushed sst that is truly below the ingested sst before it).
</blockquote></details>

Ah yes, that can happen -- the ingest went ahead without flushing the memtable since it did not overlap and the memtable couldn't accommodate the next write that came along so the memtable got flushed to a file with lower seqnum. Those later flushed files should not share any intervals with the existing ingested files that raced ahead. But that is probably too subtle to consider and check here. There is probably another case where the memtable did accept the later write(s), but we flushed it to multiple files so some files have lower seqnum than the ingested sstables that raced ahead. Same in terms of not sharing the same intervals.

Maybe expand on this comment a bit, because it's likely we'll forget.
___
*[internal/manifest/l0_sublevels.go, line 463 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun7Toj4_cthOXZ1ZnQ:-Mv0Eqeh5E5VOgEDIozn:bjh60dr) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L463)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We're doing to subdivide the "parent interval" bytes estimate down into the new child intervals. The non-incremental logic would divide evenly across all the new intervals, the incremental logic would have more of a tree-like division where the split parts get divided but the unsplit interval ranges stay at the old bytes estimates. It's unclear if this is worse, in some cases it might be more representative, so I left it as is. But I'm happy to do the same logic as the non-incremental case.
</blockquote></details>

I'd prefer doing the same estimation logic.
I believe that should allow for a randomized test that constructs a sequence of version edits containing added files and then compares the L0Sublevels generated on the final version (non incremental) and the one generated via the sequence of incremental edits to see if they are the same.


<!-- Sent from Reviewable.io -->

2022-02-03 22:07 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1465)* status: 5 of 6 files reviewed, 9 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 463 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun7Toj4_cthOXZ1ZnQ:-Mv0cABtD8VKUF6fZ8-Y:b-b4d1c3) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L463)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'd prefer doing the same estimation logic.
I believe that should allow for a randomized test that constructs a sequence of version edits containing added files and then compares the L0Sublevels generated on the final version (non incremental) and the one generated via the sequence of incremental edits to see if they are the same.
</blockquote></details>

+1 on the randomzied test. Could probably be done in a future pr, but it would be nice to check for equivalence here.


<!-- Sent from Reviewable.io -->

2022-02-03 23:04 UTC, sumeerbhola commented
Future PR is fine by me too, for the randomized test. We should definitely prioritize it so that it happens before CockroachDB v22.1.

2022-02-04 18:26 UTC, itsbilal reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1465#-:-Mv4z0jA5M6NoxI4QLrt:bz5mair)* status: 4 of 6 files reviewed, 9 unresolved discussions (waiting on @bananabrick, @jbowens, and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 371 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun0oiC7TMa-xKVqzzT:-Mv0_D6a3D1jsXFcQ1WK:bxo06mi) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L371)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Ah yes, that can happen -- the ingest went ahead without flushing the memtable since it did not overlap and the memtable couldn't accommodate the next write that came along so the memtable got flushed to a file with lower seqnum. Those later flushed files should not share any intervals with the existing ingested files that raced ahead. But that is probably too subtle to consider and check here. There is probably another case where the memtable did accept the later write(s), but we flushed it to multiple files so some files have lower seqnum than the ingested sstables that raced ahead. Same in terms of not sharing the same intervals.

Maybe expand on this comment a bit, because it's likely we'll forget.

</blockquote></details>

Done.  The tricky thing is that it can also share the same intervals (at least, where intervals = the file intervals we have in L0sublevels). Consider this panic message from a panic I added here, where the "added file" is in a newer version edit:

```
panic: left file: ycfjuqm@8 - ycfjuqm@8, 1321 - 1321, adding file: yceuxjpso@2 - yiniy@2, 1271 - 1301
```

The check we do at ingestion time for memtable overlaps is pretty specific, and it rightly caught that the memtable at the time did not have the one key that was being ingested. Then when the memtable filled up, we flushed it, and one of the flushed files (due to a flush split) ended up being completely below the ingested file in sequence numbers, and also spanned across the ingested file, falling underneath it in sublevels.

Clarifying this in a comment. Thanks!
___
*[internal/manifest/l0_sublevels.go, line 463 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun7Toj4_cthOXZ1ZnQ:-Mv0_GZg7nPCIkn_MBnD:b-4e87do) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L463)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

+1 on the randomzied test. Could probably be done in a future pr, but it would be nice to check for equivalence here.
</blockquote></details>

Done.  Will add the randomized test in a future PR, but I've added an invariant check in `TestL0Sublevels`. 


<!-- Sent from Reviewable.io -->

2022-02-04 20:06 UTC, itsbilal commented
___
*[internal/manifest/l0_sublevels.go, line 463 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1465#-Mun7Toj4_cthOXZ1ZnQ:-Mv5KvqwCwd5KPqlx1C_:b-6z45ky) ([raw file](https://github.com/cockroachdb/pebble/blob/88795ab5ed07ee20ba4b5764f174025fa4784bb3/internal/manifest/l0_sublevels.go#L463)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done.  Will add the randomized test in a future PR, but I've added an invariant check in `TestL0Sublevels`. 
</blockquote></details>

I'm happy to merge as-is, but will give Sumeer the chance to scrutinize the new `estimateBytes` logic as it's a little different.


<!-- Sent from Reviewable.io -->

2022-02-07 19:41 UTC, merged