sstable: add a writeQueue to the sstable writer
cockroachdb/pebble pull request #1466
Opened 2022-01-21 19:42 UTC by bananabrick

This pr adds a writeQueue to the sstable writer. The queue is used to
write data blocks to disk. Currently, the queue will run synchronously
with the Writer client goroutine.

A writeTask, along with a dataBlockBuf is passed to the writerQueue. The
Writer Client goroutine will block until the writeQueue finishes writing
the block to disk.

2022-01-21 19:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1466)
<!-- Reviewable:end -->

2022-01-21 20:03 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1466)* status: 0 of 3 files reviewed, 4 unresolved discussions

___
*[sstable/write_queue.go, line 17 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MtyCmB_BENCo4K2AgKH:-MtyCmB_BENCo4K2AgKI:b-tqgdjo) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/write_queue.go#L17)):*
> ```Go
> 	// todo(bananabrick) : Remove the key field once Writer.addIndexEntry is
> 	// refactored to not require the key.
> 	key InternalKey
> ```

I'm passing the key for the current synchronous implementation. Once I refactor `addIndexEntry` for the asynchronous implementation, this should no longer be required. The refactor of `addIndexEntry` is pretty complicated, and also needs changes to the `EstimatedSize` function, so I left it out for a separate pr.
___
*[sstable/writer.go, line 755 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MtyDZWu-h41plOyYXQW:-MtyDZWv2B9Ziw17ZAmt:b-jghn74) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L755)):*
> ```Go
> 		w.dataBlockBuf = nil
> 		writeTask.key = key
> 		w.queueState.writeQueue.add(writeTask)
> ```

There is still a cost to the channel writes/reads, and goroutine context switching. I got around that in my previous writeQueue pr by making the writeQueue an interface and having a separate implementation for when parallel compression is disabled.

Note that even in the "fallback" case we discussed where the queues are full, and we decide to do the compression in the Writer client goroutine, we still need to use the write queue. This is because the writeQueue needs to handle all the data block writes to maintain order.
___
*[sstable/writer.go, line 1335 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MtyDKbG0G4fW5eRIRsJ:-MtyDKbG0G4fW5eRIRsK:bongh8) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L1335)):*
> ```Go
> 		},
> 		coalescer:        rangekey.Coalescer{},
> 		dataBlockBuffers: make(chan *dataBlockBuf, 1),
> ```

`dataBlockBuffers` is a channel instead of `sync.Pool`, because this pr only handles the synchronous case, and I needed the buffer to have a max size of 1, and block when the channel is empty.
___
*[sstable/writer.go, line 1347 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MtyDF7X90AGQbCYECqr:-MtyDF7X90AGQbCYECqs:b-ntpzzw) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L1347)):*
> ```Go
> 		checksummer: checksummer{checksumType: o.Checksum},
> 	}
> 	w.queueState.writeQueue = newWriteQueue(1, w)
> ```

The queue has a size of 1, because this pr only handles the synchronous case, and the queue doesn't need to be larger.


<!-- Sent from Reviewable.io -->

2022-01-22 02:42 UTC, bananabrick commented
Posting some benchmark results:

benchstat comparison for all ycsb benchmarks run for 30 minutes, on the same machines as nightly benchmarks.

```
name                old ops/sec  new ops/sec  delta
ycsb/E/values=1024   69.6k ± 7%   69.0k ± 9%    ~     (p=0.841 n=5+5)
ycsb/A/values=1024   93.0k ± 1%   92.9k ± 1%    ~     (p=1.000 n=5+5)
ycsb/D/values=1024    112k ±17%    109k ±16%    ~     (p=0.690 n=5+5)
ycsb/F/values=1024   27.0k ± 1%   27.6k ± 1%  +2.28%  (p=0.008 n=5+5)
ycsb/C/values=1024   1.08M ±12%   1.03M ±34%    ~     (p=0.310 n=5+5)
ycsb/B/values=1024    390k ± 8%    385k ± 9%    ~     (p=0.548 n=5+5)

name                old read     new read     delta
ycsb/E/values=1024    134G ± 5%    133G ± 5%    ~     (p=0.841 n=5+5)
ycsb/A/values=1024    513G ± 1%    511G ± 1%    ~     (p=0.222 n=5+5)
ycsb/D/values=1024    199G ±12%    196G ±14%    ~     (p=0.690 n=5+5)
ycsb/F/values=1024    508G ± 0%    505G ± 0%  -0.59%  (p=0.016 n=5+5)
ycsb/C/values=1024   63.8G ± 3%   64.1G ± 4%    ~     (p=1.000 n=5+5)
ycsb/B/values=1024    286G ± 6%    283G ± 7%    ~     (p=0.421 n=5+5)

name                old write    new write    delta
ycsb/E/values=1024    147G ± 5%    147G ± 6%    ~     (p=0.841 n=5+5)
ycsb/A/values=1024    606G ± 1%    605G ± 1%    ~     (p=0.548 n=5+5)
ycsb/D/values=1024    221G ±13%    217G ±14%    ~     (p=0.690 n=5+5)
ycsb/F/values=1024    612G ± 0%    612G ± 0%    ~     (p=0.095 n=5+5)
ycsb/C/values=1024   63.8G ± 3%   64.1G ± 4%    ~     (p=1.000 n=5+5)
ycsb/B/values=1024    326G ± 6%    323G ± 7%    ~     (p=0.421 n=5+5)

name                old r-amp    new r-amp    delta
ycsb/E/values=1024    8.79 ± 3%    8.87 ± 4%    ~     (p=0.452 n=5+5)
ycsb/A/values=1024    9.65 ± 6%    9.97 ±10%    ~     (p=0.690 n=5+5)
ycsb/D/values=1024    8.03 ± 4%    8.16 ± 4%    ~     (p=0.881 n=5+5)
ycsb/F/values=1024    0.00         0.00         ~     (all equal)
ycsb/C/values=1024    2.47 ±31%    2.46 ±47%    ~     (p=0.921 n=5+5)
ycsb/B/values=1024    6.28 ± 1%    6.33 ± 1%    ~     (p=0.095 n=5+5)

name                old w-amp    new w-amp    delta
ycsb/E/values=1024    21.7 ± 2%    21.8 ± 3%    ~     (p=0.548 n=5+5)
ycsb/A/values=1024    6.67 ± 1%    6.65 ± 1%    ~     (p=0.508 n=5+5)
ycsb/D/values=1024    20.2 ± 4%    20.4 ± 3%    ~     (p=1.000 n=5+5)
ycsb/F/values=1024    11.6 ± 1%    11.4 ± 1%  -2.34%  (p=0.016 n=5+5)
ycsb/C/values=1024    0.00         0.00         ~     (all equal)
ycsb/B/values=1024    8.58 ± 2%    8.60 ± 2%    ~     (p=0.897 n=5+5)
```

benchstat comparison for all ycsb benchmarks run for 30 minutes, on gce-n1-standard-16 machines configured with a large ssd.

```
name                old ops/sec  new ops/sec  delta
ycsb/E/values=1024   61.3k ± 3%   61.1k ± 2%     ~     (p=1.000 n=5+5)
ycsb/A/values=1024    189k ± 7%    188k ± 3%     ~     (p=0.690 n=5+5)
ycsb/D/values=1024    196k ± 5%    193k ± 4%     ~     (p=0.690 n=5+5)
ycsb/F/values=1024   73.7k ± 7%   66.3k ±11%  -10.00%  (p=0.032 n=5+5)
ycsb/C/values=1024    864k ±18%    916k ±20%     ~     (p=0.548 n=5+5)
ycsb/B/values=1024    353k ± 4%    344k ± 3%     ~     (p=0.222 n=5+5)

name                old read     new read     delta
ycsb/E/values=1024    110G ± 2%    112G ± 2%     ~     (p=0.222 n=5+5)
ycsb/A/values=1024   1.00T ± 7%   0.99T ± 3%     ~     (p=0.690 n=5+5)
ycsb/D/values=1024    311G ± 5%    308G ± 3%     ~     (p=0.841 n=5+5)
ycsb/F/values=1024   1.16T ±41%   0.86T ±28%     ~     (p=0.056 n=5+5)
ycsb/C/values=1024   50.3G ± 6%   51.9G ± 4%     ~     (p=0.310 n=5+5)
ycsb/B/values=1024    281G ± 4%    276G ± 2%     ~     (p=0.548 n=5+5)

name                old write    new write    delta
ycsb/E/values=1024    122G ± 2%    124G ± 3%     ~     (p=0.222 n=5+5)
ycsb/A/values=1024   1.19T ± 7%   1.18T ± 3%     ~     (p=0.690 n=5+5)
ycsb/D/values=1024    349G ± 5%    345G ± 3%     ~     (p=0.841 n=5+5)
ycsb/F/values=1024   1.45T ±34%   1.11T ±24%     ~     (p=0.056 n=5+5)
ycsb/C/values=1024   50.3G ± 6%   52.1G ± 6%     ~     (p=0.310 n=5+5)
ycsb/B/values=1024    318G ± 4%    312G ± 2%     ~     (p=0.548 n=5+5)

name                old r-amp    new r-amp    delta
ycsb/E/values=1024    7.78 ± 4%    8.06 ± 4%     ~     (p=0.151 n=5+5)
ycsb/A/values=1024    7.03 ± 1%    7.16 ± 2%     ~     (p=0.143 n=5+5)
ycsb/D/values=1024    6.91 ± 1%    7.01 ± 2%     ~     (p=0.143 n=5+5)
ycsb/F/values=1024    0.00         0.00          ~     (all equal)
ycsb/C/values=1024    2.79 ±21%    2.62 ±49%     ~     (p=1.000 n=5+5)
ycsb/B/values=1024    5.74 ± 1%    5.80 ± 1%     ~     (p=0.071 n=5+5)

name                old w-amp    new w-amp    delta
ycsb/E/values=1024    20.3 ± 2%    20.1 ±11%     ~     (p=1.000 n=5+5)
ycsb/A/values=1024    6.43 ± 0%    6.42 ± 0%     ~     (p=0.286 n=5+5)
ycsb/D/values=1024    18.2 ± 1%    18.1 ± 4%     ~     (p=0.690 n=5+5)
ycsb/F/values=1024    9.90 ±27%    8.48 ±14%     ~     (p=0.095 n=5+5)
ycsb/C/values=1024    0.00         0.00          ~     (all equal)
ycsb/B/values=1024    9.23 ± 1%    9.25 ± 1%     ~     (p=1.000 n=5+5)
```

2022-01-24 17:05 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1466)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @bananabrick, @itsbilal, and @jbowens)

___
*[sstable/writer.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuBy2Q_5N-Nak4JtT-B:-MuBy2Qa5Db-agPZc4FP:b13f7yn) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L171)):*
> ```Go
> 		writeQueue *writeQueue
> 		// errCh is a buffered channel of size 1, and it will be written to at most once.
> 		errCh chan error
> ```

I'm unclear why this is a channel instead of a plain `error` field. There is never going to be more than one worker in `writeQueue` so there is only 1 writer which is doing peculiar things like trying to write to the channel once in order to avoid blocking. It seems to me that this channel is simply providing read-write synchronization, in which case a simpler alternative would be to add a `Writer.SetError` method and guard the `Writer.err` field using a mutex. It seems to also simplify what happens in `Writer.Error` which currently tries to pull from the channel if w.err is not already nil.
___
*[sstable/writer.go, line 760 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuBzNj669VjT2Z7Ys3b:-MuBzNj669VjT2Z7Ys3c:bgj4f6l) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L760)):*
> ```Go
> 		// this call will block until writeTask is completed by Writer.writeQueue. This
> 		// effectively makes the write pipeline synchronous with the Writer client.
> 		w.dataBlockBuf = <-w.dataBlockBuffers
> ```

I was wondering about `dataBlockBuffers`. It seems we are using this for:
- reuse of the scratch space provided by `dataBlockBuf`, for which we could also use a `sync.Pool`?
- ensuring that there isn't actual concurrency since things like `maybeAddBlockPropertiesToBlockHandle` will break in the current code if we add actual concurrency. Given this will change in a later PR, I am assuming only the former use case will remain. Is my understanding correct?

Also I am wondering whether it would be simpler to have a writerQueue.syncWrite that shares most of the code that is currently there but runs in the caller's goroutine. I suspect I am missing something important here about the "fallback" case -- could you elaborate a bit, or point me to the discussion in the other PR?
___
*[sstable/writer.go, line 1335 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MtyDKbG0G4fW5eRIRsJ:-MuC1imd7bgtt-wJc2Zk:b-6jb4kf) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L1335)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

`dataBlockBuffers` is a channel instead of `sync.Pool`, because this pr only handles the synchronous case, and I needed the buffer to have a max size of 1, and block when the channel is empty.
</blockquote></details>

I think this partially answers my earlier question. Is your current plan to remove this in a future PR and switch to a `sync.Pool`?


<!-- Sent from Reviewable.io -->

2022-01-24 17:25 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1466)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[sstable/writer.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuBy2Q_5N-Nak4JtT-B:-MuC2duG92CQbc45w5Qd:b-66ztao) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L171)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm unclear why this is a channel instead of a plain `error` field. There is never going to be more than one worker in `writeQueue` so there is only 1 writer which is doing peculiar things like trying to write to the channel once in order to avoid blocking. It seems to me that this channel is simply providing read-write synchronization, in which case a simpler alternative would be to add a `Writer.SetError` method and guard the `Writer.err` field using a mutex. It seems to also simplify what happens in `Writer.Error` which currently tries to pull from the channel if w.err is not already nil.
</blockquote></details>

Yea, that's a good idea. I was trying to avoid a mutex, but having a mutex to guard the error field seems okay. Another option is to return the error only when `writeQueue.finish` is called. This will avoid any need for extra synchronization. This method will waste some resources as the Writer client goroutine(the goroutine which calls `Writer.Add` will continue to add keys until `Writer.Close` is close is called. But this might be okay if an error while sstable is being written is rare.
___
*[sstable/writer.go, line 760 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuBzNj669VjT2Z7Ys3b:-MuC3UC0DnuuaFJSP7Jr:beynlrx) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L760)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I was wondering about `dataBlockBuffers`. It seems we are using this for:
- reuse of the scratch space provided by `dataBlockBuf`, for which we could also use a `sync.Pool`?
- ensuring that there isn't actual concurrency since things like `maybeAddBlockPropertiesToBlockHandle` will break in the current code if we add actual concurrency. Given this will change in a later PR, I am assuming only the former use case will remain. Is my understanding correct?

Also I am wondering whether it would be simpler to have a writerQueue.syncWrite that shares most of the code that is currently there but runs in the caller's goroutine. I suspect I am missing something important here about the "fallback" case -- could you elaborate a bit, or point me to the discussion in the other PR?


</blockquote></details>

Reuse of the scratch space is one of the primary purposes. Another primary purpose is that a `dataBlockBuffer` clearly defines all the data we need to do a compression, and a block write. Because of the underlying buffers throughout the `Writer`, and even within the `blockWriter`, it's difficult to reason about which goroutine owns which buffers/data without the `dataBlockBuf`.

Yea, I considered adding a `syncWrite` method, which would wait until all the pending items added to the queue, have been written.

Currently, we have the following cases for compression/writes:
1. If parallel compression is enabled for a `Writer`:
     a. We'll use the `writeQueue` for writing blocks, and a compression queue for compression.
     b. If the compression queue is "full", then we'll "fallback" and do the compression in the `Writer` client goroutine, and add a 
       `writeTask` to the `writeQueue`.
2. If parallel compression is disabled for a `Writer`:
     a. We'll compress the block in the `Writer` client goroutine(same as the "fallback" case), and add a `writeTask` to the 
       `writeQueue`.
     b. The `Writer` client goroutine will block while waiting for any `writeTask` added to the `writeQueue` to finish. This 
         preserves the current behaviour in the `Writer`.

Adding a `syncWrite` to the queue, will add another case, where we explicitly call `syncWrite` each time a `writeTask` is added to the queue. We can do this when parallel compression is disabled.
___
*[sstable/writer.go, line 1335 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MtyDKbG0G4fW5eRIRsJ:-MuC6WFH5qz8t1BeEuGW:b-1ctn80) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L1335)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think this partially answers my earlier question. Is your current plan to remove this in a future PR and switch to a `sync.Pool`?
</blockquote></details>

Not necessarily. I would always need a way to block while the write finishes in the case where parallel compression is disabled. But I think a `syncWrite` a method in the queue might be a better way to do that instead of implicitly doing this using the buffers.


<!-- Sent from Reviewable.io -->

2022-01-24 18:13 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1466)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @sumeerbhola)

___
*[sstable/writer.go, line 760 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuBzNj669VjT2Z7Ys3b:-MuCGD5S9BeVjS7dZK3G:b-gojym0) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L760)):*
> it's difficult to reason about which goroutine owns which buffers/data without the dataBlockBuf.

That makes sense. I have no issues with `dataBlockBuf` or passing it in some cases via a channel. It was the return for reuse via the channel which looked a bit odd. Given that the DB uses the same data block size for its lifetime, it seemed the reuse case could be better served by a `sync.Pool` since that also works across `Writer`s, so a new writer does not have to start with empty buffers and do allocations.

Thanks for clarifying the fallback behavior. 


<!-- Sent from Reviewable.io -->

2022-01-25 02:26 UTC, bananabrick commented
Some benchstat results for ycsb/size=64`

Machine with large ssd
```
arjunnair@crlMBP-C02FR0UTMD6TMjA4 jan24 % benchstat stat_basic_16 stat_par_16             
name              old ops/sec  new ops/sec  delta
ycsb/E/values=64    189k ± 4%    188k ± 6%    ~     (p=0.690 n=5+5)
ycsb/A/values=64    293k ± 3%    320k ± 2%  +9.19%  (p=0.008 n=5+5)
ycsb/D/values=64    599k ± 3%    595k ± 2%    ~     (p=0.690 n=5+5)
ycsb/F/values=64    153k ± 2%    147k ± 2%  -3.34%  (p=0.016 n=5+5)
ycsb/C/values=64   2.45M ±29%   2.62M ± 9%    ~     (p=0.548 n=5+5)
ycsb/B/values=64    957k ± 6%    912k ± 7%    ~     (p=0.151 n=5+5)

name              old read     new read     delta
ycsb/E/values=64   47.4G ± 4%   46.9G ± 5%    ~     (p=0.690 n=5+5)
ycsb/A/values=64    104G ± 3%    114G ± 2%  +9.13%  (p=0.008 n=5+5)
ycsb/D/values=64   81.6G ± 3%   80.6G ± 2%    ~     (p=0.310 n=5+5)
ycsb/F/values=64    377G ± 2%    362G ± 2%  -4.16%  (p=0.008 n=5+5)
ycsb/C/values=64   3.02G ± 9%   3.10G ± 2%    ~     (p=0.548 n=5+5)
ycsb/B/values=64   57.4G ± 6%   55.6G ± 8%    ~     (p=0.421 n=5+5)

name              old write    new write    delta
ycsb/E/values=64   50.9G ± 4%   50.3G ± 5%    ~     (p=0.690 n=5+5)
ycsb/A/values=64    137G ± 3%    150G ± 2%  +9.12%  (p=0.008 n=5+5)
ycsb/D/values=64   92.8G ± 3%   91.7G ± 2%    ~     (p=0.310 n=5+5)
ycsb/F/values=64    435G ± 2%    417G ± 2%  -4.05%  (p=0.008 n=5+5)
ycsb/C/values=64   2.93G ± 9%   3.01G ± 2%    ~     (p=0.548 n=5+5)
ycsb/B/values=64   68.3G ± 6%   65.9G ± 7%    ~     (p=0.310 n=5+5)

name              old r-amp    new r-amp    delta
ycsb/E/values=64    3.09 ± 2%    3.07 ± 1%    ~     (p=0.246 n=5+5)
ycsb/A/values=64    4.46 ± 1%    4.55 ± 0%  +2.02%  (p=0.008 n=5+5)
ycsb/D/values=64    4.20 ± 0%    4.20 ± 0%    ~     (p=0.444 n=5+5)
ycsb/F/values=64    0.00         0.00         ~     (all equal)
ycsb/C/values=64    1.09 ± 4%    1.08 ± 2%    ~     (p=0.619 n=4+5)
ycsb/B/values=64    3.55 ± 0%    3.56 ± 0%    ~     (p=0.171 n=4+4)

name              old w-amp    new w-amp    delta
ycsb/E/values=64    24.2 ± 0%    24.1 ± 1%    ~     (p=0.444 n=5+5)
ycsb/A/values=64    4.21 ± 0%    4.20 ± 0%    ~     (p=0.095 n=5+4)
ycsb/D/values=64    13.9 ± 1%    13.9 ± 1%    ~     (p=0.198 n=5+5)
ycsb/F/values=64    12.8 ± 1%    12.7 ± 0%  -0.73%  (p=0.048 n=5+5)
ycsb/C/values=64    0.00         0.00         ~     (all equal)
ycsb/B/values=64    6.42 ± 1%    6.43 ± 0%    ~     (p=0.302 n=5+4)

```

machines used to run the nightlies
```
arjunnair@crlMBP-C02FR0UTMD6TMjA4 jan24 % benchstat stat_basic_1 stat_par_1              
name              old ops/sec  new ops/sec  delta
ycsb/E/values=64    231k ± 5%    230k ± 5%   ~     (p=0.690 n=5+5)
ycsb/A/values=64    881k ± 8%    879k ± 8%   ~     (p=0.841 n=5+5)
ycsb/D/values=64    665k ± 4%    664k ± 4%   ~     (p=0.841 n=5+5)
ycsb/F/values=64    200k ± 1%    200k ± 0%   ~     (p=0.841 n=5+5)
ycsb/C/values=64   2.93M ±22%   3.10M ± 9%   ~     (p=1.000 n=5+5)
ycsb/B/values=64   1.19M ± 7%   1.20M ± 8%   ~     (p=1.000 n=5+5)

name              old read     new read     delta
ycsb/E/values=64   57.6G ± 6%   57.8G ± 5%   ~     (p=0.841 n=5+5)
ycsb/A/values=64    217G ± 4%    213G ± 4%   ~     (p=0.222 n=5+5)
ycsb/D/values=64   92.0G ± 5%   92.1G ± 5%   ~     (p=1.000 n=5+5)
ycsb/F/values=64    513G ± 1%    513G ± 0%   ~     (p=1.000 n=5+5)
ycsb/C/values=64   3.00G ± 9%   3.13G ± 2%   ~     (p=0.222 n=5+5)
ycsb/B/values=64   71.7G ± 7%   71.8G ± 7%   ~     (p=1.000 n=5+5)

name              old write    new write    delta
ycsb/E/values=64   61.8G ± 6%   62.0G ± 5%   ~     (p=0.841 n=5+5)
ycsb/A/values=64    316G ± 5%    311G ± 5%   ~     (p=0.548 n=5+5)
ycsb/D/values=64    104G ± 5%    104G ± 5%   ~     (p=1.000 n=5+5)
ycsb/F/values=64    587G ± 1%    588G ± 0%   ~     (p=1.000 n=5+5)
ycsb/C/values=64   2.91G ± 9%   3.04G ± 2%   ~     (p=0.222 n=5+5)
ycsb/B/values=64   85.0G ± 7%   85.2G ± 7%   ~     (p=1.000 n=5+5)

name              old r-amp    new r-amp    delta
ycsb/E/values=64    3.09 ± 1%    3.09 ± 1%   ~     (p=0.976 n=5+5)
ycsb/A/values=64    6.55 ± 3%    6.63 ± 3%   ~     (p=0.206 n=5+5)
ycsb/D/values=64    4.19 ± 0%    4.19 ± 0%   ~     (p=0.905 n=5+5)
ycsb/F/values=64    0.00         0.00        ~     (all equal)
ycsb/C/values=64    1.06 ± 1%    1.07 ± 2%   ~     (p=0.762 n=4+5)
ycsb/B/values=64    3.56 ± 1%    3.55 ± 0%   ~     (p=0.486 n=4+4)

name              old w-amp    new w-amp    delta
ycsb/E/values=64    24.1 ± 1%    24.3 ± 0%   ~     (p=0.421 n=5+5)
ycsb/A/values=64    3.23 ± 3%    3.19 ± 3%   ~     (p=0.206 n=5+5)
ycsb/D/values=64    14.1 ± 0%    14.2 ± 1%   ~     (p=0.476 n=5+5)
ycsb/F/values=64    13.2 ± 0%    13.2 ± 0%   ~     (p=0.206 n=5+5)
ycsb/C/values=64    0.00         0.00        ~     (all equal)
ycsb/B/values=64    6.41 ± 0%    6.41 ± 1%   ~     (p=0.444 n=4+5)
```

2022-01-25 23:14 UTC, itsbilal reviewed
Looking pretty good! Just some minor comments. Will wait for the `w.task` change before doing a deeper dive.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1466#-:-MuIWB7uBRKgNqDdqkTM:b-sl3kqw)* status: all files reviewed, 9 unresolved discussions (waiting on @bananabrick, @jbowens, and @sumeerbhola)

___
*[sstable/write_queue.go, line 17 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MtyCmB_BENCo4K2AgKH:-MuIGT4WB791TWIexEIU:bqz5pac) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/write_queue.go#L17)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I'm passing the key for the current synchronous implementation. Once I refactor `addIndexEntry` for the asynchronous implementation, this should no longer be required. The refactor of `addIndexEntry` is pretty complicated, and also needs changes to the `EstimatedSize` function, so I left it out for a separate pr.
</blockquote></details>

This makes sense. Do you mind renaming this to `indexKey` to make it clear this key isn't something we're writing to the block, and is just for index separator calculation?
___
*[sstable/write_queue.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuINROH5D-VwxR8aaK4:-MuINROH5D-VwxR8aaK5:b-rhhspm) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/write_queue.go#L41)):*
> ```Go
> }
> 
> func (w *writeQueue) runWorker() {
> ```

There will only be one write worker per writer, right? We're only parallelizing compression, not the write of the compressed block below. 
___
*[sstable/write_queue.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuIUKtN56-93LrOQrOa:-MuIUKtN56-93LrOQrOb:b-7g43d3) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/write_queue.go#L50)):*
> ```Go
> 		var err error
> 		if w.err == nil {
> 			err = func() error {
> ```

This sounds like an easy candidate for a separate helper function.
___
*[sstable/writer.go, line 751 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuILkFi7RtZvQ7qenqX:-MuILkFjBgIJNmBvbWmL:bnkiggo) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L751)):*
> ```Go
> 
> 		writeTask := writeQueueTasks.Get().(*writeTask)
> 		writeTask.compressionDone <- true
> ```

Could probably add a comment here that you're setting this struct the same way as if a compression was already completed asynchronously.
___
*[sstable/writer.go, line 755 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MtyDZWu-h41plOyYXQW:-MuIN7_B4Ei0AIHCnb6b:b-r4les7) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L755)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

There is still a cost to the channel writes/reads, and goroutine context switching. I got around that in my previous writeQueue pr by making the writeQueue an interface and having a separate implementation for when parallel compression is disabled.

Note that even in the "fallback" case we discussed where the queues are full, and we decide to do the compression in the Writer client goroutine, we still need to use the write queue. This is because the writeQueue needs to handle all the data block writes to maintain order.
</blockquote></details>

It'd be good if we could eliminate this overhead and it looks like you're already working away at that. I'll think of whether I can come up with other designs that do away with the need to do this `writeQueue.add` and the channel write/read from `w.tasks`, that exploit the fact that you only have one `writeQueue` worker per writer. But yes, your performance regression is likely coming from the time spent waiting for the channel to empty out and for the worker to catch up.
___
*[sstable/writer.go, line 1347 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MtyDF7X90AGQbCYECqr:-MuH_9rM0OMSMWRb_QKv:b-lvlb3e) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L1347)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

The queue has a size of 1, because this pr only handles the synchronous case, and the queue doesn't need to be larger.
</blockquote></details>

This makes sense. Do you mind adding a comment there about this as well? It can come off when you add the async case.


<!-- Sent from Reviewable.io -->

2022-01-26 18:55 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1466)* status: all files reviewed, 6 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @sumeerbhola)

___
*[sstable/write_queue.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuINROH5D-VwxR8aaK4:-MuMhuBg5Gp9o503V-jN:beiv1y0) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/write_queue.go#L41)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

There will only be one write worker per writer, right? We're only parallelizing compression, not the write of the compressed block below. 
</blockquote></details>

yep. Although that writer can write blocks in parallel.
___
*[sstable/write_queue.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuIUKtN56-93LrOQrOa:-MuMhyUf-MMWULU5AM8v:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/write_queue.go#L50)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

This sounds like an easy candidate for a separate helper function.
</blockquote></details>

Done.
___
*[sstable/writer.go, line 760 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuBzNj669VjT2Z7Ys3b:-MuMi71JDMwe-XjT5Kup:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L760)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> it's difficult to reason about which goroutine owns which buffers/data without the dataBlockBuf.

That makes sense. I have no issues with `dataBlockBuf` or passing it in some cases via a channel. It was the return for reuse via the channel which looked a bit odd. Given that the DB uses the same data block size for its lifetime, it seemed the reuse case could be better served by a `sync.Pool` since that also works across `Writer`s, so a new writer does not have to start with empty buffers and do allocations.

Thanks for clarifying the fallback behavior. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-26 21:38 UTC, bananabrick reviewed
I was able to get rid of the perf issue by adding a `writeQueue.addSync` call. This prevents the cost which mostly seemed to be from the goroutine context switching and a channel send/read from `writeQueue.task`, and a channel send/read from the `dataBlockBuffers`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1466#-:-MuNIkEO7R7oRLYNWDzT:b118rz9)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @sumeerbhola)

___
*[sstable/write_queue.go, line 96 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuNJ2He5hrijMn5g4YF:-MuNJ2He5hrijMn5g4YG:b-6y1mjk) ([raw file](https://github.com/cockroachdb/pebble/blob/42ec424f771f357a0563baaeac489c65bd649e5d/sstable/write_queue.go#L96)):*
> ```Go
> func (w *writeQueue) addSync(task *writeTask) error {
> 	// This should instantly return without blocking.
> 	<-task.compressionDone
> ```

We technically don't need to read `compressionDone` here since it's a function invariant that compression must be done before `addSync` is called. However, it's not causing perf issues, and it's nice to not add an edge case for `writeTask.compressionDone` and just always set it.
___
*[sstable/write_queue.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuNJOtm57qsZXzoGMfV:-MuNJOtm57qsZXzoGMfW:b-t8xq4h) ([raw file](https://github.com/cockroachdb/pebble/blob/42ec424f771f357a0563baaeac489c65bd649e5d/sstable/write_queue.go#L110)):*
> ```Go
> // finish should only be called once no more tasks will be added to the writeQueue.
> // finish will return any error which was encountered while tasks were processed.
> func (w *writeQueue) finish() error {
> ```

We only return any error encountered once `writeQueue.finish` is called. This has some implications, but I don't think they're important enough to not do it this way. The error handling code is really simplified here.
___
*[sstable/writer.go, line 1321 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuNJdf_6RYnFndH6sW8:-MuNJdf_6RYnFndH6sW9:b-e8n5fz) ([raw file](https://github.com/cockroachdb/pebble/blob/42ec424f771f357a0563baaeac489c65bd649e5d/sstable/writer.go#L1321)):*
> ```Go
> 		},
> 		coalescer: rangekey.Coalescer{},
> 		dataBlockBuffers: sync.Pool{
> ```

I didn't make this pool global, cause it relies on the `o.restartInterval`, and `o.Checksum`.


<!-- Sent from Reviewable.io -->

2022-01-27 01:22 UTC, sumeerbhola requested changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1466)* status: 1 of 3 files reviewed, 11 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @sumeerbhola)

___
*[sstable/write_queue.go, line 92 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuO2YEZ7NWWmh08LK55:-MuO2YE_7e1Uk0noQcqy:bfek0by) ([raw file](https://github.com/cockroachdb/pebble/blob/ecc6105a0084c7406a455c2ab4208a8677eef0cc/sstable/write_queue.go#L92)):*
> ```Go
> 
> // addSync will perform the writeTask synchronously with the caller goroutine. Calls to addSync
> // are no longer valid once writeQueue.add has been called at least once.
> ```

I think it's worth clarifying whether a caller can mix `add` and `addSync`. I assume not.
___
*[sstable/writer.go, line 1321 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuNJdf_6RYnFndH6sW8:-MuO429h6RKDzIVmzsnM:b30xppb) ([raw file](https://github.com/cockroachdb/pebble/blob/42ec424f771f357a0563baaeac489c65bd649e5d/sstable/writer.go#L1321)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I didn't make this pool global, cause it relies on the `o.restartInterval`, and `o.Checksum`.
</blockquote></details>

We can overrride those fields. Something like:
```
func newDataBlockBuf(restartInterval int, checksumType ChecksumType) *dataBlockBuf {
   d := dataBlockBufPool.Get().(*dataBlockBuf)
   d.dataBlock.blockWriter.restartInterval = restartInterval
   d.checksummer.checksumType = checksumType
   return d
}
```
___
*[sstable/writer.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuO38DM8D64jCPDoe-i:-MuO38DM8D64jCPDoe-j:br1qakm) ([raw file](https://github.com/cockroachdb/pebble/blob/ecc6105a0084c7406a455c2ab4208a8677eef0cc/sstable/writer.go#L171)):*
> ```Go
> 		writeQueue *writeQueue
> 		// errCh is a buffered channel of size 1, and it will be written to at most once.
> 		errCh chan error
> ```

is `errCh` being used?


<!-- Sent from Reviewable.io -->

2022-01-27 01:54 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1466)* status: 0 of 3 files reviewed, 10 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[sstable/write_queue.go, line 92 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuO2YEZ7NWWmh08LK55:-MuO9YBlChiU1W9FMoE3:bc22xni) ([raw file](https://github.com/cockroachdb/pebble/blob/ecc6105a0084c7406a455c2ab4208a8677eef0cc/sstable/write_queue.go#L92)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think it's worth clarifying whether a caller can mix `add` and `addSync`. I assume not.
</blockquote></details>

We can mix them. As long as all calls to `addSync` happen before any calls to `add` happen. I could've allowed them to be interleaved, but it was adding a bit of overhead, and it isn't required.
___
*[sstable/writer.go, line 751 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuILkFi7RtZvQ7qenqX:-MuO9txP6LioYEaUELt_:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/89e3c8a86c8cd4391dd25b2a09fa1f8754a5a684/sstable/writer.go#L751)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Could probably add a comment here that you're setting this struct the same way as if a compression was already completed asynchronously.
</blockquote></details>

Done.
___
*[sstable/writer.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1466#-MuO38DM8D64jCPDoe-i:-MuO9pgq3Qgoz2KvxXfr:b-u2kp9z) ([raw file](https://github.com/cockroachdb/pebble/blob/ecc6105a0084c7406a455c2ab4208a8677eef0cc/sstable/writer.go#L171)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is `errCh` being used?
</blockquote></details>

Oops, thanks.


<!-- Sent from Reviewable.io -->

2022-01-27 19:00 UTC, bananabrick commented
Here's the changes from the microbenchmarks. Differences are trivial enough to not be a concern.

```
arjunnair@gceworker-arjunnair:~/go/src/github.com/cockroachdb/pebble$ benchstat t3 t6
name                                                          old time/op    new time/op    delta
Writer/block=4.0_K/filter=true/compression=NoCompression-24      136ms ± 2%     139ms ± 2%  +2.56%  (p=0.017 n=6+5)
Writer/block=4.0_K/filter=true/compression=Snappy-24             162ms ± 1%     165ms ± 1%  +1.91%  (p=0.004 n=6+5)
Writer/block=4.0_K/filter=true/compression=ZSTD-24               502ms ± 2%     509ms ± 1%    ~     (p=0.095 n=5+5)
Writer/block=4.0_K/filter=false/compression=NoCompression-24    85.9ms ± 1%    87.4ms ± 2%  +1.77%  (p=0.004 n=6+5)
Writer/block=4.0_K/filter=false/compression=Snappy-24            112ms ± 2%     114ms ± 2%    ~     (p=0.082 n=6+5)
Writer/block=4.0_K/filter=false/compression=ZSTD-24              452ms ± 6%     452ms ± 2%    ~     (p=0.429 n=6+5)
Writer/block=32_K/filter=true/compression=NoCompression-24       133ms ± 1%     134ms ± 0%    ~     (p=0.222 n=5+5)
Writer/block=32_K/filter=true/compression=Snappy-24              156ms ± 2%     154ms ± 1%    ~     (p=0.421 n=5+5)
Writer/block=32_K/filter=true/compression=ZSTD-24                239ms ± 0%     243ms ± 2%  +1.57%  (p=0.008 n=5+5)
Writer/block=32_K/filter=false/compression=NoCompression-24     81.7ms ± 1%    82.8ms ± 1%    ~     (p=0.082 n=6+5)
Writer/block=32_K/filter=false/compression=Snappy-24             103ms ± 1%     102ms ± 0%    ~     (p=0.247 n=6+5)
Writer/block=32_K/filter=false/compression=ZSTD-24               186ms ± 1%     186ms ± 0%    ~     (p=1.000 n=6+5)

name                                                          old speed      new speed      delta
Writer/block=4.0_K/filter=true/compression=NoCompression-24    291MB/s ± 2%   284MB/s ± 2%  -2.50%  (p=0.017 n=6+5)
Writer/block=4.0_K/filter=true/compression=Snappy-24          67.9MB/s ± 1%  66.7MB/s ± 1%  -1.87%  (p=0.004 n=6+5)
Writer/block=4.0_K/filter=true/compression=ZSTD-24            11.9MB/s ± 2%  11.8MB/s ± 1%    ~     (p=0.087 n=5+5)
Writer/block=4.0_K/filter=false/compression=NoCompression-24   446MB/s ± 1%   438MB/s ± 2%  -1.74%  (p=0.004 n=6+5)
Writer/block=4.0_K/filter=false/compression=Snappy-24         87.1MB/s ± 2%  86.0MB/s ± 2%    ~     (p=0.082 n=6+5)
Writer/block=4.0_K/filter=false/compression=ZSTD-24           10.5MB/s ± 6%  10.5MB/s ± 2%    ~     (p=0.429 n=6+5)
Writer/block=32_K/filter=true/compression=NoCompression-24     293MB/s ± 1%   292MB/s ± 0%    ~     (p=0.222 n=5+5)
Writer/block=32_K/filter=true/compression=Snappy-24           51.6MB/s ± 2%  52.1MB/s ± 1%    ~     (p=0.421 n=5+5)
Writer/block=32_K/filter=true/compression=ZSTD-24             14.3MB/s ± 0%  14.1MB/s ± 2%  -1.55%  (p=0.008 n=5+5)
Writer/block=32_K/filter=false/compression=NoCompression-24    463MB/s ± 1%   456MB/s ± 1%    ~     (p=0.082 n=6+5)
Writer/block=32_K/filter=false/compression=Snappy-24          65.9MB/s ± 1%  66.2MB/s ± 0%    ~     (p=0.247 n=6+5)
Writer/block=32_K/filter=false/compression=ZSTD-24            11.7MB/s ± 1%  11.7MB/s ± 0%    ~     (p=1.000 n=6+5)

name                                                          old alloc/op   new alloc/op   delta
Writer/block=4.0_K/filter=true/compression=NoCompression-24     25.1MB ± 0%    25.1MB ± 0%  +0.01%  (p=0.004 n=6+5)
Writer/block=4.0_K/filter=true/compression=Snappy-24            25.1MB ± 0%    25.1MB ± 0%  +0.02%  (p=0.004 n=6+5)
Writer/block=4.0_K/filter=true/compression=ZSTD-24              84.1MB ± 0%    84.1MB ± 0%  +0.02%  (p=0.008 n=5+5)
Writer/block=4.0_K/filter=false/compression=NoCompression-24     799kB ± 0%     800kB ± 0%  +0.10%  (p=0.004 n=6+5)
Writer/block=4.0_K/filter=false/compression=Snappy-24            829kB ± 0%     830kB ± 0%  +0.11%  (p=0.004 n=6+5)
Writer/block=4.0_K/filter=false/compression=ZSTD-24             59.8MB ± 0%    59.9MB ± 0%  +0.02%  (p=0.004 n=6+5)
Writer/block=32_K/filter=true/compression=NoCompression-24      25.2MB ± 0%    25.2MB ± 0%  +0.01%  (p=0.004 n=6+5)
Writer/block=32_K/filter=true/compression=Snappy-24             25.4MB ± 0%    25.5MB ± 0%  +0.01%  (p=0.004 n=6+5)
Writer/block=32_K/filter=true/compression=ZSTD-24               74.1MB ± 0%    74.1MB ± 0%  +0.01%  (p=0.008 n=5+5)
Writer/block=32_K/filter=false/compression=NoCompression-24      953kB ± 0%     954kB ± 0%  +0.07%  (p=0.004 n=6+5)
Writer/block=32_K/filter=false/compression=Snappy-24            1.16MB ± 0%    1.16MB ± 0%  +0.06%  (p=0.004 n=6+5)
Writer/block=32_K/filter=false/compression=ZSTD-24              49.8MB ± 0%    49.8MB ± 0%  +0.01%  (p=0.004 n=6+5)

name                                                          old allocs/op  new allocs/op  delta
Writer/block=4.0_K/filter=true/compression=NoCompression-24        146 ± 1%       154 ± 1%  +4.97%  (p=0.004 n=6+5)
Writer/block=4.0_K/filter=true/compression=Snappy-24               151 ± 0%       159 ± 2%  +5.30%  (p=0.008 n=5+5)
Writer/block=4.0_K/filter=true/compression=ZSTD-24               85.2k ± 0%     85.2k ± 0%  +0.03%  (p=0.008 n=5+5)
Writer/block=4.0_K/filter=false/compression=NoCompression-24       100 ± 0%       104 ± 0%  +4.00%  (p=0.008 n=5+5)
Writer/block=4.0_K/filter=false/compression=Snappy-24              106 ± 0%       110 ± 0%  +3.77%  (p=0.010 n=6+4)
Writer/block=4.0_K/filter=false/compression=ZSTD-24              85.2k ± 0%     85.2k ± 0%  +0.02%  (p=0.004 n=6+5)
Writer/block=32_K/filter=true/compression=NoCompression-24         140 ± 0%       148 ± 0%  +5.18%  (p=0.004 n=6+5)
Writer/block=32_K/filter=true/compression=Snappy-24                145 ± 0%       153 ± 0%  +5.00%  (p=0.004 n=6+5)
Writer/block=32_K/filter=true/compression=ZSTD-24                10.5k ± 0%     10.6k ± 0%  +0.15%  (p=0.004 n=6+5)
Writer/block=32_K/filter=false/compression=NoCompression-24       95.0 ± 0%      98.6 ± 1%  +3.79%  (p=0.004 n=6+5)
Writer/block=32_K/filter=false/compression=Snappy-24               100 ± 0%       103 ± 0%  +3.00%  (p=0.016 n=5+4)
Writer/block=32_K/filter=false/compression=ZSTD-24               10.5k ± 0%     10.5k ± 0%  +0.12%  (p=0.004 n=6+5)
```

2022-01-27 19:24 UTC, sumeerbhola reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once @itsbilal is satisfied

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1466#-:-MuRzejP8UcX2kNGeGRk:bqe2gsm)* status: 0 of 3 files reviewed, 10 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-01-27 21:11 UTC, itsbilal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

I like that `addSync` avoids the need to use the `tasks` channel in its entirety. I was thinking of ways to allow interleaving of add and addSync calls more actively, in cases where all compression workers are full so we're compressing ourselves in the writer goroutine, but parallel compression is also enabled and we want to order the write blocks correctly that are coming off of the compression goroutines. But it's probably too much of a hassle to handle and may not even net as much a win compared to just adding it to the channel using `add`.

> Reviewed 1 of 3 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1466#-:-MuSJAtQ8Q9LH2Abk3t3:b-oac90i)* status: all files reviewed, 7 unresolved discussions (waiting on @jbowens and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-01-27 21:26 UTC, merged