*: infer `sstable.TableFormat` from `FormatMajorVerison`
cockroachdb/pebble pull request #1471
Opened 2022-01-25 00:53 UTC by nicktrav

The [Pebble SSTable Format Versions RFC][1] outlines a new versioning
scheme used for new SSTable-level features. The RFC also outlines a
requirement that external callers (i.e. Cockroach) ensure that the
format version is compatible with other stores in a cluster.

To ensure tables are created with an explicit version, the
`(*pebble.Options).NewWriterOptions` method now takes an additional
parameter that specifies the format version to be used when writing a
table. Previous the table format was pinned at RocksDBv2.

Expose a `(FormatMajorVersion).MaxTableFormat()` method that returns the
maximum allowable table format for the given `FormatMajorVersion`. This
can be used to ensure that given a store major version, an
`sstable.Writer` is capped at writing tables with a maximum table
format, to ensure compatibility with other stores running at the same
version.

New `sstable.Writer`s within Pebble itself (in contrast to `Writer`s
created _external_ to a Pebble store, e.g. Cockroach generating a table
for backup or ingestion) select the table format by consulting the
current value of `(*DB).FormatMajorVersion()` and then infer the maximum
allowable version from `(FormatMajorVersion).MaxTableFormat()`.

Update the table footer encode and decode functions to take into account
the new Pebble magic string. This new magic string implies a
Pebble-specific versioning scheme (with v1 for block properties and v2
for range keys) with the same table footer format used in RocksDBv2.

Add a compatibility check to the table write path to assert that the
presence of specific features on a table must be accompanied by the
appropriate table format (i.e. block properties must be at least version
PebbleDBv1, etc.).

Update existing tests that need to make use of newer Pebble table
features (i.e. block properties and / or range keys) to explicitly set
the table format to opt-into the newer features.

[1]: ./docs/RFCS/20220112_pebble_sstable_format_versions.md

2022-01-25 00:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1471)
<!-- Reviewable:end -->

2022-01-25 01:04 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1471)* status: 0 of 15 files reviewed, all discussions resolved (waiting on @jbowens and @sumeerbhola)

___
*[sstable/options.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuDiOaW4TRrgh1RyRxG:-MuDiOaX7DEgBVJWghIt:bxo1qns) ([raw file](https://github.com/cockroachdb/pebble/blob/fb565532fa54b32412b70d1ea8b98f6da5aaeb36/sstable/options.go#L224)):*
> ```Go
> 		o.Checksum = ChecksumTypeCRC32c
> 	}
> 	// By default, if the table format is not specified, fall back to using the
> ```

I kept this the way it was, as a lot of the existing tests create a writer using `sstable.NewWriter()` and rely on it calling `(WriterOptions).ensureDefaults()` to populate the format version in the case that it is not specified. Requiring an explicit version would result in needing up update a lot of call sites. Maybe this is what we want?

I confirmed that the non-test codepaths that call `sstable.NewWriter()` (and thus `ensureDefaults()`) are all passing opts that have the table format explicitly set, though that doesn't prevent someone adding a new call site (internal or external to Pebble), forgetting to set the table format, then having Pebble fall back to writing with RocksDBv2.
___
*[sstable/table.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuDjwmW9t5XSKbbizr0:-MuDjwmW9t5XSKbbizr1:bdhv9hm) ([raw file](https://github.com/cockroachdb/pebble/blob/fb565532fa54b32412b70d1ea8b98f6da5aaeb36/sstable/table.go#L177)):*
> ```Go
> 	rocksDBExternalFormatVersion = 2
> 
> 	pebbleDBMagic = "\xf0\x9f\xaa\xb3\xf0\x9f\xaa\xb3" // 🪳🪳
> ```

Interestingly, the LevelDB magic string is the _reverse_ of the first 8 bytes of the SHA1. Given that endianness doesn't really apply to strings, I'm just writing these bytes in order. We also just check the literal string on the read path, so I'm not sure why the LevelDB string was reversed in the first place.


<!-- Sent from Reviewable.io -->

2022-01-25 16:38 UTC, jbowens reviewed
looks great, just a couple nits

> Reviewed 3 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1471#-:-MuH5VIk8o_-ADpX2wHU:b-io2srt)* status: 3 of 15 files reviewed, 4 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[format_major_version.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuH0X4F9x_JmL8qLG3D:-MuH0X4F9x_JmL8qLG3E:bt1qhiy) ([raw file](https://github.com/cockroachdb/pebble/blob/fb565532fa54b32412b70d1ea8b98f6da5aaeb36/format_major_version.go#L90)):*
> ```Go
> 		return sstable.TableFormatPebbleDBv1, nil
> 	default:
> 		return sstable.TableFormatUnspecified, errors.Newf("pebble: unsupported format major version: %s", v)
> ```

what do you think about making `MaxTableFormat()` infallible and panicking if `v` is not a valid `FormatMajorVersion` enum value? I think it's a reasonable a panic because it's a programming error to construct an invalid `FormatMajorVersion` enum value.
___
*[sstable/format.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuH30qY8hf3FvsDKgEG:-MuH30qY8hf3FvsDKgEH:b-inv007) ([raw file](https://github.com/cockroachdb/pebble/blob/fb565532fa54b32412b70d1ea8b98f6da5aaeb36/sstable/format.go#L25)):*
> ```Go
> 	TableFormatRocksDBv2
> 	TableFormatPebbleDBv1 // Block properties.
> 	TableFormatPebbleDBv2 // Range keys.
> ```

nit: maybe drop the `DB` from the Pebble constants? I think most (all?) places we stylize it as 'Pebble' without 'DB'
___
*[sstable/format.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuH3JmtBbK4NqEquXMs:-MuH3JmtBbK4NqEquXMt:b-qndw40) ([raw file](https://github.com/cockroachdb/pebble/blob/fb565532fa54b32412b70d1ea8b98f6da5aaeb36/sstable/format.go#L32)):*
> ```Go
> // ParseTableFormat parses the given magic string and version into its
> // corresponding internal TableFormat.
> func ParseTableFormat(magic string, version uint32) (TableFormat, error) {
> ```

nit: I'm not sure, but I think this will allocate when the caller converts the magic string byte slice to a `string` to pass into `ParseTableFormat`. I think if we took in the `[]byte` but did the string conversion in the switch, `switch string(magic) {`, Go is able to infer that it's only used for a comparison and omit the string allocation.
___
*[format_major_version_test.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuH2pDg3XRf1X4t_71c:-MuH2pDg3XRf1X4t_71d:b-k6du6o) ([raw file](https://github.com/cockroachdb/pebble/blob/fb565532fa54b32412b70d1ea8b98f6da5aaeb36/format_major_version_test.go#L179)):*
> ```Go
> }
> 
> func TestFormatMajorVersions_TableFormat(t *testing.T) {
> ```

Nice test


<!-- Sent from Reviewable.io -->

2022-01-25 22:12 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1471)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[format_major_version.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuH0X4F9x_JmL8qLG3D:-MuHsKEy-_dFjqCuqjgz:bchj51v) ([raw file](https://github.com/cockroachdb/pebble/blob/fb565532fa54b32412b70d1ea8b98f6da5aaeb36/format_major_version.go#L90)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

what do you think about making `MaxTableFormat()` infallible and panicking if `v` is not a valid `FormatMajorVersion` enum value? I think it's a reasonable a panic because it's a programming error to construct an invalid `FormatMajorVersion` enum value.
</blockquote></details>

Sounds reasonable. I had the same thought but then thought that this is exposed outside of Pebble and I'm generally wary of having a library causing panics.

Given this is truly a programmer error, it's probably less of an issue at runtime. Updated.
___
*[sstable/format.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuH30qY8hf3FvsDKgEG:-MuHt1tu6D7J24sWpYmM:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/fb565532fa54b32412b70d1ea8b98f6da5aaeb36/sstable/format.go#L25)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: maybe drop the `DB` from the Pebble constants? I think most (all?) places we stylize it as 'Pebble' without 'DB'
</blockquote></details>

Done.
___
*[sstable/format.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuH3JmtBbK4NqEquXMs:-MuHtnPaCmtf52hdynAh:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/fb565532fa54b32412b70d1ea8b98f6da5aaeb36/sstable/format.go#L32)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: I'm not sure, but I think this will allocate when the caller converts the magic string byte slice to a `string` to pass into `ParseTableFormat`. I think if we took in the `[]byte` but did the string conversion in the switch, `switch string(magic) {`, Go is able to infer that it's only used for a comparison and omit the string allocation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-26 20:50 UTC, jbowens approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1471#-:-MuN8tdTAKE1_flPhUpX:bg7igkv)* status: 0 of 15 files reviewed, 3 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[format_major_version.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuN8fi961Q_0Qrv7LyK:-MuN8fi961Q_0Qrv7LyL:b-e1ou78) ([raw file](https://github.com/cockroachdb/pebble/blob/8f6167b65eadf7e6e30113a16a604f67f7006324/format_major_version.go#L82)):*
> ```Go
> // MaxTableFormat returns the maximum sstable.TableFormat that can be used at
> // this FormatMajorVersion.
> func (v FormatMajorVersion) MaxTableFormat() (sstable.TableFormat, error) {
> ```

We can remove this error return value now.


<!-- Sent from Reviewable.io -->

2022-01-27 01:52 UTC, sumeerbhola requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 6 of 15 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1471#-:-MuODvHn15k7y7r_-DmN:bg7igkv)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[format_major_version.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuH0X4F9x_JmL8qLG3D:-MuOBERc2p9lVQotopOp:b-e1si1v) ([raw file](https://github.com/cockroachdb/pebble/blob/fb565532fa54b32412b70d1ea8b98f6da5aaeb36/format_major_version.go#L90)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Sounds reasonable. I had the same thought but then thought that this is exposed outside of Pebble and I'm generally wary of having a library causing panics.

Given this is truly a programmer error, it's probably less of an issue at runtime. Updated.
</blockquote></details>

I still see `error` in the return values.
___
*[sstable/table.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuDjwmW9t5XSKbbizr0:-MuOC5XD3Adqn96InEgN:b4lw9wn) ([raw file](https://github.com/cockroachdb/pebble/blob/fb565532fa54b32412b70d1ea8b98f6da5aaeb36/sstable/table.go#L177)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Interestingly, the LevelDB magic string is the _reverse_ of the first 8 bytes of the SHA1. Given that endianness doesn't really apply to strings, I'm just writing these bytes in order. We also just check the literal string on the read path, so I'm not sure why the LevelDB string was reversed in the first place.
</blockquote></details>

maybe the C++ code in leveldb was using a 64 byte integer
___
*[sstable/writer_test.go, line 437 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuODfGS6kSy2NPQOYRk:-MuODfGS6kSy2NPQOYRl:bhpm87k) ([raw file](https://github.com/cockroachdb/pebble/blob/8f6167b65eadf7e6e30113a16a604f67f7006324/sstable/writer_test.go#L437)):*
> ```Go
> 					err = w.Close()
> 					if tf < tc.minFormat {
> 						require.Error(t, err)
> ```

nice test


<!-- Sent from Reviewable.io -->

2022-02-03 03:48 UTC, nicktrav reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1471#-:-MuxgdUA4BNkPLHRlcoB:bz5mair)* status: 11 of 15 files reviewed, 4 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[format_major_version.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuH0X4F9x_JmL8qLG3D:-MuxdFHp8afeZ5SoIH2T:bt2vr1b) ([raw file](https://github.com/cockroachdb/pebble/blob/fb565532fa54b32412b70d1ea8b98f6da5aaeb36/format_major_version.go#L90)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I still see `error` in the return values.
</blockquote></details>

Fixed.
___
*[format_major_version.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1471#-MuN8fi961Q_0Qrv7LyK:-MuxdDG59g0hhllm4zvn:b-gih2qj) ([raw file](https://github.com/cockroachdb/pebble/blob/8f6167b65eadf7e6e30113a16a604f67f7006324/format_major_version.go#L82)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

We can remove this error return value now.
</blockquote></details>

Woops. Done.


<!-- Sent from Reviewable.io -->

2022-02-03 04:24 UTC, merged