db: rework reverses limit interactions with range keys
cockroachdb/pebble pull request #1477
Opened 2022-01-26 22:54 UTC by jbowens

SeekLTWithLimit and PrevWithLimit allow iteration with a temporary lower bound.
This limited iteration mode complicates range key iteration, because we must
guarantee that an iterator will reveal any range keys covering the span between
the limit and the preceding iterator position.

Previously, this was achieved by ignoring limits in the presence of covering
range keys. This complicates metamorphic testing, which requires deterministic
behavior. While range key boundaries will never be deterministic, point keys
and the range keys that cover them are. However ignoring limits during reverse
iteration made which point keys would be surfaced nondeterministic. (When an
iterator landed on a point key beyond the limit but covered by a range key, the
point key could be deleted or it could not. Regardless, this iterator position
was surfaced to the user.)

This change adapts the behavior during reverse, limited iteration to revert to
the behavior of always returning IterAtLimit as soon as the limit is passed.
However, if there exists a range key that ends after the limit, the range key
is accessible at this `IterAtLimit` position.

The implementation and documentation of this change is incomplete in this
commit, but I wanted to put this up to solicit feedback on the iterator
interface. It's unusual, because if the iterator lands on one of these iterator
positions the iterator consumer sees:

* `IterValidityState == IterAtLimit`
* `Key() == limit`
* `Valid() == false`
* `HasPointAndRange() = (false, true)`
* `RangeKeyBounds() = (correct range key bounds)`
* `RangeKeys() = (correct range keys)`

Thoughts?

2022-01-26 22:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1477)
<!-- Reviewable:end -->

2022-01-31 02:22 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1477)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jbowens and @nicktrav)

___
*[-- commits, line 12 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1477#-MuhpszhBRpysAfXh8fF):*
I'd like to step back and understand how you are planning to make things deterministic for forward iteration. I have not given this any thought since writing the following in the RFC draft:
Randomized tests that encounter non-determinism in fragmentation can buffer all the fragments in-memory, defragment them, and then compare these defragmented range keys for equality testing. This behavior would need to be applied to Pebble's metamorphic test, for which a single Next/Prev call would turn into as many calls are needed until the next point is encountered. All the buffered fragments from these many calls would be defragmented and compared for equality.

I assume you have an idea that works despite the range key boundaries being non-deterministic.

If we have a way of handling the non-deterministic bounds, I wonder whether an alternative solution to this prev case would be to get the range key bounds when we first pass the limit but are forced to proceed due to `iterHasRangeKey()` returning true. Then remember that lower bound and stop at that revised lower bound (when we encounter that synthetic range key marker). Then all we are doing it stretching the `limit` a bit further.


<!-- Sent from Reviewable.io -->

2022-08-02 21:49 UTC, nicktrav commented
@jbowens - is this one still relevant? I'm assuming _a lot_ has changed since this was first proposed.

2022-08-02 21:51 UTC, jbowens reviewed
lolz, thanks for the ping. not relevant anymore!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1477#-:-N8VXcb698DrD-puQSEc:b-1hyty9)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @nicktrav and @sumeerbhola)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1477#-MuhpszhBRpysAfXh8fF):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

You're right, let me take a step back here.

My plan was to initially integrate range keys into the metamorphic tests by skipping all iterator positions where `HasPointAndRange()` indicates only a range key exists at the position. We already have determinism  for all other iterator positions. I was planning on circling back later, to add in determinism for range key only iterator positions.

Since I'm considering an actual Iterator interface change, I should step back and figure out how to achieve determinism in all cases first.

</blockquote></details>

Non-determinism with range keys appears in two places:
1. The `RangeBounds()` returned at any iterator position (including positions with point keys) are nondeterministic, subject to arbitrary fragmentation.
2. The iterator positions that a `IterKeyTypePointsAndRanges` iterator will visit when `HasPointAndRange() = (f, t)` are nondeterministic, as a side effect of the above nondeterminism.

I'm thinking of implementing two different strategies and randomly deciding which an iterator uses at NewIter op generation time.

Strategy A handles 


<!-- Sent from Reviewable.io -->

2022-08-02 21:51 UTC, closed without merging

2022-08-02 21:53 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1477)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1477#-MuhpszhBRpysAfXh8fF):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Non-determinism with range keys appears in two places:
1. The `RangeBounds()` returned at any iterator position (including positions with point keys) are nondeterministic, subject to arbitrary fragmentation.
2. The iterator positions that a `IterKeyTypePointsAndRanges` iterator will visit when `HasPointAndRange() = (f, t)` are nondeterministic, as a side effect of the above nondeterminism.

I'm thinking of implementing two different strategies and randomly deciding which an iterator uses at NewIter op generation time.

Strategy A handles 
</blockquote></details>

Ignore the 7-month draft comment that I accidentally posted ^.


<!-- Sent from Reviewable.io -->