[WIP] compaction: add support for concurrent manual compactions
cockroachdb/pebble pull request #1487
Opened 2022-02-01 03:17 UTC by mufeez-amjad

2022-02-01 03:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1487)
<!-- Reviewable:end -->

2022-02-02 01:44 UTC, mufeez-amjad reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @bananabrick and @jbowens)

___
*[compaction.go, line 1698 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MuqM-cT4oyX9eUP-0qr:-Mus3bMb5Hm3JDkM2mG6:b1awdyr) ([raw file](https://github.com/cockroachdb/pebble/blob/b21475c0c2710859caced01ccb7ca2ef1aaf8654/compaction.go#L1698)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

early drive-by comment, have you tried adjusting `calculateInuseKeyRanges` to limit the depth it descends and using that?

Note that we want user-key ranges, _not_ internal key ranges because compactions must always be expanded to a user-key boundaries anyways (see `expandToAtomicUnit`). The one exception is if a `Largest` boundary is exclusive `IsExclusiveSentinel()`, then the file with that `Largest` boundary does not contain that user key.
</blockquote></details>

I originally considered using `calculateInuseKeyRanges` but thought it was doing more than I needed. I took your suggestion and used that in place of `getNonOverlappingKeyRanges` and the data-driven tests pass. I also changed my unit tests to test against `calculateInuseKeyRanges` but for the following test case:

```
L1: [a, c], [d, e], [n, o], [p, q]
L2: [m, q], [s, w]
```

`calculateInuseKeyRanges` produces 
`[a, c], [d, e], [m, q], [s, w]`
(4 ranges).

I believe that it should be 
`[a, c], [d, e], [n, q]`
since
- `[a, c]` and `[d, e]` are non-overlapping with files from L2 and
- both `[n, o], [p, q]` overlap with `[m, q]` and thus must be compacted together.

Is my understanding correct?

cc @bananabrick 


<!-- Sent from Reviewable.io -->

2022-02-02 03:32 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @bananabrick and @jbowens)

___
*[compaction.go, line 1698 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MuqM-cT4oyX9eUP-0qr:-MusSghc-nTTdqs8HiFV:bvg4koq) ([raw file](https://github.com/cockroachdb/pebble/blob/b21475c0c2710859caced01ccb7ca2ef1aaf8654/compaction.go#L1698)):*
<details><summary><i>Previously, mufeez-amjad (Mufeez Amjad) wrote…</i></summary><blockquote>

I originally considered using `calculateInuseKeyRanges` but thought it was doing more than I needed. I took your suggestion and used that in place of `getNonOverlappingKeyRanges` and the data-driven tests pass. I also changed my unit tests to test against `calculateInuseKeyRanges` but for the following test case:

```
L1: [a, c], [d, e], [n, o], [p, q]
L2: [m, q], [s, w]
```

`calculateInuseKeyRanges` produces 
`[a, c], [d, e], [m, q], [s, w]`
(4 ranges).

I believe that it should be 
`[a, c], [d, e], [n, q]`
since
- `[a, c]` and `[d, e]` are non-overlapping with files from L2 and
- both `[n, o], [p, q]` overlap with `[m, q]` and thus must be compacted together.

Is my understanding correct?

cc @bananabrick 
</blockquote></details>

Each of the intervals produced using `calculateInuseKeyRanges` look like they're mutually non-overlapping with the output layer.

`a,c`, `d,e` are non-overlapping in L1 and don't overlap with L2.

`m,q` overlaps with `n,o` and `p,q` in L1, so those will be compacted together.

It seems fine, although picking `s,w` seems a bit redundant.


<!-- Sent from Reviewable.io -->

2022-02-02 20:29 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @bananabrick and @mufeez-amjad)

___
*[compaction.go, line 1698 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MuqM-cT4oyX9eUP-0qr:-Muw6gY65ERJoRHDb7Xt:bq69mqi) ([raw file](https://github.com/cockroachdb/pebble/blob/b21475c0c2710859caced01ccb7ca2ef1aaf8654/compaction.go#L1698)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Each of the intervals produced using `calculateInuseKeyRanges` look like they're mutually non-overlapping with the output layer.

`a,c`, `d,e` are non-overlapping in L1 and don't overlap with L2.

`m,q` overlaps with `n,o` and `p,q` in L1, so those will be compacted together.

It seems fine, although picking `s,w` seems a bit redundant.
</blockquote></details>

Yeah, intervals that only exist in the output level like `s-w` are redundant, but will be discarded in `pickManualHelper`:

```
	if pc.startLevel.files.Empty() {
		// Nothing to do
		return nil
	}
```


<!-- Sent from Reviewable.io -->

2022-02-07 22:11 UTC, mufeez-amjad reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @bananabrick and @mufeez-amjad)

___
*[compaction_picker.go, line 1362 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvH8IZw0p5M-77wm3dX:-MvH8IZxADjIMv8BTVGB:b-7gd2pv) ([raw file](https://github.com/cockroachdb/pebble/blob/19e11cfe195fac62eeac044cacb85933c5406255/compaction_picker.go#L1362)):*
> ```Go
> 	// TODO(peter): The conflictsWithInProgress call should no longer be
> 	// necessary, but TestManualCompaction currently expects it.
> 	if conflictsWithInProgress(manual.level, outputLevel, env.inProgressCompactions) {
> ```

`conflictsWithInProgress` checks if there is an in-progress compaction that involves either `manual.level` or `outputLevel`. This can be removed because compactions within the same level are allowed, as long as there is no overlap in key space. 

`inputRangeAlreadyCompacting` checks that:
1. no files in the input `LevelSlice` or output `LevelSlice` are being currently being compacted
2. no scheduled/in-progress compactions output to the same key space on the output level

I believe these 2 checks are sufficient to prevent two compactions from conflicting. I've also updated the data-driven test to accommodate this change.


<!-- Sent from Reviewable.io -->

2022-02-09 20:44 UTC, bananabrick requested changes
Nice. Excited to see how the benchmarks go.

Do we need to make sure that the compaction doesn't `grow` through the calls to the `pickManual` -> `pickManualHelper` -> `setupInputs` functions?

Haven't taken a look at the test files yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487#-:-MvPJx3v26HWYd0080r6:b-yixldc)* status: 0 of 9 files reviewed, 8 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[compaction.go, line 648 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvV6XaiC9dVkPE-k22A:-MvV6XajABcJMHRpFN7Z:bxyb0xt) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/compaction.go#L648)):*
> ```Go
> 
> func calculateInuseKeyRanges(
> 	v *version, cmp base.Compare, level, depth int, smallest, largest []byte,
> ```

Can we call `depth` something else? To me, `depth` is a relative measurement. For example, if `depth == 3`, Then I expect us to traverse down 3 levels, starting from `level`. So, from `level` to `level+3`.

What do you think?
___
*[compaction_picker.go, line 1362 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvH8IZw0p5M-77wm3dX:-MvV79Yy0GfJ8RBe-1bF:bbfw655) ([raw file](https://github.com/cockroachdb/pebble/blob/19e11cfe195fac62eeac044cacb85933c5406255/compaction_picker.go#L1362)):*
<details><summary><i>Previously, mufeez-amjad (Mufeez Amjad) wrote…</i></summary><blockquote>

`conflictsWithInProgress` checks if there is an in-progress compaction that involves either `manual.level` or `outputLevel`. This can be removed because compactions within the same level are allowed, as long as there is no overlap in key space. 

`inputRangeAlreadyCompacting` checks that:
1. no files in the input `LevelSlice` or output `LevelSlice` are being currently being compacted
2. no scheduled/in-progress compactions output to the same key space on the output level

I believe these 2 checks are sufficient to prevent two compactions from conflicting. I've also updated the data-driven test to accommodate this change.
</blockquote></details>

This sounds good. Looks like `conflictsWithInProgress` would've prevented us from executing multiple compactions from the same level concurrently.
___
*[db.go, line 1275 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvV8pCX2PHbsOk7i9Cm:-MvV8pCX2PHbsOk7i9Cn:bd2td2s) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1275)):*
> ```Go
> 			return err
> 		}
> 		level++
> ```

I see that in this PR, we're not making L0 compactions concurrent. The `manual` compaction here, is only valid for `L0`. How about we do:

```
if level == 0 {
     level = manual.outputLevel
} else {
     level++
}
```

Once you make L0 compactions concurrent, this won't work, and we'd have to figure out another way. We could always do a `level++` here. If the level is empty, then you could return early from `manualCompact`.

What do you think?
___
*[db.go, line 1288 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvV8G7dDcdccU6poMq7:-MvV8G7dDcdccU6poMq8:btjan9m) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1288)):*
> ```Go
> }
> 
> func (d *DB) manualCompact(manual *manualCompaction) error {
> ```

How about changing the API here to `db.manualCompact(level)`? It seems odd to me to pass in a manual compaction which gets ignored anyway.
___
*[db.go, line 1292 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVBuMdAIoG-SKasBXG:-MvVBuMdAIoG-SKasBXH:bxvqggg) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1292)):*
> ```Go
> 	splitCompactions := d.splitManualCompaction(manual)
> 	d.mu.compact.manual = append(d.mu.compact.manual, splitCompactions...)
> 	d.maybeScheduleCompaction()
> ```

We call `d.maybeScheduleCompaction` here. I'm concerned that this will only schedule one compaction at a time.

For example,
`d.maybeScheduleCompaction -> d.compact -> d.maybeScheduleCompaction -> d.compact`.

Is there some code path I'm missing which will cause more compactions to be scheduled concurrently?

Another concern I have is the call to `pickManual` returning `nil` in the `maybeScheduleCompaction`. In which case, we won't schedule anymore compactions(assuming there's only one goroutine) currently scheduling a compaction.

These concerns might be unfounded, as I might be missing some code paths.
___
*[db.go, line 1295 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVArFs2iQqIw1jwbsD:-MvVArFs2iQqIw1jwbsE:b-3w7ctz) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1295)):*
> ```Go
> 	d.mu.Unlock()
> 	for _, compaction := range splitCompactions {
> 		if err := <-compaction.done; err != nil {
> ```

We should add a small proof here as a comment, that each of these channels is guaranteed to be eventually written to. It's not necessary to read from each of these channels, since the channels are buffered, but it is necessary to do a send on each of these channels, in the case with no errors.
___
*[db.go, line 1312 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVAMP93vDmvR_1kC1b:-MvVAMP93vDmvR_1kC1c:bga5ans) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1312)):*
> ```Go
> 
> 		for _, keyRange := range keyRanges {
> 			splitManual := *manual
> ```

Could we construct a new `manualCompaction`, instead of copying over `manual`?

`splitManual := manualCompaction{...}`.

You could also do `splitManual := &manualCompaction{...}`. I think it's going to get heap allocated anyway, when we do `concurrentCompactions = append(concurrentCompactions, &splitManual)`.

It might be a bit cleaner. What do you think?


<!-- Sent from Reviewable.io -->

2022-02-09 20:50 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 0 of 9 files reviewed, 8 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[db.go, line 1288 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvV8G7dDcdccU6poMq7:-MvVF5bK9xrFsIQdftA8:b-8esko) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1288)):*
> db.manualCompact(level)
Correction: `db.manualCompact(level, keyranges...)`


<!-- Sent from Reviewable.io -->

2022-02-09 21:10 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 0 of 9 files reviewed, 8 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[db.go, line 1292 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVBuMdAIoG-SKasBXG:-MvVHw_y3ywpuctSRQss:b46iz24) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1292)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

We call `d.maybeScheduleCompaction` here. I'm concerned that this will only schedule one compaction at a time.

For example,
`d.maybeScheduleCompaction -> d.compact -> d.maybeScheduleCompaction -> d.compact`.

Is there some code path I'm missing which will cause more compactions to be scheduled concurrently?

Another concern I have is the call to `pickManual` returning `nil` in the `maybeScheduleCompaction`. In which case, we won't schedule anymore compactions(assuming there's only one goroutine) currently scheduling a compaction.

These concerns might be unfounded, as I might be missing some code paths.
</blockquote></details>

Talked offline. I forgot that we try and schedule compactions in a loop in `d.maybeScheduleCompaction`, so we would still end up scheduling up to `MaxConcurrentCompactions`.

So, both of these points shouldn't be a concern.


<!-- Sent from Reviewable.io -->

2022-02-09 21:53 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[db.go, line 1249 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVRse4-PfdMj68DqcI:-MvVRse4-PfdMj68DqcJ:b2f7x7k) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1249)):*
> ```Go
> 				}
> 				mem.flushForced = true
> 				d.maybeScheduleFlush()
> ```

I'm concerned that `d.maybeScheduleFlush` will end up scheduling background compactions, and we don't want that, because the manual compactions could end up conflicting with the on going compactions.

@jbowens Does this look correct? Do we expect background/automatic compactions to be scheduled with this particular call to `d.maybeScheduleFlush`.


<!-- Sent from Reviewable.io -->

2022-02-09 22:29 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[db.go, line 1249 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVRse4-PfdMj68DqcI:-MvVZoA1EynkOF9A8UBy:bja4m0j) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1249)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I'm concerned that `d.maybeScheduleFlush` will end up scheduling background compactions, and we don't want that, because the manual compactions could end up conflicting with the on going compactions.

@jbowens Does this look correct? Do we expect background/automatic compactions to be scheduled with this particular call to `d.maybeScheduleFlush`.
</blockquote></details>

@mufeez-amjad I think in general, we might need to ensure that:

1. There are no ongoing compactions before we call `calculateInUseKeyRanges` to determine the key ranges.
2. Only the manual compactions which we created are scheduled. Otherwise, the key space for the layers can change, and the overlaps/ranges we created won't be accurate.


<!-- Sent from Reviewable.io -->

2022-02-10 19:36 UTC, jbowens reviewed
> Do we need to make sure that the compaction doesn't `grow` through the calls to the `pickManual` -> `pickManualHelper` -> `setupInputs` functions?

I would leave it. `grow` should be a no-op, because both input and output should already be atomic compaction units, and there shouldn't be any input files that overlap the output files that are not already in the inputs.

> Reviewed 3 of 8 files at r5, 1 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487#-:-Mv_0_XL7MznkmKmNTmU:bx8h88d)* status: 4 of 9 files reviewed, 11 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[compaction.go, line 662 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvV33e252yZDBEjKReF:-MvV33e252yZDBEjKReG:b-g1ykz1) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/compaction.go#L662)):*
> ```Go
> 	}
> 
> 	for ; level <= depth && level < numLevels; level++ {
> ```

how about combining `depth` and `numLevels` checks, and just have the caller pass in `numLevels-1` if they want it all?
```
for ; level <= maxLevel; level++ {
```
___
*[db.go, line 1198 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mv_6qkL4_J9LKJSdmWd:-Mv_6qkL4_J9LKJSdmWe:bfgun4t) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1198)):*
> ```Go
> // Compact the specified range of keys in the database.
> func (d *DB) Compact(
> 	start, end []byte, /* CompactionOptions */
> ```

I'd like to see a max parallelism configuration option here. If max parallelism is 1, we would perform no fragmenting of the key range.

In tests (including within CockroachDB, outside of Pebble) we often use `Compact` to construct a particular test state, sometimes relying on a single unfragmented compaction.
___
*[db.go, line 1249 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVRse4-PfdMj68DqcI:-Mv_537b1DkXBFwiBh4p:b-j114yg) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1249)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

@mufeez-amjad I think in general, we might need to ensure that:

1. There are no ongoing compactions before we call `calculateInUseKeyRanges` to determine the key ranges.
2. Only the manual compactions which we created are scheduled. Otherwise, the key space for the layers can change, and the overlaps/ranges we created won't be accurate.
</blockquote></details>

This particular `d.maybeScheduleFlush` is before we've determined our compaction range, and we wait for it to complete (`<-mem.flushed`) before proceeding. 
___
*[db.go, line 1271 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mv_6LpTDU_vSVEb8di-:-Mv_6LpTDU_vSVEb8di0:b395jms) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1271)):*
> ```Go
> 			start: iStart,
> 			end:   iEnd,
> 		}
> ```

I was expecting to see the splitting of the range here. Is there any reason we need to perform it within `manualCompact`?


<!-- Sent from Reviewable.io -->

2022-02-10 19:37 UTC, mufeez-amjad reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 4 of 9 files reviewed, 10 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[compaction.go, line 1698 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MuqM-cT4oyX9eUP-0qr:-Mv_6gDh9PRutGBpcwO9:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b21475c0c2710859caced01ccb7ca2ef1aaf8654/compaction.go#L1698)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, intervals that only exist in the output level like `s-w` are redundant, but will be discarded in `pickManualHelper`:

```
	if pc.startLevel.files.Empty() {
		// Nothing to do
		return nil
	}
```
</blockquote></details>

Done.
___
*[db.go, line 1249 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVRse4-PfdMj68DqcI:-Mv_6BrXBpGmA6VepzdE:b-85hxlb) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1249)):*
> I'm concerned that d.maybeScheduleFlush will end up scheduling background compactions, and we don't want that, because the manual compactions could end up conflicting with the on going compactions.

It looks like the main thread is [blocked](https://github.com/cockroachdb/pebble/blob/91c353540d30b6c8a6afac246c744146d05a5eae/db.go#L1263) (before executing the manual compaction step) until the possible flush is [finished](https://github.com/cockroachdb/pebble/blob/91c353540d30b6c8a6afac246c744146d05a5eae/compaction.go#L1482). 
___
*[db.go, line 1292 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVBuMdAIoG-SKasBXG:-Mv_6c-8BUpVVVH7LNPv:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1292)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Talked offline. I forgot that we try and schedule compactions in a loop in `d.maybeScheduleCompaction`, so we would still end up scheduling up to `MaxConcurrentCompactions`.

So, both of these points shouldn't be a concern.
</blockquote></details>

Done.
___
*[db.go, line 1312 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVAMP93vDmvR_1kC1b:-Mv_6kF02To1Ez-rnSL7:ba5fuak) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1312)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Could we construct a new `manualCompaction`, instead of copying over `manual`?

`splitManual := manualCompaction{...}`.

You could also do `splitManual := &manualCompaction{...}`. I think it's going to get heap allocated anyway, when we do `concurrentCompactions = append(concurrentCompactions, &splitManual)`.

It might be a bit cleaner. What do you think?
</blockquote></details>

I was thinking copying would be better since a split compaction is inherently a copy of the manual compaction but with a new key range, and would be better in the case that we add more fields to `manualCompaction`.


<!-- Sent from Reviewable.io -->

2022-02-10 20:10 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 4 of 9 files reviewed, 10 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[db.go, line 1249 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVRse4-PfdMj68DqcI:-Mv_EqbEBKfioKJdN831:bovq3fu) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1249)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Could a delete only compaction be scheduled before the manual compaction, thus changing the level we determined the key ranges for?
</blockquote></details>

Also, we call `maybeScheduleFlush` which calls `flush`. `flush` will call `flush1`, `maybeScheduleFlush`, and then `maybeScheduleCompaction`. We write to the `flushed` channel in the `flush1` function. So, there could still be other compactions scheduled via the `maybeScheduleCompaction` call, right? This would happen after the `flushed` channel has been closed.


<!-- Sent from Reviewable.io -->

2022-02-10 20:19 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 4 of 9 files reviewed, 10 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[db.go, line 1312 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVAMP93vDmvR_1kC1b:-Mv_HOKDAP4Y5hOzz7Lt:butjk0m) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1312)):*
<details><summary><i>Previously, mufeez-amjad (Mufeez Amjad) wrote…</i></summary><blockquote>

I was thinking copying would be better since a split compaction is inherently a copy of the manual compaction but with a new key range, and would be better in the case that we add more fields to `manualCompaction`.
</blockquote></details>

Just my personal opinion that explicitly copying the fields we want is better than implicitly copying everything, and then changing the fields which are differed.

Although, this is a nit, and irrelevant if you decide to no longer pass in the manual compaction into this function.


<!-- Sent from Reviewable.io -->

2022-02-15 21:39 UTC, mufeez-amjad reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 1 of 24 files reviewed, 10 unresolved discussions (waiting on @bananabrick and @jbowens)

___
*[compaction.go, line 648 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvV6XaiC9dVkPE-k22A:-Mva-Jkn3omTDzYEyTlj:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/compaction.go#L648)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Can we call `depth` something else? To me, `depth` is a relative measurement. For example, if `depth == 3`, Then I expect us to traverse down 3 levels, starting from `level`. So, from `level` to `level+3`.

What do you think?
</blockquote></details>

Done.
___
*[compaction.go, line 662 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvV33e252yZDBEjKReF:-Mva-IKG0yG95f-MAMOJ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/compaction.go#L662)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

how about combining `depth` and `numLevels` checks, and just have the caller pass in `numLevels-1` if they want it all?
```
for ; level <= maxLevel; level++ {
```
</blockquote></details>

Done.
___
*[db.go, line 1198 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mv_6qkL4_J9LKJSdmWd:-Mvp1VY15cBYQ7ad5361:b53pdxn) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1198)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I'd like to see a max parallelism configuration option here. If max parallelism is 1, we would perform no fragmenting of the key range.

In tests (including within CockroachDB, outside of Pebble) we often use `Compact` to construct a particular test state, sometimes relying on a single unfragmented compaction.
</blockquote></details>

I considered adding an int param which can either be 1 or greater than 1 but this wouldn't be the most ideal on the cockroachdb side in terms of readability imo. I opted for a boolean param (default false) to `db.Compact` for improved readability since splitting a compaction into a `n` compactions given `n` is not in the scope of this issue.
___
*[db.go, line 1271 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mv_6LpTDU_vSVEb8di-:-Mva-aYa2LkJlXX-Nsgn:bx0yi0q) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1271)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I was expecting to see the splitting of the range here. Is there any reason we need to perform it within `manualCompact`?
</blockquote></details>

My thought was that a manual compaction of a level should still appear as a single compaction to `db.Compact`, and the logic of splitting a manual compaction and synchronization should be done in `manualCompact`. My intention was to have separation of concerns & loose coupling but I'm happy to move it here if it is more fitting.
___
*[db.go, line 1275 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvV8pCX2PHbsOk7i9Cm:-MvzE_uH680zBkhKeHcW:b-u6bx8g) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1275)):*
> If the level is empty, then you could return early from manualCompact.

Good point, we could rely on the compaction being dropped after `pickManual` but it's better to save on all the extra computation of keyranges and level slices. Added a check in `manualCompact` to exit early if a level is empty.
___
*[db.go, line 1288 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvV8G7dDcdccU6poMq7:-Mvfspt_2_fmfvGFRb7l:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1288)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

> db.manualCompact(level)
Correction: `db.manualCompact(level, keyranges...)`
</blockquote></details>

Done.
___
*[db.go, line 1295 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVArFs2iQqIw1jwbsD:-MvynhC39IBqqfjSgY1g:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1295)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

We should add a small proof here as a comment, that each of these channels is guaranteed to be eventually written to. It's not necessary to read from each of these channels, since the channels are buffered, but it is necessary to do a send on each of these channels, in the case with no errors.
</blockquote></details>

Done.
___
*[db.go, line 1312 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVAMP93vDmvR_1kC1b:-Mvft7Ff4jUXO4RCofhj:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1312)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Just my personal opinion that explicitly copying the fields we want is better than implicitly copying everything, and then changing the fields which are differed.

Although, this is a nit, and irrelevant if you decide to no longer pass in the manual compaction into this function.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-16 02:42 UTC, mufeez-amjad commented
I benchmarked my changes against master on a ~150GB LSM, here are the results:

### Summary

Roughly a 30% decrease in time taken to execute a manual compaction.

| Branch      | Time | 
| :---        |    :----   | 
| `master`      | real    550m32.809s<br>user    589m52.219ss<br>sys     36m25.205s   | 
|  `concurrent-manual` |  real    384m56.152s<br>user    373m0.258s<br>sys     28m25.139s  | 

<details>
  <summary>LSM</summary>

**Test data:**
```
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         3   138 M       -     0 B       -       -       -       -   138 M       -       -       -     0.0
      0     69428    84 G    3.02     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      1         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      2      2478   9.7 G    5.45     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      3      1975    12 G    5.72     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      4      1497    15 G    5.73     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      5       961    18 G    0.87     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      6       703    15 G       -     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
  total     77042   154 G       -   138 M     0 B       0     0 B       0   138 M       0     0 B       0     1.0
  flush         0
compact         0   583 G     0 B       0          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype         0       0       0       0       0  (default, delete, elision, move, read)
 memtbl        39   144 M
zmemtbl         0     0 B
   ztbl         0     0 B
 bcache         0     0 B    0.0%  (score == hit-rate)
 tcache         0     0 B    0.0%  (score == hit-rate)
  snaps         0       -       0  (score == earliest seq num)
 titers         0
 filter         -       -    0.0%  (score == utility)
```

**After compaction on `master`:**
```
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         1     0 B       -     0 B       -       -       -       -     0 B       -       -       -     0.0
      0         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      1         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      2         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      3         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      4         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      5         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      6      1794   111 G       -     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
  total      1794   111 G       -     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
  flush         0
compact         0     0 B     0 B       0          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype         0       0       0       0       0  (default, delete, elision, move, read)
 memtbl         0     0 B
zmemtbl         0     0 B
   ztbl         0     0 B
 bcache         0     0 B    0.0%  (score == hit-rate)
 tcache         0     0 B    0.0%  (score == hit-rate)
  snaps         0       -       0  (score == earliest seq num)
 titers         0
 filter         -       -    0.0%  (score == utility)
```

**After compaction on `concurrent-manual`:**
```
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         1     0 B       -     0 B       -       -       -       -     0 B       -       -       -     0.0
      0         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      1         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      2         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      3         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      4         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      5         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      6      1773   111 G       -     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
  total      1773   111 G       -     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
  flush         0
compact         0     0 B     0 B       0          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype         0       0       0       0       0  (default, delete, elision, move, read)
 memtbl         0     0 B
zmemtbl         0     0 B
   ztbl         0     0 B
 bcache         0     0 B    0.0%  (score == hit-rate)
 tcache         0     0 B    0.0%  (score == hit-rate)
  snaps         0       -       0  (score == earliest seq num)
 titers         0
 filter         -       -    0.0%  (score == utility)
```
</details>

<details>
  <summary>Machine</summary>

<br>

**Machine type**: n1-standard-16
**SSD**: 1000GB pd-ssd
</details>

<details>
  <summary>Resource Utilization</summary>

<br>

![SCR-20220215-tqe](https://user-images.githubusercontent.com/19630228/154184601-dcb50d5c-2fde-4d80-bcfb-70d860c1a44d.png)

![SCR-20220215-tsb](https://user-images.githubusercontent.com/19630228/154184771-b27bdc0b-6ee6-47c5-bb5a-7ea96e64279e.png)

</details>

2022-02-16 17:12 UTC, jbowens reviewed
This is looking great. Thanks for doing this!

Do you happen to have any pebble logs from those benchmark runs? I'm wondering which levels correspond to which time periods.  The taller, narrower spike of disk throughput and CPU utilization at the end of the modified run is encouraging, but what's happening in the middle of a run between the two peaks? Is that compaction of L0 which can't be parallelized?

> Reviewed 2 of 8 files at r7, 19 of 21 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487#-:-Mw2T8GI3M9PFP5s-dop:b-cfkg76)* status: 23 of 25 files reviewed, 12 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[db.go, line 1321 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw2OlI_DPnD90fAokCb:-Mw2OlI_DPnD90fAokCc:b-5frix8) ([raw file](https://github.com/cockroachdb/pebble/blob/079bbeedfc5f507f44021158017cd200d2edc575/db.go#L1321)):*
> ```Go
> 				done:  make(chan error, 1),
> 				start: InternalKey{UserKey: keyRange.Start},
> 				end:   InternalKey{UserKey: keyRange.End},
> ```

I think we should try to change `manualCompaction.{start,end}` to be just user keys `[]byte`, both inclusive. The key ranges returned by `calculateInuseKeyRanges` are inclusive on both sides, and the `start` and `end` arguments to `Compact` are both treated as inclusive as well. I think it should be a clean change, but let me know if you run into anything you're unsure about.
___
*[internal/metamorphic/ops.go, line 108 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw2Pa5A2sbuad6Ih9R3:-Mw2Pa5A2sbuad6Ih9R4:b-gw7oo6) ([raw file](https://github.com/cockroachdb/pebble/blob/079bbeedfc5f507f44021158017cd200d2edc575/internal/metamorphic/ops.go#L108)):*
> ```Go
> func (o *compactOp) run(t *test, h *history) {
> 	err := withRetries(func() error {
> 		return t.db.Compact(o.start, o.end, false)
> ```

I think we should randomize whether or not we use parallelism during the metamorphic tests. We can add a `parallel bool` field to `compactOp`, and modify `internal/metamorphic/generator.go` to set it to true 50% of the time. There's some additional places where we'll need to plumb the new state through, like `compactOp.String()` and the parsing logic in `internal/metamorphic/parser.go`. 
___
*[testdata/manual_compaction, line 890 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw2RGZdEHtG45WM-sI4:-Mw2RGZdEHtG45WM-sI5:bownzhf) ([raw file](https://github.com/cockroachdb/pebble/blob/079bbeedfc5f507f44021158017cd200d2edc575/testdata/manual_compaction#L890)):*
> ```
> ----
> 
> set-parallelize value=true
> ```

Can we plumb this through as an optional `CmdArgs` on the `compact` command?


<!-- Sent from Reviewable.io -->

2022-02-16 20:35 UTC, mufeez-amjad reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 21 of 26 files reviewed, 13 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[options.go, line 560 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw2vwRiCeH0gUVg0oBc:-Mw2vwRiCeH0gUVg0oBd:bkb912b) ([raw file](https://github.com/cockroachdb/pebble/blob/0131524697151e410a1c8d8a9560e08540478d64/options.go#L560)):*
> ```Go
> 	// scheduled or not. The default is false (enabled). This option is only used
> 	// externally when running a manual compaction, and internally for tests.
> 	DisableAutomaticCompactions bool
> ```

An issue I saw when benchmarking was that after a manual compaction finished, the levels of the LSM would remain non-empty. I noticed that before the start of the manual compaction, 2 or 3 automatic compactions were already scheduled from L0 to Lbase and Lbase to Lbase+1.

This posed a problem because previously, a manual compaction would be retried if either `startLevel` or `outputLevel` were compacting. However, with these changes, we allow concurrent compactions on the same level as long as there is no overlap. When a manual compaction is [retried](https://github.com/cockroachdb/pebble/blob/0131524697151e410a1c8d8a9560e08540478d64/compaction.go#L1585), automatic compactions are scheduled in its place. The eventual result with this is that automatic compactions starve the manual compaction, add additional conflicts with the (nonoverlapping) keyranges chosen for a manual compaction, and we lose out on the performance benefit of parallelizing compactions. 

For those reasons, I thought that the approach of disabling automatic compactions altogether in [`runDebugCompact`](https://github.com/cockroachdb/cockroach/blob/4a741cd05cdc296d22741f400b1a139119edf4a7/pkg/cli/debug.go#L795) was ideal since it seems like the easiest way to maximize the performance benefit. This was the approach that was used for the benchmarks posted above.


<!-- Sent from Reviewable.io -->

2022-02-16 21:36 UTC, bananabrick reviewed
Cool!

I think we should try and figure out what's going on in the disk throughput graph. I'm guessing the first peak corresponds to the flushes, and the second peak corresponds to the concurrent compactions. What's going on for 5+ hours in the middle? Are we spending all that time doing CPU work, and no IO? Is that computations related to the massively overlapping L0?

> Reviewed 1 of 8 files at r5, 13 of 21 files at r8, 1 of 1 files at r9, 3 of 4 files at r10, 8 of 8 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487#-:-Mw3Oqoo98OEcdLbYM9t:bqzktu9)* status: all files reviewed, 15 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[-- commits, line 6 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw3NLlY97q0IV9gnB2p):*
Since this is a bigger change, it might be worthwhile to have a detailed commit message, and also format it so that the lines aren't so long.
___
*[compaction.go, line 644 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw3OCf27y_i8CjJq8pp:-Mw3OCf27y_i8CjJq8pq:b-12xowo) ([raw file](https://github.com/cockroachdb/pebble/blob/f8199486ff57ac606d6bed629851c19fa999f4ef/compaction.go#L644)):*
> ```Go
> 		level = 0
> 	}
> 	c.inuseKeyRanges = calculateInuseKeyRanges(c.version, c.cmp, level, numLevels-1, c.smallest.UserKey, c.largest.UserKey)
> ```

nit: This line's a bit long.
___
*[compaction_picker.go, line 1360 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw3Pgua4IWA3D8zbIZU:-Mw3Pgua4IWA3D8zbIZV:b-mwkfv2) ([raw file](https://github.com/cockroachdb/pebble/blob/19e11cfe195fac62eeac044cacb85933c5406255/compaction_picker.go#L1360)):*
> ```Go
> 		return nil, false
> 	}
> 	// TODO(peter): The conflictsWithInProgress call should no longer be
> ```

I know that this comment indicates that this function wasn't previously required. However, from experimentation, it seems like this was required, right? For example, without this check, compactions might not be retried.

In the case where we're scheduling manual compactions concurrently, and disabling automatic compactions, this isn't required. But could this be required for other use cases of `db.Compact`. Iirc, there is one other use case of `db.Compact` from Cockroach.
___
*[db.go, line 1275 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvV8pCX2PHbsOk7i9Cm:-Mw3QEr98ma2hf9TcxJj:bqwx856) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1275)):*
<details><summary><i>Previously, mufeez-amjad (Mufeez Amjad) wrote…</i></summary><blockquote>

> If the level is empty, then you could return early from manualCompact.

Good point, we could rely on the compaction being dropped after `pickManual` but it's better to save on all the extra computation of keyranges and level slices. Added a check in `manualCompact` to exit early if a level is empty.
</blockquote></details>

nit: It might be cleaner, if the compaction is dropped from `pickManual`, and we wouldn't need to add extra logic here.
___
*[db.go, line 1295 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVArFs2iQqIw1jwbsD:-Mw3QbuF2pBbXkHuGMGw:b-m3yg9r) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1295)):*
<details><summary><i>Previously, mufeez-amjad (Mufeez Amjad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We don't write to the channel in the case where we increment `manual.retries`, but if we assume that the compaction will eventually be retired, then we're fine. But also, the compaction shouldn't be retried, if we're disabling automatic compactions.
___
*[internal/metamorphic/ops.go, line 108 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw2Pa5A2sbuad6Ih9R3:-Mw3SH8PBJhXyDmR2kJJ:b32v57) ([raw file](https://github.com/cockroachdb/pebble/blob/079bbeedfc5f507f44021158017cd200d2edc575/internal/metamorphic/ops.go#L108)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think we should randomize whether or not we use parallelism during the metamorphic tests. We can add a `parallel bool` field to `compactOp`, and modify `internal/metamorphic/generator.go` to set it to true 50% of the time. There's some additional places where we'll need to plumb the new state through, like `compactOp.String()` and the parsing logic in `internal/metamorphic/parser.go`. 
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-02-17 05:49 UTC, mufeez-amjad reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 17 of 31 files reviewed, 14 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[compaction_picker.go, line 1360 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw3Pgua4IWA3D8zbIZU:-Mw4oNoDDyJuF-ZUb0mr:boiyo1l) ([raw file](https://github.com/cockroachdb/pebble/blob/19e11cfe195fac62eeac044cacb85933c5406255/compaction_picker.go#L1360)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I know that this comment indicates that this function wasn't previously required. However, from experimentation, it seems like this was required, right? For example, without this check, compactions might not be retried.

In the case where we're scheduling manual compactions concurrently, and disabling automatic compactions, this isn't required. But could this be required for other use cases of `db.Compact`. Iirc, there is one other use case of `db.Compact` from Cockroach.
</blockquote></details>

Good catch. I searched for uses of that function and saw it used in the debug compact command and in a few tests. 

Yes, in the case of background compactions it's likely that without retrying manual compactions the LSM will not be fully compacted. One way to address this issue is to add `conflictsWithInProgress` back but check the key range as well. The ranges won't conflict when using `debug compact` by construction but should catch the cases where there are automatic compactions with overlap. I think we could also change the behaviour of pickManual to retry the compaction if the input levels are being compacted (I'm not entirely sure why `inputRangeAlreadyCompacting` retries the compaction but a file in the range with `isCompacting` doesn't).
___
*[db.go, line 1321 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw2OlI_DPnD90fAokCb:-Mw3k1Zj-mVeu8xCoOgc:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/079bbeedfc5f507f44021158017cd200d2edc575/db.go#L1321)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think we should try to change `manualCompaction.{start,end}` to be just user keys `[]byte`, both inclusive. The key ranges returned by `calculateInuseKeyRanges` are inclusive on both sides, and the `start` and `end` arguments to `Compact` are both treated as inclusive as well. I think it should be a clean change, but let me know if you run into anything you're unsure about.
</blockquote></details>

Done.
___
*[internal/metamorphic/ops.go, line 108 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw2Pa5A2sbuad6Ih9R3:-Mw4XOEZA0JmB4Rxjkkn:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/079bbeedfc5f507f44021158017cd200d2edc575/internal/metamorphic/ops.go#L108)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[testdata/manual_compaction, line 890 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw2RGZdEHtG45WM-sI4:-Mw3l4Sh7PbtZ-BGVnfg:b-fznogt) ([raw file](https://github.com/cockroachdb/pebble/blob/079bbeedfc5f507f44021158017cd200d2edc575/testdata/manual_compaction#L890)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Can we plumb this through as an optional `CmdArgs` on the `compact` command?
</blockquote></details>

Good idea, done.


<!-- Sent from Reviewable.io -->

2022-02-18 18:36 UTC, mufeez-amjad reviewed
I did another run of the benchmark with a 154GB LSM but with uniform values instead of zipf, and the real times were 396m12.236s and 567m9.699s for the changes and master respectively, which is close to the previous run.

> Is that compaction of L0 which can't be parallelized?

Yes, the L0 compaction isn't parallelized - from the logs it looks like the L0 compaction takes about 369m (~93%) and 529m (~93%) for the changes and master respectively. It seems like with smaller levels L1-L5, most of the benefit comes from disabling automatic compactions which interfere with the scheduling of manual compactions (retries). However, with a higher peak in the throughput graph we can assume that the compaction of larger L1-L5 would see an improvement over master.

> What's going on for 5+ hours in the middle? Are we spending all that time doing CPU work, and no IO? Is that computations related to the massively overlapping L0?

When observing the minutely LSM state output, I've seen the compaction in-progress bytes number climb very slowly when compacting L0, around 4-6 minutes for each GB compacted. With L0 = 84GB, that's around 5 hours.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487#-:-MwCtI-rA-IaoQ6I1SPz:b2qt7x)* status: 17 of 31 files reviewed, 14 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[db.go, line 1275 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvV8pCX2PHbsOk7i9Cm:-Mw7mPHS6fC3EeDZsUVQ:b-7sbjb3) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1275)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: It might be cleaner, if the compaction is dropped from `pickManual`, and we wouldn't need to add extra logic here.
</blockquote></details>

Talked offline, it's better to exit out early since `calculateInUseKeyRanges` will still return keyranges if the input level is empty.


<!-- Sent from Reviewable.io -->

2022-02-18 19:42 UTC, bananabrick reviewed
Can we run the benchmark on the master branch, with automatic compactions disabled? Or confirm through some other method that disabling automatic compactions is where we're getting most of the benefit, for this particular benchmark. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487#-:-MwDLUZuDEZPleLDrIHX:be84bc8)* status: 17 of 31 files reviewed, 14 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)



<!-- Sent from Reviewable.io -->

2022-02-19 21:26 UTC, mufeez-amjad reviewed
`master` with disabled automatic compactions:
```
real	384m55.905s
user	358m38.165s
sys	22m1.902s
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487#-:-MwIrhDx-O40KKrrzbCt:b-6cxw4z)* status: 17 of 31 files reviewed, 14 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)



<!-- Sent from Reviewable.io -->

2022-02-23 22:29 UTC, mufeez-amjad reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 16 of 31 files reviewed, 13 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[-- commits, line 6 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw3NLlY97q0IV9gnB2p):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Since this is a bigger change, it might be worthwhile to have a detailed commit message, and also format it so that the lines aren't so long.
</blockquote></details>

Updated.
___
*[compaction_picker.go, line 1360 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw3Pgua4IWA3D8zbIZU:-MwcgEDk41A1rfsGw-RN:b-ynod45) ([raw file](https://github.com/cockroachdb/pebble/blob/19e11cfe195fac62eeac044cacb85933c5406255/compaction_picker.go#L1360)):*
<details><summary><i>Previously, mufeez-amjad (Mufeez Amjad) wrote…</i></summary><blockquote>

Good catch. I searched for uses of that function and saw it used in the debug compact command and in a few tests. 

Yes, in the case of background compactions it's likely that without retrying manual compactions the LSM will not be fully compacted. One way to address this issue is to add `conflictsWithInProgress` back but check the key range as well. The ranges won't conflict when using `debug compact` by construction but should catch the cases where there are automatic compactions with overlap. I think we could also change the behaviour of pickManual to retry the compaction if the input levels are being compacted (I'm not entirely sure why `inputRangeAlreadyCompacting` retries the compaction but a file in the range with `isCompacting` doesn't).
</blockquote></details>

I added `conflictsWithInProgress` back but short-circuit the call if the manual compaction was split (because we allow multiple compactions on a level). This should ensure that calls to `db.Compact` with `parallelize=false` function as before.
___
*[db.go, line 1295 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVArFs2iQqIw1jwbsD:-Mwcg4Xb-sBB2FLwl54F:b5by9km) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1295)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

We don't write to the channel in the case where we increment `manual.retries`, but if we assume that the compaction will eventually be retired, then we're fine. But also, the compaction shouldn't be retried, if we're disabling automatic compactions.
</blockquote></details>

Updated my comment, PTAL.


<!-- Sent from Reviewable.io -->

2022-02-24 02:49 UTC, bananabrick approved these changes
> Reviewed 2 of 14 files at r12, 3 of 6 files at r13, 5 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 26 of 31 files reviewed, 17 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[compaction_picker.go, line 1360 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw3Pgua4IWA3D8zbIZU:-MwdUOUW8ysPEME5yirg:bq4950v) ([raw file](https://github.com/cockroachdb/pebble/blob/19e11cfe195fac62eeac044cacb85933c5406255/compaction_picker.go#L1360)):*
<details><summary><i>Previously, mufeez-amjad (Mufeez Amjad) wrote…</i></summary><blockquote>

I added `conflictsWithInProgress` back but short-circuit the call if the manual compaction was split (because we allow multiple compactions on a level). This should ensure that calls to `db.Compact` with `parallelize=false` function as before.
</blockquote></details>

I'm wondering if the `parallelize` param to the `db.Compact` function should be a Pebble Option. You wouldn't have to update the `db.Compact` calls in Pebble, and Cockroach. And adding it to the metamorphic test will also be simpler. Totally up to you.
___
*[compaction_picker.go, line 1365 at r14](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MwdUziy25accTalp1ux:-MwdUziy25accTalp1uy:btxoe5e) ([raw file](https://github.com/cockroachdb/pebble/blob/79def9c3cdb8727caf7a216eb39f9019d7158e05/compaction_picker.go#L1365)):*
> ```Go
> 	// the input/output range is already being compacted, and the manual
> 	// compaction ends with a non-compacted LSM.
> 	// The check is skipped when a manual compaction has been split across a level.
> ```

We should add an explanation of why we don't require this check when we split a compaction. 

```
The check is skipped when a manual compaction has been split across a level because...
```
___
*[db.go, line 1198 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mv_6qkL4_J9LKJSdmWd:-MwdViKe8yQUQSC9s57K:b-ducfcg) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1198)):*
<details><summary><i>Previously, mufeez-amjad (Mufeez Amjad) wrote…</i></summary><blockquote>

I considered adding an int param which can either be 1 or greater than 1 but this wouldn't be the most ideal on the cockroachdb side in terms of readability imo. I opted for a boolean param (default false) to `db.Compact` for improved readability since splitting a compaction into a `n` compactions given `n` is not in the scope of this issue.
</blockquote></details>

Same as my comment about maybe using an Option instead of the parallelize flag.
___
*[db.go, line 1295 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MvVArFs2iQqIw1jwbsD:-MwdWMsECRvfnPQaoCuX:b3ca9fn) ([raw file](https://github.com/cockroachdb/pebble/blob/25fe48276160763bb313c8c4389aa92819c5422a/db.go#L1295)):*
<details><summary><i>Previously, mufeez-amjad (Mufeez Amjad) wrote…</i></summary><blockquote>

Updated my comment, PTAL.
</blockquote></details>

Thanks, looks good.
___
*[db.go, line 1323 at r14](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MwdWYYX-1JBEbYzhOrV:-MwdWYYX-1JBEbYzhOrW:b1os6ty) ([raw file](https://github.com/cockroachdb/pebble/blob/79def9c3cdb8727caf7a216eb39f9019d7158e05/db.go#L1323)):*
> ```Go
> 	endLevel := level + 1
> 	baseLevel := d.mu.versions.picker.getBaseLevel()
> 	if endLevel < baseLevel {
> ```

nit: We could do:

```
if level == 0 {
    endLevel = baseLevel
}
```

It's more specific.
___
*[db.go, line 1336 at r14](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MwdWpMeD9rXYLJslK1F:-MwdWpMf13exXj0OrhQE:b-5mo49c) ([raw file](https://github.com/cockroachdb/pebble/blob/79def9c3cdb8727caf7a216eb39f9019d7158e05/db.go#L1336)):*
> ```Go
> 		})
> 	}
> 	return
> ```

nit: We don't need this return
___
*[testdata/manual_compaction, line 945 at r14](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MwdcG7CDQXbFYUHSi_H:-MwdcG7CDQXbFYUHSi_I:blj0l08) ([raw file](https://github.com/cockroachdb/pebble/blob/79def9c3cdb8727caf7a216eb39f9019d7158e05/testdata/manual_compaction#L945)):*
> ```
> 
> # While we allow 2 concurrent compactions, the ongoing compaction conflicts
> # with the compaction below, and thus it is dropped with no change to the LSM.
> ```

Which compaction is the "it" in this line referring to? Do we need this test anyway? We don't support running with background automatic compactions, and the manual compactions we create should be non overlapping.



_Code quote:_
```
# with the compaction below, and thus it is dropped with no change to the LSM.
```


<!-- Sent from Reviewable.io -->

2022-02-24 23:27 UTC, mufeez-amjad reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1487)* status: 23 of 31 files reviewed, 16 unresolved discussions (waiting on @bananabrick, @jbowens, and @mufeez-amjad)

___
*[compaction_picker.go, line 1360 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1487#-Mw3Pgua4IWA3D8zbIZU:-MwhjQrX6v8hhDq0Jdvh:b9t6mik) ([raw file](https://github.com/cockroachdb/pebble/blob/19e11cfe195fac62eeac044cacb85933c5406255/compaction_picker.go#L1360)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I'm wondering if the `parallelize` param to the `db.Compact` function should be a Pebble Option. You wouldn't have to update the `db.Compact` calls in Pebble, and Cockroach. And adding it to the metamorphic test will also be simpler. Totally up to you.
</blockquote></details>

I think parallelism as an option would be less ideal because one would have to remember to both enable/disable parallelism before/after running a manual compaction. We've seen that we should only enable parallelism in the absence of background compactions, so imo it's better to enforce that explicitly in the code.
___
*[compaction_picker.go, line 1365 at r14](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MwdUziy25accTalp1ux:-MwhVfiZ39YwzMl0fMt0:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/79def9c3cdb8727caf7a216eb39f9019d7158e05/compaction_picker.go#L1365)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

We should add an explanation of why we don't require this check when we split a compaction. 

```
The check is skipped when a manual compaction has been split across a level because...
```
</blockquote></details>

Done.
___
*[db.go, line 1323 at r14](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MwdWYYX-1JBEbYzhOrV:-MwhWIFK6JAmiMHnP3dX:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/79def9c3cdb8727caf7a216eb39f9019d7158e05/db.go#L1323)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: We could do:

```
if level == 0 {
    endLevel = baseLevel
}
```

It's more specific.
</blockquote></details>

Done.
___
*[db.go, line 1336 at r14](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MwdWpMeD9rXYLJslK1F:-MwhWLbZ4g7Xrzwxp1NI:b-yaoeva) ([raw file](https://github.com/cockroachdb/pebble/blob/79def9c3cdb8727caf7a216eb39f9019d7158e05/db.go#L1336)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: We don't need this return
</blockquote></details>

I was surprised to learn this as well, but you still need a return statement with a [named return](https://go.dev/doc/effective_go#named-results). I changed it to `return splitCompactions` to make it more clear.
___
*[testdata/manual_compaction, line 945 at r14](https://reviewable.io/reviews/cockroachdb/pebble/1487#-MwdcG7CDQXbFYUHSi_H:-MwhY73HAD5j1zYuWA3n:bdq1mbq) ([raw file](https://github.com/cockroachdb/pebble/blob/79def9c3cdb8727caf7a216eb39f9019d7158e05/testdata/manual_compaction#L945)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Which compaction is the "it" in this line referring to? Do we need this test anyway? We don't support running with background automatic compactions, and the manual compactions we create should be non overlapping.
</blockquote></details>

I added this test since there was no existing test that tested the case where there is a conflicting compaction that leads to the compaction being dropped by `pickManual`. Even with disabled background compactions, imo it's valuable to keep this test since we want to ensure that we have a safeguard against scheduling interfering manual compactions.


<!-- Sent from Reviewable.io -->

2022-02-27 19:38 UTC, merged