internal/rangekey: add DefragmentingIter
cockroachdb/pebble pull request #1509
Opened 2022-02-12 00:54 UTC by jbowens

Add a DefragmentingIter that wraps a range key iterator, defragmenting
physical fragmentation of range keys during iteration.

During flushes and compactions, range keys may be split at sstable
boundaries. This fragmentation can produce internal range-key bounds that do
not match any of the bounds ever supplied to a user range-key operation. This
physical fragmentation is necessary to avoid excessively wide sstables.

The defragmenting iterator undoes this physical fragmentation, joining spans
with abutting bounds and equal state. The defragmenting iterator supports two
separate methods of determining what is "equal state" for a span. The user
may configure which of the methods of defragmentation they desire at Init
through passing a DefragmentKind enum value:

DefragmentLogical is intended for use during user iteration, joining adjacent
CoalescedSpans if the user-observable logical state is identical.
Specifically, DefragmentLogical defragments abutting spans if the set of
range key suffix-value tuples are identical. This may be used to hide
physical fragmentation from the end user during iteration, ensuring the only
fragmentation observable is the fragmentation introduced by the user's own
operations.

DefragmentInternal is intended for use during compactions, joining adjacent
CoalescedSpans if the internal state is identical between two spans. Range
keys covering a span [a, c) may be split into two sstables, as two spans
[a,b) and [b,c). These range keys' sstables may eventually both be inputs to
the same compaction, and a DefragmentingIter configured with
DefragmentInternal may join the two spans back together before outputting to
a single sstable.

Seeking (SeekGE, SeekLT) poses an obstacle to defragmentation. A seek may
land on a physical fragment in the middle of several fragments. To avoid
needing to defragment in both directions, seeking truncates the defragmented
range key to the seek key and defragments only in the direction of iteration.
An iterator that changes direction after the seek will see the other half of
the fragmented span. An iterator that moves away from the seek key and then
moves back will no longer observe the artifical fragmentation point.

2022-02-12 00:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1509)
<!-- Reviewable:end -->

2022-02-14 19:52 UTC, nicktrav reviewed
Flushing some comments. So far, so good.

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509#-:-MvtlmI1B1PfstmOarr2:b-m4q0uv)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[internal/rangekey/defragment.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-MvtalJT-SxatyCHEgdF:-MvtalJT-SxatyCHEgdG:b-o5zi4z) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L35)):*
> ```Go
> 	// that required their fragmentation has been dropped.
> 	DefragmentInternal DefragmentMethod = iota
> 	// DefragmentLogical configures a defragmentingiter to defragment spans of
> ```

s/defragmentingiter/DefragmentingIter/
___
*[internal/rangekey/defragment.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mvtbls7AGfxEc0YL-VO:-Mvtbls7AGfxEc0YL-VP:b-f6ihz9) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L94)):*
> land on a physical fragment

Could this be "land _within_ a physical fragment"?

> A seek may land on a physical fragment in the middle of several fragments.

Could this sentence be extended to say something like "... in the middle of several fragments that would otherwise be defragmented (or recombined)"?
___
*[internal/rangekey/defragment.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-MvtckNLEKhd_BAdT91A:-MvtckNMAy8hY9ldWZ0S:b-arruay) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L103)):*
> ```Go
> //
> // TODO(jackson): Should we preserve the seek key fragmentation point until the
> // next absolute positioning method?
> ```

Are you thinking of the case where you position, iterate in the original direction, then reverse _but_ still emit the first fragment with its artificial bounds? Or is this something else? Perhaps clarify what this TODO solves?
___
*[internal/rangekey/defragment.go, line 172 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-MvteX2n1ReBMR5daToE:-MvteX2n1ReBMR5daToF:b-i45dh4) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L172)):*
> ```Go
> // properly reflected in readState.
> func (i *DefragmentingIter) Clone() *DefragmentingIter {
> 	return &DefragmentingIter{iter: *i.iter.Clone()}
> ```

Does any of the internal state need to be initialized here on copy? e.g. the `equal` function pointer, the current `iterPos`, `iterSpan`, etc.?
___
*[internal/rangekey/defragment.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-MvtgHAYBsLXfNyMILI5:-MvtgHAYBsLXfNyMILI6:b-e9bja1) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L238)):*
> ```Go
> 		// current iterator position. Skip over the rest of the current iterator
> 		// position's constitutent fragments.
> 		i.defragmentForward(nil)
> ```

In relation to the diagram, does this first call take care of the "defragment forward to land on the first z position" part?

Then the next call takes care of defragmenting forward from `z`?

Same comment for `Prev()`.
___
*[internal/rangekey/defragment.go, line 322 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mvtilyv4EyJCBzqit7B:-Mvtilyv4EyJCBzqit7C:b-hfomuy) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L322)):*
> ```Go
> }
> 
> func (i *DefragmentingIter) defragmentForward(seekKey []byte) *CoalescedSpan {
> ```

Can we document that `seekKey` can be `nil`, in which case this indicates that we're moving forward but not from a "seek" method? Same for the method below?
___
*[internal/rangekey/defragment.go, line 336 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-MvtkUjMA1GOfT7OvhSr:-MvtkUjMA1GOfT7OvhSs:b-wnjamx) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L336)):*
> ```Go
> 			break
> 		}
> 		if i.cmp(i.curr.End, i.iterSpan.Start) != 0 {
> ```

Would it make sense to do this check first, before the `!i.equal` check above, which is presumably more costly due to the looping? In other words, if the current end key is _not_ the same as the next start key, then we don't need to bother with checking the items, as the spans are not abutting.

Same comment for `defragmentBackward`.
___
*[internal/rangekey/defragment.go, line 441 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-MvtjZ_a51yv4cHezWhP:-MvtjZ_a51yv4cHezWhQ:bg7cxd4) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L441)):*
> ```Go
> 
> func equalRangeKeyInternal(cmp base.Compare, a, b *CoalescedSpan) bool {
> 	if a.LargestSeqNum != b.LargestSeqNum || a.Delete != b.Delete || len(a.Items) != len(b.Items) {
> ```

Worth an invariants-enabled check here that the start and end keys for `a` and `b` are the same?


<!-- Sent from Reviewable.io -->

2022-02-14 20:45 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509)* status: 3 of 4 files reviewed, 10 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/defragment.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mvtwbug0-WwaJ8ZdRza:-Mvtwbug0-WwaJ8ZdRzb:bsn3isx) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L38)):*
> ```Go
> 	// range keys if their external, user-visible state is identical.
> 	// specifically, this defragmenting method ignores all state besides the set
> 	// suffix-value tuples. it's intended for use during user iteration, when
> ```

is the difference that this ignores the seqnum while the `DefragmentInternal` does not (since the latter has to construct InternalKeys to output)?
___
*[internal/rangekey/defragment.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-MvtxC-Z6vKB5SjYoMVd:-MvtxC-Z6vKB5SjYoMVe:b-qiqaxi) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L103)):*
> ```Go
> //
> // TODO(jackson): Should we preserve the seek key fragmentation point until the
> // next absolute positioning method?
> ```

Maybe worth delineating the use cases a bit more
- the compaction case is not going to seek. It will start from the beginning and just iterate forward. So this is a non-issue
- An external reader falls into two categories
  - someone trying to construct a "copy" of the state here. We should require them to also proceed in a single direction. CockroachDB examples are export, replica divergence ...
  - someone trying to use the fragments to make some logical sense over some span of interest to them. In which case how we present the fragments when going back and forth doesn't matter (module our need to show only prefix spans for code abstraction cleanliness).
  - a test trying to mimic the previous bullet but without the ability to derive any logical meaning, and therefore using output comparison as a measure of correctness. e.g. metamorphic testing.

Any others? I don't think any of these need this TODO.


<!-- Sent from Reviewable.io -->

2022-02-14 21:39 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509)* status: 3 of 4 files reviewed, 10 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/defragment.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mvtwbug0-WwaJ8ZdRza:-Mvu7txy0lBuunHVVUF0:b-x5r291) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L38)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is the difference that this ignores the seqnum while the `DefragmentInternal` does not (since the latter has to construct InternalKeys to output)?
</blockquote></details>

It's a little more than that. For example, consider these fragments:

```
a.RANGEKEYSET.5: c [(@5=foo)]
a.RANGEKEYUNSET.4:c [@4]
a.RANGEKEYSET.5: c [(@4=foo)]
c.RANGEKEYSET.5: c [(@5=foo)]
```

After being coalesced, these look like two `CoalescedSpan`s:
```
CoalescedSpan{
    LargestSeqNum: 5,
    Start:         "a",
    End:           "c",
    Items:         []SuffixValue{{Suffix: "@5", Value: "foo"}, {Unset: true, Suffix: "@4"},
}
CoalescedSpan{
    LargestSeqNum: 5,
    Start:         "d",
    End:           "d",
    Items:         []SuffixValue{{Suffix: "@5", Value: "foo"},
}
```
`DefragmentInternal` will not defragment these spans, because one has unset `@4`. `DefragmentLogical` _will_ defragment them because they look identical to the user. This is defragmenting more than we need for determinism, but it ensures that every time the `*pebble.Iterator` exposes new `RangeBounds()`, it's because the range-key state actually changed.


<!-- Sent from Reviewable.io -->

2022-02-14 23:37 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509)* status: 3 of 4 files reviewed, 10 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/defragment.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mvtwbug0-WwaJ8ZdRza:-Mvu_SDO3QZLbvkFfAIG:b-o5rxrc) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L38)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

It's a little more than that. For example, consider these fragments:

```
a.RANGEKEYSET.5: c [(@5=foo)]
a.RANGEKEYUNSET.4:c [@4]
a.RANGEKEYSET.5: c [(@4=foo)]
c.RANGEKEYSET.5: c [(@5=foo)]
```

After being coalesced, these look like two `CoalescedSpan`s:
```
CoalescedSpan{
    LargestSeqNum: 5,
    Start:         "a",
    End:           "c",
    Items:         []SuffixValue{{Suffix: "@5", Value: "foo"}, {Unset: true, Suffix: "@4"},
}
CoalescedSpan{
    LargestSeqNum: 5,
    Start:         "d",
    End:           "d",
    Items:         []SuffixValue{{Suffix: "@5", Value: "foo"},
}
```
`DefragmentInternal` will not defragment these spans, because one has unset `@4`. `DefragmentLogical` _will_ defragment them because they look identical to the user. This is defragmenting more than we need for determinism, but it ensures that every time the `*pebble.Iterator` exposes new `RangeBounds()`, it's because the range-key state actually changed.
</blockquote></details>

Thanks.
- DefragmentLogical will defragment because the caller does not care about Unsets (for the same reason that a caller of `pebble.Iterator` does not care about DELs)?
- Can you add this example as a code comment.


<!-- Sent from Reviewable.io -->

2022-02-15 18:23 UTC, nicktrav reviewed
> Reviewed 1 of 4 files at r1, 8 of 8 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509)* status: all files reviewed, 4 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/defragment.go, line 441 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-MvtjZ_a51yv4cHezWhP:-MvyYMJo8sKW0yewepiM:b-vwqh7m) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L441)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

The bounds for `a` and `b` should be abutting but not equal.
</blockquote></details>

Ah, I misinterpreted the call sites.

Given that `i.equal` is checking for "equality of _items_" within two spans (depending on the use-case, internal vs. logical, etc.), could we use `i.itemsEqual` instead, given neither impl cares about the start / end keys?
___
*[testdata/rangekeys, line 85 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mvyax83CT0k00__s6R2:-Mvyax83CT0k00__s6R3:b-s8pi6q) ([raw file](https://github.com/cockroachdb/pebble/blob/2276f020a1a2ef740ed0541bb26ca1b5e5dafa43/testdata/rangekeys#L85)):*
> ```
> cat: (., [cat-dog) @3=beep)
> cat: (., [cat-dog) @3=beep)
> d: (d, [d-dog) @3=beep)
> ```

Were the diffs in these tests due to using a logical defragmenting iter for `pebble.Iterator`?


<!-- Sent from Reviewable.io -->

2022-02-15 19:01 UTC, jbowens reviewed
Added another commit that defragments in both directions, due to this:

> In integrating, I realized there's a problem with this truncation. Imagine a `SeekLT(a@15)`. This introduces an artificial truncation point at `a@15`, which causes a suffixed key to be surfaced in `RangeBounds()`. The end boundary can't just use Prefix(k) since it needs to include `[a@inf, a@15)`. Defragmenting in both directions would solve it. Can you think of any alternatives?

It cleans up the code, but of course is must perform more work than before.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509#-:-MvyiYaZ8Gg36N8bkRbC:b-1rlb81)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[internal/rangekey/defragment.go, line 441 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-MvtjZ_a51yv4cHezWhP:-MvyjNzC4FcmA_1JUdFb:b-qigf8f) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L441)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Ah, I misinterpreted the call sites.

Given that `i.equal` is checking for "equality of _items_" within two spans (depending on the use-case, internal vs. logical, etc.), could we use `i.itemsEqual` instead, given neither impl cares about the start / end keys?
</blockquote></details>

Renamed to `equalState`, since it's more than comparing `i.Items`.
___
*[testdata/rangekeys, line 85 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mvyax83CT0k00__s6R2:-MvykjXm4X8AlEUUHahk:b-ht0ukm) ([raw file](https://github.com/cockroachdb/pebble/blob/2276f020a1a2ef740ed0541bb26ca1b5e5dafa43/testdata/rangekeys#L85)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Were the diffs in these tests due to using a logical defragmenting iter for `pebble.Iterator`?
</blockquote></details>

That's right.


<!-- Sent from Reviewable.io -->

2022-02-15 20:00 UTC, nicktrav approved these changes
Did another pass, including new commit. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509#-:-Mvyy5wG-7nHPYj--qC0:b-7pxqc8)* status: all files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-02-16 18:19 UTC, sumeerbhola requested changes
I'm still reading this -- flushing a few comments. But as I mentioned on slack, don't wait on me for merging. I'll keep sending comments whenever I get time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509#-:-Mw2kMCWEtfA2GR4ni1K:b4z3rmu)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/defragment.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-MvtxC-Z6vKB5SjYoMVd:-Mw2iYmX5Rh5KA0GDZSE:b-ouv9ay) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L103)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Independent of whether any existing code paths would run afoul by this behavior. It is surprising behavior. I was worried unstable bounds could cause some unforeseen complication, even in the future.

In integrating, I realized there's a problem with this truncation. Imagine a `SeekLT(a@15)`. This introduces an artificial truncation point at `a@15`, which causes a suffixed key to be surfaced in `RangeBounds()`. The end boundary can't just use `Prefix(k)` since it needs to include `[a@inf, a@15)`. Defragmenting in both directions would solve it. Can you think of any alternatives?
</blockquote></details>

Its again the lack of ImmediateSuccessor that is preventing us from outputting [x, IS(a)), yes?
I'm fine with defragmenting in both directions.
Even though I've claimed in other reviews that we can extend the observed bounds based on the invariant we know "must hold", I am actually wary of doing that -- it is much better to actually defragment and then check that the invariant that we expect "does hold" (and issuing a corruption error if it doesn't)
___
*[internal/rangekey/defragment.go, line 45 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mw2homV51xlNnbdBJWA:-Mw2homV51xlNnbdBJWB:b-piarpp) ([raw file](https://github.com/cockroachdb/pebble/blob/b41820a5c43124231047108e17b534c9b38730f1/internal/rangekey/defragment.go#L45)):*
> ```Go
> 	//     a.RANGEKEYSET.5: c [(@5=foo)]  \
> 	//     a.RANGEKEYUNSET.4:c [@4]        - CoalescedSpan{@5=foo, unset(@4)}
> 	//     a.RANGEKEYSET.5: c [(@4=foo)]  /
> ```

I am confused why the seqnum of the unset for @4 is lower than the seqnum of the thing it is unsetting.
___
*[internal/rangekey/defragment.go, line 50 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mw2i-jbBNx9I10QrsEF:-Mw2i-jbBNx9I10QrsEG:b-37n6xr) ([raw file](https://github.com/cockroachdb/pebble/blob/b41820a5c43124231047108e17b534c9b38730f1/internal/rangekey/defragment.go#L50)):*
> ```Go
> 	// DefragmentLogical will merge these two coalesced spans because they're
> 	// abutting. It ignores unsets and deletes, whose existence during iteration
> 	// varies depending on compactions.
> ```

nice comment
___
*[internal/rangekey/defragment.go, line 144 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mw2k4JF8_q4HdLKtakZ:-Mw2k4JF8_q4HdLKtak_:b-q9uylt) ([raw file](https://github.com/cockroachdb/pebble/blob/b41820a5c43124231047108e17b534c9b38730f1/internal/rangekey/defragment.go#L144)):*
> ```Go
> ) {
> 	*i = DefragmentingIter{cmp: cmp, split: split, method: defragmentMethod}
> 	i.iter.Init(cmp, formatKey, visibleSeqNum, iter)
> ```

I'm confused by this. How can we use a `rangekey.Iter` in the compaction case given that it has coalesced and therefore lost information on the seqnum of the `CoalescedSpan.Delete`.


<!-- Sent from Reviewable.io -->

2022-02-16 18:56 UTC, sumeerbhola requested changes
I'm going to ignore the tests. I've looked at the rest. Looks good.

> Reviewed 2 of 8 files at r2, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509#-:-Mw2t2lD4vnFUmQnU6ha:b-47nyvj)* status: all files reviewed, 7 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[internal/rangekey/defragment.go, line 126 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mw2qIV30s_1qZQFyDZc:-Mw2qIV30s_1qZQFyDZd:bctctj6) ([raw file](https://github.com/cockroachdb/pebble/blob/b41820a5c43124231047108e17b534c9b38730f1/internal/rangekey/defragment.go#L126)):*
> ```Go
> 	// The value of equalState is dependent on the method of defragmenting being
> 	// performed: internal or logical. The implementations of this function that
> 	// may be used are equalRangeKeyInternal and equalRangeKeyLogical.
> ```

It looks like this does not look at the `Start`, `End` keys to see if they are adjacent, yes?
If so, can you add a code comment.
___
*[internal/rangekey/defragment.go, line 246 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mw2sdQnDLKbMIk740kO:-Mw2sdQnDLKbMIk740kP:bodgbgb) ([raw file](https://github.com/cockroachdb/pebble/blob/b41820a5c43124231047108e17b534c9b38730f1/internal/rangekey/defragment.go#L246)):*
> ```Go
> 		// fragments, defragment forward.
> 		return i.defragmentForward()
> 	case iterPosCurr:
> ```

is there an invariant that i.iterPos == iterPosCurr is equivalent to i.iterSpan == nil


<!-- Sent from Reviewable.io -->

2022-02-16 20:35 UTC, jbowens reviewed
Squashed the two commits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509#-:-Mw3Eejm2SSD3xga5kOq:bc21p30)* status: 7 of 10 files reviewed, 7 unresolved discussions (waiting on @4, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/defragment.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1509#-MvtxC-Z6vKB5SjYoMVd:-Mw2y8iHCJ-mtgwd62Vg:b1ubcge) ([raw file](https://github.com/cockroachdb/pebble/blob/eb12597585ee604b0bf5a113afb032375000fcf4/internal/rangekey/defragment.go#L103)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Its again the lack of ImmediateSuccessor that is preventing us from outputting [x, IS(a)), yes?
I'm fine with defragmenting in both directions.
Even though I've claimed in other reviews that we can extend the observed bounds based on the invariant we know "must hold", I am actually wary of doing that -- it is much better to actually defragment and then check that the invariant that we expect "does hold" (and issuing a corruption error if it doesn't)
</blockquote></details>

Makes sense
___
*[internal/rangekey/defragment.go, line 45 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mw2homV51xlNnbdBJWA:-Mw2xuux2M2eqn0ONTfE:b-u2kp9z) ([raw file](https://github.com/cockroachdb/pebble/blob/b41820a5c43124231047108e17b534c9b38730f1/internal/rangekey/defragment.go#L45)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am confused why the seqnum of the unset for @4 is lower than the seqnum of the thing it is unsetting.
</blockquote></details>

Oops, thanks.
___
*[internal/rangekey/defragment.go, line 50 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mw2i-jbBNx9I10QrsEF:-Mw2xyiU9LKrX9Rb7StW:bni2y2z) ([raw file](https://github.com/cockroachdb/pebble/blob/b41820a5c43124231047108e17b534c9b38730f1/internal/rangekey/defragment.go#L50)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nice comment
</blockquote></details>

:pray:
___
*[internal/rangekey/defragment.go, line 126 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mw2qIV30s_1qZQFyDZc:-Mw2yJo317keNgwz96wG:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b41820a5c43124231047108e17b534c9b38730f1/internal/rangekey/defragment.go#L126)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It looks like this does not look at the `Start`, `End` keys to see if they are adjacent, yes?
If so, can you add a code comment.
</blockquote></details>

Done.
___
*[internal/rangekey/defragment.go, line 144 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mw2k4JF8_q4HdLKtakZ:-Mw2yN_IAUeKM3jRZa8w:b-aj4r6y) ([raw file](https://github.com/cockroachdb/pebble/blob/b41820a5c43124231047108e17b534c9b38730f1/internal/rangekey/defragment.go#L144)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm confused by this. How can we use a `rangekey.Iter` in the compaction case given that it has coalesced and therefore lost information on the seqnum of the `CoalescedSpan.Delete`.
</blockquote></details>

Yeah, this relates to our discussion in the other PR. I am not sure where the logic to coalesce only within snapshot stripes will sit. I've considered two options so far:

1. Either the `rangekey.Iter` or `rangekey.MergingIter` take an optional slice of snapshots, coalescing only within snapshot stripes or returning `Fragments` only within stripes, respectively. In this case, we would probably want to prohibit reverse iteration if a slice of snapshots is provided.
2.  Don't use a `rangekey.Iter` during a compaction, manually feeding the spans of stripes to the `Coalescer` within the compaction-only code path.

I'm now realizing that only the first option actually allows us to reuse `DefragmentingIter` for compactions?
___
*[internal/rangekey/defragment.go, line 246 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mw2sdQnDLKbMIk740kO:-Mw3E00NB3T23vQn39-Z:bs8xlpp) ([raw file](https://github.com/cockroachdb/pebble/blob/b41820a5c43124231047108e17b534c9b38730f1/internal/rangekey/defragment.go#L246)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there an invariant that i.iterPos == iterPosCurr is equivalent to i.iterSpan == nil
</blockquote></details>

Yeah, added an invariant check.


<!-- Sent from Reviewable.io -->

2022-02-16 23:25 UTC, merged

2022-02-16 23:26 UTC, jbowens reviewed
TFTRs!

May need to circle back re: compactions and defragmenting.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509#-:-Mw3qpKfA_OBjuQxw1uQ:b562a5v)* status: 7 of 10 files reviewed, 7 unresolved discussions



<!-- Sent from Reviewable.io -->

2022-02-17 17:54 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509)* status: 7 of 10 files reviewed, 7 unresolved discussions

___
*[internal/rangekey/defragment.go, line 144 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mw2k4JF8_q4HdLKtakZ:-Mw7ko9F0gp4x_aBCwvb:b9o28rp) ([raw file](https://github.com/cockroachdb/pebble/blob/b41820a5c43124231047108e17b534c9b38730f1/internal/rangekey/defragment.go#L144)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, this relates to our discussion in the other PR. I am not sure where the logic to coalesce only within snapshot stripes will sit. I've considered two options so far:

1. Either the `rangekey.Iter` or `rangekey.MergingIter` take an optional slice of snapshots, coalescing only within snapshot stripes or returning `Fragments` only within stripes, respectively. In this case, we would probably want to prohibit reverse iteration if a slice of snapshots is provided.
2.  Don't use a `rangekey.Iter` during a compaction, manually feeding the spans of stripes to the `Coalescer` within the compaction-only code path.

I'm now realizing that only the first option actually allows us to reuse `DefragmentingIter` for compactions?
</blockquote></details>

My mental model was the following:
- FragmentIterator interface would present gathered fragments
- MergingIter would be an implementation of FragmentIterator.
- DefragmentingIter wraps a FragmentIterator and also implements FragmentIterator.
- rangekey.Iter is a trivial wrapper of FragmentIterator that maps fragments to CoalescedSpan. This is for external consumption in `pebble.Iterator`. `pebble.Iterator` will directly use a `rangekey.Iter` and we don't need a `rangekey.Iterator` interface.
- Compaction can use a different wrapper of FragmentIterator that understands snapshot stripes and produce `[]CoalescedSpan` at each position.

The problem with the above is that we do need an interleaving iter for internal use. Maybe we lift a bunch of that code out of `pebble.Iterator` and make an interleaving iter that takes as input a `internalIterator` and a `FragmentIterator`. This would be used by `pebble.Iterator` (so no more rangekey.Iter, since pebble.Iterator can map Fragments => CoalescedSpan), and the compaction code. 


<!-- Sent from Reviewable.io -->

2022-02-17 18:15 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509)* status: 7 of 10 files reviewed, 7 unresolved discussions

___
*[internal/rangekey/defragment.go, line 144 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1509#-Mw2k4JF8_q4HdLKtakZ:-Mw7quTEDFeygGTin-05:b4h1dli) ([raw file](https://github.com/cockroachdb/pebble/blob/b41820a5c43124231047108e17b534c9b38730f1/internal/rangekey/defragment.go#L144)):*
> DefragmentingIter wraps a FragmentIterator and also implements FragmentIterator.

The defragmenting iter needs to consume `CoalescedSpan`s, because for the iteration use case it needs to have already resolved deletes, unsets and shadowing.

In the compaction use case, ideally it also has already applied range-key logic, to ensure we can defragment in all the cases that we can. For example:
```
RangeKeyUnset([a,b), @1), RangeKeySet([a,b),@1=foo), RangeKeyUnset([b,c),@1)
```
Before coalescing, the `[a,b)` and `[b,c)` `Fragments` differ, but after they can be defragmented, as long as no snapshot was prohibiting dropping ` RangeKeySet([a,b),@1=foo)`.


<!-- Sent from Reviewable.io -->

2022-02-17 19:41 UTC, sumeerbhola commented
> The defragmenting iter needs to consume CoalescedSpans, because for the iteration use case it needs to have already resolved deletes, unsets and shadowing.

I may be missing something here, but I think this is a small tweak to the above framework -- one can apply the coalescing logic to Fragments to produce another Fragments. This could even be done via an optional output transform func that is applied by the `MergingIter` itself. Then the Fragments => CoalescedSpan transformation could be completely deterministic and be done at a higher layer using a pure func.

2022-02-17 21:43 UTC, jbowens reviewed
I think the awkward bit with that organization is that the act of coalescing requires building up a data structure essentially equivalent to a `CoalescingSpan` which we would then discard, and then producing another Fragments potentially requires re-encoding fragments (for example, unsetting `@2` within a `RangeKeySet([a,c), [@1=foo,@2=bar,@3=bax])`.

Thoughts on compactions configuring `rangekey.Iter` with the slice of snapshots, yielding multiple `CoalescedSpans` there during a compaction? In that case, all range-key iterators make use of the defragmenting iterator, and we can remove the `Iterator` interface through just using concrete types (or combining `rangekey.Iter` and `rangekey.DefragmentingIter` into one)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509#-:-Mw8a-at9eiiYaIc6D1K:b-nqy2oy)* status: 7 of 10 files reviewed, 7 unresolved discussions



<!-- Sent from Reviewable.io -->

2022-02-20 15:16 UTC, sumeerbhola commented
It is possible we are talking about the same thing, or close enough, or different but doesn't matter what we choose. I'll try to state the revised version of what I was sketching, and what I understood from your sketch, and then we can see which it is.

Sketch 1:
Fragments (may need a better name) becomes structured, like CoalescedSpan, but can hold uncoalesced information. So no reencoding needed after it is decoded (this is the same comment from your other PR), which would eliminate a concern you raised.
```
type Fragments struct {
	Start, End []byte
	Items []RangeItem
}

type RangeItem struct {
        Kind InternalKeyKind
	SeqNum uint64
        Suffix []byte
	Value  []byte
}
```
- FragmentIterator interface would present gathered Fragments
- MergingIter would be an implementation of FragmentIterator. If would be configured with a transform `func(Fragments) Fragments` that can discard unneeded information from output Fragments, or completely drop Fragments. For the pebble.Iterator path it can drop unsets and deletes and Fragments that only contain unsets and deletes. For compactions this transform would be snapshot aware.
- DefragmentingIter wraps a FragmentIterator and also implements FragmentIterator.
- InterleavingIter wraps a FragmentIterator and Internalterator and interleaves points and keys. This is mostly the logic of today's rangekey.InterleavingIter but without eliding Fragments that do not contain sets. Also it needs to specify when the Fragments has changed so that compactions know not to output the same thing repeatedly.
- pebble.Iterator uses InterleavingIter. It will need to ignore Fragments that do not contain sets. Also, it can do a trivial transform from Fragments to CoalescedSpan.
- Compactions use IterleavingIter.

Sketch 2:
- Continue having a FragmentIterator interface with ungathered but fragmented range keys at the base of the iterator tree.
- Gather them into Fragments in rangekey.MergingIter.
- MergingIter is used by rangeKey.Iter which is configured to be snapshot aware and produces []CoalescedSpans at each position. Usually these will be one CoalescedSpan in this slice. We would change the interface of rangekey.Iterator to match this.
- DefragmentingIter consumed MergingIter and also implements rangekey.Iterator.
- InterleavingIter wraps an InternalIterator and rangekey.Iterator. Same change needed to specify when the []CoalescedSpans has changed, so that compactions know.
- pebble.Iterator and compactions use InterleavingIter.

I think we'll want to hide rangekey.MergingIter behind an interface for flexibility (testing etc.) of DefragmentingIter.

- We need 3 interfaces in sketch 2: FragmentIterator, MergingIter*, Iter, compared to just FragmentIterator in sketch 1. Having a single InternalIterator interface for points has been very helpful in terms of being able to plug things together in flexible ways, and in improving code comprehension. You said in the previous comment that we could remove the rangekey.Iterator interface but I think we want it for flexibility in testing. Am I missing something here?
- We are undoing the gathering work that has been performed by the leaf iterators in sketch 2, that we don't undo in sketch 1 (which means fewer key comparisons).
- (nit) having a []CoalescedSpans that usually contains a single CoalescedSpans and then internally a single SuffixItems (so nested single element slices) suggests that the interface is not quite right. Also all these CoalescedSpans have the same Start, End that is being duplicated.

2022-02-23 19:36 UTC, jbowens reviewed
I have a few questions/clarifications on the two sketches:

Sketch 1:
* Since the `FragmentIterator` is used for range deletions, would this structured `Fragments` type also be used for range deletions? And similar to range-key deletions it would leave `Suffix` and `Value` empty?

Sketch 2:
* I was imagining the `FragmentIterator` interface _would_ be propagated all the way to the base of the iterator tree, but I was imagining it as unstructured fragments (more akin to the existing `Fragments` type in that other PR).
* I was not imagining returning `[]CoalescedSpans`, but instead allowing returning exactly overlapping coalesced spans akin to how the `rangekey.MergingIter` currently on the master branch behaves. This complexity would be nice to drop though.
 
The big thing I was missing from your suggestion was the added structure to `Fragments`. I prefer sketch 1 with structured fragments too.

In terms of getting there, it seems like we need to first disentangle `FragmentIterator` from `base.InternalIterator`, so that they can begin diverging. The biggest obstacle here is range deletions. During compactions, we include range deletion iterators in the point `mergingIter`, which requires range deletions to implement `base.InternalIterator`.

I suppose we could use the same iterator stack as you sketched for range keys for range deletions, interleaving rangedels using the `InterleavingIter`, and refactoring the `InterleavingIter` to be agnostic to the kind of the span it's interleaving.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509#-:-MwbcrIPEsHFh5kVBnrB:biuvwy1)* status: 7 of 10 files reviewed, 7 unresolved discussions



<!-- Sent from Reviewable.io -->

2022-02-23 20:45 UTC, jbowens reviewed
> 	Items []RangeItem

One obstacle to work out is how to avoid excessive allocations of the `Items` slice. If even low-level leaf iterators need to parse and populate the `Items` slice, how do we avoid every read of a range deletion or range key from allocating a new slice? A `fragmentBlockIter` could have a small embedded array for these items, but then the `Items` slice is no longer stable if the iterator is moved.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1509#-:-Mwc5hrU51Xe6LobZQ-e:b-d4azhq)* status: 7 of 10 files reviewed, 7 unresolved discussions



<!-- Sent from Reviewable.io -->

2022-02-24 15:24 UTC, sumeerbhola commented
> Since the FragmentIterator is used for range deletions, would this structured Fragments type also be used for range deletions? And similar to range-key deletions it would leave Suffix and Value empty?

Agreed, that we need it to be general enough for RANGEDELs. I don't have any strong opinion on the exact struct as long as it fully parses everything out.

>  The biggest obstacle here is range deletions. During compactions, we include range deletion iterators in the point mergingIter, which requires range deletions to implement base.InternalIterator.

I agree. I'll go stare at that code again.

> A fragmentBlockIter could have a small embedded array for these items, but then the Items slice is no longer stable if the iterator is moved.

Do we need the slice to be stable if the iterator is moved? I was hoping that with this `Fragments` struct approach, from the bottom-up, the whole iterator tree would only need memory stability at the current iterator position.

2022-02-24 17:13 UTC, sumeerbhola commented
> The biggest obstacle here is range deletions. During compactions, we include range deletion iterators in the point mergingIter, which requires range deletions to implement base.InternalIterator.
> I suppose we could use the same iterator stack as you sketched for range keys for range deletions, interleaving rangedels using the InterleavingIter, and refactoring the InterleavingIter to be agnostic to the kind of the span it's interleaving.

- I do think InterleavingIter should be agnostic to the kinds of keys in a Fragments span. I think it allows us more flexibility in the future.
- Using InterleavingIter for compactions, as I had sketched above, was partly motivated by the odd way we do merging for the compactionIter, as you yourself noted.
- One negative of how we do compactions is that all the RANGEDELs across all compacting files get loaded into memory up-front. The use of InterleavingIter or keyspan.MergingIter has the promise that we could eliminate that behavior (or perhaps not, because of the atomic compaction units and RANGEDELs not being properly truncated).
- That said, it does mean that InterleavingIter has to complicate its interface (expose when the Fragments have changed). And it does mean more surgery of how compactionIter gets constructed. I wonder if the following alternative could be a temporary solution, subject to future improvement (sketched here for RANGEDELs but also applies to range keys):
  - Wrap a keyspan.MergingIter to implement InternalIterator, but only implement the InternalIterator methods that are needed for the sequential iteration of compactionIter.
  - Keep using pebble.mergingIter in a similar way, but instead of one level per file for the RANGEDEL InternalIterator, use the single keyspan.MergingIter as a level. Also stash the keyspan.MergingIter in the compaction struct. Whenever a RANGEDEL InternalKey is returned, the compaction struct can grab the Fragments from the keyspan.MergingIter and feed them all to the rangeDelFrag.

2022-02-24 21:54 UTC, jbowens commented
> One negative of how we do compactions is that all the RANGEDELs across all compacting files get loaded into memory up-front. The use of InterleavingIter or keyspan.MergingIter has the promise that we could eliminate that behavior (or perhaps not, because of the atomic compaction units and RANGEDELs not being properly truncated).

I think maybe we could with a `RANGEDEL` level iterator that is capable of accumulating fragments across multiple files when an atomic compaction unit is larger than 1 file. Or perhaps we should prioritize #1495, so that a future release _will_ be able to make the assumption that `RANGEDEL`s are properly truncated.

> I wonder if the following alternative could be a temporary solution, subject to future improvement (sketched here for RANGEDELs but also applies to range keys): 

Thanks, I think this is useful as a very temporary intermediary state, allowing us to move `keyspan.FragmentIterator` away from `base.InternalIterator` without needing to simultaneously generalize `InterleavingIterator`. I drafted something here https://github.com/cockroachdb/pebble/commit/af56ce4c37c13048f01e41d85e80b4fa6adcd0f6.

2022-02-26 01:14 UTC, sumeerbhola commented
https://github.com/cockroachdb/pebble/commit/af56ce4c37c13048f01e41d85e80b4fa6adcd0f6 looks good