sstable: add RangeKeyIter iterator
cockroachdb/pebble pull request #1513
Opened 2022-02-15 16:21 UTC by jbowens

Add a range key iterator type intended to be used externally for reading the
range-keys contained within an sstable. The interface is simple, providing
forward iteration from beginning to end only. Each individual range key is
surfaced separately, even if coalesced into single physical fragments.

2022-02-15 16:21 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1513)
<!-- Reviewable:end -->

2022-02-15 16:22 UTC, jbowens reviewed
@erikgrinaker A simple forward iteration interface is enough, right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1513#-:-MvyBEvfD9yCc_8w6b76:b1jfebc)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @erikgrinaker, @nicktrav, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-02-15 16:50 UTC, erikgrinaker reviewed
On second thought, we'd ideally want the CRDB `SSTIterator` to satisfy the `SimpleMVCCIterator` interface, which uses interleaved point/range key iteration. This is based on `sstable.Reader.NewIter()`. Would it be possible to reuse the interleaving logic that we get from `pebble.Iterator`?

If not, nbd -- I can create separate SST iterator implementations for point and range keys, which covers my needs for now, and we can revisit this later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1513#-:-MvyGNdW6Ll-tkdVER1J:bydoo9n)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @nicktrav and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-02-15 17:58 UTC, nicktrav approved these changes
Nice. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1513#-:-MvyX1j6C9atRcmzeAaH:b-i2pyn4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-02-16 20:39 UTC, sumeerbhola requested changes
> On second thought, we'd ideally want the CRDB SSTIterator to satisfy the SimpleMVCCIterator interface, which uses interleaved point/range key iteration.

Where is this sst originating from? We can't defragment across ssts in this context, so we would need to expose range keys that are not prefix keys. I'm worried about polluting the `SimpleMVCCIterator` interface -- I thought we had managed to come up with a scheme such that our common iterator interfaces in the storage package would expose [start, end) pairs that were `roachpb.Key`s.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1513#-:-Mw3Ed7e20PxGuPnabW_:b-qjmu9s)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens)

___
*[sstable/external.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1513#-Mw3DXIa4WKnkvKSj7zd:-Mw3DXIa4WKnkvKSj7ze:b-wbk0n0) ([raw file](https://github.com/cockroachdb/pebble/blob/da14db2931601ca80fa28a04f26c0b7150c7cbae/sstable/external.go#L100)):*
> ```Go
> 	endKey, value, ok := rangekey.DecodeEndKey(i.iterKey.Kind(), v)
> 	if !ok {
> 		panic("pebble: unable to decode rangekey end")
> ```

I believe this can happen due to a corruption, in which case we should not panic.


<!-- Sent from Reviewable.io -->

2022-02-16 20:51 UTC, erikgrinaker reviewed
>Where is this sst originating from? We can't defragment across ssts in this context, so we would need to expose range keys that are not prefix keys. I'm worried about polluting the SimpleMVCCIterator interface -- I thought we had managed to come up with a scheme such that our common iterator interfaces in the storage package would expose [start, end) pairs that were roachpb.Keys.

These will e.g. be emitted by `Export` or ingested by `AddSSTable`, so they're generated by client and server logic. Consider e.g. streaming replication, which will reads events off of a rangefeed, build SSTs which include range tombstones, and ingest these into the target cluster. Requiring range keys to have `roachpb.Key` bounds seems perfectly fine for these, and we can assert that in `AddSSTable` during race test builds (or maybe always, if it's cheap enough).

The iteration is needed e.g. by backup restoration reading exported SSTs from an S3 bucket somewhere, combining them to figure out the latest visible point keys, then building  an SST containing the final visible point keys to be ingested and restored. It's also needed for tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1513#-:-Mw3GF7MCH_pjv8rJbQz:b-f95egj)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens)



<!-- Sent from Reviewable.io -->

2022-02-23 16:52 UTC, jbowens commented
Closing in favor of #1529.

2022-02-23 16:52 UTC, closed without merging