db: add external sstable merging iterator
cockroachdb/pebble pull request #1529
Opened 2022-02-22 23:06 UTC by jbowens

Add a pebble.NewExternalIter function that may be used to construct a
*pebble.Iterator that reads from a provided slice of sstables rather than
committed database state. Input sstables are required to contain all
zero-sequence number keys. Shadowing of keys is resolved by treating the files
as ordered in reverse chronological order.

This iterator is intended to replace the storage package's multiIterator.

Close #1526.

2022-02-22 23:06 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1529)
<!-- Reviewable:end -->

2022-02-22 23:18 UTC, jbowens reviewed
Still need to flesh out test coverage.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1529#-:-MwYiXF272FQWF5eRPut:b-frb9o2)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @erikgrinaker, @nicktrav, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-02-23 12:57 UTC, erikgrinaker reviewed
Thanks! How should overlapping range keys across SSTs be handled? This is relevant for backups, as we discussed, where two SSTs may have range keys `[a-d)@3` and `[c-e)@3` because we're resuming the second export from e.g. `c@5`. In these cases, the suffixes and values for these range keys will be the same.

I suppose if we seek to `c@6` then we'd hit the first range key, exposed as `[a-d)`, and when we get to `c@5` we'd expose `[c-e)`? Or will we somehow merge them or truncate the bounds?

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1529#-:-MwacrrDC-uC4vZSCmc7:b-qlrng5)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[external_iterator.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1529#-MwacEZ_E8gCaWRPxf9N:-MwacEZ_E8gCaWRPxf9O:bnebq3a) ([raw file](https://github.com/cockroachdb/pebble/blob/23597924f1badd04b60491cce1bd1a927cee8008/external_iterator.go#L26)):*
> ```Go
> 	o *Options,
> 	iterOpts *IterOptions,
> 	maxTableFormat sstable.TableFormat,
> ```

Do we need this? Shouldn't Pebble just error on table formats greater than the ones it knows about, and accept the rest? 


<!-- Sent from Reviewable.io -->

2022-02-23 15:56 UTC, sumeerbhola requested changes
> I suppose if we seek to c@6 then we'd hit the first range key, exposed as [a-d), and when we get to c@5 we'd expose [c-e)? Or will we somehow merge them or truncate the bounds?

My understanding is that it will be the merged bound since we are using the defragmenting iter in this code.

> Reviewed 6 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1529#-:-MwbE56PCUhKP8TYzMcq:b5t765q)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @erikgrinaker, @jbowens, @nicktrav, and @sumeerbhola)

___
*[external_iterator.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1529#-MwbEhSI40bw3C3gS-A4:-MwbEhSI40bw3C3gS-A5:b-l0ttx3) ([raw file](https://github.com/cockroachdb/pebble/blob/23597924f1badd04b60491cce1bd1a927cee8008/external_iterator.go#L20)):*
> ```Go
> // input files slice must be sorted in reverse chronological ordering. A key in
> // an a file at a lower index will shadow a key with an identical user key
> // contained within a file at a higher index.
> ```

btw, in the CockroachDB use case do we expect
- anything other than trivial shadowing (e.g. same point key => value).
- range key unsets or deletes
___
*[sstable/block.go, line 993 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1529#-MwbHdIx6f2oiw-9mI57:-MwbHdIx6f2oiw-9mI58:b-hirek9) ([raw file](https://github.com/cockroachdb/pebble/blob/23597924f1badd04b60491cce1bd1a927cee8008/sstable/block.go#L993)):*
> ```Go
> }
> 
> type rangeKeyIter struct {
> ```

This code repetition is unfortunate. 
Can we share the same code if we specify the constraint on what key kinds are permitted when constructing it? 


<!-- Sent from Reviewable.io -->

2022-02-23 16:48 UTC, jbowens reviewed
Yeah, the defragmenting iterator will merge the bounds. I added a test case demonstrating the merging.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1529#-:-MwbTt7y6rr7soveihET:b-ww0jut)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @erikgrinaker, @nicktrav, and @sumeerbhola)

___
*[external_iterator.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1529#-MwbEhSI40bw3C3gS-A4:-MwbT1sHAHzK57LUqV_3:b-dd6rs3) ([raw file](https://github.com/cockroachdb/pebble/blob/23597924f1badd04b60491cce1bd1a927cee8008/external_iterator.go#L20)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

btw, in the CockroachDB use case do we expect
- anything other than trivial shadowing (e.g. same point key => value).
- range key unsets or deletes

</blockquote></details>

My understanding is that those are the only cases of shadowing we expect in CockroachDB ^
___
*[external_iterator.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1529#-MwacEZ_E8gCaWRPxf9N:-MwbSyFq42n6diezBYk5:b-g5q05t) ([raw file](https://github.com/cockroachdb/pebble/blob/23597924f1badd04b60491cce1bd1a927cee8008/external_iterator.go#L26)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Do we need this? Shouldn't Pebble just error on table formats greater than the ones it knows about, and accept the rest? 
</blockquote></details>

Good call, removed! 
___
*[sstable/block.go, line 993 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1529#-MwbHdIx6f2oiw-9mI57:-MwbTJY20nw_FMBu8uRg:b-v2j5k5) ([raw file](https://github.com/cockroachdb/pebble/blob/23597924f1badd04b60491cce1bd1a927cee8008/sstable/block.go#L993)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This code repetition is unfortunate. 
Can we share the same code if we specify the constraint on what key kinds are permitted when constructing it? 
</blockquote></details>

Yeah, the writing was already on the wall for this reuse of `blockIter` to directly implement `keyspan.FragmentIterator`, since we intend to disentangle `keyspan.FragmentIterator` and `base.InternalIterator`. I updated this type to be used for both range deletions and range keys, and to explicitly implement `keyspan.FragmentIterator` rather than relying on the `blockIter` embedded type to transparently satisfy it.


<!-- Sent from Reviewable.io -->

2022-02-23 21:24 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 3 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1529#-:-MwcT4Gr9kSMGdKlSHQN:bg7igkv)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @erikgrinaker, @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[sstable/block.go, line 995 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1529#-MwcS2Ii-QscAzR-z3_r:-MwcS2Ii-QscAzR-z3_s:b-zfrlwr) ([raw file](https://github.com/cockroachdb/pebble/blob/df5ff62f7f6083013bd1cda830231755ee1a328c/sstable/block.go#L995)):*
> ```Go
> 	// TODO(jackson): Remove remaining dependencies on the internal
> 	// value being propagated via positioning methods and refactor the
> 	// FragmentIterator to be indepenedent of base.InternalIterator.
> ```

independent


<!-- Sent from Reviewable.io -->

2022-02-24 00:23 UTC, nicktrav approved these changes
Nice! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 10 of 10 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1529#-:-Mwd5rMo6ZfWPEc5PrqW:bfd61qr)* status: all files reviewed, 5 unresolved discussions (waiting on @erikgrinaker, @itsbilal, @jbowens, and @sumeerbhola)

___
*[external_iterator.go, line 19 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1529#-Mwd27isA1mo1BWDpvM0:-Mwd27isA1mo1BWDpvM1:b-lirmsl) ([raw file](https://github.com/cockroachdb/pebble/blob/df5ff62f7f6083013bd1cda830231755ee1a328c/external_iterator.go#L19)):*
> ```Go
> // Input sstables may contain point keys, range keys, range deletions, etc. The
> // input files slice must be sorted in reverse chronological ordering. A key in
> // an a file at a lower index will shadow a key with an identical user key
> ```

nit: key in a file
___
*[sstable/block.go, line 968 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1529#-Mwd3q3q8YiaOK-ytmlR:-Mwd3q3q8YiaOK-ytmlS:bcoy7t4) ([raw file](https://github.com/cockroachdb/pebble/blob/df5ff62f7f6083013bd1cda830231755ee1a328c/sstable/block.go#L968)):*
> ```Go
> 
> 	// decode the end key from a fragment's raw internal value. Range
> 	// deletions store the end key directly as the value, whereas range
> ```

nit: whereas other range key kinds ... 
___
*[testdata/external_iterator, line 1 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1529#-Mwd5fHb4iyqIDH0M55j:-Mwd5fHb4iyqIDH0M55k:b-9fqeo9) ([raw file](https://github.com/cockroachdb/pebble/blob/df5ff62f7f6083013bd1cda830231755ee1a328c/testdata/external_iterator#L1)):*
> ```
> build 1
> ```

Great test!


<!-- Sent from Reviewable.io -->

2022-02-24 01:25 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1529#-:-MwdKJ4t1hoA9xokgMew:bz5mair)* status: 7 of 11 files reviewed, 5 unresolved discussions (waiting on @erikgrinaker, @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-02-24 01:36 UTC, merged

2022-02-24 09:30 UTC, erikgrinaker reviewed
> Yeah, the defragmenting iterator will merge the bounds. I added a test case demonstrating the merging.

Great stuff, thanks for getting this in so fast!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1529#-:-Mwf3D5c7b63l3cEODXB:b-83l9g4)* status: 7 of 11 files reviewed, 4 unresolved discussions

___
*[external_iterator.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1529#-MwbEhSI40bw3C3gS-A4:-Mwf2aCV9YN0beEHTY1e:b-xvpby) ([raw file](https://github.com/cockroachdb/pebble/blob/23597924f1badd04b60491cce1bd1a927cee8008/external_iterator.go#L20)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

My understanding is that those are the only cases of shadowing we expect in CockroachDB ^
</blockquote></details>

I believe that's accurate, yeah. But I'm not intimately familiar with the bulk IO code.


<!-- Sent from Reviewable.io -->