manifest: add methods for extending table bounds
cockroachdb/pebble pull request #1535
Opened 2022-02-24 02:52 UTC by nicktrav

**Note for reviewers**

This is a fairly sizable patch given the many places where the smallest / largest fields were being set directly (and hence the motivation for the patch in the first place). Fortunately most of the diff comes from updating tests.

It might be beneficial to first review the updates in the `manifest` package (`version.go` and `version_edit.go`, and  corresponding data-driven test in `file_metadata_bounds`. Then review the non-test updates to use the new methods in the following:
- `compaction.go`
- `db.go`
- `flush_external.go`
- `ingest.go`

The remainder of the changes are to test files, and are fairly mechanical changes, so probably don't need as much scrutiny.

---

Currently, `FileMetadata` exposes three pairs of keys representing
bounds for a table - one each for point keys, range keys and the overall
bounds for a table. The pair for the overall bounds for the table are a
function of the point and range pairs and could technically be derived,
but instead these overall bounds are materialized on the `FileMetadata`
struct directly for performance reasons (it is faster to dereference the
struct fields than making a function call to perform one or more
comparisons).

With the addition of two pairs of bounds in #1521 for the point and
range bounds, there is a risk that a caller forgets to set a pair of
bounds, violating the invariant that the overall point and range bounds
are internally consistent with the point and range key bounds.

To mitigate this risk, introduce methods on `manifest.FileMetadata` that
can be used to "extend" the point or range key bounds for a table. These
methods will maintain the invariant that the overall bounds for the
table are computed directly from the point and range bounds.

The methods, `MaybeExtend{Point,Range}KeyBounds`, are intended for
"optimistic" use - a table's point, range and / or overall bounds may
not necessarily be extended by a call to the respective methods if the
existing bounds are smaller or larger than the provided bounds. This
confines the comparisons to these method calls, as opposed to having the
caller perform the checks to determine when bounds should be updated. As
these fields are set once and read multiple times, this is considered a
reasonable compromise.

Update all existing call sites that directly set the existing
`FileMetadata` smallest / largest bound fields to instead use the new
methods for extending bounds. The only remaining call sites that set
fields directly are limited to the `manifest` package and one call site
in `ingest.go` that needs to mutate sequence numbers. These calls sites
that store values in the fields directly are explicitly commented to
indicate why the fields are being set directly.

One alternative considered was to unexport the smallest / largest fields
and gate access behind methods. However, as mentioned above, for
performance reasons it beneficial to keep these fields exported.

2022-02-24 02:52 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1535)
<!-- Reviewable:end -->

2022-02-24 02:56 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1535)* status: 0 of 22 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/manifest/version.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1535#-MwddnFZEjfydPouTmIh:-MwddnFZEjfydPouTmIi:b-lmldap) ([raw file](https://github.com/cockroachdb/pebble/blob/64785d0250712cde42c5f918b7856038c464fe1a/internal/manifest/version.go#L106)):*
> ```Go
> 	SmallestPointKey InternalKey
> 	LargestPointKey  InternalKey
> 	HasPointKeys     bool
> ```

Coincidentally, these `HasPointKey` and `HasRangeKey` fields will be useful when we make the version edit changes to persist the types of keys we have present on a table.
___
*[internal/manifest/version.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1535#-MwddUuT-tdvsAILWkHd:-MwddUuT-tdvsAILWkHe:b-i2ourd) ([raw file](https://github.com/cockroachdb/pebble/blob/64785d0250712cde42c5f918b7856038c464fe1a/internal/manifest/version.go#L155)):*
> ```Go
> // NB: calling this method should be preferred to manually setting the bounds by
> // manipulating the fields directly, to maintain certain invariants.
> func (m *FileMetadata) MaybeExtendPointKeyBounds(cmp Compare, smallest, largest InternalKey) {
> ```

Naming is hard - open to suggestions on something a little less verbose than `MaybeExtend{Point,Range}KeyBounds`. Though, they do convey the "maybe" nature of the calls.


<!-- Sent from Reviewable.io -->

2022-02-24 16:16 UTC, sumeerbhola requested changes
I like the approach. Haven't read much of the PR, but sending some initial comments.

> One alternative considered was to unexport the smallest / largest fields
> and gate access behind methods. However, as mentioned above, for
> performance reasons it beneficial to keep these fields exported.

Won't those methods be inlined? Does `-gcflags=-m` show that they won't, if you make that change?

> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1535#-:-MwgTLpp5FvwKtLm2ii9:b-jvd2lh)* status: 1 of 22 files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, and @nicktrav)

___
*[internal/manifest/version.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1535#-MwddnFZEjfydPouTmIh:-MwgUGAJ0s4NbUFNjr-M:bw38imv) ([raw file](https://github.com/cockroachdb/pebble/blob/64785d0250712cde42c5f918b7856038c464fe1a/internal/manifest/version.go#L106)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Coincidentally, these `HasPointKey` and `HasRangeKey` fields will be useful when we make the version edit changes to persist the types of keys we have present on a table.
</blockquote></details>

We may want to optimize the sizeof FileMetadata since we have one for each file. Do you know what it was and what it is now? Maybe play around with shifting some of these bools to one place to reduce the padding for alignment.
___
*[internal/manifest/version.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1535#-MwddUuT-tdvsAILWkHd:-MwgV5WV0CohS8Eo6tU6:b-kkdo5s) ([raw file](https://github.com/cockroachdb/pebble/blob/64785d0250712cde42c5f918b7856038c464fe1a/internal/manifest/version.go#L155)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Naming is hard - open to suggestions on something a little less verbose than `MaybeExtend{Point,Range}KeyBounds`. Though, they do convey the "maybe" nature of the calls.
</blockquote></details>

I am bad at naming, but I'd be satisfied with simply `ExtendPointKeyBounds`.
___
*[internal/manifest/version_edit.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1535#-MwgVXJuDdLMlqpHACEX:-MwgVXJv13uzzYH2E_2N:b-y95i7w) ([raw file](https://github.com/cockroachdb/pebble/blob/b1b77bc4b742a3975866bfd80b351bee1b38d652/internal/manifest/version_edit.go#L274)):*
> ```Go
> 					// manifest is updated to support range keys, which will most likely
> 					// leverage a bitset to infer which key types (points or ranges) are
> 					// used for the overall smallest and largest keys.
> ```

I didn't understand the bitset comment. Is that to avoid the key comparisons for each file when opening the DB?


<!-- Sent from Reviewable.io -->

2022-02-24 17:06 UTC, nicktrav reviewed
> Won't those methods be inlined? Does -gcflags=-m show that they won't, if you make that change?

We'd thought of this, but @jbowens and I had discussed direct field access as a compromise between dedicated "getters", and direct field sets and gets.

Given the "getters" would be so simple now as to be a direct field access (I moved the comparisons onto the write path in this patch), it probably makes sense to have getters and unexport the fields (provided the methods inline, and I'd be shocked if they didn't).

I'll follow up.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1535#-:-MwgeuZR3NaeiqKDmrwR:b-mqfv4t)* status: 1 of 22 files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/manifest/version.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1535#-MwddnFZEjfydPouTmIh:-Mwgem6m-m4e4u87fwDH:b-y4zdgm) ([raw file](https://github.com/cockroachdb/pebble/blob/64785d0250712cde42c5f918b7856038c464fe1a/internal/manifest/version.go#L106)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We may want to optimize the sizeof FileMetadata since we have one for each file. Do you know what it was and what it is now? Maybe play around with shifting some of these bools to one place to reduce the padding for alignment.
</blockquote></details>

Good point. I'll play around with this some more.
___
*[internal/manifest/version_edit.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1535#-MwgVXJuDdLMlqpHACEX:-MwgaQmQ4K3b0l_rlmxh:b5l8v62) ([raw file](https://github.com/cockroachdb/pebble/blob/b1b77bc4b742a3975866bfd80b351bee1b38d652/internal/manifest/version_edit.go#L274)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't understand the bitset comment. Is that to avoid the key comparisons for each file when opening the DB?
</blockquote></details>

It's premature musing on my part (I was going to tackle this on a separate PR that follows this).

We now need to encode whether there are range keys in the table - I was thinking of something like the following scheme:

- a new file tag (`tagNewFile5`?) that simply extends `tagNewFile4` for range keys
- keeping the existing smallest / largest fields for point keys
- some way of indicating whether there are range keys present in the table (a bool?)
- if there are range keys, lay down the smallest / largest range key fields

At this point we technically have enough information to hydrate the overall bounds. However, this calculation relies on the comparison function for the table, for which we only have the name, and not the actual implementation. The `Compare` struct is available higher up, but we can't compute in this `Decode` method.

Another approach I was thinking of - we don't actually need to perform the comparison if instead we directly encode which key type corresponds to the smallest / largest bounds. Then at hydration time, we can simply set `Smallest` and `Largest` directly to wither the smallest / largest point or range key.

The bitset comment was me thinking that a `bool` (to specify the presence of range keys), plus another two fields for indicating how `Smallest` and `Largest` are set would be wasteful, and there's probably a way of packing all of that information into a single byte.

As I write this, I also wonder if we could have something like:
- if no range keys, use `tagNewFile4`, and existing logic just hydrates `Smallest` / `Largest` with the point keys (as there are no range keys to even consider), as we're doing here
- else, there are range keys, so use `tagNewFile5` as the marker:
  - write existing fields
  - encode the smallest range key
  - encode the largest range key
  - encode whether to use the point or range key for the smaller and larger fields (two bits, but we use a byte)
  - write existing custom tags from `tagNewFile4`

Did you have thoughts on an encoding scheme?


<!-- Sent from Reviewable.io -->

2022-02-24 19:02 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1535)* status: 1 of 22 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/manifest/version.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1535#-MwddnFZEjfydPouTmIh:-Mwh1JqsAkDb_qo67wQu:b-2r11ej) ([raw file](https://github.com/cockroachdb/pebble/blob/64785d0250712cde42c5f918b7856038c464fe1a/internal/manifest/version.go#L106)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Good point. I'll play around with this some more.
</blockquote></details>

Before this patch: 352 bytes
Currently: 376 bytes 

The alignment is 8 bytes, so if we pack all the bools at the end, we can get this down to 336. Pushed a fix.


<!-- Sent from Reviewable.io -->

2022-02-24 21:06 UTC, nicktrav reviewed
The inlining appears to work as expected - though I had to check the objdumps (for whatever reason `-gcflags=-m5` didn't show it, perhaps because it's so trivial?).

Changing all the calls sites to use methods and unexporting the fields is something we can look at. I'm hesitant to do it here, given how large this change is already. I can follow up with a mechanical PR if / when this lands.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1535#-:-MwhXkFa5MzPTOggOofY:b-4uuaj9)* status: 1 of 22 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-02-25 22:11 UTC, jbowens approved these changes
Nice <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1535#-:-MwmvzUi9dZKz8OVtI67:bzhmkty)* status: 3 of 22 files reviewed, 3 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[internal/manifest/version.go, line 184 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1535#-MwmuP2U3u7qNF0PilO7:-MwmuP2V5jOIlQgTnKLj:bn93d0c) ([raw file](https://github.com/cockroachdb/pebble/blob/773e11ac5f1aa1d04eeec40b17bf1f895f2dea4f/internal/manifest/version.go#L184)):*
> ```Go
> // NB: calling this method should be preferred to manually setting the bounds by
> // manipulating the fields directly, to maintain certain invariants.
> func (m *FileMetadata) MaybeExtendRangeKeyBounds(cmp Compare, smallest, largest InternalKey) {
> ```

Possibly a controversial take: I think it'd be a little more ergonomic in tests if we return the mutated receiver, like we do in [`Options.EnsureDefault()`](https://pkg.go.dev/github.com/cockroachdb/pebble#Options.EnsureDefaults), allowing chaining like:

```
m := (&fileMetadata{FileNum: 000001}).
    MaybeExtendPointKeyBounds(cmp, pointSmall, pointLarge).
    MaybeExtendRangeKeyBounds(cmp, rangeSmall, rangeLarge)
```

It's a bit unusual and potentially confusing to return the receiver, so  ¯\\_(ツ)\_/¯


<!-- Sent from Reviewable.io -->

2022-02-26 00:40 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1535)* status: 1 of 22 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/manifest/version.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1535#-MwddUuT-tdvsAILWkHd:-MwnQ2Av3Gn6s7hPNqU2:b-896fja) ([raw file](https://github.com/cockroachdb/pebble/blob/64785d0250712cde42c5f918b7856038c464fe1a/internal/manifest/version.go#L155)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am bad at naming, but I'd be satisfied with simply `ExtendPointKeyBounds`.
</blockquote></details>

Done!
___
*[internal/manifest/version.go, line 184 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1535#-MwmuP2U3u7qNF0PilO7:-MwnIuTAExijQ0fqzgAQ:b-hsfjp) ([raw file](https://github.com/cockroachdb/pebble/blob/773e11ac5f1aa1d04eeec40b17bf1f895f2dea4f/internal/manifest/version.go#L184)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Possibly a controversial take: I think it'd be a little more ergonomic in tests if we return the mutated receiver, like we do in [`Options.EnsureDefault()`](https://pkg.go.dev/github.com/cockroachdb/pebble#Options.EnsureDefaults), allowing chaining like:

```
m := (&fileMetadata{FileNum: 000001}).
    MaybeExtendPointKeyBounds(cmp, pointSmall, pointLarge).
    MaybeExtendRangeKeyBounds(cmp, rangeSmall, rangeLarge)
```

It's a bit unusual and potentially confusing to return the receiver, so  ¯\\_(ツ)\_/¯
</blockquote></details>

Fair point! Updated.


<!-- Sent from Reviewable.io -->

2022-02-26 00:40 UTC, nicktrav commented
TFTRs!

2022-02-26 00:40 UTC, merged

2022-02-26 01:02 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1535)* status: 1 of 22 files reviewed, 2 unresolved discussions

___
*[internal/manifest/version_edit.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1535#-MwgVXJuDdLMlqpHACEX:-MwnXXUT2KA4f8yuvfbH:bps1z3i) ([raw file](https://github.com/cockroachdb/pebble/blob/b1b77bc4b742a3975866bfd80b351bee1b38d652/internal/manifest/version_edit.go#L274)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

It's premature musing on my part (I was going to tackle this on a separate PR that follows this).

We now need to encode whether there are range keys in the table - I was thinking of something like the following scheme:

- a new file tag (`tagNewFile5`?) that simply extends `tagNewFile4` for range keys
- keeping the existing smallest / largest fields for point keys
- some way of indicating whether there are range keys present in the table (a bool?)
- if there are range keys, lay down the smallest / largest range key fields

At this point we technically have enough information to hydrate the overall bounds. However, this calculation relies on the comparison function for the table, for which we only have the name, and not the actual implementation. The `Compare` struct is available higher up, but we can't compute in this `Decode` method.

Another approach I was thinking of - we don't actually need to perform the comparison if instead we directly encode which key type corresponds to the smallest / largest bounds. Then at hydration time, we can simply set `Smallest` and `Largest` directly to wither the smallest / largest point or range key.

The bitset comment was me thinking that a `bool` (to specify the presence of range keys), plus another two fields for indicating how `Smallest` and `Largest` are set would be wasteful, and there's probably a way of packing all of that information into a single byte.

As I write this, I also wonder if we could have something like:
- if no range keys, use `tagNewFile4`, and existing logic just hydrates `Smallest` / `Largest` with the point keys (as there are no range keys to even consider), as we're doing here
- else, there are range keys, so use `tagNewFile5` as the marker:
  - write existing fields
  - encode the smallest range key
  - encode the largest range key
  - encode whether to use the point or range key for the smaller and larger fields (two bits, but we use a byte)
  - write existing custom tags from `tagNewFile4`

Did you have thoughts on an encoding scheme?
</blockquote></details>

the latter scheme to pack the decisions into a byte sounds good. We will also need to handle the case of range keys and no point keys.


<!-- Sent from Reviewable.io -->