db: add migration to rewrite atomic compaction units
cockroachdb/pebble pull request #1537
Opened 2022-02-25 21:17 UTC by jbowens

Add a new format major version FormatSplitUserKeys that guarantees all sstables
within the table form their own atomic compaction unit. Previous versions of
Pebble (before #1470) and RocksDB allowed keys with identical user keys to be
split across multiple tables within a level. This produced a set of files known
as an 'atomic compaction unit' that must be compacted together to preserve the
LSM invariant.

This change adds a new format major version that can't be committed until all
such atomic compaction units have been recompacted to ensure that within a
level, all versions of the same user key are within the same sstable. When
ratcheting the format major version to  FormatSplitUserKeys, Pebble will look
for atomic compaction units and schedule compactions, one-at-a-time, to rewrite
these multi-file atomic compaction units into multiple single-file atomic
compaction units.

This migration will allow future versions of Pebble to remove code necessary to
handle these atomic compaction units.

Close #1495.

2022-02-25 21:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1537)
<!-- Reviewable:end -->

2022-02-25 21:26 UTC, jbowens reviewed
@sumeerbhola — Thoughts on sneaking something like this in during stability period? If we add a migration like this to 22.1, then we don't have to worry about rangedels with bounds narrower than user keys when we're refactoring the `FragmentIterator`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537#-:-Mwmk-0j4v5Wf1frbPg8:b-p7ejjo)* status: 0 of 19 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-25 21:38 UTC, nicktrav reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537)* status: 0 of 19 files reviewed, all discussions resolved (waiting on @nicktrav)

___
*[format_major_version.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MwmnHCu8JidTrukmXD7:-MwmnHCv-6BmQOO8VYYN:b224svz) ([raw file](https://github.com/cockroachdb/pebble/blob/859312a47523897a4922fcffabd41e28d45b8da4/format_major_version.go#L78)):*
> ```Go
> 	// level. Ratcheting to the FormatSplitUserKeys version will fail if that
> 	// guarantee is not met.
> 	FormatSplitUserKeys
> ```

Nice. This was going to be my initial drive-by comment - the ordering of the migrations, given we don't want Pebblev2 in Cockroach for 22.1. :thumbsup: :thumbsup:

Now it makes me wonder - if block properties aren't yet released, could this jump back another version and use Rocksdbv2, given the table format didn't really change for this feature. It's most likely a no-op anyway, as 22.1 will have block properties, so Pebble will need to ratchet to at least Pebblev1.


<!-- Sent from Reviewable.io -->

2022-02-28 16:25 UTC, jbowens reviewed
I'm making the assumption here that there are few of these multi-file atomic compaction units, and so it's okay to synchronously perform the migration during the upgrade. Alternatively, we could schedule these compactions in the background when there's no other compactions to be picked, and only add the format major version gating in 22.2.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537#-:-Mwn4tTJCLpdkNF7mBoP:bebwjsi)* status: 0 of 19 files reviewed, all discussions resolved (waiting on @itsbilal, @nicktrav, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-02-28 19:59 UTC, sumeerbhola reviewed
> Alternatively, we could schedule these compactions in the background when there's no other compactions to be picked, and only add the format major version gating in 22.2.

Strong +1 to this. Plus we could export a metric showing how many remaining files, so that in 22.2 if the code blocks on doing these compactions, we can look at the metric on that node prior to the upgrade and understand why. Or the operator could upgrade to 22.2 unless it drops to 0 (imagining someone doing a 21.2 => 22.1 => 22.2 in rapid succession).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537#-:-Mx0tamlARxZbeUTe_XG:burixd8)* status: 0 of 19 files reviewed, all discussions resolved (waiting on @itsbilal and @nicktrav)



<!-- Sent from Reviewable.io -->

2022-02-28 20:02 UTC, sumeerbhola reviewed
So I am happy with such background behavior being added during the 22.1 stability.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537#-:-Mx0ucA15wRdP9VdTzAy:bbinyni)* status: 0 of 19 files reviewed, all discussions resolved (waiting on @itsbilal and @nicktrav)



<!-- Sent from Reviewable.io -->

2022-02-28 22:32 UTC, jbowens reviewed
Updated to pursue these compactions in the background, maintain a count of these files exposed via `Metrics()`, and avoid scanning for these files if there are known to be none. I kept the synchronous migration code, because we can just not ratchet the format major version in 22.1 and add that in 22.2.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537#-:-Mx1SFN4B7xd2DHlcBtA:be1s0m9)* status: 0 of 22 files reviewed, all discussions resolved (waiting on @itsbilal and @nicktrav)



<!-- Sent from Reviewable.io -->

2022-02-28 22:34 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @nicktrav)

___
*[compaction_picker.go, line 47 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx1Smrd-wX00_CcCXNB:-Mx1Smrd-wX00_CcCXNC:b-ifbz0p) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/compaction_picker.go#L47)):*
> ```Go
> 	pickManual(env compactionEnv, manual *manualCompaction) (c *pickedCompaction, retryLater bool)
> 	pickElisionOnlyCompaction(env compactionEnv) (pc *pickedCompaction)
> 	pickRewriteCompaction(env compactionEnv, level int, file manifest.LevelFile) (pc *pickedCompaction)
> ```

We could use these 'rewrite' compactions to implement cockroachdb/cockroach#74804 for sstables.


<!-- Sent from Reviewable.io -->

2022-03-01 01:50 UTC, nicktrav approved these changes
Just nits. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 13 of 19 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537#-:-Mx2A-PS1zfn-iczq-kn:b78sqjr)* status: all files reviewed, 8 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[compaction_picker.go, line 1620 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx1ywe234Tgdk0reVqS:-Mx1ywe234Tgdk0reVqT:bibik9i) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/compaction_picker.go#L1620)):*
> ```Go
> // of such files (may double-count an atomic compaction unit) and it returns the
> // level and LevelFile for one such file.
> func findSplitUserKey(opts *Options, vers *version) (count, level int, file manifest.LevelFile, ok bool) {
> ```

Perhaps this is me needlessly seeking out a (premature) optimization - this function is called repeatedly and ends up re-scanning the levels in the same order looking for compaction units.

That said, the only alternatives I could come up while writing this comment seemed complicated (e.g. I was thinking of some kind of lazy iterator over atomic compaction units, but would hold onto a readstate, which is blergh).

Maybe it's a non-issue in practice as searching for these units happens last in order of compaction types, and the metadata is all in-mem.
___
*[compaction_picker.go, line 1622 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx1xKpo3G2fLML7CkhT:-Mx1xKpp97v39_Tk_0L6:bxmahax) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/compaction_picker.go#L1622)):*
> ```Go
> func findSplitUserKey(opts *Options, vers *version) (count, level int, file manifest.LevelFile, ok bool) {
> 	equal := opts.equal()
> 	for l := numLevels - 1; l > 0; l-- {
> ```

Is there a specific reason for starting at L6 and working our way to L1, versus the other way around?
___
*[format_major_version.go, line 181 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx28mTU2n-o1RgT_wgb:-Mx28mTU2n-o1RgT_wgc:b-rruzj2) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/format_major_version.go#L181)):*
> ```Go
> 	FormatSplitUserKeys: func(d *DB) error {
> 		// Before finalizing the format major version, rewrite any sstables that
> 		// form multi-file atomic compaction units.
> ```

nit: maybe mention that we're guaranteed to hold the `d.mu` here, and thus safe to call the method that relies on the lock being held?
___
*[open.go, line 459 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx245QBBvKMeBkI-n2C:-Mx245QC75avgoeMH6Ql:b-sv15x8) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/open.go#L459)):*
> ```Go
> 	// might be files that do not form their own atomic compaction unit.
> 	// Initialize the count of such files.
> 	// TODO(jackson): Remove this after CockroachDB 22.2.
> ```

Nice. Accompanying ticket / issue, perhaps?

Thinking about it some more, it seems like the migration code has to live on in perpetuity, given that we allow a Pebble DB to be opened at any old version and we'll chug though all the migrations in order - maybe that's fine, but just wanted to mention it, as maybe we have a plan for such thing.
___
*[testdata/ingest_load, line 92 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx25USC9OChR2ecJvdU:-Mx25USC9OChR2ecJvdV:b-lghtb0) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/testdata/ingest_load#L92)):*
> ```
> 
> # Loading tables at an unsupported table format results in an error.
> # Write a table at version 7 (Pebble,v2) into a DB at version 6 (Pebble,v1).
> ```

nit: did this need to change? It just needs to be any two version that straddles a table format change. Same comment in `testdata/rangekeys`.
___
*[testdata/split_user_key_migration, line 1 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx26OTaEhQ419epWpuM:-Mx26OTaEhQ419epWpuN:bds3i2m) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/testdata/split_user_key_migration#L1)):*
> ```
> define
> ```

Nice test.


<!-- Sent from Reviewable.io -->

2022-03-03 23:18 UTC, jbowens reviewed
Reworked this to reuse the previously unused `FileMetdata.MarkedForCompaction` field that's persisted in the manifest. There's now two format major versions. The first guarantees that all non-atomic compaction units are marked for compaction durably. The second guarantees that there are no files marked for compaction.

To avoid too much during compaction picking, a count of the files marked for compaction is included on the `Version` and updated when applying `VersionEdit`s. The compaction picker can avoid ever looking for rewrite compactions if this count is zero. Additionally, even if the count is positive, the compaction picker uses a manifest b-tree annotation to find the file to compact, avoiding linear scans across the LSM every time it picks a rewrite compaction. This optimization probably doesn't matter much here, since we expect these split user keys to be very rare, but it would likely matter if we use these rewrite compactions for cockroachdb/cockroach#74804 .

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537#-:-MxH2U6T4uYORlsNtfcq:b-ovscsq)* status: 3 of 28 files reviewed, 7 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[compaction_picker.go, line 1075 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx5OUt-3oP0BWInMQ9X:-Mx5uWzN6dOT67ZVapId:b-4oc7fb) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/compaction_picker.go#L1075)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how expensive is it to do this repeatedly. Should we mark the FileMetadata with a bool so do we don't repeat?
</blockquote></details>

It's not cheap. Even if we mark a bool on the `FileMetadata`, the scan is O(# sstables), which is never great. One thought is that we could reuse the `f.MarkedForCompaction` bool (which does get persisted to the manifest) which ensures that we only need to do this traversal once, but requires some extra coordination.
___
*[compaction_picker.go, line 1081 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx5OoTZ32UFz6Iq6cCR:-MxH1RyJ3s1tckLf3aro:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/compaction_picker.go#L1081)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is the nonatomicFileCount stale once a compaction finishes, until there are few enough compaction candidates and we fall through to here?
Can we cheaply strengthen the staleness bound e.g. by tracking the non-atomic state in FileMetadata and adjusting the count when applying the VersionEdit?
</blockquote></details>

Done.
___
*[compaction_picker.go, line 1194 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx5OCobEhDEcp4BNOeY:-Mx5uxs-0WO76iWqmO-H:bez2r6z) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/compaction_picker.go#L1194)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

are we ensuring somewhere that level is not 0?
</blockquote></details>

`findSplitUserKey` only looks at levels 1...6.
___
*[compaction_picker.go, line 1620 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx1ywe234Tgdk0reVqS:-MxH1kwyBpEtirTpSn5F:baocr2p) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/compaction_picker.go#L1620)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Perhaps this is me needlessly seeking out a (premature) optimization - this function is called repeatedly and ends up re-scanning the levels in the same order looking for compaction units.

That said, the only alternatives I could come up while writing this comment seemed complicated (e.g. I was thinking of some kind of lazy iterator over atomic compaction units, but would hold onto a readstate, which is blergh).

Maybe it's a non-issue in practice as searching for these units happens last in order of compaction types, and the metadata is all in-mem.
</blockquote></details>

Reworked to avoid duplicate scans by a) persisting which files should be compacted in the existing `MarkedForCompaction` field that's persisted in the manifest and b) using a b-tree annotation to ensure that don't need to consistently perform linear scans of a level's file metadata looking for files marked for compaction.
___
*[compaction_picker.go, line 1622 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx1xKpo3G2fLML7CkhT:-MxH2EUV7nHWSrtOjJla:b-84590r) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/compaction_picker.go#L1622)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Is there a specific reason for starting at L6 and working our way to L1, versus the other way around?
</blockquote></details>

Just that files in L6 are more likely to be older and so more likely to have non-atomic compaction units.
___
*[format_major_version.go, line 181 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx28mTU2n-o1RgT_wgb:-MxH0yT237f9HA-xx_LG:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/format_major_version.go#L181)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: maybe mention that we're guaranteed to hold the `d.mu` here, and thus safe to call the method that relies on the lock being held?
</blockquote></details>

Done.
___
*[open.go, line 459 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mx245QBBvKMeBkI-n2C:-MxH1-gvE42hJyk4hqjG:bjxwm96) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/open.go#L459)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Nice. Accompanying ticket / issue, perhaps?

Thinking about it some more, it seems like the migration code has to live on in perpetuity, given that we allow a Pebble DB to be opened at any old version and we'll chug though all the migrations in order - maybe that's fine, but just wanted to mention it, as maybe we have a plan for such thing.
</blockquote></details>

I was imagining at some point we'd increase the minimum format major version supported by the master branch of Pebble. So non-CockroachDB users with existing databases would need to ratchet the format major version using a non-master SHA before upgrading to master.


<!-- Sent from Reviewable.io -->

2022-03-03 23:30 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537)* status: 3 of 28 files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[compaction_picker.go, line 1248 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxH6YxyBXiEK5VwLudE:-MxH6Yxz3y1AUqJ1NFcE:b-xvy0nh) ([raw file](https://github.com/cockroachdb/pebble/blob/59caac4c2d221f624112d1baa909dd2e12358e26/compaction_picker.go#L1248)):*
> ```Go
> 			continue
> 		}
> 		lf := p.vers.Levels[l].Find(p.opts.Comparer.Compare, candidate)
> ```

TODO: This needs to be fixed. `.Find` only works for L1...6 not L0. I'll fix this and add a test for a L0 rewrite compaction.


<!-- Sent from Reviewable.io -->

2022-03-07 23:13 UTC, nicktrav reviewed
This looks great - thanks for the extra effort to use make use of the annotations and the persistence.

I did a pass of the more recent changes and it looks good. A few small comments I'll wait to hear back on. But otherwise LGTM (still).

> Reviewed 20 of 25 files at r6, 5 of 7 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537#-:-MxaccCH8Y9exRRVqxbL:b-73ofay)* status: all files reviewed, 16 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[-- commits, line 13 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxaLnCh8Bk_WZqX9t7Q):*
nit: ... every file that is a member of a ... 
___
*[-- commits, line 15 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxaM36WDk3VGXV361hY):*
> but is repurposed here

No objection, just curious if we're closing the door here to using that field in the future if we're repurposing it here for this specific type of migration that happens once.
___
*[compaction.go, line 1451 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxaMsfz6pZ_u5ZIIf68:-MxaMsfz6pZ_u5ZIIf69:b-qdfcwe) ([raw file](https://github.com/cockroachdb/pebble/blob/e4bbcf2b684e7705b98492bb7bdeeed3d487948a/compaction.go#L1451)):*
> ```Go
> 	d.mu.versions.incrementCompactionBytes(-c.bytesWritten)
> 
> 	info.TotalDuration = d.timeNow().Sub(startTime)
> ```

Did this removal creep in from a rebase?
___
*[compaction_picker.go, line 1183 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxaPTJh2YwNEA9OrCai:-MxaPTJh2YwNEA9OrCaj:bif1wsh) ([raw file](https://github.com/cockroachdb/pebble/blob/268f7c3441f35c9cb15e1ed60763dba248cce645/compaction_picker.go#L1183)):*
> ```Go
> 		return accum
> 	}
> 	// If we haven't accumulated an eligible file yet, or f's LargestSeqNum is
> ```

nit: the first part of this comment (before the comma) pertains to this first check, and the second pertains to the next set of type-conversions and checks. Was confused reading it. Suggest splitting the comment?
___
*[format_major_version.go, line 75 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxaRXNH7x-scMKIxehc:-MxaRXNH7x-scMKIxehd:b-d7m9zs) ([raw file](https://github.com/cockroachdb/pebble/blob/268f7c3441f35c9cb15e1ed60763dba248cce645/format_major_version.go#L75)):*
> ```Go
> 	FormatBlockPropertyCollector
> 	// FormatSplitUserKeysMarked is a format major version that guarantees that
> 	// all files the share user keys with neighbors are marked for compaction in
> ```

nit: ... all files that share ...
___
*[format_major_version.go, line 76 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxaRbow8rHRCdzYLZNP:-MxaRbow8rHRCdzYLZNQ:b-kj7h5l) ([raw file](https://github.com/cockroachdb/pebble/blob/268f7c3441f35c9cb15e1ed60763dba248cce645/format_major_version.go#L76)):*
> ```Go
> 	// FormatSplitUserKeysMarked is a format major version that guarantees that
> 	// all files the share user keys with neighbors are marked for compaction in
> 	// the manifest. Ratcheting to FormatSplitUserKeysMarked will block until
> ```

When we talk about "blocking" here (and below), I take it we're talking about just blocking ratcheting, and not blocking progress elsewhere in the DB (i.e. holding locks). Worth clarifying?
___
*[format_major_version.go, line 379 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxaVQAjEilvGQeqM4LY:-MxaVQAjEilvGQeqM4LZ:b-7op9qq) ([raw file](https://github.com/cockroachdb/pebble/blob/268f7c3441f35c9cb15e1ed60763dba248cce645/format_major_version.go#L379)):*
> ```Go
> 	// database lock while we're scanning the file metadata.
> 	//
> 	// If we find a file to mark, we'll re-acquire the mutex before marking it,
> ```

Given that we're dropping and re-acquiring the lock, is there any issue with a race where the version passed into this function is different to the version of the DB that exists when the we log the version edit in the calling function (above)?

I'm thinking of a situation where version `v1` is passed in, we find a set of files to mark for compaction / annotate on one or more levels of `v1`. However, above us, the version moved forward to `v2` (`>v1`), so we're annotating a stale version. When we exit this function, we return `true` to say that we marked some files on `v1`, triggering a version edit to be logged, but this will persist `v2`. Is it possible that we'd lose the annotations in that case?

I'm probably missing some invariant that guarantees that this is safe. Can we bolster the comment with this proof in that case?
___
*[internal/manifest/btree.go, line 593 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxaXyfkEK7hI8GqD6Qf:-MxaXyfkEK7hI8GqD6Qg:b-dmrcr2) ([raw file](https://github.com/cockroachdb/pebble/blob/268f7c3441f35c9cb15e1ed60763dba248cce645/internal/manifest/btree.go#L593)):*
> ```Go
> 	if !n.leaf {
> 		for i := int16(0); i <= n.count; i++ {
> 			n.children[i].invalidateAnnotation(a)
> ```

I take it the recursion here is safe to perform - i.e. bounded depth, etc. Or can Go optimize this as a tail call (I couldn't find a good answer in the quick googling I just did).
___
*[internal/manifest/level_metadata.go, line 74 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxaYaVZ-A3ztlz6JXAY:-MxaYaVZ-A3ztlz6JXAZ:b-i1lh90) ([raw file](https://github.com/cockroachdb/pebble/blob/9d0c3914df4b4d58b3871edac3e4541e53662f1a/internal/manifest/level_metadata.go#L74)):*
> ```Go
> // key-sorted (eg, non-L0).
> func (lm *LevelMetadata) Find(cmp base.Compare, m *FileMetadata) *LevelFile {
> 	// TODO(jackson): Add an assertion that lm is key-sorted.
> ```

Did we change something elsewhere makes this TODO about `lm` being key-sortable obsolete?
___
*[internal/manifest/level_metadata.go, line 107 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxaZHSWC9i_L5piJNyj:-MxaZHSWC9i_L5piJNyk:b-wgvzkn) ([raw file](https://github.com/cockroachdb/pebble/blob/268f7c3441f35c9cb15e1ed60763dba248cce645/internal/manifest/level_metadata.go#L107)):*
> ```Go
> 
> // InvalidateAnnotation clears any cached annotations defined by Annotator. The
> // Annotator is used as the key for pre-calculated values, so equal Annotators
> ```

Is "equal" here taken to mean equality of the underlying dynamic type (i.e. same instance)?
___
*[testdata/split_user_key_migration, line 56 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxabBNRAPqmO6aV6mwe:-MxabBNRAPqmO6aV6mwf:b7lr3yj) ([raw file](https://github.com/cockroachdb/pebble/blob/268f7c3441f35c9cb15e1ed60763dba248cce645/testdata/split_user_key_migration#L56)):*
> ```
> 006
> 
> # Ensure the files previously marked for compaction are still marked for
> ```

Worth doing something like a DB close / open here too to prove that we don't lose the marked files? Not sure it really tests persistence, just that it's recomputed.


<!-- Sent from Reviewable.io -->

2022-03-08 14:36 UTC, sumeerbhola requested changes
> Reviewed 9 of 25 files at r6, 1 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537)* status: all files reviewed, 21 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[-- commits, line 15 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxaM36WDk3VGXV361hY):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

> but is repurposed here

No objection, just curious if we're closing the door here to using that field in the future if we're repurposing it here for this specific type of migration that happens once.
</blockquote></details>

I suppose we could reuse it post-FormatMarkCompacted. 
___
*[compaction_picker.go, line 1185 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-Mxdpr28CJkkUR6LP8QR:-Mxdpr2907z0F2-KjtlA:b-qn9gkk) ([raw file](https://github.com/cockroachdb/pebble/blob/268f7c3441f35c9cb15e1ed60763dba248cce645/compaction_picker.go#L1185)):*
> ```Go
> 	// If we haven't accumulated an eligible file yet, or f's LargestSeqNum is
> 	// less than the accumulated file's, use f.
> 	if accum == nil {
> ```

nit: can we factor out
```
// REQUIRES: f is non-nil, and f.MarkedForCompaction=true.
func mergeHelper(f *FileMetadata, dst interface{}) (interface{}, bool)
```
and then do
```
func (a markedForCompactionAnnotator) Accumulate(
	f *fileMetadata, dst interface{},
) (interface{}, bool) {
	if !f.MarkedForCompaction {
		// Not marked for compaction; return dst.
		return dst, true
	}
        return mergeHelper(f, dst)
}

func (a markedForCompactionAnnotator) Merge(v interface{}, accum interface{}) interface{} {
	if v == nil {
		return accum
	}
        accum, _ = mergeHelper(v.(*fileMetadata), accum)
        return accum
}
```
___
*[compaction_picker.go, line 1253 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxdrO7H3_HjxgBKQN66:-MxdrO7H3_HjxgBKQN67:b-52gc05) ([raw file](https://github.com/cockroachdb/pebble/blob/268f7c3441f35c9cb15e1ed60763dba248cce645/compaction_picker.go#L1253)):*
> ```Go
> 		}
> 
> 		inputs := lf.Slice()
> ```

How about a comment like the following:
// L0 files generated by a flush have never been split such that adjacent files can contain the same user key. So we do not need to rewrite an atomic compaction unit for L0. Note that there is nothing preventing two different flushes from producing files that are non-overlapping from an InternalKey perspective, but span the same user key. However, such files cannot be in the same L0 sublevel, since each sublevel requires non-overlapping user keys (unlike other levels).
___
*[format_major_version.go, line 190 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxdtmljDVdkTMeP8ZxN:-MxdtmljDVdkTMeP8ZxO:b5zvg2d) ([raw file](https://github.com/cockroachdb/pebble/blob/268f7c3441f35c9cb15e1ed60763dba248cce645/format_major_version.go#L190)):*
> ```Go
> 	FormatSplitUserKeysMarked: func(d *DB) error {
> 		// Mark any unmarked files with split-user keys. Note all format major
> 		// versions migrations are invoked with DB.mu locked.
> ```

Should we move the formatVers out of DB.mu and give it its own mutex? I am worried about hiccups in normal writes if we hold this lock for too long.
With that change we could have the implementation acquire and release DB.mu periodically, say after scanning each level to mark, and we would not be risking that a second migration could start concurrently.
___
*[format_major_version.go, line 320 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxdvcMACdWuQr2FwHgk:-MxdvcMACdWuQr2FwHgl:b-30l7sy) ([raw file](https://github.com/cockroachdb/pebble/blob/268f7c3441f35c9cb15e1ed60763dba248cce645/format_major_version.go#L320)):*
> ```Go
> 		d.maybeScheduleCompactionPicker(func(picker compactionPicker, env compactionEnv) *pickedCompaction {
> 			return picker.pickRewriteCompaction(env)
> 		})
> ```

How will a compaction actually run while this method holds onto DB.mu?
___
*[format_major_version.go, line 424 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxdweD59qExzLGt73HV:-MxdweD59qExzLGt73HW:bitb7ta) ([raw file](https://github.com/cockroachdb/pebble/blob/268f7c3441f35c9cb15e1ed60763dba248cce645/format_major_version.go#L424)):*
> ```Go
> 		// If we marked any files for compaction, clear the compaction-picking
> 		// annotation that caches files marked-for-compaction, as it's now
> 		// out-of-date.
> ```

I don't understand what is out of date? Could you elaborate?


<!-- Sent from Reviewable.io -->

2022-03-09 17:23 UTC, jbowens reviewed
@sumeerbhola any more comments?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537#-:-MxjhEZn1fay70ySb9h0:bv1buns)* status: all files reviewed, 7 unresolved discussions (waiting on @itsbilal and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-03-09 21:12 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> (I didn't look at the tests since @nicktrav was doing a careful review)

> Reviewed 1 of 25 files at r6, 2 of 3 files at r9, 1 of 11 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537#-:-MxkWQ1PC_g-mnzqSdUv:b-x4uu3k)* status: all files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[db.go, line 326 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxkVM51Av5dmElSGk78:-MxkVM522LjRwyjl8G87:b-sl25v5) ([raw file](https://github.com/cockroachdb/pebble/blob/7dc3d8df773f8f0e81dc060cd66f75170f5b2cea/db.go#L326)):*
> ```Go
> 			// currently in the process of ratcheting the format major version
> 			// to vers + 1. As a part of ratcheting the format major version,
> 			// migrations may may drop and re-acquire the mutex.
> ```

may drop


<!-- Sent from Reviewable.io -->

2022-03-10 00:36 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537#-:-Mxl9eLn-zyKi9Q25_Fh:bz5mair)* status: 28 of 30 files reviewed, 8 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[db.go, line 326 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxkVM51Av5dmElSGk78:-Mxl9TbA0PnY6KU1ZPW4:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/7dc3d8df773f8f0e81dc060cd66f75170f5b2cea/db.go#L326)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

may drop
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-10 00:36 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1537#-:-Mxl9eLn-zyKi9Q25_Fh:bz5mair)* status: 28 of 30 files reviewed, 8 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[db.go, line 326 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1537#-MxkVM51Av5dmElSGk78:-Mxl9TbA0PnY6KU1ZPW4:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/7dc3d8df773f8f0e81dc060cd66f75170f5b2cea/db.go#L326)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

may drop
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-10 01:09 UTC, merged