*: refactor keyspan.Span to represent a set of keys
cockroachdb/pebble pull request #1587
Opened 2022-03-18 17:28 UTC by jbowens

This commit performs an (unfortunately massive) refactor to how range deletions
and range keys are represented. Previously, a keyspan.Span represented a single
internal key.

This commit refactors keyspan.Span to represent a user key span [Start, End)
and a set of Keys that are defined over the span. A new keyspan.Key type is
introduced to represent each individual key defined over the span.
Additionally, the keyspan.FragmentIterator interface is disentangled from the
base.InternalIterator interface, allowing it return individual keyspan.Spans.

This refactoring requires leaf iterators over keyspan.Spans to 'gather'
overlapping fragments (which necessarily must have identical bounds) to form a
single keyspan.Span encapsulating the entire state over the user key bounds.
Consolidated spans reduces key comparisons during iteration: In many cases
(batches, memtables, compactions) range deletions are passed through a
fragmenter before iteration, and the fragmenter necessarily knows which
fragments have identical bounds.

Subsequent work will adapt the range key interleaving iterator to work with
arbitrary key spans, and eventually use it in compactions to interleave range
deletions and range keys among points.

2022-03-18 17:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1587)
<!-- Reviewable:end -->

2022-03-18 18:41 UTC, jbowens reviewed
Sorry for the enormity of this pull request. I tried to trim it down, but `keyspan.Span`s and `FragmentIterator`s are everywhere.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1587#-:-MyTHDUN1scB0XUpJaCD:b-mirjcw)* status: 0 of 80 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-03-21 20:17 UTC, jbowens reviewed
For review, I recommend starting in `internal/keyspan` (especially `span.go` and `iter.go`), then proceeding to `internal/rangekey` and `internal/rangedel`, and then to `sstable/block.go`.

All the places that accumulate `[]Key`s deserve some scrutiny, because they're a new opportunity for memory reuse to go awry.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1587#-:-Myi4kFH6q9t3t19e-fb:bwwek6g)* status: 0 of 81 files reviewed, all discussions resolved (waiting on @itsbilal, @nicktrav, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-03-22 18:59 UTC, sumeerbhola requested changes
flushing some comments for the keyspan package (not yet done with keyspan).

> Reviewed 6 of 81 files at r1, 2 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1587#-:-MymzoG7BJn53ydQHUBB:bi1r6t5)* status: 8 of 81 files reviewed, 18 unresolved discussions (waiting on @itsbilal, @jbowens, and @nicktrav)

___
*[internal/keyspan/bound_iter.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymqyNF7EAIXZUOfsUW:-MymqyNF7EAIXZUOfsUX:b-p9fyqc) ([raw file](https://github.com/cockroachdb/pebble/blob/0ad186894f6dfa60b3b39371fa6df2d623f4dfd7/internal/keyspan/bound_iter.go#L25)):*
> ```Go
> 	// kinds for the table bounds.
> 	// boundKindTableStart
> 	// boundKindTableEnd
> ```

is this TODO going away because our earlier speculation that complex key stability semantics are not needed if we work with gathered spans turned out to be correct?
___
*[internal/keyspan/bound_iter.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymrW8E-XSuUi6Hc7jp:-MymrW8E-XSuUi6Hc7jq:b-dyxe3f) ([raw file](https://github.com/cockroachdb/pebble/blob/0ad186894f6dfa60b3b39371fa6df2d623f4dfd7/internal/keyspan/bound_iter.go#L39)):*
> ```Go
> 	// Start keys have user keys equal to the boundKey's key field. If the
> 	// boundKind is boundKindFragmentEnd, all fragments' End keys equal the
> 	// boundKey's key field.
> ```

I think we should preserve some part of this comment relating to boundKind and when key is the start or end key in the span.
___
*[internal/keyspan/bound_iter.go, line 185 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Mymsc7e4Mjik2aoCYOH:-Mymsc7e4Mjik2aoCYOI:b-idtf1n) ([raw file](https://github.com/cockroachdb/pebble/blob/0ad186894f6dfa60b3b39371fa6df2d623f4dfd7/internal/keyspan/bound_iter.go#L185)):*
> ```Go
> 		//               ^      \                      /     ^
> 		//             i.iter          current pos         i.iter
> 		//             before                              after
> ```

yay, more simplicity!
___
*[internal/keyspan/fragmenter.go, line 184 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymwWHcEjIsXUt2ZFeH:-MymwWHcEjIsXUt2ZFeI:b-pre6bu) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/fragmenter.go#L184)):*
> ```Go
> // span read from an sstable. The Keys slice of a Span returned during sstable
> // iteration is only valid until the next iterator operation. The stability of
> // the user keys depend on whether the block is prefix compressed.
> ```

This comment has always been somewhat odd. We should probably also say that the current code is correct because the rangedel and range key blocks are not prefix compressed..
___
*[internal/keyspan/fragmenter.go, line 416 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymvkAG3AXEQKOHTF1Z:-MymvkAG3AXEQKOHTF1_:b-kzjagk) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/fragmenter.go#L416)):*
> ```Go
> 			// with the keyspan.MergingIter which will perform just-in-time
> 			// fragmentation, and only guaranteeing the memory lifetime for the
> 			// current span.
> ```

Is this change because we previously were not doing the right thing in the fragmenter for range keys? Why was the old code correct for range tombstones?

I suppose the problem is that if consecutive Spans fed into the fragmenter come from the same level, we've lost the memory for the first span when we see the second one and try to flush it. And I am assuming what you are saying here regarding keyspan.MergingIter is that since it knows the origin of each Span and the corresponding level, it can do the fragmentation without stepping to the next fragment in the same level (since it knows they are guaranteed not to overlap). Is this correct? Hmm, what I said here isn't fixed by this copying at emit time -- it would require a copy at Add time.
___
*[internal/keyspan/fragmenter.go, line 439 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymycFT8V3Et-PI-fH_:-MymycFT8V3Et-PI-fHa:bcmrpej) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/fragmenter.go#L439)):*
> ```Go
> 		// If growing the array backing keysAlloc by double would construct a
> 		// larger array, do that.
> 		if double := 2 * cap(f.keysAlloc); double > sz {
> ```

aren't the cap and len the same for keysAlloc?
___
*[internal/keyspan/get.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Mymqa2q6p6kci817uBA:-Mymqa2q6p6kci817uBB:b-ezjy2l) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/get.go#L40)):*
> ```Go
> 	}
> 
> 	// Invariant: key >= iterSpan.Start
> ```

should this be key > iterSpan.Start?
___
*[internal/keyspan/seek.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymlX9H3tt1fqOne3Pf:-MymlX9H3tt1fqOne3Pg:badcab8) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/seek.go#L30)):*
> ```Go
> 
> 	if !iterSpan.Valid() || cmp(key, iterSpan.End) >= 0 {
> 		// The current span lies entirely before the search key. Advance the
> ```

... the search key, or the iterator is exhausted.
___
*[internal/keyspan/seek.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Mymlq6_AHy7c7QABstr:-Mymlq6_AHy7c7QABsts:b10qdsb) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/seek.go#L35)):*
> ```Go
> 		iterSpan = iter.Next()
> 	}
> 	// The iterator is positioned at a valid iterSpan which is the first
> ```

Should we return here if !iterSpan.Valid()? It seems odd to call Visible on an invalid span.
___
*[internal/keyspan/seek.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymoZxf2nRFB4ImqCY2:-MymoZxf2nRFB4ImqCY3:b4xzu9i) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/seek.go#L94)):*
> ```Go
> 		iterSpan = iter.Prev().Visible(snapshot)
> 	}
> 	return iterSpan
> ```

loving the simplification of this function!
___
*[internal/keyspan/span.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Mymhsp295hyQrYaYGlP:-Mymhsp295hyQrYaYGlQ:b7h5wnd) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/span.go#L29)):*
> ```Go
> type Span struct {
> 	// Start and End encode the user key range of all the contained
> 	// items, with an inclusive start key and exclusive end key.
> ```

Is there an invariant that both will be nil or both will be non-nil?
___
*[internal/keyspan/span.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Mym_3I-4yyKxQfBvM1Q:-Mym_3I-4yyKxQfBvM1R:b-sc59iv) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/span.go#L32)):*
> ```Go
> 	Start, End []byte
> 	// Keys holds the set of keys applied over the [Start, End) user key
> 	// range. Keys is sorted by (SeqNum, Kind) descending.
> ```

Since Key has an optional Suffix, does that mean that the RANGEKEY{SET,UNSET} has been parsed? And so the Value is only non-nil for a RANGEKEYSET and represents what the user provided? I think this could use code comments.

And is there a sort order if the (SeqNum, Kind) are equal?
___
*[internal/keyspan/span.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymhyzD2daoBU5k-jlf:-MymhyzD2daoBU5k-jlg:b-c0w065) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/span.go#L33)):*
> ```Go
> 	// Keys holds the set of keys applied over the [Start, End) user key
> 	// range. Keys is sorted by (SeqNum, Kind) descending.
> 	Keys []Key
> ```

Is there an invariant that if Start, End are non-nil, this slice will be [...]

2022-03-22 22:43 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1587)* status: 8 of 81 files reviewed, 18 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[internal/keyspan/bound_iter.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymqyNF7EAIXZUOfsUW:-MynSBHG7vwq-XuD3fY8:b-jpgbdl) ([raw file](https://github.com/cockroachdb/pebble/blob/0ad186894f6dfa60b3b39371fa6df2d623f4dfd7/internal/keyspan/bound_iter.go#L25)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this TODO going away because our earlier speculation that complex key stability semantics are not needed if we work with gathered spans turned out to be correct?
</blockquote></details>

Yeah, that's right.

I previously also intended to use these bound kinds for the optimization of returning 'empty' range keys when the iterator is positioned between two range keys, so that we don't need to load any range key blocks. For that optimization, the level iterator can now return an empty (no keys) but valid span between sstable boundaries.
___
*[internal/keyspan/bound_iter.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymrW8E-XSuUi6Hc7jp:-MynTrd6DsRs_7B66lvs:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0ad186894f6dfa60b3b39371fa6df2d623f4dfd7/internal/keyspan/bound_iter.go#L39)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we should preserve some part of this comment relating to boundKind and when key is the start or end key in the span.
</blockquote></details>

Done.



_Code quote:_
```Go
	// and kind. If the boundKind is boundKindFragmentStart, all fragments'
```
___
*[internal/keyspan/fragmenter.go, line 184 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymwWHcEjIsXUt2ZFeH:-MynUhQ8Br6Z_InAAyoN:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/fragmenter.go#L184)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This comment has always been somewhat odd. We should probably also say that the current code is correct because the rangedel and range key blocks are not prefix compressed..
</blockquote></details>

Done.
___
*[internal/keyspan/fragmenter.go, line 416 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymvkAG3AXEQKOHTF1Z:-MynXQrNEJESukjh5tu8:b-vk121h) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/fragmenter.go#L416)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this change because we previously were not doing the right thing in the fragmenter for range keys? Why was the old code correct for range tombstones?

I suppose the problem is that if consecutive Spans fed into the fragmenter come from the same level, we've lost the memory for the first span when we see the second one and try to flush it. And I am assuming what you are saying here regarding keyspan.MergingIter is that since it knows the origin of each Span and the corresponding level, it can do the fragmentation without stepping to the next fragment in the same level (since it knows they are guaranteed not to overlap). Is this correct? Hmm, what I said here isn't fixed by this copying at emit time -- it would require a copy at Add time.
</blockquote></details>

This is because previously `Emit` was called with a `[]Span` slice, and none of the `Emit` functions assumed that `[]Span` slice would be stable. All of the `Emit` implementations either accumulated the spans, appending them into their own `[]Span` slice or wrote them out to a `Writer`. Now we're moving that slice into the `Span`, forcing an allocation if the caller wants to retain it.

An alternative interface that is closer to the previous interface would be `Emit(start, end []byte, unsafeKeys []Key)`. The `[]Key` slice would not be safe to retain, just like the old `[]Span` slice was not safe to retain. This would push the allocation into the client, if they need to retain the slice.
___
*[internal/keyspan/fragmenter.go, line 439 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymycFT8V3Et-PI-fH_:-MynX5z_-0u2R7kVGuOD:b-z5g3qk) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/fragmenter.go#L439)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

aren't the cap and len the same for keysAlloc?
</blockquote></details>

oops, yeah. I had thought `cap(f.keysAlloc)` gave the unsliced array's original capacity. I dropped the `saveKeys` optimization for now.
___
*[internal/keyspan/get.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Mymqa2q6p6kci817uBA:-Mynb1jR6C-BbfkvSuyO:b1jxzi3) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/get.go#L40)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should this be key > iterSpan.Start?
</blockquote></details>

good catch, done.
___
*[internal/keyspan/seek.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymlX9H3tt1fqOne3Pf:-MynbbeB7WkTSNWWFdfB:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/seek.go#L30)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... the search key, or the iterator is exhausted.
</blockquote></details>

Done.
___
*[internal/keyspan/seek.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Mymlq6_AHy7c7QABstr:-Mynbr2fAGl83zytM1Xl:b-37209f) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/seek.go#L35)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Should we return here if !iterSpan.Valid()? It seems odd to call Visible on an invalid span.
</blockquote></details>

I suppose the same applies down below within the for loop.

I'm wondering now whether `SeekGE`/`SeekLE` really need to be responsible for visibility filtering. I believe all the usages only care about finding a span that covers a particular point key. If the span covering `key` is not visible, I believe we have no need for the returned span. The onus of performing `.Visible(<snapshot>)` could be moved to the caller once they seek to the covering span.
___
*[internal/keyspan/span.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Mymhsp295hyQrYaYGlP:-MyngjRg34rpzy7v2BMT:b-jnis0o) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/span.go#L29)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is there an invariant that both will be nil or both will be non-nil?
</blockquote></details>

Yeah, documented.
___
*[internal/keyspan/span.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Mym_3I-4yyKxQfBvM1Q:-MyniV2v6X_YPoMPfetM:b-czekhe) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/span.go#L32)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Since Key has an optional Suffix, does that mean that the RANGEKEY{SET,UNSET} has been parsed? And so the Value is only non-nil for a RANGEKEYSET and represents what the user provided? I think this could use code comments.

And is there a sort order if the (SeqNum, Kind) are equal?
</blockquote></details>

Yeah, that's right. Added some more comments.

Currently, the sort order is undefined if sequence number and kind are equal (added a comment). This might change when coalescing range keys takes a `Span` and returns a `Span`, but I'm not sure.
___
*[internal/keyspan/span.go, line 33 at r2](https://reviewa [...]

2022-03-23 13:23 UTC, sumeerbhola requested changes
done with the keyspan package

> Reviewed 1 of 81 files at r1, 6 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1587#-:-MyqwJyKD-oZGbFuCirZ:boyagqn)* status: 10 of 81 files reviewed, 20 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/keyspan/fragmenter.go, line 416 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymvkAG3AXEQKOHTF1Z:-MyqnLA-DV96b-nbqEKf:b7qdysc) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/fragmenter.go#L416)):*
Got it.

> I suppose the problem is that if consecutive Spans fed into the fragmenter come from the same level, we've lost the memory for the first span when we see the second one and try to flush it. And I am assuming what you are saying here regarding keyspan.MergingIter is that since it knows the origin of each Span and the corresponding level, it can do the fragmentation without stepping to the next fragment in the same level (since it knows they are guaranteed not to overlap). Is this correct? Hmm, what I said here isn't fixed by this copying at emit time -- it would require a copy at Add time.

Regarding this "why we don't need to copy at Add time", I think we should add to the code comment where we talk about prefix compression. We also use the fact that all the sstable rangedel iters are held open for the duration of the compaction. So what I was saying above about moving from one file in the level to the next file does not cause problems. Also, it seems to me that the following cloneKey call is unnecessary https://github.com/cockroachdb/pebble/blob/6164579cf2cbd6ef0bbe133cc3f0f1ed2bbf17b9/compaction.go#L2389
What am I missing?

Your code comment about just-in-time fragmentation is escaping me understanding -- could you elaborate?
___
*[internal/keyspan/fragmenter.go, line 75 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Myqmu0L7kN2Q_Oz7doX:-Myqmu0L7kN2Q_Oz7doY:b9usjlh) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/keyspan/fragmenter.go#L75)):*
> ```Go
> 	//
> 	// WARNING: The Keys slice of the Span is owned by the Fragmenter and may
> 	// not be retained.
> ```

but now Emit is copying the slice.
___
*[internal/keyspan/seek.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Mymlq6_AHy7c7QABstr:-MyqqItz1xpuY1MOmnXs:b-lj9z6z) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/seek.go#L35)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I suppose the same applies down below within the for loop.

I'm wondering now whether `SeekGE`/`SeekLE` really need to be responsible for visibility filtering. I believe all the usages only care about finding a span that covers a particular point key. If the span covering `key` is not visible, I believe we have no need for the returned span. The onus of performing `.Visible(<snapshot>)` could be moved to the caller once they seek to the covering span.
</blockquote></details>

I am ok with whatever you decide.
___
*[internal/keyspan/truncate.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyqsL5L6uGtC8Wf6DfH:-MyqsL5L6uGtC8Wf6DfI:b-ub8wsc) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/keyspan/truncate.go#L57)):*
> ```Go
> 		}
> 		if !s.Empty() && cmp(s.Start, s.End) < 0 {
> 			spans = append(spans, s.ShallowClone())
> ```

I hadn't thought through the allocation cost of this gathered spans approach -- we will often have a slice of Keys with 1 element. I am sure we can optimize the cost away. I worry that our normal benchmarks won't stress rangedels and rangekeys in a way that we will notice the additional cost. How about creating an issue regarding creating such a benchmark, so we can run it on the code before and after this refactor and see where to optimize (run it after this PR merges of course).


<!-- Sent from Reviewable.io -->

2022-03-23 14:42 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 
this is hugely appreciated!
the pebble code base is starting to look as if range keys were natively supported from the beginning, and not bolted on later.

> Reviewed 37 of 81 files at r1, 10 of 14 files at r2, 4 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1587#-:-MyrD1EU8YN0EUvDsHRy:bsf2gqb)* status: 61 of 81 files reviewed, 23 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[compaction.go, line 2389 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Myr7_rFDY20FAkpXjza:-Myr7_rFDY20FAkpXjzb:b919r6w) ([raw file](https://github.com/cockroachdb/pebble/blob/0ad186894f6dfa60b3b39371fa6df2d623f4dfd7/compaction.go#L2389)):*
> ```Go
> 				for j := 0; j < frags.Count(); j++ {
> 					s := frags.At(j)
> 					s.Start = iter.cloneKey(s.Start)
> ```

So you've removed this cloning of the key, that I was asking about earlier. Maybe add a code comment why a shallow clone is sufficient.
___
*[sstable/block.go, line 1038 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyrBOgUECHsORM0Gn3M:-MyrBOgUECHsORM0Gn3N:b-smg2ra) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/sstable/block.go#L1038)):*
> ```Go
> 	k, internalValue = i.blockIter.Next()
> 	for k != nil && i.blockIter.cmp(k.UserKey, i.span.Start) == 0 {
> 		i.decodeSpanKeys(k, internalValue)
> ```

so there will be multiple calls to 
```
i.span, i.err = rangekey.Decode(*k, internalValue, i.span.Keys)
```
after we have set
```
i.span.Keys = i.keyBuf[:0]
```
This is a bit confusing. The call to Decode provides i.span.Keys as scratch space so it must be the unused part of the slice, but by doing the assignment `i.span.Keys` is now the used part. Won't this cause an overwrite?
___
*[testdata/flushable_batch, line 24 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyqzA5764LKK1DNiOD4:-MyqzA5764LKK1DNiOD5:b670cd1) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/testdata/flushable_batch#L24)):*
> ```
> c#5,2:2
> c#4,1:1
> 1-3:{(#6,RANGEDEL)}
> ```

very nice readability improvement!


<!-- Sent from Reviewable.io -->

2022-03-23 17:13 UTC, nicktrav reviewed
Done with `keyspan`. Flushing some comments.

> Reviewed 3 of 81 files at r1, 1 of 14 files at r2, 6 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1587#-:-Myrl7Qk4EI7JSWx0QR6:bqda0co)* status: 61 of 81 files reviewed, 30 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/keyspan/bound_iter.go, line 185 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Mymsc7e4Mjik2aoCYOH:-MyrX10oCC54U0WrQMvm:b19olyb) ([raw file](https://github.com/cockroachdb/pebble/blob/0ad186894f6dfa60b3b39371fa6df2d623f4dfd7/internal/keyspan/bound_iter.go#L185)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

yay, more simplicity!
</blockquote></details>

This is great! Occam's razor ftw.
___
*[internal/keyspan/fragmenter.go, line 70 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyrYIBy5-sTT_SK0_2V:-MyrYIBy5-sTT_SK0_2W:b2s2fs5) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/keyspan/fragmenter.go#L70)):*
> ```Go
> 	Format base.FormatKey
> 	// Emit is called to emit a fragmented span and its keys. Every key defined
> 	// within the emitted Span applied over the entirety of the Span's key span.
> ```

nit: "... is applied over ..."? Or "... applies to the entirety of ..."?
___
*[internal/keyspan/iter.go, line 13 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyrcIiD1ng-vK9npntw:-MyrcIiD1ng-vK9npntx:b-b4clgd) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/keyspan/iter.go#L13)):*
> ```Go
> )
> 
> // FragmentIterator defines an interator interface over spans. The spans
> ```

s/interator/iterator/
___
*[internal/keyspan/iter.go, line 59 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyrdLtS7V4Vwh-gRL4J:-MyrdLtS7V4Vwh-gRL4K:bxvvwuv) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/keyspan/iter.go#L59)):*
> Exhausting all the key/value pairs in a table is not considered to be an error.

This comment seemed a bit out of place, given that it's talking about tables, and exhausting an iter can happen independent of closing it.
___
*[internal/keyspan/iter.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyrdpRo8N1Z-aqMBUBF:-MyrdpRo8N1Z-aqMBUBG:b34385l) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/keyspan/iter.go#L67)):*
> ```Go
> 	// result of Next and Prev will be undefined until the iterator has been
> 	// repositioned with SeekGE, SeekLT, First, or Last.
> 	SetBounds(lower, upper []byte)
> ```

nit: worth saying that that lower and upper are inclusive and exclusive bounds, respectively?
___
*[internal/keyspan/merging_iter.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyriFhb2MfRf2ZOf68b:-MyriFhb2MfRf2ZOf68c:bfa8n8b) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/keyspan/merging_iter.go#L76)):*
> ```Go
> // merging iterator wraps each of these input iterators with a
> // fragmentBoundIterator that returns each individual boundary of the underlying
> // fragments separately. If the underyling FragmentIterator has fragments
> ```

s/underyling/underlying/
___
*[internal/keyspan/span.go, line 5 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyrRpeiAmEys_4OTW2Y:-MyrRpeiAmEys_4OTW2Z:bcpdim9) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/keyspan/span.go#L5)):*
> ```Go
> // the LICENSE file.
> 
> package keyspan // import "github.com/cockroachdb/pebble/internal/keyspan"
> ```

Sorry to be a bore - should we add unit test coverage for `Span` / `Keys` and associated methods? I'm sure we have transitive coverage, but just in case.
___
*[internal/keyspan/span.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyrO-sjAxaxVehTxmmG:-MyrO-sk4fB87C5PI8c1:b-o9qkye) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/keyspan/span.go#L96)):*
> ```Go
> 
> // LargestKey returns the largest internal key defined by the span's keys. The
> // returned key will always be a sentinel key at the end boundary. It panics if
> ```

Worth a brief comment here to explain _why_ we use the sentinel? i.e. span end is exclusive, but we want "inclusive", etc.


<!-- Sent from Reviewable.io -->

2022-03-23 17:45 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1587)* status: 54 of 81 files reviewed, 25 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[compaction.go, line 2389 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Myr7_rFDY20FAkpXjza:-MyrqOK83dcIi9NQ40cp:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0ad186894f6dfa60b3b39371fa6df2d623f4dfd7/compaction.go#L2389)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So you've removed this cloning of the key, that I was asking about earlier. Maybe add a code comment why a shallow clone is sufficient.
</blockquote></details>

Done.
___
*[internal/keyspan/fragmenter.go, line 416 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MymvkAG3AXEQKOHTF1Z:-MyrkrONELz8WHSuJiFo:btaef6f) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/fragmenter.go#L416)):*
> Your code comment about just-in-time fragmentation is escaping me understanding -- could you elaborate?

Added some elaboration here. Basically what you described here:
>  it can do the fragmentation without stepping to the next fragment in the same level  

but used to avoid cloning `[]Key` during compactions, etc. A compaction only needs to hold onto the current rangedel `keyspan.Span`.
___
*[internal/keyspan/fragmenter.go, line 75 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Myqmu0L7kN2Q_Oz7doX:-MyrkVjb53dpdsXTL0Dy:b-h6ukpi) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/keyspan/fragmenter.go#L75)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

but now Emit is copying the slice.
</blockquote></details>

oops, removed.
___
*[internal/keyspan/merging_iter.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyriFhb2MfRf2ZOf68b:-Myro7nN4L7rZA4Hg7Op:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/keyspan/merging_iter.go#L76)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

s/underyling/underlying/
</blockquote></details>

Done.
___
*[internal/keyspan/seek.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Mymlq6_AHy7c7QABstr:-Myrs2lI9WmQR6DPL4AS:bp2jimd) ([raw file](https://github.com/cockroachdb/pebble/blob/b207c70373760347fdd98da3f4df38a1cd034bd1/internal/keyspan/seek.go#L35)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am ok with whatever you decide.
</blockquote></details>

Added a TODO for now.
___
*[internal/keyspan/span.go, line 5 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyrRpeiAmEys_4OTW2Y:-MyrsBkyE7BHHjuH6JDh:bp2jimd) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/keyspan/span.go#L5)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Sorry to be a bore - should we add unit test coverage for `Span` / `Keys` and associated methods? I'm sure we have transitive coverage, but just in case.
</blockquote></details>

Added a TODO for now.
___
*[internal/keyspan/truncate.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyqsL5L6uGtC8Wf6DfH:-MyrpSsU6JR-8TlCj8V2:b-p3oi86) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/keyspan/truncate.go#L57)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I hadn't thought through the allocation cost of this gathered spans approach -- we will often have a slice of Keys with 1 element. I am sure we can optimize the cost away. I worry that our normal benchmarks won't stress rangedels and rangekeys in a way that we will notice the additional cost. How about creating an issue regarding creating such a benchmark, so we can run it on the code before and after this refactor and see where to optimize (run it after this PR merges of course).
</blockquote></details>

Do you think we can use #1295 to track this work? (Also tagging #1444 so that we consult this discussion when we perform range key benchmarking)
___
*[sstable/block.go, line 1038 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyrBOgUECHsORM0Gn3M:-MyrqlFyCgzeDpqMgHN5:bma6p9d) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/sstable/block.go#L1038)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

so there will be multiple calls to 
```
i.span, i.err = rangekey.Decode(*k, internalValue, i.span.Keys)
```
after we have set
```
i.span.Keys = i.keyBuf[:0]
```
This is a bit confusing. The call to Decode provides i.span.Keys as scratch space so it must be the unused part of the slice, but by doing the assignment `i.span.Keys` is now the used part. Won't this cause an overwrite?
</blockquote></details>

This current organization is convoluted and subtle. `Decode` doesn't use it as scratch space, but as the destination of accumulated Spans. The result is that `Decode` returns a `Span` with all the keys that already existed in the slice, plus all the newly decoded `Key`s. I'm going to put a TODO to clean this up, because it is very confusing and subtle.


<!-- Sent from Reviewable.io -->

2022-03-23 18:26 UTC, nicktrav approved these changes
Done with the rest, excluding tests. I'll review those now, so don't block on the review there. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Thanks for the herculean effort in re-working this! :muscle:

> Reviewed 10 of 81 files at r1, 8 of 14 files at r2, 4 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1587#-:-Mys0Th85kFw5kEowhnT:bwt7uw0)* status: 54 of 81 files reviewed, 28 unresolved discussions (waiting on @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/coalesce.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyrsKwt63ziCgCSfvCw:-MyrsKwt63ziCgCSfvCx:b-r33bdg) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/rangekey/coalesce.go#L76)):*
> ```Go
> // CoalescedSpan.
> 
> // Coalesce imposes range key semantics and coalesces range keys with the same
> ```

nit: there are some other mentions of "fragments" / `keyspan.Fragments` in this comment. Do we want to replace those too?
___
*[internal/rangekey/rangekey.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyrtdohCbSpsEMn7Nex:-MyrtdohCbSpsEMn7Ney:b-op2712) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/rangekey/rangekey.go#L60)):*
> ```Go
> )
> 
> // Encode take a Span containing only range keys. It invokes the provided
> ```

s/take/takes/
___
*[sstable/block.go, line 990 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Myrwb3WCYi3RP90Az_u:-Myrwb3WCYi3RP90Az_v:bt2ylat) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/sstable/block.go#L990)):*
> ```Go
> }
> 
> func (i *fragmentBlockIter) decodeSpanKeys(k *InternalKey, internalValue []byte) {
> ```

nit: `decodeSpanKey`, singular?


<!-- Sent from Reviewable.io -->

2022-03-23 18:44 UTC, nicktrav reviewed
Reviewed the tests too. I didn't scrutinize heavily, but they also <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 68 of 81 files at r1, 5 of 14 files at r2, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1587#-:-Mys4p4QBhdH3kd-WcbE:b-18lonf)* status: all files reviewed, 26 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-03-23 18:55 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1587#-:-Mys7MutDsMOXrxjj6P6:b-ppj9h9)* status: all files reviewed, 24 unresolved discussions (waiting on @itsbilal, @nicktrav, and @sumeerbhola)

___
*[internal/rangekey/coalesce.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-MyrsKwt63ziCgCSfvCw:-Mys6ywS7LJmQtzJ7s2v:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/internal/rangekey/coalesce.go#L76)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: there are some other mentions of "fragments" / `keyspan.Fragments` in this comment. Do we want to replace those too?
</blockquote></details>

Done.
___
*[sstable/block.go, line 990 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1587#-Myrwb3WCYi3RP90Az_u:-Mys7BuS3CAqYsrtAR1V:b520vrw) ([raw file](https://github.com/cockroachdb/pebble/blob/ec7c969050397d92cb9bac45cf5a60466c782863/sstable/block.go#L990)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: `decodeSpanKey`, singular?
</blockquote></details>

it's using `Keys` to refer to `Span.Keys`. I'll make sure to make this clearer when I address the below TODO around `i.span.Keys` accumulation.


<!-- Sent from Reviewable.io -->

2022-03-23 19:06 UTC, merged