vfs: capture operation type affected by disk slowness
cockroachdb/pebble pull request #1672
Opened 2022-04-27 21:26 UTC by nicktrav

Currently, if a Pebble DB is backed by `vfs.FS` that is wrapped with a
`vfs.diskHealthCheckingFS`, the DB can be made aware of operations that
are taking longer than some threshold. Typically these "disk slowness"
events are capture to the Pebble event log.

The current implementation does not make any distinction between the
operation type (write, sync, etc.) that was observed as slow.

Capture the type of operation being performed when emitting a disk
slowness event into the event log.

2022-04-27 21:26 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1672)
<!-- Reviewable:end -->

2022-04-27 21:29 UTC, nicktrav commented
No strong opinions on whether this goes in or not. It came up in the context of a support issue ([internal](cockroachlabs/support#1564)) where we knew that some operation on a WAL was "slow", and the question was "what type of operation".

2022-05-02 20:12 UTC, sumeerbhola requested changes
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1672)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @nicktrav and @sumeerbhola)

___
*[`vfs/disk_health.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1672#-N15NM4q3zkEvZOMo97p:-N15NM4r7j_fwjE3g9W0:b-nk838m) ([raw file](https://github.com/cockroachdb/pebble/blob/6a51ed5ebfa9040c2b6b2874e98bd93b9c500ec8/vfs/disk_health.go#L62)):*
> ```Go
> 	stopper        chan struct{}
> 	lastOp         uint32
> 	lastWriteNanos int64
> ```

Can we bundle lastWriteNanos and lastOp into a single int64, say by sampling the time at Create time and using it as a shared offset for both now and the lastWriteNanos? With the current sequence
```
	atomic.StoreInt64(&d.lastWriteNanos, time.Now().UnixNano())
	atomic.StoreUint32(&d.lastOp, uint32(o))
	defer func() {
		atomic.StoreInt64(&d.lastWriteNanos, 0)
		atomic.StoreUint32(&d.lastOp, 0)
	}()
```
there is a risk that the ticker grabs inconsistent values of lastWriteNanos and lastOp -- in the extreme an older value of lastWriteNanos that exceeded the threshold and then a newer value of lastOp that has just begun.


<!-- Sent from Reviewable.io -->

2022-05-03 02:21 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1672)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @jbowens and @sumeerbhola)

___
*[`vfs/disk_health.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1672#-N15NM4q3zkEvZOMo97p:-N16gGs_-Q9o2wbRpqyr:b8qgkoc) ([raw file](https://github.com/cockroachdb/pebble/blob/6a51ed5ebfa9040c2b6b2874e98bd93b9c500ec8/vfs/disk_health.go#L62)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

You're right there's a race here.

If I'm understanding your suggestion - given the health checking doesn't need to be "exact" (i.e. currently, it's nanosecond precision, but it could reasonably just be microsecond, or even millisecond / second precision), we can zero out a portion of the int64 (the last few bits) and repurpose it for the op code?

I was also thinking if the precision was something like millisecond / second - we could get away with 7 bytes and then use the last (or first) byte as the op type.

Either way accomplishes the same goal. Do you have a preference? cc: @jbowens 
</blockquote></details>

I don't think we *need* to play with the precision, though that is definitely a reasonable alternative. These files are not going to be open for 290 years. So if we stash the starting offset at Create time we can use 56 bits for the nanos from that offset. I think that gives us > 2 years, though you should double check my math, for how long the file object is alive, for this timing to work. I doubt we will have a file open for write for that long. We could also bump up to 60 bits or something and get a longer life.


<!-- Sent from Reviewable.io -->

2022-05-04 22:07 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1672#-:-N1G6MTR7FQcc_0hB930:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[`vfs/disk_health.go` line 165 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1672#-N1G4ed3CBrU43zu0TYl:-N1G4ed4-evhWPY7vG1k:bi3kc5c) ([raw file](https://github.com/cockroachdb/pebble/blob/d31ae847a02cdab7b27151ae321ba390265da500/vfs/disk_health.go#L165)):*
> ```Go
> 
> 	offsetNanos := time.Since(d.createTime).Nanoseconds()
> 	if offsetNanos < 0 || (offsetNanos > 1<<nOffsetBits-1) {
> ```

is there anything ensuring a monotonic clock?
If not, I think we should avoid panicking for offsetNanos < 0, by changing it to offsetNanos=0. So if we have a small regression in the clock and a very slow op, we'll still catch it. 
___
*[`vfs/disk_heath_test.go` line 17 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1672#-N1G5eXN4vno3b6V7YPs:-N1G5eXN4vno3b6V7YPt:b-u52p09) ([raw file](https://github.com/cockroachdb/pebble/blob/d31ae847a02cdab7b27151ae321ba390265da500/vfs/disk_heath_test.go#L17)):*
> ```Go
> 
> type mockFile struct {
> 	syncDuration time.Duration
> ```

syncAndWriteDuration?
___
*[`vfs/disk_heath_test.go` line 188 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1672#-N1G6F1c9NtKQ-AQyd9g:-N1G6F1c9NtKQ-AQyd9h:bb7lbs2) ([raw file](https://github.com/cockroachdb/pebble/blob/d31ae847a02cdab7b27151ae321ba390265da500/vfs/disk_heath_test.go#L188)):*
> ```Go
> 	// trigger a panic, as the calculated offset from the file creation time would
> 	// result in integer overflow.
> 	require.Panics(t, func() { _, _ = hcFile.Write([]byte("uh oh")) })
> ```

nice


<!-- Sent from Reviewable.io -->

2023-01-19 20:39 UTC, closed without merging