db: add Pebble interface for CPU slot granter
cockroachdb/pebble pull request #1714
Opened 2022-05-23 19:30 UTC by bananabrick

CockroachDB has, or will have the ability to let Pebble know when
it can use additional CPU resources. Since Cockroach imports Pebble
and not the other way around, this pr defines a Pebble interface
which describes methods which Cockroach's slot granter should define.

2022-05-23 19:30 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1714)
<!-- Reviewable:end -->

2022-05-26 16:16 UTC, sumeerbhola requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1714)* status: all files reviewed, 3 unresolved discussions (waiting on @bananabrick)

___
*[`compaction.go` line 2080 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1714#-N3074bO8q5Amd5JbxNE:-N3074bO8q5Amd5JbxNF:b-5php1n) ([raw file](https://github.com/cockroachdb/pebble/blob/0c23e5e10e0fc10da94e4a81ddf64b935c53b30e/compaction.go#L2080)):*
> ```Go
> 		slotGranter = loadedGranter.(SlotGranter)
> 	}
> 	var gotSlot int
> ```

Let's make this more secure against accounting errors caused by early return, with something like:
```
var numCompressionProcs int
defer func() {
  if numCompressionProcs > 0 {
     cpuWorkGranter.ReturnProcs(numCompressionProcs)
   }
}
...

newOutput := func() error {
   ....
   if cpuWorkGranter != nil {
      numCompressionProcs += cpuWorkGranter.TryGetProcs(1)
      if numCompressionProcs > 0 ...
   ...
}

finishOutput := func() error {
    ...
    if numCompressionProcs > 0 {
      cpuWorkGranter.ReturnProcs(numCompressionProcs)
      numCompressionProcs = 0
    }
```
___
*[`db.go` line 187 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1714#-N303galBsmofFd--YnD:-N303galBsmofFd--YnE:btq0nnk) ([raw file](https://github.com/cockroachdb/pebble/blob/0c23e5e10e0fc10da94e4a81ddf64b935c53b30e/db.go#L187)):*
> ```Go
> // SlotGranter can be used to give Pebble the ability to perform additional
> // CPU bound work. Primarily, the interface will be used by Cockroach so that
> // it can pass its soft slot granter to Pebble.
> ```

The slot terminology is probably not appropriate here. Also, mark this as experimental and subject to change in a code comment. How about something like:
```
// CPUWorkPermissionGranter is used to request permission to opportunistically use additional CPUs to speed up internal background work. Each granted "proc" can be used to spin up a CPU bound goroutine, i.e, if scheduled each such goroutine can consume one P in the goroutine scheduler. The calls to ReturnProcs can be a bit delayed, since Pebble interacts with this interface in a coarse manner. So one should assume that the total number of granted procs is a non tight upper bound on the CPU that will get consumed.
type CPUWorkPermissionGranter interface {
  TryGetProcs(num int) int
   ReturnProcs(num int)
}
```
___
*[`db.go` line 484 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1714#-N3009S1DDqgZV4UQyUS:-N3009S1DDqgZV4UQyUT:b-wotgkk) ([raw file](https://github.com/cockroachdb/pebble/blob/0c23e5e10e0fc10da94e4a81ddf64b935c53b30e/db.go#L484)):*
> ```Go
> 
> // SetSlotGranter can be used to set the SlotGranter in Pebble. It can be called
> // anytime after Pebble is opened.
> ```

A bit of a nit. I'm assuming this is  a method and not part of Options since it is easier in CockroachDB to wire this up after Pebble has been created? Currently we create engines before creating admission control stuff in `NewServer` in `server.go`. Though perhaps that could be reordered.
Even if it can't, I think it is somewhat peculiar to not put this in `Options` since CockroachDB's initialization sequencing issues are not Pebble's problem. Conceptually this is something that lives for the lifetime of a Pebble instance and so Options is the right place. If we need a level of indirection to make this dynamic, it could be done inside CockroachDB.
 


<!-- Sent from Reviewable.io -->

2022-05-26 18:58 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1714)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)

___
*[`compaction.go` line 2080 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1714#-N3074bO8q5Amd5JbxNE:-N30izV80ogBxe3MOMi2:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0c23e5e10e0fc10da94e4a81ddf64b935c53b30e/compaction.go#L2080)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Let's make this more secure against accounting errors caused by early return, with something like:
```
var numCompressionProcs int
defer func() {
  if numCompressionProcs > 0 {
     cpuWorkGranter.ReturnProcs(numCompressionProcs)
   }
}
...

newOutput := func() error {
   ....
   if cpuWorkGranter != nil {
      numCompressionProcs += cpuWorkGranter.TryGetProcs(1)
      if numCompressionProcs > 0 ...
   ...
}

finishOutput := func() error {
    ...
    if numCompressionProcs > 0 {
      cpuWorkGranter.ReturnProcs(numCompressionProcs)
      numCompressionProcs = 0
    }
```

</blockquote></details>

Done.
___
*[`db.go` line 187 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1714#-N303galBsmofFd--YnD:-N30j-eJ39uPW3Y54k94:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0c23e5e10e0fc10da94e4a81ddf64b935c53b30e/db.go#L187)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The slot terminology is probably not appropriate here. Also, mark this as experimental and subject to change in a code comment. How about something like:
```
// CPUWorkPermissionGranter is used to request permission to opportunistically use additional CPUs to speed up internal background work. Each granted "proc" can be used to spin up a CPU bound goroutine, i.e, if scheduled each such goroutine can consume one P in the goroutine scheduler. The calls to ReturnProcs can be a bit delayed, since Pebble interacts with this interface in a coarse manner. So one should assume that the total number of granted procs is a non tight upper bound on the CPU that will get consumed.
type CPUWorkPermissionGranter interface {
  TryGetProcs(num int) int
   ReturnProcs(num int)
}
```
</blockquote></details>

Done.
___
*[`db.go` line 484 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1714#-N3009S1DDqgZV4UQyUS:-N30j0EZCuY2Mv8jstRZ:b5ntty7) ([raw file](https://github.com/cockroachdb/pebble/blob/0c23e5e10e0fc10da94e4a81ddf64b935c53b30e/db.go#L484)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

A bit of a nit. I'm assuming this is  a method and not part of Options since it is easier in CockroachDB to wire this up after Pebble has been created? Currently we create engines before creating admission control stuff in `NewServer` in `server.go`. Though perhaps that could be reordered.
Even if it can't, I think it is somewhat peculiar to not put this in `Options` since CockroachDB's initialization sequencing issues are not Pebble's problem. Conceptually this is something that lives for the lifetime of a Pebble instance and so Options is the right place. If we need a level of indirection to make this dynamic, it could be done inside CockroachDB.
 
</blockquote></details>

Will set the option in Cockroach.


<!-- Sent from Reviewable.io -->

2022-05-26 19:59 UTC, bananabrick commented
Need to make a small change to this. Just realized that I'm not respecting the parallelism option which is passed in. 😬

2022-05-27 12:59 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1714#-:-N34aV5o8g81lWVbiyeu:bg7igkv)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-05-27 23:13 UTC, bananabrick commented
TFTR!

2022-05-27 23:13 UTC, merged