internal/metamorphic: add block-property filter coverage
cockroachdb/pebble pull request #1737
Opened 2022-06-03 19:51 UTC by jbowens

**sstable: fix additional bounds check bugs**

In 4406dabc a bounds-checking bug was fixed in the two-level index
iterator's SeekLT method. The same bug existed within Last and
skipBackward and was missed.

**db: refactor levelIter/mergingIter boundary interface**

The levelIter and mergingIter are tightly coupled in a few places, with the
levelIter passing additional context to the mergingIter by writing into fields
owned by the mergingIter. This commit is a small refactor to organize these
fields together into a `levelIterBoundaryContext` struct. This is in
preparation for adding an additional field.

**db: don't filter range deletions based on point-key block filters**

Previously, if an iterator configured with a block-property filter encountered
a table that contained all excluded point keys, the iterator would skip the
table entirely, including its range deletions. An iterator configured with a
block-property filter could observe keys outside the filtered range that no
longer exist.

This behavior was fine from CockroachDB's perspective, which always pairs a
filtered iterator with an unfiltered iterator, seeking the latter in tandem.
The behavior is likely to be surprising in non-CockroachDB use cases.
Additionally, the behavior is an obstacle to range-key masking which must
respect range deletions for keys not covered by the masking range key.

This change requires additional coordination between the mergingIter and
levelIter to ensure that a levelIter doesn't close a file while other levels
still require its range deletions. This coordination takes the form a new
`isIgnorableBoundaryKey` field. The levelIter may return a file's smallest or
largest boundary key [without any value], setting `isIgnorableBoundaryKey` to
true to signal the key doesn't repesent a real KV pair. This scheme is also
extended to SeekPrefixGE, which previously synthesized a RANGEDEL key to serve
a similar purpose.

**internal/metamorphic: add block-property filter coverage**

Add test coverage for block-property filters to the metamorphic tests.
Division of keys into blocks are nondeterministic, so this introduces
nondeterminism into Iterator behavior. To account for this, the metamorphic
test's iterator wrapper is adjusted to skip any keys that are eligible for
filtering.

Fix https://github.com/cockroachdb/pebble/issues/1725.

2022-06-03 19:51 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1737)
<!-- Reviewable:end -->

2022-06-03 19:53 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737)* status: 0 of 15 files reviewed, 1 unresolved discussion

___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3f776G-_quKEPK-d5j):*
I swear I checked for this; but somehow they slipped through.


<!-- Sent from Reviewable.io -->

2022-06-06 21:21 UTC, sumeerbhola reviewed
btw, I'm assuming you don't want to narrow the block property collector interface to only allow keys. I'm a bit torn about this -- I can see some utility to a future where values also contribute.

Either way, I think we could use a better version of the "truthful-bpf" comment from https://github.com/cockroachdb/pebble/issues/1725#issuecomment-1139741524 in block_property.go, to lay out the meaning of correctness.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737#-:-N3usOb81Ou098pHsUDI:b-f8unx2)* status: 9 of 15 files reviewed, 10 unresolved discussions (waiting on @jbowens and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-06-29 22:27 UTC, jbowens reviewed
nice, yeah, I added a comment to block_property.go describing this 'deterministic' block-property filtering.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737#-:-N5lZ_c83L5HSufkj8Va:btptqe7)* status: 1 of 16 files reviewed, 10 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`level_iter.go` line 79 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tMyOLBnzgtWObosyV:-N5l989XARGFbdajh2k8:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/level_iter.go#L79)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

to recognize ...
</blockquote></details>

Done.
___
*[`level_iter.go` line 680 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tQXxQEtLwBK2KE6jV:-N5l9fhb8fT4tiM7HZDy:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/level_iter.go#L680)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think its worth saying in a code comment here something like: it is safe to return l.iterFile.Largest since it must have been skipped, and therefore must be > what we have previously returned when iterating in this direction, and so the monotonicity required by the mergingIter heap is not violated.
</blockquote></details>

Done.
___
*[`level_iter.go` line 750 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tRBpo0e8OjBYj3mzp:-N5l9ml52LH2ehuz6eDt:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/level_iter.go#L750)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`merging_iter.go` line 48 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tLPtl0H2LWHvIslVG:-N5lAAYeCrLMaduS7JR-:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/88f5d752d9c444a611193ca177cdd463f4110dbc/merging_iter.go#L48)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

sentinel.
</blockquote></details>

Done.
___
*[`table_cache.go` line 400 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tSH1S9JH6xoXErdx5:-N5lBigfBFXl6rBpQupL:b2csj4r) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/table_cache.go#L400)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

would it be slightly more efficient if we returned filteredAll only if rangeDelIter was non-nil?
</blockquote></details>

i'm not sure. we won't ever attempt to call `FilteredAnyKeys()` unless the level's rangedel iter is non-nil. i think the thing that might be slightly more efficient is to only populate `levelIter.filteredIter` if the rangedel iter is non-nil, so we can avoid the interface type assertion: i'll make that change now.
___
*[`sstable/reader.go` line 219 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tT6w316Cxjlyru639:-N5lAbsD7XDTb421yorU:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/sstable/reader.go#L219)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

for naming consistency, can you call this `filteredAnyKeys`.
</blockquote></details>

Done.
___
*[`sstable/reader.go` line 527 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tpUwM2WLELBGdQTul:-N5lI-N-9DzXMJcFeAWI:bp7r8st) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/sstable/reader.go#L527)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This makes me nervous, in that I think this happens to be correct because of the specifics of the logic in `seekGEHelper` that tries to use the current iterator position and avoids doing a seek.
But in general I am worried that if we have previously stopped because the block was irrelevant, it could also include keys that are relevant to this seek position. And so if we now decide to not do a full seek (which is correct) we may erroneously return filteredKey=false, when it is in fact true.

Maybe one way to build more confidence is to establish an invariant on these next optimizations for the seeks e.g. do we ever try to use a next optimization if the last positioning call (step or seek) returned nothing because of `loadBlockIrrelevant`. I think not, because we seem to condition on `!data.isDataInvalidated()` and on `!i.index.isDataInvalidated()`, but I would appreciate you taking a closer look.
</blockquote></details>

I see what you mean. I scrutinized the code, and my understanding matches yours: The conditions on `!i.data.isDataInvalidated()` and `!i.index.isDataInvalidated()` ensure we'll never `trySeekUsingNext` if the last positioning method returned nothing. I'm going to spend a little more time with this tomorrow to find the right invariants to document and assert.


<!-- Sent from Reviewable.io -->

2022-06-29 22:30 UTC, jbowens reviewed
Note to self: this needs to be updated to apply similar logic for range-key deletions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737#-:-N5l_HfAAvSC6nj6GsYA:br9e6ob)* status: 1 of 16 files reviewed, 10 unresolved discussions (waiting on @jbowens and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-06-30 18:09 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737)* status: 0 of 18 files reviewed, 10 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`level_iter.go` line 680 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tQXxQEtLwBK2KE6jV:-N5plJ_j4SrLeztDwgsW:b74vfd) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/level_iter.go#L680)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually, it _is_ possible `l.iterFile.Largest` was _not_ skipped. A SeekGE that lands on a index separator `k` only knows that the block at the index entry contains keys ≤ k. We can't know whether there were actually keys between the seek key and the index key. If the block is then excluded due to block-property filters, we'll think keys were filtered when none were.

I think this ≤ monotonicity—as opposed to strictly increasing monotonicity—is still okay with respect to the merging iterator. I adjusted the commentary here and renamed the `FilteredAnyKeys` function to `MaybeFilteredKeys()`.
___
*[`sstable/reader.go` line 96 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tUA-W3UNx1VY1fNjt:-N5plCBx-oMbIGS4lbFi:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/sstable/reader.go#L96)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this change could use some datadriven testing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-01 17:34 UTC, nicktrav reviewed
> Reviewed 1 of 2 files at r1, 14 of 14 files at r7, 5 of 5 files at r8, 6 of 6 files at r9, 12 of 12 files at r11, 6 of 6 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737)* status: all files reviewed, 13 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[`sstable/block_property.go` line 53 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N5uhoAE5414vFXNgItQ:-N5uhoAE5414vFXNgItR:bov993r) ([raw file](https://github.com/cockroachdb/pebble/blob/4d9ccec78adc0603991389c699176d79f81e4d50/sstable/block_property.go#L53)):*
> ```Go
> // into blocks is nondeterministic. Block propery filtering may introduce two
> // kinds of errors:
> //   a) Point keys that match the filter may be surfaced. This may happen
> ```

In the context of block property filters, doesn't "filter" imply that it matches (intersects / selects) the block? Yet here we're saying that "point keys matching the filter" is a type of error?
___
*[`sstable/block_property.go` line 52 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N5uo-yM6KwbiSFPZyvb:-N5uo-yM6KwbiSFPZyvc:b-fsthcd) ([raw file](https://github.com/cockroachdb/pebble/blob/2ee9c7eeb59ad87b3594128c945d2973f320ee55/sstable/block_property.go#L52)):*
> ```Go
> // Block property filtering is nondeterministic because the separation of keys
> // into blocks is nondeterministic. Block propery filtering may introduce two
> // kinds of errors:
> ```

Is "error" accurate in this context? Can this be thought of more like a "false positive"?
___
*[`sstable/testdata/block_properties` line 443 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N5uluBYD-k6onamTzYB:-N5uluBYD-k6onamTzYC:b-p29jne) ([raw file](https://github.com/cockroachdb/pebble/blob/0fc31049ff17c9b36da0750917c1756827289879/sstable/testdata/block_properties#L443)):*
> ```
> <a@1:1> MaybeFilteredKeys()=true
> 
> # Test FilteredAnyKeys().
> ```

nit: `MaybeFilteredKeys`? Same elsewhere.


<!-- Sent from Reviewable.io -->

2022-07-01 18:56 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737)* status: 9 of 18 files reviewed, 13 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[`sstable/block_property.go` line 53 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N5uhoAE5414vFXNgItQ:-N5v2tf4EzKO9EREjTzo:b7ovbh2) ([raw file](https://github.com/cockroachdb/pebble/blob/4d9ccec78adc0603991389c699176d79f81e4d50/sstable/block_property.go#L53)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

In the context of block property filters, doesn't "filter" imply that it matches (intersects / selects) the block? Yet here we're saying that "point keys matching the filter" is a type of error?
</blockquote></details>

Since block boundaries are completely variable, it is only meaningful to define block-property filters in order to apply a filter function that is a function of the key-value pairs. Block and table level filtering is just the mechanic, but the intended filter is always a function of the point keys themselves.
___
*[`sstable/block_property.go` line 52 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N5uo-yM6KwbiSFPZyvb:-N5v43n9-ipMTSi17gmS:b-qu51xb) ([raw file](https://github.com/cockroachdb/pebble/blob/2ee9c7eeb59ad87b3594128c945d2973f320ee55/sstable/block_property.go#L52)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Is "error" accurate in this context? Can this be thought of more like a "false positive"?
</blockquote></details>

I think "false positive" or "false negative" are errors, in the statistical sense. I used the "false negative" language down below to describe the first form of error. I'm not sure whether "false positive" (positive as in what survives the filter) or "false negative" (negative as in the filter failing to detect the key) is the appropriate term?

I don't think the second form of error can be described as a false negative/positive, because it's a violation of the semantics ordinarily guaranteed by Pebble: If you delete a key, it should appear deleted on all subsequent reads.
___
*[`sstable/testdata/block_properties` line 443 at r11](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N5uluBYD-k6onamTzYB:-N5v6RRo1qFdlPe7xrzx:b1jxzi3) ([raw file](https://github.com/cockroachdb/pebble/blob/0fc31049ff17c9b36da0750917c1756827289879/sstable/testdata/block_properties#L443)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: `MaybeFilteredKeys`? Same elsewhere.
</blockquote></details>

good catch, done.


<!-- Sent from Reviewable.io -->

2022-07-01 21:52 UTC, nicktrav approved these changes
> Reviewed 9 of 9 files at r14, 9 of 9 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737)* status: all files reviewed, 10 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[`sstable/block_property.go` line 53 at r9](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N5uhoAE5414vFXNgItQ:-N5vWXl27dOO0NPG8r4k:bfu30ai) ([raw file](https://github.com/cockroachdb/pebble/blob/4d9ccec78adc0603991389c699176d79f81e4d50/sstable/block_property.go#L53)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Since block boundaries are completely variable, it is only meaningful to define block-property filters in order to apply a filter function that is a function of the key-value pairs. Block and table level filtering is just the mechanic, but the intended filter is always a function of the point keys themselves.
</blockquote></details>

The mechanics of it I understand. Just a matter of interpretation ... does "match the filter" mean "filtering for" or "filtering out"? /shrug
___
*[`sstable/block_property.go` line 52 at r13](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N5uo-yM6KwbiSFPZyvb:-N5vSDws3trSpzY-ExCi:b4c9lyr) ([raw file](https://github.com/cockroachdb/pebble/blob/2ee9c7eeb59ad87b3594128c945d2973f320ee55/sstable/block_property.go#L52)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think "false positive" or "false negative" are errors, in the statistical sense. I used the "false negative" language down below to describe the first form of error. I'm not sure whether "false positive" (positive as in what survives the filter) or "false negative" (negative as in the filter failing to detect the key) is the appropriate term?

I don't think the second form of error can be described as a false negative/positive, because it's a violation of the semantics ordinarily guaranteed by Pebble: If you delete a key, it should appear deleted on all subsequent reads.
</blockquote></details>

:thumbsup: 


<!-- Sent from Reviewable.io -->

2022-07-05 17:04 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 5 files at r8, 3 of 6 files at r9, 2 of 12 files at r11, 4 of 9 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737#-:-N6EJWUI-gPuTXalEPGb:bg7igkv)* status: all files reviewed, 12 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[`level_iter.go` line 680 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tQXxQEtLwBK2KE6jV:-N6E9vp10p2_sy4Tg4Iu:bpzmazz) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/level_iter.go#L680)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Actually, it _is_ possible `l.iterFile.Largest` was _not_ skipped. A SeekGE that lands on a index separator `k` only knows that the block at the index entry contains keys ≤ k. We can't know whether there were actually keys between the seek key and the index key. If the block is then excluded due to block-property filters, we'll think keys were filtered when none were.

I think this ≤ monotonicity—as opposed to strictly increasing monotonicity—is still okay with respect to the merging iterator. I adjusted the commentary here and renamed the `FilteredAnyKeys` function to `MaybeFilteredKeys()`.
</blockquote></details>

I see. Can you also add this index separator example to the code comment to clarify to the reader why we need this maybe-semantics.
___
*[`table_cache.go` line 400 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tSH1S9JH6xoXErdx5:-N6EAd3E9mSm7miGMhmN:b2nhysk) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/table_cache.go#L400)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

i'm not sure. we won't ever attempt to call `FilteredAnyKeys()` unless the level's rangedel iter is non-nil. i think the thing that might be slightly more efficient is to only populate `levelIter.filteredIter` if the rangedel iter is non-nil, so we can avoid the interface type assertion: i'll make that change now.
</blockquote></details>

ack
___
*[`sstable/block_property.go` line 59 at r15](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N6ECHx_7qEfd4m0EktA:-N6ECHx_7qEfd4m0EktB:b-j5bcvb) ([raw file](https://github.com/cockroachdb/pebble/blob/37817233812728fec201fa57c5468b16d0477af7/sstable/block_property.go#L59)):*
> ```Go
> //      used for filtering is not a strict function of the user key, a block
> //      containing k.DEL may be filtered, while a block containing the deleted
> //      key k.SET may not be filtered.
> ```

The comment is missing a correctness definition. I think it is worth separating out the abstract notion of the kv-filter. Also, it may be easier to read if the solution to each problem goes together with the problem definition.

So I'd suggest organizing it in a manner like (of course with all the other details in your comment):
- There is a filter that applies to key-value pairs. Correctness is defined as surfacing exactly the key-value pairs that correspond to applying the kv-filter *after* reading from the DB.
- Block property filtering that uses that kv-filter produces additional values that don't satisfy the filter because of the separation of keys into blocks. These can be removed by reapplying the kv-filter above the filtering applied by bpf.
- Block property filtering may surface point keys that have been deleted if the kv-filter looks at the value. Don't use such a filter (actually the more nuanced statement in your comment).
___
*[`sstable/reader.go` line 527 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tpUwM2WLELBGdQTul:-N6EGzlc8jP69HJ-tobF:b5g76lo) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/sstable/reader.go#L527)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I see what you mean. I scrutinized the code, and my understanding matches yours: The conditions on `!i.data.isDataInvalidated()` and `!i.index.isDataInvalidated()` ensure we'll never `trySeekUsingNext` if the last positioning method returned nothing. I'm going to spend a little more time with this tomorrow to find the right invariants to document and assert.
</blockquote></details>

I think we also need a code comment here talking about this potential interaction between `maybeFilteredKeys` and `trySeekUsingNext` so that the next person changing this code is careful about it. And it isn't limited to `trySeekUsingNext` -- I believe it applies to all stepping instead of seeking optimizations here (there is the monotonic bounds one, that has nothing to do with `trySeekUsingNext`). So it also needs a code comment in `SeekLT`.
___
*[`sstable/testdata/block_properties` line 508 at r15](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N6EIZXz0me33otmjMdM:-N6EIZXz0me33otmjMdN:bz5xkb5) ([raw file](https://github.com/cockroachdb/pebble/blob/37817233812728fec201fa57c5468b16d0477af7/sstable/testdata/block_properties#L508)):*
> ```
> seek-lt a
> seek-lt c
> seek-lt ca
> ```

can you add `seek-lt f` and `seek-lt e` and `seek-lt d` -- I am assuming the first two will produce MaybeFilteredKeys=true.

And is it possible to exercise some of the stepping optimizations by doing SeekGE followed by Next and confirming the correctness of the MaybeFilteredKeys. Also with the one with monotonic bounds that apply to both SeekGE and SeekLT.


<!-- Sent from Reviewable.io -->

2022-07-06 23:01 UTC, jbowens reviewed
@sumeerbhola —I further narrowed `MaybeFilteredKeys` to only be defined at exhausted iterator positions, because otherwise seeks that apply the try-seek-using-next optimization and don't move the iterator position at all will violate the contract. We only care about the exhausted iterator position for levelIter.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737#-:-N6Kijho0kSTnOaWqOKE:bcuhh7)* status: 8 of 18 files reviewed, 11 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[`level_iter.go` line 680 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tQXxQEtLwBK2KE6jV:-N6JkLAuBJX5trhlhTKP:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/level_iter.go#L680)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I see. Can you also add this index separator example to the code comment to clarify to the reader why we need this maybe-semantics.
</blockquote></details>

Done.
___
*[`sstable/block_property.go` line 59 at r15](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N6ECHx_7qEfd4m0EktA:-N6Jpa9o1FYqwBObzdMO:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/37817233812728fec201fa57c5468b16d0477af7/sstable/block_property.go#L59)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The comment is missing a correctness definition. I think it is worth separating out the abstract notion of the kv-filter. Also, it may be easier to read if the solution to each problem goes together with the problem definition.

So I'd suggest organizing it in a manner like (of course with all the other details in your comment):
- There is a filter that applies to key-value pairs. Correctness is defined as surfacing exactly the key-value pairs that correspond to applying the kv-filter *after* reading from the DB.
- Block property filtering that uses that kv-filter produces additional values that don't satisfy the filter because of the separation of keys into blocks. These can be removed by reapplying the kv-filter above the filtering applied by bpf.
- Block property filtering may surface point keys that have been deleted if the kv-filter looks at the value. Don't use such a filter (actually the more nuanced statement in your comment).
</blockquote></details>

Done.
___
*[`sstable/reader.go` line 527 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3tpUwM2WLELBGdQTul:-N6JxESz1h7IrMpybjNG:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/sstable/reader.go#L527)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we also need a code comment here talking about this potential interaction between `maybeFilteredKeys` and `trySeekUsingNext` so that the next person changing this code is careful about it. And it isn't limited to `trySeekUsingNext` -- I believe it applies to all stepping instead of seeking optimizations here (there is the monotonic bounds one, that has nothing to do with `trySeekUsingNext`). So it also needs a code comment in `SeekLT`.
</blockquote></details>

Done.
___
*[`sstable/reader.go` line 695 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N3trQSU2hmCRe15dICX:-N6JxFRsEoh8yjf1WDMm:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/0468c5069e4a1261436190fa34bf3053cab77ec6/sstable/reader.go#L695)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same worry here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-07 12:18 UTC, sumeerbhola requested changes
> because otherwise seeks that apply the try-seek-using-next optimization and don't move the iterator position at all will violate the contract

Because the only safe thing to do in that case is to return true?
Narrowing to exhausted sounds good.

> Reviewed 1 of 12 files at r11, 2 of 10 files at r16, 8 of 8 files at r17.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737#-:-N6NUjp103Yvc7VHHM8_:b-d4vbuj)* status: all files reviewed (commit messages unreviewed), 16 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`sstable/block_property.go` line 54 at r17](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N6NVqSVEubli3gEtqdJ:-N6NVqSVEubli3gEtqdK:b3pbwoa) ([raw file](https://github.com/cockroachdb/pebble/blob/8635bb0f38e4d1d509484e4ebcf37d244eacec2e/sstable/block_property.go#L54)):*
> ```Go
> // implement efficient application of a filter F that applies to key-value
> // pairs. Consider correctness defined as surfacing exactly the same key-value
> // pairs that would be surfaced if one applied the filter F above block-property
> ```

I think it should say "if one applied the filter F above regular iteration"
___
*[`sstable/block_property.go` line 55 at r17](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N6NVmz420meZIbjFiIg:-N6NVmz420meZIbjFiIh:b7f4bbp) ([raw file](https://github.com/cockroachdb/pebble/blob/8635bb0f38e4d1d509484e4ebcf37d244eacec2e/sstable/block_property.go#L55)):*
> ```Go
> // pairs. Consider correctness defined as surfacing exactly the same key-value
> // pairs that would be surfaced if one applied the filter F above block-property
> // filtering With this correctness definition, block property filtering may
> ```

nit: missing period
___
*[`sstable/block_property.go` line 58 at r17](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N6NW7-R8Y5UtaQfXTPT:-N6NW7-R8Y5UtaQfXTPU:bfj9taw) ([raw file](https://github.com/cockroachdb/pebble/blob/8635bb0f38e4d1d509484e4ebcf37d244eacec2e/sstable/block_property.go#L58)):*
> ```Go
> // introduce two kinds of errors:
> //
> //   a) Block property filtering that uses a kv-filter may produce additional
> ```

we haven't defined "kv-filter". Perhaps the earlier comment that introduces F can say "... of a filter F that applies to key-value pairs (abbreviated as kv-filter)."
___
*[`sstable/testdata/block_properties` line 538 at r17](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N6NZ3pq0SFD_vS49MSd:-N6NZ3pq0SFD_vS49MSe:b-6s12to) ([raw file](https://github.com/cockroachdb/pebble/blob/8635bb0f38e4d1d509484e4ebcf37d244eacec2e/sstable/testdata/block_properties#L538)):*
> ```
> . MaybeFilteredKeys()=true
> . MaybeFilteredKeys()=true
> <b@10:2> MaybeFilteredKeys()=true
> ```

with bounds [b,e), isn't b@10 the first key that is encountered regardless of block property filtering? I'm confused by this true value.
___
*[`sstable/testdata/block_properties` line 540 at r17](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N6NZjlO9buYSPQ1DNlu:-N6NZjlO9buYSPQ1DNlv:b-8ugctg) ([raw file](https://github.com/cockroachdb/pebble/blob/8635bb0f38e4d1d509484e4ebcf37d244eacec2e/sstable/testdata/block_properties#L540)):*
> ```
> <b@10:2> MaybeFilteredKeys()=true
> <c@15:3> MaybeFilteredKeys()=false
> ```

The corner case I was worried about was something like
```
set-bounds lower=b upper=ee
seek-ge d
set-bounds lower=ee upper=g
seek-ge ee
```
where I think the layout of blocks and indices will cause the first seek to skip the lower level index block containing e and f. Then the next set-bounds qualifies for the monotonic bounds stepping optimization, and we want to ensure that `seek-ge ee` also returns true.


<!-- Sent from Reviewable.io -->

2022-07-08 01:14 UTC, jbowens reviewed
Pondering a randomized test that randomizes the index block size and data block size. Maybe two variants, one that tests trySeekUsingNext and one that tests monotonically increasing/decreasing bounds. Might leave it as a TODO/issue to follow up with during stability period.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737#-:-N6QME8u29jCzH4gO8bx:bx8knwn)* status: 15 of 18 files reviewed, 15 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-07-10 20:30 UTC, sumeerbhola requested changes
> Reviewed 1 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737)* status: 16 of 18 files reviewed, 17 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`sstable/reader.go` line 520 at r18](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N6dju-E9NOGPSDecVXa:-N6dju-E9NOGPSDecVXb:b-pez31s) ([raw file](https://github.com/cockroachdb/pebble/blob/f72b9417455dbb57c30f4c59ab8a27d38c81a6cd/sstable/reader.go#L520)):*
> ```Go
> 	// reached. The i.data.isDataInvalidated() indicates that the sstable was
> 	// exhausted.
> 	if trySeekUsingNext && (i.exhaustedBounds == +1 || i.data.isDataInvalidated()) {
> ```

If this case ok because if `maybeFilteredKeys=true`, it will stay true (since the reset to false is after this return)?

Are we losing this optimization for the `twoLevelIterator` case with your latest change because `trySeekUsingNext` will get set to false in the expanded slow-path for `twoLevelIterator.SeekGE`?
___
*[`sstable/reader.go` line 581 at r18](https://reviewable.io/reviews/cockroachdb/pebble/1737#-N6dkdTNDK8NucZce0LE:-N6dkdTOCQDrQ5P5nxhH:box09n1) ([raw file](https://github.com/cockroachdb/pebble/blob/f72b9417455dbb57c30f4c59ab8a27d38c81a6cd/sstable/reader.go#L581)):*
> ```Go
> 		// caller claimed externally known invariant represented by
> 		// trySeekUsingNext=true.
> 		if trySeekUsingNext {
> ```

also, I wonder whether I overlooked this case in my original "This makes me nervous" comment. It doesn't use anything about `i.data.isDataInvalidated` or `i.index.isDataInvalidated`.
- isn't it possible for erroneously return `maybeFilteredKeys=false`
- And this optimization seems to suffer from the same regression in the `twoLevelIterator` case.

If we ever use `trySeekUsingNext` should we just conservatively return `maybeFilteredKeys=true`? I'm generally more concerned about losing a seek optimization than returning an extra synthetic key -- and there are some microbenchmarks that suggested that optimizations for seeks on exhausted iterators were quite helpful since with 90% of the data in L6, it is not uncommon to have L1-L5 level iterators already exhausted. 


<!-- Sent from Reviewable.io -->

2022-07-18 17:10 UTC, jbowens reviewed
TFTR!

filed #1817

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1737#-:-N7HHQ6Y0KZXmI3cTnst:b1dl698)* status: 3 of 18 files reviewed, 17 unresolved discussions (waiting on @nicktrav and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-07-18 17:10 UTC, merged