db: lazily construct combined iterator
cockroachdb/pebble pull request #1791
Opened 2022-06-28 21:32 UTC by jbowens

Combined range-key iteration adds overhead to Pebble iterators. Construction of
the range-key iterator stack adds a noticeable slowdown, even when the LSM
contains no range keys. Additionally, when the LSM contains range keys outside
of the span being iterated over, additional key comparisons are expected to add
an additional slowdown. In order to optimize these cases for the expected case
of rare range keys, this commit adds lazy combined iteration.

When an iterator is constructed with the IterKeyTypePointsAndRanges key type,
iterator construction examines the indexed batch (if any) and memtables to see
if they contain any range keys. If they don't, the iterator is initially
constructed with only a point iterator stack. A flag signals to lower-level
iterators that the user configured the iterator for combined iteration, but
combined iteration isn't yet being used.

When a levelIter observes a file containing range keys, the levelIter sets
state to signal that there might be range keys that need to be interleaved. An
interstitial internal iterator `lazyCombinedIter` observes the signal,
constructs the range-key iterator and reconfigures the iterator stack to use
combined iteration.

While this commit is nice performance win, it unfortunately introduces several
subtle complexities:
  1. When performing lazy combined iteration, the merging iterator must not
     alter seek keys according to range deletions until AFTER the level is
     already positioned according the seek key. This allows levelIters the
     opportunity to observe range keys between the user-provided seek key and
     the new modified seek key.
  2. When the merging iterator does seek a level to a tombstone's end key, it
     must set a new RelativeSeek seek flag, which causes the levelIter to scan
     all the fileMetadata between the original seek and the modified seek,
     rather than skipping straight to the fileMetadata matching the modified
     seek.
  3. Deciding how to seek the range-key iterator when switching to combined
     iteration is full of intricacies depending on the iterator operation
     and context.

The below benchmarks capture the performance improvement of avoiding the
range-key iterator construction when no range keys exist in the LSM. There
aren't yet suitable benchmarks for measuring the improvement in cases where
there exist range keys in the LSM, but the range keys are outside the keyspace
being iterated over.

```
name                                                    old time/op    new time/op    delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64-10         3.04µs ± 5%    2.62µs ± 5%  -13.69%  (p=0.000 n=9+10)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64-10       21.2µs ± 1%    20.7µs ± 1%   -2.74%  (p=0.000 n=9+10)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64-10     1.41ms ± 1%    1.36ms ± 1%   -3.10%  (p=0.000 n=9+10)
MVCCGet_Pebble/batch=false/versions=1/valueSize=8-10      3.02µs ± 2%    2.58µs ± 0%  -14.84%  (p=0.000 n=9+10)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8-10     3.48µs ± 2%    3.06µs ± 4%  -12.08%  (p=0.000 n=9+9)
MVCCGet_Pebble/batch=false/versions=100/valueSize=8-10    7.29µs ± 2%    6.93µs ±11%   -4.88%  (p=0.028 n=9+10)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8-10       1.59µs ± 1%    1.57µs ± 4%     ~     (p=0.128 n=9+10)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8-10      2.18µs ± 3%    2.18µs ± 6%     ~     (p=0.593 n=10+10)
MVCCGet_Pebble/batch=true/versions=100/valueSize=8-10     5.55µs ± 9%    5.17µs ± 1%   -6.95%  (p=0.000 n=10+9)

name                                                    old speed      new speed      delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64-10       21.1MB/s ± 5%  24.4MB/s ± 5%  +15.90%  (p=0.000 n=9+10)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64-10      301MB/s ± 1%   310MB/s ± 1%   +2.82%  (p=0.000 n=9+10)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64-10    454MB/s ± 1%   469MB/s ± 1%   +3.20%  (p=0.000 n=9+10)
MVCCGet_Pebble/batch=false/versions=1/valueSize=8-10    2.65MB/s ± 2%  3.11MB/s ± 1%  +17.44%  (p=0.000 n=9+10)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8-10   2.30MB/s ± 2%  2.62MB/s ± 4%  +13.86%  (p=0.000 n=9+9)
MVCCGet_Pebble/batch=false/versions=100/valueSize=8-10  1.10MB/s ± 1%  1.16MB/s ±10%   +5.66%  (p=0.031 n=8+10)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8-10     5.04MB/s ± 1%  5.10MB/s ± 4%     ~     (p=0.127 n=9+10)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8-10    3.68MB/s ± 3%  3.68MB/s ± 6%     ~     (p=0.589 n=10+10)
MVCCGet_Pebble/batch=true/versions=100/valueSize=8-10   1.44MB/s ± 9%  1.54MB/s ± 2%   +7.00%  (p=0.000 n=10+10)
```

Close https://github.com/cockroachdb/pebble/issues/1780.

2022-06-28 21:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1791)
<!-- Reviewable:end -->

2022-06-29 09:58 UTC, erikgrinaker commented
Love the speedups, but share your hesitation about the complexity. Is it possible to constrain this e.g. by introducing new abstraction layers?

We also need to be careful that we don't fall off a performance cliff when range keys do show up (initially due to import rollbacks). We haven't done any benchmarking of this case yet, but my sense is that it's going to be pretty severe at current, so we're likely going to have to do a substantial amount of optimization for this case as well. Are there other alternatives to make combined iterator construction cheaper? Do you think it's worthwhile to eat this complexity cost regardless, or should we explore other options first?

2022-06-29 14:00 UTC, jbowens commented
The iterator construction code path is already very minimal, at least in the case with no range keys in the LSM.

I haven't been able to think of any viable alternatives—I experimented with an alternative that cached `Iterator`s when `Close`d so that they can be reused on `NewIter`. That approach brought its own host of complexities and had a lessor (~5%) impact on the benchmarks. It could probably be optimized further, maybe with lock-free synchronization, but it brings its own challenges. I also think the caching approach would become less effective with higher compaction concurrency settings, at least without additional complexity of its own.

I'm leaning towards eating the complexity regardless, but I would like to spend more time trying to pare down its complexity, especially after spending some time away from the problem.

I think the biggest reason to go this route is that I expect it will help significantly in the case that the LSM contains range keys, but those range keys are in a part of the keyspace untouched by the iterator. Currently, I expect each LSM level containing a range key will have a significant impact on performance: It'll introduce key comparisons per-level per-seek. There are probably optimizations that can help mitigate this impact on repeated seeks in the same part of the keyspace, but even then the impact on the first seek will be significant.

2022-06-29 14:10 UTC, erikgrinaker commented
Makes sense. We could possibly be more aggressive about iterator reuse in CRDB too, could be worth pooling and reconfiguring them rather than cloning -- at least on the read path. Will give it a spin when I get back to optimization work.

2022-07-20 14:55 UTC, jbowens reviewed
Note to self to account for external iterators, which cannot use lazy-combined iteration because they do not use `levelIter`s.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1791#-:-N7R5ckA6MQwIIGkoY5y:b-6z4m3)* status: 0 of 37 files reviewed, all discussions resolved (waiting on @erikgrinaker, @itsbilal, @nicktrav, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-07-20 22:25 UTC, nicktrav approved these changes
Apologies for the delay in reviewing, and thanks for persevering with this rework!

> I'm leaning towards eating the complexity regardless, but I would like to spend more time trying to pare down its complexity, especially after spending some time away from the problem.

Inclined to agree here. We have something that's directionally correct. Perhaps after some time away from the problem we can revisit and optimize further - like we did for the fragmenting iter stack. That said, I can't really offer any alternatives.

Going to add my <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> as a `+1`, but you probably want at least a `+2`.

> Reviewed 5 of 29 files at r1, 32 of 32 files at r4, 23 of 23 files at r5, 14 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1791#-:-N7Sg1-D-DH2ErV2-LGT:b8ai8xq)* status: all files reviewed, 5 unresolved discussions (waiting on @erikgrinaker, @itsbilal, @jbowens, and @sumeerbhola)

___
*[`range_keys.go` line 103 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7SXGSABDOMKSOegWK5:-N7SXGSABDOMKSOegWK6:b-f134mj) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/range_keys.go#L103)):*
> ```Go
> // observed.
> type combinedIterState struct {
> 	key         []byte
> ```

nit: could this be called `rangeKey` to indicate that it always stores a range key copy. It wasn't clear from the callsites that this would always be a range key, yet it's used as if it's a range key.
___
*[`range_keys.go` line 116 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7STjXZ83y0r-KA2cdy:-N7STjXZ83y0r-KA2cdz:b65aph4) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/range_keys.go#L116)):*
> ```Go
> 	dir int8, pointKey *InternalKey, pointValue []byte, seekKey []byte,
> ) (*InternalKey, []byte) {
> 	// Invariant: i.rangeKey is nil.
> ```

Worth some gated invariant checks?
___
*[`range_keys.go` line 167 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7SY7Iy26-vazjjiL41:-N7SY7Iy26-vazjjiL42:b-sbwmv5) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/range_keys.go#L167)):*
> ```Go
> 		// key instead to `bar`. It is guaranteed that no range key exists
> 		// earlier than `bar`, otherwise a levelIter would've observed it and
> 		// set `combinedIterState.key` to its start key.
> ```

In other words, we're setting `seekKey = min(pointKey, combinedIterState.key)` to avoid skipping a point key, if one is present? Wonder if you could add that as a sentence at the end.
___
*[`range_keys.go` line 186 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7SYpoi2Ue50c5MUIri:-N7SYpoi2Ue50c5MUIrj:bzbz30m) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/range_keys.go#L186)):*
> ```Go
> 	// iterator.
> 	if dir == +1 {
> 		return i.parent.rangeKey.iiter.InitSeekGE(seekKey, pointKey, pointValue)
> ```

Treat this as UX nitpick (applying to a previous patch). I found the `rangeKey` field to be a little confusing. Rather than being a range key _iterator_, it's the _state_ associated with (possibly) interleaved iteration. Indeed, the type is `iteratorRangeKeyState`. Perhaps we could `s/rangeKey/rangeKeyState` (in a follow up)?

This would then make it clearer in these long, chained operations that we're referring to an "interleaving iterator in the parent's (combined) range key iteration state" (a mouthful).
___
*[`internal/base/iterator.go` line 197 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7SK8NcB3gkOgOLzzjf:-N7SK8NcB3gkOgOLzzjg:b-qpj5e7) ([raw file](https://github.com/cockroachdb/pebble/blob/ae39974228fcaa83a0253ffd11c66d81789635d4/internal/base/iterator.go#L197)):*
> ```Go
> const SeekGEFlagsNone = SeekGEFlags(0)
> 
> // TrySeekUsingNext indicates whether a a performance optimization was enabled
> ```

nit: s/a a/a/


<!-- Sent from Reviewable.io -->

2022-07-21 02:11 UTC, sumeerbhola reviewed
I have some high level questions:
- What aspect of iterator construction is showing up as a cost in the profiles, that motivated this change? I presume it is not just allocations since hopefully we could avoid that via reuse.
- Are we seeing iterator construction to be important in MVCCScan_Pebble because `runMVCCScan` used `Pebble` as a reader and not `pebbleReadOnly`, so there is no iterator reuse? What happens in the benchmark if we switch to `pebbleReadOnly`? Is the cost of seeking and iteration also higher with the eagerly constructed combined iterator?
- Does this change cause any performance improvement for tpcc or kv95? I believe those tend to have `BatchRequests` with a single request, so iterator reuse is not possible. I am curious because if those challenging cases don't show an improvement, this optimization may not be necessary.

In general I find our iterator stack to be close to the bounds of comprehensibility (I realize I am also to blame for that state of affairs :), so I am eager to avoid more complexities.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1791#-:-N7TT87w91B7Y6Mpx62c:b-y3m1qn)* status: all files reviewed, 5 unresolved discussions (waiting on @erikgrinaker, @itsbilal, and @jbowens)



<!-- Sent from Reviewable.io -->

2022-07-21 09:58 UTC, erikgrinaker commented
>Does this change cause any performance improvement for tpcc or kv95?

I did a couple of quick three-minute `kv95/enc=false/nodes=3/cpu=32` runs with this against `master`, showed a ~3% improvement. That recovers about half of the 7% regression we have since 22.1. I agree that the complexity is unfortunate, but at the same time, we need to claw back most of those 7%.

2022-07-21 14:09 UTC, jbowens reviewed
> What aspect of iterator construction is showing up as a cost in the profiles, that motivated this change? I presume it is not just allocations since hopefully we could avoid that via reuse.

Yeah, the allocations are already prevented through pooling and bundling into a single 'iterator range-key state' struct. The initialization of the various internal iterators (which is really just struct initialization, eg, copying fields) shows up. During seeks, the overhead of just descending the range-key iterator stack to observe that nothing is there also shows up. And when closing an iterator, zeroing out and returning the `iteratorRangeKeyState` struct to the pool shows up.

This is all without any range keys existing anywhere in the LSM. I haven't done benchmarking of the performance when there exist range keys in the LSM but not in the key space of iteration, but I imagine it's an additional drop-off since it requires seeking each level within the `LevelMetadata`, initializing the `keyspan.MergingIter` heap and stepping it to find the correct span.

> What happens in the benchmark if we switch to pebbleReadOnly? Is the cost of seeking and iteration also higher with the eagerly constructed combined iterator?

I can try this today. Yeah, the cost of seeking specifically is higher with the combined iterator. Relative positioning does not seem to be more expensive, at least in the case where there are zero range keys in the LSM. Even with range keys in the LSM, I expect relative positioning to be okay, because typically we only need to perform a single additional key comparison to know that we're still within the current span.

> I am eager to avoid more complexities.

Yeah, I hear ya. I'm hopeful we'll be able to pare down the complexity with time. The complexity that bleeds into the `mergingIter` is to accommodate existing optimizations for range deletions (adjusting the seek key according to range-dels during lazy iteration would allow skipping range keys).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1791#-:-N7Vw4FaAT_jIeUaOE7v:bbzhclo)* status: all files reviewed, 5 unresolved discussions (waiting on @erikgrinaker, @itsbilal, and @jbowens)



<!-- Sent from Reviewable.io -->

2022-07-21 21:13 UTC, sumeerbhola requested changes
still reading

> Reviewed 5 of 29 files at r1, 32 of 32 files at r4, 23 of 23 files at r5, 7 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1791#-:-N7XauMF1qBUHtvkYC1l:bantulr)* status: all files reviewed, 7 unresolved discussions (waiting on @erikgrinaker, @itsbilal, and @jbowens)

___
*[`db.go` line 1002 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7XVqYM7nqXiW7-zU0K:-N7XVqYO6BdDYkTz87pT:buxmj5l) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/db.go#L1002)):*
> ```Go
> 			}
> 
> 			// Wrap an empty point iterator with an interleaving iterator that
> ```

why is it an "empty point iterator"?
___
*[`iterator.go` line 1978 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7X_G8o--zoA3AvL6eq:-N7X_G8o--zoA3AvL6er:b-i9v6ja) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/iterator.go#L1978)):*
> ```Go
> 				}
> 			}
> 			if i.rangeKey != nil && i.batch.countRangeKeys > 0 {
> ```

Does this need to change?
My understanding is that this lazy behavior may cause `i.rangeKey` to be nil, even though range key iteration is configured. In which case if the batch now has some range keys, we need to initialize the range key iterator stack. Am I missing something?
___
*[`sstable/reader.go` line 757 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7XOrwJ1UmRQtCAGnLQ:-N7XOrwJ1UmRQtCAGnLR:b-yrgqpb) ([raw file](https://github.com/cockroachdb/pebble/blob/ae39974228fcaa83a0253ffd11c66d81789635d4/sstable/reader.go#L757)):*
> ```Go
> 		i.maybeFilteredKeysSingleLevel = false
> 		var ikey *InternalKey
> 		if ikey, _ = i.index.SeekGE(key, base.SeekGEFlagsNone); ikey == nil {
> ```

btw, I did not look very carefully to see that the numerous plumbing changes in this commit correctly make a choice between using `base.SeekGEFlagsNone` versus switching what was received in a `flags` parameter by doing `flags.DisableTrySeekUsingNext()`. It won't cause a problem now because there is only one bit of useful information in these flags, but could in the future, by not propagating something else that was in the `flags` parameter.


<!-- Sent from Reviewable.io -->

2022-07-22 14:09 UTC, sumeerbhola requested changes
> Reviewed 4 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1791)* status: all files reviewed, 17 unresolved discussions (waiting on @erikgrinaker, @itsbilal, and @jbowens)

___
*[`level_iter.go` line 272 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7_zzGW42C0CUpEWncy:-N7_zzGW42C0CUpEWncz:b8vt2u1) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/level_iter.go#L272)):*
> ```Go
> 				l.combinedIterState.key = append(l.combinedIterState.key[:0], file.SmallestRangeKey.UserKey...)
> 			} else if l.cmp(l.combinedIterState.key, file.SmallestRangeKey.UserKey) > 0 {
> 				l.combinedIterState.key = append(l.combinedIterState.key[:0], file.SmallestRangeKey.UserKey...)
> ```

this is a bit peculiar and initially seems inefficient, in that we will keep comparing and copying keys even though triggered is true. Though I see why it is not inefficient, it can use a code comment
IIUC, we may start with combinedIterState.{initialized,triggered}=false. The triggered false=>true transition can happen for many levelIters at the same positioning call, though of course it will happen sequentially since the iterator stack is single threaded. The first levelIter will cause triggered false=>true transition, since that is what is observed to decide to do the initialization. But there may be other levelIters who must also accumulate their key information if initialization has not happened, so we fall into this key comparison path. Once initialized transitions to true we know that no one is observing these keys anymore, so all of this is elided. 
___
*[`level_iter.go` line 310 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7a5fjtBToHhSW-fcGx:-N7a5fjtBToHhSW-fcGy:b-aryjeq) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/level_iter.go#L310)):*
> ```Go
> 	for m != nil {
> 		if m.HasRangeKeys {
> 			l.maybeTriggerCombinedIteration(m, +1)
> ```

if `maybeTriggerCombinedIteration` returned a bool indicating when it had triggered, we could use a true value to seek if we have not yet reached the seek position.
Fine for it to be a TODO for later.
___
*[`level_iter.go` line 315 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7a2nXC4QJLW5GVh4y1:-N7a2nXC4QJLW5GVh4y2:bs92pxf) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/level_iter.go#L315)):*
> ```Go
> 			// that contains range keys ≥ key but no point keys ≥ key, in which
> 			// case we must next to find the first file containing a point key
> 			// greater than or equal to key.
> ```

what if this file has a range tombstone only?
If think we need a comment at `HasPointKeys` stating that it is true even if there are only range tombstones (I see `ExtendPointKeyBounds` being called with range tombstones), and a comment here also clarifying that.
___
*[`level_iter.go` line 334 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7a4_7u1s7ltF_GxaZ4:-N7a4_7u1s7ltF_GxaZ5:bg1opqe) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/level_iter.go#L334)):*
> ```Go
> 		// for correctness by mergingIter.SeekGE (see the comment in that
> 		// function).
> 		if m.LargestPointKey.IsExclusiveSentinel() && l.cmp(m.LargestPointKey.UserKey, key) == 0 {
> ```

aside: should we do an audit of all `cmp(...) == 0` code in Pebble and plumb `Equal` into these places, for efficiency?
There seem to be ~20 such places.
___
*[`level_iter.go` line 344 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7a6XLcDnw9AkLz0d69:-N7a6XLcDnw9AkLz0d6A:b-g05nyx) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/level_iter.go#L344)):*
> ```Go
> 			m = l.files.Next()
> 			continue
> 		}
> ```

This loop is a bit hard to follow: we have a number of `l.cmp(m.LargestPointKey.UserKey, key)` calls and continue calls, and the ordering is subtle. The following seems simpler to me. It incurs an unnecessary comparison when we are before the seek pos and `!m.HasPointKeys()`, but I think that case should be rare enough.


```
doSeek := func() {
  m = l.files.SeekGE(l.cmp, key)
  if m.LargestPointKey.IsExclusiveSentinel() && l.cmp(m.LargestPointKey.UserKey, key) == 0 {
    m = l.files.Next()
  }
}
pastSeekPos := false
if !nextInsteadOfSeek {
   doSeek()
   pastSeekPos = true
}
triggered := false
for m != nil {
  // If haven't triggered, try to trigger.
  if !triggered && m.HasRangeKeys {
    triggered = l.maybeTriggerCombinedIteration(m, +1)
    if triggered && !pastSeekPos {
      // Seek
      doSeek()
      pastSeekPos = true
      continue
    }
  }
  if !pastSeekPos {
     cmp := l.cmp(m.LargestPointKey.UserKey, key)
     if cmp < 0 || (cmp == 0 && !m.LargestPointKey.IsExclusiveSentinel()) {
       pastSeekPos = true
     }
  }
  if pastSeekPos && m.HasPointKeys {
    break
  }
  m = l.files.Next()
}

```
___
*[`level_iter.go` line 460 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7a155S8wBSR3LR-1-c:-N7a155S8wBSR3LR-1-d:bvfo1zb) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/level_iter.go#L460)):*
> ```Go
> 			}
> 
> 			l.maybeTriggerCombinedIteration(file, dir)
> ```

I can't remember the list of cases where we are already positioned at the correct file, so being defensive and calling `maybeTriggerCombinedIteration` sounds good to me. But is there a case you know of where we wouldn't have already triggered combined iteration if this file had a range key? Is it one of those SetOptions cases where we have switched from only point iteration to point-and-range iteration and left the point iter at its original position? If you know of one/many, or if this is just defensive, it could use a code comment.
___
*[`merging_iter.go` line 909 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7_ytqS-tT8MHhbqxLe:-N7_ytqS-tT8MHhbqxLf:b-eig177) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/merging_iter.go#L909)):*
> ```Go
> 		// TODO(jackson): We could preserve this optimization here and in seekLT
> 		// if we instead explicitly checked for the existence of any files
> 		// within this level contain range keys overlapping the span [key,
> ```

wouldn't it be existence of any files at all levels below this level? since that's where this seek is going to apply.
___
*[`range_keys.go` line 96 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7_rt9w7YXFr0SeIS4e:-N7_rt9xBLks5WBtUXJG:b-rp9sl3) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/range_keys.go#L96)):*
> ```Go
> // Various low-level iterators (mergingIter, leveliter) hold pointers to the
> // *pebble.Iterator's combinedIterState. This allows them to check whether or
> // not they must monitor for files containing range keys (!initialized), or not.
> ```

The phrasing suggests both levelIter and mergingIter need to monitor for files containing range keys -- isn't it sufficient for levelIter to do such monitoring?
___
*[`range_keys.go` line 112 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7_sr602l7wkLENB7IZ:-N7_sr602l7wkLENB7I_:b-c5hc2a) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/range_keys.go#L112)):*
> ```Go
> 
> // initCombinedIteration is invoked after a pointIter positioning operation
> // resulted in i.combinedIterState.triggered=true.
> ```

Can you add comments for each of these parameters. It isn't clear what `pointKey` and `seekKey` mean. And is the positioning operation always a seek? I presume not since normal steps could also cause file switching and cause triggered false=>true transition. Is seekKey nil in that case?
___
*[`range_keys.go` line 184 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7_vzj_3MK1tJE6Zh5t:-N7_vzj_3MK1tJE6Zh [...]

2022-07-22 19:06 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1791)* status: all files reviewed, 15 unresolved discussions (waiting on @erikgrinaker, @itsbilal, @nicktrav, and @sumeerbhola)

___
*[`db.go` line 1002 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7XVqYM7nqXiW7-zU0K:-N7aU6ab35-1iAsdxlgE:bj6ribc) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/db.go#L1002)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why is it an "empty point iterator"?
</blockquote></details>

Thanks, this was a stale comment from an earlier iteration. Done.
___
*[`iterator.go` line 1978 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7X_G8o--zoA3AvL6eq:-N7aXYPfDrtEpSKt6Sly:bfmflb5) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/iterator.go#L1978)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Does this need to change?
My understanding is that this lazy behavior may cause `i.rangeKey` to be nil, even though range key iteration is configured. In which case if the batch now has some range keys, we need to initialize the range key iterator stack. Am I missing something?
</blockquote></details>

This code path only is only possible for closing out the range-key iterator if it needs to be reconstructed. Since there is no range-key iterator yet, there's nothing to do here.

Down below when `i.rangeKey` is nil, range-key iteration is enabled and the batch is empty, we won't hit the no-op fast-path because of the new condition:
```
if i.rangeKey != nil || !i.opts.rangeKeys() || i.batch == nil || i.batch.countRangeKeys == 0 {
	// Fast path. This preserves the Seek-using-Next optimizations as
	// long as the iterator wasn't already invalidated up above.
	return
}
```

And we'll fall through to reinitializing the iterator in `finishInitializingIter`, which will construct the range-key iterator stack.

Added some clarifying comments.
___
*[`level_iter.go` line 272 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7_zzGW42C0CUpEWncy:-N7abtd4EJUbdzHsdzOV:b-qfn0jf) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/level_iter.go#L272)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this is a bit peculiar and initially seems inefficient, in that we will keep comparing and copying keys even though triggered is true. Though I see why it is not inefficient, it can use a code comment
IIUC, we may start with combinedIterState.{initialized,triggered}=false. The triggered false=>true transition can happen for many levelIters at the same positioning call, though of course it will happen sequentially since the iterator stack is single threaded. The first levelIter will cause triggered false=>true transition, since that is what is observed to decide to do the initialization. But there may be other levelIters who must also accumulate their key information if initialization has not happened, so we fall into this key comparison path. Once initialized transitions to true we know that no one is observing these keys anymore, so all of this is elided. 
</blockquote></details>

added a comment. also, i realized that the key copying was unnecessary. we only ever store keys from `fileMetadata` bounds here, which are guaranteed to be heap allocated and stable.
___
*[`level_iter.go` line 310 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7a5fjtBToHhSW-fcGx:-N7aoQqr3LjR8MFnpyrD:b733kgd) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/level_iter.go#L310)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

if `maybeTriggerCombinedIteration` returned a bool indicating when it had triggered, we could use a true value to seek if we have not yet reached the seek position.
Fine for it to be a TODO for later.
</blockquote></details>

it's not clear to me if it's actually preferable to seek under this condition. if we're next-ing instead of seeking, it's because there's a range deletion. It would need to be a very broad tombstone to cover several files. also if it does cover several files, it should be very temporary because a delete-only compaction can delete those wholly covered files. this is probably something to consider once we have better benchmarks w/ rangedels (linking #1295)

an aside, after this is merged, I'd like to try setting `relativeSeek=true` when `TrySeekUsingNext=true`. I had a rough experiment that seemed to indicate it's a win for `CheckSSTCollisions`
___
*[`level_iter.go` line 315 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7a2nXC4QJLW5GVh4y1:-N7ahTmb4p7jHK0k79Iv:bb7f2mf) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/level_iter.go#L315)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what if this file has a range tombstone only?
If think we need a comment at `HasPointKeys` stating that it is true even if there are only range tombstones (I see `ExtendPointKeyBounds` being called with range tombstones), and a comment here also clarifying that.
</blockquote></details>

done
___
*[`level_iter.go` line 334 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7a4_7u1s7ltF_GxaZ4:-N7ag-NW8GBkYaV8uC0H:bef087e) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/level_iter.go#L334)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

aside: should we do an audit of all `cmp(...) == 0` code in Pebble and plumb `Equal` into these places, for efficiency?
There seem to be ~20 such places.
</blockquote></details>

good call, filed #1819
___
*[`level_iter.go` line 344 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7a6XLcDnw9AkLz0d69:-N7ai7NlDnD7UuEs0Q9J:b-7m1i9p) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/level_iter.go#L344)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This loop is a bit hard to follow: we have a number of `l.cmp(m.LargestPointKey.UserKey, key)` calls and continue calls, and the ordering is subtle. The following seems simpler to me. It incurs an unnecessary comparison when we are before the seek pos and `!m.HasPointKeys()`, but I think that case should be rare enough.


```
doSeek := func() {
  m = l.files.SeekGE(l.cmp, key)
  if m.LargestPointKey.IsExclusiveSentinel() && l.cmp(m.LargestPointKey.UserKey, key) == 0 {
    m = l.files.Next()
  }
}
pastSeekPos := false
if !nextInsteadOfSeek {
   doSeek()
   pastSeekPos = true
}
triggered := false
for m != nil {
  // If haven't triggered, try to trigger.
  if !triggered && m.HasRangeKeys {
    triggered = l.maybeTriggerCombinedIteration(m, +1)
    if triggered && !pastSeekPos {
      // Seek
      doSeek()
      pastSeekPos = true
      continue
    }
  }
  if !pastSeekPos {
     cmp := l.cmp(m.LargestPointKey.UserKey, key)
     if cmp < 0 || (cmp == 0 && !m.LargestPointKey.IsExclusiveSentinel()) {
       pastSeekPos = true
     }
  }
  if pastSeekPos && m.HasPointKeys {
    break
  }
  m = l.files.Next()
}

```

</blockquote></details>

there's a bit of additional trickiness that we also need to check the file that we seek, eg `m = l.files.SeekGE(l.cmp, key)` for range keys and possibly trigger too. also, even if we seek we're not guaranteed that `pastSeekPos=true`, because `SeekGE` seeks according to the combined file bounds (eg, `Largest`,`Smallest` instead of `LargestPoint` and `SmallestPoint`)

I did a little additional reorganization and added clearer code comments here.
___
*[`level_iter.go` line 460 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7a155S8wBSR3LR-1-c:-N7awq8D3ydNXcu3Ed3e:b-1dffpv) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75 [...]

2022-07-22 19:46 UTC, jbowens reviewed
TFTRs! Going to merge to get some roachperf runs over the weekend.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1791#-:-N7bRVhiD4ZAHQS858Y9:b-gulrup)* status: 6 of 39 files reviewed, 15 unresolved discussions (waiting on @erikgrinaker, @itsbilal, @nicktrav, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-07-22 19:46 UTC, merged

2022-07-26 20:39 UTC, sumeerbhola reviewed
> Reviewed 1 of 23 files at r8, 6 of 16 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1791)* status: 13 of 39 files reviewed, 15 unresolved discussions

___
*[`level_iter.go` line 344 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7a6XLcDnw9AkLz0d69:-N7wCac_BwZDZ-wPnT6F:b4z1756) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/level_iter.go#L344)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

there's a bit of additional trickiness that we also need to check the file that we seek, eg `m = l.files.SeekGE(l.cmp, key)` for range keys and possibly trigger too. also, even if we seek we're not guaranteed that `pastSeekPos=true`, because `SeekGE` seeks according to the combined file bounds (eg, `Largest`,`Smallest` instead of `LargestPoint` and `SmallestPoint`)

I did a little additional reorganization and added clearer code comments here.
</blockquote></details>

Thanks, it is easier to follow now.
___
*[`range_keys.go` line 112 at r6](https://reviewable.io/reviews/cockroachdb/pebble/1791#-N7_sr602l7wkLENB7IZ:-N7wDj1J7Y2LLYmnPyNS:b-p3wv9e) ([raw file](https://github.com/cockroachdb/pebble/blob/a65e75e980a7b85b36aee74392e12b704aae86cf/range_keys.go#L112)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

done
</blockquote></details>

Much clearer - thanks.


<!-- Sent from Reviewable.io -->