db: add snapshot-pinned keys sstable properties and metrics
cockroachdb/pebble pull request #1814
Opened 2022-07-15 22:05 UTC by jbowens

Informs #1204.

2022-07-15 22:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1814)
<!-- Reviewable:end -->

2022-07-16 04:51 UTC, jbowens commented
I think a good next step after this PR would be to run some experiments that are known to incur high w-amp (@tbg might have something in mind?) and observe whether the LSM stats record significant pinned bytes.

2022-07-19 01:32 UTC, sumeerbhola requested changes
I haven't yet read `compactionIter` but flushing some minor comments (it looks good).

> Reviewed 3 of 24 files at r1, 1 of 5 files at r2, 1 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1814#-:-N7J422L014g9MEPjY7M:bkr79un)* status: 4 of 29 files reviewed, 5 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`compaction.go` line 2288 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N7IyLpe52zALRud4twu:-N7IyLpe52zALRud4twv:b-o37ccy) ([raw file](https://github.com/cockroachdb/pebble/blob/fb8d4fe6e9d8f6362eebf2cb32e58531583e09d9/compaction.go#L2288)):*
> ```Go
> 	}()
> 
> 	internalTableOptConstructor := private.SSTableInternalTableOpt.(func(func(p *sstable.Properties)) sstable.WriterOption)
> ```

I'm confused by the indirection happening here.
`private.SSTableInternalTableOpt` used to be an interface `sstable.WriterOption`. Is this change because it was too wide and gave access to the whole `Writer` when all we want is access to the `Properties`? So is this using something that takes a `func(*sstable.Properties)` and produces something that is a `sstable.WriterOption`.

So something like
```
type propertiesAdapter struct {
    f func(p *sstable.Properties)
}
func (p propertiesAdapter) writerApply(w *Writer) {
   f(w.props)
}
```

which could be used as
```
internalTableOpt := propertiesAdapter{
  f: func(p *sstable.Properties) {
     ...
  }
}
```
I guess I am confused about the casting starting with `private.SSTableInternalTableOpt`. And I never understood why `private.SSTableInternalOpt` is an `interface{}` and not the real type.
___
*[`compaction.go` line 2669 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N7J-xTC3QfQuCjIrc_e:-N7J-xTC3QfQuCjIrc_f:b-8baw9q) ([raw file](https://github.com/cockroachdb/pebble/blob/fb8d4fe6e9d8f6362eebf2cb32e58531583e09d9/compaction.go#L2669)):*
> ```Go
> 				// its elision. Increment the stats.
> 				pinnedCount++
> 				pinnedBytes += uint64(len(key.UserKey)) + base.InternalTrailerLen + uint64(len(val))
> ```

the bytes include the value, but the properties documentation says "cumulative bytes of keys". I guess it was meant to say "key-value pairs".
___
*[`db.go` line 423 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N7J3SB93GTcDK-aLpSY:-N7J3SB93GTcDK-aLpSZ:b-2nbf16) ([raw file](https://github.com/cockroachdb/pebble/blob/e0c7a267a4803bdb87279322966e59c1f7e16092/db.go#L423)):*
> ```Go
> 			// The cumulative count and size of snapshot-pinned keys written to
> 			// sstables.
> 			cumulativePinnedCount uint64
> ```

I assume the idea is to compare it with the cumulative number of bytes being written in compactions.

Is there a value to knowing how many of the bytes currently in the DB are pinned? It would mean reading the properties (in the background) after the DB is opened, so I guess we can wait until we think it is worth the trouble.
___
*[`sstable/properties.go` line 144 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N7IsGyD1e1dpwVCuJEx:-N7IsGyF25Ijuw518P1I:b-i5m91p) ([raw file](https://github.com/cockroachdb/pebble/blob/fb8d4fe6e9d8f6362eebf2cb32e58531583e09d9/sstable/properties.go#L144)):*
> ```Go
> 	SnapshotPinnedKeys uint64 `prop:"pebble.num.snapshot-pinned-keys"`
> 	// The cumulative bytes of keys in this table that were pinned by open
> 	// snapshots.
> ```

Is this comparable to `RawKeySize`? If yes, can you add a comment.

Also, how about calling this `SnapshotPinnedKeySize` and also having `SnapshotPinnedValueSize` that would be comparable to `RawValueSize`?
___
*[`sstable/writer.go` line 1893 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N7J1Dy65UnCZlc522DM:-N7J1Dy65UnCZlc522DN:b-1pww2s) ([raw file](https://github.com/cockroachdb/pebble/blob/fb8d4fe6e9d8f6362eebf2cb32e58531583e09d9/sstable/writer.go#L1893)):*
> ```Go
> 
> // Apply this option during Close.
> func (i internalTableOpt) postApply() {}
> ```

when does `writerApply` get applied? And is `postApply` part of an interface?

Oh, I see -- `postApply` is just a marker saying when `writerApply` should be called, yes?
This could use some code commentary.


<!-- Sent from Reviewable.io -->

2022-07-28 22:48 UTC, nicktrav approved these changes
Nice! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 24 of 24 files at r1, 5 of 5 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1814#-:-N85zdKbEawYaIHb4lDp:bfd61qr)* status: all files reviewed, 8 unresolved discussions (waiting on @jbowens)

___
*[`internal/keyspan/fragmenter.go` line 238 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N85u2x47Dont5XOB8A1:-N85u2x47Dont5XOB8A2:bowrpfz) ([raw file](https://github.com/cockroachdb/pebble/blob/fb8d4fe6e9d8f6362eebf2cb32e58531583e09d9/internal/keyspan/fragmenter.go#L238)):*
> ```Go
> 	// CoversInvisibly indicates the tested key does fall within the span's
> 	// bounds and the span contains at least one key with a higher sequence
> 	// number, but none visible at the provided snapshot.
> ```

Some diagrams might be useful for these types, demonstrating "visible" and "invisible".
___
*[`internal/keyspan/testdata/fragmenter_covers` line 1 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N85yVij0KDdKnBAEYaR:-N85yVij0KDdKnBAEYaS:be9uam5) ([raw file](https://github.com/cockroachdb/pebble/blob/fb8d4fe6e9d8f6362eebf2cb32e58531583e09d9/internal/keyspan/testdata/fragmenter_covers#L1)):*
> ```
> build
> ```

Without reading the test code directly, it's a little hard to decipher how this test works. Can you add a brief description?


<!-- Sent from Reviewable.io -->

2022-08-02 20:59 UTC, nicktrav reviewed
> Reviewed 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1814)* status: all files reviewed, 8 unresolved discussions (waiting on @jbowens)



<!-- Sent from Reviewable.io -->

2023-03-21 19:12 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1814)* status: 1 of 29 files reviewed, 6 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[`compaction.go` line 2288 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N7IyLpe52zALRud4twu:-NC1pa558etcxQdiaNH5:b8nelth) ([raw file](https://github.com/cockroachdb/pebble/blob/fb8d4fe6e9d8f6362eebf2cb32e58531583e09d9/compaction.go#L2288)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm confused by the indirection happening here.
`private.SSTableInternalTableOpt` used to be an interface `sstable.WriterOption`. Is this change because it was too wide and gave access to the whole `Writer` when all we want is access to the `Properties`? So is this using something that takes a `func(*sstable.Properties)` and produces something that is a `sstable.WriterOption`.

So something like
```
type propertiesAdapter struct {
    f func(p *sstable.Properties)
}
func (p propertiesAdapter) writerApply(w *Writer) {
   f(w.props)
}
```

which could be used as
```
internalTableOpt := propertiesAdapter{
  f: func(p *sstable.Properties) {
     ...
  }
}
```
I guess I am confused about the casting starting with `private.SSTableInternalTableOpt`. And I never understood why `private.SSTableInternalOpt` is an `interface{}` and not the real type.
</blockquote></details>

I think `private.SSTableInternalTableOpt` is an `interface{}` to avoid a cyclical package dependency.
___
*[`compaction.go` line 2669 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N7J-xTC3QfQuCjIrc_e:-N8A2qhF7tgzFZiHb_cY:bnxplms) ([raw file](https://github.com/cockroachdb/pebble/blob/fb8d4fe6e9d8f6362eebf2cb32e58531583e09d9/compaction.go#L2669)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the bytes include the value, but the properties documentation says "cumulative bytes of keys". I guess it was meant to say "key-value pairs".
</blockquote></details>

thanks, done by splitting this into two properties.
___
*[`db.go` line 423 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N7J3SB93GTcDK-aLpSY:-N8A30Ob-ygs5N8uf3h_:b-i67rhp) ([raw file](https://github.com/cockroachdb/pebble/blob/e0c7a267a4803bdb87279322966e59c1f7e16092/db.go#L423)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I assume the idea is to compare it with the cumulative number of bytes being written in compactions.

Is there a value to knowing how many of the bytes currently in the DB are pinned? It would mean reading the properties (in the background) after the DB is opened, so I guess we can wait until we think it is worth the trouble.
</blockquote></details>

yeah, I think there's some value, especially for just getting a sense of how much space amplification results from snapshots under workloads. for our own internal use, we can use the `cockroach debug pebble db properties` command to aggregate all the sstables' props 
___
*[`sstable/properties.go` line 144 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N7IsGyD1e1dpwVCuJEx:-N8A5hQP6iLQugQwg3Pu:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/fb8d4fe6e9d8f6362eebf2cb32e58531583e09d9/sstable/properties.go#L144)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this comparable to `RawKeySize`? If yes, can you add a comment.

Also, how about calling this `SnapshotPinnedKeySize` and also having `SnapshotPinnedValueSize` that would be comparable to `RawValueSize`?
</blockquote></details>

Done.
___
*[`sstable/writer.go` line 1893 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N7J1Dy65UnCZlc522DM:-N8AeC7a6cpTVh1ipIGk:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/fb8d4fe6e9d8f6362eebf2cb32e58531583e09d9/sstable/writer.go#L1893)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

when does `writerApply` get applied? And is `postApply` part of an interface?

Oh, I see -- `postApply` is just a marker saying when `writerApply` should be called, yes?
This could use some code commentary.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-21 19:12 UTC, jbowens commented
Resurrecting this one for fixit week.

2023-03-21 21:33 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1814)* status: 1 of 29 files reviewed, 6 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[`compaction_iter.go` line 301 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N7LeImn1LkGjMc_LspF:-NR54j9x2VDpVflugvQq:b-86mr6o) ([raw file](https://github.com/cockroachdb/pebble/blob/e0c7a267a4803bdb87279322966e59c1f7e16092/compaction_iter.go#L301)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The preceding call to `nextInStripe` can return due to `sameStripeNonSkippable` while leaving `i.skip=true`. So we may be still in the same snapshot stripe.
I am trying to find that case in the following comment.

Should we store the `stripeChangeType` returned by `nextInStripe` etc. and split the `newStripe` case into `newStripeSameKey` and `newStripeDifferentKey`, and use the former to decide that pinned is true. That will allow us to leverage the current behavior of `i.skip` which stays true even with intermediate `sameStripeNonSkippable`.

I think what you have here is logically similar, so this may be subjective.


</blockquote></details>

I like it, done.


<!-- Sent from Reviewable.io -->

2023-03-23 18:30 UTC, bananabrick reviewed
Looking good. Have some clarifying questions/nits.

> Reviewed 2 of 21 files at r5, 1 of 1 files at r6, 16 of 24 files at r7, 1 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1814#-:-NREj1imBq33Db0bnwRx:bwzquvr)* status: 21 of 29 files reviewed, 18 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[`compaction.go` line 2761 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NR9kfrB-A9TsX-CYzzN:-NR9kfrB-A9TsX-CYzzO:b-wq2y43) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/compaction.go#L2761)):*
> ```Go
> 		// Set the external sst version to 0. This is what RocksDB expects for
> 		// db-internal sstables; otherwise, it could apply a global sequence number.
> 		p.ExternalFormatVersion = 0
> ```

I'm confused about `ExternalFormatVersion`. It's not being used by Pebble, is it used by Cockroach? `ExternalFormatVersion` is set to `rocksDBExternalFormatVersion` in `NewWriter` and then we set this to 0 during `Close`. Definitely confusing due to the multiple layers of indirection.

Could we directly set these in `finishOutput` before calling `Writer.Close`? 
___
*[`compaction_iter.go` line 324 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NREfuDT7dwndigXzCPM:-NREfuDT7dwndigXzCPN:b13cg9a) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/compaction_iter.go#L324)):*
> i.iterKey is the first of a new snapshot stripe.

Is this true? Can `iterStripeChange` not be `sameStripeSkippable` or `sameStripeNonSkippable`?
___
*[`compaction_iter.go` line 358 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NREYCyj0aaakAVOXLlu:-NREYCyj0aaakAVOXLlv:b-vnwk3w) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/compaction_iter.go#L358)):*
> ```Go
> 			// therefore warrants some investigation.
> 			i.saveKey()
> 			// TODO(jackson): Handle tracking pinned statistics for range keys
> ```

nit: It would be nice to update this todo to indicate what it would take to handle tracking pinned stats for range keys. It would allow someone else to pick up the todo and implement it in the future more easily.
___
*[`compaction_iter.go` line 415 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NREcLUMEEMLNrn_9hOO:-NREcLUMEEMLNrn_9hOP:b-bbkavl) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/compaction_iter.go#L415)):*
> ```Go
> 			// preserving the original value, and potentially mutating the key
> 			// kind.
> 			i.setNext()
> ```

Will the value of `snapshotPinned` stay the same after the call to `setNext` here? Or after the `mergeNext` call below?
___
*[`compaction_iter.go` line 518 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRB2sC5Bir7LuEWoKIc:-NRB2sC6-2an42JKHkOU:bc3e4eq) ([raw file](https://github.com/cockroachdb/pebble/blob/1e5ddd10389e7d47635241f9eb20ff6a979a5d9d/compaction_iter.go#L518)):*
> ```Go
> // overwriting or mutating the saved key or value before they have been returned
> // to the caller of the exported function (i.e. the caller of Next, First, etc.)
> func (i *compactionIter) nextInStripe() stripeChangeType {
> ```

nit: We could write a comment that the caller must use the return type to update `i.iterStripeChange`. Or update `iterStripeChange` from within `nextInStripe` and also return stripeChangeType.
___
*[`metrics.go` line 482 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRA0pTJ1ub9iMf6t02T:-NRA0pTJ1ub9iMf6t02U:b-kxtsxq) ([raw file](https://github.com/cockroachdb/pebble/blob/1e5ddd10389e7d47635241f9eb20ff6a979a5d9d/metrics.go#L482)):*
> ```Go
> 	formatCacheMetrics(w, &m.BlockCache, "bcache")
> 	formatCacheMetrics(w, &m.TableCache, "tcache")
> 	w.Printf("  snaps %9d %7s %7d  (score == earliest seq num)\n",
> ```

Why remove this?
___
*[`sstable/properties.go` line 152 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRAFYmpDQKja74ldB9E:-NRAFYmpDQKja74ldB9F:b-xv0sp4) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/sstable/properties.go#L152)):*
> ```Go
> 	// The cumulative bytes of values in this table that were pinned by
> 	// open snapshots. This value is comparable to RawValueSize.
> 	SnapshotPinnedValueSize uint64 `prop:"pebble.raw.snapshot-pinned-values"`
> ```

nit: I think we don't need the `raw` in the tags for the fields here.
___
*[`sstable/properties.go` line 371 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRAFipk9xw5m1NBty_A:-NRAFipk9xw5m1NBty_B:b-2g3b3z) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/sstable/properties.go#L371)):*
> ```Go
> 		p.saveString(m, unsafe.Offsetof(p.PropertyCollectorNames), p.PropertyCollectorNames)
> 	}
> 	if p.SnapshotPinnedKeys > 0 {
> ```

Does writing these change the on disk format of the sstables? Would we require version gating for older versions of Pebble which try and read this kind of sstable?
___
*[`internal/keyspan/testdata/fragmenter_covers` line 1 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRAljHX--gOoeE6lZYx:-NRAljHX--gOoeE6lZYy:b-npf7hm) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/internal/keyspan/testdata/fragmenter_covers#L1)):*
> ```
> # This datadriven test uses a single command 'build' that illustrates a sequence
> ```

I like this test. It's pretty thorough.
___
*[`internal/keyspan/testdata/fragmenter_covers` line 5 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRAfSRN7HJXzikHz0_f:-NRAfSRN7HJXzikHz0_g:b-ith0eo) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/internal/keyspan/testdata/fragmenter_covers#L5)):*
> ```
> #
> # 'add' lines add a new span with the provided sequence number and the provided
> # bounds.
> ```

We should add a line that there is no output line associated with the `add` command.
___
*[`internal/keyspan/testdata/fragmenter_covers` line 12 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRAa_95AY9zK0iygCcx:-NRAa_95AY9zK0iygCcy:bphri5y) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/internal/keyspan/testdata/fragmenter_covers#L12)):*
> ```
> build
> deleted a.SET.0     5
> add 3: a-----------m
> ```

nit: How about `addedSpan` instead of `add`? It clarifies what's going on in the test.
___
*[`range_del_test.go` line 427 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRArmCpATMCwNWlZPvW:-NRArmCpATMCwNWlZPvX:bhcidac) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/range_del_test.go#L427)):*
> ```Go
> 		FS: vfs.NewMem(),
> 		Levels: []LevelOptions{
> 			{TargetFileSize: 200},
> ```

Is this because the properties increase the size of the sstable?


<!-- Sent from Reviewable.io -->

2023-03-23 21:54 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1814)* status: 21 of 29 files reviewed, 15 unresolved discussions (waiting on @bananabrick, @nicktrav, and @sumeerbhola)

___
*[`compaction.go` line 2761 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NR9kfrB-A9TsX-CYzzN:-NRF5ApJEMi8TRpmpO_w:bxjd3gm) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/compaction.go#L2761)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I'm confused about `ExternalFormatVersion`. It's not being used by Pebble, is it used by Cockroach? `ExternalFormatVersion` is set to `rocksDBExternalFormatVersion` in `NewWriter` and then we set this to 0 during `Close`. Definitely confusing due to the multiple layers of indirection.

Could we directly set these in `finishOutput` before calling `Writer.Close`? 
</blockquote></details>

We don't use it. It exists only for compatibility with RocksDB (which the MostCompatible format major version still supports). It's set to `rocksDBExternalFormatVersion` so that non-internal constructors of sstables set `rocksDBExternalFormatVersion`.

The existing indirection and private hook exist to ensure that it's not possible for external users of  the `sstable` package to fiddle with the standard sstable properties, but Pebble itself is allowed to manipulate them appropriately.
___
*[`compaction_iter.go` line 324 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NREfuDT7dwndigXzCPM:-NRFN2na9ACiiUZi3qgB:b-a48iy8) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/compaction_iter.go#L324)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

> i.iterKey is the first of a new snapshot stripe.

Is this true? Can `iterStripeChange` not be `sameStripeSkippable` or `sameStripeNonSkippable`?
</blockquote></details>

this was poorly worded; updated
___
*[`compaction_iter.go` line 415 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NREcLUMEEMLNrn_9hOO:-NRFNGp264s5Zu0uFseq:besecjz) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/compaction_iter.go#L415)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Will the value of `snapshotPinned` stay the same after the call to `setNext` here? Or after the `mergeNext` call below?
</blockquote></details>

Yeah. Both of these cases return one key to represent the snapshot stripe. `setNext` and `mergeNext` determine the value of the resulting key-value pair, but it's still representing a snapshot stripe that's not the first.
___
*[`compaction_iter.go` line 518 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRB2sC5Bir7LuEWoKIc:-NRFP9smBrF5PWWETYA9:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/1e5ddd10389e7d47635241f9eb20ff6a979a5d9d/compaction_iter.go#L518)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: We could write a comment that the caller must use the return type to update `i.iterStripeChange`. Or update `iterStripeChange` from within `nextInStripe` and also return stripeChangeType.
</blockquote></details>

Done.
___
*[`metrics.go` line 482 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRA0pTJ1ub9iMf6t02T:-NRFQYbL4miz11941TPl:bqmzm0) ([raw file](https://github.com/cockroachdb/pebble/blob/1e5ddd10389e7d47635241f9eb20ff6a979a5d9d/metrics.go#L482)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Why remove this?
</blockquote></details>

thanks, this was a mistake during rebasing
___
*[`sstable/properties.go` line 152 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRAFYmpDQKja74ldB9E:-NRFQeLJ8J4T07pzCHKD:bbubpnf) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/sstable/properties.go#L152)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: I think we don't need the `raw` in the tags for the fields here.
</blockquote></details>

The `raw` is to match `rocksdb.raw.[range-key.]{key,value}.size` properties.
___
*[`sstable/properties.go` line 371 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRAFipk9xw5m1NBty_A:-NRFR-417aD4i1OP8i-a:b-vi1kv3) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/sstable/properties.go#L371)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Does writing these change the on disk format of the sstables? Would we require version gating for older versions of Pebble which try and read this kind of sstable?
</blockquote></details>

no — the properties block is just a block where the key is the property name (eg, `pebble.raw.snapshot-pinned-keys`). At read time, if the property is unrecognized, it's loaded into the `UserProperties` map.
___
*[`internal/keyspan/testdata/fragmenter_covers` line 5 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRAfSRN7HJXzikHz0_f:-NRFRyR4E7z3o1yTT3S8:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/internal/keyspan/testdata/fragmenter_covers#L5)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

We should add a line that there is no output line associated with the `add` command.
</blockquote></details>

Done.
___
*[`range_del_test.go` line 427 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRArmCpATMCwNWlZPvW:-NRFSVUJ8a7xIHSNvNYg:bb77u1k) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/range_del_test.go#L427)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Is this because the properties increase the size of the sstable?
</blockquote></details>

Yeah


<!-- Sent from Reviewable.io -->

2023-03-24 17:52 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1814)* status: 14 of 30 files reviewed, 15 unresolved discussions (waiting on @bananabrick, @nicktrav, and @sumeerbhola)

___
*[`compaction.go` line 2288 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1814#-N7IyLpe52zALRud4twu:-NRJjXw--Ej85L9xFUmw:b-x6rsy2) ([raw file](https://github.com/cockroachdb/pebble/blob/fb8d4fe6e9d8f6362eebf2cb32e58531583e09d9/compaction.go#L2288)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think `private.SSTableInternalTableOpt` is an `interface{}` to avoid a cyclical package dependency.
</blockquote></details>

I updated this interface boundary to be a little more direct (and remove the `postApply` marker)
___
*[`compaction.go` line 2761 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NR9kfrB-A9TsX-CYzzN:-NRJjRkXDW9NDWvV9ReN:b-3sdswx) ([raw file](https://github.com/cockroachdb/pebble/blob/c92b5ebb564b44b17d67e312fa0fc283ff7fc2e2/compaction.go#L2761)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

We don't use it. It exists only for compatibility with RocksDB (which the MostCompatible format major version still supports). It's set to `rocksDBExternalFormatVersion` so that non-internal constructors of sstables set `rocksDBExternalFormatVersion`.

The existing indirection and private hook exist to ensure that it's not possible for external users of  the `sstable` package to fiddle with the standard sstable properties, but Pebble itself is allowed to manipulate them appropriately.
</blockquote></details>

I updated this interface boundary to be a little more direct.


<!-- Sent from Reviewable.io -->

2023-03-30 15:01 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 24 files at r1, 2 of 21 files at r5, 12 of 24 files at r7, 1 of 3 files at r8, 8 of 11 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1814#-:-NRn1ODi9WcegIy24wRE:bg7igkv)* status: 25 of 30 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @jbowens, and @nicktrav)

___
*[`compaction_iter.go` line 390 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRmqAbQ--bzj2eKYnIu:-NRmqAbQ--bzj2eKYnIv:baq6u7m) ([raw file](https://github.com/cockroachdb/pebble/blob/2a29376f16c357437cd0fbde221be5a5a43ac0aa/compaction_iter.go#L390)):*
> ```Go
> 		switch i.iterKey.Kind() {
> 		case InternalKeyKindDelete, InternalKeyKindSingleDelete:
> 			if i.elideTombstone(i.iterKey.UserKey) {
> ```

we are always calling `elideTombstone` now, which involves a key comparison, while earlier it was only happening if `i.curSnapshotIdx == 0`. Is this not a performance concern because the common case in CockroachDB will be `i.curSnapshotIdx == 0` (since snapshots are rare)?
___
*[`compaction_iter.go` line 537 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRmo9ep5-TsPa33YV3n:-NRmo9ep5-TsPa33YV3o:b-fh6ay) ([raw file](https://github.com/cockroachdb/pebble/blob/2a29376f16c357437cd0fbde221be5a5a43ac0aa/compaction_iter.go#L537)):*
> ```Go
> // stripeChangeType indicates how the snapshot stripe changed relative to the previous
> // key. If no change, it also indicates whether the current entry is skippable.
> // If there snapshot changed, it also indicates whether the new stripe was
> ```

nit: if the ...
___
*[`metrics.go` line 236 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRmtlW11WC5kcO6oMNi:-NRmtlW11WC5kcO6oMNj:bfqir65) ([raw file](https://github.com/cockroachdb/pebble/blob/2a29376f16c357437cd0fbde221be5a5a43ac0aa/metrics.go#L236)):*
> ```Go
> 		// sstables during flushes or compactions that would've been elided if
> 		// it weren't for open snapshots.
> 		PinnedKeysSize uint64
> ```

this is key and value size, yes? Should we call it PinnedSize?
___
*[`sstable/properties.go` line 149 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRmvQv50LKddDldM2QN:-NRmvQv50LKddDldM2QO:b-gljxnm) ([raw file](https://github.com/cockroachdb/pebble/blob/2a29376f16c357437cd0fbde221be5a5a43ac0aa/sstable/properties.go#L149)):*
> ```Go
> 	// The cumulative bytes of keys in this table that were pinned by
> 	// open snapshots. This value is comparable to RawKeySize.
> 	SnapshotPinnedKeySize uint64 `prop:"pebble.raw.snapshot-pinned-keys"`
> ```

shouldn't this and the one below be suffixed by `.size`?


<!-- Sent from Reviewable.io -->

2023-03-30 17:14 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1814)* status: 25 of 30 files reviewed, 18 unresolved discussions (waiting on @bananabrick, @nicktrav, and @sumeerbhola)

___
*[`compaction_iter.go` line 390 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRmqAbQ--bzj2eKYnIu:-NRnTWDbDZfoNyQvy2-I:bnwv2ng) ([raw file](https://github.com/cockroachdb/pebble/blob/2a29376f16c357437cd0fbde221be5a5a43ac0aa/compaction_iter.go#L390)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we are always calling `elideTombstone` now, which involves a key comparison, while earlier it was only happening if `i.curSnapshotIdx == 0`. Is this not a performance concern because the common case in CockroachDB will be `i.curSnapshotIdx == 0` (since snapshots are rare)?
</blockquote></details>

I think that's true, but I don't have a great intuition for truly how rare snapshots are. Hopefully these metrics can help with that.

We alternatively could also liberally label these tombstones as pinned.

Also worth noting that L5->L6 compactions, plus compactions over keyspaces that are entirely in-use avoid the key comparison.
___
*[`metrics.go` line 236 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRmtlW11WC5kcO6oMNi:-NRnUwjR9UffM1sLi-mc:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/2a29376f16c357437cd0fbde221be5a5a43ac0aa/metrics.go#L236)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this is key and value size, yes? Should we call it PinnedSize?
</blockquote></details>

Done.
___
*[`sstable/properties.go` line 149 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1814#-NRmvQv50LKddDldM2QN:-NRnVWIK9ZfvAxhnbhKR:bxsqqq) ([raw file](https://github.com/cockroachdb/pebble/blob/2a29376f16c357437cd0fbde221be5a5a43ac0aa/sstable/properties.go#L149)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

shouldn't this and the one below be suffixed by `.size`?
</blockquote></details>

ah, good catch. Done.


<!-- Sent from Reviewable.io -->

2023-03-30 18:57 UTC, jbowens commented
TFTRs!

2023-03-30 18:57 UTC, merged