db: use block properties for efficient range-key masking
cockroachdb/pebble pull request #1824
Opened 2022-07-26 18:43 UTC by jbowens

Add a new `IterOptions.RangeKeyMasking.Filter` option that allows skipping of
sstable blocks that contain exclusively keys masked by range keys. The user
configures a block-property collector to record the maximal suffix within a
block and a block-property filter to filter on the property. The filter
additional must implement a `SetSuffix` method that dynamically changes the
filtering criteria.

Close #1713.

2022-07-26 18:43 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1824)
<!-- Reviewable:end -->

2022-07-28 02:11 UTC, sumeerbhola requested changes
made a rough first pass -- flushing some preliminary comments

> Reviewed 1 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1824#-:-N81ZWyS6eVXcWyx5KbE:b-euxwiz)* status: 1 of 32 files reviewed, 7 unresolved discussions (waiting on @erikgrinaker and @jbowens)

___
*[`options.go` line 266 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N81TdVK8iamvVCWXm66:-N81TdVK8iamvVCWXm67:b-y6gjda) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/options.go#L266)):*
> ```Go
> // ask the filter mask to compare the property to the current masking range
> // key's suffix. If the mask reports no intersection, the block may be skipped.
> type BlockPropertyFilterMask interface {
> ```

I'm unsure about the various consumers of this interface. Presumably the only code that cares that this implements `BlockPropertyFilter` is a sstable iterator. And the `SetSuffix` call is for use by the interleaving iterator. Is that correct?
___
*[`range_keys.go` line 313 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N81XEIdDDvbtYDKghGD:-N81XEIdDDvbtYDKghGE:bme4o8i) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/range_keys.go#L313)):*
> ```Go
> // key is considered out-of-bounds. If the iterator is positioned within a range
> // key, it compares the corresponding range key bound.
> var _ sstable.BoundLimitedBlockPropertyFilter = (*rangeKeyMasking)(nil)
> ```

I was expecting to see the implementation of `BoundLimitedBlockPropertyFilter` also to be in the sstable package, and not here. It would have a changeable `maskSpan`. It seems separable from the decision of when to change `maskSpan` that is handled by `rangeKeyMasking`. 
Though I can see why this may hinder readability since the suffix is being changed at the same time.
Part of the issue is that the notion of bound-limiting is quite well abstracted, but changing the configuration of the block property filter is not something we abstract (changing a "suffix" is too implementation specific), since we've not needed to.
I don't have good ideas here, and what you have here may be the right level of abstraction.

I'll stare at this some more tomorrow.
 
___
*[`sstable/block_property.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N81VP1P1WfuVV44cYmZ:-N81VP1P1WfuVV44cYm_:bn6plfd) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/sstable/block_property.go#L146)):*
> ```Go
> // imposes an additional constraint on its usage, requiring that only blocks
> // containing exclusively keys between its lower and upper bounds may be
> // filtered.
> ```

But it doesn't expose those bounds because they are changing? I think it's worth being explicit in this code comment.
___
*[`sstable/block_property.go` line 154 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N81VhVWEuuX6g0y8DFk:-N81VhVWEuuX6g0y8DFl:bkc81zh) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/sstable/block_property.go#L154)):*
> ```Go
> //
> // During forward iteration the lower bound (and during backward iteration the
> // upper bound) must be externally guaranteed, with Intersects only returning
> ```

This is hard for someone to follow. I think it is worth being explicit that the current [l,u) bound is unknown, but it is somehow externally guaranteed that during forward iteration the sstable is at a key >= l, and that this is arranged by the higher layers of the iterator stack. So then the sstable iterator only needs to confirm that the ssblock it is applying the filter to has an exclusive upper bound <= u.
___
*[`sstable/block_property.go` line 172 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N81WVc61dRl22gqLPPp:-N81WVc61dRl22gqLPPq:bop84vp) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/sstable/block_property.go#L172)):*
> ```Go
> 	// KeyIsWithinUpperBound tests whether the provided internal key falls
> 	// within the current upper bound of the filter. A true return value
> 	// indicates that the filter may be used to filter blocks containing keys ≤
> ```

all the keys in the block must satisfy keys <= key, yes?
Worth strengthening this comment.
___
*[`sstable/block_property.go` line 734 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N81SUVm3LowpN4PId8z:-N81SUVm3LowpN4PId9-:b-ntrjgh) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/sstable/block_property.go#L734)):*
> ```Go
> 		}
> 		if i >= len(f.shortIDToFiltersIndex) {
> 			return blockIntersects, nil
> ```

what if `ret` was set to `blockMaybeExcluded` in the earlier for loop? Why is this ignoring that setting?
___
*[`sstable/block_property.go` line 761 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N81Ska1DWaqYF3t3OFy:-N81Ska1DWaqYF3t3OFz:bbqcq18) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/sstable/block_property.go#L761)):*
> ```Go
> 				return ret, err
> 			} else if !intersects {
> 				ret = blockMaybeExcluded
> ```

can this code be extracted into a func, so not repeated twice?


<!-- Sent from Reviewable.io -->

2022-07-28 15:00 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1824)* status: 1 of 32 files reviewed, 7 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)

___
*[`options.go` line 266 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N81TdVK8iamvVCWXm66:-N83lVamCHUErEfkZXiu:bp9lvxs) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/options.go#L266)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm unsure about the various consumers of this interface. Presumably the only code that cares that this implements `BlockPropertyFilter` is a sstable iterator. And the `SetSuffix` call is for use by the interleaving iterator. Is that correct?
</blockquote></details>

yeah, the `BlockPropertyFilter` implementation is used by the `iteratorRangeKeyState` which wraps it, in turn implementing the `sstable.BoundLimitedBlockPropertyFilter` interface and calling `SetSuffix` as needed, with help from the interleaving iterator. The `iteratorRangeKeyState` type serves as an adapter, bridging between the external range-key masking specifics and the more abstracted bound-limiting consumed by the sstable iterator.
___
*[`sstable/block_property.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N81VP1P1WfuVV44cYmZ:-N849tB_4zKV5fF_LQ3x:bd5g6kg) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/sstable/block_property.go#L146)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

But it doesn't expose those bounds because they are changing? I think it's worth being explicit in this code comment.
</blockquote></details>

yeah, done.
___
*[`sstable/block_property.go` line 154 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N81VhVWEuuX6g0y8DFk:-N84Dff3C5jpuT1PMjMo:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/sstable/block_property.go#L154)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is hard for someone to follow. I think it is worth being explicit that the current [l,u) bound is unknown, but it is somehow externally guaranteed that during forward iteration the sstable is at a key >= l, and that this is arranged by the higher layers of the iterator stack. So then the sstable iterator only needs to confirm that the ssblock it is applying the filter to has an exclusive upper bound <= u.
</blockquote></details>

Done.
___
*[`sstable/block_property.go` line 172 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N81WVc61dRl22gqLPPp:-N84H81g15MGEVrGfBYR:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/sstable/block_property.go#L172)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

all the keys in the block must satisfy keys <= key, yes?
Worth strengthening this comment.
</blockquote></details>

Done.
___
*[`sstable/block_property.go` line 734 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N81SUVm3LowpN4PId8z:-N84HVoiCuwxvl0QzBOT:bvnydch) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/sstable/block_property.go#L734)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what if `ret` was set to `blockMaybeExcluded` in the earlier for loop? Why is this ignoring that setting?
</blockquote></details>

oof, this was a bug
___
*[`sstable/block_property.go` line 761 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N81Ska1DWaqYF3t3OFy:-N84ImZH3Ez2vUW0eshD:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/sstable/block_property.go#L761)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can this code be extracted into a func, so not repeated twice?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-28 15:29 UTC, erikgrinaker reviewed
Nice speedup! Looks good at a high level.

CRDB currently gets the block property collectors and filters supplied by Pebble, specifically via `sstable.NewBlockIntervalCollector` and `sstable.NewBlockIntervalFilter`. I'd expect it to also offer a corresponding `BlockPropertyFilterMask` implementation to pair with these, either extending the block interval filter or a separate one, but I couldn't find any. Did I miss it?

> Reviewed 1 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1824#-:-N84OWUDAZmOPDr3b_UG:b-t7kqn0)* status: 1 of 32 files reviewed, 7 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-07-28 16:55 UTC, jbowens reviewed
>  I'd expect it to also offer a corresponding BlockPropertyFilterMask implementation to pair with these,

My expectation is that the CRDB `pkg/storage` will implement a small wrapper around `sstable.BlockIntervalFilter`. The wrapper will only need to implement `SetSuffix`, which it can implement by decoding the timestamp in the suffix and calling `BlockIntervalFilter.SetInterval(<decoded timestamp>, math.MaxUint64)`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1824#-:-N84iK3r6YdEkNrlEhjR:b7l4dik)* status: 1 of 32 files reviewed, 7 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-07-28 16:57 UTC, erikgrinaker reviewed
I see, makes sense. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1824#-:-N84jO036Ir1Vsm4PGdJ:b9cxpmm)* status: 1 of 32 files reviewed, 7 unresolved discussions (waiting on @erikgrinaker, @jbowens, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-07-28 20:45 UTC, nicktrav reviewed
Flushing some comments. I'm still on an `r1`, so apologies if I'm restating something that's been addressed.

> Reviewed 27 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1824#-:-N85V8qm5iPaZoGW6Lxc:b-nzikuj)* status: 21 of 32 files reviewed, 17 unresolved discussions (waiting on @erikgrinaker, @jbowens, @nicktrav, and @sumeerbhola)

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N80hDj33jtu8Ml52rmE):*
Delicious!
___
*[`options.go` line 262 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N85K4wn1E-AcdV66fH6:-N85K4wn1E-AcdV66fH7:btce631) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/options.go#L262)):*
> If a block's keys ... all fall within the bounds of the masking range key and the block was annotated

In the case where the collector sees a maximal suffix for the block (e.g. `a@100`), but there's also an unsuffixed key in the block, what happens (e.g. `a`)? Is an unsuffixed key always treated treated as being unmasked? How does this "infinite" masking threshold get captured by the collector?

For Cockroach, where an unsuffixed key sorts first (`a < a@1 < a@100 < b`, right?), this is fine. Is there a sharp edge here for others that needs documenting?
___
*[`range_keys.go` line 81 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N85LbX61beMR8GswanQ:-N85LbX61beMR8GswanR:b-kyes1z) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/range_keys.go#L81)):*
> ```Go
> }
> 
> // Range key masking
> ```

These docs are :100:. Thank you for adding.
___
*[`range_keys.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N85L2z_1-NDZCRRe-0T:-N85L2z_1-NDZCRRe-0U:bvw8or9) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/range_keys.go#L89)):*
> act as mask

nit: "act as a mask" or "act as masks"
___
*[`range_keys.go` line 127 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N85MEiZCtZ4ajDNtS_R:-N85MEiZCtZ4ajDNtS_S:b-rnge3s) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/range_keys.go#L127)):*
> ```Go
> //
> // The SkipPoint logic is sufficient to ensure that the Pebble iterator filters
> // out all masked point keys. However, it requires the iterator read each masked
> ```

nit: "requires that the iterator read"
___
*[`range_keys.go` line 253 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N85OzkAE0QkUqOovAXw:-N85OzkAE0QkUqOovAXx:bf37v14) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/range_keys.go#L253)):*
> ```Go
> // _p_, and
> //
> //     _t_ ≤ _r_ < _p_
> ```

Maybe it's just me, but every time I encounter this inequality, it does my head in. The issue (for me) is in interpreting `<` to mean "suffix sorts strictly before" rather than in the mathematical sense. I realize we call that out in the next sentence.

Any chance we can define `<` and `<=` in this "sorts strictly before" / "sorts before" sense before the inequality. e.g. "... where`≤`and `<` imply that the suffix sorts before or strictly before ...".

Treat this as a nit, though I think the docs could be less confusing here.
___
*[`range_keys.go` line 256 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N85QMsB6cbB7aCFCHMC:-N85QMsB6cbB7aCFCHMD:b-4mz79u) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/range_keys.go#L256)):*
> suffixes with higher integers sort before suffixes with lower integers:

To the above point, we could drive it home in terms of the inequality as "e.g. `@7 <= @6 < @5`".
___
*[`range_keys.go` line 307 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N85ULExEO1_q9_7n5os:-N85ULExEO1_q9_7n5ot:bnynh8z) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/range_keys.go#L307)):*
> ```Go
> // This extended BoundLimitedBlockPropertyFilter interface adds two new methods,
> // KeyIsWithinLowerBound and KeyIsWithinUpperBound, for testing whether a
> // particular block is within bounds.
> ```

A diagram, or textual example may help drive home the point here. i.e. point key is masked by the mask active suffix, but it is not in the span responsible for the mask.
___
*[`range_keys.go` line 346 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N85UvO3-D8eA7kGoS25:-N85UvO3-D8eA7kGoS26:b-iz03vj) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/range_keys.go#L346)):*
> ```Go
> func (m *rangeKeyMasking) KeyIsWithinUpperBound(ik *InternalKey) bool {
> 	// Invariant: m.maskSpan != nil
> 	// tktk: document inclusivity requirements here and on the interface.
> ```

nit: leftovers?
___
*[`iterator_test.go` line 2125 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N80jHCv0kQ6xVLCnAVl:-N80jHCw92FjKFQmSKY0:bdrici4) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/iterator_test.go#L2125)):*
> ```Go
> 
> // BenchmarkIterator_RangeKeyMasking benchmarks a scan through a keyspace with
> // 10,000 random suffixed point keys, and three range covering most of the
> ```

nit: s/three range/three range keys/
___
*[`iterator_test.go` line 2174 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N80kZpe8QJU1BpFGsqA:-N80kZpe8QJU1BpFGsqB:b6m4y7s) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/iterator_test.go#L2174)):*
> ```Go
> 		d.mu.Unlock()
> 		if stillCompacting {
> 			time.Sleep(time.Millisecond)
> ```

I learned about the following pattern recently, that I _think_ obviates the need for the `time.Sleep`. Something like:

```go
	func() {
		d.mu.Lock()
		defer d.mu.Unlock()
		for d.mu.compact.compactingCount > 0 {
			d.mu.compact.cond.Wait()
		}
	}()
```
___
*[`iterator_test.go` line 2195 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N80jVT6D2wmk51-anpr:-N80jVT6D2wmk51-anps:b-tb4ucf) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/iterator_test.go#L2195)):*
> ```Go
> 			require.NoError(b, d.Flush())
> 
> 			// Populate 3 range keys, covering most of the keyspac, at the given
> ```

nit: s/keyspac/keyspace/
___
*[`iterator_test.go` line 2223 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N80lQq70GmEIyPRQr1f:-N80lQq70GmEIyPRQr1g:b-mqjp2r) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/iterator_test.go#L2223)):*
> ```Go
> 			b.StopTimer()
> 			require.NoError(b, d.Close())
> 			mem.ResetToSyncedState()
> ```

TIL. Nice.


<!-- Sent from Reviewable.io -->

2022-07-28 21:10 UTC, nicktrav reviewed
> Reviewed 4 of 31 files at r1, 4 of 4 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1824)* status: all files reviewed, 17 unresolved discussions (waiting on @jbowens and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-07-29 15:03 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1824)* status: all files reviewed, 11 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[`options.go` line 262 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N85K4wn1E-AcdV66fH6:-N89F_pu1_39FiCB7oSQ:bbat3jj) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/options.go#L262)):*
The testkeys block property collector implements this by recording the maximal interval if a block contains any keys without suffixes: https://github.com/jbowens/pebble/blob/masking/internal/testkeys/blockprop/blockprop.go#L87-L91

> For Cockroach, where an unsuffixed key sorts first (a < a@1 < a@100 < b, right?), this is fine. Is there a sharp edge here for others that needs documenting?

I don't think the key sorting is enough, because a block may contain many runs of alternating unsuffixed and suffixed keys. Cockroach relies on its segmented keyspace. The region of the keyspace that contains MVCC keys only contains MVCC keys, and a time-bound iterator reading MVCC history doesn't care about unsuffixed keys that might live at the edge. This is something we should document clearly in pkg/storage's interface for masking. 

I'll add a comment here for external users.
___
*[`range_keys.go` line 127 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N85MEiZCtZ4ajDNtS_R:-N89M44H6MIc5Xji8CVE:b-yhsmim) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/range_keys.go#L127)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: "requires that the iterator read"
</blockquote></details>

heh, I tend to prefer the more colloquial omission of unrequired "that"s
___
*[`range_keys.go` line 253 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N85OzkAE0QkUqOovAXw:-N89NoCr8vpSlwykvmyB:bl5g7xc) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/range_keys.go#L253)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Maybe it's just me, but every time I encounter this inequality, it does my head in. The issue (for me) is in interpreting `<` to mean "suffix sorts strictly before" rather than in the mathematical sense. I realize we call that out in the next sentence.

Any chance we can define `<` and `<=` in this "sorts strictly before" / "sorts before" sense before the inequality. e.g. "... where`≤`and `<` imply that the suffix sorts before or strictly before ...".

Treat this as a nit, though I think the docs could be less confusing here.
</blockquote></details>

Took your suggestion below to add an example. I want to avoid going to deep into the Cockroach-specific ordering of keys here. From the perspective of Pebble, these are only opaque byte keys, and the only comparison that exists is the sort ordering.
___
*[`range_keys.go` line 256 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N85QMsB6cbB7aCFCHMC:-N89NnqE0ORBM75KIAa0:bb7f2mf) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/range_keys.go#L256)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

> suffixes with higher integers sort before suffixes with lower integers:

To the above point, we could drive it home in terms of the inequality as "e.g. `@7 <= @6 < @5`".
</blockquote></details>

done
___
*[`iterator_test.go` line 2174 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N80kZpe8QJU1BpFGsqA:-N89Q3PjDfz_q5HAE6da:bsef6fl) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/iterator_test.go#L2174)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

I learned about the following pattern recently, that I _think_ obviates the need for the `time.Sleep`. Something like:

```go
	func() {
		d.mu.Lock()
		defer d.mu.Unlock()
		for d.mu.compact.compactingCount > 0 {
			d.mu.compact.cond.Wait()
		}
	}()
```
</blockquote></details>

nice, forgot we have a condvar there.


<!-- Sent from Reviewable.io -->

2022-07-29 15:35 UTC, nicktrav approved these changes
All my comments / questions addressed. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1824#-:-N89a6YX7EqEtImZ9v2B:b-abnq1d)* status: all files reviewed, 7 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`options.go` line 262 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N85K4wn1E-AcdV66fH6:-N89Zd1LADFseopOg09z:b-z3bmtx) ([raw file](https://github.com/cockroachdb/pebble/blob/e3e2982de96a89b47ff915ba93201316cc827089/options.go#L262)):*
> The testkeys block property collector implements this by recording the maximal interval if a block contains any keys without suffixes:

Perfect.

> I'll add a comment here for external users.

:+1: 


<!-- Sent from Reviewable.io -->

2022-08-01 21:31 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1824#-:-N8QJUDJ8sMfollwj703:bz5mair)* status: all files reviewed, 15 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[`level_iter.go` line 170 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N8OOSBu5ariZF3XvxqJ:-N8PwIu1CmR_TsGf44hA:b-ojb64b) ([raw file](https://github.com/cockroachdb/pebble/blob/e4f1f33651c3a9ceacf3a0fe2046f6536a3647f1/level_iter.go#L170)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: if these are specific to sstable iters, would it be clearer to name them `internalSSTableIterOpts`?
</blockquote></details>

I think the `bytesIterated` field is also used by the memtable and flushable batch iterators, although maybe we should rip that out altogether.
___
*[`options.go` line 215 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N8OQW9G0oGBWf5fONYe:-N8Pza1J9rjQjnGItUbT:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e4f1f33651c3a9ceacf3a0fe2046f6536a3647f1/options.go#L215)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

shouldn't this be `Suffix <= range-key-suffix`?
</blockquote></details>

Done.
___
*[`options.go` line 216 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N8OR-71BIUYSsAwqSQ-:-N8Q-TMU5MKMulPTL38w:bcxdkzy) ([raw file](https://github.com/cockroachdb/pebble/blob/e4f1f33651c3a9ceacf3a0fe2046f6536a3647f1/options.go#L216)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

"have suffixes less" seems to contradict the _r_ < _p_ below.

There are other such code comments below too. @nicktrav also mentioned this.
I don't have good ideas regarding how to fix this. Also, it can be postponed to a future PR.
</blockquote></details>

Done., at least within this external documentation :sweat_smile: 
___
*[`range_keys.go` line 237 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N8Oh-vUDb9XMGWaez9S:-N8Q0bJR-YVsT8HYk3X2:b-d11ety) ([raw file](https://github.com/cockroachdb/pebble/blob/e4f1f33651c3a9ceacf3a0fe2046f6536a3647f1/range_keys.go#L237)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this lazy changing of the suffix an optimization? Or is to avoid defining `SetSuffix(nil)` as no suffix?
</blockquote></details>

It's an optimization. In particular, I wanted `Intersects` to be very cheap when there's no range key since it must be invoked on every block load, including when there are no range keys and no benefit to the block-property filter. Implementing `Intersects` with knowledge of whether there's an active mask avoids decoding the property if it doesn't matter. Once I added that, I figured there's no reason to clear the filter if it's never going to be consulted.
___
*[`sstable/block_property.go` line 656 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N8OVk-iCBBUDv83ujl3:-N8Q3MaUAKLuAbmRhvNC:b-ytro99) ([raw file](https://github.com/cockroachdb/pebble/blob/e4f1f33651c3a9ceacf3a0fe2046f6536a3647f1/sstable/block_property.go#L656)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't quite understand the "If a filter is bound-limited ..." sentence. Isn't it by definition bound-limited and applicable to a limited span of the keyspace? Is this sentence trying to say something about the case where the filter is currently bound-limited? Should there be a notion of the filter is active versus inactive -- it's currently an implementation detail, but maybe useful for such code comments.
</blockquote></details>

I'm not sure why this sentence was phrased as a conditional. I've updated it. Added a couple comments about active/inactive
___
*[`sstable/reader.go` line 828 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N8Oaot936r4kXSJnUWN:-N8QJT3-0ImhacK68zP9:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e4f1f33651c3a9ceacf3a0fe2046f6536a3647f1/sstable/reader.go#L828)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same question as `twoLevelIterator` about upper-bound not being satisfied.
</blockquote></details>

Done.
___
*[`sstable/reader.go` line 1680 at r5](https://reviewable.io/reviews/cockroachdb/pebble/1824#-N8OaN8BB_dQm9563ru2:-N8QHh312ygC4_kVLd8R:b-rf9wj5) ([raw file](https://github.com/cockroachdb/pebble/blob/e4f1f33651c3a9ceacf3a0fe2046f6536a3647f1/sstable/reader.go#L1680)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

by doing `SeekGE` hasn't the iterator violated the requirement that an upper-bound is externally satisfied?
Or is this irrelevant because we won't have an active mask when doing seeks? It is worth a code comment.

If we wanted to keep using a range key mask during such as seek (as discussed in https://github.com/cockroachdb/pebble/issues/1713#issuecomment-1201241720), we do know the upper-bound of this index block that we have not yet loaded, so we could use that upper-bound in deciding whether to apply the filter in `loadIndex` below.

</blockquote></details>

yeah, it's irrelevant because the mask is inactive. added a comment.

good point. i think i'll take a stab late this week at seek optimizations, maybe including bpf masking


<!-- Sent from Reviewable.io -->

2022-08-01 21:38 UTC, merged

2022-08-01 21:45 UTC, jbowens commented
embarassing, forgot to push first: #1842