internal/rangekey: sort keys by suffix once during iteration
cockroachdb/pebble pull request #1831
Opened 2022-07-29 16:13 UTC by jbowens

During iteration over range keys, a stack of keyspan.FragmentIterators handle
various parts of range-key iteration: fragmenting, shadowing and defragmenting.
Previously, the keyspan.Span and keyspan.FragmentIterator strictly specified
the order of keys within a Span: always by Trailer, descending.

This created some unfortunate gymnastics during range-key iteration:
- To resolve shadowing (or "coalesce" range keys), the keyspan.Transform
  invoked by the keyspan.MergingIter) would sort the keys by suffix, and
  re-sort by Trailer.
- To determine whether or not two range key spans should be defragmented into a
  single Span, the range-key iterator would copy the keys into a buffer to sort
  by suffix.
- Lastly, when the range keys were surfaced to the *pebble.Iterator, they'd
  once again be sorted by suffix to present to the client.

This commit relaxes the keyspan.Span contract, allowing the Transform that
resolves shadowing to leave range keys in sorted order. This allows the
defragmenting iterator and the pebble.Iterator to avoid any additional sorting.

Benchmark results when rebased over #1824:
```
name                                                           old time/op    new time/op    delta
Iterator_RangeKeyMasking/range-keys-suffixes=@10/forward-10      2.35ms ± 6%    2.24ms ± 4%   -4.88%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@10/backward-10     3.31ms ± 3%    3.13ms ± 3%   -5.52%  (p=0.000 n=19+19)
Iterator_RangeKeyMasking/range-keys-suffixes=@50/forward-10      2.08ms ±11%    1.97ms ± 4%   -5.13%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@50/backward-10     2.78ms ± 5%    2.67ms ± 2%   -3.99%  (p=0.000 n=19+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@75/forward-10      1.00ms ± 5%    0.95ms ± 0%   -4.80%  (p=0.000 n=20+18)
Iterator_RangeKeyMasking/range-keys-suffixes=@75/backward-10     1.40ms ± 3%    1.34ms ± 1%   -4.15%  (p=0.000 n=19+19)
Iterator_RangeKeyMasking/range-keys-suffixes=@100/forward-10      150µs ± 0%     150µs ± 1%   -0.22%  (p=0.003 n=19+19)
Iterator_RangeKeyMasking/range-keys-suffixes=@100/backward-10     308µs ± 0%     302µs ± 0%   -2.15%  (p=0.000 n=20+20)

name                                                           old alloc/op   new alloc/op   delta
Iterator_RangeKeyMasking/range-keys-suffixes=@10/forward-10      2.88kB ± 1%    2.64kB ± 0%   -8.41%  (p=0.000 n=20+16)
Iterator_RangeKeyMasking/range-keys-suffixes=@10/backward-10     4.49kB ± 1%    4.22kB ± 1%   -5.88%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@50/forward-10      2.88kB ± 1%    2.62kB ± 1%   -9.22%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@50/backward-10     4.47kB ± 1%    4.22kB ± 1%   -5.75%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@75/forward-10      2.86kB ± 0%    2.60kB ± 0%   -9.14%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@75/backward-10     4.45kB ± 0%    4.20kB ± 0%   -5.78%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@100/forward-10     2.85kB ± 0%    2.59kB ± 0%   -8.98%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@100/backward-10    4.45kB ± 0%    4.19kB ± 0%   -5.80%  (p=0.000 n=20+20)

name                                                           old allocs/op  new allocs/op  delta
Iterator_RangeKeyMasking/range-keys-suffixes=@10/forward-10        41.0 ± 0%      33.0 ± 0%  -19.51%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@10/backward-10       46.0 ± 0%      38.0 ± 0%  -17.39%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@50/forward-10        41.0 ± 0%      33.0 ± 0%  -19.51%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@50/backward-10       46.0 ± 0%      38.0 ± 0%  -17.39%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@75/forward-10        41.0 ± 0%      33.0 ± 0%  -19.51%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@75/backward-10       46.0 ± 0%      38.0 ± 0%  -17.39%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@100/forward-10       41.0 ± 0%      33.0 ± 0%  -19.51%  (p=0.000 n=20+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@100/backward-10      47.0 ± 0%      39.0 ± 0%  -17.02%  (p=0.000 n=20+20)
```

2022-07-29 16:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1831)
<!-- Reviewable:end -->

2022-08-02 21:22 UTC, jbowens reviewed
@sumeerbhola do you have thoughts on this relaxed `keyspan.Span` contract?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1831#-:-N8VQQfF1vor3ffkRKEy:b-2e27ww)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-08-03 21:12 UTC, sumeerbhola requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1831#-:-N8_YOvd7z3vX9_QTVUf:bg7igkv)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @jbowens)

___
*[`iterator.go` line 258 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1831#-N8_WJ2t2Zd0fDRtKc2G:-N8_WJ2u9Nm9xKlref1N:b-4t343t) ([raw file](https://github.com/cockroachdb/pebble/blob/8ae54924b9704ff94194d778a49529cc6f26b022/iterator.go#L258)):*
> ```Go
> 	rangeKeyOnly bool
> 	hasRangeKey  bool
> 	keys         []RangeKeyData
> ```

is there any sort invariant for this slice?
___
*[`internal/keyspan/span.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1831#-N8_Wfmx9odeJCSXJJvi:-N8_Wfmx9odeJCSXJJvj:b-cp9ejo) ([raw file](https://github.com/cockroachdb/pebble/blob/8ae54924b9704ff94194d778a49529cc6f26b022/internal/keyspan/span.go#L41)):*
> ```Go
> 	// or sstable blocks. A single internal key in a range key block may produce
> 	// several decoded Keys.
> 	Keys []Key
> ```

if there are only 2 sort orders should we add an enum and store it here, so we can validate expectations wherever a particular sort order is assumed?
Maybe also encode things like shadowing, so it's a more general set of properties that are true about the `Span`. It may be helpful. It would allow for a cheaper check than the panics you've added in `iterator.go`, so would be viable to do this even when invariants.Enabled was false.


<!-- Sent from Reviewable.io -->

2022-08-04 22:53 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1831)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`iterator.go` line 258 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1831#-N8_WJ2t2Zd0fDRtKc2G:-N8eLQHOEtTQhmuhoLe3:b7nzhuh) ([raw file](https://github.com/cockroachdb/pebble/blob/8ae54924b9704ff94194d778a49529cc6f26b022/iterator.go#L258)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there any sort invariant for this slice?
</blockquote></details>

yeah, good call. i'll add a comment that it's sorted by suffix ascending
___
*[`internal/keyspan/span.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1831#-N8_Wfmx9odeJCSXJJvi:-N8f2ygD520MzGtsEn8w:bt029g9) ([raw file](https://github.com/cockroachdb/pebble/blob/8ae54924b9704ff94194d778a49529cc6f26b022/internal/keyspan/span.go#L41)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

if there are only 2 sort orders should we add an enum and store it here, so we can validate expectations wherever a particular sort order is assumed?
Maybe also encode things like shadowing, so it's a more general set of properties that are true about the `Span`. It may be helpful. It would allow for a cheaper check than the panics you've added in `iterator.go`, so would be viable to do this even when invariants.Enabled was false.
</blockquote></details>

good idea. for now i encoded just keys sort order.


<!-- Sent from Reviewable.io -->

2022-08-08 01:20 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1831#-:-N8v1RLJ8xVT8Be7MC_9:bg7igkv)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`internal/keyspan/merging_iter.go` line 818 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1831#-N8v198pC_7Gg-0QsBKH:-N8v198pC_7Gg-0QsBKI:b94okm6) ([raw file](https://github.com/cockroachdb/pebble/blob/ca93b0a890228d637422fc23f7dba4d43be3b5d4/internal/keyspan/merging_iter.go#L818)):*
> ```Go
> 	// TODO(jackson): We should be able to remove this sort and instead
> 	// guarantee that we'll return keys in the order of the levels they're from.
> 	// With careful iterator construction, this would  guarantee that they're
> ```

Can you elaborate on this "careful iterator construction" -- specifically what do we do now that violates the trailer descending oder?
___
*[`internal/keyspan/span.go` line 156 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1831#-N8v-oGbAGMsTP1TAzSc:-N8v-oGbAGMsTP1TAzSd:b-x8mmsd) ([raw file](https://github.com/cockroachdb/pebble/blob/ca93b0a890228d637422fc23f7dba4d43be3b5d4/internal/keyspan/span.go#L156)):*
> ```Go
> // LargestSeqNum returns the largest sequence number of a key contained within
> // the span. It requires the Span's keys be in ByTrailerDesc order. It panics if
> // the span contains no keys or its keys are sorted in a different order.
> ```

the code is missing a panic for `if s.KeysOrder != ByTrailerDesc`


<!-- Sent from Reviewable.io -->

2022-08-08 17:33 UTC, jbowens reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1831#-:-N8yWGMfDwE1WSyLpWxv:b-814g8k)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @sumeerbhola)

___
*[`internal/keyspan/merging_iter.go` line 818 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1831#-N8v198pC_7Gg-0QsBKH:-N8yUqxZ-z7leQBI1KFr:bw0etzl) ([raw file](https://github.com/cockroachdb/pebble/blob/ca93b0a890228d637422fc23f7dba4d43be3b5d4/internal/keyspan/merging_iter.go#L818)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you elaborate on this "careful iterator construction" -- specifically what do we do now that violates the trailer descending oder?
</blockquote></details>

I don't actually know, but in some tests it appeared to be the case. I'm hoping to circle back on this either later this week or next week.
___
*[`internal/keyspan/span.go` line 156 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1831#-N8v-oGbAGMsTP1TAzSc:-N8yVnnZ9eUuvL8LlXhI:b36pig5) ([raw file](https://github.com/cockroachdb/pebble/blob/ca93b0a890228d637422fc23f7dba4d43be3b5d4/internal/keyspan/span.go#L156)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the code is missing a panic for `if s.KeysOrder != ByTrailerDesc`
</blockquote></details>

oops, thanks


<!-- Sent from Reviewable.io -->

2022-08-08 17:34 UTC, merged