db: add NextPrefix to Iterator
cockroachdb/pebble pull request #1860
Opened 2022-08-05 22:13 UTC by jbowens

Expose a NextPrefix method on *pebble.Iterator that may be called when the user
wishes to move to the next key prefix (as determined by Comparer.Split).
NextPrefix guarantees that it will move to the next key prefix.

I'd like to revisit the optimization from #1387, but for now this commit
introduces the new positioning method and relies on the slight optimization of
only needing to compare prefixes, instead of finding each new user key using
user key comparisons and comparing their prefixes.

2022-08-05 22:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1860)
<!-- Reviewable:end -->

2022-08-08 12:26 UTC, erikgrinaker approved these changes
Looks good at a high level!

In CRDB, we fall back to doing a seek. Can we drop this optimization (alternatively move it down into Pebble) and rely on `NextPrefix` entirely?

https://github.com/cockroachdb/cockroach/blob/5e2930bede5bbaf40801fd4bdf6a740228e207b7/pkg/storage/pebble_iterator.go#L439-L444

2022-08-08 13:38 UTC, jbowens commented
@erikgrinaker Yeah, I think we should move some form of it down to Pebble. I think we can improve upon it within Pebble, like only seeking the internal level iterators that are positioned at key with the same prefix.

We'll need to expose an `ImmediateSuccessor` function on `Comparer` so that Pebble can construct the appropriate seek key, since Pebble has no direct knowledge of the key encoding.

2022-08-09 00:21 UTC, nicktrav approved these changes
Nice! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860#-:-N8zuTQj3jnRMQMnNvVc:be8rotp)* status: all files reviewed, 5 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`iterator.go` line 602 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N8zo_1d3MD1OoIkIfFw:-N8zo_1d3MD1OoIkIfFx:bfjtm22) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L602)):*
> ```Go
> 	// as a simple Next and nextPrefixKey is not invoked.
> 	if invariants.Enabled && i.pos != iterPosCurForward && i.pos != iterPosNext {
> 		panic("pebble: nextPrefixKey called from a limited or reverse position state")
> ```

The comment block above indicates that `nextPrefixKey` degenerates to a simple `Next()` for limited or reverse iteration, yet we're panicking here in the invariants case. In other words, it doesn't seem _fatal_ to correctness based on the docs. Indeed, we even allow it when `!invariants.Enabled`.

Is it actually user error - in which case perhaps we should _always_ panic (and not just when invariants are enabled). Or if it's allowed, perhaps just leave the comment and remove the panic?
___
*[`iterator.go` line 615 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N8zpw4K31Nx3y90BY5H:-N8zpw4K31Nx3y90BY5I:bnqkvq1) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L615)):*
> ascending by suffix

For completeness, perhaps a parenthetical comment here indicating that the nil suffix sorts before any non-nil suffix for keys with equal prefix?
___
*[`iterator.go` line 621 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N8zqHvX6Y1qgDH2Zx9j:-N8zqHvX6Y1qgDH2Zx9k:b-kh0c1p) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L621)):*
> ```Go
> 		//    prefix   seq  suffix   suffix   seq    suffix   prefix
> 		//       |      |     |        |       |       |         |
> 		//   a#0 <  b#4 < b#0 < b@10#3 < b@5#9 < b@5#0 < b@0#100 < c#5
> ```

We may also want to point out that in this example, "ascending by suffix" for MVCC-like suffixes implies that `@10 < @5`. Else, to the uninitiated, it may read as integer ordering, and appear incorrect.
___
*[`iterator.go` line 625 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N8zr5pKE6K8fgDFop9s:-N8zr5pKE6K8fgDFop9t:b-6bke2x) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L625)):*
> ```Go
> 		// In terms of cost of comparison, trailers/seqnums (a uint64) are
> 		// cheapest, suffixes (typically encoded MVCC timestamps) are next
> 		// cheapest, and prefixes are most expensive.
> ```

I assume the statement here around suffix comparison is due to (typically) shorter, fixed length slices, relative to prefixes, which are (technically) "unbounded"? At least for MVCC suffixes.
___
*[`iterator.go` line 635 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N8zrc2i7VgFU-RuqslX:-N8zrc2i7VgFU-RuqslY:bxjmjbs) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L635)):*
> ```Go
> 		//      new user key: Zero is the smallest sequence number. No key with
> 		//      the same user key may have a lower sequence number, so i.iterKey
> 		//      must be a new user key.
> ```

For my own understanding - this relies on the invariant that there are no duplicate keys at seqnum `0`. And I assume this is why we had #1843 recently to disallow ingested sstables with the same user key?
___
*[`iterator.go` line 648 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N8zuNFO9B4fibbfBniN:-N8zuNFO9B4fibbfBniO:b86p9tz) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L648)):*
> ```Go
> 		//      user keys, i.iterKey necessarily must have a different prefix.
> 		//
> 		// We combine 1, 2 & 3 to avoid a prefix comparison when possible.
> ```

Love how this optimization is popping up all over the place.


<!-- Sent from Reviewable.io -->

2022-08-09 22:56 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860)* status: 8 of 27 files reviewed, 3 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[`iterator.go` line 602 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N8zo_1d3MD1OoIkIfFw:-N93n7Li9ahooeXKZFP-:b-3t4lng) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L602)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

The comment block above indicates that `nextPrefixKey` degenerates to a simple `Next()` for limited or reverse iteration, yet we're panicking here in the invariants case. In other words, it doesn't seem _fatal_ to correctness based on the docs. Indeed, we even allow it when `!invariants.Enabled`.

Is it actually user error - in which case perhaps we should _always_ panic (and not just when invariants are enabled). Or if it's allowed, perhaps just leave the comment and remove the panic?
</blockquote></details>

I think you might've missed the tail of this sentence: "If Iterator.NextPrefix is called after a reverse-iteration method, NextPrefix behaves as a simple Next and _nextPrefixKey is not invoked_."

When switching directions, `NextPrefix` will not invoke `nextPrefixKey`.
___
*[`iterator.go` line 615 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N8zpw4K31Nx3y90BY5H:-N93ncwxCvt4dWv1tvvU:bb7f2mf) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L615)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

> ascending by suffix

For completeness, perhaps a parenthetical comment here indicating that the nil suffix sorts before any non-nil suffix for keys with equal prefix?
</blockquote></details>

done
___
*[`iterator.go` line 625 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N8zr5pKE6K8fgDFop9s:-N93o-ZhAxzM89vjaQE1:b-v0pdba) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L625)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

I assume the statement here around suffix comparison is due to (typically) shorter, fixed length slices, relative to prefixes, which are (technically) "unbounded"? At least for MVCC suffixes.
</blockquote></details>

that's right.
___
*[`iterator.go` line 635 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N8zrc2i7VgFU-RuqslX:-N93o7fFDKdRqjFazwES:b-xxip22) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L635)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

For my own understanding - this relies on the invariant that there are no duplicate keys at seqnum `0`. And I assume this is why we had #1843 recently to disallow ingested sstables with the same user key?
</blockquote></details>

yes, we've always had the invariant that no two keys have the same user key and sequence number (it's not restricted to just seqnum 0).  Pebble would never create such duplicate keys itself, but the gap fixed by #1843 accidentally permitted external sstable writers to add duplicate keys within the same sstable.


<!-- Sent from Reviewable.io -->

2022-08-10 04:50 UTC, sumeerbhola requested changes
> Reviewed 3 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860)* status: 8 of 28 files reviewed, 7 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[`iterator.go` line 581 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N950nE416MnGVXqxmxe:-N950nE416MnGVXqxmxf:bc5nebh) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L581)):*
> ```Go
> 	}
> 	if i.iterValidityState != IterValid {
> 		i.keyBuf = append(i.keyBuf[:0], i.iterKey.UserKey...)
> ```

can you remind me when is this if-block taken. Is it possible that both this block and the if-block following this will get executed in which case `i.key` is the same as `i.iterKey.UserKey` are the same.
___
*[`iterator.go` line 602 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N8zo_1d3MD1OoIkIfFw:-N95-Ofr7FBc7yjaZdYz:bix74zw) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L602)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think you might've missed the tail of this sentence: "If Iterator.NextPrefix is called after a reverse-iteration method, NextPrefix behaves as a simple Next and _nextPrefixKey is not invoked_."

When switching directions, `NextPrefix` will not invoke `nextPrefixKey`.
</blockquote></details>

I am similarly confused. We seem to be defining the behavior for these other cases, but then panicking when those happen.
___
*[`iterator.go` line 607 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N953y9jCNfO01aN_HVO:-N953y9jCNfO01aN_HVP:b3ucw0l) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L607)):*
> ```Go
> 	for {
> 		trailer := i.iterKey.Trailer
> 		i.iterKey, i.iterValue = i.iter.Next()
> ```

where in CockroachDB do we expect to use this? Aren't all the CockroachDB code-paths falling back to seek, which this is not, so in some cases this could be a regression?
___
*[`iterator.go` line 642 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N953MC55wlnPIekqk-2:-N953MC55wlnPIekqk-3:bncbjdh) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L642)):*
> ```Go
> 		//
> 		//   3. i.iterKey's user key ≠ the previous key's user key AND
> 		//      suffix(i.iterKey) ≤ suffix(prev key) together imply unequal
> ```

suffix(i.iterKey) < suffix(prev key) => user key has changed
and the prefix must also have changed.
Can this be used to improve the optimization.
___
*[`iterator.go` line 607 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N954ZDt8-1-294UYPWq:-N954ZDt8-1-294UYPWr:b-su7wkt) ([raw file](https://github.com/cockroachdb/pebble/blob/1b2c91d2075fe61765eec2584891739bba7db0dc/iterator.go#L607)):*
> ```Go
> 
> 	const numNextsBeforeSeek = 3
> 	for j := 0; j < numNextsBeforeSeek; j++ {
> ```

never mind my comment about seeking, on the previous commit.


<!-- Sent from Reviewable.io -->

2022-08-10 20:44 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860)* status: 4 of 28 files reviewed, 6 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[`iterator.go` line 581 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N950nE416MnGVXqxmxe:-N98SSBw1FMDgzcX_ig7:b3jz0oi) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L581)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you remind me when is this if-block taken. Is it possible that both this block and the if-block following this will get executed in which case `i.key` is the same as `i.iterKey.UserKey` are the same.
</blockquote></details>

thanks for calling this out. this case would never be hit. I pulled it from `nextUserKey`, and `nextUserKey` uses it when switching directions.
___
*[`iterator.go` line 602 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N8zo_1d3MD1OoIkIfFw:-N98N9oF5VYRoVFgrAaT:box5ah3) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L602)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am similarly confused. We seem to be defining the behavior for these other cases, but then panicking when those happen.
</blockquote></details>

I reworded the comment above this invariant. The above comment is attempting to explain why this function `nextPrefixKey`–distinct from `NextPrefix`–will never be called under these circumstances.
___
*[`iterator.go` line 607 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N953y9jCNfO01aN_HVO:-N98Nne86jRIjwtsorDL:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L607)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

where in CockroachDB do we expect to use this? Aren't all the CockroachDB code-paths falling back to seek, which this is not, so in some cases this could be a regression?
</blockquote></details>

Done.
___
*[`iterator.go` line 642 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N953MC55wlnPIekqk-2:-N98SKMg063-GGDoLsMs:bd3lkk4) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L642)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

suffix(i.iterKey) < suffix(prev key) => user key has changed
and the prefix must also have changed.
Can this be used to improve the optimization.
</blockquote></details>

yeah, added
___
*[`iterator.go` line 607 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N954ZDt8-1-294UYPWq:-N98NnMY35qAti_WBrCh:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/1b2c91d2075fe61765eec2584891739bba7db0dc/iterator.go#L607)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

never mind my comment about seeking, on the previous commit.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-10 22:00 UTC, jbowens reviewed
I ran the MVCC scan benchmarks:

```
name                                                                     old time/op    new time/op     delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=0-10           4.24µs ± 4%     4.08µs ± 1%    -3.92%  (p=0.048 n=5+5)
MVCCScan_Pebble/rows=1/versions=2/valueSize=64/numRangeKeys=0-10           4.74µs ± 6%     4.11µs ± 3%   -13.39%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=10/valueSize=64/numRangeKeys=0-10          5.69µs ± 3%     4.59µs ± 0%   -19.38%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=100/valueSize=64/numRangeKeys=0-10         10.3µs ±17%      7.7µs ± 1%   -25.43%  (p=0.016 n=5+4)
MVCCScan_Pebble/rows=1/versions=1000/valueSize=64/numRangeKeys=0-10        41.1µs ± 7%     30.8µs ± 4%   -25.21%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64/numRangeKeys=0-10         23.0µs ± 6%     22.4µs ± 0%      ~     (p=0.690 n=5+5)
MVCCScan_Pebble/rows=100/versions=2/valueSize=64/numRangeKeys=0-10         27.6µs ± 0%     27.6µs ± 0%      ~     (p=0.206 n=5+5)
MVCCScan_Pebble/rows=100/versions=10/valueSize=64/numRangeKeys=0-10        64.6µs ± 0%     55.2µs ± 1%   -14.44%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=100/versions=100/valueSize=64/numRangeKeys=0-10        176µs ± 0%      125µs ± 2%   -28.58%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=100/versions=1000/valueSize=64/numRangeKeys=0-10      1.22ms ± 6%     0.61ms ± 4%   -50.19%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64/numRangeKeys=0-10       1.35ms ± 0%     1.42ms ± 0%    +5.19%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10000/versions=2/valueSize=64/numRangeKeys=0-10       1.84ms ± 0%     1.86ms ± 0%    +1.06%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10000/versions=10/valueSize=64/numRangeKeys=0-10      5.34ms ± 1%     4.42ms ± 1%   -17.19%  (p=0.016 n=4+5)
MVCCScan_Pebble/rows=10000/versions=100/valueSize=64/numRangeKeys=0-10     15.8ms ± 3%     10.9ms ± 3%   -31.38%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10000/versions=1000/valueSize=64/numRangeKeys=0-10     124ms ± 9%       63ms ±28%   -49.08%  (p=0.008 n=5+5)

name                                                                     old speed      new speed       delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=0-10         15.1MB/s ± 4%   15.7MB/s ± 1%      ~     (p=0.056 n=5+5)
MVCCScan_Pebble/rows=1/versions=2/valueSize=64/numRangeKeys=0-10         13.5MB/s ± 5%   15.6MB/s ± 3%   +15.39%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=10/valueSize=64/numRangeKeys=0-10        11.3MB/s ± 3%   14.0MB/s ± 0%   +23.99%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=100/valueSize=64/numRangeKeys=0-10       6.25MB/s ±15%   8.32MB/s ± 1%   +33.21%  (p=0.016 n=5+4)
MVCCScan_Pebble/rows=1/versions=1000/valueSize=64/numRangeKeys=0-10      1.56MB/s ± 7%   2.08MB/s ± 4%   +33.63%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64/numRangeKeys=0-10        279MB/s ± 6%    286MB/s ± 0%      ~     (p=0.690 n=5+5)
MVCCScan_Pebble/rows=100/versions=2/valueSize=64/numRangeKeys=0-10        232MB/s ± 0%    232MB/s ± 0%      ~     (p=0.206 n=5+5)
MVCCScan_Pebble/rows=100/versions=10/valueSize=64/numRangeKeys=0-10      99.1MB/s ± 0%  115.9MB/s ± 1%   +16.88%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=100/versions=100/valueSize=64/numRangeKeys=0-10     36.4MB/s ± 0%   51.0MB/s ± 2%   +40.03%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=100/versions=1000/valueSize=64/numRangeKeys=0-10    5.25MB/s ± 6%  10.53MB/s ± 4%  +100.65%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64/numRangeKeys=0-10      475MB/s ± 0%    452MB/s ± 0%    -4.94%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10000/versions=2/valueSize=64/numRangeKeys=0-10      347MB/s ± 0%    344MB/s ± 0%    -1.04%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10000/versions=10/valueSize=64/numRangeKeys=0-10     120MB/s ± 1%    145MB/s ± 1%   +20.77%  (p=0.016 n=4+5)
MVCCScan_Pebble/rows=10000/versions=100/valueSize=64/numRangeKeys=0-10   40.5MB/s ± 3%   59.0MB/s ± 3%   +45.74%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10000/versions=1000/valueSize=64/numRangeKeys=0-10  5.17MB/s ± 9%  10.35MB/s ±24%  +100.08%  (p=0.008 n=5+5)
```

I'm going to try to narrow in on the `rows=10000/versions=1` and `rows=10000/versions=2` subbenchmarks that show a slight regression. Maybe it's noise, or maybe some of the optimizations in that top-level `Next` loop are actually deoptimizations.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860#-:-N98kg0K5i4GhjhX5lgv:b-lufmbx)* status: 4 of 28 files reviewed, 6 unresolved discussions (waiting on @nicktrav and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-08-11 15:45 UTC, jbowens reviewed
> I'm going to try to narrow in on the rows=10000/versions=1 and rows=10000/versions=2 subbenchmarks that show a slight regression. Maybe it's noise, or maybe some of the optimizations in that top-level Next loop are actually deoptimizations.

This was the various top-level Next optimizations, like comparing suffixes first. The MVCCScan_Pebble benchmark writes all the keys at the same timestamp, so it was a de-optimization there. I removed it for now until we have a more representative benchmark that does indicate it's worth it.

Updated the commit and PR description with the latest numbers.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860#-:-N9CZpOMCR4NQZYqANCt:b-q98obw)* status: 4 of 28 files reviewed, 6 unresolved discussions (waiting on @nicktrav and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-08-11 17:57 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860)* status: 4 of 28 files reviewed, 7 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[`merging_iter.go` line 1129 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9D1sSc6vhRG6jUhJSy:-N9D1sSc6vhRG6jUhJSz:b-vae50j) ([raw file](https://github.com/cockroachdb/pebble/blob/a66095e6ba525896c9e0ec64217cd6c201542f63/merging_iter.go#L1129)):*
> ```Go
> 		m.nextEntry(item, succKey)
> 		prevIndex = item.index
> 	}
> ```

@sumeerbhola — it seems like similar optimizations could be done in the general SeekGE with TrySeekUsingNext case, wdyt?


<!-- Sent from Reviewable.io -->

2022-08-11 22:33 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860)* status: 4 of 28 files reviewed, 9 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[`-- commits` line 11 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9E-ENX5X_cY9BV1NyS):*
I think I am missing something regarding "instead of finding each new user key". Are we saving this cost in the top-level iterator?
___
*[`iterator.go` line 651 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9E-so32r9lbU2sxDhT:-N9E-so32r9lbU2sxDhU:b-jf8q3v) ([raw file](https://github.com/cockroachdb/pebble/blob/762aaeb1f6e72c48277e8f954852e8494153c155/iterator.go#L651)):*
> ```Go
> 	// unconditionally.
> 	i.prefixOrFullSeekKey = i.comparer.ImmediateSuccessor(i.prefixOrFullSeekKey[:0], i.key[:currentPrefixLen])
> 	i.iterKey, i.iterValue = i.iter.NextPrefix(i.prefixOrFullSeekKey)
> ```

Is there a reason why this cannot be a `i.iter.SeekGE` call with `seekGEFlagTrySeekUsingNext`?

In general, I am still mulling over this optimization (a) I don't have a clear mental model of what parts of the iterator stack we are trying to optimize (in comparison, for the various earlier try-seek-using-next optimizations, it was clear that we were trying to save the ssblock reload and binary search), (b) whether the optimizations are "significant" to warrant the additional complexity, (c) is there a cleaner optimization approach that can subsume what we have done in the past (which has added complexity), and makes our code more understandable.

Is there a need to merge this before stability? Maybe a synchronous session early next week would help clear my doubts.
___
*[`merging_iter.go` line 1129 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9D1sSc6vhRG6jUhJSy:-N9Dy-Nm4ks_vXHFlNHp:b6u42xs) ([raw file](https://github.com/cockroachdb/pebble/blob/a66095e6ba525896c9e0ec64217cd6c201542f63/merging_iter.go#L1129)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

@sumeerbhola — it seems like similar optimizations could be done in the general SeekGE with TrySeekUsingNext case, wdyt?
</blockquote></details>

I don't quite understand what "similar optimizations" means. Currently the `trySeekUsingNext` are passed down to the leaf iterators in the tree, where the optimization is applied (especially for sstable iterators), and `mergingIter` and `levelIter` don't have much to do with it. Are you suggesting that `mergingIter` could figure out that it does not even need to call down to some files because they are already positioned at the right place, i.e., avoiding a noop method call?


<!-- Sent from Reviewable.io -->

2022-08-12 02:02 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860)* status: 4 of 28 files reviewed, 9 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[`-- commits` line 11 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9E-ENX5X_cY9BV1NyS):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think I am missing something regarding "instead of finding each new user key". Are we saving this cost in the top-level iterator?
</blockquote></details>

Yeah, for example the pebbleMVCCScanner saves a key comparison and a key copy:

```
1:  (memcpy) pebbleMVCCScanner saves iter.Key()
2:           pebbleMVCCScanner calls iter.Next
3:           (pebble.Iterator).Next()
4:               (pebble.Iterator).nextUserKey
5:  (memcmp)         i.equal(key, i.iterKey.UserKey)
6:                   <...repeat nextUserKey until new user key...>
7:               (pebble.Iterator).findNextEntry
8:  (memcpy)     save i.iterKey to i.key
9:  (memcmp) is iter.Key() a new prefix?
10:          <...repeat Next...>
```
vs

```
1:           pebbleMVCCScanner calls iter.NextPrefix
2:           (pebble.Iterator).NextPrefix()
3:               (pebble.Iterator).nextPrefixKey
4:  (memcmp)         i.equal(key[:ki], i.iterKey.UserKey[:iki])
5:                   <...repeat nextUserKey until new prefix...>
6:               (pebble.Iterator).findNextEntry
7:  (memcpy)         save i.iterKey to i.key
```
___
*[`iterator.go` line 651 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9E-so32r9lbU2sxDhT:-N9EkMLfDtbMRZ2GeT07:bad2rjd) ([raw file](https://github.com/cockroachdb/pebble/blob/762aaeb1f6e72c48277e8f954852e8494153c155/iterator.go#L651)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is there a reason why this cannot be a `i.iter.SeekGE` call with `seekGEFlagTrySeekUsingNext`?

In general, I am still mulling over this optimization (a) I don't have a clear mental model of what parts of the iterator stack we are trying to optimize (in comparison, for the various earlier try-seek-using-next optimizations, it was clear that we were trying to save the ssblock reload and binary search), (b) whether the optimizations are "significant" to warrant the additional complexity, (c) is there a cleaner optimization approach that can subsume what we have done in the past (which has added complexity), and makes our code more understandable.

Is there a need to merge this before stability? Maybe a synchronous session early next week would help clear my doubts.
</blockquote></details>

The original motivation for not using SeekGE was that if the keyspace is covered by a range key, the interleaving iterator will unnecessarily interleave the range key at the seek key. This particular issue could be avoided through a simple `SeekGEFlags`.

I think the remaining bits of the optimization that warrant a separate internal iterator method are the bits that depend on the external knowledge of a proximate seek key (see the other comment).

 > Is there a need to merge this before stability?

I'd like to get something in this release to avoid the scan regression that integrating with range keys introduced. I'm down for a synchronous session next week, but this PR is substantial enough that merging it once stability starts is questionable.
___
*[`merging_iter.go` line 1129 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9D1sSc6vhRG6jUhJSy:-N9Ed2gSBleAiHlS68rZ:b-8h5fzw) ([raw file](https://github.com/cockroachdb/pebble/blob/a66095e6ba525896c9e0ec64217cd6c201542f63/merging_iter.go#L1129)):*
>  i.e., avoiding a noop method call?

Yeah, including its key comparisons (finding the right file within the level, comparing against the index keys, and then finally against the seek key).  

The effectiveness of this optimization depends on the proximity of the seek key. _If_ we have an expectation that the seek key proximate to the current iterator position, then there are likely only a few of the levels that need to be re-positioned at all. We can seek the top of the heap to the seek key (still propagating `trySeekUsingNext` to optimize the leaf iterator calls), and then fixup the heap. If a different level is now at the top of the heap, repeat. Whenever we one of the previously seeked levels is at the heap root, we're done.

The above's worst case is worse. If all L levels need to be repositioned we're paying all the ordinary seeks costs per-leaf iter, _and_ we pay the O(log L) heap update cost L times, instead of the usual O(L) to heapify once.

I think this optimization makes a lot of sense in the context of `NextPrefix` where our expectation is that there are very few levels that may contain keys with the next prefix.

I think it might make sense in other SeekGE cases in Cockroach where we have some external knowledge that the seek key is proximate, but we'd need an interface to signal that.


<!-- Sent from Reviewable.io -->

2022-08-15 12:53 UTC, sumeerbhola approved these changes
> Reviewed 2 of 9 files at r1, 2 of 24 files at r5, 7 of 20 files at r6, 2 of 7 files at r7, 1 of 1 files at r8, 6 of 12 files at r9, 2 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860)* status: 23 of 28 files reviewed, 16 unresolved discussions (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[`-- commits` line 39 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WUtUl0u101nsMaBPD):*
is this huge gain with large number of versions because most of the levels are already at the next prefix? Or because the key-value pairs are small enough and compressible that even with 1000 versions they are often fitting into the same block? I am just trying to get some intuition into why these high version results are so much better with NextPrefix vs SeekGE.
___
*[`batch.go` line 1752 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WShJg7CdDQrpcClJR:-N9WShJg7CdDQrpcClJS:b-pzav95) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/batch.go#L1752)):*
> ```Go
> 
> // Note: flushFlushableBatchIter.Next mirrors the implementation of
> // flushableBatchIter.Next due to performance. Keep the two in sync.
> ```

Did this mean to say `NextPrefix`. Also, `flushFlushableBatchIter` doesn't seem to have a `NextPrefix` method.
___
*[`iterator.go` line 581 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N950nE416MnGVXqxmxe:-N9WTcHS46yPnDdVOrSU:b-llfs4i) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L581)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

thanks for calling this out. this case would never be hit. I pulled it from `nextUserKey`, and `nextUserKey` uses it when switching directions.
</blockquote></details>

nit: do we need to guard this with invariants.Enabled given the simple enum comparison?
___
*[`iterator.go` line 651 at r8](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9E-so32r9lbU2sxDhT:-N9WUcsu0BlkbMJQmINR:b-9qo32n) ([raw file](https://github.com/cockroachdb/pebble/blob/762aaeb1f6e72c48277e8f954852e8494153c155/iterator.go#L651)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

The original motivation for not using SeekGE was that if the keyspace is covered by a range key, the interleaving iterator will unnecessarily interleave the range key at the seek key. This particular issue could be avoided through a simple `SeekGEFlags`.

I think the remaining bits of the optimization that warrant a separate internal iterator method are the bits that depend on the external knowledge of a proximate seek key (see the other comment).

 > Is there a need to merge this before stability?

I'd like to get something in this release to avoid the scan regression that integrating with range keys introduced. I'm down for a synchronous session next week, but this PR is substantial enough that merging it once stability starts is questionable.
</blockquote></details>

Ack. This now makes sense.
___
*[`iterator.go` line 649 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WUPBN1w2v2jLnzSLV:-N9WUPBN1w2v2jLnzSLW:b-s4foxt) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/iterator.go#L649)):*
> ```Go
> 	//
> 	// TODO(jackson): NextPrefix might be performant enough that we can call it
> 	// unconditionally.
> ```

not clear to me what this TODO is saying, since there isn't a condition here. Is it referring to the next calls earlier in this function? 
___
*[`level_iter.go` line 824 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WVrmk6ELH8veTukpi:-N9WVrmk6ELH8veTukpj:bgqkyb9) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/level_iter.go#L824)):*
> ```Go
> 	}
> 
> 	if l.largestBoundary == nil {
> ```

This method is slightly different from `Next`. Can you elaborate on why the differences?
___
*[`merging_iter.go` line 1129 at r7](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9D1sSc6vhRG6jUhJSy:-N9WWhTz9LnDYsWE3Ko8:b-a7jufr) ([raw file](https://github.com/cockroachdb/pebble/blob/a66095e6ba525896c9e0ec64217cd6c201542f63/merging_iter.go#L1129)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

>  i.e., avoiding a noop method call?

Yeah, including its key comparisons (finding the right file within the level, comparing against the index keys, and then finally against the seek key).  

The effectiveness of this optimization depends on the proximity of the seek key. _If_ we have an expectation that the seek key proximate to the current iterator position, then there are likely only a few of the levels that need to be re-positioned at all. We can seek the top of the heap to the seek key (still propagating `trySeekUsingNext` to optimize the leaf iterator calls), and then fixup the heap. If a different level is now at the top of the heap, repeat. Whenever we one of the previously seeked levels is at the heap root, we're done.

The above's worst case is worse. If all L levels need to be repositioned we're paying all the ordinary seeks costs per-leaf iter, _and_ we pay the O(log L) heap update cost L times, instead of the usual O(L) to heapify once.

I think this optimization makes a lot of sense in the context of `NextPrefix` where our expectation is that there are very few levels that may contain keys with the next prefix.

I think it might make sense in other SeekGE cases in Cockroach where we have some external knowledge that the seek key is proximate, but we'd need an interface to signal that.
</blockquote></details>

I see. Thanks for the explanation.
___
*[`internal/base/iterator.go` line 163 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WW37BD6dUUAGExsQG:-N9WW37BD6dUUAGExsQH:b1r1azr) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/internal/base/iterator.go#L163)):*
> ```Go
> 	// valid implementation of NextPrefix is to call SeekGE with succKey.
> 	//
> 	// It is valid to call NextPrefix when the iterator is positioned before the
> ```

Are we actually ever using this when switching directions? My understanding was no, since `Iterator.nextPrefixKey` is the only caller. Could we use that to simplify the implementations a bit?
___
*[`sstable/reader.go` line 1069 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WYCM04ZHgHzEutCJY:-N9WYCM04ZHgHzEutCJZ:b-gqldu3) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/sstable/reader.go#L1069)):*
> ```Go
> 
> func (i *singleLevelIterator) skipForward(lowerBound []byte) (*InternalKey, []byte) {
> 	const nextsBeforeSeek = 3
> ```

We have already failed with `NextPrefix` on the current data block before falling into this path. What is the justification fro trying again to do nexts? It's a bit unfortunate that we are having to complicate `skipForward` with index seeks for this case. Can we move the index seek to `NextPrefix`?
___
*[`sstable/reader.go` line 1914 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WYhup6wq-LEpOOmoW:-N9WYhuqCQp_H4zYuPCm:bvqp4za) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/sstable/reader.go#L1914)):*
> ```Go
> 			return nil, nil
> 		}
> 		if lowerBound != nil && i.cmp(ikey.UserKey, lowerBound) < 0 {
> ```

A comment would be helpful, in that by comparing the upper bound we know that this block cannot have a key that satisfies our requirement. Though if the upper bound of the block is higher, it still may only contain keys < lowerBound. Seems like this would return a key < lowerBound in that case. What am I missing?


<!-- Sent from Reviewable.io -->

2022-11-21 16:02 UTC, sumeerbhola requested changes
I'm taking a look again at this PR, in the hope that we can drive this over the finish line. I was trying to look mostly where we have complexity etc., and added some comments below (in addition to the previous unresolved comments).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860#-:-NHPmnSDAuyF96-RfM6X:bysc0co)* status: 23 of 28 files reviewed, 21 unresolved discussions (waiting on @jbowens and @nicktrav)

___
*[`batch.go` line 1319 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NHPnzeQCJgkvm0GElRZ:-NHPnzeQCJgkvm0GElR_:b-l1qqed) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/batch.go#L1319)):*
> ```Go
> 	for ikey != nil && (ikey.SeqNum() >= i.snapshot || i.cmp(ikey.UserKey, succKey) < 0) {
> 		ikey = i.iter.Next()
> 	}
> ```

why not seek after 3 nexts like in blockIter?
___
*[`batch.go` line 1752 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WShJg7CdDQrpcClJR:-NHPnsIW1aqJyR-dhfh1:b-uf76n6) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/batch.go#L1752)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Did this mean to say `NextPrefix`. Also, `flushFlushableBatchIter` doesn't seem to have a `NextPrefix` method.
</blockquote></details>

Is there a reason we don't do Next's here, like we do in batchIter?
___
*[`iterator.go` line 607 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N953y9jCNfO01aN_HVO:-NHPoMxwDbBYyjIV1b9X:b-wtzr16) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L607)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

With `TableFormatPebblev3` doing these Nexts is not good since we will lose the optimization due to `setHasSamePrefix` that allows us to not do prefix comparisons. Can we do the following TODO right away. It does give a Next-ing budget to each InternalIterator so won't call seek immediately. I am curious what the benchmark numbers will look like with that change.
```
	// After nexting a few times, we still haven't found the next prefix. Use
	// the slightly more expensive NextPrefix, which may seek in some levels of
	// the iterator stack.
	//
	// TODO(jackson): NextPrefix might be performant enough that we can call it
	// unconditionally.
```
___
*[`iterator.go` line 1420 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NHPpwGm6pYf_ECGM4EZ:-NHPpwGm6pYf_ECGM4E_:bmqcx2b) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/iterator.go#L1420)):*
> ```Go
> //
> // When switching directions or called after NextWithLimit returns IterAtLimit,
> // NextPrefix moves the iterator to the next user key, regardless of prefix.
> ```

I am slightly concerned about this semantic difference, in that it doesn't make any sense to support these cases. So I would prefer to say that these are an invariant violation (and we should check when `invariants.Enabled`).
___
*[`level_iter.go` line 831 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NHPsj0j0FnsqN1aKXtH:-NHPsj0j0FnsqN1aKXtI:bjax5ol) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/level_iter.go#L831)):*
> ```Go
> 		}
> 	}
> 	return l.verify(l.skipEmptyFileForward())
> ```

if we switch to the next file and it is continuing with the same prefix, won't we return something less than `succKey`, which is incorrect?
___
*[`merging_iter.go` line 1120 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NHPrkUa9Gm68Zzshy20:-NHPrkUa9Gm68Zzshy21:b6bgdpw) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/merging_iter.go#L1120)):*
> ```Go
> 	}
> 	if m.levelsPositioned == nil {
> 		m.levelsPositioned = make([]bool, len(m.levels))
> ```

can we avoid this allocation via `iterAlloc`?
___
*[`internal/base/iterator.go` line 163 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WW37BD6dUUAGExsQG:-NHPsEuB29ntFNp9_EXw:b91rrnu) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/internal/base/iterator.go#L163)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are we actually ever using this when switching directions? My understanding was no, since `Iterator.nextPrefixKey` is the only caller. Could we use that to simplify the implementations a bit?
</blockquote></details>

Adding to this, I would prefer to make this is an invariant violation.
___
*[`sstable/reader.go` line 1022 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NHPt_7wByyw6NstDBbc:-NHPt_7x2vjx2kqOG8u3:b-e8pz09) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/sstable/reader.go#L1022)):*
> ```Go
> 
> // NextPrefix implements (base.InternalIterator).NextPrefix.
> func (i *singleLevelIterator) NextPrefix(succKey []byte) (*InternalKey, []byte) {
> ```

I am going to assume that this `NextPrefix` approach is settled and that this PR will merge soon. I can start implementing NextPrefix for v3 sstables.
___
*[`sstable/reader.go` line 1069 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WYCM04ZHgHzEutCJY:-NHPtzi2D58MlMM3nTXf:b-jfgrg6) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/sstable/reader.go#L1069)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We have already failed with `NextPrefix` on the current data block before falling into this path. What is the justification fro trying again to do nexts? It's a bit unfortunate that we are having to complicate `skipForward` with index seeks for this case. Can we move the index seek to `NextPrefix`?
</blockquote></details>

Looking at this again, I do think we should SeekGE if NextPrefix was not satisfied in the existing data block. If there are few versions, we will typically not straddle data blocks so the common case will work well. The only bad situation is with huge key-value pairs, but then if we are commonly straddling data blocks the next data block may not be the right one either.


<!-- Sent from Reviewable.io -->

2022-11-30 18:24 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860)* status: 1 of 29 files reviewed, 18 unresolved discussions (waiting on @nicktrav and @sumeerbhola)

___
*[`batch.go` line 1319 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NHPnzeQCJgkvm0GElRZ:-NI4OcCbENh-jm4awN1L:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/batch.go#L1319)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why not seek after 3 nexts like in blockIter?
</blockquote></details>

Done.
___
*[`batch.go` line 1752 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WShJg7CdDQrpcClJR:-NI4Of9m5jAQ7reDNRFb:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/batch.go#L1752)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is there a reason we don't do Next's here, like we do in batchIter?
</blockquote></details>

Done.
___
*[`iterator.go` line 581 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N950nE416MnGVXqxmxe:-NI8jEp_9hRpWxJnzdvw:bvvpcss) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L581)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: do we need to guard this with invariants.Enabled given the simple enum comparison?
</blockquote></details>

i believe post-refactor this is no longer relevant.
___
*[`iterator.go` line 607 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N953y9jCNfO01aN_HVO:-NI8ADp15DzBp48JOpre:bqshqci) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L607)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

With `TableFormatPebblev3` doing these Nexts is not good since we will lose the optimization due to `setHasSamePrefix` that allows us to not do prefix comparisons. Can we do the following TODO right away. It does give a Next-ing budget to each InternalIterator so won't call seek immediately. I am curious what the benchmark numbers will look like with that change.
```
	// After nexting a few times, we still haven't found the next prefix. Use
	// the slightly more expensive NextPrefix, which may seek in some levels of
	// the iterator stack.
	//
	// TODO(jackson): NextPrefix might be performant enough that we can call it
	// unconditionally.
```


</blockquote></details>

I tried unconditionally calling NextPrefix, and unfortunately it causes a ~3-4% regression relative to master. Adding a single `Next` before calling `NextPrefix` changes it to a 0-2% improvement over master. I think it's due to:

1. calling `ImmediateSuccessor` to prepare for NextPrefix requires a key copy
2. if the next prefix is in a different level, currently calling `i.iter.NextPrefix` requires two key comparisons: the leaf sstable iterator will perform a key comparison against `succKey`, and the merging iterator will perform a key comparison when a new level becomes the heap root to determine whether or not calling the child iterator's `NextPrefix` is necessary.

The `setHasSamePrefix` optimization will remove that leaf sstable iterator key comparison, leaving us with a `ImmediateSuccessor` key copy and a `Compare` call and possibly a merging iterator key comparison if the heap root level changes. That's versus one `bytes.Equal` in the i.iter.Next case.

I think we could conceivably lazily compute `ImmediateSuccessor` by passing a `func() []byte` down the iterator stack, which is a pointer to a function on the iterator that returns `prefixOrFullSeekKey`, populating it using `ImmediateSuccessor` if it hasn't already. We could pass the `i.key` prefix as an additional `NextPrefix` argument, so that the merging iterator can perform a `bytes.Equal` instead of a `Compare`.

I think for now we should go with the single `i.iter.Next`, and then we can circle back to see if those other optimizations let us unconditionally `NextPrefix`.
___
*[`iterator.go` line 649 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WUPBN1w2v2jLnzSLV:-NI8jJpC86i5HnfK1Xgp:b-30uu5z) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/iterator.go#L649)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

not clear to me what this TODO is saying, since there isn't a condition here. Is it referring to the next calls earlier in this function? 
</blockquote></details>

I think this comment is also on since-removed code.
___
*[`iterator.go` line 1420 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NHPpwGm6pYf_ECGM4EZ:-NI8GUXf19_JgfAMqH4w:bqafswj) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/iterator.go#L1420)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am slightly concerned about this semantic difference, in that it doesn't make any sense to support these cases. So I would prefer to say that these are an invariant violation (and we should check when `invariants.Enabled`).
</blockquote></details>

I added support for these cases only because it aids in metamorphic test integration. Otherwise, we'd need to prohibit the generator from producing `NextPrefix` operations after reverse iteration operations or forward operations `-WithLimit`. We don't have any mechanism to do this yet. How about documenting the behavior as undefined in these cases, and when we improve the metamorphic tests we can remove functional support for these cases?
___
*[`level_iter.go` line 824 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WVrmk6ELH8veTukpi:-NI8IJua7WEfrQRUEDMT:b-sb1d2q) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/level_iter.go#L824)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This method is slightly different from `Next`. Can you elaborate on why the differences?
</blockquote></details>

Updated to more closely mirror `Next`—previously the code always fell back to a seek when the file was exhausted. Now we only fall back to seeking in the cases we need to, and preserve symmetry with Next.
___
*[`level_iter.go` line 831 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NHPsj0j0FnsqN1aKXtH:-NI8R5mj-gfbDDvKWE1Y:bnrhe87) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/level_iter.go#L831)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

if we switch to the next file and it is continuing with the same prefix, won't we return something less than `succKey`, which is incorrect?
</blockquote></details>

If SeekGE moves to a next file, it disables TrySeekUsingNext. I updated this to handle the seeking explicitly anyways, so we explicitly switch to a new file and explicitly seek within the file using `base.SeekGEFlagsNone`.
___
*[`merging_iter.go` line 1120 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NHPrkUa9Gm68Zzshy20:-NI8UAA4Ay-EAszE2Hos:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/merging_iter.go#L1120)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can we avoid this allocation via `iterAlloc`?
</blockquote></details>

Done.
___
*[`sstable/reader.go` line 1022 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NHPt_7wByyw6NstDBbc:-NHVC3Hv4adiOeH8fERV:b2nhb2c) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/sstable/reader.go#L1022)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am going to assume that this `NextPrefix` approach is settled and that this PR will merge soon. I can start implementing NextPrefix for v3 sstables [...]

2022-12-11 05:53 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 10 of 25 files at r11, 5 of 11 files at r13, 5 of 7 files at r14, 5 of 5 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860#-:-NIzjXdu-dbX1bIf6e6J:bg7igkv)* status: 26 of 29 files reviewed, 22 unresolved discussions (waiting on @jbowens)

___
*[`batch.go` line 1752 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WShJg7CdDQrpcClJR:-NIz8dtIDakPe-BiKaL9:b-oqgnwr) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/batch.go#L1752)):*
> Did this mean to say NextPrefix. Also, flushFlushableBatchIter doesn't seem to have a NextPrefix method.

Overlooked comment?
___
*[`batch.go` line 1790 at r15](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NIz8TMW6o9F-LY1AzuF:-NIz8TMW6o9F-LY1AzuG:boza9th) ([raw file](https://github.com/cockroachdb/pebble/blob/2a0d6891dff3c93dddc2c438a5366b4ad8626468/batch.go#L1790)):*
> ```Go
> 
> // Note: flushFlushableBatchIter.Next mirrors the implementation of
> // flushableBatchIter.Next due to performance. Keep the two in sync.
> ```

NextPrefix?
___
*[`iterator.go` line 607 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N953y9jCNfO01aN_HVO:-NIzcEhD3LfnMXeuLK3J:b-mv0bvj) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L607)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I tried unconditionally calling NextPrefix, and unfortunately it causes a ~3-4% regression relative to master. Adding a single `Next` before calling `NextPrefix` changes it to a 0-2% improvement over master. I think it's due to:

1. calling `ImmediateSuccessor` to prepare for NextPrefix requires a key copy
2. if the next prefix is in a different level, currently calling `i.iter.NextPrefix` requires two key comparisons: the leaf sstable iterator will perform a key comparison against `succKey`, and the merging iterator will perform a key comparison when a new level becomes the heap root to determine whether or not calling the child iterator's `NextPrefix` is necessary.

The `setHasSamePrefix` optimization will remove that leaf sstable iterator key comparison, leaving us with a `ImmediateSuccessor` key copy and a `Compare` call and possibly a merging iterator key comparison if the heap root level changes. That's versus one `bytes.Equal` in the i.iter.Next case.

I think we could conceivably lazily compute `ImmediateSuccessor` by passing a `func() []byte` down the iterator stack, which is a pointer to a function on the iterator that returns `prefixOrFullSeekKey`, populating it using `ImmediateSuccessor` if it hasn't already. We could pass the `i.key` prefix as an additional `NextPrefix` argument, so that the merging iterator can perform a `bytes.Equal` instead of a `Compare`.

I think for now we should go with the single `i.iter.Next`, and then we can circle back to see if those other optimizations let us unconditionally `NextPrefix`.
</blockquote></details>

Doing one `i.iter.Next` sounds good.
___
*[`iterator.go` line 1420 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NHPpwGm6pYf_ECGM4EZ:-NIzb56g3Fq94j6eBPFp:b-hfghm4) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/iterator.go#L1420)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I added support for these cases only because it aids in metamorphic test integration. Otherwise, we'd need to prohibit the generator from producing `NextPrefix` operations after reverse iteration operations or forward operations `-WithLimit`. We don't have any mechanism to do this yet. How about documenting the behavior as undefined in these cases, and when we improve the metamorphic tests we can remove functional support for these cases?
</blockquote></details>

Sounds good
___
*[`internal/keyspan/interleaving_iter.go` line 489 at r15](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NIzivK0AEHVy6X3k2kU:-NIzivK1De41UjpM-0eD:b-ur25lt) ([raw file](https://github.com/cockroachdb/pebble/blob/2a0d6891dff3c93dddc2c438a5366b4ad8626468/internal/keyspan/interleaving_iter.go#L489)):*
> ```Go
> 
> 	// Refresh the point key if the current point key has already been
> 	// interleaved.
> ```

Comment could do with some updating in light of the more complicated conditional.
___
*[`internal/keyspan/interleaving_iter.go` line 708 at r15](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NIzjTEr--07vJNFhAF7:-NIzjTEr--07vJNFhAF8:bb7lbs2) ([raw file](https://github.com/cockroachdb/pebble/blob/2a0d6891dff3c93dddc2c438a5366b4ad8626468/internal/keyspan/interleaving_iter.go#L708)):*
> ```Go
> 					// TODO(jackson): If we thread a base.Comparer through to
> 					// InterleavingIter so that we have access to
> 					// ImmediateSuccessor, we could use NextPrefix. We'd need to
> ```

nice
___
*[`iterator_test.go` line 2782 at r15](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NIzhOVA4GHNNWmD1FjI:-NIzhOVA4GHNNWmD1FjJ:biy3719) ([raw file](https://github.com/cockroachdb/pebble/blob/2a0d6891dff3c93dddc2c438a5366b4ad8626468/iterator_test.go#L2782)):*
> ```Go
> 
> 		// Portion the keys into `readAmp` overlapping key sets.
> 		for _, ks := range testkeys.Divvy(keys, readAmp) {
> ```

does this use of `Divvy` mean that the nextprefix will surely be in a different level than the heap root?


<!-- Sent from Reviewable.io -->

2022-12-12 18:40 UTC, jbowens reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1860#-:-NJ6cdziC9EM8V4ZDr2v:b-814g8k)* status: 26 of 29 files reviewed, 22 unresolved discussions (waiting on @sumeerbhola)

___
*[`batch.go` line 1752 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WShJg7CdDQrpcClJR:-NJ6cBCWEEaq87ruFjgQ:b5t3ztw) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/batch.go#L1752)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> Did this mean to say NextPrefix. Also, flushFlushableBatchIter doesn't seem to have a NextPrefix method.

Overlooked comment?
</blockquote></details>

yeah, added a `flushFlushableBatchIter.NextPrefix` method (that panics with "unimplemented")
___
*[`batch.go` line 1790 at r15](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NIz8TMW6o9F-LY1AzuF:-NJ6Uo_N318LzVxiLxRf:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/2a0d6891dff3c93dddc2c438a5366b4ad8626468/batch.go#L1790)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

NextPrefix?
</blockquote></details>

Done.
___
*[`iterator.go` line 607 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N953y9jCNfO01aN_HVO:-NJ6VegJ6Da-PhQGzUiQ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/3bdc85d47264c54ba9ef37041217266e07e0b394/iterator.go#L607)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Doing one `i.iter.Next` sounds good.
</blockquote></details>

Done.
___
*[`iterator.go` line 1420 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NHPpwGm6pYf_ECGM4EZ:-NJ6Vgdt98GvO0ZBeYTl:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/iterator.go#L1420)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Sounds good
</blockquote></details>

Done.
___
*[`internal/base/iterator.go` line 163 at r10](https://reviewable.io/reviews/cockroachdb/pebble/1860#-N9WW37BD6dUUAGExsQG:-NJ6VhqrDXsSVegf6Kkk:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/69f6d4709ca565922f515bbca83c3f89e42e5989/internal/base/iterator.go#L163)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Adding to this, I would prefer to make this is an invariant violation.
</blockquote></details>

Done.
___
*[`internal/keyspan/interleaving_iter.go` line 489 at r15](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NIzivK0AEHVy6X3k2kU:-NJ6WuTZDahZ1mbIuJyo:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/2a0d6891dff3c93dddc2c438a5366b4ad8626468/internal/keyspan/interleaving_iter.go#L489)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Comment could do with some updating in light of the more complicated conditional.
</blockquote></details>

Done.
___
*[`internal/keyspan/interleaving_iter.go` line 708 at r15](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NIzjTEr--07vJNFhAF7:-NJ6VT2e5iX27sRp7q4z:b32vhw) ([raw file](https://github.com/cockroachdb/pebble/blob/2a0d6891dff3c93dddc2c438a5366b4ad8626468/internal/keyspan/interleaving_iter.go#L708)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nice
</blockquote></details>

:)
___
*[`iterator_test.go` line 2782 at r15](https://reviewable.io/reviews/cockroachdb/pebble/1860#-NIzhOVA4GHNNWmD1FjI:-NJ6c-co7pX_wID9rAPe:b-qskrbt) ([raw file](https://github.com/cockroachdb/pebble/blob/2a0d6891dff3c93dddc2c438a5366b4ad8626468/iterator_test.go#L2782)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

does this use of `Divvy` mean that the nextprefix will surely be in a different level than the heap root?
</blockquote></details>

yeah, it did. I updated it to use a different scheme so that the next prefix is sometimes in the same level, sometimes in another.


<!-- Sent from Reviewable.io -->

2022-12-12 18:47 UTC, merged