db: enforce batch point visibility in the merging iterator
cockroachdb/pebble pull request #1945
Opened 2022-09-06 21:32 UTC by jbowens

Previously, visibility of batch point keys was enforced within the batch iterator. This commit moves this visibility enforcement into the merging iterator, alongside the visibility enforcement of committed keys. Span keys (eg, range deletions and range keys) are still subject to visibility filtering when the batch iterator is constructed, because it's necessary to process all these spans to fragment them appropriately.

This change addresses the pathological behavior observed in cockroachdb/cockroach#87277: filtering keys within leaf iterators can force the leaf iterators to iterate through more keys than necessary. If many mutations are made to a batch since the iterator was opened, the batch iterator may need to iterate over many entries before finding a visible key. This iteration may extend well beyond the next or previous key in the merging iterator.

Using the SeekLT benchmark from cockroachdb/cockroach#87373, relative to master:
```
name                          old time/op  new time/op  delta
SeekLTNext/useBatch=false-10   182ms ± 6%   190ms ± 2%     ~     (p=0.056 n=5+5)
SeekLTNext/useBatch=true-10    2.71s ± 7%   0.18s ± 2%  -93.53%  (p=0.008 n=5+5)
```

And relative to 22.1:
```
name                          old time/op  new time/op  delta
SeekLTNext/useBatch=false-10   182ms ± 6%   185ms ± 2%     ~     (p=0.690 n=5+5)
SeekLTNext/useBatch=true-10    2.71s ± 7%   0.17s ± 2%  -93.68%  (p=0.008 n=5+5)
```

2022-09-06 21:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1945)
<!-- Reviewable:end -->

2022-09-07 13:13 UTC, erikgrinaker commented
Awesome, thanks @jbowens! I'll leave a proper review to the storage team, but this seems great.

2022-09-07 19:54 UTC, sumeerbhola requested changes
> Reviewed 6 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1945)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @aliher1911, @erikgrinaker, and @jbowens)

___
*[`batch.go` line 872 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1945#-NBORPux6A5BPZaPr3TS:-NBORPux6A5BPZaPr3TT:b-kaei5h) ([raw file](https://github.com/cockroachdb/pebble/blob/5aefa5e425cacbdf92a6be89b060607c8496b434/batch.go#L872)):*
> ```Go
> 		// significantly farther than necessary filtering many batch keys that
> 		// are not visible at the batch sequence number. Instead, the merging
> 		// iterator enforces bounds.
> ```

Can you add a small example here.
___
*[`get_iter.go` line 128 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1945#-NBOUGmj2tjxQtCM4ZN4:-NBOUGmj2tjxQtCM4ZN5:bkm9mww) ([raw file](https://github.com/cockroachdb/pebble/blob/5aefa5e425cacbdf92a6be89b060607c8496b434/get_iter.go#L128)):*
> ```Go
> 			}
> 			g.iter = g.batch.newInternalIter(nil)
> 			g.rangeDelIter = g.batch.newRangeDelIter(nil, base.InternalKeySeqNumMax)
> ```

I'm a bit confused here, since I thought we were only using InternalKeySeqNumMax when constructing point iters.
More broadly, I realized I've never looked at `getIter` and it is unclear to me why it works:
- we don't seem to seek to getIter.key anywhere, which would make a get very inefficient. I must be missing something.
- we are creating a batch iter here after closing the iter we have created previously. Do you why we needed to close it? And why are we then continuing to use a tombstone from before, in the `if g.tombstone != nil && g.tombstone.VisibleAt(g.snapshot)` block?
___
*[`iterator.go` line 2003 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1945#-NBOVfUn0ZoZnbmMvHX0:-NBOVfUn0ZoZnbmMvHX1:b-xourx4) ([raw file](https://github.com/cockroachdb/pebble/blob/5aefa5e425cacbdf92a6be89b060607c8496b434/iterator.go#L2003)):*
> ```Go
> 					// No range deletions exist in the batch. We only need to
> 					// update the batchIter's snapshot.
> 					i.batchPointIter.snapshot = nextBatchSeqNum
> ```

So we are also enforcing in the point iter?


<!-- Sent from Reviewable.io -->

2022-09-07 21:28 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1945)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @aliher1911, @erikgrinaker, and @sumeerbhola)

___
*[`batch.go` line 872 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1945#-NBORPux6A5BPZaPr3TS:-NBOkk7e3mRoYCHmYFlt:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/5aefa5e425cacbdf92a6be89b060607c8496b434/batch.go#L872)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a small example here.
</blockquote></details>

Done.
___
*[`get_iter.go` line 128 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1945#-NBOUGmj2tjxQtCM4ZN4:-NBOlKVM9iva0DpWlxdJ:b-xwy6ao) ([raw file](https://github.com/cockroachdb/pebble/blob/5aefa5e425cacbdf92a6be89b060607c8496b434/get_iter.go#L128)):*
>  I thought we were only using InternalKeySeqNumMax when constructing point iters.

This change isn't a functional one, just for consistency. Get always reads the entirety of the batch's history, so no batch keys should be filtered. Previously we were calculating the true batch seqnum for the current batch offset, but there's no point because the use of the seqnum and the getIter are only scoped to this single `Get` call.

yeah, `getIter` has confused me the few times that I've looked at it.

> we don't seem to seek to getIter.key anywhere, which would make a get very inefficient. I must be missing something.

I think down below, whenever we drop to a new level we do:
```
g.iterKey, g.iterValue = g.iter.SeekGE(g.key, base.SeekGEFlagsNone)
```

my understanding is that this function is structured like:
```
for {
    if g.iter != nil {
        // g.iterKey, g.iterValue are initialized with some internal key >= g.key.
        
        // if there's a rangedel deleting g.key, return nil, nil and !Valid()

        // if g.iterKey is not visible, next within this level to try to find a
        // visible key within the level with the same user key, and continue

        // if g.iterKey same user key as g.key, return it.
      
        // otherwise, g.key doesn't exist within the level g.iter and we close g.iter so
        // that we drop down to the next  level of the LSM.
    }

    // drop to the next level of the LSM, setting g.iter to the next level's internal
    // iterator, seeking it to g.key and modifying state so that we won't visit the level
    // again (eg, clearing `g.batch` or incrementing `g.level`).
}
```
___
*[`iterator.go` line 2003 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1945#-NBOVfUn0ZoZnbmMvHX0:-NBOqMbo8gu8tPwwJ8jt:b-o6eb88) ([raw file](https://github.com/cockroachdb/pebble/blob/5aefa5e425cacbdf92a6be89b060607c8496b434/iterator.go#L2003)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So we are also enforcing in the point iter?
</blockquote></details>

thanks, this was a mistake


<!-- Sent from Reviewable.io -->

2022-09-07 21:40 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1945#-:-NBOtIDS2XWiIbHwNfiw:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @aliher1911, @erikgrinaker, @jbowens, and @sumeerbhola)

___
*[`get_iter.go` line 128 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1945#-NBOUGmj2tjxQtCM4ZN4:-NBOsXWS6PxWU8pSTNVm:bn9fvo7) ([raw file](https://github.com/cockroachdb/pebble/blob/5aefa5e425cacbdf92a6be89b060607c8496b434/get_iter.go#L128)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

>  I thought we were only using InternalKeySeqNumMax when constructing point iters.

This change isn't a functional one, just for consistency. Get always reads the entirety of the batch's history, so no batch keys should be filtered. Previously we were calculating the true batch seqnum for the current batch offset, but there's no point because the use of the seqnum and the getIter are only scoped to this single `Get` call.

yeah, `getIter` has confused me the few times that I've looked at it.

> we don't seem to seek to getIter.key anywhere, which would make a get very inefficient. I must be missing something.

I think down below, whenever we drop to a new level we do:
```
g.iterKey, g.iterValue = g.iter.SeekGE(g.key, base.SeekGEFlagsNone)
```

my understanding is that this function is structured like:
```
for {
    if g.iter != nil {
        // g.iterKey, g.iterValue are initialized with some internal key >= g.key.
        
        // if there's a rangedel deleting g.key, return nil, nil and !Valid()

        // if g.iterKey is not visible, next within this level to try to find a
        // visible key within the level with the same user key, and continue

        // if g.iterKey same user key as g.key, return it.
      
        // otherwise, g.key doesn't exist within the level g.iter and we close g.iter so
        // that we drop down to the next  level of the LSM.
    }

    // drop to the next level of the LSM, setting g.iter to the next level's internal
    // iterator, seeking it to g.key and modifying state so that we won't visit the level
    // again (eg, clearing `g.batch` or incrementing `g.level`).
}
```
</blockquote></details>

Can you add a code comment with "Get always reads the entirety of the batch's history, so no batch keys should be filtered." to explain the use of InternalKeySeqNumMax.


<!-- Sent from Reviewable.io -->

2022-09-07 22:04 UTC, jbowens reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1945#-:-NBOyr5p0HTNaWzvSyxx:b-814g8k)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @aliher1911, @erikgrinaker, and @sumeerbhola)

___
*[`get_iter.go` line 128 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1945#-NBOUGmj2tjxQtCM4ZN4:-NBOyspD8O776JbJacVn:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/5aefa5e425cacbdf92a6be89b060607c8496b434/get_iter.go#L128)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a code comment with "Get always reads the entirety of the batch's history, so no batch keys should be filtered." to explain the use of InternalKeySeqNumMax.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-07 22:04 UTC, merged