db: enable TrySeekUsingNext after Next in external iters
cockroachdb/pebble pull request #1960
Opened 2022-09-14 21:56 UTC by jbowens

**sstable: include more blocks' stats in BlockBytes**

Previously, BlockBytes and BlockBytesInCache only included data blocks
and sometimes the top-level index block. Now it always includes the
top-level index block, the first-level index block and the filter block.

This is motivated by a latter commit that needs the inclusion of index
blocks for a test case that illustrates the effectiveness of an
optimization.

**db: add ExternalIter_NonOverlapping_SeekNextScan benchmark**

Add a new benchmark that illustrates the pathological behavior of an external
iterator that must repeatedly seek into exhausted sstables.

**db: enable TrySeekUsingNext after Next in external iters**

Enable the TrySeekUsingNext optimization in another case, specifically
for external iterators. Previously this optimization only applied if the
previous positioning operation was also a seek.

This commit also enables it during forward iteration of external
iterators if the seek key is strictly greater than the current iterator
position's user key. This allows the optimization to trigger during
workloads that perform SeekGEs with monotonically increasing keys,
interspersed with Nexts. This is the case for CockroachDB scans.

This optimization is not enabled for non-external iterators because it
is unclear whether there is a performance benefit in these case. This
optimization is particularly beneficial with external iterators, because
it avoids the pathological behavior of re-seeking exhausted sstable
iterators.

```
name                                                                                  old time/op    new time/op    delta
ExternalIter_NonOverlapping_SeekNextScan/keys=100/files=1/forward-only=false-16         45.8µs ± 1%    46.4µs ± 3%     ~     (p=0.222 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=100/files=1/forward-only=true-16          46.0µs ± 1%    35.4µs ± 2%  -23.02%  (p=0.008 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=100/files=10/forward-only=false-16         532µs ± 1%     545µs ± 2%   +2.40%  (p=0.016 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=100/files=10/forward-only=true-16          533µs ± 1%     300µs ± 0%  -43.67%  (p=0.008 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=100/files=100/forward-only=false-16       6.27ms ± 4%    6.09ms ± 1%     ~     (p=0.151 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=100/files=100/forward-only=true-16        5.93ms ± 1%    4.66ms ± 1%  -21.53%  (p=0.008 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=10000/files=1/forward-only=false-16       2.06ms ± 1%    2.15ms ± 1%   +4.12%  (p=0.008 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=10000/files=1/forward-only=true-16        2.10ms ± 2%    0.64ms ± 0%  -69.68%  (p=0.008 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=10000/files=10/forward-only=false-16      48.2ms ± 1%    48.9ms ± 2%     ~     (p=0.095 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=10000/files=10/forward-only=true-16       48.5ms ± 3%     2.1ms ± 1%  -95.64%  (p=0.008 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=10000/files=100/forward-only=false-16      461ms ± 1%     470ms ± 3%     ~     (p=0.095 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=10000/files=100/forward-only=true-16       461ms ± 2%      15ms ± 1%  -96.67%  (p=0.008 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=100000/files=1/forward-only=false-16       256ms ± 1%     257ms ± 2%     ~     (p=0.421 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=100000/files=1/forward-only=true-16        255ms ± 2%       7ms ± 1%  -97.38%  (p=0.008 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=100000/files=10/forward-only=false-16      438ms ± 2%     446ms ± 2%     ~     (p=0.095 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=100000/files=10/forward-only=true-16       444ms ± 3%      19ms ± 1%  -95.81%  (p=0.008 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=100000/files=100/forward-only=false-16     5.26s ± 1%     5.37s ± 1%   +2.16%  (p=0.008 n=5+5)
ExternalIter_NonOverlapping_SeekNextScan/keys=100000/files=100/forward-only=true-16      5.26s ± 1%     0.11s ± 1%  -97.92%  (p=0.008 n=5+5)
```

2022-09-14 21:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1960)
<!-- Reviewable:end -->

2022-09-19 19:52 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1960#-:-NCMIdQD33PxU1lU0uSF:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`iterator.go` line 1105 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1960#-NCMIVCg7vYPysVYaeE7:-NCMIVCg7vYPysVYaeE8:b-j94l2v) ([raw file](https://github.com/cockroachdb/pebble/blob/c1c8c8cd5e013900329d1b320a93a17d80302710/iterator.go#L1105)):*
> ```Go
> 		flags = flags.EnableTrySeekUsingNext()
> 		if invariants.Enabled && flags.TrySeekUsingNext() && !i.forceEnableSeekOpt && disableSeekOpt(key, uintptr(unsafe.Pointer(i))) {
> 			flags = flags.DisableTrySeekUsingNext()
> ```

I am curious what read scenario in the storage package motivated this optimization.
___
*[`sstable/reader.go` line 512 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1960#-NC7GncL3edS0_UfZxkg:-NC7GncM4hwuf4-pEASC:b-cw7klp) ([raw file](https://github.com/cockroachdb/pebble/blob/529fd359360b36f76dd0596e6028e96ffee1ae77/sstable/reader.go#L512)):*
> ```Go
> 	bh BlockHandle, raState *readaheadState,
> ) (cache.Handle, error) {
> 	block, _, err := i.reader.readBlock(bh, nil /* transform */, raState, i.stats)
> ```

I don't think anyone else used the `cacheHit` return value, so perhaps it can be removed?


<!-- Sent from Reviewable.io -->

2022-09-21 01:47 UTC, jbowens reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1960#-:-NCSicWoBAflXGk812UH:b-814g8k)* status: 7 of 14 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`iterator.go` line 1105 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1960#-NCMIVCg7vYPysVYaeE7:-NCSg9DGCwfVUvUwdssE:b8qu13y) ([raw file](https://github.com/cockroachdb/pebble/blob/c1c8c8cd5e013900329d1b320a93a17d80302710/iterator.go#L1105)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am curious what read scenario in the storage package motivated this optimization.
</blockquote></details>

This is motivated by a `NextKey` scan during restore. When the next key isn't found through Next, it falls back to seeking. There's no level iterator to prevent the seek from propagating into an exhausted sstable iterator, and the sstable iterator reseeks:

![Screenshot 2022-09-07 at 18.56.47.png](https://files.reviewableusercontent.io/images/reviewable/867352/hl29VLOCAY9A8FHsG5iu-D62/Screenshot%202022-09-07%20at%2018.56.47.png)
___
*[`sstable/reader.go` line 512 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1960#-NC7GncL3edS0_UfZxkg:-NCSg6z-DfqDLnE0Qivc:b-48vilg) ([raw file](https://github.com/cockroachdb/pebble/blob/529fd359360b36f76dd0596e6028e96ffee1ae77/sstable/reader.go#L512)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't think anyone else used the `cacheHit` return value, so perhaps it can be removed?
</blockquote></details>

Good call, done.


<!-- Sent from Reviewable.io -->

2022-09-21 14:39 UTC, sumeerbhola requested changes
> Reviewed 3 of 7 files at r4, 1 of 1 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1960)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`iterator.go` line 1105 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1960#-NCMIVCg7vYPysVYaeE7:-NCVTZFu3ZCdLLPatN3D:b24i49w) ([raw file](https://github.com/cockroachdb/pebble/blob/c1c8c8cd5e013900329d1b320a93a17d80302710/iterator.go#L1105)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This is motivated by a `NextKey` scan during restore. When the next key isn't found through Next, it falls back to seeking. There's no level iterator to prevent the seek from propagating into an exhausted sstable iterator, and the sstable iterator reseeks:

![Screenshot 2022-09-07 at 18.56.47.png](https://files.reviewableusercontent.io/images/reviewable/867352/hl29VLOCAY9A8FHsG5iu-D62/Screenshot%202022-09-07%20at%2018.56.47.png)

</blockquote></details>

I am confused. For the case where the iterator is exhausted, which is presumably the common one, `i.iterValidityState` will be `IterExhausted` and we will not use this optimization, yes?
I am assuming that `i.forwardOnly` does not apply monotonicity of keys in the `SeekGE` call, and only that we will not use `Prev`, `SeekLT`. Is that correct?


<!-- Sent from Reviewable.io -->

2022-09-21 14:50 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1960)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`iterator.go` line 1105 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1960#-NCMIVCg7vYPysVYaeE7:-NCVWK0p3zgW5szAaFaG:b-24wd0g) ([raw file](https://github.com/cockroachdb/pebble/blob/c1c8c8cd5e013900329d1b320a93a17d80302710/iterator.go#L1105)):*
> I am confused. For the case where the iterator is exhausted, which is presumably the common one, i.iterValidityState will be IterExhausted and we will not use this optimization, yes?

In this use, the caller has provided multiple sstables to NewExternalIter (eg, the various sstables making up a backup). The top-level `pebble.Iterator` is not exhausted, but an individual sstable iterator making up a level may be.

> I am assuming that i.forwardOnly does not apply monotonicity of keys in the SeekGE call, and only that we will not use Prev, SeekLT. Is that correct?

Yeah, that's right


<!-- Sent from Reviewable.io -->

2022-09-21 15:06 UTC, sumeerbhola approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1960)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`iterator.go` line 1105 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1960#-NCMIVCg7vYPysVYaeE7:-NCV_Nc-3mYcgldzSEqV:ba47yx1) ([raw file](https://github.com/cockroachdb/pebble/blob/c1c8c8cd5e013900329d1b320a93a17d80302710/iterator.go#L1105)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> I am confused. For the case where the iterator is exhausted, which is presumably the common one, i.iterValidityState will be IterExhausted and we will not use this optimization, yes?

In this use, the caller has provided multiple sstables to NewExternalIter (eg, the various sstables making up a backup). The top-level `pebble.Iterator` is not exhausted, but an individual sstable iterator making up a level may be.

> I am assuming that i.forwardOnly does not apply monotonicity of keys in the SeekGE call, and only that we will not use Prev, SeekLT. Is that correct?

Yeah, that's right

</blockquote></details>

Ah yes, my thinking was muddled.


<!-- Sent from Reviewable.io -->

2022-09-21 15:24 UTC, jbowens commented
TFTR!

2022-09-21 15:24 UTC, merged