db: fix RangeKeyChanged and -WithLimit interaction
cockroachdb/pebble pull request #1967
Opened 2022-09-19 18:31 UTC by jbowens

First two commits are from #1962.

----

Fix a bug whereby RangeKeyChanged would sometimes return false for an
iterator position that held range keys immediately after an at-limit
position. The documented interface dictates that after any !Valid()
iterator position, an iterator position that holds range keys should
return RangeKeyChanged()=true:

> Invalid iterator positions are considered to not hold range keys,
> meaning that if an iterator steps from an IterExhausted or IterAtLimit
> position onto a position with a range key, RangeKeyChanged will yield
> true.

Previously every iterator positioning operation would reset
`i.rangeKey.updated=false` before executing. Now, it's initialized to
represent the current internal state of the range keys held in
`i.rangeKey`. If there exists a range key at the current internal
iterator position, `i.rangeKey.updated` is initialized to true if the
previous iterator position did not hold range keys.

2022-09-19 18:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1967)
<!-- Reviewable:end -->

2022-09-21 20:44 UTC, sumeerbhola requested changes
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1967)* status: 1 of 14 files reviewed, 2 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`iterator.go` line 1015 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1967#-NCWk7nrDsQcFrEm2Dmx:-NCWk7nrDsQcFrEm2Dmy:b-jtc8wx) ([raw file](https://github.com/cockroachdb/pebble/blob/13be2eca0971ca646a0c4dca3030344a6846dd1e/iterator.go#L1015)):*
> ```Go
> 		// NB: Check Valid() before clearing requiresReposition.
> 		i.rangeKey.prevPosHadRangeKey = i.rangeKey.hasRangeKey && i.Valid()
> 		i.rangeKey.updated = i.rangeKey.hasRangeKey && !i.rangeKey.prevPosHadRangeKey
> ```

is this `i.rangeKey.hasRangeKey && (!i.rangeKey.hasRangeKey || !i.Valid())` which simplifies to `i.rangeKey.hasRangeKey && !i.Valid()`? Which means that we have range key at the current position and we did not expose it previously, so if we find any range key now, updated is required to be true.
I am not sure which formulation is easier to understand. But this could use a code comment.

Also mention that the remaining code in this function will only flip updated from false to true and not the other way around. Though maybe this behavior is not quite true because of the `i.rangeKey.updated = i.rangeKey.hasRangeKey && requiresReposition` below, since `updated` could become false if `requiresReposition` is false. I am a bit confused about correctness.
___
*[`iterator.go` line 1311 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1967#-NCWmZDr-8R9d2-7mPzN:-NCWmZDr-8R9d2-7mPzO:b-wmmss4) ([raw file](https://github.com/cockroachdb/pebble/blob/81a4342ccf171449e034bc5a639beecf7feb6bba/iterator.go#L1311)):*
> ```Go
> 					i.lastPositioningOp = seekLTLastPositioningOp
> 
> 					// If there's a range key iterator stack, we need to update
> ```

I can see why it is reasonable to remove this code, but it isn't clear why this code continues to exist for SeekGE.


<!-- Sent from Reviewable.io -->

2022-09-22 16:15 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1967)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`iterator.go` line 1015 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1967#-NCWk7nrDsQcFrEm2Dmx:-NC_yDYmC50-ZMwPMGcB:b-q68dy3) ([raw file](https://github.com/cockroachdb/pebble/blob/13be2eca0971ca646a0c4dca3030344a6846dd1e/iterator.go#L1015)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this `i.rangeKey.hasRangeKey && (!i.rangeKey.hasRangeKey || !i.Valid())` which simplifies to `i.rangeKey.hasRangeKey && !i.Valid()`? Which means that we have range key at the current position and we did not expose it previously, so if we find any range key now, updated is required to be true.
I am not sure which formulation is easier to understand. But this could use a code comment.

Also mention that the remaining code in this function will only flip updated from false to true and not the other way around. Though maybe this behavior is not quite true because of the `i.rangeKey.updated = i.rangeKey.hasRangeKey && requiresReposition` below, since `updated` could become false if `requiresReposition` is false. I am a bit confused about correctness.

</blockquote></details>

I updated to `i.rangeKey.hasRange && !i.Valid()`, I think it is more understandable. Added a comment with a small example to each site.
___
*[`iterator.go` line 1311 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1967#-NCWmZDr-8R9d2-7mPzN:-NC_xokQCUN6pGKZy_zl:b-t6o2v0) ([raw file](https://github.com/cockroachdb/pebble/blob/81a4342ccf171449e034bc5a639beecf7feb6bba/iterator.go#L1311)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I can see why it is reasonable to remove this code, but it isn't clear why this code continues to exist for SeekGE.
</blockquote></details>

thanks, that was an oversight


<!-- Sent from Reviewable.io -->

2022-09-22 17:01 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1967#-:-NCa8J9NDeUnDwK_jsmT:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`iterator.go` line 1025 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1967#-NCa7FWE6Nhgma4omvcr:-NCa7FWE6Nhgma4omvcs:bqdsw2e) ([raw file](https://github.com/cockroachdb/pebble/blob/3a5f7efaa6f2657510b0159e76f7bdf9e07e4960/iterator.go#L1025)):*
> ```Go
> 		// The remainder of this function will only update i.rangeKey.updated if
> 		// the iterator moves into a new range key, or out of the current range
> 		// key.
> ```

maybe add:
i.e., it will only set to true, and not to false.


<!-- Sent from Reviewable.io -->

2022-09-22 19:14 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1967)* status: all files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)

___
*[`iterator.go` line 1025 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1967#-NCa7FWE6Nhgma4omvcr:-NCaaft_4Xi9tfIgTr8t:bac675t) ([raw file](https://github.com/cockroachdb/pebble/blob/3a5f7efaa6f2657510b0159e76f7bdf9e07e4960/iterator.go#L1025)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

maybe add:
i.e., it will only set to true, and not to false.
</blockquote></details>

I might be misunderstanding you, but that's not strictly true. In particular during the execution of a seek, we can land back on the same range key again. If that happens, we'll set `i.rangeKey.updated=false` if the previous position had a range key (`i.rangeKey.prevPosHadRangeKey`) and the bounds match.


<!-- Sent from Reviewable.io -->

2022-09-22 20:02 UTC, sumeerbhola commented
I see that now.
The case you point out is one where updated would be initially set to false based on `i.rangeKey.updated = i.rangeKey.hasRangeKey && !i.Valid()`, i.e., this is not one where `prevPosHadRangeKey` is true. Is my understanding correct?

I do find it hard to reason about correctness where the logic is distributed in this manner. Is the original bug fixed in this PR caused by the else-block in 
```
	if s == nil {
		i.rangeKey.hasRangeKey = false
		i.rangeKey.updated = i.rangeKey.prevPosHadRangeKey
		return
	} else if !i.rangeKey.stale {
		// The range key `s` is identical to the one currently saved. No-op.
		return
	}
```
It seems to be the only place in `saveRangeKey` where we do not explicitly set `updated`. If yes, it may be clearer if we don't reuse `updated` in the manner this PR does, which is a carrier of information across a nested set of function calls. Would the above else-if be able to use `i.ramgeKey.updated = !i.rangeKey.prevPosHadRangeKey`?

I probably am missing something critical because I am also missing why
```
	if i.rangeKey == nil || i.opts.KeyTypes == IterKeyTypePointsOnly {
		return
	}
```
at the top of `saveRangeKey` doesn't need to set `updated` to false for the case where we have set it to true earler.

2022-09-23 13:34 UTC, jbowens reviewed
> I do find it hard to reason about correctness where the logic is distributed in this manner.

agreed, I do find this organization lacking too but have found it difficult to simplify/consolidate.

> Would the above else-if be able to use `i.rangeKey.updated = !i.rangeKey.prevPosHadRangeKey`?

`saveRangeKey` may be called multiple times within a single top-level `Iterator` call (eg, because of deleted keys). So one call to `saveRangeKey` when we enter a new range key may mark `i.rangeKey.updated = true`. A subsequent call would fall into this else-if case, and should preserve the existing `i.rangeKey.updated` value.

> I probably am missing something critical because I am also missing why ... at the top of saveRangeKey doesn't need to set updated to false for the case where we have set it to true earler.

I might be misunderstanding, but that case is when an iterator is not iterating over range keys (either because it's configured not to, or the lazy-combined iterator hasn't found one yet). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1967#-:-NCeOAHC5I2BGI9vr4sR:b-i4tdpp)* status: all files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-09-23 16:24 UTC, jbowens reviewed
I'm going to merge this as-is, and we can follow up with a refactor if we come up with something.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1967#-:-NCf9QTb-fkdm8CRz9N0:bwz3fca)* status: all files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-09-23 16:24 UTC, merged

2022-09-25 17:59 UTC, sumeerbhola reviewed
Thanks, this was useful for my understanding.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1967#-:-NCpnIzrCo6tLTV_6ybM:bhd366s)* status: all files reviewed, 3 unresolved discussions



<!-- Sent from Reviewable.io -->