db: restore TrySeekUsingNext across SetOptions batch refresh
cockroachdb/pebble pull request #1987
Opened 2022-09-27 21:28 UTC by jbowens

A recent change began invalidating the iterator in SetOptions if the iterator was configured to read through an indexed batch that had been modified. This prevented the TrySeekUsingNext optimization from triggering when the pebbleBatch's iterator was reused.

This change makes enabling trySeekUsingNext within the batchIter slightly more difficult (#1946).

Relative to HEAD:
```
name                                                  old time/op    new time/op    delta
MVCCBatchPut_Pebble/valueSize=10/batchSize=1-24         7.52µs ± 4%    7.79µs ± 5%      ~     (p=0.151 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=100-24       3.81µs ± 9%    1.48µs ± 0%   -61.31%  (p=0.008 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=10000-24     2.83µs ± 6%    1.42µs ± 1%   -49.69%  (p=0.008 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=100000-24    2.01µs ± 2%    1.55µs ± 2%   -22.94%  (p=0.008 n=5+5)

name                                                  old speed      new speed      delta
MVCCBatchPut_Pebble/valueSize=10/batchSize=1-24       1.33MB/s ± 4%  1.28MB/s ± 5%      ~     (p=0.143 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=100-24     2.63MB/s ±10%  6.78MB/s ± 0%  +157.64%  (p=0.008 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=10000-24   3.54MB/s ± 6%  7.02MB/s ± 1%   +98.53%  (p=0.008 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=100000-24  4.97MB/s ± 2%  6.45MB/s ± 2%   +29.75%  (p=0.008 n=5+5)
```

Relative to 22.1:
```
name                                                  old time/op    new time/op    delta
MVCCBatchPut_Pebble/valueSize=10/batchSize=1-24         8.31µs ± 3%    7.79µs ± 5%    ~     (p=0.056 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=100-24       1.42µs ± 1%    1.48µs ± 0%  +3.80%  (p=0.008 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=10000-24     1.35µs ± 1%    1.42µs ± 1%  +5.51%  (p=0.008 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=100000-24    1.46µs ± 1%    1.55µs ± 2%  +6.39%  (p=0.008 n=5+5)

name                                                  old speed      new speed      delta
MVCCBatchPut_Pebble/valueSize=10/batchSize=1-24       1.20MB/s ± 4%  1.28MB/s ± 5%  +6.64%  (p=0.040 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=100-24     7.04MB/s ± 1%  6.78MB/s ± 0%  -3.70%  (p=0.008 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=10000-24   7.41MB/s ± 1%  7.02MB/s ± 1%  -5.21%  (p=0.008 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=100000-24  6.86MB/s ± 1%  6.45MB/s ± 2%  -5.98%  (p=0.008 n=5+5)
```

Informs cockroachdb/cockroach#88723.
Informs cockroachdb/cockroach#88819.

2022-09-27 21:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1987)
<!-- Reviewable:end -->

2022-09-28 13:51 UTC, sumeerbhola requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1987)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1987#-ND3JSxA2qAgosUs-Rdg):*
are you referring to the change in https://github.com/cockroachdb/pebble/pull/1640?
I am starting to lose track of things, so trying to swap state back into my head.
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1987#-ND3KAmg0mCBq05MCKfg):*
What is "this change"? I am assuming not #1946, since that is an issue and not a commit/PR.
And I thought the problem is that the whole `InternalIterator` tree is not able to use `trySeekUsingNext` which affects the sstable iterators. The regression is not due to the `batchIter` respecting `trySeekUsingNext` since it never did. Am I missing something?
___
*[`iterator.go` line 2116 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1987#-ND3KziU69MeyMnrZJze:-ND3KziU69MeyMnrZJzf:b5mbaqs) ([raw file](https://github.com/cockroachdb/pebble/blob/0e35983cfa6550ccc29440a55e87575a411e9226/iterator.go#L2116)):*
> ```Go
> 					// No range deletions exist in the batch. We only need to
> 					// update the batchIter's snapshot.
> 					i.invalidate()
> ```

Is the correctness argument for this removal something like (there is probably a more precise way to say this):
- we have new keys in the batchIter, and we will update its snapshot to make them visible. The batchIter ignores `trySeekUsingNext` so any seek done to it will see these new keys.
- the sstable iterators `trySeekUsingNext` optimizations are based on the previous seeks etc. they have seen and have nothing to do with the mergingIter state (e.g. the mergingIter state may now move backward in the keyspace even if a SeekGE is moving forward in the key space, because of the new keys in the batchIter). Hence we can preserve the optimization for them, by not invalidating.


<!-- Sent from Reviewable.io -->

2022-09-28 14:59 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1987)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1987#-ND3JSxA2qAgosUs-Rdg):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

are you referring to the change in https://github.com/cockroachdb/pebble/pull/1640?
I am starting to lose track of things, so trying to swap state back into my head.
</blockquote></details>

Yeah, #1640 originally introduced the bug.
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1987#-ND3KAmg0mCBq05MCKfg):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

What is "this change"? I am assuming not #1946, since that is an issue and not a commit/PR.
And I thought the problem is that the whole `InternalIterator` tree is not able to use `trySeekUsingNext` which affects the sstable iterators. The regression is not due to the `batchIter` respecting `trySeekUsingNext` since it never did. Am I missing something?
</blockquote></details>

I'm not sure I understand. By "this change" I mean this commit that's up for review.

I had filed #1946 because _if_ TrySeekUsingNext optimization are _not_ enabled across SetOptions with a modified batch, the iterator's view of the batch never changes between the call that positions the iterator and the subsequent call that reuses the iterator position using TrySeekUsingNext=true. With this PR, we will once again allow TrySeekUsingNext to apply across SetOptions with a modified batch, meaning we cannot reuse the batchIter's position when TrySeekUsingNext=true, because there might be new visible entries that we've missed.
___
*[`iterator.go` line 2116 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1987#-ND3KziU69MeyMnrZJze:-ND3ZNvP3ZIBK7H-F-Jb:b-t9d1xj) ([raw file](https://github.com/cockroachdb/pebble/blob/0e35983cfa6550ccc29440a55e87575a411e9226/iterator.go#L2116)):*
> Locally decided by the sstable iterators based on monotonic bounds. I am assuming the invalidate call here did nothing to harm those. Is that correct?

Yeah, that's right.

> But now that I look at the code more carefully we only apply the second and third cases when i.batch == nil.

Currently SeekGE only applies the second and third cases when i.batch == nil, while SeekPrefixGE applies the third case regardless of `i.batch`'s nilness (and has no version of the second optimization.

I believe we could modify SeekGE to also apply the second case regardless of `i.batch`'s nilness, because the batchIter ignores `trySeekUsingNext`.


----

An aside, but I think making use of TrySeekUsingNext in batchIter (#1946) is still possible _between calls to SetOptions that refresh the view of the batch_, although I doubt the performance benefit warrants the complexity.


<!-- Sent from Reviewable.io -->

2022-09-28 19:51 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1987)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`iterator.go` line 2116 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1987#-ND3KziU69MeyMnrZJze:-ND4ZOqpBA2gZ72GwcNy:boezi1s) ([raw file](https://github.com/cockroachdb/pebble/blob/0e35983cfa6550ccc29440a55e87575a411e9226/iterator.go#L2116)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> Locally decided by the sstable iterators based on monotonic bounds. I am assuming the invalidate call here did nothing to harm those. Is that correct?

Yeah, that's right.

> But now that I look at the code more carefully we only apply the second and third cases when i.batch == nil.

Currently SeekGE only applies the second and third cases when i.batch == nil, while SeekPrefixGE applies the third case regardless of `i.batch`'s nilness (and has no version of the second optimization.

I believe we could modify SeekGE to also apply the second case regardless of `i.batch`'s nilness, because the batchIter ignores `trySeekUsingNext`.


----

An aside, but I think making use of TrySeekUsingNext in batchIter (#1946) is still possible _between calls to SetOptions that refresh the view of the batch_, although I doubt the performance benefit warrants the complexity.
</blockquote></details>

(some repetition from our in-person conversation)

A. Expanding Opt3:
Let's assume we have defined an invariant that `batchIter` ignores `trySeekUsingNext` because it it mutable.
We could change the code in SeekGE to exclude only Opt2 (within pebble.Iterator) when `i.batch != nil`. This is strictly better than our current SeekGE optimization, which also excludes Opt3 when `i.batch != nil`. This narrower than necessary optimization has existed since it was introduced in https://github.com/cockroachdb/pebble/pull/1412.
So now Opt3 will apply for batch iteration for both SeekGE and SeekPrefixGE. 

B. Ensuring opt3 works even when the batchIter is being adjusted in SetOptions:
Because of the invariant we defined earlier we should never need to call `i.invalidate()`. All we want to do is mark a bit saying that Opt2 is disabled, and we could do that by tracking it separately. I was initially going to suggest that in addition to your change here, we also try to see if the actual rangedels have changed in the else block below and if they haven't don't call i.invalidate() there either, but it seems there is a simpler solution.

C. Expanding Opt2:
The `i.batch == nil` restriction seems unnecessary. The same bit we'll track to prevent Opt2 in B above can be used to indicate that the batch has not been refreshed, so since the visibility in the batch has not changed, the mergingIter is in a good state too.

D. Applying `trySeekUsingNext` in the `batchIter` itself
We know in `SetOptions` whether `i.batchPointIter` is going to see some new state. In which case we can set a bool in the batchPointIter that for the next Seek call it should ignore the value of trySeekUsingNext and always use false.

Thoughts?


<!-- Sent from Reviewable.io -->

2022-09-28 22:14 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1987)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @sumeerbhola)

___
*[`iterator.go` line 2116 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1987#-ND3KziU69MeyMnrZJze:-ND59St95wjDvFzJtr7g:bf2nw16) ([raw file](https://github.com/cockroachdb/pebble/blob/0e35983cfa6550ccc29440a55e87575a411e9226/iterator.go#L2116)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

(some repetition from our in-person conversation)

A. Expanding Opt3:
Let's assume we have defined an invariant that `batchIter` ignores `trySeekUsingNext` because it it mutable.
We could change the code in SeekGE to exclude only Opt2 (within pebble.Iterator) when `i.batch != nil`. This is strictly better than our current SeekGE optimization, which also excludes Opt3 when `i.batch != nil`. This narrower than necessary optimization has existed since it was introduced in https://github.com/cockroachdb/pebble/pull/1412.
So now Opt3 will apply for batch iteration for both SeekGE and SeekPrefixGE. 

B. Ensuring opt3 works even when the batchIter is being adjusted in SetOptions:
Because of the invariant we defined earlier we should never need to call `i.invalidate()`. All we want to do is mark a bit saying that Opt2 is disabled, and we could do that by tracking it separately. I was initially going to suggest that in addition to your change here, we also try to see if the actual rangedels have changed in the else block below and if they haven't don't call i.invalidate() there either, but it seems there is a simpler solution.

C. Expanding Opt2:
The `i.batch == nil` restriction seems unnecessary. The same bit we'll track to prevent Opt2 in B above can be used to indicate that the batch has not been refreshed, so since the visibility in the batch has not changed, the mergingIter is in a good state too.

D. Applying `trySeekUsingNext` in the `batchIter` itself
We know in `SetOptions` whether `i.batchPointIter` is going to see some new state. In which case we can set a bool in the batchPointIter that for the next Seek call it should ignore the value of trySeekUsingNext and always use false.

Thoughts?
</blockquote></details>

Nice, sounds good. Just pushed a commit with these changes and it's a net improvement over 22.1 in the regressed benchmark.


<!-- Sent from Reviewable.io -->

2022-09-29 19:43 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1987#-:-ND9lfpKAV2-nCMdfvTk:bg7igkv)* status: all files reviewed, 6 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`iterator.go` line 242 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1987#-ND9ggQxA32MQRT8Fxlm:-ND9ggQyEpNP1ammGBqo:bsq6n6g) ([raw file](https://github.com/cockroachdb/pebble/blob/7bbee7451948da240abeb4011f747d95b62aeacc/iterator.go#L242)):*
> ```Go
> 	// Used for determining when it's safe to perform SeekGE optimizations that
> 	// reuse the iterator state to avoid the cost of a full seek if the iterator
> 	// if it's already positioned in the correct place. If iterator's view of
> ```

nit: ... is already positioned ... 
___
*[`testdata/iter_histories/iter_optimizations` line 171 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1987#-ND9j3Jz-VsaqDU8s40H:-ND9j3Jz-VsaqDU8s40I:ba4cwn5) ([raw file](https://github.com/cockroachdb/pebble/blob/7bbee7451948da240abeb4011f747d95b62aeacc/testdata/iter_histories/iter_optimizations#L171)):*
> ```
> # try-seek-using-next prerequisite that previously regressed. Is there a way to
> # adapt to this test so that the absence of the try-seek-using-next optimization
> # is visible in the iterator statistics?
> ```

Are you thinking of explicitly exposing counters of these optimizations in IteratorStats/InternalIteratorStats?
It sounds reasonable.
___
*[`testdata/iter_histories/iter_optimizations` line 273 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1987#-ND9kcyx6ItJrYBz9ROk:-ND9kcyx6ItJrYBz9ROl:bnahi04) ([raw file](https://github.com/cockroachdb/pebble/blob/7bbee7451948da240abeb4011f747d95b62aeacc/testdata/iter_histories/iter_optimizations#L273)):*
> ```
> seek-prefix-ge b@6
> ----
> b@5: (b@5, .)
> ```

if the original was b@3 and this seek landed on b@3, then doing another seek for b@5 after adding b@4 seems like a more tricky test case. With the current test case the batchIter is at b@5 so technically it could see the newly added b@3 if it did not ignore trySeekUsingNext.


<!-- Sent from Reviewable.io -->

2022-09-29 20:22 UTC, jbowens reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1987#-:-ND9ucMyDyKSstbIFv87:b-814g8k)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @sumeerbhola)

___
*[`testdata/iter_histories/iter_optimizations` line 171 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1987#-ND9j3Jz-VsaqDU8s40H:-ND9sCdm0WndYYtK7GGO:bc1fb3y) ([raw file](https://github.com/cockroachdb/pebble/blob/7bbee7451948da240abeb4011f747d95b62aeacc/testdata/iter_histories/iter_optimizations#L171)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are you thinking of explicitly exposing counters of these optimizations in IteratorStats/InternalIteratorStats?
It sounds reasonable.
</blockquote></details>

Yeah :+1: 
___
*[`testdata/iter_histories/iter_optimizations` line 273 at r2](https://reviewable.io/reviews/cockroachdb/pebble/1987#-ND9kcyx6ItJrYBz9ROk:-ND9tCWSEU1CVhPJ8A3N:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/7bbee7451948da240abeb4011f747d95b62aeacc/testdata/iter_histories/iter_optimizations#L273)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

if the original was b@3 and this seek landed on b@3, then doing another seek for b@5 after adding b@4 seems like a more tricky test case. With the current test case the batchIter is at b@5 so technically it could see the newly added b@3 if it did not ignore trySeekUsingNext.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-29 20:32 UTC, merged