db: integrate elastic cpu granter with pebble
cockroachdb/pebble pull request #1988
Opened 2022-09-27 22:12 UTC by bananabrick

This pr modifies the interface of the CPUWorkPermissionGranter to accommodate the change from cpu soft slots to the elastic cpu granter.

The CPUWorkPermissionGranter returns a handle which internally calculates the CPU time spent on the Writer client goroutine.

2022-09-27 22:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/1988)
<!-- Reviewable:end -->

2022-10-18 14:29 UTC, sumeerbhola requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1988)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @bananabrick)

___
*[`db.go` line 177 at r1](https://reviewable.io/reviews/cockroachdb/pebble/1988#-NEfU3Rv0RslJNpMA9D-:-NEfU3Rv0RslJNpMA9D0:bmbe072) ([raw file](https://github.com/cockroachdb/pebble/blob/b8a87a7de8e3dfa95f0018eea957c67e452cf2e2/db.go#L177)):*
> ```Go
> // use additional CPUs to speed up internal background work.
> type CPUWorkPermissionGranter interface {
> 	TryGetHandle(time.Duration) CPUWorkHandle
> ```

I was expecting something like
```
type CPUWorkHandle interface {
    Permitted() bool
}

type CPUWorkPermissionGranter interface {
  // GetPermission returns a handle regardless of whether permission is granted or not. In the latter case, the
  // handle is only useful for recording the CPU time actually spent on this calling goroutine.
  GetPermission(time.Duration) CPUWorkHandle
  // CPUWorkDone must be called regardless of whether Permitted returns true or false.
  CPUWorkDone(CPUWorkHandle)
}
```


<!-- Sent from Reviewable.io -->

2022-10-20 19:06 UTC, sumeerbhola requested changes
> Reviewed 4 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1988)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @bananabrick)

___
*[`compaction.go` line 2363 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1988#-NEqm3vt2PItxtWHLiuH:-NEqm3vt2PItxtWHLiuI:b-a7ih27) ([raw file](https://github.com/cockroachdb/pebble/blob/d4e29f23f260e66681bce5ab991813f41e52b389/compaction.go#L2363)):*
> ```Go
> 		internalTableOpt := private.SSTableInternalTableOpt.(sstable.WriterOption)
> 
> 		const MaxFileWriteAdditionalCPUTime = time.Nanosecond * 1e8 // 100ms
> ```

`time.Millisecond*100` would be easier and not need the comment.
___
*[`compaction_test.go` line 906 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1988#-NEqlOTYEn7Dvp_VEMzl:-NEqlOTYEn7Dvp_VEMzm:bsftg1) ([raw file](https://github.com/cockroachdb/pebble/blob/d4e29f23f260e66681bce5ab991813f41e52b389/compaction_test.go#L906)):*
> ```Go
> 
> func (t *cpuPermissionGranter) GetPermission(dur time.Duration) CPUWorkHandle {
> 	t.granted += dur
> ```

is `granted` actually `requested` since it is being incremented regardless of the value of `permit`?
___
*[`compaction_test.go` line 912 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1988#-NEql_fSC2qHnwk39sEa:-NEql_fSC2qHnwk39sEb:b-buahm) ([raw file](https://github.com/cockroachdb/pebble/blob/d4e29f23f260e66681bce5ab991813f41e52b389/compaction_test.go#L912)):*
> ```Go
> 
> func (t *cpuPermissionGranter) CPUWorkDone(h CPUWorkHandle) {
> 	t.returned += h.(cpuWorkHandle).dur
> ```

is `returned` actually `requestedDone`? It is not being returned.


<!-- Sent from Reviewable.io -->

2022-10-24 21:22 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1988)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @sumeerbhola)

___
*[`compaction.go` line 2363 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1988#-NEqm3vt2PItxtWHLiuH:-NFAoEhp8Vxv270Vt-VO:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d4e29f23f260e66681bce5ab991813f41e52b389/compaction.go#L2363)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

`time.Millisecond*100` would be easier and not need the comment.
</blockquote></details>

Done.
___
*[`compaction_test.go` line 906 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1988#-NEqlOTYEn7Dvp_VEMzl:-NFArypXA0Ztkcl1-Ia8:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d4e29f23f260e66681bce5ab991813f41e52b389/compaction_test.go#L906)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is `granted` actually `requested` since it is being incremented regardless of the value of `permit`?
</blockquote></details>

Done.
___
*[`compaction_test.go` line 912 at r3](https://reviewable.io/reviews/cockroachdb/pebble/1988#-NEql_fSC2qHnwk39sEa:-NFArz9U5F0AEiBJjORJ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d4e29f23f260e66681bce5ab991813f41e52b389/compaction_test.go#L912)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is `returned` actually `requestedDone`? It is not being returned.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-26 18:40 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1988#-:-NFKaBOW235h5JyH3Cwf:bg7igkv)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @bananabrick)

___
*[`compaction_test.go` line 936 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1988#-NFKa320BQO6cBkQgqOz:-NFKa320BQO6cBkQgqP-:b1ym6ex) ([raw file](https://github.com/cockroachdb/pebble/blob/80a3025f4fafe0d5656e501063bd86d40734bf84/compaction_test.go#L936)):*
> ```Go
> 	}
> 	require.True(t, g.used)
> 	require.Equal(t, g.requestCount, g.requestCount)
> ```

should this be require.Equal(t, 0, g.requestCount)?


<!-- Sent from Reviewable.io -->

2022-10-26 21:56 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/1988)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @sumeerbhola)

___
*[`compaction_test.go` line 936 at r4](https://reviewable.io/reviews/cockroachdb/pebble/1988#-NFKa320BQO6cBkQgqOz:-NFLHu6N2DDm_kMXdQO-:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/80a3025f4fafe0d5656e501063bd86d40734bf84/compaction_test.go#L936)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should this be require.Equal(t, 0, g.requestCount)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-26 22:26 UTC, merged