db: apply TrySeekUsingNext to level metadata
cockroachdb/pebble pull request #2058
Opened 2022-10-25 22:53 UTC by jbowens

When TrySeekUsingNext=true, the iterator knows the current seek key must be greater than or equal to the key at the current iterator position. This knowledge can be used by level iterators to avoid re-seeking within the level metadata, under the expectation that the seek key is proximate and Next-ing will require fewer key comparisons.

For now this optimization doesn't fallback to seeking if it doesn't find the sought file. This is thought to be okay in real-world use cases that typically seek within a limited area of the keyspace (eg, within a single Cockroach KV range) which won't require traversing many file metadatas to position appropriately.

```
name                                                                            old speed      new speed      delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=8/numRangeKeys=0-24                 1.33MB/s ± 1%  1.32MB/s ± 1%    ~     (p=0.074 n=10+5)
MVCCScan_Pebble/rows=1/versions=2/valueSize=8/numRangeKeys=0-24                 1.25MB/s ± 0%  1.25MB/s ± 1%    ~     (p=0.200 n=10+5)
MVCCScan_Pebble/rows=1/versions=10/valueSize=8/numRangeKeys=0-24                1.00MB/s ± 1%  1.00MB/s ± 1%    ~     (p=0.224 n=10+5)
MVCCScan_Pebble/rows=1/versions=100/valueSize=8/numRangeKeys=0-24                480kB/s ± 0%   480kB/s ± 0%    ~     (all equal)
MVCCScan_Pebble/rows=10/versions=1/valueSize=8/numRangeKeys=0-24                7.95MB/s ± 1%  7.99MB/s ± 1%    ~     (p=0.262 n=10+5)
MVCCScan_Pebble/rows=10/versions=2/valueSize=8/numRangeKeys=0-24                6.94MB/s ± 1%  6.94MB/s ± 1%    ~     (p=1.000 n=10+5)
MVCCScan_Pebble/rows=10/versions=10/valueSize=8/numRangeKeys=0-24               3.71MB/s ± 3%  3.72MB/s ± 0%    ~     (p=0.807 n=10+5)
MVCCScan_Pebble/rows=10/versions=100/valueSize=8/numRangeKeys=0-24              1.41MB/s ± 1%  1.45MB/s ± 0%  +2.63%  (p=0.001 n=10+5)
MVCCScan_Pebble/rows=100/versions=1/valueSize=8/numRangeKeys=0-24               20.1MB/s ± 1%  20.3MB/s ± 0%  +1.16%  (p=0.002 n=8+5)
MVCCScan_Pebble/rows=100/versions=2/valueSize=8/numRangeKeys=0-24               15.4MB/s ± 1%  15.5MB/s ± 1%    ~     (p=0.135 n=10+5)
MVCCScan_Pebble/rows=100/versions=10/valueSize=8/numRangeKeys=0-24              6.05MB/s ± 1%  6.09MB/s ± 1%    ~     (p=0.051 n=10+5)
MVCCScan_Pebble/rows=100/versions=100/valueSize=8/numRangeKeys=0-24             1.98MB/s ± 1%  2.09MB/s ± 1%  +5.82%  (p=0.001 n=10+5)
MVCCScan_Pebble/rows=1000/versions=1/valueSize=8/numRangeKeys=0-24              25.7MB/s ± 1%  25.9MB/s ± 1%    ~     (p=0.122 n=10+5)
MVCCScan_Pebble/rows=1000/versions=2/valueSize=8/numRangeKeys=0-24              19.0MB/s ± 1%  18.9MB/s ± 1%    ~     (p=0.837 n=10+5)
MVCCScan_Pebble/rows=1000/versions=10/valueSize=8/numRangeKeys=0-24             6.83MB/s ± 1%  6.82MB/s ± 1%    ~     (p=0.475 n=9+5)
MVCCScan_Pebble/rows=1000/versions=100/valueSize=8/numRangeKeys=0-24            2.11MB/s ± 2%  2.26MB/s ± 2%  +7.40%  (p=0.001 n=10+5)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=8/numRangeKeys=0-24             26.8MB/s ± 2%  26.9MB/s ± 1%    ~     (p=0.617 n=10+5)
MVCCScan_Pebble/rows=10000/versions=2/valueSize=8/numRangeKeys=0-24             19.6MB/s ± 1%  19.5MB/s ± 1%    ~     (p=0.259 n=9+5)
MVCCScan_Pebble/rows=10000/versions=10/valueSize=8/numRangeKeys=0-24            6.91MB/s ± 2%  6.91MB/s ± 2%    ~     (p=0.536 n=9+5)
MVCCScan_Pebble/rows=10000/versions=100/valueSize=8/numRangeKeys=0-24           2.16MB/s ± 4%  2.27MB/s ± 4%  +5.07%  (p=0.013 n=9+5)
MVCCScan_Pebble/rows=50000/versions=1/valueSize=8/numRangeKeys=0-24             26.4MB/s ± 1%  26.6MB/s ± 1%  +0.85%  (p=0.025 n=10+5)
MVCCScan_Pebble/rows=50000/versions=2/valueSize=8/numRangeKeys=0-24             19.3MB/s ± 1%  19.5MB/s ± 1%  +0.95%  (p=0.005 n=10+5)
MVCCScan_Pebble/rows=50000/versions=10/valueSize=8/numRangeKeys=0-24            6.94MB/s ± 4%  6.99MB/s ± 2%    ~     (p=0.572 n=10+5)
MVCCScan_Pebble/rows=50000/versions=100/valueSize=8/numRangeKeys=0-24           2.22MB/s ± 7%  2.31MB/s ± 6%    ~     (p=0.105 n=10+5)

name                                                                            old time/op    new time/op    delta
CheckSSTConflicts/keys=1000/sstKeys=10/overlap=false/prefixSeek=false-24           108µs ± 1%     106µs ± 3%    ~     (p=0.056 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=10/overlap=false/prefixSeek=true-24           3.11µs ± 0%    3.04µs ± 2%  -2.30%  (p=0.024 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=10/overlap=true/prefixSeek=false-24            136µs ± 0%     131µs ± 1%  -3.42%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=10/overlap=true/prefixSeek=true-24             120µs ± 1%     117µs ± 1%  -2.63%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=100/overlap=false/prefixSeek=false-24          111µs ± 1%     110µs ± 1%  -1.30%  (p=0.032 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=100/overlap=false/prefixSeek=true-24          3.08µs ± 1%    3.05µs ± 1%    ~     (p=0.222 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=100/overlap=true/prefixSeek=false-24           381µs ± 1%     379µs ± 1%    ~     (p=0.310 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=100/overlap=true/prefixSeek=true-24            177µs ± 1%     176µs ± 1%  -0.75%  (p=0.016 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=1000/overlap=false/prefixSeek=false-24         117µs ± 0%     115µs ± 0%  -1.39%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=1000/overlap=false/prefixSeek=true-24         3.07µs ± 1%    3.06µs ± 0%    ~     (p=0.310 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=1000/overlap=true/prefixSeek=false-24          785µs ± 1%     768µs ± 1%  -2.23%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=1000/overlap=true/prefixSeek=true-24           760µs ± 0%     746µs ± 1%  -1.90%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=10000/overlap=false/prefixSeek=false-24        117µs ± 0%     115µs ± 0%  -1.08%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=10000/overlap=false/prefixSeek=true-24        3.08µs ± 1%    3.05µs ± 1%    ~     (p=0.175 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=10000/overlap=true/prefixSeek=false-24        1.96ms ± 1%    1.96ms ± 1%    ~     (p=0.548 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=10000/overlap=true/prefixSeek=true-24         6.43ms ± 0%    6.41ms ± 1%    ~     (p=0.548 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=100000/overlap=false/prefixSeek=false-24       122µs ± 1%     121µs ± 1%    ~     (p=0.222 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=100000/overlap=false/prefixSeek=true-24       3.01µs ± 1%    2.99µs ± 3%    ~     (p=0.460 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=100000/overlap=true/prefixSeek=false-24       6.74ms ± 0%    6.69ms ± 0%  -0.67%  (p=0.032 n=5+5)
CheckSSTConflicts/keys=1000/sstKeys=100000/overlap=true/prefixSeek=true-24        63.9ms ± 1%    63.3ms ± 1%    ~     (p=0.056 n=5+5)
CheckSSTConflicts/keys=10000/sstKeys=10/overlap=false/prefixSeek=false-24          105µs ± 1%     104µs ± 1%    ~     (p=0.310 n=5+5)
CheckSSTConflicts/keys=10000/sstKeys=10/overlap=false/prefixSeek=true-24          3.04µs ± 1%    3.03µs ± 1%    ~     (p=0.421 n=5+5)
CheckSSTConflicts/keys=10000/sstKeys=10/overlap=true/prefixSeek=false-24           132µs ± 1%     131µs ± 1%    ~     (p=0.222 n=5+5)
CheckSSTConflicts/keys=10000/sstKeys=10/overlap=true/prefixSeek=true-24            116µs ± 1%     114µs ± 1%  -1.60%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=10000/sstKeys=100/overlap=false/prefixSeek=false-24         109µs ± 1%     107µs ± 1%  -1.05%  (p=0.032 n=5+5)
CheckSSTConflicts/keys=10000/sstKeys=100/overlap=false/prefixSeek=true-24         3.02µs ± 1%    3.02µs ± 1%    ~     (p=0.730 n=5+5)
CheckSSTConflicts/keys=10000/sstKeys=100/overlap=true/prefixSeek=false-24          394µs ± 0%     392µs ± 0%  -0.46%  (p=0.032 n=5+5)
CheckSSTConflicts/keys=10000/sstKeys=100/overlap=true/prefixSeek=true-24           178µs ± 1%     173µs ± 0%  -2.56%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=10000/sstKeys=1000/overlap=false/prefixSeek=false-24        114µs ± 1%     113µs ± 1%  -0.99%  (p=0. [...]

2022-10-25 22:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2058)
<!-- Reviewable:end -->

2022-10-26 15:26 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2058)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[`level_iter.go` line 656 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2058#-NFJrTHCC8GX64jpza5R:-NFJrTHCC8GX64jpza5S:b-r8rik5) ([raw file](https://github.com/cockroachdb/pebble/blob/12868b0e2a1c717590c8737c325eef5cf5491ea5/level_iter.go#L656)):*
> ```Go
> 		//      but provides a large benefit to many practical access patterns. If
> 		//      the worst case proves to be a problem, we can fallback to a seek
> 		//      after some fixed number of Nexts
> ```

nit: missing period.

How will we know the worst case is a problem? We should consider creating a tracking issue for constructing realistic benchmarks for scans and seeks. And I think we should fallback to nexts now. With 1TB in L6 and 32MB files, we will have ~30K files in L6 -- nexting through them could get very expensive.

We should rename the `isRelativeSeek` parameter in `findFileGE` to something else since this is not a relative seek.


<!-- Sent from Reviewable.io -->

2022-10-28 16:17 UTC, jbowens reviewed
I ran the benchmarks with a larger value size (64 bytes), to get a bit larger of an LSM and the benefit predictably improved. It would be great to have more realistic LSMs available for this kind of microbenchmarking.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2058#-:-NFUNBAo7TlmD2_3hEDe:b3wlbkj)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @sumeerbhola)

___
*[`level_iter.go` line 656 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2058#-NFJrTHCC8GX64jpza5R:-NFUMxba9sUd8TR6gbM9:bjrztw4) ([raw file](https://github.com/cockroachdb/pebble/blob/12868b0e2a1c717590c8737c325eef5cf5491ea5/level_iter.go#L656)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: missing period.

How will we know the worst case is a problem? We should consider creating a tracking issue for constructing realistic benchmarks for scans and seeks. And I think we should fallback to nexts now. With 1TB in L6 and 32MB files, we will have ~30K files in L6 -- nexting through them could get very expensive.

We should rename the `isRelativeSeek` parameter in `findFileGE` to something else since this is not a relative seek.

</blockquote></details>

Updated to fall back to seeks and refactored the code to propagate the `SeekGEFlags` into `findFileGE`.


<!-- Sent from Reviewable.io -->

2022-10-31 13:40 UTC, sumeerbhola approved these changes
> I ran the benchmarks with a larger value size (64 bytes), to get a bit larger of an LSM and the benefit predictably improved. 

nice!

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2058#-:-NFiGTLS2HpiDAJKtos9:bpvorz8)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`level_iter.go` line 346 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2058#-NFiEcg2EITG4-BJkXMU:-NFiEcg2EITG4-BJkXMV:b-sh7dx) ([raw file](https://github.com/cockroachdb/pebble/blob/b87355d373dab0decee2ccf643f3dbd865ddc151/level_iter.go#L346)):*
> ```Go
> 	var nextsUntilSeek int
> 	var nextInsteadOfSeek bool
> 	if flags.TrySeekUsingNext() {
> ```

Can you remind me: can both TrySeekUsingNext and RelativeSeek be true? If not, can you add that to the code comment?
___
*[`testdata/level_iter_seek` line 309 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2058#-NFiG6TxAyUJpjaKT7n_:-NFiG6TxAyUJpjaKT7na:b-izbw) ([raw file](https://github.com/cockroachdb/pebble/blob/f34af25a01873c9cf027e53147754e96ec8b2b53/testdata/level_iter_seek#L309)):*
> ```
> # Seeks to immediately following keys.
> iter
> seek-prefix-ge a true
> ```

why was this test passing trySeekUsingNext=true when the iterator was not positioned? Just a test error?


<!-- Sent from Reviewable.io -->

2022-10-31 15:02 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2058)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`level_iter.go` line 346 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2058#-NFiEcg2EITG4-BJkXMU:-NFiYwWW4VAo4EEM3lVN:b4fe3w) ([raw file](https://github.com/cockroachdb/pebble/blob/b87355d373dab0decee2ccf643f3dbd865ddc151/level_iter.go#L346)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you remind me: can both TrySeekUsingNext and RelativeSeek be true? If not, can you add that to the code comment?
</blockquote></details>

at most one can be true. added a comment.
___
*[`testdata/level_iter_seek` line 309 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2058#-NFiG6TxAyUJpjaKT7n_:-NFiYzy826b-W_2XV8U7:bxzpm5l) ([raw file](https://github.com/cockroachdb/pebble/blob/f34af25a01873c9cf027e53147754e96ec8b2b53/testdata/level_iter_seek#L309)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why was this test passing trySeekUsingNext=true when the iterator was not positioned? Just a test error?
</blockquote></details>

yeah just a test error.


<!-- Sent from Reviewable.io -->

2022-10-31 15:17 UTC, jbowens commented
TFTR!

2022-10-31 15:17 UTC, merged