db: fix levelIter TrySeekUsingNext optimization
cockroachdb/pebble pull request #2087
Opened 2022-11-01 21:40 UTC by jbowens

The optimization added in #2085 began using an enabled TrySeekUsingNext to avoid re-seeking within a level's file metadata. This optimization was dependent on the invariant that the iterator remained positioned at previous seek key, so that a subsequent seek to a larger key does not need to backtrack.

This invariant wasn't strictly preserved by the levelIter during SeekPrefixGE calls. During a SeekPrefixGE, the sstable iterator may return nil despite the existence of sstable keys greater than the seek key if the sstable's bloom filter excludes the seek prefix. If the sstable DOES NOT contain any range tombstones, the levelIter advances to the next file only if the file's largest bound indicates that the sstable contains no point keys with prefixes larger than the seek prefix, returning nil if it does not.

However, if the file DOES contain range tombstones, the levelIter returns a synthetic largest boundary key so that the file remains open until the merging iterator passes beyond its bounds. This ensures the file's range deletions' effects on other keys are observed. If another level returned a key greater than this largest boundary key, the merging iterator could step beyond the level's synthetic boundary key.  This step could advance the levelIter to the next file, despite its irrelevance to the original SeekPrefixGE. This step would also break the invariant that the level iterator remained positioned at the seek key.

This commit fixes the bug by comparing the synthetic boundary key to the seek prefix, avoiding ever Next-ing the level iterator beyond the seek prefix.

Based on our current understanding of the issue, this commit will also fix cockroachdb/cockroach#89327. By preventing advancement of the levelIter beyond the seek prefix, the merging iterator will prevent unbounded iteration through sstables exclusively containing range deletions.

Fix #2084.

2022-11-01 21:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2087)
<!-- Reviewable:end -->

2022-11-01 21:46 UTC, jbowens reviewed
It'd be nice to add a new `invariants`-gated assertion around this invariant we rely on, but I've yet to come up with an assertable variant.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2087#-:-NFp865E5lrGQw2RDvPi:b-p74su5)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @itsbilal and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2022-11-02 02:02 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2087)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFq3hbp3eTj-WYZMV_8):*
did you #2058, since #2085 has not merged yet?


<!-- Sent from Reviewable.io -->

2022-11-02 03:30 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2087)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @sumeerbhola)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFq3hbp3eTj-WYZMV_8):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

did you #2058, since #2085 has not merged yet?
</blockquote></details>

lol, sorry, transposed those digits. i will fixup the references in the commit tomorrow


<!-- Sent from Reviewable.io -->

2022-11-02 14:03 UTC, sumeerbhola requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2087)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFsZlXTEgnvxW4CfCVm):*
(perhaps the following phrasing is slightly easier for the reader)

the levelIter does not advance to the next file if the file's largest bound has a prefix larger than the seek prefix, returning nil, else it does advance since the next file could contain the seek prefix.
___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFs_dIH0Z90wcnpTSob):*
and this would happen because another level may not care about prefix matching?
___
*[`-- commits` line 35 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFsaetv-4IYUKImec8O):*
Nice.
Could you add a microbenchmark confirming that it will fix that performance problem?
___
*[`merging_iter.go` line 710 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFsbIg-9OaaqDSNgSSj:-NFsbIg-9OaaqDSNgSSk:bpm2k9j) ([raw file](https://github.com/cockroachdb/pebble/blob/604b4ec50025dedf0a51db27d89f2f5eb64db7d5/merging_iter.go#L710)):*
> ```Go
> 		//    bloom filter check. Avoiding Next-ing the file has a performance
> 		//    benefit of unnecessarily advancing to the next file, but it's also
> 		//    necessary for correctness of some TrySeekUsingNext optimizations
> ```

It seems necessary for correctness of `findFileGE` but deeper in the stack it doesn't seem necessary for correctness since if the file has changed, the `levelIter` will DisableTrySeekUsingNext().

Hmm, it seems I am wrong in my understanding. If the `levelIter` moves too far forward we could have a problem. First SeekPrefixGE(a), and boundary key is a range tombstone at c, and so we move to the next file and we have properly positioned there. Then SeekPrefixGE(b) which has a match in the previous file will erroneously look in the second file and not find b. It seems this problem was masked earlier because `findFileGE` would do the binary search and realize it needed to load the first file.
Is my understanding correct?

We should deterministically turn off the `findFileGE` optimization, like we do with the `disableBoundsOpt` logic in reader.go, so that the metamorphic test can find a problem. Maybe even better, whenever `invariants.Enabled` also do the binary search and check that what is being returned in the optimized path is the same as the binary search. 


<!-- Sent from Reviewable.io -->

2022-11-02 20:37 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2087)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFsZlXTEgnvxW4CfCVm):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

(perhaps the following phrasing is slightly easier for the reader)

the levelIter does not advance to the next file if the file's largest bound has a prefix larger than the seek prefix, returning nil, else it does advance since the next file could contain the seek prefix.
</blockquote></details>

Done
___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFs_dIH0Z90wcnpTSob):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

and this would happen because another level may not care about prefix matching?
</blockquote></details>

Yeah. Even if the other level is a level iter, a bloom filter check that fails to exclude the key can return a key larger than the prefix.
___
*[`-- commits` line 35 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFsaetv-4IYUKImec8O):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Nice.
Could you add a microbenchmark confirming that it will fix that performance problem?
</blockquote></details>

Done.
___
*[`merging_iter.go` line 710 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFsbIg-9OaaqDSNgSSj:-NFu1wol7CWSdkYG5763:b-owomps) ([raw file](https://github.com/cockroachdb/pebble/blob/604b4ec50025dedf0a51db27d89f2f5eb64db7d5/merging_iter.go#L710)):*
>  It seems this problem was masked earlier because findFileGE would do the binary search and realize it needed to load the first file. Is my understanding correct?

Yeah, that matches my understanding.

> We should deterministically turn off the findFileGE optimization, like we do with the disableBoundsOpt logic in reader.go, so that the metamorphic test can find a problem. Maybe even better, whenever invariants.Enabled also do the binary search and check that what is being returned in the optimized path is the same as the binary search.

Good idea. Updated to reuse `disableSeekOpt` for the same deterministic disabling. The separate binary seek assertion is tricky. We may legitimately be positioned at a later file because TrySeekUsingNext can take advantage of the fact that the previous iterator positioning operation discovered the previous file(s) contained only deleted keys.


<!-- Sent from Reviewable.io -->

2022-11-03 15:39 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2087#-:-NFy8P5K8JmvJXn4iQ3h:bg7igkv)* status: all files reviewed, 7 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`-- commits` line 40 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFy4XBpEYHK-7LTUpkz):*
nice!
___
*[`merging_iter.go` line 710 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFsbIg-9OaaqDSNgSSj:-NFy52ED9iKeE28AzAC3:bmp7sgf) ([raw file](https://github.com/cockroachdb/pebble/blob/604b4ec50025dedf0a51db27d89f2f5eb64db7d5/merging_iter.go#L710)):*
> We may legitimately be positioned at a later file because TrySeekUsingNext can take advantage of the fact that the previous iterator positioning operation discovered the previous file(s) contained only deleted keys.

Ah yes, that makes sense. This is a subtlety that is easy to miss, and could affect us in future code optimizations. Could you add a code comment stating that the answer from findFileGE may differ from the binary search case and why that is ok.
___
*[`iterator_test.go` line 2812 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFy8D5P8ItgdARU3BeK:-NFy8D5Q7kWqmzs8nBgR:b-811ivk) ([raw file](https://github.com/cockroachdb/pebble/blob/fdc1623196d2e572472eb9cd3da1b0bbeb2c9ed7/iterator_test.go#L2812)):*
> ```Go
> 	defer func() { require.NoError(b, d.Close()) }()
> 
> 	defer d.NewSnapshot().Close()
> ```

why a snapshot? a code comment would be helpful.


<!-- Sent from Reviewable.io -->

2022-11-03 17:33 UTC, jbowens reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2087#-:-NFyY_tNEzuSiyoCvsIz:b-814g8k)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`merging_iter.go` line 710 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFsbIg-9OaaqDSNgSSj:-NFyYZHJCVV05G0t-rle:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/604b4ec50025dedf0a51db27d89f2f5eb64db7d5/merging_iter.go#L710)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> We may legitimately be positioned at a later file because TrySeekUsingNext can take advantage of the fact that the previous iterator positioning operation discovered the previous file(s) contained only deleted keys.

Ah yes, that makes sense. This is a subtlety that is easy to miss, and could affect us in future code optimizations. Could you add a code comment stating that the answer from findFileGE may differ from the binary search case and why that is ok.
</blockquote></details>

Done.
___
*[`iterator_test.go` line 2812 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2087#-NFy8D5P8ItgdARU3BeK:-NFyWSr96DhpK-JrLhsG:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/fdc1623196d2e572472eb9cd3da1b0bbeb2c9ed7/iterator_test.go#L2812)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why a snapshot? a code comment would be helpful.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-03 17:49 UTC, merged