rfc: virtual sstables in the ingestion path
cockroachdb/pebble pull request #2116
Opened 2022-11-09 23:16 UTC by bananabrick

2022-11-09 23:16 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2116)
<!-- Reviewable:end -->

2022-11-10 03:32 UTC, bananabrick commented
Need to fix a few todos before review

2022-11-14 20:35 UTC, bananabrick reviewed
This should be good for review. I have some minor todos in there, but they shouldn't hinder review.

The RFC discusses the components required to ensure correctness. It doesn't delve into precise implementation details. So, for `Reader.NewRawRangeKeyIter` we mention that we need to perform filtering within the `fragmentBlockIter`, but we don't touch on the precise algorithm to perform such filtering.

As the implementation progresses, we can probably sneak those details into the RFC if necessary.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2116#-:-NGreyBi0w4PzM4GIfSv:b-zqe6t)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-16 15:06 UTC, sumeerbhola requested changes
Generally looks good.
Some of my comments are not about this RFC but ensuring that whatever we do here can be extended by @itsbilal without a lot of refactoring, for the disaggregated shared storage masking use case.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2116#-:-NH-yD5Z9XBr_QuvpDNa:b-j7ksmx)* status: all files reviewed (commit messages unreviewed), 10 unresolved discussions (waiting on @bananabrick, @itsbilal, and @jbowens)

___
*[`docs/RFCS/virtual_sstable.md` line 25 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-pqJGADCidZ4xBahE:-NH-pqJGADCidZ4xBahF:b-4tr2q5) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L25)):*
> ```Markdown
> files, which have no data overlap with other files in the lsm, lower in the lsm
> because of file boundary overlap with files in the lsm. In this case, we are
> forces to place files higher in the lsm, sometimes in L0, which can cause higher
> ```

nit: forced
___
*[`docs/RFCS/virtual_sstable.md` line 76 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-q1K71mkIZ4IdjOyn:-NH-q1K71mkIZ4IdjOyo:b-o1ret0) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L76)):*
> ```Markdown
> ```
> We cannot use virtual sstables in the above scenario for two reasons:
> 1. We don't have a quick method of detecting no data overlap.
> ```

I think for the virtual sst use case where we will mask data (not this RFC, but we should make sure what we are doing here is easily extendable) we are still good in this case since the first virtual sst will have e and the second one p--r.
@itsbilal 
___
*[`docs/RFCS/virtual_sstable.md` line 102 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-qdVJDYuZ2Mb03sKG:-NH-qdVJDYuZ2Mb03sKH:b-pr3161) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L102)):*
> ```Markdown
>   would be additional implementation complexity(see the `FilemetaData` section).
>   We also want to avoid too many virtual sstables in the lsm as they can lead to
>   space amp(see `Compaction` section).
> ```

Again, the masking case will need to do this, but seems like an easy extension.
___
*[`docs/RFCS/virtual_sstable.md` line 109 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-qntjDusxU6Vg108a:-NH-qntjDusxU6Vg108b:b3r74gv) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L109)):*
> ```Markdown
>   1. For CockroachDB's snapshot ingestion, there is one large sst (up to 512MB)
>      and many tiny ones. We can choose the apply this splitting logic only for
>      the large sst. It is ok for the tiny ssts to be ingested into L0.
> ```

For masking (for disaggregated shared storage) we could avoid keeping the local keyspace in blobstore and do the usual snapshot ingest where we lay down a rangedel and ingest a unshared sst.
___
*[`docs/RFCS/virtual_sstable.md` line 150 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-rJf60LIDbAEKjy7L:-NH-rJf60LIDbAEKjy7M:b1qw8pd) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L150)):*
> ```Markdown
> metadata field to indicate the file number of the parent sstable. In the latter
> case, we can use a few of the most significant bits of the 64 bit file number to
> distinguish the virtual sstables.
> ```

I thought the latter was a good idea when originally writing https://github.com/cockroachdb/pebble/issues/1683 but for the masking use case in disaggregated shared storage we cannot put any limit on the number of times a sst will be virtualized (we will prioritize compactions for small ssts to avoid any performance issues, but we can't make any guarantees there). So I now think the former is better
@itsbilal 
___
*[`docs/RFCS/virtual_sstable.md` line 179 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-rxQy8QC74gETzBql:-NH-rxQy8QC74gETzBqm:b8pzimj) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L179)):*
> ```Markdown
> These fields are used for l0 sublevels, pebble tooling, delete compaction hints,
> and a lot of plumbing. We don't need to worry about the L0 sublevels use case
> because we won't have virtual sstables in L0. For the rest of the use cases
> ```

@itsbilal 
Hmm, so we if we do virtualize L0 files for the masking case will we need to iterate over it to construct tight seqnum bounds?
I think its worth looking at the L0SubLevels logic again and see if we can manage with these being lower and upper bounds for the sublevel assignment. I suspect it can since these virtual ssts pointing to the same sst will never overlap in their keyspans.
___
*[`docs/RFCS/virtual_sstable.md` line 220 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-sufo7Wv6F9kqUcGS:-NH-sufpCpgsO_zs1ISU:bjnwt46) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L220)):*
> ```Markdown
> virtual sstables, we can have a case where the last version which references a
> physical sstable is unrefed, but the physical sstable is not added to the
> obsolete table list because its `FilemetaData.refs` count is not 0. Since the
> ```

I didn't understand this scenario where there is no one referencing the physical sstable but the refs count is not zero. Could you elaborate?
___
*[`docs/RFCS/virtual_sstable.md` line 235 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-uElb5kM5rVnZ4rM8:-NH-uElb5kM5rVnZ4rM9:b-n7c8e9) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L235)):*
> ```Markdown
> Deleted files still referenced by older versions are considered zombie sstables.
> For the sake of simplicity, we can modify the definition of zombie sstables to
> include physical sstables which have been virtualized. When the physical sstable
> ```

Don't quite understand this. The clean definition would be that zombie tables are those physical sstables that are not directly or indirectly (via virtual ssts) referenced by the latest version. This is not easy to compute given the incremental computation in `BulkVersionEdit.Apply`. But I think if we kept an additional refcount pointer in the FileMetadata that counts the number of refs in the latest version, we could compute this incrementally. I think it's important not to overcount zombie ssts.

We should consider having some additional counts related to number of physical ssts that have been virtualized, and number of virtual ssts. It would be useful for diagnosis to know if the latter is much larger than the former. 
___
*[`docs/RFCS/virtual_sstable.md` line 261 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-vrhZBRqHZ5vuiJ4J:-NH-vrhZBRqHZ5vuiJ4K:bswk7iq) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L261)):*
> ```Markdown
> We could either have an abstraction over the physical sstable `Reader` per
> virtual sstable, or update the `Reader` API to accept file bounds of the
> sstable. In the latter case, we would create one `Reader` on the physical
> ```

+1 to the latter. We should be caching a single Reader per physical sst.
I think most (all?) of the `tableCacheShard` methods that lookup or construct a `Reader` take a `FileMetadata` parameter, so they can use that to find the `Reader` for the physical sstable, and then use the bounds in the `FileMetadata` (if it is a virtual sst) in creating the sstable iterator (in tableCacheShard.newIters).
___
*[`docs/RFCS/virtual_sstable.md` line 303 at r1](https://reviewable.io/reviews/cockroachdb/peb [...]

2022-11-16 23:16 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2116)* status: all files reviewed (commit messages unreviewed), 9 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`docs/RFCS/virtual_sstable.md` line 76 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-q1K71mkIZ4IdjOyn:-NH1IO3HEYHwbqWXo8Vl:b-qaymuq) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L76)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think for the virtual sst use case where we will mask data (not this RFC, but we should make sure what we are doing here is easily extendable) we are still good in this case since the first virtual sst will have e and the second one p--r.
@itsbilal 
</blockquote></details>

Yea that makes sense. Would the goal be to mask f-n in every single sstable already existing in the lsm?
___
*[`docs/RFCS/virtual_sstable.md` line 102 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-qdVJDYuZ2Mb03sKG:-NH1IpxcANijouG4ymx7:bcxsai1) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L102)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Again, the masking case will need to do this, but seems like an easy extension.
</blockquote></details>

Yea should be easy as long as we can fall back to the worst case of scanning the sstables in L0 to compute smallest/largest sequence numbers.
___
*[`docs/RFCS/virtual_sstable.md` line 109 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-qntjDusxU6Vg108a:-NH1JBny29VoImjfpzw9:b8pphxa) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L109)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

For masking (for disaggregated shared storage) we could avoid keeping the local keyspace in blobstore and do the usual snapshot ingest where we lay down a rangedel and ingest a unshared sst.
</blockquote></details>

Is this saying that in the case where we're ingesting tiny ssts, we avoid the masking + virtualizing and just write a range delete like we currently do?
___
*[`docs/RFCS/virtual_sstable.md` line 150 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-rJf60LIDbAEKjy7L:-NH1JLG8EtmBofU64NnO:bu1l8sa) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L150)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I thought the latter was a good idea when originally writing https://github.com/cockroachdb/pebble/issues/1683 but for the masking use case in disaggregated shared storage we cannot put any limit on the number of times a sst will be virtualized (we will prioritize compactions for small ssts to avoid any performance issues, but we can't make any guarantees there). So I now think the former is better
@itsbilal 
</blockquote></details>

Yea, it seems simpler to assign a unique file number to every virtual sst.
___
*[`docs/RFCS/virtual_sstable.md` line 220 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-sufo7Wv6F9kqUcGS:-NH1JX8T75hk8Dsa6pAL:be4rjzh) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L220)):*
>we can have a case where the last version which references a
physical sstable is unrefed, but the physical sstable is not added to the
obsolete table list because its `FilemetaData.refs` count is not 0. Since the

Example:
There are virtual sstables referring to some physical sstable 'a' and therefore the refs count of the `FilemetaData` associated with 'a' is > 1. The sstable 'a' is only directly referenced by an older Version 'b'. When version 'b' is unrefed, the refcount of the `FilemetaData` associated with a will be decremented but still be at least one. We're going to determine whether to add sstable 'a' to the obsolete table list, and we won't because the ref count of sstable 'a' is not 0.
___
*[`docs/RFCS/virtual_sstable.md` line 261 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-vrhZBRqHZ5vuiJ4J:-NH1YU4pERau_kgv-qjA:bw7pj6x) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L261)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

+1 to the latter. We should be caching a single Reader per physical sst.
I think most (all?) of the `tableCacheShard` methods that lookup or construct a `Reader` take a `FileMetadata` parameter, so they can use that to find the `Reader` for the physical sstable, and then use the bounds in the `FileMetadata` (if it is a virtual sst) in creating the sstable iterator (in tableCacheShard.newIters).
</blockquote></details>

Yea, the latter makes sense to me.
___
*[`docs/RFCS/virtual_sstable.md` line 303 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-xDxDDdoNx_ajD8tQ:-NH1eO8g9h_zeGeG4Zlo:bf08n44) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L303)):*
>  When the ratio of the virtual sst size to the sum-size becomes small (high space amplification), it should be prioritized for compaction.

This ratio will start small and only get larger as other virtual sstables are deleted. For example, if we have to two virtual sstables 'a' and 'b' with sizes 1MB each. Then for sstable 'a' the initial ratio would be 0.5, and once sstable 'b' is deleted the ratio will become 1. Not sure how that indicates space amp. I would think we'd want to improve the odds of a virtual sstable being picked for a compaction as other virtual sstables with the same backing file are deleted.

We can still use the ratio, but it seems like we'd want to pick a virtual sstable for compaction when the ratio becomes too large?


<!-- Sent from Reviewable.io -->

2022-11-17 21:50 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2116)* status: all files reviewed (commit messages unreviewed), 9 unresolved discussions (waiting on @bananabrick, @itsbilal, and @jbowens)

___
*[`docs/RFCS/virtual_sstable.md` line 76 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-q1K71mkIZ4IdjOyn:-NH6Nlqx6Z9STXlOy399:b-uysxnn) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L76)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Yea that makes sense. Would the goal be to mask f-n in every single sstable already existing in the lsm?
</blockquote></details>

Yes, that would be the goal.
___
*[`docs/RFCS/virtual_sstable.md` line 109 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-qntjDusxU6Vg108a:-NH6NvJp9-802Ks5e5S_:b-qtx2w4) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L109)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Is this saying that in the case where we're ingesting tiny ssts, we avoid the masking + virtualizing and just write a range delete like we currently do?
</blockquote></details>

Correct. We can use the rangedel scheme when we are not importing shared ssts (from another LSM) directly into L5/L6.
___
*[`docs/RFCS/virtual_sstable.md` line 220 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-sufo7Wv6F9kqUcGS:-NH6OesiArv5DvM_pjCR:bmppjsj) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L220)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

>we can have a case where the last version which references a
physical sstable is unrefed, but the physical sstable is not added to the
obsolete table list because its `FilemetaData.refs` count is not 0. Since the

Example:
There are virtual sstables referring to some physical sstable 'a' and therefore the refs count of the `FilemetaData` associated with 'a' is > 1. The sstable 'a' is only directly referenced by an older Version 'b'. When version 'b' is unrefed, the refcount of the `FilemetaData` associated with a will be decremented but still be at least one. We're going to determine whether to add sstable 'a' to the obsolete table list, and we won't because the ref count of sstable 'a' is not 0.





</blockquote></details>

I'm still not getting it. Currently `FileMetadata.refs` is incremented/decremented via the btree in `LevelMetadata` which lives in a `Version`. So at most 1 ref per Version for a FileMetadata. Different versions with the same file may share a ref if they share a btree node. We are changing `FileMetadata.refs` to be a pointer, so that virtual sst FileMetadata will use the same `refs` pointer. So a `LevelMetadata` LM2 that has 2 virtual ssts that refer to the same physical file will hold 2 refs. `LevelMetadata` LM1 that has only 1 physical sst will hold 1 ref. So the total is 3 (let's say the btree nodes were different). When LM1 goes away the refs value will be decremented once, and will equal 2. When LM2 goes away the refs value will be decremented twice and will become 0.
What am I missing?
___
*[`docs/RFCS/virtual_sstable.md` line 303 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-xDxDDdoNx_ajD8tQ:-NH6Y7eI6gWFMbfx2GRV:b-4dhvmk) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L303)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

>  When the ratio of the virtual sst size to the sum-size becomes small (high space amplification), it should be prioritized for compaction.

This ratio will start small and only get larger as other virtual sstables are deleted. For example, if we have to two virtual sstables 'a' and 'b' with sizes 1MB each. Then for sstable 'a' the initial ratio would be 0.5, and once sstable 'b' is deleted the ratio will become 1. Not sure how that indicates space amp. I would think we'd want to improve the odds of a virtual sstable being picked for a compaction as other virtual sstables with the same backing file are deleted.

We can still use the ratio, but it seems like we'd want to pick a virtual sstable for compaction when the ratio becomes too large?


</blockquote></details>

Yes, something like that, but I didn't mean to define the ratio using the size of 'a'. The ratio is one value defined for the physical sst in the latest version. The virtual ssts "inherit" that value too, since they are the ones who will need to be picked in compactions. More specifically, I was imagining something like:

```
type FileMetadata struct {
  // State needed by both physical and virtual ssts and that is different for each.
  ...
  
  // Non-nil if virtual sst. 
  physicalSST *FileMetadata
  
  // Non-nil if physical sst.
  physicalState *physicalState
}

type physicalState struct {
  // Total refs across all virtual ssts * versions. That is, if the same virtual sst is
  // present in multiple versions, it may have multiple refs, if the btree node is not
  // the same.
  totalRefs int32
  
  // Number of virtual ssts in the latest version that refer to this physical SST. Will
  // be 1 if there is only a physical sst, or there is only 1 virtual sst referencing
  // this physical sst.
  // INVARIANT: refsInLatestVersion <= totalRefs
  // refsInLatestVersion == 0 is a zombie sstable.
  refsInLatestVersion int32

  fileSize uint64

  // If sst is not virtualized and in latest version virtualSizeSumInLatestVersion == fileSize.
  // If virtualSizeSumInLatestVersion > 0 and virtualSizeSumInLatestVersion/fileSize is very small,
  // the corresponding virtual sst(s) should be candidates for compaction. These candidates
  // can be tracked via btree annotations.
  // Incrementlly updated in BulkVersionEdit.Apply, when updating refsInLatestVersion.
  virtualSizeSumInLatestVersion uint64
}
```


<!-- Sent from Reviewable.io -->

2022-11-22 01:00 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2116)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`docs/RFCS/virtual_sstable.md` line 67 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH6WJXW8mO1T4rRyBh0:-NHRQUqi00uU3md_ZNqI:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L67)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Probably also worth mentioning here (or in the section before) that the easier-to-solve case happens very regularly when an sstable spans a range boundary (which pebble has no knowledge of), and we ingest a snapshot of a range in between the two already-present ranges. The harder case over here is less likely to happen.
</blockquote></details>

Done.
___
*[`docs/RFCS/virtual_sstable.md` line 76 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-q1K71mkIZ4IdjOyn:-NHRQXDEEvQzhPMg1ojc:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L76)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

@bananabrick Yes, we'd mask the entirety of f-n in every sstable in the LSM. You could possibly mention this here as a feature that would be supported with the virtual sstable work (i.e. not every physical sstable key will belong to a virtual sstable), and some , and that uses of it will come later. 
</blockquote></details>

Done.
___
*[`docs/RFCS/virtual_sstable.md` line 102 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-qdVJDYuZ2Mb03sKG:-NHRQumY6OA49ofbmnOr:b-9fns1z) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L102)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The masking case will also, in the common disaggregated storage CockroachDB use case, only split one L0 sstable into at most two virtual sstables. But yeah not important to mention that here.
</blockquote></details>

Added a bit about the masking case use case in L0.
___
*[`docs/RFCS/virtual_sstable.md` line 109 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-qntjDusxU6Vg108a:-NHRUIXt7VH3gTcuPC3B:bv50dej) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L109)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

@bananabrick that's correct, the tiny ssts will be the local keyspace in a snapshot ingest.
</blockquote></details>

Added a bit about the masking case.
___
*[`docs/RFCS/virtual_sstable.md` line 150 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-rJf60LIDbAEKjy7L:-NHRVTMJ1kysYyxIgyXz:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L150)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I also agree we should use a new FileNum, incrementally assigned like all other FileNums. An additional field can hold the physical FileNum. That also makes it easier to incorporate into the disaggregated storage case (where the physical file could be owned by another node).
</blockquote></details>

Done.
___
*[`docs/RFCS/virtual_sstable.md` line 179 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-rxQy8QC74gETzBql:-NHRW6OJA2eXAzj0KFQd:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L179)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

That's accurate, we can get away with a looser seqnum bound in this case because the split files will never by definition overlap in user keys. Also easier to do now that we never split user keys across multiple files. 
</blockquote></details>

Done.
___
*[`docs/RFCS/virtual_sstable.md` line 220 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-sufo7Wv6F9kqUcGS:-NHRZhjV4Usml5bjb-Cs:b-bwrvok) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L220)):*
When LM1 goes away the refcount will be decremented to 2. Since the refcount isn't 0, the physical sst number will not be added to the obsolete table list and it shouldn't be.


> Since virtual sstables keep track of their parent physical sstable, we can just add the physical sstable
to the obsolete table list when the last virtual sstable which references it is deleted.

So we'd have to change the code a bit to make sure that the physical sst number is added to the obsolete file list when the refcount eventually hits 0 and the refcount will hit 0 when the last virtual sst is unrefed. Maybe I'm missing something.
___
*[`docs/RFCS/virtual_sstable.md` line 235 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-uElb5kM5rVnZ4rM8:-NHRkbpW5zrqEHx2KInP:b-bw8e14) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L235)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Don't quite understand this. The clean definition would be that zombie tables are those physical sstables that are not directly or indirectly (via virtual ssts) referenced by the latest version. This is not easy to compute given the incremental computation in `BulkVersionEdit.Apply`. But I think if we kept an additional refcount pointer in the FileMetadata that counts the number of refs in the latest version, we could compute this incrementally. I think it's important not to overcount zombie ssts.

We should consider having some additional counts related to number of physical ssts that have been virtualized, and number of virtual ssts. It would be useful for diagnosis to know if the latter is much larger than the former. 
</blockquote></details>

Updated.
___
*[`docs/RFCS/virtual_sstable.md` line 287 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH6_ayW-vRYnkFv-zNh:-NHRWzJa1df2Yz-RC9SZ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L287)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

In addition to this, you'd also need to update the `SetBounds` logic to never set the bounds of an sstable iterator (either singleLevelIterator or twoLevelIterator) to be outside the bounds of the virtual sstable. The bounds code does a lot of optimizations to just stop bounds-checking if the entirety of an sstable is within the bounds, but for virtual sstables you'd still need to keep bounds checks around because even if the entirety of a virtual sstable is within bounds, the physical sstable could span outside it, and you don't want to unintentionally surface keys that are masked or in other virtual sstables.
</blockquote></details>

Done.
___
*[`docs/RFCS/virtual_sstable.md` line 303 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-xDxDDdoNx_ajD8tQ:-NHRbCvo3lIwegW8q0TS:brj81fd) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L303)):*
Updated. Didn't add all the code details from the struct, but wrote a paragraph on how we'll manage zombie sstables and compaction picking.

>   // Non-nil if virtual sst. 
>   physicalSST *FileMetadata


We seem to be accumulating many fields which are optional in the file metadata. Each of these occupy 8 bytes per file metadata. I wonder if we should embed a struct in the DB struct for these optional fields.

Something like:

```
type DB struct {

    optionalFileMeta st [...]

2022-11-22 14:47 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2116#-:-NHUncWR9028EvjCHKA5:bg7igkv)* status: all files reviewed, 12 unresolved discussions (waiting on @bananabrick, @itsbilal, and @jbowens)

___
*[`docs/RFCS/virtual_sstable.md` line 220 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-sufo7Wv6F9kqUcGS:-NHUk7Or9UeCVKDE9Pmw:b-o4cxfe) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L220)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

When LM1 goes away the refcount will be decremented to 2. Since the refcount isn't 0, the physical sst number will not be added to the obsolete table list and it shouldn't be.


> Since virtual sstables keep track of their parent physical sstable, we can just add the physical sstable
to the obsolete table list when the last virtual sstable which references it is deleted.

So we'd have to change the code a bit to make sure that the physical sst number is added to the obsolete file list when the refcount eventually hits 0 and the refcount will hit 0 when the last virtual sst is unrefed. Maybe I'm missing something.


</blockquote></details>

Maybe we are saying the same thing. I was objecting to the phrasing:

`With virtual sstables, we can have a case where the last version which references a physical sstable is unrefed, but the physical sstable is not added to the obsolete table list because its `FilemetaData.refs` count is not 0.`

We decrement FileMetadata refs when the btree node is being deleted because no version is referencing the node, so I still don't see a case where there is no version referencing a file and the refs is > 0.
___
*[`docs/RFCS/virtual_sstable.md` line 303 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-xDxDDdoNx_ajD8tQ:-NHUmtP10T5Hu8kAMPP6:b-6s2fxd) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L303)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Updated. Didn't add all the code details from the struct, but wrote a paragraph on how we'll manage zombie sstables and compaction picking.

>   // Non-nil if virtual sst. 
>   physicalSST *FileMetadata


We seem to be accumulating many fields which are optional in the file metadata. Each of these occupy 8 bytes per file metadata. I wonder if we should embed a struct in the DB struct for these optional fields.

Something like:

```
type DB struct {

    optionalFileMeta struct {
          physicalState map[FileNum]physicalState
          parentSST map[FileNum]FileNum

          // Other range key state
          ...

          // Other L0 sublevel state
          ...
}
```

Could save > 32 bytes per `FilemetaData` overall in the general case where an sst is not virtual, not in L0, doesn't have range keys.
</blockquote></details>

I don't think optional fields should be emdedded in the DB struct. But we should move them into single struct pointers in FileMetadata. I am all for FileMetadata cleanup since we already have optional stuff there like in https://github.com/cockroachdb/pebble/issues/2047.
___
*[`docs/RFCS/virtual_sstable.md` line 81 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NHUiO89B7-kkrFy6FNO:-NHUiO89B7-kkrFy6FNP:b-6zr506) ([raw file](https://github.com/cockroachdb/pebble/blob/e4ef936ba88c62bb39ffbf8aa5905afb28441e18/docs/RFCS/virtual_sstable.md#L81)):*
> ```Markdown
> 
> Note that in Cockroach, the easier to solve case where an ingesting sstable can
> slide in between two existing sstables is more likely to happen. It occurs when
> ```

nit: "slide in between two existing sstables" sounds like we don't need virtual sstables. Did you mean that the ingesting sstable overlaps with the bounds of one existing sstable and can slide in between two virtual ssts constructed from that existing sstable?

I prefer @itsbilal 's wording in his comment, since it talks about the actual CockroachDB scenario: two existing ranges with one sstable spanning the two ranges, and a new range being added that falls between these two ranges.


<!-- Sent from Reviewable.io -->

2022-11-22 16:35 UTC, itsbilal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> modulo open comments

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2116#-:-NHVBS9O2nBogmNoVV8Q:bncunyn)* status: all files reviewed, 14 unresolved discussions (waiting on @bananabrick, @jbowens, and @sumeerbhola)

___
*[`docs/RFCS/virtual_sstable.md` line 28 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NHV6XhN3-JmGylJJS5K:-NHV6XhO07brxifcPc3q:bgmijw2) ([raw file](https://github.com/cockroachdb/pebble/blob/e4ef936ba88c62bb39ffbf8aa5905afb28441e18/docs/RFCS/virtual_sstable.md#L28)):*
> ```Markdown
> read-amp and unnecessary write-amp as the file is moved lower down the lsm. See
> https://github.com/cockroachdb/cockroach/issues/80589 for the problem occurring
> in practice.
> ```

Not a big deal, but it's worthwhile mentioning here that this design will eventually also be used to enable the disaggregated storage use-case. You could link to that RFC: https://github.com/cockroachdb/cockroach/pull/70419/files
___
*[`docs/RFCS/virtual_sstable.md` line 81 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NHUiO89B7-kkrFy6FNO:-NHV8lMN348LRfhFt8WY:bn4sivr) ([raw file](https://github.com/cockroachdb/pebble/blob/e4ef936ba88c62bb39ffbf8aa5905afb28441e18/docs/RFCS/virtual_sstable.md#L81)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: "slide in between two existing sstables" sounds like we don't need virtual sstables. Did you mean that the ingesting sstable overlaps with the bounds of one existing sstable and can slide in between two virtual ssts constructed from that existing sstable?

I prefer @itsbilal 's wording in his comment, since it talks about the actual CockroachDB scenario: two existing ranges with one sstable spanning the two ranges, and a new range being added that falls between these two ranges.
</blockquote></details>

Yeah I agree that "slide in between two existing sstables" is confusing. Feel free to copy the wording in my comment.
___
*[`docs/RFCS/virtual_sstable.md` line 120 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NHVAsKP9Onj8Cr1dAP2:-NHVAsKP9Onj8Cr1dAP3:bbn7ufz) ([raw file](https://github.com/cockroachdb/pebble/blob/e4ef936ba88c62bb39ffbf8aa5905afb28441e18/docs/RFCS/virtual_sstable.md#L120)):*
> ```Markdown
>      higher level is smaller, so there is lower risk of littering the LSM with
>      long-lived small virtual ssts.
>   3. For disaggregated storage implementation, we can avoid masking for tiny
> ```

I believe this is the first mention of masking / excising but it's not defined otherwise in this RFC. You could end this sentence with "more details on that are out of scope for this RFC" to avoid questions about this, and that also avoids you having to define what you mean by masking.
___
*[`docs/RFCS/virtual_sstable.md` line 191 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NHVAacG3suMiELdwINW:-NHVAQRb5j-jS8NmP2nP:b-r1og4s) ([raw file](https://github.com/cockroachdb/pebble/blob/e4ef936ba88c62bb39ffbf8aa5905afb28441e18/docs/RFCS/virtual_sstable.md#L191)):*
> ```Markdown
> and an upper bound for the largest seq number work.
> 
> For the disaggregated storage masking use case, we would need to support the
> ```

I... don't think this is accurate, or in line with my comment above? We don't need tight seqnum bounds for L0 virtual sstables. Either way it's probably a good idea for this RFC to not be overly prescriptive on disaggregated storage just to keep its scope small. I would just delete this paragraph entirely.


<!-- Sent from Reviewable.io -->

2022-11-22 19:54 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2116)* status: all files reviewed, 12 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`docs/RFCS/virtual_sstable.md` line 220 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-sufo7Wv6F9kqUcGS:-NHVpTy58NFBPLAv6DGB:b1j0vfa) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L220)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Maybe we are saying the same thing. I was objecting to the phrasing:

`With virtual sstables, we can have a case where the last version which references a physical sstable is unrefed, but the physical sstable is not added to the obsolete table list because its `FilemetaData.refs` count is not 0.`

We decrement FileMetadata refs when the btree node is being deleted because no version is referencing the node, so I still don't see a case where there is no version referencing a file and the refs is > 0.

</blockquote></details>

Clarified the wording. Added a notion of direct/indirect references.
___
*[`docs/RFCS/virtual_sstable.md` line 303 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NH-xDxDDdoNx_ajD8tQ:-NHVoohN8Yhgn5w1raQn:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/536e5ae4ff23114dbb728ee6958c4aca15332061/docs/RFCS/virtual_sstable.md#L303)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't think optional fields should be emdedded in the DB struct. But we should move them into single struct pointers in FileMetadata. I am all for FileMetadata cleanup since we already have optional stuff there like in https://github.com/cockroachdb/pebble/issues/2047.
</blockquote></details>

Done.
___
*[`docs/RFCS/virtual_sstable.md` line 120 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NHVAsKP9Onj8Cr1dAP2:-NHVqLQk4aGlN8GIJhx1:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e4ef936ba88c62bb39ffbf8aa5905afb28441e18/docs/RFCS/virtual_sstable.md#L120)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I believe this is the first mention of masking / excising but it's not defined otherwise in this RFC. You could end this sentence with "more details on that are out of scope for this RFC" to avoid questions about this, and that also avoids you having to define what you mean by masking.
</blockquote></details>

Done.
___
*[`docs/RFCS/virtual_sstable.md` line 191 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2116#-NHVAacG3suMiELdwINW:-NHVq2Le7RLhb-YoZyce:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e4ef936ba88c62bb39ffbf8aa5905afb28441e18/docs/RFCS/virtual_sstable.md#L191)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I... don't think this is accurate, or in line with my comment above? We don't need tight seqnum bounds for L0 virtual sstables. Either way it's probably a good idea for this RFC to not be overly prescriptive on disaggregated storage just to keep its scope small. I would just delete this paragraph entirely.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-22 20:41 UTC, merged