internal/keyspan: modify FragmentIterator seek semantics
cockroachdb/pebble pull request #2146
Opened 2022-11-20 18:09 UTC by jbowens

Alter the semantics of SeekGE and SeekLT on FragmentIterator. Previously, FragmentIterator's seek operations were defined only in terms of span start keys. This commit changes the seek operations to be defined in terms of the keys contained by the span. A SeekGE now seeks to the first span containing a key ≥ the seek key, and a SeekLT now seeks to the last span containing a key < seek key. These new semantics match the typical top-level iterator use.

With these new semantics, SeekLT can still be implemented in terms of a simple span start key seek. Seeking to the last span containing a key < seek key is equivalent to seeking to the last span with a start key less the given key.

However, SeekGE implementations now require an extra key comparison and sometimes a Next. Since top-level iterator requires the containment semantics anyways, this key comparison and Next is only being moved down the stack into the interface implementation. When using the keyspan merging iterator, the keyspan.MergingIter's SeekGE implementation performs a SeekLT per-level, which suffers no additional overhead.

With the MergingIter and DefragmentingIter implementations, these new semantics reduce the amount of work performed during a seek. The previous iterator stack's SeekGE looked like (left-to-right, top-down):

```
                         InterleavingIter.SeekGE
                                    │
                   ╭────────────────┴───────────────╮
                   │                                │
        DefragmentingIter.SeekLT         DefragmentingIter.Next()
                   │                                │
       ╭───────────┴───╮                            │
       │               │                            │
 MergingIter.SeekLT    ├── defragmentFwd            ├── defragmentFwd
       │               │                            │
       │               ╰── defragmentBwd            ╰── defragmentFwd
       ╰───────────╮
                   │
       ╭───────────┴───────────╮
       │                       │
 MergingIter.SeekGE      MergingIter.Prev
       │
       ╰─╶╶ per level╶╶ ─╮
                         │
             ╭───────────┴───────────╮
             │                       │
         <?>.SeekLT              <?>.Next
```

The new iterator stack's SeekGE, assuming it doesn't hit the new defragmenting fast path, looks like:
```
                         InterleavingIter.SeekGE
                                    │
                         DefragmentingIter.SeekGE
                                    │
                   ╭────────────────┴───────────────╮
                   │                                ├── defragmentBwd*
             MergingIter.SeekGE                     │
                   │                                ╰── defragmentFwd
                   ╰─╶╶ per level╶╶ ─╮
                                     │
                                     │
                                     ├── <?>.SeekLT
                                     │
                                     ╰── <?>.Next
```

\* — The call to defragmentBackward during SeekGE may now sometimes be elided, specifically if the span discovered by MergingIter.SeekGE does not contain the seek key within its bounds.

Note that in this interface, there are no calls to any of the leaf FragmentIterator's SeekGE methods which would suffer the extra key comparison and Next. Instead, the MergingIter calls SeekLT and unconditionally Nexts each of the leafs as a part of its logic to fragment bounds across levels.

This reduced work for seeks has a large impact on the MVCCGet and MVCCScan microbenchmarks in the presence of range keys.

```
name                                                                      old time/op    new time/op     delta
MVCCGet_Pebble/batch=false/versions=1/valueSize=8/numRangeKeys=0-24         6.30µs ± 1%     6.22µs ± 2%      ~     (p=0.095 n=5+5)
MVCCGet_Pebble/batch=false/versions=1/valueSize=8/numRangeKeys=1-24         11.5µs ± 1%     10.3µs ± 1%    -9.95%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=false/versions=1/valueSize=8/numRangeKeys=100-24        118µs ± 1%       79µs ± 2%   -33.14%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8/numRangeKeys=0-24        23.9µs ± 1%     24.1µs ± 2%      ~     (p=0.310 n=5+5)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8/numRangeKeys=1-24        31.7µs ± 2%     29.6µs ± 1%    -6.65%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8/numRangeKeys=100-24       109µs ± 1%       69µs ± 2%   -36.58%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=false/versions=100/valueSize=8/numRangeKeys=0-24        100µs ± 1%       99µs ± 3%      ~     (p=0.310 n=5+5)
MVCCGet_Pebble/batch=false/versions=100/valueSize=8/numRangeKeys=1-24        110µs ± 1%      106µs ± 2%    -3.24%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=false/versions=100/valueSize=8/numRangeKeys=100-24      197µs ± 2%      153µs ± 1%   -22.75%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=0-24          3.74µs ± 1%     3.57µs ± 1%    -4.47%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=1-24          6.01µs ± 1%     4.93µs ± 2%   -17.86%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=100-24        66.1µs ± 1%     28.8µs ± 1%   -56.35%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=0-24         20.4µs ± 1%     20.4µs ± 1%      ~     (p=0.690 n=5+5)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=1-24         25.9µs ± 1%     23.9µs ± 3%    -7.79%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=100-24       89.3µs ± 1%     50.2µs ± 2%   -43.76%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=true/versions=100/valueSize=8/numRangeKeys=0-24        98.7µs ± 1%     97.9µs ± 1%      ~     (p=0.151 n=5+5)
MVCCGet_Pebble/batch=true/versions=100/valueSize=8/numRangeKeys=1-24         106µs ± 1%      103µs ± 1%    -2.63%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=true/versions=100/valueSize=8/numRangeKeys=100-24       179µs ± 3%      131µs ± 2%   -26.75%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=0-24            10.9µs ± 3%     10.7µs ± 1%      ~     (p=0.151 n=5+5)
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=1-24            17.9µs ± 1%     16.1µs ± 2%   -10.35%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=100-24           172µs ± 1%       94µs ± 2%   -45.23%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=2/valueSize=64/numRangeKeys=0-24            13.0µs ± 1%     13.1µs ± 2%      ~     (p=0.690 n=5+5)
MVCCScan_Pebble/rows=1/versions=2/valueSize=64/numRangeKeys=1-24            21.1µs ± 1%     19.0µs ± 2%    -9.70%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=2/valueSize=64/numRangeKeys=100-24           158µs ± 1%       83µs ± 3%   -47.57%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=10/valueSize=64/numRangeKeys=0-24           20.3µs ± 1%     20.1µs ± 2%      ~     (p=0.151 n=5+5)
MVCCScan_Pebble/rows=1/versions=10/valueSize=64/numRangeKeys=1-24           30.6µs ± 2%     27.6µs ± 1%    -9.70%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=10/valueSize=64/numRangeKeys=100-24          160µs ± 2%       88µs ± 3%   -45.10%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=100/valueSize=64/numRangeKeys=0-24          41.5µs ± 1%     41.1µs ± 1%    -0.97%  (p=0.048 n=5+5)
MVCCScan_Pebble/rows=1/versions=100/valueSize=64/numRangeKeys=1-24          50.9µs ± 1%     48.6µs ± 2%    -4.67%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=100/valueSize=64/numRangeKeys=100-24         140µs ± 2%       94µs ± 1%   -32.43%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10/versions=1/valueSize=64/numRangeKeys=0-24           15.6µs ± 2%     16.1µs ± 1%    +3.21%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10/versions=1/valueSize=64/numRangeKeys=1-24           24.0µs ± 1%     23.1µs ± 2%    -3.87%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=10/ [...]

2022-11-20 18:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2146)
<!-- Reviewable:end -->

2022-11-21 23:18 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2146)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @sumeerbhola)

___
*[`internal/keyspan/level_iter.go` line 190 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NHRTvzV1P86EmMQkH-0:-NHRTvzV1P86EmMQkH-1:byyykya) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/level_iter.go#L190)):*
> ```Go
> 	if f != nil && l.keyType == manifest.KeyTypeRange && l.cmp(key, f.SmallestRangeKey.UserKey) < 0 {
> 		prevFile := l.files.Prev()
> 		l.files.Next()
> ```

I owe unit tests for the keyspan level iter for these cases.


<!-- Sent from Reviewable.io -->

2022-11-29 18:51 UTC, sumeerbhola requested changes
I haven't finished reading `keyspan.MergingIter` because I don't understand the need to do `SeekLT` on the underlying `FragmentIterators` when doing `MergingIter.SeekGE`

> Reviewed 17 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2146#-:-NI3iPVm8368d7F3gmuZ:b-2xzjad)* status: 17 of 18 files reviewed, 9 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`-- commits` line 67 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3IbQi1iIvd2_ve9Zx):*
this ascii art really helped!
Do we have something like this in a code comment which illustrates the (a) logical interfaces involved in the iterator tree, (b) the typical struct types providing the implementation?
___
*[`internal/keyspan/interleaving_iter.go` line 783 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3aBOk065U2PFOV2AT:-NI3aBOk065U2PFOV2AU:bcg964i) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/interleaving_iter.go#L783)):*
> ```Go
> }
> 
> // keyspanSeekGE seeks the keyspan iterator to the first span covering k ≥ key.
> ```

what is `k` in this code comment?
___
*[`internal/keyspan/interleaving_iter.go` line 790 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3aEj16eKEsIxU6jit:-NI3aEj16eKEsIxU6jiu:b-89a4l7) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/interleaving_iter.go#L790)):*
> ```Go
> }
> 
> // keyspanSeekLT seeks the keyspan iterator to the last span covering k < key.
> ```

Ditto
___
*[`internal/keyspan/iter.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3ZVOS2dfHqRhhrbLF:-NI3ZVOS2dfHqRhhrbLG:btk6js7) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/iter.go#L116)):*
> ```Go
> 		h := int(uint(i.index+upper) >> 1) // avoid overflow when computing h
> 		// i.index ≤ h < upper
> 		if i.cmp(key, i.spans[h].Start) > 0 {
> ```

key > i.spans[h].Start, causes us to exclude h, so we are looking for the first index where key <= i.spans[index].Start. The code comments here could be improved in that we should define f.

Also, since we have all the spans, can we just change the code to do a binary search using i.spans[h].End and avoid the extra logic below?
___
*[`internal/keyspan/level_iter.go` line 190 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NHRTvzV1P86EmMQkH-0:-NI3bei8ELLERWE5EMjb:b-sbc63f) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/level_iter.go#L190)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I owe unit tests for the keyspan level iter for these cases.
</blockquote></details>

I didn't understand this code change. On master, if `prevFile == nil` we were leaving the `manifest.LevelIterator` positioned at nil? How does the FragmentIterator semantic change result in the need for the change?
___
*[`internal/keyspan/merging_iter.go` line 347 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3gemI4tjMGrKTaS34:-NI3gemI4tjMGrKTaS35:b9n1o27) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/merging_iter.go#L347)):*
> ```Go
> 	m.invalidate() // clear state about current position
> 
> 	// SeekGE(k) seeks to the first span with a end key greater than the given
> ```

nit: an end key ...
___
*[`internal/keyspan/merging_iter.go` line 349 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3i8iY-0OXEPLQ2Man:-NI3i8iY-0OXEPLQ2Mao:b-og9eve) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/merging_iter.go#L349)):*
> ```Go
> 	// SeekGE(k) seeks to the first span with a end key greater than the given
> 	// key. The merged span M that we're searching for might straddle the seek
> 	// `key`. In this case, the M.Start may be a key ≤ the seek key.
> ```

I don't understand why we need to use SeekLT here.
___
*[`internal/keyspan/seek.go` line 11 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3JKnh1CKcZ4Nx_zz6:-NI3JKnh1CKcZ4Nx_zz7:bgd4umb) ([raw file](https://github.com/cockroachdb/pebble/blob/87eccabb90a3692dc75dd302a686773723f1acb1/internal/keyspan/seek.go#L11)):*
> ```Go
> // SeekGE seeks to the span that contains the target key or the first span past
> // the target key.
> func SeekGE(cmp base.Compare, iter FragmentIterator, key []byte) *Span {
> ```

Glad to see this code deletion!
___
*[`sstable/block.go` line 1280 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3KPEDBIGP6hcZF_4k:-NI3KPEDBIGP6hcZF_4l:b-rt6sb) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/sstable/block.go#L1280)):*
> ```Go
> // SeekGE implements (keyspan.FragmentIterator).SeekGE.
> func (i *fragmentBlockIter) SeekGE(k []byte) *keyspan.Span {
> 	if s := i.SeekLT(k); s != nil && i.blockIter.cmp(k, s.End) < 0 {
> ```

For the case where this comparison is false, is the `gatherBackward` work happening in `SeekLT` unnecessary?
If so, maybe worth adding a TODO pointing out this future optimization.


<!-- Sent from Reviewable.io -->

2022-12-15 21:23 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2146)* status: 0 of 25 files reviewed, 8 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`-- commits` line 67 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3IbQi1iIvd2_ve9Zx):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this ascii art really helped!
Do we have something like this in a code comment which illustrates the (a) logical interfaces involved in the iterator tree, (b) the typical struct types providing the implementation?
</blockquote></details>

added this as an ASCII code comment on the range key iterator config type. is this what you had in mind? 
___
*[`internal/keyspan/interleaving_iter.go` line 783 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3aBOk065U2PFOV2AT:-NIJMzX3Eo0I1Q_gejlc:b-886gsx) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/interleaving_iter.go#L783)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what is `k` in this code comment?
</blockquote></details>

Fixed
___
*[`internal/keyspan/interleaving_iter.go` line 790 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3aEj16eKEsIxU6jit:-NIJN-g78Dj0JQnBq6wc:b-886gsx) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/interleaving_iter.go#L790)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Fixed
___
*[`internal/keyspan/iter.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3ZVOS2dfHqRhhrbLF:-NIJPJrm6BFrR1BFdwsP:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/iter.go#L116)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

key > i.spans[h].Start, causes us to exclude h, so we are looking for the first index where key <= i.spans[index].Start. The code comments here could be improved in that we should define f.

Also, since we have all the spans, can we just change the code to do a binary search using i.spans[h].End and avoid the extra logic below?
</blockquote></details>

Done.
___
*[`internal/keyspan/level_iter.go` line 190 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NHRTvzV1P86EmMQkH-0:-NJMcvDt-k4Lr2zNaGbh:bi6q8m2) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/level_iter.go#L190)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't understand this code change. On master, if `prevFile == nil` we were leaving the `manifest.LevelIterator` positioned at nil? How does the FragmentIterator semantic change result in the need for the change?
</blockquote></details>

I'm still trying to understand why we never saw failures from this before.

I separated this change out into #2187, along with some new related invariant checking. My understanding is that previously, we would 'peek' back at the previous sstable. If there was a previous file, we'd synthesize an empty span that straddles the boundaries of the sstable. We'd then reposition `l.files` back onto our current file. But if there was no previous file, we left the iterator positioned at the exhausted position behind the current file. A subsequent Prev would prev the `manifest.LevelIterator` again, even though the `LevelIterator` was already exhausted in the reverse direction.
___
*[`internal/keyspan/merging_iter.go` line 349 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3i8iY-0OXEPLQ2Man:-NIJNGNF6PngcjPnkL8L:bnipos0) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/merging_iter.go#L349)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't understand why we need to use SeekLT here.
</blockquote></details>

Expanded the comment to explain this more thoroughly
___
*[`internal/keyspan/seek.go` line 11 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3JKnh1CKcZ4Nx_zz6:-NIJNRPDBKQgXETm2-03:b-j1we20) ([raw file](https://github.com/cockroachdb/pebble/blob/87eccabb90a3692dc75dd302a686773723f1acb1/internal/keyspan/seek.go#L11)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Glad to see this code deletion!
</blockquote></details>

:raised_hands: 
___
*[`sstable/block.go` line 1280 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3KPEDBIGP6hcZF_4k:-NIJS5Uv5wN7oMpk5IuU:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/sstable/block.go#L1280)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

For the case where this comparison is false, is the `gatherBackward` work happening in `SeekLT` unnecessary?
If so, maybe worth adding a TODO pointing out this future optimization.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-21 01:38 UTC, sumeerbhola requested changes
> Reviewed 1 of 19 files at r2, 4 of 5 files at r3, 18 of 19 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2146)* status: 23 of 25 files reviewed, 9 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`-- commits` line 67 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3IbQi1iIvd2_ve9Zx):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

added this as an ASCII code comment on the range key iterator config type. is this what you had in mind? 
</blockquote></details>

Which source file -- somehow I am not seeing it?
___
*[`internal/keyspan/iter.go` line 109 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NJmI7YfCn7iYDt3qgq7:-NJmI7YfCn7iYDt3qgq8:bf843rt) ([raw file](https://github.com/cockroachdb/pebble/blob/76029d54c7f124a919343829f67bd9c563224b0e/internal/keyspan/iter.go#L109)):*
> ```Go
> 	// NB: manually inlined sort.Search is ~5% faster.
> 	//
> 	// Define f(j) = true iff the span i.spans[j] is strictly before `key`
> ```

f(j) = false?
___
*[`internal/keyspan/level_iter.go` line 190 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NHRTvzV1P86EmMQkH-0:-NJmIl1n8BM3FcbLRGVV:b2nhysk) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/level_iter.go#L190)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I'm still trying to understand why we never saw failures from this before.

I separated this change out into #2187, along with some new related invariant checking. My understanding is that previously, we would 'peek' back at the previous sstable. If there was a previous file, we'd synthesize an empty span that straddles the boundaries of the sstable. We'd then reposition `l.files` back onto our current file. But if there was no previous file, we left the iterator positioned at the exhausted position behind the current file. A subsequent Prev would prev the `manifest.LevelIterator` again, even though the `LevelIterator` was already exhausted in the reverse direction.
</blockquote></details>

ack


<!-- Sent from Reviewable.io -->

2022-12-21 01:38 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2146)* status: 23 of 25 files reviewed, 9 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`-- commits` line 67 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3IbQi1iIvd2_ve9Zx):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Which source file -- somehow I am not seeing it?
</blockquote></details>

ignore this. I accidentally flushed comments before finishing


<!-- Sent from Reviewable.io -->

2022-12-21 02:09 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 19 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2146#-:-NJmRCC_8x1avgC0pZdu:bg7igkv)* status: 24 of 25 files reviewed, 14 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`internal/keyspan/merging_iter.go` line 349 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NI3i8iY-0OXEPLQ2Man:-NJmOzUyBlrJlNmCOyuD:b-kqds3j) ([raw file](https://github.com/cockroachdb/pebble/blob/e53702b1c7dfa9125f5b42a95ba03b7e41667242/internal/keyspan/merging_iter.go#L349)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Expanded the comment to explain this more thoroughly
</blockquote></details>

Thanks. This is very clear now.
___
*[`internal/keyspan/merging_iter.go` line 422 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NJmNMFV9g5MctHIfhaN:-NJmNMFV9g5MctHIfhaO:b-hbj2ks) ([raw file](https://github.com/cockroachdb/pebble/blob/76029d54c7f124a919343829f67bd9c563224b0e/internal/keyspan/merging_iter.go#L422)):*
> ```Go
> 			}
> 		} else {
> 			// s.End > key
> ```

and s.Start < key
___
*[`internal/keyspan/merging_iter.go` line 454 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NJmNkct70V8Imen1oDS:-NJmNkct70V8Imen1oDT:b-wum92k) ([raw file](https://github.com/cockroachdb/pebble/blob/76029d54c7f124a919343829f67bd9c563224b0e/internal/keyspan/merging_iter.go#L454)):*
> ```Go
> 	//
> 	// Assume that the tightest start boundary ≤ k is the current heap root (cases
> 	// 1 & 2). After we switch to a min heap, we'll check for the third case and
> ```

"tightest start boundary ... cases 1 & 2". But case 1 includes the end boundary and case 2 is only an end boundary.  Did this mean to say "tightest boundary"?
___
*[`internal/keyspan/merging_iter.go` line 504 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NJmPRhdC4RgW2oaph5K:-NJmPRhdC4RgW2oaph5L:bsyz1wv) ([raw file](https://github.com/cockroachdb/pebble/blob/76029d54c7f124a919343829f67bd9c563224b0e/internal/keyspan/merging_iter.go#L504)):*
> ```Go
> 	// SeekLT(k) seeks to the last span with a start key less than the given
> 	// key. The merged span M that we're searching for might straddle the seek
> 	// `key`. In this case, the M.Start may be a key ≤ the seek key.
> ```

did this mean to say:
the M.End may be a key >= the seek key
___
*[`internal/keyspan/merging_iter.go` line 559 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NJmQawzAwyi64mvYF6A:-NJmQawzAwyi64mvYF6B:b-7q79jc) ([raw file](https://github.com/cockroachdb/pebble/blob/76029d54c7f124a919343829f67bd9c563224b0e/internal/keyspan/merging_iter.go#L559)):*
> ```Go
> 			// s.Start < key
> 			// We need to use this span's end bound, since that's the smallest
> 			// bound ≥ key.
> ```

smallest bound > key , I think, since this span was found by SeekGE.
___
*[`internal/keyspan/merging_iter.go` line 588 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NJmQx2c-Cd_rDxPR0Ce:-NJmQx2c-Cd_rDxPR0Cf:b-9doz3n) ([raw file](https://github.com/cockroachdb/pebble/blob/76029d54c7f124a919343829f67bd9c563224b0e/internal/keyspan/merging_iter.go#L588)):*
> ```Go
> 	// exclusive end boundary.
> 	//
> 	// Assume that the tightest end boundary ≥ k is the current heap root (cases
> ```

tightest boundary >= k


<!-- Sent from Reviewable.io -->

2023-01-06 02:43 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2146)* status: 13 of 25 files reviewed, 13 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`internal/keyspan/iter.go` line 109 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NJmI7YfCn7iYDt3qgq7:-NL3wXJI9TcykAcIgijO:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/76029d54c7f124a919343829f67bd9c563224b0e/internal/keyspan/iter.go#L109)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

f(j) = false?
</blockquote></details>

Done.
___
*[`internal/keyspan/merging_iter.go` line 422 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NJmNMFV9g5MctHIfhaN:-NL3wgtrAbmsRgkAYmmT:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/76029d54c7f124a919343829f67bd9c563224b0e/internal/keyspan/merging_iter.go#L422)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

and s.Start < key
</blockquote></details>

Done.
___
*[`internal/keyspan/merging_iter.go` line 454 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NJmNkct70V8Imen1oDS:-NL3ws-r4QqI6wF6VlCE:blxof8g) ([raw file](https://github.com/cockroachdb/pebble/blob/76029d54c7f124a919343829f67bd9c563224b0e/internal/keyspan/merging_iter.go#L454)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

"tightest start boundary ... cases 1 & 2". But case 1 includes the end boundary and case 2 is only an end boundary.  Did this mean to say "tightest boundary"?
</blockquote></details>

it meant to refer to 'start' as in the boundary we're establishing for the merged span, but I think it's confusing and reworded it to "tightest boundary".
___
*[`internal/keyspan/merging_iter.go` line 504 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NJmPRhdC4RgW2oaph5K:-NL3x9e_1xpXKE0zQS5l:baelngq) ([raw file](https://github.com/cockroachdb/pebble/blob/76029d54c7f124a919343829f67bd9c563224b0e/internal/keyspan/merging_iter.go#L504)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

did this mean to say:
the M.End may be a key >= the seek key
</blockquote></details>

thanks, Done.
___
*[`internal/keyspan/merging_iter.go` line 559 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NJmQawzAwyi64mvYF6A:-NL3xP100hAF9zIlCdJ7:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/76029d54c7f124a919343829f67bd9c563224b0e/internal/keyspan/merging_iter.go#L559)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

smallest bound > key , I think, since this span was found by SeekGE.
</blockquote></details>

Done.
___
*[`internal/keyspan/merging_iter.go` line 588 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2146#-NJmQx2c-Cd_rDxPR0Ce:-NL3xTbT6WqDNRDO7tKm:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/76029d54c7f124a919343829f67bd9c563224b0e/internal/keyspan/merging_iter.go#L588)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

tightest boundary >= k
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-10 02:37 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 12 files at r5, 5 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2146#-:-NLOXQ68D_hzbENn7fOm:bg7igkv)* status: 19 of 25 files reviewed, 13 unresolved discussions (waiting on @itsbilal and @jbowens)



<!-- Sent from Reviewable.io -->

2023-01-10 15:04 UTC, jbowens commented
TFTR!

2023-01-10 15:05 UTC, merged