merging_iter: disable prefix TrySeekUsingNext after relative seek
cockroachdb/pebble pull request #2151
Opened 2022-11-29 16:16 UTC by itsbilal

Doing a TrySeekUsingNext during a SeekPrefixGE is unsafe if the last SeekPrefixGE did a relative seek to the end of a rangedel tombstone in the merging iter as part of the process of finding a visible user key. This is because there could have been a visible key in between our seek prefix and the start of the rangedel, that was not visible to us due to a bloom filter mismatch, but will become visible on the second SeekPrefixGE.

Fixes cockroachdb/cockroach#92205.

2022-11-29 16:16 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2151)
<!-- Reviewable:end -->

2022-11-29 16:20 UTC, itsbilal commented
@jbowens @sumeerbhola just like last time, there's another possible solution here: instead of having the mergingIter remember this boolean, we could just reset `Iterator.lastPositioningOp` to `unknownLastPositionOp` if we went into the `nextUserKey` case in `findNextEntry`. From the merging iter's perspective, it's not its fault that it got Next()'d after a `SeekPrefixGE`, and it shouldn't have to remember that to undo the optimization within it. However I didn't go down that path as it would disable `trySeekUsingNext` too aggressively, such as if we have two user keys of the same prefix and the first one is deleted.

2022-11-29 16:57 UTC, itsbilal commented
Stressed the seed in #2150 before this change and it failed pretty readily. After this change it seems to pass every time. So it looks like this change would also fix #2150.

2022-11-30 21:32 UTC, sumeerbhola reviewed
Nice find!

Do you have an exact sequence of events from one of the buggy runs?
I am wary of this change -- it is getting too complicated if we are having to remember what happened last time. One possibility would be disable this `levelIter.findFileGE` optimization when doing prefix seeks.

Another possibility would be to strengthen the invariant as we did in the last bug. I think the problem is not with the successive seeks done inside `seekGE` when it finds a series of tombstones. If `seekGE` is called with a `key` that matches the prefix, I think  (we should formally prove this) the successive seeks are sound. The problem I suspect is that in the first iteration of `findNextEntry` the `item` at the top of the heap may already be past the prefix. Then we will use this `item` to drive `isNextEntryDeleted` which will call `seekGE` and do the seeks. If the first iteration of `findNextEntry` had an `item` that was the same prefix, everything would be correct until the second iteration which would exit due to the following logic if `item` was no longer a prefix, since `reseeked` is true:
```
		if m.prefix != nil && (reseeked || m.levels[item.index].isIgnorableBoundaryKey) {
			if n := m.split(item.key.UserKey); !bytes.Equal(m.prefix, item.key.UserKey[:n]) {
				return nil, base.LazyValue{}
			}
		}
```
Hmm, maybe not quite correct that it would exit in the second iteration, since we don't unconditionally set `reseeked` to true. But I suspect the solution does lie in the need to do something like the following to replace our current logic:
```
		if m.prefix != nil {
			if n := m.split(item.key.UserKey); !bytes.Equal(m.prefix, item.key.UserKey[:n]) {
				return nil, base.LazyValue{}
			}
		}
```
The question is whether this extra comparison cost is worth the `levelIter.findFileGE` optimization. It could become quite costly if we end up iterating many times.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2151#-:-NI9OxEC7PbRRY5WfZFa:b-ym7g18)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jbowens)



<!-- Sent from Reviewable.io -->

2022-12-01 16:50 UTC, itsbilal reviewed
@sumeerbhola The sequence of events is exactly the same (after eliding irrelevant details) as the test case. So yes you're right, the top element of the heap is already past the prefix by the time we go into `findNextEntry`. However it doesn't seem necessary for this bug to happen; what's more important is that the end key of the range tombstone is past the prefix, as that's what we actually re-seek on. Given that, I'm also not entirely convinced that flipping `reseeked` would help, as you point out the reseeking would have already happened in `isNextEntryDeleted` by then.

Maybe the fix is to have `isNextEntryDeleted` exhaust all levelIters below `item.index` in the case where `seekKey` is past the prefix. And we can probably do that check in just that case, and it shouldn't be too expensive if we're going to seek anyway.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2151#-:-NIDNOPq-sfuOO7OJ6ZO:b-q3nd0y)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jbowens)



<!-- Sent from Reviewable.io -->

2022-12-01 20:09 UTC, sumeerbhola requested changes
I think we need an attempt at a correctness proof. Do you want to take a stab at that?

It's interesting that you placed this logic in `isNextEntryDeleted` instead of just altering what we have in `findNextEntry`. Your choice doesn't suffer from the performance concern I had wrt doing key comparisons in the `findNextEntry` loop if that loop is continuing because the key is not visible. So that is good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2151#-:-NIEHp2L8amooc0GyOYf:b-4tjmb8)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jbowens)



<!-- Sent from Reviewable.io -->

2022-12-01 21:22 UTC, jbowens reviewed
Would it be sufficient to check if `seekKey`, the rangedel end boundary, has a different prefix. If it does, remove all levels lower than the tombstone from the heap immediately without seeking?

It seems like this would
a) remove the need for the `reseeked` bool+check in `findNextEntry` and
b) avoid the cost of reseeking which almost always lands the levelIter beyond the prefix in practice anyways, since rangedels ending within the bounds of a mvcc key should be very rare (seems only possible in Cockroach at sstable boundaries?).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2151#-:-NIEWcaXAzSFyAYHx0rh:b-94ijgp)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @itsbilal)



<!-- Sent from Reviewable.io -->

2022-12-02 19:10 UTC, itsbilal reviewed
@jbowens that's a good idea for a solution too. I've implemented that - PTAL! 

@sumeerbhola do you think we still need a correctness proof with the newest solution? I can take a stab at one, but I also find the simplicity of "just don't go past the prefix as that's what really violates the `trySeekUsingNext` invariants" convincing enough.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2151#-:-NIIr40g3B0cDI6PMYiK:bg4wo46)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @itsbilal)



<!-- Sent from Reviewable.io -->

2022-12-05 20:32 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2151)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @itsbilal)

___
*[`merging_iter.go` line 668 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2151#-NIYtVuB-RYLWZ_-6-JK:-NIYtVuCBqhHdPm2LAjU:bang2du) ([raw file](https://github.com/cockroachdb/pebble/blob/11a9dc0a929c7958b9addc8e1e1c0d1712c27705/merging_iter.go#L668)):*
> ```Go
> 				// the original prefix, we can remove all merging iter levels shadowed
> 				// by the range-del tombstone and return immediately. This is
> 				// important to make `TrySeekUsingNext` work correctly, as a reseek on
> ```

nit: ... make subsequent `TrySeekUsingNext` ...

nit: "shadowed by the range-del" introduces a new term. I would slightly prefer something more elaborate like:
... we can remove all merging iter levels below the level of the range-del tombstone and return. This is correct since those levels cannot provide a key that matches the prefix. Additionally this is necessary to make subsequent `TrySeekUsingNext` ...
___
*[`merging_iter.go` line 682 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2151#-NIYuX38EhoUu9U8S_sR:-NIYuX38EhoUu9U8S_sS:b3bw70r) ([raw file](https://github.com/cockroachdb/pebble/blob/11a9dc0a929c7958b9addc8e1e1c0d1712c27705/merging_iter.go#L682)):*
> ```Go
> 						for i := item.index; i < len(m.levels); i++ {
> 							// Remove this level from the heap.
> 							m.levels[i].iterKey = nil
> ```

This is the only code in this file that seems to do such explicit removal. This could use a code comment justifying that setting iterKey and iterValue is sufficient. Something like:
Not touching iter and rangeDelIter is correct since we want to use them for subsequent `trySeekUsingNext` optimization. And levelIterBoundaryContext is set by the levelIter, so not touching that is also correct. ...

- Do we even need to set iterKey and iterValue to nil. These are supposed to refer to the current iter position and now we are violating that invariant. Doing so is probably fine given that we will only bring this level back into the heap due to a Seek*/First/Last and that will re-initialize iterKey and iterValue. But this can also use a code comment.
- Alternatively, we could just remove these levels from the heap. It seems over-kill to reinitialize the heap given that it will do `keyspan.SeekGE` for the range del iters. Hmm, the heap element `mergingIterItem` does not know its position in the heap, so this doesn't seem viable without adding a pos field. But we can still do something lighterweight than `initMinHeap` by not seeking the range del iters.
___
*[`merging_iter.go` line 717 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2151#-NIYsDoy1Gp_w-AVsXzs:-NIYsDoy1Gp_w-AVsXzt:b5vaw) ([raw file](https://github.com/cockroachdb/pebble/blob/11a9dc0a929c7958b9addc8e1e1c0d1712c27705/merging_iter.go#L717)):*
> ```Go
> 		//    each time. Note that isNextEntryDeleted already did at least 4 key
> 		//    comparisons in order to return true, and additionally at least one
> 		//    heap comparison to step to the next entry.
> ```

is this comment stale?


<!-- Sent from Reviewable.io -->

2022-12-05 20:37 UTC, sumeerbhola commented
@itsbilal I don't think a correctness proof is needed now. I responded with some comments, but they are mostly nits.

2022-12-05 21:57 UTC, itsbilal reviewed
@sumeerbhola TFTR! I've addressed your points about the comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2151#-:-NIZHk03CBore-g4CFB2:b-ws9w6d)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`merging_iter.go` line 668 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2151#-NIYtVuB-RYLWZ_-6-JK:-NIZ8CAX24AO1IOQT2Bm:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/11a9dc0a929c7958b9addc8e1e1c0d1712c27705/merging_iter.go#L668)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: ... make subsequent `TrySeekUsingNext` ...

nit: "shadowed by the range-del" introduces a new term. I would slightly prefer something more elaborate like:
... we can remove all merging iter levels below the level of the range-del tombstone and return. This is correct since those levels cannot provide a key that matches the prefix. Additionally this is necessary to make subsequent `TrySeekUsingNext` ...
</blockquote></details>

Done.
___
*[`merging_iter.go` line 682 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2151#-NIYuX38EhoUu9U8S_sR:-NIZ8ZJc5jY9m3vH0FgV:b-y85po2) ([raw file](https://github.com/cockroachdb/pebble/blob/11a9dc0a929c7958b9addc8e1e1c0d1712c27705/merging_iter.go#L682)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is the only code in this file that seems to do such explicit removal. This could use a code comment justifying that setting iterKey and iterValue is sufficient. Something like:
Not touching iter and rangeDelIter is correct since we want to use them for subsequent `trySeekUsingNext` optimization. And levelIterBoundaryContext is set by the levelIter, so not touching that is also correct. ...

- Do we even need to set iterKey and iterValue to nil. These are supposed to refer to the current iter position and now we are violating that invariant. Doing so is probably fine given that we will only bring this level back into the heap due to a Seek*/First/Last and that will re-initialize iterKey and iterValue. But this can also use a code comment.
- Alternatively, we could just remove these levels from the heap. It seems over-kill to reinitialize the heap given that it will do `keyspan.SeekGE` for the range del iters. Hmm, the heap element `mergingIterItem` does not know its position in the heap, so this doesn't seem viable without adding a pos field. But we can still do something lighterweight than `initMinHeap` by not seeking the range del iters.
</blockquote></details>

We don't touch the other fields in `mergingIterLevel` when we `Next()` the iterator too; only `iterKey` and `iterVal`, so this should be safe enough. I've added a comment to clarify that we don't need to mutate anything else.

On removing the levels from the heap, that turned out to be more annoying than I'd have liked, unless we explicitly keep track of positions just for this one relatively-rare operation. We'd have `initMinHeap`'d anyway if we did the seekGE like we used to, and elsewhere in the iterator it looks like our canonical thing to do after a seek is to call `initMinHeap` so I'm good with a slightly more expensive rare call as long as it's conceptually simpler. I've added a TODO to track positions and to do a lighter-weight heap removal if at all possible.
___
*[`merging_iter.go` line 717 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2151#-NIYsDoy1Gp_w-AVsXzs:-NIZ9tn0Ac7NeiHrtYiW:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/11a9dc0a929c7958b9addc8e1e1c0d1712c27705/merging_iter.go#L717)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this comment stale?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-06 21:39 UTC, itsbilal commented
TFTR!

2022-12-06 21:39 UTC, merged