*: Add support for a shared FS/dir that stores some sstables
cockroachdb/pebble pull request #2231
Opened 2023-01-10 16:20 UTC by itsbilal

This change adds plumbing for marking some SSTables as "shared" that live in a separate shared FS and directory passed into Options. Files in this directory are disambiguated by a UniqueID generated at Open() time, or loaded from the Options file if one was found, as it would be possible for files from multiple Pebbles to be present in the same directory.

This change also writes SSTables below L5 to the shared FS if one is specified.

2023-01-10 16:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2231)
<!-- Reviewable:end -->

2023-01-10 19:21 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 0 of 15 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`compaction.go` line 2824 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLS1r4p3v0HpolKn6Y1:-NLS1r4qCRdRlxyE_6YV:bw70ajx) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/compaction.go#L2824)):*
> ```Go
> 				return nil, pendingOutputs, err
> 			}
> 			if err := vfs.CopyAcrossFS(fs, origPath, sharedFS, destPath); err != nil {
> ```

Would it be more efficient to write out the file directly on shared storage? Maybe leave a TODO
___
*[`compaction.go` line 3035 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLS2BTg1wHABWJ5Oxe-:-NLS2BTg1wHABWJ5Oxe0:b-92weo2) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/compaction.go#L3035)):*
> ```Go
> 
> // obsoleteFile holds information about a file that needs to be deleted soon.
> type obsoleteFile struct {
> ```

[nit] This looks like it should just contain a `fileInfo` (either as a field or embedded)
___
*[`options.go` line 634 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLS6WU33-JatxhATi6o:-NLS6WU33-JatxhATi6p:b4prfor) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/options.go#L634)):*
> ```Go
> 		// however Open() can set it to the last-set Unique ID if it finds one in
> 		// the Options file.
> 		UniqueID uint64
> ```

[nit] "unique id" sounds very generic, maybe DB ID or Store ID
___
*[`internal/manifest/version.go` line 1112 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLS4xUaBS8fzgZ7PbAS:-NLS4xUaBS8fzgZ7PbAT:bacr5oe) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/internal/manifest/version.go#L1112)):*
> ```Go
> 		for f := iter.First(); f != nil; f = iter.Next() {
> 			fileFS := fs
> 			path := base.MakeFilepath(fs, dirname, base.FileTypeTable, f.FileNum)
> ```

It feels that this logic needs to be encapsulated or we'll end up duplicating this kind of code in many places. Maybe a struct that contains `fs, sharedFs, sharedDir` and implements a function that returns the path and the fs given a`fileInfo`


<!-- Sent from Reviewable.io -->

2023-01-11 15:49 UTC, sumeerbhola requested changes
> Reviewed 7 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 7 of 15 files reviewed, 9 unresolved discussions (waiting on @itsbilal and @RaduBerinde)

___
*[`compaction.go` line 2815 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWV8BH7Li6mFDfDFOB:-NLWV8BH7Li6mFDfDFOC:b-w1xi8w) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/compaction.go#L2815)):*
> ```Go
> 		//
> 		// TODO(bilal): Move this outputLevel >= 5 logic for determining whether
> 		// a file should become shared to elsewhere when it's more complex.
> ```

Should this be hidden in the `sharedFS` implementation?
To tolerate transient unavailability of the shared storage it would absorb all writes locally and when the file was closed would copy it over. And if the copy did not succeed it would keep track in local persistent storage of what pending copies need to be done.
What I am suggesting may not be the right abstraction, but I do think we need to decompose the sub-systems in a way that we can manage complexity. We do a decomposition like this for the `encryptedFS`, which has its own "manifest".
___
*[`options.go` line 626 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWNppN-R7lj6EKKd1v:-NLWNppN-R7lj6EKKd1w:blr10lc) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/options.go#L626)):*
> ```Go
> 		// not fully owned by this Pebble instance, necessitating more coordination
> 		// for deletes. It is also expected to have slower read/write performance
> 		// than FS.
> ```

How about being a bit more explicit in this comment about what it means to "not fully own". Something like:
SharedFS is for writing files that can later be read by others that are given the name of the file. There is a single writer for a file. Only sstables should be put in SharedFS.

The "necessitating more coordination" part is not clear. From the perspective of this interface, which is for use by Pebble, could we hide the coordination part behind an `ImportFile(filename string)` method in a `SharedFS` interface that extends `vfs.FS`? So the contract would be that to share a file, the sender (original writer, or someone who has imported) would send over the filename and wait for the receiver to tell the sender that it has called `ImportFile`. Once that has happened the sender can safely delete the file since the receiver has taken a reference. We of course will need an out-of-band mechanism to do cleanup when a store that has imported (or wrote originally) permanently disappears, but that cleanup mechanism would be a component of the implementation and not part of this interface. 
___
*[`options.go` line 630 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWP49L1DYn6ENdf50v:-NLWP49L1DYn6ENdf50w:b9k2d5c) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/options.go#L630)):*
> ```Go
> 
> 		// UniqueID is a unique ID that's generated for new Pebble instances and
> 		// serialized into the Options file. Used to disambiguate this instance's
> ```

the files *written* by this instance, yes?
___
*[`table_cache.go` line 274 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWUQhrA2Q1UAurQrtz:-NLWUQhrA2Q1UAurQru-:bwxsevm) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/table_cache.go#L274)):*
> ```Go
> type tableCacheKey struct {
> 	cacheID uint64
> 	fileNum FileNum
> ```

Doesn't this need to change since `fileNum` is no longer sufficient as the key?
And for the block cache too?
___
*[`internal/manifest/version.go` line 1112 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLS4xUaBS8fzgZ7PbAS:-NLWRlaWBkljvk53EqzD:b32v57) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/internal/manifest/version.go#L1112)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It feels that this logic needs to be encapsulated or we'll end up duplicating this kind of code in many places. Maybe a struct that contains `fs, sharedFs, sharedDir` and implements a function that returns the path and the fs given a`fileInfo`
</blockquote></details>

+1
___
*[`internal/manifest/version_edit.go` line 308 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWRyDK38ERZNc4IQ0r:-NLWRyDK38ERZNc4IQ0s:b-lg64oy) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/internal/manifest/version_edit.go#L308)):*
> ```Go
> 						}
> 						onSharedFS = (field[0] == 1)
> 						uniqueID, err = d.readUvarint()
> ```

is it fair to say that the sstable identifier is now (fileNum: uint64, onSharedFS: bool, creatorUniqueID: uint64)?
If yes, would be worth highlighting with a code comment in the `FileMetadata` declaration.


<!-- Sent from Reviewable.io -->

2023-01-11 16:06 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 7 of 15 files reviewed, 9 unresolved discussions (waiting on @itsbilal and @RaduBerinde)

___
*[`internal/manifest/version_edit.go` line 308 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWRyDK38ERZNc4IQ0r:-NLW_6G08Fhzb6QAQSlp:b9ox23g) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/internal/manifest/version_edit.go#L308)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is it fair to say that the sstable identifier is now (fileNum: uint64, onSharedFS: bool, creatorUniqueID: uint64)?
If yes, would be worth highlighting with a code comment in the `FileMetadata` declaration.
</blockquote></details>

Another option (in the same vein of more abstraction boundaries).

SharedFS does a mapping from local filenum to shared filename:
- Is configured with which levels to share, or other more complicated policies
- Writer client tell sharedFS when opening a sstable for writing which level it corresponds to and a lower bound on the first key in the sstable. Latter can be used to exclude CockroachDB's local key space from sharing (in the future).
  - SharedFS manages all the staging first to local filesystem and then to shared storage.
- Reader client (for sharing with other nodes) is aware of policies in SharedFS since it needs to know that for certain parts of the keyspace it should only read up to L4.
  - Asks SharedFS for the (local filenum, shared filename) pairs for L5 and L6 in the relevant keyspace. If some of these files have not yet been written to shared storage (because of an outage), the SharedFS will block. 
  - Places a "hold" on deletion of these local filenums
  - sends over the shared filenames
- Receiver client gives the shared filename to its local SharedFS which generates a local filenum (in a manner consistent with the filenum generation Pebble currently does, so as to not have collisions)


<!-- Sent from Reviewable.io -->

2023-01-11 23:45 UTC, itsbilal reviewed
TFTRs! Addressed some of the comments, added to the discussions in others

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231#-:-NLYDIevB7eVpWO6v5g_:b-njjqyx)* status: 0 of 15 files reviewed, 7 unresolved discussions (waiting on @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`compaction.go` line 2815 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWV8BH7Li6mFDfDFOB:-NLY9Obu9TUpk5tiYQli:b-5frscu) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/compaction.go#L2815)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Should this be hidden in the `sharedFS` implementation?
To tolerate transient unavailability of the shared storage it would absorb all writes locally and when the file was closed would copy it over. And if the copy did not succeed it would keep track in local persistent storage of what pending copies need to be done.
What I am suggesting may not be the right abstraction, but I do think we need to decompose the sub-systems in a way that we can manage complexity. We do a decomposition like this for the `encryptedFS`, which has its own "manifest".
</blockquote></details>

I like this idea, where `sharedFS` could take care of falling back to local FS if shared FS is unavailable. There could be a "ReadyForShare()" method that confirms a file is in blob storage. I'll update the TODO for this.
___
*[`compaction.go` line 2824 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLS1r4p3v0HpolKn6Y1:-NLXp4rzDIkAGeEI2SdK:bn1fc3s) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/compaction.go#L2824)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Would it be more efficient to write out the file directly on shared storage? Maybe leave a TODO
</blockquote></details>

Yeah, it probably would be - especially behind a `bufio.Writer`. Added a todo.
___
*[`compaction.go` line 3035 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLS2BTg1wHABWJ5Oxe-:-NLXp8x3C1-ETHZbcM85:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/compaction.go#L3035)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This looks like it should just contain a `fileInfo` (either as a field or embedded)
</blockquote></details>

Done.
___
*[`options.go` line 626 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWNppN-R7lj6EKKd1v:-NLYCDHg98seX28xKXwU:b-hzowzf) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/options.go#L626)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How about being a bit more explicit in this comment about what it means to "not fully own". Something like:
SharedFS is for writing files that can later be read by others that are given the name of the file. There is a single writer for a file. Only sstables should be put in SharedFS.

The "necessitating more coordination" part is not clear. From the perspective of this interface, which is for use by Pebble, could we hide the coordination part behind an `ImportFile(filename string)` method in a `SharedFS` interface that extends `vfs.FS`? So the contract would be that to share a file, the sender (original writer, or someone who has imported) would send over the filename and wait for the receiver to tell the sender that it has called `ImportFile`. Once that has happened the sender can safely delete the file since the receiver has taken a reference. We of course will need an out-of-band mechanism to do cleanup when a store that has imported (or wrote originally) permanently disappears, but that cleanup mechanism would be a component of the implementation and not part of this interface. 
</blockquote></details>

the sender would send over the s/filename/`SharedSSTMeta`/ or some other struct that contains all the fields to resolve a path (and additional fields for bounds), but otherwise I agree. The cleanup mechanism is something @RaduBerinde is putting more thought into. I'm happy to add an `ImportFile(filename string)` to an interface extending `vfs.FS` if he's good with the idea of keeping this coordination in the `sharedFS`. The other way would be to implement it in some other coordinator struct in Pebble that operates *on* a `sharedFS` and just uses plain file handles to put down (and scan) markers.

I've made the comment change otherwise.
___
*[`options.go` line 630 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWP49L1DYn6ENdf50v:-NLY0_8t022W6KOxG8Pk:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/options.go#L630)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the files *written* by this instance, yes?
</blockquote></details>

Done.
___
*[`options.go` line 634 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLS6WU33-JatxhATi6o:-NLXpIOT7TZhfDrcMbWQ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/options.go#L634)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] "unique id" sounds very generic, maybe DB ID or Store ID
</blockquote></details>

Done.
___
*[`table_cache.go` line 274 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWUQhrA2Q1UAurQrtz:-NLY0bWz-uo197DplCTZ:b-ppu3yf) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/table_cache.go#L274)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Doesn't this need to change since `fileNum` is no longer sufficient as the key?
And for the block cache too?
</blockquote></details>

I'm going to let the virtual sstable changes handle any cache changes as it's going to be more relevant there, but this still works because each `shared` sstable still gets a unique `fileNum` for its own instance.

It'll probably be a good idea to have the `fileNum`s here map to physical files if we have a locally-owned physical sstable backing the current virtual sstable, that way we can use the same `Reader` for both the pre-excised and post-excised sstable. But that can come later.
___
*[`internal/manifest/version.go` line 1112 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLS4xUaBS8fzgZ7PbAS:-NLY4NAW4zlDRmFkdaeG:b-nbeud9) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/internal/manifest/version.go#L1112)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

+1
</blockquote></details>

Elsewhere in the code it's a little more common to pass around iterators or `fileMetadata` instead of file path parameters? I'll also be introducing a `SharedSSTMeta` or `SharedTableMeta` which implements many of these fields and will be exported by iterators. Does that ease your concern or should I do one just for the few path variables?
___
*[`internal/manifest/version_edit.go` line 308 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWRyDK38ERZNc4IQ0r:-NLY8ScV68YjeeTgaFZx:b-tzqcfd) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/internal/manifest/version_edit.go#L308)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Another option (in the same vein of more abstraction boundaries).

SharedFS does a mapping from local filenum to shared filename:
- Is configured with which levels to share, or other more complicated policies
- Writer client tell sharedFS when opening a sstable for writing which level it corresponds to and a lower bound on the first key in the sstable. Latter can be used to exclude CockroachDB's local key space from sharing (in the future).
  - SharedFS manages all the staging first to local filesystem and then to [...]

2023-01-12 02:39 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 0 of 15 files reviewed, 7 unresolved discussions (waiting on @bananabrick, @itsbilal, and @RaduBerinde)

___
*[`internal/manifest/version_edit.go` line 308 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWRyDK38ERZNc4IQ0r:-NLYpS5g66zTOaK5eX22:b-qlftl3) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/internal/manifest/version_edit.go#L308)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I think `fileNum` is still a unique identifier for an SST for each pebble and that's unlikely to change. I don't want to over-legislate much here yet because Arjun is going to make many similar `FileMetadata` changes when he lands virtual SSTs imminently so I'd rather build off of whatever comes in that PR. It's why I kept the pieces here to be the bare minimum necessary for having a sharedFS.

We will also inevitably have bounds logic tied to non-shared files (eg. an L0 file that gets excised away), and we'll need it for the ingestion case with virtual SSTs too that doesn't concern disaggregated storage at all, and where `sharedFS` is nil.

I do like the idea of pushing down the level to the sharedFS, and that way the seqnum substitution could happen in an sst iterator that is created by sharedFS instead of one that's created by the table cache. 
</blockquote></details>

I think we can decouple the virtual sstable logic that will come from @bananabrick 's PR, from the filename mapping.

Pebble needs to know the virtual keyspans and also needs to know if the sstable is foreign (for the key seqnum stuff). The virtual sstable change will give us the former (which will map a virtual sst filenum to the base filenum), and we will need the add the latter.

But Pebble doesn't need to know how a locally assigned filenum that it has picked to be unique, either when creating a new file for writing or when calling import, maps to some actual blobname in S3 etc. It would be nice to define an interface for this `SharedFS` in this PR.


<!-- Sent from Reviewable.io -->

2023-01-12 21:18 UTC, jbowens reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 0 of 15 files reviewed, 7 unresolved discussions (waiting on @bananabrick, @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`internal/manifest/version_edit.go` line 308 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWRyDK38ERZNc4IQ0r:-NLbh5tS9oND7uSWamZd:b8kihez) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/internal/manifest/version_edit.go#L308)):*
> Writer client tell sharedFS when opening a sstable for writing which level it corresponds to and a lower bound on the first key in the sstable. Latter can be used to exclude CockroachDB's local key space from sharing (in the future).

This seems a little tricky, given sstables can be moved across levels. I'm a little wary of sharedFS directly understanding levels, because it muddles the VFS abstraction. LSM versioning means that a file doesn't have one level.

I +1 the notion of a thicker SharedFS which handles the mapping from local filenum to shared filename. Thinking through more abstraction boundaries, another option is accepting an `Options.SecondaryStorage` option but keeping a single `vfs.FS` field:

```
type SecondaryStorage interface {
    // Offload records that the named file should be moved to secondary storage.
    Offload(path string)
    // Sync ensures that record of all previous calls to `Offload` are persisted. After
    // Sync, a process restart must not forget to offload any files that were previously
    // marked for offloading. Sync does NOT guarantee that the files themselves have
    // have already been offloaded to secondary storage.
    Sync() error
    // IsOffloaded returns true if the named file is persisted on secondary storage. If
    // true, the named file may also be available locally. If false, the named file MUST
    // be available locally.
    IsOffloaded(path string) bool
}
```

All file manipulation continues to go through `Options.FS`. If `SecondaryStorage` is provided, then `Options.FS` must hold a shared FS (maybe implemented by the same type as the one implementing `SecondaryStorage`). When `Open`-ing a file, the sharedFS uses a local file handle if available or a blob-storage one if not. I don't think we're losing anything by forcing file creations to go to the local filesystem first, but curious your thoughts.


<!-- Sent from Reviewable.io -->

2023-01-12 22:30 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 0 of 15 files reviewed, 7 unresolved discussions (waiting on @bananabrick, @itsbilal, and @RaduBerinde)

___
*[`internal/manifest/version_edit.go` line 308 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWRyDK38ERZNc4IQ0r:-NLc5GbG6DjAWnGE3M2H:b-pl5dzw) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/internal/manifest/version_edit.go#L308)):*
> I don't think we're losing anything by forcing file creations to go to the local filesystem first, but curious your thoughts.

I don't think we want to impose that. I am keen to get rid of disk write bandwidth as a resource bottleneck when running with a "good" sharedFS implementation -- bandwidth provisioning is a major headache for our customers.


<!-- Sent from Reviewable.io -->

2023-01-13 15:51 UTC, itsbilal reviewed
Thanks for the reviews! Added a `SharedFileHandle` and a beefier `SharedFS` interface. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231#-:-NLforur3hrONiv3leTu:bvdvqvc)* status: 0 of 16 files reviewed, 7 unresolved discussions (waiting on @bananabrick, @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`internal/manifest/version_edit.go` line 308 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWRyDK38ERZNc4IQ0r:-NLfUSHt4Y0E_EXQ1HtN:bwvuu3i) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/internal/manifest/version_edit.go#L308)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> I don't think we're losing anything by forcing file creations to go to the local filesystem first, but curious your thoughts.

I don't think we want to impose that. I am keen to get rid of disk write bandwidth as a resource bottleneck when running with a "good" sharedFS implementation -- bandwidth provisioning is a major headache for our customers.
</blockquote></details>

I've added a `SharedFileHandle` struct that `SharedFS` uses to construct shared file paths, and that contains the two fields Pebble needs to be aware of (instance ID and file num). I didn't want to legislate a shared FS manifest right now because it sounds unnecessary to me when we really only need to hold two additional fields on top of what we already store in FileMetadata. If a shared FS manifest ends up being necessary, we can do that on our own behind the interface (and we might need to if we want to write-through to sharedFS while having a fallback to localFS within `sharedFS`), but with the way the interface is right now, a stateless `sharedFS` would also be an acceptable implementation.

The good thing is `MakeSharedSSTFilePath` is gone now.


<!-- Sent from Reviewable.io -->

2023-01-13 16:01 UTC, itsbilal commented
Ah, looks like #2186 + this change may have introduced a circular dependency in the changes to `Open()` here. Let me take a look.

2023-01-14 06:05 UTC, RaduBerinde commented
> What I am suggesting may not be the right abstraction, but I do think we need to decompose the sub-systems in a way that we can manage complexity.

We need to pull back for a bit and think carefully about the entire abstraction. I don't think a filesystem-style interface is the right thing here. We should come up with a new "object storage" interface that contains the high level operations that we need (many of the FS-type operations aren't necessary). The implementation should be able to use cloud storage, or some future distributed storage/caching layer, without any changes in Pebble. As an example, the logic for the naming of shared files should live *inside* the implementation of that interface, not in Pebble. Likewise, if we want to use local FS to "buffer" data around cloud storage unavailability, all that should also be inside this implementation and not in Pebble.

2023-01-17 17:02 UTC, sumeerbhola requested changes
> We need to pull back for a bit and think carefully about the entire abstraction. I don't think a filesystem-style interface is the right thing here. We should come up with a new "object storage" interface that contains the high level operations that we need (many of the FS-type operations aren't necessary).

My interpretation of this is that `SharedFS` should not extend `FS`. We should include only the methods we need for sstable reading/writing, since those are the only things that live on the `SharedFS`. In that sense I completely agree.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231#-:-NM-XT3p7KMp3TFBv2FF:b-91m66b)* status: 0 of 16 files reviewed, 11 unresolved discussions (waiting on @bananabrick, @itsbilal, and @RaduBerinde)

___
*[`options.go` line 634 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NM-Z1VA2NA1CkDXf6GN:-NM-Z1VBBZSzow91vYH4:bx3ladk) ([raw file](https://github.com/cockroachdb/pebble/blob/a41d98cff8491c2f00293056a47ba74ca3291748/options.go#L634)):*
> ```Go
> 		// uint64, however Open() can set it to the last-set Instance ID if it finds
> 		// one in the Options file.
> 		InstanceID uint64
> ```

CockroachDB's `StoreID` type is an int32. Using a uint64 here seems fine, but I am curious if you think there are any performance implications of the choice being made here.
___
*[`internal/manifest/version_edit.go` line 308 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NLWRyDK38ERZNc4IQ0r:-NM-dwA53s0xADxiNVtE:b-skynj7) ([raw file](https://github.com/cockroachdb/pebble/blob/9f9cefbb217510e792f0ddf6e8edebf9b757033e/internal/manifest/version_edit.go#L308)):*
> I didn't want to legislate a shared FS manifest right now because it sounds unnecessary to me when we really only need to hold two additional fields on top of what we already store in FileMetadata. ... but with the way the interface is right now, a stateless sharedFS would also be an acceptable implementation.

I can appreciate that viewpoint, but I'd prefer to get the interfaces to be what we expect them to be in the future. Storing the mapping is a quick implementation.
___
*[`vfs/vfs.go` line 150 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NM-ZvT2Cg3UgxEyCRQm:-NM-ZvT2Cg3UgxEyCRQn:b-srch4o) ([raw file](https://github.com/cockroachdb/pebble/blob/a41d98cff8491c2f00293056a47ba74ca3291748/vfs/vfs.go#L150)):*
> ```Go
> 
> 	// SetInstanceID sets the instance ID of the current Pebble instance. Called
> 	// during Open(). Can be stored and/or used by the implementation to
> ```

Does this need to be called during `Open`, or just before any other operations on the `SharedFS`?
If it needs to be `Open`, then I suppose we can't use the `CockroachDB` storeId when this Pebble instance is embedded in CockroachDB. If it is a different ID, we will need to store the mapping somewhere. Any thoughts on these details?
___
*[`vfs/vfs.go` line 155 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NM-a7lC5sXPpTZo9DBc:-NM-a7lC5sXPpTZo9DBd:b-jwzzm4) ([raw file](https://github.com/cockroachdb/pebble/blob/a41d98cff8491c2f00293056a47ba74ca3291748/vfs/vfs.go#L155)):*
> ```Go
> 
> 	// ResolvePath converts a SharedFileHandle to a file path that can
> 	// be used by FS methods for file manipulation/reading (eg. Create(), Open()).
> ```

There are 2 cases here:
- Creating a new file: We want to provide a local `FileNum` in the parameter, so that the `SharedFS` can remember the mapping.  The `CreatorInstanceID` is the one we have already set via `SetInstanceID`.
- Opening an existing file: This could be a file created by this instance or by another instance. In either case, we have assigned it a local `FileNum` (for the latter case, that local FileNum assignment should happen in `Reference`). Again only the local `FileNum` should be needed as a parameter.

But I think we should separate these two cases into different methods, such as
```
ResolveNewPath(fileNum uint64) string
ResolveExistingPath(fileNum uint64) string
```
so that the implementation can do proper error checking, and since only the former involves a write and fsync (to record the mapping).
___
*[`vfs/vfs.go` line 164 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NM-bUbw3KF5n6w557VM:-NM-bUbw3KF5n6w557VN:b2l4khn) ([raw file](https://github.com/cockroachdb/pebble/blob/a41d98cff8491c2f00293056a47ba74ca3291748/vfs/vfs.go#L164)):*
> ```Go
> 	// instance can call ResolvePath() and then Create() directly without
> 	// calling this method.
> 	Reference(fileHandle SharedFileHandle) error
> ```

I was expecting something like `ReferenceForeign(resolvedPath string, localFileNum uint64) error`, where we are telling the `SharedFS` to create a mapping from `localFileNum` to `resolvedPath`. The invariant is that the mapping cannot be changed, and asking to create the same mapping multiple times will succeed but there is still only 1 reference.

Then `MarkObsolete` would become `Dereference(fileNum uint64)`.

I think with these changes, Pebble only needs to remember (a) the local `fileNum`, (b) whether a sstable is in the `SharedFS` or a regular `FS` (because in the future not all L5 and L6 files will be in the sharedFS, and even L0-L4 are likely to be in the sharedFS), (c) if in the `SharedFS`, whether it is a foreign sst (for the seqnum remapping).

One question is whether even (b) should be something that Pebble should not bother remembering. It will remove demux code from Pebble which is better. In this world we would just have a new narrower `FS` interface for ssts, which could be either all local, or mix of local and shared. The local impl would not support the `ReferenceForeign`, and `Dereference` would be deletion.


<!-- Sent from Reviewable.io -->

2023-01-17 18:14 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 0 of 16 files reviewed, 11 unresolved discussions (waiting on @bananabrick, @itsbilal, and @RaduBerinde)

___
*[`vfs/vfs.go` line 164 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NM-bUbw3KF5n6w557VM:-NM-tt5RCC988mbDzFUn:b-2sh8jq) ([raw file](https://github.com/cockroachdb/pebble/blob/a41d98cff8491c2f00293056a47ba74ca3291748/vfs/vfs.go#L164)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I was expecting something like `ReferenceForeign(resolvedPath string, localFileNum uint64) error`, where we are telling the `SharedFS` to create a mapping from `localFileNum` to `resolvedPath`. The invariant is that the mapping cannot be changed, and asking to create the same mapping multiple times will succeed but there is still only 1 reference.

Then `MarkObsolete` would become `Dereference(fileNum uint64)`.

I think with these changes, Pebble only needs to remember (a) the local `fileNum`, (b) whether a sstable is in the `SharedFS` or a regular `FS` (because in the future not all L5 and L6 files will be in the sharedFS, and even L0-L4 are likely to be in the sharedFS), (c) if in the `SharedFS`, whether it is a foreign sst (for the seqnum remapping).

One question is whether even (b) should be something that Pebble should not bother remembering. It will remove demux code from Pebble which is better. In this world we would just have a new narrower `FS` interface for ssts, which could be either all local, or mix of local and shared. The local impl would not support the `ReferenceForeign`, and `Dereference` would be deletion.
</blockquote></details>

I am becoming more keen on having an `sstFS` which includes APIs that are needed when backed by a shared FS implementation, and not having two `FS`s for dealing with ssts.

What I am missing is a very clear understanding of the APIs needed for "data export", which will be used for sending range snapshots. It is relatively easy to add a `supportsExportViaSharedFile() bool` method to this `sstFS`, which the non-shared implementation will return false. But when it returns true, we need to do something to get the L5 and L6 ssts that we are sending over. Pebble already knows the filenums corresponding to those L5 and L6 ssts and it can manage their lifecycle by ensuring that `Dereference` is not called. I suppose all that is needed is a `ResolvePathShared(fileNum uint64) (string, error)` that will return an error if it cannot return a string name that can be sent to a remote node (say because the file is local).


<!-- Sent from Reviewable.io -->

2023-01-17 18:17 UTC, RaduBerinde reviewed
> My interpretation of this is that SharedFS should not extend FS. We should include only the methods we need for sstable reading/writing, since those are the only things that live on the SharedFS. In that sense I completely agree.

Yes. I've been looking through the code and it looks like extracting a more narrow interface just for SST storage would help even with just the current functionality - there is a lot of complication in the sstable code around write buffering, read-ahead, etc and these could all live behind the interface (inside the implementation). I will continue to work on that and hopefully have something out within a few days.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231#-:-NM-wMSZ9CXgVR1AqQFp:b-je709v)* status: 0 of 16 files reviewed, 11 unresolved discussions (waiting on @bananabrick, @itsbilal, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-02-01 04:37 UTC, itsbilal commented
This is ready for another look. I've distilled a lot of the comments above and simplified the `SharedStorage` interface into one that's just FS-like and is only responsible for interacting directly with blob storage and handling obsoletion of files (open to thoughts on pulling that out of the interface and letting objstorage.Provider do it). With #2267 implementing a better middleware for handling state on where each file lives, I can see `SharedFilePath` being something that the objstorage.Provider can store in its manifest / generate itself.

I've kept the instanceID but made it a `uint32` for performance / size reasons. I think it's still a good idea to have it at this level and it seems to be in line with Radu's RFC.

2023-02-01 17:33 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 0 of 16 files reviewed, 12 unresolved discussions (waiting on @bananabrick, @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`options.go` line 630 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NND-D9G5m6_1EDXaG1y:-NND-D9G5m6_1EDXaG1z:b-n49i8d) ([raw file](https://github.com/cockroachdb/pebble/blob/77de12648ccf474081040c66a3a29753d2f63524/options.go#L630)):*
> ```Go
> 		SharedStorage vfs.SharedStorage
> 
> 		// InstanceID is a unique ID that's generated for each Pebble instance and
> ```

In the demo, this was a random a 32-bit integer, which I think isn't enough randomness to prevent collisions. Eg, with  ~3,000 nodes the odds of a collision is 1:1000. I think we'll want to ensure we have uniqueness confirmed by consensus. Can we lazily initialize the instance ID once we have the store ID available?


<!-- Sent from Reviewable.io -->

2023-02-01 20:54 UTC, itsbilal reviewed
Made the change, this PR is now _just_ the blob storage driver interface. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231#-:-NNDkSVs6y0mM_OSU16K:b8c0v9w)* status: 0 of 16 files reviewed, 12 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`options.go` line 634 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NM-Z1VA2NA1CkDXf6GN:-NM5H5DV3N9AReZrdqts:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a41d98cff8491c2f00293056a47ba74ca3291748/options.go#L634)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

CockroachDB's `StoreID` type is an int32. Using a uint64 here seems fine, but I am curious if you think there are any performance implications of the choice being made here.
</blockquote></details>

Done.
___
*[`options.go` line 630 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NND-D9G5m6_1EDXaG1y:-NNDix-LADwBN9sOLety:b-sbrwtc) ([raw file](https://github.com/cockroachdb/pebble/blob/77de12648ccf474081040c66a3a29753d2f63524/options.go#L630)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

In the demo, this was a random a 32-bit integer, which I think isn't enough randomness to prevent collisions. Eg, with  ~3,000 nodes the odds of a collision is 1:1000. I think we'll want to ensure we have uniqueness confirmed by consensus. Can we lazily initialize the instance ID once we have the store ID available?
</blockquote></details>

We probably could, but we'd have to go back and rename a bunch of files or so, and that seems like a lot of logistical work. I was hoping we could just lay down a marker for a shared ID, and as part of `SetInstanceID` we could check if there's a marker in the shared storage for that ID and if there is one, we regenerate it. That should help a ton while still conserving some bits.

Either way, this is out of this PR as the sharedstorage interface is now just a blob storage driver.
___
*[`vfs/vfs.go` line 150 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NM-ZvT2Cg3UgxEyCRQm:-NM5HRxx1OcFcWWBhHDs:b-txh1ht) ([raw file](https://github.com/cockroachdb/pebble/blob/a41d98cff8491c2f00293056a47ba74ca3291748/vfs/vfs.go#L150)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Does this need to be called during `Open`, or just before any other operations on the `SharedFS`?
If it needs to be `Open`, then I suppose we can't use the `CockroachDB` storeId when this Pebble instance is embedded in CockroachDB. If it is a different ID, we will need to store the mapping somewhere. Any thoughts on these details?
</blockquote></details>

Maybe the comment isn't clear, but this is `Options.Experimental.InstanceID`. It won't be called by Cockroach into Pebble, rather it'll be called by Pebble itself during Open into this method.

The way the instance ID determination is written right now, Pebble can decide on it before Cockroach has arrived at a store ID in the first place. That's a critically important detail as sharedFS might need this ID before it can write any files itself.
___
*[`vfs/vfs.go` line 155 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NM-a7lC5sXPpTZo9DBc:-NNCOCAd4H3TTvQJ9LFy:bylvc5y) ([raw file](https://github.com/cockroachdb/pebble/blob/a41d98cff8491c2f00293056a47ba74ca3291748/vfs/vfs.go#L155)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

There are 2 cases here:
- Creating a new file: We want to provide a local `FileNum` in the parameter, so that the `SharedFS` can remember the mapping.  The `CreatorInstanceID` is the one we have already set via `SetInstanceID`.
- Opening an existing file: This could be a file created by this instance or by another instance. In either case, we have assigned it a local `FileNum` (for the latter case, that local FileNum assignment should happen in `Reference`). Again only the local `FileNum` should be needed as a parameter.

But I think we should separate these two cases into different methods, such as
```
ResolveNewPath(fileNum uint64) string
ResolveExistingPath(fileNum uint64) string
```
so that the implementation can do proper error checking, and since only the former involves a write and fsync (to record the mapping).
</blockquote></details>

Path resolution is now buried inside the SharedStorage.
___
*[`vfs/vfs.go` line 164 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NM-bUbw3KF5n6w557VM:-NM4buvN2S7_So8HOTy_:b-bhg1jt) ([raw file](https://github.com/cockroachdb/pebble/blob/a41d98cff8491c2f00293056a47ba74ca3291748/vfs/vfs.go#L164)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am becoming more keen on having an `sstFS` which includes APIs that are needed when backed by a shared FS implementation, and not having two `FS`s for dealing with ssts.

What I am missing is a very clear understanding of the APIs needed for "data export", which will be used for sending range snapshots. It is relatively easy to add a `supportsExportViaSharedFile() bool` method to this `sstFS`, which the non-shared implementation will return false. But when it returns true, we need to do something to get the L5 and L6 ssts that we are sending over. Pebble already knows the filenums corresponding to those L5 and L6 ssts and it can manage their lifecycle by ensuring that `Dereference` is not called. I suppose all that is needed is a `ResolvePathShared(fileNum uint64) (string, error)` that will return an error if it cannot return a string name that can be sent to a remote node (say because the file is local).
</blockquote></details>

Done (unnecessary as Provider will handle this).


<!-- Sent from Reviewable.io -->

2023-02-01 23:20 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 0 of 16 files reviewed, 12 unresolved discussions (waiting on @bananabrick, @jbowens, and @sumeerbhola)

___
*[`options.go` line 630 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NND-D9G5m6_1EDXaG1y:-NNEFt9c4pPJHdOOQOjp:b-7ylmk8) ([raw file](https://github.com/cockroachdb/pebble/blob/77de12648ccf474081040c66a3a29753d2f63524/options.go#L630)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We probably could, but we'd have to go back and rename a bunch of files or so, and that seems like a lot of logistical work. I was hoping we could just lay down a marker for a shared ID, and as part of `SetInstanceID` we could check if there's a marker in the shared storage for that ID and if there is one, we regenerate it. That should help a ton while still conserving some bits.

Either way, this is out of this PR as the sharedstorage interface is now just a blob storage driver.
</blockquote></details>

If we just want to generate this as a random 64-bit integer, it would be easy enough to do as part of the shared object manifest (aka catalog). But it would be nice if it matched the store ID so there isn't another inscrutable ID that we'd need to map when debugging things. Realistically we'd need to delay creation of any L5/L6 object until the store ID is set (which I'm not sure is feasible)


<!-- Sent from Reviewable.io -->

2023-02-02 21:02 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231#-:-NNIw04t3EJr2dvu2Y2u:bg7igkv)* status: 1 of 16 files reviewed, 15 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @RaduBerinde)

___
*[`vfs/vfs.go` line 184 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNIuSWvArzREng4H2YD:-NNIuSWvArzREng4H2YE:bpauo28) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L184)):*
> ```Go
> 	io.Closer
> 
> 	// ReadFile is shorthand for ReadFileAt with offset 0.
> ```

How about removing this shorthand. There is no special case of reading the start of a sstable.
___
*[`vfs/vfs.go` line 200 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNIuqDr5_ptGYKzeDuh:-NNIuqDr5_ptGYKzeDui:b-xt6lof) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L200)):*
> ```Go
> 
> 	// List enumerates files within the supplied prefix, returning a list of
> 	// objects within that prefix. If delimiter is non-empty names which have the
> ```

nit: ... non-empty, names ...
___
*[`vfs/vfs.go` line 202 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNIvf3U-xzM0hKUHaAu:-NNIvf3VDedJ6N2ryU_p:bgj1fjo) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L202)):*
> ```Go
> 	// objects within that prefix. If delimiter is non-empty names which have the
> 	// same prefix, prior to the delimiter, are grouped into a single result which
> 	// is that prefix. The order that results are returned is undefined.
> ```

So the prefix is used for filtering regardless of delimiter, but the delimiter is for grouping but not ordering? I am a bit confused. Can you give an example?


<!-- Sent from Reviewable.io -->

2023-02-02 21:10 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 1 of 16 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @sumeerbhola)

___
*[`vfs/vfs.go` line 178 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNHpw4NAOHnwV9N-dC3:-NNHpw4NAOHnwV9N-dC4:b-vqp4bj) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L178)):*
> ```Go
> // top of these methods.
> //
> // TODO(bilal): Consider reworking this interface to return File-like objects,
> ```

I would move this to `objstorage` (maybe in its own subpackage, e.g. `objstorage/sharedobj`) and rename `File` to `Object` in the methods.

I'd also remove this TODO - if we move the middleware behind an interface, it would be a new higher-level interface (fairly similar to the current `Provider` public "interface"), and we would still use this interface inside that implementation.
___
*[`vfs/vfs.go` line 190 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNHqJEo24_OhZ3fnnih:-NNHqJEo24_OhZ3fnnii:bnwbjx5) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L190)):*
> ```Go
> 	ReadFileAt(basename string, offset int64) (io.ReadCloser, int64, error)
> 
> 	// Writer returns a writer for the requested name.
> ```

This should explain the semantics when the object exists (I believe it will be overwritten?). Maybe `CreateObject` is a better name than `Writer`.

Also, I believe this is an all-or-nothing operation (at least on S3 - either there is a single `PutObject` request, or a multi-part upload which only becomes effective with `CompleteMultiPartUpload`). Is this something that would be useful to promise here? I don't think we care about that for SSTs, maybe we would for the blob feature @sumeerbhola is working on?
___
*[`vfs/vfs.go` line 201 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNHtS-A1TozNjlr2gc8:-NNHtS-A1TozNjlr2gc9:byuugzu) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L201)):*
> ```Go
> 	// List enumerates files within the supplied prefix, returning a list of
> 	// objects within that prefix. If delimiter is non-empty names which have the
> 	// same prefix, prior to the delimiter, are grouped into a single result which
> ```

Prior to the delimiter but after the given `prefix`. Maybe a short example would help.
___
*[`vfs/vfs.go` line 202 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNHtIatCmZZ0qqmiyXF:-NNHtIatCmZZ0qqmiyXG:bfs1h46) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L202)):*
> ```Go
> 	// objects within that prefix. If delimiter is non-empty names which have the
> 	// same prefix, prior to the delimiter, are grouped into a single result which
> 	// is that prefix. The order that results are returned is undefined.
> ```

How can the caller differentiate between an object or a group ("subdirectory")
___
*[`vfs/vfs.go` line 202 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNIvf3U-xzM0hKUHaAu:-NNIwJ0VDPDgxhSr5L4w:bxhvvdt) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L202)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So the prefix is used for filtering regardless of delimiter, but the delimiter is for grouping but not ordering? I am a bit confused. Can you give an example?
</blockquote></details>

This is my understanding - say we have files
```
a
x/y/1
x/y/2
x/z/1
x/z/2
```

Say we use no prefix (`prefix = ""`). If we don't use a delimiter, we get all of the above. If we use delimiter `/` we get `a` and `x`. A set delimiter means we are listing "directory style"

Say we use prefix `x/`. If we don't use a delimiter, we get all four that start with `x/`. If we use delimiter `/` we get `x/y` and `x/z`  (or maybe `y` and `z` -  I'm not sure if the result would contain the `x/` prefix we provided or not).


AFAICT, there is nothing special about the delimiter used. From what I've read, S3 will treat all names as opaque strings but will use a prefix to break things up into shards internally (the first X chars, where X is chosen depending on how many different values there are for X). Which explains why in some cases you want to include hashed shard early in the filenames.


<!-- Sent from Reviewable.io -->

2023-02-03 18:21 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 1 of 16 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @RaduBerinde)

___
*[`vfs/vfs.go` line 190 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNHqJEo24_OhZ3fnnih:-NNNUsUFEb7clRfhJXKj:b8bxy6) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L190)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should explain the semantics when the object exists (I believe it will be overwritten?). Maybe `CreateObject` is a better name than `Writer`.

Also, I believe this is an all-or-nothing operation (at least on S3 - either there is a single `PutObject` request, or a multi-part upload which only becomes effective with `CompleteMultiPartUpload`). Is this something that would be useful to promise here? I don't think we care about that for SSTs, maybe we would for the blob feature @sumeerbhola is working on?
</blockquote></details>

Blob files will be written the same way as SSTs.
___
*[`vfs/vfs.go` line 202 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNIvf3U-xzM0hKUHaAu:-NNNV66P2yFQtzRekFaB:b-4gy5c9) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L202)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is my understanding - say we have files
```
a
x/y/1
x/y/2
x/z/1
x/z/2
```

Say we use no prefix (`prefix = ""`). If we don't use a delimiter, we get all of the above. If we use delimiter `/` we get `a` and `x`. A set delimiter means we are listing "directory style"

Say we use prefix `x/`. If we don't use a delimiter, we get all four that start with `x/`. If we use delimiter `/` we get `x/y` and `x/z`  (or maybe `y` and `z` -  I'm not sure if the result would contain the `x/` prefix we provided or not).


AFAICT, there is nothing special about the delimiter used. From what I've read, S3 will treat all names as opaque strings but will use a prefix to break things up into shards internally (the first X chars, where X is chosen depending on how many different values there are for X). Which explains why in some cases you want to include hashed shard early in the filenames.
</blockquote></details>

Is this behavior specific to S3?
It sounds like specifying the delimiter means don't do a recursive search into the directory for files. The phrasing sounds confusing to me.

Do we have a use case for specifying the delimiter? If not, can we drop it from the interface until we need it.


<!-- Sent from Reviewable.io -->

2023-02-03 21:20 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 1 of 16 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @sumeerbhola)

___
*[`vfs/vfs.go` line 202 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNIvf3U-xzM0hKUHaAu:-NNO7YBIDS7z7d19xvBO:b-qcadrm) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L202)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this behavior specific to S3?
It sounds like specifying the delimiter means don't do a recursive search into the directory for files. The phrasing sounds confusing to me.

Do we have a use case for specifying the delimiter? If not, can we drop it from the interface until we need it.

</blockquote></details>

google and azure support the same delimiter semantics (as does the CRDB`cloud.ExternalStorage` interface).

I don't immediately see a usecase for us. We could efficiently list all "creator-id"s that have shared objects I guess.


<!-- Sent from Reviewable.io -->

2023-02-06 17:15 UTC, itsbilal reviewed
> Dismissed @sumeerbhola from 6 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 1 of 16 files reviewed, 7 unresolved discussions (waiting on @itsbilal, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`vfs/vfs.go` line 178 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNHpw4NAOHnwV9N-dC3:-NNbc-qq1gx4iFB1-qcZ:b6yk1qf) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L178)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I would move this to `objstorage` (maybe in its own subpackage, e.g. `objstorage/sharedobj`) and rename `File` to `Object` in the methods.

I'd also remove this TODO - if we move the middleware behind an interface, it would be a new higher-level interface (fairly similar to the current `Provider` public "interface"), and we would still use this interface inside that implementation.
</blockquote></details>

Moved. Also updated the TODO to just be about the latter part - pushing obsoletion behind it. It's just a TODO so we can always just drop it.
___
*[`vfs/vfs.go` line 184 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNIuSWvArzREng4H2YD:-NNbZyMw5CCwPhGoYcvh:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L184)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How about removing this shorthand. There is no special case of reading the start of a sstable.
</blockquote></details>

Done.
___
*[`vfs/vfs.go` line 201 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNHtS-A1TozNjlr2gc8:-NNbb6SH48DsG4BSpeYc:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L201)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Prior to the delimiter but after the given `prefix`. Maybe a short example would help.
</blockquote></details>

Done.
___
*[`vfs/vfs.go` line 202 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNIvf3U-xzM0hKUHaAu:-NNbb9zjDHTbR23tXsig:bccgl32) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L202)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

google and azure support the same delimiter semantics (as does the CRDB`cloud.ExternalStorage` interface).

I don't immediately see a usecase for us. We could efficiently list all "creator-id"s that have shared objects I guess.
</blockquote></details>

Good point, added some examples. PTAL.
___
*[`vfs/vfs.go` line 202 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNHtIatCmZZ0qqmiyXF:-NNbbDbLC7_i_fv72pkU:bot5cnc) ([raw file](https://github.com/cockroachdb/pebble/blob/45a5ee1227e3c6df7cf5d60adfdb507f4a303007/vfs/vfs.go#L202)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How can the caller differentiate between an object or a group ("subdirectory")
</blockquote></details>

Not in an obvious way. The `ReaderAt` and `Size` call would fail if you called it at just a directory. Mimics how we use `ExternalStorage`.


<!-- Sent from Reviewable.io -->

2023-02-06 20:22 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231)* status: 0 of 17 files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`objstorage/shared/storage.go` line 44 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNcO9456758CHFmTIWD:-NNcO9456758CHFmTIWE:b-sc96f7) ([raw file](https://github.com/cockroachdb/pebble/blob/8a77fa3bedba1c328b58adaa1a12006774643aee/objstorage/shared/storage.go#L44)):*
> ```Go
> 	//   List("", "/") -> ["a", "b"]
> 	//   List("b", "/") -> ["4", "5", "6"]
> 	//   List("b", "") -> ["4", "5", "6"]
> ```

Shouldn't this be `"/4", "/5", "/6"`?


<!-- Sent from Reviewable.io -->

2023-02-06 21:23 UTC, itsbilal commented
*[`objstorage/shared/storage.go` line 44 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2231#-NNcO9456758CHFmTIWD:-NNcb6qn1eOzZoPL_hfZ:bnqtbtj) ([raw file](https://github.com/cockroachdb/pebble/blob/8a77fa3bedba1c328b58adaa1a12006774643aee/objstorage/shared/storage.go#L44)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Shouldn't this be `"/4", "/5", "/6"`?
</blockquote></details>

Oops, yes. Fixed


<!-- Sent from Reviewable.io -->

2023-02-06 22:00 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2231#-:-NNcjhkdE2yQMQRrmcO9:bnfp4nl)* status: 0 of 17 files reviewed, 7 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-02-07 14:38 UTC, merged