internal/manifest: fix Version.Overlaps length bug
cockroachdb/pebble pull request #2256
Opened 2023-01-19 21:27 UTC by jbowens

Previously, calling `Version.Overlaps` for a level lower than L0 would return a LevelSlice containing the correct files but a `length` field of zero. Thankfully, it appears there were no call sites that accessed such a LevelSlice's `Len()`. Compaction picking came close, but the `Reslice` calls to expand to the atomic compaction unit would compute the length on the adjusted slice before the first call to Len.

This commit fixes this bug by:

1. introducing a [subtreeCount] into the level metadata b-tree nodes, which is incrementally updated with the total number of files within the node's subtree.
2. adding a countLeft method to the B-Tree iterator, which returns the number of files to the left of the iterator's current position within a level. This method takes advantage of the incrementally-computed [subtreeCount] to compute a total in log(N) time.
3. adjusting Overlaps to compute the number of files it's returning in a LevelSlice by subtracting the countLeft values for the end and start bound iterator positions.

2023-01-19 21:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2256)
<!-- Reviewable:end -->

2023-01-20 18:13 UTC, sumeerbhola requested changes
Nice catch!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2256#-:-NMFN_bB8LQx-Vm3aNl9:b-73m6vw)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @jbowens)

___
*[`internal/manifest/btree.go` line 199 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMFH_Kr3NdtHCtWVIhs:-NMFH_Kr3NdtHCtWVIht:b-1fydkr) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/btree.go#L199)):*
> ```Go
> 		// Other references remain. Can't free.
> 		return
> 	}
> ```

unrelated to this PR, this code is a bit confusing.
Why are we only unreffing from `n.items` when `recursive` is true -- those are not in child nodes? I suspect we need a better definition of `recursive` in the method comment.
___
*[`internal/manifest/btree.go` line 250 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMFJImN77kDnmGb4XYl:-NMFJImN77kDnmGb4XYm:b-9xq2mk) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/btree.go#L250)):*
> ```Go
> }
> 
> func (n *node) insertAt(index int, item *FileMetadata, nd *node) {
> ```

I think it would be good to document the various entry points for calling into btree and some additional details of what those entry points call. Without distinguishing between low-level helpers and higher-level (entry points or helpers), it is hard for someone to judge why only certain methods update the `subtreeCount`. For instance, `insertAt` is not updating the `subtreeCount` because it is only called by `insert`, which does.
___
*[`internal/manifest/btree.go` line 365 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMFKXfsE_8D5tM_Pu0g:-NMFKXfsE_8D5tM_Pu0h:bxg89ed) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/btree.go#L365)):*
> ```Go
> //		 +-----------+     +-----------+
> //		 |         x |     | z         |
> //		 +-----------+     +-----------+
> ```

I couldn't reconcile this picture with the code (I've ignored the details here before this PR).
The code is moving `i+1` onwards to a different node `next`. `next` is not linked to `n` and simply returned. The picture shows pointers showing links. It also shows 2 child nodes.
___
*[`internal/manifest/btree.go` line 390 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMF5oVlEJoC2CYgW1qg:-NMF5oVlEJoC2CYgW1qh:b-dik4f8) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/btree.go#L390)):*
> ```Go
> 	}
> 	n.count = int16(i)
> 	n.subtreeCount -= int(next.count) + 1
> ```

why +1?
___
*[`internal/manifest/version.go` line 734 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMF2k_GEEHsY6HS-yd-:-NMF2k_GEEHsY6HS-yd0:bpyl3b3) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/version.go#L734)):*
> ```Go
> 
> 	iter = startIter.Clone()
> 	s := LevelSlice{
> ```

Should we introduce a constructor (or multiple ones, one that lacks a length parameter and another that computes the length) and add a comment that even code that shares the package should not directly initialized a `LevelSlice` struct.
Otherwise we may introduce another bug in the future.

And having the code below in `version.go` seems too low-level. It belongs in the implementation of `LevelSlice`, which also makes it more amenable to unit testing.
___
*[`internal/manifest/version.go` line 744 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMF3YWb-ce-x5glcPrB:-NMF3YWb-ce-x5glcPrC:bbwwdgh) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/version.go#L744)):*
> ```Go
> 		s.length = endIter.iter.countLeft() - startIter.iter.countLeft() + 1
> 	}
> 	if invariants.Enabled {
> ```

Even the constructor that takes a length parameter could benefit from doing such invariant checking to ensure that the parameter has the correct value.
___
*[`internal/manifest/btree_test.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMFNJ7l0R157gYqHwpE:-NMFNJ7mAUBLXNUiFvHL:b-pt07l) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/btree_test.go#L39)):*
> ```Go
> //        Invariant verification        //
> //////////////////////////////////////////
> ```

Do we have a fully randomized test of the btree that builds a large btree with a random sequence of insertions and deletions and checks at every step that it is equivalent to a sorted array?


<!-- Sent from Reviewable.io -->

2023-01-24 19:34 UTC, jbowens reviewed
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2256)* status: 2 of 9 files reviewed, 7 unresolved discussions (waiting on @sumeerbhola)

___
*[`internal/manifest/btree.go` line 199 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMFH_Kr3NdtHCtWVIhs:-NMV5oG3E6HBU7L9bVBr:b-8fqt6c) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/btree.go#L199)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

unrelated to this PR, this code is a bit confusing.
Why are we only unreffing from `n.items` when `recursive` is true -- those are not in child nodes? I suspect we need a better definition of `recursive` in the method comment.
</blockquote></details>

renamed to `contentsToo` and added some commentary
___
*[`internal/manifest/btree.go` line 250 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMFJImN77kDnmGb4XYl:-NMUPyhAAp2kUsOelzWi:by9opny) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/btree.go#L250)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think it would be good to document the various entry points for calling into btree and some additional details of what those entry points call. Without distinguishing between low-level helpers and higher-level (entry points or helpers), it is hard for someone to judge why only certain methods update the `subtreeCount`. For instance, `insertAt` is not updating the `subtreeCount` because it is only called by `insert`, which does.
</blockquote></details>

Good call, I added some comments to distinguish, but I also uppercased all the entrypoints to make it obvious. Although these methods won't actually be accessed outside the package, mimicking the exporting convention seems to help readability.
___
*[`internal/manifest/btree.go` line 365 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMFKXfsE_8D5tM_Pu0g:-NMUvv0E6NoZBX7OQ_Z4:b-hloi9q) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/btree.go#L365)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I couldn't reconcile this picture with the code (I've ignored the details here before this PR).
The code is moving `i+1` onwards to a different node `next`. `next` is not linked to `n` and simply returned. The picture shows pointers showing links. It also shows 2 child nodes.
</blockquote></details>

yeah, this comment is confusing. I updated it to annotate `n` and `next`, and describe which part of the transformation is the responsibility of the caller.
___
*[`internal/manifest/btree.go` line 390 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMF5oVlEJoC2CYgW1qg:-NMUw7Oq-fhPtWIKTo4a:b-7ux5l8) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/btree.go#L390)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why +1?
</blockquote></details>

it's because `out` is a file that was removed from `n` (and not copied to `next`). it'll end up being a part of `n`'s parent node
___
*[`internal/manifest/version.go` line 734 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMF2k_GEEHsY6HS-yd-:-NMUVPt2DCJTNhcfwvz4:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/version.go#L734)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Should we introduce a constructor (or multiple ones, one that lacks a length parameter and another that computes the length) and add a comment that even code that shares the package should not directly initialized a `LevelSlice` struct.
Otherwise we may introduce another bug in the future.

And having the code below in `version.go` seems too low-level. It belongs in the implementation of `LevelSlice`, which also makes it more amenable to unit testing.
</blockquote></details>

Done.
___
*[`internal/manifest/version.go` line 744 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMF3YWb-ce-x5glcPrB:-NMUVZLNA-eN5_c9iFn0:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/version.go#L744)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Even the constructor that takes a length parameter could benefit from doing such invariant checking to ensure that the parameter has the correct value.
</blockquote></details>

Done.
___
*[`internal/manifest/btree_test.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMFNJ7l0R157gYqHwpE:-NM_ACiaCE_fCYYLY7hv:b-vap5m1) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/btree_test.go#L39)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we have a fully randomized test of the btree that builds a large btree with a random sequence of insertions and deletions and checks at every step that it is equivalent to a sorted array?
</blockquote></details>

there wasn't; I added one


<!-- Sent from Reviewable.io -->

2023-01-24 21:42 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 7 files at r2, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2256#-:-NM_iinnA6GtiTr-wb0O:bg7igkv)* status: all files reviewed, 8 unresolved discussions (waiting on @jbowens)

___
*[`internal/manifest/btree.go` line 393 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NM_h26V1B2n_Ef75Ieh:-NM_h26V1B2n_Ef75Iei:b2xw4gd) ([raw file](https://github.com/cockroachdb/pebble/blob/5aebc10474aca5e7ceafa576a32f2c7eb31c6465/internal/manifest/btree.go#L393)):*
> ```Go
> //	              +-----------+     +-----------+
> //
> // split does perform the complete transformation; the caller is responsible for
> ```

does not perform?
___
*[`internal/manifest/btree_test.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMFNJ7l0R157gYqHwpE:-NM_ibcNAkGMl8ei_7Bx:bor96cm) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/btree_test.go#L39)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

there wasn't; I added one
</blockquote></details>

Thanks. Just curious -- did it turn up any bugs?


<!-- Sent from Reviewable.io -->

2023-01-31 19:49 UTC, jbowens reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2256#-:-NN8N8bCBqu0wxa9N3yh:b-814g8k)* status: all files reviewed, 8 unresolved discussions (waiting on @sumeerbhola)

___
*[`internal/manifest/btree.go` line 393 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NM_h26V1B2n_Ef75Ieh:-NN8MnUz6J9Nk6oMtTbm:b4g0byo) ([raw file](https://github.com/cockroachdb/pebble/blob/5aebc10474aca5e7ceafa576a32f2c7eb31c6465/internal/manifest/btree.go#L393)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

does not perform?
</blockquote></details>

oops, done.
___
*[`internal/manifest/btree_test.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2256#-NMFNJ7l0R157gYqHwpE:-NN8MpaIEqcsfY-kAZli:b-2zq7ic) ([raw file](https://github.com/cockroachdb/pebble/blob/d08517bca1fb2a2341e293c3af2dd33a28d71208/internal/manifest/btree_test.go#L39)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Thanks. Just curious -- did it turn up any bugs?
</blockquote></details>

yeah, it turned up bugs in the error cases where eg, the file already exists in the tree during insert or doesn't exist during delete. these cases should be fatal errors in Pebble's use of the btree already, but I think it's a good we found them


<!-- Sent from Reviewable.io -->

2023-01-31 20:02 UTC, merged