replay: unlake TestCollectCorpus
cockroachdb/pebble pull request #2258
Opened 2023-01-20 00:22 UTC by bananabrick

Files can be deleted asynchronously so it makes sense to wait for cleaning to complete before listing the files.

2023-01-20 00:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2258)
<!-- Reviewable:end -->

2023-01-20 04:58 UTC, bananabrick commented
This was stressed on my gceworker on this branch: https://github.com/cockroachdb/pebble/actions/runs/3962893708/jobs/6790113662, and with this fix the flakes stop.

2023-01-20 14:50 UTC, jbowens reviewed
Does this flake on master? I haven't been able to reproduce, although I don't know why it wouldn't.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2258#-:-NMEdjsW5IJotqQ5wZNi:buyhstm)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[`db.go` line 490 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2258#-NMEd_fl6TA_AfnTmqLH:-NMEd_fl6TA_AfnTmqLI:b-sdj3r6) ([raw file](https://github.com/cockroachdb/pebble/blob/329276c095e9a0e3b7ca1dc044b0e0c85d537cff/db.go#L490)):*
> ```Go
> 		d.mu.cleaner.cond.Wait()
> 	}
> }
> ```

I'd love to avoid exporting this. I think it would work to wait for cleaning after an explicit flush (in `DB.Flush`)
___
*[`replay/replay_test.go` line 300 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2258#-NMEdPVlD1rYG9yUj5mW:-NMEdPVlD1rYG9yUj5mX:b-rpvo1y) ([raw file](https://github.com/cockroachdb/pebble/blob/329276c095e9a0e3b7ca1dc044b0e0c85d537cff/replay/replay_test.go#L300)):*
> ```Go
> 		case "wait-for-cleaning":
> 			d.WaitForCleaning()
> 			return ""
> ```

let's combine this with `list-files` to avoid boilerplate


<!-- Sent from Reviewable.io -->

2023-01-21 21:32 UTC, bananabrick reviewed
No, it doesn't. Something about my changes to the `flush1` function changes the timing of these. It repros every 5 mins on my gceworker without this patch, on my flushable ingest branch.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2258#-:-NMFnPWPDub2Kt6ftjjp:btp46l6)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`db.go` line 490 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2258#-NMEd_fl6TA_AfnTmqLH:-NMGPwps6RDx46TxOeZy:b-2x774n) ([raw file](https://github.com/cockroachdb/pebble/blob/329276c095e9a0e3b7ca1dc044b0e0c85d537cff/db.go#L490)):*
> I'd love to avoid exporting this. I think it would work to wait for cleaning after an explicit flush (in DB.Flush)
Does it make sense to wait for cleaning after every call to DB.Flush? Doesn't it change the semantics of that function/make it slower?
___
*[`replay/replay_test.go` line 300 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2258#-NMEdPVlD1rYG9yUj5mW:-NMFndg-AAJs7EL_kE78:bmjyqe4) ([raw file](https://github.com/cockroachdb/pebble/blob/329276c095e9a0e3b7ca1dc044b0e0c85d537cff/replay/replay_test.go#L300)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

let's combine this with `list-files` to avoid boilerplate
</blockquote></details>

Not every call to `list-files` should have that call. I tried that first and it errors out. There's cases where we're not listing files on the `build` dir in which case waiting for cleaning doesn't make sense, and there's could be cases where we could `list-files` after the DB is closed, and we set db to `nil`, in which case the test would panic.


<!-- Sent from Reviewable.io -->

2023-01-22 16:42 UTC, jbowens requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2258)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[`db.go` line 490 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2258#-NMEd_fl6TA_AfnTmqLH:-NMPM-SW6qZCVh8_lW7m:b-5k3e0) ([raw file](https://github.com/cockroachdb/pebble/blob/329276c095e9a0e3b7ca1dc044b0e0c85d537cff/db.go#L490)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

> I'd love to avoid exporting this. I think it would work to wait for cleaning after an explicit flush (in DB.Flush)
Does it make sense to wait for cleaning after every call to DB.Flush? Doesn't it change the semantics of that function/make it slower?
</blockquote></details>

Explicit flushes are not performance sensitive
___
*[`replay/replay_test.go` line 300 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2258#-NMEdPVlD1rYG9yUj5mW:-NMPLt1Q4RbOWgIvU3qW:b-rawhhm) ([raw file](https://github.com/cockroachdb/pebble/blob/329276c095e9a0e3b7ca1dc044b0e0c85d537cff/replay/replay_test.go#L300)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Not every call to `list-files` should have that call. I tried that first and it errors out. There's cases where we're not listing files on the `build` dir in which case waiting for cleaning doesn't make sense, and there's could be cases where we could `list-files` after the DB is closed, and we set db to `nil`, in which case the test would panic.
</blockquote></details>

errors how? can we not do a nil check of the DB?


<!-- Sent from Reviewable.io -->

2023-01-23 17:42 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2258)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`db.go` line 490 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2258#-NMEd_fl6TA_AfnTmqLH:-NMUhLFk3z3YGqE6tQiK:b-jomfdg) ([raw file](https://github.com/cockroachdb/pebble/blob/329276c095e9a0e3b7ca1dc044b0e0c85d537cff/db.go#L490)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Explicit flushes are not performance sensitive
</blockquote></details>

There's some tests which are acquiring a cleaning turn before calling `DB.Flush`, so waiting for cleaning in `DB.Flush` makes those tests hang. Waiting for flush on `list-files` now. Added a `must not use outside tests` warning to the `WaitForCleaning` function. And also renamed it to `TestOnlyWaitForCleaning`.

A bit odd, but lmk if that seems good enough.
___
*[`replay/replay_test.go` line 300 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2258#-NMEdPVlD1rYG9yUj5mW:-NMUhYLBDfX8BjkJni2m:bwz5evu) ([raw file](https://github.com/cockroachdb/pebble/blob/329276c095e9a0e3b7ca1dc044b0e0c85d537cff/replay/replay_test.go#L300)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

errors how? can we not do a nil check of the DB?
</blockquote></details>

We could.


<!-- Sent from Reviewable.io -->

2023-01-24 16:26 UTC, jbowens approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2258#-:-NMZabqlA7GENh6AI-Sj:bnfp4nl)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @itsbilal)



<!-- Sent from Reviewable.io -->

2023-01-24 17:54 UTC, merged

2023-02-01 20:12 UTC, jbowens commented
Ran into a comment that made me do some more archaeology here. Looks like flush used to synchronously ensure files were deleted: https://github.com/cockroachdb/pebble/commit/bb805d0c8238e733ca154dfb5e43bcb9aeec6b37 This was changed in https://github.com/cockroachdb/pebble/commit/f8e879e0ae2f8e923e13df46772edf091d5159e3. I may look at fixing the behavior for manual flushes later.