vfs: Make all onDiskSlow calls async in diskHealthChecking{File,FS}
cockroachdb/pebble pull request #2278
Opened 2023-01-25 23:43 UTC by itsbilal

In case the event listener stalls during an OnDiskSlow() call, we need to ensure that the disk health checking goroutine itself is not interrupted. This change spins up a new goroutine to make the event listener call, while letting the health checking goroutine itself keep ticking at its own pace.

Fixes #2273.

2023-01-25 23:44 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2278)
<!-- Reviewable:end -->

2023-01-26 00:10 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2278)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`event.go` line 638 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMfOZCZ4R18HCj5Uacy:-NMfOZCZ4R18HCj5Uacz:b-e06wrp) ([raw file](https://github.com/cockroachdb/pebble/blob/e50f65cae37b0c124e7fbf68b43236d22d126a75/event.go#L638)):*
> ```Go
> 			// DiskSlow is a potentially critical event as it could result in the
> 			// process crashing. Run both operations in parallel so that either could
> 			// crash the process even if the other blocks.
> ```

[nit] Feels strange that one is async and one isn't. We should make them both async, or we should wait until both are done before returning.
___
*[`event.go` line 640 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMfOs5l2C9QTZ41a90g:-NMfOs5l2C9QTZ41a90h:b-9kkdsl) ([raw file](https://github.com/cockroachdb/pebble/blob/e50f65cae37b0c124e7fbf68b43236d22d126a75/event.go#L640)):*
> ```Go
> 			// crash the process even if the other blocks.
> 			go func() {
> 				a.DiskSlow(info)
> ```

[nit] can just be `go a.DiskSlow(info)`
___
*[`vfs/disk_health.go` line 396 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMfP4ST0XAmgg16hUMq:-NMfP4SUBsRgeIMrvAwY:b26j6xh) ([raw file](https://github.com/cockroachdb/pebble/blob/e50f65cae37b0c124e7fbf68b43236d22d126a75/vfs/disk_health.go#L396)):*
> ```Go
> 						inflightOp := *d.mu.inflight[i]
> 						go func(inflightOp slot, nanos int64, now time.Time) {
> 							d.onSlowDisk(inflightOp.name, inflightOp.opType, now.Sub(time.Unix(0, nanos)))
> ```

Are we moving `nanos` on the heap here? Why not just ` go d.onSlowDisk(..)`?


<!-- Sent from Reviewable.io -->

2023-01-26 00:17 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2278#-:-NMfQv6N2wiR2g21F9ws:b-814g8k)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jbowens and @RaduBerinde)

___
*[`event.go` line 638 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMfOZCZ4R18HCj5Uacy:-NMfQY2D3a7FS27FIocI:b-63zqsv) ([raw file](https://github.com/cockroachdb/pebble/blob/e50f65cae37b0c124e7fbf68b43236d22d126a75/event.go#L638)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Feels strange that one is async and one isn't. We should make them both async, or we should wait until both are done before returning.
</blockquote></details>

Done. Had them wait, that way they're async from one another. That way it's still the caller's responsibility to call the event listener in an async way, and the event listener itself is allowed to block.
___
*[`event.go` line 640 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMfOs5l2C9QTZ41a90g:-NMfQXbtCWE3-8b5vOeW:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/e50f65cae37b0c124e7fbf68b43236d22d126a75/event.go#L640)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] can just be `go a.DiskSlow(info)`
</blockquote></details>

Done.
___
*[`vfs/disk_health.go` line 396 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMfP4ST0XAmgg16hUMq:-NMfQhic97Dio2nh-diw:b-dp6kp0) ([raw file](https://github.com/cockroachdb/pebble/blob/e50f65cae37b0c124e7fbf68b43236d22d126a75/vfs/disk_health.go#L396)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Are we moving `nanos` on the heap here? Why not just ` go d.onSlowDisk(..)`?
</blockquote></details>

Yeah, we are. Is the heap leak inefficient enough? I guess I could load the atomic again into a `nanos` just so we don't leak the outer nanos if that's going to be an allocation, that way the allocation at least becomes conditional on us being in the disk-slow case. PTAL?


<!-- Sent from Reviewable.io -->

2023-01-26 00:23 UTC, RaduBerinde commented
*[`vfs/disk_health.go` line 396 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMfP4ST0XAmgg16hUMq:-NMfSB667aAtSTW-Px2v:b-cyo0bh) ([raw file](https://github.com/cockroachdb/pebble/blob/e50f65cae37b0c124e7fbf68b43236d22d126a75/vfs/disk_health.go#L396)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yeah, we are. Is the heap leak inefficient enough? I guess I could load the atomic again into a `nanos` just so we don't leak the outer nanos if that's going to be an allocation, that way the allocation at least becomes conditional on us being in the disk-slow case. PTAL?
</blockquote></details>

Bur why do we have to calculate inside the goroutine? If we just do `d.onSlowDisk(..)` we calculate it beforehand


<!-- Sent from Reviewable.io -->

2023-01-26 00:26 UTC, RaduBerinde commented
*[`vfs/disk_health.go` line 396 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMfP4ST0XAmgg16hUMq:-NMfSdoU22g-qy6kGxdh:b-ig953u) ([raw file](https://github.com/cockroachdb/pebble/blob/e50f65cae37b0c124e7fbf68b43236d22d126a75/vfs/disk_health.go#L396)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Bur why do we have to calculate inside the goroutine? If we just do `d.onSlowDisk(..)` we calculate it beforehand
</blockquote></details>

Oh sorry, r2 looks good. And I was wrong - I didn't notice you made nanos an argument, it was ok before too.


<!-- Sent from Reviewable.io -->

2023-01-26 02:08 UTC, sumeerbhola reviewed
I wonder whether this is the right solution. We are spinning up goroutines and if we have a huge number of slow disk events whose goroutines try to write to disk to log, they will all get stuck. Perhaps this is not a problem now since our write concurrency is low (WAL + compactions + SQL spilling), but if we also start measuring reads this could be a bigger issue.

An alternative would be to make this the problem of whoever is using Pebble (e.g. CockroachDB). Pebble would document that `EventListener.DiskSlow` is required to return without doing any synchronous IO. CockroachDB can still tee everything other than `DiskSlow` to the `pebbleLogger` (it can simply overwrite the `DiskSlow` func in the `EventListener` returned by `pebble.MakeLoggingEventListener` to make it a noop). The CockroachDB implementation of `DiskSlow` would use a fixed size circular buffer of events to be logged that a separate (single) goroutine can pick up and log.

We may want to change `diskHealthCheckingFS` so that it doesn't emit these events while holding `diskHealthCheckingFS.mu` since we don't want a deadlock where the caller holding `diskHealthCheckingFS.mu` tries to acquire a mutex on the circular buffer (if it is not lock free). And later the logging goroutine holding the circular buffer mutex tries to write to disk -- though we can break this deadlock trivially by making the circular buffer mu the lowest in the ordering (the logging goroutine would release it before logging).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2278#-:-NMfkqoIAgzx4jyXUliV:b-4s01bh)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @jbowens)



<!-- Sent from Reviewable.io -->

2023-01-26 03:03 UTC, itsbilal reviewed
> We may want to change diskHealthCheckingFS so that it doesn't emit these events while holding diskHealthCheckingFS.mu since we don't want a deadlock where the caller holding diskHealthCheckingFS.mu tries to acquire a mutex on the circular buffer (if it is not lock free). 

Isnt' this already the case in this PR? The call to the event listener is happening in a separate goroutine which holds no locks, and the goroutine creating it is the one holding the `diskHealthCheckingFS.mu`, so it's going to go ahead and release it once it's done going through `d.mu.inflight` and then our child goroutines can do whatever the event listener is doing. Unless I'm misunderstanding your point about the logging event listener.

I also don't think we will, in normal (CockroachDB) cases, end up with too many logging goroutines stuck on the log step - the tick interval is pretty low and as you said write concurrency is also pretty low, and we'll soon be past the fatal threshold where the other tee'd event listener will just crash the whole process. But it'd be best to test this in practice.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2278#-:-NMg--596d7_1hb-CeTL:b-47j9bb)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jbowens)



<!-- Sent from Reviewable.io -->

2023-01-26 14:17 UTC, sumeerbhola commented
> Isnt' this already the case in this PR?

The alternative I was suggesting would eliminate this PR. But anyway the deadlock I was musing about is not possible (in what I was suggesting), since the `EventListener.DiskSlow` func is not allowed to depend (even indirectly) on any IO code (by the contract) -- this includes not waiting on a mutex that is being held by something doing IO (so the logging goroutine would copy the circular buffer, release the mutex, and then do IO).

I am now more inclined towards making this CockroachDB's problem. By spinning up a goroutine in Pebble we are trying to solve a problem specific to what CockroachDB is doing in its event handler -- the solution belongs in that higher layer. And the higher layer knows what part of the handling is allowed to be lossy (the logging, via the circular buffer) and what cannot be lossy (the crashing) -- that knowledge is not available to Pebble hence the necessity to make everything non-lossy by using a goroutine per event.

2023-01-26 16:06 UTC, itsbilal commented
I see what you mean now. I would still advocate for this change, as it does seem non-ideal that Pebble calls into an external interface from a very critical goroutine, while holding a mutex in it nonetheless. If the event handler takes too long for any reason (whether IO or, say, a deadlock), Pebble would genuinely miss stalls. Pebble doesn't need to require too many guarantees off of the EventListener, and rarely spinning off a new goroutine to make it happen seems in line with what it should be doing here. I worry that if we don't strengthen up the disk health checking code, some future event handler code will just come around and break disk health checking again.

Even the `TeeEventHandler` code makes sense from that principle, it runs both of them concurrently.

2023-01-26 19:12 UTC, itsbilal commented
This is ready for a review after making changes that were suggested in standup. PTAL!

2023-01-26 19:20 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2278#-:-NMjWYD2A4D5LqbXDT95:bnfp4nl)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`vfs/disk_health.go` line 277 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMjVkrt6ht1XvZvRiWC:-NMjVkrt6ht1XvZvRiWD:bhrfo3z) ([raw file](https://github.com/cockroachdb/pebble/blob/a091a61e8c5f8a1b03eec83628a831e425f31591/vfs/disk_health.go#L277)):*
> ```Go
> 	// in tests before the ticker starts. Used to change the tick interval
> 	// to speed up tests.
> 	testingHook func(f File)
> ```

[nit] This is no longer used
___
*[`vfs/disk_health.go` line 416 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMjW8RE4_9Mqv6HztFw:-NMjW8RE4_9Mqv6HztFx:bwskhj7) ([raw file](https://github.com/cockroachdb/pebble/blob/a091a61e8c5f8a1b03eec83628a831e425f31591/vfs/disk_health.go#L416)):*
> ```Go
> 						inflightOp.name = d.mu.inflight[i].name
> 						inflightOp.opType = d.mu.inflight[i].opType
> 						inflightOp.startNanos = atomic.LoadInt64(&d.mu.inflight[i].startNanos)
> ```

[nit] why Load it again (instead of just using `nanos`)?


<!-- Sent from Reviewable.io -->

2023-01-26 19:53 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2278#-:-NMjd0KA2P08fIKlACS2:b-814g8k)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @jbowens and @sumeerbhola)

___
*[`vfs/disk_health.go` line 277 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMjVkrt6ht1XvZvRiWC:-NMjd17zCOuAElElG99V:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a091a61e8c5f8a1b03eec83628a831e425f31591/vfs/disk_health.go#L277)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This is no longer used
</blockquote></details>

Done.
___
*[`vfs/disk_health.go` line 416 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMjW8RE4_9Mqv6HztFw:-NMjd1kw4pjuLrXYOy8S:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a091a61e8c5f8a1b03eec83628a831e425f31591/vfs/disk_health.go#L416)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] why Load it again (instead of just using `nanos`)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-26 20:08 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2278)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`event.go` line 648 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMflggT86CTp9DhV1Fq:-NMflggT86CTp9DhV1Fr:blnqt78) ([raw file](https://github.com/cockroachdb/pebble/blob/2ed559a67f2e0d04e7b192e9a3b7e89a744188d4/event.go#L648)):*
> ```Go
> 			b.DiskSlow(info)
> 			wg.Wait()
> 		},
> ```

I think we could leave this entirely synchronous, and rely on the ordering.
___
*[`vfs/disk_health.go` line 419 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMjgAWe64LrAEV83hgW:-NMjgAWe64LrAEV83hgX:b4e2w92) ([raw file](https://github.com/cockroachdb/pebble/blob/c8bcdc9051b3abe275603db1b93e7f257f99f89f/vfs/disk_health.go#L419)):*
> ```Go
> 				for i := range exceededSlots {
> 					d.onSlowDisk(exceededSlots[i].name, exceededSlots[i].opType, now.Sub(time.Unix(0, exceededSlots[i].startNanos)))
> 				}
> ```

although this won't block with `d.mu`, it will block the filesystem's one goroutine monitoring filesystem-level operations. if `onSlowDisk` were to block indefinitely, new writes could still be attempted but we'd never call `onSlowDisk` again at the filesystem level. are we okay with that? (not sure if this was already discussed during standup)


<!-- Sent from Reviewable.io -->

2023-01-26 20:17 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2278)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`event.go` line 648 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMflggT86CTp9DhV1Fq:-NMjiW-m1r9uJfrPb8eQ:bvupnaa) ([raw file](https://github.com/cockroachdb/pebble/blob/2ed559a67f2e0d04e7b192e9a3b7e89a744188d4/event.go#L648)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think we could leave this entirely synchronous, and rely on the ordering.
</blockquote></details>

We could, but I think this makes it less brittle. We still wait on it so it's still synchronous to some extent, just parallel.
___
*[`vfs/disk_health.go` line 419 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMjgAWe64LrAEV83hgW:-NMjiCm0DOCACntIPk5d:bv03u2l) ([raw file](https://github.com/cockroachdb/pebble/blob/c8bcdc9051b3abe275603db1b93e7f257f99f89f/vfs/disk_health.go#L419)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

although this won't block with `d.mu`, it will block the filesystem's one goroutine monitoring filesystem-level operations. if `onSlowDisk` were to block indefinitely, new writes could still be attempted but we'd never call `onSlowDisk` again at the filesystem level. are we okay with that? (not sure if this was already discussed during standup)
</blockquote></details>

Yeah, this was discussed (mostly in the conversation above and also a bit in the standup) and the preferred choice was to make the call asynchronous (or fully stubbed-out) in Cockroach as it's more aware of the implementation details of the logger there. The EventListener contract already requires all calls to return immediately.


<!-- Sent from Reviewable.io -->

2023-01-26 20:17 UTC, itsbilal commented
*[`vfs/disk_health.go` line 419 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMjgAWe64LrAEV83hgW:-NMjic3w8SKaiRYX3Jly:bgpqht7) ([raw file](https://github.com/cockroachdb/pebble/blob/c8bcdc9051b3abe275603db1b93e7f257f99f89f/vfs/disk_health.go#L419)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yeah, this was discussed (mostly in the conversation above and also a bit in the standup) and the preferred choice was to make the call asynchronous (or fully stubbed-out) in Cockroach as it's more aware of the implementation details of the logger there. The EventListener contract already requires all calls to return immediately.
</blockquote></details>

https://github.com/cockroachdb/cockroach/pull/96021 is the Cockroach change.


<!-- Sent from Reviewable.io -->

2023-01-26 20:28 UTC, sumeerbhola requested changes
> Reviewed 1 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2278)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`event.go` line 648 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMflggT86CTp9DhV1Fq:-NMjj-cB7P8simO38hZr:b-sz5hn5) ([raw file](https://github.com/cockroachdb/pebble/blob/2ed559a67f2e0d04e7b192e9a3b7e89a744188d4/event.go#L648)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We could, but I think this makes it less brittle. We still wait on it so it's still synchronous to some extent, just parallel.
</blockquote></details>

Once we do the documentation earlier this should not be needed. I thought we had agreed that any goroutine creation (which may be expedient) should be in the CockroachDB code.
___
*[`event.go` line 436 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMjjAAO-Zn2ZPbtS7Os:-NMjjAAO-Zn2ZPbtS7Ot:b-dbzlxf) ([raw file](https://github.com/cockroachdb/pebble/blob/c8bcdc9051b3abe275603db1b93e7f257f99f89f/event.go#L436)):*
> ```Go
> 	// DiskSlow is invoked after a disk write operation on a file created
> 	// with a disk health checking vfs.FS (see vfs.DefaultWithDiskHealthChecks)
> 	// is observed to exceed the specified disk slowness threshold duration.
> ```

Can you add here:
// DiskSlow is called on a goroutine that is monitoring slowness/stuckness. The callee MUST return without doing any IO, or blocking on anything (like a mutex) that is waiting on IO. This is imperative in order to reliably monitor for slowness, since if this goroutine gets stuck, the monitoring will stop working.
___
*[`vfs/disk_health.go` line 401 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMjknVFD_JyL0oghLMM:-NMjknVFD_JyL0oghLMN:b-6zhz1s) ([raw file](https://github.com/cockroachdb/pebble/blob/c8bcdc9051b3abe275603db1b93e7f257f99f89f/vfs/disk_health.go#L401)):*
> ```Go
> 				// Scan the inflight slots for any slots recording a start
> 				// time older than the diskSlowThreshold.
> 				var exceededSlots []slot
> ```

Can we lift the declaration out of the for loop and just slice it down to 0 length here, to avoid repeated allocations.


<!-- Sent from Reviewable.io -->

2023-01-26 20:56 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2278#-:-NMjr_UB7Op2gCnGx8kG:b-814g8k)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`event.go` line 648 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMflggT86CTp9DhV1Fq:-NMjrBPkDkbMgl1hmGzS:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/2ed559a67f2e0d04e7b192e9a3b7e89a744188d4/event.go#L648)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Once we do the documentation earlier this should not be needed. I thought we had agreed that any goroutine creation (which may be expedient) should be in the CockroachDB code.
</blockquote></details>

Done.
___
*[`event.go` line 436 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMjjAAO-Zn2ZPbtS7Os:-NMjrArMCl2uPSlT_8Zw:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c8bcdc9051b3abe275603db1b93e7f257f99f89f/event.go#L436)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add here:
// DiskSlow is called on a goroutine that is monitoring slowness/stuckness. The callee MUST return without doing any IO, or blocking on anything (like a mutex) that is waiting on IO. This is imperative in order to reliably monitor for slowness, since if this goroutine gets stuck, the monitoring will stop working.
</blockquote></details>

Done.
___
*[`vfs/disk_health.go` line 401 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2278#-NMjknVFD_JyL0oghLMM:-NMjrTm66j8G7aGpRyuJ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c8bcdc9051b3abe275603db1b93e7f257f99f89f/vfs/disk_health.go#L401)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can we lift the declaration out of the for loop and just slice it down to 0 length here, to avoid repeated allocations.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-26 22:47 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2278#-:-NMkFz5WA2_4yEuAWldo:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @jbowens)



<!-- Sent from Reviewable.io -->

2023-01-26 22:49 UTC, itsbilal commented
TFTR!

2023-01-26 22:49 UTC, merged

2023-01-26 23:03 UTC, nicktrav commented
We'll backport this, yeah?