db: implement relaxed target file size splitting heuristic
cockroachdb/pebble pull request #2316
Opened 2023-02-09 19:53 UTC by jbowens

This commit implements a compaction-splitting heuristic as implemented by RocksDB and described within the blog post "Reduce Write Amplification by Aligning Compaction Output File Boundaries." [1]

Aligning sstable boundaries can significantly reduce write amplification. Consider the following compaction:

                                   +----------------------+
                  input            |                      |
                  level            +----------------------+
                                              \/
                           +---------------+       +---------------+
                  output   |XXXXXXX|       |       |      |XXXXXXXX|
                  level    +---------------+       +---------------+

The input-level file overlaps two files in the output level, but only partially. The beginning of the first output-level file and the end of the second output-level file will be rewritten verbatim. This write IO is "wasted" in the sense that no merging is being performed.

To prevent the above waste, this commit adapts the file-size splitter to attempt to split output files at the boundaries of overlapping grandparent files. The file-size spliiter still strives to write output files of approximately the target file size, by constraining this splitting at grandparent points to apply only if the current output's file size is about the right order of magnitude.

The tolerance for how much an output file may deviate from its target file size is adaptive, based on the number of grandparent files that are observed while constructing the file. The particulars of this heuristic are currently implemented as they are within RocksDB. Future work may adjust the heuristic to improve write-amp savings, or reduce the difference between actual and target file sizes.

As implemented, a kv0 (random writes) compaction workload that writes 20gb of data starting from an empty database with compaction concurrency 5 observes a ~19% reduction in write-amplification:

```
                         │ master-829675f94-kv20gb.txt │ boundary-alignment-a8aafd44-kv20gb.txt │
                         │            wamp             │      wamp        vs base               │
Replay/kv0/20gb/WriteAmp                    9.445 ± 2%        7.650 ± 8%  -19.01% (p=0.002 n=6)
```

[1] http://rocksdb.org/blog/2022/10/31/align-compaction-output-file.html

2023-02-09 19:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2316)
<!-- Reviewable:end -->

2023-02-09 20:16 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @RaduBerinde and @sumeerbhola)

___
*[`compaction.go` line 219 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NNrnqli6nLt7QzWvVWa:-NNrnqli6nLt7QzWvVWb:b-gcvuuj) ([raw file](https://github.com/cockroachdb/pebble/blob/9b8e2fa39a9a09ab7021d50f9a51502aa50e517e/compaction.go#L219)):*
> ```Go
> 	if key.Kind() == InternalKeyKindRangeDelete || tw == nil {
> 		return noSplit
> 	}
> ```

The omission of range keys in this existing code seems suspect to me.


<!-- Sent from Reviewable.io -->

2023-02-09 20:29 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

___
*[`-- commits` line 51 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NNrp7SC5npUUzde1oMc):*
This is a larger w-amp reduction than I observed with a much smaller kv0 workload:

```
                         │ old-kvshort.txt │         new-kvshort-3.txt         │
                         │      wamp       │    wamp     vs base               │
Replay/kv0short/WriteAmp       5.587 ± 12%   4.891 ± 4%  -12.44% (p=0.002 n=6)
```

I'm running another 40gb kv0 workload experiment now. I don't have an explanation for why this heuristic would become more effective with a larger write volume. I know the savings are dependent on the fan-out factor. If compactions regularly have fewer output-level sstables relative to inputs, the amount of waste due to misalignment is higher. The RocksDB blog post describes how with a fan out of 6x, this heuristic should be able to save a theoretical ~14% if always producing perfectly aligned files.

Is the fan-out factor smaller with the larger workload because the LSM is becoming more inverted? I need to add more metrics to the workload replayer to make that more observable. 


<!-- Sent from Reviewable.io -->

2023-02-10 21:17 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @bananabrick, @jbowens, and @RaduBerinde)

___
*[`-- commits` line 51 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NNrp7SC5npUUzde1oMc):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This is a larger w-amp reduction than I observed with a much smaller kv0 workload:

```
                         │ old-kvshort.txt │         new-kvshort-3.txt         │
                         │      wamp       │    wamp     vs base               │
Replay/kv0short/WriteAmp       5.587 ± 12%   4.891 ± 4%  -12.44% (p=0.002 n=6)
```

I'm running another 40gb kv0 workload experiment now. I don't have an explanation for why this heuristic would become more effective with a larger write volume. I know the savings are dependent on the fan-out factor. If compactions regularly have fewer output-level sstables relative to inputs, the amount of waste due to misalignment is higher. The RocksDB blog post describes how with a fan out of 6x, this heuristic should be able to save a theoretical ~14% if always producing perfectly aligned files.

Is the fan-out factor smaller with the larger workload because the LSM is becoming more inverted? I need to add more metrics to the workload replayer to make that more observable. 
</blockquote></details>

Very nice!

What are the steps to reproduce this?
Is there pacing to prevent the LSM from getting inverted?


<!-- Sent from Reviewable.io -->

2023-02-13 16:58 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @bananabrick, @jbowens, and @RaduBerinde)

___
*[`-- commits` line 51 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NNrp7SC5npUUzde1oMc):*
> The RocksDB blog post describes how with a fan out of 6x, this heuristic should be able to save a theoretical ~14% if always producing perfectly aligned files.

My understanding of that calculation is that it is assuming the same target file size across levels. Are we doubling the file size in these experiments, like we do in CockroachDB? If we have a data size fanout of 6, and are compacting a F byte file from the higher level that roughly overlaps with 6F bytes at the lower level, and there are 2F sized files at the lower level, then the wastage is 2/(6+1) = 28.5%.
    


<!-- Sent from Reviewable.io -->

2023-02-13 17:24 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @bananabrick, @RaduBerinde, and @sumeerbhola)

___
*[`-- commits` line 51 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NNrp7SC5npUUzde1oMc):*
> Is there pacing to prevent the LSM from getting inverted?

These numbers were collected with a pacer that strives to keep r-amp ≤ 10. I suppose that's still more aggressive than is typical in a steady state. I'll try again this time pacing by the reference workload's r-amp.

> What are the steps to reproduce this?

1. Follow the instructions in [this confluence doc](https://cockroachlabs.atlassian.net/wiki/spaces/STOR/pages/2861105466/Compaction+benchmarking#Precollected-workloads), using the snapshot `7817513537632901661` to mount a volume containing the workload to your gceworker.
2. Check out [jbowens/pebble:boundary-alignment-test](https://github.com/jbowens/pebble/tree/boundary-alignment-test) and `go install ./cmd/pebble`.
3. Run `pebble bench replay -v "/mnt/disks/$DISK_NAME/store_1/20230117212340" --name kv0/20gb --count 6 --options "[Options] max_concurrent_compactions=5" --max-writes 20480 > with-alignment-20gb.txt`

You can build and run `cmd/pebble` without these commits to get numbers for master and use `benchstat` to compare results.

> My understanding of that calculation is that it is assuming the same target file size across levels. Are we doubling the file size in these experiments, like we do in CockroachDB? If we have a data size fanout of 6, and are compacting a F byte file from the higher level that roughly overlaps with 6F bytes at the lower level, and there are 2F sized files at the lower level, then the wastage is 2/(6+1) = 28.5%.

Yeah, we're doubling file size each level. What's a "data size fanout?" I'm not convinced I'm thinking about this right, but my thinking was:  Level L has N bytes and files of target size F, so level L+1 has 10N bytes and files of 2F size. If keys are randomly distributed and equally-sized, then level L+1 should have 10x as many bytes within the bounds of a file in L. Those 10x bytes are distributed across files of double the size, so there should be ~5 overlapping files in level L+1 if perfectly aligned. Since before the heuristic, they were almost never aligned, there's an expect overlap of 6 files.


<!-- Sent from Reviewable.io -->

2023-02-13 17:42 UTC, jbowens reviewed
With `--options "[Options] max_concurrent_compactions=5" --max-writes 10240 --pacer=fixed-ramp=10`:

```
                                               │ 46a768dca-10gb.txt │           19381f17e-10gb.txt           │
                                               │       bytes        │     bytes      vs base                 │
BenchmarkReplay/kv0/10gb/DatabaseSize/mean           2.966Gi ± 4%     3.138Gi ±  3%   +5.81% (p=0.004 n=6)
BenchmarkReplay/kv0/10gb/DatabaseSize/max            5.261Gi ± 1%     5.085Gi ±  1%   -3.36% (p=0.002 n=6)
BenchmarkReplay/kv0/10gb/EstimatedDebt/mean          2.639Gi ± 5%     2.457Gi ±  8%   -6.91% (p=0.002 n=6)
BenchmarkReplay/kv0/10gb/EstimatedDebt/max           4.258Gi ± 3%     3.788Gi ± 11%  -11.04% (p=0.002 n=6)

                                          │ 46a768dca-10gb.txt │        19381f17e-10gb.txt         │
                                          │        move        │    move     vs base               │
BenchmarkReplay/kv0/10gb/CompactionCounts          591.5 ± 10%   409.0 ± 4%  -30.85% (p=0.002 n=6)

                                          │ 46a768dca-10gb.txt │         19381f17e-10gb.txt         │
                                          │    compactions     │ compactions  vs base               │
BenchmarkReplay/kv0/10gb/CompactionCounts          3.659k ± 2%   2.950k ± 2%  -19.37% (p=0.002 n=6)

                                          │ 46a768dca-10gb.txt │         19381f17e-10gb.txt         │
                                          │      default       │   default    vs base               │
BenchmarkReplay/kv0/10gb/CompactionCounts          3.068k ± 4%   2.543k ± 3%  -17.11% (p=0.002 n=6)

                                           │ 46a768dca-10gb.txt │          19381f17e-10gb.txt          │
                                           │       sec/op       │    sec/op     vs base                │
BenchmarkReplay/kv0/10gb/DurationWorkload          209.3 ±   7%    165.2 ±  3%   -21.06% (p=0.002 n=6)
BenchmarkReplay/kv0/10gb/DurationQuiescing         17.33 ±   6%    11.41 ±  4%   -34.19% (p=0.002 n=6)
BenchmarkReplay/kv0/10gb/WriteStalls               8.852 ± 100%   20.362 ± 38%  +130.03% (p=0.009 n=6)

                                      │ 46a768dca-10gb.txt │        19381f17e-10gb.txt        │
                                      │       files        │   files     vs base              │
BenchmarkReplay/kv0/10gb/ReadAmp/mean           8.862 ± 6%   8.166 ± 6%  -7.85% (p=0.004 n=6)
BenchmarkReplay/kv0/10gb/ReadAmp/max            12.00 ± 8%   12.00 ± 0%       ~ (p=1.000 n=6)

                                  │ 46a768dca-10gb.txt │        19381f17e-10gb.txt         │
                                  │        wamp        │    wamp     vs base               │
BenchmarkReplay/kv0/10gb/WriteAmp           8.794 ± 1%   7.229 ± 2%  -17.80% (p=0.002 n=6)

                                     │ 46a768dca-10gb.txt │         19381f17e-10gb.txt          │
                                     │       stalls       │   stalls     vs base                │
BenchmarkReplay/kv0/10gb/WriteStalls         28.50 ± 135%   82.00 ± 35%  +187.72% (p=0.004 n=6)
``` 

I believe the increased write stalls are because we're able to push more throughput, that the r-amp pacing is no longer the bottleneck, flushing throughput is. I want to try more experiments with pacing according to the _reference_ r-amp, and with larger total write volumes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316#-:-NOAnmH5BE0zvpXCraLr:b8u2glq)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @bananabrick, @RaduBerinde, and @sumeerbhola)

___
*[`-- commits` line 51 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NNrp7SC5npUUzde1oMc):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> Is there pacing to prevent the LSM from getting inverted?

These numbers were collected with a pacer that strives to keep r-amp ≤ 10. I suppose that's still more aggressive than is typical in a steady state. I'll try again this time pacing by the reference workload's r-amp.

> What are the steps to reproduce this?

1. Follow the instructions in [this confluence doc](https://cockroachlabs.atlassian.net/wiki/spaces/STOR/pages/2861105466/Compaction+benchmarking#Precollected-workloads), using the snapshot `7817513537632901661` to mount a volume containing the workload to your gceworker.
2. Check out [jbowens/pebble:boundary-alignment-test](https://github.com/jbowens/pebble/tree/boundary-alignment-test) and `go install ./cmd/pebble`.
3. Run `pebble bench replay -v "/mnt/disks/$DISK_NAME/store_1/20230117212340" --name kv0/20gb --count 6 --options "[Options] max_concurrent_compactions=5" --max-writes 20480 > with-alignment-20gb.txt`

You can build and run `cmd/pebble` without these commits to get numbers for master and use `benchstat` to compare results.

> My understanding of that calculation is that it is assuming the same target file size across levels. Are we doubling the file size in these experiments, like we do in CockroachDB? If we have a data size fanout of 6, and are compacting a F byte file from the higher level that roughly overlaps with 6F bytes at the lower level, and there are 2F sized files at the lower level, then the wastage is 2/(6+1) = 28.5%.

Yeah, we're doubling file size each level. What's a "data size fanout?" I'm not convinced I'm thinking about this right, but my thinking was:  Level L has N bytes and files of target size F, so level L+1 has 10N bytes and files of 2F size. If keys are randomly distributed and equally-sized, then level L+1 should have 10x as many bytes within the bounds of a file in L. Those 10x bytes are distributed across files of double the size, so there should be ~5 overlapping files in level L+1 if perfectly aligned. Since before the heuristic, they were almost never aligned, there's an expect overlap of 6 files.
</blockquote></details>

Another factor here might be Raft log. Although the kv0 user writes are randomly distributed in the user keyspace, the raft log writes are not distributed. I think workloads like the raft log (queue-like, or ephemeral data) benefit more from this heuristic. If a higher-level files contain a group of dense writes relative to the existing data, those files are expected to have relatively little overlap with the next level's files. The lower overlap causes higher wastage.


<!-- Sent from Reviewable.io -->

2023-02-13 18:19 UTC, sumeerbhola reviewed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @bananabrick, @jbowens, and @RaduBerinde)

___
*[`-- commits` line 51 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NNrp7SC5npUUzde1oMc):*

> What's a "data size fanout?"

I'm speculating that when they say "average compaction fan-out is about 6" they mean the volume of the data in Li+1 that precisely overlaps with the file in Li that is being compacted down. There are 2 factor on why this is not 10, (a) the kMinOverlapping ratio, (b) the smoothed level multiplier. (b) we can quantify:

We pick the number of open levels L, to be the smallest L such that, 10^L >= B_6/Max_base, where B_6 is the current bytes in L6 (I am ignoring the 90% of the total bytes in the LSM logic that we apply) and Max_base is the maximum bytes configured for L_base (typically 64MB for CockroachDB).

Once we have chosen L, we compute x^L = B_6/Max_base, where x becomes the smoothed-level-multiplier.

Say the mean size that caused us to open a particular level to become Lbase was Max_base/2. That is
10^L = B_6/(Max_base/2). Then we get x^L = (10^L)/2.

For L = 2: x^2 = 100/2, x = 7.07
L=3: x^3 = 500, x = 7.93
L=4: x^4 = 5000, x = 8.41
With 20GB in the LSM, I suppose we are in the L=4 case. So assuming just this (b) effect, we get 2/(8.41+1) = 21% wastage.

This doesn't explain why the benefit is getting better with a larger LSM. With this model there is less wastage with a larger LSM.
___
*[`compaction.go` line 139 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOAiJqoAJOE3liom_iF:-NOAiJqoAJOE3liom_iG:b-16rpi0) ([raw file](https://github.com/cockroachdb/pebble/blob/9b8e2fa39a9a09ab7021d50f9a51502aa50e517e/compaction.go#L139)):*
> ```Go
> // fileSizeSplitter is a compactionOutputSplitter that enforces target file
> // sizes. This splitter splits to a new output file when the estimated file size
> // is 1/2x-2x the target file size. If there are overlapping grandparent files,
> ```

nit: I find it easier to parse 0.5x-2x


<!-- Sent from Reviewable.io -->

2023-02-13 20:26 UTC, sumeerbhola requested changes
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316)* status: 2 of 6 files reviewed, 7 unresolved discussions (waiting on @bananabrick, @jbowens, and @RaduBerinde)

___
*[`compaction.go` line 204 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOBPDr7-BkYfg-QpA8C:-NOBPDr7-BkYfg-QpA8D:b-v4bcvu) ([raw file](https://github.com/cockroachdb/pebble/blob/9b8e2fa39a9a09ab7021d50f9a51502aa50e517e/compaction.go#L204)):*
> ```Go
> 	f.atGrandparentBoundary = true
> 	f.boundariesObserved++
> 	f.nextGrandparent = f.grandparents.Next()
> ```

Is this Next aware of the key span of this compaction or can also step to a file that is completely outside the keyspan? Just out of curiosity, since there is logic in `shouldSplitBefore` that is sensitive to `nextGrandparent` being nil.
___
*[`compaction.go` line 216 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOBNLLd6as6q5L7kVm0:-NOBNLLd6as6q5L7kVm1:bmsxgf0) ([raw file](https://github.com/cockroachdb/pebble/blob/9b8e2fa39a9a09ab7021d50f9a51502aa50e517e/compaction.go#L216)):*
> ```Go
> 	// If the key is a range tombstone, the EstimatedSize won't grow rightaway
> 	// when a range tombstone is added to the fragmenter. It's better to make a
> 	// sequence of range tombstones visible to the fragmenter.
> ```

But we don't know whether this sequence of range tombstones will all have the same start key, yes?
So we could get a sequence of tombstones [f,g), [g,h), [h,i) and then a point key and even though we ought to have split before f we would not? If yes, there is no need to change the code since range tombstones are rare, but a code comment would help.
___
*[`compaction.go` line 219 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NNrnqli6nLt7QzWvVWa:-NOBOOhHBkt8rUuqAFzF:b-4q89to) ([raw file](https://github.com/cockroachdb/pebble/blob/9b8e2fa39a9a09ab7021d50f9a51502aa50e517e/compaction.go#L219)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

The omission of range keys in this existing code seems suspect to me.
</blockquote></details>

Can you create an issue to track this suspicion?
___
*[`compaction.go` line 236 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOBOlc9DtFayzQEDqgm:-NOBOlc9DtFayzQEDqgn:bkfm9r6) ([raw file](https://github.com/cockroachdb/pebble/blob/9b8e2fa39a9a09ab7021d50f9a51502aa50e517e/compaction.go#L236)):*
> ```Go
> 		// If there are no more overlapping grandparents, optimize for the
> 		// target file size and split as soon as we hit the target file size.
> 		if estSize >= f.targetFileSize {
> ```

Why does it matter whether there are no more grandparents or not? Say the last grandparent in the grandparent level is [h,k). My understanding is that we may have reached h. So we would want to split now.
Oh, maybe this is the fallback case when there haven't been grandparents for a while and we are now falling back to splitting purely based on file size. So should this be `f.nextGrandparent == nil && !atGrandparentBoundary`?
___
*[`compaction.go` line 255 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOBRPY483LSVK9jT8Ba:-NOBRPY483LSVK9jT8Bb:b-h00c20) ([raw file](https://github.com/cockroachdb/pebble/blob/9b8e2fa39a9a09ab7021d50f9a51502aa50e517e/compaction.go#L255)):*
> ```Go
> 		// split aligned with a grandparent. If this is the first grandparent
> 		// boundary observed, we split immediately (we're already at ≥50% the
> 		// target file size). Otherwise, each overlapping grandparent we've
> ```

Is `boundariesObserved` lower bounded by 1? So `pctOfTargetSize >= 55`.
So we will split at 55%?


<!-- Sent from Reviewable.io -->

2023-02-13 23:12 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @bananabrick, @jbowens, and @RaduBerinde)

___
*[`compaction.go` line 213 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOBzrNiCpEgrtKZWh3C:-NOBzrNj-KyQJVOg5QmK:b864xq9) ([raw file](https://github.com/cockroachdb/pebble/blob/9b8e2fa39a9a09ab7021d50f9a51502aa50e517e/compaction.go#L213)):*
> ```Go
> func (f *fileSizeSplitter) shouldSplitBefore(key *InternalKey, tw *sstable.Writer) maybeSplit {
> 	atGrandparentBoundary := f.atGrandparentBoundary
> 	f.atGrandparentBoundary = false
> ```

This resetting to false is a bit subtle in terms of composability with a splitter that will use the decision from this splitter with potentially some delay. The existing `fileSizeSplitter` would keep reasserting `splitNow`, which we no longer do.

In the common case the previous key will be a different user key. What happens in the uncommon case when it isn't: we have already written this user key to the current file, so the grandparent who we are trying to split before is already unavoidably caught up in the future compaction of the current file. So we may as well go on with this file until the start of the next grandparent. Which is what this code is doing. But it could use some code comments explaining this.

Should we also consider end keys of grandparent given that we have immediate successor? If we have grandparents [a,b), [c,d) and [k,l) and we could not split at c because the current sst was too small, we could attempt to split again at or after d, and before k. I suppose the only thing that improves is fewer output files hitting the 2*targetSize, so probably not worth the extra code complexity.
___
*[`compaction.go` line 263 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOC2-si9fk_ocWkgrET:-NOC2-si9fk_ocWkgrEU:bnjyrsb) ([raw file](https://github.com/cockroachdb/pebble/blob/9b8e2fa39a9a09ab7021d50f9a51502aa50e517e/compaction.go#L263)):*
> ```Go
> 		// principled formulation that can either further reduce w-amp or
> 		// produce files closer to the target file size?
> 		pctOfTargetSize := 50 + 5*minUint64(f.boundariesObserved, 8)
> ```

so the max is 50+5*8 = 90%? I was expecting 200%.


<!-- Sent from Reviewable.io -->

2023-02-14 00:31 UTC, jbowens reviewed
Here are two more runs (10GB and 20GB), this time using the reference read-amp pacer. This pacer is more aggressive because it keeps the read amp level with the read amp when the workload was collected. With this pacer, we see the write-amp benefit reduce with the higher write volume. I think the `fixed-ramp=10` pacer was letting more of a compaction backlog to accumulate.

With `--options "[Options] max_concurrent_compactions=5" --max-writes 10240 --pacer=reference-ramp`:
```
                                          │ d62bba1-10gb-reframp.txt │     19381f17e-10gb-reframp.txt     │
                                          │       compactions        │ compactions  vs base               │
BenchmarkReplay/kv0/10gb/CompactionCounts                3.801k ± 0%   3.227k ± 5%  -15.10% (p=0.002 n=6)

                                          │ d62bba1-10gb-reframp.txt │     19381f17e-10gb-reframp.txt     │
                                          │         default          │   default    vs base               │
BenchmarkReplay/kv0/10gb/CompactionCounts                3.228k ± 1%   2.845k ± 6%  -11.87% (p=0.002 n=6)

                                               │ d62bba1-10gb-reframp.txt │       19381f17e-10gb-reframp.txt       │
                                               │          bytes           │     bytes      vs base                 │
BenchmarkReplay/kv0/10gb/DatabaseSize/mean                 2.870Gi ± 1%     3.041Gi ±  2%   +5.96% (p=0.002 n=6)
BenchmarkReplay/kv0/10gb/DatabaseSize/max                  5.199Gi ± 2%     5.023Gi ±  1%   -3.40% (p=0.002 n=6)
BenchmarkReplay/kv0/10gb/EstimatedDebt/mean                2.172Gi ± 4%     2.018Gi ± 14%   -7.07% (p=0.015 n=6)
BenchmarkReplay/kv0/10gb/EstimatedDebt/max                 4.002Gi ± 7%     3.353Gi ± 16%  -16.22% (p=0.004 n=6)

                                           │ d62bba1-10gb-reframp.txt │     19381f17e-10gb-reframp.txt     │
                                           │          sec/op          │   sec/op     vs base               │
BenchmarkReplay/kv0/10gb/DurationWorkload               229.5 ±  2%     182.2 ±  8%  -20.61% (p=0.002 n=6)
BenchmarkReplay/kv0/10gb/DurationQuiescing             17.018 ± 24%     9.516 ± 10%  -44.08% (p=0.002 n=6)

                                      │ d62bba1-10gb-reframp.txt │    19381f17e-10gb-reframp.txt     │
                                      │          files           │   files     vs base               │
BenchmarkReplay/kv0/10gb/ReadAmp/mean                7.113 ±  4%   6.828 ± 9%        ~ (p=0.132 n=6)
BenchmarkReplay/kv0/10gb/ReadAmp/max                 10.00 ± 10%   12.00 ± 8%  +20.00% (p=0.002 n=6)

                                    │ d62bba1-10gb-reframp.txt │     19381f17e-10gb-reframp.txt      │
                                    │           B/s            │     B/s       vs base               │
BenchmarkReplay/kv0/10gb/Throughput               39.67Mi ± 2%   51.01Mi ± 7%  +28.59% (p=0.002 n=6)

                                  │ d62bba1-10gb-reframp.txt │    19381f17e-10gb-reframp.txt     │
                                  │           wamp           │    wamp     vs base               │
BenchmarkReplay/kv0/10gb/WriteAmp                 9.228 ± 1%   7.548 ± 2%  -18.20% (p=0.002 n=6)
```


With `--options "[Options] max_concurrent_compactions=5" --max-writes 20480 --pacer=reference-ramp`:

```
                                          │ d62bba1-20gb-reframp-2.txt │     19381f17-20gb-reframp.txt     │
                                          │        compactions         │ compactions  vs base              │
BenchmarkReplay/kv0/20gb/CompactionCounts                  8.337k ± 2%   8.682k ± 2%  +4.14% (p=0.002 n=6)

                                          │ d62bba1-20gb-reframp-2.txt │     19381f17-20gb-reframp.txt      │
                                          │          default           │   default    vs base               │
BenchmarkReplay/kv0/20gb/CompactionCounts                  6.777k ± 3%   7.705k ± 3%  +13.68% (p=0.002 n=6)

                                               │ d62bba1-20gb-reframp-2.txt │       19381f17-20gb-reframp.txt       │
                                               │           bytes            │    bytes      vs base                 │
BenchmarkReplay/kv0/20gb/DatabaseSize/mean                  5.175Gi ±  1%     5.123Gi ± 1%   -1.00% (p=0.002 n=6)
BenchmarkReplay/kv0/20gb/DatabaseSize/max                   9.627Gi ±  1%     9.411Gi ± 0%   -2.25% (p=0.002 n=6)
BenchmarkReplay/kv0/20gb/EstimatedDebt/mean                 2.920Gi ± 11%     1.769Gi ± 4%  -39.42% (p=0.002 n=6)
BenchmarkReplay/kv0/20gb/EstimatedDebt/max                  6.518Gi ± 20%     3.466Gi ± 5%  -46.82% (p=0.002 n=6)

                                           │ d62bba1-20gb-reframp-2.txt │       19381f17-20gb-reframp.txt        │
                                           │           sec/op           │   sec/op     vs base                   │
BenchmarkReplay/kv0/20gb/DurationWorkload                   510.6 ±  4%   489.2 ±  6%   -4.19% (p=0.041 n=6)
BenchmarkReplay/kv0/20gb/DurationQuiescing                 23.775 ± 22%   9.403 ± 17%  -60.45% (p=0.002 n=6)

                                      │ d62bba1-20gb-reframp-2.txt │     19381f17-20gb-reframp.txt      │
                                      │           files            │    files     vs base               │
BenchmarkReplay/kv0/20gb/ReadAmp/mean                  7.019 ±  8%   5.381 ±  2%  -23.34% (p=0.002 n=6)
BenchmarkReplay/kv0/20gb/ReadAmp/max                  11.000 ± 18%   8.000 ± 12%  -27.27% (p=0.002 n=6)

                                    │ d62bba1-20gb-reframp-2.txt │     19381f17-20gb-reframp.txt      │
                                    │            B/s             │     B/s       vs base              │
BenchmarkReplay/kv0/20gb/Throughput                 36.64Mi ± 4%   39.22Mi ± 5%  +7.05% (p=0.009 n=6)

                                  │ d62bba1-20gb-reframp-2.txt │     19381f17-20gb-reframp.txt     │
                                  │            wamp            │    wamp     vs base               │
BenchmarkReplay/kv0/20gb/WriteAmp                  10.102 ± 2%   8.933 ± 1%  -11.57% (p=0.002 n=6)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316#-:-NOC8xA67qbZU749L_M-:be2uome)* status: 2 of 6 files reviewed, 8 unresolved discussions (waiting on @bananabrick, @RaduBerinde, and @sumeerbhola)

___
*[`-- commits` line 51 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NNrp7SC5npUUzde1oMc):*
Ahh, I forgot about the smoothed level multiplier.

> the kMinOverlapping ratio

I don't have a great intuition for how the `kMinOverlappingRatio` affects the data distribution.
___
*[`compaction.go` line 139 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOAiJqoAJOE3liom_iF:-NOC0yIM9pMnNvYLcwUh:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/9b8e2fa39a9a09ab7021d50f9a51502aa50e517e/compaction.go#L139)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: I find it easier to parse 0.5x-2x
</blockquote></details>

Done.
___
*[`compaction.go` line 204 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOBPDr7-BkYfg-QpA8C:-NOC15rz9FkgvWfxNfee:b-qiyu3s) ([raw file](https://github.com/cockroachdb/pebble/blob/9b8e2fa39a9a09ab7021d50f9a51502aa50e517e/compaction.go#L204)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this Next aware of the key span of this compaction or can also step to a file that is completely outside the keyspan? Just out of curiosity, since there is logic in `shouldSplitBefore` that is sensitive to `nextGrandparent` being nil.
</blockquote></details>

Yeah, it is bounded because it's constructed through `Overlaps`. Added a comment.
___
*[`compaction.go` line 213 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOBzrNiCpEgrtKZWh3C:-NOCHvlD85l00YPZbgiz:buq5nzp) ([raw file](https://github.com/cockroachdb/ [...]

2023-02-14 17:03 UTC, jbowens reviewed
More numbers

With `--options '[Options] max_concurrent_compactions=5' --max-writes 40960 --pacer=reference-ramp`:
```
                                          │ 5d8daed0ac-40gb-reframp.txt │    739646eb1b-40gb-reframp.txt     │
                                          │         compactions         │ compactions   vs base              │
BenchmarkReplay/kv0/40gb/CompactionCounts                   17.46k ± 2%   18.99k ± 11%  +8.74% (p=0.002 n=6)

                                          │ 5d8daed0ac-40gb-reframp.txt │     739646eb1b-40gb-reframp.txt     │
                                          │           default           │   default     vs base               │
BenchmarkReplay/kv0/40gb/CompactionCounts                   12.66k ± 1%   15.44k ± 15%  +22.03% (p=0.002 n=6)

                                               │ 5d8daed0ac-40gb-reframp.txt │      739646eb1b-40gb-reframp.txt       │
                                               │            bytes            │     bytes      vs base                 │
BenchmarkReplay/kv0/40gb/DatabaseSize/mean                   9.877Gi ±  1%     9.639Gi ±  2%   -2.41% (p=0.002 n=6)
BenchmarkReplay/kv0/40gb/DatabaseSize/max                    19.06Gi ±  2%     18.41Gi ±  1%   -3.43% (p=0.002 n=6)
BenchmarkReplay/kv0/40gb/EstimatedDebt/mean                  7.335Gi ±  3%     3.732Gi ± 42%  -49.12% (p=0.002 n=6)
BenchmarkReplay/kv0/40gb/EstimatedDebt/max                  15.795Gi ± 10%     8.434Gi ± 46%  -46.60% (p=0.002 n=6)

                                           │ 5d8daed0ac-40gb-reframp.txt │    739646eb1b-40gb-reframp.txt     │
                                           │           sec/op            │   sec/op     vs base               │
BenchmarkReplay/kv0/40gb/DurationWorkload                   1851.2 ±  9%   924.8 ± 14%  -50.05% (p=0.002 n=6)
BenchmarkReplay/kv0/40gb/DurationQuiescing                  104.68 ± 54%   18.48 ± 43%  -82.34% (p=0.002 n=6)

                                      │ 5d8daed0ac-40gb-reframp.txt │    739646eb1b-40gb-reframp.txt     │
                                      │            files            │    files     vs base               │
BenchmarkReplay/kv0/40gb/ReadAmp/mean                  10.403 ±  4%   6.368 ± 14%  -38.79% (p=0.002 n=6)
BenchmarkReplay/kv0/40gb/ReadAmp/max                   18.500 ± 19%   9.000 ± 22%  -51.35% (p=0.002 n=6)

                                    │ 5d8daed0ac-40gb-reframp.txt │      739646eb1b-40gb-reframp.txt      │
                                    │             B/s             │      B/s       vs base                │
BenchmarkReplay/kv0/40gb/Throughput                 20.90Mi ± 13%   43.38Mi ± 11%  +107.52% (p=0.002 n=6)

                                  │ 5d8daed0ac-40gb-reframp.txt │    739646eb1b-40gb-reframp.txt    │
                                  │            wamp             │    wamp     vs base               │
BenchmarkReplay/kv0/40gb/WriteAmp                   10.274 ± 1%   9.063 ± 6%  -11.78% (p=0.002 n=6)

                                     │ 5d8daed0ac-40gb-reframp.txt │   739646eb1b-40gb-reframp.txt    │
                                     │           stalls            │  stalls    vs base               │
BenchmarkReplay/kv0/40gb/WriteStalls                  485.50 ± 32%   10.00 ± ?  -97.94% (p=0.002 n=6)
```

With `--options '[Options] max_concurrent_compactions=5' --max-writes 40960 --pacer=fixed-ramp=10`:
```
                                               │ 5d8daed0ac-40gb-fixedramp10.txt │    739646eb1b-40gb-fixedramp10.txt    │
                                               │              bytes              │    bytes      vs base                 │
BenchmarkReplay/kv0/40gb/DatabaseSize/mean                       10.015Gi ± 1%     9.644Gi ± 1%   -3.71% (p=0.002 n=6)
BenchmarkReplay/kv0/40gb/DatabaseSize/max                         18.57Gi ± 0%     18.47Gi ± 0%   -0.53% (p=0.002 n=6)
BenchmarkReplay/kv0/40gb/EstimatedDebt/mean                       6.528Gi ± 2%     5.048Gi ± 6%  -22.68% (p=0.002 n=6)
BenchmarkReplay/kv0/40gb/EstimatedDebt/max                        12.00Gi ± 2%     10.99Gi ± 2%   -8.40% (p=0.002 n=6)

                                           │ 5d8daed0ac-40gb-fixedramp10.txt │  739646eb1b-40gb-fixedramp10.txt  │
                                           │             sec/op              │   sec/op    vs base               │
BenchmarkReplay/kv0/40gb/DurationWorkload                        1013.0 ± 2%   845.5 ± 1%  -16.54% (p=0.002 n=6)
BenchmarkReplay/kv0/40gb/DurationQuiescing                        39.88 ± 7%   23.83 ± 6%  -40.25% (p=0.002 n=6)

                                      │ 5d8daed0ac-40gb-fixedramp10.txt │  739646eb1b-40gb-fixedramp10.txt  │
                                      │              files              │   files     vs base               │
BenchmarkReplay/kv0/40gb/ReadAmp/mean                        9.270 ± 2%   7.372 ± 3%  -20.48% (p=0.002 n=6)
BenchmarkReplay/kv0/40gb/ReadAmp/max                         12.00 ± 0%   11.00 ± 9%   -8.33% (p=0.015 n=6)

                                    │ 5d8daed0ac-40gb-fixedramp10.txt │   739646eb1b-40gb-fixedramp10.txt   │
                                    │               B/s               │     B/s       vs base               │
BenchmarkReplay/kv0/40gb/Throughput                      38.96Mi ± 2%   47.09Mi ± 1%  +20.86% (p=0.002 n=6)

                                  │ 5d8daed0ac-40gb-fixedramp10.txt │  739646eb1b-40gb-fixedramp10.txt  │
                                  │              wamp               │    wamp     vs base               │
BenchmarkReplay/kv0/40gb/WriteAmp                       10.553 ± 1%   8.661 ± 1%  -17.93% (p=0.002 n=6)
```

The 40gb w/ reference-ramp pacing numbers are a little crazy. Throughput is more than double, although the write-amp reduction is ~11%. Is this change improving compaction parallelism out of L0 or out of LBase?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316#-:-NOFpg1r8zm8gk5MZOXe:bukgixz)* status: 1 of 6 files reviewed, 8 unresolved discussions (waiting on @bananabrick, @RaduBerinde, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-02-14 21:35 UTC, sumeerbhola reviewed
Just trying to understand the results.

Why are there 2 rows for `BenchmarkReplay/kv0/20gb/CompactionCounts` in some of these runs?
And do you know why the throughput increase is so much better than the decrease in write-amp?
```
BenchmarkReplay/kv0/40gb/Throughput                 20.90Mi ± 13%   43.38Mi ± 11%  +107.52% (p=0.002 n=6)
```
Is it the fewer write stalls, and less pacing to keep the read-amp in check? The latter will happen with admission control too, so this is quite fantastic!

Ah, just noticed your last comment about compaction parallelism. So the throughput includes compaction writes, or is it only user facing writes?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316#-:-NOGpVaH4-7p2SOlfrEM:b-fccqaq)* status: 1 of 6 files reviewed, 8 unresolved discussions (waiting on @bananabrick and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2023-02-14 21:52 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316#-:-NOGuc6B65djUzxOnWH7:bg7igkv)* status: 5 of 6 files reviewed, 9 unresolved discussions (waiting on @bananabrick, @jbowens, and @RaduBerinde)

___
*[`-- commits` line 51 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NNrp7SC5npUUzde1oMc):*
> I don't have a great intuition for how the kMinOverlappingRatio affects the data distribution.

Neither do I. But it must be reducing the byte ratio from what the model for (b) predicts. Pebble logs often show compactions where the byte ratios are small.
___
*[`compaction.go` line 213 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOBzrNiCpEgrtKZWh3C:-NOGsMAv4ZPvOwuw2HlG:bwfe8tu) ([raw file](https://github.com/cockroachdb/pebble/blob/9b8e2fa39a9a09ab7021d50f9a51502aa50e517e/compaction.go#L213)):*
> Maybe splitting immediately after end keys would improve the likelihood of move compactions? 

Good point
___
*[`compaction.go` line 263 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOC2-si9fk_ocWkgrET:-NOGt38O8ppfy1MwF0DR:b-q32h51) ([raw file](https://github.com/cockroachdb/pebble/blob/9b8e2fa39a9a09ab7021d50f9a51502aa50e517e/compaction.go#L263)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This is the maximum lower bound. We start off willing to split at the first grandparent between [50%,200%]. As we observe grandparents, the 50% lower bound lifts up 5% at a time until a maximum of 90%. Renamed this to `minimumPctOfTargetSize`
</blockquote></details>

Ah yes.
___
*[`testdata/manual_compaction_file_boundaries` line 298 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOGu6pV1WsPFWsBLOg-:-NOGu6pV1WsPFWsBLOg0:b-unoa79) ([raw file](https://github.com/cockroachdb/pebble/blob/739646eb1b6c53921718b27750faab707ff2c03b/testdata/manual_compaction_file_boundaries#L298)):*
> ```
>   000098:[f@1#238,1-fz@1#264,1]: 6602 bytes (6.4 K)
>   000099:[g@1#265,1-gz@1#291,1]: 6602 bytes (6.4 K)
>   000100:[h@1#292,1-hz@1#318,1]: 6602 bytes (6.4 K)
> ```

Nice test.
Is it possible to test the boundaries of the 50% to 200% size logic, and the `minimumPctOfTargetSize` adjustment?


<!-- Sent from Reviewable.io -->

2023-02-15 01:29 UTC, jbowens reviewed
> Why are there 2 rows for BenchmarkReplay/kv0/20gb/CompactionCounts in some of these runs?

It's a little vague in the output, but the first one is the total count of compactions and the second is the count of only default auto compactions (as opposed to move, elision, etc).

> Is it the fewer write stalls, and less pacing to keep the read-amp in check?

I think so, although I suspect it's being exaggerated by the pacing mechanism. The reference r-amp pacing might be too sensitive to noise. If non-determinism causes the replay to have just 1 more r-amp at the same point in the workload, the pacer will wait for it reduce.  I think this might introduce excessive pacing. I'm thinking we should probably tolerate a small delta (maybe even just +1) over the reference r-amp. 

> is it only user facing writes?

It's only user-facing writes. I was thinking the compaction parallelism might be helping keep read-amp in check, which then permits the pacer to push more user writes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316#-:-NOHeLFPDoMP79eOb4kP:bw17m5g)* status: 5 of 6 files reviewed, 9 unresolved discussions (waiting on @bananabrick, @RaduBerinde, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-02-15 16:23 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2316)* status: 5 of 6 files reviewed, 9 unresolved discussions (waiting on @bananabrick, @RaduBerinde, and @sumeerbhola)

___
*[`testdata/manual_compaction_file_boundaries` line 298 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2316#-NOGu6pV1WsPFWsBLOg-:-NOKsicy7rMDzMTpxEsL:bbrnptu) ([raw file](https://github.com/cockroachdb/pebble/blob/739646eb1b6c53921718b27750faab707ff2c03b/testdata/manual_compaction_file_boundaries#L298)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Nice test.
Is it possible to test the boundaries of the 50% to 200% size logic, and the `minimumPctOfTargetSize` adjustment?
</blockquote></details>

Yeah, added a couple more tests to exercise these behaviors.


<!-- Sent from Reviewable.io -->

2023-02-15 16:28 UTC, jbowens commented
TFTR!

2023-02-15 16:39 UTC, merged