.*: virtual sstable FileMetadata changes
cockroachdb/pebble pull request #2352
Opened 2023-02-21 20:12 UTC by bananabrick

This pr introduces the FileMetadata changes which will be required to make further virtual sstable changes.

This pr doesn't deal with persisting of the FileMetadata to disk through the version edits.

2023-02-21 20:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2352)
<!-- Reviewable:end -->

2023-02-21 20:19 UTC, bananabrick reviewed
@sumeerbhola This doesn't have the decoding/encoding/version edit changes. I put out this pr first, because it should be non-controversial, and future changes can be concurrently sequenced on top of it.

Future changes which can be built on top of this include:
1. version edit changes + decoding/encoding.
2. Iterator + table cache changes.
3. asynchronous stats collection changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NOpaw3552b9ZkdBOMiN:b-ubo8w9)* status: 0 of 17 files reviewed, 1 unresolved discussion

___
*[`internal/manifest/version.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOpbAKE4yKhVdz73_nP:-NOpbAKE4yKhVdz73_nQ:br92eio) ([raw file](https://github.com/cockroachdb/pebble/blob/33d1932f5fd53a8b172c015069f27dbdc40c07fd/internal/manifest/version.go#L162)):*
> ```Go
> // sstable.
> type VirtualState struct {
> 	Parent PhysicalFileMeta
> ```

@itsbilal Going to assume for now that we're keeping around the parent files metadata here, which would mean that we definitely need the version edit changes to support manifest replay.

Another reason we need the parent file's metadata pointer in the virtual sstable meta is to support refcounting. We need to access the parent file metadata's `atomic.refs` count, and we also need to access the parent file metadata's `atomic.latestRefs`. An additional reason would be that we also need to implement a compaction picking heuristic to minimize space amp due to virtual sstables, and that would also need to access the parent file's metadata.


<!-- Sent from Reviewable.io -->

2023-02-21 20:28 UTC, bananabrick commented
Just copied code over from https://github.com/cockroachdb/pebble/pull/2288. Will take a more careful look to make sure that I didn't miss some change.

2023-02-22 00:32 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: 0 of 17 files reviewed, 3 unresolved discussions

___
*[`checkpoint.go` line 260 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOq-9kz3VWsptOmij5x:-NOq-9kz3VWsptOmij5y:binf9mi) ([raw file](https://github.com/cockroachdb/pebble/blob/829216b844d5d4d59c32af845ee1615eb0786052/checkpoint.go#L260)):*
> ```Go
> 
> 	var excludedFiles map[deletedFileEntry]*fileMetadata
> 	dedup := make(map[base.FileNum]struct{})
> ```

This pattern to iterate over the file metadata and deduplicating the parent sstables of a virtual sstable is coming up all over the place, but idk if there's a clean way of avoiding it.
___
*[`internal/manifest/version.go` line 169 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOqWROy9MMGdSGP0_0c:-NOqWROy9MMGdSGP0_0d:bkbmfb0) ([raw file](https://github.com/cockroachdb/pebble/blob/7f5ac717a6a190091dd024c4e07df7b956a4da7e/internal/manifest/version.go#L169)):*
> ```Go
> 
> // FileMetadata holds the metadata for an on-disk or virtual sstable.
> type FileMetadata struct {
> ```

Haven't added the state needed for the space amplification compaction picking heuristic as that would be very hard to test carefully without the rest of the virtual sstable changes.


<!-- Sent from Reviewable.io -->

2023-02-22 03:23 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @RaduBerinde)

___
*[`version_set_test.go` line 116 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOr88OoA4VkA8UNyfOh:-NOr88OoA4VkA8UNyfOi:bdzuq4c) ([raw file](https://github.com/cockroachdb/pebble/blob/f1717dc93d6325ccd5858fdc23ee0ec6cb68b820/version_set_test.go#L116)):*
> ```Go
> 			return d.getInProgressCompactionInfoLocked(nil)
> 		})
> 		d.updateReadStateLocked(nil)
> ```

I find it odd that we don't call updateReadStateLocked from within `logAndApply` and instead rely on the caller to make sure that the read state is updated.


<!-- Sent from Reviewable.io -->

2023-02-22 15:32 UTC, sumeerbhola reviewed
> Will take a more careful look to make sure that I didn't miss some change.

is this ready for a look?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NOtcrXKDID4HWwMVcln:b-tnc22e)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @bananabrick, @itsbilal, and @RaduBerinde)

___
*[`internal/manifest/version.go` line 169 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOqWROy9MMGdSGP0_0c:-NOtcaVM4UZlQmOtz2dU:b-u33etv) ([raw file](https://github.com/cockroachdb/pebble/blob/7f5ac717a6a190091dd024c4e07df7b956a4da7e/internal/manifest/version.go#L169)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Haven't added the state needed for the space amplification compaction picking heuristic as that would be very hard to test carefully without the rest of the virtual sstable changes.
</blockquote></details>

Please add it. It's fine if it can't be tested yet, which can be left as a TODO in a test file. I'd really like to have the full "data-structure" part of virtual ssts in this PR.


<!-- Sent from Reviewable.io -->

2023-02-22 16:39 UTC, itsbilal commented
I made this point in a meeting with Arjun and I'll repeat it here so @sumeerbhola hears it too, but I'd support a FileMetadata that only has one additional field for virtual sstables, i.e. `PhysicalFileNum`. We really don't need any other fields from the physical file metadata, and keeping the physical meta around in the manifest (and adding all the logic for "unlinked" files in the version edit, etc., and changing the VersionEdit format) seems pretty unnecessary all for a marginal increase in debuggability. Also increases risk for something that is likely going into 23.1. Unless the manifest has rotated twice since the physical sst was created, we can always look back at the AddedFiles in the version edit for the physical SST creation to get the PhysicalMeta we are interested in.

I also worry about the space-amp increase in storing the smallest/largest point/range keys extra times for a FileMetadata that is really not being used except for the FileNum. Those fields take up much more space than a single uint64 for the physical file num (which will only be present if the virtual sst has a tag for virtual sst), and could only lead to more manifest rotations.

The only thing that becomes slightly harder with only storing a file num, is ref counting, but we can restructure ref counting to operate away from the FileMetadata and in some map[PhysicalFileNum] and that solves that problem pretty easily. It's also very easy to detect obsolete files at Open() time; we can just track which PhysicalFileNums are on disk but not referenced by any virtual sstables. My prototype actually did that change.

One more point is that `PhysicalMeta` will probably not exist or will be very Provider-managed for virtual sstables backed by a disaggregated shared foreign SST anyway.





<!-- Sent from Reviewable.io -->

2023-02-22 16:45 UTC, sumeerbhola requested changes
> Reviewed 1 of 17 files at r1, 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: 2 of 18 files reviewed, 15 unresolved discussions (waiting on @bananabrick, @itsbilal, and @RaduBerinde)

___
*[`version_set.go` line 44 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOu-Hjc3Jh7_KXYZhEW:-NOu-Hjc3Jh7_KXYZhEX:b-z7q1a9) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/version_set.go#L44)):*
> ```Go
> // like it sounds: a delta from the previous version. Version edits are logged
> // to the MANIFEST file, which is replayed at startup.
> type versionSet struct {
> ```

where is `backingPhysicalTables map[FileNum]physicalMeta` that is in the other PR?
___
*[`internal/manifest/btree.go` line 210 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtq01M9Yg5g7pXvugV:-NOtq01M9Yg5g7pXvugW:bs5bohw) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/btree.go#L210)):*
> ```Go
> 	if contentsToo {
> 		for _, f := range n.items[:n.count] {
> 			if f.Unref() == 0 {
> ```

I think we need a signature like
```
// INVARIANT: additionalObsolete != nil => refCount == 0
Unref() (refCount int32, additionalObsolete *FileMetadata)
```
if we are ref counting virtual ssts too.

If not, we need something like the following where `obsolete` may be the `FileMetadata we called unref on (for a physical sst) or the underlying physical sst (if we called on a virtual sst).
```
// INVARIANT: obsolete != nil => refCount == 0
Unref() (refCount int32, obsolete *FileMetadata)
```
___
*[`internal/manifest/version.go` line 165 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtmbNG-uujuRX8U-Lp:-NOtmbNG-uujuRX8U-Lq:bgn038o) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L165)):*
> ```Go
> 	// ParentSSTNum is the FileNum of VirtualState.Parent. We need to store
> 	// this separately for manifest replay.
> 	ParentSSTNum base.FileNum
> ```

why duplicating the FileNum here instead of using Parent.FileNum?
___
*[`internal/manifest/version.go` line 168 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtnE-91dT0wDr5QyEX:-NOtnE-91dT0wDr5QyEY:b-hguwrn) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L168)):*
> ```Go
> }
> 
> // FileMetadata holds the metadata for an on-disk or virtual sstable.
> ```

nit: worth saying on-disk/physical since we have also defined the term physical sst above.
___
*[`internal/manifest/version.go` line 189 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtqcXrC92FJmOkoaf2:-NOtqcXrC92FJmOkoaf3:b-60qkmc) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L189)):*
> ```Go
> 		// version and decremented when the version is unreferenced. The file is
> 		// obsolete when the reference count falls to zero. The refs field is
> 		// only used for physical sstables. Virtual sstables will update their
> ```

Why only physical ssts? Don't we need a ref count for virtual ssts given that many versions can have the same virtual sst? I think they can also become zombies. We could track virtual sst zombies separately from physical sst zombies, even though some of the latter zombies will be zombies due to references from the former.

I think what you are doing here is noticing that there is no physical resource to delete when only the refs for a virtual sst drop to zero, hence why bother tracking it. I suppose that will work too, and is fine. Could you add a comment somewhere on this reasoning.
___
*[`internal/manifest/version.go` line 195 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtulQ2309IFcNh2-OB:-NOtulQ2309IFcNh2-OC:b-xi52gr) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L195)):*
> ```Go
> 		// Note that we could just turn FileMetadata.atomic.refs to a pointer
> 		// so that a virtual sstable can directly update the refs field in its
> 		// own FileMetadata. But then we'll suffer an additional allocation on
> ```

I think we should cleanly separate what is only needed for physical ssts and only for virtual ssts by having *VirtualState and *PhysicalState pointers and we should do that now. Allocations can be pooled via `sync.Pool` in the future since we know when a sst becomes obsolete. And file creation is not happening 1000s of times a second, so we can do that allocation optimization later. I'm wary of continuing down this flattening path since eventually we will unflatten due to https://github.com/cockroachdb/pebble/issues/2047, so we may as well not flatten for new stuff we are adding.
___
*[`internal/manifest/version.go` line 210 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtrP52BQ5utdlLSiA5:-NOtrP52BQ5utdlLSiA6:bhkcjkm) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L210)):*
> ```Go
> 		//
> 		// INVARIANT: latestRefs <= refs.
> 		latestRefs int32
> ```

We should state an invariant somewhere that a physical sst that has references from other virtual ssts no longer exists as a first-class citizen in any level of the latest version. Though it could be a first class citizen of a level in an older version. I was imagining latestRefs to be only for such physical ssts, since for the others it is trivially 0 or 1. Were you planning to use it in all cases?
We need a term for such physical ssts. virtualized-physical sst? I am terrible with names. Maybe backing-physical sst, since you use that term below. Is `PhysicalFileMeta` for both regular physical ssts and backing-physical ssts?
___
*[`internal/manifest/version.go` line 242 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtvoz_7jVNRUGdp1nq:-NOtvoz_7jVNRUGdp1nr:b2gt1ho) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L242)):*
> ```Go
> 	// alter point keys.
> 	// NB: these field should be set using ExtendPointKeyBounds. They are left
> 	// exported for reads as an optimization.
> ```

are all the following `InternalKeys` precise for virtual ssts?
___
*[`internal/manifest/version.go` line 264 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtwFHa2W2nDZjpH6cR:-NOtwFHa2W2nDZjpH6cS:b-cl47zn) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L264)):*
> ```Go
> 	// TODO(bananabrick): To support manifest replay for virtual sstables, we
> 	// probably need to compute virtual sstable stats asynchronously. Otherwise,
> 	// we'd have to write virtual sstable stats to the version edit.
> ```

I don't think we want to write these stats for virtual ssts to the version edit given that we don't write these for physical ssts. Is this TODO for a future PR? Is there some aspect of this stats computation that is tricky?
___
*[`internal/manifest/version.go` line 303 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtx-8y6hk0iXA5XLen:-NOtx-8y6hk0iXA5XLeo:b-jq9ley) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L303)):*
> ```Go
> 	// HasPointKeys tracks whether the table contains point keys (including
> 	// RANGEDELs). If a table contains only range deletions, HasPointsKeys is
> 	// still true.
> ```

are all the following fields precise for virtual ssts?
___
*[`internal/manifest/version.go` line 1285 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtzqrgBN7BP0xjRiHj:-NOtzqrgBN7BP0xjRiHk:b-kdxv5b) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L1285)):*
>  [...]

2023-02-22 17:18 UTC, itsbilal reviewed
> Reviewed 7 of 17 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 3 files at r4, 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: 13 of 18 files reviewed, 17 unresolved discussions (waiting on @bananabrick, @RaduBerinde, and @sumeerbhola)

___
*[`internal/manifest/version.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOpbAKE4yKhVdz73_nP:-NOu4e2P55TYilYQSr2A:beqy06c) ([raw file](https://github.com/cockroachdb/pebble/blob/33d1932f5fd53a8b172c015069f27dbdc40c07fd/internal/manifest/version.go#L162)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

@itsbilal Going to assume for now that we're keeping around the parent files metadata here, which would mean that we definitely need the version edit changes to support manifest replay.

Another reason we need the parent file's metadata pointer in the virtual sstable meta is to support refcounting. We need to access the parent file metadata's `atomic.refs` count, and we also need to access the parent file metadata's `atomic.latestRefs`. An additional reason would be that we also need to implement a compaction picking heuristic to minimize space amp due to virtual sstables, and that would also need to access the parent file's metadata.
</blockquote></details>

I'm okay with that direction if Sumeer and others are good with it, however it's a pretty critical decision that's going to inform a lot of what comes next. I just want us to carefully make that choice and to consider the alternative as well, so I left a top-level comment making the case against this approach.
___
*[`internal/manifest/version.go` line 195 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtulQ2309IFcNh2-OB:-NOu4CYw2qLIY2Om6rXs:bfos0or) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L195)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we should cleanly separate what is only needed for physical ssts and only for virtual ssts by having *VirtualState and *PhysicalState pointers and we should do that now. Allocations can be pooled via `sync.Pool` in the future since we know when a sst becomes obsolete. And file creation is not happening 1000s of times a second, so we can do that allocation optimization later. I'm wary of continuing down this flattening path since eventually we will unflatten due to https://github.com/cockroachdb/pebble/issues/2047, so we may as well not flatten for new stuff we are adding.
</blockquote></details>

I agree that we should separate VirtualState and PhysicalState, instead of keeping the refs here and not using them in virtual sstable metas. That way VirtualState can just reference a PhysicalState instead of a Physical file metadata in its entirety, and that is also more adaptable for when PhysicalState is some Provider-owned thing for disaggregated storage.
___
*[`internal/manifest/version.go` line 203 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOu5xc1EINQ1fwu5exK:-NOu5xc1EINQ1fwu5exL:b-v4y8cg) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L203)):*
> ```Go
> 		refs int32
> 
> 		// latestRefs are the references to a physical sstable in the latest
> ```

I think `versionRefs` or `virtualRefs` is a far better name for this, seeing as iterators don't increment this but versions do.
___
*[`internal/manifest/version_edit.go` line 113 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOu2UUaAFpvfgpGLBlH:-NOu2UUaAFpvfgpGLBlI:bncv7zc) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version_edit.go#L113)):*
> ```Go
> 
> // Decode decodes an edit from the specified reader.
> // TODO(bananabrick): Support decoding of virtual sstable state.
> ```

nit: empty line before todo


<!-- Sent from Reviewable.io -->

2023-02-22 18:32 UTC, bananabrick reviewed
Yea, we could move the ref counting logic to a map in the versionSet, and then only store a parent physical sst number in the virtual ssts. I don't think golang maps are safe for concurrent access even to different keys, so we'd probably need to work around that. Imo, the ref counting logic as it is right now is a lot simpler. But if we go for this, I'd want to move the ref counting logic for all cases and not just the virtual sst cases to a separate map.

> Unless the manifest has rotated twice since the physical sst was created, we can always look back at the AddedFiles in the version edit for the physical SST creation to get the PhysicalMeta we are interested in.

Why twice? Either way, it seems as if the core questions are:
1. Whether we want to store some physical state of the parent file meta in virtual ssts.
This can be avoided by using maps in the versionSet for refcounting, and only store a parent sst number. But the map would need to be safe for concurrent access to different keys, and we might see a perf hit there.

2. Whether we want the additional debuggability to determine exactly when a physical sst is no longer required by the latest version, and exactly when it transitions to zombie.
This can be partly determined just using the latest version ref counting, and I suppose if a system restarts, and the latest version has a virtual sst, then we can still determine the state the parent sst is in. We'll lose information about obsolete/zombie tables, which is fine because those would be deleted on restart anyway.

> I also worry about the space-amp increase in storing the smallest/largest point/range keys extra times for a FileMetadata that is really not being used except for the FileNum. 

I like the idea of only storing `PhysicalState` in the virtual meta, which would solve this. We'd still need the version edit changes in this case, though.

Overall, I'm good with not having those changes, because that's easier to test, but I've also implemented the changes already, so I'm also okay with keeping them.

Thoughts @sumeerbhola?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NOuFn0WARNLxBdKepm2:bobqmiu)* status: 13 of 18 files reviewed, 17 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-02-22 19:52 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: 13 of 18 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @itsbilal, and @sumeerbhola)

___
*[`checkpoint.go` line 285 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOqe5LiBqfIVQk4MLV2:-NOqe5LiBqfIVQk4MLV3:b8q33ar) ([raw file](https://github.com/cockroachdb/pebble/blob/5ceaa45f9dc31de5223598a28aaff24129738753/checkpoint.go#L285)):*
> ```Go
> 				}
> 			} else {
> 				considerFile = f
> ```

I assume that there is an invariant that the same physical SST can't appear both as a physical SST and as a parent to a virtual SST. Are we verifying that somewhere?

In any case, it would be easier here to just use `BackingPhysicalFile()` and dedup in all cases.
___
*[`internal/manifest/version.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOqdUQo5m91IZOJbPTX:-NOqdUQpDujKjShk6sLB:b-4z6v8h) ([raw file](https://github.com/cockroachdb/pebble/blob/33d1932f5fd53a8b172c015069f27dbdc40c07fd/internal/manifest/version.go#L165)):*
> ```Go
> 	// ParentSSTNum is the FileNum of VirtualState.Parent. We need to store
> 	// this separately for manifest replay.
> 	ParentSSTNum base.FileNum
> ```

Could you explain this field a little more? Its existence suggests that there are situations where this field is set but `Parent` isn't? (that aspect should be documented for `Parent`).

We should add a `NewVirtualState` constructor which gets a `PhysicalFileMeta` and sets both fields.

Is the logic around this field isolated to this package? If so, we should unexport


<!-- Sent from Reviewable.io -->

2023-02-22 19:56 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: 13 of 18 files reviewed, 19 unresolved discussions (waiting on @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`internal/manifest/version.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOqdUQo5m91IZOJbPTX:-NOugi5d735uvMPaWKLc:b-12dsyt) ([raw file](https://github.com/cockroachdb/pebble/blob/33d1932f5fd53a8b172c015069f27dbdc40c07fd/internal/manifest/version.go#L165)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Could you explain this field a little more? Its existence suggests that there are situations where this field is set but `Parent` isn't? (that aspect should be documented for `Parent`).

We should add a `NewVirtualState` constructor which gets a `PhysicalFileMeta` and sets both fields.

Is the logic around this field isolated to this package? If so, we should unexport
</blockquote></details>

Yea, this field isn't required. I realized that, but didn't make the change here. Will make it.


<!-- Sent from Reviewable.io -->

2023-02-22 19:58 UTC, RaduBerinde reviewed
> I don't think golang maps are safe for concurrent access even to different keys, so we'd probably need to work around that.

We can use a RWLock, we'd only need read access to get to the atomic's address. Or, if we use a regular lock, we don't need the atomics anymore (plus it enables adjusting multiple counts at once).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NOufsqB7r-DbzGxxai7:byki2g3)* status: 13 of 18 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @itsbilal, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-02-22 19:59 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: 13 of 18 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @itsbilal, and @sumeerbhola)

___
*[`internal/manifest/version.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOqdUQo5m91IZOJbPTX:-NOuhBgW2An5rdBLffGT:b-dcc4cr) ([raw file](https://github.com/cockroachdb/pebble/blob/33d1932f5fd53a8b172c015069f27dbdc40c07fd/internal/manifest/version.go#L165)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Yea, this field isn't required. I realized that, but didn't make the change here. Will make it.
</blockquote></details>

If that field isn't required, then we don't need `VirtualState` (it ends up being just a double pointer to `FileMetadata`). We'd just need a `VirtualParent *FileMetadata`


<!-- Sent from Reviewable.io -->

2023-02-22 20:01 UTC, RaduBerinde commented
*[`internal/manifest/version.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOqdUQo5m91IZOJbPTX:-NOuhnJa9J37kowoCJti:by2txsl) ([raw file](https://github.com/cockroachdb/pebble/blob/33d1932f5fd53a8b172c015069f27dbdc40c07fd/internal/manifest/version.go#L165)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If that field isn't required, then we don't need `VirtualState` (it ends up being just a double pointer to `FileMetadata`). We'd just need a `VirtualParent *FileMetadata`
</blockquote></details>

Or rather `VirtualParent PhysicalFileMeta`


<!-- Sent from Reviewable.io -->

2023-02-22 20:22 UTC, sumeerbhola reviewed
> I made this point in a meeting with Arjun and I'll repeat it here so @sumeerbhola hears it too, but I'd support a FileMetadata that only has one additional field for virtual sstables, i.e. PhysicalFileNum. We really don't need any other fields from the physical file metadata, and keeping the physical meta around in the manifest (and adding all the logic for "unlinked" files in the version edit, etc., and changing the VersionEdit format) seems pretty unnecessary all for a marginal increase in debuggability.
> ...
> I also worry about the space-amp increase in storing the smallest/largest point/range keys extra times for a FileMetadata that is really not being used except for the FileNum. Those fields take up much more space than a single uint64 for the physical file num (which will only be present if the virtual sst has a tag for virtual sst), and could only lead to more manifest rotations.

I lean heavily towards debuggability in this case. We only need to store those fields once for each virtualized physical sstable, so I am doubtful that there is enough cost for this to matter (and we have improved our manifest rotation logic). And we should be explicit about when we have virtualized physical ssts in a version and when we delete them -- I am quite unmoved about not changing version edit. One question is what we will store about these virtualized physical ssts in the disagg world where there are also foreign ssts. Maybe we don't want to ship all the `Smallest*`, `Largest*` keys around for the underlying physical sst (though one will need those for the virtual sst) -- I am very sympathetic to that position. But we do need the `fileNum, fileSize` stored for these virtualized physical sst (and the version edit will need to explicitly state when the transition from physical => virtualized-physical is happening). So we have a state machine that looks like
physical-sst (has a level) => virtualized-physical-sst => zombie => obsolete
physical-sst => zombie => obsolete
where both virtualized-physical-sst and physical-sst are start states in the state machine. The virtualized-physical-sst start state will only exist in disagg storage (for foreign ssts). Also, we would need to de-dup in this disagg storage case since we may import the same virtualized-physical sst at different points in time. We need the de-duping for the local ref counting and also to keep how many bytes in the virtualized-physical sst are still relevant (to prioritize compactions to reduce space amp -- yes for disagg storage this space amp is only for a single LSM and not across LSMs but it is still worth tracking and minimizing per-LSM space amp since it will make the cluster wide space amp lower). `fileNum, fileSize` are also the only things in `fileInfo` which we use in various places (like obsolete files) so should minimize that part of the plumbing change.

> The only thing that becomes slightly harder with only storing a file num, is ref counting, but we can restructure ref counting to operate away from the FileMetadata and in some map[PhysicalFileNum] and that solves that problem pretty easily.

I may not be understanding this suggestion, but I don't think this works. The reason we have a copy-on-write btree is that we can install new versions without making a full copy of the btree, and which is why ref counting works the way it is (a ref may be shared across versions if that part of the btree is shared). A map would require a copy of the map for each new version, which I think is a non starter.
I think we can have FileMetadata struct for both physical ssts and virtual ssts. Both of them have a `*physicalState` where
```
type physicalState struct {
   FileNum  FileNum
   Size uint64
   Refs int32
   RefsInLatestVersion int32
}
```

   

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NOugxal5uDcsQQklII0:be01qnv)* status: 13 of 18 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @itsbilal, and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2023-02-22 20:31 UTC, sumeerbhola reviewed
> Also, we would need to de-dup in this disagg storage case since we may import the same virtualized-physical sst at different points in time.

Ignore this. We may give the foreign sst a new local filenum when importing through the provider, and then generate a (second) local filenum for the virtual sst. In which case it becomes the provider's job to also ref count for the foreign ssts (another layer of ref counting much like we have many layers of ref counting now -- nothing to worry about). If we don't do this "new local filenum" we can have complexities where a virtualized-physical sst is in zombie state, and we need to transition it back out since we are importing a new virtual sst that points to it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NOunNVB6ce094XCrQ1C:b6yci6s)* status: 13 of 18 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @itsbilal, and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2023-02-22 20:54 UTC, itsbilal commented
I think my map suggestion was taken more literally than I meant it to be, probably because I specified it as a go type. I just meant that we'd do refcounting on one int for all virtual sstables that map to one physical sstable. That int can be in a `*PhysicalState` that the virtual sstable FileMetadatas store a pointer to, like you suggested; the main point being that it doesn't need to be part of the FileMetadata and can be taken outside of it.

The VersionEdit can already store that transition to virtual by marking the physical SST's `FileNum` as deleted, and have new AddedFiles `FileMetadatas` in the same VersionEdit that are virtual sstables off of it. We already don't have a clear record of when SSTs go from zombie to obsolete, as that's dependent on iterators closing. But if the purpose is to document that transition to zombie explicitly for debuggability purposes, I would support a `VersionEdit` change that has one additional field, `DeletedBackingFiles []base.FileNum` (or maybe `map[base.FileNum]struct{}` similar to `DeletedFiles`) or so, that names the physical file num in the same version edit when the last Virtual SST from it was in `DeletedFiles`. That gets us the observability improvement without keeping around the entire metadata (which to me seems pretty excessive when we only need one or two fields).

As for `fileSize`, I still see enough ways to be able to implement the partial-zombie-table compaction heuristic without storing the total size of the physical sstable, but if Arjun feels that we should have it around, having it in the PhysicalState is not a bad idea. And I like the definition of `PhysicalState` that @sumeerbhola proposed.

In short, this is what I'm suggesting:

1) Have a physical state struct like Sumeer proposed, that stores the refs and physical file num and size. Looks like we have consensus on this.
2) Add a `VersionEdit` field, `DeletedBackingFiles` that specifies the transition from virtualized-physical-sstable to zombie; similar to what Arjun was planning on doing, except we don't store the entire physical FileMetadata there, but just the physical filenum. I know that this isn't the VersionEdit PR but we're basically required to make some decisions about that here.
3) Don't have virtual file metadata point to a physical file metadata, but just to its `physicalState`. This way, we're able to maintain the guarantee that if you have a `*FileMetadata`, you can mint a valid iterator on it.

2023-02-22 21:57 UTC, bananabrick commented
> In short, this is what I'm suggesting:

>Have a physical state struct like Sumeer proposed, that stores the refs and physical file num and size. Looks like we have >consensus on this.
>Add a VersionEdit field, DeletedBackingFiles that specifies the transition from virtualized-physical-sstable to zombie; >similar to what Arjun was planning on doing, except we don't store the entire physical FileMetadata there, but just the >physical filenum. I know that this isn't the VersionEdit PR but we're basically required to make some decisions about that >here.
>Don't have virtual file metadata point to a physical file metadata, but just to its physicalState. This way, we're able to >maintain the guarantee that if you have a *FileMetadata, you can mint a valid iterator on it.

This sounds good to me. I think the version edit will also need an additional field for `AddedBackingState` which will be written to once the physical sst is first virtualized if we're also storing the size of the physical sst. There's ways to work around it, of course.

2023-02-22 23:20 UTC, sumeerbhola reviewed
> I know that this isn't the VersionEdit PR but we're basically required to make some decisions about that here.

btw, I would prefer to have the VersionEdit changes in this PR. We need the reasoning about the state transitions to know that we have the right state. We can leave the edit encoding/decoding to a later PR if folks prefer.

>  I think the version edit will also need an additional field for AddedBackingState which will be written to once the physical sst is first virtualized if we're also storing the size of the physical sst.

Making this explicit, as you outlined, would be my preference too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NOvPGIsB0OTpjeDrYGP:bigd2hf)* status: 13 of 18 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @itsbilal, and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2023-02-22 23:38 UTC, itsbilal commented
I think `AddedBackingState` and `DeletedBackingState` would do this job well. The filenum it's keyed on could be the physical file num (and providers generate a physical file num for foreign SSTs that can just act as a placeholder, either way disaggregated storage details are not super relevant for this PR). It might make sense to make the value more expandable than just a `uint64`, maybe a `BackingState` that's an interface that has an `Encode` method and a `String` method (our `physicalState` struct could implement this interface) , and we have a `DecodeBackingState` method in `internal/manifest` that produces a `BackingState` at restart. `objstorage` could have a separate `BackingState` implementation. But the `BackingState` interface work can wait until after virtual SSTs are done, as long as the on-disk format in the versionedit decode PR supports something other than just the size.

2023-02-23 01:53 UTC, itsbilal commented
Actually, Nevermind what I said about the BackingState interface and the on disk format being flexible. The provider’s catalog will contain any additional fields anyway.

2023-02-24 04:14 UTC, bananabrick commented
This needs a bit more work before I request review again. Haven't completed all of the suggestions with satisfactory quality yet.

2023-02-24 15:44 UTC, jbowens reviewed
> As for fileSize, I still see enough ways to be able to implement the partial-zombie-table compaction heuristic without storing the total size of the physical sstable

I might be misunderstanding, but I think we we need the total size of the physical sstable if only for disk space usage accounting. Cockroach relies on Pebble maintaining an accounting of all disk space usage under its control for the purpose of reporting in the DB console. This needs to by physical disk space usage, not virtual.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NP34smNA1Cy6PtBnziW:b-uvxg07)* status: 6 of 32 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @itsbilal, @RaduBerinde, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-02-24 15:56 UTC, itsbilal commented
@jbowens I didn't elaborate so the confusion is warranted, but I was thinking of a "dead disk space contribution" metric that is `(physical sst size - sum of sizes of VSSTs) / num-VSSTs`. This can be stored in table stats (and easily recalculated at startup without persisting to the manifest), and vssts with higher values of that should be prioritized for compactions so we end up getting rid of physical SSTs with unused keys sooner rather than later. But storing the size and calculating that metric differently for compaction-picking purposes also a fair alternative.

Either way my main point was to not store the whole FileMetadata.

2023-02-24 16:05 UTC, jbowens reviewed
To clarify, I'm not talking about the heuristic. I'm talking about the incremental physical file size deltas passed in to `logAndApply`: https://github.com/cockroachdb/pebble/blob/bc4c9afe47a543163d6a583383bd9ae84e58310d/version_set.go#L350

We'll need to know the physical file size when it transitions into a zombie state for the purpose of disk space usage reporting. A lazy accounting of physical file sizes would become very tricky (what happens if a physical file becomes zombie before its stats or loaded?).

> Either way my main point was to not store the whole FileMetadata.

Got it

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NP38XtKCXiA0xRbYSDQ:b8p9wmn)* status: 6 of 32 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @itsbilal, @RaduBerinde, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-02-27 19:19 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: 6 of 33 files reviewed, 16 unresolved discussions (waiting on @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`checkpoint.go` line 285 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOqe5LiBqfIVQk4MLV2:-NOurqAa3B5uMAGJ0S6Z:b-jo3kpg) ([raw file](https://github.com/cockroachdb/pebble/blob/5ceaa45f9dc31de5223598a28aaff24129738753/checkpoint.go#L285)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I assume that there is an invariant that the same physical SST can't appear both as a physical SST and as a parent to a virtual SST. Are we verifying that somewhere?

In any case, it would be easier here to just use `BackingPhysicalFile()` and dedup in all cases.
</blockquote></details>

Yea, when we create virtual sstables from a physical sstable, we will write a `VersionEdit` which adds the virtual sstables to the lsm, and removes the physical sstable which was virtualized. So, the change to remove the physical sstables and add the virtual sstables will be atomic. I've written the invariant down in the version edit type above the `CreateBackingTables` field.

Made the change to always dedup.
___
*[`version_set.go` line 44 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOu-Hjc3Jh7_KXYZhEW:-NOv-o-zDxbD7J-HJiBJ:b-ewlzwu) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/version_set.go#L44)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

where is `backingPhysicalTables map[FileNum]physicalMeta` that is in the other PR?
</blockquote></details>

Had removed it because it wasn't used anywhere, but now that I've added the version edit changes, it is once again used.
___
*[`internal/manifest/btree.go` line 210 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtq01M9Yg5g7pXvugV:-NOv13-18foQyLvqhNvX:b-7vuuxl) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/btree.go#L210)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we need a signature like
```
// INVARIANT: additionalObsolete != nil => refCount == 0
Unref() (refCount int32, additionalObsolete *FileMetadata)
```
if we are ref counting virtual ssts too.

If not, we need something like the following where `obsolete` may be the `FileMetadata we called unref on (for a physical sst) or the underlying physical sst (if we called on a virtual sst).
```
// INVARIANT: obsolete != nil => refCount == 0
Unref() (refCount int32, obsolete *FileMetadata)
```

</blockquote></details>

Currently, we're handling this in `addObsoleteLocked`: https://github.com/cockroachdb/pebble/pull/2352/files#diff-8b636b47efdad980c4371c99f9d558e8e14673c917574019be4ecdc6aa727341R761. If a virtual sstable is the last to become obsolete, we make sure that we only add the parent sstable of the virtual sstable to `versionSet.obsoleteTables`. This is also enforced through types. Only metadata associated with the physical files can be added to `versionSet.obsoleteTables`.
___
*[`internal/manifest/version.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOpbAKE4yKhVdz73_nP:-NOv3JyT2BNQ2dFNhbJB:bubsbrg) ([raw file](https://github.com/cockroachdb/pebble/blob/33d1932f5fd53a8b172c015069f27dbdc40c07fd/internal/manifest/version.go#L162)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I'm okay with that direction if Sumeer and others are good with it, however it's a pretty critical decision that's going to inform a lot of what comes next. I just want us to carefully make that choice and to consider the alternative as well, so I left a top-level comment making the case against this approach.
</blockquote></details>

Only keeping around a `PhysicalState` which will be reconstructed during manifest replay.
___
*[`internal/manifest/version.go` line 165 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtmbNG-uujuRX8U-Lp:-NOv4RMhEFsg5tnP_i9-:b6z9o3) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L165)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why duplicating the FileNum here instead of using Parent.FileNum?
</blockquote></details>

Got rid of this.
___
*[`internal/manifest/version.go` line 189 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtqcXrC92FJmOkoaf2:-NOvXE5Y63EJv15ilj7z:b-3c2r3y) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L189)):*
> Why only physical ssts?

We use refcounting for two purposes:
1. Delete obsolete files. Don't need to do this for virtual ssts.
2. Zombie table tracking. Currently, I'm only adding physical ssts to the zombie table map which is a map from `filenum -> filesize`. We could add virtual ssts to the zombie list, but at the point which we make the decision to add the virtual sst to the zombie list, its parent physical sst will already be in the list. The extra on disk file usage is already represented by the parent physical sst which is in the zombie list.

Do we need further metrics here? 

> I think what you are doing here is noticing that there is no physical resource to delete when only the refs for a virtual sst drop to zero, hence why bother tracking it. I suppose that will work too, and is fine. Could you add a comment somewhere on this reasoning.

Added a comment.
___
*[`internal/manifest/version.go` line 195 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtulQ2309IFcNh2-OB:-NP0USz87-5oiWgC0Ofu:bzakijj) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L195)):*
>  And file creation is not happening 1000s of times a second

Wasn't worried too much about performance due to allocations, but the fact that any code constructing a file metadata will have to ensure that the `PhysicalState` is allocated and set. Outside of test code, file meta is only created by ingestions/flushes/manifest replay, so this isn't too bad, I guess.

We now have a bunch of `FileMetadata.Init` all over the test code though. Some tests don't need `PhysicalState` to be set, but I erred on the side of caution.
___
*[`internal/manifest/version.go` line 203 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOu5xc1EINQ1fwu5exK:-NOveWp8COKHErmzXesw:bs45l57) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L203)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I think `versionRefs` or `virtualRefs` is a far better name for this, seeing as iterators don't increment this but versions do.
</blockquote></details>

Called it `latestVersionRefs` cause the latest part is crucial.
___
*[`internal/manifest/version.go` line 210 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOtrP52BQ5utdlLSiA5:-NP-FlTB-aU1cXmK--sb:b-8mywvq) ([raw file](https://github.com/cockroachdb/pebble/blob/9e8708317325837a0c37fbeef2ae8f003cacef4d/internal/manifest/version.go#L210)):*
> We should state an invariant somewhere that a physical sst that has references from other virtual ssts no longer exists as a first-class citizen in any level of the latest version.

Since this invariant is ensured by writing "correct" version edits, I've stated this invariant in the version edit above the `CreateBackingTables` field.

> I was imagining latestRefs to be only for such physical ssts, since for the others it is trivially 0 or 1. Were you planning to use it in all cases?

Yes, it's pretty easy to maintain it for all cases and avoids special casing. For physical ssts which don't back a virtual sst, it'll be either 0 or 1 like you said.

> Is Ph [...]

2023-02-27 20:14 UTC, bananabrick reviewed
Made the requested changes. There's some basic testing for the version edit changes, but will definitely add more. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NPJVXEm3Dv_ZDPS5L6E:bfubysm)* status: 6 of 33 files reviewed, 16 unresolved discussions (waiting on @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`internal/manifest/version.go` line 169 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOqWROy9MMGdSGP0_0c:-NPJVh605lv0zCqKuLT2:burpzsg) ([raw file](https://github.com/cockroachdb/pebble/blob/7f5ac717a6a190091dd024c4e07df7b956a4da7e/internal/manifest/version.go#L169)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Please add it. It's fine if it can't be tested yet, which can be left as a TODO in a test file. I'd really like to have the full "data-structure" part of virtual ssts in this PR.
</blockquote></details>

Added a `VirtualizedSize` to physical state, which keeps track of sum of virtual sstable sizes in the latest version.


<!-- Sent from Reviewable.io -->

2023-02-27 22:44 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: 6 of 33 files reviewed, 17 unresolved discussions (waiting on @itsbilal, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`version_set_test.go` line 36 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPK1yBz9ez74Lfz6GwV:-NPK1yBz9ez74Lfz6GwW:b4pance) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set_test.go#L36)):*
> ```Go
> // we're adding the physical sstable to the obsolete tables list iff the file is
> // truly obsolete.
> func TestLatestRefCounting(t *testing.T) {
> ```

This test is a bit clunky, but it gets the job done and I don't think we need a full data driven test here.


<!-- Sent from Reviewable.io -->

2023-03-01 19:16 UTC, sumeerbhola requested changes
> Reviewed 1 of 9 files at r8, 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: 9 of 33 files reviewed, 37 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @RaduBerinde)

___
*[`version_set.go` line 88 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT3FVrD3EfUJ6G9Qx9:-NPT3FVrD3EfUJ6G9QxA:buooldu) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L88)):*
> ```Go
> 	// A pointer to versionSet.addObsoleteLocked. Avoids allocating a new closure
> 	// on the creation of every version.
> 	obsoleteFn        func(obsolete []*fileMetadata)
> ```

how will we get the `fileMetadata` when a physical-sst that was referred to by virtual-leveled-ssts becomes obsolete? Or is this the metadata for that last virtual-leveled-sst?
___
*[`version_set.go` line 103 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT5NCoC6NVD98fZqtj:-NPT5NCoC6NVD98fZqtk:ba9cxq8) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L103)):*
> ```Go
> 	// Note that we don't keep track of physical sstable state backing a virtual
> 	// sstable which is not in the latest version.
> 	backingPhysicalState map[FileNum]*physicalState
> ```

We discussed this a week ago on slack, regarding whether this backing map should be in `VersionSet` or in each `Version`. I can see the efficiency benefit of putting this in `VersionSet` since then we don't have to copy the map for each new version, even though one could argue that this is really state that belongs in a Version.
___
*[`version_set.go` line 520 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT6Q6O6dgd8Vkp8W_h:-NPT6Q6O6dgd8Vkp8W_i:b9a5ho3) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L520)):*
> ```Go
> 				delete(vs.backingPhysicalState, fileNum)
> 			}
> 		}
> ```

This is another thing we previously discussed on slack.

We have multiple paths that do `BulkVersionEdit.Apply`. So I am slightly worried about not having a simple to understand story regarding application of edits.

What we have here is an "incomplete" VersionEdit that was passed into `logAndApply` that we are trying to (a) fix it up, to make it complete, (b) fix up the `backingPhysicalState`. This works since:
- This is the only place where we are writing an edit that is changing the state of the DB. The other `BulkVersionEdit.Apply` paths are reading from the manifest and accumulating changes, so those `VersionEdits` are known to be complete. So those don't need to fix the `VersionEdit`.
- The `backingPhysicalState` is in the `versionSet` and not the (new) `Version` so we can do the fix up code for (b) after calling `BulkVersionEdit.Apply`.

But the latter bullet is not sufficient coverage I think. There is also `versionSet.Load` which does:
```
	newVersion, _, err := bve.Apply(nil, vs.cmp, opts.Comparer.FormatKey, opts.FlushSplitBytes, opts.Experimental.ReadCompactionRate)
	if err != nil {
		return err
	}
	newVersion.L0Sublevels.InitCompactingFileInfo(nil /* in-progress compactions */)
	vs.append(newVersion)
```
and so does not not update `backingPhysicalState`. We can fix `versionSet.Load` but this is error prone in that it is easy to overlook things.

The ideal solution would be:
- lift out `backingPhysicalState` from `versionSet` and put it in each `Version`.
- Add a new method called `func (b *BulkVersionEdit) AccumulateFirstEditIncomplete(ve *VersionEdit, latestVersion *Version)  (completedEdit *VersionEdit, err error)` which *must* be called when the latest version to which this BVE will be applied is known (and this edit is the first edit in the BVE, which is sufficient for this `logAndApply` case where we only accumulate one edit in the BVE). We will use this method in `logAndApply` since this is the only path where the `VersionEdit` is possibly incomplete.
- The completedEdit is the one that will be encoded.
- BVE.Apply handles creation/maintenance of the `Version.backingPhysicalState` in the latest version. It is self-contained so we don't need to worry about overlooking (b).

The only difficulty I see with this ideal is that we do not want to keep copying the `backingPhysicalState` map. For that I would be ok with a mild hack: we can place `backingPhysicalState` in the `Version` but say that it is only reflective of the backing state for the latest version in the sequence of versions produced by BulkVersionEdit.Apply and that one can't fork the history. That allows us to just reuse the map.

edit: I see now the following code in `BVE.Apply`.
```
	// Note that backingState will only be modified here during manifest replay.
	for _, fileNum := range b.RemovedBackingState {
		delete(backingState, fileNum)
	}
```
I am ok with the current setup too, of keeping ``backingPhysicalState` in `versionSet` since it is basically the same as the hack I mentioned. But I am very keen that we we introduce `AccumulateFirstEditIncomplete` and never have to fiddle with `backingPhysicalState` inside `logAndApply`.
___
*[`internal/manifest/version.go` line 121 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPSr1248UPZeU6-3fLx:-NPSr1248UPZeU6-3fLy:bb5wl0r) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/internal/manifest/version.go#L121)):*
> ```Go
> 
> // PhysicalFileMeta is used by functions which want a guarantee that their input
> // belongs to a physical file on disk and not a virtual file.
> ```

I'm going to be repetitive here -- we need a way to distinguish between the two kinds of physical sstables in the terminology. And we need that terminology definition in this file since there are some physical ssts for which we have a FileMetadata and some for which we only have PhysicalState.

Here is a rough attempt.

FileMetadata is maintained for leveled-ssts, i.e., they belong to a level of some version. FileMetadata does not contain the actual level of the sst, since such leveled-ssts can move across levels in different versions, while sharing the same FileMetadata (the Version object maintains the level of the FileMetadata). There are two kinds of leveled-ssts, physical-leveled-ssts and virtual-leveled-ssts. Underlying both kinds of leveled-ssts is a physical-sst, for which the only state is PhysicalState. A physical-sst is level-less. It is possible for a physical-sst to be referred to by a physical-leveled-sst in one version and by one or more virtual-leveled-ssts in a different version. We maintain some invariants:
- A physical-sst in a version is either only referred to be one physical-leveled-sst or one or more virtual-leveled-ssts.
- Once a physical-sst is referred to be virtual-leveled-ssts in the latest version, it cannot go back to being referred to by a physical-leveled-sst in any future version.

The FileMetadata for a physical-leveled-sst contains extra information about the underlying physical-sst that is discarded when the physical-sst is referred to by virtual-leveled-ssts in the latest version (since only the PhysicalState is retained). This is ok since we will never go back to this being referred to by a physical-leveled-sst (second invariant above). 
___
*[`internal/manifest/version.go` line 160 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPSw23B04zpTDRnw-KP:-NPSw23B04zpTDRnw-KQ:b6jz9p6) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/internal/manifest/version.go#L160)):*
> ```Go
> 
> // PhysicalState is state which is associated with physical sstables on disk.
> // Some state like the FileNum might not be exclusive to physical sstables, but
> ```

I am not sure what "FileNum might not be exclusive to physical state" is trying to say. Is it trying to say that virtual-leveled-ssts also have filenums, or that physical-levele [...]

2023-03-02 04:55 UTC, bananabrick reviewed
Left some comments for further discussion, and made most of the changes. Left some comments around the accumulation, completion, application of version edits. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NPVewygDC9X5kAt6p0y:blfq35k)* status: 6 of 33 files reviewed, 36 unresolved discussions (waiting on @itsbilal, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`version_set.go` line 88 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT3FVrD3EfUJ6G9Qx9:-NPU8oI2-8w_8G2n4YlK:bg29mb3) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L88)):*
> Or is this the metadata for that last virtual-leveled-sst?

Yes it is.  `obsoleteFn` refers to `versionSet.addObsoleteLocked` which can handle virtual meta passed.
___
*[`version_set.go` line 520 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT6Q6O6dgd8Vkp8W_h:-NPV3cR80LHmMnMW88G8:b-zc0zfx) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L520)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is another thing we previously discussed on slack.

We have multiple paths that do `BulkVersionEdit.Apply`. So I am slightly worried about not having a simple to understand story regarding application of edits.

What we have here is an "incomplete" VersionEdit that was passed into `logAndApply` that we are trying to (a) fix it up, to make it complete, (b) fix up the `backingPhysicalState`. This works since:
- This is the only place where we are writing an edit that is changing the state of the DB. The other `BulkVersionEdit.Apply` paths are reading from the manifest and accumulating changes, so those `VersionEdits` are known to be complete. So those don't need to fix the `VersionEdit`.
- The `backingPhysicalState` is in the `versionSet` and not the (new) `Version` so we can do the fix up code for (b) after calling `BulkVersionEdit.Apply`.

But the latter bullet is not sufficient coverage I think. There is also `versionSet.Load` which does:
```
	newVersion, _, err := bve.Apply(nil, vs.cmp, opts.Comparer.FormatKey, opts.FlushSplitBytes, opts.Experimental.ReadCompactionRate)
	if err != nil {
		return err
	}
	newVersion.L0Sublevels.InitCompactingFileInfo(nil /* in-progress compactions */)
	vs.append(newVersion)
```
and so does not not update `backingPhysicalState`. We can fix `versionSet.Load` but this is error prone in that it is easy to overlook things.

The ideal solution would be:
- lift out `backingPhysicalState` from `versionSet` and put it in each `Version`.
- Add a new method called `func (b *BulkVersionEdit) AccumulateFirstEditIncomplete(ve *VersionEdit, latestVersion *Version)  (completedEdit *VersionEdit, err error)` which *must* be called when the latest version to which this BVE will be applied is known (and this edit is the first edit in the BVE, which is sufficient for this `logAndApply` case where we only accumulate one edit in the BVE). We will use this method in `logAndApply` since this is the only path where the `VersionEdit` is possibly incomplete.
- The completedEdit is the one that will be encoded.
- BVE.Apply handles creation/maintenance of the `Version.backingPhysicalState` in the latest version. It is self-contained so we don't need to worry about overlooking (b).

The only difficulty I see with this ideal is that we do not want to keep copying the `backingPhysicalState` map. For that I would be ok with a mild hack: we can place `backingPhysicalState` in the `Version` but say that it is only reflective of the backing state for the latest version in the sequence of versions produced by BulkVersionEdit.Apply and that one can't fork the history. That allows us to just reuse the map.

edit: I see now the following code in `BVE.Apply`.
```
	// Note that backingState will only be modified here during manifest replay.
	for _, fileNum := range b.RemovedBackingState {
		delete(backingState, fileNum)
	}
```
I am ok with the current setup too, of keeping ``backingPhysicalState` in `versionSet` since it is basically the same as the hack I mentioned. But I am very keen that we we introduce `AccumulateFirstEditIncomplete` and never have to fiddle with `backingPhysicalState` inside `logAndApply`.
</blockquote></details>

This is the solution I went with:

- Added a new method called
```
func (b *BulkVersionEdit) ApplyAndCompleteVE(
        ve *versionEdit, curr *Version,
	cmp Compare,
	formatKey base.FormatKey,
	flushSplitBytes int64,
	readCompactionRate int64,
	backingState map[base.FileNum]*BackingState) (completedEdit *VersionEdit, err error)
```

Ideally, we'd complete the versionEdit before the apply step, and even before the accumulate step. But to determine if a version edit must be completed, we need to determine if a file is transitioning to a zombie status. To do that, we need to iterate over the files being added and removed in the bulk version edit, and look up/update the refcounts of the files. While it is possible to do this before the accumulate or during the accumulate step, it is error prone and the logic will be just as or more complex than the file refcounting logic we already have in the apply step.

We complete the version edit before the backingState is updated.

- BVE.Apply handles creation/maintenance of the `VersionSet.backingState` in the latest version. It is self-contained.

I'll keep thinking about a better solution, but posting this to unblock the rest of the review. Overall, if we decide to refactor the code around `logAndApply/load/Apply/Accumulate`, I'd rather reason about the code in isolation separate from this pr.
___
*[`internal/manifest/version.go` line 121 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPSr1248UPZeU6-3fLx:-NPUFibX5tseQWfI8VIm:bfl6mhh) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/internal/manifest/version.go#L121)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm going to be repetitive here -- we need a way to distinguish between the two kinds of physical sstables in the terminology. And we need that terminology definition in this file since there are some physical ssts for which we have a FileMetadata and some for which we only have PhysicalState.

Here is a rough attempt.

FileMetadata is maintained for leveled-ssts, i.e., they belong to a level of some version. FileMetadata does not contain the actual level of the sst, since such leveled-ssts can move across levels in different versions, while sharing the same FileMetadata (the Version object maintains the level of the FileMetadata). There are two kinds of leveled-ssts, physical-leveled-ssts and virtual-leveled-ssts. Underlying both kinds of leveled-ssts is a physical-sst, for which the only state is PhysicalState. A physical-sst is level-less. It is possible for a physical-sst to be referred to by a physical-leveled-sst in one version and by one or more virtual-leveled-ssts in a different version. We maintain some invariants:
- A physical-sst in a version is either only referred to be one physical-leveled-sst or one or more virtual-leveled-ssts.
- Once a physical-sst is referred to be virtual-leveled-ssts in the latest version, it cannot go back to being referred to by a physical-leveled-sst in any future version.

The FileMetadata for a physical-leveled-sst contains extra information about the underlying physical-sst that is discarded when the physical-sst is referred to by virtual-leveled-ssts in the latest version (since only the PhysicalState is retained). This is ok since we will never go back to this being referred to by a physical-leveled-sst (second invariant above). 
</blockquote></details>

Done. Thanks for providing the comment.

`physical-leveled, virtual-leveled, physical` is explicit but verbose. I opted for `physical, virtual` for leveled ssts, and `backing` for the sst fi [...]

2023-03-02 20:14 UTC, RaduBerinde reviewed
The latest iteration is very nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NPYwJGE5u-aNdhMpElH:b-40b2pk)* status: 6 of 33 files reviewed, 46 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @sumeerbhola)

___
*[`internal/manifest/version.go` line 120 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPYv3HgBU6lhn8qkiYR:-NPYv3HgBU6lhn8qkiYS:bhr6eio) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/internal/manifest/version.go#L120)):*
> ```Go
> }
> 
> // PhysicalFileMeta is used by functions which want a guarantee that their input
> ```

[nit] feels like these definitions (including BackingState) should come after the `FileMetadata` which explains everything.
___
*[`internal/manifest/version.go` line 195 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPYwczREZ5gzvRxg-N8:-NPYwczREZ5gzvRxg-N9:b-n373d0) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/internal/manifest/version.go#L195)):*
> ```Go
> 		VirtualizedSize uint64
> 	}
> 	FileNum base.FileNum
> ```

I wonder if this would be a good time to consider coming up with a new type for this. `FileNum` serves as both a logical number within a manifest and a "handle" on reading/writing the object (the former is what we want in FileMetadata and the latter is what we need here).

If we use the same type, I could see a lot of bugs where we use `FileMetadata.FileNum` instead of `FileMetadata.BackingState.FileNum` (and that works just fine for physical so the bugs would only show up for virtual).
___
*[`internal/manifest/version.go` line 202 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPYvc4y2jzPmJBxlp4y:-NPYvc4y2jzPmJBxlp4z:bavir5p) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/internal/manifest/version.go#L202)):*
> ```Go
> // some version. FileMetadata does not contain the actual level of the sst,
> // since such leveled-ssts can move across levels in different versions, while
> // sharing the same FileMetadata. There are two kinds of leveled-ssts, physical
> ```

Would it be accurate to say that there is only one `FileMetadata` for a given `FileNum`? (that invariant would explain why we need to share the metadata in different versions/levels)
___
*[`internal/manifest/version.go` line 209 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPYvqwm9nV_xAOSFyvY:-NPYvqwm9nV_xAOSFyvZ:b31oo4) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/internal/manifest/version.go#L209)):*
> ```Go
> //
> // We maintain some invariants:
> // 	1. A backing-sst in a version is either only referred to by one physical sst
> ```

[nit] I'd say "Within a version, a backing-sst is .." (makes it a bit more clear that all SSTs talked about are in the same version)
___
*[`internal/manifest/version.go` line 246 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPYtMM49x4xPl8uTZy8:-NPYtMM49x4xPl8uTZy9:bhiu6c) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/internal/manifest/version.go#L246)):*
> ```Go
> 	// FileNum is the file number.
> 	//
> 	// INVARIANT: when !FileMetadata.Virtual, FileNum == PhysicalState.FileNum.
> ```

BackingState?
___
*[`internal/manifest/version.go` line 249 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPYtQuq3p3IiBdmVXtK:-NPYtQuq3p3IiBdmVXtL:b-2dfbbe) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/internal/manifest/version.go#L249)):*
> ```Go
> 	FileNum base.FileNum
> 	// Size is the size of the file, in bytes. Size is an approximate value for
> 	// virtual sstables.
> ```

What does it approximate? Is it an approximation of how much data in the physical SST is required to e.g. fully iterate through the virtual SST?
___
*[`internal/manifest/version.go` line 251 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPYtO569eNhC86I_RIx:-NPYtO569eNhC86I_RIy:bhiu6c) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/internal/manifest/version.go#L251)):*
> ```Go
> 	// virtual sstables.
> 	//
> 	// INVARIANT: when !FileMetadata.Virtual, Size == PhysicalState.Size.
> ```

BackingState?
___
*[`internal/manifest/version.go` line 274 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPYtvOL-moxpH2ts6zu:-NPYtvOL-moxpH2ts6zv:bpurde4) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/internal/manifest/version.go#L274)):*
> ```Go
> 	// exported for reads as an optimization.
> 	SmallestPointKey InternalKey
> 	LargestPointKey  InternalKey
> ```

For virtual SSTs, are these fields used to delineate where the virtual SST's keyspace starts and ends?
___
*[`internal/manifest/version.go` line 343 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPYu5bIBC3IoSIpJFl9:-NPYu5bIBC3IoSIpJFlA:b-71bi19) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/internal/manifest/version.go#L343)):*
> ```Go
> 	// table bounds.
> 	boundTypeSmallest, boundTypeLargest boundType
> 	// Virtual is true if the FileMetadata belongs to a virtual sstable.
> ```

It would be good to outline here how the virtual boundaries are determined
___
*[`internal/manifest/version.go` line 367 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPYuMkm7aaEaHnCTkfw:-NPYuMkm7aaEaHnCTkfx:b-qz912k) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/internal/manifest/version.go#L367)):*
> ```Go
> // ValidateVirtual should be called once the FileMetadata for a virtual sstable
> // is created to verify that the fields of the virtual sstable are sound.
> func (m *FileMetadata) ValidateVirtual(parent *FileMetadata) {
> ```

What's a "parent" in this latest iteration?


<!-- Sent from Reviewable.io -->

2023-03-06 17:18 UTC, sumeerbhola requested changes
This is getting closer to the finish line!

> Reviewed 2 of 17 files at r1, 2 of 3 files at r4, 3 of 24 files at r7, 2 of 6 files at r10, 3 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NPrvTV8Ejir_GIzrKPA:btacww3)* status: 14 of 33 files reviewed, 54 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @RaduBerinde)

___
*[`db.go` line 1834 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrirsJ3tyPlJpLIdZH:-NPrirsJ3tyPlJpLIdZI:bgpgyva) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/db.go#L1834)):*
> ```Go
> 			if opt.withProperties && !m.Virtual {
> 				// The withProperties option isn't used by Cockroach, so it
> 				// should be okay to skip virtual sstable support here.
> ```

This is hacky, and I think we should support this properly by stating that the properties are for the underlying sstable (we don't need to de-duplicated). Since `SSTableInfo` is only used in this case we can add fields `IsVirtual` and `PhysicalFileNum` to it. I am ok with a TODO here pointing to an issue.
___
*[`db.go` line 1891 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrjl5fCaHn_b3Of2uI:-NPrjl5fCaHn_b3Of2uJ:b535se3) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/db.go#L1891)):*
> ```Go
> 				// sstables backing file here to get the disk usage. But the
> 				// table cache is currently built to operate on FileMetadata and
> 				// not BackingState.
> ```

This needs a tracking issue too. Maybe create an overarching one with the list of things that we need to address before considering this production worthy.
___
*[`format_major_version.go` line 499 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrkJYsAzc4KvlbG-sZ:-NPrkJYsAzc4KvlbG-s_:bsybn3x) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/format_major_version.go#L499)):*
> ```Go
> 			for f := iter.First(); f != nil; f = iter.Next() {
> 				err = tc.withReader(
> 					f, func(r *sstable.Reader) error {
> ```

what's the reason for this formatting change?
___
*[`version_set.go` line 88 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT3FVrD3EfUJ6G9Qx9:-NPrlLCh0p1jdJ6at7oH:b812x1v) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L88)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

> Or is this the metadata for that last virtual-leveled-sst?

Yes it is.  `obsoleteFn` refers to `versionSet.addObsoleteLocked` which can handle virtual meta passed.
</blockquote></details>

I think this is confusing and needs comments at least. Otherwise it is easy to imagine that we may be passing a virtual sst here because it is obsolete. Better yet, can we change this to `fileInfo`? `versionSet.addObsoleteLocked` does not need anything else from the `FileMetadata`.
___
*[`version_set.go` line 520 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT6Q6O6dgd8Vkp8W_h:-NPrnK8J2ad9TNvc7l1K:b-wsu3a9) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L520)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

This is the solution I went with:

- Added a new method called
```
func (b *BulkVersionEdit) ApplyAndCompleteVE(
        ve *versionEdit, curr *Version,
	cmp Compare,
	formatKey base.FormatKey,
	flushSplitBytes int64,
	readCompactionRate int64,
	backingState map[base.FileNum]*BackingState) (completedEdit *VersionEdit, err error)
```

Ideally, we'd complete the versionEdit before the apply step, and even before the accumulate step. But to determine if a version edit must be completed, we need to determine if a file is transitioning to a zombie status. To do that, we need to iterate over the files being added and removed in the bulk version edit, and look up/update the refcounts of the files. While it is possible to do this before the accumulate or during the accumulate step, it is error prone and the logic will be just as or more complex than the file refcounting logic we already have in the apply step.

We complete the version edit before the backingState is updated.

- BVE.Apply handles creation/maintenance of the `VersionSet.backingState` in the latest version. It is self-contained.

I'll keep thinking about a better solution, but posting this to unblock the rest of the review. Overall, if we decide to refactor the code around `logAndApply/load/Apply/Accumulate`, I'd rather reason about the code in isolation separate from this pr.

</blockquote></details>

The reason I am quibbling about `BVE.ApplyAndCompleteVE` is that one applies a BVE and not a VE and this pattern is clean: accumulate VEs into a BVE, then Apply. By saying `ApplyAndCompleteVE` we are saying there is only 1 VE in this BVE, so why did we even bother staging it in the BVE by calling `Accumulate` beforehand? We didn't even have a complete VE so what did we Accumulate, and why was that meaningful. It sounds semantically wonky.

I'd be ok with either my preceding suggestion of `func (b *BulkVersionEdit) AccumulateFirstEditIncomplete(ve *VersionEdit, latestVersion *Version) (completedEdit *VersionEdit, err error)` followed by `Apply`, or a single step `AccumulateIncompleteAndApply` which is called on an empty BVE. With the first option, we would update `backingStateMap` in `Apply` and `AccumulateFirstEditIncomplete` would have done the ref-counting calculations to know which `backingStates` need to be removed.
___
*[`version_set.go` line 103 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrpDdh9bNR06ZpWbyk:-NPrpDdh9bNR06ZpWbyl:bgg1bme) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/version_set.go#L103)):*
> ```Go
> 	// don't keep track of backing state which supports a virtual sstable
> 	// which is not in the latest version.
> 	backingState map[FileNum]*backingState
> ```

nit: backingStateMap (harder to write code comments when both the map and the elements are called backingState)
___
*[`version_set.go` line 686 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrq_bJ7gdJuK6SQel7:-NPrq_bJ7gdJuK6SQel8:b-ioszdt) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/version_set.go#L686)):*
> ```Go
> 			if _, ok := dedup[meta.BackingState.FileNum]; !ok {
> 				dedup[meta.BackingState.FileNum] = struct{}{}
> 				snapshot.CreateBackingTables = append(
> ```

so we are including these for physical ssts too?
Maybe I misunderstood the definition of `CreateBackingTables` because I was expecting this to be the same as the list in `versionSet.backingStateMap`.
___
*[`version_set.go` line 782 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrqrqQ8SHaEsvxRaxl:-NPrqrqR9fL9r64nm00L:b-gqfa5b) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/version_set.go#L782)):*
> ```Go
> 	for _, f := range obsolete {
> 		backingState := f.BackingState
> 		_, ok := dedup[backingState.FileNum]
> ```

why would we have duplicates here if only the last virtual sst holding the reference would be added via `addObsoleteLocked`?
___
*[`internal/manifest/version.go` line 120 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPYv3HgBU6lhn8qkiYR:-NPrtEYk671xO_a3jzJ9:b32v57) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/internal/manifest/version.go#L120)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] feels like these definitions (including BackingState) should come after the `FileMetadata` which explains everything.
</blockquote></details>

+1
___
*[`internal/manifest/version.go` line 180 at r11](https://reviewable.io [...]

2023-03-09 22:21 UTC, itsbilal reviewed
I agree with the others, this is really taking shape!

> Reviewed 1 of 17 files at r1, 4 of 24 files at r7, 5 of 9 files at r8, 11 of 22 files at r12, 1 of 3 files at r13, 3 of 4 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NQ7So_SAehhTZI9NBlV:bjqvk7f)* status: 26 of 34 files reviewed, 61 unresolved discussions (waiting on @bananabrick, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`db.go` line 1891 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrjl5fCaHn_b3Of2uI:-NQ76-FOEtoqIiPMKQFu:bb04mwy) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/db.go#L1891)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This needs a tracking issue too. Maybe create an overarching one with the list of things that we need to address before considering this production worthy.
</blockquote></details>

The table cache should continue to operate on FileMetadata right? That way we can rely on it to create the appropriate bounds-enforcing virtual iterator. I'm good with a TODO/tracking issue here, but I don't see how this is a problem for this function; the `iter` should already be the constrained one.

The single biggest reason why I wanted us to separate out physical state from `FileMetadata` was so iterators could continue to be created on `FileMetadata`, as they everything you could possibly need to know when creating and using iterators.
___
*[`ingest.go` line 1025 at r15](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NQ7E9eC8kRtDeUNQsEE:-NQ7E9eDAiTYnjSjXFDA:bb8xphw) ([raw file](https://github.com/cockroachdb/pebble/blob/f4af57ae04ec7b89c46464576e04d92d04105d3e/ingest.go#L1025)):*
> ```Go
> // DB.mu must be locked when calling.
> //
> // TODO(bananabrick): Make sure that the ingestion step only passes in the
> ```

I can see us needing this for virtual SSTs ingested in disaggregated storage, any particular reason not to generally support this case too?
___
*[`table_stats.go` line 410 at r15](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NQ7JzpFD4NYCeBXVBZb:-NQ7JzpFD4NYCeBXVBZc:bspxj6w) ([raw file](https://github.com/cockroachdb/pebble/blob/f4af57ae04ec7b89c46464576e04d92d04105d3e/table_stats.go#L410)):*
> ```Go
> 		for file := iter.First(); file != nil; file = iter.Next() {
> 			var err error
> 			if file.Virtual {
> ```

This will never happen because we'd have already hit the panic in `PhysicalMeta()` right?
___
*[`internal/manifest/version.go` line 188 at r15](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NQ7Fg1jCJT6AkrR-Ru6:-NQ7Fg1kAdXji2fFDw_u:biizu9d) ([raw file](https://github.com/cockroachdb/pebble/blob/f4af57ae04ec7b89c46464576e04d92d04105d3e/internal/manifest/version.go#L188)):*
> ```Go
> 	// ingested. For virtual sstables, this corresponds to the wall clock time
> 	// when the FileMetadata for the virtual sstable was first created.
> 	// virtual sstables.
> ```

nit: probably didn't mean to keep around this "virtual sstables." at the end?
___
*[`internal/manifest/version.go` line 279 at r15](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NQ7IU0oBVV2Rdzh63La:-NQ7IU0oBVV2Rdzh63Lb:bosclyj) ([raw file](https://github.com/cockroachdb/pebble/blob/f4af57ae04ec7b89c46464576e04d92d04105d3e/internal/manifest/version.go#L279)):*
> ```Go
> // NB: This type should only be constructed by calling
> // FileMetadata.PhysicalMeta.
> type PhysicalFileMeta struct {
> ```

Is there a good reason for it to be a wrapping struct? How about:

`type PhysicalFileMeta *FileMetadata`

I also don't see this being used in anything other than stats calculation (unless I missed something) - maybe we should have a TODO to get rid of this once stats work for virtual SSTs. It makes more sense to have code deal with FileMetadata and BackingState only, not PhysicalFileMeta and VirtualFileMeta.
___
*[`internal/manifest/version.go` line 332 at r15](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NQ7Ksqu4MCh-Q2DlJpb:-NQ7Ksqu4MCh-Q2DlJpc:b-3up2kq) ([raw file](https://github.com/cockroachdb/pebble/blob/f4af57ae04ec7b89c46464576e04d92d04105d3e/internal/manifest/version.go#L332)):*
> ```Go
> 		//
> 		// INVARIANT: latestVersionRefs <= refs.
> 		latestVersionRefs int32
> ```

Having this and `VirtualizedSize` be atomics and not just regular ints protected by `db.mu` or the version list or manifest lock seems unintuitive, and suggests that they are open to more concurrency than they actually are. And the value for VirtualizedSize makes sense in conjunction with latestVersionRefs, not on its own. But it's also hard to have these two actually be protected by those mutexes, since you are updating them in bve.Apply* and not `versionSet.logAndApply`.

I think the correct way to clean this up is to move the zombie logic to `versionSet.logAndApply`, so we compute zombie tables _after_ a version has been successfully installed, and where we currently bump the Version ref.
___
*[`internal/manifest/version_edit.go` line 124 at r15](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NQ75FU_49u7GCNId_8R:-NQ75FU_49u7GCNId_8S:b-yw3rdd) ([raw file](https://github.com/cockroachdb/pebble/blob/f4af57ae04ec7b89c46464576e04d92d04105d3e/internal/manifest/version_edit.go#L124)):*
> ```Go
> 	// The physical sstable associated with the BackingState must also not be
> 	// present in NewFiles.
> 	CreateBackingTables []*BackingState
> ```

should be CreatedBackingTables as all other verbs are in the past tense (addedfiles, deletedfiles)
___
*[`internal/manifest/version_edit.go` line 141 at r15](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NQ75MaR7Ghz3KvN9Nt6:-NQ75MaR7Ghz3KvN9Nt7:b-1vsogq) ([raw file](https://github.com/cockroachdb/pebble/blob/f4af57ae04ec7b89c46464576e04d92d04105d3e/internal/manifest/version_edit.go#L141)):*
> ```Go
> 	// and RemoveBackingTables. A file must be present in RemoveBackingTables in
> 	// exactly one version edit.
> 	RemoveBackingTables []base.FileNum
> ```

should be RemovedBackingTables as all other verbs are in the past tense, and the comment should also be in the past tense.
___
*[`internal/manifest/version_edit.go` line 834 at r15](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NQ7Rzqc8mRCj4BgonzM:-NQ7Rzqc8mRCj4BgonzN:b9gy9q5) ([raw file](https://github.com/cockroachdb/pebble/blob/f4af57ae04ec7b89c46464576e04d92d04105d3e/internal/manifest/version_edit.go#L834)):*
> ```Go
> 			// We're adding this file to the new version, so increment the
> 			// latest refs count.
> 			f.LatestRef()
> ```

Another major issue here is that our ref counting will become inconsistent if we error out in this method, eg. below where we `InitL0Sublevels`; we'd have bumped up this ref here for a version that never gets installed. It's why I think refs should be best read/written to outside of `BulkVersionEdit` and in `VersionSet.logAndApply`. Thoughts?


<!-- Sent from Reviewable.io -->

2023-03-20 23:56 UTC, bananabrick reviewed
Addressed comments. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NPt9H2a3RhK04-nioRd:bgih49z)* status: 13 of 34 files reviewed, 50 unresolved discussions (waiting on @itsbilal, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`db.go` line 1834 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrirsJ3tyPlJpLIdZH:-NPsJRuc5aXhTPqY0xs0:b-3i4x2e) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/db.go#L1834)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is hacky, and I think we should support this properly by stating that the properties are for the underlying sstable (we don't need to de-duplicated). Since `SSTableInfo` is only used in this case we can add fields `IsVirtual` and `PhysicalFileNum` to it. I am ok with a TODO here pointing to an issue.
</blockquote></details>

Added here because I want to avoid too many todos.
___
*[`db.go` line 1891 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrjl5fCaHn_b3Of2uI:-NPsI8o62z6J0NvOnI4h:bcrjyzm) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/db.go#L1891)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The table cache should continue to operate on FileMetadata right? That way we can rely on it to create the appropriate bounds-enforcing virtual iterator. I'm good with a TODO/tracking issue here, but I don't see how this is a problem for this function; the `iter` should already be the constrained one.

The single biggest reason why I wanted us to separate out physical state from `FileMetadata` was so iterators could continue to be created on `FileMetadata`, as they everything you could possibly need to know when creating and using iterators.
</blockquote></details>

Got rid of the special casing for now. We would need `Reader.EstimatedDiskUsage` to work on virtual sstables, which requires further constraining of the bounds `start,end` to within the virtual sstable bounds, which is what I do in the read path changes.
___
*[`ingest.go` line 1025 at r15](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NQ7E9eC8kRtDeUNQsEE:-NR02iS3Cm4u8w-OA2Pd:b4qar4e) ([raw file](https://github.com/cockroachdb/pebble/blob/f4af57ae04ec7b89c46464576e04d92d04105d3e/ingest.go#L1025)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I can see us needing this for virtual SSTs ingested in disaggregated storage, any particular reason not to generally support this case too?
</blockquote></details>

All this does is open a reader and validate block checksums for each block in the sstable. Can probably pass in the `BackingState` of the virtual sstables, grab a reader, and validate block checksums on those. That's what the todo is indicating. Makes more sense to do this in the read path pr once the reader changes are in.
___
*[`table_stats.go` line 410 at r15](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NQ7JzpFD4NYCeBXVBZb:-NR03f4oEI37mS-xd2kw:bcpk5q9) ([raw file](https://github.com/cockroachdb/pebble/blob/f4af57ae04ec7b89c46464576e04d92d04105d3e/table_stats.go#L410)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

This will never happen because we'd have already hit the panic in `PhysicalMeta()` right?
</blockquote></details>

The input to the function is a `physicalMeta` but the files we are iterating over here can be virtual.
___
*[`version_set.go` line 88 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT3FVrD3EfUJ6G9Qx9:-NPt9s_p76bBfsAtqijN:b1lzdjp) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L88)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think this is confusing and needs comments at least. Otherwise it is easy to imagine that we may be passing a virtual sst here because it is obsolete. Better yet, can we change this to `fileInfo`? `versionSet.addObsoleteLocked` does not need anything else from the `FileMetadata`.
</blockquote></details>

We want to pass virtual sstables into that function. The `addObsoleteLocked` function is called from `Version.Unref` and `Version.UnrefLocked`. Initially, I was only passing physical sst meta to `addObsoleteLocked`, but a suggestion was made during review that the we should let `addObsoleteLocked` handle virtual ssts being passed.

`obsolete []*fileMetadata` definition is accurate. It can be the file metadata associated with either a physical or virtual sstable which was recently obsoleted.

I added a comment with the explanation to `addObsoleteLocked`.
___
*[`version_set.go` line 103 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT5NCoC6NVD98fZqtj:-NPtD8EME3kuuhsjptmy:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L103)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We discussed this a week ago on slack, regarding whether this backing map should be in `VersionSet` or in each `Version`. I can see the efficiency benefit of putting this in `VersionSet` since then we don't have to copy the map for each new version, even though one could argue that this is really state that belongs in a Version.
</blockquote></details>

Done.
___
*[`version_set.go` line 520 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT6Q6O6dgd8Vkp8W_h:-NR049Zf6Iy5Nen6D5M9:b-t11l7r) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L520)):*
> or a single step AccumulateIncompleteAndApply which is called on an empty BVE.

Doing this currently. We're still accumulating first within the function, applying, and then completing the incomplete version edit. 


If we want, instead of completing an incomplete version edit, we could just write two version edits. One where the last virtual sstable in a version associated with a backing table gets deleted. And a subsequent version edit which has the `RemovedBackingTables` entry. That way we can get rid of the incomplete version edit mess. But I think overall, even the current solution is pretty easy to understand.
___
*[`version_set.go` line 686 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrq_bJ7gdJuK6SQel7:-NPtDcf43D8AgbdQCadP:bfueaji) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/version_set.go#L686)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

so we are including these for physical ssts too?
Maybe I misunderstood the definition of `CreateBackingTables` because I was expecting this to be the same as the list in `versionSet.backingStateMap`.
</blockquote></details>

Oversight. The accuracy of `CreateBackingTables` when we write the manifest snapshot is only tested during manifest replay, and there's no manifest replay testing without ve decoding/encoding.
___
*[`version_set.go` line 782 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrqrqQ8SHaEsvxRaxl:-NPtEvNz6_JsENNiuk3v:bfdmtiw) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/version_set.go#L782)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why would we have duplicates here if only the last virtual sst holding the reference would be added via `addObsoleteLocked`?
</blockquote></details>

We wouldn't. But it was an implicit invariant. I turned the fact that there should be no duplicate backing files passed into `addObsoleteLocked` into an invariant and I added a panic if there's duplicates and invariants are enabled.

Doesn't seem like a necessary invariant to explicitly write down, but there's no harm in it.
___
*[`internal/manifest/version.go` line 180 at r11](https://re [...]

2023-03-21 16:33 UTC, jbowens reviewed
> Reviewed 1 of 17 files at r1, 4 of 22 files at r12, 4 of 14 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: 17 of 34 files reviewed, 55 unresolved discussions (waiting on @bananabrick, @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`checkpoint.go` line 194 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR3ruEV1p3Wnu14WeQW:-NR3ruEV1p3Wnu14WeQX:b1b6ozd) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/checkpoint.go#L194)):*
> ```Go
> 	manifestSize := d.mu.versions.manifest.Size()
> 	optionsFileNum := d.optionsFileNum
> 	virtualBackingFiles := make(map[base.FileNum]struct{})
> ```

can we call this `versionBackingFiles` or `allBackingFiles`? the `virtual` here is mildly confusing
___
*[`checkpoint.go` line 378 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR3rQFs4R3NkOl9VtCH:-NR3rQFs4R3NkOl9VtCI:b9vp47l) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/checkpoint.go#L378)):*
> ```Go
> 					ve.RemovedBackingTables = append(ve.RemovedBackingTables, fileNum)
> 				}
> 			}
> ```

rather than adding two new arguments just to compute the intersection, should we add a single parameter `excludedBackingFiles` and put the onus on the caller to compute the intersection? 
___
*[`db.go` line 1891 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrjl5fCaHn_b3Of2uI:-NR3tR5OBFmSKyWoRscQ:bp9qmtp) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/db.go#L1891)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Got rid of the special casing for now. We would need `Reader.EstimatedDiskUsage` to work on virtual sstables, which requires further constraining of the bounds `start,end` to within the virtual sstable bounds, which is what I do in the read path changes.
</blockquote></details>

I think implementing `EstimatedDiskUsage` for virtual sstables by constraining the bounds is the best option, but I don't love how it can obscure physical disk space usage outside the virtual SST's bounds that is pinned by the virtual sstable's sole reference. In a sense, a single reference backing sstable is a part of the physical disk space usage of this keyspan.
___
*[`table_stats.go` line 477 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR3wC2nBF7juo21T5fx:-NR3wC2oEbl4sCPEzR0L:bnbenaq) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/table_stats.go#L477)):*
> ```Go
> 			//
> 			// TODO(bananabrick): See if we can include virtual sstables here to
> 			// get a more accurate estimate.
> ```

I think we should include virtual sstables here. We're not necessarily reclaiming any disk space by compacting them, but by the same token we may reclaim an _outsized_ portion of the physical file size if we're deleting the last reference (and so the compaction is especially beneficial at reducing space amplification). I think it would be reasonable to do the simple thing and just treat these the same as physical files with narrower bounds would be treated. The two competing over and under estimates may be a wash.
___
*[`version_set.go` line 782 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrqrqQ8SHaEsvxRaxl:-NR3yAi67bR0yjSlcdcm:biyx1pn) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/version_set.go#L782)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

We wouldn't. But it was an implicit invariant. I turned the fact that there should be no duplicate backing files passed into `addObsoleteLocked` into an invariant and I added a panic if there's duplicates and invariants are enabled.

Doesn't seem like a necessary invariant to explicitly write down, but there's no harm in it.
</blockquote></details>

Since we don't need to de-duplicate, I think we should put the entire de-duplication (eg, in a second `for` loop) behind the `invarinats.Enabled` flag.
___
*[`internal/manifest/version.go` line 365 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR3zc0U0ZJuhJ8AxS5C:-NR3zc0U0ZJuhJ8AxS5D:b-uplkfv) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/internal/manifest/version.go#L365)):*
> ```Go
> // after the relevant state has been set in the FileMetadata is not necessary
> // in tests which don't rely on BackingState.
> func (m *FileMetadata) Init() {
> ```

`Init` functions like this make me nervous because it's so easy to forget to invoke them.
___
*[`internal/manifest/version.go` line 428 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR4-TMG9gpbfQQluv2i:-NR4-TMG9gpbfQQluv2j:bt6iet4) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/internal/manifest/version.go#L428)):*
> ```Go
> 	}
> 
> 	return atomic.AddInt32(&m.BackingState.Atomic.latestVersionRefs, -1)
> ```

worth asserting (behind `invariants.Enabled`) that the return value `AddInt32` in both of the unref calls is ≥ 0


<!-- Sent from Reviewable.io -->

2023-03-22 19:25 UTC, itsbilal reviewed
Getting very close! I think these comments plus the ones Jackson left are the only suggestions I can think of.

> Reviewed 7 of 22 files at r12, 8 of 14 files at r16, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NR9m9xB4G4kaw-u9XDK:bw2cuq2)* status: all files reviewed, 55 unresolved discussions (waiting on @bananabrick, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`checkpoint.go` line 194 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR3ruEV1p3Wnu14WeQW:-NR9RrSx9JIvQVcBEojC:b-qezo8i) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/checkpoint.go#L194)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

can we call this `versionBackingFiles` or `allBackingFiles`? the `virtual` here is mildly confusing
</blockquote></details>

I second this
___
*[`version_set.go` line 88 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT3FVrD3EfUJ6G9Qx9:-NR9lnHu37j5n2t8JSZ3:b6dad5j) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L88)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

We want to pass virtual sstables into that function. The `addObsoleteLocked` function is called from `Version.Unref` and `Version.UnrefLocked`. Initially, I was only passing physical sst meta to `addObsoleteLocked`, but a suggestion was made during review that the we should let `addObsoleteLocked` handle virtual ssts being passed.

`obsolete []*fileMetadata` definition is accurate. It can be the file metadata associated with either a physical or virtual sstable which was recently obsoleted.

I added a comment with the explanation to `addObsoleteLocked`.
</blockquote></details>

Can you refer to the suggestion that was made to allow virtual ssts to be passed here? the way I see it, this function should only deal with backing states, as it isn't smart enough to know if a virtual sst has a backing state that's still in use.
___
*[`version_set.go` line 786 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR9lFjz8u8Enho6tpPa:-NR9lFk-AOQI5lDZXKWN:b-ufibv1) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/version_set.go#L786)):*
> ```Go
> //
> // DB.mu must be held when addObsoleteLocked is called.
> func (vs *versionSet) addObsoleteLocked(obsolete []*fileMetadata) {
> ```

This should take in `*BackingState` not `*FileMetadata`. Makes it clearer that this function can't be called with a virtual sst just because that virtual sst is no longer used, even if its backing state is still referenced somewhere. And also simplifies the comment above it a lot (eg. "The backing states aassociated with files in obsolete list must not appear more than once" -> "The backing states must not appear more than once")
___
*[`internal/manifest/version.go` line 274 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPYtvOL-moxpH2ts6zu:-NR9W1HSBFVfFa9zaffx:b-k4q42j) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/internal/manifest/version.go#L274)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Yes, and rather it'll be the Smallest/Largest overall bounds where we will constrain iterators, not just the point key bounds. We expect the range key state to be complete within Smallest/Largest, even if there aren't any point keys for large parts of the overall key space.
___
*[`internal/manifest/version.go` line 198 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR9Vl210oBvfA6jikEP:-NR9Vl210oBvfA6jikEQ:bdnj059) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/internal/manifest/version.go#L198)):*
> ```Go
> 	// Lower and upper bounds for the smallest and largest sequence numbers in
> 	// the table, across both point and range keys. For physical sstables, these
> 	// values are precise.
> ```

nit: s/precise/tight bounds? also probably worth saying that for virtual sstables, these values are loose bounds in that no keys with sequence numbers outside these bounds are expected, but there's no guarantee that there will be a key _at_ the largest/smallest seq num.
___
*[`internal/manifest/version.go` line 401 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR9ese-4v5sZXlfH79D:-NR9ese06gD-87pr3Ty_:bheqhc2) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/internal/manifest/version.go#L401)):*
> ```Go
> }
> 
> // Ref increments the ref count associated with the backing sstable.
> ```

I think it'd be best if this comment called out that this is meant for, say, iterator / read state refs, and the one for LatestRef can say that this is meant for Versions.


<!-- Sent from Reviewable.io -->

2023-03-23 22:29 UTC, bananabrick reviewed
Responded to the review. PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NRF_bFv6Vxq_TI2jZC5:b-8dedh7)* status: 27 of 34 files reviewed, 52 unresolved discussions (waiting on @itsbilal, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`checkpoint.go` line 194 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR3ruEV1p3Wnu14WeQW:-NRFWa9w10ojrKy2NrdU:bjmmszx) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/checkpoint.go#L194)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I second this
</blockquote></details>

But it's not all backing files or `BackingState` in the version. It's the `BackingState` which backs virtual sstables in latest version.
___
*[`checkpoint.go` line 378 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR3rQFs4R3NkOl9VtCH:-NRFYkXo3Q09Xp3ly9GI:b-fkp09k) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/checkpoint.go#L378)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

rather than adding two new arguments just to compute the intersection, should we add a single parameter `excludedBackingFiles` and put the onus on the caller to compute the intersection? 
</blockquote></details>

Yea, done.
___
*[`db.go` line 1891 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrjl5fCaHn_b3Of2uI:-NRFNNAaEoDofDh8_y_m:b-9twvwx) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/db.go#L1891)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think implementing `EstimatedDiskUsage` for virtual sstables by constraining the bounds is the best option, but I don't love how it can obscure physical disk space usage outside the virtual SST's bounds that is pinned by the virtual sstable's sole reference. In a sense, a single reference backing sstable is a part of the physical disk space usage of this keyspan.
</blockquote></details>

Technically we can just grab `BackingState.Size` once for virtual sstables. But it doesn't work for cases where the virtual sstable doesn't overlap with `start,end` but the physical sstable does.

Left it as is for now.
___
*[`table_stats.go` line 477 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR3wC2nBF7juo21T5fx:-NRFMgAw9Jg_KttMburO:b6w99d5) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/table_stats.go#L477)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think we should include virtual sstables here. We're not necessarily reclaiming any disk space by compacting them, but by the same token we may reclaim an _outsized_ portion of the physical file size if we're deleting the last reference (and so the compaction is especially beneficial at reducing space amplification). I think it would be reasonable to do the simple thing and just treat these the same as physical files with narrower bounds would be treated. The two competing over and under estimates may be a wash.
</blockquote></details>

Don't disagree. Turned the continue into a panic. We might have to call `Reader.EstimatedDiskUsage` which will only work for virtual sstables after the read path pr is up. Leaving the todo for now with updated wording.
___
*[`version_set.go` line 88 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT3FVrD3EfUJ6G9Qx9:-NRFHvTb-ce5oyQPPlwx:bnnomg) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L88)):*
https://reviewable.io/reviews/cockroachdb/pebble/2288#-NOLhoH--L-ZIxwTbViB

> as it isn't smart enough to know if a virtual sst has a backing state that's still in use.

None of the backing states of virtual sstables passed in can be in use. They're no longer referenced by any Version. Anyway, I'm passing in BackingState now.
___
*[`version_set.go` line 782 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPrqrqQ8SHaEsvxRaxl:-NRFM9LW9IIgDC6xbJS5:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/version_set.go#L782)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Since we don't need to de-duplicate, I think we should put the entire de-duplication (eg, in a second `for` loop) behind the `invarinats.Enabled` flag.
</blockquote></details>

Done.
___
*[`version_set.go` line 786 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR9lFjz8u8Enho6tpPa:-NRFLW0j1DIMO3-1PFIO:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/version_set.go#L786)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

This should take in `*BackingState` not `*FileMetadata`. Makes it clearer that this function can't be called with a virtual sst just because that virtual sst is no longer used, even if its backing state is still referenced somewhere. And also simplifies the comment above it a lot (eg. "The backing states aassociated with files in obsolete list must not appear more than once" -> "The backing states must not appear more than once")
</blockquote></details>

Done.
___
*[`internal/manifest/version.go` line 195 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPYwczREZ5gzvRxg-N8:-NR0TQWlBF_P748eg6Qy:b8q92wr) ([raw file](https://github.com/cockroachdb/pebble/blob/91ef869d7b1f0abcd6438b293adf5919e08db6b0/internal/manifest/version.go#L195)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

+1
</blockquote></details>

I can see the use for that, but I think we already get some type safety here. If a function is expecting `BackingState.FileNum` instead of `FileMetadata.FileNum`, then we can make the input parameter to the function a `*BackingState` and use the function that way. I plan to do this for some of the table cache functions in the read path.

But I left a TODO here to create a separate type for `BackingState.FileNum`, which I'll work in the read path pr.
___
*[`internal/manifest/version.go` line 365 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR3zc0U0ZJuhJ8AxS5C:-NREr1zx8x9lYSv2cQGg:b-wzto30) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/internal/manifest/version.go#L365)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

`Init` functions like this make me nervous because it's so easy to forget to invoke them.
</blockquote></details>

Same. But I don't know how to avoid it. The good news is that we only create FileMetadata during `runCompaction` and `ingest`.
___
*[`internal/manifest/version.go` line 401 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR9ese-4v5sZXlfH79D:-NREtlDVAjLP6gxBox1R:b-us2jkl) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/internal/manifest/version.go#L401)):*
Both `BackingState.Atomic.refs` and `BackingState.atomic.latestVersionRefs` have comments explaining what they're tracking.

>  that this is meant for, say, iterator / read state refs, and the one for LatestRef can say that this is meant for Versions.

Both are tracking references to the FileMetadata by Versions.
___
*[`internal/manifest/version.go` line 428 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR4-TMG9gpbfQQluv2i:-NREtRTG0sppD7L0qcqe:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/internal/manifest/version.go#L428)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

worth asserting (behind `invariants.Enabled`) that the return value `AddInt32` in both of the unref calls is ≥ 0
</blockquote></de [...]

2023-03-24 01:28 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: 22 of 34 files reviewed, 60 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @sumeerbhola)

___
*[`internal/manifest/version.go` line 325 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRG9KLm-2Nfe2tmHbaw:-NRG9KLm-2Nfe2tmHbax:b-upwgb2) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L325)):*
> ```Go
> //
> // See the comment above the FileMetadata type for sstable terminology.
> type BackingState struct {
> ```

[nit] "state" doesn't feel right, maybe `FileBacking` ? "FileBacking contains the metadata associated with a physical file; within a version, a FileBacking either backs a single physical sstable, or one or more virtual sstables."
___
*[`internal/manifest/version.go` line 333 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRGBRyw49f5DnXpVXdb:-NRGBRyw49f5DnXpVXdc:b-p15v48) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L333)):*
> ```Go
> 		// backing sst file from disk. The backing file is obsolete when the
> 		// reference count falls to zero.
> 		refs int32
> ```

I think we can switch these over to [atomic.Int32](https://pkg.go.dev/sync/atomic#Int32) (added in go 1.19)
___
*[`internal/manifest/version.go` line 341 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRGAJ2W8Gh-QGaCCua8:-NRGAJ2W8Gh-QGaCCua9:b-xpm345) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L341)):*
> ```Go
> 		// INVARIANT: latestVersionRefs <= refs.
> 		latestVersionRefs int32
> 		// VirtualizedSize is set iff the backing sst is only referred to by
> ```

Is this accurate? If this backing is used for a physical sst in the previous version, and a bunch of virtual ones in the latest version, won't it be set? Should it be "VirtualizedSize is set if the backing is used for virtual sstables in the latest version"?
___
*[`internal/manifest/version.go` line 367 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRGAi3tEHcL081mJPMb:-NRGAi3tEHcL081mJPMc:b-3yybxq) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L367)):*
> ```Go
> // after the relevant state has been set in the FileMetadata is not necessary
> // in tests which don't rely on BackingState.
> func (m *FileMetadata) Init() {
> ```

[nit] `Init` is too general, maybe`InitPhysical` or `InitPhysicalBacking`
___
*[`internal/manifest/version.go` line 372 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRGAxXA8WuekTzeTGCM:-NRGAxXA8WuekTzeTGCN:b-k1j9ce) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L372)):*
> ```Go
> 	}
> 	if m.BackingState == nil {
> 		m.BackingState = &BackingState{}
> ```

[nit] `&BackingState{Size: m.Size, FileNum: m.FileNum}`
___
*[`internal/manifest/version.go` line 378 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRGB6D576B9vUyovZW-:-NRGB6D576B9vUyovZW0:bp8jxaj) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L378)):*
> ```Go
> }
> 
> // ValidateVirtual should be called once the FileMetadata for a virtual sstable
> ```

[supernit] should first say what it does, "ValidateVirtual verifies that the fields of a virtual sstable are sound. It should be calle donce .."
___
*[`internal/manifest/version.go` line 399 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRGCSV1DV_Vf5QZ3HAQ:-NRGCSV1DV_Vf5QZ3HAR:b-rduc0q) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L399)):*
> ```Go
> 
> // Refs returns the refcount of backing sstable.
> func (m *FileMetadata) Refs() int32 {
> ```

[nit] `Refs()` is very close to`Ref()`, maybe `NumRefs()`. Or maybe `HasRefs()` since we only care if it's 0 or not.
___
*[`internal/manifest/version.go` line 409 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRGCvc56hyo9AvKrLO3:-NRGCvc56hyo9AvKrLO4:b-aq9v8k) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L409)):*
> ```Go
> 
> // Unref decrements the ref count associated with the backing sstable.
> func (m *FileMetadata) Unref() int32 {
> ```

[nit] maybe return `(hasRemainingRefs bool)` instead of the count (same for the Latest version)


<!-- Sent from Reviewable.io -->

2023-03-27 21:06 UTC, sumeerbhola requested changes
> Reviewed 3 of 24 files at r7, 9 of 22 files at r12, 7 of 14 files at r16, 1 of 2 files at r17, 12 of 12 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: all files reviewed, 63 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @RaduBerinde)

___
*[`checkpoint.go` line 279 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRZXBzl4a033PEVDXtM:-NRZXBzm-B4ltQoIaI2f:bz85na9) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/checkpoint.go#L279)):*
> ```Go
> 			}
> 
> 			backingState := f.BackingState
> ```

physical ssts also have a `BackingState`. I assume this computation is correct because `requiredBackingFiles` (which will include backing for physical ssts) is only used for subtracting from `virtualBackingFiles` and the latter only contains the ones backing virtual ssts (and because a backing sst cannot be backing both a physical and a virtual sst in a version). Is my understanding correct? If yes, this needs a code comment. Or better yet, lets scope `requiredBackingFiles` only to those needed for virtual ssts.
___
*[`table_stats.go` line 477 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR3wC2nBF7juo21T5fx:-NRZjWFdEvX4-Wb8xNDv:b-qk5am5) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/table_stats.go#L477)):*
> I think it would be reasonable to do the simple thing and just treat these the same as physical files with narrower bounds would be treated. 

+1
___
*[`version_set.go` line 520 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT6Q6O6dgd8Vkp8W_h:-NRZkqFB8qCFOF8TJ6lN:b4e38l4) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L520)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

> or a single step AccumulateIncompleteAndApply which is called on an empty BVE.

Doing this currently. We're still accumulating first within the function, applying, and then completing the incomplete version edit. 


If we want, instead of completing an incomplete version edit, we could just write two version edits. One where the last virtual sstable in a version associated with a backing table gets deleted. And a subsequent version edit which has the `RemovedBackingTables` entry. That way we can get rid of the incomplete version edit mess. But I think overall, even the current solution is pretty easy to understand.
</blockquote></details>

Current solution is good
___
*[`version_set.go` line 778 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRZlFSa7wnsWl5_3Nk2:-NRZlFSa7wnsWl5_3Nk3:bl7qkiq) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/version_set.go#L778)):*
> ```Go
> 
> // addObsoleteLocked will add the fileInfo associated with obsolete backing
> // sstables to the obsolete tables list. If virtual sstables are passed into
> ```

"If virtual sstables are passed into ..." seems stale since the parameter is now `[]*backingState`.
___
*[`internal/manifest/version.go` line 341 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRGAJ2W8Gh-QGaCCua8:-NRZnfHI5XG_RrpgW7Ri:bn3ya9r) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L341)):*
> Should it be "VirtualizedSize is set if the backing is used for virtual sstables in the latest version"?

sounds right
___
*[`internal/manifest/version_edit.go` line 739 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRZpsV-1IIb5bzGHc2k:-NRZpsV-1IIb5bzGHc2l:b1dfpvm) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version_edit.go#L739)):*
> ```Go
> 
> 	for _, fileNum := range b.RemovedBackingState {
> 		delete(backingStateMap, fileNum)
> ```

Will `b.RemovedBackingState` ever be non-empty, given that `ve.RemovedBackingTables` must be empty?
I think we should check the latter condition and return an error. 
___
*[`version_set_test.go` line 116 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NOr88OoA4VkA8UNyfOh:-NRZrsvF8XFKY8lBlZxC:bopi33q) ([raw file](https://github.com/cockroachdb/pebble/blob/f1717dc93d6325ccd5858fdc23ee0ec6cb68b820/version_set_test.go#L116)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I find it odd that we don't call updateReadStateLocked from within `logAndApply` and instead rely on the caller to make sure that the read state is updated.
</blockquote></details>

I think it was a choice based on drawing a code abstraction boundary around the version code, that does not know about memtables.
___
*[`version_set_test.go` line 36 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPK1yBz9ez74Lfz6GwV:-NRZsaOc4QAcRy3oeoBX:b-vmce5) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set_test.go#L36)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

This test is a bit clunky, but it gets the job done and I don't think we need a full data driven test here.
</blockquote></details>

We should consider adding a specialized randomized test that creates and deletes virtual ssts, and relies on strong invariant checking to uncover bugs in our manifest handling code.


<!-- Sent from Reviewable.io -->

2023-03-27 23:09 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: all files reviewed, 57 unresolved discussions (waiting on @itsbilal, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`checkpoint.go` line 279 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRZXBzl4a033PEVDXtM:-NR_AUR6BvHxZlMmwbn1:b-b4il9r) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/checkpoint.go#L279)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

physical ssts also have a `BackingState`. I assume this computation is correct because `requiredBackingFiles` (which will include backing for physical ssts) is only used for subtracting from `virtualBackingFiles` and the latter only contains the ones backing virtual ssts (and because a backing sst cannot be backing both a physical and a virtual sst in a version). Is my understanding correct? If yes, this needs a code comment. Or better yet, lets scope `requiredBackingFiles` only to those needed for virtual ssts.
</blockquote></details>

Made `requiredBackingFiles` only track virtual virtual ssts.
___
*[`table_stats.go` line 477 at r17](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NR3wC2nBF7juo21T5fx:-NR_C89c-vIW1RKvgCuL:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c81d4012693bad42487c0b629f07d61aa50e590c/table_stats.go#L477)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> I think it would be reasonable to do the simple thing and just treat these the same as physical files with narrower bounds would be treated. 

+1
</blockquote></details>

Done.
___
*[`version_set.go` line 520 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPT6Q6O6dgd8Vkp8W_h:-NR_C7YHCs2JLkYOYKBm:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set.go#L520)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Current solution is good
</blockquote></details>

Done.
___
*[`version_set.go` line 778 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRZlFSa7wnsWl5_3Nk2:-NR_CvaRCPBZ9v0aZQO-:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/version_set.go#L778)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

"If virtual sstables are passed into ..." seems stale since the parameter is now `[]*backingState`.
</blockquote></details>

Done.
___
*[`internal/manifest/version.go` line 325 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRG9KLm-2Nfe2tmHbaw:-NR_FTlH2nsO-hVcM-ff:b-aisivj) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L325)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] "state" doesn't feel right, maybe `FileBacking` ? "FileBacking contains the metadata associated with a physical file; within a version, a FileBacking either backs a single physical sstable, or one or more virtual sstables."
</blockquote></details>

Keeping this as is for now.
___
*[`internal/manifest/version.go` line 333 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRGBRyw49f5DnXpVXdb:-NR_FVjo4IGvxCscGclE:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L333)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think we can switch these over to [atomic.Int32](https://pkg.go.dev/sync/atomic#Int32) (added in go 1.19)
</blockquote></details>

Done.
___
*[`internal/manifest/version.go` line 399 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRGCSV1DV_Vf5QZ3HAQ:-NR_H7ls4ZsXIeB0QvQi:b-dfjrep) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L399)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `Refs()` is very close to`Ref()`, maybe `NumRefs()`. Or maybe `HasRefs()` since we only care if it's 0 or not.
</blockquote></details>

Going to keep this as is since we use the same naming scheme for `Version.Refs/Ref`.
___
*[`internal/manifest/version.go` line 409 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRGCvc56hyo9AvKrLO3:-NR_HI0-6plwzoUo7cx9:bcuzcrb) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L409)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe return `(hasRemainingRefs bool)` instead of the count (same for the Latest version)
</blockquote></details>

Going to keep this as is.
___
*[`internal/manifest/version_edit.go` line 739 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRZpsV-1IIb5bzGHc2k:-NR_HWQ8CSy5PD5xRp_D:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version_edit.go#L739)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Will `b.RemovedBackingState` ever be non-empty, given that `ve.RemovedBackingTables` must be empty?
I think we should check the latter condition and return an error. 
</blockquote></details>

Done.
___
*[`version_set_test.go` line 36 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPK1yBz9ez74Lfz6GwV:-NR_IrHI6r9_s-IEMXdZ:bhdk0vq) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set_test.go#L36)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We should consider adding a specialized randomized test that creates and deletes virtual ssts, and relies on strong invariant checking to uncover bugs in our manifest handling code.
</blockquote></details>

I believe this will be covered by metamorphic tests once Pebble is writing virtual sstables y default. We can be more precise about invariants regarding some of the data structures in the manifest code, but metamorphic tests should also implicitly check those invariants.

Either way, I'd like to merge such a randomized test in a separate pr if necessary.


<!-- Sent from Reviewable.io -->

2023-03-28 00:59 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 17 files at r1, 25 of 26 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352#-:-NR_iURk1uKdw23qQVKC:bg7igkv)* status: 33 of 34 files reviewed, 57 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @RaduBerinde)

___
*[`internal/manifest/version.go` line 325 at r18](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRG9KLm-2Nfe2tmHbaw:-NR_h2MCDdvXyklWdgEP:b-8u30fd) ([raw file](https://github.com/cockroachdb/pebble/blob/31a2012feb9868628da4e9b5b005001520fe42d7/internal/manifest/version.go#L325)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Keeping this as is for now.
</blockquote></details>

I like `FileBacking`, since it is more specific than `BackingState`
___
*[`version_set_test.go` line 36 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPK1yBz9ez74Lfz6GwV:-NR_hsl26A32on7IGaXG:b-pwm6bb) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set_test.go#L36)):*
> Either way, I'd like to merge such a randomized test in a separate pr if necessary.

That is fine. But let's see if there is a way to have more focused randomized testing of virtual ssts -- the metamorphic test is great but sometimes can take a long time to find bugs.


<!-- Sent from Reviewable.io -->

2023-03-28 19:05 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2352)* status: 33 of 34 files reviewed, 56 unresolved discussions (waiting on @itsbilal, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`internal/manifest/version.go` line 379 at r19](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NRdKGC1A3kEBSE3Rs_n:-NRdb-uC90iozYDrZ_L5:bb77ufg) ([raw file](https://github.com/cockroachdb/pebble/blob/0188a219e6d64f673cf053ca848b8f73cecc5ded/internal/manifest/version.go#L379)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I imagine the write path will call into this and that's why it's exported?
</blockquote></details>

Yes.
___
*[`version_set_test.go` line 36 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2352#-NPK1yBz9ez74Lfz6GwV:-NRdb1xl8rqmMzHc4KVM:brxp9sq) ([raw file](https://github.com/cockroachdb/pebble/blob/a40c7e0bf3e71d9b666c6ed03dabc93ffc40203c/version_set_test.go#L36)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> Either way, I'd like to merge such a randomized test in a separate pr if necessary.

That is fine. But let's see if there is a way to have more focused randomized testing of virtual ssts -- the metamorphic test is great but sometimes can take a long time to find bugs.
</blockquote></details>

Sounds good.


<!-- Sent from Reviewable.io -->

2023-03-28 19:27 UTC, merged