*: add skip-shared iteration mode to ScanInternal
cockroachdb/pebble pull request #2357
Opened 2023-02-23 20:56 UTC by itsbilal

This change adds a skip-shared iteration mode to ScanInternal(), allowing the caller to pass in a Visitor function to expose files in shareable levels (defined as L5 and below) instead of individually visiting all the keys in those files. The file's bounds are truncated to keys within the scan bounds before calling the visitor function. If a file in a shareable level is not marked as shared according to objstorage.Provider, we return a special error, allowing the caller to restart scanning in non-skip-shared mode or so.

2023-02-23 20:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2357)
<!-- Reviewable:end -->

2023-02-23 23:08 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @bananabrick and @itsbilal)

___
*[`internal_iterator.go` line 34 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NP-UAtL9DryLI55eVR6:-NP-UAtL9DryLI55eVR7:b-3xaraj) ([raw file](https://github.com/cockroachdb/pebble/blob/711f8d955614bb4cf4f40b50c8ab72b34f69427b/internal_iterator.go#L34)):*
> ```Go
> // construct a shared file's manifest.FileMetadata on another node.
> type SharedSSTMeta struct {
> 	sharedobjcat.SharedObjectMetadata
> ```

Rather than exposing this kind of internal metadata (and including it in higher level protos!), it would be better to let the objprovider encode it into an opaque buffer. That way the higher layer doesn't need any changes if we want to change it.

Something like this: https://github.com/RaduBerinde/pebble/commit/5001f16d9fe23c3f63a18e32fe516656b59777ac

One thing I try to keep in mind (at least as an example) - what if in the future we need a bigger CreatorID (e.g. that includes the cluster UUID). How hard would it be to add that? We would add a new tag in the SharedObjectBacking encoding, and we can still accept the old tag for backward compatibility.

I will try to get something like that merged soon if you agree.


<!-- Sent from Reviewable.io -->

2023-02-23 23:24 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[`db.go` line 1134 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NP-Z4yPBvqhXy6MkbZJ:-NP-Z4yPBvqhXy6MkbZK:b-vkvx3k) ([raw file](https://github.com/cockroachdb/pebble/blob/711f8d955614bb4cf4f40b50c8ab72b34f69427b/db.go#L1134)):*
> ```Go
> 		LowerBound: lower,
> 		UpperBound: upper,
> 	}, visitSharedFile != nil /* skipSharedLevels */)
> ```

[nit] extract out `skipSharedLevels := visitSharedFile != nil`

Btw couldn't this be an internal (unexported) option in `IterOptions`?
___
*[`internal_iterator.go` line 281 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NP-ZnaM3kGXBXSUgqWC:-NP-ZnaM3kGXBXSUgqWD:b-43g72w) ([raw file](https://github.com/cockroachdb/pebble/blob/711f8d955614bb4cf4f40b50c8ab72b34f69427b/internal_iterator.go#L281)):*
> ```Go
> 						return err
> 					}
> 					if !objMeta.IsShared() && !db.opts.private.disableProviderSharedFileCheck {
> ```

[nit] we already checked the flag


<!-- Sent from Reviewable.io -->

2023-02-24 17:34 UTC, itsbilal commented
*[`internal_iterator.go` line 34 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NP-UAtL9DryLI55eVR6:-NP3Ty7C70log94LoM7n:bc1n6xs) ([raw file](https://github.com/cockroachdb/pebble/blob/711f8d955614bb4cf4f40b50c8ab72b34f69427b/internal_iterator.go#L34)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Rather than exposing this kind of internal metadata (and including it in higher level protos!), it would be better to let the objprovider encode it into an opaque buffer. That way the higher layer doesn't need any changes if we want to change it.

Something like this: https://github.com/RaduBerinde/pebble/commit/5001f16d9fe23c3f63a18e32fe516656b59777ac

One thing I try to keep in mind (at least as an example) - what if in the future we need a bigger CreatorID (e.g. that includes the cluster UUID). How hard would it be to add that? We would add a new tag in the SharedObjectBacking encoding, and we can still accept the old tag for backward compatibility.

I will try to get something like that merged soon if you agree.

</blockquote></details>

I think that makes sense; my understanding was that `SharedObjectMetadata` would only contain the fields that are worth sharing, but on closer look that's probably incorrect.

We will likely need additional fields for sure, especially if we use multiple buckets (eg. one per region) and we'd need to create more `shared.Storage`'s for those. I think having Pebble own the encoding/decoding makes sense.

If you're down to do something like that, I'd support it. Also happy to take a stab at it myself - lemme know what you think.


<!-- Sent from Reviewable.io -->

2023-02-24 20:38 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @bananabrick and @RaduBerinde)

___
*[`db.go` line 1134 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NP-Z4yPBvqhXy6MkbZJ:-NP48BpB4-8Y2cHde9YH:br3d2at) ([raw file](https://github.com/cockroachdb/pebble/blob/711f8d955614bb4cf4f40b50c8ab72b34f69427b/db.go#L1134)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] extract out `skipSharedLevels := visitSharedFile != nil`

Btw couldn't this be an internal (unexported) option in `IterOptions`?
</blockquote></details>

Good point - fixed. 
___
*[`internal_iterator.go` line 281 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NP-ZnaM3kGXBXSUgqWC:-NP48Fiu9EYOD2f21z2-:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/711f8d955614bb4cf4f40b50c8ab72b34f69427b/internal_iterator.go#L281)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] we already checked the flag
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-24 22:43 UTC, RaduBerinde commented
*[`internal_iterator.go` line 34 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NP-UAtL9DryLI55eVR6:-NP4_pGZBnBSJ9MkYqtw:bgbviha) ([raw file](https://github.com/cockroachdb/pebble/blob/711f8d955614bb4cf4f40b50c8ab72b34f69427b/internal_iterator.go#L34)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I think that makes sense; my understanding was that `SharedObjectMetadata` would only contain the fields that are worth sharing, but on closer look that's probably incorrect.

We will likely need additional fields for sure, especially if we use multiple buckets (eg. one per region) and we'd need to create more `shared.Storage`'s for those. I think having Pebble own the encoding/decoding makes sense.

If you're down to do something like that, I'd support it. Also happy to take a stab at it myself - lemme know what you think.
</blockquote></details>

Great. I had started on that already, it should be easy. I did it on top of #2346 (and some other stuff on top of that), I'll finalize it once I get more stuff merged.


<!-- Sent from Reviewable.io -->

2023-02-27 14:56 UTC, sumeerbhola requested changes
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[`internal_iterator.go` line 31 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPILCce7F033WS53Toj:-NPILCce7F033WS53Tok:brkuvdg) ([raw file](https://github.com/cockroachdb/pebble/blob/dde8a22456209a2a9ac7d686723790b80b8ead52/internal_iterator.go#L31)):*
> ```Go
> // to this Pebble instance and can be ingested by other Pebble instances, or
> // belongs to another Pebble instance and can be ingested by this Pebble
> // instance. This struct must contain all fields that are necessary to
> ```

nit: this phrasing was a bit confusing for me. It sounds to me like SharedSSTMeta is what is being sent around between different Pebble instances, so it makes sense that this comment is talking about both the Pebble instance that is "exporting" it and one that is "importing" it. But the one exporting it is not necessarily the creator (it could have imported it in the past). It would be good to be clearer in this comment -- maybe I am nitpicking about the lack of a clear definition of "belongs" -- I suppose it includes the case I mentioned in that even if the creator is different it currently also "belongs" to the exporting Pebble.
___
*[`internal_iterator.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPIM8BOBSwLcah0-WPO:-NPIM8BOBSwLcah0-WPP:be8o5ne) ([raw file](https://github.com/cockroachdb/pebble/blob/dde8a22456209a2a9ac7d686723790b80b8ead52/internal_iterator.go#L38)):*
> ```Go
> 	// Smallest and Largest internal keys for the overall bounds. The kind and
> 	// SeqNum of these will reflect what is physically present on the source
> 	// Pebble instance; it's up to the ingesting instance to set the trailer
> ```

why would the ingesting instance need to fix these bounds if they are already truncated to the scan bounds?
___
*[`options.go` line 185 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPIMky-3Xp7_d2uQbIa:-NPIMky-3Xp7_d2uQbIb:bliczci) ([raw file](https://github.com/cockroachdb/pebble/blob/dde8a22456209a2a9ac7d686723790b80b8ead52/options.go#L185)):*
> ```Go
> 	// skipSharedLevels skips levels that are shareable (level >=
> 	// sharedLevelStart). Only valid with scanInternalIterator.
> 	skipSharedLevels bool
> ```

is it very inconvenient to do
```
type ScanInternalOptions struct {
   IterOptions
   skipSharedLevels bool
}
```
___
*[`options.go` line 875 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPIMaxT7r2p61x-BeFA:-NPIMaxT7r2p61x-BeFB:b-pbnmb1) ([raw file](https://github.com/cockroachdb/pebble/blob/dde8a22456209a2a9ac7d686723790b80b8ead52/options.go#L875)):*
> ```Go
> 		// that all files in L5 and L6 are shared, even if the Provider disagrees
> 		// or there is no provider. Used only in tests
> 		disableProviderSharedFileCheck bool
> ```

nit: can you call this testingDisableProviderSharedFileCheck


<!-- Sent from Reviewable.io -->

2023-02-27 19:28 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NPJLCFyE6aPzFjnCoaY:b-814g8k)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @bananabrick, @itsbilal, and @sumeerbhola)

___
*[`internal_iterator.go` line 31 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPILCce7F033WS53Toj:-NPJJDmh8VaSldll9x8N:b-j0uqjm) ([raw file](https://github.com/cockroachdb/pebble/blob/dde8a22456209a2a9ac7d686723790b80b8ead52/internal_iterator.go#L31)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: this phrasing was a bit confusing for me. It sounds to me like SharedSSTMeta is what is being sent around between different Pebble instances, so it makes sense that this comment is talking about both the Pebble instance that is "exporting" it and one that is "importing" it. But the one exporting it is not necessarily the creator (it could have imported it in the past). It would be good to be clearer in this comment -- maybe I am nitpicking about the lack of a clear definition of "belongs" -- I suppose it includes the case I mentioned in that even if the creator is different it currently also "belongs" to the exporting Pebble.
</blockquote></details>

No you're correct, the use of "belongs" is pretty ambiguous here. I've reworded the comment, let me know if this makes more sense now.
___
*[`internal_iterator.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPIM8BOBSwLcah0-WPO:-NPJJKON5OuCymDFtMIq:bus05a2) ([raw file](https://github.com/cockroachdb/pebble/blob/dde8a22456209a2a9ac7d686723790b80b8ead52/internal_iterator.go#L38)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why would the ingesting instance need to fix these bounds if they are already truncated to the scan bounds?
</blockquote></details>

The ingesting instance will only need to set the trailer, not the user key. The user key truncation we do on the sender side and in this PR.

I guess we could also do trailer substitution on the sender side, but I find it more intuitive to have the recipient take care of sequence numbers. Eg. the metadata we send could be `foo#354,SET - foobar#596,SET`, and the recipient would have to set both seqnums in the bounds to 3 assuming this is an L5 SST, and also do the appropriate read-time trailer substitution.
___
*[`options.go` line 185 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPIMky-3Xp7_d2uQbIa:-NPJKVKZ2Ffogz7NSdh2:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/dde8a22456209a2a9ac7d686723790b80b8ead52/options.go#L185)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is it very inconvenient to do
```
type ScanInternalOptions struct {
   IterOptions
   skipSharedLevels bool
}
```
</blockquote></details>

Done.
___
*[`options.go` line 875 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPIMaxT7r2p61x-BeFA:-NPJKfJp1r13CkEJjXr5:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/dde8a22456209a2a9ac7d686723790b80b8ead52/options.go#L875)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: can you call this testingDisableProviderSharedFileCheck
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-27 19:42 UTC, sumeerbhola reviewed
looks good, but I didn't look carefully since others are primary reviewers.

> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NPJOCpH50dQF-fV8RE9:b76jaf9)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[`internal_iterator.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPIM8BOBSwLcah0-WPO:-NPJMSri7dVJYlaSE9J3:b-nkkh9q) ([raw file](https://github.com/cockroachdb/pebble/blob/dde8a22456209a2a9ac7d686723790b80b8ead52/internal_iterator.go#L38)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The ingesting instance will only need to set the trailer, not the user key. The user key truncation we do on the sender side and in this PR.

I guess we could also do trailer substitution on the sender side, but I find it more intuitive to have the recipient take care of sequence numbers. Eg. the metadata we send could be `foo#354,SET - foobar#596,SET`, and the recipient would have to set both seqnums in the bounds to 3 assuming this is an L5 SST, and also do the appropriate read-time trailer substitution.
</blockquote></details>

nit: If this is only the seqnum substitution (and not the key kind) could you specify that in the comment?

Presumably we won't fiddle with the seqnum when encountering a `InternalKeyRangeDeleteSentinel`.


<!-- Sent from Reviewable.io -->

2023-02-27 21:11 UTC, itsbilal reviewed
TFTR! I'll wait for #2362 to land, and then rebase this on top of it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NPJhe8h3kRq7_NGoaaK:batd72u)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @bananabrick, @itsbilal, and @sumeerbhola)

___
*[`internal_iterator.go` line 38 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPIM8BOBSwLcah0-WPO:-NPJhd7K69Rov23wAxVE:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/dde8a22456209a2a9ac7d686723790b80b8ead52/internal_iterator.go#L38)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: If this is only the seqnum substitution (and not the key kind) could you specify that in the comment?

Presumably we won't fiddle with the seqnum when encountering a `InternalKeyRangeDeleteSentinel`.

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-28 21:51 UTC, itsbilal commented
I've rebased on top of master and addressed the TODO about SharedObjectBacking, this is ready for another look.

2023-02-28 23:07 UTC, RaduBerinde reviewed
Posted some comments. Would be good to get a second pair of eyes on all the key logic.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NPPGg0R8anUcNWbxmwf:blne2ui)* status: 1 of 7 files reviewed, 13 unresolved discussions (waiting on @bananabrick, @itsbilal, and @sumeerbhola)

___
*[`internal_iterator.go` line 142 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPDnN45Y_VA_ArG2g2:-NPPDnN45Y_VA_ArG2g3:bs12qxh) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L142)):*
> ```Go
> 	}
> 	// Fast path: file is entirely within [lower, upper).
> 	if cmp(lower, file.Smallest.UserKey) <= 0 && cmp(upper, file.Largest.UserKey) > 0 {
> ```

We should save these results (e.g. `needLowerTruncate, needUpperTruncate`) and use them below. We'll save some comparisons and also ensure that the checks are actually the same (see below).
___
*[`internal_iterator.go` line 160 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPAxcd0kN6y2OKp5Ig:-NPPAxcd0kN6y2OKp5Ih:b-60mxo6) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L160)):*
> ```Go
> 		return nil, err
> 	}
> 	if iter != nil {
> ```

In what cases can `newIters` return a nil `iter` in a non-error case? This doesn't seem to be well documented. I couldn't find a return path that actually returns that (in `tableCacheShard.newIters` at least). Even if it's empty, I'd expect a non-nil iterator that just returns nothing.

I'd argue the same about the range iterator, we should have an "empty" implementation so you don't need to special-case `nil` (that'd be a separate change though of course).
___
*[`internal_iterator.go` line 164 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPA3JF23joYh6iobhl:-NPPA3JF23joYh6iobhm:btyjl1o) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L164)):*
> ```Go
> 	}
> 	if rangeDelIter != nil {
> 		rangeDelIter = keyspan.Truncate(cmp, rangeDelIter, lower, upper, nil, nil)
> ```

[nit] shouldn't `newIters` do this internally when we have a `LowerBound`/`UpperBound`? (maybe an extra IterOption?)
___
*[`internal_iterator.go` line 206 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPDdjABQpaiTLV20a7:-NPPDdjABQpaiTLV20a8:b-2z6p5s) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L206)):*
> ```Go
> 	// Check if we need to truncate on the right side. This means finding a new
> 	// LargestPointKey and LargestRangeKey that is < upper.
> 	if cmp(upper, file.Largest.UserKey) < 0 {
> ```

Shouldn't this be `<= 0`? (if yes, maybe add a test for this case).
___
*[`internal_iterator.go` line 212 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPFujK8u_GVXuj-Mk4:-NPPFujK8u_GVXuj-Mk5:b-r3zjoi) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L212)):*
> ```Go
> 			key, _ := iter.SeekLT(upper, base.SeekLTFlagsNone)
> 			if key != nil {
> 				sst.LargestPointKey.UserKey = append(sst.LargestPointKey.UserKey[:0], key.UserKey...)
> ```

[nit] This could be a `CopyFrom` method on `InternalKey`
___
*[`internal_iterator.go` line 245 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPFSkL5GJn231OP7cM:-NPPFSkL5GJn231OP7cN:bw035oe) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L245)):*
> ```Go
> 		}
> 	}
> 	switch {
> ```

I'm surprised we don't already have helper code for this kind of thing.
___
*[`internal_iterator.go` line 259 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPP83Lc3banIehE46HZ:-NPP83Lc3banIehE46H_:b57jc7f) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L259)):*
> ```Go
> 	// have any keys within those bounds. Skip such files.
> 	if len(sst.Smallest.UserKey) == 0 {
> 		return nil, nil
> ```

[nit] Returning a nil result is a bit surprising and error-prone, maybe also add a `shouldSkip` return value
___
*[`internal_iterator.go` line 298 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPP7ln5CiWIcZEn7OXa:-NPP7ln5CiWIcZEn7OXb:blvdd4u) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L298)):*
> ```Go
> 					}
> 					if !objMeta.IsShared() {
> 						return ErrInvalidSkipSharedIteration
> ```

Add an `errors.Wrap()` with the FileNum
___
*[`options.go` line 878 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPP8SIkDsBTG2bjR9Mm:-NPP8SIkDsBTG2bjR9Mn:b-b4xiy2) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/options.go#L878)):*
> ```Go
> 		// pretend that all files in L5 and L6 are shared, even if the Provider
> 		// disagrees or there is no provider. Used only in tests.
> 		testingDisableProviderSharedFileCheck bool
> ```

Do we really need this? We have in-memory shared.Storage implementation available
___
*[`objstorage/shared_backing.go` line 28 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPP6wnpArFeTogttCJk:-NPP6wnpArFeTogttCJl:b-8xjb4h) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/objstorage/shared_backing.go#L28)):*
> ```Go
> 		return err.Error()
> 	}
> 	return fmt.Sprintf("(creatorID=%s,FileNum=%s)", meta.Shared.CreatorID, meta.Shared.CreatorFileNum)
> ```

[nit] different capitalization for the two


<!-- Sent from Reviewable.io -->

2023-03-01 00:48 UTC, bananabrick reviewed
Nice.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NPPcxX39Ck9Bm-Y9cKu:b-83sjo4)* status: 1 of 7 files reviewed, 17 unresolved discussions (waiting on @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`db.go` line 1121 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPP2Q6EKEJP4BUQMvr:-NPPP2Q6EKEJP4BUQMvs:b-m9o61y) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/db.go#L1121)):*
> ```Go
> // their metadatas truncated to [lower, upper) and passed into visitSharedFile.
> // ErrInvalidSkipSharedIteration is returned if visitSharedFile is not nil and an
> // sstable in L5 or L6 is found that is not in shared storage according to
> ```

It would help me if an example of the case where an sstable can be found in L5/L6 and not shared storage was listed here. I'm assuming it has to do with Pebble starting without shared storage, and then transitioning over to shared storage?
___
*[`db.go` line 1143 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPPfxj8DXBvJwJW6Ir:-NPPPfxj8DXBvJwJW6Is:bgtp8d2) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/db.go#L1143)):*
> ```Go
> 
> // NewInternalIter constructs and returns a new scanInternalIterator on this db.
> // If skipSharedLevels is true, levels below sharedLevelsStart are *not* added
> ```

nit: "If scanInternalOptions.skipSharedLevels is true ...".
___
*[`internal_iterator.go` line 160 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPAxcd0kN6y2OKp5Ig:-NPPb9Oe6QIm_Zh-skjw:b-b8rbjs) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L160)):*
> In what cases can newIters return a nil iter in a non-error case? This doesn't seem to be well documented. I couldn't find a return path that actually returns that (in tableCacheShard.newIters at least). Even if it's empty, I'd expect a non-nil iterator that just returns nothing.

I think it won't ever be nil. We have some places in the code like the `ingestTargetLevel` function which don't check if the iterator is nil.
___
*[`internal_iterator.go` line 191 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPaNyfCjowmXGlErEa:-NPPaNyfCjowmXGlErEb:b-ne04ag) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L191)):*
> ```Go
> 			if span != nil && (len(sst.SmallestPointKey.UserKey) == 0 || base.InternalCompare(cmp, span.SmallestKey(), sst.SmallestPointKey) < 0) {
> 				sst.SmallestPointKey.UserKey = append(sst.SmallestPointKey.UserKey[:0], span.Start...)
> 				sst.SmallestPointKey.Trailer = base.MakeTrailer(span.LargestSeqNum(), InternalKeyKindRangeDelete)
> ```

I can't figure out why we use `span.LargestSeqNum` and not `span.SmallestKey().Trailer` here. I'm missing some context, I think.
___
*[`internal_iterator.go` line 206 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPDdjABQpaiTLV20a7:-NPPYEoWDi9INZHSMQQg:b-65o3lh) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L206)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Shouldn't this be `<= 0`? (if yes, maybe add a test for this case).
</blockquote></details>

+1. I believe this should be <= 0.
___
*[`internal_iterator.go` line 245 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPFSkL5GJn231OP7cM:-NPPccMpA6bVdvrAvdF3:bax8lni) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L245)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'm surprised we don't already have helper code for this kind of thing.
</blockquote></details>

We do, but it's tightly coupled with the `FileMetadata`. See `FileMetadata.{ExtendPointKeyBounds, ExtendRangeKeyBounds}`.
___
*[`internal_iterator.go` line 285 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPTszvBdo7qb5YN84e:-NPPTszvBdo7qb5YN84f:b-fr6olt) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L285)):*
> ```Go
> 	if visitSharedFile != nil {
> 		if provider != nil && !db.opts.private.testingDisableProviderSharedFileCheck {
> 			panic("expected non-nil Provider in skip-shared iteration mode")
> ```

`visitSharedFile != nil`, so we're in skip-shared iteration mode. In this mode, we expect `provider != nil`. Should we be panicking if the `provider == nil`?

I think the `db.objProvider` is set on `Open`, so would this always be non nil always, unless we unset it after `Open`.


<!-- Sent from Reviewable.io -->

2023-03-01 00:53 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357)* status: 1 of 7 files reviewed, 18 unresolved discussions (waiting on @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`internal_iterator.go` line 91 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPe3gX5TzXHTl_E_85:-NPPe3gX5TzXHTl_E_86:bcmmpow) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L91)):*
> ```Go
> // replication. For use with {db,snapshot}.ScanInternal().
> //
> // scanInternalIterator is allowed to ignorepoint keys deleted by range deletions,
> ```

"ignore point" instead of ignorepoint
___
*[`internal_iterator.go` line 191 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPaNyfCjowmXGlErEa:-NPPdlDr0-GcBNhWX93W:bnqq3k9) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L191)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I can't figure out why we use `span.LargestSeqNum` and not `span.SmallestKey().Trailer` here. I'm missing some context, I think.
</blockquote></details>

Are we changing the key kind?


<!-- Sent from Reviewable.io -->

2023-03-09 18:51 UTC, itsbilal reviewed
TFTRs!

> Dismissed @bananabrick and @sumeerbhola from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NQ6hlmE26XqE86bulVp:bz5mair)* status: 0 of 8 files reviewed, 11 unresolved discussions (waiting on @bananabrick, @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`db.go` line 1121 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPP2Q6EKEJP4BUQMvr:-NQ6-TW48OPMp6qwapR5:b-yf2u0r) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/db.go#L1121)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

It would help me if an example of the case where an sstable can be found in L5/L6 and not shared storage was listed here. I'm assuming it has to do with Pebble starting without shared storage, and then transitioning over to shared storage?
</blockquote></details>

That's one possible case. Others would be where we make the provider smart enough to allow migrations to shared storage. This use-case explicitly came up in one of the meetings (was it a standup?) where we felt it was a good idea to account for partially-shared cases from the start.
___
*[`db.go` line 1205 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPSesH18py2mdBzEnju:-NQ67Lky2p-EQfco9zCc:b6golgv) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/db.go#L1205)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what would cause `i.rangeKey != nil` -- I thought we were initializing this `scanInternalIterator` for the first time here.
</blockquote></details>

Yeah, it will never be the case. Fixed.
___
*[`internal_iterator.go` line 91 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPe3gX5TzXHTl_E_85:-NQ67hyo2MiDVrYNUm99:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L91)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

"ignore point" instead of ignorepoint
</blockquote></details>

Done.
___
*[`internal_iterator.go` line 160 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPAxcd0kN6y2OKp5Ig:-NQ698Cm6of4lnywnzvF:b4tz7f9) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L160)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

> In what cases can newIters return a nil iter in a non-error case? This doesn't seem to be well documented. I couldn't find a return path that actually returns that (in tableCacheShard.newIters at least). Even if it's empty, I'd expect a non-nil iterator that just returns nothing.

I think it won't ever be nil. We have some places in the code like the `ingestTargetLevel` function which don't check if the iterator is nil.
</blockquote></details>

I just had this as a defensive case. Removed.
___
*[`internal_iterator.go` line 164 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPA3JF23joYh6iobhl:-NQ69PgO4A46-AuailGr:b-65pk2u) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L164)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] shouldn't `newIters` do this internally when we have a `LowerBound`/`UpperBound`? (maybe an extra IterOption?)
</blockquote></details>

The one for rangedels does not. That could change with some of the virtual sstable work, but currently we rely on read-time truncation (we have similar logic in the compaction input iter creation code).
___
*[`internal_iterator.go` line 191 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPaNyfCjowmXGlErEa:-NQ6AlFF5byRRjnVsH2U:b5mfwcp) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L191)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Are we changing the key kind?
</blockquote></details>

It should be logically equivalent. We aren't changing anything. Just makes the contents of the trailer more obvious. Either way I've changed to smallestKey().Trailer.
___
*[`internal_iterator.go` line 206 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPDdjABQpaiTLV20a7:-NQ6f1i3EztaHwPKX_E0:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L206)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

+1. I believe this should be <= 0.
</blockquote></details>

Done.
___
*[`internal_iterator.go` line 212 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPFujK8u_GVXuj-Mk4:-NQ6f33H0Bd5t4ygrNq8:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L212)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This could be a `CopyFrom` method on `InternalKey`
</blockquote></details>

Done.
___
*[`internal_iterator.go` line 285 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPTszvBdo7qb5YN84e:-NQ6Hq56ASh4uTSNYyR-:b-2vorx5) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L285)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

`visitSharedFile != nil`, so we're in skip-shared iteration mode. In this mode, we expect `provider != nil`. Should we be panicking if the `provider == nil`?

I think the `db.objProvider` is set on `Open`, so would this always be non nil always, unless we unset it after `Open`.
</blockquote></details>

Good catch, I meant provider == nil.
___
*[`internal_iterator.go` line 325 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPSioI0Ao3TigHWZtv0:-NQ6ctPgEuSVLhCoG1ku:bh3d1hz) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L325)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we remove RangeKeySets, RangeKeyUnsets that are covered by a RangeKeyDelete?
And what about RangeKeySets that have been unset?
</blockquote></details>

Yes, we remove them in both cases. And return the RangeKeyDelete/rangeKeyUnset that did the unsetting/deleting.
___
*[`internal_iterator.go` line 330 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPSiZWJ4CcqQoqPg_J1:-NQ6cyRsDXLRDNYMUPkC:by2hwoi) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L330)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Multiple overlapping randedels are being collapsed, because of `rangeDel.LargestSeqNum()`, yes?
</blockquote></details>

That is correct, we're only returning the highest seqnum for each fragment.
___
*[`internal_iterator.go` line 335 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPShTw-1q1pCIMogeM1:-NQ6dERB1eobHdrn0Cqo:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L335)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: instead of using `iter.pointKeyIter.Span()` here it would be clearer to call the equivalent `iter.unsafeRangeDel()` to make it obvious that this span we are using is a rangedel.
</blockquote></details>

Done.
___
*[`internal_iterator.go` line 339 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPShiJnCxS1lA4alo2X:-NQ6dNB6ARgeQVQPJHTw:b-fts1bh) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L339)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are we collap [...]

2023-03-09 21:23 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357)* status: 0 of 8 files reviewed, 11 unresolved discussions (waiting on @bananabrick, @itsbilal, and @RaduBerinde)

___
*[`internal_iterator.go` line 339 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPShiJnCxS1lA4alo2X:-NQ7EHYK2u5DtsnHRKsE:bert9wv) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L339)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We're not. The caller would be responsible for collapsing point keys. Should we do that here?
</blockquote></details>

It is going to be more work for the caller to do this, so may be worth doing this in one place. It's your choice -- I don't have a strong opinion.

btw, I suspect we will evolve this internal scan to also cover the tool use case in https://github.com/cockroachdb/pebble/issues/1996#issuecomment-1452658990, and at that point we will probably add some options for how much collapsing we want from the scan.


<!-- Sent from Reviewable.io -->

2023-03-16 23:08 UTC, itsbilal reviewed
Added point-key collapsing, PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NQgfeTK5N9-DfKY1Aac:b-wc269b)* status: 0 of 8 files reviewed, 11 unresolved discussions (waiting on @bananabrick, @RaduBerinde, and @sumeerbhola)

___
*[`internal_iterator.go` line 339 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPShiJnCxS1lA4alo2X:-NQgfchT1EgBMMDSZZlx:b-sx745r) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/internal_iterator.go#L339)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It is going to be more work for the caller to do this, so may be worth doing this in one place. It's your choice -- I don't have a strong opinion.

btw, I suspect we will evolve this internal scan to also cover the tool use case in https://github.com/cockroachdb/pebble/issues/1996#issuecomment-1452658990, and at that point we will probably add some options for how much collapsing we want from the scan.

</blockquote></details>

Done. This is ready for another look.


<!-- Sent from Reviewable.io -->

2023-03-30 16:20 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @bananabrick, @itsbilal, and @sumeerbhola)

___
*[`options.go` line 878 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPP8SIkDsBTG2bjR9Mm:-NRnJG61DH9XKwLp0Efz:b-xmedx4) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/options.go#L878)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We need the provider to mention that the file is shared, right? Is there a way to force that?
</blockquote></details>

What I mean, can't we wire up the logic to create L5+ objects as shared (should be a ~1 line change in compaction.go?), and then set up the scan_internal test to use an in-mem shared.Storage.


<!-- Sent from Reviewable.io -->

2023-03-30 16:49 UTC, RaduBerinde reviewed
The pointCollapsingIter has a ton of cases, there is no way we are testing all of them.. Is there a way to have a randomized test or somehow hook it up to the metamorphic test? Perhaps something that (at least partially) checks the results of the `pointCollpasingIter` against keys as returned by `Db.Get()`? Or something that gets the results of `pointCollapsingIter` for a random range, then clears the random range, and repopulates it with the results (and this should be a no-op as far as the external API is concerned)?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NRnLx669BfnN8ypwhqn:bfx4b68)* status: 0 of 9 files reviewed, 12 unresolved discussions (waiting on @bananabrick, @itsbilal, and @sumeerbhola)

___
*[`scan_internal.go` line 117 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NRnL9kPAPHXoxLpp2fQ:-NRnL9kPAPHXoxLpp2fR:bc3xnni) ([raw file](https://github.com/cockroachdb/pebble/blob/060327b4d4a7ca08bee1d4e33e055b2f0278e67f/scan_internal.go#L117)):*
> ```Go
> 	merge       base.Merge
> 	err         error
> 	iterKey     *InternalKey
> ```

The mechanics of when iterKey is updated and when it is &savedKey are worth documenting here. They feel a bit fragile to me.. would adding a flag to use instead of doing `iterKey == &savedKey` help?


<!-- Sent from Reviewable.io -->

2023-04-03 18:47 UTC, itsbilal reviewed
TFTR! On the testing piece, I plan to add a randomized test when we also have the foreign sstable iterator for levels below L5, to verify that keys observed by the top level iterator are the same whether seen through the regular iterator stack, or a disaggregated iterator stack (which will use pointCollapsingIter). ScanInternal is sort of not the best place to do that because we don't have a good way to interpret the shared files. Does that make sense?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NS7QfhM9pgbOhUXKsDe:b1t7pox)* status: 0 of 10 files reviewed, 11 unresolved discussions (waiting on @bananabrick, @RaduBerinde, and @sumeerbhola)

___
*[`options.go` line 878 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPP8SIkDsBTG2bjR9Mm:-NS7D_XPBdhh8mNcLB9x:bw3nl9s) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/options.go#L878)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What I mean, can't we wire up the logic to create L5+ objects as shared (should be a ~1 line change in compaction.go?), and then set up the scan_internal test to use an in-mem shared.Storage.
</blockquote></details>

Ah right, I missed that we can just pass that option there. Done; thanks for mentioning!
___
*[`scan_internal.go` line 117 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NRnL9kPAPHXoxLpp2fQ:-NS7L6rl-2uNFAfxaEqA:bs14ijr) ([raw file](https://github.com/cockroachdb/pebble/blob/060327b4d4a7ca08bee1d4e33e055b2f0278e67f/scan_internal.go#L117)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The mechanics of when iterKey is updated and when it is &savedKey are worth documenting here. They feel a bit fragile to me.. would adding a flag to use instead of doing `iterKey == &savedKey` help?
</blockquote></details>

I've clarified the use of the two fields in a comment here, but yes the idea is that only `findNextEntry` would need to care about the distinction between the two uses ,while all other methods can just set `iterKey` like we do in all the other internal iterators. And `findNextEntry` does have a short comment already talking about this.


<!-- Sent from Reviewable.io -->

2023-04-03 20:15 UTC, RaduBerinde reviewed
Yeah, sounds good!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NS7kBpk2DxpdSRrEyCn:b-kbc424)* status: 0 of 10 files reviewed, 10 unresolved discussions (waiting on @bananabrick, @itsbilal, and @sumeerbhola)

___
*[`options.go` line 878 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPP8SIkDsBTG2bjR9Mm:-NS7kbrQ9Z41yMWWo4Lq:b-wdj8zi) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/options.go#L878)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Ah right, I missed that we can just pass that option there. Done; thanks for mentioning!
</blockquote></details>

Nice, thanks!
___
*[`scan_internal.go` line 117 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NRnL9kPAPHXoxLpp2fQ:-NS7jiin0XLzjN9-j0cz:b2f0pk7) ([raw file](https://github.com/cockroachdb/pebble/blob/060327b4d4a7ca08bee1d4e33e055b2f0278e67f/scan_internal.go#L117)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I've clarified the use of the two fields in a comment here, but yes the idea is that only `findNextEntry` would need to care about the distinction between the two uses ,while all other methods can just set `iterKey` like we do in all the other internal iterators. And `findNextEntry` does have a short comment already talking about this.
</blockquote></details>

Thanks, the comment is useful!
___
*[`scan_internal.go` line 124 at r10](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NS7jHeAAXxyq8IaoXEL:-NS7jHeAAXxyq8IaoXEM:b-o9m44l) ([raw file](https://github.com/cockroachdb/pebble/blob/2c49fb4ae186c7346e753040b8df0621ef6b8b34/scan_internal.go#L124)):*
> ```Go
> 	// comments in findNextEntry on how this field is used.
> 	//
> 	// At the end of a positioning call,if pos == pcIterPosNext, iterKey is
> ```

[supernit] reformat like this:
```
At the end of a positioning call:
 - if pos == pcIterPosNext, ...
 - if pos == pcIterPosCur, ...
```


<!-- Sent from Reviewable.io -->

2023-04-06 19:32 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NSN2aW8C_FTQpdg-4Q6:b-814g8k)* status: 0 of 10 files reviewed, 8 unresolved discussions (waiting on @bananabrick and @sumeerbhola)

___
*[`scan_internal.go` line 124 at r10](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NS7jHeAAXxyq8IaoXEL:-NSN2YGDDpsXmDrsXECZ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/2c49fb4ae186c7346e753040b8df0621ef6b8b34/scan_internal.go#L124)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[supernit] reformat like this:
```
At the end of a positioning call:
 - if pos == pcIterPosNext, ...
 - if pos == pcIterPosCur, ...
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-07 16:07 UTC, sumeerbhola submitted a review, later dismissed
(drive-by)

> Reviewed 1 of 8 files at r6, 3 of 8 files at r8, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NSRT9rz1DTEEYXt2Vi9:b-y45lkk)* status: 7 of 10 files reviewed, 12 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[`scan_internal.go` line 54 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSRLxs64lZlh-UvCQaS:-NSRLxs64lZlh-UvCQaT:b5fwuyv) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L54)):*
> ```Go
> 	// to remain unchanged by the ingesting instance.
> 	//
> 	// Note that these bounds could
> ```

nit: stale line wrapping
___
*[`scan_internal.go` line 101 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSRMnan2HRn4hFslZfJ:-NSRMnan2HRn4hFslZfK:b-p27rww) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L101)):*
> ```Go
> 
> // pointCollapsingIterator is an internalIterator that collapses point keys and
> // returns at most one point internal key for each user key. Merges are merged,
> ```

I thought we were going to disallow Merge, SetWithDel and SingleDel, since we were going to only use this on the real MVCC key space in CockroachDB `[keys.SystemMax, keys.MaxKey)`?
Something changed with that plan?
___
*[`scan_internal.go` line 109 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSRNPJW5T98G93Eqtm3:-NSRNPJX-broEJn6pGMs:b-rpgqgj) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L109)):*
> ```Go
> // TODO(bilal): Implement the unimplemented internalIterator methods below.
> // Currently this iterator only supports the forward iteration case necessary
> // for scanInternal, however foreign sstable iterators will also need to use this
> ```

Related to the previous comment, this scan is not very performance sensitive, but the foreign sstable iterators will be user-facing and very performance sensitive. So limiting the generality seems worthwhile.
___
*[`scan_internal.go` line 131 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSROblwAUt_rU4CrVG6:-NSROblwAUt_rU4CrVG7:blbonp3) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L131)):*
> ```Go
> 	//    the value of savedKey is undefined.
> 	iterKey  *InternalKey
> 	savedKey InternalKey
> ```

Do we need this backing of `iterKey` by `savedKey` if there was no merging.
In the forward direction the first key we encounter is what we will return. We do need to save the key so we can skip the following ones that have the same key, by doing a key comparison (and we can use the seqnum optimization to avoid the comparison in half of the cases where the seqnum has increased).

This also makes me think that `pointCollapsingIter` whose input is a sequence of keys from across the iterator stack, is not how we will iterate over foreign sstables, where we are iterating over a single sst at a time, and have to adjust the seqnum.
For the latter case and forward iteration, the first key encountered is also what we need to return, and we need to skip succeeding keys that are equal (again subject to the seqnum optimization to avoid the key comparison). So it sounds similar-ish but there is scope to further optimize key comparisons and even avoid saving the key by making changes to the block format, since we are in the context of a single sstable. For example, with the latest v3 format, for the common case of a sequence of SETs and a single MVCC version, the `setHasSamePrefix` bit will be false, which implies that the user key has changed.


<!-- Sent from Reviewable.io -->

2023-04-08 23:04 UTC, bananabrick reviewed
Looks good. I have some questions.

> Reviewed 1 of 8 files at r6, 4 of 8 files at r8, 3 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NSY65oO3EZ3SUraYzpj:b-jsj784)* status: all files reviewed, 20 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`compaction.go` line 2805 at r10](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSJPiQa8FyKP3wkqcAU:-NSJPiQa8FyKP3wkqcAV:bhzrctf) ([raw file](https://github.com/cockroachdb/pebble/blob/2c49fb4ae186c7346e753040b8df0621ef6b8b34/compaction.go#L2805)):*
> ```Go
> 		// some careful handling around move compactions to ensure all files in
> 		// lower levels are in shared storage.
> 		createOpts := objstorage.CreateOptions{
> ```

Are we writing all compaction/flush output files to shared storage here? I was under the impression that only the last two levels will have files in shared storage.
___
*[`db.go` line 1121 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NPPP2Q6EKEJP4BUQMvr:-NSJQYeiCtjPv8OFuKsN:b-p4qvle) ([raw file](https://github.com/cockroachdb/pebble/blob/af99bf4585d898c4153cc1ec6c657584e91dfe5d/db.go#L1121)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

That's one possible case. Others would be where we make the provider smart enough to allow migrations to shared storage. This use-case explicitly came up in one of the meetings (was it a standup?) where we felt it was a good idea to account for partially-shared cases from the start.
</blockquote></details>

nit: Could add an example to the comment for those who won't be familiar with the reasoning.
___
*[`options.go` line 883 at r10](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSJSC-F0Syodl9pSuLO:-NSJSC-F0Syodl9pSuLP:bvpjv0z) ([raw file](https://github.com/cockroachdb/pebble/blob/2c49fb4ae186c7346e753040b8df0621ef6b8b34/options.go#L883)):*
> ```Go
> 		// pretend that all files in L5 and L6 are shared, even if the Provider
> 		// disagrees or there is no provider. Used only in tests.
> 		testingDisableProviderSharedFileCheck bool
> ```

This is no longer used, I believe.
___
*[`scan_internal.go` line 428 at r10](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSN9Dq8ADkBrehZcg4-:-NSN9Dq97792Z3GiW6eW:btk0bo2) ([raw file](https://github.com/cockroachdb/pebble/blob/2c49fb4ae186c7346e753040b8df0621ef6b8b34/scan_internal.go#L428)):*
> // scanInternalIterator is an iterator that returns all internal keys instead of
// collapsing them by user keys.

Is this true?
___
*[`scan_internal.go` line 496 at r10](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSNEMIk9aS0dh7-1usY:-NSNEMIk9aS0dh7-1usZ:b-2g0fse) ([raw file](https://github.com/cockroachdb/pebble/blob/2c49fb4ae186c7346e753040b8df0621ef6b8b34/scan_internal.go#L496)):*
> ```Go
> 	//
> 	// TODO(bilal): Once virtual sstables go in, verify that the constraining of
> 	// bounds to virtual sstable bounds happens below this method, so we aren't
> ```

This is another reason why the sstable iterators should enforce the virtual sstable bounds.
___
*[`scan_internal.go` line 607 at r10](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSNAoVk5GrASW_s9eDY:-NSNAoVk5GrASW_s9eDZ:b-aq32p2) ([raw file](https://github.com/cockroachdb/pebble/blob/2c49fb4ae186c7346e753040b8df0621ef6b8b34/scan_internal.go#L607)):*
> ```Go
> 	visitSharedFile func(sst *SharedSSTMeta) error,
> ) error {
> 	if visitSharedFile != nil && (lower == nil || upper == nil) {
> ```

Are we not allowing lower/upper == nil when visiting shared files to simplify the code?
___
*[`scan_internal.go` line 177 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSY5gTb8IOeUV_b6Ffi:-NSY5gTb8IOeUV_b6Ffj:b-h6i3a4) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L177)):*
> ```Go
> // findNextEntry is called to return the next key. It must be positioned at the
> // start of the first user key we are interested in.
> func (p *pointCollapsingIterator) findNextEntry() (*base.InternalKey, base.LazyValue) {
> ```

This function looks good to me, but it could use another set of eyes. The merge/singledel logic in particular, as the rest is straightforward.
___
*[`scan_internal.go` line 202 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSY2xqf-pc1JpTjesSJ:-NSY2xqf-pc1JpTjesSK:bgwh3j9) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L202)):*
> ```Go
> 			if p.valueMerger != nil {
> 				if invariants.Enabled {
> 					if p.savedKey.Kind() != InternalKeyKindMerge {
> ```

Does this need be to invariants gated? Would we want the system to continue running even if the key kind isn't a merge?
___
*[`scan_internal.go` line 229 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSY5E0QESu_MjNIbLmt:-NSY5E0R3zieUMSBE8W9:b-1ibd3a) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L229)):*
> ```Go
> 			// Fast forward to the next user key.
> 			p.saveKey()
> 			for p.iterKey != nil && p.comparer.Equal(p.iterKey.UserKey, p.savedKey.UserKey) {
> ```

Is this equality guaranteed to be equal for the first iteration? Maybe we can skip the check for the first iteration.
___
*[`scan_internal.go` line 240 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSY0Xvh38zLBsOZMYTA:-NSY0Xvh38zLBsOZMYTB:b-87gwnk) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L240)):*
> ```Go
> 			// compacted into a Del to turn into a SetWithDelete. This is a fast
> 			// path optimization that can break SINGLEDEL determinism. To lead to
> 			// consistent SINGLEDEL behaviour, this iterator should *not* be used for
> ```

We're supporting single del in this iterator. Is it okay to use this iterator, even without single del determinism?
___
*[`scan_internal.go` line 368 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSXckMrBZ_NCWzgGU-6:-NSXckMrBZ_NCWzgGU-7:b-1r1xt6) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L368)):*
> ```Go
> 	switch p.pos {
> 	case pcIterPosCur:
> 		p.saveKey()
> ```

Is it valid to to call `Next` once an iterKey has already been set to nil? If `iterKey` is `nil` when `Next` is called and `p.pos == pcIterPosCur`, then doesn't it mean that the last positioning op returned `nil`. I guess we're allowing calls to `Next` even if we returned a `nil` key to the caller, which is fine.


<!-- Sent from Reviewable.io -->

2023-04-13 19:31 UTC, bananabrick approved these changes
> Reviewed 1 of 8 files at r8, 3 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357)* status: 9 of 10 files reviewed, 12 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`scan_internal.go` line 101 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSRMnan2HRn4hFslZfJ:-NSvy6uSC80j-W23evS1:bb76ops) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L101)):*
> but I've retained the merge logic as it shouldn't cause performance issues.

I think if we're sure that there will be no merges in the key space where this iterator is used, then we should get rid of the merge case too. The rest <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
___
*[`scan_internal.go` line 175 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSw4-Lw-SavNTlP-Cfc:-NSw4-Lw-SavNTlP-Cfd:b-q3hntr) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L175)):*
> ```Go
> }
> 
> // findNextEntry is called to return the next key. It must be positioned at the
> ```

nit: It would be clearer to clarify what the "It" in "It must be positioned.." is referring to.
___
*[`scan_internal.go` line 211 at r12](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSw4h1SDDyPsAxZAlhn:-NSw4h1SDDyPsAxZAlho:b9bgzx4) ([raw file](https://github.com/cockroachdb/pebble/blob/80826d177944c895b9492ce5eb8d8b89e3df9a8b/scan_internal.go#L211)):*
> ```Go
> 			if p.valueMerger != nil {
> 				return finishAndReturnMerge()
> 			} else if p.savedKey.Kind() == InternalKeyKindSingleDelete {
> ```

Do we need this single delete case?


<!-- Sent from Reviewable.io -->

2023-04-17 15:33 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NTEqBCR1Jep6rsTbBZd:b-814g8k)* status: 9 of 10 files reviewed, 11 unresolved discussions (waiting on @bananabrick and @sumeerbhola)

___
*[`scan_internal.go` line 101 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSRMnan2HRn4hFslZfJ:-NTEnh6jD08R1ADmQ8Gn:bm6xv3b) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L101)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

> but I've retained the merge logic as it shouldn't cause performance issues.

I think if we're sure that there will be no merges in the key space where this iterator is used, then we should get rid of the merge case too. The rest <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>



</blockquote></details>

TFTR!

I think the question revolves around whether we'll ever read /System/tsd keys from disaggregated storage, and/or replicate those system ranges across the keyspace. Maybe keeping the door open for now is a good call which is why I implemented the Merge cases. It also comes at no performance hit when we encounter no merges. The only real drawback is having extra lightly-used code.
___
*[`scan_internal.go` line 175 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSw4-Lw-SavNTlP-Cfc:-NTEpFxr6SX3wOHr167e:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L175)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: It would be clearer to clarify what the "It" in "It must be positioned.." is referring to.
</blockquote></details>

Done.
___
*[`scan_internal.go` line 211 at r12](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSw4h1SDDyPsAxZAlhn:-NTEpHi6Dbv7-_EvghyW:btquzjz) ([raw file](https://github.com/cockroachdb/pebble/blob/80826d177944c895b9492ce5eb8d8b89e3df9a8b/scan_internal.go#L211)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Do we need this single delete case?
</blockquote></details>

Good catch, removed.


<!-- Sent from Reviewable.io -->

2023-04-17 19:17 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357)* status: 6 of 10 files reviewed, 11 unresolved discussions (waiting on @bananabrick and @sumeerbhola)

___
*[`scan_internal.go` line 101 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSRMnan2HRn4hFslZfJ:-NTFcokZDrT_uQKegTk-:bxhum4b) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L101)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

TFTR!

I think the question revolves around whether we'll ever read /System/tsd keys from disaggregated storage, and/or replicate those system ranges across the keyspace. Maybe keeping the door open for now is a good call which is why I implemented the Merge cases. It also comes at no performance hit when we encounter no merges. The only real drawback is having extra lightly-used code.
</blockquote></details>

What if we prevented both sides of a snapshot stripe from being compacted into L5/L6? That would a) prevent needing to collapse points internally within a table and b) prevent needing to apply range deletions within a table. Compaction picking heuristics examining L4 and L5 files could avoid files that have largest seq nums indicating they contain any keys newer than the oldest snapshot.


<!-- Sent from Reviewable.io -->

2023-04-18 16:13 UTC, itsbilal reviewed
Seeing as the bulk of this PR is approved and there's verbal support for this PR going in as-is, and we can address the question of merges in the future (and possibly deleting that code), I'll merge this for now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357#-:-NTK7owC6J1zpa8UjRLn:b-wbsl9v)* status: 6 of 10 files reviewed, 11 unresolved discussions (waiting on @bananabrick and @sumeerbhola)

___
*[`scan_internal.go` line 101 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NSRMnan2HRn4hFslZfJ:-NTK7ZeT1Ulu6t40PYL_:b1kxrp6) ([raw file](https://github.com/cockroachdb/pebble/blob/bb80b5e1fd03c8d2ed78d9584026cfdab27cd159/scan_internal.go#L101)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

What if we prevented both sides of a snapshot stripe from being compacted into L5/L6? That would a) prevent needing to collapse points internally within a table and b) prevent needing to apply range deletions within a table. Compaction picking heuristics examining L4 and L5 files could avoid files that have largest seq nums indicating they contain any keys newer than the oldest snapshot.
</blockquote></details>

I think that makes a lot of sense - as long as we are sparse in our use of snapshots (i.e. I don't want L4 to accumulate more files due to open snapshots preventing them from being written to L5). Something we can explore as a separate issue once we have done a deeper audit of our use of snapshots. I'll write up an issue about this.


<!-- Sent from Reviewable.io -->

2023-04-18 16:13 UTC, merged

2023-04-18 20:36 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2357)* status: 6 of 10 files reviewed, 13 unresolved discussions

___
*[`scan_internal.go` line 99 at r13](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NTL0SwhBj4RsfbkuNjs:-NTL0SwhBj4RsfbkuNjt:b-pdimvv) ([raw file](https://github.com/cockroachdb/pebble/blob/3844537c7f4d3d8926ea2ba1c482bf28718e9beb/scan_internal.go#L99)):*
> ```Go
> // pointCollapsingIterator is an internalIterator that collapses point keys and
> // returns at most one point internal key for each user key. Merges are merged,
> // sets are emitted as-is, and SingleDeletes are collapsed with the next point
> ```

nit: this SingleDelete comment is stale.
___
*[`scan_internal.go` line 196 at r13](https://reviewable.io/reviews/cockroachdb/pebble/2357#-NTL2s0H9tn1O8vMWOOS:-NTL2s0H9tn1O8vMWOOT:b-5krp57) ([raw file](https://github.com/cockroachdb/pebble/blob/3844537c7f4d3d8926ea2ba1c482bf28718e9beb/scan_internal.go#L196)):*
> ```Go
> 		// NB: p.savedKey is either the current key (iff p.iterKey == &p.savedKey),
> 		// or the previous key.
> 		if p.iterKey != &p.savedKey && !p.comparer.Equal(p.iterKey.UserKey, p.savedKey.UserKey) {
> ```

These loops were a bit confusing to me.
After staring at them for some time I realized that the outer loop implies that `p.iterKey` onwards is the only things we can return. That is, an earlier saved key is no longer under consideration to be returned.

Also, staring at this if-condition I think this has a needless comparison when we know we are already past the savedKey, e.g. when we applied a rangedel below. We could save that by doing
```
p.iterKey, p.value = p.iter.Next()
p.saveKey()
```
before calling continue


<!-- Sent from Reviewable.io -->