db: expose new metrics for compaction concurrency
cockroachdb/pebble pull request #2436
Opened 2023-04-06 18:44 UTC by jbowens

Compute and calculate two new metrics, `Uptime` and `Compact.Duration` which together may be used to compute the effective compaction concurrency over an interval.

**db: add Uptime metric**

Add a new Metric recording the database's uptime since Open. This can be used
in combination with other metrics to integrate over time.

**db: add Compact.Duration metric**

Add a new Compact.Duration metric that measures the cumulative time spent in
compactions since Open. This may be used in combination with Metrics.Uptime to
compute the effective compaction concurrency (https://github.com/cockroachdb/pebble/issues/1934). Callers may compute
effective compaction concurrency over an interval by measuring both Uptime and
Compact.Duration at the beginning and end of the interval and subtracting.

Close #1934.

2023-04-06 18:44 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2436)
<!-- Reviewable:end -->

2023-04-07 17:00 UTC, sumeerbhola requested changes
> Reviewed 3 of 3 files at r1, 1 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2436)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`compaction.go` line 1677 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2436#-NSRdRQW4QNOLXxxMZ4o:-NSRdRQW4QNOLXxxMZ4p:bds91le) ([raw file](https://github.com/cockroachdb/pebble/blob/86929113488c4160ade17f9f15dc2b2e8915d367/compaction.go#L1677)):*
> ```Go
> 	// in-progress compactions. This ensures Metrics.Compact.Duration does not
> 	// miss or double count a completing compaction's duration.
> 	d.mu.compact.duration += d.timeNow().Sub(c.beganAt)
> ```

Should we delay this duration computation until where we do `d.mu.compact.compactingCount--`, since we could block in obsolete file deletion after this, and that would prevent starting of another compaction.

Also, isn't this code also executed for flushes?
___
*[`db.go` line 417 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2436#-NSReGurE4CtX7Xld4T5:-NSReGurE4CtX7Xld4T6:b-gqi5sb) ([raw file](https://github.com/cockroachdb/pebble/blob/86929113488c4160ade17f9f15dc2b2e8915d367/db.go#L417)):*
> ```Go
> 
> 			// The cumulative duration of all completed compactions since Open.
> 			// Does not include flushes.
> ```

relates to previous question


<!-- Sent from Reviewable.io -->

2023-04-14 19:45 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2436)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`compaction.go` line 1677 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2436#-NSRdRQW4QNOLXxxMZ4o:-NT0HC5Q3PmH-bEt6Rhc:b-gklc4i) ([raw file](https://github.com/cockroachdb/pebble/blob/86929113488c4160ade17f9f15dc2b2e8915d367/compaction.go#L1677)):*
> Also, isn't this code also executed for flushes?

Oops, good catch.

> Should we delay this duration computation until where we do d.mu.compact.compactingCount--, since we could block in obsolete file deletion after this, and that would prevent starting of another compaction.

I took this suggestion, but I ran afoul of some undocumented invariant that I don't understand. If `getInProgressCompactionInfoLocked` returns compactions that have successfully completed but are now deleting obsolete files, deadlock is possible. I observed this in unit tests and the metamorphic tests, with a goroutine indefinitely blocked waiting for memtable stall to abate. Any ideas?


<!-- Sent from Reviewable.io -->

2023-04-17 17:29 UTC, sumeerbhola requested changes
> Reviewed 2 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2436)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`compaction.go` line 1677 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2436#-NSRdRQW4QNOLXxxMZ4o:-NTFDvB_-wahl6ZYezLa:b4s7cnx) ([raw file](https://github.com/cockroachdb/pebble/blob/86929113488c4160ade17f9f15dc2b2e8915d367/compaction.go#L1677)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> Also, isn't this code also executed for flushes?

Oops, good catch.

> Should we delay this duration computation until where we do d.mu.compact.compactingCount--, since we could block in obsolete file deletion after this, and that would prevent starting of another compaction.

I took this suggestion, but I ran afoul of some undocumented invariant that I don't understand. If `getInProgressCompactionInfoLocked` returns compactions that have successfully completed but are now deleting obsolete files, deadlock is possible. I observed this in unit tests and the metamorphic tests, with a goroutine indefinitely blocked waiting for memtable stall to abate. Any ideas?

</blockquote></details>

IIUC, we are just removing from `d.mu.compact.inProgress` later than before. Is my understanding correct?
It seems unfortunate that we have some undocumented invariant which allows `DB.mu.compactingCount` to be decremented later than removal from `DB.mu.inProgress`.
Odd about the memtable stall -- flush should not be affected.
We may be worse in some performance metrics since we use in-progress compactions in figuring out the ingest target level.
I don't think we have any consistency invariant between the latest `Version` and `inProgress` since we are calling `logAndApply` with the current set of in-progress compactions and removing this compaction after that call. I am wondering why that is even correct (since we use these in-progress compactions to mark L0 files as compacting). Maybe we are just being more pessimistic than we need to be, and it isn't a correctness issue. Ah maybe it doesn't matter since those L0 files that were compacted to Lbase are gone now, so there is nothing there in L0 to mark.

I'll stare some more at the code.


<!-- Sent from Reviewable.io -->

2023-05-08 16:20 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2436)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`compaction.go` line 1677 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2436#-NSRdRQW4QNOLXxxMZ4o:-NUw6lqP3XHBDcgWMltB:b-t95of5) ([raw file](https://github.com/cockroachdb/pebble/blob/86929113488c4160ade17f9f15dc2b2e8915d367/compaction.go#L1677)):*
I took another look and the indefinite memtable stall seems to be a result of `InitCompactingFileInfo` being invoked with the extra L0 compaction that's actually completed. `InitCompactingFileInfo` marks all the intervals overlapping any L0 base compactions' bounds as base compacting, even if the contained `FileMetadata` are not marked as currently compacting:
```
	// Some intervals may be base compacting without the files contained within
	// those intervals being marked as compacting. This is possible if the files
	// were added after the compaction initiated, and the active compaction
	// files straddle the input file. Mark these intervals as base compacting.
```

> I don't think we have any consistency invariant between the latest `Version` and `inProgress` since we are calling `logAndApply` with the current set of in-progress compactions and removing this compaction after that call.

Deleting obsolete files may drop the database mutex. In the meantime, another compaction/flush may complete and call `logAndApply` with a set of in-progress compactions that includes the completed compaction whose goroutine is deleting obsolete files.

I'm still thinking about what to do about this. It would be nice and easier to reason about if all the post-compaction state transitions were atomic, but I believe we have test dependencies on a compaction deleting the files it made obsolete before being cleared from `inProgress`.


<!-- Sent from Reviewable.io -->

2023-05-15 20:09 UTC, jbowens reviewed
@sumeerbhola — this is good for another look

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2436#-:-NVW12nkDYLiGMZpugRf:bqx5v82)* status: 1 of 9 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-05-16 19:14 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 8 files at r3, 5 of 8 files at r4, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2436#-:-NV_yv11BTaR6IMtm3Pe:bg7igkv)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @jbowens)

___
*[`compaction.go` line 2596 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2436#-NV_y8SwCMtte5f2T0WI:-NV_y8SwCMtte5f2T0WJ:bpkt8jl) ([raw file](https://github.com/cockroachdb/pebble/blob/06b07306568e3c8c76af01f568836898403e3370/compaction.go#L2596)):*
> ```Go
> 	d.maybeUpdateDeleteCompactionHints(c)
> 	// NB: clearing compacting state must occur before updating the read state;
> 	// L0Sublevels initialization depends on it.
> ```

L0Sublevels for the output version of this compaction has already been initialized in `logAndApply`. But that code filtered out `c` because of `d.getInProgressCompactionInfoLocked(c)` (I had overlooked that filtering in my previous round of comments). 


<!-- Sent from Reviewable.io -->

2023-05-16 20:36 UTC, merged