db: add reserved Pebblev4 sstable format
cockroachdb/pebble pull request #2528
Opened 2023-05-16 15:49 UTC by jbowens

This commit defines but leaves unused a new sstable table Pebblev4 that will subsume Pebblev2 and Pebblev3 sstable formats. Future work (#2465, #2340) will require additional sstable table formats. Stabilization of the table format extensions introduced in the Pebblev3 table format is required before that can happen. The new Pebblev4 format will include Pebblev3's extensions. This commit adjusts the code to not respect the Experimental.EnableValueBlocks setting in future format major versions that make use of the Pebblev4 sstable format.

There's some subtlety involved in this change, hence the introduction of the Pebblev4 sstable format before it's used.

2023-05-16 15:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2528)
<!-- Reviewable:end -->

2023-05-16 20:49 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2528#-:-NVaJoEKBuSWm3qCHHY3:bnfp4nl)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`sstable/suffix_rewriter_test.go` line 21 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2528#-NVaJOX9Cx5w5VWqkSqf:-NVaJOX9Cx5w5VWqkSqg:boxxxnp) ([raw file](https://github.com/cockroachdb/pebble/blob/02d9053763ebbda6b541ff58686ef7663d634563/sstable/suffix_rewriter_test.go#L21)):*
> ```Go
> 
> 	format := TableFormatPebblev2
> 	format += TableFormat(rand.Intn(int(TableFormatPebblev4 - TableFormatPebblev2)))
> ```

[nit] would it make more sense to do a `Run()` for each version?
___
*[`sstable/suffix_rewriter_test.go` line 21 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2528#-NVaJelzBx1J4guuvUvJ:-NVaJelzBx1J4guuvUvK:b-agw8f6) ([raw file](https://github.com/cockroachdb/pebble/blob/02d9053763ebbda6b541ff58686ef7663d634563/sstable/suffix_rewriter_test.go#L21)):*
> ```Go
> 
> 	format := TableFormatPebblev2
> 	format += TableFormat(rand.Intn(int(TableFormatPebblev4 - TableFormatPebblev2)))
> ```

Should `TableFormatPebblev4` here be `TableFormatMax` so we test v4 as well?


<!-- Sent from Reviewable.io -->

2023-05-16 21:31 UTC, sumeerbhola requested changes
> Reviewed 11 of 12 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2528)* status: all files reviewed, 4 unresolved discussions (waiting on @jbowens)

___
*[`sstable/suffix_rewriter.go` line 221 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2528#-NVaSbFHC_mdXJ8M3c7h:-NVaSbFHC_mdXJ8M3c7i:bgcg442) ([raw file](https://github.com/cockroachdb/pebble/blob/02d9053763ebbda6b541ff58686ef7663d634563/sstable/suffix_rewriter.go#L221)):*
> ```Go
> 			copy(scratch.UserKey[si:], to)
> 
> 			// NB: for TableFormatPebblev3, since
> ```

nit: and higher
___
*[`sstable/testdata/writer_value_blocks` line 217 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2528#-NVaSzfAEA99abynoTM4:-NVaSzfAEA99abynoTM5:b-n962wx) ([raw file](https://github.com/cockroachdb/pebble/blob/02d9053763ebbda6b541ff58686ef7663d634563/sstable/testdata/writer_value_blocks#L217)):*
> ```
>       1258    index: offset=264, length=77
>       1261    [padding]
>       1295    version: 4
> ```

why is the test writing v4 sstables before we've finished defining that format?


<!-- Sent from Reviewable.io -->

2023-05-17 18:38 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2528#-:-NVf-UWD91CkO-ru0--Q:bz5mair)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @sumeerbhola)

___
*[`sstable/suffix_rewriter_test.go` line 21 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2528#-NVaJOX9Cx5w5VWqkSqf:-NVew7geE7YsACiQy5Zr:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/02d9053763ebbda6b541ff58686ef7663d634563/sstable/suffix_rewriter_test.go#L21)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] would it make more sense to do a `Run()` for each version?
</blockquote></details>

Done
___
*[`sstable/suffix_rewriter_test.go` line 21 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2528#-NVaJelzBx1J4guuvUvJ:-NVew86FCaq9_NB3N7i3:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/02d9053763ebbda6b541ff58686ef7663d634563/sstable/suffix_rewriter_test.go#L21)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should `TableFormatPebblev4` here be `TableFormatMax` so we test v4 as well?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-05-17 18:39 UTC, merged