*: add IngestAndExcise operation
cockroachdb/pebble pull request #2538
Opened 2023-05-17 22:49 UTC by itsbilal

This change adds an IngestAndExcise operation that does the below additional things alongside a regular ingestion:

1) It ingests some SharedSSTMeta files, which are provider-backed
   sstables that could be owned by other nodes.
2) It excises existing sstables within the provided excise span (within
   which all sstables from 1 must fit) by creating new virtual sstables
   that exclude keys from the excise span.

While this change can be implemented independently of #2455, some of the end-to-end tests in future changes will rely on both that and this.

Fixes #2520.

2023-05-17 22:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2538)
<!-- Reviewable:end -->

2023-05-18 21:59 UTC, RaduBerinde reviewed
Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538#-:-NVkraZq1oyAcq5x7UGs:bdtx8r6)* status: 0 of 12 files reviewed, 8 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[`ingest.go` line 76 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkIFmZBN5YcW_v2anu:-NVkIFmZBN5YcW_v2anv:b4nh0ju) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L76)):*
> ```Go
> 			meta.LargestRangeKey.SetSeqNum(base.SeqNumL6RangeKey)
> 		default:
> 			panic(fmt.Sprintf("unexpected level in shared meta: %d", sm.Level))
> ```

Even though we currently store all levels on blob storage, we will only share L5+ when rebalancing?
___
*[`ingest.go` line 327 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkIsa0EZC6Py5oxNC-:-NVkIsa0EZC6Py5oxNC0:b35m40f) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L327)):*
> ```Go
> }
> 
> func ingestSortAndVerify(
> ```

[nit] I'd consolidate some of the comments below in a function comment explaining the slices. Maybe it would be more clear to have `localMeta, localPaths, sharedMeta`
___
*[`ingest.go` line 1215 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkNgczCFZDTs3I4gn8:-NVkNgd-4PKnpiEko8Fc:bqqqqch) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L1215)):*
> ```Go
> func (d *DB) excise(
> 	exciseSpan KeyRange, m *fileMetadata, ve *versionEdit, level int,
> ) (*versionEdit, error) {
> ```

we're modifying `ve` in place, why are we returning it also?
___
*[`ingest.go` line 1234 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkNsnSAIBCZY3LxnL2:-NVkNsnT5EWixv1Dy0Su:b-oga6rq) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L1234)):*
> ```Go
> 	var rangeKeyIter keyspan.FragmentIterator
> 	backingTableCreated := false
> 	// Create a file to the left of the excise span, if one exists.
> ```

[nit] "if necessary"
___
*[`ingest.go` line 1539 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkMWRm5vLiAMgpy_6i:-NVkMWRm5vLiAMgpy_6j:b-wom0dn) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L1539)):*
> ```Go
> 					FileNum: m.FileNum,
> 				}]; ok {
> 					levelMetrics.NumFiles--
> ```

[nit] This block is the same path with the block below.. Maybe move everything here or invert it to `if !deleted { continue }`
___
*[`ingest.go` line 1544 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkN3Nh0i9TvCdEzqGj:-NVkN3Ni6qXRkDwJZHl6:bpq0v2g) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L1544)):*
> ```Go
> 					continue
> 				}
> 				// Take advantage of the fact that excise() must have added files at
> ```

Maybe it would be cleaner if `excise` would return the subslice of files it added?
___
*[`ingest.go` line 1546 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkMRSi-P6UQ7cNSTjW:-NVkMRSj5xsCRn-Ao3VT:b-7llj4v) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L1546)):*
> ```Go
> 				// Take advantage of the fact that excise() must have added files at
> 				// the end of ve.NewFiles to update levelMetrics accordingly.
> 				for i := len(ve.NewFiles) - 1; i >= 0; i-- {
> ```

[nit] `i >= 0 && ve.NewFiles[i].Meta.FileBacking == m.FileBacking` would be more clear
___
*[`ingest.go` line 1427 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkqf0U8EbzXKHZPW6J:-NVkqf0U8EbzXKHZPW6K:b-8fti4a) ([raw file](https://github.com/cockroachdb/pebble/blob/16dedfc69705d2bc108cd43ec463c205be02256b/ingest.go#L1427)):*
> ```Go
> 		}
> 	}
> ```

Do we have a facility for checking that the Smallest/Largest keys are correct in the metadata? I assume they can be cross-checked against an interator. We could (under `invariants`) randomly run that check, or we could trigger it from tests.


<!-- Sent from Reviewable.io -->

2023-05-23 22:06 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538#-:-NW9dScqCZm1wG2saSnP:b-814g8k)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @bananabrick and @RaduBerinde)

___
*[`ingest.go` line 76 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkIFmZBN5YcW_v2anu:-NW8si4V9HqcfViuS46g:b-ysopzp) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L76)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Even though we currently store all levels on blob storage, we will only share L5+ when rebalancing?
</blockquote></details>

That's right. The stuff in `ScanInternal` already filters for just sharing levels above sharedLevelStart.
___
*[`ingest.go` line 327 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkIsa0EZC6Py5oxNC-:-NW8soK2AkncA2LEs4Le:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L327)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I'd consolidate some of the comments below in a function comment explaining the slices. Maybe it would be more clear to have `localMeta, localPaths, sharedMeta`
</blockquote></details>

Done.
___
*[`ingest.go` line 1215 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkNgczCFZDTs3I4gn8:-NW9VNwL4inn2vCNiBmv:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L1215)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

we're modifying `ve` in place, why are we returning it also?
</blockquote></details>

Done.
___
*[`ingest.go` line 1234 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkNsnSAIBCZY3LxnL2:-NW9VZevAYLJSwNSpq_W:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L1234)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] "if necessary"
</blockquote></details>

Done.
___
*[`ingest.go` line 1539 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkMWRm5vLiAMgpy_6i:-NW9Z2WE4e9xZF0v_WNQ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L1539)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This block is the same path with the block below.. Maybe move everything here or invert it to `if !deleted { continue }`
</blockquote></details>

Done.
___
*[`ingest.go` line 1544 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkN3Nh0i9TvCdEzqGj:-NW9b1yCDIP7_WjuSNoc:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L1544)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Maybe it would be cleaner if `excise` would return the subslice of files it added?
</blockquote></details>

Done.
___
*[`ingest.go` line 1546 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkMRSi-P6UQ7cNSTjW:-NW9b2iQ4l1aMgKJY3Fc:bkqwhx1) ([raw file](https://github.com/cockroachdb/pebble/blob/a7e7f4f9b567c6d7292fb1c6812808edaa5c3836/ingest.go#L1546)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `i >= 0 && ve.NewFiles[i].Meta.FileBacking == m.FileBacking` would be more clear
</blockquote></details>

Done (simplified due to the new return value).
___
*[`ingest.go` line 1427 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkqf0U8EbzXKHZPW6J:-NW9Y0H36gKB9jljmlKA:bws1k8v) ([raw file](https://github.com/cockroachdb/pebble/blob/16dedfc69705d2bc108cd43ec463c205be02256b/ingest.go#L1427)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we have a facility for checking that the Smallest/Largest keys are correct in the metadata? I assume they can be cross-checked against an interator. We could (under `invariants`) randomly run that check, or we could trigger it from tests.
</blockquote></details>

By correct you mean that they're calculated accurately, or that they just obey some common invariants like Largest > Smallest ? I added meta.Validate calls for the latter, but the former would sort of require re-running this logic or something like it to verify. I'm gonna give this more thought though.


<!-- Sent from Reviewable.io -->

2023-05-24 19:03 UTC, sumeerbhola requested changes
> Reviewed 3 of 11 files at r1, 6 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538)* status: 3 of 13 files reviewed, 6 unresolved discussions (waiting on @bananabrick, @itsbilal, and @RaduBerinde)

___
*[`compaction.go` line 2566 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWE0Pbt1-G7intW9EEK:-NWE0PbuCFgQhDdH5dWt:b-m0g6zv) ([raw file](https://github.com/cockroachdb/pebble/blob/b2daacc2c7432ded7acdd6923eda713ebaceb35f/compaction.go#L2566)):*
> ```Go
> 			c.inputs[i].files.Each(func(m *manifest.FileMetadata) {
> 				if m.Deleted {
> 					err = firstError(err, errors.New("pebble: file deleted by a concurrent operation, will retry compaction"))
> ```

Can we ensure/check that this code path gets exercised a lot, both in a regular unit test and the metamorphic test?
___
*[`ingest.go` line 87 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWE7OuA3VseT_bBq7fS:-NWE7OuA3VseT_bBq7fT:bel7hb4) ([raw file](https://github.com/cockroachdb/pebble/blob/b2daacc2c7432ded7acdd6923eda713ebaceb35f/ingest.go#L87)):*
> ```Go
> 		case 5:
> 			meta.SmallestPointKey.SetSeqNum(base.SeqNumL5Point)
> 			meta.LargestPointKey.SetSeqNum(base.SeqNumL5RangeDel)
> ```

why is SeqNumL5RangeDel not equal to SeqNumL5Point? With the same seqnum, the rangedel will not delete the point, as desired.
___
*[`ingest.go` line 946 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWE5_9_Ddc1VKv-uwsy:-NWE5_9_Ddc1VKv-uwsz:b6i3qp) ([raw file](https://github.com/cockroachdb/pebble/blob/b2daacc2c7432ded7acdd6923eda713ebaceb35f/ingest.go#L946)):*
> ```Go
> }
> 
> func (d *DB) ingest(
> ```

nit: even though this is not public, this code is getting complicated enough that it is worth have a code comment explaining its behavior and the parameters.
___
*[`ingest.go` line 963 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWE5n-gCPE9qdARQ0G2:-NWE5n-gCPE9qdARQ0G3:b65e37n) ([raw file](https://github.com/cockroachdb/pebble/blob/b2daacc2c7432ded7acdd6923eda713ebaceb35f/ingest.go#L963)):*
> ```Go
> 	}
> 	for i := range shared {
> 		pendingOutputs[len(paths)+i] = d.mu.versions.getNextFileNum().DiskFileNum()
> ```

it's not quite fair to use `DiskFileNum` for things that are not on disk. We have `FileNum` for that. We even say this:

```
// A DiskFileNum is just a FileNum belonging to a file which exists on disk.
// Note that a FileNum is an internal DB identifier and it could belong to files
// which don't exist on disk. An example would be virtual sstable FileNums.
// Converting a DiskFileNum to a FileNum is always valid, whereas converting a
// FileNum to DiskFileNum may not be valid and care should be taken to prove
// that the FileNum actually exists on disk.
```
___
*[`internal/manifest/l0_sublevels.go` line 904 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWE2IT_2qrPhBd_etUP:-NWE2IT_2qrPhBd_etUQ:b9ml2aw) ([raw file](https://github.com/cockroachdb/pebble/blob/b2daacc2c7432ded7acdd6923eda713ebaceb35f/internal/manifest/l0_sublevels.go#L904)):*
> ```Go
> // Contains returns whether the specified key exists in the UserKeyRange.
> func (k *UserKeyRange) Contains(cmp base.Compare, key []byte) bool {
> 	return cmp(k.Start, key) <= 0 && cmp(key, k.End) < 0
> ```

The comment for `UserKeyRange` says that `End` is inclusive.

Also `compaction.elideTombstone` could use this I think.


<!-- Sent from Reviewable.io -->

2023-05-24 21:56 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538#-:-NWEkYqN3jjVFzo2gz5J:b-814g8k)* status: 1 of 13 files reviewed, 6 unresolved discussions (waiting on @bananabrick, @RaduBerinde, and @sumeerbhola)

___
*[`compaction.go` line 2566 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWE0Pbt1-G7intW9EEK:-NWEkEfI2O_QnXYqvDK4:brlsoat) ([raw file](https://github.com/cockroachdb/pebble/blob/b2daacc2c7432ded7acdd6923eda713ebaceb35f/compaction.go#L2566)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can we ensure/check that this code path gets exercised a lot, both in a regular unit test and the metamorphic test?
</blockquote></details>

Good point. In my testing it fires pretty regularly, and once we wire up the metamorphic test we should see many background errors with this case. I'm writing an end-to-end test in a different branch, and I'll try to add an assertion there that we encountered at least one call to EventListener.BackgroundError.
___
*[`ingest.go` line 87 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWE7OuA3VseT_bBq7fS:-NWERTmi6n7I_qNoTCRK:bivxlsb) ([raw file](https://github.com/cockroachdb/pebble/blob/b2daacc2c7432ded7acdd6923eda713ebaceb35f/ingest.go#L87)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why is SeqNumL5RangeDel not equal to SeqNumL5Point? With the same seqnum, the rangedel will not delete the point, as desired.
</blockquote></details>

It's just clearer this way, but also I forgot that we don't delete points at the same seqnums as a rangedel. Happy to collapse the two seqnums if you think it's better that way.
___
*[`ingest.go` line 946 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWE5_9_Ddc1VKv-uwsy:-NWEcxE33NEENr6q_3qJ:bx4gk51) ([raw file](https://github.com/cockroachdb/pebble/blob/b2daacc2c7432ded7acdd6923eda713ebaceb35f/ingest.go#L946)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: even though this is not public, this code is getting complicated enough that it is worth have a code comment explaining its behavior and the parameters.
</blockquote></details>

There's already the giant comment at `Ingest` which talks about the process. I'll add another at IngestAndExcise and one here that references to it.
___
*[`ingest.go` line 963 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWE5n-gCPE9qdARQ0G2:-NWEQJuR9cXpYL7WQR3u:b-65mjzz) ([raw file](https://github.com/cockroachdb/pebble/blob/b2daacc2c7432ded7acdd6923eda713ebaceb35f/ingest.go#L963)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

it's not quite fair to use `DiskFileNum` for things that are not on disk. We have `FileNum` for that. We even say this:

```
// A DiskFileNum is just a FileNum belonging to a file which exists on disk.
// Note that a FileNum is an internal DB identifier and it could belong to files
// which don't exist on disk. An example would be virtual sstable FileNums.
// Converting a DiskFileNum to a FileNum is always valid, whereas converting a
// FileNum to DiskFileNum may not be valid and care should be taken to prove
// that the FileNum actually exists on disk.
```
</blockquote></details>

I made this comment elsewhere including in the `DiskFIleNum` PR, that the correct name for it should be `BackingFileNum` because we use it to reference FileBackings and we already use it in FileBacking even if an sstable is in shared.Storage and not in the provider. Which is to say I fully agree with you and that this type is wrongly tagged. I just think we should do it in a separate PR because it'll be a wholesale rename of the type and a lot of comment edits.

And since we're creating filenums in the provider that the metadatas will now reference, we'll need to do the conversion to `DiskFileNum` (which will soon be `BackingFileNum`, and mentally we should treat it as such) somewhere anyway between here and `InitProviderBacking` (and also `provider.AttachSharedObjects` which specifically asks for `DiskFileNums` to attach to).
___
*[`internal/manifest/l0_sublevels.go` line 904 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWE2IT_2qrPhBd_etUP:-NWEc35S6WHGLMChzSEE:bn0c24w) ([raw file](https://github.com/cockroachdb/pebble/blob/b2daacc2c7432ded7acdd6923eda713ebaceb35f/internal/manifest/l0_sublevels.go#L904)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The comment for `UserKeyRange` says that `End` is inclusive.

Also `compaction.elideTombstone` could use this I think.
</blockquote></details>

Ah, oops. Good catch. I'll split the types and create a new `KeyRange` in the toplevel package that is inclusive,exclusive.

I'll keep `compaction.elideTombstone` as-is as it's the inclusive, inclusive case and is more directly dealing with key ranges coming from L0 Sublevels (and has an optimization to `break` based on the sort order of key ranges).


<!-- Sent from Reviewable.io -->

2023-05-24 23:15 UTC, jbowens reviewed
flushing some comments

> Reviewed 1 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538#-:-NWF1opg31vuKnK5uafa:b-tl838d)* status: 2 of 13 files reviewed, 15 unresolved discussions (waiting on @bananabrick, @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`ingest.go` line 43 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWEsXaL48ATSvu6p294:-NWEsXaL48ATSvu6p295:blbm6pt) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L43)):*
> ```Go
> }
> 
> // Valid returns true if the UserKeyRange is defined.
> ```

nit: s/UserKeyRange/KeyRange/
___
*[`ingest.go` line 48 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWEsazH-jw3v4GsZqYW:-NWEsazH-jw3v4GsZqYX:blbm6pt) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L48)):*
> ```Go
> }
> 
> // Contains returns whether the specified key exists in the UserKeyRange.
> ```

nit: s/UserKeyRange/KeyRange/
___
*[`ingest.go` line 74 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWExxh17M7cscqMaj50:-NWExxh17M7cscqMaj51:bf77b9d) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L74)):*
> ```Go
> 	meta.FileNum = fileNum.FileNum()
> 	meta.CreationTime = time.Now().Unix()
> 	meta.Virtual = true
> ```

I didn't realize that all shared sstables are virtual—if the underlying sst's bounds are narrower than the KV range, could we use the shared sstable directly without marking it as "virtual," but continuing to retrieve the object from the object provider.
___
*[`ingest.go` line 76 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWF0N7MAluPwDk2Gzc5:-NWF0N7MAluPwDk2Gzc6:bm86jaw) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L76)):*
> ```Go
> 	meta.Virtual = true
> 	meta.Size = sm.Size
> 	meta.InitProviderBacking(fileNum, uint64(size))
> ```

how does this fit into the virtual sstable compaction heuristics? eg, we inflate virtual sstable's compaction priority by the non-live data of the backing sstable under the assumption that if we compact the virtual sstable(s), we can remove the backing sstable. The introduction of shared sstables complicates this, because removing this store's reference to the shared object won't necessarily allow us to delete the sstable from external storage.

Typically, we _expect_ incoming shared sstables to already be a subset of the data of the underlying cloud sstable. I'm mildly concerned that we'll be over-prioritizing compacting shared sstables that we just ingested.
___
*[`ingest.go` line 84 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWEtlj02Tl6m8mwzkmJ:-NWEtlj02Tl6m8mwzkmK:b-j0xw1s) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L84)):*
> ```Go
> 		case 5:
> 			meta.SmallestRangeKey.SetSeqNum(base.SeqNumL5RangeKeySet)
> 			meta.LargestRangeKey.SetSeqNum(base.SeqNumL5RangeKeyUnsetDel)
> ```

similarly to @sumeerbhola's comment about rangedels, i don't think there's any requirement for separate sequence numbers here:
```
// Additionally, internal range keys at the same sequence number have subtle
// mechanics:
//   - RANGEKEYSETs shadow RANGEKEYUNSETs of the same suffix.
//   - RANGEKEYDELs only apply to keys at lower sequence numbers.
```
Once coalesced, for each unique fragment bounds,  each suffix only appears once within `RANGEKYSET` or `RANGEKEYUNSET`. `RANGEKEYDEL`s can safely share the same sequence number and not affect anything other than L6 range keys. 

Also, since point keys and range keys have parallel existences, the same sequence number can be used for point keys and range keys.
___
*[`ingest.go` line 120 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWEwBMP7bNCChBKPN6i:-NWEwBMP7bNCChBKPN6j:bwulqph) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L120)):*
> ```Go
> 	opts *Options, fmv FormatMajorVersion, path string, cacheID uint64, fileNum base.DiskFileNum,
> ) (*fileMetadata, error) {
> 	var readable objstorage.Readable
> ```

nit: are the changes to this func intentional?
___
*[`ingest.go` line 299 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWEwsiO2TyFgMex006M:-NWEwsiO2TyFgMex006N:b-4v5b97) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L299)):*
> ```Go
> 	sharedMeta := make([]*fileMetadata, 0, len(shared))
> 	levels := make([]uint8, 0, len(shared))
> 	var sharedObjs []objstorage.SharedObjectToAttach
> ```

nit: should this also be pre-allocated to `len(shared)` capacity?
___
*[`ingest.go` line 365 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWEz8ojEyWkKhNV-g-Z:-NWEz8ojEyWkKhNV-g-_:b-1isx5k) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L365)):*
> ```Go
> 	for i := range lr.sharedMeta {
> 		f := lr.sharedMeta[i]
> 		if !exciseSpan.Contains(cmp, f.Smallest.UserKey) || !exciseSpan.Contains(cmp, f.Largest.UserKey) {
> ```

what if `f` is exclusive in the end boundary? that seems like it must be possible if not probable, in which case the user key of the exclusive bound does not fall within `exciseSpan`.
___
*[`ingest.go` line 854 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWF-6fg7kOg0V6u9mlT:-NWF-6fg7kOg0V6u9mlU:bl0zeuo) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L854)):*
> ```Go
> // ingestion process.
> //
> // Panics if this DB instance was not instantiated with a shared.Storage.
> ```

is this true? Even without shared storage, we want to use IngestAndExcise for snapshot reception, no?


<!-- Sent from Reviewable.io -->

2023-05-25 20:28 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538)* status: 2 of 13 files reviewed, 20 unresolved discussions (waiting on @bananabrick, @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`ingest.go` line 311 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWJUnAVBaSgtfen5Q0H:-NWJUnAVBaSgtfen5Q0I:bj42ycs) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L311)):*
> ```Go
> 		})
> 	}
> 	sharedObjMetas, err := provider.AttachSharedObjects(sharedObjs)
> ```

this is where the references will be durably persisted, right? in that case for shared files this is behaving a little more like `ingestLoad` _and_ `ingestLink`. should the attachment be deferred until `ingestLink`?
___
*[`ingest.go` line 1131 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWJWqEX2co5JT8oQHZN:-NWJWqEX2co5JT8oQHZO:brg84q1) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L1131)):*
> ```Go
> 			// flushable ingests and need to wait synchronously. Either remove this
> 			// caveat by fleshing out flushable ingest logic to also account for these
> 			// cases, or remove this TODO.
> ```

unfortunately at the moment it appears just about all snapshot ingests overlap the memtable (cockroachdb/cockroach#99273) which will mean we'll need to wait for the flush during all snapshot ingests. hopefully KV will be able to remove that overlap in this release, otherwise we might want to look for creative options to avoid holding up the commit pipeline. @sumeerbhola suggested waiting for the flush _before_ entering the commit pipeline. in cockroach the  fact that the Replica performing the ingest is blocked waiting on the ingest should ensure we won't overlap the memtable once we do enter the pipeline.
___
*[`ingest.go` line 1274 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWJYNMW6JoqCty0SRM-:-NWJYNMW6JoqCty0SRM0:baujs5b) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L1274)):*
> ```Go
> func (d *DB) excise(
> 	exciseSpan KeyRange, m *fileMetadata, ve *versionEdit, level int,
> ) ([]manifest.NewFileEntry, error) {
> ```

this function both mutates `ve` and returns the slice of new file entries? do we use the returned new file entries somewhere?
___
*[`ingest.go` line 1277 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWJYrdPEjsYANzbkTI6:-NWJYrdPEjsYANzbkTI7:b8uj0mv) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L1277)):*
> `d.cmp(exciseSpan.End, m.Smallest.UserKey) < 0`

should this be `<=`? I think `exciseSpan.End` is exclusive, but `m.Smallest.UserKey` is inclusive

nit: could use 
```
if v := d.cmp(exciseSpan.Start, m.Largest.UserKey); v > 0 || (m.Largest.IsExclusiveSentinel() && v == 0) || ...
```
to perform the `exciseSpan.Start, m.Largest.UserKey` comparison once
___
*[`ingest.go` line 1295 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWJ_9UwAsjwFd7azIaC:-NWJ_9UwAsjwFd7azIaD:b-bdetyy) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L1295)):*
> ```Go
> 	backingTableCreated := false
> 	// Create a file to the left of the excise span, if necessary.
> 	// The bounds of this file will be [m.Smallest, exciseSpan.Start].
> ```

this code appears to find a tighter end boundary than `exciseSpan.Start`.

can you remind me why you decided to read the table to look up tight bounds instead of using the laxer `exciseSpan.Start` bound (or a key computed with `Comparer.Separator`?


<!-- Sent from Reviewable.io -->

2023-05-29 16:17 UTC, itsbilal reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538#-:-NWcHJGl8UF2apSuq9wB:bz5mair)* status: 1 of 16 files reviewed, 16 unresolved discussions (waiting on @bananabrick, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`ingest.go` line 87 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWE7OuA3VseT_bBq7fS:-NWc3loLAbEzPW9meyuI:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b2daacc2c7432ded7acdd6923eda713ebaceb35f/ingest.go#L87)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Up to you. We will use one seqnum with https://github.com/cockroachdb/pebble/pull/2559 and the existing globalSeqNum logic will suffice. 
</blockquote></details>

Done.
___
*[`ingest.go` line 43 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWEsXaL48ATSvu6p294:-NWO_TEu8GkPVpF5deO7:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L43)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: s/UserKeyRange/KeyRange/
</blockquote></details>

Done.
___
*[`ingest.go` line 48 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWEsazH-jw3v4GsZqYW:-NWO_TwC0YK5244xIgWu:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L48)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: s/UserKeyRange/KeyRange/
</blockquote></details>

Done.
___
*[`ingest.go` line 74 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWExxh17M7cscqMaj50:-NWO_Va49RHYqu9aY3j3:b-fn45te) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L74)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Hmm, given that the `objstorage.Provider` will map this to `fileNum`, not virtualizing should be easy to do in this case.
</blockquote></details>

Yeah, we could get away with that. We'd just need to pass this fact over in `SharedSSTMeta` because if virtual is false, we won't do the read-time bounds-enforcement and end up exposing keys that are outside of bounds.
___
*[`ingest.go` line 76 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWF0N7MAluPwDk2Gzc5:-NWc9RkE1k1NeZEXUHag:b2re5bp) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L76)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Glad you raised this. I remember a past discussion in which I had glibly claimed that doing such inflation was fine, since most sstables would fall into a single CRDB range, and we can tolerate some amount of rewriting. Maybe that's ok as a starting point, but we *will* need to fix this before serious usage: we could have workloads where all ranges in the cluster are say 64MB, because of load-based splits, and LSMs with all levels populated (so L6 with 128MB files), and we don't want rewrites in that case.

The RFC says
> Shared sstables do not span range boundaries. Note that this is
  best-effort behavior and does not eliminate the need to apply a key
  span constraint at iteration time (due to range splits).

But I don't know if this is worth doing -- it introduces more metadata coordination between CRDB and Pebble (to virtualize at split time) and potentially unnecessary code complexity. Also, it does not easily address the problem for workloads with load-based splits where there could be lots of splits and merges (say for various parts of the keyspace the workload has 1h of high load and 1h of no load and this pattern repeats). Ideally we don't want such splits and merges to result in excessive compaction activity.

I made a simple example with a file of size 100 written by N1. N1 shares it with N2 and retains an interest in only 20 out of 100, while N2 is interested in 80. Eventually N1's interest declines to 10, and N2's to 20 and no one else is sharing (say there were further splits and the ranges got transferred to a different region/AZ).
The intent here was to see if we can encode this information in the references so that every node with a reference can periodically scan all the references (say every few hours), sum the useful bytes in the file and use that for compaction prioritization. This would avoid the need for explicit communication.
If references are not updated, then they encode what the node was interested in when it created the ref. So, ref(N1).bytes=100, and ref(N2).bytes=80. If N1 sums its current interest (when it drops to 10) with ref(N2).bytes, it gets 90. Similarly, N2 sums 20 + 100 = 120. Since the file size is 100, these sums are clearly not representing the actual waste. We could fix this by updating the reference whenever a node reduces `FileBacking.VirtualizedSize`.

@RaduBerinde 
</blockquote></details>

Good point. Maybe a good solution here is to use the virtual sstable size as the underlying backing sstable size as well. That way our math for the number of non-live bytes starts off at 0 and we don't give special priority right off the bat to cleaning away references to foreign sstables (which might be living in a cheaper tier of storage anyway).

Important to note that for progressive restore we would need to prioritize these sstables for compaction anyway. But we can probably do that with a new compaction type (a "rewrite" compaction or so) that kicks in when we need to move things from SharedStorage to `vfs.FS`, instead of messing with existing compaction scoring which should be agnostic to that preference (because not every deployment will need to prioritize moving things from `SharedStorage` to a closer `SharedStorage` or to a `vfs.FS`).
___
*[`ingest.go` line 84 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWEtlj02Tl6m8mwzkmJ:-NWc3k5z8mZAsMGivLC9:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L84)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

similarly to @sumeerbhola's comment about rangedels, i don't think there's any requirement for separate sequence numbers here:
```
// Additionally, internal range keys at the same sequence number have subtle
// mechanics:
//   - RANGEKEYSETs shadow RANGEKEYUNSETs of the same suffix.
//   - RANGEKEYDELs only apply to keys at lower sequence numbers.
```
Once coalesced, for each unique fragment bounds,  each suffix only appears once within `RANGEKYSET` or `RANGEKEYUNSET`. `RANGEKEYDEL`s can safely share the same sequence number and not affect anything other than L6 range keys. 

Also, since point keys and range keys have parallel existences, the same sequence number can be used for point keys and range keys.
</blockquote></details>

Done.
___
*[`ingest.go` line 120 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWEwBMP7bNCChBKPN6i:-NWP0zLZ467TAk0O6CJp:b-a4wcvi) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L120)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: are the changes to this func intentional?
</blockquote></details>

Oops. Done.
___
*[`ingest.go` line 299 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWEwsiO2TyFgMex006M:-NWOn9oYCUA2njPivCxG:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L299)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: should this also be pre-allocated to `len(shared)` capacity?
</blockquote></details>

Done.
___
*[`ingest.go` line 311 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWJUnAVBaSgtfen5Q0H:-NWOrrv_5RkLUL6VmpBL:b-qu6n94) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e37 [...]

2023-05-31 15:41 UTC, sumeerbhola requested changes
> Reviewed 6 of 11 files at r8, 4 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538)* status: 11 of 16 files reviewed, 18 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @RaduBerinde)

___
*[`compaction.go` line 2566 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWE0Pbt1-G7intW9EEK:-NWmInT47caVvMF1I9kP:bq0ncok) ([raw file](https://github.com/cockroachdb/pebble/blob/b2daacc2c7432ded7acdd6923eda713ebaceb35f/compaction.go#L2566)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Good point. In my testing it fires pretty regularly, and once we wire up the metamorphic test we should see many background errors with this case. I'm writing an end-to-end test in a different branch, and I'll try to add an assertion there that we encountered at least one call to EventListener.BackgroundError.
</blockquote></details>

sounds good
___
*[`compaction.go` line 1339 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWmKK-31r_gSMLwVLEu:-NWmKK-31r_gSMLwVLEv:bjkx57o) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/compaction.go#L1339)):*
> ```Go
> 	) (keyspan.FragmentIterator, error) {
> 		iter, rangeDelIter, err := newIters(context.Background(), f.FileMetadata,
> 			&IterOptions{level: l}, internalIterOpts{bytesIterated: &c.bytesIterated})
> ```

was not passing the level an oversight? Is this needed for `NewFixedSeqnumRangeDelIter`?
___
*[`ingest.go` line 74 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWExxh17M7cscqMaj50:-NWmL6FP7REFT7Dy-i6j:b-lz7fkw) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L74)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yeah, we could get away with that. We'd just need to pass this fact over in `SharedSSTMeta` because if virtual is false, we won't do the read-time bounds-enforcement and end up exposing keys that are outside of bounds.
</blockquote></details>

nit: if this is a TODO for a later PR can we track it somewhere?
___
*[`ingest.go` line 76 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWF0N7MAluPwDk2Gzc5:-NWmLV7b9N2R_SfP-OG3:b-y6o227) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L76)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Good point. Maybe a good solution here is to use the virtual sstable size as the underlying backing sstable size as well. That way our math for the number of non-live bytes starts off at 0 and we don't give special priority right off the bat to cleaning away references to foreign sstables (which might be living in a cheaper tier of storage anyway).

Important to note that for progressive restore we would need to prioritize these sstables for compaction anyway. But we can probably do that with a new compaction type (a "rewrite" compaction or so) that kicks in when we need to move things from SharedStorage to `vfs.FS`, instead of messing with existing compaction scoring which should be agnostic to that preference (because not every deployment will need to prioritize moving things from `SharedStorage` to a closer `SharedStorage` or to a `vfs.FS`).
</blockquote></details>

+1 to not messing with compaction scoring for progressive restore.
___
*[`ingest.go` line 365 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWEz8ojEyWkKhNV-g-Z:-NWmMWneAY-3BWm8Ces-:b47hxnx) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L365)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. Good catch!
</blockquote></details>

It seems we are always doing this containment check when we have InternalKeys, in which case we should just define `Contains` as taking an `InternalKey` param and move all this logic in there. Not that it matters, but it will also save an unnecessary key comparison since we don't need to compare `End` and `f.Largest.UserKey` twice.
___
*[`ingest.go` line 854 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWF-6fg7kOg0V6u9mlT:-NWmNgk74JmlMxZ7QETd:b-t515cg) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L854)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

It's not. Removed. Though the question of when we decide to call this method in Cockroach is still a bit of an open question (do we want to "pilot" it with disagg storage or do we want to roll it out more widely rightaway?)
</blockquote></details>

IMO, its easier to "pilot" it with disagg storage, since it reduce the number of times we need to evaluate the performance implication of this change.
___
*[`ingest.go` line 1131 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWJWqEX2co5JT8oQHZN:-NWmOOut3QEnAfeSlz3M:btrivz3) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L1131)):*
> This sounds like a good idea, but we'd still need a second check within the pipeline for concurrency reasons right?

Yep. This is just about reducing the probability of waiting for the flush in the commit pipeline. We could enable this behavior with ingest options. There would be some coordination to prevent N ingests all flushing memtables -- they'd all wait in the same place and after duration D, if the memtable was not naturally flushed, a flush would be done, where D is perhaps a DB option (to pace the maximum flush rate).
___
*[`ingest.go` line 1277 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWJYrdPEjsYANzbkTI6:-NWmQ6s38gQMV4zvWQ8k:b2sr0fg) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L1277)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you make this a method on excise span? It's easier to read when its abstracted out, and also more amenable to narrow unit tests. And I think we need some such unit tests, since its easy for all of us to miss/introduce such bugs when reading/writing code.
___
*[`ingest.go` line 1295 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWJ_9UwAsjwFd7azIaC:-NWmQy4225B8u54t7MrK:b-zhb2s2) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L1295)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Comment updated. And yeah I found a tight user-key bound because in my testing with the prototype I saw a lot of cases like these:

1) Wide memtable gets flushed, with some local and some table keys
2) Another wide memtable gets flushed, with the local keys sitting in between the local and table keys from 1)
3) A bunch more of the above ingestions, with table keys occasionally slotting in between other ranges' table keys.

If we just created vsstables with loose bounds without confirming if there are any keys within those bounds, we'll likely end up with a lot of ghost vsstables that don't contain any keys - forcing us to needlessly open vsstables that turn out to be empty. It can also have an effect on compaction picking / read amp in higher levels because we will think that that level has an overlapping file even though it doesn't.

Maybe that's not too much of a problem if we are unlikely to iterate from one range to another anyway (which would be the only case where we'd try reading empty vsstables), and if our vsst compaction picking heuristics are good enough at compacting tiny vsstables.
</blockquote></details>

These are compelling reasons. Could you add a code comment to that effect.
___
*[`ingest.go` line 1606 at r9](https://reviewable.io/ [...]

2023-06-01 21:20 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538)* status: 11 of 16 files reviewed, 22 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @sumeerbhola)

___
*[`ingest.go` line 1277 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWJYrdPEjsYANzbkTI6:-NWsp47K9xst78P2Enff:b-xesmf0) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L1277)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you make this a method on excise span? It's easier to read when its abstracted out, and also more amenable to narrow unit tests. And I think we need some such unit tests, since its easy for all of us to miss/introduce such bugs when reading/writing code.
</blockquote></details>

I agree, I saw the same logic reproduced many places.. Could also be an `IntersectsSpan` method on`FileMetadata`
___
*[`ingest.go` line 65 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWsopk1EPEiUo5L6c6k:-NWsopk1EPEiUo5L6c6l:bttqxop) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/ingest.go#L65)):*
> ```Go
> }
> 
> // ingestLoad1Shared loads the fileMetadata for one shared sstable.
> ```

[nit] maybe it would help to mention the sequence number rewrite here
___
*[`ingest.go` line 82 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWsouXlEfBRkyolEbg3:-NWsouXlEfBRkyolEbg4:bl4l3w6) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/ingest.go#L82)):*
> ```Go
> 		meta.LargestRangeKey = sm.LargestRangeKey
> 		switch sm.Level {
> 		case 5:
> ```

[nit, maybe suggestion for future clean-up] we have logic around these L5/L6 sequence numbers in a few places, I'm wondering if it would help to factor it out into some helpers that are all in the same place.

For example, this switch can be moved to a function that is given a level and returns a sequence number (and panics internally if the level is invalid), and this code would become
```
seq := sharedMetaSeqNum(sm.Level)
meta.SmallestRangeKey.SetSeqNum(seq)
...
```
___
*[`ingest.go` line 353 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWsoxeB-tmitnxeTbfY:-NWsoxeB-tmitnxeTbfZ:b-xk7lww) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/ingest.go#L353)):*
> ```Go
> 		if !exciseSpan.Contains(cmp, f.Smallest.UserKey) || !(exciseSpan.Contains(cmp, f.Largest.UserKey) ||
> 			(cmp(exciseSpan.End, f.Largest.UserKey) == 0 && f.Largest.IsExclusiveSentinel())) {
> 			return errors.New("pebble: shared file outside of excise span")
> ```

Should this be an AssertionFailed?
___
*[`ingest.go` line 1640 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWspHKt0IWNupsxMZuC:-NWspHKuAI2ImgHx1L8r:b8dcig7) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/ingest.go#L1640)):*
> ```Go
> 		//
> 		// Note that since there's a `defer d.mu.Unlock()` above, we need to relock
> 		// the db mutex before we return an error.
> ```

This is fragile, consider using defer
```
err := func() error {
  d.mu.Unlock()
  defer d.mu.Lock()
  ...
}()`
```


<!-- Sent from Reviewable.io -->

2023-06-02 23:26 UTC, itsbilal reviewed
TFTRs! Flushing updates so far, only remaining big piece is the flush/memtable overlap wait before we go into the commit pipeline. Will knock that out very soon.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538#-:-NWyQbNqAZboepgIukNl:b-e8hagu)* status: 8 of 16 files reviewed, 18 unresolved discussions (waiting on @bananabrick, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`compaction.go` line 1339 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWmKK-31r_gSMLwVLEu:-NWsA5N_CEliFuxPXKLj:bflg34w) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/compaction.go#L1339)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

was not passing the level an oversight? Is this needed for `NewFixedSeqnumRangeDelIter`?
</blockquote></details>

Yeah, it was an oversight that got detected in the testing PR. Also now that we're only using one seqnum per level/sstable, we need `NewFixedSeqnumRangeDelIter` less as our existing sequence number fixing logic for globally-seqnum'd sstables works as it always has. But we can't just sub `NewFixedSeqnumRangeDelIter` with `NewRawRangeDelIter` yet because the latter won't elide rangedels at the same sequence number.
___
*[`ingest.go` line 74 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWExxh17M7cscqMaj50:-NWsIFOR4kR220lSB32i:b7rbfp7) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L74)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: if this is a TODO for a later PR can we track it somewhere?
</blockquote></details>

Filed https://github.com/cockroachdb/pebble/issues/2583 to track this.
___
*[`ingest.go` line 76 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWF0N7MAluPwDk2Gzc5:-NWyPF-g1I9P8FnGiFTA:b-u38zrh) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L76)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

+1 to not messing with compaction scoring for progressive restore.
</blockquote></details>

Added the short-term solution for now. Will write up a follow-up issue for the more general case of compaction heuristics around shared sstables. 
___
*[`ingest.go` line 365 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWEz8ojEyWkKhNV-g-Z:-NWw3WSj2E7CURF9pjZF:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L365)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It seems we are always doing this containment check when we have InternalKeys, in which case we should just define `Contains` as taking an `InternalKey` param and move all this logic in there. Not that it matters, but it will also save an unnecessary key comparison since we don't need to compare `End` and `f.Largest.UserKey` twice.
</blockquote></details>

Done.
___
*[`ingest.go` line 854 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWF-6fg7kOg0V6u9mlT:-NWsVc_D8q2DbvZ6DnEN:b-lp9ux5) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L854)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

IMO, its easier to "pilot" it with disagg storage, since it reduce the number of times we need to evaluate the performance implication of this change.
</blockquote></details>

Agreed. I'll keep that in mind for the KV replication change (https://github.com/cockroachdb/cockroach/issues/103028 ).
___
*[`ingest.go` line 1277 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWJYrdPEjsYANzbkTI6:-NWsYaeR-3mZa6swtR7Y:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L1277)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I agree, I saw the same logic reproduced many places.. Could also be an `IntersectsSpan` method on`FileMetadata`
</blockquote></details>

Done.
___
*[`ingest.go` line 1295 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWJ_9UwAsjwFd7azIaC:-NWsPXNH25WWLcWX7YMd:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L1295)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

These are compelling reasons. Could you add a code comment to that effect.
</blockquote></details>

Done.
___
*[`ingest.go` line 82 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWsouXlEfBRkyolEbg3:-NWyPRW1EcaESjD3OyDK:b-p4o3ic) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/ingest.go#L82)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit, maybe suggestion for future clean-up] we have logic around these L5/L6 sequence numbers in a few places, I'm wondering if it would help to factor it out into some helpers that are all in the same place.

For example, this switch can be moved to a function that is given a level and returns a sequence number (and panics internally if the level is invalid), and this code would become
```
seq := sharedMetaSeqNum(sm.Level)
meta.SmallestRangeKey.SetSeqNum(seq)
...
```
</blockquote></details>

Done. This makes sense to do now that we have only one seqnum per level. The original design had a different seqnum for different kinds within a level.
___
*[`ingest.go` line 353 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWsoxeB-tmitnxeTbfY:-NWw3VesEvLamAREyIk_:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/ingest.go#L353)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should this be an AssertionFailed?
</blockquote></details>

Done.
___
*[`ingest.go` line 1606 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWmRe_u3FU3BJ3m3VWV:-NWsPba59tcXEbfDS-J9:b8cg5ss) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/ingest.go#L1606)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If the ingest does not have shared files (say due to AddSSTable in CRDB), and we ingest a local file into a shared level won't we hit the following error? Should this decision be a property of the DB and not the individual ingest?

```
// If visitSharedFile is not nil, ScanInternal iterates in skip-shared iteration
// mode. In this iteration mode, sstables in levels L5 and L6 are skipped, and
// their metadatas truncated to [lower, upper) and passed into visitSharedFile.
// ErrInvalidSkipSharedIteration is returned if visitSharedFile is not nil and an
// sstable in L5 or L6 is found that is not in shared storage according to
// provider.IsShared.
```
</blockquote></details>

We won't hit this because we already moved the file to shared storage in `ingestLink` (see the `PreferSharedStorage: true` there).
___
*[`ingest.go` line 1640 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWspHKt0IWNupsxMZuC:-NWw_8Ud04eQ2cHIBFKs:b-m5ggc0) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/ingest.go#L1640)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is fragile, consider using defer
```
err := func() error {
  d.mu.Unlock()
  defer d.mu.Lock()
  ...
}()`
```
</blockquote></details>

Done (removed entirely due to bug mentioned elsewhere, see comment)


<!-- Sent from Reviewable.io -->

2023-06-05 17:44 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538)* status: 8 of 16 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @sumeerbhola)

___
*[`ingest.go` line 1427 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NVkqf0U8EbzXKHZPW6J:-NXBcGAT0Qj5x18VoMcX:b-nzoczm) ([raw file](https://github.com/cockroachdb/pebble/blob/16dedfc69705d2bc108cd43ec463c205be02256b/ingest.go#L1427)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

By correct you mean that they're calculated accurately, or that they just obey some common invariants like Largest > Smallest ? I added meta.Validate calls for the latter, but the former would sort of require re-running this logic or something like it to verify. I'm gonna give this more thought though.
</blockquote></details>

That they're accurate. That e.g. `SmallestPoint` is the first key returned by a point iterator, etc. Feels like it could be useful to check e.g. when opening an SST file (in `invariants` mode, maybe with a random probability if it's expensive).

The logic would be along the lines of using some iterators to find the first and last point and range keys and then checking all the fields.

Not for this PR of course, maybe we should just file an issue for now?
___
*[`ingest.go` line 111 at r10](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NXBdKDG12XjtSy-Hy9G:-NXBdKDG12XjtSy-Hy9H:bzh70ya) ([raw file](https://github.com/cockroachdb/pebble/blob/e507c39634713e887216058f5628d405d5be8ff6/ingest.go#L111)):*
> ```Go
> 		meta.SmallestSeqNum = seqNum
> 		meta.LargestSeqNum = seqNum
> 		meta.ExtendPointKeyBounds(opts.Comparer.Compare, meta.SmallestPointKey, meta.LargestPointKey)
> ```

[nit] add a comment saying `Initialize the bounds` (I was initially confused by the "extend" part, but we're really initializing it)


<!-- Sent from Reviewable.io -->

2023-06-06 04:26 UTC, sumeerbhola requested changes
> Reviewed 1 of 3 files at r7, 1 of 6 files at r9, 2 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538)* status: 13 of 16 files reviewed, 18 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @RaduBerinde)

___
*[`compaction.go` line 1339 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWmKK-31r_gSMLwVLEu:-NXD0u1m5Js5uJzamUOg:b-og5w4c) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/compaction.go#L1339)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yeah, it was an oversight that got detected in the testing PR. Also now that we're only using one seqnum per level/sstable, we need `NewFixedSeqnumRangeDelIter` less as our existing sequence number fixing logic for globally-seqnum'd sstables works as it always has. But we can't just sub `NewFixedSeqnumRangeDelIter` with `NewRawRangeDelIter` yet because the latter won't elide rangedels at the same sequence number.
</blockquote></details>

I didn't understand the "we can't just sub ..." part given we do
```
func (r *Reader) NewRawRangeDelIter() (keyspan.FragmentIterator, error) {
	return r.NewFixedSeqnumRangeDelIter(r.Properties.GlobalSeqNum)
}
```
___
*[`ingest.go` line 854 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWF-6fg7kOg0V6u9mlT:-NXDvAuNAvljNMm7IK3z:b-dsulbl) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L854)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Agreed. I'll keep that in mind for the KV replication change (https://github.com/cockroachdb/cockroach/issues/103028 ).
</blockquote></details>

For the metamorphic test will we make this operation be metamorphic with a batch consisting of a RANGEDEL for the excise span followed by the behavior akin to `ingestUsingApply`?
___
*[`ingest.go` line 1131 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWJWqEX2co5JT8oQHZN:-NXD2pcW7cK83Dtj-sl4:b-lhw7xs) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L1131)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Trying to implement this change, I realized that we can't really rotate the memtable without entering the commit pipeline temporarily anyway (and grabbing the commit pipeline mutex and the DB mutex). We'd need to do that if we overlap with the mutable memtable, which I imagine will be the common case anyway. And just grabbing the mutex is still easier than adding a batch to the pipeline to track our ingestion (or at least the AllocateSeqNum call), so that would still be an improvement over the status quo.

Is it still worth to do this change in the same PR? I also realized we have #2112 filed to track just this fix. I'm good with completing it through in one PR if we expect the KV issue to be a significant blocker.
</blockquote></details>

As discussed in the sync, fine to do it later.
___
*[`ingest.go` line 1606 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWmRe_u3FU3BJ3m3VWV:-NXDrK5c2SmoLNukvO_e:bgamqta) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/ingest.go#L1606)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

We won't hit this because we already moved the file to shared storage in `ingestLink` (see the `PreferSharedStorage: true` there).
</blockquote></details>

So all the local paths are being moved to shared storage via `PreferSharedStorage`? In the CRDB range snapshot case they will typically not get ingested into L5 or L6 since there will be foreign ssts being ingested there, so have we unnecessarily placed them in shared storage?
We seem to have an interface mismatch here for ingests since we don't know what level these will get ingested in at the time of linking them.


<!-- Sent from Reviewable.io -->

2023-06-07 16:45 UTC, itsbilal reviewed
TFTRs!

> Dismissed @jbowens and @sumeerbhola from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538#-:-NXLi8rgB-s_To5H_uCW:bz5mair)* status: 13 of 16 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`compaction.go` line 1339 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWmKK-31r_gSMLwVLEu:-NXLakKOCunoLYjOjGa2:bd7u5le) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/compaction.go#L1339)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't understand the "we can't just sub ..." part given we do
```
func (r *Reader) NewRawRangeDelIter() (keyspan.FragmentIterator, error) {
	return r.NewFixedSeqnumRangeDelIter(r.Properties.GlobalSeqNum)
}
```
</blockquote></details>

Ah right, I had forgotten that we were doing the collapse in both cases. Cleaned up the iterator stack to not rely on `FixedSeqnumRangeDelIter` (and made the same change for range keys/points).
___
*[`ingest.go` line 854 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWF-6fg7kOg0V6u9mlT:-NXLbmIZ9tbvy4ogF1rz:badqgwx) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L854)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

For the metamorphic test will we make this operation be metamorphic with a batch consisting of a RANGEDEL for the excise span followed by the behavior akin to `ingestUsingApply`?
</blockquote></details>

That might not be sufficient for metamorphic test equivalence/determinism as we might have snapshots open that could read the excised keys and see different results between the excise and rangedel cases. But yes if we fallback to doing a RANGEDEL+RANGEKEYDEL if there's a snapshot open, then this would work well.
___
*[`ingest.go` line 1606 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWmRe_u3FU3BJ3m3VWV:-NXLfgWJ2eCT0KtVgpYA:b-k5y74i) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/ingest.go#L1606)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Looking again at this, given that we are determining the level simply based on whether there are shared files or not, and not based on whether there is a shared file below that overlaps, we could use this same decision in setting the value of `PreferSharedStorage`.
</blockquote></details>

That's right. I am still a little wary of passing `false` in any case to `PreferSharedStorage` or moving the level-determination logic here, as we haven't worked on move compactions yet, or at least come up with a good way to do move compactions to L5/L6 more efficiently than doing regular compactions. It'll just result in more instances of us not being able to fast-rebalance because there was one local file that got move-compacted into L5 and is now forcing regular replication when we call `ScanInternal`.

I will revisit all these `PreferSharedStorage` values when we have a move compaction implemented for local -> shared. But for now I think an unconditional `true` makes sense. I'll file an issue for implementing said move compaction and revisiting these `PreferSharedStorage` values.
___
*[`ingest.go` line 352 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NXFz4PK9E4ziOrlOfuu:-NXLcryi5gGxKML7X_su:b-z30p98) ([raw file](https://github.com/cockroachdb/pebble/blob/c700ec568dd82d1bf4c0e88e529b7fd9f5e55aa7/ingest.go#L352)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

where do we verify that the shared metas for the same level do not overlap?
</blockquote></details>

It would panic in `logAndApply`, but I just added a check in `ingestSortAndVerify`.
___
*[`ingest.go` line 1602 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NXFzvq0-pX23Q3xT_In:-NXLc6ZR-L3FfJFp_qgx:b1cu5nb) ([raw file](https://github.com/cockroachdb/pebble/blob/c700ec568dd82d1bf4c0e88e529b7fd9f5e55aa7/ingest.go#L1602)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this Level from `SharedSSTMeta.Level`? If yes, we should verify this before getting to this stage.
</blockquote></details>

Yes, we set it in `ingestLoad` ourselves, it's why it's in the `ingestLoadResult`. Is there another check we should have? I moved the lookup in `sharedLevels` around to make it clearer.


<!-- Sent from Reviewable.io -->

2023-06-07 19:03 UTC, jbowens reviewed
> Reviewed 2 of 11 files at r8, 1 of 9 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538)* status: 8 of 17 files reviewed, 20 unresolved discussions (waiting on @bananabrick, @itsbilal, @RaduBerinde, and @sumeerbhola)

___
*[`ingest.go` line 854 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWF-6fg7kOg0V6u9mlT:-NXMAi7i3i1FtI2J4iDn:b-3fds1) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L854)):*
> But yes if we fallback to doing a RANGEDEL+RANGEKEYDEL if there's a snapshot open, then this would work well.

We should be careful to make sure that we actually exercise IngestAndExcise if we do this. I suspect almost all the time _some_ snapshot is open.
___
*[`ingest.go` line 50 at r12](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NXM7ZpG9C4P2SBBSgxE:-NXM7ZpG9C4P2SBBSgxF:b-i60hae) ([raw file](https://github.com/cockroachdb/pebble/blob/d6ae580cb6560c71ad8d0721f57870126c244ee1/ingest.go#L50)):*
> ```Go
> func (k *KeyRange) Contains(cmp base.Compare, key InternalKey) bool {
> 	v := cmp(key.UserKey, k.End)
> 	return cmp(k.Start, key.UserKey) <= 0 && (v < 0 || (v == 0 && key.IsExclusiveSentinel()))
> ```

nit: because of the ordering of these conditions, i think we'll always perform both comparisons. if we flip the order, we can avoid the start key comparison if the end key comparison already precludes the possibility of overlap
___
*[`ingest.go` line 1212 at r12](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NXMCGdOCM0nqN4r9qlb:-NXMCGdOCM0nqN4r9qlc:b-s1y2zg) ([raw file](https://github.com/cockroachdb/pebble/blob/d6ae580cb6560c71ad8d0721f57870126c244ee1/ingest.go#L1212)):*
> ```Go
> 		//
> 		// For shared sstables, we do not need to update sequence numbers. These
> 		// sequence numbers are already set in ingestLoad.
> ```

i've completely forgotten why we need these unique shared-sstable sequence numbers. when we're excising, there are local internal keys above the ingested shared sstable; we've excised them. we allocate _n_ sequence numbers for _n_ sstables. why couldn't we just use the local engine's sequence numbers for setting the global seq num for each sstable, ensuring that overlapping sstables are appropriately sequenced according to the level they're slotted into?
___
*[`ingest.go` line 1349 at r12](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NXMDe4a-ZW-KYcH124n:-NXMDe4a-ZW-KYcH124o:bv6334r) ([raw file](https://github.com/cockroachdb/pebble/blob/d6ae580cb6560c71ad8d0721f57870126c244ee1/ingest.go#L1349)):*
> ```Go
> 	// directly into the space occupied by them. We choose to incur the cost of
> 	// calculating tight bounds at this time instead of creating more work in the
> 	// future.
> ```

This I/O can also opportunistically be performed before acquiring the manifest lock, like the target-file size I/O can be as described in #2112. I suspect that could help p99 commit latency significantly in the presence of ingests. Maybe leave a TODO referencing #2112?


<!-- Sent from Reviewable.io -->

2023-06-08 15:12 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538)* status: 8 of 17 files reviewed, 19 unresolved discussions (waiting on @bananabrick, @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`ingest.go` line 854 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWF-6fg7kOg0V6u9mlT:-NXQZD7H7NwgmNnV4FKV:bqog80t) ([raw file](https://github.com/cockroachdb/pebble/blob/8182b6ab027b5e5ea346e287e3796c246c5d62f2/ingest.go#L854)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> But yes if we fallback to doing a RANGEDEL+RANGEKEYDEL if there's a snapshot open, then this would work well.

We should be careful to make sure that we actually exercise IngestAndExcise if we do this. I suspect almost all the time _some_ snapshot is open.
</blockquote></details>

Agreed
___
*[`ingest.go` line 50 at r12](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NXM7ZpG9C4P2SBBSgxE:-NXQZBVTCgtNO789EOdT:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/d6ae580cb6560c71ad8d0721f57870126c244ee1/ingest.go#L50)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: because of the ordering of these conditions, i think we'll always perform both comparisons. if we flip the order, we can avoid the start key comparison if the end key comparison already precludes the possibility of overlap
</blockquote></details>

Done.
___
*[`ingest.go` line 1212 at r12](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NXMCGdOCM0nqN4r9qlb:-NXQXWnb9QzgD2rjm_aN:b-wzyz4i) ([raw file](https://github.com/cockroachdb/pebble/blob/d6ae580cb6560c71ad8d0721f57870126c244ee1/ingest.go#L1212)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

i've completely forgotten why we need these unique shared-sstable sequence numbers. when we're excising, there are local internal keys above the ingested shared sstable; we've excised them. we allocate _n_ sequence numbers for _n_ sstables. why couldn't we just use the local engine's sequence numbers for setting the global seq num for each sstable, ensuring that overlapping sstables are appropriately sequenced according to the level they're slotted into?
</blockquote></details>

The RFC called for two reserved seqnums in L5 (+ one for L6 for three in total), and based on our discussion in NYC we bumped that count up to 5 reserved seqnums. To make seqnum assignment easier at ingest time we just went with the reserved seqnum approach, but you're right that given the seqnum changes in this PR, we can just do seqnum assignment the old-fashioned way for shared sstables too (as long as they get lower seqnums than local sstables in the same ingestion) and we'll be okay. It's just that the seqnum changes are recent enough that the rest of the design (or even past PRs, like #2455, which really should have had the seqnum simplifiication and not this PR) don't account for it all.
___
*[`ingest.go` line 1349 at r12](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NXMDe4a-ZW-KYcH124n:-NXQYbv-20ARk8wLsnB3:bu76lyr) ([raw file](https://github.com/cockroachdb/pebble/blob/d6ae580cb6560c71ad8d0721f57870126c244ee1/ingest.go#L1349)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This I/O can also opportunistically be performed before acquiring the manifest lock, like the target-file size I/O can be as described in #2112. I suspect that could help p99 commit latency significantly in the presence of ingests. Maybe leave a TODO referencing #2112?
</blockquote></details>

Yeah that would make sense, there's an optimization to do as much of this work as possible before grabbing the manifest lock. Added the TODO.


<!-- Sent from Reviewable.io -->

2023-06-08 21:58 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> (I didn't look carefully at the tests)

> Reviewed 5 of 9 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2538#-:-NXS03Ka95O2FwvbOjQm:b55bmq8)* status: 13 of 17 files reviewed, 20 unresolved discussions (waiting on @bananabrick, @itsbilal, @jbowens, and @RaduBerinde)

___
*[`ingest.go` line 1606 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NWmRe_u3FU3BJ3m3VWV:-NXS-qqU8xfFmgEBuMCc:b2nhb2c) ([raw file](https://github.com/cockroachdb/pebble/blob/5057eb41b2e9ff4b5ab22b27a4469bd8180e6936/ingest.go#L1606)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

That's right. I am still a little wary of passing `false` in any case to `PreferSharedStorage` or moving the level-determination logic here, as we haven't worked on move compactions yet, or at least come up with a good way to do move compactions to L5/L6 more efficiently than doing regular compactions. It'll just result in more instances of us not being able to fast-rebalance because there was one local file that got move-compacted into L5 and is now forcing regular replication when we call `ScanInternal`.

I will revisit all these `PreferSharedStorage` values when we have a move compaction implemented for local -> shared. But for now I think an unconditional `true` makes sense. I'll file an issue for implementing said move compaction and revisiting these `PreferSharedStorage` values.
</blockquote></details>

Ack
___
*[`ingest.go` line 1602 at r11](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NXFzvq0-pX23Q3xT_In:-NXRztToEA-8hRUqOGsu:bqzebjo) ([raw file](https://github.com/cockroachdb/pebble/blob/c700ec568dd82d1bf4c0e88e529b7fd9f5e55aa7/ingest.go#L1602)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yes, we set it in `ingestLoad` ourselves, it's why it's in the `ingestLoadResult`. Is there another check we should have? I moved the lookup in `sharedLevels` around to make it clearer.
</blockquote></details>

I was not clear in my comment. I didn't mean to move the `sharedLevel` logic around. I was saying that this `if f.Level < sharedLevelsStart` should be validated earlier. I added a comment for that.
___
*[`ingest.go` line 1212 at r12](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NXMCGdOCM0nqN4r9qlb:-NXRyTckC8JgrbDZ6uJI:b-j1uq1r) ([raw file](https://github.com/cockroachdb/pebble/blob/d6ae580cb6560c71ad8d0721f57870126c244ee1/ingest.go#L1212)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The RFC called for two reserved seqnums in L5 (+ one for L6 for three in total), and based on our discussion in NYC we bumped that count up to 5 reserved seqnums. To make seqnum assignment easier at ingest time we just went with the reserved seqnum approach, but you're right that given the seqnum changes in this PR, we can just do seqnum assignment the old-fashioned way for shared sstables too (as long as they get lower seqnums than local sstables in the same ingestion) and we'll be okay. It's just that the seqnum changes are recent enough that the rest of the design (or even past PRs, like #2455, which really should have had the seqnum simplifiication and not this PR) don't account for it all.
</blockquote></details>

Yes, it doesn't seem we need these reserved seqnums. That thinking predates the use of excising across all the levels.
Fine to do it later.
___
*[`ingest.go` line 308 at r13](https://reviewable.io/reviews/cockroachdb/pebble/2538#-NXS-FlxE3zjM4hLWFRg:-NXS-FlxE3zjM4hLWFRh:bp4gvcc) ([raw file](https://github.com/cockroachdb/pebble/blob/8b1278a6c6afe639c10d36a9cf6dd5fca1fccc13/ingest.go#L308)):*
> ```Go
> 			return ingestLoadResult{}, err
> 		}
> 		if m != nil {
> ```

why would `m` be nil when `err` is nil?

I was suggesting validating that `shared[i].Level  < sharedLevelsStart` here. That is, the argument error checking should happen as early as possible. 


<!-- Sent from Reviewable.io -->

2023-06-12 16:41 UTC, itsbilal commented
Race test failure is #2613.

2023-06-12 16:41 UTC, merged