sharedcache: move to fine-grained locking
cockroachdb/pebble pull request #2586
Opened 2023-06-02 14:14 UTC by joshimhoff

Part of https://github.com/cockroachdb/pebble/issues/2541.

**sharedcache: fix bug that "leaks" cache block indexes**

This commit introduces assertions regarding in-memory shard state such as
s.mu.where & s.mu.free that caught an existing bug in the cache. The bug is:
If concurrent calls to ReadAt are made, then shard.set might be called for
a logical block that is already in the cache. Before this commit, such a
situation would "leak" a cache block, meaning the cache block index would
be removed from s.mu.where, implying the cache block could never be used
again. As of this commit, the bug is fixed.

**sharedcache: move to fine-grained locking**

Before this commit, s.mu was held when s.get & s.set were reading and
writing to s.file. This was done to simplify merging an intial implemenation
with the necessary correctness properties. This commit moves to fine-grained
locking, to improve the performance of the cache. A table mapping each cache
block index to its "lock state" is introduced. During the reading and writing
to s.file, only the specific cache block being updated is locked. Both read and
write locks are supported, so that multiple reads of some cache block can be
done concurrently. Also, writing back to the cache is now done asynchronously
with respect to the call to ReadAt.

With this commit merged, I think we can run some production experiments
measuring the efficiency of the cache.

2023-06-02 14:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2586)
<!-- Reviewable:end -->

2023-06-02 15:37 UTC, joshimhoff commented
I have just realized that my read lock approach doesn't work as is. In the case of two concurrent reads, the first reader to unlock will unlock despite that the second reader's read is not done. I will fix this bug, perhaps by keeping a reference count. 

I'll leave the PR up for review, despite this bug being present right now, as early feedback will be helpful.

2023-06-02 19:18 UTC, RaduBerinde reviewed
First commit LGTM

Yeah, the typical solution is to have a reader count where 0 = unlocked and -1 = write locked.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586#-:-NWxXT9X2Wla4Hel6SDp:bh45ji7)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @joshimhoff and @sumeerbhola)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 405 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NWxUtAWCYKC4yhx91C1:-NWxUtAWCYKC4yhx91C2:b-4puvck) ([raw file](https://github.com/cockroachdb/pebble/blob/447e324d2a5d6a7912cd10f10181b28cbfbfdf30/objstorage/objstorageprovider/sharedcache/shared_cache.go#L405)):*
> ```Go
> 		}
> 
> 		// Note that numWritten == writeSize, since we checked for an error above.
> ```

[nit] I'd just do `_, err :=` and use `writeSize`
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 423 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NWxUYp2DTlfNXKYSo4X:-NWxUYp2DTlfNXKYSo4Y:bgyzkn4) ([raw file](https://github.com/cockroachdb/pebble/blob/447e324d2a5d6a7912cd10f10181b28cbfbfdf30/objstorage/objstorageprovider/sharedcache/shared_cache.go#L423)):*
> ```Go
> 	for _, v := range s.mu.free {
> 		if cacheBlockInds[v] {
> 			panic(fmt.Sprintf("repeated cache block index: %v %v %v %v", v, cacheBlockInds, s.mu.where, s.mu.free))
> ```

[nit] use a different message (block both used and free?)
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NWxVJgt7PnqC74M2CMA:-NWxVJgt7PnqC74M2CMB:b-x4o2lq) ([raw file](https://github.com/cockroachdb/pebble/blob/450a89415286db7513f2750a4d5a9b901ca9a4f9/objstorage/objstorageprovider/sharedcache/shared_cache.go#L35)):*
> ```Go
> 	blockSize int
> 
> 	// WriteBackWaitGroup is public to enable testing from sharedcache_test.
> ```

What you can do to keep the non-testing code clean is to create a `_test` file that has `package sharedcache` and add getters, e.g. `func (c *Cache) WriteBackWaitGroup() sync.WaitGroup { return c.writeBackWaitGroup }`. These methods will be accessible from the other `_test` file.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 236 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NWxWLKyALVkmaCr3dFS:-NWxWLKyALVkmaCr3dFT:b8wk3po) ([raw file](https://github.com/cockroachdb/pebble/blob/450a89415286db7513f2750a4d5a9b901ca9a4f9/objstorage/objstorageprovider/sharedcache/shared_cache.go#L236)):*
> ```Go
> 		// TODO(josh): None of these datastructures are space-efficient.
> 		// Focusing on correctness to start.
> 		where map[whereMapKey]int64
> ```

[nit] consider making this a separate type and documenting what the value is
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 242 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NWxW4-z7ewjCLlGwhm9:-NWxW4-z7ewjCLlGwhmA:b-z28n9p) ([raw file](https://github.com/cockroachdb/pebble/blob/450a89415286db7513f2750a4d5a9b901ca9a4f9/objstorage/objstorageprovider/sharedcache/shared_cache.go#L242)):*
> ```Go
> }
> 
> type whereMapKey struct {
> ```

[nit] a better name would be descriptibe, e.g. `objectBlockID`
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 327 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NWxXEv21nU_GBhIoi6G:-NWxXEv21nU_GBhIoi6H:b9gpfv6) ([raw file](https://github.com/cockroachdb/pebble/blob/450a89415286db7513f2750a4d5a9b901ca9a4f9/objstorage/objstorageprovider/sharedcache/shared_cache.go#L327)):*
> ```Go
> 			// We could block on the write completing, but it is not necessary, since if two
> 			// reads are done in close succession, we would expect a hit on the second one due
> 			// to the in-memory block cache.
> ```

I was confused by this comment for a while, I'd rephrase along the lines of "In practice, if we have two reads of the same SST block in close succession, we would expect the second to hit in the in-memory block cache; so it's not worth optimizing this case here".


<!-- Sent from Reviewable.io -->

2023-06-05 12:49 UTC, joshimhoff reviewed
The code is now properly tracking the number of readers.

PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586#-:-NXAZ2bB0ZYI4IXcZoZn:blwmm18)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 405 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NWxUtAWCYKC4yhx91C1:-NXAVvqf1ZwII2glkkhB:bcvjgzp) ([raw file](https://github.com/cockroachdb/pebble/blob/447e324d2a5d6a7912cd10f10181b28cbfbfdf30/objstorage/objstorageprovider/sharedcache/shared_cache.go#L405)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I'd just do `_, err :=` and use `writeSize`
</blockquote></details>

Good idea. Done.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 423 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NWxUYp2DTlfNXKYSo4X:-NXAW7rMAYkJu_YdsKl5:b-hzd16b) ([raw file](https://github.com/cockroachdb/pebble/blob/447e324d2a5d6a7912cd10f10181b28cbfbfdf30/objstorage/objstorageprovider/sharedcache/shared_cache.go#L423)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] use a different message (block both used and free?)
</blockquote></details>

It doesn't necessarily mean block was used and in free, as block could be in free twice. The complete in-memory state is printed out tho, so I think the ambiguity is okay. Note tho that I did add a "(used)" or "(free)" suffix to the messages.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NWxVJgt7PnqC74M2CMA:-NXAYrwb-YNUOE8S5T1U:bclxk5d) ([raw file](https://github.com/cockroachdb/pebble/blob/450a89415286db7513f2750a4d5a9b901ca9a4f9/objstorage/objstorageprovider/sharedcache/shared_cache.go#L35)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What you can do to keep the non-testing code clean is to create a `_test` file that has `package sharedcache` and add getters, e.g. `func (c *Cache) WriteBackWaitGroup() sync.WaitGroup { return c.writeBackWaitGroup }`. These methods will be accessible from the other `_test` file.
</blockquote></details>

Done. Much better. Thank you.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 236 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NWxWLKyALVkmaCr3dFS:-NXAUCW9DBh0VXDQ7bYn:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/450a89415286db7513f2750a4d5a9b901ca9a4f9/objstorage/objstorageprovider/sharedcache/shared_cache.go#L236)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] consider making this a separate type and documenting what the value is
</blockquote></details>

Done.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 242 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NWxW4-z7ewjCLlGwhm9:-NXAVLTBCZOFNwuZTzDM:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/450a89415286db7513f2750a4d5a9b901ca9a4f9/objstorage/objstorageprovider/sharedcache/shared_cache.go#L242)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] a better name would be descriptibe, e.g. `objectBlockID`
</blockquote></details>

Done.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 327 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NWxXEv21nU_GBhIoi6G:-NXAVXcJ-5h7NnAaa_WJ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/450a89415286db7513f2750a4d5a9b901ca9a4f9/objstorage/objstorageprovider/sharedcache/shared_cache.go#L327)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I was confused by this comment for a while, I'd rephrase along the lines of "In practice, if we have two reads of the same SST block in close succession, we would expect the second to hit in the in-memory block cache; so it's not worth optimizing this case here".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-05 22:42 UTC, RaduBerinde approved these changes
> Reviewed 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586)* status: all files reviewed, 3 unresolved discussions (waiting on @joshimhoff and @sumeerbhola)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 274 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXCht2q3IY5kXepw3R0:-NXCht2q3IY5kXepw3R1:b-z47m0f) ([raw file](https://github.com/cockroachdb/pebble/blob/d96be4ea2e33b9286d8364352e08ad1d2d5ace0b/objstorage/objstorageprovider/sharedcache/shared_cache.go#L274)):*
> ```Go
> 	unlocked lockState = 0
> 	// locks tracks the number of distinct readers of the logical block in an SST.
> 	readLockTakenInc = 1
> ```

[nit] it doesn't make much sense to have this constant, I'd remove it and move the comment to `lockState`
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 484 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXCi1HTB3LA9IljI_65:-NXCi1HTB3LA9IljI_66:bh57mxn) ([raw file](https://github.com/cockroachdb/pebble/blob/d96be4ea2e33b9286d8364352e08ad1d2d5ace0b/objstorage/objstorageprovider/sharedcache/shared_cache.go#L484)):*
> ```Go
> func (s *shard) dropReadLock(cacheBlockInd int64) {
> 	s.mu.Lock()
> 	s.mu.locks[cacheBlockInd] -= readLockTakenInc
> ```

[nit] worth an `invariants` assertion that the count is > 0
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 491 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXCi47PBtbXjXHGIdEC:-NXCi47PBtbXjXHGIdED:b-179ues) ([raw file](https://github.com/cockroachdb/pebble/blob/d96be4ea2e33b9286d8364352e08ad1d2d5ace0b/objstorage/objstorageprovider/sharedcache/shared_cache.go#L491)):*
> ```Go
> func (s *shard) dropWriteLock(cacheBlockInd int64) {
> 	s.mu.Lock()
> 	s.mu.locks[cacheBlockInd] = unlocked
> ```

[nit] `invariants` assertion that the count is -1


<!-- Sent from Reviewable.io -->

2023-06-06 02:54 UTC, RaduBerinde approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586)* status: all files reviewed, 3 unresolved discussions (waiting on @joshimhoff and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-06-06 02:54 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586#-:-NXDc5dVBaztRRvOchiP:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @joshimhoff and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-06-06 14:26 UTC, joshimhoff reviewed
TTFR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586#-:-NXFirK3-ky451Guli8W:b-80vssw)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 274 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXCht2q3IY5kXepw3R0:-NXFfLqV5doW0jDCYCQv:b-ayyllo) ([raw file](https://github.com/cockroachdb/pebble/blob/d96be4ea2e33b9286d8364352e08ad1d2d5ace0b/objstorage/objstorageprovider/sharedcache/shared_cache.go#L274)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] it doesn't make much sense to have this constant, I'd remove it and move the comment to `lockState`
</blockquote></details>

Without it, I'd need to add a comment every time I did `lock += 1` or `lock > 0` to mention read locking. I agree it should always be zero... which is kind of odd. I'll leave it for now, based on the assumption you don't have strong feelings.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 484 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXCi1HTB3LA9IljI_65:-NXFfhX46jH1XdBRb9wd:bz5py0o) ([raw file](https://github.com/cockroachdb/pebble/blob/d96be4ea2e33b9286d8364352e08ad1d2d5ace0b/objstorage/objstorageprovider/sharedcache/shared_cache.go#L484)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] worth an `invariants` assertion that the count is > 0
</blockquote></details>

Good idea! Done.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 491 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXCi47PBtbXjXHGIdEC:-NXFgQWICsOo7lw-zQYh:b-896fja) ([raw file](https://github.com/cockroachdb/pebble/blob/d96be4ea2e33b9286d8364352e08ad1d2d5ace0b/objstorage/objstorageprovider/sharedcache/shared_cache.go#L491)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `invariants` assertion that the count is -1
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2023-06-06 15:52 UTC, RaduBerinde reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586#-:-NXGPBK05OlaZwg954HB:bnfp4nl)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-06-06 15:54 UTC, sumeerbhola requested changes
(apologies for the tardiness)

> Reviewed 1 of 3 files at r3, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586#-:-NXGPPGe15XLXJFAjOyH:b-4li34y)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @joshimhoff and @RaduBerinde)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGFMP663fjcdn3ctfP:-NXGFMP663fjcdn3ctfQ:b-1bcm17) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L143)):*
> ```Go
> 	// the number of bytes read successfully. As is, we cannot tell if the readable.ReadAt
> 	// should be returned from cache.ReadAt. For now, the cache just swallows all
> 	// io.EOF errors.
> ```

I thought the `Readable.ReadAt` interface was simplified by @RaduBerinde to not return the bytes read successfully because the Pebble callers do not try to read beyond the end of the file, so we did not need to distinguish the different errors. Is the issue here that the cache does not know the size of the object and attempts to read whole blocks, so can go over the end? We could add a `Size()` method to `ReaderAt` and not read beyond. I don't have an opinion on which approach is preferable. 
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 150 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGGtDd9Bkhr0s6jS7f:-NXGGtDd9Bkhr0s6jS7g:b1ozj2t) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L150)):*
> ```Go
> 
> 	// TODO(josh): For writing back to the cache, we may want a concurrency-limited approach
> 	// that does batching, instead of what is below. I think it's reasonable tho to
> ```

nit: though
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 153 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGGwbD2Ct1JVJemfi5:-NXGGwbD2Ct1JVJemfi6:b1nezhv) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L153)):*
> ```Go
> 	// run a production experiment with what is below, before making adjustments. Note that
> 	// the writes being done are in multiples of the filesystem block size. The filesystem
> 	// might do okay with them.
> ```

Could you elaborate on "The filesystem might do ...". I don't understand what is being said there, and how it relates to the concurrency-limited issue.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 275 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGLwfGBz1Cayk1tijY:-NXGLwfGBz1Cayk1tijZ:b-y1fol) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L275)):*
> ```Go
> 	// locks tracks the number of distinct readers of the logical block in an SST.
> 	readLockTakenInc = 1
> 	writeLockTaken   = -1
> ```

I think we need a code comment explaining the purpose of these.
IIUC, the readLock (which is really a read reference count -- may be worth renaming it), is ensuring that a cache block is not evicted and overwritten while there are readers.
The writeLock is for the case where someone is currently populating the cache block with the desired data.

Semantically, I don't think these "locks" belong with the cache block index. They are representing what is happening with a cache block that is currently assigned to a `logicalBlockID`. At eviction time, we can evict a `logicalBlockID` if *it* has no readers or a writer. At read time, we have to wait when reading the data for a `logicalBlockID` if a writer is currently writing it. So I think they should be in a struct that is the value in the map.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 335 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGLDXN0Ii6-BnmXAGp:-NXGLDXN0Ii6-BnmXAGq:b-k7zel) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L335)):*
> ```Go
> 	// The data extent might cross cache block boundaries, hence the loop. In the hot
> 	// path, max two iterations of this loop will be executed, since reads are sized
> 	// in units of sstable block size.
> ```

currently if there are 2 cache blocks needed to satisfy this read, and the first block is not in the cache and the second one is, will we end up reading both?
If yes, I think we should fix this (TODO is fine). This is not an unlikely scenario if we are doing a reverse scan, since those iterate over sstable blocks in reverse order and due to cache block aligned reads will have read the suffix of the sstable block that will be needed next.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 347 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGNMGP61xNfrGZuL-2:-NXGNMGP61xNfrGZuL-3:b2v6dzk) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L347)):*
> ```Go
> 			return n, nil
> 		}
> 		if s.mu.locks[cacheBlockInd] == writeLockTaken {
> ```

Slightly unrelated to this if-block, multiple reads within the same few milliseconds (anything that is smaller than the object store read latency) that miss on the same `logicalBlockID` will not necessarily be rare. We should have a TODO to measure the occurrences of such racing reads that end up all doing the same object store read. IIUC, such racing reads will likely return with the previous `if !ok`.

Coming to this if-block, this seems to to be the case where someone else has already done the read, and is in the process of populating the cache block. By returning here, this caller will do a (wasted) read. We should consider waiting for that write to finish. Again a TODO is fine. 
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 481 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGP7s16Yiezd_eB5BX:-NXGP7s16Yiezd_eB5BY:b4j4zhi) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L481)):*
> ```Go
> }
> 
> // Should be inlined.
> ```

Does it inline? I don't know if this matters much. The latency cost of cache hits will probably be dominated by the disk read.


<!-- Sent from Reviewable.io -->

2023-06-06 16:20 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @joshimhoff and @sumeerbhola)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGFMP663fjcdn3ctfP:-NXGR93f8KKD_ocLRgwb:b-24fq6r) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L143)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I thought the `Readable.ReadAt` interface was simplified by @RaduBerinde to not return the bytes read successfully because the Pebble callers do not try to read beyond the end of the file, so we did not need to distinguish the different errors. Is the issue here that the cache does not know the size of the object and attempts to read whole blocks, so can go over the end? We could add a `Size()` method to `ReaderAt` and not read beyond. I don't have an opinion on which approach is preferable. 
</blockquote></details>

This is correct, we may go over the size of the object here because of rounding up to the cache block size. The `Readable` already has a cheap `Size()` getter we can use for this.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 261 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGT_oi6g2VZRws_kVR:-NXGT_oi6g2VZRws_kVS:b-jfvycl) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L261)):*
> ```Go
> // Maps a logical block in an SST to an index of the cache block with the
> // file contents (to the "cache block index").
> type whereMap map[logicalBlockID]int64
> ```

[nit] consider defining a type for the cache block index
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 275 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGLwfGBz1Cayk1tijY:-NXGS6D-DLh3mRlSLHZk:b-3vdcku) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L275)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we need a code comment explaining the purpose of these.
IIUC, the readLock (which is really a read reference count -- may be worth renaming it), is ensuring that a cache block is not evicted and overwritten while there are readers.
The writeLock is for the case where someone is currently populating the cache block with the desired data.

Semantically, I don't think these "locks" belong with the cache block index. They are representing what is happening with a cache block that is currently assigned to a `logicalBlockID`. At eviction time, we can evict a `logicalBlockID` if *it* has no readers or a writer. At read time, we have to wait when reading the data for a `logicalBlockID` if a writer is currently writing it. So I think they should be in a struct that is the value in the map.
</blockquote></details>

I don't see the advantage of storing it in the map.. It is a property of a cache block and it's reasonable (and more memory-efficient, because of the hash map load factor) to keep the per-cache-block state in a simple table.

I support moving it to a struct that is documented as storing per-cache-block state. We will probably need to add the logical block ID to it too (to update the `whereMap` during eviction).
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 335 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGLDXN0Ii6-BnmXAGp:-NXGTm3b-ukt1Uiw5yVB:brtorln) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L335)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

currently if there are 2 cache blocks needed to satisfy this read, and the first block is not in the cache and the second one is, will we end up reading both?
If yes, I think we should fix this (TODO is fine). This is not an unlikely scenario if we are doing a reverse scan, since those iterate over sstable blocks in reverse order and due to cache block aligned reads will have read the suffix of the sstable block that will be needed next.
</blockquote></details>

Correct..  We could look at what's available at the end of the range as well. If there is a piece available inside, we will re-read it (but I think that's what we want, we don't want to break up into multiple read requests for cost reasons). I agree a TODO is fine for now though.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 347 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGNMGP61xNfrGZuL-2:-NXGUcqi29acVLXRrTAm:b-v5bav4) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L347)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Slightly unrelated to this if-block, multiple reads within the same few milliseconds (anything that is smaller than the object store read latency) that miss on the same `logicalBlockID` will not necessarily be rare. We should have a TODO to measure the occurrences of such racing reads that end up all doing the same object store read. IIUC, such racing reads will likely return with the previous `if !ok`.

Coming to this if-block, this seems to to be the case where someone else has already done the read, and is in the process of populating the cache block. By returning here, this caller will do a (wasted) read. We should consider waiting for that write to finish. Again a TODO is fine. 
</blockquote></details>

Ah.. We assumed that the second request would wait for the first in the pebble block cache but I see that's not the case.. Seems like it would be a bigger win if we did this there no?


<!-- Sent from Reviewable.io -->

2023-06-06 16:38 UTC, joshimhoff reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 153 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGGwbD2Ct1JVJemfi5:-NXGQcj07tGNWbS97PS3:b-u6an8p) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L153)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Could you elaborate on "The filesystem might do ...". I don't understand what is being said there, and how it relates to the concurrency-limited issue.
</blockquote></details>

Since the writes are done in units of filesystem block size already, and since the file system manages its own queue, I am not sure I can speak to the concrete benefit of either of the following changes:

- Batch up writing back blocks to the secondary cache
- Concurrency limit the number of writes to the secondary cache happening at once

I think it will be easier to speak to the need for those changes, once we benchmark the code as is.

Does it make sense now?

(I do think concurrency / rate limiting writes (maybe more the latter) could make sense as a prioritization scheme. Need fast reads more than fast writes, since reads face users. Maybe best to smooth out write rate as a result, when possible.)
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 275 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGLwfGBz1Cayk1tijY:-NXGYFPhB92Ug5wfzFIp:b-4mk0vq) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L275)):*
Will beef up commentary.

> So I think they should be in a struct that is the value in the map.

This is actually what I had initially :) 

Semantically, I don't see why it's wrong semantically to store a lock with the cache block index. What is locked is the range of bytes on disk pointed at by the cache block index, IMHO. Example: If there are active readers, it cannot be used to store a different logical block.

Sumeer, is your argument about clarity of code, or some concrete benefit to your suggested approach over what is here (e.g. less lock contention)? How strongly do you feel?
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 335 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGLDXN0Ii6-BnmXAGp:-NXGRMeWEEvI1qUeACk_:b-nv8v1i) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L335)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Correct..  We could look at what's available at the end of the range as well. If there is a piece available inside, we will re-read it (but I think that's what we want, we don't want to break up into multiple read requests for cost reasons). I agree a TODO is fine for now though.
</blockquote></details>

I will add a TODO. Thanks for noting the reverse scan use case.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 347 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGNMGP61xNfrGZuL-2:-NXGSPv65QUKlsQUHPcq:b-57a1uv) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L347)):*
Radu, not sure I follow what you have realized. I'm just gonna write out my current thinking re: Sumeer's Qs, so you can comment on it too.

> We should have a TODO to measure the occurrences of such racing reads that end up all doing the same object store read. IIUC, such racing reads will likely return with the previous `if !ok`.

Agree re: the behavior of the current code & will add a TODO.

> Coming to this if-block, this seems to to be the case where someone else has already done the read, and is in the process of populating the cache block. By returning here, this caller will do a (wasted) read. We should consider waiting for that write to finish. Again a TODO is fine.

An opinion I have related to this discussion is: Blocks should be written back to both the in-memory block cache AND the secondary cache, since having hot blocks in the secondary cache means no big latency hit in case of process restart. 

The reason I am not sure we need to optimize this case is: The seconder reader will hit the in-memory primary cache, since that is written to as part of the first sstable read, before the write back to the secondary cache (which is async unlike the write back the in-memory primary cache IIUC). 

Actually, ^^ is another reason that I think blocks should be written back to both the in-memory block cache AND the secondary cache.

Sumeer / Radu, let me know what you think about this, and either way I can beef up the comment / add a TODO.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 481 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGP7s16Yiezd_eB5BX:-NXGRn7G654aOAFLZ6-c:b-l03yfb) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L481)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Does it inline? I don't know if this matters much. The latency cost of cache hits will probably be dominated by the disk read.
</blockquote></details>

Do you suggest me checking if it inlines, or should I just remove the comment, since sort of a premature optimization anyway? Not sure how to check but could be a fun diversion.


<!-- Sent from Reviewable.io -->

2023-06-06 17:03 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @joshimhoff and @RaduBerinde)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 153 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGGwbD2Ct1JVJemfi5:-NXG_kIu0K0b_dq35Zvm:bkrlz00) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L153)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

Since the writes are done in units of filesystem block size already, and since the file system manages its own queue, I am not sure I can speak to the concrete benefit of either of the following changes:

- Batch up writing back blocks to the secondary cache
- Concurrency limit the number of writes to the secondary cache happening at once

I think it will be easier to speak to the need for those changes, once we benchmark the code as is.

Does it make sense now?

(I do think concurrency / rate limiting writes (maybe more the latter) could make sense as a prioritization scheme. Need fast reads more than fast writes, since reads face users. Maybe best to smooth out write rate as a result, when possible.)
</blockquote></details>

Ack. Do we have a metric for the cumulative write (and read) cache bytes so we can see whether the cache write bandwidth is significant when compared to the compaction and flush bandwidth?
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 275 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGLwfGBz1Cayk1tijY:-NXGaJFdEEfxKqCz2qOF:b-b55ti8) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L275)):*
> I don't see the advantage of storing it in the map

I am not claiming it as an advantage. I am claiming that semantically it belongs in the `whereMap` entry since it only makes sense for a `logicalBlockID` that is present in the cache -- it represents that `logicalBlockID`'s readers and writers. More sophisticated eviction is also related to the state maintained for `logicalBlockID`s, so I don't think there is any need for any complex state associated with each cache block (other than the list of free cache blocks).

Regarding memory efficiency, I am not sure we need to optimize that now. And we have ideas to move the map to a kv store.

Coming back to where it semantically belongs, I personally find the following code a bit awkward when thinking about correctness, since I have to think about whether `s.mu.locks[cacheBlockInd]` means a lock for this logical block or some other logical block that may be using the same `cacheBlockInd`. The fact that a `cacheBlockInd` is the map value of at most one `logicalBlockID` is a higher level invariant that we are already relying on.
```
		k := logicalBlockID{
			filenum:               fileNum,
			offsetInUnitsOfBlocks: (ofs + int64(n)) / int64(s.blockSize),
		}
		s.mu.Lock()
		cacheBlockInd, ok := s.mu.where[k]
		if !ok {
			s.mu.Unlock()
			return n, nil
		}
		if s.mu.locks[cacheBlockInd] == writeLockTaken {
```

Same for the following eviction code. Whether something can be evicted is a property of the `logicalBlockID`, IMO, so having to look up something by the `cacheBlockInd` seems odd.

```
			for k1, v := range s.mu.where {
				// This implies that hot blocks will not be evicted as often, meaning the
				// eviction scheme is not quite random. I think that's fine for now, since we plan
				// to leverage a more sophisticated eviction scheme eventually anyway.
				lock := s.mu.locks[v]
				if lock >= readLockTakenInc || lock == writeLockTaken {
					continue
				}
```

I don't want to bike shed either, so if you all are unanimous with the current scheme, feel free to ignore me.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 481 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGP7s16Yiezd_eB5BX:-NXGdvWC2hE3WWoAomXj:bns1jpp) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L481)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

Do you suggest me checking if it inlines, or should I just remove the comment, since sort of a premature optimization anyway? Not sure how to check but could be a fun diversion.
</blockquote></details>

In the sharedcache directory, do `go build -gcflags='-m -m' 2>  <output file>` and see what the output file says about inlining.
You may also find https://dave.cheney.net/high-performance-go-workshop/sydney-2019.html useful reading


<!-- Sent from Reviewable.io -->

2023-06-06 17:06 UTC, joshimhoff reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 275 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGLwfGBz1Cayk1tijY:-NXGf0K15ryx8xPIqc7T:bls0zd0) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L275)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> I don't see the advantage of storing it in the map

I am not claiming it as an advantage. I am claiming that semantically it belongs in the `whereMap` entry since it only makes sense for a `logicalBlockID` that is present in the cache -- it represents that `logicalBlockID`'s readers and writers. More sophisticated eviction is also related to the state maintained for `logicalBlockID`s, so I don't think there is any need for any complex state associated with each cache block (other than the list of free cache blocks).

Regarding memory efficiency, I am not sure we need to optimize that now. And we have ideas to move the map to a kv store.

Coming back to where it semantically belongs, I personally find the following code a bit awkward when thinking about correctness, since I have to think about whether `s.mu.locks[cacheBlockInd]` means a lock for this logical block or some other logical block that may be using the same `cacheBlockInd`. The fact that a `cacheBlockInd` is the map value of at most one `logicalBlockID` is a higher level invariant that we are already relying on.
```
		k := logicalBlockID{
			filenum:               fileNum,
			offsetInUnitsOfBlocks: (ofs + int64(n)) / int64(s.blockSize),
		}
		s.mu.Lock()
		cacheBlockInd, ok := s.mu.where[k]
		if !ok {
			s.mu.Unlock()
			return n, nil
		}
		if s.mu.locks[cacheBlockInd] == writeLockTaken {
```

Same for the following eviction code. Whether something can be evicted is a property of the `logicalBlockID`, IMO, so having to look up something by the `cacheBlockInd` seems odd.

```
			for k1, v := range s.mu.where {
				// This implies that hot blocks will not be evicted as often, meaning the
				// eviction scheme is not quite random. I think that's fine for now, since we plan
				// to leverage a more sophisticated eviction scheme eventually anyway.
				lock := s.mu.locks[v]
				if lock >= readLockTakenInc || lock == writeLockTaken {
					continue
				}
```

I don't want to bike shed either, so if you all are unanimous with the current scheme, feel free to ignore me.

</blockquote></details>

Thanks for giving your reasoning in more detail! Gonna think it over a bit before responding.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 481 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGP7s16Yiezd_eB5BX:-NXGfA6LBXUAaVszAMyU:b-9755fn) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L481)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

In the sharedcache directory, do `go build -gcflags='-m -m' 2>  <output file>` and see what the output file says about inlining.
You may also find https://dave.cheney.net/high-performance-go-workshop/sydney-2019.html useful reading
</blockquote></details>

Thank you!


<!-- Sent from Reviewable.io -->

2023-06-06 17:33 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @joshimhoff and @sumeerbhola)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 275 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGLwfGBz1Cayk1tijY:-NXGkBS82s0WdwdLbxQr:b-bnzso) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L275)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

Thanks for giving your reasoning in more detail! Gonna think it over a bit before responding.
</blockquote></details>

I think you can frame it both ways. To me the lock state is telling me the state of the physical cache block (whether I can read it or not). Similarly, the eviction algorithm could be on top of cache blocks not logical blocks (e.g. if it's LRU we can have a LRU list of cache blocks not a LRU list of logical block IDs.

Maybe for now leave a TODO to investigate whether this should live in the map.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 347 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGNMGP61xNfrGZuL-2:-NXGjfHZ1D0cqhlWIDJH:bat61q4) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L347)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

Radu, not sure I follow what you have realized. I'm just gonna write out my current thinking re: Sumeer's Qs, so you can comment on it too.

> We should have a TODO to measure the occurrences of such racing reads that end up all doing the same object store read. IIUC, such racing reads will likely return with the previous `if !ok`.

Agree re: the behavior of the current code & will add a TODO.

> Coming to this if-block, this seems to to be the case where someone else has already done the read, and is in the process of populating the cache block. By returning here, this caller will do a (wasted) read. We should consider waiting for that write to finish. Again a TODO is fine.

An opinion I have related to this discussion is: Blocks should be written back to both the in-memory block cache AND the secondary cache, since having hot blocks in the secondary cache means no big latency hit in case of process restart. 

The reason I am not sure we need to optimize this case is: The seconder reader will hit the in-memory primary cache, since that is written to as part of the first sstable read, before the write back to the secondary cache (which is async unlike the write back the in-memory primary cache IIUC). 

Actually, ^^ is another reason that I think blocks should be written back to both the in-memory block cache AND the secondary cache.

Sumeer / Radu, let me know what you think about this, and either way I can beef up the comment / add a TODO.
</blockquote></details>

The case is when we get a second read while we're reading data from blob storage. Currently we start a second read for the same data; it would be better if the second request would just wait for the first one to complete. But I'm arguing that it might be more beneficial to implement something like this at the in-memory block cache level rather than here.


<!-- Sent from Reviewable.io -->

2023-06-06 23:26 UTC, sumeerbhola requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586#-:-NXI0uaLB_ARLnr0zgYe:bg7igkv)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @joshimhoff and @RaduBerinde)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 275 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGLwfGBz1Cayk1tijY:-NXHpe2w0CCH0yz4muUN:b-lxoiya) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L275)):*
> the eviction algorithm could be on top of cache blocks not logical blocks

Agreed, that in some sense there are only cache blocks and some have data (and possibly readers/writers) and some are free. The map is only needed because we need a lookup data-structure for the cache blocks that have data. And those are the only ones that have ongoing readers/writers. Also those will be the only ones for which the hit related information is needed for eviction purposes. But yes, that unnecessary state can also be maintained for free blocks, and it doesn't cost much since in steady state the number of free blocks will be a tiny fraction of the total blocks.

So I withdraw my opinion -- it doesn't matter to me how this is setup now. I'll wait about having an opinion until we have the more sophisticated state for eviction, persistent map etc. :)
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 347 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGNMGP61xNfrGZuL-2:-NXHvIXY10wFcCfi9FGA:bkrqgfv) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L347)):*
> The reason I am not sure we need to optimize this case is: The seconder reader will hit the in-memory primary cache, since that is written to as part of the first sstable read, before the write back to the secondary cache (which is async unlike the write back the in-memory primary cache IIUC).

That's a good point.

> The case is when we get a second read while we're reading data from blob storage. Currently we start a second read for the same data; it would be better if the second request would just wait for the first one to complete. But I'm arguing that it might be more beneficial to implement something like this at the in-memory block cache level rather than here.

I agree that we could also put this in the in-memory block cache. But that cache is extremely performance sensitive wrt CPU cycles, so I am wary of adding waiting logic in there. My understanding of the lookup behavior is the following sequence:
- Get from block cache. If success or not a shared storage file, return.
- Get from shared cache. If success return.

Since we are falling through to the second step, and failure here requires a more expensive block storage read, we can do the waiting in the second step if there are other readers also encountering this miss. The CPU cycles for more complex code will matter less here.

btw, I've built such a cache in a past life -- all the readers of that block waited in a queue, and the first one was responsible for doing the read and populating the cache, and signaling the others when done. The one responsible for populating the cache could encounter a transient or permanent error. In that setting the code respected context cancellation, so the transient error could also be due to the higher-level request timing out -- we don't respect cancellation inside Pebble, but this has come up recently in https://github.com/cockroachdb/cockroach/issues/104262 (not that we need to change anything urgently in Pebble, but worth keeping in mind). A transient error would cause the reader to return the error to its caller and handoff the responsibility of the read to the next waiter. A permanent error would get recorded as a cache entry to avoid reading it again. I bring all this up because when reads were to the "local filesystem" we didn't worry much in the Pebble code about transient errors, but we need to handle them better now. I'm not quite sure what we are doing now for transient errors from object storage -- transparently retrying indefinitely on a transient error would makes the stuckness problem worse, given that contexts are not passed into Pebble. Glancing at a `cloud.ExternalStorage` implementation, s3_storage.go, it seems we don't retry at all. Is my understanding accurate?

 


<!-- Sent from Reviewable.io -->

2023-06-06 23:27 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586#-:-NXI1FbVBS_ZTp5joYCS:bg7igkv)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @joshimhoff and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2023-06-06 23:49 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @joshimhoff and @sumeerbhola)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 347 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGNMGP61xNfrGZuL-2:-NXI5xwi9sLGtczatsM4:bn2mfpi) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L347)):*
> Glancing at a `cloud.ExternalStorage` implementation, s3\_storage.go, it seems we don't retry at all. Is my understanding accurate?

In `ReadFileAt` we use a `NewResumingReader` which retries. We will probably need to tweak the retry settings for our purposes.


<!-- Sent from Reviewable.io -->

2023-06-07 13:54 UTC, joshimhoff reviewed
TTFRs! Interesting discussions all around.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586#-:-NXL2f1_CjthgQ9Pk3Ba:bs5n8tg)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGFMP663fjcdn3ctfP:-NXL6EfMASuBGERMWMw3:b-smgriy) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L143)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is correct, we may go over the size of the object here because of rounding up to the cache block size. The `Readable` already has a cheap `Size()` getter we can use for this.
</blockquote></details>

I updated the TODO to mention using `Size`. Radu, `ObjectReader` doesn't have a `Size` method. Do we just want to add one to the interface?

I'll try to follow up with a fix here before I go on vacation next week but a little short on time also.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 150 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGGtDd9Bkhr0s6jS7f:-NXL0bVs6avZGMkO1Hy-:bt2vr1b) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L150)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: though
</blockquote></details>

Fixed.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 153 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGGwbD2Ct1JVJemfi5:-NXL0m875DqSjA57drn-:bv4kc49) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L153)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Ack. Do we have a metric for the cumulative write (and read) cache bytes so we can see whether the cache write bandwidth is significant when compared to the compaction and flush bandwidth?
</blockquote></details>

Not yet. We should do an instrumentation PR soon. Agree with idea of having metrics for read & write BW coming from the cache.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 261 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGT_oi6g2VZRws_kVR:-NXL3bJs397mkmx9TREs:bcvjgzp) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L261)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] consider defining a type for the cache block index
</blockquote></details>

Good idea. Done.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 275 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGLwfGBz1Cayk1tijY:-NXL1OuSEy9bxlnfQPWG:b-t8oxoq) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L275)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> the eviction algorithm could be on top of cache blocks not logical blocks

Agreed, that in some sense there are only cache blocks and some have data (and possibly readers/writers) and some are free. The map is only needed because we need a lookup data-structure for the cache blocks that have data. And those are the only ones that have ongoing readers/writers. Also those will be the only ones for which the hit related information is needed for eviction purposes. But yes, that unnecessary state can also be maintained for free blocks, and it doesn't cost much since in steady state the number of free blocks will be a tiny fraction of the total blocks.

So I withdraw my opinion -- it doesn't matter to me how this is setup now. I'll wait about having an opinion until we have the more sophisticated state for eviction, persistent map etc. :)

</blockquote></details>

Good discussion. Will leave as is for now.
___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 347 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGNMGP61xNfrGZuL-2:-NXL1e_U8Z1VjlCToYrR:b838kl7) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L347)):*
I've added a TODO about repeat reads. I noted that it could go in either the primary or secondary cache, and I linked this PR also, since there are additional details in this thread.

> I bring all this up because when reads were to the "local filesystem" we didn't worry much in the Pebble code about transient errors, but we need to handle them better now.

This is an interesting observation.


<!-- Sent from Reviewable.io -->

2023-06-07 13:55 UTC, joshimhoff commented
Still need to add a bit more to the comments as per earlier threads. Doing that now.

2023-06-07 14:18 UTC, joshimhoff reviewed
Added additional commentary, TODOs, etc.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586#-:-NXLDHyEDdfDL24YmKoh:b1hlyiy)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @RaduBerinde and @sumeerbhola)

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 481 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGP7s16Yiezd_eB5BX:-NXLD7093J2RQccMBi6m:b-2e9sfy) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L481)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

Thank you!
</blockquote></details>

Doesn't inline:

```
~/g/s/g/c/p/o/o/sharedcache [fine-grained-locks] $ cat inline | grep 'drop'
./shared_cache.go:500:6: cannot inline (*shard).dropReadLock: function too complex: cost 163 exceeds budget 80
./shared_cache.go:512:6: cannot inline (*shard).dropWriteLock: function too complex: cost 163 exceeds budget 80
./shared_cache.go:338:7:     from (*shard).dropReadLock(s, cacheBlockInd) (call parameter) at ./shared_cache.go:387:18
./shared_cache.go:338:7:     from (*shard).dropReadLock(s, cacheBlockInd) (call parameter) at ./shared_cache.go:387:18
~/g/s/g/c/p/o/o/sharedcache [fine-grained-locks] $ cat inline | grep 'freeBlock'
./shared_cache.go:524:6: cannot inline (*shard).freeBlock: function too complex: cost 177 exceeds budget 80
./shared_cache.go:406:7:     from (*shard).freeBlock(s, k, cacheBlockInd) (call parameter) at ./shared_cache.go:490:15
./shared_cache.go:406:7:     from (*shard).freeBlock(s, k, cacheBlockInd) (call parameter) at ./shared_cache.go:490:15
```

I have adjusted the comment to note this.


<!-- Sent from Reviewable.io -->

2023-06-07 14:27 UTC, merged

2023-06-07 14:32 UTC, RaduBerinde commented
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGFMP663fjcdn3ctfP:-NXLGI6q1lGeCMwjumim:bx97m72) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L143)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

I updated the TODO to mention using `Size`. Radu, `ObjectReader` doesn't have a `Size` method. Do we just want to add one to the interface?

I'll try to follow up with a fix here before I go on vacation next week but a little short on time also.
</blockquote></details>

`objstorage.Readable` has a `Size()` method. We can just pass the size to the cache, along with the `ObjectReader`


<!-- Sent from Reviewable.io -->

2023-06-07 14:33 UTC, joshimhoff reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2586)* status: 3 of 4 files reviewed, 7 unresolved discussions

___
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGFMP663fjcdn3ctfP:-NXLG_9z4fdvXfIV-wwY:b-g6llew) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L143)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`objstorage.Readable` has a `Size()` method. We can just pass the size to the cache, along with the `ObjectReader`
</blockquote></details>

Makes sense. Thanks!


<!-- Sent from Reviewable.io -->

2023-06-07 14:33 UTC, RaduBerinde commented
*[`objstorage/objstorageprovider/sharedcache/shared_cache.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/pebble/2586#-NXGFMP663fjcdn3ctfP:-NXLGThL68MG45gkMhYJ:b-j1bbka) ([raw file](https://github.com/cockroachdb/pebble/blob/cf8e66b7fba6685e9b1834559ef5b1471842ad5f/objstorage/objstorageprovider/sharedcache/shared_cache.go#L143)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`objstorage.Readable` has a `Size()` method. We can just pass the size to the cache, along with the `ObjectReader`
</blockquote></details>

More specifically -`sharedReadable` has a `size` field


<!-- Sent from Reviewable.io -->