*: allow virtual sstables to truncate range keys/dels
cockroachdb/pebble pull request #2672
Opened 2023-06-23 16:01 UTC by itsbilal

Previously, our virtual sstable read code panicked if we saw a rangedel or rangekey get truncated at a virtual sstable file bound. While this is rare, this is an allowable use of virtual sstables in Cockroach and one that will (on rare occasion) happen organically, eg. when there are two range dels or range keys that abut each other while in different KV ranges (thereby getting defragmented by Pebble, which isn't aware of CockroachDB ranges).

Also add a guard against 0 filesizes, which can cause panics in compaction code.

2023-06-23 16:01 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2672)
<!-- Reviewable:end -->

2023-06-26 21:50 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2672)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @itsbilal)

___
*[`sstable/reader.go` line 2963 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NYtcnq95wHeyv9yU8c1:-NYtcnq95wHeyv9yU8c2:b-55mr1) ([raw file](https://github.com/cockroachdb/pebble/blob/975fbcb07b9285309864318d64e02fa9c33f1511/sstable/reader.go#L2963)):*
> ```Go
> 	return keyspan.Truncate(
> 		v.reader.Compare, iter, v.vState.lower.UserKey, v.vState.upper.UserKey,
> 		&v.vState.lower, &v.vState.upper, true, /* panicOnPartialOverlap */
> ```

A `Span` has an inclusive start key, and an exclusive end key. The bounds used for truncation are `v.vState.lower.UserKey, v.vState.upper.UserKey`.

`v.vState.upper.UserKey` can be inclusive. Let's say it is.

Let's say we're truncating some `Span` `s` with bounds `s.Start`, and `s.End`. And `S.End` > `v.vState.upper.UserKey`.  So, we'll truncate `End` to `v.vState.upper.UserKey`. This is probably incorrect, because the end key of the span is always treated as exclusive, whereas we want to treat `v.vState.upper.UserKey` as inclusive.

Instead of passing in `&v.vState.upper` into the `Truncate` function, could we manufacture a key which is lexicographically one greater than > `v.vState.upper.UserKey` ?


<!-- Sent from Reviewable.io -->

2023-06-27 21:19 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2672)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @bananabrick)

___
*[`sstable/reader.go` line 2963 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NYtcnq95wHeyv9yU8c1:-NYygbFX42OzRxi0lWvS:bksbk3n) ([raw file](https://github.com/cockroachdb/pebble/blob/975fbcb07b9285309864318d64e02fa9c33f1511/sstable/reader.go#L2963)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

A `Span` has an inclusive start key, and an exclusive end key. The bounds used for truncation are `v.vState.lower.UserKey, v.vState.upper.UserKey`.

`v.vState.upper.UserKey` can be inclusive. Let's say it is.

Let's say we're truncating some `Span` `s` with bounds `s.Start`, and `s.End`. And `S.End` > `v.vState.upper.UserKey`.  So, we'll truncate `End` to `v.vState.upper.UserKey`. This is probably incorrect, because the end key of the span is always treated as exclusive, whereas we want to treat `v.vState.upper.UserKey` as inclusive.

Instead of passing in `&v.vState.upper` into the `Truncate` function, could we manufacture a key which is lexicographically one greater than > `v.vState.upper.UserKey` ?
</blockquote></details>

You bring up a good point, which is that a virtual sstable `[a#4,SET-b#7,SET]` that has a rangedel `[aa-e)` inside it would end up exposing the key at `b#7, SET`even if it is originally deleted by it, because we'll truncate the rangedel to an exclusive at the file upper bound even if it's inclusive there. Since the "generate a key that's exactly one higher" problem is not worth generalizing all the way up to Cockroach, we can achieve the same purpose of this PR by setting panicOnPartialOverlap to `!fileUpper.IsExclusiveSentinel()`, which is that we will only truncate range dels and range keys at a file bound key if the upper bound key is an exclusive sentinel. This is an easy contract to obey for both excises and ingest-time splits. We can relax the panic for any truncations on the lower end.

I've made this change, PTAL!


<!-- Sent from Reviewable.io -->

2023-06-29 20:25 UTC, bananabrick reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2672)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @itsbilal)

___
*[`ingest.go` line 1467 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NZ7oDl45NTyHrrkxglU:-NZ7oDl45NTyHrrkxglV:b-xdy8ft) ([raw file](https://github.com/cockroachdb/pebble/blob/1f5f2a95c338f1586cc5e29652ec9b119cb6a258/ingest.go#L1467)):*
> ```Go
> 			}
> 			if leftFile.Size == 0 {
> 				// On occasion, estimateSize gives us a low estimate, i.e. a 0 file size. This
> ```

Do you know when this can return 0?

Looking at the `EstimateDiskUsage` function, the last return line is:

```
return includeInterpolatedValueBlocksSize(
    endBH.Offset + endBH.Length + blockTrailerLen - startBH.Offset), nil)
```
Shouldn't the `startBh.Offset` be <= `endBH.Offset`, so we should get a value > 0.

The function does say that only blocks containing point keys are considered. So, maybe that has something to do with this.
___
*[`sstable/reader.go` line 2963 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NYtcnq95wHeyv9yU8c1:-NYz0ixf9XOcHGpmzM22:b-gjk47v) ([raw file](https://github.com/cockroachdb/pebble/blob/975fbcb07b9285309864318d64e02fa9c33f1511/sstable/reader.go#L2963)):*
> Since the "generate a key that's exactly one higher" problem is not worth generalizing all the way up to Cockroach

Would we have to do that? Would it be sufficient to pass in the next lexicographically higher key of `vState.upper.UserKey` to the `upper` parameter of `Truncate`?

I'm fine with ensuring this invariant, but we should document/enforce these invariants on virtual sstable creation. Maybe in `FileMetadata.ValidateVirtual`. What do you think?

Could you also clarify why we can ensure this invariant for inclusive end keys but not exclusive end key?
___
*[`sstable/reader.go` line 2961 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NZ7TGyy1gSSe5BYw1E1:-NZ7TGyz7imdkZv4W89o:bykn3h3) ([raw file](https://github.com/cockroachdb/pebble/blob/1f5f2a95c338f1586cc5e29652ec9b119cb6a258/sstable/reader.go#L2961)):*
> ```Go
> 	// Truncation of spans isn't allowed at a user key that also contains points
> 	// in the same virtual sstable, as it would lead to covered points getting
> 	// uncovered. Set panicOnUpperTruncate to true if the file's upper bound
> ```

I think we should add an example here to clarify why we're doing this, and also in the comment below.


<!-- Sent from Reviewable.io -->

2023-07-04 20:45 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2672#-:-NZXdfL7EX_hCvXRwge7:b-814g8k)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @bananabrick)

___
*[`ingest.go` line 1467 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NZ7oDl45NTyHrrkxglU:-NZXZG3M1mafd7yk0MSt:b-4yqy6z) ([raw file](https://github.com/cockroachdb/pebble/blob/1f5f2a95c338f1586cc5e29652ec9b119cb6a258/ingest.go#L1467)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

Do you know when this can return 0?

Looking at the `EstimateDiskUsage` function, the last return line is:

```
return includeInterpolatedValueBlocksSize(
    endBH.Offset + endBH.Length + blockTrailerLen - startBH.Offset), nil)
```
Shouldn't the `startBh.Offset` be <= `endBH.Offset`, so we should get a value > 0.

The function does say that only blocks containing point keys are considered. So, maybe that has something to do with this.

</blockquote></details>

Yeah that's basically it; we end up in cases where there are no point keys in the virtual sstable but there's a rangedel or range key. the code for `EstimateDiskUsage` has a bunch of `if key == nil { return 0, iter.Error() }` cases in it, which ends up returning `0, nil` if the iterator also didn't error out and just happened to have nothing in the range (or a seekGE at the start key put us past all the index entries).
___
*[`sstable/reader.go` line 2963 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NYtcnq95wHeyv9yU8c1:-NZXcIWc7nDt24xO1OVz:b-hvy0gl) ([raw file](https://github.com/cockroachdb/pebble/blob/975fbcb07b9285309864318d64e02fa9c33f1511/sstable/reader.go#L2963)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

> Since the "generate a key that's exactly one higher" problem is not worth generalizing all the way up to Cockroach

Would we have to do that? Would it be sufficient to pass in the next lexicographically higher key of `vState.upper.UserKey` to the `upper` parameter of `Truncate`?

I'm fine with ensuring this invariant, but we should document/enforce these invariants on virtual sstable creation. Maybe in `FileMetadata.ValidateVirtual`. What do you think?

Could you also clarify why we can ensure this invariant for inclusive end keys but not exclusive end key?




</blockquote></details>

The issue is that generating the "next lexicographically higher key of x" is not a problem we want to solve, as it reduces generality. Pebble so far has stayed away from having a comparer method that does that, and we probably want to keep it that way.

We should check for this in `ValidateVirtual`, yes, but we already have https://github.com/cockroachdb/pebble/issues/2593  to do that.
___
*[`sstable/reader.go` line 2961 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NZ7TGyy1gSSe5BYw1E1:-NZXc3NH0TR_O6sADspn:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/1f5f2a95c338f1586cc5e29652ec9b119cb6a258/sstable/reader.go#L2961)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I think we should add an example here to clarify why we're doing this, and also in the comment below.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-05 13:45 UTC, sumeerbhola requested changes
> Reviewed 1 of 8 files at r2, 3 of 5 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2672)* status: 6 of 9 files reviewed, 6 unresolved discussions (waiting on @bananabrick and @itsbilal)

___
*[`-- commits` line 10 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NZ_zw-S0ajjb51p0sMt):*
I am assuming this could also happen because a CockroachDB range got split, and there was a rangedel  or rangekey that was written before the split and later we excised one of the post-split ranges?
___
*[`ingest.go` line 1467 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NZ7oDl45NTyHrrkxglU:-NZa6N8R6V5u3OXqTrVD:b-7j2g8w) ([raw file](https://github.com/cockroachdb/pebble/blob/1f5f2a95c338f1586cc5e29652ec9b119cb6a258/ingest.go#L1467)):*
> we end up in cases where there are no point keys in the virtual sstable but there's a rangedel or range key.

can you add this as a code comment here.
___
*[`ingest.go` line 1578 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NZa6S1nD8NuGTCN2wpg:-NZa6S1nD8NuGTCN2wph:b-7ropln) ([raw file](https://github.com/cockroachdb/pebble/blob/77fa822d62d334ec4f525db666e2d6924cd8880f/ingest.go#L1578)):*
> ```Go
> 			// On occasion, estimateSize gives us a low estimate, i.e. a 0 file size. This
> 			// can cause panics in places where we divide by file sizes. Correct for it
> 			// here.
> ```

ditto
___
*[`internal/keyspan/truncate.go` line 68 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NZa7tXmARcce3UpajRl:-NZa7tXmARcce3UpajRm:b-kdogrj) ([raw file](https://github.com/cockroachdb/pebble/blob/77fa822d62d334ec4f525db666e2d6924cd8880f/internal/keyspan/truncate.go#L68)):*
> ```Go
> 
> 		if panicOnUpperTruncate && truncated {
> 			panic("pebble: bounds should not be truncated")
> ```

nit: upper bound should not be truncated
___
*[`sstable/reader.go` line 2963 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NYtcnq95wHeyv9yU8c1:-NZaAaTD0iui9rXoZU74:b-32i932) ([raw file](https://github.com/cockroachdb/pebble/blob/975fbcb07b9285309864318d64e02fa9c33f1511/sstable/reader.go#L2963)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The issue is that generating the "next lexicographically higher key of x" is not a problem we want to solve, as it reduces generality. Pebble so far has stayed away from having a comparer method that does that, and we probably want to keep it that way.

We should check for this in `ValidateVirtual`, yes, but we already have https://github.com/cockroachdb/pebble/issues/2593  to do that.
</blockquote></details>

I am getting confused by the reasoning here, so I'll try to replay what I can re-construct from this discussion and code.
- The virtualization of a table always uses userkey bound of the form [start-user-key, end-user-key), whether this happens via excise (for the left and right tables) or when exporting a shared file.
- The largest point key in this sst must be < end-user-key.
- A rangedel is truncated by this virtualization on the right-hand-side iff it straddles end-user-key. In that case the end-user-key exclusive sentinel is the contribution of this rangedel to the virtual sst upper bound. Then truncating at that end-user-key does not expose any covered point key.
- A similar argument applies to rangekeys. However, when both a rangedel and rangekey straddle the end-user-key, the sst upper bound will be due to the rangedel sentinel (since rangedel InternalKeyKind sorts after). This is fine since we use the general `v.vState.upper.IsExclusiveSentinel()` call to decide whether truncation is permitted or not.

We have lost some fidelity in that we will permit truncation of a rangedel if there is a rangekey that straddled end-user-key but not a rangedel (and vice versa), but that is ok from a correctness perspective since there won't actually be any truncation of the rangedel in that case.

Is this accurate?

It would be nice if we had a code comment that laid this out clearly in some high-level place where we define sst virtualization.


<!-- Sent from Reviewable.io -->

2023-07-06 17:11 UTC, itsbilal reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2672#-:-NZgAyDs9M7ZxrPV6B6H:bz5mair)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @bananabrick and @sumeerbhola)

___
*[`-- commits` line 10 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NZ_zw-S0ajjb51p0sMt):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am assuming this could also happen because a CockroachDB range got split, and there was a rangedel  or rangekey that was written before the split and later we excised one of the post-split ranges?
</blockquote></details>

That's right. That would also do it.
___
*[`ingest.go` line 1467 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NZ7oDl45NTyHrrkxglU:-NZg3xBDAg2f-i5kgX7_:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/1f5f2a95c338f1586cc5e29652ec9b119cb6a258/ingest.go#L1467)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> we end up in cases where there are no point keys in the virtual sstable but there's a rangedel or range key.

can you add this as a code comment here.
</blockquote></details>

Done.
___
*[`ingest.go` line 1578 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NZa6S1nD8NuGTCN2wpg:-NZg49kW95D7m_6bl0Ro:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/77fa822d62d334ec4f525db666e2d6924cd8880f/ingest.go#L1578)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`internal/keyspan/truncate.go` line 68 at r4](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NZa7tXmARcce3UpajRl:-NZg4AMe-6AbN_tJzFX3:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/77fa822d62d334ec4f525db666e2d6924cd8880f/internal/keyspan/truncate.go#L68)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: upper bound should not be truncated
</blockquote></details>

Done.
___
*[`sstable/reader.go` line 2963 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NYtcnq95wHeyv9yU8c1:-NZg4GwaEdmncH2hRqc9:bsdvqd5) ([raw file](https://github.com/cockroachdb/pebble/blob/975fbcb07b9285309864318d64e02fa9c33f1511/sstable/reader.go#L2963)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am getting confused by the reasoning here, so I'll try to replay what I can re-construct from this discussion and code.
- The virtualization of a table always uses userkey bound of the form [start-user-key, end-user-key), whether this happens via excise (for the left and right tables) or when exporting a shared file.
- The largest point key in this sst must be < end-user-key.
- A rangedel is truncated by this virtualization on the right-hand-side iff it straddles end-user-key. In that case the end-user-key exclusive sentinel is the contribution of this rangedel to the virtual sst upper bound. Then truncating at that end-user-key does not expose any covered point key.
- A similar argument applies to rangekeys. However, when both a rangedel and rangekey straddle the end-user-key, the sst upper bound will be due to the rangedel sentinel (since rangedel InternalKeyKind sorts after). This is fine since we use the general `v.vState.upper.IsExclusiveSentinel()` call to decide whether truncation is permitted or not.

We have lost some fidelity in that we will permit truncation of a rangedel if there is a rangekey that straddled end-user-key but not a rangedel (and vice versa), but that is ok from a correctness perspective since there won't actually be any truncation of the rangedel in that case.

Is this accurate?

It would be nice if we had a code comment that laid this out clearly in some high-level place where we define sst virtualization.
</blockquote></details>

What you described is mostly accurate. One of the things to keep in mind is that while excise/truncation of shared files happens with a `[start, end)` user key bound in mind, the actual `FileMetadata` we generate for the truncated file(s) is of a `[start, end]` bound that's tight on user keys. We actually iterate the sstable to find the new smallest and largest internal keys, and set the SST to that.

The complex cases are, say, when you have an sstable 00009:

```
00009.sst:
a.RANGEKEYSET.8:d
a.SET.5:foo
b.SET.6:bar
```

And you're excising `b-e`. In this case the new LARGEST will be `b#RANGEKEYSET,inf`and the smallest will stay the same. The point keys get excluded. Since excise always operates on a `[smallest, largest)` excised span, if we're in the case where we're truncating away the right half of a rangekey or rangedel, we can always set the largest for the sstable left of the excise to a range del/key sentinel. We can also observe that in *all* cases where we truncate a range key/del on the upper bound, we will always have a fileMetadata with a largest key that's a sentinel key. So we leverage that observation to update this assertion to allow upper-bound truncates only if fileMeta.Largest.IsExclusiveSentinel() is true.

We don't need to pay too much attention to whether that's a rangedel or range key sentinel, at least from a correctness perspective. 

I already added a comment with a similar example in `VirtualReader.NewRawRange{Del,Key}Iter`. The unfortunate thign is that there's no single place where we define sstable virtualization. Maybe we should also copy or reference this comment in the places where we create virtual sstables (currently it's only `ingestLoad1Shared/truncateSharedFiles` and `excise`).


<!-- Sent from Reviewable.io -->

2023-07-06 21:27 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 9 files at r1, 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2672#-:-NZh5_yj9aY7nnjc3wk7:bg7igkv)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @bananabrick)

___
*[`sstable/reader.go` line 2963 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NYtcnq95wHeyv9yU8c1:-NZgzc1YEl3_9DeghbXh:bepppx2) ([raw file](https://github.com/cockroachdb/pebble/blob/975fbcb07b9285309864318d64e02fa9c33f1511/sstable/reader.go#L2963)):*
> We actually iterate the sstable to find the new smallest and largest internal keys, and set the SST to that.

Right. I didn't mention that in the comment since the reasoning about correctness did not seem to require that assumption. But considering that in the example definitely helps the reader.

I think we could use a long code comment on `VirtualFileMeta` -- since that is just a pointer to a `FileMetadata` we have implicitly inherited the comments on the `FileMetadata` fields, which don't tell us anything about what `Smallest*`, `Largest*` on a virtual sst mean and what invariants they must satisfy relative to the actual data in the physical sst.
 


<!-- Sent from Reviewable.io -->

2023-07-07 19:36 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2672#-:-NZlqgYo51L4P1BOt1lV:b-814g8k)* status: 8 of 10 files reviewed, 5 unresolved discussions (waiting on @bananabrick and @sumeerbhola)

___
*[`sstable/reader.go` line 2963 at r1](https://reviewable.io/reviews/cockroachdb/pebble/2672#-NYtcnq95wHeyv9yU8c1:-NZlqiEC4wxDFxCv6xs3:b-t4k8ut) ([raw file](https://github.com/cockroachdb/pebble/blob/975fbcb07b9285309864318d64e02fa9c33f1511/sstable/reader.go#L2963)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> We actually iterate the sstable to find the new smallest and largest internal keys, and set the SST to that.

Right. I didn't mention that in the comment since the reasoning about correctness did not seem to require that assumption. But considering that in the example definitely helps the reader.

I think we could use a long code comment on `VirtualFileMeta` -- since that is just a pointer to a `FileMetadata` we have implicitly inherited the comments on the `FileMetadata` fields, which don't tell us anything about what `Smallest*`, `Largest*` on a virtual sst mean and what invariants they must satisfy relative to the actual data in the physical sst.
 
</blockquote></details>

Added the comment, good idea. Thanks!


<!-- Sent from Reviewable.io -->

2023-07-07 19:50 UTC, merged