db: do not cache compaction block reads
cockroachdb/pebble pull request #2699
Opened 2023-06-29 19:19 UTC by jbowens

2023-06-29 19:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2699)
<!-- Reviewable:end -->

2023-06-29 19:24 UTC, jbowens commented
@cockroachdb/storage — I'd appreciate a look this afternoon on this. I don't need a thorough look, but would like to identify any egregious correctness issues.

2023-07-13 22:59 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 12 of 15 files at r1, 2 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2699#-:-N_GTdNiEt2Dho1r5ZKl:b-uwkowd)* status: all files reviewed, 1 unresolved discussion (waiting on @bananabrick and @jbowens)

___
*[`sstable/buffer_pool.go` line 77 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_GTYxRCScuNXpqGUo9:-N_GTYxRCScuNXpqGUoA:b-hh2do0) ([raw file](https://github.com/cockroachdb/pebble/blob/9017c6da53551404125bb0bc2325799081c7fc30/sstable/buffer_pool.go#L77)):*
> ```Go
> 	*p = BufferPool{
> 		cache: cache,
> 		pool:  pool,
> ```

[nit] should we do `pool[:0]` here so there's no possibility of misuse?


<!-- Sent from Reviewable.io -->

2023-07-14 13:56 UTC, sumeerbhola requested changes
> Reviewed 7 of 15 files at r1, 2 of 4 files at r2, 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2699)* status: all files reviewed, 8 unresolved discussions (waiting on @bananabrick and @jbowens)

___
*[`compaction.go` line 2756 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_Jac6K0XuyJMxmvG7Q:-N_Jac6K0XuyJMxmvG7R:brqfg85) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/compaction.go#L2756)):*
> ```Go
> 
> 	// Compactions use a pool of buffers to read blocks, avoiding polluting the
> 	// block cache with blocks that will not be read again.
> ```

Can you add a comment on why 5 is a good value for initial size.
In the worst-case with 2 level compactions do we have up to 2 data blocks, 2 value blocks, 2 rangedel blocks and 2 rangekey blocks allocated?
___
*[`sstable/block.go` line 405 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_JbJ_K89UCKnKJilQR:-N_JbJ_K89UCKnKJilQS:b-5k2prd) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/sstable/block.go#L405)):*
> ```Go
> 	cached      []blockEntry
> 	cachedBuf   []byte
> 	cacheHandle cache.Handle
> ```

is `cacheHandle` unused, since we have the `cache.Handle` inside `bufferHandle`?
___
*[`sstable/buffer_pool.go` line 49 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_J_48I2Mc_s5IBvTAf:-N_J_48I2Mc_s5IBvTAg:bxts0ub) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/sstable/buffer_pool.go#L49)):*
> ```Go
> 	// pool contains all the buffers held by the pool, including buffers that
> 	// are in-use.
> 	pool []allocedBuffer
> ```

IIUC, the invariant is that for every `pool[i]` the `pool[i].v` value is non-nil. If so, can you add a comment.
___
*[`sstable/buffer_pool.go` line 66 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_JYweJ8ksxty97dNL1:-N_JYweJ8ksxty97dNL2:b-bbo17j) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/sstable/buffer_pool.go#L66)):*
> ```Go
> func (p *BufferPool) Init(cache *cache.Cache, initialSize int) {
> 	*p = BufferPool{
> 		cache: cache,
> ```

I don't see why `cache.Alloc` and `cache.Free` are methods on the `Cache` struct. They don't seem to reference anything in the cache. Could they be functions. Then we don't need `cache` as a member.
___
*[`sstable/buffer_pool.go` line 139 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_JXT-j1_bqYcSBWXwm:-N_JXT-j1_bqYcSBWXwn:b-rpm11n) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/sstable/buffer_pool.go#L139)):*
> ```Go
> 	// is no longer in use and a future call to BufferPool.Alloc may reuse this
> 	// buffer.
> 	b.p.pool[b.i].b = nil
> ```

This code is not setting `b.p` to nil, which makes me worry that if `Release` is accidentally called again it may free a buffer that no longer belongs to `Buf`. I suppose we can't do better because `Release` is a value receiver. I am guessing making it a pointer receiver is not going to cause `Buf` to be heap allocated, in which case we could fix this.
___
*[`sstable/reader.go` line 3429 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_JczqAC7DG0fJIy7QD:-N_JczqB0-JkfWrhJ1Fr:b-rzrpq3) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/sstable/reader.go#L3429)):*
> ```Go
> 			decompressed = cacheValueOrBuf{buf: bufferPool.Alloc(decodedLen)}
> 		} else {
> 			decompressed = cacheValueOrBuf{
> ```

so we need two bufs for each block, which means my previous comment may have undercounted by 2x.
___
*[`sstable/value_block.go` line 753 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_Jejq14lZAuUPITjpj:-N_Jejq14lZAuUPITjpk:bpxr5t4) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/sstable/value_block.go#L753)):*
> ```Go
> ) (bufferHandle, error) {
> 	ctx = objiotracing.WithBlockType(ctx, objiotracing.ValueBlock)
> 	return bpwc.r.readBlock(ctx, h, nil, nil, stats, nil /* buffer pool */)
> ```

this case should be rare enough but if we needed to use the buffer pool we could since the `blockProviderWhenClosed` is not allowed to outlive the iterator tree, which means it cannot outlive the buffer pool.


<!-- Sent from Reviewable.io -->

2023-07-14 19:48 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2699)* status: all files reviewed, 7 unresolved discussions (waiting on @bananabrick and @sumeerbhola)

___
*[`compaction.go` line 2756 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_Jac6K0XuyJMxmvG7Q:-N_Kf2gIBUKmVvOEq0QA:b-gfrntd) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/compaction.go#L2756)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a comment on why 5 is a good value for initial size.
In the worst-case with 2 level compactions do we have up to 2 data blocks, 2 value blocks, 2 rangedel blocks and 2 rangekey blocks allocated?
</blockquote></details>

In the worst case for a two-level compaction, we have up to 2 index blocks, 2 data blocks, 2 value blocks, _n_ rangedel blocks and _n_ rangekey blocks + 1 ephemeral block used to hold the intermediary compressed data block during a block load. I've bumped this up to 12 and written up a justification.
___
*[`sstable/block.go` line 405 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_JbJ_K89UCKnKJilQR:-N_Kjm1ABXhpiy3AyM-8:b-oz8o77) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/sstable/block.go#L405)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is `cacheHandle` unused, since we have the `cache.Handle` inside `bufferHandle`?
</blockquote></details>

Good catch
___
*[`sstable/buffer_pool.go` line 49 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_J_48I2Mc_s5IBvTAf:-N_Kk8DB5T_X44AlvyGF:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/sstable/buffer_pool.go#L49)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

IIUC, the invariant is that for every `pool[i]` the `pool[i].v` value is non-nil. If so, can you add a comment.
</blockquote></details>

Done.
___
*[`sstable/buffer_pool.go` line 66 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_JYweJ8ksxty97dNL1:-N_KvhXg4eY-dRjKRSrT:b-i9s80l) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/sstable/buffer_pool.go#L66)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't see why `cache.Alloc` and `cache.Free` are methods on the `Cache` struct. They don't seem to reference anything in the cache. Could they be functions. Then we don't need `cache` as a member.
</blockquote></details>

Very good point. This also lets us remove `cache` as a member from `cacheValueOrBuf`
___
*[`sstable/buffer_pool.go` line 139 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_JXT-j1_bqYcSBWXwm:-N_KkDij6vXGUyseYIwk:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/sstable/buffer_pool.go#L139)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This code is not setting `b.p` to nil, which makes me worry that if `Release` is accidentally called again it may free a buffer that no longer belongs to `Buf`. I suppose we can't do better because `Release` is a value receiver. I am guessing making it a pointer receiver is not going to cause `Buf` to be heap allocated, in which case we could fix this.
</blockquote></details>

Done.
___
*[`sstable/buffer_pool.go` line 77 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_GTYxRCScuNXpqGUo9:-N_KvxRs6TU8tnOO9rZ0:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/9017c6da53551404125bb0bc2325799081c7fc30/sstable/buffer_pool.go#L77)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] should we do `pool[:0]` here so there's no possibility of misuse?
</blockquote></details>

Done
___
*[`sstable/reader.go` line 3429 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_JczqAC7DG0fJIy7QD:-N_Kl1xjCWoklFYrTqQ6:b-eo7br8) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/sstable/reader.go#L3429)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

so we need two bufs for each block, which means my previous comment may have undercounted by 2x.
</blockquote></details>

It should be a constant +1 buf since only one of the buffers survive to the end
___
*[`sstable/value_block.go` line 753 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_Jejq14lZAuUPITjpj:-N_Km-U6DY-1Otp3HsKc:befsf87) ([raw file](https://github.com/cockroachdb/pebble/blob/6c2252521f6933ad14043dd2057d318f4167d34c/sstable/value_block.go#L753)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this case should be rare enough but if we needed to use the buffer pool we could since the `blockProviderWhenClosed` is not allowed to outlive the iterator tree, which means it cannot outlive the buffer pool.
</blockquote></details>

Left a TODO here


<!-- Sent from Reviewable.io -->

2023-07-14 20:04 UTC, bananabrick reviewed
> they may be freed by a different thread inducing excessive TLB shootdowns

I never thought about this.

Why is it necessary that a free happens on a different thread to observe a TLB shootdown? If more than one thread is working with some memory, and any one of those threads calls free, we'd have the same problem right? Doesn't necessarily have to be a different thread than the one which allocated the memory.

> A compaction only requires a relatively small working set of buffers during its  scan across input sstables.

Do we really need manual memory allocation for these buffers?

> Reviewed 6 of 15 files at r1, 1 of 5 files at r3, 6 of 25 files at r4, 14 of 17 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2699#-:-N_Kgcy3EFW3mmGzmeyj:b9xyg64)* status: all files reviewed, 8 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`sstable/buffer_pool.go` line 99 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_KxROl8_Js9_MxwEPS:-N_KxROl8_Js9_MxwEPT:b-lqm74c) ([raw file](https://github.com/cockroachdb/pebble/blob/c5fc0298a28eeb04e0c5ff1c93a0ddb08afaccbe/sstable/buffer_pool.go#L99)):*
> ```Go
> 	for i := 0; i < len(p.pool); i++ {
> 		if p.pool[i].b == nil {
> 			if len(p.pool[i].v.Buf()) >= n {
> ```

nit: I think there's an invariant that `v.buf` is never resized so `cap(v.Buf) == len(v.Buf)`, when a `Value` is used by the BufferPool. Could we mention that in the `allocatedBuffer`?


<!-- Sent from Reviewable.io -->

2023-07-14 21:00 UTC, jbowens reviewed
> Why is it necessary that a free happens on a different thread to observe a TLB shootdown? If more than one thread is working with some memory, and any one of those threads calls free, we'd have the same problem right? Doesn't necessarily have to be a different thread than the one which allocated the memory.

I believe that's true, but:
1. for these blocks read during compactions, the expectation is that only the one thread running the compaction goroutine is reading this memory, so only the free from another thread is causing any TLB shootdown.
2. jemalloc has a thread-local 'tcache' of cached objects. Beyond the TLB shootdown, the memory being freed from another thread defeats the utility of the thread-local tcache, making it less likely that subsequent allocations can be served by the tcache.

> Do we really need manual memory allocation for these buffers?

Not strictly, but we already need to use a manual accounting of their lifecycles, so keeping them off the Go heap and out of GC's view is just a freebie.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2699#-:-N_L69VdA1yuK6tB18lP:b-s9tw8l)* status: all files reviewed, 8 unresolved discussions (waiting on @bananabrick and @sumeerbhola)

___
*[`sstable/buffer_pool.go` line 99 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_KxROl8_Js9_MxwEPS:-N_LBJsG8wQqrsMgPY0j:b-7penrc) ([raw file](https://github.com/cockroachdb/pebble/blob/c5fc0298a28eeb04e0c5ff1c93a0ddb08afaccbe/sstable/buffer_pool.go#L99)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: I think there's an invariant that `v.buf` is never resized so `cap(v.Buf) == len(v.Buf)`, when a `Value` is used by the BufferPool. Could we mention that in the `allocatedBuffer`?
</blockquote></details>

while true, it's not an invariant we use in any way


<!-- Sent from Reviewable.io -->

2023-07-14 22:03 UTC, bananabrick approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> the expectation is that only the one thread running the compaction goroutine is reading this memory, so only the free from another thread is causing any TLB shootdown.

If the compaction thread is still reading the memory, then another thread wouldn't call free on it, because the refcount of the Value isn't 0, right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2699#-:-N_LPjzj6-WH33nJWl0x:b-ebj4f6)* status: all files reviewed, 8 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`sstable/buffer_pool.go` line 99 at r6](https://reviewable.io/reviews/cockroachdb/pebble/2699#-N_KxROl8_Js9_MxwEPS:-N_LQKlo1Y13bMZV8bfi:bb450by) ([raw file](https://github.com/cockroachdb/pebble/blob/c5fc0298a28eeb04e0c5ff1c93a0ddb08afaccbe/sstable/buffer_pool.go#L99)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

while true, it's not an invariant we use in any way
</blockquote></details>

I figured we're relying on it here: `len(p.pool[i].v.Buf()) >= n`, we use `len` instead of `cap`, and it's correct to use `len` instead of `cap`, because `len == cap`.


<!-- Sent from Reviewable.io -->

2023-07-15 20:38 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 25 files at r4, 9 of 17 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2699#-:-N_QGbGnAxOTzsms0xTD:bg7igkv)* status: all files reviewed, 8 unresolved discussions (waiting on @jbowens)



<!-- Sent from Reviewable.io -->

2023-07-16 02:54 UTC, jbowens reviewed
>If the compaction thread is still reading the memory, then another thread wouldn't call free on it, because the refcount of the Value isn't 0, right?

That's right, but even if the compaction thread is done with the block and has moved on to a subsequent block, the block may still be in its TLB. I believe even in this scenario, the processor suffers the cost of a 'TLB shootdown.'

TFTRs! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2699#-:-N_Rb4XgEVBEQLZvl4Vi:b57583f)* status: all files reviewed, 8 unresolved discussions (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-07-16 02:55 UTC, merged