record: allow unbounded queued blocks in LogWriter
cockroachdb/pebble pull request #2762
Opened 2023-07-20 21:50 UTC by jbowens

Previously, a LogWriter would allocate up to 16 blocks of 32 KiB for buffering WAL writes. If all 16 blocks had been allocated and no free blocks were available, a batch writing to the WAL would queue until the flushing goroutine freed blocks. In testing of write-heavy workloads, especially with larger value sizes, we've seen queueing at the LogWriter. This queueing blocks the commit pipeline, preventing any batches from committing regardless of priority and whether they require waiting for fsync.

This commit modifies LogWriter to allow the queueing of an unbounded number of blocks. In practice, for the current WAL, the memtable size serves as an upper bound. With a 64 MiB memtable, at most 64 MiB / 32 KiB = 2,048 blocks may queue. This is not an unreasonable of additional memory overhead for a write-heavy workload.

Beyond improving throughput for write-heavy workloads, removing this hard bound improves tolerance of momentary fsync stalls.

Informs cockroachdb/cockroach#88699.

2023-07-20 21:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2762)
<!-- Reviewable:end -->

2023-07-21 16:25 UTC, jbowens reviewed
We might also consider adding additional memory accounting for these blocks. I don't think it's urgent, given the 64 MiB bound. But if in the future we allow pipelining WALs and permit buffering writes across the WAL rotation (which I think would help tail latencies considerably), I think we'll need some kind of accounting.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2762#-:-N_tF8Ii8DRbvWm3cyFJ:b-yuxkbb)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2023-07-23 16:55 UTC, sumeerbhola requested changes
Is it worth adding some commentary to https://github.com/cockroachdb/pebble/issues/2540?

Can you add a test that does allocate a large number of blocks, so we can be sure that (a) it is correct, (b) the slices are behaving reasonably in that we are not incurring slice allocations where we don't expect to.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2762#-:-Na2ag9G6kHO9IcWfMup:b-xheya)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @jbowens)

___
*[`batch.go` line 323 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2762#-Na2aqkI7QqwyNELAVdi:-Na2aqkI7QqwyNELAVdj:b-m6qxdv) ([raw file](https://github.com/cockroachdb/pebble/blob/fb76a24ac0984653275fbe9a3d7afb7f3476d844/batch.go#L323)):*
> ```Go
> 	// WALQueueWaitDuration is the wait time for allocating memory blocks in the
> 	// LogWriter (due to the LogWriter not writing fast enough).
> 	WALQueueWaitDuration time.Duration
> ```

will this come back once we add some memory bound?
I am wondering whether we want to keep this for now given that we have the plumbing for it in CockroachDB already.
___
*[`record/log_writer.go` line 569 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2762#-Na2drpHCiJlpMjQBzeQ:-Na2drpHCiJlpMjQBzeR:b-dd9phd) ([raw file](https://github.com/cockroachdb/pebble/blob/3a8381951b7e36a39633e6227d155ec4a64e61b7/record/log_writer.go#L569)):*
> ```Go
> 	w.free.Lock()
> 	if len(w.free.blocks) == 0 {
> 		w.free.blocks = append(w.free.blocks, &block{})
> ```

should we consider allocating the free blocks from a `sync.Pool`, given the well-defined lifecycle and the larger number of blocks a `logWriter` may allocate? That is, two levels of free pool management -- what we have here, and then the `sync.Pool` for `&block{}` and return them all to the `sync.Pool` in `LogWriter.Close`.


<!-- Sent from Reviewable.io -->

2023-07-24 15:52 UTC, jbowens reviewed
Added a comment to #2540 and a unit test + benchmark.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2762#-:-Na7a9X520omof365wQF:bt9ola6)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`batch.go` line 323 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2762#-Na2aqkI7QqwyNELAVdi:-Na7Cjh-56dyj55InTNq:bpadcw4) ([raw file](https://github.com/cockroachdb/pebble/blob/fb76a24ac0984653275fbe9a3d7afb7f3476d844/batch.go#L323)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

will this come back once we add some memory bound?
I am wondering whether we want to keep this for now given that we have the plumbing for it in CockroachDB already.
</blockquote></details>

Yeah, I started to wonder whether we ultimately should only have `MemtableStopWritesThreshold` which will also bound on the queued WAL blocks. But I'll keep this around so we can make a decision then.
___
*[`record/log_writer.go` line 569 at r2](https://reviewable.io/reviews/cockroachdb/pebble/2762#-Na2drpHCiJlpMjQBzeQ:-Na7ZWLc3cFE0FryNgHe:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/3a8381951b7e36a39633e6227d155ec4a64e61b7/record/log_writer.go#L569)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should we consider allocating the free blocks from a `sync.Pool`, given the well-defined lifecycle and the larger number of blocks a `logWriter` may allocate? That is, two levels of free pool management -- what we have here, and then the `sync.Pool` for `&block{}` and return them all to the `sync.Pool` in `LogWriter.Close`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-24 17:12 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2762#-:-Na7shBG5ohihQk5jEQj:bg7igkv)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @jbowens)



<!-- Sent from Reviewable.io -->

2023-07-24 17:37 UTC, jbowens commented
TFTR!

2023-07-24 17:37 UTC, merged