*: implement EventuallyFileOnlySnapshots
cockroachdb/pebble pull request #2775
Opened 2023-07-27 17:47 UTC by itsbilal

This change adds a new type of snapshots, EventuallyFileOnlySnapshots, that only stay in the snapshot list until all memtables with keys less than the snapshot have been flushed. After that, these file-only snapshots switch to holding a Version ref (which is akin to holding a readState ref minus the memtables). This allows for a good balance between the write-amp implications of staying in the snapshot list for too long, and the space-amp concerns with holding onto obsolete files.

Fixes #2740.

2023-07-27 17:47 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/2775)
<!-- Reviewable:end -->

2023-07-31 19:20 UTC, itsbilal commented
This is ready for a look; the latest push keeps all Snapshot guarantees for the key spans passed in.

2023-08-01 21:10 UTC, jbowens reviewed
> Reviewed 1 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2775)* status: 1 of 10 files reviewed, 9 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`compaction.go` line 2132 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamvKeOAzV8rLvrCiWj:-NamvKeOAzV8rLvrCiWk:b-805zrn) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/compaction.go#L2132)):*
> ```Go
> 			// The fact that this transition spins off its own goroutine is
> 			// unfortunate, but it's better than having the flush goroutine wait for
> 			// acquisition of s.efos' internal mutex while it holds the DB mutex.
> ```

do we do anything slow while holding the EFOS's mutex? I find the asynchrony harder to reason about. 
___
*[`ingest.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamOnJz0_6jbEBqaTvP:-NamOnJz0_6jbEBqaTvQ:b-7yi7ed) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/ingest.go#L71)):*
> ```Go
> 
> // OverlapsKeyRange checks if this span overlaps with the provided KeyRange.
> // Not that we aren't checking for full containment of either span in the other,
> ```

nit: s/Not/Note/
___
*[`ingest.go` line 1190 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamkwJn7RZfxKL44MPr:-NamkwJn7RZfxKL44MPs:b-xbsvo8) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/ingest.go#L1190)):*
> ```Go
> 			// EventuallyFileOnlySnapshot that has yet to be converted to a file-only
> 			// snapshot (as it's waiting on a memtable to flush). In that case, wait
> 			// on the mutable memtable just to be safe.
> ```

This could use an explanation for why it's necessary to wait on the mutable memtable. I'm also having trouble convincing myself this is sufficient.

My muddled understanding: If the `exciseSpan` overlaps with the mutable memtable, `mem` already points to the mutable memtable. So this code only has an effect when the `exciseSpan` does NOT overlap the mutable memtable. The problematic case is where the `exciseSpan` and the file-only snapshots protected ranges intersect but do not cover exactly the same keyspan(s). If the `exciseSpan` finds no overlap with the mutable memtable but the intersecting snapshot has not yet converted to a file-only snapshot, the snapshot must be waiting on some key to be flushed that the falls outside the `exciseSpan`'s bounds. If the excise proceeded, it would remove keys that the eventually-file-only snapshot requires before the eventually-file-only-snapshot has acquired its reference.

But does it need to be the _mutable_ memtable? We need the excise to wait for the most recent memtable that an intersecting eventually file-only snapshot is waiting for. This may not be the mutable memtable. It could be an immutable memtable currently being flushed. Suppose we wait for the most recent memtable that an intersecting eventually-only file snapshot is waiting for, and that's memtable _M_. Then another eventually-only file snapshot is opened that again overlaps the excise span. That EOFS _S_<sub>2</sub> intersects the mutable memtable _M+1_.  The excise has not yet applied, so the EOFS _S_<sub>2</sub> _also_ expects to observe the keys that the excise span plans on removing once _M+1_ is flushed.

If the user is continually opening EOFS for the same intersecting span and continually intersecting with the mutable memtable, won't it never be safe for the excise to proceed?
___
*[`snapshot.go` line 198 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamPbToCSUIjMQ0Wb9e:-NamPbToCSUIjMQ0Wb9f:b5zeowa) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L198)):*
> ```Go
> // An EventuallyFileOnlySnapshot also takes a list of KeyRanges at
> // instantiation time. These are saved inside the underlying Snapshot, and
> // any excises that happen during it
> ```

unfinished (stale?) comment
___
*[`snapshot.go` line 201 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamRPU1DRj3sgcPt6j5:-NamRPU1DRj3sgcPt6j6:bjrm2xa) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L201)):*
> ```Go
> type EventuallyFileOnlySnapshot struct {
> 	mu struct {
> 		sync.RWMutex
> ```

Is anything expensive done while holding the write mutex? Wondering if this should be an ordinary `sync.Mutex` to simplify the synchronization
___
*[`snapshot.go` line 214 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamQIPv0bRvx4hYVMPE:-NamQIPv0bRvx4hYVMPF:b-vig4fk) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L214)):*
> ```Go
> 		// The wrapped regular snapshot, if not a file-only snapshot yet.
> 		snap      *Snapshot
> 		readState *readState
> ```

nit: can you explicitly mention that the `EventuallyFileOnlySnapshot` has ref'd the `readState` if non-nil?
___
*[`snapshot.go` line 223 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamuoOLDYoSJeZSjU4t:-NamuoOLDYoSJeZSjU4u:b-utxsnb) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L223)):*
> ```Go
> 	// excised, if true, signals that the above ranges were excised during the
> 	// lifetime of this snapshot.
> 	excised atomic.Bool
> ```

How is this used other than the assertion?
___
*[`snapshot.go` line 238 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Namut38DHupp1g9GFsS:-Namut38DHupp1g9GFsT:b-1q3b6h) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L238)):*
> ```Go
> ) {
> 	if es.excised.Load() {
> 		panic("pebble: snapshot excised before conversion to file-only snapshot")
> ```

nit: `panic(errors.AssertionFailedf(...))`
___
*[`snapshot.go` line 351 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamSsyR8hyYeQQbVOL0:-NamSsyR8hyYeQQbVOL1:bl6ycq8) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L351)):*
> ```Go
> 	close(es.closed)
> 	es.mu.RLock()
> 	defer es.mu.RUnlock()
> ```

Should this be acquiring a write lock on the RWMutex?


<!-- Sent from Reviewable.io -->

2023-08-01 21:19 UTC, sumeerbhola requested changes
still reading, flushing some initial comments

> Reviewed 2 of 10 files at r1, 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2775#-:-Namy2B128M4b4c3ivri:b2quafx)* status: 4 of 10 files reviewed, 17 unresolved discussions (waiting on @itsbilal)

___
*[`db.go` line 1018 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamsM3M8WAWUA7SQMHJ:-NamsM3M8WAWUA7SQMHK:bhpu7rn) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/db.go#L1018)):*
> ```Go
> 	// files in the associated version from being deleted if there is a current
> 	// compaction. The readState is unref'd by Iterator.Close().
> 	readState := sOpts.readState
> ```

Shouldn't the code be reffing `sOpts.readState`, to correspond to the unref that will happen when the iterator is closed?

Also be reffing `sOpts.vers`?
___
*[`db.go` line 1480 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Namsk6pEVQbU95yioZk:-Namsk6pEVQbU95yioZl:b-1gr1tt) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/db.go#L1480)):*
> ```Go
> // NewEventuallyFileOnlySnapshot returns a point-in-time view of the current DB
> // state, similar to NewSnapshot. See the comment at EventuallyFileOnlySnapshot
> // for its semantics.
> ```

if we require keyRanges to be sorted, we should say this here. And verify under `invariants.Enabled`.
___
*[`db.go` line 1488 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Namt3RHBLSMP7PhFjXr:-Namt3RHBLSMP7PhFjXs:bmlgur5) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/db.go#L1488)):*
> ```Go
> 	internalKeyRanges := make([]internalKeyRange, len(keyRanges))
> 	for i := range keyRanges {
> 		internalKeyRanges[i] = internalKeyRange{
> ```

Could you add a comment where `internalKeyRange` is declared that `largest` is inclusive.
___
*[`db.go` line 1500 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamuBEZ5rkCHbeq7cuz:-NamuBEZ5rkCHbeq7cv-:b-arg2c) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/db.go#L1500)):*
> ```Go
> 	for i := range d.mu.mem.queue {
> 		mem := d.mu.mem.queue[i]
> 		if ingestMemtableOverlaps(d.cmp, mem, internalKeyRanges) {
> ```

I wonder whether we could do this overlap checking without holding `d.mu`, since that will block all writes. I realize we do the same with ingests, and snapshot creation may not be a high rate activity, but just raising it as a potential improvement.
We have already picked `seqNum` so no future writes are relevant (except for excise). We could:
- Grab the list of memtables to check and readerRef them and release the mutex.
- Make a list of the ones that overlap (expensive step).
-  Acquire the mutex again and do pointer comparison of the overlapping ones and the current (unflushed) ones (set intersection). If the intersecting set of memtables is empty, then we can transition to file only now.

I guess the problem is that an excise could come in between the first mutex release and the subsequent acquisition and we've grabbed a seqnum already that is pre-excise. Perhaps we could push onto `DB.mu.snapshots` when holding the first mutex and use that to check that an excise did not happen. 
___
*[`db.go` line 1505 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Namx4HxCVtClzOn-pK7:-Namx4HxCVtClzOn-pK8:b-a3pj37) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/db.go#L1505)):*
> ```Go
> 		}
> 	}
> 	es := &EventuallyFileOnlySnapshot{
> ```

nit: can you move all this code to a `makeEventuallyFileOnlySnapshot` func in snapshot.go. It's easier to grok and maintain when its near to the struct declaration.
___
*[`iterator.go` line 2669 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamrFQ2EuCXHDhYcwT1:-NamrFQ2EuCXHDhYcwT2:b-r6tl9c) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/iterator.go#L2669)):*
> ```Go
> 	}
> 	if vers != nil {
> 		vers.Ref()
> ```

where do we unref the version in `Close`?

If this is a bug, I am surprised our "leaked iterators" checking on closing the DB did not catch it.
___
*[`snapshot.go` line 198 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Namomav8lzIb4XCY7NY:-Namomav8lzIb4XCY7NZ:b-m27vnh) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L198)):*
> ```Go
> // An EventuallyFileOnlySnapshot also takes a list of KeyRanges at
> // instantiation time. These are saved inside the underlying Snapshot, and
> // any excises that happen during it
> ```

nit: incomplete sentence.
___
*[`snapshot.go` line 219 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NampDUtEqy7e7Lmvzx6:-NampDUtEqy7e7Lmvzx7:bve185f) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L219)):*
> ```Go
> 	}
> 
> 	// Key ranges to watch for an excise on.
> ```

Are the ranges in sorted order?


<!-- Sent from Reviewable.io -->

2023-08-01 21:49 UTC, sumeerbhola requested changes
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2775)* status: 5 of 10 files reviewed, 20 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[`ingest.go` line 1190 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamkwJn7RZfxKL44MPr:-Nan0KZs1IuhFp57DVPl:bt9i2ru) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/ingest.go#L1190)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This could use an explanation for why it's necessary to wait on the mutable memtable. I'm also having trouble convincing myself this is sufficient.

My muddled understanding: If the `exciseSpan` overlaps with the mutable memtable, `mem` already points to the mutable memtable. So this code only has an effect when the `exciseSpan` does NOT overlap the mutable memtable. The problematic case is where the `exciseSpan` and the file-only snapshots protected ranges intersect but do not cover exactly the same keyspan(s). If the `exciseSpan` finds no overlap with the mutable memtable but the intersecting snapshot has not yet converted to a file-only snapshot, the snapshot must be waiting on some key to be flushed that the falls outside the `exciseSpan`'s bounds. If the excise proceeded, it would remove keys that the eventually-file-only snapshot requires before the eventually-file-only-snapshot has acquired its reference.

But does it need to be the _mutable_ memtable? We need the excise to wait for the most recent memtable that an intersecting eventually file-only snapshot is waiting for. This may not be the mutable memtable. It could be an immutable memtable currently being flushed. Suppose we wait for the most recent memtable that an intersecting eventually-only file snapshot is waiting for, and that's memtable _M_. Then another eventually-only file snapshot is opened that again overlaps the excise span. That EOFS _S_<sub>2</sub> intersects the mutable memtable _M+1_.  The excise has not yet applied, so the EOFS _S_<sub>2</sub> _also_ expects to observe the keys that the excise span plans on removing once _M+1_ is flushed.

If the user is continually opening EOFS for the same intersecting span and continually intersecting with the mutable memtable, won't it never be safe for the excise to proceed?
</blockquote></details>

Also, isn't this the case where the ingest should not wait and the EFOS will eventually return an error due to the code later in this source file?
___
*[`snapshot.go` line 238 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Nan1jJt-Sib6nnSL-wP:-Nan1jJt-Sib6nnSL-wQ:b71qt0i) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L238)):*
> ```Go
> ) {
> 	if es.excised.Load() {
> 		panic("pebble: snapshot excised before conversion to file-only snapshot")
> ```

I wasn't expecting this to panic, since I thought we were admitting the possibility of this error.
___
*[`snapshot.go` line 261 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Nan2JjP0aseQR4s9SMx:-Nan2JjQ4SUd8hkm3-iQ:b-ei6cgo) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L261)):*
> ```Go
> 	earliestUnflushedSeqNum uint64, vers *version,
> ) error {
> 	if base.Visible(earliestUnflushedSeqNum, es.seqNum, InternalKeySeqNumMax) {
> ```

why should it fail here given we verified `!base.Visible(earliestUnflushedSeqNum, s.efos.seqNum, InternalKeySeqNumMax)` in compaction.go?
___
*[`snapshot.go` line 287 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Nan35PoArS6eBQ1s9m4:-Nan35Pp3hZae9fcFLwE:b-7th1a6) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L287)):*
> ```Go
> 		es.mu.transitioned.Broadcast()
> 	} else {
> 		vers.Unref()
> ```

Why would this else case happen? `NewEventuallyFileOnlySnapshot` doesn't use this method when creating a EFOS that is initially file only.
Is this because this is async so can be triggered by multiple flushes?
If we can't make the whole thing synchronous we should set some bit in `maybeTransitionToFileOnlySnapshotAsync` so that only the first caller needs to start a goroutine and then this method can be stricter about the state it expects to see.


<!-- Sent from Reviewable.io -->

2023-08-02 20:11 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2775#-:-NaqnHGa1Vw0O4Y-XTpq:b-814g8k)* status: 5 of 10 files reviewed, 15 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[`compaction.go` line 2132 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamvKeOAzV8rLvrCiWj:-NaqnIz25BfrnWwuvxqr:b3zgfh0) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/compaction.go#L2132)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

do we do anything slow while holding the EFOS's mutex? I find the asynchrony harder to reason about. 
</blockquote></details>

Nothing heavy. I just had to untangle a bunch of mutexes and add a `snap.closeLocked` to make things work well synchronously without deadlocks, but the latest change does it.
___
*[`db.go` line 1018 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamsM3M8WAWUA7SQMHJ:-NaqoNI-Dzgt3frHyq6i:b74bjjg) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/db.go#L1018)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Shouldn't the code be reffing `sOpts.readState`, to correspond to the unref that will happen when the iterator is closed?

Also be reffing `sOpts.vers`?
</blockquote></details>

You're right that we're missing one round of ref/unref of `vers`, but we don't need to ref readState in the case below
___
*[`db.go` line 1480 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Namsk6pEVQbU95yioZk:-NaqpGNPEu4Qtivr0YnG:bl0mxdv) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/db.go#L1480)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

if we require keyRanges to be sorted, we should say this here. And verify under `invariants.Enabled`.
</blockquote></details>

We don't, as I expect the number of keyRanges to be a constant size and small for each EFOS (4?) so we just do a nested loop iteration each time. But if we want to require it to be sorted, it would allow us to do binary-searches to check for overlaps.
___
*[`db.go` line 1488 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Namt3RHBLSMP7PhFjXr:-NaqpbPr6aSpu0C_WbAB:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/db.go#L1488)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Could you add a comment where `internalKeyRange` is declared that `largest` is inclusive.
</blockquote></details>

Done.
___
*[`db.go` line 1505 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Namx4HxCVtClzOn-pK7:-NaquGi00Tv5blULMGId:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/db.go#L1505)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: can you move all this code to a `makeEventuallyFileOnlySnapshot` func in snapshot.go. It's easier to grok and maintain when its near to the struct declaration.
</blockquote></details>

Done.
___
*[`ingest.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamOnJz0_6jbEBqaTvP:-NaquJKl9R1PD5Ghk-2K:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/ingest.go#L71)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: s/Not/Note/
</blockquote></details>

Done.
___
*[`ingest.go` line 1190 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamkwJn7RZfxKL44MPr:-Narf6X52RaDvXdo0eaj:b-g6ktet) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/ingest.go#L1190)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Also, isn't this the case where the ingest should not wait and the EFOS will eventually return an error due to the code later in this source file?
</blockquote></details>

(conversation was continued on slack but bringing it back here)

Yes you're right @jbowens , the wait on the mutable memtable is not sufficient. I've removed this case entirely and brought back the error case in `WaitForFileOnlySnapshot` for when the excise races past the EFOS' transition. Also updated one of the tests to exercise the error case better.
___
*[`iterator.go` line 2669 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamrFQ2EuCXHDhYcwT1:-NaquMV64q9DOqwuqr1u:bh11ton) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/iterator.go#L2669)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

where do we unref the version in `Close`?

If this is a bug, I am surprised our "leaked iterators" checking on closing the DB did not catch it.
</blockquote></details>

Done. We were missing an unref in Close. And since this is just the clone case, we weren't leaking an iterator.
___
*[`snapshot.go` line 198 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamPbToCSUIjMQ0Wb9e:-NaqvNy75J3O125Lw6zm:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L198)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

unfinished (stale?) comment
</blockquote></details>

Done.
___
*[`snapshot.go` line 198 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Namomav8lzIb4XCY7NY:-NaqvOQC2mZEfvNcolUw:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L198)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: incomplete sentence.
</blockquote></details>

Done.
___
*[`snapshot.go` line 201 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamRPU1DRj3sgcPt6j5:-NaqvP_m9K-amEW0pAuE:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L201)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Is anything expensive done while holding the write mutex? Wondering if this should be an ordinary `sync.Mutex` to simplify the synchronization
</blockquote></details>

Done.
___
*[`snapshot.go` line 214 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamQIPv0bRvx4hYVMPE:-NaqvVCaBmka8XVuuyoE:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L214)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: can you explicitly mention that the `EventuallyFileOnlySnapshot` has ref'd the `readState` if non-nil?
</blockquote></details>

Done.
___
*[`snapshot.go` line 219 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NampDUtEqy7e7Lmvzx6:-NaqvW-WBeUN26gcVc4p:b-faxefj) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L219)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are the ranges in sorted order?
</blockquote></details>

Nope (see comment above).
___
*[`snapshot.go` line 223 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamuoOLDYoSJeZSjU4t:-NaqvYNU7fbfF-sCpFEn:b-rg6yy4) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L223)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

How is this used other than the assertion?
</blockquote></details>

Done (irrelevant given new changes)
___
*[`snapshot.go` line 238 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Nan1jJt-Sib6nnSL-wP:-Naqv_ux94mewhVyWfB8:b-21rb84) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L238)):*
<det [...]

2023-08-09 15:05 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2775#-:-NbPn20rBzVgKPHomDyP:b-814g8k)* status: 5 of 13 files reviewed, 19 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`db.go` line 1480 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Namsk6pEVQbU95yioZk:-NbPn4ROA-n7lO4cxqEA:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/db.go#L1480)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Let's require them to be sorted (so we don't have to change the API) and it's fine to leave a TODO to improve the implementation later.
</blockquote></details>

Done.
___
*[`db.go` line 1500 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamuBEZ5rkCHbeq7cuz:-NbPn5o20ilDFOS8AUfo:bg4l448) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/db.go#L1500)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Thoughts about this? Should this be captured in a todo or an issue?
</blockquote></details>

I'll shortly file an issue enumerating this optimization, if that sounds good!
___
*[`db.go` line 986 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbL3-dN9rJNpOHeJ0ua:-NbPn2vG-J_b_ECekiEJ:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/9e17bf2739f8c941b90758de8d26d8255a27e93c/db.go#L986)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think it would be simpler to understand by enumerating the 3 cases. Something like:

```
// - Classic snapshot: only snapshot is set. Since this is a classic snapshot, the callee will use the latest readState.
// - EFOS that has not yet become file-only: only snapshot and readState are set. It is not safe for the callee to use the latest readState, since the transition to file-only can happen concurrently and cause the latest readState to stop preserving seqnums needed by the snapshot.
// - EFOS that has become file-only: only seqNum, vers are set.
//
// A consequence of the above cases is that at most one of vers and readState are non-nil, and both are nil for a classic snapshot.
```
</blockquote></details>

Done.
___
*[`db.go` line 1031 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbL1wOu8TyfAVpLu_My:-NbPn3_D0sYru83NX6gc:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/9e17bf2739f8c941b90758de8d26d8255a27e93c/db.go#L1031)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: this nicely fits in as an `else` in the previous if-elseif block since when the first 2 conditions are not satisfied, what remains is `sOpts.vers != nil`.
</blockquote></details>

Done.
___
*[`ingest.go` line 1803 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbL6HDO2cx0vUhTxARZ:-NbPnFU6BcBq6rjwElhX:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/9e17bf2739f8c941b90758de8d26d8255a27e93c/ingest.go#L1803)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: can break out of the loop after setting true
</blockquote></details>

Done.
___
*[`iterator.go` line 2669 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamrFQ2EuCXHDhYcwT1:-NbPnGO26le5kgXxKmJS:b-nyau35) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/iterator.go#L2669)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> And since this is just the clone case, we weren't leaking an iterator.

So do we not test clone in a way that would have triggered the bug? If so, can you create an issue?
</blockquote></details>

Added some tests for the clone case that'd have caught this. We do test Clone, we just weren't testing it with EFOS.
___
*[`snapshot.go` line 253 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbL9MCU0LiOUvGjXCqj:-NbPnR_K6OY4YNn0rFTH:b-mmy3t9) ([raw file](https://github.com/cockroachdb/pebble/blob/9e17bf2739f8c941b90758de8d26d8255a27e93c/snapshot.go#L253)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm unclear on why this is a channel. Can this be a bool inside mu? 
</blockquote></details>

We check it inside the loop in `WaitForFileOnlySnapshot` without holding the EFOS mutex, and I wanted to have the ability to break out of that loop without grabbing that mutex. That's really the only reason why it's not inside that mutex. I could make it an atomic though, if we want.
___
*[`snapshot.go` line 361 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbLA0tg6gXPKGG8vcKy:-NbPngIY2083uFeFc3o3:b-dhwhol) ([raw file](https://github.com/cockroachdb/pebble/blob/9e17bf2739f8c941b90758de8d26d8255a27e93c/snapshot.go#L361)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How easy would it be to make this a DB wide schedule (configured in opts) that would flush at a certain frequency if there was a waiting EFOS? Or can we convince ourselves that a EFOS created every 1ms will not cause excessive flushes?
</blockquote></details>

That's not that different from calling this method with a large value for `dur`, right? Say we do create an EFOS every 1ms, but we call `WaitForFileOnlySnapshot` with a 10s duration after creating each of those. The EFOS will all end up calling `maybeScheduleDelayedFlush` on the current memtable, and the first one to hit the 10s will end up going through with the memtable rotation/flush. The others will all realize the memtable they're waiting on has flushed and will do nothing, as `maybeScheduleDelayedFlush` is set up to handle that case.

We could reduce the goroutine proliferation by having it centrally scheduled in db, but functionally it won't be any different in causing or reducing excessive flushes. What do you think? It shouldn't be much harder to do it there so I'm down to make the change, but just wanted to confirm.
___
*[`snapshot.go` line 368 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbLARkSBlUMWux8T9XR:-NbPopeH9uud4WvQneXp:b-c382v8) ([raw file](https://github.com/cockroachdb/pebble/blob/9e17bf2739f8c941b90758de8d26d8255a27e93c/snapshot.go#L368)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can we simplify by having a channel to signal that the transition to file only snapshot is done. That way we don't have to attempt the transition here.
</blockquote></details>

Done. I moved to a cond lock if that makes sense; reduces the chances that we wait on the channel _after_ a concurrent flush goroutine has done the transition.


<!-- Sent from Reviewable.io -->

2023-08-09 18:00 UTC, jbowens reviewed
> Reviewed 1 of 10 files at r1, 1 of 7 files at r4, 1 of 5 files at r8, 1 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2775)* status: 6 of 13 files reviewed, 22 unresolved discussions (waiting on @itsbilal and @sumeerbhola)

___
*[`compaction.go` line 2135 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbQ8JF69uoc5PXb300Q:-NbQ8JF69uoc5PXb300R:b-v6snxh) ([raw file](https://github.com/cockroachdb/pebble/blob/2484eb019046744a3ae6768320a03271ac193286/compaction.go#L2135)):*
> ```Go
> 				continue
> 			}
> 			if s.efos.excised.Load() {
> ```

nit: can you add a comment explaining that the EFOS cannot transition to file-only in this case.
___
*[`db.go` line 1500 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamuBEZ5rkCHbeq7cuz:-NbQApFyAtotVNtEWfbn:b-iapj50) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/db.go#L1500)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I'll shortly file an issue enumerating this optimization, if that sounds good!
</blockquote></details>

When you file the issue, you can link it to #2112, the issue for the analogous improvement to Ingest.
___
*[`db.go` line 987 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbQ-Yrn8e9rJ7wKjxQ3:-NbQ-Yro-aNWKLVMiM5U:b-lmcprl) ([raw file](https://github.com/cockroachdb/pebble/blob/2484eb019046744a3ae6768320a03271ac193286/db.go#L987)):*
> ```Go
> //   - No snapshot: All fields are zero values.
> //   - Classic snapshot: Only `snapshot` is set. The latest readState will be used
> //     and the seqNum from inside the *Snapshot will be used.
> ```

nit: Would we be able to simplify further by removing `snapshot` and just copying `snapshot.seqNum` onto `seqNum`? Then we always use the provided `seqNum` if non-zero. If `readState` is provided, we fall into the EFOS pre-file-only state and use the readState. If `vers` is provided, we fall into the file-only state and use that version. If neither `readState` nor `vers` is provided, we use the latest read state and it's a classic snapshot.
___
*[`ingest.go` line 1791 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbQBXnyBlpJgr1t7mD-:-NbQBXnyBlpJgr1t7mD0:b-hzsd4l) ([raw file](https://github.com/cockroachdb/pebble/blob/2484eb019046744a3ae6768320a03271ac193286/ingest.go#L1791)):*
> ```Go
> 			// write a file overlapping with the excise span.
> 			if exciseSpan.OverlapsInternalKeyRange(d.cmp, c.smallest, c.largest) {
> 				c.cancel.Store(true)
> ```

The glorious code coverage integration that @RaduBerinde added shows that the cancel case is untested. I realize that predates this PR, but can you file an issue for a unit test that covers this case?
___
*[`iterator.go` line 2671 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbQG6c_DwhE2xCn02pk:-NbQG6c_DwhE2xCn02pl:b-casxc4) ([raw file](https://github.com/cockroachdb/pebble/blob/2484eb019046744a3ae6768320a03271ac193286/iterator.go#L2671)):*
> ```Go
> 	if readState != nil {
> 		readState.ref()
> 	}
> ```

When cloning an iterator constructed off a snapshot, should we try to create it off the snapshot instead of reusing the same readState? If the current read state has progressed, we might be able to release zombie [mem]tbls. I'm not sure if we ever Clone a snapshot iterator in Cockroach. Maybe leave a TODO?
___
*[`snapshot.go` line 287 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-Nan35PoArS6eBQ1s9m4:-NbQQ2q86Xu-PMmiFgTw:b-j8uo1i) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/snapshot.go#L287)):*
> we could leave that responsibility solely up to the flushing goroutine, in which case this else case would go away.

This seems worthwhile to reduce complexity.
___
*[`snapshot.go` line 217 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbQHg-9EDTbbMH8U-Wq:-NbQHg-9EDTbbMH8U-Wr:bisdzmw) ([raw file](https://github.com/cockroachdb/pebble/blob/2484eb019046744a3ae6768320a03271ac193286/snapshot.go#L217)):*
nit: I found this comment a little confusing and maybe a little too focused on the internal implementation. Wdyt of something like:

> EventuallyFileOnlySnapshot (aka EFOS) provides a read-only point-in-time view of the database state, similar to Snapshot. A EventuallyFileOnlySnapshot induces less write amplification, at the cost of increased space amplification. While a Snapshot may increase write amplification across all flushes and compactions, a EventuallyFileOnlySnapshot only prevents the elision of keys for flushes of memtables that a) are open when the snapshot is created and b) overlap the specified key ranges. Once all such memtables have been flushed, the "EventuallyFileOnlySnapshot" transitions to a file-only snapshot state in which it pins zombies sstables like an open Iterator would, without pinning any memtables. Callers that can tolerate the increased space amplification of pinning zombie sstables until the snapshot is closed may prefer EventuallyFileOnlySnapshots for their reduced write amplification.
>
> EventuallyFileOnlySnapshots interact with the [IngestAndExcise] operation in subtle ways. Unlike Snapshots, EventuallyFileOnlySnapshots guarantee that their read-only point-in-time view is unaltered by the excision. However, an excise  ...

(I didn't finish because I still don't fully grok the interaction with excise here (see my other comment).
___
*[`snapshot.go` line 346 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbQO5Gv0OnvVJMcsT-L:-NbQO5Gv0OnvVJMcsT-M:b-6zhdjh) ([raw file](https://github.com/cockroachdb/pebble/blob/2484eb019046744a3ae6768320a03271ac193286/snapshot.go#L346)):*
> ```Go
> //
> // Idempotent; can be called multiple times with no side effects.
> func (es *EventuallyFileOnlySnapshot) WaitForFileOnlySnapshot(dur time.Duration) error {
> ```

Checking understanding: 
- If you call `EventuallyFileOnlySnapshot`, you get a usable EFOS that you can call `NewIter` on, which will just use the pinned read state.
- If you call `WaitForFileOnlySnapshot` and receive a nil error, you're guaranteed that you can continue to use the EFOS as a file-only snapshot indefinitely without pinning memtables.
- If you created a EFOS, never call `WaitForFileOnlySnapshot` and keep calling `NewIter` on it, the behavior is identical to `Clone`-ing an iterator and the snapshot provides no utility. If a conflicting excise occurs, the `readState` stays ref'd.

I think this could use some more explicit documentation on the intended usage.
___
*[`snapshot.go` line 461 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbQRpZG6M9f8hMnvNO3:-NbQRpZG6M9f8hMnvNO4:b-5r971t) ([raw file](https://github.com/cockroachdb/pebble/blob/2484eb019046744a3ae6768320a03271ac193286/snapshot.go#L461)):*
> ```Go
> ) error {
> 	if es.db == nil {
> 		panic(ErrClosed)
> ```

is this case possible?


<!-- Sent from Reviewable.io -->

2023-08-10 19:20 UTC, sumeerbhola requested changes
looks good -- only one small thing

> Reviewed 1 of 5 files at r8, 1 of 4 files at r9, 4 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2775#-:-NbVt0KkE5L17Czv-t4G:b-4tvu8b)* status: 8 of 13 files reviewed, 19 unresolved discussions (waiting on @itsbilal, @jbowens, and @RaduBerinde)

___
*[`iterator.go` line 2671 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbQG6c_DwhE2xCn02pk:-NbVqT0K1VP6gBWKFfwo:b-4n9mmt) ([raw file](https://github.com/cockroachdb/pebble/blob/2484eb019046744a3ae6768320a03271ac193286/iterator.go#L2671)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done (left TODO)
</blockquote></details>

We do not clone when we have a `pebbleSnapshot` in CockroachDB, so there is no urgency to do this.
___
*[`snapshot.go` line 361 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbLA0tg6gXPKGG8vcKy:-NbVs1az6XOMP_IO8j9T:b-bnlfex) ([raw file](https://github.com/cockroachdb/pebble/blob/9e17bf2739f8c941b90758de8d26d8255a27e93c/snapshot.go#L361)):*
> but functionally it won't be any different in causing or reducing excessive flushes

Agreed

I remembered now the other reason this was bothering me, and it relates to the use case of CRDB's outgoing snapshot. My assumption was that no one will call `WaitForFileOnlySnapshot` in that case, but we do want a transition to happen in a timely manner. We could change the CRDB code to spin up an extra goroutine, which is possibly fine given the limited concurrency. I don't have a strong opinion either way.
___
*[`snapshot.go` line 346 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbQO5Gv0OnvVJMcsT-L:-NbVoOdr3aWU2QlT0MgL:baov4xg) ([raw file](https://github.com/cockroachdb/pebble/blob/2484eb019046744a3ae6768320a03271ac193286/snapshot.go#L346)):*
> unless a conflicting excise happens in which case we keep using the readState.

I missed this. I think we should return an error. It's better than an OOM, which, however rare, is annoying.


<!-- Sent from Reviewable.io -->

2023-08-11 16:39 UTC, itsbilal reviewed
TFTR!

Added a second commit with the change to return an error from NewIter, as it really increased the surface area of this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2775#-:-Nb_StlO1DNrmayylAd6:bfy0uhz)* status: 4 of 30 files reviewed, 19 unresolved discussions (waiting on @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`snapshot.go` line 361 at r7](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbLA0tg6gXPKGG8vcKy:-Nb_OV396RhWWpbpCq9w:b-wnfiqc) ([raw file](https://github.com/cockroachdb/pebble/blob/9e17bf2739f8c941b90758de8d26d8255a27e93c/snapshot.go#L361)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> but functionally it won't be any different in causing or reducing excessive flushes

Agreed

I remembered now the other reason this was bothering me, and it relates to the use case of CRDB's outgoing snapshot. My assumption was that no one will call `WaitForFileOnlySnapshot` in that case, but we do want a transition to happen in a timely manner. We could change the CRDB code to spin up an extra goroutine, which is possibly fine given the limited concurrency. I don't have a strong opinion either way.
</blockquote></details>

We can probably leave that as a follow-up optimization, this change is large enough as-is. I'll file an issue to have one goroutine that ticks at a configurable interval and schedules a flush if there are waiting EFOS.
___
*[`snapshot.go` line 346 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbQO5Gv0OnvVJMcsT-L:-Nb_KDI7AFVI-ve_Wf10:bqiyto1) ([raw file](https://github.com/cockroachdb/pebble/blob/2484eb019046744a3ae6768320a03271ac193286/snapshot.go#L346)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> unless a conflicting excise happens in which case we keep using the readState.

I missed this. I think we should return an error. It's better than an OOM, which, however rare, is annoying.
</blockquote></details>

The one annoyance there is going to be threading the error value from `NewIter` through all the relevant Cockroach/Pebble interfaces. I've made that change, but the tests rely a little too heavily on the fact that non-EFOS implementations don't return an error in NewIter. If that changes the tests will fail or panic anyway so that's fine.


<!-- Sent from Reviewable.io -->

2023-08-11 21:30 UTC, itsbilal reviewed
Added a third commit with more testing for concurrent excises and compaction / EFOS cancellation. Could have done that as a standalone PR, but since it came up here + it also tests for EFOS stuff, it makes sense to do it here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2775#-:-NbaVIiX53tWv7FeEjHN:b-eec9ys)* status: 1 of 31 files reviewed, 19 unresolved discussions (waiting on @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`ingest.go` line 1791 at r9](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbQBXnyBlpJgr1t7mD-:-NbaVTNX93l48qxOzlvG:b-m539f) ([raw file](https://github.com/cockroachdb/pebble/blob/2484eb019046744a3ae6768320a03271ac193286/ingest.go#L1791)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Writing a unit test that blocks a compaction is relatively annoying but yes I can file an issue to do one. We'll get coverage with the metamorphic test of this case no matter what, in my experience it's very common for an excise to cancel a compaction in Cockroach too.
</blockquote></details>

This is done now.


<!-- Sent from Reviewable.io -->

2023-08-14 19:25 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 5 files at r8, 1 of 1 files at r11, 10 of 26 files at r13, 22 of 23 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2775#-:-NbpVcxD9UqXwnd2sk0Q:bg7igkv)* status: all files reviewed, 20 unresolved discussions (waiting on @itsbilal, @jbowens, and @RaduBerinde)

___
*[`testdata/ingest_shared` line 739 at r13](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbpUFcR7G-Pq7EJcg4m:-NbpUFcR7G-Pq7EJcg4n:b956ca5) ([raw file](https://github.com/cockroachdb/pebble/blob/3e0491711c7fd4f82e42dc683c4ce599036d0bc7/testdata/ingest_shared#L739)):*
> ```
> .
> 
> # Eventually File-only snapshots error out when a concurrent excise happens.
> ```

where is the error below?


<!-- Sent from Reviewable.io -->

2023-08-14 21:30 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/2775#-:-Nbpn59j7G_a4HAASpMc:b-814g8k)* status: 6 of 31 files reviewed, 20 unresolved discussions (waiting on @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`db.go` line 1500 at r3](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NamuBEZ5rkCHbeq7cuz:-NbpxJYi7irTEuLntl7C:bqo5lzr) ([raw file](https://github.com/cockroachdb/pebble/blob/8223fdbc05599808f18df36acd333c8cc84a38b8/db.go#L1500)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

On it!
</blockquote></details>

Filed https://github.com/cockroachdb/pebble/issues/2824. 
___
*[`testdata/ingest_shared` line 739 at r13](https://reviewable.io/reviews/cockroachdb/pebble/2775#-NbpUFcR7G-Pq7EJcg4m:-Nbpn6k5D7xNQoBdxDEj:baedn5o) ([raw file](https://github.com/cockroachdb/pebble/blob/3e0491711c7fd4f82e42dc683c4ce599036d0bc7/testdata/ingest_shared#L739)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

where is the error below?
</blockquote></details>

AH oops. This comment is better described as "Tests for EFOS, which does ....., follow below". Reworded.


<!-- Sent from Reviewable.io -->

2023-08-14 21:31 UTC, merged