db: fix mergingIter, levelIter error propagation
cockroachdb/pebble pull request #3181
Opened 2023-12-21 22:15 UTC by jbowens

**internal/itertest: add iterator probes**

This commit introduces facilities for attaching 'probes' to internal iterators.
A probe is invoked on every operation against the iterator and provided with
information about the operation in-progress and its results. A probe may modify
the return result freely.

Building off the work in vfs/errorfs and internal/dsl, this commit introduces a
DSL for expressing probes and the circumstances with which they should
activate.

In the immediate term, probes will be used for error injection in intenral
iterator unit tests.

**db: fix mergingIter, levelIter error propagation**

This commit adds facilities for unit testing error propagation in the merging
iterator and level iterator through defining "probes" for individual file point
iterators or range deletion iterators. Additional unit testing reveals a host
of unpropagated errors, which in several cases resulted in incorrect results
including skipped keys and surfacing deleted keys.

The unit tests and bug fixes included within this commit are not comprehensive.
Randomized tests introduced in future commits will ensure that we have
comprehensive coverage. Future bug fixes will be able to use the testing
facilities introduced in this commit to add focused regression tests.

Some of the facilities are copied into the pebble package from internal/keyspan
temporarily. In future refactors, these will be consolidated within a common
package. Those refactors are deferred to ensure that these bug fixes are easily
able to be backported to previous releases.

Informs #1115.

2023-12-21 22:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/3181)
<!-- Reviewable:end -->

2024-01-04 22:38 UTC, sumeerbhola requested changes
nice!
I am still reading merging_iter.go, but flushing some early comments.

> Reviewed 4 of 4 files at r1, 2 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3181#-:-NnLc5cF4LuhsatCs7gv:b-uw1avq)* status: 6 of 11 files reviewed, 7 unresolved discussions (waiting on @aadityasondhi and @jbowens)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnLTd8i3YHlCcfN3XDQ):*
nit: internal
___
*[`merging_iter.go` line 333 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnLb6465UN2b3-6nBtx:-NnLb6465UN2b3-6nBty:bwffhk3) ([raw file](https://github.com/cockroachdb/pebble/blob/a83db2e236bfecf2e1a7440ea3fa8ca4ec227f4e/merging_iter.go#L333)):*
> ```Go
> 			m.heap.items = append(m.heap.items, l)
> 		} else {
> 			m.err = firstError(m.err, l.iter.Error())
> ```

why did this error checking go away?
___
*[`internal/itertest/dsl.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnL_HaI2_-koqGoL1XS:-NnL_HaI2_-koqGoL1XT:bynw7bx) ([raw file](https://github.com/cockroachdb/pebble/blob/8f158cdf1e6e07862d907185486c91cf4d3f967b/internal/itertest/dsl.go#L88)):*
> ```Go
> 
> // Error implements error.
> func (p *ErrorProbe) Error() error {
> ```

why does `ErrorProbe` need to implement `error`?
___
*[`internal/itertest/probe.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnLWt79B0lGsOi0c-_n:-NnLWt7A0tVcbKTOdBF-:b1np7s5) ([raw file](https://github.com/cockroachdb/pebble/blob/8f158cdf1e6e07862d907185486c91cf4d3f967b/internal/itertest/probe.go#L66)):*
> ```Go
> 	Kind    OpKind
> 	SeekKey []byte
> 	Key     *base.InternalKey
> ```

Can you clarify in a code comment that Key, Value and Err are initialized with the what the iterator returned, if there was an underlying iterator. And then the probe can alter them.
___
*[`internal/itertest/probe.go` line 135 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnLYJrN-78RsQrihJif:-NnLYJrN-78RsQrihJig:b-4la5br) ([raw file](https://github.com/cockroachdb/pebble/blob/8f158cdf1e6e07862d907185486c91cf4d3f967b/internal/itertest/probe.go#L135)):*
> ```Go
> func (p *probeIterator) handleOp(preProbeOp Op) (*base.InternalKey, base.LazyValue) {
> 	p.probeCtx.Op = preProbeOp
> 	if preProbeOp.Key == nil && p.iter != nil {
> ```

why does it matter whether `preProbeOp.Key == nil`? Presumably this is classifying operations into absolute positioning ones and relative positioning ones. Shouldn't we care about the error returned by the underlying iterator even for absolute positioning operations?
___
*[`internal/itertest/probe.go` line 140 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnLY35h0L8WY5qS7BTP:-NnLY35h0L8WY5qS7BTQ:b-czg3lu) ([raw file](https://github.com/cockroachdb/pebble/blob/8f158cdf1e6e07862d907185486c91cf4d3f967b/internal/itertest/probe.go#L140)):*
> ```Go
> 
> 	p.probe.Probe(&p.probeCtx)
> 	p.err = p.probeCtx.Op.Err
> ```

Do we need to copy the error into `p.err`, or can we just return `p.probeCtx.Op.Err` in `probeIterator.Error`?
___
*[`internal/itertest/probe.go` line 233 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnLZEC2CoDtm_QVMnWQ:-NnLZEC2CoDtm_QVMnWR:b-co8icg) ([raw file](https://github.com/cockroachdb/pebble/blob/8f158cdf1e6e07862d907185486c91cf4d3f967b/internal/itertest/probe.go#L233)):*
> ```Go
> 	}
> 
> 	p.probeCtx.Op = op
> ```

couldn't use `handleOp` here?


<!-- Sent from Reviewable.io -->

2024-01-05 17:39 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3181)* status: 6 of 11 files reviewed, 6 unresolved discussions (waiting on @aadityasondhi and @sumeerbhola)

___
*[`merging_iter.go` line 333 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnLb6465UN2b3-6nBtx:-NnPRsHk6dkUgt460C9F:b-k8y1he) ([raw file](https://github.com/cockroachdb/pebble/blob/a83db2e236bfecf2e1a7440ea3fa8ca4ec227f4e/merging_iter.go#L333)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why did this error checking go away?
</blockquote></details>

error checking was moved to be alongside the iterator positioning operation that might've errored, and this method doesn't actually perform any positioning. The move is partially motivated by the plan to begin returning error return values from the positioning methods themselves
___
*[`internal/itertest/dsl.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnL_HaI2_-koqGoL1XS:-NnPSIRGCwvP9E0EjbTG:b-5i0hod) ([raw file](https://github.com/cockroachdb/pebble/blob/8f158cdf1e6e07862d907185486c91cf4d3f967b/internal/itertest/dsl.go#L88)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why does `ErrorProbe` need to implement `error`?
</blockquote></details>

hm, it doesn't really need to—the intention is that `ErrInjected` is both the injected error value and implements the `Probe` interface by inserting itself. maybe a case of 'you aren't gonna need it'.
___
*[`internal/itertest/probe.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnLWt79B0lGsOi0c-_n:-NnPUC1gAe1N790PCl5c:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8f158cdf1e6e07862d907185486c91cf4d3f967b/internal/itertest/probe.go#L66)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you clarify in a code comment that Key, Value and Err are initialized with the what the iterator returned, if there was an underlying iterator. And then the probe can alter them.
</blockquote></details>

Done.
___
*[`internal/itertest/probe.go` line 135 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnLYJrN-78RsQrihJif:-NnPUw503JWM1i-8Kcxt:bntubs4) ([raw file](https://github.com/cockroachdb/pebble/blob/8f158cdf1e6e07862d907185486c91cf4d3f967b/internal/itertest/probe.go#L135)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why does it matter whether `preProbeOp.Key == nil`? Presumably this is classifying operations into absolute positioning ones and relative positioning ones. Shouldn't we care about the error returned by the underlying iterator even for absolute positioning operations?
</blockquote></details>

`Op.Key` was the returned InternalKey (and we're only required to check `Error()` if the key is `nil`. This naming was confusing so I embedded `Key`, `Value` and `Err` under a `Return` field to disambiguate the seek key from the key returned by the iterator.
___
*[`internal/itertest/probe.go` line 140 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnLY35h0L8WY5qS7BTP:-NnPgRjP6MTKCnYg34-S:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/8f158cdf1e6e07862d907185486c91cf4d3f967b/internal/itertest/probe.go#L140)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we need to copy the error into `p.err`, or can we just return `p.probeCtx.Op.Err` in `probeIterator.Error`?
</blockquote></details>

Done.
___
*[`internal/itertest/probe.go` line 233 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnLZEC2CoDtm_QVMnWQ:-NnPh3cW0-NbwLpAbPFb:b-davgcl) ([raw file](https://github.com/cockroachdb/pebble/blob/8f158cdf1e6e07862d907185486c91cf4d3f967b/internal/itertest/probe.go#L233)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

couldn't use `handleOp` here?
</blockquote></details>

added a comment; we don't want to call `iter.Error()`, like handleOp does.


<!-- Sent from Reviewable.io -->

2024-01-08 21:38 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 2 of 9 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3181#-:-Nnf-lZpApOkP9yUeWRL:b-uwkowd)* status: all files reviewed, 8 unresolved discussions (waiting on @aadityasondhi and @jbowens)

___
*[`merging_iter.go` line 703 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3181#-Nnew39gBbq9uYfRkSg9:-Nnew39gBbq9uYfRkSgA:b-xz1el3) ([raw file](https://github.com/cockroachdb/pebble/blob/1bbcdea5024475e66d8cc7b9ae8b98fe8f9631db/merging_iter.go#L703)):*
> ```Go
> // it is deleted, moves the iterators forward as needed and returns true, else
> // it returns false. item is the top item in the heap. If any of the required
> // iterator operations error,the error is returend without updating m.err.
> ```

nit: returned
___
*[`testdata/merging_iter` line 363 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3181#-NnexK6u-ecvFlj5BF3C:-NnexK6u-ecvFlj5BF3D:b-o59e14) ([raw file](https://github.com/cockroachdb/pebble/blob/1bbcdea5024475e66d8cc7b9ae8b98fe8f9631db/testdata/merging_iter#L363)):*
> ```
> d#4,1:4
> 
> # Test the above but an error is encounted when Prev-ing to establish the min
> ```

nit: encountered


<!-- Sent from Reviewable.io -->

2024-01-08 22:03 UTC, jbowens reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3181#-:-Nnf5ZPu-KFwwuM9aJIu:b-814g8k)* status: 4 of 11 files reviewed, 6 unresolved discussions (waiting on @aadityasondhi and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2024-01-08 22:17 UTC, merged