base: add UserKeyBounds
cockroachdb/pebble pull request #3417
Opened 2024-03-17 00:03 UTC by RaduBerinde

This commit adds `UserKeyBounds` which represents a range of user keys with inclusive start boundary and either inclusive or exclusive range boundary.

This replaces ad-hoc code in various places.

Note: I think there are more places where this can be used and I will look at them as a follow-up, I just didn't want it all in one PR.

2024-03-17 00:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/3417)
<!-- Reviewable:end -->

2024-03-19 14:58 UTC, sumeerbhola requested changes
Looks great. Some minor comments.

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3417#-:-NtMCz104pmiZl8Oymo3:bm54kgh)* status: all files reviewed, 9 unresolved discussions (waiting on @itsbilal, @jbowens, and @RaduBerinde)

___
*[`flushable.go` line 297 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM9HB4Bo25Hm5BZ_f-:-NtM9HB4Bo25Hm5BZ_f0:b96u0an) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/flushable.go#L297)):*
> ```Go
> 			fileBounds := f.UserKeyBounds()
> 			if fileBounds.End.Applies(s.comparer.Compare, bounds.Start) {
> 				// This file's largest key is larger than bounds.Start. Either the file
> ```

equal to or larger?
___
*[`flushable.go` line 301 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM9PIM4HtjrzWDAQSL:-NtM9PIM4HtjrzWDAQSM:b-3fhwr3) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/flushable.go#L301)):*
> ```Go
> 				// we can stop iterating since the files are sorted. But first,
> 				// determine if there's overlap and call fn if necessary.
> 				if bounds.End.Applies(s.comparer.Compare, fileBounds.Start) {
> ```

How about adding to the comment:
The bounds largest key is greater than equal to the file's smallest key. So the file overlaps ....
___
*[`ingest.go` line 781 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM6vIv4YmJjBxDYDmt:-NtM6vIv4YmJjBxDYDmu:b-p8k1ln) ([raw file](https://github.com/cockroachdb/pebble/blob/3453026711f90e73fe8bff98f16a72adf570b2a2/ingest.go#L781)):*
> ```Go
> 	computeOverlapWithSpans := func(rIter keyspan.FragmentIterator) (bool, error) {
> 		// NB: The spans surfaced by the fragment iterator are non-overlapping.
> 		span, err := rIter.SeekLT(keyRange.smallest.UserKey)
> ```

was this `SeekLT` unnecessary, because it predated https://github.com/cockroachdb/pebble/commit/a80169845786dc35b791d5071a165977c45b80d7?
___
*[`ingest.go` line 790 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM8SPO97ADleZPvPI-:-NtM8SPO97ADleZPvPI0:b-2mdlia) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/ingest.go#L790)):*
> ```Go
> 				// The span starts after our bounds.
> 				return false, nil
> 			}
> ```

SeekGE says
```
	// SeekGE moves the iterator to the first span covering a key greater than
	// or equal to the given key. This is equivalent to seeking to the first
	// span with an end key greater than the given key.
```
so aren't we guaranteed that span.End > bounds.Start, so the following comparison is unnecessary?
___
*[`internal/base/key_bounds.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM2EfqEMiyvWfq8mtN:-NtM2EfqEMiyvWfq8mtO:bootmp4) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/base/key_bounds.go#L62)):*
> ```Go
> 
> // Applies returns true if the given key is "before" the end boundary.
> func (eb UserKeyEndBoundary) Applies(cmp Compare, userKey []byte) bool {
> ```

would `GreaterOrEqual` fully capture the meaning?
___
*[`internal/base/key_bounds.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM2VHi9n6gDJzZG0Qe:-NtM2VHi9n6gDJzZG0Qf:b-ttik4m) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/base/key_bounds.go#L69)):*
> ```Go
> // AppliesToInternalKey returns true if the given internal key is "before" the
> // end boundary.
> func (eb UserKeyEndBoundary) AppliesToInternalKey(cmp Compare, key InternalKey) bool {
> ```

GreaterOrEqualThanInternalKey?
___
*[`internal/base/key_bounds.go` line 153 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM3Rrb2BS4wvWmE1ak:-NtM3Rrb2BS4wvWmE1al:bpafkw7) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/base/key_bounds.go#L153)):*
> ```Go
> }
> 
> // Format converts the bounds to a string of the form "[foo, bar)", using the
> ```

nit: "[foo, bar)" or "[foo, bar]" ...
___
*[`internal/manifest/version.go` line 985 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtMAigz7Ufu6Bd0WFSY:-NtMAigz7Ufu6Bd0WFSZ:b-txr19v) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/manifest/version.go#L985)):*
> ```Go
> 
> func overlaps(iter LevelIterator, cmp Compare, bounds base.UserKeyBounds) LevelSlice {
> 	startIter := iter.Clone()
> ```

how about adding a comment that `overlaps` is only for levels other than L0.
___
*[`internal/manifest/version.go` line 1006 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtMAtstDQB6kInyCStV:-NtMAtstDQB6kInyCStW:bu1zcvt) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/manifest/version.go#L1006)):*
> ```Go
> 		if bounds.End.Kind == base.Inclusive {
> 			// endIter is now pointing at the *first* file with a largest key >= end.
> 			// If there are multiple files including the user key `end`, we want all
> ```

Will there be multiple files, given we don't split user keys across files? should we add a panic?
We are also not checking if the `endIterFile.Largest` is exclusive, so I suppose it could be and we do need to `Next()`. Though, `LevelIterator.SeekGE` should give us some guarantees there. Probably best to leave this as-is for now, with a TODO to come back to this.


<!-- Sent from Reviewable.io -->

2024-03-19 16:15 UTC, RaduBerinde commented
*[`internal/base/key_bounds.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM2EfqEMiyvWfq8mtN:-NtMU6Q6DklaZX92I0r-:b8qvfcn) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/base/key_bounds.go#L62)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

would `GreaterOrEqual` fully capture the meaning?
</blockquote></details>

GreaterOrEqual is confusing when it's exclusive. I wanted a more conceptual term that abstracts away the exact kind of comparison we need to make. If it was a method on the key I'd call it "Within(boundary)" or "CompliesWith(boundary)" I couldn't find a better reciprocal to that than "applies". Maybe "Contains" would work better?


<!-- Sent from Reviewable.io -->

2024-03-19 18:27 UTC, sumeerbhola requested changes
> Reviewed 3 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3417)* status: 15 of 18 files reviewed, 9 unresolved discussions (waiting on @itsbilal, @jbowens, and @RaduBerinde)

___
*[`flushable.go` line 297 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM9HB4Bo25Hm5BZ_f-:-NtMwor31v-EQHm9xeSV:b-gm90mg) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/flushable.go#L297)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do you understand why it's ok to stop and `break` below? Is it not possible that a `bounded` overlaps multiple files on a level?
</blockquote></details>

Yes, it could overlap with multiple files in the `ingestedFlushable`.
The contract is that the `ingestedFlushable` is one entity, and the caller just wants to know the `bounded` objects that overlap with that entity. `fn` doesn't care which part of that entity overlapped.
___
*[`internal/base/key_bounds.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM2EfqEMiyvWfq8mtN:-NtMrdUaE7Q_wD7frEMV:b-ot6whu) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/base/key_bounds.go#L62)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

GreaterOrEqual is confusing when it's exclusive. I wanted a more conceptual term that abstracts away the exact kind of comparison we need to make. If it was a method on the key I'd call it "Within(boundary)" or "CompliesWith(boundary)" I couldn't find a better reciprocal to that than "applies". Maybe "Contains" would work better?
</blockquote></details>

Admittedly, we are doing something slightly odd. All the callers of this method, and `AppliesToInternalKey`, from outside this file, have a whole `UserKeyBounds` and are choosing to call with the end key in that bounds struct (instead of calling a method on the whole struct).

So stepping back, if we have an interval [a, b) or [a, b], and a different key c, what we are asking is whether the interval extends up to or beyond c. But we also want it to return true when a > c, so there isn't a clear meaning to what we are asking even if we asked with a whole interval (which suggests "Contains" could be more confusing)

So coming back to the end key by itself. It represents a key b (inclusive) or immediatePredecessor(b) (exclusive). Yes, we can't compute the immediatePredecessor, but it is conceptually a key (I realize I am on shaky ground here, since one can't argue that a real number has an immediate predecessor, even if one can't compute it). So if we go with that interpretation, GreaterOrEqual is reasonable, just like 1.999... < 2 - delta as delta approaches 0.


<!-- Sent from Reviewable.io -->

2024-03-19 20:03 UTC, RaduBerinde reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3417#-:-NtNIicW3fns3oWv9ynL:b-814g8k)* status: 13 of 18 files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`flushable.go` line 297 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM9HB4Bo25Hm5BZ_f-:-NtN892sBkrct2VF3TX8:b-whespq) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/flushable.go#L297)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Yes, it could overlap with multiple files in the `ingestedFlushable`.
The contract is that the `ingestedFlushable` is one entity, and the caller just wants to know the `bounded` objects that overlap with that entity. `fn` doesn't care which part of that entity overlapped.
</blockquote></details>

Ah, duh, thanks. I reworked the code a bit to make things more clear. Also added an invariants check that the files really are sorted.
___
*[`internal/base/key_bounds.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM2EfqEMiyvWfq8mtN:-NtNBVn39d7VWF6XjQOV:b-7e85yu) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/base/key_bounds.go#L62)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Admittedly, we are doing something slightly odd. All the callers of this method, and `AppliesToInternalKey`, from outside this file, have a whole `UserKeyBounds` and are choosing to call with the end key in that bounds struct (instead of calling a method on the whole struct).

So stepping back, if we have an interval [a, b) or [a, b], and a different key c, what we are asking is whether the interval extends up to or beyond c. But we also want it to return true when a > c, so there isn't a clear meaning to what we are asking even if we asked with a whole interval (which suggests "Contains" could be more confusing)

So coming back to the end key by itself. It represents a key b (inclusive) or immediatePredecessor(b) (exclusive). Yes, we can't compute the immediatePredecessor, but it is conceptually a key (I realize I am on shaky ground here, since one can't argue that a real number has an immediate predecessor, even if one can't compute it). So if we go with that interpretation, GreaterOrEqual is reasonable, just like 1.999... < 2 - delta as delta approaches 0.
</blockquote></details>

I was thinking about it like `EndBoundary` represents the range `[MinKey - Key]` or `[MinKey - Key)`, hence the Contains. But I agree that when using it from `UserKeyBounds` it becomes confusing.

I see your real line analogy but the readers of the code might not have the same analogy in mind..

Some other ideas:
 - `Includes() / IncludesInternalKey()`
 - `Encloses() / EnclosesInternalKey()`
 - reverse the meaning and call it `Excludes[InternalKey]`

Or reverse it to `base.UserKeyWithinEndBoundary()` and `InternalKey.WithinEndBoundary()`. Maybe one day we'll have a `UserKey` type and the first one would become `UserKey.WithinEndBoundary()`.
___
*[`internal/manifest/version.go` line 985 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtMAigz7Ufu6Bd0WFSY:-NtNFXszE3FXuXXrVwY8:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/manifest/version.go#L985)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about adding a comment that `overlaps` is only for levels other than L0.
</blockquote></details>

Done.
___
*[`internal/manifest/version.go` line 1006 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtMAtstDQB6kInyCStV:-NtNHqXE6xba56Esb3Mn:b-dzfe3v) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/manifest/version.go#L1006)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Will there be multiple files, given we don't split user keys across files? should we add a panic?
We are also not checking if the `endIterFile.Largest` is exclusive, so I suppose it could be and we do need to `Next()`. Though, `LevelIterator.SeekGE` should give us some guarantees there. Probably best to leave this as-is for now, with a TODO to come back to this.
</blockquote></details>

Yeah I tried to simplify it and got some test failures. Leaving a TODO.


<!-- Sent from Reviewable.io -->

2024-03-19 21:28 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 6 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3417#-:-NtNbGNj5YLzVXXUn0Qp:bg7igkv)* status: all files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, and @RaduBerinde)

___
*[`internal/base/key_bounds.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM2EfqEMiyvWfq8mtN:-NtNZx3c5KeklOufj-oj:b-1061l1) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/base/key_bounds.go#L62)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I was thinking about it like `EndBoundary` represents the range `[MinKey - Key]` or `[MinKey - Key)`, hence the Contains. But I agree that when using it from `UserKeyBounds` it becomes confusing.

I see your real line analogy but the readers of the code might not have the same analogy in mind..

Some other ideas:
 - `Includes() / IncludesInternalKey()`
 - `Encloses() / EnclosesInternalKey()`
 - reverse the meaning and call it `Excludes[InternalKey]`

Or reverse it to `base.UserKeyWithinEndBoundary()` and `InternalKey.WithinEndBoundary()`. Maybe one day we'll have a `UserKey` type and the first one would become `UserKey.WithinEndBoundary()`.
</blockquote></details>

Go with whatever name you prefer -- I don't want to bike shed this.

One thought is that the method comment says "Applies returns true if the given key is "before" the end boundary." (though it should say "before or equal"), and how we explain the method can suggest the name. So perhaps `AfterOrEqual`?
___
*[`internal/manifest/version.go` line 1006 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtMAtstDQB6kInyCStV:-NtN_tB3BsoAF2M8y121:b-ucfkn4) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/manifest/version.go#L1006)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah I tried to simplify it and got some test failures. Leaving a TODO.
</blockquote></details>

Thanks.


<!-- Sent from Reviewable.io -->

2024-03-20 00:10 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3417)* status: all files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`internal/base/key_bounds.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM2EfqEMiyvWfq8mtN:-NtOB1TU9hSNdSWkQzoc:brletmy) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/base/key_bounds.go#L62)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Go with whatever name you prefer -- I don't want to bike shed this.

One thought is that the method comment says "Applies returns true if the given key is "before" the end boundary." (though it should say "before or equal"), and how we explain the method can suggest the name. So perhaps `AfterOrEqual`?
</blockquote></details>

I don't love either of the options so far.. I'll sleep on it a bit.

I wrote "before" because in my mind the boundary is conceptually an infinitely thin vertical line that is immediately either before of after `.Key` :)


<!-- Sent from Reviewable.io -->

2024-03-20 00:49 UTC, RaduBerinde commented
*[`internal/base/key_bounds.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM2EfqEMiyvWfq8mtN:-NtOK-1eDm0uLG1ZGTlE:b-7ci3u1) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/base/key_bounds.go#L62)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't love either of the options so far.. I'll sleep on it a bit.

I wrote "before" because in my mind the boundary is conceptually an infinitely thin vertical line that is immediately either before of after `.Key` :)
</blockquote></details>

Yet another option would be a method on `Compare` itself, `cmp.WithinEndBound(key, b.End)`


<!-- Sent from Reviewable.io -->

2024-03-20 03:10 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3417)* status: 13 of 18 files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`internal/base/key_bounds.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM2EfqEMiyvWfq8mtN:-NtOp7jODqqYpRpXbCDQ:b-n26ckj) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/base/key_bounds.go#L62)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yet another option would be a method on `Compare` itself, `cmp.WithinEndBound(key, b.End)`
</blockquote></details>

Ok, I came up with something reasonable. I changed the boundary to be a more generic `UserKeyBoundary` (no longer specific to the end of the interval) and changed this method to `IsUpperBoundFor`. This makes the call sites more clear.


<!-- Sent from Reviewable.io -->

2024-03-20 17:51 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3417#-:-NtRzGlG3WPcdFbealo3:bg7igkv)* status: all files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, and @RaduBerinde)

___
*[`internal/base/key_bounds.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM2EfqEMiyvWfq8mtN:-NtRzA329jt9-26zEMxp:b-mp4sc1) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/base/key_bounds.go#L62)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ok, I came up with something reasonable. I changed the boundary to be a more generic `UserKeyBoundary` (no longer specific to the end of the interval) and changed this method to `IsUpperBoundFor`. This makes the call sites more clear.
</blockquote></details>

`IsUpperBoundFor` is perfect.


<!-- Sent from Reviewable.io -->

2024-03-20 17:56 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3417)* status: all files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`internal/base/key_bounds.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3417#-NtM2EfqEMiyvWfq8mtN:-NtS-QiM0vcYvvZ8iTgR:bz5m8k5) ([raw file](https://github.com/cockroachdb/pebble/blob/5f3957aef786c1577c2df94f05ad66c334da5a82/internal/base/key_bounds.go#L62)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

`IsUpperBoundFor` is perfect.
</blockquote></details>

TFTR!!


<!-- Sent from Reviewable.io -->

2024-03-20 17:56 UTC, merged