colblk: add UintBuilder, DeltaEncoding
cockroachdb/pebble pull request #3731
Opened 2024-07-03 15:52 UTC by jbowens

Add a UintBuilder column writer for building uint{8,16,32,64} columns. The UintBuilder will use a delta encoding when possible to represent an array of values as a constant C and an array of deltas using a smaller-width uint. This is expected to reduce the size of blocks in many instances. Internal key trailers have zero sequence numbers in ingested sstables, and almost always have zero sequence numbers in L6 sstables. This will allow most data blocks in these sstables to encode either a single 8-byte constant, or an 8-byte constant and an array of 1-byte deltas if the key kinds vary.

2024-07-03 15:52 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/3731)
<!-- Reviewable:end -->

2024-07-03 19:14 UTC, RaduBerinde reviewed
Cool! Made a first pass but haven't looked at the testing code yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731#-:-O0u0DUl8deWJmNQeeg5:bbug1gh)* status: 0 of 9 files reviewed, 10 unresolved discussions (waiting on @aadityasondhi, @jbowens, @petermattis, and @sumeerbhola)

___
*[`internal/aligned/aligned.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0t_PgK3Zl1GusBPkZX:-O0t_PgK3Zl1GusBPkZY:bw5k7j1) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/internal/aligned/aligned.go#L16)):*
> ```Go
> // but small n can often be misaligned.
> func ByteSlice(n int) []byte {
> 	// Allocate n + align64 - 1 bytes to ensure we have room to align.
> ```

Does Go guarantee that a `[]uint64` is aligned? (I would be surprised if it didn't). We could do `make([]uint64, (n+align64-1)/align64)` and do an unsafe cast to `[]byte`. That way we won't allocate weird lengths when our lengths are "nice" (eg powers of 2)
___
*[`sstable/colblk/column.go` line 61 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tZTVH1lhkDfr2Y3D7:-O0tZTVH1lhkDfr2Y3D8:bezz7je) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/column.go#L61)):*
> ```Go
> func (t DataType) uintWidth() uint32 {
> 	switch t {
> 	case DataTypeUint8:
> ```

[nit] could be
```
  if d >= DataTypeUint8 && d <= DataTypeUint64 {
    return 1 << (d - DataTypeUint8)
  }
  panic()
```
___
*[`sstable/colblk/column.go` line 111 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tsnUr8V6oTqlnb5Ty:-O0tsnUr8V6oTqlnb5Tz:bgu0tlj) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/column.go#L111)):*
> ```Go
> // ColumnEncoding describes the encoding of a column.
> //
> // Delta encoding (bits 0, 1):
> ```

Here we are trying to convey three things
 - how the possible encodings work at a high level
 - how the encoded data is organized
 - how we encode this information into the uint8

We shouldn't need to read through descriptions of the lower aspects in order to understand the higher aspects. I'd focus on these three aspects separately. Here's an attempt (assuming I understood the details correctly).

```
// ColumnEncoding describes the data encoding for a single column.
//
// Column data can optionally contain a NULL bitmap, where each bit corresponds
// to a row in the column and a set bit indicates that the corresponding row is
// NULL). Column data can optionally use delta encoding where each value is a
// delta from a base, constant value.
//
// The layout of the encoded data is as follows:
//   - [optional] NULL Bitmap
//   - [optional] a "base" constant value for delta encodings
//   - n data values.
//
// The ColumnEncoding byte is a combination of the following values:
//   - delta encoding indicator (0 to 1): indicates if delta encoding is used.
//   - delta encoding byte width (0 to 3): the byte width of the data values
//     representing the deltas; 0 indicates all values are equal.
//   - null bitmap indicator (0 to 1)
```
___
*[`sstable/colblk/column.go` line 175 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0u-O-WCZlX8sE5zwnS:-O0u-O-WCZlX8sE5zwnT:b-vk14pl) ([raw file](https://github.com/cockroachdb/pebble/blob/dc95e51b0638a9f12bb93f3ffd3476cbf6abc191/sstable/colblk/column.go#L175)):*
> ```Go
> 	var sb strings.Builder
> 	if e.HasConstant() {
> 		fmt.Fprint(&sb, "const")
> ```

[nit] wouldn't "delta" be more appropriate? In general, I find it strange that the focus is on whether there is a constant rather than whether we are using a delta encoding. I guess the constant will make more sense as we introduce more encodings/types? (for bytes values maybe it's a byte prefix for all of them? though I would also consider that a "delta" encoding at a high level)
___
*[`sstable/colblk/column.go` line 192 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0u0-R22PPO0G5pctDo:-O0u0-R22PPO0G5pctDp:bccml42) ([raw file](https://github.com/cockroachdb/pebble/blob/dc95e51b0638a9f12bb93f3ffd3476cbf6abc191/sstable/colblk/column.go#L192)):*
> ```Go
> 	// indicates a constant is present, the entirety of the column is a single
> 	// value. Otherwise, the column encodes n full-width values for n rows.
> 	DeltaEncodingNone DeltaEncoding = 0
> ```

[nit] I think it would be useful to differentiate between "no delta encoding" and "delta encoding with no data". Or rename to `DeltaEncodingWidth` but then don't define values like it's an enum.
___
*[`sstable/colblk/uints.go` line 32 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tvBL44NT0l3cp6iTE:-O0tvBL44NT0l3cp6iTF:b-ml5uda) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/uints.go#L32)):*
> ```Go
> 
> 	// array holds the underlying heap-allocated array in which values are
> 	// stored. elems provides access to elements without bounds checking. n is
> ```

[nit] move the comment for `n` above `n int`
___
*[`sstable/colblk/uints.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0twx4z3LnXsro5nEnI:-O0twx4z3LnXsro5nEnJ:b8vitas) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/uints.go#L37)):*
> ```Go
> 	array struct {
> 		n     int
> 		elems UnsafeRawSlice[T]
> ```

[nit] mention that elems is a slice that grows automatically
___
*[`sstable/colblk/uints.go` line 71 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tw1plAYew8Hn5fiRo:-O0tw1plAYew8Hn5fiRp:b-32837h) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/uints.go#L71)):*
> ```Go
> // Init initializes the UintBuilder. If useDefault=true, any rows that are not
> // explicitly set are assumed to be the provided default value. For the purpose
> // of determining whether a delta encoding is possible, the column is assumed to
> ```

It wasn't clear from this comment if the last statement is only true when `setDefault` is true.
It feels weird to have to pass an inconsequential value when `useDefault` is false.. Maybe split into `Init` and `InitWithDefaultValue`?


By the way, why is that assumption necessary? Can't we calculate all th delta stuff in `Finish`?
___
*[`sstable/colblk/unsafe_slice.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0txmRA8YDXm7Lusx6Z:-O0txmRA8YDXm7Lusx6_:b-4mua2y) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/unsafe_slice.go#L43)):*
> ```Go
> }
> 
> // UnsafeUint8s is an UnsafeRawSlice of uint8s.
> ```

UnsafeIntegerSlice. But maybe it would be more useful something like "is a slice of uint8s, possibly using delta encoding internally".
___
*[`sstable/colblk/unsafe_slice.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tzbLGELB4_yfvgJwS:-O0tzbLGELB4_yfvgJwT:b-li78hk) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/unsafe_slice.go#L81)):*
> ```Go
> // At returns the `i`-th element of the slice.
> func (s UnsafeIntegerSlice[T]) At(i int) T {
> 	switch s.deltaWidth {
> ```

This branching in the hot path is unfortunate.. Maybe the compiler optimizes it nicely with a table..

I wonder if it would be feasible (depending on how it's used) to make it generic in both the visible type and the underlying type (`UnsafeIntegerSlice[T constraints.Integer, U constraints.Integer]`).


<!-- Sent from Reviewable.io -->

2024-07-03 21:24 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @aadityasondhi, @petermattis, @RaduBerinde, and @sumeerbhola)

___
*[`internal/aligned/aligned.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0t_PgK3Zl1GusBPkZX:-O0uT3486gB5Q26Bpt3k:bap0xug) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/internal/aligned/aligned.go#L16)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Does Go guarantee that a `[]uint64` is aligned? (I would be surprised if it didn't). We could do `make([]uint64, (n+align64-1)/align64)` and do an unsafe cast to `[]byte`. That way we won't allocate weird lengths when our lengths are "nice" (eg powers of 2)
</blockquote></details>

Yeah, from some reading I believe it does. That's a good idea. In real block cache allocations, we'll use `malloc` and have a word-alignment guarantee.
___
*[`sstable/colblk/column.go` line 61 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tZTVH1lhkDfr2Y3D7:-O0uTzXr7KR-mtm39cPd:b-esfcfc) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/column.go#L61)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] could be
```
  if d >= DataTypeUint8 && d <= DataTypeUint64 {
    return 1 << (d - DataTypeUint8)
  }
  panic()
```
</blockquote></details>

nice, done
___
*[`sstable/colblk/column.go` line 111 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tsnUr8V6oTqlnb5Ty:-O0uS-ue-w-EL1_lWDvT:b3tylto) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/column.go#L111)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Here we are trying to convey three things
 - how the possible encodings work at a high level
 - how the encoded data is organized
 - how we encode this information into the uint8

We shouldn't need to read through descriptions of the lower aspects in order to understand the higher aspects. I'd focus on these three aspects separately. Here's an attempt (assuming I understood the details correctly).

```
// ColumnEncoding describes the data encoding for a single column.
//
// Column data can optionally contain a NULL bitmap, where each bit corresponds
// to a row in the column and a set bit indicates that the corresponding row is
// NULL). Column data can optionally use delta encoding where each value is a
// delta from a base, constant value.
//
// The layout of the encoded data is as follows:
//   - [optional] NULL Bitmap
//   - [optional] a "base" constant value for delta encodings
//   - n data values.
//
// The ColumnEncoding byte is a combination of the following values:
//   - delta encoding indicator (0 to 1): indicates if delta encoding is used.
//   - delta encoding byte width (0 to 3): the byte width of the data values
//     representing the deltas; 0 indicates all values are equal.
//   - null bitmap indicator (0 to 1)
```
</blockquote></details>

thanks, agreed that's much better
___
*[`sstable/colblk/column.go` line 175 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0u-O-WCZlX8sE5zwnS:-O0uS2j73V8M8cmp_J94:b-u33f6x) ([raw file](https://github.com/cockroachdb/pebble/blob/dc95e51b0638a9f12bb93f3ffd3476cbf6abc191/sstable/colblk/column.go#L175)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] wouldn't "delta" be more appropriate? In general, I find it strange that the focus is on whether there is a constant rather than whether we are using a delta encoding. I guess the constant will make more sense as we introduce more encodings/types? (for bytes values maybe it's a byte prefix for all of them? though I would also consider that a "delta" encoding at a high level)
</blockquote></details>

Yeah, I agree I found this organization a little unsatisfying. I was trying to preserve the flexibility to use the 'constant bit' for other column types that could encode a single value representing the value for all rows. Eg, if all rows had the same byte slice, the RawBytes encoding could set the constant bit and only encode a single byte slice. I don't think it's realistic for most data types, so I've taken your suggestion of collapsing the the constant w/ no deltas option into the DeltaEncoding enum. 
___
*[`sstable/colblk/column.go` line 192 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0u0-R22PPO0G5pctDo:-O0uStyiBE51TqnblYgz:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/dc95e51b0638a9f12bb93f3ffd3476cbf6abc191/sstable/colblk/column.go#L192)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I think it would be useful to differentiate between "no delta encoding" and "delta encoding with no data". Or rename to `DeltaEncodingWidth` but then don't define values like it's an enum.
</blockquote></details>

Done
___
*[`sstable/colblk/uints.go` line 71 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tw1plAYew8Hn5fiRo:-O0uHjBa0wP7RcTAPY2D:bkedede) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/uints.go#L71)):*
> Maybe split into `Init` and `InitWithDefaultValue`?

Done.

> By the way, why is that assumption necessary? Can't we calculate all th delta stuff in `Finish`?

We need the Size to be accurate, but also performant, because we call it after every additional kv to determine whether we should finish the block.
___
*[`sstable/colblk/unsafe_slice.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0txmRA8YDXm7Lusx6Z:-O0uIW4d2WzfARGpPH2m:bb7f2mf) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/unsafe_slice.go#L43)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

UnsafeIntegerSlice. But maybe it would be more useful something like "is a slice of uint8s, possibly using delta encoding internally".
</blockquote></details>

done
___
*[`sstable/colblk/unsafe_slice.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tzbLGELB4_yfvgJwS:-O0uIhDF4jvUHC88nAkD:b-udmxdj) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/unsafe_slice.go#L81)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This branching in the hot path is unfortunate.. Maybe the compiler optimizes it nicely with a table..

I wonder if it would be feasible (depending on how it's used) to make it generic in both the visible type and the underlying type (`UnsafeIntegerSlice[T constraints.Integer, U constraints.Integer]`).
</blockquote></details>

Yeah, it's unfortunate. I think the visible type will always be statically known, but the underlying type will never be. 


<!-- Sent from Reviewable.io -->

2024-07-03 21:54 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731)* status: 0 of 9 files reviewed, 8 unresolved discussions (waiting on @aadityasondhi, @jbowens, @petermattis, and @sumeerbhola)

___
*[`sstable/colblk/column.go` line 175 at r3](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0u-O-WCZlX8sE5zwnS:-O0uWVxR5O4dpzwA7r1D:b93qqi2) ([raw file](https://github.com/cockroachdb/pebble/blob/dc95e51b0638a9f12bb93f3ffd3476cbf6abc191/sstable/colblk/column.go#L175)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, I agree I found this organization a little unsatisfying. I was trying to preserve the flexibility to use the 'constant bit' for other column types that could encode a single value representing the value for all rows. Eg, if all rows had the same byte slice, the RawBytes encoding could set the constant bit and only encode a single byte slice. I don't think it's realistic for most data types, so I've taken your suggestion of collapsing the the constant w/ no deltas option into the DeltaEncoding enum.
</blockquote></details>

The RawBytes example is analogous to a constant int column, so we can still call that "delta encoding". In fact for raw bytes we may want to make the constant be any common prefix of the values (with all equal being a special case of that).
___
*[`sstable/colblk/column.go` line 174 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0uX91v8_TSaSCLkaFP:-O0uX91v8_TSaSCLkaFQ:b-m809ht) ([raw file](https://github.com/cockroachdb/pebble/blob/01493604e56e69ce1ad93f8cf7c9179c8d760af8/sstable/colblk/column.go#L174)):*
> ```Go
> 	switch d {
> 	case DeltaEncodingNone:
> 		return ""
> ```

[nit] I'd make this "none" so we don't end up with confusing logs
___
*[`sstable/colblk/uints.go` line 71 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tw1plAYew8Hn5fiRo:-O0uXz9OAjPD3YJZBxtP:b-w6jxn4) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/uints.go#L71)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> Maybe split into `Init` and `InitWithDefaultValue`?

Done.

> By the way, why is that assumption necessary? Can't we calculate all th delta stuff in `Finish`?

We need the Size to be accurate, but also performant, because we call it after every additional kv to determine whether we should finish the block.
</blockquote></details>

I see.. It sounds like `Size` can suddenly double when adding a value.. I wonder if we should have an API that would allow you to finish the block before the doubling. Maybe configuring the builder with a maximum and allowing a `Set` to fail? But that assumes the rows are populated in order.
___
*[`sstable/colblk/uints.go` line 134 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0uXi0P19rLAbcfBUC-:-O0uXi0P19rLAbcfBUC0:b-onm10g) ([raw file](https://github.com/cockroachdb/pebble/blob/01493604e56e69ce1ad93f8cf7c9179c8d760af8/sstable/colblk/uints.go#L134)):*
> ```Go
> 			n2 <<= 1 /* double the size */
> 		}
> 		newData := make([]byte, n2*int(unsafe.Sizeof(T(0))))
> ```

Should we use `ByteSlice` here? Seems like we'd want it aligned.
___
*[`sstable/colblk/unsafe_slice.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tzbLGELB4_yfvgJwS:-O0uZ_CD05P-4qv2G0EY:b-lv8uvo) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/unsafe_slice.go#L81)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, it's unfortunate. I think the visible type will always be statically known, but the underlying type will never be.
</blockquote></details>

Could we always store a `uint64` slice internally and have some precomputed shifts and masks?
```
vals[i>>indexShift] >> ((i & indexMask) << indexShift) & valMask
```
where `indexShift` is log2(byte width), `indexMask = (1 << indexShift)-1`, `valMask = (1 << (1 << indexShift)) - 1`
___
*[`sstable/colblk/unsafe_slice.go` line 89 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0uZTwFA2hJ9jR8IIXK:-O0uZTwFA2hJ9jR8IIXL:bdd9k31) ([raw file](https://github.com/cockroachdb/pebble/blob/01493604e56e69ce1ad93f8cf7c9179c8d760af8/sstable/colblk/unsafe_slice.go#L89)):*
> ```Go
> 		return s.base
> 	case 1:
> 		return s.base + T(*(*int8)(unsafe.Pointer(uintptr(s.deltaPtr) + uintptr(i))))
> ```

Why are these ints signed?


<!-- Sent from Reviewable.io -->

2024-07-04 14:11 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731)* status: 0 of 9 files reviewed, 8 unresolved discussions (waiting on @aadityasondhi, @petermattis, @RaduBerinde, and @sumeerbhola)

___
*[`sstable/colblk/uints.go` line 71 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tw1plAYew8Hn5fiRo:-O0y2Usw-l4HtU0qst2_:b-1whnoo) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/uints.go#L71)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I see.. It sounds like `Size` can suddenly double when adding a value.. I wonder if we should have an API that would allow you to finish the block before the doubling. Maybe configuring the builder with a maximum and allowing a `Set` to fail? But that assumes the rows are populated in order.
</blockquote></details>

I probably did a poor job explaining this in the comments on `ColumnWriter.{Size,Finish}`, but the intention is that the caller can:

1. Add a kv `n-1` to a block and its columns.
2. `size := blockWriter.Size()`
3. Add a kv `n` to a block and its columns.
4. `newSize := blockWriter.Size()`
5. If `newSize` is too big (and, with the new size class heuristics, the old `size` is closer to the size class it falls into), the caller can allocate a buffer for `size` and `blockWriter.Finish(n-1)` to serialize the block without kv `n`.

This avoids some tricky (esp with prefix compression) estimation involved in trying to determine what the block size with a new KV would be.

There's still a wart in the above scheme where if you have large KVs, you end up memcpying everything an extra time: once into the previous block and once into the block it ultimately is written to. I was talking with @sumeerbhola about this in the office.  We might be able to avoid the actual copying of values and keys until we've committed to including the KV in the final block, but we decided that could be a follow-up consideration.


<!-- Sent from Reviewable.io -->

2024-07-04 16:45 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731)* status: 0 of 9 files reviewed, 8 unresolved discussions (waiting on @aadityasondhi, @jbowens, @petermattis, and @sumeerbhola)

___
*[`sstable/colblk/uints.go` line 71 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tw1plAYew8Hn5fiRo:-O0y_iY7662_kxjfh1bh:blfqo3a) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/uints.go#L71)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I probably did a poor job explaining this in the comments on `ColumnWriter.{Size,Finish}`, but the intention is that the caller can:

1. Add a kv `n-1` to a block and its columns.
2. `size := blockWriter.Size()`
3. Add a kv `n` to a block and its columns.
4. `newSize := blockWriter.Size()`
5. If `newSize` is too big (and, with the new size class heuristics, the old `size` is closer to the size class it falls into), the caller can allocate a buffer for `size` and `blockWriter.Finish(n-1)` to serialize the block without kv `n`.

This avoids some tricky (esp with prefix compression) estimation involved in trying to determine what the block size with a new KV would be.

There's still a wart in the above scheme where if you have large KVs, you end up memcpying everything an extra time: once into the previous block and once into the block it ultimately is written to. I was talking with @sumeerbhola about this in the office.  We might be able to avoid the actual copying of values and keys until we've committed to including the KV in the final block, but we decided that could be a follow-up consideration.
</blockquote></details>

Yeah, we could make setting a value a prepare/commit style API:

```
func SetKeyPrepare() SetKeyCommitter
func (SetKeyCommitter) NewSize()
func (SetKeyCommitter) Commit()
```

We only copy the actual data in `Commit`. The `SetKeyCommitter` stores the updated internal state for delta values, which we can just copy directly in `Commit`. We can just discard the `SetKeyCommitter` if we don't want the value in the block.

I think it's simple enough and makes the API cleaner to use - it might be overall less work to just do this from the start, especially if we'll have multiple implementation with similar API.
___
*[`sstable/colblk/uints.go` line 118 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0ybrbK4LWE1Xh9_syQ:-O0ybrbK4LWE1Xh9_syR:b-aztsbn) ([raw file](https://github.com/cockroachdb/pebble/blob/01493604e56e69ce1ad93f8cf7c9179c8d760af8/sstable/colblk/uints.go#L118)):*
> ```Go
> 	} else {
> 		b.delta.minimum = T(0) - 1
> 		b.delta.maximum = 0
> ```

Seems error prone that we don't reset the array values here, even if we expect all of them to get set.
___
*[`sstable/colblk/uints.go` line 125 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0yb8k39bAar2n_J_Iz:-O0yb8k39bAar2n_J_J-:bhxjj9) ([raw file](https://github.com/cockroachdb/pebble/blob/01493604e56e69ce1ad93f8cf7c9179c8d760af8/sstable/colblk/uints.go#L125)):*
> ```Go
> 
> // Set sets the value of the provided row index to v.
> func (b *UintBuilder[T]) Set(row int, v T) {
> ```

Will we ever need to set rows out-of-order? If not, it would be good to require increasing `row` here. It would make some things easier, especially for prefix compression.
In fact, if we're not using the default, we'd require `row` to be the last value plus one


<!-- Sent from Reviewable.io -->

2024-07-08 14:41 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @aadityasondhi, @petermattis, @RaduBerinde, and @sumeerbhola)

___
*[`sstable/colblk/uints.go` line 71 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tw1plAYew8Hn5fiRo:-O1HifrO9MSr22AHuFmG:b6wb0mf) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/uints.go#L71)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, we could make setting a value a prepare/commit style API:

```
func SetKeyPrepare() SetKeyCommitter
func (SetKeyCommitter) NewSize()
func (SetKeyCommitter) Commit()
```

We only copy the actual data in `Commit`. The `SetKeyCommitter` stores the updated internal state for delta values, which we can just copy directly in `Commit`. We can just discard the `SetKeyCommitter` if we don't want the value in the block.

I think it's simple enough and makes the API cleaner to use - it might be overall less work to just do this from the start, especially if we'll have multiple implementation with similar API.
</blockquote></details>

I think it may end up being a pessimization, since the block-building path is hot and the resulting API adds more overhead. I'm going to wait.
___
*[`sstable/colblk/uints.go` line 118 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0ybrbK4LWE1Xh9_syQ:-O1Hj86KEd3LskwSdD9j:b8b9q5h) ([raw file](https://github.com/cockroachdb/pebble/blob/01493604e56e69ce1ad93f8cf7c9179c8d760af8/sstable/colblk/uints.go#L118)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Seems error prone that we don't reset the array values here, even if we expect all of them to get set.
</blockquote></details>

In the data block building benchmarks, resetting these values comes at a significant cost.
___
*[`sstable/colblk/uints.go` line 125 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0yb8k39bAar2n_J_Iz:-O1HkF0R9aFeBtvyv4_g:b-gjqwp7) ([raw file](https://github.com/cockroachdb/pebble/blob/01493604e56e69ce1ad93f8cf7c9179c8d760af8/sstable/colblk/uints.go#L125)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Will we ever need to set rows out-of-order? If not, it would be good to require increasing `row` here. It would make some things easier, especially for prefix compression.
In fact, if we're not using the default, we'd require `row` to be the last value plus one
</blockquote></details>

No, but storing the row per-column on every new KV is a significant cost in the data block building benchmarks.
___
*[`sstable/colblk/uints.go` line 134 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0uXi0P19rLAbcfBUC-:-O1HluhHCYhVcSWf6V0i:b-6ced5m) ([raw file](https://github.com/cockroachdb/pebble/blob/01493604e56e69ce1ad93f8cf7c9179c8d760af8/sstable/colblk/uints.go#L134)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should we use `ByteSlice` here? Seems like we'd want it aligned.
</blockquote></details>

updated to allocate `[]T`
___
*[`sstable/colblk/unsafe_slice.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tzbLGELB4_yfvgJwS:-O1HlknZDsm2Zsz6K3sY:bw41igr) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/unsafe_slice.go#L81)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Could we always store a `uint64` slice internally and have some precomputed shifts and masks?
```
vals[i>>indexShift] >> ((i & indexMask) << indexShift) & valMask
```
where `indexShift` is log2(byte width), `indexMask = (1 << indexShift)-1`, `valMask = (1 << (1 << indexShift)) - 1`
</blockquote></details>

not sure I follow. what do you mean store a `uint64` slice internally?
___
*[`sstable/colblk/unsafe_slice.go` line 89 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0uZTwFA2hJ9jR8IIXK:-O1HkcMi47fhOU_rWwJi:b5ttvwd) ([raw file](https://github.com/cockroachdb/pebble/blob/01493604e56e69ce1ad93f8cf7c9179c8d760af8/sstable/colblk/unsafe_slice.go#L89)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why are these ints signed?
</blockquote></details>

Thanks—forgot to update these when I made a switch to using uints.


<!-- Sent from Reviewable.io -->

2024-07-08 19:15 UTC, sumeerbhola requested changes
> Reviewed 1 of 7 files at r1, 1 of 5 files at r2, 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731)* status: 3 of 9 files reviewed, 8 unresolved discussions (waiting on @aadityasondhi, @jbowens, @petermattis, and @RaduBerinde)

___
*[`internal/aligned/aligned.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0t_PgK3Zl1GusBPkZX:-O1IYoE75fGaUVtvfbO1:b50rbx6) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/internal/aligned/aligned.go#L16)):*
does the unsafe cast approach not work?

> In real block cache allocations, we'll use `malloc` and have a word-alignment guarantee.

Is the idea here that if the block start is word aligned, there is nothing in the block layout that will have broken that alignment for individual columns (e.g. the Bitmap column)? If yes, is that documented somewhere?

And if `ByteSlice` is needed by the writer, the block cache is irrelevant, yes?
___
*[`sstable/colblk/column.go` line 61 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1IaHcyD2jSjkEV22nZ:-O1IaHcyD2jSjkEV22n_:bde75hg) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/column.go#L61)):*
> ```Go
> func (t DataType) uintWidth() uint32 {
> 	if t >= DataTypeUint8 && t <= DataTypeUint64 {
> 		return 1 << (t - DataTypeUint8)
> ```

can you add an assertion that this is <= 8.
___
*[`sstable/colblk/column.go` line 121 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1IazN80te1tzdhw3IW:-O1IazN80te1tzdhw3IX:b2463d7) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/column.go#L121)):*
> ```Go
> 	// EncodingDefault indicates that the default encoding is in-use for a
> 	// column, encoding n values for n rows.
> 	EncodingDefault ColumnEncoding = 0
> ```

What does "default encoding" mean when bits 0-3 are used to represent these other things?
It seems to me that that `ColumnDesc` has a 1 byte data type and a 1 byte encoding. The interpretation of the encoding byte is dependent on the data type. Some data types may have only one encoding so the encoding byte would be 0.
If this is correct, should there be a code comment stating that these DeltaEncoding bits are only for `DataTypeUint*`?

(flushing since we had a longer in-person discussion about this)
___
*[`sstable/colblk/uints.go` line 203 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1IZFaL9sW4uplY-Gw7:-O1IZFaL9sW4uplY-Gw8:b-fxp59b) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L203)):*
> ```Go
> }
> 
> func (b *UintBuilder[T]) Finish(col, rows int, offset uint32, buf []byte) (uint32, ColumnDesc) {
> ```

is there an alignment requirement on buf here?


<!-- Sent from Reviewable.io -->

2024-07-08 19:59 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731)* status: 3 of 9 files reviewed, 12 unresolved discussions (waiting on @aadityasondhi, @jbowens, @petermattis, and @RaduBerinde)

___
*[`sstable/colblk/uints.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1Io12h5t6BM1w7vmEZ:-O1Io12h5t6BM1w7vmE_:b-naqdlm) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L54)):*
> ```Go
> 	//
> 	// Any call to Size or Finish that supplies [rows] that's inclusive of the
> 	// index stored in minMaxRow may use the stored width. Calls with fewer
> ```

what is `minMaxRow`?
___
*[`sstable/colblk/uints.go` line 55 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1IoBhD66gm1eQlenNq:-O1IoBhD66gm1eQlenNr:btxtx28) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L55)):*
> ```Go
> 	// Any call to Size or Finish that supplies [rows] that's inclusive of the
> 	// index stored in minMaxRow may use the stored width. Calls with fewer
> 	// [rows] must recompute the min/max. In expected usage, only Finish will be
> ```

regarding "expected usage", is there a code simplification if we only supported this usage?
For instance we would only need to store widthWithLastTwoRows [2]uint32, and no recomputation.
___
*[`sstable/colblk/uints.go` line 80 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1IpNP_CYbUK8mtcwu9:-O1IpNP_CYbUK8mtcwuA:b-czh3xp) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L80)):*
> ```Go
> // assumed to be the provided default value. For the purpose of determining
> // whether a delta encoding is possible, the column is assumed to contain at
> // least 1 default value.
> ```

do we need a default that is not 0?
If there is no default `init(false, ...)`, are rows that are not set equal to NULL?

If we follow the rough guideline of our in-person discussion the default would be the zero-value for the type and there would be no distinction between absence (NULL) and the zero-value in the encoding.
___
*[`sstable/colblk/uints.go` line 118 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1Ir2Nk-kx_jQ_tmMI2:-O1Ir2Nk-kx_jQ_tmMI3:b3x3jgu) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L118)):*
> ```Go
> 		}
> 	} else {
> 		b.delta.minimum = T(0) - 1
> ```

we are subtracting 1 from uint(0), so won't it wrap around to the max value?


<!-- Sent from Reviewable.io -->

2024-07-08 22:23 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731)* status: 1 of 11 files reviewed, 11 unresolved discussions (waiting on @aadityasondhi, @petermattis, @RaduBerinde, and @sumeerbhola)

___
*[`internal/aligned/aligned.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0t_PgK3Zl1GusBPkZX:-O1JLki81eOabEq83DVB:b6wlf63) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/internal/aligned/aligned.go#L16)):*
Updated this to do the cast

> Is the idea here that if the block start is word aligned, there is nothing in the block layout that will have broken that alignment for individual columns (e.g. the Bitmap column)? If yes, is that documented somewhere?

Yeah, expanded the `ColumnWriter.Finish` comment with this and added it to the beginning of a doc comment describing the overarching block format

> And if `ByteSlice` is needed by the writer, the block cache is irrelevant, yes?

Yeah, that's true
___
*[`sstable/colblk/column.go` line 61 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1IaHcyD2jSjkEV22nZ:-O1JAMAuETW8zWME2Ay-:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/column.go#L61)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add an assertion that this is <= 8.
</blockquote></details>

Done.
___
*[`sstable/colblk/uints.go` line 118 at r4](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0ybrbK4LWE1Xh9_syQ:-O1JC6ddDqSbDyDgW6rP:bb6un1j) ([raw file](https://github.com/cockroachdb/pebble/blob/01493604e56e69ce1ad93f8cf7c9179c8d760af8/sstable/colblk/uints.go#L118)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] It would be good to mention that in a comment here, e.g.
`// We could reset all values as a precaution, but it has a visible cost in benchmarks.`
</blockquote></details>

Done
___
*[`sstable/colblk/uints.go` line 54 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1Io12h5t6BM1w7vmEZ:-O1JAouV9KiJBCAnmxt2:b4h0aoo) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L54)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what is `minMaxRow`?
</blockquote></details>

oops, fixed
___
*[`sstable/colblk/uints.go` line 80 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1IpNP_CYbUK8mtcwu9:-O1JK1wV32iC-c_s_PAs:bu8m2nh) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L80)):*
updated to remove support for configuring the default value. 

> If there is no default `init(false, ...)`, are rows that are not set equal to NULL?

it's undefined (eg, the caller is required to set all values)
___
*[`sstable/colblk/uints.go` line 118 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1Ir2Nk-kx_jQ_tmMI2:-O1JCB2c79Mqe8V9CFgh:bx20sab) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L118)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we are subtracting 1 from uint(0), so won't it wrap around to the max value?
</blockquote></details>

Yeah, to initialize the minimum to the max representable value. Added a comment
___
*[`sstable/colblk/uints.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1Hzk507Ej964sGQPm6:-O1JCZzY4HWVKbTBZMZu:b-th2zke) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L143)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] we could `copy` into `newDataTyped` (and set defaultValue) directly, before creating newElems. Same thing, just a bit more readable
</blockquote></details>

good call, done
___
*[`sstable/colblk/uints.go` line 203 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1IZFaL9sW4uplY-Gw7:-O1JL0_AAZybWu5VPhKE:b-padq1j) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L203)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there an alignment requirement on buf here?
</blockquote></details>

yeah, added this to the `ColumnWriter.Finish` comment
___
*[`sstable/colblk/unsafe_slice.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O0tzbLGELB4_yfvgJwS:-O1JCqcl6Jtj-sfdFIX2:b-dwozp5) ([raw file](https://github.com/cockroachdb/pebble/blob/6c4ba4396cf3f891e8f58a6e0bfdecdfbb17d571/sstable/colblk/unsafe_slice.go#L81)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Sorry, I mean treat it as a uint64 slice in all cases. On x86 even that's not necessary, I believe we could just do
```
T(*(*uint64)(unsafe.Pointer(uintptr(s.deltaPtr) + uintptr(i) << deltaWidthShift)))
```

Anyway, maybe just leave a TODO for now to experiment with other implementations.
</blockquote></details>

Added the TODO!


<!-- Sent from Reviewable.io -->

2024-07-09 00:40 UTC, sumeerbhola requested changes
> Reviewed 4 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731)* status: 5 of 11 files reviewed, 14 unresolved discussions (waiting on @aadityasondhi, @jbowens, @petermattis, and @RaduBerinde)

___
*[`sstable/colblk/column.go` line 61 at r6](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1JrsT8AuW18Bczgns_:-O1JrsT8AuW18Bczgnsa:b-3ownw1) ([raw file](https://github.com/cockroachdb/pebble/blob/bd78301679ed6e4d1a7a87c90399be668123c696/sstable/colblk/column.go#L61)):*
> ```Go
> func (t DataType) uintWidth() uint32 {
> 	if t >= DataTypeUint8 && t <= DataTypeUint64 {
> 		v := t - DataTypeUint8
> ```

DataTypeUint64 - DataTypeUint8 is currently 3, so the if-condition for the panic seems weak.
___
*[`sstable/colblk/column.go` line 201 at r6](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1Jt4ce2FbPBWm3xEeO:-O1Jt4ce2FbPBWm3xEeP:bvfn3w1) ([raw file](https://github.com/cockroachdb/pebble/blob/bd78301679ed6e4d1a7a87c90399be668123c696/sstable/colblk/column.go#L201)):*
> ```Go
> 	Encoder
> 	// NumColumns returns the number of columns the ColumnWriter will encode.
> 	NumColumns() int
> ```

(copying a question over from https://github.com/cockroachdb/pebble/pull/3711#pullrequestreview-2157202836)
if this is a writer for a single column, why would it ever return a value other than 1?
___
*[`sstable/colblk/uints.go` line 79 at r6](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1JtydKA7FA6OJE4oU8:-O1JtydKA7FA6OJE4oU9:by7teru) ([raw file](https://github.com/cockroachdb/pebble/blob/bd78301679ed6e4d1a7a87c90399be668123c696/sstable/colblk/uints.go#L79)):*
> ```Go
> // set are assumed to be zero. For the purpose of determining whether a delta
> // encoding is possible, the column is assumed to contain at least 1 default
> // value.
> ```

The last sentence "... the column is assumed ..." is unclear to me. Why does it matter whether there is a value with the default in this column?
Oh, I see -- it seems an optimization to set an ok-ish value of min and max, and not a correctness requirements. If we don't make this assumption we need to know if there were some skipped row indices in `Set`. Is my understanding correct?

Is there a reason why we don't require monotonically increasing `row` values in `Set`. That would allow us to know if there is a gap and deal with defaults more easily. It would eliminate the need to have a `useDefault` field -- if there is a gap, we would fill it in with defaults.


<!-- Sent from Reviewable.io -->

2024-07-09 16:00 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731)* status: 5 of 11 files reviewed, 14 unresolved discussions (waiting on @aadityasondhi, @petermattis, @RaduBerinde, and @sumeerbhola)

___
*[`sstable/colblk/column.go` line 61 at r6](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1JrsT8AuW18Bczgns_:-O1N84XF0fNEwU-Ldd9v:bvks2q5) ([raw file](https://github.com/cockroachdb/pebble/blob/bd78301679ed6e4d1a7a87c90399be668123c696/sstable/colblk/column.go#L61)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

DataTypeUint64 - DataTypeUint8 is currently 3, so the if-condition for the panic seems weak.
</blockquote></details>

what did you have in mind for the assertion?

https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1IaHcyD2jSjkEV22nZ
___
*[`sstable/colblk/column.go` line 201 at r6](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1Jt4ce2FbPBWm3xEeO:-O1N9QRa086uD5Fnif8H:b-7l5ui2) ([raw file](https://github.com/cockroachdb/pebble/blob/bd78301679ed6e4d1a7a87c90399be668123c696/sstable/colblk/column.go#L201)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

(copying a question over from https://github.com/cockroachdb/pebble/pull/3711#pullrequestreview-2157202836)
if this is a writer for a single column, why would it ever return a value other than 1?
</blockquote></details>

It doesn't necessarily write a single column. Specifically the `KeyWriter` interface will implement ColumnWriter. `KeyWriter` is defined by the application and encodes user keys in a user-defined schema
___
*[`sstable/colblk/uints.go` line 55 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1IoBhD66gm1eQlenNq:-O1ND-Hp8SMxeiO8Bxwx:b-lszzgz) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L55)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

regarding "expected usage", is there a code simplification if we only supported this usage?
For instance we would only need to store widthWithLastTwoRows [2]uint32, and no recomputation.
</blockquote></details>

Expanded the TODO below; I've been trying to avoid that subtlety in the API, but it may be net cleaner that way
___
*[`sstable/colblk/uints.go` line 79 at r6](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1JtydKA7FA6OJE4oU8:-O1NCMdt1fMjcAphxdzk:b-ykcfiy) ([raw file](https://github.com/cockroachdb/pebble/blob/bd78301679ed6e4d1a7a87c90399be668123c696/sstable/colblk/uints.go#L79)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The last sentence "... the column is assumed ..." is unclear to me. Why does it matter whether there is a value with the default in this column?
Oh, I see -- it seems an optimization to set an ok-ish value of min and max, and not a correctness requirements. If we don't make this assumption we need to know if there were some skipped row indices in `Set`. Is my understanding correct?

Is there a reason why we don't require monotonically increasing `row` values in `Set`. That would allow us to know if there is a gap and deal with defaults more easily. It would eliminate the need to have a `useDefault` field -- if there is a gap, we would fill it in with defaults.
</blockquote></details>

Yeah, when I was working on getting down the block-building overhead, avoiding the per-column, per-row store was impactful to the benchmarks


<!-- Sent from Reviewable.io -->

2024-07-09 17:04 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731)* status: 4 of 11 files reviewed, 14 unresolved discussions (waiting on @aadityasondhi, @petermattis, @RaduBerinde, and @sumeerbhola)

___
*[`sstable/colblk/uints.go` line 55 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1IoBhD66gm1eQlenNq:-O1NRTv7AojSV3n9-iEx:b64s58v) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L55)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Expanded the TODO below; I've been trying to avoid that subtlety in the API, but it may be net cleaner that way
</blockquote></details>

Ah, now that we use this encoding for the offsets in RawBytes and the soon-to-be-added PrefixBytes, we have an instance of an expected usage that requires the more permissive contract. Adding a new row to PrefixBytes may result in +2 additional offsets (+1 for a new bundle prefix), so the PrefixBytes implementation of the more constrained contract would require a slightly more permissive contract from the UintBuilder.


<!-- Sent from Reviewable.io -->

2024-07-09 18:23 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731)* status: 4 of 11 files reviewed, 13 unresolved discussions (waiting on @aadityasondhi, @jbowens, @petermattis, and @sumeerbhola)

___
*[`sstable/colblk/uints.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1Hzk507Ej964sGQPm6:-O1NiCgr6SqdLmbD4Z3O:b-tw0wjx) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L143)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

good call, done
</blockquote></details>

We still need to do
```
if b.useDefault {
  for i := b.array.n; i < len(newDataTyped); i++ {
    newDataTyped[i] = b.defaultValue
  }
```


By the way, do we envision usage where the default value is not 0?


<!-- Sent from Reviewable.io -->

2024-07-09 18:35 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731)* status: 4 of 11 files reviewed, 13 unresolved discussions (waiting on @aadityasondhi, @petermattis, @RaduBerinde, and @sumeerbhola)

___
*[`sstable/colblk/uints.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1Hzk507Ej964sGQPm6:-O1Nlfhj2dkxbpDn6266:b-yalo24) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L143)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We still need to do
```
if b.useDefault {
  for i := b.array.n; i < len(newDataTyped); i++ {
    newDataTyped[i] = b.defaultValue
  }
```


By the way, do we envision usage where the default value is not 0?
</blockquote></details>

I already made the change where the default value is only zero (so we don't need to update the grown size)


<!-- Sent from Reviewable.io -->

2024-07-09 19:31 UTC, RaduBerinde reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731#-:-O1Nylf-EZw-Mlwr7xxl:bnfp4nl)* status: 4 of 11 files reviewed, 13 unresolved discussions (waiting on @aadityasondhi, @jbowens, @petermattis, and @sumeerbhola)

___
*[`sstable/colblk/uints.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1Hzk507Ej964sGQPm6:-O1Nyj4s8zgnBi3GdtQp:b-khgprv) ([raw file](https://github.com/cockroachdb/pebble/blob/51074522fa4d5605024c9f71596f16cba2e4cd5f/sstable/colblk/uints.go#L143)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I already made the change where the default value is only zero (so we don't need to update the grown size)
</blockquote></details>

Ah, missed that, great :thumbsup: 


<!-- Sent from Reviewable.io -->

2024-07-10 00:24 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 5 files at r2, 1 of 5 files at r4, 1 of 7 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731#-:-O1P0it-0T0YoxT0w1Mw:bg7igkv)* status: 9 of 11 files reviewed, 14 unresolved discussions (waiting on @aadityasondhi, @jbowens, @petermattis, and @RaduBerinde)

___
*[`sstable/colblk/column.go` line 61 at r6](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1JrsT8AuW18Bczgns_:-O1OxW8Z8Y9zycVsaWn0:bqr96n8) ([raw file](https://github.com/cockroachdb/pebble/blob/bd78301679ed6e4d1a7a87c90399be668123c696/sstable/colblk/column.go#L61)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

what did you have in mind for the assertion?

https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1IaHcyD2jSjkEV22nZ
</blockquote></details>

didn't meant to drag this on -- it was a just a minor opinion.
```
rv := 1 << (t - DataTypeUint8)
if rv > 8 {
  panic("width greater than 8 bytes")
}
return rv
```
___
*[`sstable/colblk/uints.go` line 79 at r6](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1JtydKA7FA6OJE4oU8:-O1OzcEz174PSVDEX12J:brr2yve) ([raw file](https://github.com/cockroachdb/pebble/blob/bd78301679ed6e4d1a7a87c90399be668123c696/sstable/colblk/uints.go#L79)):*
> avoiding the per-column, per-row store was impactful to the benchmarks

Ack. Possibly the tight loop that initializes to the default value has better cache locality. AFAIK, golang compiler does not auto-vectorize.
___
*[`sstable/colblk/uints.go` line 208 at r8](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1P0HUL1VcvszwRJ3yL:-O1P0HUL1VcvszwRJ3yM:b-weft8v) ([raw file](https://github.com/cockroachdb/pebble/blob/237b17894ea5ec0890f535c8952764510cc4e354/sstable/colblk/uints.go#L208)):*
> ```Go
> }
> 
> // Size implements ColumnWriter, serializing the column into offset [offset] of
> ```

nit: Finish implements ...


<!-- Sent from Reviewable.io -->

2024-07-10 15:37 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3731#-:-O1SHaYrDlEA1c9fNUyZ:bz5mair)* status: 7 of 11 files reviewed, 13 unresolved discussions (waiting on @aadityasondhi, @petermattis, @RaduBerinde, and @sumeerbhola)

___
*[`sstable/colblk/column.go` line 61 at r6](https://reviewable.io/reviews/cockroachdb/pebble/3731#-O1JrsT8AuW18Bczgns_:-O1SHUQ51rwMnfP0WBoa:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/bd78301679ed6e4d1a7a87c90399be668123c696/sstable/colblk/column.go#L61)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

didn't meant to drag this on -- it was a just a minor opinion.
```
rv := 1 << (t - DataTypeUint8)
if rv > 8 {
  panic("width greater than 8 bytes")
}
return rv
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-10 16:15 UTC, merged