sstable: genericize sstable iterators by data block iterator
cockroachdb/pebble pull request #3834
Opened 2024-08-10 16:51 UTC by jbowens

In preparation for columnar blocks, this commit introduces type parameters to the {single,two}LevelIterator types. Parameterizing the sstable iterator ensures we pay the cost of dynamic dispatch only when entering the sstable iterator (as we do today) and ensures the compiler is able to inline data block iterator methods where relevant.

In order to continue to allocate the data block iterator struct within the single-level iterator, this commit introduces two type paramters: one for the non-pointer iterator type, and one for the pointer type on which iteration methods are defined. This adds some slightly cumbersome ergonomics to data block iterator usage sites.

2024-08-10 16:51 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/3834)
<!-- Reviewable:end -->

2024-08-12 14:41 UTC, sumeerbhola requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3834)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`sstable/reader_iter_single_lvl.go` line 249 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3834#-O46-ehX0LlZDbPyd5oj:-O46-ehX0LlZDbPyd5ok:bjk6maw) ([raw file](https://github.com/cockroachdb/pebble/blob/9759e901e6ecc9c2916739309e6706b5649ab5f6/sstable/reader_iter_single_lvl.go#L249)):*
> ```Go
> 				stats:  stats,
> 			}
> 			(&i.data).SetGetLazyValue(i.vbReader.getLazyValueForPrefixAndValueHandle)
> ```

I must have missed this `SetGetLazyValue` change. This is probably an allocation, for the closure. Can you check? If an interface was used we would avoid that allocation.

Also, I am confused why this compiles -- how is *D implementing `SetGetLazyValue`? 
___
*[`sstable/reader_iter_single_lvl.go` line 472 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3834#-O460f3iBpk40753iZUt:-O460f3iBpk40753iZUu:b-ynhspx) ([raw file](https://github.com/cockroachdb/pebble/blob/9759e901e6ecc9c2916739309e6706b5649ab5f6/sstable/reader_iter_single_lvl.go#L472)):*
> ```Go
> 		// Ensure the data block iterator is invalidated even if loading of the block
> 		// fails.
> 		PD(&i.data).Invalidate()
> ```

How about also adding a `PD` member to `singleLevelIterator` when initializing, and avoiding all these casts, given many of these are on the critical performance path.


<!-- Sent from Reviewable.io -->

2024-08-12 15:26 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3834)* status: all files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`sstable/reader_iter_single_lvl.go` line 249 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3834#-O46-ehX0LlZDbPyd5oj:-O463-dF6utEhVoogFNa:b1r1z0) ([raw file](https://github.com/cockroachdb/pebble/blob/9759e901e6ecc9c2916739309e6706b5649ab5f6/sstable/reader_iter_single_lvl.go#L249)):*
> I must have missed this `SetGetLazyValue` change. This is probably an allocation, for the closure. Can you check? If an interface was used we would avoid that allocation.

Good catch: https://github.com/cockroachdb/pebble/pull/3838

> Also, I am confused why this compiles -- how is \*D implementing `SetGetLazyValue`?

I think because `D` and `PD` have been substituted with concrete types up above, it knows `&i.data` is `*rowblik.Iter` which implement `SetGetLazyValue`.
___
*[`sstable/reader_iter_single_lvl.go` line 472 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3834#-O460f3iBpk40753iZUt:-O462B4J9N4VD93ge-iN:b4thhs6) ([raw file](https://github.com/cockroachdb/pebble/blob/9759e901e6ecc9c2916739309e6706b5649ab5f6/sstable/reader_iter_single_lvl.go#L472)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How about also adding a `PD` member to `singleLevelIterator` when initializing, and avoiding all these casts, given many of these are on the critical performance path.
</blockquote></details>

Shouldn't the casts be free since they're just changing the type of the pointer address? My mental model might be off, but I thought a `PD` member would force an extra load of the member, whereas `PD(&i.data)` would just be the pointer of `i` added with a fixed offset into the struct.


<!-- Sent from Reviewable.io -->

2024-08-12 18:04 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3834#-:-O46kpzPC0DNttRmrDOI:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens)

___
*[`sstable/reader_iter_single_lvl.go` line 472 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3834#-O460f3iBpk40753iZUt:-O46YwGp237cJ5Kn2ii0:b-fdsf8w) ([raw file](https://github.com/cockroachdb/pebble/blob/9759e901e6ecc9c2916739309e6706b5649ab5f6/sstable/reader_iter_single_lvl.go#L472)):*
My mental model here is average at best, but here is what I believe:

Type assertions to a concrete type are very cheap since it involves a simple pointer comparison between a known concrete type and the real type available in the interface struct.

But this is not that kind of type assertion. It seems akin to a type assertion to an interface (based on the description in https://research.swtch.com/interfaces). The runtime code knows the concrete type of `&i.data`, and needs to (a) confirm that it implements PD, (b) construct the (or find the already constructed) itable for the (interface type, concrete type) pair, so it can set the itable pointer in the PD interface struct.

I suppose it can do (b) first and if is in the cache the answer to (a) must be yes. Perhaps the assembly for this could shed some light.

> I thought a `PD` member would force an extra load of the member

Hmm, perhaps I should be thinking of loads. I simplistically assume everything is in a register.


<!-- Sent from Reviewable.io -->

2024-08-12 18:11 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3834)* status: all files reviewed, 2 unresolved discussions (waiting on @sumeerbhola)

___
*[`sstable/reader_iter_single_lvl.go` line 472 at r1](https://reviewable.io/reviews/cockroachdb/pebble/3834#-O460f3iBpk40753iZUt:-O46lYgHBrYfsCJmNpuW:b-4ul6s8) ([raw file](https://github.com/cockroachdb/pebble/blob/9759e901e6ecc9c2916739309e6706b5649ab5f6/sstable/reader_iter_single_lvl.go#L472)):*
> Type assertions to a concrete type are very cheap since it involves a simple pointer comparison between a known concrete type and the real type available in the interface struct.

So I don't really know what I'm talking about, but since this is using generics I assumed at code generation time these _are_ both statically-known concrete types. I'll futz around with generating the assembly of a simplified example to see if I can parse what it's doing.


<!-- Sent from Reviewable.io -->

2024-08-13 15:25 UTC, jbowens commented
I'm struggling to parse the assembly, but the light purple is the assembly for a function call using PD(&i.data)

<img width="516" alt="Screenshot 2024-08-13 at 11 21 27 AM" src="https://github.com/user-attachments/assets/9e6fb733-1201-4b67-967b-852a34d9b91e">

and then here the light purple is the assembly for a function call using an explicit `PD` member:

<img width="495" alt="Screenshot 2024-08-13 at 11 21 08 AM" src="https://github.com/user-attachments/assets/6d52275f-84f7-4bdf-b4dd-a8e8fb041da1">

looks like there is an extra MOVQ instruction

2024-08-13 15:26 UTC, jbowens commented
TFTR!

2024-08-13 15:28 UTC, merged

2024-08-13 17:55 UTC, RaduBerinde commented
*[`sstable/block/block.go` line 115 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3834#-O4Bs0b4Ab1vatoLB1HQ:-O4Bs0b58X3AHkJFxtNw:byqjsjp) ([raw file](https://github.com/cockroachdb/pebble/blob/3ff865b4153a4d33f79ea6ad8471b67567038e3c/sstable/block/block.go#L115)):*
> ```Go
> 	// while initializing the containing struct, eg::
> 	//   iter = sstableIter{dataBlockIter: iter.dataBlockIter.ResetForReuse()}
> 	ResetForReuse() D
> ```

Is this the only reason for having the `D` parameter? Can't this be a `Reset()` function that mutates the object?


<!-- Sent from Reviewable.io -->

2024-08-13 19:01 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3834)* status: 6 of 10 files reviewed, 3 unresolved discussions

___
*[`sstable/block/block.go` line 115 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3834#-O4Bs0b4Ab1vatoLB1HQ:-O4C6HGu8JTcuGpURQe_:bw7d69z) ([raw file](https://github.com/cockroachdb/pebble/blob/3ff865b4153a4d33f79ea6ad8471b67567038e3c/sstable/block/block.go#L115)):*
> Is this the only reason for having the `D` parameter?

No, the `*D` down below is the reason for it. It allows us to allocate the block iterator with the single-level iterator, even though the pointer type is the one that implements the iterator interface.


<!-- Sent from Reviewable.io -->

2024-08-13 19:21 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3834)* status: 6 of 10 files reviewed, 3 unresolved discussions

___
*[`sstable/block/block.go` line 115 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3834#-O4Bs0b4Ab1vatoLB1HQ:-O4CAXKm5ZZD-iU82_ql:b-6gq9to) ([raw file](https://github.com/cockroachdb/pebble/blob/3ff865b4153a4d33f79ea6ad8471b67567038e3c/sstable/block/block.go#L115)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> Is this the only reason for having the `D` parameter?

No, the `*D` down below is the reason for it. It allows us to allocate the block iterator with the single-level iterator, even though the pointer type is the one that implements the iterator interface.
</blockquote></details>

:exploding_head:


<!-- Sent from Reviewable.io -->

2024-08-13 19:52 UTC, RaduBerinde commented
*[`sstable/block/block.go` line 115 at r2](https://reviewable.io/reviews/cockroachdb/pebble/3834#-O4Bs0b4Ab1vatoLB1HQ:-O4CHldIETZTAxitbZhE:b147hnx) ([raw file](https://github.com/cockroachdb/pebble/blob/3ff865b4153a4d33f79ea6ad8471b67567038e3c/sstable/block/block.go#L115)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

:exploding_head:
</blockquote></details>

It would be nice if we could have a type constraint like `[D | *D DataBlockIterator]`


<!-- Sent from Reviewable.io -->