db: prevent conflicting, concurrent L0->LBase compactions
cockroachdb/pebble pull request #885
Opened 2020-09-09 14:37 UTC by jbowens

Previously, it was possible for compaction picking to pick an L0->LBase
compaction that conflicted with an existing L0->LBase compaction under
specific conditions.

A flush of a new sstable constructs a new Version and sublevel
intervals. If a flushed table does not overlap any individual
currently-compacting files, its intervals within sublevels
datastructures are not marked as compacting, although the flushed table
may still overlap with the active compaction's key range (eg, if the new
sstable sits squarely between two compacting files' keyspaces). If no
files exist in LBase that intersect with the intersection of the newly
flushed sstable's keyspace and the active compaction's keyspace, a
new compaction of the flush sstable would be allowed to start.

This change augments our existing concurrent compaction failsafe to
compare picked L0->LBase compaction key ranges against the key ranges of
in-progress compactions, preventing the compaction if necessary.

I think we'll probably want to also adapt L0 sublevels to avoid picking
these base compactions earlier through passing active compactions into
InitCompactingFileInfo, but adding this to the failsafe also patches the
non-sublevels codepaths and will provide defense in depth once we fix
L0-sublevel picking.

Fix #875.

2020-09-09 14:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/885)
<!-- Reviewable:end -->

2020-09-09 16:20 UTC, itsbilal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> great catch, thanks for digging into this!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885#-:-MGncj7P8hW3GIA82JPa:bncfzfr)* status: all files reviewed, 1 unresolved discussion (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction_picker.go, line 1346 at r1](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGncoqGAItLUFEqMKyM:-MGncoqGAItLUFEqMKyN:b-ssnb8b) ([raw file](https://github.com/cockroachdb/pebble/blob/6dedcfea7448e74cdf399abbfa39eb49dfe13f2f/compaction_picker.go#L1346)):*
> ```Go
> 	//
> 	//   a b c d e f g h i j k l m n o p q r s t u v w x y z
> 	if pc.startLevel.level == 0 && pc.outputLevel != nil && pc.outputLevel.level != 0 {
> ```

While this works as a good place to short circuit a compaction, there's another place where we can choose to not pick a conflicting compaction to begin with: right in `PickBaseCompaction` after the call to `baseCompactionUsingSeed`. Instead of just checking if the seed interval has `!isBaseCompacting`, we'd need to check if all the intervals the seed file spans has `!isBaseCompacting`. We already do a similar check for all overlapped LBase files, we'd just need to do the same for all L0 sublevel intervals. We'd also have to make a similar change in `L0Sublevels.extendFiles`.

That said, I'm okay with this change as-is as it's a quick fix for a fairly serious bug, we can always do it the more efficient way in the future. Would be good if we had an issue to track this.


<!-- Sent from Reviewable.io -->

2020-09-09 17:03 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens and @petermattis)

___
*[compaction_picker.go, line 1341 at r1](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGnmxMG56TwQKcl-AoP:-MGnmxMG56TwQKcl-AoQ:b-11g2rl) ([raw file](https://github.com/cockroachdb/pebble/blob/6dedcfea7448e74cdf399abbfa39eb49dfe13f2f/compaction_picker.go#L1341)):*
> ```Go
> 	// L0
> 	//   ↦--------- X0 ----------↤
> 	//                       ↦------------ Y0 -------------↤
> ```

I didn't understand this example. One of the fileIntervals that Y0 is in is already `isBaseCompacting`. I need to reread `baseCompactionUsingSeed` to see if we just have a bug there.


<!-- Sent from Reviewable.io -->

2020-09-09 17:08 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: all files reviewed, 2 unresolved discussions (waiting on @jbowens and @petermattis)

___
*[compaction_picker.go, line 1341 at r1](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGnmxMG56TwQKcl-AoP:-MGnpS2F6bzru9-RUFp5:bjosiea) ([raw file](https://github.com/cockroachdb/pebble/blob/6dedcfea7448e74cdf399abbfa39eb49dfe13f2f/compaction_picker.go#L1341)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't understand this example. One of the fileIntervals that Y0 is in is already `isBaseCompacting`. I need to reread `baseCompactionUsingSeed` to see if we just have a bug there.
</blockquote></details>

hmm, I may be misinterpreting this diagram. Are smaller sublevels lower in this diagram? I guess not since Y0 can't have a smaller sublevel than X0 if it is flushed later.


<!-- Sent from Reviewable.io -->

2020-09-09 17:22 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: all files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[compaction_picker.go, line 1346 at r1](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGncoqGAItLUFEqMKyM:-MGns4ir9L7AuropvZa3:b-9btlcf) ([raw file](https://github.com/cockroachdb/pebble/blob/6dedcfea7448e74cdf399abbfa39eb49dfe13f2f/compaction_picker.go#L1346)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

While this works as a good place to short circuit a compaction, there's another place where we can choose to not pick a conflicting compaction to begin with: right in `PickBaseCompaction` after the call to `baseCompactionUsingSeed`. Instead of just checking if the seed interval has `!isBaseCompacting`, we'd need to check if all the intervals the seed file spans has `!isBaseCompacting`. We already do a similar check for all overlapped LBase files, we'd just need to do the same for all L0 sublevel intervals. We'd also have to make a similar change in `L0Sublevels.extendFiles`.

That said, I'm okay with this change as-is as it's a quick fix for a fairly serious bug, we can always do it the more efficient way in the future. Would be good if we had an issue to track this.
</blockquote></details>

If I understand the PR description correctly, the problem scenario is two existing files compacting, [a,b] and [f,g], and they are part of the same compaction. And then a new file is added to L0 [d,e]. We currently don't know in `L0Sublevels.InitCompactingFileInfo()` that these two files are part of the same compaction. If we passed in the existing compaction bounds from `DB.mu.compact.inProgress` we could mark all fileIntervals that overlapped with a compaction as compacting.


<!-- Sent from Reviewable.io -->

2020-09-09 17:22 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: all files reviewed, 2 unresolved discussions (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[compaction_picker.go, line 1341 at r1](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGnmxMG56TwQKcl-AoP:-MGnqJHd2bMi2Lx895cA:bq82og2) ([raw file](https://github.com/cockroachdb/pebble/blob/6dedcfea7448e74cdf399abbfa39eb49dfe13f2f/compaction_picker.go#L1341)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

hmm, I may be misinterpreting this diagram. Are smaller sublevels lower in this diagram? I guess not since Y0 can't have a smaller sublevel than X0 if it is flushed later.
</blockquote></details>

Sorry, I probably should've used a diagram for a compaction that can be generated from the sublevel compaction picking here. This diagram was intended to demonstrate an example of why checking just `Compacting` for input files is insufficient as a failsafe against concurrent L0->LBase compaction conflicts. I think the compaction conflict demonstrated in this diagram is only possible without sublevels enabled.

The test case in this PR however is an example of a conflicting compaction that _is_ generated by sublevels base compaction picking:  https://github.com/cockroachdb/pebble/blob/6dedcfea7448e74cdf399abbfa39eb49dfe13f2f/testdata/compaction_picker_L0#L263-L282

AFAICT, it's not possible for sublevels to generally detect the type of conflict outlined in that test case without knowing which L0 files are a part of the same base compaction. If you have the files `[a b c] d e f [g h i]` within one sublevel and with the bracketed files in an active compaction, there's no way of knowing whether or not the bracketed files are in _same_ compaction that will output an sstable with keyrange a-i or two separate compactions that will output separate sstables with key ranges a-c and g-i. The distinction matters for determining whether or not it's safe to base compact `d e f` if there are no Lbase files in the range d-f.


<!-- Sent from Reviewable.io -->

2020-09-09 17:25 UTC, itsbilal commented
___
*[compaction_picker.go, line 1346 at r1](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGncoqGAItLUFEqMKyM:-MGntBIr7D3yTWlrMmS0:b-fl7zrf) ([raw file](https://github.com/cockroachdb/pebble/blob/6dedcfea7448e74cdf399abbfa39eb49dfe13f2f/compaction_picker.go#L1346)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If I understand the PR description correctly, the problem scenario is two existing files compacting, [a,b] and [f,g], and they are part of the same compaction. And then a new file is added to L0 [d,e]. We currently don't know in `L0Sublevels.InitCompactingFileInfo()` that these two files are part of the same compaction. If we passed in the existing compaction bounds from `DB.mu.compact.inProgress` we could mark all fileIntervals that overlapped with a compaction as compacting.
</blockquote></details>

My interpretation of the diagram was that if `[a,d]` is base compacting and and `[c,f]`comes in, we can still choose the `[d,f]`interval as a seed interval for a new base compaction, pick the `[c,f]` file (as it's not compacting), and never realize that that file has an interval with `isBaseCompacting = true`. Reading the `PickBaseCompaction` code paths with that in mind confirms that this bug is possible.

It doesn't seem to be a concurrency / "we haven't called InitCompactingFileInfo yet" bug. Just an oversight in base compaction picking.


<!-- Sent from Reviewable.io -->

2020-09-09 17:28 UTC, itsbilal commented
___
*[compaction_picker.go, line 1346 at r1](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGncoqGAItLUFEqMKyM:-MGnu4J-EKv0sZ5p639T:b-5mqv0u) ([raw file](https://github.com/cockroachdb/pebble/blob/6dedcfea7448e74cdf399abbfa39eb49dfe13f2f/compaction_picker.go#L1346)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

My interpretation of the diagram was that if `[a,d]` is base compacting and and `[c,f]`comes in, we can still choose the `[d,f]`interval as a seed interval for a new base compaction, pick the `[c,f]` file (as it's not compacting), and never realize that that file has an interval with `isBaseCompacting = true`. Reading the `PickBaseCompaction` code paths with that in mind confirms that this bug is possible.

It doesn't seem to be a concurrency / "we haven't called InitCompactingFileInfo yet" bug. Just an oversight in base compaction picking.
</blockquote></details>

Actually, nevermind, that isn't possible because the latter compaction would choose the former file due to the base compaction invariant on older overlapping files. 


<!-- Sent from Reviewable.io -->

2020-09-09 17:31 UTC, itsbilal commented
___
*[compaction_picker.go, line 1341 at r1](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGnmxMG56TwQKcl-AoP:-MGnufuO8x80fWLMGl4Q:b-iadye7) ([raw file](https://github.com/cockroachdb/pebble/blob/6dedcfea7448e74cdf399abbfa39eb49dfe13f2f/compaction_picker.go#L1341)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Sorry, I probably should've used a diagram for a compaction that can be generated from the sublevel compaction picking here. This diagram was intended to demonstrate an example of why checking just `Compacting` for input files is insufficient as a failsafe against concurrent L0->LBase compaction conflicts. I think the compaction conflict demonstrated in this diagram is only possible without sublevels enabled.

The test case in this PR however is an example of a conflicting compaction that _is_ generated by sublevels base compaction picking:  https://github.com/cockroachdb/pebble/blob/6dedcfea7448e74cdf399abbfa39eb49dfe13f2f/testdata/compaction_picker_L0#L263-L282

AFAICT, it's not possible for sublevels to generally detect the type of conflict outlined in that test case without knowing which L0 files are a part of the same base compaction. If you have the files `[a b c] d e f [g h i]` within one sublevel and with the bracketed files in an active compaction, there's no way of knowing whether or not the bracketed files are in _same_ compaction that will output an sstable with keyrange a-i or two separate compactions that will output separate sstables with key ranges a-c and g-i. The distinction matters for determining whether or not it's safe to base compact `d e f` if there are no Lbase files in the range d-f.
</blockquote></details>

Yeah the diagram confused me too - as I guessed that was the more authoritative example than the test. Might be a good idea to emulate the test case (plus a comment in line with what you've written here) in place of the diagram.


<!-- Sent from Reviewable.io -->

2020-09-09 17:40 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: all files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction_picker.go, line 1341 at r1](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGnmxMG56TwQKcl-AoP:-MGnude-A-T9jc2J5a9Y:b-ovyxgi) ([raw file](https://github.com/cockroachdb/pebble/blob/6dedcfea7448e74cdf399abbfa39eb49dfe13f2f/compaction_picker.go#L1341)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yeah the diagram confused me too - as I guessed that was the more authoritative example than the test. Might be a good idea to emulate the test case (plus a comment in line with what you've written here) in place of the diagram.
</blockquote></details>

That's what I suspected in my response to Bilal's comment below. I have a preference to fixing this in `L0Sublevels` since that is where we maintain sophisticated logic for L0 compactions -- adding this to compaction_picker seems like a bolt-on fix.

Also, I am wondering why both these L1 files became part of the same compaction. The initial picking in `L0Sublevels` should not have caused that. Is there something that I am overlooking in `pickedCompaction.setupInputs` that is causing this extension (the logic there with `baseIter` doesn't look like it could cause this)?


<!-- Sent from Reviewable.io -->

2020-09-09 22:45 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[compaction_picker.go, line 1341 at r1](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGnmxMG56TwQKcl-AoP:-MGp-k2DCs5fv9k3tX9b:b-32d9wy) ([raw file](https://github.com/cockroachdb/pebble/blob/6dedcfea7448e74cdf399abbfa39eb49dfe13f2f/compaction_picker.go#L1341)):*
> I have a preference to fixing this in L0Sublevels since that is where we maintain sophisticated logic for L0 compactions -- adding this to compaction_picker seems like a bolt-on fix.

Adding a fix to L0Sublevels sounds good to me, but I think this problem also exists without L0Sublevels enabled. This function `inputAlreadyCompacting` is used as a 'failsafe' to prevent conflicting compactions, and I think it makes sense to extend it to ensure safety of base compactions too. I'll look into that L0Sublevels fix.

> Also, I am wondering why both these L1 files became part of the same compaction. The initial picking in L0Sublevels should not have caused that. Is there something that I am overlooking in pickedCompaction.setupInputs that is causing this extension (the logic there with baseIter doesn't look like it could cause this)?

Why shouldn't they become part of the same compaction?


<!-- Sent from Reviewable.io -->

2020-09-10 13:44 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction_picker.go, line 1341 at r1](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGnmxMG56TwQKcl-AoP:-MGsDw2e1Cf0F3NOaAzV:b-khxl05) ([raw file](https://github.com/cockroachdb/pebble/blob/6dedcfea7448e74cdf399abbfa39eb49dfe13f2f/compaction_picker.go#L1341)):*
> Why shouldn't they become part of the same compaction?

I may be misremembering, but I thought all our code widened a compaction in its key span only if forced to due to the need to maintain a correctness invariant. Once the key span is widened due to a correctness invariant it may of course add more files to improve write amplification. In this scenario, the two L0 files are not overlapping and their corresponding L1 files are such that including one does not widen L0. I am curious if we have an unintended "performance bug" elsewhere.


<!-- Sent from Reviewable.io -->

2020-09-10 13:45 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[compaction_picker.go, line 1329 at r2](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGsBYV67rCK8AIbRUX8:-MGsBYV67rCK8AIbRUX9:b-97mrwt) ([raw file](https://github.com/cockroachdb/pebble/blob/c1f34a7b1d569c2916547bf39413add44a3b9ec9/compaction_picker.go#L1329)):*
> ```Go
> 	// input tables from both start and output levels are not already
> 	// compacting is sufficient, because tables in positive levels are
> 	// nonoverlapping and we always compact contiguous files.
> ```

I'm not understanding why the problem you describe below cannot occur for non-L0 compactions. 

```
L0
                         | 000200  |
L1
     | 000100  |                             | 000101  |
L2
     | 000001  |                             | 000002  |

     a b c d e f g h i j k l m n o p q r s t u v w x y z
```

If we compact L1 to L2 I don't see what prevents a concurrent move compaction of `000200` into L2 which seems like it could create exactly the same overlap problem. I feel like I must be missing something.
___
*[compaction_picker.go, line 1368 at r2](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGsFYta3a39ptzRlgdQ:-MGsFYta3a39ptzRlgdR:b-ofeh3j) ([raw file](https://github.com/cockroachdb/pebble/blob/c1f34a7b1d569c2916547bf39413add44a3b9ec9/compaction_picker.go#L1368)):*
> ```Go
> 					continue
> 				}
> 				sm, la := manifest.KeyRange(pc.cmp, info.files.Iter())
> ```

Perhaps we should add `smallest` and `largest` fields to `compactionInfo`. Those fields are already present in `compaction` which is what is used to create a `compactionInfo`.


<!-- Sent from Reviewable.io -->

2020-09-10 21:36 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction_picker.go, line 1329 at r2](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGsBYV67rCK8AIbRUX8:-MGtwdKsBAAEDGbGMlAh:bya0v07) ([raw file](https://github.com/cockroachdb/pebble/blob/c1f34a7b1d569c2916547bf39413add44a3b9ec9/compaction_picker.go#L1329)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not understanding why the problem you describe below cannot occur for non-L0 compactions. 

```
L0
                         | 000200  |
L1
     | 000100  |                             | 000101  |
L2
     | 000001  |                             | 000002  |

     a b c d e f g h i j k l m n o p q r s t u v w x y z
```

If we compact L1 to L2 I don't see what prevents a concurrent move compaction of `000200` into L2 which seems like it could create exactly the same overlap problem. I feel like I must be missing something.
</blockquote></details>

If you're missing something, I'm missing it too. I'll try to produce an additional test case with a non-L0 compaction.
___
*[compaction_picker.go, line 1368 at r2](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGsFYta3a39ptzRlgdQ:-MGtwa_O5Q-FJr9N_asq:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c1f34a7b1d569c2916547bf39413add44a3b9ec9/compaction_picker.go#L1368)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Perhaps we should add `smallest` and `largest` fields to `compactionInfo`. Those fields are already present in `compaction` which is what is used to create a `compactionInfo`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-10 23:30 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[compaction_picker.go, line 1329 at r2](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGsBYV67rCK8AIbRUX8:-MGuKoGo6HmXWbJgXc1L:bxl5l7n) ([raw file](https://github.com/cockroachdb/pebble/blob/c1f34a7b1d569c2916547bf39413add44a3b9ec9/compaction_picker.go#L1329)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

If you're missing something, I'm missing it too. I'll try to produce an additional test case with a non-L0 compaction.
</blockquote></details>

I suspect it is impossible to trigger the non-L0 case due to how we expand compactions:

```
// grow grows the number of inputs at c.level without changing the number of
// c.level+1 files in the compaction, and returns whether the inputs grew. sm
// and la are the smallest and largest InternalKeys in all of the inputs.
func (pc *pickedCompaction) grow(sm, la InternalKey) bool { ... }
```

If we were to ever change that logic then it seems possible to hit this bug.


<!-- Sent from Reviewable.io -->

2020-09-11 15:39 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: 1 of 9 files reviewed, 2 unresolved discussions (waiting on @itsbilal and @petermattis)

___
*[compaction_picker.go, line 1329 at r2](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGsBYV67rCK8AIbRUX8:-MGxmb9p1dcv2LNDhXJb:b-ayxgzm) ([raw file](https://github.com/cockroachdb/pebble/blob/c1f34a7b1d569c2916547bf39413add44a3b9ec9/compaction_picker.go#L1329)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I suspect it is impossible to trigger the non-L0 case due to how we expand compactions:

```
// grow grows the number of inputs at c.level without changing the number of
// c.level+1 files in the compaction, and returns whether the inputs grew. sm
// and la are the smallest and largest InternalKeys in all of the inputs.
func (pc *pickedCompaction) grow(sm, la InternalKey) bool { ... }
```

If we were to ever change that logic then it seems possible to hit this bug.
</blockquote></details>

Yeah, you're right. I think it may still be possible in the non-L0 case if the in-progress compaction was created as a manual compaction.

I added a new test case for this scenario in the non-L0 case.


<!-- Sent from Reviewable.io -->

2020-09-11 18:23 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[testdata/compaction_picker_concurrency, line 22 at r4](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGyO65pCLZP_YrsPRH-:-MGyO65pCLZP_YrsPRH0:b8usi1m) ([raw file](https://github.com/cockroachdb/pebble/blob/1c56d7d176d0173fc96f844c2cfbe3e2f9848c46/testdata/compaction_picker_concurrency#L22)):*
> ```
>   000010:a.SET.1-z.SET.2
> compactions
>   L1 000201 000202 -> L2 000101
> ```

This looks unnatural. How did we get a state where `000201` and `000202` are compacting , but `000203` is not part if the compaction? Is your thinking that `000203` was added to L1 after this compaction started? 

I wonder if this scenario could still be a problem if `000201` and `000202` where on L2 while `000203` was on L1. If `000203` were the seed for a compaction it could be moved to L2, and from their to L3 which would hit the conflict.


<!-- Sent from Reviewable.io -->

2020-09-11 19:41 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @itsbilal and @petermattis)

___
*[testdata/compaction_picker_concurrency, line 22 at r4](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGyO65pCLZP_YrsPRH-:-MGyaNna9auhWzGYbtAE:b3wfshf) ([raw file](https://github.com/cockroachdb/pebble/blob/1c56d7d176d0173fc96f844c2cfbe3e2f9848c46/testdata/compaction_picker_concurrency#L22)):*
> This looks unnatural. How did we get a state where 000201 and 000202 are compacting , but 000203 is not part if the compaction? Is your thinking that 000203 was added to L1 after this compaction started?

Yeah, exactly. I was thinking an L0->L1 compaction with multiple inputs could construct `000203` after a manual compaction already started compacting `000201` and `000202`.

> I wonder if this scenario could still be a problem if 000201 and 000202 where on L2 while 000203 was on L1. If 000203 were the seed for a compaction it could be moved to L2, and from their to L3 which would hit the conflict.

In this case L3 has base files spanning the breadth of the key space, which would prevent the conflict. Were you thinking if 000010 was in L4? I think a multi-level move like you describe can generally produce the conflict with a manual compaction.


<!-- Sent from Reviewable.io -->

2020-09-11 20:02 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[testdata/compaction_picker_concurrency, line 22 at r4](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGyO65pCLZP_YrsPRH-:-MGykJP7DLQyqhw5KbJI:b-tx6rnc) ([raw file](https://github.com/cockroachdb/pebble/blob/1c56d7d176d0173fc96f844c2cfbe3e2f9848c46/testdata/compaction_picker_concurrency#L22)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> This looks unnatural. How did we get a state where 000201 and 000202 are compacting , but 000203 is not part if the compaction? Is your thinking that 000203 was added to L1 after this compaction started?

Yeah, exactly. I was thinking an L0->L1 compaction with multiple inputs could construct `000203` after a manual compaction already started compacting `000201` and `000202`.

> I wonder if this scenario could still be a problem if 000201 and 000202 where on L2 while 000203 was on L1. If 000203 were the seed for a compaction it could be moved to L2, and from their to L3 which would hit the conflict.

In this case L3 has base files spanning the breadth of the key space, which would prevent the conflict. Were you thinking if 000010 was in L4? I think a multi-level move like you describe can generally produce the conflict with a manual compaction.

</blockquote></details>

I should have been more explicit. I was imagining all of the existing L1->L3 sstables to be shifted down one level so that `000203` could sit in L1 by itself. Perhaps it is sufficient to expand the commentary about the scenario you're testing here and how it could have come in to being.

Are the L0 sstables necessary for some reason? I don't understand what function they are performing.


<!-- Sent from Reviewable.io -->

2020-09-14 18:40 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @itsbilal and @petermattis)

___
*[testdata/compaction_picker_concurrency, line 22 at r4](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGyO65pCLZP_YrsPRH-:-MGzAQHe9rn8kbUlSsOJ:bi1nub2) ([raw file](https://github.com/cockroachdb/pebble/blob/1c56d7d176d0173fc96f844c2cfbe3e2f9848c46/testdata/compaction_picker_concurrency#L22)):*
> Are the L0 sstables necessary for some reason? I don't understand what function they are performing.

They were just to ensure that we allow additional compaction concurrency, since concurrency is now a function of L0 read amp. 


<!-- Sent from Reviewable.io -->

2020-09-14 18:41 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @itsbilal and @petermattis)

___
*[testdata/compaction_picker_concurrency, line 22 at r4](https://reviewable.io/reviews/cockroachdb/pebble/885#-MGyO65pCLZP_YrsPRH-:-MHCusJ1E_Kk5LeZid45:br4n7eh) ([raw file](https://github.com/cockroachdb/pebble/blob/1c56d7d176d0173fc96f844c2cfbe3e2f9848c46/testdata/compaction_picker_concurrency#L22)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

> Are the L0 sstables necessary for some reason? I don't understand what function they are performing.

They were just to ensure that we allow additional compaction concurrency, since concurrency is now a function of L0 read amp. 
</blockquote></details>

Added some additional commentary here.


<!-- Sent from Reviewable.io -->

2020-09-16 22:44 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885)* status: 1 of 9 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @petermattis)

___
*[internal/manifest/l0_sublevels.go, line 363 at r6](https://reviewable.io/reviews/cockroachdb/pebble/885#-MHO4f0lAUOJt2cfcKWF:-MHO4f0lAUOJt2cfcKWG:b7agok7) ([raw file](https://github.com/cockroachdb/pebble/blob/023a8070287dd55c6a65d9c7d4898a6cb1d16ff8/internal/manifest/l0_sublevels.go#L363)):*
> ```Go
> 	// compaction files straddle the input file. Mark these intervals as base
> 	// compacting.
> 	for _, c := range inProgress {
> ```

@itsbilal, @sumeerbhola does this look like an appropriate fix for the Sublevels base compaction picking part of the fix?


<!-- Sent from Reviewable.io -->

2020-09-21 16:45 UTC, itsbilal approved these changes
Sublevels part <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> save for some comments around edge cases where a compaction's largest key is the sentinel key.

> Reviewed 1 of 4 files at r3, 1 of 7 files at r5, 5 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885#-:-MHlYOPD8y1_3RN1zK38:bkflk7s)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 365 at r6](https://reviewable.io/reviews/cockroachdb/pebble/885#-MHlWZDH2SIHX28HOd4Z:-MHlWZDH2SIHX28HOd4_:by27xm9) ([raw file](https://github.com/cockroachdb/pebble/blob/023a8070287dd55c6a65d9c7d4898a6cb1d16ff8/internal/manifest/l0_sublevels.go#L365)):*
> ```Go
> 	for _, c := range inProgress {
> 		startIK := intervalKey{key: c.Smallest.UserKey, isLargest: false}
> 		endIK := intervalKey{key: c.Largest.UserKey, isLargest: true}
> ```

Having `isLargest: c.Largest.Trailer != InternalKeyRangeDelSentinel` would be slightly more optimal.
___
*[internal/manifest/l0_sublevels.go, line 370 at r6](https://reviewable.io/reviews/cockroachdb/pebble/885#-MHlY6d6BB7vOvRSSNA9:-MHlY6d6BB7vOvRSSNAA:bvrvq56) ([raw file](https://github.com/cockroachdb/pebble/blob/023a8070287dd55c6a65d9c7d4898a6cb1d16ff8/internal/manifest/l0_sublevels.go#L370)):*
> ```Go
> 		})
> 		end := sort.Search(len(s.orderedIntervals), func(i int) bool {
> 			return intervalKeyCompare(s.cmp, s.orderedIntervals[i].startKey, endIK) > 0
> ```

I think this should be >= 0, as `endIK` is exclusive. 


<!-- Sent from Reviewable.io -->

2020-09-22 16:40 UTC, jbowens reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/885#-:-MHqfsgV2tYNPuAkgt8e:bz5mair)* status: 7 of 9 files reviewed, 5 unresolved discussions (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[internal/manifest/l0_sublevels.go, line 365 at r6](https://reviewable.io/reviews/cockroachdb/pebble/885#-MHlWZDH2SIHX28HOd4Z:-MHqfoLP4elU6SaXeBh2:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/023a8070287dd55c6a65d9c7d4898a6cb1d16ff8/internal/manifest/l0_sublevels.go#L365)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Having `isLargest: c.Largest.Trailer != InternalKeyRangeDelSentinel` would be slightly more optimal.
</blockquote></details>

Done.
___
*[internal/manifest/l0_sublevels.go, line 370 at r6](https://reviewable.io/reviews/cockroachdb/pebble/885#-MHlY6d6BB7vOvRSSNA9:-MHqfnvV5W4XKTSygNCR:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/023a8070287dd55c6a65d9c7d4898a6cb1d16ff8/internal/manifest/l0_sublevels.go#L370)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I think this should be >= 0, as `endIK` is exclusive. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-22 20:54 UTC, merged