internal/manifest: use B-Tree for organizing level file metadata
cockroachdb/pebble pull request #939
Opened 2020-09-24 13:17 UTC by jbowens

Update the LevelMetadata, LevelSlice, LevelIterator types to be backed
by a B-Tree, allowing logarithmic applications of version edits.

2020-09-24 13:18 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/939)
<!-- Reviewable:end -->

2020-09-25 15:30 UTC, jbowens reviewed
Added a new commit https://github.com/cockroachdb/pebble/pull/939/commits/278b1284c5aa487ebcf921fd94e205dd0095059d that allows 'annotating' B-Tree nodes with arbitrary bookkeeping, and uses that functionality to remove the remaining two O(# sstables) operations. That gives us the 🆒  `BenchmarkManySSTablesNewVersion` numbers we were hoping for. Lemme know if it would be easier to review these commits in separate PRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939#-:-MI4s8a4-W2_LsqSG0vc:b-y8anqq)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @itsbilal and @petermattis)

___
*[internal/manifest/version_test.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/pebble/939#-MI-SSqc1iAwXk94yzmD:-MI-SSqc1iAwXk94yzmE:b-ish8qz) ([raw file](https://github.com/cockroachdb/pebble/blob/0de3d4ad6d605d1da534db2ff558c7781d3b1614/internal/manifest/version_test.go#L168)):*
> ```Go
> 		Size:     1,
> 		Smallest: base.ParseInternalKey("p.SET.7138"),
> 		Largest:  base.ParseInternalKey("u.SET.7139"),
> ```

Note that these changes to `TestOverlaps` and `TestContains` test data correct the file ordering, because `p.SET.7148` sorts before `p.SET.7138`.


<!-- Sent from Reviewable.io -->

2020-09-25 16:08 UTC, petermattis commented
Those sure are nice benchmark numbers. I guess computer science works.

2020-09-28 23:26 UTC, petermattis reviewed
This PR is a bit more involved than I was expecting. Which is fine, I just won't have time to scrutinize it until later this week.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939#-:-MILyurPAZR4tza3xcTR:b-xsn681)* status: 0 of 20 files reviewed, 5 unresolved discussions (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[compaction_picker.go, line 1141 at r3](https://reviewable.io/reviews/cockroachdb/pebble/939#-MIM13aW6lWZYs52zoI4:-MIM13aW6lWZYs52zoI5:b33ep9n) ([raw file](https://github.com/cockroachdb/pebble/blob/c226ed43b378f03eceb8c3058e6dcdb32afaf789/compaction_picker.go#L1141)):*
> ```Go
> 	}
> 	candidate := v.(*fileMetadata)
> 	if candidate == nil || candidate.Compacting || candidate.LargestSeqNum >= env.earliestSnapshotSeqNum {
> ```

Is this `candidate == nil` check necessary given that you checked `v == nil` a few lines up?
___
*[internal/manifest/btree.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/pebble/939#-MILwPtTB5BVNLqja4aa:-MILwPtTB5BVNLqja4ab:bq4ti6j) ([raw file](https://github.com/cockroachdb/pebble/blob/82a72c1759add35db38282e296705e90967da6c4/internal/manifest/btree.go#L25)):*
> ```Go
> }
> 
> func btreeCmpKeys(cmp Compare) btreeCmp {
> ```

Elsewhere we use the term `BySmallestKey`. For consistency, can we name this `btreeCmpSmallestKey`?
___
*[internal/manifest/btree.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/pebble/939#-MILwdl41j1448Vh2Zlu:-MILwdl41j1448Vh2Zlv:brtn8c1) ([raw file](https://github.com/cockroachdb/pebble/blob/82a72c1759add35db38282e296705e90967da6c4/internal/manifest/btree.go#L31)):*
> ```Go
> }
> 
> // btreeCmpSpecificOrder is used in tests to construct a B-Tree with a
> ```

Can the tests that require this be changed to use `btreeCmpSeqNum`, or perhaps a new `btreeCmpFileNum`? The `SpecificOrder` approach is certainly clever, but it wasn't at all clear to me when looking at the tests what it was doing until I read this code.
___
*[internal/manifest/level_metadata.go, line 87 at r3](https://reviewable.io/reviews/cockroachdb/pebble/939#-MIM-QFY2nRJxGq6apsT:-MIM-QFZD6JvOptWR5lw:bgfvgfn) ([raw file](https://github.com/cockroachdb/pebble/blob/c226ed43b378f03eceb8c3058e6dcdb32afaf789/internal/manifest/level_metadata.go#L87)):*
> ```Go
> // Annotator. The Annotator is used as the key for pre-calculated
> // values, so equal Annotators must be used to avoid duplicate computations
> // and cached annotations.
> ```

Can you add a comment about synchronization? Seems like this isn't safe for multiple goroutines to call concurrently if they end up updating a node's cached annotation info. 


<!-- Sent from Reviewable.io -->

2020-10-02 21:49 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939)* status: 0 of 20 files reviewed, 4 unresolved discussions (waiting on @itsbilal and @petermattis)

___
*[compaction_picker.go, line 1141 at r3](https://reviewable.io/reviews/cockroachdb/pebble/939#-MIM13aW6lWZYs52zoI4:-MIfFunQ82KvDhEUwKaj:bss4a2b) ([raw file](https://github.com/cockroachdb/pebble/blob/c226ed43b378f03eceb8c3058e6dcdb32afaf789/compaction_picker.go#L1141)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this `candidate == nil` check necessary given that you checked `v == nil` a few lines up?
</blockquote></details>

Removed.
___
*[internal/manifest/btree.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/pebble/939#-MILwPtTB5BVNLqja4aa:-MIfFu0ZAq649wXOe3XE:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/82a72c1759add35db38282e296705e90967da6c4/internal/manifest/btree.go#L25)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Elsewhere we use the term `BySmallestKey`. For consistency, can we name this `btreeCmpSmallestKey`?
</blockquote></details>

Done.
___
*[internal/manifest/btree.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/pebble/939#-MILwdl41j1448Vh2Zlu:-MIfG0v42b69SYNQYGTM:bx6l1re) ([raw file](https://github.com/cockroachdb/pebble/blob/82a72c1759add35db38282e296705e90967da6c4/internal/manifest/btree.go#L31)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can the tests that require this be changed to use `btreeCmpSeqNum`, or perhaps a new `btreeCmpFileNum`? The `SpecificOrder` approach is certainly clever, but it wasn't at all clear to me when looking at the tests what it was doing until I read this code.
</blockquote></details>

Yeah, agreed. Unfortunately, a lot of them structured dictating a specific state (eg, a specific L0 sublevels structure), often as a part of a data-driven test that's not easy to restructure for just the consistency checking command. I'll try to convert them, but I think some of them will just need to be split out/replaced by completely separate tests.
___
*[internal/manifest/level_metadata.go, line 87 at r3](https://reviewable.io/reviews/cockroachdb/pebble/939#-MIM-QFY2nRJxGq6apsT:-MIfFspj2z2IuB2el_j0:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c226ed43b378f03eceb8c3058e6dcdb32afaf789/internal/manifest/level_metadata.go#L87)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you add a comment about synchronization? Seems like this isn't safe for multiple goroutines to call concurrently if they end up updating a node's cached annotation info. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-07 12:23 UTC, petermattis reviewed
I think this generally looks good, though I think there might be a perf regression for `NewIter` due to newly introduced allocations. I suspect you're going to have to change `L0Subevels.Levels` to `[]LevelMetadata`. Worth doing some microbenchmarks, or perhaps roachtest runs to verify my suspicion that this needs addressing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939#-:-MJ2-Y-LEGskahg6iRod:b9ssmlq)* status: 0 of 20 files reviewed, 5 unresolved discussions (waiting on @itsbilal and @jbowens)

___
*[compaction_picker.go, line 459 at r5](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ1yi8X7f2cdFmf1m1e:-MJ1yi8X7f2cdFmf1m1f:b61k3ty) ([raw file](https://github.com/cockroachdb/pebble/blob/fc359d11b63f42ffe5d37a53c5be5d9a30b92e75/compaction_picker.go#L459)):*
> ```Go
> 
> func (a compensatedSizeAnnotator) Value(f *fileMetadata) (interface{}, bool) {
> 	return compensatedSize(f), f.Stats.Valid
> ```

I believe this will cause an allocation on every call to `compensatedSizeAnnotator.Value` because we're storing a non-pointer value in `interface{}`. Rather than having separate `Value` and `Merge` methods, perhaps there should be a single `Merge(f *fileMetadata, annotation interface{}) (interface{}, bool)` method. We'd then change the type to `*uint64` and we'd only have to perform a single allocation per btree node, rather than one per entry in the node.

Hmm, looking at how `Annotation` is implemented I see this won't quite work, but I suspect something is there. Perhaps what is needed are `Accumulate` and `Merge` methods. `Merge` remains as it is now, and `Accumulate`  is what I'm describing above. Or maybe you have another idea for avoiding the per-entry allocation here.
___
*[db.go, line 781 at r5](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ1wupvAx-7l2Dds1Uw:-MJ1wupvAx-7l2Dds1Ux:b-v0n8x9) ([raw file](https://github.com/cockroachdb/pebble/blob/fc359d11b63f42ffe5d37a53c5be5d9a30b92e75/db.go#L781)):*
> ```Go
> 	// oldest.
> 	for i := len(current.L0Sublevels.Levels) - 1; i >= 0; i-- {
> 		slice := manifest.NewLevelSliceKeySorted(d.cmp, current.L0Sublevels.Levels[i])
> ```

Is this causing an allocation (or more than one allocation) per-sublevel? I suspect that will show up on microbenchmarks. Perhaps `L0Sublevels.Levels` needs to be btree-ified. 
___
*[internal/manifest/btree.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/pebble/939#-MILwdl41j1448Vh2Zlu:-MJ1vvGV3n1cz3HVtHrM:b4n1vkq) ([raw file](https://github.com/cockroachdb/pebble/blob/82a72c1759add35db38282e296705e90967da6c4/internal/manifest/btree.go#L31)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, agreed. Unfortunately, a lot of them structured dictating a specific state (eg, a specific L0 sublevels structure), often as a part of a data-driven test that's not easy to restructure for just the consistency checking command. I'll try to convert them, but I think some of them will just need to be split out/replaced by completely separate tests.
</blockquote></details>

Ack, ok.
___
*[internal/manifest/level_metadata.go, line 72 at r5](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ1vhZB7M-pwE-aTqsY:-MJ1vhZB7M-pwE-aTqsZ:b-lrg96) ([raw file](https://github.com/cockroachdb/pebble/blob/fc359d11b63f42ffe5d37a53c5be5d9a30b92e75/internal/manifest/level_metadata.go#L72)):*
> ```Go
> 
> // Find finds the provided file in the level if it exists.
> func (lm *LevelMetadata) Find(cmp base.Compare, m *FileMetadata) *LevelFile {
> ```

This only works if the level is key-sorted, right? I think that is worth calling out in the comment.
___
*[internal/manifest/version_edit.go, line 487 at r5](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ2-EOb-sYw1jD0EYHw:-MJ2-EOb-sYw1jD0EYHx:b-beuzbt) ([raw file](https://github.com/cockroachdb/pebble/blob/fc359d11b63f42ffe5d37a53c5be5d9a30b92e75/internal/manifest/version_edit.go#L487)):*
> ```Go
> 	v := new(Version)
> 	for level := range v.Levels {
> 		if curr == nil || curr.Levels[level].tree.root == nil {
> ```

@sumeerbhola Can you scrutinize the changes here? I believe you're the person most familiar with this code.


<!-- Sent from Reviewable.io -->

2020-10-07 18:37 UTC, sumeerbhola requested changes
Flushing comments from a partial pass. Will continue reading.

> Reviewed 2 of 9 files at r2, 3 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939#-:-MJ3L_WA08O3fLN1hB15:b8bxw6t)* status: 3 of 20 files reviewed, 17 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/manifest/btree.go, line 668 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3623_2N8xUVmx-_cB:-MJ3623_2N8xUVmx-_cC:bx6ggtt) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/btree.go#L668)):*
> ```Go
> 
> // iterStack represents a stack of (node, pos) tuples, which captures
> // iteration state as an iterator descends a btree.
> ```

I realize the lack of comments here is due to `interval_btree_tmpl.go` lacking them, but could you add field level comments for `iterStack` and `iterator`.
___
*[internal/manifest/btree.go, line 785 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3BHO34EX0Gt1iuLXJ:-MJ3BHO34EX0Gt1iuLXK:b-7cpszr) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/btree.go#L785)):*
> ```Go
> }
> 
> func cmpIter(a, b iterator) int {
> ```

I realized when looking at `LevelIterator` that `cmpIter` is used outside this file.
Is there an assumption that the iterators were created on the same btree and not on two different btrees that refer to the same root?
Are we only mutating btrees after cloning them, when there are existing iterators?
___
*[internal/manifest/btree.go, line 801 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3CWeK8dO_8gpIAzrE:-MJ3CWeK8dO_8gpIAzrF:bmqwqsb) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/btree.go#L801)):*
> ```Go
> 	// If an iterator's stack ends, we stop descending and use its current
> 	// node and position for the final comparison. One iterator's stack may
> 	// end before another's if one iterator is positioned deeper in the tree.
> ```

Is this positional comparison done in order to avoid using `iterator.cmp` which may be more expensive because of string comparisons?
___
*[internal/manifest/btree.go, line 902 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3505F8U9LKuDsM8of:-MJ3505F8U9LKuDsM8og:b-jc2upe) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/btree.go#L902)):*
> ```Go
> // seekGE seeks to the first item greater-than or equal to the provided
> // item.
> func (i *iterator) seekGE(cmp Compare, userKey []byte) {
> ```

It is odd to see this when the btree is allowed to be ordered by seqnum. Is this specifically to for levels > 0 which are sorted by the smallest key? Also, for such levels are we implicitly using the invariant here that the file intervals are non-overlapping? If so, this could use some code comments.

Similar comment for `seekLT` below.
___
*[internal/manifest/btree.go, line 1020 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ36tGQ6q6VmEhBijNX:-MJ36tGQ6q6VmEhBijNY:bukvck8) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/btree.go#L1020)):*
> ```Go
> // valid returns whether the iterator is positioned at a valid position.
> func (i *iterator) valid() bool {
> 	return i.r != nil && i.pos >= 0 && i.pos < i.n.count
> ```

when does an `iterator` have a nil root?
___
*[internal/manifest/level_metadata.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3DtOv5wkd9AJzCH95:-MJ3DtOv5wkd9AJzCH96:b7ortgr) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/level_metadata.go#L86)):*
> ```Go
> // sorted by the L0 sequence number sort order.
> // TODO(jackson): Can we improve this interface or avoid needing to export
> // a slice constructor like this?
> ```

Does this TODO also apply to the `NewLevelSliceKeySorted` function below?
___
*[internal/manifest/level_metadata.go, line 111 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3EdAp2y8t_vQLy7QU:-MJ3EdAp2y8t_vQLy7QV:bevzqnk) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/level_metadata.go#L111)):*
> ```Go
> 
> // LevelSlice contains a slice of the files within a level of the LSM.
> type LevelSlice struct {
> ```

I'm confused about the difference between `LevelSlice` and `LevelIterator` -- they seem to have the same members. Seems like `LevelSlice` serves as an iterator whose position is not changed, and serves as a basis for instantiating other iterators using `LevelSlice.iter.clone()`.
___
*[internal/manifest/level_metadata.go, line 144 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3F_WG--JFQlwqbeiT:-MJ3F_WHDNIQEMbzqN7A:b-hnlqck) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/level_metadata.go#L144)):*
> ```Go
> 		return true
> 	}
> 	return ls.start != nil && ls.end != nil && cmpIter(*ls.start, *ls.end) > 0
> ```

this looks similar to the `LevelIter.Empty` method.
___
*[internal/manifest/level_metadata.go, line 165 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3FgHGEBOnDWE0DXKZ:-MJ3FgHGEBOnDWE0DXK_:b5b8mq8) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/level_metadata.go#L165)):*
> ```Go
> 	iter := ls.Iter()
> 	for f := iter.First(); f != nil; f = iter.Next() {
> 		len++
> ```

a linear-time length method bring backs bad memories. Where will this be called and should we be worried about this? The `LevelSlice` seems a const, so should the first call cache the result?

The caching question applies to `SizeSum()` too, though that was always linear.
___
*[internal/manifest/version.go, line 159 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3GgSO9RCJSpcXRaBb:-MJ3GgSO9RCJSpcXRaBc:b-zcf919) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/version.go#L159)):*
> ```Go
> 	}
> 	// Break ties by file number.
> 	switch {
> ```

why is this code block not using `cmpUint64(m.FileNum, b.FileNum)`?
___
*[internal/manifest/version.go, line 242 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3HzeaB0QfurUg_qsV:-MJ3HzeaB0QfurUg_qsW:b7aapff) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/version.go#L242)):*
> ```Go
> 		endIter.next()
> 	}
> 	// LevelSlice uses inclusive bounds, so if we seeked to the end sentinel
> ```

Why does it use inclusive bounds?
And is there a description of this sentinel somewhere (I see `LevelIterator` mentioning `sentinel state` a couple of times without an explanation)?

I am a bit concerned that implementation details of `LevelIterator` are leaking out here. Could this be avoided with a tighter specification of what one gets with the seek methods?
___
*[internal/manifest/version.go, line 555 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3Jrh01EELuS56rbQu:-MJ3Jrh01EELuS56rbQv:bdd811h) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/version.go#L555)):*
> ```Go
> func (v *Version) CheckOrdering(cmp Compare, format base.FormatKey) error {
> 	bcmp := btreeCmpSmallestKey(cmp)
> 	for sublevel := len(v.L0Sublevels.Levels) - 1; sublevel >= 0; sublevel-- {
> ```

are we doing this because sub-levels are still using go slices? And that will continue in the future because we don't expect many files in L0?


<!-- Sent from Reviewable.io -->

2020-10-07 19:39 UTC, sumeerbhola requested changes
> Reviewed 1 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939)* status: 4 of 20 files reviewed, 20 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[internal/manifest/version_edit.go, line 524 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3P9VU8h5Qs2-XTboV:-MJ3P9VU8h5Qs2-XTboW:bwlcg9e) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/version_edit.go#L524)):*
> ```Go
> 		// associated with a deleted file, just the file number. When applying
> 		// these version edits, we must do a linear scan of the LevelMetadata
> 		// looking for the deleted files.
> ```

We don't mix these two cases in a `BulkVersionEdit` so how about lifting this `fileNumsOnly` computation into `BVE.Accumulate` and keeping it as a member field of BVE?
Additionally, once BVE knows about this mode as the one where it is starting of with a nil Version, it can keep a map[FileNum]*FileMetadata of the added files so far, and fix what is provided in the implementation of `Accumulate` -- it will be more efficient than scanning here, and seems like it would simplify this code.
___
*[internal/manifest/version_edit.go, line 557 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3Z84_C_bGgH4XfK8L:-MJ3Z84_C_bGgH4XfK8M:b-b7guj6) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/version_edit.go#L557)):*
> ```Go
> 		}
> 
> 		var sm, la *FileMetadata
> ```

can you add a comment for `sm` and `la`. It seems we want the smallest span that covers all the added files so we can then check for overlaps later.
___
*[internal/manifest/version_edit.go, line 594 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3ZawA2BhUal64Sunv:-MJ3ZawB3olmSeVFZ-wd:bvyizu9) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/version_edit.go#L594)):*
> ```Go
> 				}
> 				if m := end.Next(); m == nil {
> 					end.Prev()
> ```

what is this re-slicing for? Can you add a code comment.


<!-- Sent from Reviewable.io -->

2020-10-09 17:20 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939)* status: 1 of 24 files reviewed, 20 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[db.go, line 781 at r5](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ1wupvAx-7l2Dds1Uw:-MJDFReS8SAnxHphw002:b6pubqs) ([raw file](https://github.com/cockroachdb/pebble/blob/fc359d11b63f42ffe5d37a53c5be5d9a30b92e75/db.go#L781)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this causing an allocation (or more than one allocation) per-sublevel? I suspect that will show up on microbenchmarks. Perhaps `L0Sublevels.Levels` needs to be btree-ified. 
</blockquote></details>

Yeah, it is. I think it either needs to be btree-ified or `LevelSlice`/`LevelIterator` need to be interfaces with plain Go slice implementations. I don't like the added indirection of making them interfaces, but I also don't like reconstructing these sublevel b-trees from scratch on every L0 version edit. :thinking:
___
*[internal/manifest/btree.go, line 668 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3623_2N8xUVmx-_cB:-MJ3rRLQBdJVn2arAagD:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/btree.go#L668)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I realize the lack of comments here is due to `interval_btree_tmpl.go` lacking them, but could you add field level comments for `iterStack` and `iterator`.
</blockquote></details>

Done.
___
*[internal/manifest/btree.go, line 785 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3BHO34EX0Gt1iuLXJ:-MJDGBKs7x0tZpRo_LuK:b-51zc2b) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/btree.go#L785)):*
> Are we only mutating btrees after cloning them, when there are existing iterators?

Yeah, whenever a btree is going to be mutated, we clone it, apply the modifications and only then will new iterators be constructed. If modifications were made, existing iterators will have different root nodes. In practice though, we only compare iterators created from the same exact `btree`. 

> Is there an assumption that the iterators were created on the same btree and not on two different btrees that refer to the same root?

It's not possible for two different btrees to share the same root, because the btree uses copy-on-write semantics and the first modification to the b-tree will construct a new root.
___
*[internal/manifest/btree.go, line 801 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3CWeK8dO_8gpIAzrE:-MJ3kWmk3p3NMb5-sik6:bw3xv73) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/btree.go#L801)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this positional comparison done in order to avoid using `iterator.cmp` which may be more expensive because of string comparisons?
</blockquote></details>

Yeah, the `LevelIterator` performs pretty frequent bounds checking. It also helps handle cases where an iterator may not be positioned over a `*FileMetadata` eg, seeking or nexting past the last file.  A call to `SeekGE` on a `LevelIterator` with bounds may need to adjust its position back to the end bound if it seeks off the end so that `Prev` works correctly.
___
*[internal/manifest/btree.go, line 902 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3505F8U9LKuDsM8of:-MJDCdP2BwuozhEaGtVl:b-l2v4ii) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/btree.go#L902)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It is odd to see this when the btree is allowed to be ordered by seqnum. Is this specifically to for levels > 0 which are sorted by the smallest key? Also, for such levels are we implicitly using the invariant here that the file intervals are non-overlapping? If so, this could use some code comments.

Similar comment for `seekLT` below.
</blockquote></details>

That's right. Done.
___
*[internal/manifest/btree.go, line 1020 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ36tGQ6q6VmEhBijNX:-MJ3k46r13DG1UCmfWzT:bsc58pu) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/btree.go#L1020)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

when does an `iterator` have a nil root?
</blockquote></details>

only when an `iterator` is constructed from an empty `btree`
___
*[internal/manifest/level_metadata.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3DtOv5wkd9AJzCH95:-MJ3if1G9SEwLksfcS58:bk8pclo) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/level_metadata.go#L86)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Does this TODO also apply to the `NewLevelSliceKeySorted` function below?
</blockquote></details>

Yeah, it does. Duplicated it there.
___
*[internal/manifest/level_metadata.go, line 111 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3EdAp2y8t_vQLy7QU:-MJ3gko71VaGz3GteqhK:b-m3dqj8) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/level_metadata.go#L111)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm confused about the difference between `LevelSlice` and `LevelIterator` -- they seem to have the same members. Seems like `LevelSlice` serves as an iterator whose position is not changed, and serves as a basis for instantiating other iterators using `LevelSlice.iter.clone()`.
</blockquote></details>

Yeah, the intention is for `LevelSlice` to be an immutable slice of a level, while `LevelIterator` is a mutable iterator. I'll expand the comments here.
___
*[internal/manifest/level_metadata.go, line 144 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3F_WG--JFQlwqbeiT:-MJDCZ1dEOWqvubsDREi:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/level_metadata.go#L144)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this looks similar to the `LevelIter.Empty` method.
</blockquote></details>

Done.
___
*[internal/manifest/level_metadata.go, line 165 at r4](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ3FgHGEBOnDWE0DXKZ:-MJD1YVs0lhZg7OCSQtQ:byi0x10) ([raw file](https://github.com/cockroachdb/pebble/blob/94e576f0be1aac097c45ccde36a83f5ca79feaf6/internal/manifest/level_metadata.go#L165)):*
The call sites are all compaction-related call sites, called on inputs to compactions. I agree it's a footgun to have a O(1) `LevelMetadata.Len` and a linear `LevelSlice.Len`. I updated the `LevelSlice` type to store the length as a member field. In _most_ cases where we construct a `LevelSlice` we don't need to calculate it, because we already have it available to us.

> The caching question applies to `SizeSum()` too, though that was always linear.

I don't think we can precompute the size sum on `LevelSlice` construction, because there are codepaths that obtain a `LevelSlice` of the entire level, and we don't already have the size precomputed and readily available _here_. In practice, we never call `SizeSum` on a `LevelSlice` representing the whole level. The `versionSet` does incrementally maintain level size sums, and I think it would be a good idea to try and consolidate these code paths.

One option is to use an `Annotator` to annotate each B-Tree node with the size of all the files in its subtree. This could replace the `versionSet` incremental size updates and allow us to cheaply calculate a `LevelMetadata`'s size when [...]

2020-10-09 17:30 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939)* status: 1 of 24 files reviewed, 20 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[db.go, line 781 at r5](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ1wupvAx-7l2Dds1Uw:-MJDP2zz3SSaQLQ2j4Wz:b-kus6mw) ([raw file](https://github.com/cockroachdb/pebble/blob/fc359d11b63f42ffe5d37a53c5be5d9a30b92e75/db.go#L781)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, it is. I think it either needs to be btree-ified or `LevelSlice`/`LevelIterator` need to be interfaces with plain Go slice implementations. I don't like the added indirection of making them interfaces, but I also don't like reconstructing these sublevel b-trees from scratch on every L0 version edit. :thinking:
</blockquote></details>

Reconstructing the sublevel b-trees on every L0 version edit is preferable to reconstructing them on every `NewIter` call. I'm not sure how I feel about making `LevelSlice`/`LevelIterator` interfaces.


<!-- Sent from Reviewable.io -->

2020-10-12 15:24 UTC, sumeerbhola requested changes
> Reviewed 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939)* status: 2 of 24 files reviewed, 26 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction_picker.go, line 459 at r5](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ1yi8X7f2cdFmf1m1e:-MJRy2Dv5niHNhSj1t_x:b-c6yg1l) ([raw file](https://github.com/cockroachdb/pebble/blob/fc359d11b63f42ffe5d37a53c5be5d9a30b92e75/compaction_picker.go#L459)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I believe this will cause an allocation on every call to `compensatedSizeAnnotator.Value` because we're storing a non-pointer value in `interface{}`. Rather than having separate `Value` and `Merge` methods, perhaps there should be a single `Merge(f *fileMetadata, annotation interface{}) (interface{}, bool)` method. We'd then change the type to `*uint64` and we'd only have to perform a single allocation per btree node, rather than one per entry in the node.

Hmm, looking at how `Annotation` is implemented I see this won't quite work, but I suspect something is there. Perhaps what is needed are `Accumulate` and `Merge` methods. `Merge` remains as it is now, and `Accumulate`  is what I'm describing above. Or maybe you have another idea for avoiding the per-entry allocation here.
</blockquote></details>

Was this discussion resolved?

Isn't there an issue even for pointers in that whenever a `node` changes we have to allocate the object pointed-to by the pointer, when constructing the return value of `Merge`. If instead `Merge` also provided as parameter the result pointer into which the `Merge` could place the output we would avoid that allocation.
___
*[internal/manifest/btree.go, line 21 at r7](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJRzNOtE4WVqfNqSIr3:-MJRzNOtE4WVqfNqSIr4:b-styik4) ([raw file](https://github.com/cockroachdb/pebble/blob/c8459e1826f5a0678c6abefe7b3db0ea455e15a6/internal/manifest/btree.go#L21)):*
> ```Go
> // An Annotator defines a computation over a level's FileMetadata. If the
> // computation is stable and uses inputs that are fixed for the lifetime of
> // a FileMetadata, the LevelMetadata's internal data structures are annotated
> ```

I'd prefer if the comments in this file referred to the structs defined here instead of `LevelMetadata`.
___
*[internal/manifest/btree.go, line 84 at r7](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJJFxNb-cnMM3as-uPR:-MJJFxNb-cnMM3as-uPS:b-k1z8b7) ([raw file](https://github.com/cockroachdb/pebble/blob/c8459e1826f5a0678c6abefe7b3db0ea455e15a6/internal/manifest/btree.go#L84)):*
> ```Go
> type annotation struct {
> 	annotator Annotator
> 	v         interface{}
> ```

is `v` the output of running `annotator` on some file, or of merging? I guess it is both. Can you add a code comment for this struct.
___
*[internal/manifest/btree.go, line 92 at r7](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJJG0d285yeUlXRokDc:-MJJG0d285yeUlXRokDd:b-kr407v) ([raw file](https://github.com/cockroachdb/pebble/blob/c8459e1826f5a0678c6abefe7b3db0ea455e15a6/internal/manifest/btree.go#L92)):*
> ```Go
> 	leaf  bool
> 	items [maxItems]*FileMetadata
> 	annot []annotation
> ```

is `[]annotation` correspond to the files in `items`?
Ah, now I see that the `btree` can have multiple annotators, so I guess this is the annotation output for each annotator. Could you add a code comment.

Also, I'm unclear on the semantics. I'm assuming the annotator output for the root node include the `items` in that node and that of all the children. Could you add a code comment.
___
*[internal/manifest/btree.go, line 562 at r7](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJSNvVs9k2omlGXylkH:-MJSNvVs9k2omlGXylkI:b6e0afv) ([raw file](https://github.com/cockroachdb/pebble/blob/c8459e1826f5a0678c6abefe7b3db0ea455e15a6/internal/manifest/btree.go#L562)):*
> ```Go
> func (n *node) annotation(a Annotator) (interface{}, bool) {
> 	for _, an := range n.annot {
> 		if an.annotator == a {
> ```

if the annotators were assigned dense numbering using an enum, then not only would we not need to search, we could preallocate the output object on the heap (comment thread elsewhere). It would require an additional bool to mark whether something was cacheable or not.
___
*[internal/manifest/btree.go, line 565 at r7](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJSNEoACZEbzFVyTwz4:-MJSNEoACZEbzFVyTwz5:beesur6) ([raw file](https://github.com/cockroachdb/pebble/blob/c8459e1826f5a0678c6abefe7b3db0ea455e15a6/internal/manifest/btree.go#L565)):*
> ```Go
> 			return an.v, true
> 		}
> 	}
> ```

I'm assuming when an element is inserted/removed all nodes on the path from the root to where the change happens have their annotations cleared. It wasn't quite clear which code is doing that for the ancestors of the node where the insert finally happens (where I see the annotations being cleared in `insertAt`). Its not in `mut` if I am reading correctly. Can you clarify?
___
*[internal/manifest/btree.go, line 735 at r7](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJJGLN6CySpBNBgDOb0:-MJJGLN6CySpBNBgDOb1:bufu4ge) ([raw file](https://github.com/cockroachdb/pebble/blob/c8459e1826f5a0678c6abefe7b3db0ea455e15a6/internal/manifest/btree.go#L735)):*
> ```Go
> // iteration state as an iterator descends a btree.
> type iterStack struct {
> 	// a contains aLen stack frames when an iterator stack is shorter enough.
> ```

nit: ... short enough.


<!-- Sent from Reviewable.io -->

2020-10-20 16:15 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939)* status: 1 of 27 files reviewed, 25 unresolved discussions (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[compaction_picker.go, line 459 at r5](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ1yi8X7f2cdFmf1m1e:-MK5ee0fBNawezEYxGZc:b-8rve77) ([raw file](https://github.com/cockroachdb/pebble/blob/fc359d11b63f42ffe5d37a53c5be5d9a30b92e75/compaction_picker.go#L459)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Was this discussion resolved?

Isn't there an issue even for pointers in that whenever a `node` changes we have to allocate the object pointed-to by the pointer, when constructing the return value of `Merge`. If instead `Merge` also provided as parameter the result pointer into which the `Merge` could place the output we would avoid that allocation.

</blockquote></details>

Nope, I hadn't gotten to it yet. I followed your recommendation here and modified the `Merge` function's semantics to merge two adjacent values, (optionally) writing the result into the right value.
___
*[db.go, line 781 at r5](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJ1wupvAx-7l2Dds1Uw:-MK5lc1M4v1NvCJAaMPa:b-8kpfci) ([raw file](https://github.com/cockroachdb/pebble/blob/fc359d11b63f42ffe5d37a53c5be5d9a30b92e75/db.go#L781)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Reconstructing the sublevel b-trees on every L0 version edit is preferable to reconstructing them on every `NewIter` call. I'm not sure how I feel about making `LevelSlice`/`LevelIterator` interfaces.
</blockquote></details>

I updated NewL0Sublevels to construct the sublevel B-Trees. The flat go slices of the sublevels still exist in an unexported `levelFiles` field. They're a little tricky to remove completely because of some intricate logic written in terms of indexing. I'll take another stab at removing them altogether. 
___
*[internal/manifest/btree.go, line 21 at r7](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJRzNOtE4WVqfNqSIr3:-MJnSXz47bRJW6qRrNqq:b-dic1mz) ([raw file](https://github.com/cockroachdb/pebble/blob/c8459e1826f5a0678c6abefe7b3db0ea455e15a6/internal/manifest/btree.go#L21)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'd prefer if the comments in this file referred to the structs defined here instead of `LevelMetadata`.
</blockquote></details>

Hmm, I'm used to writing godoc comments like this in terms of the types exported from the package. I might be in the minority here, but I consume [godoc](https://godoc.org/github.com/cockroachdb/pebble/internal/manifest) documentation even for internal packages. I also tend to think of Go packages as the cohesive unit, rather than source files.

I added a separate comment that won't be pulled into the godoc that describes more of the specifics with respect to the structs within this file.
___
*[internal/manifest/btree.go, line 84 at r7](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJJFxNb-cnMM3as-uPR:-MK1_7d_4U9pTZBDHJ6w:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c8459e1826f5a0678c6abefe7b3db0ea455e15a6/internal/manifest/btree.go#L84)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is `v` the output of running `annotator` on some file, or of merging? I guess it is both. Can you add a code comment for this struct.
</blockquote></details>

Done.
___
*[internal/manifest/btree.go, line 92 at r7](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJJG0d285yeUlXRokDc:-MK1_pt5-ofmsa1EHlfw:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c8459e1826f5a0678c6abefe7b3db0ea455e15a6/internal/manifest/btree.go#L92)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is `[]annotation` correspond to the files in `items`?
Ah, now I see that the `btree` can have multiple annotators, so I guess this is the annotation output for each annotator. Could you add a code comment.

Also, I'm unclear on the semantics. I'm assuming the annotator output for the root node include the `items` in that node and that of all the children. Could you add a code comment.
</blockquote></details>

Done.
___
*[internal/manifest/btree.go, line 562 at r7](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJSNvVs9k2omlGXylkH:-MK1_siL-ibxPPhGhT-p:b-7s6ihq) ([raw file](https://github.com/cockroachdb/pebble/blob/c8459e1826f5a0678c6abefe7b3db0ea455e15a6/internal/manifest/btree.go#L562)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

if the annotators were assigned dense numbering using an enum, then not only would we not need to search, we could preallocate the output object on the heap (comment thread elsewhere). It would require an additional bool to mark whether something was cacheable or not.
</blockquote></details>

The enum would create a tight coupling to the compaction picking logic which would be nice to avoid. If we do create a tight coupling, maybe we should just scrap the `Annotator` interface and add explicit `compensatedSizeSum` and `elisionOnlyCompactionCandidate` fields to the `leafNode` struct?

One other thing to note is that the elision-only compaction annotator is only ever used on L6, and the compensated size annotator is never used on L6.

The search doesn't seem to big of a deal, because in practice we have 0 or 1 annotations, but it would be nice to avoid that allocation...

Edit: I updated the implementation to add the additional bool and reuse the output object between annotation calculations. I think this now limits the allocations to 1 per annotator per node for the lifetime of the node, plus one per node for the `[]annotation` slice.
___
*[internal/manifest/btree.go, line 565 at r7](https://reviewable.io/reviews/cockroachdb/pebble/939#-MJSNEoACZEbzFVyTwz4:-MK5fK3q0VO4NTPqxwUx:b-4oxoq) ([raw file](https://github.com/cockroachdb/pebble/blob/c8459e1826f5a0678c6abefe7b3db0ea455e15a6/internal/manifest/btree.go#L565)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm assuming when an element is inserted/removed all nodes on the path from the root to where the change happens have their annotations cleared. It wasn't quite clear which code is doing that for the ancestors of the node where the insert finally happens (where I see the annotations being cleared in `insertAt`). Its not in `mut` if I am reading correctly. Can you clarify?
</blockquote></details>

I updated the code to clear from `mut`, because it's less subtle and less likely to break if we make changes to the btree.


<!-- Sent from Reviewable.io -->

2020-10-20 21:32 UTC, sumeerbhola requested changes
> Reviewed 1 of 13 files at r6, 7 of 16 files at r8, 4 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939)* status: 13 of 27 files reviewed, 32 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction_picker.go, line 482 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6j9z-47U7-UMKsPEX:-MK6j9z09DvNv35MY3it:b-xo5sd) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/compaction_picker.go#L482)):*
> ```Go
> // iterator. Use the compensatedSizeAnnotator if querying the total
> // compensated size of a level.
> func totalCompensatedSize(iter manifest.LevelIterator) uint64 {
> ```

is this function still used?
___
*[compaction_picker.go, line 1118 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6kD4oCAMDxDQU0S-7:-MK6kD4oCAMDxDQU0S-8:byn732z) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/compaction_picker.go#L1118)):*
> ```Go
> 		return dst, true
> 	}
> 	return f, true
> ```

I didn't understand why there isn't a comparison between the sequence number of `dst` and `f` like in `Merge`.
___
*[internal/manifest/btree.go, line 161 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6RK3B3tzOBVwy-V1q:-MK6RK3B3tzOBVwy-V1r:br68d07) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/btree.go#L161)):*
> ```Go
> 		// Exclusive ownership. Can mutate in place.
> 
> 		// clearAnnotations is called whenever a node is mutated, resetting all its
> ```

what is `clearAnnotations`?
___
*[internal/manifest/l0_sublevels.go, line 184 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6T5LNAxfQY52I005M:-MK6T5LNAxfQY52I005N:ba7r7f9) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/l0_sublevels.go#L184)):*
> ```Go
> 	// Levels are ordered from oldest sublevel to youngest sublevel in the
> 	// outer slice, and the inner slice contains non-overlapping files for
> 	// that sublevel in increasing key order.
> ```

can you add a comment that `Levels` is constructed from `levelFiles` to satisfy callers that need a `LevelSlice` (I am assuming this is for constructing `levelIterator`).
___
*[internal/manifest/level_metadata.go, line 427 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6X-0R1hoHQnzqWKTS:-MK6X-0R1hoHQnzqWKTT:brvd89u) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/level_metadata.go#L427)):*
> ```Go
> 		(i.start != nil && cmpIter(i.iter, *i.start) < 0) {
> 		return nil
> 	}
> ```

I'm trying to understand why this is not something like (and included a question about semantics when seeks are combined with prev/next).
```
	if i.end != nil && cmpIter(i.iter, *i.end) > 0 {
		i.iter = i.end.clone()
		i.iter.next()
		// Since seek(fn) positioned beyond i.end we know that there is nothing to return within the bounds
		return nil.
		// Question: shouldn't we position at the actual place where fn is true, so that one has to do many calls to prev before getting back into bounds?
	} else if i.start != nil && cmpIter(i.iter, *i.start) < 0 {
		i.iter = i.start.clone()
		return i.iter.cur()
	}
	if !i.iter.valid() {
		return nil
	}
	return i.iter.cur()
```
___
*[internal/manifest/version_edit.go, line 450 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6mnhf-TKTDSn207te:-MK6mnhf-TKTDSn207tf:buuxalf) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/version_edit.go#L450)):*
> ```Go
> 	for _, nf := range ve.NewFiles {
> 		// A new file should not have been deleted in this or a preceding
> 		// VersionEdit at the same level (though files can move across levels).
> ```

We shouldn't see a file in `ve.DeletedFiles` that is being added in this `VersionEdit`, so I am not clear why the processing of `ve.DeletedFiles` was moved from before this for loop to after this for loop. It seems to have weakened the error checking.
___
*[internal/manifest/version_edit.go, line 561 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6sXjq8wgUDUJITKIf:-MK6sXjq8wgUDUJITKIg:b-k8ryan) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/version_edit.go#L561)):*
> ```Go
> 		for _, f := range addedFiles {
> 			if _, ok := deletedMap[f.FileNum]; ok {
> 				addZombie(f.FileNum, f.Size)
> ```

we have already called `addZombie` for all the files in `deletedMap` earlier, so do we need to do this again?


<!-- Sent from Reviewable.io -->

2020-10-21 16:01 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939)* status: 8 of 27 files reviewed, 32 unresolved discussions (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[compaction_picker.go, line 482 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6j9z-47U7-UMKsPEX:-MKAXbKXCyqC5z1aGLNv:b4ti9bk) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/compaction_picker.go#L482)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this function still used?
</blockquote></details>

Yeah, it's still called once in `calculateSizeAdjust` to calculate the compensated size of a running compaction's inputs.

Since a compaction's inputs don't span an entire B-Tree, it's tricky to use the annotations for this. I have a branch where I implemented a function that took an `*iterator` and  returned three values: an annotation value merged across all the values left of the iterator position, the annotation value at the current iterator position, and an annotation value merged across all the values right of the iterator position. It could be used to compute the compensated size of a bounded `LevelSlice` using annotations. I decided to pocket it though because it was complicated and in practice compaction input slices should be small.
___
*[compaction_picker.go, line 1118 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6kD4oCAMDxDQU0S-7:-MKAcGJL6i-SzAvsdg_o:b-fz9gy1) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/compaction_picker.go#L1118)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't understand why there isn't a comparison between the sequence number of `dst` and `f` like in `Merge`.
</blockquote></details>

Oops, that was a mistake. Fixed.
___
*[internal/manifest/btree.go, line 161 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6RK3B3tzOBVwy-V1q:-MKAcSYV68B-Vbo31gq0:bur3k6c) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/btree.go#L161)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what is `clearAnnotations`?
</blockquote></details>

I forgot to update this comment when I moved clearing into `mut`. Fixed!
___
*[internal/manifest/l0_sublevels.go, line 184 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6T5LNAxfQY52I005M:-MKAXKLu2gVB9I1P-h0o:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/l0_sublevels.go#L184)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a comment that `Levels` is constructed from `levelFiles` to satisfy callers that need a `LevelSlice` (I am assuming this is for constructing `levelIterator`).
</blockquote></details>

Done.
___
*[internal/manifest/level_metadata.go, line 427 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6X-0R1hoHQnzqWKTS:-MKAn9GW7eoJWj4E5dHy:bjnna43) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/level_metadata.go#L427)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm trying to understand why this is not something like (and included a question about semantics when seeks are combined with prev/next).
```
	if i.end != nil && cmpIter(i.iter, *i.end) > 0 {
		i.iter = i.end.clone()
		i.iter.next()
		// Since seek(fn) positioned beyond i.end we know that there is nothing to return within the bounds
		return nil.
		// Question: shouldn't we position at the actual place where fn is true, so that one has to do many calls to prev before getting back into bounds?
	} else if i.start != nil && cmpIter(i.iter, *i.start) < 0 {
		i.iter = i.start.clone()
		return i.iter.cur()
	}
	if !i.iter.valid() {
		return nil
	}
	return i.iter.cur()
```
</blockquote></details>

You're right, it should be that. I worked myself into a confusion during the refactor.

Re: the question about seeks & prev, next, the current semantics where a single `Prev` calls returns you to the last item of the slice is what we rely on practice. The rest of the underlying B-Tree should be completely hidden, except when calling `Reslice`.
___
*[internal/manifest/version_edit.go, line 450 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6mnhf-TKTDSn207te:-MKAerd90XjQjYLILHKw:bgi5wqu) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/version_edit.go#L450)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We shouldn't see a file in `ve.DeletedFiles` that is being added in this `VersionEdit`, so I am not clear why the processing of `ve.DeletedFiles` was moved from before this for loop to after this for loop. It seems to have weakened the error checking.
</blockquote></details>

Ah, yeah, you're right. I corrected the ordering of the for loops and unified the error messages since this case falls into two different code paths depending on whether we're replaying a manifest or not.
___
*[internal/manifest/version_edit.go, line 561 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6sXjq8wgUDUJITKIf:-MKAgPnl5IanM_4OvxhD:b-48vilg) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/version_edit.go#L561)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we have already called `addZombie` for all the files in `deletedMap` earlier, so do we need to do this again?
</blockquote></details>

Good call, done.


<!-- Sent from Reviewable.io -->

2020-10-21 21:56 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 18 files at r1, 1 of 9 files at r2, 1 of 13 files at r6, 5 of 16 files at r8, 1 of 5 files at r9, 6 of 6 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939#-:-MKC9KqmD1eAOT5BQn4g:bg7igkv)* status: all files reviewed, 34 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction_picker.go, line 482 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6j9z-47U7-UMKsPEX:-MKC5Ljc2UCToaT9xe_U:b-dxcbts) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/compaction_picker.go#L482)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, it's still called once in `calculateSizeAdjust` to calculate the compensated size of a running compaction's inputs.

Since a compaction's inputs don't span an entire B-Tree, it's tricky to use the annotations for this. I have a branch where I implemented a function that took an `*iterator` and  returned three values: an annotation value merged across all the values left of the iterator position, the annotation value at the current iterator position, and an annotation value merged across all the values right of the iterator position. It could be used to compute the compensated size of a bounded `LevelSlice` using annotations. I decided to pocket it though because it was complicated and in practice compaction input slices should be small.
</blockquote></details>

Makes sense.
___
*[internal/manifest/level_metadata.go, line 427 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6X-0R1hoHQnzqWKTS:-MKC756U1l0eWb99FT9E:b-z6lkaw) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/level_metadata.go#L427)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

You're right, it should be that. I worked myself into a confusion during the refactor.

Re: the question about seeks & prev, next, the current semantics where a single `Prev` calls returns you to the last item of the slice is what we rely on practice. The rest of the underlying B-Tree should be completely hidden, except when calling `Reslice`.
</blockquote></details>

Could you add a code comment to that effect somewhere in this function.
___
*[internal/manifest/level_metadata.go, line 415 at r10](https://reviewable.io/reviews/cockroachdb/pebble/939#-MKC7EZm7_HBdksluLLH:-MKC7EZm7_HBdksluLLI:b-sf2ffs) ([raw file](https://github.com/cockroachdb/pebble/blob/9dd42f217480c5df1172fc6778bd623ea421b43c/internal/manifest/level_metadata.go#L415)):*
> ```Go
> 	// has start or end bounds, we may have exceeded them. Reset to the bounds
> 	// if necessary.
> 	if i.end != nil && cmpIter(i.iter, *i.end) > 0 {
> ```

does `cmpIter` require `i.iter.valid()` return true?
___
*[internal/manifest/version_edit.go, line 561 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6sXjq8wgUDUJITKIf:-MKC8KPE7Jib3FWPOObD:b-i8g0qw) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/version_edit.go#L561)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Good call, done.
</blockquote></details>

Can you add a code comment that states something like
// Already called addZombie on this file in preceding loop, so don't need to do it here.
___
*[internal/manifest/version_edit_test.go, line 275 at r10](https://reviewable.io/reviews/cockroachdb/pebble/939#-MKC8dn_8-ud5q0PFqmn:-MKC8dn_8-ud5q0PFqmo:bueb5vp) ([raw file](https://github.com/cockroachdb/pebble/blob/9dd42f217480c5df1172fc6778bd623ea421b43c/internal/manifest/version_edit_test.go#L275)):*
> ```Go
> 		m.LargestSeqNum = m.Largest.SeqNum()
> 		if m.SmallestSeqNum > m.LargestSeqNum {
> 			m.SmallestSeqNum, m.LargestSeqNum = m.LargestSeqNum, m.SmallestSeqNum
> ```

do we have incorrect input data for this test, that required this change? If yes, wouldn't it be better to fix the input?


<!-- Sent from Reviewable.io -->

2020-10-22 15:05 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939)* status: all files reviewed, 34 unresolved discussions (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[internal/manifest/level_metadata.go, line 427 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6X-0R1hoHQnzqWKTS:-MKFngzl4xbl_suKYM2h:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/level_metadata.go#L427)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Could you add a code comment to that effect somewhere in this function.
</blockquote></details>

Done.
___
*[internal/manifest/level_metadata.go, line 415 at r10](https://reviewable.io/reviews/cockroachdb/pebble/939#-MKC7EZm7_HBdksluLLH:-MKFlLqTAuksOVZslOXv:b7evrbi) ([raw file](https://github.com/cockroachdb/pebble/blob/9dd42f217480c5df1172fc6778bd623ea421b43c/internal/manifest/level_metadata.go#L415)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

does `cmpIter` require `i.iter.valid()` return true?
</blockquote></details>

No, it doesn't. I just double checked and it also does _not_ require the underlying B-Tree to have a root node either.
___
*[internal/manifest/version_edit.go, line 561 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6sXjq8wgUDUJITKIf:-MKFlGpwBUP4J1vzssNL:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/version_edit.go#L561)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a code comment that states something like
// Already called addZombie on this file in preceding loop, so don't need to do it here.
</blockquote></details>

Done.
___
*[internal/manifest/version_edit_test.go, line 275 at r10](https://reviewable.io/reviews/cockroachdb/pebble/939#-MKC8dn_8-ud5q0PFqmn:-MKFo-3o3UkrqarhMmZn:b27jhm2) ([raw file](https://github.com/cockroachdb/pebble/blob/9dd42f217480c5df1172fc6778bd623ea421b43c/internal/manifest/version_edit_test.go#L275)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

do we have incorrect input data for this test, that required this change? If yes, wouldn't it be better to fix the input?
</blockquote></details>

It's not incorrect so much as insufficient. We provided the smallest and largest internal keys for the file metadata, and those were always correct, but we also used their sequence numbers to set the smallest and largest sequence numbers for the file assuming the smallest user key had the smallest sequence number and vice versa. We could extend the test to provide a separate sequence number range, but I'm not sure it's worth the verbosity.


<!-- Sent from Reviewable.io -->

2020-10-22 15:30 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939)* status: all files reviewed, 34 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[internal/manifest/level_metadata.go, line 427 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6X-0R1hoHQnzqWKTS:-MKFvTtp2USwlHrRw1T0:b5dyw60) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/level_metadata.go#L427)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

forgot to push? or maybe reviewable is acting up.


<!-- Sent from Reviewable.io -->

2020-10-22 19:44 UTC, jbowens reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/939#-:-MKGptKH8xJk2Cu0cw3N:b-814g8k)* status: 16 of 27 files reviewed, 34 unresolved discussions (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[internal/manifest/level_metadata.go, line 427 at r9](https://reviewable.io/reviews/cockroachdb/pebble/939#-MK6X-0R1hoHQnzqWKTS:-MKGppWD-ebn_UXoLuk6:b-ph88by) ([raw file](https://github.com/cockroachdb/pebble/blob/c423f22b6988cfdc6e678201f89c92681fad23e3/internal/manifest/level_metadata.go#L427)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

forgot to push? or maybe reviewable is acting up.
</blockquote></details>

Oops, yeah, pushed.


<!-- Sent from Reviewable.io -->

2020-10-22 19:58 UTC, merged