*: Implement deletion pacing of obsolete compaction files
cockroachdb/pebble pull request #981
Opened 2020-11-02 22:50 UTC by itsbilal

Currently, file deletions are not rate limited at all. This is
usually not an issue, however if a lot of bytes are deleted
all at once, this could slow down or even stall disk writes on
some SSDs, if an ssd-level garbage collection run gets kicked off.
As it's hard to detect when this would happen in advance, it makes
sense to be pacing deletions at some rate all the time.

This PR implements deletionPacer, which works in some ways like
{compaction,flush}Pacer, except the threshold it has (i.e. free
space on disk in bytes) is treated as a minimum rather than a
maximum for inducing slowness, unlike the other pacers that are
based on read-amplification. The deletion pacer is disabled by
default to make most tests more deterministic, however it will
most likely be enabled in cockroach.

Fixes #129.

2020-11-02 22:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/pebble/981)
<!-- Reviewable:end -->

2020-11-03 14:33 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/981)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[options.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLDUtkh0glJN1H__eSX:-MLDUtkh0glJN1H__eSY:bhssudn) ([raw file](https://github.com/cockroachdb/pebble/blob/149316af251badc33ed82751bc25590d62ff6994/options.go#L324)):*
> ```Go
> 		DeleteRangeFlushDelay time.Duration
> 
> 		// MaxDeletionRate is the maximum number of bytes per second that would
> ```

What should we set this value to? Too high and we're not pacing adequately. Too low and we'll let the disk fill up until there are fewer than 16 GB left at which point we'll delete until we reach until there are >16 GB free and then pace deletions again.

Perhaps we should pace deletions so that we don't allow more than X% of the disk to be obsolete sstables where X is something like 10%. No need for a max deletion rate, though I think we'd want a `MinDeletionRate` to ensure that we delete obsolete sstables eventually even in the absence of new write operations. 
___
*[pacer.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLDSguA6ZC9Yot4F2pD:-MLDSguA6ZC9Yot4F2pE:b-chyu0p) ([raw file](https://github.com/cockroachdb/pebble/blob/149316af251badc33ed82751bc25590d62ff6994/pacer.go#L38)):*
> ```Go
> 	refreshBytesThreshold uint64
> 	slowdownThreshold     uint64
> 	thresholdIsMin        bool
> ```

Rather than a new field, could we replace `slowdownThreshold` with a closure that takes the current level? Or perhaps `thresholdCrossed` should be a boolean passed in to `internalPacer.limit` rather than passing in `currentLevel`. Then the caller could determine whether to use `<=` or `>=`. That would argue for moving `slowdownThreshold` out of `internalPacer` and into `compactionPacer`, `deletionPacer`, and `flushPacer`.
___
*[pacer.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLDTaH-1rU7M3pHSdg1:-MLDTaH-1rU7M3pHSdg2:b-ekc1uy) ([raw file](https://github.com/cockroachdb/pebble/blob/149316af251badc33ed82751bc25590d62ff6994/pacer.go#L274)):*
> ```Go
> // newDeletionPacer instantiates a new deletionPacer for use after a compaction.
> // The limiter passed in must be a singleton shared across this pebble instance.
> func newDeletionPacer(limiter limiter, getInfo func() deletionPacerInfo) *deletionPacer {
> ```

Nit: generally we put `constructor` functions like this immediately after the struct definition and before any methods on the struct.
___
*[pacer.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLDS9RV8nfyPwZFGo-J:-MLDS9RV8nfyPwZFGo-K:bo1zw8b) ([raw file](https://github.com/cockroachdb/pebble/blob/149316af251badc33ed82751bc25590d62ff6994/pacer.go#L280)):*
> ```Go
> 			// If there are less than slowdownThreshold bytes of free space on
> 			// disk, do not pace deletions at all.
> 			slowdownThreshold: 16 << 30, // 16 GB
> ```

"Slowdown threshold" makes me think of a threshold at which slowdowns will begin. This is the opposite. I think it would be clearer to name this `disablePacingThreshold`. 


<!-- Sent from Reviewable.io -->

2020-11-04 00:28 UTC, sumeerbhola requested changes
> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/981)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[options.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLDUtkh0glJN1H__eSX:-MLFbnmf7sYbr69SEpYM:bcnj1kd) ([raw file](https://github.com/cockroachdb/pebble/blob/149316af251badc33ed82751bc25590d62ff6994/options.go#L324)):*
> No need for a max deletion rate, though I think we'd want a MinDeletionRate to ensure that we delete obsolete sstables eventually even in the absence of new write operations.

Isn't this already a `MinDeletionRate` since it is the rate applied when there is > 16GB free, else there is no limit?

I like the idea of a threshold that is a fraction of garbage to live or total data.
___
*[pacer.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLFcjA2E1kvvvmk8-pc:-MLFcjA2E1kvvvmk8-pd:b-utnu5r) ([raw file](https://github.com/cockroachdb/pebble/blob/149316af251badc33ed82751bc25590d62ff6994/pacer.go#L66)):*
> ```Go
> 		burst := p.limiter.Burst()
> 		for amount > uint64(burst) {
> 			p.limiter.AllowN(time.Now(), burst)
> ```

Can you add a comment like
// AllowN will subtract the burst if there are enough tokens available, else leave the tokens untouched. That is, we are making a best-effort to account for this activity, but by ignoring the return value, we do this activity nonetheless.


<!-- Sent from Reviewable.io -->

2020-11-11 18:47 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/981)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[options.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLDUtkh0glJN1H__eSX:-MLsaTa42I_Ioc9tGsgX:bvnhd5o) ([raw file](https://github.com/cockroachdb/pebble/blob/149316af251badc33ed82751bc25590d62ff6994/options.go#L324)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> No need for a max deletion rate, though I think we'd want a MinDeletionRate to ensure that we delete obsolete sstables eventually even in the absence of new write operations.

Isn't this already a `MinDeletionRate` since it is the rate applied when there is > 16GB free, else there is no limit?

I like the idea of a threshold that is a fraction of garbage to live or total data.
</blockquote></details>

Done. I had to move many things around, and add tracking of obsolete file sizes in `vs.metrics`, but this should work now. PTAL.
___
*[pacer.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLDSguA6ZC9Yot4F2pD:-MLsaaZeEPTzn9Zpux2_:b-pvhpjk) ([raw file](https://github.com/cockroachdb/pebble/blob/149316af251badc33ed82751bc25590d62ff6994/pacer.go#L38)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Rather than a new field, could we replace `slowdownThreshold` with a closure that takes the current level? Or perhaps `thresholdCrossed` should be a boolean passed in to `internalPacer.limit` rather than passing in `currentLevel`. Then the caller could determine whether to use `<=` or `>=`. That would argue for moving `slowdownThreshold` out of `internalPacer` and into `compactionPacer`, `deletionPacer`, and `flushPacer`.
</blockquote></details>

Given how the other fields in internalPacer (eg. prevBytesIterated) didn't make sense for deletionPacer anyway, I ended up renaming internalPacer to `compactionInternalPacer` and made deletionPacer a standalone thing. That should be cleaner.
___
*[pacer.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLFcjA2E1kvvvmk8-pc:-MLsc59NB-c7eSePNTBi:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/149316af251badc33ed82751bc25590d62ff6994/pacer.go#L66)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a comment like
// AllowN will subtract the burst if there are enough tokens available, else leave the tokens untouched. That is, we are making a best-effort to account for this activity, but by ignoring the return value, we do this activity nonetheless.



</blockquote></details>

Done.
___
*[pacer.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLDTaH-1rU7M3pHSdg1:-MLsatzqEjyc1RULazgq:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/149316af251badc33ed82751bc25590d62ff6994/pacer.go#L274)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: generally we put `constructor` functions like this immediately after the struct definition and before any methods on the struct.
</blockquote></details>

Done.
___
*[pacer.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLDS9RV8nfyPwZFGo-J:-MLsauaJ79atTEGZNLbP:bqnx61c) ([raw file](https://github.com/cockroachdb/pebble/blob/149316af251badc33ed82751bc25590d62ff6994/pacer.go#L280)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

"Slowdown threshold" makes me think of a threshold at which slowdowns will begin. This is the opposite. I think it would be clearer to name this `disablePacingThreshold`. 
</blockquote></details>

Done (less relevant now).


<!-- Sent from Reviewable.io -->

2020-11-12 02:03 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> modulo the performance questions

> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/981#-:-MLuBIbsAAyMvibidlxU:bo2ylv7)* status: all files reviewed, 10 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 1171 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu68Km0oEzRM47YLvs:-MLu68Kn4IiFZ9Ixn4tc:b-3jnb77) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/compaction.go#L1171)):*
> ```Go
> func (d *DB) getDeletionPacerInfo() deletionPacerInfo {
> 	var pacerInfo deletionPacerInfo
> 	if space, err := d.opts.FS.GetFreeSpace(d.dirname); err == nil {
> ```

Is `GetFreeSpace` which seems to use `statfs` fast or accurate or both? We are calling this for each obsolete file, so I am primarily concerned with this not being too slow.
___
*[compaction.go, line 2597 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu9KM2Aui7l9qNBLF6:-MLu9KM2Aui7l9qNBLF7:b8wj4wt) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/compaction.go#L2597)):*
> ```Go
> 	for _, of := range files {
> 		path := base.MakeFilename(d.opts.FS, of.dir, of.fileType, of.fileNum)
> 		if stat, err := d.opts.FS.Stat(path); err == nil {
> ```

(see later comment about Stat)
___
*[pacer.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu-r-Z5MFnsmGv4vr2:-MLu-r-Z5MFnsmGv4vr3:b2kiw0s) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/pacer.go#L252)):*
> ```Go
> }
> 
> // deletionPacer rate limits deletions after a compaction finishes up. This
> ```

nit: "up" is not needed.
Also, we delete obsolete files in cases other than compaction, such as when an iterator close removes the last ref on a `readState`. So we could just say that deletionPacer rate limits deletion of obsolete files.
___
*[pacer.go, line 265 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu1XR_0vxX3b7BT-Jv:-MLu1XR_0vxX3b7BT-Jw:b-gri9l5) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/pacer.go#L265)):*
> ```Go
> }
> 
> // newDeletionPacer instantiates a new deletionPacer for use after a compaction.
> ```

same comment about not mentioning compaction.
___
*[pacer.go, line 269 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu9ult5oPpgX7iRHwX:-MLu9ult5oPpgX7iRHwY:b-57m3lc) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/pacer.go#L269)):*
> ```Go
> func newDeletionPacer(limiter limiter, getInfo func() deletionPacerInfo) *deletionPacer {
> 	return &deletionPacer{
> 		limiter: limiter,
> ```

I was initially worried that coming up with a good rate value is necessary for this to work well. If the rate is too low, we would climb up to the obsoleteBytesMaxRatio and then remove all pacing -- ideally we want the rate to be just enough to keep the obsolete bytes from slowly growing. But I realized this will work fine because the granularity of the pacing change is so fine-grained: as soon as we will go above obsoleteBytesMaxRatio we will remove pacing, but after removing 1 (or few files) we will drop below the ratio and resume pacing. The switching back and forth between both regimes over a short time interval will result in a smoothed deletion rate that is close to optimal.
___
*[version_set.go, line 665 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu4Kg-1b_G1GG_2biX:-MLu4Kg-1b_G1GG_2biY:bsrm0sw) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/version_set.go#L665)):*
> ```Go
> 	for _, fileNum := range obsolete {
> 		path := base.MakeFilename(vs.opts.FS, vs.dirname, fileTypeTable, fileNum)
> 		if stat, err := vs.opts.FS.Stat(path); err == nil {
> ```

Working with distributed file systems has drilled into me that `Stat` is not free. We aren't quite in that situation, even with EBS, but wanted to mention that if we cared we could avoid this Stat since `FileMetadata` has the size (though it would require a bunch of plumbing changes since we will need to change all the way to the btree `node.decRef`).


<!-- Sent from Reviewable.io -->

2020-11-12 14:04 UTC, petermattis reviewed
This approach looks good to me too. I think we do need to address the stat'ing of files, though. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/981#-:-MLwlLw_AZePeetgcQQ3:bnlms2j)* status: all files reviewed, 12 unresolved discussions (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[options.go, line 325 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLwinbwBEwZEG0X0Be1:-MLwinbwBEwZEG0X0Be2:b7ovoc5) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/options.go#L325)):*
> ```Go
> 
> 		// MinDeletionRate is the minimum number of bytes per second that would
> 		// be deleted. This is used to slow down deletions when compactions
> ```

Nit: `s/This/Deletion pacing/g`
___
*[options.go, line 327 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLwiu7Q-c_8lbdt-4eX:-MLwiu7Q-c_8lbdt-4eY:bbe2h8j) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/options.go#L327)):*
> ```Go
> 		// be deleted. This is used to slow down deletions when compactions
> 		// finish up and clean up their obsolete files. Deleting lots of files
> 		// at once can cause disk latency to go up on some SSDs, so this feature
> ```

Nit: `s/so this feature/which this functionality/g`
___
*[options.go, line 331 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLwjEbo9mE3l4D5cBic:-MLwjEbo9mE3l4D5cBid:b6vkbq7) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/options.go#L331)):*
> ```Go
> 		// theoretically unlimited; pacing is disabled when there are too many
> 		// obsolete files relative to live bytes, or there isn't enough disk
> 		// space available.
> ```

Let's mention that deletion pacing can be disabled by setting this to 0 (which I think is the default).
___
*[version_set.go, line 662 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLwk17x0Lz_r1E8ww5_:-MLwk17x0Lz_r1E8ww5a:b-59gglh) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/version_set.go#L662)):*
> ```Go
> }
> 
> func (vs *versionSet) incrementObsoleteTables(obsolete []FileNum) {
> ```

Nit: add the `Locked` suffix to this method to make the locking clear.
___
*[version_set.go, line 665 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu4Kg-1b_G1GG_2biX:-MLwk5WX0sg1cl9FhgHD:b3ykh9b) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/version_set.go#L665)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Working with distributed file systems has drilled into me that `Stat` is not free. We aren't quite in that situation, even with EBS, but wanted to mention that if we cared we could avoid this Stat since `FileMetadata` has the size (though it would require a bunch of plumbing changes since we will need to change all the way to the btree `node.decRef`).
</blockquote></details>

Another consideration here: we shouldn't be doing any disk I/O (which stat might involve) while holding `DB.mu`.

While mildly irritating to plumb, I don't see any particular difficulty in change `obsolete` to be a `[]base.FileMetadata`. Possibly I'm missing something, but I think that is the right thing to do.


<!-- Sent from Reviewable.io -->

2020-11-12 19:41 UTC, itsbilal reviewed
Made the change to plumb FileMetadatas through, instead of stat-ing-on-the-fly. Still have the per-file GetFreeSpace()s though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/981#-:-MLxoOrzBIjrEao_cl9m:b-h36wn1)* status: 6 of 15 files reviewed, 8 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 1171 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu68Km0oEzRM47YLvs:-MLxpXAL3HTJgDBBOP-5:bicuefw) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/compaction.go#L1171)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is `GetFreeSpace` which seems to use `statfs` fast or accurate or both? We are calling this for each obsolete file, so I am primarily concerned with this not being too slow.
</blockquote></details>

The motivation behind that is to be able to react quickly to increases in disk space usage. Let me know if it's too frequent though; I could add some sort of logic that only calls GetFreeSpace if x seconds, or y bytes of file deletions, have passed since the last call.
___
*[compaction.go, line 2597 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu9KM2Aui7l9qNBLF6:-MLxoM_RBjVdxtwnYJNs:b-j5u4dl) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/compaction.go#L2597)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

(see later comment about Stat)
</blockquote></details>

Done. We only Stat in the `Open` case now.
___
*[options.go, line 325 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLwinbwBEwZEG0X0Be1:-MLxo2gR6JHDlHtvZdxa:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/options.go#L325)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `s/This/Deletion pacing/g`
</blockquote></details>

Done.
___
*[options.go, line 327 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLwiu7Q-c_8lbdt-4eX:-MLxoAqdD8rnHiZ_iu2N:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/options.go#L327)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `s/so this feature/which this functionality/g`
</blockquote></details>

Done.
___
*[options.go, line 331 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLwjEbo9mE3l4D5cBic:-MLxoIy86sp2McltkINI:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/options.go#L331)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Let's mention that deletion pacing can be disabled by setting this to 0 (which I think is the default).
</blockquote></details>

Done.
___
*[pacer.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu-r-Z5MFnsmGv4vr2:-MLxxWDUDD1smKfZpcmA:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/pacer.go#L252)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: "up" is not needed.
Also, we delete obsolete files in cases other than compaction, such as when an iterator close removes the last ref on a `readState`. So we could just say that deletionPacer rate limits deletion of obsolete files.

</blockquote></details>

Done.
___
*[pacer.go, line 265 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu1XR_0vxX3b7BT-Jv:-MLxxcWMCe0zMueRWcJ_:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/pacer.go#L265)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same comment about not mentioning compaction.
</blockquote></details>

Done.
___
*[version_set.go, line 662 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLwk17x0Lz_r1E8ww5_:-MLxxt95B69Ck0_ohtmg:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/version_set.go#L662)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: add the `Locked` suffix to this method to make the locking clear.
</blockquote></details>

Done.
___
*[version_set.go, line 665 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu4Kg-1b_G1GG_2biX:-MLxxsJd3x-1xKMSeOeK:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/version_set.go#L665)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Another consideration here: we shouldn't be doing any disk I/O (which stat might involve) while holding `DB.mu`.

While mildly irritating to plumb, I don't see any particular difficulty in change `obsolete` to be a `[]base.FileMetadata`. Possibly I'm missing something, but I think that is the right thing to do.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-12 21:01 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/981)* status: 6 of 15 files reviewed, 8 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 1171 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu68Km0oEzRM47YLvs:-MLy8NdM1xG6a_qHibQb:b-cax0p6) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/compaction.go#L1171)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The motivation behind that is to be able to react quickly to increases in disk space usage. Let me know if it's too frequent though; I could add some sort of logic that only calls GetFreeSpace if x seconds, or y bytes of file deletions, have passed since the last call.
</blockquote></details>

Unless you or @petermattis have a good mental model of what this does under the covers, and whether it is O(1), it would be good to measure this call on roachprod.


<!-- Sent from Reviewable.io -->

2020-11-12 21:15 UTC, petermattis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/981#-:-MLyIjtA0y8aA8xXEBjm:bnfp4nl)* status: 6 of 15 files reviewed, 7 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[compaction.go, line 1171 at r2](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLu68Km0oEzRM47YLvs:-MLyGlAd2Ra4uV25mZsw:bjvw75l) ([raw file](https://github.com/cockroachdb/pebble/blob/b285ab7bf2adff9d001013abe615e4abe0d25e1f/compaction.go#L1171)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Unless you or @petermattis have a good mental model of what this does under the covers, and whether it is O(1), it would be good to measure this call on roachprod.
</blockquote></details>

My mental model is that `statvfs` (the underlying system call) is O(1) and is powered by data stored in memory. I could very well be mistaken about this. I'm sure I looked at this at one point in the distance past, but my memory could be wrong or it could have changed. I think that all means that it would be good to verify that call is cheap-ish. Worthwhile measuring on `ext4`, `xfs`, and `zfs` and then leaving a comment here with the findings. Or spelunk the Linux kernel code to prove this.
___
*[compaction.go, line 2386 at r3](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLyHT5U7r21mKO9rXsa:-MLyHT5U7r21mKO9rXsb:b6806j6) ([raw file](https://github.com/cockroachdb/pebble/blob/92b2ecb0284f21eeaac373d522f48a1a50183d5b/compaction.go#L2386)):*
> ```Go
> 	var obsoleteOptions []FileNum
> 
> 	d.mu.Unlock()
> ```

I don't think this is necessary as `scanObsoleteFiles` is only called at startup before `Open` returns. The comments above could make this clearer.


<!-- Sent from Reviewable.io -->

2020-11-13 14:17 UTC, sumeerbhola requested changes
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/981)* status: all files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[compaction.go, line 1928 at r3](https://reviewable.io/reviews/cockroachdb/pebble/981#-MM0wPxqBDLpHVwIPInC:-MM0wPxr8XzZTrI0HpbR:b4534d2) ([raw file](https://github.com/cockroachdb/pebble/blob/92b2ecb0284f21eeaac373d522f48a1a50183d5b/compaction.go#L1928)):*
> ```Go
> 		fileNum := d.mu.versions.getNextFileNum()
> 		fileMeta.FileNum = fileNum
> 		pendingOutputs = append(pendingOutputs, fileMeta)
> ```

do we update the size for these after they are written, or since this slice is used when the compaction results in an error, we can't be sure of the size so need to stat?


<!-- Sent from Reviewable.io -->

2020-11-18 21:35 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/981)* status: all files reviewed, 8 unresolved discussions (waiting on @jbowens, @petermattis, and @sumeerbhola)

___
*[compaction.go, line 1928 at r3](https://reviewable.io/reviews/cockroachdb/pebble/981#-MM0wPxqBDLpHVwIPInC:-MMSFeGV25a_8gbyHcdb:b5ozl5f) ([raw file](https://github.com/cockroachdb/pebble/blob/92b2ecb0284f21eeaac373d522f48a1a50183d5b/compaction.go#L1928)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

do we update the size for these after they are written, or since this slice is used when the compaction results in an error, we can't be sure of the size so need to stat?
</blockquote></details>

Yeah, we don't know of the size of the _latest_ output if the compaction finishes in an error. But that should be okay - it just means we won't be pacing deletions of one of the obsolete files from errored-out compactions at all. That seems like a good thing to me.

We do update the fileMeta's size when we finish an output. That's in line 2045.
___
*[compaction.go, line 2386 at r3](https://reviewable.io/reviews/cockroachdb/pebble/981#-MLyHT5U7r21mKO9rXsa:-MMSGC0k2ohghgtf6Aa-:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/92b2ecb0284f21eeaac373d522f48a1a50183d5b/compaction.go#L2386)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I don't think this is necessary as `scanObsoleteFiles` is only called at startup before `Open` returns. The comments above could make this clearer.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-19 02:30 UTC, itsbilal commented
Ran `clearrange/checks=true` on roachprod with an instrumented binary that tracked runtime of `GetFreeSpace`. All invocations on both zfs and ext4 took <= 10 microseconds, regardless of disk volume usage. I'm convinced this is constant time.

2020-11-19 14:03 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/981#-:-MMVoIhE3BY-qixDSZoh:bg7igkv)* status: all files reviewed, 8 unresolved discussions (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[compaction.go, line 1171 at r4](https://reviewable.io/reviews/cockroachdb/pebble/981#-MMVo2E_6mHzjByZZkRE:-MMVo2E_6mHzjByZZkRF:b-9bx3cc) ([raw file](https://github.com/cockroachdb/pebble/blob/6a7637d654b7bf92f8fee6584b6074eaecf7f157/compaction.go#L1171)):*
> ```Go
> func (d *DB) getDeletionPacerInfo() deletionPacerInfo {
> 	var pacerInfo deletionPacerInfo
> 	if space, err := d.opts.FS.GetFreeSpace(d.dirname); err == nil {
> ```


Can you add a code comment here with your measurements.


<!-- Sent from Reviewable.io -->

2020-11-19 15:05 UTC, itsbilal reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/981#-:-MMW1PVK2Wiq4g91ITcn:bz5mair)* status: all files reviewed, 8 unresolved discussions (waiting on @jbowens and @sumeerbhola)

___
*[compaction.go, line 1171 at r4](https://reviewable.io/reviews/cockroachdb/pebble/981#-MMVo2E_6mHzjByZZkRE:-MMW08pb9TAj4jTKCIvf:b-896fix) ([raw file](https://github.com/cockroachdb/pebble/blob/6a7637d654b7bf92f8fee6584b6074eaecf7f157/compaction.go#L1171)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a code comment here with your measurements.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-19 15:38 UTC, merged